### ISSUE TITLE
What SWFs do we use for testing?

### ISSUE THREAD

**Issue by OmarShehata** [ruffle-rs/ruffle#1]
I know this has been tested on that historic dog flash animation on Newgrounds (whose name I forgot so I can't find it), but would it be a good idea to put some of these test files in the repo? They could be a collection of ones that have specific features, some that work, and some that don't yet. That would make it really easy for a new contributor to take on a specific new feature and have a real test case to be working towards.

Or would that bloat the size of the repo? Perhaps we could put a list of links then in the README or wiki? @Herschel what do you think?

I tried it on my oldest favorite animation (https://www.newgrounds.com/portal/view/454086) and got:

```
Fatal error:
Couldn't find any pixel format that matches the criteria.
```

**Comment by larsiusprime** [comment]
May I humbly suggest the "Homestar runner challenge?"

Essentially -- use classic homestar cartoons as an additional test bed. There's a couple of strategic reasons for this that make them useful for testing:

- They're very well known and so being able to pull it off would get attention for the project
- IIRC a large majority of them were done with Flash 5, even well past that version's prime, so "getting homestar working" is probably an easier subproblem then "get any arbitrary swf" working
- There's some light interactivity in many of them that lets you know how you're doing on scripting support
- For bonus points, try to support the [games](http://homestarrunner.com/games.html) as well

One obstacle might be getting permission, but I'm sure the Brothers Chaps would be very interested.  I can reach out if you're interested.

**Comment by stuaxo** [comment]
re: testing, is there value in running test suites from other flash implementations ?

Shumway - based on Javascript
https://github.com/mozilla/shumway/tree/master/test

Lightspark uses flex to build their tests
https://github.com/lightspark/lightspark

**Comment by kmeisthax** [comment]
@larsiusprime That's been my entire test strategy so far - for example, I'm working on PR #120 to support the main menus, and I implemented #205 specifically because the games and toons menus need it.

A surprisingly high amount of Homestar Runner already works, including very recent animations. I'm really glad they still post Flash files.

**Comment by Herschel** [comment]
Closing as we have a fairly robust test suite now.
It is still an open question whether we move away from FLAs toward ASC/third-party generation tools for some/most tests, but our current methods seem to be working well enough for the near future.

**Comment by OmarShehata** [comment]
> current methods seem to be working well enough for the near future.

Thanks for following up here @Herschel ! In case anyone else is looking for this - the current method you're referring to is the test SWF's here right?

https://github.com/ruffle-rs/ruffle/tree/master/swf/tests/swfs

I also found these demo SWF's but the links seem to be broken:

https://github.com/ruffle-rs/ruffle/wiki/Test-SWFs

For example (https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/web-demo/heroes_of_cybertron.swf) gives me an AWS "NoSuchKey" error.

**Comment by Herschel** [comment]
The main Ruffle test suite is here:
https://github.com/ruffle-rs/ruffle/tree/master/core/tests/swfs

with some `swf` specific tests here:
https://github.com/ruffle-rs/ruffle/tree/master/swf/tests/swfs

The way to run these is:
`cargo test --all`
which will run the entire test suite. This involves simulating the SWFs in the core/tests folder in Ruffle and comparing the trace output to the output from the official Flash Player. Whenever we add a feature, we try to add a test SWF to verify the output. I'll go ahead and update the wiki.
