### ISSUE TITLE
Shadez 2: Grey Screen Issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10008]
### Describe the bug

https://www.crazymonkeygames.com/Shadez-2.html
Preloader seems to show up, but then transitions to a grey screen after that.

### Expected behavior

Game should be loading up after the preloader and not get stuck on a grey screen

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
Grey screen issue is gone and I can actually get to the main menu and even into the first tutorial mission, however i'm running into a problem. It all runs fine until I build and place the refinery, the game seems to get stuck and the console log gets spammed alot.

[Uploading www.crazymonkeygames.com-1679113603575.log…]()

**Comment by n0samu** [comment]
Fixed by #10344
