### ISSUE TITLE
Trying to run AS3 game causes "cannot recursively acquire mutex", "recursive use of an object would cause unsafe aliasing", & "unreachable" errors

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#1000]
https://www.crazygames.com/game/mega-miner

**Comment by Herschel** [comment]
Closing in favor of #1368.

**Comment by Lord-McSweeney** [comment]
The SWF (https://web.archive.org/web/20170705082807/https://files.crazygames.com/megaminer.swf) needs some unimplemented XML properties (specifically `settings`) and TLF text support.
