### ISSUE TITLE
iridescent - black screen on start

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#10000]
### Describe the bug

`ERROR ruffle_core::avm2::activation: AVM2 error: Object(ErrorObject(ErrorObject { class: Error, ptr: 0x55ccc4dba170 }))
ERROR ruffle_core::avm2::activation: Error: flash.display.Loader.unload - not yet implemented
ERROR ruffle_core::avm2::activation: AVM2 error: Object(ErrorObject(ErrorObject { class: Error, ptr: 0x55ccc4dba170 }))
ERROR ruffle_core::avm2::activation: Error: flash.display.Loader.unload - not yet implemented
ERROR ruffle_core::avm2::activation: AVM2 error: Object(ErrorObject(ErrorObject { class: Error, ptr: 0x55ccc4dba170 }))
ERROR ruffle_core::avm2::activation: Error: flash.display.Loader.unload - not yet implemented
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "removedFromStage", class: flash.events::Event, ptr: 0x55ccc4db88b0 }) to handler FunctionObject(FunctionObject { ptr: 0x55ccabf3cb70 }) : AvmError(Object(ErrorObject(ErrorObject { class: Error, ptr: 0x55ccc4dba170 })))
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x55ccc4db7f70 }) to handler FunctionObject(FunctionObject { ptr: 0x55ccbfa60000 }) : RustError("Cannot call null or undefined method child of class XML")
0`

### Expected behavior

the game should reach the menu

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[657514_iridescent-v-2-0.swf.zip](https://github.com/ruffle-rs/ruffle/files/10949388/657514_iridescent-v-2-0.swf.zip)

**Comment by Lord-McSweeney** [comment]
Needs `XML.child`.

**Comment by Lord-McSweeney** [comment]
Now needs `XML.nodeKind`: `RustError("Cannot call null or undefined method nodeKind of class XML")`.

**Comment by evilpie** [comment]
This game needs at least:
- XML.nodeKind()
- XML.namespace()
- A Namespace object with uri/prefix/toString
- `XML.hasOwnProperty("@attribute")`

**Comment by evilpie** [comment]
This now reaches in-game. :tada: Sadly after the third room everything starts to lag.
