### ISSUE TITLE
Prequel Adventure: Katia Take Control: Katia falls through floor

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10025]
### Describe the bug

[KatiaTakeControl.zip](https://github.com/ruffle-rs/ruffle/files/10951920/KatiaTakeControl.zip)
As soon as the SWF gets through the preloader intro, Katia instantly proceeds to fall through the floor, making the swf unplayable.

### Expected behavior

Katia shouldn't fall through the floor as soon as the SWF starts.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
Probably because of `BitmapData.hitTest()` not being implemented.

**Comment by Dinnerbone** [comment]
Still broken even with `hitTest`

**Comment by waspennator** [comment]
![Katia Fixed](https://user-images.githubusercontent.com/78768499/225785687-c5c4cd41-72e3-4cc8-b1fa-a676ea4dc80e.png)
