### ISSUE TITLE
Dino run marathon of doom -  animations are not played properly, regression

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#10059]
### Describe the bug

while this game has some issues with the dino colour, this issue is about the recent regression

Ruffle before (2023-03-13)
https://user-images.githubusercontent.com/103858019/225121031-11e62c55-b570-4b0c-b60e-9722e3df0409.mp4

Ruffle now (2023-03-14)

https://user-images.githubusercontent.com/103858019/225121117-ee0a5dcf-b433-436e-9ff6-f147244e5d5f.mp4

as you can see, the dino barely runs anymore, eating small creatures just keeps them on the dino's mouth, etc

### Expected behavior

ruffle should not regress

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[566176_dinoRunMD-working.zip](https://github.com/ruffle-rs/ruffle/files/10973211/566176_dinoRunMD-working.zip)

**Comment by Toad06** [comment]
Thanks for the report.

It seems like the in-game music also stopped working. I ran a bisect and both of these issues appear to be related to 97d6de1a46652b7eddda1c2d753b06a25c0a4a76 (#9928).

@Aaron1011, just to let you know in case you have an idea.

**Comment by n0samu** [comment]
This seems to be fixed now
