### ISSUE TITLE
Error on https://armorgames.com/play/3189/pandemic-ii

### ISSUE THREAD

**Issue by 1uk32** [ruffle-rs/ruffle#10053]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.15.3/src/gles/web.rs:288:60
Error stack:
```
339/U/n.wbg.__wbg_new_15d3966e9981a196@https://agi.armorgames.com/ruffle/core.ruffle.232c98a410606efcc0cf.js:1:47866
core::ops::function::FnOnce::call_once{{vtable.shim}}::h8cd677756bfcdf86@:wasm-function[7876]:0x7d3f51
std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8@:wasm-function[5335]:0x717e4e
core::panicking::panic_fmt::h2a7f454a5f5da218@:wasm-function[7767]:0x7cf4f5
core::result::unwrap_failed::h6072dd9795ba6508@:wasm-function[6065]:0x750839
<T as wgpu::context::DynContext>::surface_configure::he0d771817de42fdf@:wasm-function[6588]:0x770237
wgpu::Surface::configure::h9f92107922b8ab0c@:wasm-function[3075]:0x5f18d4
<ruffle_render_wgpu::target::SwapChainTarget as ruffle_render_wgpu::target::RenderTarget>::resize::h2a26dc5cdfe71a16@:wasm-function[8131]:0x7da4b3
<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::set_viewport_dimensions::h37ee72e769b8f54b@:wasm-function[4345]:0x6becf9
ruffle_core::player::Player::set_viewport_dimensions::h0c0dac4d4a5b2349@:wasm-function[1296]:0x3bc39d
ruffle_web::Ruffle::tick::hafd02a478b8ee1de@:wasm-function[691]:0x23e9b0
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hbc7b77607193b825@:wasm-function[9474]:0x80c95c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8b29205b4bbb53a2@:wasm-function[8378]:0x7dfc93
A@https://agi.armorgames.com/ruffle/core.ruffle.232c98a410606efcc0cf.js:1:2563
f@https://agi.armorgames.com/ruffle/core.ruffle.232c98a410606efcc0cf.js:1:2240

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/3189/pandemic-ii?fp=ng
SWF URL: https://cache.armorgames.com/files/games/pandemic-ii-3189.swf?v=1373587520

# Browser Info
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-13
Channel: nightly
Built: 2023-03-13T00:19:09.191Z
Commit: b527054a1e2317d9e17ed0dfbfc0e9cceaafd760
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 64
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 4964376

**Comment by Sonikkustar** [comment]
Game seems to work fine now. I played through as much as I could (damn you New Zealand) and didn't experience any issues.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/fadcf120-023b-4cb2-a58d-5b51aa13d5cf)

Game is using **nightly-2023-11-13**.
