### ISSUE TITLE
400 Years: Cannot climb hills

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10077]
### Describe the bug

In [400 Years](https://github.com/ruffle-rs/ruffle/files/10210248/610738_400years_v1_1NG.zip) (#8752), the player character should climb the slope. Instead, he walks straight into it.
![ruffle_400years](https://user-images.githubusercontent.com/71368227/225284452-a16d9af1-645f-46e9-b2b8-393106bc245a.gif)

### Expected behavior

You should be able to climb the slope.
![flashplayer_400years](https://user-images.githubusercontent.com/71368227/225284538-72bbdf97-e179-4da4-b272-4025694d2816.gif)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Needs #10076 and some other upcoming PRs.

**Comment by ActionWavele** [comment]
still an issue

**Comment by n0samu** [comment]
`moveAndColide` in the Game class seems to be the relevant function. The game is checking `getPixel` values against specific integer constants to determine what tile the player is interacting with. I guess it's no surprise that it doesn't work in Ruffle :(
