### ISSUE TITLE
BucketBall 2: in-game background changes to black and fades out repeatedly

### ISSUE THREAD

**Issue by grishka** [ruffle-rs/ruffle#10093]
### Describe the bug

Load the swf file, start new game, select 1st level:

https://user-images.githubusercontent.com/1478258/225433986-721099cb-7ff8-4358-998e-a11da7c89b30.mov

The swf: [bucketball_2.swf.zip](https://github.com/ruffle-rs/ruffle/files/10984224/bucketball_2.swf.zip)

### Expected behavior

Nothing flickers in Adobe flash player:

https://user-images.githubusercontent.com/1478258/225434904-ec8e667a-5a2f-4bc0-a30b-0226afb2a728.mov

(this game also relies on bitmap filters quite a lot, but there's already an issue for those and they're coming in the future, hopefully)

### Affected platform

Online demo

### Operating system

macOS 12.6.1

### Browser

Vivaldi 5.7.2921.63 (Stable channel) (arm64) aka Chrome 110.0.5481.195

**Comment by grishka** [comment]
When you click a ball to shoot it, there are black squares around the dots:
![Снимок экрана 2023-03-15 в 23 39 06](https://user-images.githubusercontent.com/1478258/225436522-9f02e614-32f5-4cbb-8048-43b641188b95.png)

**Comment by grishka** [comment]
"Touch the bubbles 3" has the same exact visual artifacts (and was likely made by the same people): 
[touch_the_bubbles_3.swf.zip](https://github.com/ruffle-rs/ruffle/files/10984332/touch_the_bubbles_3.swf.zip)

**Comment by grishka** [comment]
As of today's nightly build, I can no longer reproduce this. I also updated my OS to 13.3 in the meantime, but that shouldn't affect the web demo, right?

**Comment by n0samu** [comment]
This was fixed by #10158.
