### ISSUE TITLE
princess main swf error looks wrong on ruffle

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#10100]
### Describe the bug

Just load and it will fail to find xml and show error.

See picture for what is, and what it should look like.

[DVC_OS.swf.zip](https://github.com/ruffle-rs/ruffle/files/10984738/DVC_OS.swf.zip)
![image](https://user-images.githubusercontent.com/151014/225450675-f56283b5-0c8d-49b4-bbb5-10f684763339.png)

### Expected behavior

See picture for compare

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

**Comment by n0samu** [comment]
The text width issue is probably the same as https://github.com/ruffle-rs/ruffle/issues/9690#issuecomment-1443424363

**Comment by Lord-McSweeney** [comment]
Fixed by #13923.
