### ISSUE TITLE
(AVM2) Accurate slap shot stuck on ZayPlay logo [Regression] in master

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#10114]
### Describe the bug

This game no longer playable after #10066 PR  

[accurateslapshot.zip](https://github.com/ruffle-rs/ruffle/files/10986397/accurateslapshot.zip)

### Expected behavior

Game should run

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Browser

Firefox Nightly 113.0a1

**Comment by Aaron1011** [comment]
This should be fixed in https://github.com/ruffle-rs/ruffle/commit/ba88b52167968353cf5ee19a0834cd6f5373bc87

**Comment by SN902** [comment]
Issue fixed
