### ISSUE TITLE
Zombie Trailer Park - Blue Screen after Loading

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10130]
### Describe the bug

Hey,

this was a muck liked and played game on my site. It throws some error which ends in a blue screen:

https://www.newgrounds.com/portal/view/555446?emulate=flash

### Expected behavior

No blue screen...

### Affected platform

Online demo

### Operating system

All

**Comment by n0samu** [comment]
Seems to be caused by this error:
` ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: TypeError: Type Coercion failed: cannot convert Object(StageObject(StageObject { name: Assets_splash, ptr: 0x19d21109700 })) to flash.display.LoaderInfo.`

**Comment by desertking** [comment]
still blue with all the latest updates...
