### ISSUE TITLE
Burrito Bison: Stuck before title screen

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10143]
### Describe the bug

https://www.newgrounds.com/portal/view/562620?emulate=flash
Tested it out on the web page and tested it on desktop via spoofing the web page to get past the site lock, the results still the same, the game gets stuck on the screen here and nothing shows up in the console logs.

![Burrito Bison Ruffle](https://user-images.githubusercontent.com/78768499/225803419-0e7cbcc5-4662-46ff-bd25-37a1eec55199.png)

### Expected behavior

The game should actually start

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by kuka-alekseevna** [comment]
There is an error, actually.

```
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1010: A term is undefined and has no properties. (accessing field: initCheck)
	at Main/init()
	at Main/frame2()
```

There are two embedded SWFs in binaryData, and they have troubles accessing some of their classes after embedding.

**Comment by Lord-McSweeney** [comment]
Progressed by #12967- the new error is "`TypeError: null is not an Object`"
