### ISSUE TITLE
.: Mechanical Commando :.: Wonky title screen buttons and loading screen softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10140]
### Describe the bug

[www.newgrounds.com-1679021163017.log](https://github.com/ruffle-rs/ruffle/files/10997338/www.newgrounds.com-1679021163017.log)

https://www.newgrounds.com/portal/view/475495?emulate=flash
This game has 2 noticable issues going on with it.

1: The menu button text doesn't seem to be appearing properly, essentially making it much harder to guess what to click on unless you know from muscle memory.

2: As soon as you try to start a level, the game instantly jumps to a loading screen after loading a weirdly broken level (With text that's correctly rendered somehow) and gets stuck there forever.

![Commando Ruffle 1](https://user-images.githubusercontent.com/78768499/225798765-5383dc5e-6fe7-4d23-b09c-4212835c0307.png)
![Commando Ruffle 2](https://user-images.githubusercontent.com/78768499/225798768-14a2ec25-95f2-4c8f-bd8f-6dbcadb720c6.png)
![Commando Ruffle 3](https://user-images.githubusercontent.com/78768499/225798772-b8022a41-a78e-4ec9-9626-d4c65baf9e65.png)

### Expected behavior

The menu buttons should appear normally and the game shouldn't softlock when loading a level (Weirdly enough the third image is also what appears in ruffle when the game softlocks, so I got no idea what ruffle is doing wrong with rendering the text)

![Commando Flash 1](https://user-images.githubusercontent.com/78768499/225799320-ecee8354-ed51-41e8-a1f9-1c776a3b449d.png)
![Commando Flash 2](https://user-images.githubusercontent.com/78768499/225799329-0781faff-064b-4f6a-87d1-e3851724af52.png)
![Commando Flash 3](https://user-images.githubusercontent.com/78768499/225799339-e697570f-f8ea-45a1-ab5b-8633b22d987f.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
I think the important error is this: `Resolved parameter type TheGameAS3.Effects::Acteur_c is unresolvable, not a class, null, or undefined`.

**Comment by waspennator** [comment]
Menu text no longer seems to be an issue, but the softlock when loading a mission still remains.

**Comment by waspennator** [comment]
Softlock is gone, outsight of some slight freezes during loading, game seems to work fine.
