### ISSUE TITLE
GOBTRON: Enemies never spawn

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10145]
### Describe the bug

https://www.newgrounds.com/portal/view/506146?emulate=flash
Game seems to work up until the 1st wave begins, at which point no enemies seem to show up, essentially leaving you softlocked.

[ruffle.rs-1679024069681.log](https://github.com/ruffle-rs/ruffle/files/10997587/ruffle.rs-1679024069681.log)

### Expected behavior

Enemies should be appearing after the 1st wave message appears.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Warning `Display object container has no child with name pupil` shows up, as well as `Attempted to add frame scripts to non-MovieClip this!`.

**Comment by n0samu** [comment]
This seems to be fixed now!
