### ISSUE TITLE
The Peacekeeper: Title Screen buttons and stuck mouse

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10152]
### Describe the bug

https://www.newgrounds.com/portal/view/621239?emulate=flash
The game seems to get past the preloader now, but not only do the menu buttons not display the text properly (Save for the host game button), if you try and start a new game by clicking where the start game button usually is, the target reticle mouse cursor will freeze in place (only visually, you can still move your mouse around) and a bunch of errors start spawning in the log.

[www.newgrounds.com-1679028138500.log](https://github.com/ruffle-rs/ruffle/files/10997921/www.newgrounds.com-1679028138500.log)

![The Peacekeeper Ruffle](https://user-images.githubusercontent.com/78768499/225815068-bfcecbc1-cdaa-4a37-9ed5-64c36ae42bf9.png)

### Expected behavior

The buttons should look normal and trying to start a new game shouldn't stick the cursor in place.

![The Peacekeeper Flash](https://user-images.githubusercontent.com/78768499/225815044-31944a91-b40b-4b5c-835a-596c4c4fa558.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
The title screen buttons with broken text seem to be fixed as of 2023-04-02.

![PC Ruffle](https://user-images.githubusercontent.com/78768499/231329103-173d2589-d975-4b9f-ac0b-e48160ebf938.png)

The mouse however visually still seems to get stuck in place after pressing play with this error (Issue is only visual, while the on screen cursor gets stuck, the actual cursor can still be moved around and I can still click on buttons.)

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x5ec4910 }) to handler FunctionObject(FunctionObject { ptr: 0x8de5708 }) : TypeError: Error # 1009: Cannot access a property or method of a null object reference. (accessing field: soundTransform)

**Comment by waspennator** [comment]
Game seems to work alright now, but the performance could be alot better, unsure whether to keep it open for performance or make a new report for it.

**Comment by Aaron1011** [comment]
Can you make a separate bug report for the performance issues?

**Comment by waspennator** [comment]
Closing for #17491
