### ISSUE TITLE
Knightmare Tower: Stuck before Title Screen

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10150]
### Describe the bug

[www.newgrounds.com-1679026851203.log](https://github.com/ruffle-rs/ruffle/files/10997841/www.newgrounds.com-1679026851203.log)

https://www.newgrounds.com/portal/view/602131?emulate=flash
As soon as you click play, it will go through a screen transition or two, then get stuck on this.

![Knightmare Tower Ruffle](https://user-images.githubusercontent.com/78768499/225811948-4eda1924-5273-42de-9dc1-4317015262af.png)

### Expected behavior

The game should be starting up without issue.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Relevant error: `RustError("VerifyError: Trait isPlaying in class CoreClip has same name as trait isPlaying in class MovieClip, but does not override it")`.

**Comment by Lord-McSweeney** [comment]
This also seems to need `XML.copy`.

**Comment by Lord-McSweeney** [comment]
Should be fixed by #14671
