### ISSUE TITLE
Doodle God: From Ruffle Nightly 2023-02-25 onwards, a brown square is shown instead of the title screen

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#10157]
### Describe the bug

Tested from Ruffle Nightly 2023-02-25 to Ruffle Nightly 2023-03-17
Doodle God SWF used: [doodle-god.zip](https://github.com/ruffle-rs/ruffle/files/10998187/doodle-god.zip)

This is what the game looks like when I run it on Ruffle Nightly 2023-02-25 onwards. I used Ruffle Nightly 2023-02-25 for the example, but the result is the same for future versions.

https://user-images.githubusercontent.com/36887711/225823476-6f63a9a4-efcc-4377-9450-6e5cb837e636.mp4

### Expected behavior

This is what the game looks like when I run it on Ruffle Nightly 2023-02-24.

https://user-images.githubusercontent.com/36887711/225823441-0bb83827-9587-4a84-bd98-e47d4b6189db.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 111

**Comment by Toad06** [comment]
Thanks for the report.

The issue seems to be fixed in the current nightly build (2023-03-21). Could you please give it a try to see if the game also works on your end? Thank you.

**Comment by WyvernB** [comment]
It looks like the issue is fixed in that build.
