### ISSUE TITLE
Flippin' Dead: Double intro logo softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10151]
### Describe the bug

https://www.newgrounds.com/portal/view/605013?emulate=flash
Game plays the juicy beast logo intro twice, then gets stuck on a black screen forever.

[www.newgrounds.com-1679027059589.log](https://github.com/ruffle-rs/ruffle/files/10997857/www.newgrounds.com-1679027059589.log)

### Expected behavior

Game should be starting up after the juicy beast intro

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Yet again `RustError("VerifyError: Trait isPlaying in class CoreClip has same name as trait isPlaying in class MovieClip, but does not override it")`.

**Comment by waspennator** [comment]
The double intro softlock has turned into a single intro softlock testing again.

**Comment by Aaron1011** [comment]
This is working on the latest Ruffle
