### ISSUE TITLE
Zombie Hooker XXX-mas: White Screen Softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10156]
### Describe the bug

https://www.newgrounds.com/portal/view/521563?emulate=flash
I can see the preloader for like half a second, then it vanishes to a white screen and tosses this up in the logs.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x45122d0 }) to handler FunctionObject(FunctionObject { ptr: 0x786db8 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"flash.xml\"))), name: Some(\"XMLDocument\"), params: [], flags: MultinameFlags(0x0) }")

### Expected behavior

It should load normally without doing that

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Will be progressed by #10112 but then needs `XMLDocument.ignoreWhite`.

**Comment by waspennator** [comment]
Game seems to be playable now with #10299 merged in.
