### ISSUE TITLE
Interactive Homestuck flashes run, but flicker insanely and are completely unplayable

### ISSUE THREAD

**Issue by Rult** [ruffle-rs/ruffle#1015]
_epilepsy warning_

SWF: [one](https://www.homestuck.com/flash/hs2/03318/03318.swf), [two](https://www.homestuck.com/flash/hs2/03692/03692.swf).
Expected behaviour: [one](https://www.homestuck.com/story/3321), [two](https://www.homestuck.com/story/3695).

Tested on both web (ruffle.rs demo) and desktop (windows 10).

**Comment by j-james** [comment]
ActionScript 3 is not yet supported by Ruffle, see [the project roadmap.](https://github.com/ruffle-rs/ruffle/wiki/Roadmap) and issue #12 .

**Comment by Rult** [comment]
Thanks for clarification! 

I think there should be a pinned issue for this case (and maybe a guide how to detect the AS version) to prevent issues like #1000

**Comment by Herschel** [comment]
Closing in favor of #1368.
