### ISSUE TITLE
Katawa Crash: Unable to create new profile

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#10154]
### Describe the bug

Tested on Ruffle Nightly 2023-03-17
Katawa Crash SWF used: [katawacrash.zip](https://github.com/ruffle-rs/ruffle/files/10998052/katawacrash.zip)

This is what the game looks like in the Ruffle Demo. You should be able to create a new profile by pressing "Register New" and pressing Enter when it has a name on it. However, this doesn't work on the demo.

https://user-images.githubusercontent.com/36887711/225818818-f28b18cf-fad4-49cd-963f-bd3080758515.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/225818940-38eddea8-d15f-4578-8f63-93945721bae1.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 111

**Comment by n0samu** [comment]
The error is:
`WARN ruffle_core::avm2::amf: Serialization is not implemented for class other than Object: VectorObject(VectorObject { ptr: 0x29fa38bc380 })`

Same issue as #9688.

**Comment by n0samu** [comment]
Fixed by #12240
