### ISSUE TITLE
Rullo: Display issue

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#10164]
### Describe the bug

Tested on Ruffle Nightly 2023-03-17
Rullo SWF used: [rullogame.zip](https://github.com/ruffle-rs/ruffle/files/11001661/rullogame.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/225914658-728ff96e-6002-4a00-bae3-9efc4ceaa9c7.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/225914850-90daa3a5-3562-4faf-839e-2a29901f00ec.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 111

**Comment by n0samu** [comment]
This happens because the game sets `stage.scaleMode = StageScaleMode.NO_SCALE`. We should probably use Ruffle's new `forceScale` option on the demo page to make games like this display as expected.
