### ISSUE TITLE
Bad Piggies: Property Bytes not found on flash.display.Loader and there is no default value

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#10179]
### Describe the bug

Game - https://www.gameflare.com/online-game/bad-piggies/
SWF - https://data.gameflare.com/games/3371/IpvdsF8mGgh7u4.swf

error:
```
ERROR ruffle_core::avm2::activation: AVM2 error: Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0x2811dd76080 }))
ERROR ruffle_core::avm2::activation: ReferenceError: Error #1069: Property Bytes not found on flash.display.Loader and there is no default value.
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2811db5f200 }) to handler FunctionObject(FunctionObject { ptr: 0x2811d7967f0 }) : AvmError(Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0x2811dd76080 })))
```

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
This is because of an error in a String function that causes an operation to return "Bytes" instead of "loadBytes".

**Comment by MartySVK** [comment]
With these PRs, game looks fully playable...great job 🥳

**Comment by Lord-McSweeney** [comment]
Still one minor issue- the "resume" button which can be accessed from the pause menu is in the wrong location, but that's a relatively small issue.
