### ISSUE TITLE
Tilt: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10183]
### Describe the bug

Download SWF file: [tilt_decrypted.zip](https://github.com/ruffle-rs/ruffle/files/11006092/tilt_decrypted.zip)

After the intro splash screens, [Tilt](http://www.notdoppler.com/tilt-b.php) shows only a blank screen.

This error is repeated several times:
```
ERROR ruffle_core::avm2::activation: ReferenceError: Error #1069: Property text not found on String and there is no default value.
        at org.ascollada.core::ColladaElement$/parseStringArray()
        at org.papervision3d.objects.parsers::DAE/parseNode()
        at org.papervision3d.objects.parsers::DAE/parseVisualScene()
        at org.papervision3d.objects.parsers::DAE/parseScene()
        at org.papervision3d.objects.parsers::DAE/parseAfterMaterials()
        at org.papervision3d.objects.parsers::DAE/parse()
        at org.papervision3d.objects.parsers::DAE/load()
        at com.devm.puzzle.level::Level3D/init()
        at com.devm.puzzle::Game/init()
        at com.devm.puzzle::Main/initGame()
```

### Expected behavior

The main menu should load.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Here is the relevant AS function:
```as
public static function parseStringArray(param1:XML) : Array
{
    var _loc2_:String = param1.text().toString();
    _loc2_ = _loc2_.replace(/^\s+/,"");
    _loc2_ = _loc2_.replace(/\s+$/,"");
    return _loc2_.split(/\s+/);
}
```
The error message does not make sense because it implies that Ruffle is trying to get the `text` of a String, even though it should be trying to get the text of an XML.

**Comment by adrian17** [comment]
This could be a bug with https://github.com/ruffle-rs/ruffle/pull/9806

> When an XML object has simple content, you can call non-XML methods directly on it - it will internally be stringified, and the method will be called on the resulting string

This does sound like what's happening here, but not sure why it's not finding our `name()`.

**Comment by adrian17** [comment]
Oh, well this is simply because we don't have `text()` implemented.

I think we should just stub all the methods (even have them throw exceptions instead of no-op), just to prevent the misleading fallback-to-string scenario.

**Comment by evilpie** [comment]
This works now, but there is some text missing in the main menu.
