### ISSUE TITLE
Pac-Man games go to start screen when eating ghosts & after some time passes

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#1018]
https://www.newgrounds.com/portal/view/448783
http://free80sarcade.com/pacman-java.php
It appears that the newgrounds submission is actually based on the game hosted on free80sarcade.com , as the newgrounds submission says they got the `.fla` from neave.com , which is the place that free80sarcade.com got the `.swf` from. Interestingly enough, the newgrounds submission takes a lot longer to crash(they both crash right away when you eat a ghost).

**Comment by Herschel** [comment]
Same `tellTarget` scoping issue as #805

**Comment by Herschel** [comment]
Fixed by #1094.
