### ISSUE TITLE
Insulin Dog banner running forever (dog does not sit)

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#10188]
### Describe the bug

In picture, 2 banners is shown, one in ruffle and one in flash. As you can see, dog is correctly sitting when mouse is outside window. Ruffle does not do this so dog keeps running forever.

To repeat this:
In zip there is 3 files, run insulin_banner.swf, and wait for info block to go away, then mouse in and out of banner window. In Flash, dog sits after a second of mouse not inside window area. All 3 files is required as it wont function properly otherwise.

![image](https://user-images.githubusercontent.com/151014/226070340-a8d1de3e-4971-417f-bcab-b621c0c9ec07.png)

zip
[dogbanner.zip](https://github.com/ruffle-rs/ruffle/files/11006994/dogbanner.zip)

### Expected behavior

Doggy sits when mouse is outside window.

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

**Comment by SN902** [comment]
dog is correctly sitting when mouse on info button in left corner of the screen, pretty sure it's input issue

**Comment by n0samu** [comment]
Same problem as #3144

**Comment by Lord-McSweeney** [comment]
Issue still occurring (at least on desktop).

**Comment by Lord-McSweeney** [comment]
Fixed by #10622.
