### ISSUE TITLE
Snakes on a Cartesian Plane: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10195]
### Describe the bug

Download SWF: [snakesonacartesianplane_decrypted.zip](https://github.com/ruffle-rs/ruffle/files/11007192/snakesonacartesianplane_decrypted.zip)

Pressing the spacebar to start the game in [Snakes on a Cartesian Plane](http://www.notdoppler.com/snakesonacartesianplane.php) shows only a blank screen. A `Modifying an XML object is not yet implemented` error appears first, but it doesn't seem to stop the game from working. Instead, this repeated error does:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: finished)
        at MenuState/update()
        at org.flixel::FlxGame/update()
        at org.flixel::FlxGame/step()
        at org.flixel::FlxGame/onEnterFrame()
```

### Expected behavior

The game should start.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Tested with #10186.

**Comment by n0samu** [comment]
With some upcoming PRs, the `Modifying an XML object is not yet implemented` error is replaced with a new error:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x20d7bb3b9c0 }) to handler FunctionObject(FunctionObject { ptr: 0x20d75d68f40 }) : ReferenceError: Error #1037: Cannot assign to a method name on XML.
        at MenuButton()
        at MenuState/create()
        at org.flixel::FlxGame/switchState()
        at org.flixel::FlxGame/step()
        at org.flixel::FlxGame/onEnterFrame()
```
Other than that, nothing has changed.

**Comment by n0samu** [comment]
With #10892, the game makes it to the mode selection screen, but nothing is clickable. The new error is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x245b7c9f748 }) to handler FunctionObject(FunctionObject { ptr: 0x245a33fdef8 }) : RustError("Modifying an XMLList object is not yet implemented: target XmlObject(XmlObject { ptr: 0x245b7c3b378 })")`

**Comment by evilpie** [comment]
After  #11128 we get the failure `TypeError: Error #1010: A term is undefined and has no properties. (accessing field: stats)`.

To me this looks a bit like it might be  timing problem with loading swfs?
- Main::onStage calls `this.getKong` and `load`.
- `getKong` uses a Loader to load a remote SWF
- `load` calls `unlock`, which accesses `kongregate.stats`. `kongregate` at this point is still undefined.
- At some point after the event listener `kongComplete` (from the loader) is called and `kongregate` is presumably set

**Comment by n0samu** [comment]
The error you mentioned seems to only happen when unlocking a new game mode. That happens when you reopen the game on a different day from when you last played:
```as
            if(save.data.day != null)
            {
                if(save.data.day != _loc1_.getDate())
                {
                    if(Main.isLocked("foresight"))
                    {
                        Main.unlock("foresight");
                    }
                }
            }
```
If you delete Ruffle's save file for the game, the error disappears but all of the buttons on the level select menu are still unclickable. Here is the error I get then:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2630cc1ab98 }) to handler FunctionObject(FunctionObject { ptr: 0x2630c944fd8 }) : RustError("Cannot set an XML/XMLList object Object(XmlListObject(XmlListObject { ptr: 0x2630cc1dce8 })) as an element yet")
```

Implementing that feature might progress the game at least when no save data is present.

**Comment by n0samu** [comment]
Not sure exactly when or why, but this game is working fine now! 🎉
