### ISSUE TITLE
Track the Ball: Cannot play first level

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10193]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/tracktheball.swf

The first level of [Track the Ball](http://www.notdoppler.com/tracktheball.php) appears blank and is not playable. The error is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x21b451a3c80 }) to handler FunctionObject(FunctionObject { ptr: 0x21b33ea5f30 }) : RustError("Cannot call null or undefined method text of class XMLList")`

### Expected behavior

The level should be playable.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

#10186 implements XML.text but XMLList.text still needs to be implemented.

**Comment by evilpie** [comment]
This game also needs XML.parent when clicking on the retry button.
