### ISSUE TITLE
Great work! Anything I can do to help out?

### ISSUE THREAD

**Issue by JasonHuang3D** [ruffle-rs/ruffle#102]
3 years ago I started a project named AJC, that re-compile AS3 source codes to JS and interacting with my handed written flash api (wasm that written in c++), to achieve similar goals as Ruffle dose today. 17 months ago, bad things happened to me, so the project has been suspended. During the AJC development, we completed almost 80% of flash apis those are 95% accurate as original flash player provides, regardless so many differences that DOM provides. Here is a very beginning test repo that forked by someone else : https://github.com/shanewfx/AJC-Flash-WebAssembly-Examples.

Thanks for your hard workings, If there is anything I could do to help out, please let me know.

**Comment by Herschel** [comment]
Hi Jason,

When we start implementing the AVM2, I'm sure we could use your help. I might have some questions and (with your permission) look at your code as reference. Currently we are starting from the ground up, working on AVM1 support.

Thank you for the kind words and linking to your cool project!
