### ISSUE TITLE
Add workaround to kill getTimer busy loops

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1020]
Once upon a time, many games used this trick:
```
var time = getTimer();
while( getTimer() - time <= 1000 / framerate ) { }
```
By setting the SWF to a higher FPS and using a busy loop to stall to the target framerate, the Flash plugin would sometimes run your game at a more consistent framerate (at the cost of melting your CPU).

This kills performance in Ruffle, (e.g. on web, where this is tied to the browser event loop and blocks the browser's UI) and is generally unnecessary, so we should have some workaround to kill this code, possibly by forcing a specific framerate, and returning dummy values for getTimer. We may also be able to auto-detect this in some way (match a bytecode pattern?)

Madness Accelerant (https://www.newgrounds.com/portal/view/512407) is an example that uses this.

**Comment by Dinnerbone** [comment]
One way we could do this is to count how many times `getTimer()` is called in a frame, and if it's more than say 5 - add some arbitrary amount to it every additional call. Keep track of how much we've pretended to go forwards, and then at the end of the frame let's sleep for that much time and reset our fake value to the real value.

**Comment by Herschel** [comment]
I like that solution! That avoids us having to try to detect what the target framerate is in some complicated way. 

The copy of Fancy Pants 1 on NG (https://www.newgrounds.com/portal/view/301341) is another example of this.

**Comment by adrian17** [comment]
> Madness Accelerant (https://www.newgrounds.com/portal/view/512407) is an example that uses this.

I don't see it there. There is a function `fpsLimiter()`, but it appears to be a noop.
