### ISSUE TITLE
Gravity Master: Flickering menu buttons

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10208]
### Describe the bug

[1_gravity-master.zip](https://github.com/ruffle-rs/ruffle/files/11007660/1_gravity-master.zip)
Game seems to work but the buttons have a major issue, they keep on flickering a bunch, making it hard to click on em. Just load up the SWF and you'll see it right away.

### Expected behavior

The buttons should be looking normal and not flickering a bunch.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by n0samu** [comment]
Fixed by #10734
