### ISSUE TITLE
Bababadalgharaghtakamm...: Stuck on preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10207]
### Describe the bug

https://www.newgrounds.com/portal/view/539658?emulate=flash
Game gets stuck on preloader with this message in the log

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xc9c348 }) to handler FunctionObject(FunctionObject { ptr: 0x8f08c0 }) : RustError("VerifyError: Trait z in class dwgraphicsclass has same name as trait z in class DisplayObject, but does not override it")

### Expected behavior

Game should be able to load to the title screen

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
Similar errors also seem to occur on

https://www.newgrounds.com/portal/view/524602?emulate=flash
https://www.newgrounds.com/portal/view/515365?emulate=flash
https://www.newgrounds.com/portal/view/506452?emulate=flash
https://www.newgrounds.com/portal/view/506247?emulate=flash
https://www.newgrounds.com/portal/view/505708?emulate=flash (NSFW)
https://www.newgrounds.com/portal/view/501616?emulate=flash
https://www.newgrounds.com/portal/view/497449?emulate=flash

**Comment by Lord-McSweeney** [comment]
I think this occurs because playerglobal versioning is not yet implemented.

**Comment by Lord-McSweeney** [comment]
Fixed by #12967.
