### ISSUE TITLE
Naya's Quest: Glitchy text and performance issues

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10205]
### Describe the bug

https://www.newgrounds.com/portal/view/625766?emulate=flash
Game seems to work, but the text is hard to read out and the performance is pretty bad unless you run it on desktop, but it's still bad there.

[www.newgrounds.com-1679117972351.log](https://github.com/ruffle-rs/ruffle/files/11007593/www.newgrounds.com-1679117972351.log)

![Naya Ruffle 1](https://user-images.githubusercontent.com/78768499/226087469-ce902637-0cd6-445c-ac41-2f7a3f70cf6f.png)
![Naya Ruffle 2](https://user-images.githubusercontent.com/78768499/226087470-a92d4bb9-7157-43af-9619-60a7c04adaee.png)

### Expected behavior

The performance should be stable and the text should look like this.

![Naya Flash 1](https://user-images.githubusercontent.com/78768499/226087483-b6595dd5-5edf-438d-9e5d-19dee414cc82.png)
![Naya Flash 2](https://user-images.githubusercontent.com/78768499/226087484-e7f4b89f-35c6-4717-80a6-2c0d11fea7e5.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
![Naya Ruffle 1](https://user-images.githubusercontent.com/78768499/226230534-7d57595f-3276-46fd-92c9-48d98ab24ee4.png)
![Naya Ruffle 2](https://user-images.githubusercontent.com/78768499/226230537-ead557ff-1c42-4bfa-810e-26246596abc1.png)
Performance is still iffy, but the visuals have started to improve more as of the latest nightly.

**Comment by waspennator** [comment]
Tested it out again on the latest nightly on web and alongside the iffy performance, i'm seeing this now in the console logs.

Error dispatching event EventObject(EventObject { type: "timer", class: flash.events::TimerEvent, ptr: 0x1d86a18 }) to handler FunctionObject(FunctionObject { ptr: 0x8c098f8 }) : ReferenceError: Error # 1069: Property merge not found on flash.display.BitmapData and there is no default value.

**Comment by waspennator** [comment]
Apparently retesting and looking through the logs, I think this game also needs BitmapData.merge.

**Comment by SuchAFuriousDeath** [comment]
Just FYI, BitmapData.merge is implemented as of #12593.
