### ISSUE TITLE
Text New Line is not corrected respected.

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#1021]
http://filesharing24.com/d/EL0
24 Hours only then auto delete.

Click "Upcoming"->Click on "Game Development" or anything actually.

In the Actual Flash player, the description is in multiple lines, in Ruffles, it is one long continuous line.

**Comment by Herschel** [comment]
Unfortunately the download link has already expired. Please attach SWFs directly to GitHub issues by putting them in a ZIP file and drag them onto the issue textbox. Thank you!

**Comment by BracerJack** [comment]
[Bug.zip](https://github.com/ruffle-rs/ruffle/files/5105930/Bug.zip)

**Comment by Herschel** [comment]
Our text field HTML parsing is incorrectly case-sensitive, causing the HTML in these text field to not be parsed correctly (particularly `<P>`.)

**Comment by BracerJack** [comment]
That's wonderful to know, and incrementally, ruffles gets better and better thanks to you !
