### ISSUE TITLE
Homebrew command for mac: brew install --HEAD ruffle-rs/ruffle/ruffle not working on macOS monterery 12.5.1 M2 chip

### ISSUE THREAD

**Issue by Sunlord330** [ruffle-rs/ruffle#10213]
### Describe the bug

Homebrew command brew install --HEAD ruffle-rs/ruffle/ruffle doesn't work on my M2 macOS Monetery 12.5.1 

error codes are:
error: failed to run custom build command for `ruffle_core v0.1.0 (/private/tmp/ruffle-20230318-19857-1fwt85i/core)`

Caused by:
  process didn't exit successfully: `/private/tmp/ruffle-20230318-19857-1fwt85i/target/debug/build/ruffle_core-626ddd97922b4e6b/build-script-build` (exit status: 101)
  --- stderr
  The operation couldn’t be completed. Unable to locate a Java Runtime.
  Please visit http://www.java.com for information on installing Java.

  thread 'main' panicked at 'Failed to build playerglobal: "Compiling failed with code ExitStatus(unix_wait_status(256))"', core/build.rs:7:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):

### Expected behavior

I wanted to install it 

### Affected platform

Desktop app

### Operating system

macOS Monterey M2 chip 12.5.1 system update

**Comment by n0samu** [comment]
As the error message states, installing Ruffle with Homebrew requires the Java runtime to be installed. This is because Homebrew compiles Ruffle from source. I'd recommend downloading Ruffle via our website instead: https://ruffle.rs/#downloads

**Comment by unitof** [comment]
@Sunlord330 Was able to replicate once I uninstalled `java` from my own machine! Fixed by adding an `openjdk` build dep for the Homebrew tap. Go ahead and try `brew install ruffle-rs/ruffle/ruffle --head` again?

**Comment by unitof** [comment]
@n0samu You can go ahead and close this, fixed in ruffle-rs/homebrew-ruffle.

**Comment by n0samu** [comment]
Thank you!
