### ISSUE TITLE
Error on https://archive.org/details/worlds-hardest-game-4

### ISSUE THREAD

**Issue by nommonbomb** [ruffle-rs/ruffle#10214]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false
(Cached) null

# Page Info
Page URL: https://archive.org/details/worlds-hardest-game-4

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15329.44.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-17
Channel: nightly
Built: 2023-03-17T00:21:29.148Z
Commit: 32f8330199d6c244e41d15fcbb9a9d028fc83af8
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Hello @nommonbomb, please follow the instructions in our FAQ to fix this problem: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#internetarchive
