### ISSUE TITLE
Sheepy: The small Textfield flashes and displays incorrectly.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#10239]
### Describe the bug

[sheepy.zip](https://github.com/ruffle-rs/ruffle/files/11010100/sheepy.zip)

![sheepy](https://user-images.githubusercontent.com/75052171/226150826-8f58c0bc-5236-4f04-8f82-5014b4eba5e7.gif)

When you start the game in **"Sheepy"**(AVM2), a large Textfield appears. However, as shown in the gif above, smaller Textfields jiggle and flicker across the screen. These smaller Textfields are not visible on the actual screen.

![image](https://user-images.githubusercontent.com/75052171/226150867-706a9f44-e822-468c-a850-0cf5cca0dbd9.png)

(However, if you type text in a large Textfield and press Enter, the game will proceed normally).

The same thing happens with Textfields that appear during the game.

![image](https://user-images.githubusercontent.com/75052171/226150885-f26ab7b8-2cc9-4cd2-ad67-447678091957.png)

Confirmed in 2023-03-19 Nightly.

### Expected behavior

The small Textfield should not be visible.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 111

**Comment by Lord-McSweeney** [comment]
This issue has been appearing with the Papa Louie's games, though those are AVM2.

**Comment by Herschel** [comment]
This game is actually AVM2 as well. The issue appears to be in the standard Flash `fl.controls.TextInput` component.

**Comment by Jmousy** [comment]
Oops, my bad. I mistakenly thought this was an AVM1, and @Herschel is right.

**Comment by n0samu** [comment]
This is also a massive problem in [Incredibots](https://incredibots.com/if/game.php?v=ib1):

https://user-images.githubusercontent.com/71368227/229373279-ccc79b55-4114-4d64-82f3-ef979c14fec1.mp4

**Comment by Lord-McSweeney** [comment]
(This is not a text-related issue.)

**Comment by n0samu** [comment]
Fixed by #10734
