### ISSUE TITLE
Spike's Day Out: Hot Dog softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10235]
### Describe the bug

[674596_dayout-infra.zip](https://github.com/ruffle-rs/ruffle/files/11009954/674596_dayout-infra.zip)
Game seems to work fine up until you try to take the hot dog from this cart (which you need to be wearing the hat by pressing X, before pressing space to take it), on ruffle the animation plays, but the text box never goes away and you are essentially stuck, capable of moving around, but softlocked on this street.

![Spikes Day Out Ruffle](https://user-images.githubusercontent.com/78768499/226147833-8a29ae52-b2cc-4446-aa6a-7d24e1608c39.png)

### Expected behavior

Picking up the hot dog shouldn't softlock you to this street and the text box should vanish once you move after you get the hot dog.
![Spikes Day Out Flash](https://user-images.githubusercontent.com/78768499/226147840-9da55660-f7fc-4ff6-9976-4cf3c980852e.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Herschel** [comment]
The player's animation when picking up the hotdog is a movieclip named `bitt`. Most of the game pauses while `bitt != null`. Moving left or right changes to the walking animation and should clear `bitt`, but this doesn't happen in Ruffle's case, causing the soft lock. Seems like a timeline issue where instance names aren't cleaned up.

**Comment by Lord-McSweeney** [comment]
#5431 might fix this.

**Comment by waspennator** [comment]
Actually I retried it out as of the latest nightly, seems like it just fixed itself somehow.
