### ISSUE TITLE
Puzzling War: Stuck on Preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10241]
### Describe the bug

https://www.newgrounds.com/portal/view/554329?emulate=flash
Game gets stuck on a black screen trying to load the gamezhero preloader.

Got RustError("Cannot call null or undefined method updatePosition of class com.gamezhero.api.as3::GamePreloader") when constructing AVM2 side of movie clip of type com.tempalabs.puzzlingwar::Preloader

### Expected behavior

Preloader should show up and I should be able to play the game.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Herschel** [comment]
Only investigated briefly, but the preloader skin gets loaded via `Loader` and on Event.INIT 1) the `Loader.content` gets immediately reparented and 2) the `updatePosition` function is grabbed from the loaded content. So we haven't initialized enough of the content for the `updatePosition` to exist, and/or the reparenting of the content is screwing it up.

**Comment by waspennator** [comment]
Tested it out again, game seems to work with the latest nightly and can actually get into gameplay, however i'm noticing an issue with the preloader now. For some reason the ding noise that plays when the preloader finishes loading keeps constantly going off and the Gamezhero logo keeps repeating on loop. On desktop it's tolerable, but on the web version, the special NG Gamezhero logo keeps sounding off every 2 seconds, even into gameplay.

"Attempted to add frame scripts to non-MovieClip this!"

"Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x12b80f0 }) to handler FunctionObject(FunctionObject { ptr: 0x63150c8 }) : RustError("ArgumentError: Child not a valid display object")"

**Comment by waspennator** [comment]
Retested again and the preloader audio issue seems to have gone away now.
