### ISSUE TITLE
Ruffle scanner fails compilation

### ISSUE THREAD

**Issue by tsunamistate** [ruffle-rs/ruffle#10255]
### Describe the bug

Prerequisites:

* User has cloned ruffle and opened a shell in project root
* User has installed rust and Java, and they are in PATH, as per dependency requirements

Steps to reproduce:

1. Run command to compile ruffle scanner: `cargo run --release --package=ruffle_scanner -- scan {path to swf folder} {path to CSV to be generated}`

Actual behaviour:

Compilation fails on `ruffle_render` crate with the following error message:

```
error[E0433]: failed to resolve: use of undeclared crate or module `lyon`
 --> render\src\shape_utils.rs:5:9
  |
5 | pub use lyon::path::FillRule;
  |         ^^^^ use of undeclared crate or module `lyon`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `ruffle_render` due to previous error
```

### Expected behavior

Ruffle scanner compiles without errors and generates CSV file with report of compatibility for SWF files contained in the folder

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by relrelb** [comment]
Fixed by #10277.
