### ISSUE TITLE
Adventure Ponies: Boss Names set to Null?

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10268]
### Describe the bug

[adventure-ponies.zip](https://github.com/ruffle-rs/ruffle/files/11012889/adventure-ponies.zip)
Game seems to be playable now, but there seems to be an issue i've noticed during gameplay, during the boss fights, their names show up as null instead of their actual names. (Dragon, Hydra, Iron Will, etc) This also shows up during the end level screens where their names show up as null too.

Notice the name of the boss on the top right
![Adventure Ponies Ruffle 1](https://user-images.githubusercontent.com/78768499/226225557-36638ce7-77c2-455e-8301-9a9ac781ff66.png)

### Expected behavior

The bosses should have their proper names set on the top right.

![Adventure Ponies Flash](https://user-images.githubusercontent.com/78768499/226225679-0b95c0a7-6d25-4f9a-9444-49089b570756.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by evilpie** [comment]
Seems to work perfectly with #10369 and #10299.

**Comment by waspennator** [comment]
![Adventure Ponies Ruffle 2](https://user-images.githubusercontent.com/78768499/229258878-8b926486-1342-47d1-bca4-213022fa0f86.png)
Can confirm boss names seem to show up now.
