### ISSUE TITLE
WolfPuncher 2: Wolfsplosion loud loop

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10272]
### Describe the bug

[wolfpuncher2_release_by_extradan-d5n4rbp.zip](https://github.com/ruffle-rs/ruffle/files/11013216/wolfpuncher2_release_by_extradan-d5n4rbp.zip)
(Content warning for a game about punching a cartoon wolf) 
Game seems to work alright up until you get a game over by not punching the wolf for enough time. At which point the explosion effects appear on the wolf and the wolfsplosion text on the bottom right show up, but the wolf never goes through the wolfsplosion animation and the sound just loops loudly as hell. Easiest way to see it is to start the game up and don't punch the wolf, it'll happen in 2-3 seconds.

Tried running it through the ruffle website and only saw this pop up in the logs, dunno if this is what's causing it or not.

Encountered stub: AVM2 flash.media.Sound constructor with arguments

### Expected behavior

The Wolf should go red while exploding, going through it's wolfsplosion animation, then the game should transition over to the game over scene.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by waspennator** [comment]
Still an issue as of the latest nightly.

**Comment by waspennator** [comment]
Ran it through a decompiler and tried to figure out the problem code causing the issue, checked for the first frame where the game over sequence begin and I think it starts around here checking in the script. Providing log files.

[Wolfpunch maintimeline source.txt](https://github.com/ruffle-rs/ruffle/files/11537607/Wolfpunch.maintimeline.source.txt)
[Wolfpunch p-code source.txt](https://github.com/ruffle-rs/ruffle/files/11537608/Wolfpunch.p-code.source.txt)

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
