### ISSUE TITLE
Give Up 2: Stuck on preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10285]
### Describe the bug

[GiveUp2_Viral.zip](https://github.com/ruffle-rs/ruffle/files/11022043/GiveUp2_Viral.zip)
Game gets stuck on a preloader with a blank play button, clicking on it seems to do nothing except lead to a black screen.

[ruffle.rs-1679338459813.log](https://github.com/ruffle-rs/ruffle/files/11022047/ruffle.rs-1679338459813.log)

![Give Up 2 Ruffle](https://user-images.githubusercontent.com/78768499/226439286-470b9362-6bca-41a3-9192-38363e0f462f.png)

### Expected behavior

![Give Up 2 Flash](https://user-images.githubusercontent.com/78768499/226439315-49b0340c-def8-40cd-9922-2d181acb3e66.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
SWF now seems to go through the armor games and massive monster/tasselfoot logos, but these seem to be the remaining issues with the game now.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x5162e90 }) to handler FunctionObject(FunctionObject { ptr: 0x24fba28 }) : RustError("Bitmap size is not valid")

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x8f5678 }) to handler FunctionObject(FunctionObject { ptr: 0x1281028 }) : TypeError: Error # 1009: Cannot access a property or method of a null object reference. (accessing field: y)

**Comment by waspennator** [comment]
Retested again after #10577 was merged in and it seems to be playable now, but the preloader button is still not correct visually and the game slows down alot once starting a run.

I have a feeling the (accessing field: y) error is what's causing the preloader button issues visually, least thats my guess.

**Comment by Sonikkustar** [comment]
The preloader screen appears to work now:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/27d71cdf-775e-4316-8032-2f86057ef6ee)

The slowdown is still present, though what's strange is that it seems to disappear at certain points like when the bombs are dropped in Stage 6.

Tested on **ruffle-nightly-2023_12_19-windows-x86_64**
