### ISSUE TITLE
Super D - loading screen and logo repeats

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#10296]
### Describe the bug

The loading screen and the logo keep repeating in an endless loop. Hope this can be somehow addressed

http://www.freeworldgroup.com/games8/gameindex/superd.htm

### Expected behavior

Should go to main menu and game plays as normal!

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

### Additional information

It's a great game, hope it gets sorted one day!

**Comment by Lord-McSweeney** [comment]
I think this is happening because the main file (http://www.freeworldgroup.com/superd/superd1mochi.swf) returns 404.

**Comment by freeworldgroup** [comment]
the whole game is present in the .swf - nothing is missing. Perhaps the 404 relates to the mochi ad, but that shouldn't affect loading to the main menu screen. 

> I think this is happening because the main file (http://www.freeworldgroup.com/superd/superd1mochi.swf) returns 404.

**Comment by freeworldgroup** [comment]
works fine now
