### ISSUE TITLE
Ruffle extension causes cloudflare verification loop

### ISSUE THREAD

**Issue by kotenok2000** [ruffle-rs/ruffle#10300]
Ruffle extension 0.1.0 nightly 2023-03-21 causes cloudflare verification loop

**Comment by Dinnerbone** [comment]
May I ask which browser you're using? Do you have any other extensions along side ruffle that might be contributing to it?

**Comment by kotenok2000** [comment]
I also have 
https://chrome.google.com/webstore/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci
https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae
https://chrome.google.com/webstore/detail/showpassword/bbiclfnbhommljbjcoelobnnnibemabl
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
https://chrome.google.com/webstore/detail/ultrawideo/bfbnagnphiehemkdgmmficmjfddgfhpl
https://chrome.google.com/webstore/detail/yatm-yet-another-tab-mana/cleopomnamfenlfpglofnooemoakdgef
https://chrome.google.com/webstore/detail/%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA-%D1%80%D1%83%D0%BD%D0%B5%D1%82%D0%B0/npgcnondjocldhldegnakemclmfkngch

**Comment by n0samu** [comment]
Same issue as #10037

**Comment by kotenok2000** [comment]
Closing as duplicate
