### ISSUE TITLE
The Last Dalek: Floor fails to load

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10305]
### Describe the bug

http://downloads.bbc.co.uk/tv/isite-flash/doctorwho/games/lastdalek/isometrics.swf (Playable if you have the ruffle extension, otherwise yank it from flashpoint)
The game seems to work up until you start the level, at which point it loads into a room with missing assets like the floor, the hazmat suit characters walking around, and the music and sound effects.

![The Last Dalek Ruffle](https://user-images.githubusercontent.com/78768499/226740220-5abe3063-a025-470c-b00f-b0a9dea3f535.png)
[donbcfbmhbcapadipfkeojnmajbakjdc-1679432142501.log](https://github.com/ruffle-rs/ruffle/files/11033612/donbcfbmhbcapadipfkeojnmajbakjdc-1679432142501.log)

### Expected behavior

![The Last Dalek Flash](https://user-images.githubusercontent.com/78768499/226740271-19135dfa-c582-4f6a-a66b-a2e92cdb8eb0.png)
The game should be fully initializing like this.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
Still occuring on latest nightly, either it's not rendering the assets cause checking the log, it can't "instantiate" non registered character ID's or it's something else i'm unsure of.

**Comment by Lord-McSweeney** [comment]
This needs `ImportAssets`

**Comment by TDGalea** [comment]
I have this game hosted [on my website](https://tdgalea.co.uk/o/Games/DoctorWho/TheLastDalek.html) with Ruffle embedded.
For me, the game doesn't even get past the first loading screen.
I'd be happy to help in any way I can (testing on-site, etc.) seeing the pull request from 22/05 as a start of hopefully getting this fixed.

**Comment by waspennator** [comment]
Issue seems to be fixed up on my end and seems to play reasonably fine.

@TDGalea 
I tried running the game through your website and I think the problem is that the game is multiasset, seems like it's not properly retriving the assets for the game correctly.
[tdgalea.co.uk-1721454668639.log](https://github.com/user-attachments/files/16318981/tdgalea.co.uk-1721454668639.log)

**Comment by waspennator** [comment]
Closing for now since the original issue of the floor not loading has been fixed though.
