### ISSUE TITLE
In Bloons TD 5, you can't put a monkey on the ground

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#10319]
### Describe the bug

In the first level of Bloons TD 5, you can't put a monkey on the ground. It worked before https://github.com/ruffle-rs/ruffle/commit/078672782ccac2eb38c23e739fc820e32e8bd052

![image](https://user-images.githubusercontent.com/10010569/226994554-faf84556-c6cb-4a88-be1c-cfe766eb1b58.png)

Online Game - https://www.gameflare.com/online-game/bloons-tower-defense-5/
SWF - https://data.gameflare.com/games/3550/WDzRSvadTXBNOR.swf

### Expected behavior

Put a monkey on the ground

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Dinnerbone** [comment]
Fixed by #10315, specifically c85910b46d66dd621e0566c220690c952fd677e3

**Comment by n0samu** [comment]
Seems like this unfortunately has regressed again :(

**Comment by n0samu** [comment]
For convenience, here is the de-mochicrypted SWF: [btd5_decrypted.zip](https://github.com/ruffle-rs/ruffle/files/11381859/btd5_decrypted.zip)

The `isWithin` function in `levels.terrain.TerrainType` returns false in Ruffle but true in Flash Player:
```as
	public function isWithin(param1:MovieClip) : Boolean
	{
		var _loc2_:Rectangle = new Rectangle(0,0,this.resultData.width,this.resultData.height);
		this.resultData.fillRect(_loc2_,0);
		var _loc3_:Matrix = new Matrix();
		_loc3_.translate(param1.x,param1.y);
		_loc3_.scale(this.xScale,this.yScale);
		this.resultData.draw(param1,_loc3_);
		var _loc4_:Point = new Point(0,0);
		return !this.inverseTestMap.hitTest(_loc4_,1,this.resultData,_loc4_,1);
	}
```
But I think the problem probably starts in the TerrainType constructor, which draws the `inverseTestMap` that `isWithin` is hitTesting against:
```as
        public function TerrainType(param1:MovieClip)
        {
            super();
            this.testMap = new BitmapData(Math.ceil(PLAY_AREA_WIDTH * STANDARD_PRECISION_SCALE),Math.ceil(PLAY_AREA_HEIGHT * STANDARD_PRECISION_SCALE),true,0);
            this.xScale = this.testMap.width / PLAY_AREA_WIDTH;
            this.yScale = this.testMap.height / PLAY_AREA_HEIGHT;
            var _loc2_:Matrix = new Matrix();
            _loc2_.translate(param1.x,param1.y);
            _loc2_.scale(this.xScale,this.yScale);
            this.testMap.fillRect(new Rectangle(0,0,this.testMap.width,this.testMap.height),16777215);
            this.testMap.draw(param1,_loc2_);
            this.inverseTestMap = new BitmapData(this.testMap.width,this.testMap.height);
            this.inverseTestMap.fillRect(new Rectangle(0,0,this.testMap.width,this.testMap.height),4294967295);
            this.inverseTestMap.draw(new Bitmap(this.testMap),null,null,BlendMode.ERASE);
            this.resultData = new BitmapData(this.testMap.width,this.testMap.height);
        }
```
