### ISSUE TITLE
DefineEditText does not seem to function properly?

### ISSUE THREAD

**Issue by Thestickman391** [ruffle-rs/ruffle#1032]
How it should look:
![image](https://user-images.githubusercontent.com/4157860/90942763-43e5f900-e46b-11ea-9013-129a36c66d6c.png)
How it looks in Ruffle (note that the text is not editable or able to be inputted at all):
![image](https://user-images.githubusercontent.com/4157860/90942774-4e07f780-e46b-11ea-8051-eede1259c753.png)

**Comment by z3ntu** [comment]
Duplicate of #41 ?

**Comment by Herschel** [comment]
Implemented in #1447.
