### ISSUE TITLE
Error on https://archive.org/details/htf-petunias-summer-smoochie_flash

### ISSUE THREAD

**Issue by RafaelSagas** [ruffle-rs/ruffle#10340]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false
(Cached) null

# Page Info
Page URL: https://archive.org/details/htf-petunias-summer-smoochie_flash

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-17
Channel: nightly
Built: 2023-03-17T00:21:29.148Z
Commit: 32f8330199d6c244e41d15fcbb9a9d028fc83af8
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Hello @RafaelSagas, please follow the instructions in our FAQ to fix this problem: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#internetarchive
