### ISSUE TITLE
Split Brain Propsal letters, can't click "Left" or "Right"  to switch those.

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#10343]
### Describe the bug

![image](https://user-images.githubusercontent.com/151014/227452816-a9c9ad2f-b0f2-4ac3-92d2-ad0ff59a00cb.png)

On Adobe, I clicked some of Right and Left to change those. Cursor changes to pointing hand. On Ruffle neither happens, so it cannot be changed so game is unwinnable.

### Expected behavior

I could click Left or Right to correct proposal so funds is sent. 

Run splitBrain_main.swf after extracting. All files is needed.
[splitbrain.zip](https://github.com/ruffle-rs/ruffle/files/11059481/splitbrain.zip)

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

**Comment by n0samu** [comment]
Like #4253, this game uses HTML text with `asfunction` links, which Ruffle does not support yet.
