### ISSUE TITLE
Morphing: Tiled graphics are distorted

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10379]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/morphing.swf

In [Morphing](http://www.notdoppler.com/morphing.php), Ruffle draws some tile graphics in a distorted way. To easily see it, follow these steps:
1. Select the Level Editor on the game's main menu.
2. Hover over the right sidebar and select the green rectangle tool.
![image](https://user-images.githubusercontent.com/71368227/227757426-587705a7-fca1-4b8c-8723-3f46460359d4.png)
3. Draw a long line. This will create a long and distorted-looking shape.
4. Hover over the bar at the bottom and select a different tile pattern.
5. You should be able to observe the same problem with several of the other tile patterns, including the metal one and the green one.

Here is an example result:
![ruffle_morphing_distortion](https://user-images.githubusercontent.com/71368227/227757516-0d6f3a49-e752-402d-b7a1-399d41ab496b.png)

### Expected behavior

Here is the result of drawing the same objects in Flash Player:
![flashplayer_morphing_tiles_expected](https://user-images.githubusercontent.com/71368227/227757545-84fd3f12-1dca-46bc-9bc4-0f23f46a40fe.png)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Fixed by #10630.
