### ISSUE TITLE
Azurefish - strange issue with colllecting

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#10370]
### Describe the bug

when playing Azurefish on Ruffle, (which recently has started to work, thanks!) I was collecting items and testing things out, and did this for several days, clicking new game each time. Normally pressing new game resets all progress and places items back where they were, as you'd expect
today, when doing that yet again, I had collected only a few bananas when i received the achievement for getting all of them (I was shocked to think I had gotten them all so absent mindedly, which I actually had not)  

as it turns out, Ruffle doesn't seem to clear the save file, BUT will reset the items, so collecting a couple here and there, then clicking new game will keep the count, and reset the items, making the achievement 'cheesable'

you can actually get more than the total amount normally possible!

https://user-images.githubusercontent.com/103858019/227743344-2574db4e-02ff-4213-9390-917fea424b28.mp4

if you want to test this yourself, collect the bananas, they are the easiest, and are mostly all nearly the water's surface

### Expected behavior

new game should reset the save, as it does on flash

### Affected platform

Desktop app

### Operating system

Linux Mint

### Additional information

[566907_Final_Azurefish.zip](https://github.com/ruffle-rs/ruffle/files/11070267/566907_Final_Azurefish.zip)

**Comment by n0samu** [comment]
This happens because `SharedObject.clear()` is currently unimplemented.
