### ISSUE TITLE
Music Twister - Error after clicking start

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10372]
### Describe the bug

Hey,

there is some weird error and this game does not load after pressing start - https://www.izzygames.com/music-twister-t5854.html

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "added", class: flash.events::Event, ptr: 0x36f3fa0 }) to handler FunctionObject(FunctionObject { ptr: 0x36f3e00 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: x)

I leave it open for a while to look after but normally I don't let ruffle run on games that don't work as it could take some time for fixing it.

### Expected behavior

To start the game

### Affected platform

Desktop app

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Direct link to the SWF file: https://www.spiele-umsonst.de/azad/downloads/flashgames/musictwister.swf
You don't need to worry about keeping the webpage up or using Ruffle since we can always download/test the SWF directly from its URL.

**Comment by desertking** [comment]
Ahh yeah that makes sense :D

**Comment by Sonikkustar** [comment]
Game seems to load just fine now when pressing start. I was able to finish Stage 1 at the very least.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/286be5d6-d991-406a-a85b-f6a157acfc00)

Site uses **nightly-2023-12-23**.
