### ISSUE TITLE
Crash test launcher - looping intro logo

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#10371]
### Describe the bug

flash:

https://user-images.githubusercontent.com/103858019/227745342-189d2cbb-622c-43c1-b76a-dbaf7ca2b7fc.mp4

Ruffle: 

https://user-images.githubusercontent.com/103858019/227745350-f6686964-8d51-49d5-bfd4-b58cdb441019.mp4

### Expected behavior

the logo should not loop, and the menu should appear

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

also, it seems like there is a small audio delay?
(desktop)

[crashTestaug25MTA2Nw==.zip](https://github.com/ruffle-rs/ruffle/files/11070344/crashTestaug25MTA2Nw.zip)

**Comment by Lord-McSweeney** [comment]
Progressed by #10368, but the sitelock appears now, even on web (`farm.maxgames.com`).

**Comment by ActionWavele** [comment]
I just tried on deskop flash player
no sitelock

**Comment by Kz-92** [comment]
this seems to be fixed on latest, I will make a new issue for the new problem
