### ISSUE TITLE
House of Wolves: right click does not work

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#10389]
### Describe the bug

House of Wolves
- when you select a settler, with a right click you can do some action like the move. But it is not working in Ruffle (no errors). It is working in Flash.

SWF - https://data.gameflare.com/games/4772/W0CfhIUObjkuPk.swf

### Expected behavior

select settler, click with the right mouse button and move

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Possibly related to this error: `Modifying an XML object is not yet implemented`.

**Comment by MartySVK** [comment]
not sure, this error was there before, but it is not anymore

**Comment by Lord-McSweeney** [comment]
In that case, the issue is probably #10288.
