### ISSUE TITLE
Army of Ages: copy is not a function of class XML

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#10390]
### Describe the bug

The game is currently stuck on an error:
``
copy is not a function of class XML
``

SWF - https://data.gameflare.com/games/1884/6tkKc7XgIkdXg8.swf

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by evilpie** [comment]
I've got this working with #10412 and #10413 and some additional namespace related patch.

**Comment by MartySVK** [comment]
The current error is:
``
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x2848db48a20 }) to handler FunctionObject(FunctionObject { ptr: 0x28488a80210 }) : RustError("Can not set non-public name yet")
``

**Comment by MartySVK** [comment]
> #10385 makes it work

nice, game looks playable with this PR
