### ISSUE TITLE
Runes of the Ancient Forest - Black Screen (Weird Error)

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10403]
### Describe the bug

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/runesoftheancientforest.swf
ruffle_web-wasm_extensions.js:677 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2c4cdd0 }) to handler FunctionObject(FunctionObject { ptr: 0x26dc4b8 }) : Error: It looks like custom metadata is being ignored by your compiler. If you're compiling with the Flash IDE you need to open your "Publish Settings" and select "Publish SWC". See: https://github.com/robotlegs/robotlegs-framework/wiki/Common-Problems

### Expected behavior

Load and Run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
Seems like the same underlying issue as #8330.
