### ISSUE TITLE
Provide API to automate frame-accurate interaction with the .swf content

### ISSUE THREAD

**Issue by Semnodime** [ruffle-rs/ruffle#10404]
**Describe the feature**
I like to create a tool which provides means for autmatically searching through games, recovering interaction and plot trees, hidden easter eggs, optimal game-play paths, and so on.

For that it would be useful if I could **interact with ruffle (or more precise, the .swf projected by ruffle) via some sort of API, scripting language, and so on.**

I base my idea on some implementations I have used in the past, which allowed interacting with emulators of various game consoles (like nintedo):
Simply writing python code which get's loaded by the emulator or vice versa (could be as simple as ruffle game.swf --script script.py, or import ruffle in python):
```python
import ruffle

COLOR_BLACK = 0x000000

while True:
    img = ruffle.render_frame() # screenshot of current frame
    if img[0][0][0] != COLOR_BLACK:
        break

ruffle.input_key(ruffle.keys.KEY_DOWN)
ruffle.advance_frame()
ruffle.input_mouse('left_click', 15, 188)
ruffle.advance_frame()
…
```

**Comment by n0samu** [comment]
Several users have found success in using Ruffle with libTAS. Have you considered trying that?

**Comment by Dinnerbone** [comment]
I've considered something for desktop to help automate benchmarks but not to the degree where it's scriptable, just a preset command list. I agree that might be better for a TAS tool

**Comment by Semnodime** [comment]
@n0samu  Thanks for pointing out `libTAS`. I just installed it and try to make it work. If something utterly unsupported occurs which is interesting for `ruffle` itself (instead of merely `libTAS`), I will let you know by reopening this issue.

**Comment by Semnodime** [comment]
@n0samu  Thanks for pointing out `libTAS`. I just installed it and try to make it work. If something utterly unsupported occurs which is interesting for `ruffle` itself (instead of merely `libTAS`), I will let you know by reopening this issue.
