### ISSUE TITLE
Error on https://www.glowmonkey.com/chooseyourweapon4.php

### ISSUE THREAD

**Issue by BE-Code** [ruffle-rs/ruffle#10400]
# Error Info
Error name: Error
Error message: panicked at 'No script object for display object', core/src/avm1/activation.rs:396:18
Error stack:
```
339/getImports/imports.wbg.__wbg_new_15d3966e9981a196@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:2200:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0312d4caddbaee90@:wasm-function[8041]:0x7f70c8
std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8@:wasm-function[5353]:0x72d280
core::panicking::panic_fmt::h2a7f454a5f5da218@:wasm-function[7921]:0x7f23f2
ruffle_core::display_object::edit_text::EditText::try_bind_text_field_variable::h9c5fbbbb126491b9@:wasm-function[3706]:0x68392c
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::post_instantiation::he4a116ef9010da52@:wasm-function[3069]:0x604073
ruffle_core::display_object::movie_clip::MovieClip::instantiate_child::hd244d6ebb7358c42@:wasm-function[768]:0x28fda1
ruffle_core::display_object::movie_clip::MovieClip::place_object::h97ffd21186ba2fdd@:wasm-function[1560]:0x4352bf
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29acd9
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29a484
<ruffle_core::display_object::loader_display::LoaderDisplay as ruffle_core::display_object::TDisplayObject>::enter_frame::he06e52605ff8f9e8@:wasm-function[3074]:0x607a6c
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::enter_frame::h57e3f4ff64f72aa1@:wasm-function[783]:0x29a48e
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::hbd86c15abf8951d3@:wasm-function[1546]:0x43058b
ruffle_web::Ruffle::tick::hd363147e523d3ba1@:wasm-function[691]:0x2465cb
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h36472d83d0669f8c@:wasm-function[9645]:0x8304a6
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h678c9e4dc3beaab6@:wasm-function[8552]:0x802ee1
__wbg_adapter_56@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:282:10
real@moz-extension://a2bea15a-7c53-437e-b057-5ec8346bd108/dist/339.js:259:20

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: games/chooseyourweapon4.swf
Param quality: high
Param wmode: opaque
Param swfversion: 6.0.65.0
Param expressinstall: Scripts/expressInstall.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.glowmonkey.com/chooseyourweapon4.php
SWF URL: https://www.glowmonkey.com/games/chooseyourweapon4.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-19
Channel: nightly
Built: 2023-03-19T00:19:16.337Z
Commit: 5aac938e868e7dab2550d9482f754a6daf314921
Is extension: true

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 2546381

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.
