### ISSUE TITLE
Ancient Planet - Stuck after loader

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10449]
### Describe the bug

https://www.newgrounds.com/portal/view/648700?emulate=flash - This nice tower defense game hangs after the loader. 

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x1996570 }) to handler FunctionObject(FunctionObject { ptr: 0x1996240 }) : ReferenceError: Error #1065: Variable decodeURI is not defined.

### Expected behavior

To show the menu

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
See #10878 for update (panic).
