### ISSUE TITLE
Firefox plugin not compatible with Firefox For Android?

### ISSUE THREAD

**Issue by divinity76** [ruffle-rs/ruffle#10446]
### Describe the bug

Trying to install the Ruffle extension on Firefox Android from https://addons.mozilla.org/en-US/firefox/addon/ruffle_rs/ fails, with a greyed-out "Add to Firefox" button and the message "(!) To find add-ons compatible with Firefox for Android, [click here](https://addons.mozilla.org/en-US/android/)."

However the Ruffle.rs demo page works fine, so Ruffle works, but the extension install page doesn't.

### Expected behavior

Should be possible to install Ruffle on Firefox Android.

### Affected platform

Browser's extension

### Operating system

Android 11

### Browser

Firefox For Android 111.1.0 (Build #2015940019), 7539a6a366+ GV: 111.0.1-20230320155232 AS: 96.4.0 2023-03-20T22:36:55.036201

### Additional information

Tested on phone Ulefone Power Armor 13

**Comment by torokati44** [comment]
AFAIK the extension is marked by us as compatible with Android, but the set of extensions available to install on mobile is hand-picked by Mozilla itself.

**Comment by torokati44** [comment]
It is indeed possible to install it on Firefox Nightly, in debug mode, in a roundabout way:
https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/

And it does work:
![Screenshot_20230329-120240](https://user-images.githubusercontent.com/288816/228500573-5242a21b-dea8-47bf-8fa8-dbd5eb7cadc9.png)

**Comment by divinity76** [comment]
Maybe worthwhile to ask the addons.mozilla.org team about allowing Android installations?

**Comment by n0samu** [comment]
I kind of doubt Mozilla would allow us in particular when so few extensions are available. But hopefully the general situation with add-ons on Android will improve eventually.

**Comment by divinity76** [comment]
> I kind of doubt Mozilla would allow us in particular when so few extensions are available.

You're probably right, but IMO we should at least give them a (second, the first was to mark it as Android-compatible) chance, so at least we can get the story straight, like

>we did reach out to addons.mozilla and they explicitly refused to allow Android installations. Nothing more we can do.

**Comment by Small-Ku** [comment]
https://blog.mozilla.org/addons/2023/09/27/test-firefox-android-extensions-and-help-developers-prepare-for-an-open-mobile-ecosystem-in-december/

And Firefox Nightly seems able to install add-ons through addons.mozilla.org recently.

**Comment by torokati44** [comment]
This will probably change in about two weeks! :partying_face: 
See https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/ and https://github.com/ruffle-rs/ruffle/pull/14233.

**Comment by divinity76** [comment]
This is now fixed! I have no problem installing Ruffle on Firefox Android v120.1.1 😁
