### ISSUE TITLE
Earn To Die 2012 (Part 1) : cannot start game

### ISSUE THREAD

**Issue by Mickmick2012** [ruffle-rs/ruffle#10447]
### Describe the bug

When starting the game (either chosing with sound or muted), the game changes to a gray screen

### Expected behavior

Game should start and play

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Google Chrome

### Additional information

it logs this error in the dev console : 

` Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xd24c68 }) to handler FunctionObject(FunctionObject { ptr: 0xd24a08 }) : RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)")`

**Comment by evilpie** [comment]
This is fixed by https://github.com/ruffle-rs/ruffle/pull/10299.

**Comment by Mickmick2012** [comment]
#10299 is merged, will test when the next nightly build comes out
