### ISSUE TITLE
Doom 2D: Marine Speak

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#10464]
### Describe the bug

https://user-images.githubusercontent.com/75534590/228857731-1d0b61fd-f579-42be-9b15-0e55f332eff9.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/228857790-68fc34f0-bd25-462d-b0d7-7f4970d3c526.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[498101_Doom2D.zip](https://github.com/ruffle-rs/ruffle/files/10280682/498101_Doom2D.zip)

**Comment by n0samu** [comment]
Can you explain what the issue is? I don't understand it from watching your videos

**Comment by mateon1** [comment]
I believe the issue the video is meant to show is the sound effect of the phone not stopping after a short time.
The rendering differences also make the ruffle version nearly unreadable, but I don't think that's what the original issue meant.

**Comment by p0008874** [comment]
With debug menu, the instance keep delete when Marine is speaking
https://github.com/ruffle-rs/ruffle/assets/75534590/8a043064-fe9b-4cf1-8d1b-eb9c30189231

This is whole code.
```
package
{
   import flash.display.MovieClip;
   import flash.events.Event;
   import flash.media.Sound;
   import flash.media.SoundChannel;
   
   public dynamic class Knarrenheinz extends MovieClip
   {
       
      
      public var radio:Sound;
      
      public var radioChannel:SoundChannel;
      
      public function Knarrenheinz()
      {
         super();
         addFrameScript(0,frame1,1,frame2);
      }
      
      internal function frame1() : *
      {
         stop();
      }
      
      internal function frame2() : *
      {
         stop();
         radio = new Radio();
         radioChannel = radio.play();
         radioChannel.addEventListener(Event.SOUND_COMPLETE,radioChannelHandler);
      }
      
      public function radioChannelHandler(param1:Event) : void
      {
         radioChannel = null;
      }
   }
}

```
