### ISSUE TITLE
Cannot load external images with AS3 Loader

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10463]
### Describe the bug

Consider this sample: [AS3ImageLoader.zip](https://github.com/ruffle-rs/ruffle/files/11110181/AS3ImageLoader.zip)
```as
var loader:Loader = new Loader();
var url:URLRequest = new URLRequest("test.png");
loader.load(url);
addChild(loader);
```
Ruffle requests and reads the image file, but never displays it. Loading SWF files works fine, but loading image files does not.

### Expected behavior

The image should be displayed in the top-left corner of the player.
![image](https://user-images.githubusercontent.com/71368227/228800123-25b2bcef-f9a1-4a23-b55d-31ef45e70db7.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This problem was first mentioned by @Lord-McSweeney in #10440.

**Comment by Lord-McSweeney** [comment]
Fixed by #11045.
