### ISSUE TITLE
Ancient Jewels - Endless Pop Up but no error

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10462]
### Describe the bug

https://www.newgrounds.com/portal/view/515309?emulate=flash - When you want to start the level and get some infos a pop-up comes up where you press okay but nothing happens just flashes back. Or the game instantly ends? I don't know,

![image](https://user-images.githubusercontent.com/23042167/228784630-55f7ae57-1bb0-4976-b82b-c0696f081361.png)

### Expected behavior

To run the game and be playable

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by desertking** [comment]
The game progress now but there are still bugs. The game goals are bugged. There is only one tile in the top left which needs to be "matched" to win every level. That is not how the game works.

**Comment by evilpie** [comment]
@desertking could you open a new issue for this?
