### ISSUE TITLE
cursor missing in input textfield,  avm1

### ISSUE THREAD

**Issue by flashuser2** [ruffle-rs/ruffle#10478]
### Describe the bug

When an input textfield is selected, but nothing is written in it, the cursor doesn't show.
Is it possible to add this to the code? 
It wasn't a problem in earlier versions of ruffle,    i.e. one from 8th of july 2021.
[input_text_cursor_issue.zip](https://github.com/ruffle-rs/ruffle/files/11122504/input_text_cursor_issue.zip)

### Expected behavior

Input textfield works best if the cursor becomes visible the very moment an input textfield is selected, - before the user starts to write in it.

### Affected platform

Self-hosted version

### Operating system

windows 10

### Browser

Firefox

**Comment by n0samu** [comment]
Somewhat related to #3682
