### ISSUE TITLE
BitmapData "erase" not working

### ISSUE THREAD

**Issue by pestoforce** [ruffle-rs/ruffle#10484]
### Describe the bug

In Flash Player using BitmapData.draw with the 4th param as "erase" draws the specified pixels in a mode that makes that area of the bitmap transparent:

`bmd.draw(newTile, ma, null, "erase");`

In Ruffle, this is not currently working (but no panic or error is shown). 

### Expected behavior

Using "erase" in a bitmapData draw function should erase the specified pixels.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Chrome

### Additional information

Here is a minimal reproduction of the issue as .fla and .swf
[bitmapdata_erase.zip](https://github.com/ruffle-rs/ruffle/files/11124843/bitmapdata_erase.zip)

The crates are initialized and drawn into a bitmapData object. Every 30 frames an "erase" call is made. The crates should be "erased" from top left, row by row.

**Comment by n0samu** [comment]
BitmapData.Draw with blend mode is already implemented in AVM1 and AVM2, so this not working is a bug.

**Comment by n0samu** [comment]
Fixed by #11323
