### ISSUE TITLE
The I of It: Unclickable walkthrough button

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10496]
### Describe the bug

https://www.newgrounds.com/portal/view/570709?emulate=flash
Normally when getting in game, there's a walkthrough button on the top right of the screen that's supposed to take you to a walkthrough page, but you can't seem to click on it in ruffle, just start the game up and once the intro cutscene ends, look for the walkthrough text on the top right of the screen and try to click on it.

### Expected behavior

You should be able to click on it like in flash.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by waspennator** [comment]
Update, not only is the walkthrough button still broken, but on the title screen, the play more games and a game by gameshot buttons aren't clickable either.

**Comment by n0samu** [comment]
The relevant buttons are actually HTML text fields with <a> tags that link to the relevant sites. Here's the "a game by gameshot.org" field (DefineEditText 323) for example:
`<p align="left"><font face="Gilles' Comic Font" size="16" color="#000000" letterSpacing="1.000000" kerning="1"><a href="http://www.gameshot.org" target = "_blank">a game by </a><font size="18"><a href="http://www.gameshot.org" target = "_blank">Gameshot.org</a></font></font></p>`

Ruffle currently does not have this functionality implemented.
