### ISSUE TITLE
10 More Bullets - Regression to a black screen

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#10492]
### Describe the bug

https://www.newgrounds.com/portal/view/627247/format/flash?emulate=flash

I had previously logged 10 More Bullets as working but with slow performance. I went to test it with the April 1st build to see if the performance improved but it is now stuck on a black screen. My console has logged this error:

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xd16bd0 }) to handler FunctionObject(FunctionObject { ptr: 0xd279b0 }) : ReferenceError: Error #1065: Variable decodeURI is not defined.

### Expected behavior

Expected for the game to load and be playable like it was when I last tested, maybe two weeks ago.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome version Version 110.0.5481.178

**Comment by n0samu** [comment]
Should be progressed by #10360

**Comment by waspennator** [comment]
Doesn't seem to get stuck on a black screen on my end on the latest nightly anymore, though performance is still slow on my end least on web.
