### ISSUE TITLE
VVVVVV (Beta Tester Version) Black Screen on Startup, Error in console

### ISSUE THREAD

**Issue by replaymikey** [ruffle-rs/ruffle#10508]
### Describe the bug

[VVVVVV Beta Test.zip](https://github.com/ruffle-rs/ruffle/files/11130147/VVVVVV.Beta.Test.zip) After Ruffle loads, I get a black window and this error in Google Chrome's Console: ERROR core/src/avm2/events.rs:419 "Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xf4e7b8 }) to handler FunctionObject(FunctionObject { ptr: 0x5b1238 }) : RustError("VerifyError: Trait z in class dwgraphicsclass has same name as trait z in class DisplayObject, but does not override it")"

### Expected behavior

In Adobe Flash Player, once the file loads it would show a text box saying "click to start" as shown below 
![VVVVVV Beta test click to start screen](https://user-images.githubusercontent.com/40784301/229305401-4384be73-60c1-4607-b0d5-5b9f49704716.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Google Chrome Verison 111.0.5563.112

### Additional information

Left and Right control the menus. Couldn't find much about this SWF file but I concluded it was a beta test version because in the credits under beta testing it says you, yes, you.

**Comment by Lord-McSweeney** [comment]
This happens because playerglobal versioning is not yet implemented.
