### ISSUE TITLE
Xenos -  graphical issues and black screen on start 

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#10507]
### Describe the bug

`ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x55e5043d2860 }) to handler FunctionObject(FunctionObject { ptr: 0x55e4f859cba0 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: freeze)
`

Flash: 

https://user-images.githubusercontent.com/103858019/229300160-31287505-5b3b-4e23-8827-9269fa9f4a85.mp4

Ruffle:

https://user-images.githubusercontent.com/103858019/229300199-86cd71aa-835c-44ee-bcb1-ef76b7abcc03.mp4

### Expected behavior

should act like flash / be able to be played

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[gXenosMaxGamesMTM1OA==,g,.swf.zip](https://github.com/ruffle-rs/ruffle/files/11129981/gXenosMaxGamesMTM1OA.g.swf.zip)

**Comment by Lord-McSweeney** [comment]
I think the relevant error before that is that ColorMatrix is not defined:
```
TypeError: Error #1006: ColorMatrix is not a function of class global.
	at MCgui/updateXenos()
	at MCgui()
	at Game/sceneSetup()
	at Game/Update()
```

**Comment by Kz-92** [comment]
seems fixed on latest
