### ISSUE TITLE
Wasted Youth, Part 1: Context menu items not showing (AS2)

### ISSUE THREAD

**Issue by twilson90** [ruffle-rs/ruffle#10525]
### Describe the bug

The latest Windows build displays no context menu at all on right click, let alone custom context menu items.
There's already some discussion of this but they were tagged avm2.

### Expected behavior

Default context menu and/or custom context menu items should display on right click.

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

ruffle-nightly-2023_04_02-windows-x86_64

**Comment by n0samu** [comment]
Context menu and other UI elements are not implemented in the desktop app yet. This is being worked on in #10426.
