### ISSUE TITLE
The Ruffle desktop app is extremely unstable on my end

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1052]
Issues include artifacts on vectors, images not displaying at all, and lag that gets worse to the point of freezing my computer when the window is maximized.

Processor: AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G  2.50 GHz
Memory: 8 GB
Operating System: Windows 10 Home 64-bit

Comparison of a game running in the desktop app vs. other instances/players:
[Ruffle Desktop](https://cdn.discordapp.com/attachments/722872096002408529/748241150951030854/unknown.png) | [Ruffle Web](https://cdn.discordapp.com/attachments/722872096002408529/748241633568620645/unknown.png) | [Adobe Flash Player](https://cdn.discordapp.com/attachments/722872096002408529/748241264516005988/unknown.png)

[Example SWF used](https://cdn.discordapp.com/attachments/722872096002408529/748239711931203755/bubblebust18.swf)

[Log](https://cdn.discordapp.com/attachments/722872096002408529/748246847557992469/message.txt)

I'm using the latest nightly from [here](https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/windows/ruffle_windows_latest.zip).

**Comment by Delphox** [comment]
I had the same rendering issue and figured out it seems to be caused by DX12. By making a shortcut to ruffle.exe and adding the argument `-g vulkan` or `-g dx11`, the graphical issues don't occur.
