### ISSUE TITLE
The variables do not get send from actionscript 2 to php 

### ISSUE THREAD

**Issue by charco57** [ruffle-rs/ruffle#10535]
### Describe the bug

I have an actionscript 2.0 file that collects data and sends it to php. 
This worked fine in flash, but fails in ruffle.

The actionscript
****************
function fillForm() {
	// displays the summary results
	summary.myName.text = me;
	summary.myMail.text = email;
	summary.score.text = correct;
	summary.questions_asked.text = numQ;
	var percentage = Math.round(100*correct/numQ);
	summary.perc.text = percentage;
	for(var w=0; w<wrongUns.length; w++){
		showWrongOnes += wrongUns[w]+"<br>";  // this is fine for summary screen, but not for emailed results.
	}
	summary.further_study.htmlText = showWrongOnes;  // display errors on summary screen
	elapsed();
	summary.m.text = minutes_elapsed;
	summary.s.text = seconds_elapsed;

	// now the variables to be sent by mail
	summary.testName=testName;
	summary.realname = me;
	summary.marks = correct;
	summary.asked = numQ;
	summary.percentage = percentage;
	summary.timeTakenMin = minutes_elapsed;
	summary.timeTakenSec = seconds_elapsed;
	summary.destination = email;// the email address input by the person doing the test
	summary.wrongOnes = wrongUnsPhp; // this emails the whole array string separated by <br> tags for processing by php
	summary.txtFile = txtFile;
}

summary.sendit.onRelease = function() {
		// send variables in form movieclip (the textfields)
		// to email PHP page which will send the mail
		summary.loadVariables("../mail/mc_test.php","POST");
	};

*********************************************

The php mail form gets sent, but none of the variables are collected:

*********************************************

<?php

error_reporting(E_ALL);

$lineBreak = "\n";
$comma = ", ";

$subject=$_POST["testName"];
$data1=$_POST["realname"];
$data2=$_POST["marks"];
$data3=$_POST["asked"];
$data5=$_POST["txtFile"];
$incomingArray = $_POST["wrongOnes"];
$sendTo=$_POST["destination"];
$data7=$_POST["percentage"];

$emailList = "*****@*****.com".","."*****@******.org";

$arr = explode(".,", $incomingArray);

$wrongArray="";
foreach ($arr as $wrong){
$wrongArray.="<li style='font-family:Verdana;font-size:12px;color:maroon'>".$wrong."</li>";
}

$headers = "MIME-Version: 1.0" . "\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\n";
$headers .= "bcc: $emailList\r\n";
$headers .= "From: " . $_POST["realname"]. "<" . "*******l@******.com".">\r\n";

// next include a reply_to
$headers .= "Reply-To: " . "results@ibchem.com". "\r\n";

$headers .= "Return-path: " . $_POST["email"]. "\r\n";;

// now we can add the content of the message to a body variable
$message = "<html><head><title>Online test results</title></head><body> <p>";
$message .= "<p style='font-family:verdana;font-size:12px;color:blue'>".$_POST["realname"]." has taken the ".$subject." and attempted ".$_POST["asked"]. " questions";
$message .= " in ".$_POST["timeTakenMin"]." minutes and ".$_POST["timeTakenSec"]." seconds";
$message .= " and scored a total of ".$_POST["marks"]."</p>\r\n\r\n";

$message .= "<p style='font-family:verdana;font-size:12px;color:blue'>The results were sent to <u>".$sendTo."</u></p>\r\n\r\n";
$message .= "<p style='font-family:verdana;font-size:12px;color:blue'>The following question themes were answered incorrectly: </p><p style='font-family:verdana;font-size:12px;color:maroon'><ul>".$wrongArray."</ul></p>";
$message .= "\r\n\r\n"."<p style='font-family:verdana;font-size:12px;color:blue'>The final percentage total = ".$data7."%</p>";
$message .= "</body></html>";
// once the variables have been defined, they can be included
// in the mail function call which will send you an email
mail($sendTo, $subject, $message, $headers);

?>

### Expected behavior

The php file receives the POST variables and parses them into an email.

The email is being sent but none of the information gets parsed.

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by n0samu** [comment]
Closing in favor of #2584 and #10545. I think we finally have a good idea of what's going wrong, so hopefully a fix will come soon enough!
