### ISSUE TITLE
MovieClip.loadVariables with method argument does not send local variables

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10545]
Adobe's official docs are very unclear, but [this page](https://www.oreilly.com/library/view/actionscript-the-definitive/1565928520/re143.html) has a good explanation of the `method` argument of MovieClip.loadVariables:
> method: If specified, variables are both sent and loaded. If omitted, variables are loaded only. Must be either the literal "GET" or "POST"; no other expression is allowed.

Ruffle's implementation of this is incorrect. Consider the attached project [loadVarsTest.zip](https://github.com/ruffle-rs/ruffle/files/11146105/loadVarsTest.zip) with this code:
```as
test_mc.go_btn.onRelease = function() {
	test_mc.test1 = "hi";
	test_mc.test2 = "bye";
	trace(test_mc.test1);
	trace(test_mc.test2);
	test_mc.loadVariables("http://localhost:8000","GET");
	test_mc.loadVariables("http://localhost:8000","POST");
}
```
With a server listening at port 8000, you'll see Flash Player send 2 requests:
`GET /?test1=hi&test2=bye`
`POST /`, body: `test1=hi&test2=bye`

Meanwhile Ruffle's requests look a bit different:
`GET /?super=%5Bobject+Object%5D&arguments=`
`POST /`, body: `super=%5Bobject+Object%5D&arguments=`

Both Ruffle and Flash Player trace the correct values:
```
hi
bye
```

This is the cause of #2584.

**Comment by Herschel** [comment]
Fixed by #10571.

**Comment by n0samu** [comment]
Awesome, thank you! Just a note - Ruffle is sending the value of the `go_btn` variable when it shouldn't be - I guess Ruffle should ignore variables set via PlaceObject tags.
`go_btn=_level0.test_mc.go_btn&test2=bye&test1=hi`

**Comment by torokati44** [comment]
@n0samu this sounds like a separate, follow-up issue to me.
