### ISSUE TITLE
Snailiad - Can't proceed past intro

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#10540]
### Describe the bug

https://www.newgrounds.com/portal/view/573352?emulate=flash

Snailiad is at a point now where it starts up, the title screen works and the intro works but it stops when you get to the game.

The prominent console error appears to be:
Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3f661b0 }) to handler FunctionObject(FunctionObject { ptr: 0x3f289f0 }) : RustError("Modifying an XMLList object is not yet implemented: target XmlObject(XmlObject { ptr: 0x4cf8a28 })")

### Expected behavior

Once everything is working, game should proceed to gameplay after the intro.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome version Version 110.0.5481.178

**Comment by Lord-McSweeney** [comment]
This also needs `ByteArrayObject` serialization.
