### ISSUE TITLE
Gateway 2 - Robot Disappears

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10569]
### Describe the bug

https://www.spiele-umsonst.de/gateway-2-t891.html - I use the files from Flashpoint on Newgrounds the robot seems to be there.... But the flashpoint version works thou not on web.. Confusing

ERROR core/src/library.rs:200 Tried to instantiate non-registered character ID 87
ruffle_web-wasm_extensions.js:681 ERROR core/src/display_object/movie_clip.rs:1608 Unable to instantiate display node id 87, reason being: Character id doesn't exist
ruffle_web-wasm_extensions.js:681 ERROR core/src/library.rs:200 Tried to instantiate non-registered character ID 87
ruffle_web-wasm_extensions.js:681 ERROR core/src/display_object/movie_clip.rs:1608 Unable to instantiate display node id 87, reason being: Character id doesn't exist
ruffle_web-wasm_extensions.js:681 ERROR core/src/library.rs:200 Tried to instantiate non-registered character ID 87
ruffle_web-wasm_extensions.js:681 ERROR core/src/display_object/movie_clip.rs:1608 Unable to instantiate display node id 87, reason being: Character id doesn't exist

### Expected behavior

The Robot to be visible.

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by relrelb** [comment]
This uses the `ImportAssets2` tag, which is currently unimplemented.

**Comment by n0samu** [comment]
Closing in favor of #2365
