### ISSUE TITLE
This is the Only Level 3: Level does not work

### ISSUE THREAD

**Issue by angelo-wf** [ruffle-rs/ruffle#10601]
### Describe the bug

The intro and menu seems to work fine, but as soon as the level is entered, the transition effect constantly loops, flashing the screen black quite rapidly ***[possible epilepsy warning]***. Pausing and unpausing with `P` causes this to stop.

However, interaction within the level does not work at all. You can move/jump around and use the doors, but spikes do not kill you and the switch cannot be pulled. The level timer is also frozen, but pausing and unpausing makes it tick forward by 0.03 seconds every time.

SWF: [here, from jmbt02.com](https://static1.squarespace.com/static/554aebede4b00d559e8e331c/t/5573c35ae4b0d8ce4d0eedbe/1433650010848/TITOL3-PUBLIC_secure.swf) or [in browser on Newgrounds](https://www.newgrounds.com/portal/view/588876/format/?emulate=flash).

### Expected behavior

The level to work properly. The transition should play once, the timer should run, spike should kill you and pulling the switch should be possible (opening the gate).

### Affected platform

Online demo

### Operating system

macOS Ventura 13.3

### Browser

Safari 16.4

### Additional information

Lines like the following are constantly logged while inside the level (and not paused):
```
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x136b508 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1335f98 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x301beb8 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1335e10 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x120d340 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)
[Log] ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1372ed8 }) to handler FunctionObject(FunctionObject { ptr: 0x34dd308 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: a) (core.ruffle.3bff15b5edc179b68ef0.js, line 1)

```

**Comment by Lord-McSweeney** [comment]
There are also some warnings, such as `Display object container has no child with name tile1x2`.

**Comment by moodyboy3** [comment]
I am also experiencing this exact same bug. I opened the game on KBHGames, which has a lot of flash games that all use the Ruffle emulator, and I could not flip the switch at all.

I also experienced two bugs in This Is The Only Level 2. First bug is that after the Free Falling level, it gave me the congratulations message, even though I did not finish the game, but I was able to bypass this. The second, more major bug is that for me, stage 32 is called "This is my hint." However, I could not find any mention of this level in any walkthrough, and no matter what, I could not open the gate, which means this level is probably a bug and is meant to be another level.

**Comment by Gargaj** [comment]
The game seems to work fine with the latest extension for now (try https://www.gamezhero.com/games/thisistheonlylevel3 ); however, on Stage 7 you're required to use a right-click context menu to advance, and while the menu option does show up, it doesn't do anything:
![image](https://github.com/ruffle-rs/ruffle/assets/1702533/0ad37f4a-57af-4cba-8fd5-a7336f7cba07)

**Comment by n0samu** [comment]
AS3 context menu callbacks are unimplemented; see also https://github.com/ruffle-rs/ruffle/issues/10287#issuecomment-1476889450. Closing since the original issue is resolved.
