### ISSUE TITLE
Memory.exe: Right click won't work

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#10612]
### Describe the bug

https://user-images.githubusercontent.com/75534590/230738850-2cdcfece-86d0-4dc5-92f1-fdc79cbbddf3.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/230738854-99541bc6-1eb6-45d2-8afb-3e96546c8a78.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

https://www.newgrounds.com/portal/view/715381

**Comment by p0008874** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/75534590/ff112786-423a-4000-8b9f-800b14531237)
Right click still won't remove and Context menu popup.

**Comment by n0samu** [comment]
See #10288
