### ISSUE TITLE
Graphics.beginBitmapFill() is not working for images

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10628]
### Describe the bug

Despite supposedly being implemented in #10123, Graphics.beginBitmapFill() does not seem to be working, at least for images / image data. [The example from the Adobe documentation](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html#beginBitmapFill()) shows nothing but a blank screen in Ruffle, but it works in Flash Player.

### Expected behavior

The code should display the `image1.jpg` file.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I found this while investigating why the graphics are messed up in #9535. Here is an example based on the code from that game: [beginBitmapFill.zip](https://github.com/ruffle-rs/ruffle/files/11186672/beginBitmapFill.zip)
The developer's logo should be displayed, but Ruffle again shows nothing but a blank screen.

**Comment by Lord-McSweeney** [comment]
In #9735, #9971, and #9549, `beginBitmapFill` seems to be working, though incorrectly. On at least the first two, it seems that the resulting graphics drawn are scaled incorrectly. This issue may also be the cause for #9549 not displaying correctly.
