### ISSUE TITLE
Sky Cops: Ocean background not shown

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10633]
### Describe the bug

Link to SWF: https://www.playgb.com/swfs/1_3.swf

In [Sky Cops](https://www.playgb.com/play/sky-cops), after you click the Start Mission button, you'll be flying over the ocean towards an island. But since Ruffle version 2023-02-07, the ocean is not shown anymore.
![image](https://user-images.githubusercontent.com/71368227/230862116-0c0a438c-8deb-4777-af29-d18ae268e1e1.png)

### Expected behavior

The ocean should be visible.
![image](https://user-images.githubusercontent.com/71368227/230863038-c737c52b-f7b5-4161-931e-e4a2959fe425.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This is a regression caused by commit 755425ebf from #8873.

**Comment by Toad06** [comment]
I think this is the same issue as #9522. If you change the `pending_removal` function to always return false, the background is displayed as expected.
https://github.com/ruffle-rs/ruffle/blob/be2d5faa6f4798b7169d83e54171e2ac90407e37/core/src/display_object.rs#L1105-L1107

Maybe that checking for a negative depth is not sufficient.

**Comment by Toad06** [comment]
Confirmed that using something more reliable than the depth fixes the issue:
https://github.com/ruffle-rs/ruffle/compare/master...Toad06:ruffle:unload_test

**Comment by n0samu** [comment]
Awesome, looking forward to a PR if you're up for it! 😃

**Comment by waspennator** [comment]
Still present as of the latest nightly
