### ISSUE TITLE
Ripple Dot Zero: Loading error

### ISSUE THREAD

**Issue by moodyboy3** [ruffle-rs/ruffle#10637]
### Describe the bug

The menu screen and world map screen are working very well. However, when I pressed spacebar to play the first level ("Like You Just Woke Up"), it shows a loading error screen. I attached a screenshot of the error below.

I opened the game on this site: https://kbhgames.com/game/ripple-dot-zero

![rippledot_screenshot](https://user-images.githubusercontent.com/130413107/231022624-5891af9a-f9f4-4326-abea-f0c0cb312db6.jpg)

### Expected behavior

The level should load properly with no problems, and no error screen.

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Google Chrome, Version 111.0.5563.147

**Comment by Lord-McSweeney** [comment]
It seems that the assets were removed from all the stores except this one: https://www.rippledotzero.com/rdz/2/tutorial_01_sheet.swf
Unfortunately, that one returns a CORS error when trying to access from kbhgames.com.

**Comment by n0samu** [comment]
Please install the Ruffle browser extension and access the game from here: https://www.rippledotzero.com/

This will avoid the CORS error. CORS is a security restriction of the modern web that we can't do anything about. So the game can't work on third-party sites such as KBHGames unless the developers configure their web server to send the appropriate CORS headers.

**Comment by moodyboy3** [comment]
I installed the browser and clicked on the link you sent, and everything is working well now. Thank you very much.
