### ISSUE TITLE
Error on moz-extension://e45decce-a1b2-4d90-a156-c0be9dd7b1c2/player.html

### ISSUE THREAD

**Issue by Athrodite** [ruffle-rs/ruffle#10642]
Operating on most recent firefox update with web app, trying to access a couple of animal creator games [https://www.webpaws.com/games/play.php?gid=1304](url) & [https://www.webpaws.com/games/play.php?gid=1110 ](url)
Seems to affect literally nothing else I've opened even on the same website. On the regular page, it almost loads in, then stops and gives "Ruffle wasn't able to run the Flash embedded in this page. You can try to open the file in a separate tab, to sidestep this issue." But when I do, it does the same thing and then goes to a 'something went wrong' message. Sometimes it lets me click a play button that comes up before the actual game, but just goes to the same thing. These are the error details from the separate tab.

# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
Error stack:
```
339/getImports/imports.wbg.__wbg_new_15d3966e9981a196@moz-extension://e45decce-a1b2-4d90-a156-c0be9dd7b1c2/dist/339.js:2212:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h927501cce3fc7417@:wasm-function[8169]:0x8058cd
std::panicking::rust_panic_with_hook::hc53aea0352e77326@:wasm-function[5446]:0x7390b5
core::panicking::panic_fmt::hf4a9df75710ece83@:wasm-function[8051]:0x80053c
alloc::raw_vec::capacity_overflow::hf53f9cfda71e4fe1@:wasm-function[7844]:0x7fbd78
alloc::raw_vec::RawVec<T,A>::reserve_for_push::hde571ac3f730c22a@:wasm-function[5139]:0x71eeac
ruffle_core::bitmap::operations::flood_fill::h23d407d4eaac595a@:wasm-function[1487]:0x4202c5
ruffle_core::avm1::globals::bitmap_data::flood_fill::hee6c9b4ae86c1c10@:wasm-function[2269]:0x544de2
ruffle_core::avm1::function::Executable::exec::h4504ceb347e7fd28@:wasm-function[589]:0x1a6658
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h24252d26605522dc@:wasm-function[970]:0x336251
ruffle_core::avm1::activation::Activation::run_actions::h74244169b0188f52@:wasm-function[480]:0x12335
ruffle_core::avm1::function::Executable::exec::h4504ceb347e7fd28@:wasm-function[589]:0x1a6435
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call::h1ac8c21d9358a332@:wasm-function[1609]:0x44b2f5
ruffle_core::avm1::activation::Activation::run_actions::h74244169b0188f52@:wasm-function[480]:0x24c32
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h79b4ab1b5fc5a77b@:wasm-function[1603]:0x4493cf
ruffle_core::player::Player::run_actions::h0f3a9dd2c2001f52@:wasm-function[848]:0x2d8e85
ruffle_web::Ruffle::tick::h34d7356c042327a9@:wasm-function[683]:0x23e53e
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3339895efa4d93d4@:wasm-function[9796]:0x83e2ad
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfa30efc5d157bfb9@:wasm-function[8683]:0x8111e1
__wbg_adapter_56@moz-extension://e45decce-a1b2-4d90-a156-c0be9dd7b1c2/dist/339.js:293:10
real@moz-extension://e45decce-a1b2-4d90-a156-c0be9dd7b1c2/dist/339.js:270:20

```

# Player Info
Allows script access: false

# Page Info
Page URL: moz-extension://e45decce-a1b2-4d90-a156-c0be9dd7b1c2/player.html?url=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F9f78e7b6-b6e6-4026-9ace-d2bc1c9d3225%2Fd2hu5h0-65117560-6d56-42d9-91bf-73943eefb60b.swf%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl0sIm9iaiI6W1t7InBhdGgiOiIvZi85Zjc4ZTdiNi1iNmU2LTQwMjYtOWFjZS1kMmJjMWM5ZDMyMjUvZDJodTVoMC02NTExNzU2MC02ZDU2LTQyZDktOTFiZi03Mzk0M2VlZmI2MGIuc3dmIn1dXX0.rewnGJx5hiZxIZmhj0VTKlBI_k5i-PbUXvACy5TPwUE
SWF URL: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9f78e7b6-b6e6-4026-9ace-d2bc1c9d3225/d2hu5h0-65117560-6d56-42d9-91bf-73943eefb60b.swf?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl0sIm9iaiI6W1t7InBhdGgiOiIvZi85Zjc4ZTdiNi1iNmU2LTQwMjYtOWFjZS1kMmJjMWM5ZDMyMjUvZDJodTVoMC02NTExNzU2MC02ZDU2LTQyZDktOTFiZi03Mzk0M2VlZmI2MGIuc3dmIn1dXX0.rewnGJx5hiZxIZmhj0VTKlBI_k5i-PbUXvACy5TPwUE

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-01
Channel: nightly
Built: 2023-04-01T00:23:12.618Z
Commit: 6fda813f0c329200cb6ca345c3f3debf35423f40
Is extension: true

# Metadata
width: 900
height: 600
frameRate: 60
numFrames: 2
swfVersion: 9
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 943832

**Comment by n0samu** [comment]
Looks like Ruffle is running out of memory. Not sure why yet.

**Comment by n0samu** [comment]
From Dinnerbone on Discord:
> I'd say the bug here is that our flood_fill impl must be infinite looping
I've not really looked at it before, but it does look susceptible to be broken if it's told to replace X with X
