### ISSUE TITLE
Mahjong Classic - No reaction when clicking play button

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10663]
### Describe the bug

Here is the .swf file and the error it throws. I guess the mochi can be ignored it's rather the bottom one?

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/mahjongclassic.swf
viewtopic,p,7164.html#7164:1 Access to fetch at 'https://www.mochiads.com/static/lib/services/MochiLC.swf' from origin 'https://www.spiele-umsonst.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
www.mochiads.com/static/lib/services/MochiLC.swf:1          Failed to load resource: net::ERR_FAILED
ruffle_web-wasm_extensions.js:681 ERROR core/src/loader.rs:834 Error during movie loading: FetchError("Got JS error")
viewtopic,p,7164.html#7164:1 Access to fetch at 'https://www.mochiads.com/static/lib/services/services.swf' from origin 'https://www.spiele-umsonst.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
www.mochiads.com/static/lib/services/services.swf:1          Failed to load resource: net::ERR_FAILED
ruffle_web-wasm_extensions.js:681 ERROR core/src/display_object/movie_clip.rs:2127 Got "ReferenceError: Error #1069: Property http://adobe.com/AS3/2006/builtin::hasOwnProperty not found on Class and there is no default value." when constructing AVM2 side of movie clip of type game::MainMenu

### Expected behavior

Load and Run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
The important error is this one:
```
ReferenceError: Error #1069: Property http://adobe.com/AS3/2006/builtin::hasOwnProperty not found on Class and there is no default value.
	at com.greensock.easing::FastEase$/activate()
	at game::MainMenu()
	at flash.display::DisplayObject/flash.display::DisplayObject()
	at flash.display::InteractiveObject/flash.display::InteractiveObject()
	at flash.display::DisplayObjectContainer/flash.display::DisplayObjectContainer()
	at flash.display::Sprite()
	at flash.display::MovieClip()
	at Mahjong_fla::main_60()
	at flash.display::MovieClip/flash::display::MovieClip::nextFrame()
	at Mahjong_fla::fullLogo_26/frame180()
```

**Comment by desertking** [comment]
The play button seems to work here as well now as in Dead Zed 2 and Popstar I reported.

**Comment by Lord-McSweeney** [comment]
Seems to be playable now.
