### ISSUE TITLE
Text width miscalculated when setting autoSize on centered or right-aligned text field

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10660]
### Describe the bug

Consider the following sample: [NanacaScoreField.zip](https://github.com/ruffle-rs/ruffle/files/11209875/NanacaScoreField.zip). This is a simpler demonstration of #1440.

Here is the AS code:
```as
score_txt.autoSize = "right";
score_txt.text = "999.99";
```

In Ruffle, it looks like this:
![image](https://user-images.githubusercontent.com/71368227/231421473-81b8dbdb-eaca-4bf9-8acc-ebbc3047b3f2.png)

Notice that the score text is cut off.

### Expected behavior

Here is how it appears in Flash:
![image](https://user-images.githubusercontent.com/71368227/231421343-5a0a8223-6020-4d33-bc5c-bd11727325e7.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

The score_txt field is set to right alignment in the Flash editor. The problem persists if the field is set to center alignment, and disappears if the field is set to left alignment. The problem disappears if the AS code that sets `autoSize` is removed, but persists if `autoSize` is set to "left", "right", or "center".

I tried adding the following line after https://github.com/ruffle-rs/ruffle/blob/aef3ed2fcb00c3df0ef21230c52971f30ade24de/core/src/display_object/edit_text.rs#L730
`println!("bounds: {:?}\nintrinsic bounds: {:?}", edit_text.bounds, intrinsic_bounds);`

According to my understanding of the concept of "intrinsic bounds", they should always start at (0, 0). I noticed that the intrinsic bounds have a nonzero `offset_x` when there is a problem, whereas `offset_x` is 0 when Ruffle is working correctly.

**Comment by SuchAFuriousDeath** [comment]
https://github.com/ruffle-rs/ruffle/blob/690ce110d84dcf8925d60247f685587d8c53adfc/core/src/display_object/edit_text.rs#L746

If we swap intrinsic_bounds.width() for intrinsic_bounds.extent_x(), it seems to be fixed. Even the original #1440. No idea why though, I just messed around.

**Comment by n0samu** [comment]
If it works and doesn't break other tests, I say go for it!

**Comment by SuchAFuriousDeath** [comment]
I ran all tests and all succeeded.

**Comment by n0samu** [comment]
Here is another minimal demonstration that also includes a center-aligned text field and gives both fields outlines: [test.zip](https://github.com/ruffle-rs/ruffle/files/12378071/test.zip)

Here's how it looks in Flash:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/485219b8-63d1-4e9d-b5af-a2465ff10c6b)

Here's how it looks in Ruffle:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/b256ade2-af35-4f23-95b1-a1955120b100)

And here's how it looks in Ruffle with #12598:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/a86a4493-a983-4352-b1bd-7769f8069b29)

The PR at least makes the text visible, but it's still wrong.
