### ISSUE TITLE
Sum Tracks - Loops and gets stuck after armorgames intro

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10670]
### Describe the bug

As in the headline described. It gets stuck after the armorgames intro loops a bit and stays grey.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/sumtracks.swf
viewtopic,p,8590.html:1821 accepted
ruffle_web-wasm_extensions.js:681 ERROR core/src/avm2/globals/flash/net/shared_object.rs:37 SharedObject::get_local: Movie was None
ruffle_web-wasm_extensions.js:681 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xe67728 }) to handler FunctionObject(FunctionObject { ptr: 0x22afcf8 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: data)
ruffle_web-wasm_extensions.js:681 ERROR core/src/avm2/globals/flash/net/shared_object.rs:37 SharedObject::get_local: Movie was None

### Expected behavior

Load and Run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Same problem as https://github.com/ruffle-rs/ruffle/issues/10074#issuecomment-1504361281
