### ISSUE TITLE
Raccoon Racing: Character selection screen does not advance to the next screen

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#10673]
### Describe the bug

[raccoon-racing.zip](https://github.com/ruffle-rs/ruffle/files/11222412/raccoon-racing.zip)

In **"Raccoon Racing"**, when you click on any character in the character selection screen, you should see a picture of a raccoon to proceed to the next screen. However, in Ruffle (as of Nightly 2023-04-13), you see a picture of a raccoon and nothing happens.

The two comparison images below are in GIF format. The image quality was degraded due to GIF compression. This is a large file and may take a while to load.

### Adobe Flash Player (Expected)

![afp](https://user-images.githubusercontent.com/75052171/231768805-55a05cb0-0757-49b6-bda5-3fe6a98c0365.gif)

### Ruffle (Current)

![ruffle](https://user-images.githubusercontent.com/75052171/231769320-5a2e6938-c18e-4e6c-b5e3-4bffa101a163.gif)

### Expected behavior

After selecting a character, the Select Stage screen should appear.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 111

**Comment by Toad06** [comment]
The issue wasn't present in nightly-2021-01-12 (thouigh the game was not in a playable state) - here are the related commits: https://github.com/ruffle-rs/ruffle/compare/nightly-2021-01-12...nightly-2021-01-13
