### ISSUE TITLE
Super Smash Flash - No shadows on the HUD and text (visual bug)

### ISSUE THREAD

**Issue by noddy360** [ruffle-rs/ruffle#10683]
### Describe the bug

This is a minor visual bug in Super Smash Flash. It's nothing gamebreaking or anything, but it's definitely noticeable for someone who's been playing this game since 2007.
Some of the text and HUD elements display without shadows, which is innacurate compared to the actual Flash Player.
Below is a comparison image between the Flash Player (left) and Ruffle (right). I've circled the areas of concern to make it easier to see, I hope it helps:
![Sin título](https://user-images.githubusercontent.com/31973588/231943812-50328cbe-f838-4961-8a1b-932e39d2764e.png)
This visual bug can also be seen in other areas of the game, such as the text on the loading screen when you start the game, and the text in the Adventure Mode title cards.
![Sin título2](https://user-images.githubusercontent.com/31973588/231946375-612f9e14-3018-4197-89cf-abe133198d60.png)

### Expected behavior

The text and HUD elements should have shadows behind them, but they don't in Ruffle. The rest of the game plays without any problems, it's just this one visual bug that sticks out to me.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Google Chrome 111

**Comment by n0samu** [comment]
Filter effects are unimplemented, see #15

**Comment by waspennator** [comment]
![Screenshot 2023-07-09 150236](https://github.com/ruffle-rs/ruffle/assets/78768499/ceb886e5-cfd7-4bfb-a409-b2316f305e8f)
![Screenshot 2023-07-09 150342](https://github.com/ruffle-rs/ruffle/assets/78768499/b5c98084-e3b1-4b82-ad52-5b76de1526e9)
Should be fully resolved by #11878
