### ISSUE TITLE
Youda Sushi Chef demo: Customer graphics are glitched

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10698]
### Describe the bug

Link to SWF: https://www.shockwave.com/content/youdasushichef/sis/YoudaSushiChef_Demo.swf

The previous issue with Youda Sushi Chef (#9085) has been resolved, so the game "works", but the customer sprites are totally messed up:
![image](https://user-images.githubusercontent.com/71368227/232251290-0e1ee8a1-3ad9-4aca-a824-21985fcb5703.png)

### Expected behavior

Here's what the screen is supposed to look like:
![image](https://user-images.githubusercontent.com/71368227/232251358-12f99e00-06d0-4a8f-a7b3-11a7fd4273e7.png)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Looks like the customer sprite animations are composed of multiple embedded VP6 videos with alpha channels. This is almost certainly the same bug as #10700.

**Comment by n0samu** [comment]
Related to #2529. I guess it indicates that something is rendering incorrectly? Not sure.

**Comment by Lord-McSweeney** [comment]
Fixed by #10736.
