### ISSUE TITLE
Visual regression in Governor of Poker

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#10700]
https://spielen.govofpoker.com/games/governor-of-poker-1.swf

nightly-2023-04-04 vs nightly-2023-04-05:
![good](https://user-images.githubusercontent.com/14274782/232253564-9cd3dd2f-c71f-4250-9f88-68de0698f753.png) ![bad](https://user-images.githubusercontent.com/14274782/232253567-bc44694c-dfac-4935-bc2a-c5a010206cf1.png)

The related sprite is in `movies/DefineVideoStream (801)`.

Bisection says that 2ad43994b8f1e507905e45b0b8dca7c4d81eea7a is the first bad commit.

**Comment by Toad06** [comment]
@torokati44, pinging to let you know.

**Comment by Lord-McSweeney** [comment]
This might also be the cause of #10698.

**Comment by torokati44** [comment]
Really sorry that I missed your ping, @Toad06!
Thanks for testing and the report, a fix is now submitted for review.
