### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by henri57** [ruffle-rs/ruffle#10701]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:602:51
Error stack:
```
339/O/n.wbg.__wbg_new_15d3966e9981a196@https://ruffle.rs/demo/339.index.js:1:48008
core::ops::function::FnOnce::call_once{{vtable.shim}}::h31d10b9661c38166@:wasm-function[8139]:0x7ef248
std::panicking::rust_panic_with_hook::hc53aea0352e77326@:wasm-function[5466]:0x727eb6
core::panicking::panic_fmt::hf4a9df75710ece83@:wasm-function[8020]:0x7e9e86
core::panicking::panic::h54beb3f515dd3c6d@:wasm-function[7387]:0x7b6005
ruffle_core::bitmap::bitmap_data::BitmapData::update_dirty_texture::hefb37dc961254f68@:wasm-function[1233]:0x39a90c
<ruffle_core::library::MovieLibrarySource as ruffle_render::bitmap::BitmapSource>::bitmap_handle::h38d21e8290bf8b6c@:wasm-function[3216]:0x60d431
<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::h20d8ef5807f9087b@:wasm-function[1035]:0x33c94b
ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h8bcf323e115a57d3@:wasm-function[3030]:0x5f0376
ruffle_core::display_object::movie_clip::MovieClip::preload::h515cadf80469be7e@:wasm-function[619]:0x1c80a1
ruffle_web::Ruffle::tick::h23b5ea28441fd7bc@:wasm-function[694]:0x23a296
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h8b0a8540a2d13a96@:wasm-function[9758]:0x8269ee
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h56085f3bbff8f367@:wasm-function[8652]:0x7fac35
A@https://ruffle.rs/demo/339.index.js:1:2588
f@https://ruffle.rs/demo/339.index.js:1:2265

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-15
Channel: nightly
Built: 2023-04-15T00:18:50.945Z
Commit: ddb45f2cc2b9c5d9d4dbc5702cfbe907ffc49f2c
Is extension: false

# Metadata
width: 400
height: 600
frameRate: 18
numFrames: 435
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 13540135

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play when the error occurred?

**Comment by henri57** [comment]
bimboclass3.swf from MrDaniel
[bimboclass3.zip](https://github.com/ruffle-rs/ruffle/files/11242699/bimboclass3.zip)

**Comment by n0samu** [comment]
The problem happens due to this error:
`WARN run_frame: ruffle_core::bitmap::bitmap_data: Failed to register raw bitmap for BitmapData: TooLarge`
I paged through all of these terrible cursed images in JPEXS, and found that the image causing this issue is the `DefineBitsJPEG3 (519)` tag, which has its dimensions set to 8705 x 30789 pixels... for some reason. This is the same problem as #2759.
