### ISSUE TITLE
Intro music doesn't play in Club Penguin PSA Missions

### ISSUE THREAD

**Issue by sticks-stuff** [ruffle-rs/ruffle#1070]
Interestingly, running `ruffle quests\global\audio\intromusic.swf` does play the music correctly.

To replicate use `wget --recursive --no-parent https://icer.ink/media1.clubpenguin.com/play/v2/games/quests/` to grab all the PSA missions and then run `ruffle /q*/quest.swf` and then see that the intro music does not play during the introduction.

**Comment by relrelb** [comment]
The intro music seems to play by now. In fact, it doesn't even stop, probably because `Sound.setVolume` is unimplemented.

**Comment by relrelb** [comment]
Closing since this seems to be fixed now.
