### ISSUE TITLE
Flickering on Astronomy Simulator (ActionScript3 Warning Message

### ISSUE THREAD

**Issue by avheuv** [ruffle-rs/ruffle#10721]
Astronomy professor here. Using Ruffle to resurrect some excellent online flash simulations for students. Most work great, but one has a persistent flickering issue, which I have observed on: 
- Chrome OS running Chrome
- MacOS running Chrome
- MacOS running Safari
- Windows 10 running Chrome
- Windows 10 running Edge
- Android running Chrome

Ruffle gives the attached warning and the interactive elements in the simulation flicker as shown in the attached image. The simulations does respond to some actions. Here is the simulation: https://agl-initiatives.org/astroUNL/naap/habitablezones/animations/stellarHabitableZone.html

Is there any solution that I can implement? Can anyone point me in a direction that could fix this issue? 

Thanks,
AVH
![Screenshot 2023-04-17 at 11 27 01 AM](https://user-images.githubusercontent.com/20188651/232535198-36ad6bbb-9a74-4955-b336-c8b44ef63927.png)
![Screenshot 2023-04-17 at 11 25 44 AM](https://user-images.githubusercontent.com/20188651/232535205-d8ee181d-faa2-4f82-828e-a73bb80f94d5.png)

Edit: Added link to simulation.

**Comment by Aaron1011** [comment]
@avheuv Can you post a link to the web page or SWF?

**Comment by adrian17** [comment]
And if you can't for whatever reason, please post a screenshot of the Console tab of the browser devtools.
Without one of these I don't think we'll be able to do any kind of research into the issue.

**Comment by avheuv** [comment]
Of course, I'm so sorry.
https://astro.unl.edu/naap/habitablezones/animations/stellarHabitableZone.html

**Comment by Aaron1011** [comment]
This seems to be caused by classes like `CheckBox` that extend `Sprite` (but *not* `MovieClip`) having frames in the associated `DefineSprite` tag. We're advancing (and looping) those frames, but Flash's behavior is different. I'm continuing to investigate

**Comment by Lord-McSweeney** [comment]
A lot of SWFs have similar issues with flickering UI elements.
