### ISSUE TITLE
Club Penguin PSA Mission 7 Piano Always Hits Two Notes

### ISSUE THREAD

**Issue by Thestickman391** [ruffle-rs/ruffle#1073]
Flash
![image](https://user-images.githubusercontent.com/4157860/91653052-f6affa00-eaf0-11ea-9af2-fa41e37742fd.png)
Ruffle
![image](https://user-images.githubusercontent.com/4157860/91653044-e13ad000-eaf0-11ea-914a-d924053c56e2.png)
Download the swf https://icer.ink/media1.clubpenguin.com/play/v2/games/quests/q7/common/rooms/piano2.swf and see that in Ruffle you can't hit only one note at a time

**Comment by ZingBallyhoo** [comment]
With warnings on the player logs:
```
WARN  ruffle_core::avm1::globals::movie_clip] Ignoring shape hittest and using bounding box instead. Shape based hit detection is not yet implemented. See https://github.com/ruffle-rs/ruffle/issues/177
```
https://github.com/ruffle-rs/ruffle/issues/177
