### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by ersdtfgyhjk** [ruffle-rs/ruffle#10742]
# Error Info
Error name: Error
Error message: Error loading movie: Couldn't read SWF
Error stack:
```
Error: Error loading movie: Couldn't read SWF
    at X.load (https://ruffle.rs/demo/index.js:1:45834)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mali-G72"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC_LDR | CLEAR_TEXTURE | TEXTURE_COMPRESSION_ASTC_HDR
Current limits: Limits { max_texture_dimension_1d: 16383, max_texture_dimension_2d: 16383, max_texture_dimension_3d: 16383, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-19
Channel: nightly
Built: 2023-04-19T00:19:49.258Z
Commit: 4f4327b152087379bae0d566a5d80aa7c9b9c477
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Hi, can you upload the game you were trying to play?

**Comment by n0samu** [comment]
No information provided, closing
