### ISSUE TITLE
Wrong colors with OpenGL renderer on Linux

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#10750]
### Describe the bug

On Linux, the Ruffle desktop app displays incorrect colors with the OpenGL renderer. This can easily be tested by running `./ruffle -g gl` from the terminal. Here is what the [Ruffle logo SWF](https://ruffle.rs/assets/logo-anim.swf) looks like, for example:
![image](https://user-images.githubusercontent.com/71368227/233272185-15b0bea6-0ef9-4f2e-8d3b-9e24ee742f1d.png)

### Expected behavior

The colors should look the same as when the default Vulkan renderer is used.
![image](https://user-images.githubusercontent.com/71368227/233272355-cabd4f34-51c9-4828-8cdf-03d602a2191a.png)

### Affected platform

Desktop app

### Operating system

Ubuntu 22.04 LTS

### Additional information

This has been pointed out a few times before on Discord, but an issue was never logged.

**Comment by Lord-McSweeney** [comment]
A bisect points to b7bc835def1ef66bd1a52bbefbe6b00c9b2663bd being the source of the issue (or at least #9034, I might have messed up bisecting).

**Comment by torokati44** [comment]
Thanks for the bisect @Lord-McSweeney! In that case, pinging @Dinnerbone as the author of said PR, as well as of https://github.com/gfx-rs/wgpu/pull/3343.
