### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

### ISSUE THREAD

**Issue by MISTERYaqwx** [ruffle-rs/ruffle#10752]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X -1_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by n0samu** [comment]
This looks like a problem with the website's server, not with Ruffle. And this is ab extremely old version of Ruffle.
