### ISSUE TITLE
Hot Dog HotShot - White Screen after Play Game

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10762]
### Describe the bug

https://www.newgrounds.com/portal/view/551869?emulate=flash - As mentioned above the game stays white after the player hits play game

### Expected behavior

load menu and work

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Seeing a lot of this warning:
`WARN run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: DoAction tag in AVM2 movie`
Also seeing these:
`WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys`
`WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 XML.name() namespaces`

If I had to guess, I'd say the blocker is XML namespaces.

**Comment by Lord-McSweeney** [comment]
I don't get the `DoAction tag in AVM2 movie`, but I do get this: `GET https://uploads.ungrounded.net/ruffle_wrapper/Upsell.xml 404`

**Comment by n0samu** [comment]
That's because NG doesn't have their logLevel set to "warn" or higher. You should run the game in the desktop app or extension.

**Comment by evilpie** [comment]
I doubt it's related to XML namespaces. The uses of the XML.name at least compare them to string without one.

**Comment by evilpie** [comment]
Seems to work fine now.
