### ISSUE TITLE
Mouse wheeling list makes list "hidden"

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#10769]
### Describe the bug

If I rotate mouse wheel in list at top right, it will sometimes disappear, especially if fast spinning. It does not happen with adobe.

![error](https://user-images.githubusercontent.com/151014/233742114-13ffdf79-a27e-425e-914f-0a7d032287b6.png)

Note picture is complete version, with all hundreds of files. the zip covers minimum files to show bug. so there will be no animation on left, nor text at bottom right. List is loaded so you can test it regardless.
Ignore the unimplemented blend stuff on ruffle too. :)

[swffiles.zip](https://github.com/ruffle-rs/ruffle/files/11299543/swffiles.zip)

### Expected behavior

List keeps showing text of list entries, regardless of how fast I spin mouse wheel.

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

**Comment by n0samu** [comment]
I'm able to consistently reproduce this if I click and hold somewhere in the middle of the scrollbar (to jump to that position), then scroll with the mouse wheel.

**Comment by Toad06** [comment]
I can only reproduce the issue the way nosamu described it. And it also occurs in Flash Player.

**Comment by n0samu** [comment]
Oh good point, I didn't notice it also happens in Flash Player. And yeah, that was the only way I could reproduce it. Closing the issue then!

**Comment by rredford** [comment]
Interesting. In flash I cannot scroll down fast from top to get blank box while ruffle I can, but using nosamu method I can get it on both. What's the difference?

**Comment by n0samu** [comment]
I guess if the scrolling is faster than the SWF's code can load the items they show up blank. It's pretty easy to scroll down the list fast by clicking in the scrollbar. Maybe Ruffle on your system allows faster scrolling with the wheel than Flash does. Either way I'd classify this as a bug in the SWF

**Comment by rredford** [comment]
Allright, well glad its not ruffle issue :D thanks
