### ISSUE TITLE
Issues with Papa's pancakeria

### ISSUE THREAD

**Issue by ProbablyIdiot** [ruffle-rs/ruffle#10760]
The game works fine, but the animation speed is broken in places as well as some visual glitches. 

Transparency broken:
![image](https://user-images.githubusercontent.com/103178805/233581529-af394c85-75b9-475e-a0fc-d3d82b671439.png)

Play button text not centered (is when using flash):
![image](https://user-images.githubusercontent.com/103178805/233581728-3d6392d7-61a4-4019-8abe-fc9093c8cd53.png)

Text input box broken (flashes with random boxes):
![image](https://user-images.githubusercontent.com/103178805/233581875-f7206e87-d91e-4c73-9312-87dec1f17f4c.png)

**Comment by n0samu** [comment]
The text box issue will be fixed by #10734. The other issues are due to unimplemented features. See also: #9201

**Comment by n0samu** [comment]
The missing button blends (transparency) has been fixed by #11891.

**Comment by kjarosh** [comment]
Everything seems to be fixed as of today
