### ISSUE TITLE
Error of "Could not parse URL because of relative URL without a base" even with --spoof-url

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#10773]
### Describe the bug

If a page tries to navigate to a relative URL, normally Ruffle errors (e.g. `ERROR ruffle_desktop::navigator: Could not parse URL because of relative URL without a base, the corrupt URL was: somepage.html`). However, passing it the `--spoof-url` option provides Ruffle a base URL, which Ruffle should use.

Example: Open any of the Weed To Wonder SWFs on desktop and try clicking any of the navigation buttons.

### Expected behavior

Navigation is successful (new page opens in browser).

### Affected platform

Desktop app

### Operating system

Linux

**Comment by n0samu** [comment]
Another good test is the Articles button in this Flash site element: http://ultrasounds.com/US.swf
