### ISSUE TITLE
Zombie Rush: No response when clicking the Play button

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#10789]
### Describe the bug

[zombie_rush.zip](https://github.com/ruffle-rs/ruffle/files/11302999/zombie_rush.zip)

When I click the 'Play' button in the **'Zombie Rush'** game, it is unresponsive and unable to start the game.
AVM1 & Checked on Ruffle 2023-04-22 Nightly.

![image](https://user-images.githubusercontent.com/75052171/233824273-52f2c730-148d-4162-84f5-198806d551a5.png)

### Expected behavior

When you click the Play button, the game should start.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 111

**Comment by n0samu** [comment]
This happens because the game is quickly jumping between frames 94 and 95, and the actual clickable button (DefineButton2 37) is only placed on frame 95. This is yet another instance of #1108.

**Comment by n0samu** [comment]
Fixed by #10862
