### ISSUE TITLE
Final Slam 2 = no color

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#10821]
### Describe the bug

In Final Slam 2,the colors of fighters is grey,which means no color. This mostly happens in creating a character.

### Expected behavior

The fighters should be at least colored, no exceptions. even in fight,even in creating a character.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 112

**Comment by waspennator** [comment]
I tested this issue out on my end and while I was able to confirm the bug where the fighters look all gray happened on older builds, it seems to have gone away as of ruffle build 2023-07-06, can you confirm on your end too?
