### ISSUE TITLE
Self hosted doesn't match with desktop version

### ISSUE THREAD

**Issue by dolarfred** [ruffle-rs/ruffle#10849]
Since the 'Desktop' version of April 26 my swfs using radio buttons and checkboxes work fine, but using the 'Self hosted' web version it doesn't. . .
Same for the version of 27...!!

**Comment by n0samu** [comment]
Please attach the SWF in question and/or link to the website where the problem is occurring

**Comment by dolarfred** [comment]
Here is my attached file:
[laPenduleDefNavig_dolarfred.swf.zip](https://github.com/ruffle-rs/ruffle/files/11342857/laPenduleDefNavig_dolarfred.swf.zip)

**Comment by dolarfred** [comment]
Sorry,
it was a problem with my Firefox browser on my mac (probably  the cache that i've tried to clear, but no result...i've to fix that)

I've tried with :
- Safari without problem
- Firefox on PC Windows without problem
- Min browser without problem
Sorry for this request

**Comment by dolarfred** [comment]
An old ruffle extension had interacted with the self hosted ruffle...!
