### ISSUE TITLE
Relative URLs in extension page are parsed relative to the extension page

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#10844]
### Describe the bug

For example, opening this URL (chrome):
`chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=http%3A%2F%2Fnew.weedtowonder.org%2Fw2w-home.swf`

And clicking "Domestication" will result in a navigation to
`chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/domestication.html`.

The navigation should be to `http://new.weedtowonder.org/domestication.html`.

### Expected behavior

Paths on the extension page SWF viewer should be parsed correctly.

### Affected platform

Browser's extension

### Operating system

(irrelevant)

### Browser

Chrome

**Comment by danielhjacobs** [comment]
Strangely, unless this bug was introduced in the last few days and therefore isn't in Firefox yet, this seems to not affect Firefox. I see you did mention Chrome in the browser section, but I thought it worth noting that this explicitly does not affect Firefox.

**Comment by danielhjacobs** [comment]
In Firefox, the internal player page says for http://new.weedtowonder.org/w2w-home.swf says `document.getElementById('player').loadedConfig.base`. In Chrome, it says `null`.

**Comment by danielhjacobs** [comment]
I think #5144 was bugged for Chrome.

**Comment by relrelb** [comment]
Fixed by #10850.
