### ISSUE TITLE
Visual artifacts / glitches when mousing around Nextcloud interface in Vivaldi

### ISSUE THREAD

**Issue by JL102** [ruffle-rs/ruffle#10857]
### Describe the bug

Firstly, I have no clue why this would happen. There are no Flash files anywhere on Nextcloud (for those of you who don't know, [Nextcloud](https://nextcloud.com) is a self-hosted cloud storage software) so I would not expect Ruffle to affect it at all. Nevertheless, whenever Ruffle is enabled on Vivaldi, mousing around the header causes some strange visual glitches across the webpage.

Here's a screen recording of it happening: https://files.drakinite.net/vivaldi_2023-04-27_22-54-41.mp4

if I disable Ruffle, close the tab, and re-open the tab, then the glitches disappear. I tested on Chrome, Firefox, and Edge and the issue only seems to appear on Vivaldi. 

### Expected behavior

Here's a recording of the interface when Ruffle is disabled: http://files.drakinite.net/vivaldi_2023-04-27_22-48-25.mp4

### Affected platform

Browser's extension

### Operating system

Windows 11, Windows 10, and Ubuntu 22.04

### Browser

Vivaldi

### Additional information

Since Nextcloud is a bit time consuming to set up, if a developer who's looking at this issue would like me to help you save time, send me an email and I can make an account for you on my personal instance.

**Comment by n0samu** [comment]
Have you verified that not only does disabling Ruffle stop the glitch, but also that re-enabling Ruffle and reloading the page immediately makes the glitch reappear?

**Comment by JL102** [comment]
> Have you verified that not only does disabling Ruffle stop the glitch, but also that re-enabling Ruffle and reloading the page immediately makes the glitch reappear?

Yes. Actually, the glitch immediately appears when enabling ruffle.

To "enable" the glitch:
1. enable Ruffle
2. Switch tabs back to an open Nextcloud tab

To "disable" the glitch:
1. Disable Ruffle
2. Completely close the Nextcloud tab
3. Open a new Nextcloud tab

**Comment by n0samu** [comment]
Okay, thanks for confirming. I don't think there's a real chance that I could diagnose this problem, even with the right environment to test it, so I'll leave it at that for now.

**Comment by JL102** [comment]
Hey, update: The visual glitch actually DOES appear sometimes when Ruffle is disabled and/or uninstalled. Gonna close this issue and I'll try and figure out how to reproduce it, then submit a bug report with Vivaldi.
