### ISSUE TITLE
Help  Linux firefox addon

### ISSUE THREAD

**Issue by mesflit** [ruffle-rs/ruffle#10854]
### Describe the bug

I downloaded the plugin.
I downloaded the swf file. How do I run it offline. It doesn't work when I run the swf file with firefox

### Expected behavior

I downloaded the swf file. How do I run it offline. It doesn't work when I run the swf file with firefox

### Affected platform

Browser's extension

### Operating system

Debian Sid arm64

### Browser

Firefox

**Comment by n0samu** [comment]
The Ruffle browser extension is intended for running Flash content on webpages, not for running local SWF files. To run SWF files, you should use the desktop app or the [Web Demo](https://ruffle.rs/demo/) instead.
