### ISSUE TITLE
slider regression

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#10872]
### Describe the bug

https://user-images.githubusercontent.com/98996990/235295422-1f9d405a-9b8d-4872-bfd4-db0d721e76cc.mp4

[flash5770.zip](https://github.com/ruffle-rs/ruffle/files/11358789/flash5770.zip)

### Expected behavior

https://user-images.githubusercontent.com/98996990/235295427-2d3dcf1c-edb7-430d-a6d0-f921cda7b2ab.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Chrome 112.0.5615.138

**Comment by relrelb** [comment]
Regressed by #10855, and will be fixed by #10866.
