### ISSUE TITLE
Learn to Fly 3 - game is broken after second start

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#10888]
### Describe the bug

After the second start game is broken. Error:

``
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x21b2da56c68 }) to handler FunctionObject(FunctionObject { ptr: 0x21b2d5467e8 }) : RustError("Error: Invalid object")
``

SWF - https://data.gameflare.com/games/6897/qOzPxl4TTIqgMm.swf
URL - https://www.gameflare.com/online-game/learn-to-fly-3/

### Expected behavior

progress the game after clicking on New Game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
The invalid object error is `Error(Nom([], Eof))`

**Comment by Dinnerbone** [comment]
This tries to send Flash Remoting packets with #13856 but is hit by CORS

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://lbgserver.com/amfphp/amfphp-2.2/Amfphp/. (Reason: CORS request did not succeed). Status code: (null).
> Couldn't submit AMF Packet to https://lbgserver.com/amfphp/amfphp-2.2/Amfphp/: FetchError("Got JS error")

**Comment by MartySVK** [comment]
no more issues 🥳
