### ISSUE TITLE
Min hero tower of sages is broken.

### ISSUE THREAD

**Issue by jman1593** [ruffle-rs/ruffle#10893]
When I try to use min hero tower of sages with ruffle, it pauses  randomly, doesn't show all of the text, and doesn't work after level one.

**Comment by Lord-McSweeney** [comment]
SWF available at https://data.gameflare.com/games/4137/fyKhzYWcdGNGB1.swf

**Comment by jman1593** [comment]
What about the not working after level 1?

**Comment by jman1593** [comment]
what's causing the poor performance? is there a way fix it?

**Comment by n0samu** [comment]
What do you mean when you say it doesn't work after level 1? I was able to get into the second battle, although I keep losing, lol. Another problem I noticed is that I can keep upgrading my minions even when I don't have any points left to spend, making my number of points become negative.
![image](https://user-images.githubusercontent.com/71368227/235380023-937e1e0f-b320-48cf-9c3b-a17e7408252a.png)

**Comment by jman1593** [comment]
ok, thank you. Is there any way to fix how slow it is, or fixing the points?

**Comment by n0samu** [comment]
You can try to download the SWF file and play it with the Adobe Flash projector instead: http://web.archive.org/web/20220401020702/https://www.adobe.com/support/flashplayer/debug_downloads.html

**Comment by jman1593** [comment]
ok. Also, by level I mean until you get the green seal.

**Comment by jman1593** [comment]
Also, I was hoping to add this to my game website, so is there any way to make an emulator work with an html file, like embedded, or something like that? Also, if yes, what emulator?

**Comment by n0samu** [comment]
You can check out my article https://nosamu.medium.com/flash-player-emulators-how-to-play-swfs-in-2021-and-beyond-d56c3899b7e6

Anyway this is getting a little off-topic, you might want to go to the Discussions tab and open a discussion instead

**Comment by jman1593** [comment]
ok.
