### ISSUE TITLE
How to use awayfl?

### ISSUE THREAD

**Issue by jman1593** [ruffle-rs/ruffle#10897]
I was wondering how to use awayfl player embed. I have been trying to find a video and trying to figure it out for the past hour, and I can't find anything.

**Comment by Lord-McSweeney** [comment]
Please report issues to awayfl, or ask on Ruffle's discord (https://discord.gg/ruffle) instead of using Ruffle's issue tracker for this.

**Comment by n0samu** [comment]
Not Ruffle-related, please ask in the AwayFL Discord or something
