### ISSUE TITLE
Running content from URL in the desktop app

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1093]
The official Flash projector includes the ability to open SWFs from an internet location instead of locally, which allows for testing to be done without having a certain SWF downloaded prior and also enables projects like Flashpoint to not have to rely solely on a browser to display Flash content from its simulated internet servers. Adding a feature to run internet content in the desktop version of Ruffle would be a monumental step towards making it easier to test games and therefore find more bugs to squash (especially if it can be made to work in FP).

**Comment by Herschel** [comment]
This is needed for whenever a local SWF makes network requests, too (i.e. loadVars with a local SWF set to the network sandbox). We can use [reqwest](https://github.com/seanmonstar/reqwest).

**Comment by Herschel** [comment]
Closed via #1259.
