### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by mari-does-not-dream-of-mental-stability** [ruffle-rs/ruffle#10955]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 39032 but the index is 39032', core/src/bitmap/bitmap_data.rs:604:9
Error stack:
```
339/O/n.wbg.__wbg_new_15d3966e9981a196@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.7d3ff466cfbd971981de.js:1:48914
core::ops::function::FnOnce::call_once{{vtable.shim}}::hd28f65a61f685e47@:wasm-function[8418]:0x811c6f
std::panicking::rust_panic_with_hook::h7f7102b82d51338f@:wasm-function[5512]:0x733897
core::panicking::panic_fmt::he4489d678d6570d5@:wasm-function[8271]:0x80c4b5
core::panicking::panic_bounds_check::h1213b10c1e002d73@:wasm-function[6633]:0x78d676
ruffle_core::bitmap::operations::copy_on_cpu::ha57d1f647286244e@:wasm-function[779]:0x2aafb6
ruffle_core::bitmap::operations::copy_pixels::hd834677fae0a78bc@:wasm-function[4235]:0x6c51e8
ruffle_core::avm2::globals::flash::display::bitmap_data::copy_pixels::h1320c5f91c02c9a2@:wasm-function[727]:0x28311e
ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce@:wasm-function[780]:0x2ab7ae
ruffle_core::avm2::object::TObject::call_property::hbef9b7a23152cbbb@:wasm-function[1116]:0x386444
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h1ff9616f1a2d6ab7@:wasm-function[2665]:0x5a55a9
ruffle_core::avm2::activation::Activation::run_actions::h8ac32777c1f985d5@:wasm-function[494]:0x2880d
ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce@:wasm-function[780]:0x2accb4
ruffle_core::avm2::object::TObject::call_property::hfa2ab3f33ae33aa2@:wasm-function[1084]:0x377981
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h1ff9616f1a2d6ab7@:wasm-function[2665]:0x5a54cc
ruffle_core::avm2::activation::Activation::run_actions::h8ac32777c1f985d5@:wasm-function[494]:0x2880d
ruffle_core::avm2::function::Executable::exec::hb5981ebd76854dce@:wasm-function[780]:0x2accb4
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h6f0d2770d8d43363@:wasm-function[968]:0x33d1b2
ruffle_core::avm2::events::dispatch_event_to_target::h29c4576f472cb6d9@:wasm-function[818]:0x2d840c
ruffle_core::avm2::events::dispatch_event::h4f613c83b5ffdf89@:wasm-function[1059]:0x36b99b
ruffle_core::avm2::Avm2::broadcast_event::hb1e91ebb3c093986@:wasm-function[732]:0x288d65
<ruffle_core::display_object::stage::Stage as ruffle_core::display_object::TDisplayObject>::enter_frame::h30084f9445d920e9@:wasm-function[4564]:0x6e399f
ruffle_web::Ruffle::tick::h3ce578a805835bf7@:wasm-function[721]:0x27894b
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::hbe145fe6518da68c@:wasm-function[10131]:0x8536f9
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hbde675465be1b1f1@:wasm-function[9000]:0x82967a
A@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.7d3ff466cfbd971981de.js:1:2600
f@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.7d3ff466cfbd971981de.js:1:2277

```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::copyPixels()
    at Game/drawGame()
    at Game/loop()
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1683287747%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F661000%2F661412_dontescape3.swf%3F1551187149%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264556d1c06230%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A720%2C%22height%22%3A540%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F661000%2Fflash_661412_card.png%3Ff1601072036%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/661000/661412_dontescape3.swf?1551187149

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-05
Channel: nightly
Built: 2023-05-05T00:22:42.542Z
Commit: 58d786b8694d46fd12a10418604968d067ac7684
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 2
swfVersion: 22
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 11988533

**Comment by Lord-McSweeney** [comment]
See also #10954. This is a regression, most likely due to #10908.

**Comment by n0samu** [comment]
Actually I've now bisected this to commit 50a0298d3081e3a23c8b1b7c21bc3f8e89e6fb36 from #10583.

**Comment by n0samu** [comment]
Game is Don't Escape 3: https://www.newgrounds.com/portal/view/661412

**Comment by n0samu** [comment]
I just found an additional regression caused by an earlier commit (adabb81804c043b80f3de1247c2bb1ceca848ea5) of #10583. So the first commit of the PR messed up the rendering of some graphical effects, and the later commit caused the crash to start occurring. To illustrate the problem adabb81804c043b80f3de1247c2bb1ceca848ea5 caused, here are videos to compare:

**Before** (correct):

https://github.com/ruffle-rs/ruffle/assets/71368227/74ba5a4e-f445-4d80-a1e8-767ae1eec5e2

**After** (wrong):

https://github.com/ruffle-rs/ruffle/assets/71368227/f7bf5bf4-a8c9-4744-9776-13e20432c1c9
