### ISSUE TITLE
Popstar - Cannot click anything in the menu

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10974]
### Describe the bug

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/popstarnew.swf - Dunno what causes the error but I'm unable to click anything in the menu

### Expected behavior

click & run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
I expected that this was some problem related to MochiCrypt, but after decrypting the game, the problem persists. This reminds me of #10600, but I have no idea what causes either issue.

**Comment by desertking** [comment]
Same as with Dead Zed 2 the play button seems to work now as the game..

**Comment by n0samu** [comment]
Fixed by #10992
