### ISSUE TITLE
Forty Thieves Solitaire - Click on the buttons does nothing

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10975]
### Describe the bug

https://www.spiele-umsonst.de/azad/downloads/flashgames/fortythievessolitaire.swf - If you click play game in the menu or something else nothing happens, maybe has to do with the errors it throws?

core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "mouseUp", class: flash.events::MouseEvent, ptr: 0x103a8d4 }) to handler FunctionObject(FunctionObject { ptr: 0x3a63904 }) : ReferenceError: Error #1069: Property getLineText not found on flash.text.TextField and there is no default value.

### Expected behavior

Do something onclick...

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by desertking** [comment]
It progressed. You can click it and you can't click it again now. Before that you could endlessly push it. Any timetabel when this may work again. Waiting for it :)

**Comment by n0samu** [comment]
The game needs a functional implementation (or more functional stub) of getLineText for the game to work. Here is the relevant code in `com.glowingeyegames.elements.GEGButton`:
```as
		public function get label() : String {
			var st:Array = new Array();
			for(var i:int = 0; i < this._button.txt_label.numLines; i++) {
				st.push(this._button.txt_label.getLineText(i).replace(/^\s+|\s+$/g,""));
			}
			return st.join("||");
		}
		private function onClick(e:MouseEvent) : void {
			if(!this.disabled) {
				e.target.dispatchEvent(new EventController(EventController.GAMEEVENT,this.label));
				if(this._disableAfterClick) {
					this.disabled = true;
				}
				GameMaster.clip.dispatchEvent(new EventController(EventController.GAMEEVENT,"sndButtonClick"));
			}
		}
```
Since the current getLineText stub always returns an empty string, the `label` property of the button is incorrect, the event is dispatched with an empty name, and the proper response does not happen.
