### ISSUE TITLE
Super Race - menu not showing

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#10983]
### Describe the bug

Game appears to load, but you cannot see the menu nor select any options. Music is playing in the background.

http://www.freeworldgroup.com/games6/gameindex/superrace.htm

Web based version of RUFFLE. 

### Expected behavior

Menu should show and should have ability to select options to start playing game. 

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Chrome

**Comment by n0samu** [comment]
Related to SharedObject serialization:
```
WARN run_frame:run_all_phases_avm2: ruffle_core::avm2::amf: Serialization is not implemented for class other than Object: ScriptObject(ScriptObject { name: FWG::PlayerInfo, ptr: 0x1a0dacb4bb8 })
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Got "RustError("Error: Invalid object")" when constructing AVM2 side of movie clip of type FWG::Main
```

**Comment by freeworldgroup** [comment]
game now loads well, but none of the buttons work to control super hero when flying.

**Comment by freeworldgroup** [comment]
working fine now
