### ISSUE TITLE
Broken toys from abowman.com

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1098]
http://abowman.com/ has some neat toys that don't work well with Ruffle.

**Minor issues:**

http://cdn.abowman.com/widgets/fish/fish.swf
http://cdn.abowman.com/widgets/spider/spider.swf
http://cdn.abowman.com/widgets/treefrog/treefrog.swf
"ABOWMAN" watermark displays incorrectly

**Major issues:**

http://cdn.abowman.com/widgets/ballclock/ballclock.swf
Launches to white screen with error
`[2020-09-03T05:46:28Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("Test") })`

http://cdn.abowman.com/widgets/discdrop/discDrop.swf
Launches to white screen with error
`[2020-09-03T05:47:07Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("AbstractItem") })`

http://cdn.abowman.com/widgets/dog/dog.swf
Launches to white screen with no error

~~http://cdn.abowman.com/widgets/hamster/hamster.swf
spinning bar and mounting button inside hamster wheel are missing~~

http://cdn.abowman.com/widgets/pendulumclock/pendulumClockV2.swf
~~Numbers, hands, and watermark don't display~~
Waterrmark displays in incorrect font

http://cdn.abowman.com/widgets/penguins/penguins.swf
Penguins, "ABOWMAN" watermark display incorrectly

http://cdn.abowman.com/widgets/stingray/stingray.swf
"ABOWMAN" watermark displays incorrectly, stingray doesn't appear, error spammed in console
`[2020-09-03T06:04:20Z ERROR ruffle_core::library] Tried to instantiate non-registered character ID 0`

http://cdn.abowman.com/widgets/turtles/turtle.swf
Launches to white screen with error
`[2020-09-03T06:06:24Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("Font") })`

All of these were tested in the latest debug desktop app.

**Comment by davidar** [comment]
The ones that completely fail to load seem to use AS3 #1368 

#1483 fixes the watermarks, and some of the issues with the penguins

**Comment by davidar** [comment]
Now that my PRs have been merged, all the non-AS3 widgets should be rendering properly, so I guess this issue can be closed in favour of #1368?

**Comment by Herschel** [comment]
Fixed by #1483.
