### ISSUE TITLE
Actionscript 2's loadMovie in Ruffles load the document's color of the swf loaded while the actual Flash player never do :D

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#1100]
The original Flash Player load the contents in the *.swf (pictures/sounds/etc) but NOT the document color of the loaded swf.

But it does in ruffles.
Does that matters in the long run ?
No.

Just some consistency stuff to take note.

And here's another one, once unloadMovie() is called, the contents in the loaded *.swf is gone (good) but...here's the crazy thing...the loaded swf's document background color which would have never been loaded in the Original Flash player stays in ruffles ;p

Now the second one is pretty deadly because it calls into question just how "unloaded" is unloadMovie() in ruffles (memory leak issues in the long run ?) since the loaded *.swf's background color is now "cursed" unto the host's document background color without permission which would have never happen in the official Flash player in the first place because the loaded swf's background color would have never been loaded.

**Comment by BracerJack** [comment]
[LoadMovie bgcolor issue.zip](https://github.com/ruffle-rs/ruffle/files/5168770/LoadMovie.bgcolor.issue.zip)
Here is a small example using an asset from my game to show the bug :D

**Comment by Herschel** [comment]
Need to ignore SetBackgroundColor tag if it's not the root level 0 movie.

**Comment by BracerJack** [comment]
Yeah !

**Comment by relrelb** [comment]
I believe the solution is as simple as:
```diff
diff --git a/core/src/display_object/movie_clip.rs b/core/src/display_object/movie_clip.rs
index 0201e0d1..75e346e3 100644
--- a/core/src/display_object/movie_clip.rs
+++ b/core/src/display_object/movie_clip.rs
@@ -2930,7 +2930,10 @@ impl<'gc, 'a> MovieClip<'gc> {
         context: &mut UpdateContext<'_, 'gc, '_>,
         reader: &mut SwfStream<&'a [u8]>,
     ) -> DecodeResult {
-        *context.background_color = reader.read_rgb()?;
+        let background_color = reader.read_rgb()?;
+        if self.parent().is_none() {
+            *context.background_color = background_color;
+        }
         Ok(())
     }
```

**Comment by BracerJack** [comment]
Hope this gets committed into core :D
Thanks relrelb.

**Comment by moulins** [comment]
I've tested @relrelb's patch on the test case in #2133, and it fixes the issue.

Is there anything else that would preclude this patch from being merged on `master`?

**Comment by BracerJack** [comment]
Yeah I am just as curious as well, this bug has been there for months now along with a fix that already exist.

**Comment by Herschel** [comment]
It only needs someone to make a PR :-)
