### ISSUE TITLE
Error on https://ero.e7c.net/adlink/t103102/

### ISSUE THREAD

**Issue by teitoharu** [ruffle-rs/ruffle#11008]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: false

# Page Info
Page URL: https://ero.e7c.net/adlink/t103102/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-11
Channel: nightly
Built: 2021-11-11T00:14:36.131Z
Commit: 60eb88b3265601d16467672a732081b30884707d
Is extension: false

**Comment by Lord-McSweeney** [comment]
Closing because of old Ruffle version and undescriptive error report (this could just be a connection problem).

**Comment by n0samu** [comment]
Looks like a server error, not a Ruffle issue
