### ISSUE TITLE
Is there any way to use the desktop version with OpenGL

### ISSUE THREAD

**Issue by camthesaxman** [ruffle-rs/ruffle#11018]
I just built ruffle from source, but when I try to run it, I get an error.
```
Error: Couldn't create wgpu rendering backend

Caused by:
    Ruffle requires hardware acceleration, but no compatible graphics device was found supporting Vulkan, DirectX 12, DirectX 11, Metal or Web GPU
```
I don't have any recent hardware that supports Vulkan, so I'd like to run this with OpenGL. This same PC is able to run the web version of Ruffle here (https://ruffle.rs/demo/) with no issues, but I'd like to run it standalone for better performance and without a web browser.

**Comment by iwannabethedev** [comment]
I am not certain, but, I think you can pass in a desired graphics/renderer backend.

If you run the desktop application from a command line, you might be able to pass in the flag `--help`. That should give a list of configuration options. If you then instead pass in `-g gl`, I would guess that Ruffle would try to use OpenGL as its graphics/renderer backend. Does that work for you?

You can also ask in the Discord.

I wonder if it would be nice for the desktop application to have some way of configuring these values without passing in command-line values, like for users (maybe there already is such a way and I am merely ignorant of that way).

**Comment by camthesaxman** [comment]
Thanks, that worked! I didn't see a listing of the command-line options on GitHub or the ruffle.rs site, and I didn't think to pass in `--help` to check, but it runs now.

**Comment by Lord-McSweeney** [comment]
Note that colors are currently a little broken on the OpenGL backend on Linux (see #10750).
