### ISSUE TITLE
Add FLV support (there is a pull request for it)

### ISSUE THREAD

**Issue by TemaisgameNoobas** [ruffle-rs/ruffle#11025]
Hello. I have an SWF file from a website. The website is Neave.TV (2006 version) and sadly, the main purpose of it is video. Everything there is FLV, and I could not play videos from it. Everything works fine expect video playback.
The PR:  #10756 

I have all files from it to get it working.

The files: [neavefiles.zip](https://github.com/ruffle-rs/ruffle/files/11466741/neavefiles.zip)
(I will convert that MP4 video to FLV, or as I remember it can already play MP4 videos)

**Comment by n0samu** [comment]
Can you add a comment to #723 instead? And if you want to attach an example, please attach one that matches your request. Here you asked for FLV decoding but attached a sample with an MP4 video (I don't understand why)
