### ISSUE TITLE
Error on https://www.mostfungames.com/beat-up-your-pc.htm

### ISSUE THREAD

**Issue by deadhead75** [ruffle-rs/ruffle#11022]
# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: expected a module of at least 8 bytes

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.mostfungames.com/beat-up-your-pc.htm

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Lord-McSweeney** [comment]
Closing as invalid because of old Ruffle version and undescriptive error (seems like an empty WASM file).
