### ISSUE TITLE
will strike force heroes 2 be playable

### ISSUE THREAD

**Issue by UMBreomn** [ruffle-rs/ruffle#11020]
i want to feel nostalgia again

**Comment by iwannabethedev** [comment]
Can you described the issue(s) you encounter when trying to play that game?

**Comment by UMBreomn** [comment]
nvm

**Comment by UMBreomn** [comment]
but i got quiston how do you get better performence

**Comment by UMBreomn** [comment]
nvm it give you a grey screen after a match

**Comment by UMBreomn** [comment]
blank grey screen
