### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by steer12** [ruffle-rs/ruffle#11042]
# Error Info
Error name: Error
Error message: Ruffle is panicking!
Error stack:
```
Error: Ruffle is panicking!
    at Ye.load (https://ruffle.rs/demo/index.js:1:88159)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-A326K/KSS4DWC5) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/20.0 Chrome/106.0.5249.126 Mobile Safari/537.36
Platform: Linux aarch64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-13
Channel: nightly
Built: 2023-05-13T00:19:15.756Z
Commit: a023e11098d9f4dc1fe4a8c6768d7e3c47140dc8
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Ruffle cannot load SWFs while panicking.
