### ISSUE TITLE
Gibbets 4: Illegal write to read-only property builtInItems on flash.ui.ContextMenu

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#11053]
### Describe the bug

The game is stuck on loading with the error:

``
ERROR ruffle_core::display_object::movie_clip: Got "ReferenceError: Error #1074: Illegal write to read-only property builtInItems on flash.ui.ContextMenu." when constructing AVM2 side of movie clip of type Main::CurrentStateManager
``

SWF - https://data.gameflare.com/games/5092/x6HtXDrXIxUZ7r.swf
Game - https://www.gameflare.com/online-game/gibbets-4/

**Gibbets: Santa in Trouble** and **Gibbets 3** have the same problem

### Expected behavior

progress loading

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by 0xSharkyy** [comment]
this might be an issue with the games .swf file

**Comment by Aaron1011** [comment]
We just need to define a setter for `builtInItems`
