### ISSUE TITLE
Ruffle extension failed to load one of my favorite flash games.

### ISSUE THREAD

**Issue by KrzysztofoGuard** [ruffle-rs/ruffle#11051]
On this page | https://supermariobros.online/super-goblin-war-machine | The Ruffle extension cannot run one of my favorite flash games and shows a black screen. I am asking the Ruffle team to look into this issue and bringing this game to life.

**Comment by Lord-McSweeney** [comment]
This is due to unimplemented `SharedObject.setProperty()`.

**Comment by n0samu** [comment]
The game appears to work now, but it is very slow. Tested via [Flashpoint's testing site](https://ooooooooo.ooo/static/?68dad594-9523-4afb-846d-873a7c821125) since the original link is dead.
