### ISSUE TITLE
Intrusion 2 Demo - game freezes

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11063]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/33004628-e38d-4dfe-b970-fdf4dd4b1c41

### Expected behavior

game shouldn't freeze

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 113.0.5672.93

**Comment by Lord-McSweeney** [comment]
Closing in favor of #9623.
