### ISSUE TITLE
one step back - character falls through the ground

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11081]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/50616435-46c1-46ff-8a5c-da06bd85603f

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/8401ce2d-5a58-475f-9804-c234c79a3be2

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[544158_TimeBender2.zip](https://github.com/ruffle-rs/ruffle/files/11493156/544158_TimeBender2.zip)

**Comment by Lord-McSweeney** [comment]
(note: not a regression)
