### ISSUE TITLE
Buttons are sometimes difficult to click after a goto

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1108]
Imagine this frame sequence:
Frame 1: Button placed with rollOver/release handlers
Frame 2: Empty frame with no button, with gotoAndPlay(1) code

If the user hovers over the button, when the button is destroyed and recreated by the goto, Flash does not fire the rollover event a second time. The button remains clickable in its hover state.

However, a movie clip will act more as expected: it will fire its rollover event a second time as it gets recreated. It is also difficult to click (have to click and release faster than the movie framerate).

In Ruffle, buttons act like the movie clip case, becoming unclickable and firing their events twice. Some research is needed because I'm unsure of the exact Flash behavior -- the button should indeed get recreated, because if you put an MC with actions inside the button, those actions run twice as the button and MC get recreated. But I'm not sure how Flash decides not to fire the rollover events a second time.

The play button in Supersoldier (https://www.newgrounds.com/portal/view/284305) is very unresponsive because of this (cc #177). You can sometimes click it by mashing very quickly.

Minimal sample, with both an MC and a button:
[button-recreate.zip](https://github.com/ruffle-rs/ruffle/files/5172211/button-recreate.zip)

**Comment by michiel2005** [comment]
We are currently recreating the button with the run_goto() in display object -> movie_clip.rs.
But we're not saving the state of the button before the goto. instead we create the button again like it is totally new. I am pretty sure that when we save the button state it is currently in, like clicked. And then recreate the button with that state. it will work.
Since OverDownToOverUp for example does not get called because the button is not in it's clicked state anymore after one goto has passed.

**Comment by n0samu** [comment]
This bug also makes it extremely difficult to click the "Start" button in *Courage the Cowardly Dog: Nightmare Vacation*. (Pressing the spacebar to start the game works fine, at least.)
This is a multiasset game, so the easiest way to test it is to load it via the SWF URL in the Ruffle extension: https://www.getgames.io/games/swf/courage-the-cowardly-dog-nightmare-vacantion/game.swf

**Comment by Toad06** [comment]
Here are [some samples](https://github.com/ruffle-rs/ruffle/files/11415130/_samples.zip) (edited with JPEXS) based on the file available in #4402. Epilepsy warning.

---

fileA (rollOver triggered once):
- frame 1: PlaceObject2 button
- frame 3: RemoveObject2 button + gotoAndPlay(1)

---

fileB (rollOver triggered as long as the mouse hovers the button):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button
- frame 3: gotoAndPlay(1)

---

fileC (rollOver triggered once):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button + PlaceObject2 button (same characteristics as the button in frame 1)
- frame 3: RemoveObject2 button + gotoAndPlay(1)

---

fileD (rollOver triggered as long as the mouse hovers the button):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button + PlaceObject2 button (different matrix)
- frame 3: RemoveObject2 button + gotoAndPlay(1)

---

fileE (rollOver triggered once):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button + PlaceObject2 button (different name)
- frame 3: RemoveObject2 button + gotoAndPlay(1)

---

fileF (rollOver triggered as long as the mouse hovers the button):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button + PlaceObject2 button (different depth - 172)
- frame 3: RemoveObject2 button (depth 172) + gotoAndPlay(1)

---

fileG (rollOver triggered as long as the mouse hovers the button):
- frame 1: PlaceObject2 button
- frame 2: RemoveObject2 button + PlaceObject2 button (different depth - 172)
- frame 3: gotoAndPlay(1)

---

fileZ (rollOver triggered once - also works in Ruffle):
- frame 1: PlaceObject2 button
- frame 3: gotoAndPlay(1)

**Comment by n0samu** [comment]
Fixed by #10862 🎉
