### ISSUE TITLE
Cocolani

### ISSUE THREAD

**Issue by cmdocmd** [ruffle-rs/ruffle#11094]
### Describe the bug

![image](https://github.com/ruffle-rs/ruffle/assets/55096480/4daa51d7-1b30-4367-ab30-92a81b026a90)

### Expected behavior

the swf file should work probably

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome

### Additional information

You can test it with this link
https://safariislandsgame.com/play/

**Comment by n0samu** [comment]
The game is Cocolani, can you change the issue title to mention the name of the game please?

**Comment by cmdocmd** [comment]
I can see that this issue doesn't appear anymore so closing the issue
