### ISSUE TITLE
FPA World 2 and World 3 standalone PC builds boot but freeze with graphical issues (patreon only)

### ISSUE THREAD

**Issue by Adamillo** [ruffle-rs/ruffle#11108]
### Describe the bug

There's are special standalone PC builds of FPA World 1, World 2 and World 3 that are only avaiable via patreon. FPA World 2 and 3 boot but freezes with graphical issues. Here's how it looks like. EPILEPSY WARNING btw

https://github.com/ruffle-rs/ruffle/assets/45568316/d54ce6b9-47f9-4ce3-989b-1ab950e75d5f

https://github.com/ruffle-rs/ruffle/assets/45568316/0edcb7d5-796e-47f4-8ca7-f03cd62e1cfa

Here's a video of me booting up the games directly instead of the SFPA swf. For an explanation on what's happening, look in issue #11107

https://github.com/ruffle-rs/ruffle/assets/45568316/841989db-417d-49d2-a7c8-77dbb7f797d1

### Expected behavior

The games should boot up just fine instead of freezing with graphical issues

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Without access to the files we probably won't be able to do anything. You can hope it gets fixed by something else I guess

**Comment by Adamillo** [comment]
> Without access to the files we probably won't be able to do anything. You can hope it gets fixed by something else I guess

It is easily accessible when you are a patron in Brad Bornes Patreon page, it costs like 2$ per month, which is pretty cheap

**Comment by Adamillo** [comment]
Fixed by #11005, it boots further but has different issues now
