### ISSUE TITLE
HitTest issues on very large shapes

### ISSUE THREAD

**Issue by vicbiss** [ruffle-rs/ruffle#11127]
### Describe the bug

HitTest collision is offset or not accurate in one level where the ground movieclip is very large. This is on level 13, I've included an swf with all levels unlocked
[Pendulum.zip](https://github.com/ruffle-rs/ruffle/files/11518288/Pendulum.zip)

### Expected behavior

There is a level in one of my games that has a shape that is 10500 px wide. I realize this large of a shape is bad practice, but hitTests and the game work fine in flash, and they were working in Ruffle as of around a week or so ago. The game uses hitTest for collision, but now the collision in the level seems to be offset, I'm assuming this is an issue with the massive size of the shape.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by Lord-McSweeney** [comment]
I believe this issue is due to Twips overflowing, see for example #11077.

**Comment by iwannabethedev** [comment]
@vicbiss Could you post a video of how to reproduce the bug? Level 13 is a bit difficult.

**Comment by iwannabethedev** [comment]
I could complete level 13, and I do not understand what the bug is in this case. Could you explain further?

**Comment by iwannabethedev** [comment]
Which version of Ruffle are you using?

**Comment by n0samu** [comment]
@vicbiss I think this bug has already been fixed (just like #11077) so please test the game in the latest version of Ruffle and let us know!
