### ISSUE TITLE
The mouse pointer position should frozen after right click.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#11130]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/75534590/498eea30-8766-4109-8802-ec5d26679582

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/75534590/57c6e6ab-8af5-437a-8a4c-9caaf7e6547f

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

http://eye.swfchan.com/flash.asp?id=5682&n=The+Maze.swf

Here's Html5 version can frozen after right click.
https://www.playscarymazegame.net/play-scary-maze-game/

**Comment by Toad06** [comment]
We probably need to add a `<div>` element between the canvas and the context menu, as a transparent overlay.
