### ISSUE TITLE
rendering wrong layer in front

### ISSUE THREAD

**Issue by Benman2785** [ruffle-rs/ruffle#11147]
### Describe the bug

good example here - the yellow circles are rendered infront of the main image - not behind it

https://youtu.be/_C1KEeFOqj4

https://hoffmeister.li/flash-games/ZzZ_AS3_Road_of_the_Dead_2.html

### Expected behavior

should be rendered as "shine" behind the logo

### Affected platform

Self-hosted version

### Operating system

Win11

### Browser

Opera

### Additional information

ruffle-nightly-2023_05_20-web-selfhosted

**Comment by n0samu** [comment]
@Benman2785 Please leave the speculation out of your issue, you got me so confused thinking that there was a version of The Last Stand with an NG logo. Please edit your issue to remove mention of that game and instead attach / link to the SWF where the issue with the NG logo actually occurs. Thanks

**Comment by n0samu** [comment]
Someone on Discord found an SWF to demonstrate the issue: https://clickjogos.netlify.app/jogos/games/bulletbill3.swf

**Comment by Benman2785** [comment]
sry for late answer and confusion - got a long week behind me and even have to work tomorrow and monday (which is a holiday here) :/

added the link to game with logo

**Comment by Kippykip** [comment]
Yes it looks like its supposed to blur the circles, but I don't think ruffle has the blur effect yet

**Comment by n0samu** [comment]
Blur filter is implemented now (though imperfectly) so this looks a little better. The animation also needs the glow filter though.

**Comment by waspennator** [comment]
Should be fixed by #11878

**Comment by Lord-McSweeney** [comment]
Fixed by #11878.
