### ISSUE TITLE
BlendMode.MULTIPLY does not handle alpha blending correctly

### ISSUE THREAD

**Issue by Aaron1011** [ruffle-rs/ruffle#11140]
I've created a test case demonstrating the bug: https://github.com/Aaron1011/ruffle/tree/blend-mode-multiply-bug

Under Ruffle, this renders a large black square. Under Flash Player, it renders a small red square.

**Comment by n0samu** [comment]
This was regressed by #9096 - before that the square was the correct size but an incorrect color.
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/36fcdb30-9660-4c18-b667-2c36500817ff)

And strangely enough, it rendered with the correct color before the initial blend mode implementation (#8262):
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/542f27c0-95e9-4612-bbf6-0808a00bac76)

So it seems like Flash is ignoring the blend mode completely. If I remove the "multiply" argument from the `draw()` call, the rendering in Flash is exactly the same.
