### ISSUE TITLE
Nambers: Visual glitch

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11161]
### Describe the bug

Link to SWF: https://static.arcadespot.com/wp-content/uploads/2015/10/nambers.swf

In [Nambers](https://arcadespot.com/game/nambers/), there is a visual glitch after selecting the numbers.

![nambers_ruffle_glitch](https://github.com/ruffle-rs/ruffle/assets/71368227/d31304c5-f6bf-4c4a-b5d8-f419c13ff34f)

### Expected behavior

Here is what it's supposed to look like.

![nambers_flashplayer_expected](https://github.com/ruffle-rs/ruffle/assets/71368227/73450337-718c-44b0-b05a-d3f23f9c8612)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Tested with #11080, which fixes previous issues with this game.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/ruffle-rs/ruffle/pull/11198
