### ISSUE TITLE
Ruffle Error on https://happyhopper.org/

### ISSUE THREAD

**Issue by GamerChild** [ruffle-rs/ruffle#11172]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://happyhopper.org/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by n0samu** [comment]
That looks like a transient server error unrelated to Ruffle. Is the site working for you now? (It works fine for me)

**Comment by GamerChild** [comment]
Yes it is, thank you!
________________________________
