### ISSUE TITLE
Black rectangles and `BlendMode::Multiply` bug.

### ISSUE THREAD

**Issue by iwannabethedev** [ruffle-rs/ruffle#11184]
(Creating an issue based on investigations in Discord).

Possibly relevant issues:
- #10455 
- #10884 
- #9304 

Possibly relevant PRs:
- #9096 (as I understand the comments at Discord , the commit before that PR gave a different gray error, and that PR gives the black rectangle error). The old comment `// Can't be trivial, 0 alpha is special case` might be relevant.

**Comment by Lord-McSweeney** [comment]
Possibly relevant: #11140

**Comment by iwannabethedev** [comment]
@Aaron1011 I created this issue from the Discord investigations that you and others did, to avoid it being forgotten about.

Does it look accurate? Anything missing? Would it make sense to link to the branch that you mentioned to help debug the specific issue that a user had?

**Comment by iwannabethedev** [comment]
CC @Dinnerbone .
