### ISSUE TITLE
briker 2 - game is unplayable

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11183]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/882e37f2-d183-47ce-a2b1-364c213dcc7d

[briker2.zip](https://github.com/ruffle-rs/ruffle/files/11538149/briker2.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/4cd73db7-ba66-41bf-ba73-89d67988914f

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
The error is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::globals::flash::display::movie_clip: Attempted to add frame scripts to non-MovieClip this!`

**Comment by n0samu** [comment]
This will be fixed by #11084.
