### ISSUE TITLE
Some Movies Play Without Sound

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1118]
There are some movies where everything works fine but the audio doesn't play. Here are the ones I've noted:

https://www.newgrounds.com/portal/view/585448/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/530899/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/539060/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/599214/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/560828/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/550770/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/526954/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/186371/format/flash?emulate=flash

**Comment by Dinnerbone** [comment]
Investigation results:

| ID | Reason |
| -- | ------ |
| [585448](https://www.newgrounds.com/portal/view/585448/format/flash?emulate=flash) | Needs Nellymoser - #5 |
| [530899](https://www.newgrounds.com/portal/view/530899/format/flash?emulate=flash) | "Missing stream for clip 0". Unsure. |
| [539060](https://www.newgrounds.com/portal/view/539060/format/flash?emulate=flash) | "Missing stream for clip 0". Unsure. |
| [599214](https://www.newgrounds.com/portal/view/599214/format/flash?emulate=flash) | "Missing stream for clip 0". Unsure. |
| [560828](https://www.newgrounds.com/portal/view/560828/format/flash?emulate=flash) | "Missing stream for clip 0". Unsure. |
| [550770](https://www.newgrounds.com/portal/view/550770/format/flash?emulate=flash) | "Missing stream for clip 0". File does contain unknown opcodes. |
| [526954](https://www.newgrounds.com/portal/view/526954/format/flash?emulate=flash) | "Missing stream for clip 0". Unsure. |
| [186371](https://www.newgrounds.com/portal/view/186371/format/flash?emulate=flash) | Needs Nellymoser - #5 |

**Comment by zanzlanz** [comment]
Guilherme Fernandes offered another SWF with mostly broken audio:
https://jogorodaaroda.com/wp-content/uploads/games/custom/R/roda-a-roda-jequiti.swf

**Comment by n0samu** [comment]
All of the sound issues mentioned here seem to be fixed.
