### ISSUE TITLE
Regressions in "Mini-putt 2" and "Luigi's Day"

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1120]
These games worked fine in the previous nightly build (2020-09-03) but you can no longer play them at all because some mouse actions are not detected.

In "Mini-putt 2", you cannot drop the ball.
https://www.newgrounds.com/portal/view/38598/

In "Luigi's Day", you cannot click the "Play" button.
https://www.newgrounds.com/portal/view/44505

**Comment by Dinnerbone** [comment]
Ran a bisect, issue is introduced in f2f70cc8820223e02a48086871bab7c5551ab865.

It's using the shape based hit testing now, which for some reason is less accurate here?

**Comment by Herschel** [comment]
Static text need to care about shapeflag hit test, too.
