### ISSUE TITLE
Nightflies: Cannot play levels

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11214]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/nightflies.swf

Trying to start a level in [Nightflies](http://www.notdoppler.com/nightflies.php) results in a blank white screen instead. The error is:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "level", class: flash.events::Event, ptr: 0x228b1e9e508 }) to handler FunctionObject(FunctionObject { ptr: 0x228b1d92bf8 }) : RustError("Adding a new attribute to XML object is not yet implemented: Multiname { ns: Multiple([Namespace(Private(\"\")), Namespace(Namespace(\"\")), Namespace(Namespace(\"http://adobe.com/AS3/2006/builtin\")), Namespace(Private(\"\")), Namespace(PackageInternal(\"\")), Namespace(Protected(\"ClassAllLevelsRoly\")), Namespace(StaticProtected(\"ClassAllLevelsRoly\")), Namespace(StaticProtected(\"Object\"))]), name: Some(\"fon\"), params: [], flags: MultinameFlags(ATTRIBUTE) } = Integer(1)")
```

### Expected behavior

The levels should be playable.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This is the same problem preventing buying upgrades in Age of War 2 (#9958)

**Comment by MartySVK** [comment]
The game is working with https://github.com/ruffle-rs/ruffle/pull/11242
