### ISSUE TITLE
Graphical glitches and flickering on New Super Mario Bros website

### ISSUE THREAD

**Issue by XXLuigiMario** [ruffle-rs/ruffle#1122]
![glitch](https://user-images.githubusercontent.com/7153662/92241856-34c96700-eebf-11ea-98fb-cb8832a9eb85.gif)

Navigate the different sections to see the results, they seem to differ depending on what was previously on-screen.

**Running on Flash:** https://youtu.be/EgyKDb_ZfeU
**Game file:** https://nul.sh/misc/nsmb/

**Comment by Toad06** [comment]
Seems to work now, I think this is fixed by #2174. Remains an issue where Mario and Koopa don't move when the file starts playing (I don't think this is supposed to happen?).

**Comment by XXLuigiMario** [comment]
> 
> 
> Seems to work now, I think this is fixed by #2174. Remains an issue where Mario and Koopa don't move when the file starts playing (I don't think this is supposed to happen?).

You're right, pretty much all graphical glitches are gone now 😄
I kind of suspected #2037 when I saw it talked about on the Discord.
And yeah, Mario and the enemies should move immediately upon loading the file, but they only do after switching tabs once.
Might open another issue for that. Another notable one is that when a new audio track begins it overlaps with the previous one, likely has to do with Sound#setVolume being unimplemented (#273).
