### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Oozaru341** [ruffle-rs/ruffle#11229]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
    at O.n.wbg.__wbg_new_87297f22973157c8 (https://ruffle.rs/demo/339.index.js:1:50933)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h843ca02ed8ea0379 (wasm://wasm/02c3a016:wasm-function[8623]:0x82f1bf)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/02c3a016:wasm-function[5615]:0x75209c)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/02c3a016:wasm-function[8472]:0x82a52c)
    at alloc::raw_vec::capacity_overflow::h743526e95bf6b28b (wasm://wasm/02c3a016:wasm-function[8239]:0x8243e0)
    at swf::read::decompress_swf::h00e40ca22d92ad53 (wasm://wasm/02c3a016:wasm-function[688]:0x20deae)
    at ruffle_load_data externref shim (wasm://wasm/02c3a016:wasm-function[9079]:0x8453b8)
    at L.load_data (https://ruffle.rs/demo/339.index.js:1:4269)
    at Ke.load (https://ruffle.rs/demo/index.js:2:205843)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-26
Channel: nightly
Built: 2023-05-26T00:19:45.397Z
Commit: 6d76e9669c54f7712ba4273d15e90f5683160955
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Asked on Discord, the file attempted to run was this one: https://cdn.discordapp.com/attachments/722872096002408529/1111771693862617118/drawthelineparking.swf
This file is corrupted (it looks like it was uploaded to a server in text mode instead of binary mode). Closing the issue as this wouldn't work in Flash Player either
