### ISSUE TITLE
Respecting MovieClip._lockroot

### ISSUE THREAD

**Issue by djmuted** [ruffle-rs/ruffle#1124]
Ruffle does not seem to respect _lockroot property. Adding support for this feature would solve various problems occurring in SWF preloaders.
Usage:
```
game_mc._lockroot = true;
```
`_lockroot` property specifies what `_root` refers to when a SWF file is loaded into a movie clip. The `_lockroot` property is undefined by default. You can set this property within the SWF file that is being loaded or in the handler that is loading the movie clip.

For example, suppose you have a document called Games.swf that lets a user choose a game to play, and loads the game (for example, Chess.swf) into the game_mc movie clip. You want to make sure that, if _root is used in Chess.swf, it still refers to _root in Chess.swf after being loaded into Games.swf.

**Comment by zeh** [comment]
@djmuted #1823 should fix this soon, when/if merged. In the meantime, do you have any live examples where `_lockroot` is used so we can test to make sure? I did add some tests that I believe are exhaustive, but I'd like to compare a "before and after" in a real world scenario to be sure.
