### ISSUE TITLE
Home Sheep Home 2 - text is misplaced and regression

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11248]
### Describe the bug

latest nightly build

https://github.com/ruffle-rs/ruffle/assets/98996990/26c19b89-90e5-4e34-9c70-06eec1a61fe7

nightly build 2023-05-26

https://github.com/ruffle-rs/ruffle/assets/98996990/d0b7ea25-1701-4098-a79a-da072898189d

### Expected behavior

![2](https://github.com/ruffle-rs/ruffle/assets/98996990/58c488af-d3de-4d92-b7aa-3912f072ce63)
![3](https://github.com/ruffle-rs/ruffle/assets/98996990/6239662c-a5c6-4e00-bff7-2630ec0e426c)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

nightly build 2023-03-12 seems to loads the game very quickly
is this some other regression

https://github.com/ruffle-rs/ruffle/assets/98996990/657e01e8-dfdc-4cfd-8c99-8b571dd269cd

**Comment by n0samu** [comment]
Can you please link to or attach the SWF file that you're testing?

**Comment by zjk261** [comment]
[homesheephome2lostinlondon.zip](https://github.com/ruffle-rs/ruffle/files/11583595/homesheephome2lostinlondon.zip)

**Comment by n0samu** [comment]
Hmm, that seems to be the same SWF that I'm unable to run because it quickly uses up all my RAM (#8416). I'm also running it via the desktop app on Windows 10.

**Comment by Lord-McSweeney** [comment]
Can confirm, but it uses enough memory and CPU that running it is unreliable (sometimes script timeouts, even with high timeout duration), so I can't bisect.

**Comment by zjk261** [comment]
game is now playable on latest nightly build
but text is still misplaced
![1](https://github.com/ruffle-rs/ruffle/assets/98996990/2b76992b-7e8b-4f76-acc4-3a2608cf3237)
![2](https://github.com/ruffle-rs/ruffle/assets/98996990/e71e869c-44ae-42d3-8af6-d62a31769e2e)

**Comment by Lord-McSweeney** [comment]
@zjk261 was the text originally misplaced before the PR that made it unplayable?

**Comment by zjk261** [comment]
yes

**Comment by Lord-McSweeney** [comment]
Regression has since been fixed
