### ISSUE TITLE
Crash on GiftClicker.swf

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11252]
### Describe what you were doing

Trying to run the game. This is the same game from #11239 - this is the error I get after merging in the upcoming PRs including #11245.

Link to SWF (for convenience): https://game285222.konggames.com/gamez/0028/5222/live/GiftClicker.swf

### What does the crash message say?

panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Error matching ShaderStages(NONE | FRAGMENT) shader requirements against the pipeline
    Location[1] is provided by the previous stage output but is not consumed as input by this stage.

', C:\Users\nosamu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.16.0\src\backend\direct.rs:3019:5

### Ruffle Version

0.1.0-nightly (32069e63f09bfa3eee4743fe591be0acdb861af3 2023-05-28)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Pro) [64-bit]

### Additional information

Filename: GiftClicker.swf

### AVM2 Callstack
```
	at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
	at starling.display.materials::StandardMaterial/drawTriangles()
	at starling.display.graphics::Graphic/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.display::Sprite/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.display::Sprite/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.display::Sprite/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.core::Starling/render()
	at starling.core::Starling/nextFrame()
	at starling.core::Starling/onEnterFrame()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD FirePro W5100"
Adapter Device Type: DiscreteGpu
Adapter Driver Name: "AMD proprietary driver"
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by Aaron1011** [comment]
See https://github.com/gfx-rs/wgpu/issues/3748

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/13379
