### ISSUE TITLE
Desktop: Right click did not reveal the Cursor

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#11255]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/75534590/6f9b925e-df38-486d-997b-db094988d1e9

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/75534590/9dffb2e7-4178-49d9-bb4b-4dd7ab156e7a

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[files (2).zip](https://github.com/ruffle-rs/ruffle/files/11584744/files.2.zip)

**Comment by Toad06** [comment]
The same thing occurs if you hover one of the items in the menu at the top. Dinnerbone in https://github.com/ruffle-rs/ruffle/pull/10426#issuecomment-1561857128 was aware of the issue:
> we'll have to store ruffle's preferred state and dance between that and egui's preferred state depending on where the mouse is
