### ISSUE TITLE
Incredibox V2: Stuck at loading.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#11264]
### Describe the bug

![ruffle_9GfIve2g0X](https://github.com/ruffle-rs/ruffle/assets/75534590/ae14c70c-9d14-4f6c-9f2e-1c665eddcf2b)

```
2023-05-29T09:58:46.641716Z ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x193433e74d8 }) to handler FunctionObject(FunctionObject { ptr: 0x19342a0c9f8 }) : TypeError: Error #1006: toUpperCase is not a function of class XMLList.
        at incredibox_fla::MainTimeline/initTexte()
        at index_fla::MainTimeline/ChargeSwfFini()
```
### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/75534590/ec82e681-64b9-4866-9e5b-81e743c8e609

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[www.incredibox.com.zip](https://github.com/ruffle-rs/ruffle/files/11591433/www.incredibox.com.zip)

Use: ruffle -Pcompo="" -ProotFolder=../app/ -PappFolder=v2/

**Comment by Lord-McSweeney** [comment]
Here's the code that causes that:
```
this.boxBtBonus.btBonus1.sonTexte = this.mainXML.bouton.bonusT1.text().toUpperCase();
this.boxBtBonus.btBonus1.sonTexte1 = this.mainXML.bouton.bonusT2.text().toUpperCase();
this.boxBtBonus.btBonus1.sonTexte2 = this.mainXML.bouton.bonusT3.text().split("NOM").join(this.appXML.pathBonus.swf[0].@name).toUpperCase();
this.boxBtBonus.btBonus2.sonTexte = this.mainXML.bouton.bonusT1.text().toUpperCase();
this.boxBtBonus.btBonus2.sonTexte1 = this.mainXML.bouton.bonusT2.text().toUpperCase();
this.boxBtBonus.btBonus2.sonTexte2 = this.mainXML.bouton.bonusT3.text().split("NOM").join(this.appXML.pathBonus.swf[1].@name).toUpperCase();
this.boxBtBonus.btBonus3.sonTexte = this.mainXML.bouton.bonusT1.text().toUpperCase();
this.boxBtBonus.btBonus3.sonTexte1 = this.mainXML.bouton.bonusT2.text().toUpperCase();
this.boxBtBonus.btBonus3.sonTexte2 = this.mainXML.bouton.bonusT3.text().split("NOM").join(this.appXML.pathBonus.swf[2].@name).toUpperCase();
```

**Comment by evilpie** [comment]
Any ideas how this is supposed to work? text() returning XMLList seems correct and when I tried `text().toUpperCase()` in a test SWF it also didn't work in Flash. I tried to look the P-code of function, but also didn't spot any kind of conversion that might have been invisible.

**Comment by Lord-McSweeney** [comment]
AFAIK that on single-element XMLLists, the method gets propagated to the first child of the XMLList. On XML elements with simple content, the method gets called to the text version of the simple content, and I would assume that that's what's happening here.
