### ISSUE TITLE
kingdom rush frontiers - can't enter the game on web demo

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11280]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/6cedaaee-d43e-41b0-b5ed-6025b37a4a76

### Expected behavior

clicking the save slot should start the game

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 113.0.5672.127

### Additional information

game is from flashpoint
game works in desktop app

**Comment by n0samu** [comment]
This happens because the SWF expects to be able to access ExternalInterface, but we don't have `allowScriptAccess` enabled in the web demo.
