### ISSUE TITLE
Ruffle Desktop Player GUI: Pauses while clicking on options

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11287]
### Describe the bug

Mentioned it on the discord, but also posting here for posterity, the new gui ruffle desktop player has is very nice, but it has a weird quirk where if you click on something like the settings in the advanced file picker without moving your mouse, it'll get stuck halfway through showing the options until I move my mouse, then it finishes up.

Easiest way to see it is to open up the advanced file picker and without moving your mouse, click on one of the options like network settings and notice it doesn't fully open up until you move your mouse a bit. The same also happens with the files, settings, and help buttons, but weirdly after it happens once, it fixes itself for them.

![Ruffle GUI](https://github.com/ruffle-rs/ruffle/assets/78768499/85c376e3-282e-44d2-bb89-17ce3bd5a136)

### Expected behavior

If I click on network settings for example, it should fully open up when I click on it and I shouldn't have to move my mouse to get it to fully open up.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by waspennator** [comment]
Tried out tonights latest nightly and the issue seems to have gone away.

**Comment by p0008874** [comment]
Nah, It still exist.
