### ISSUE TITLE
Portal: The Flash Version - Endless Beeping Sound

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1128]
In Portal: The Flash Version, after you click "New Game" on the title screen and click the follow-up "Start" button, it goes to a black screen that says "Launching project... Press any key to continue." In the Flash version there is no sound but in the Ruffle version, there's a looping beep sound. This sound continues endlessly as you play the game. Maybe something that was intended for a site-lock message that's failing?

https://www.newgrounds.com/portal/view/404612/format/flash?emulate=flash

**Comment by labbo-lab** [comment]
i've had this problem too :/ 
its extremly annoying

**Comment by Herschel** [comment]
Seems to be fixed in the latest Ruffle versions (I believe fixed by #2825).
