### ISSUE TITLE
Way to select specific renderer for Desktop Ruffle Build

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11286]
**Describe the feature**
Honestly would be nice if there could be an easy way to specify which renderer you'd want the desktop ruffle player to use for SWFS, like on windows you'd have access to DX12 or Vulkan, or Linux you'd have Vulkan or GLES.

**Comment by n0samu** [comment]
Of course you can select it via the `-g` command line argument, but I assume you're asking for a GUI feature? That would be hard because by the time Ruffle is rendering the GUI, it is in fact using a renderer. And you'd have to restart Ruffle to make it use a different one.

**Comment by waspennator** [comment]
Yeah, moreso talking about having it in the gui,  whether there's a pop up asking if you wanna restart ruffle to change renderer or a notice saying it'll change on next start up. It would be a good step in the right direction regardless if there could be a way to change it outside of the command line.

**Comment by waspennator** [comment]
Feature implemented by #15338
