### ISSUE TITLE
Minicraft flash edition isn't playable

### ISSUE THREAD

**Issue by swaggybaguette** [ruffle-rs/ruffle#11284]
### Describe the bug

The actual game doesn't start in ruffle, only the ZyBy.com intro plays then hangs on a black screen, title screen music plays though

### Expected behavior

I see the title screen and am able to proceed with the game 
![image](https://github.com/ruffle-rs/ruffle/assets/125625453/f354d7f5-38f1-42cb-bd5b-9303cca6981f)

### Affected platform

Online demo

### Operating system

Manjaro Linux, x86_64, Linux 6.1.25-1-MANJARO

### Browser

Librewolf 102.0.1

### Additional information

here is the swf http://files.catbox.moe/xo5lm1.swf

**Comment by n0samu** [comment]
With #10275, the menu displays correctly, but does not respond to any keyboard input. So the game still isn't playable, but you *can* click the sponsor logo 😆

**Comment by Lord-McSweeney** [comment]
Key input seems to be working now, but with high latency between pressing the key and the game actually responding to the input.

**Comment by n0samu** [comment]
Can confirm that the game is working fine now, but just extremely slow. You can get ingame with Ruffle's `--max-execution-duration` option bumped up a bit.
