### ISSUE TITLE
Neopets Loader Version 9 seems to present XML problem

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#11289]
[np9_loader_v12.zip](https://github.com/ruffle-rs/ruffle/files/11597633/np9_loader_v12.zip)
### Describe the bug

Games in Neopets that utilize version 9 of the nploader SWF seem to present Ruffle with an XML loading problem.

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0xced544 }) to handler FunctionObject(FunctionObject { ptr: 0xce28f4 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: childNodes)

This version mostly applies to those games that were last using ActionScript 3 such as:
Destruct-O-Match III -- https://www.neopets.com/games/game.phtml?game_id=999&size=regular&quality=high&play=true
Jungle Raiders -- https://www.neopets.com/games/game.phtml?game_id=1064&size=regular&quality=high&play=true
Wheeler's Wild Ride -- https://www.neopets.com/games/game.phtml?game_id=1080&size=regular&quality=high&play=true

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.neopets.com/games/play_flash.phtml?va=&game_id=999&nc_referer=&age=1&hiscore=&sp=0&questionSet=&r=6605273&&width=650&height=488&quality=high&inpage=1
SWF URL: https://images.neopets.com/games/gaming_system/np9_loader_v12.swf (will attach the game SWF if I can figure out how to find it).

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-05-30
Channel: nightly
Built: 2023-05-30T00:21:44.167Z
Commit: 8d6c08df4d10fb2f77511af3d605c61a5b94b7bc
Is extension: true

# Metadata
width: 640
height: 600
frameRate: 30
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 86902

### Expected behavior

Game should be able to load correctly.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Chromium Edge

**Comment by evilpie** [comment]
Is there some way to run this locally?

**Comment by sombraguerrero** [comment]
Not really, at least not to run them correctly. All of the Neopets games are coded to expect resources only accessible from within the site.

**Comment by Dinnerbone** [comment]
This is a bug in the XMLNode/XMLDocument legacy shim. It appears as though every "thing" separated by a newline, should correspond to an item in `childNodes`.

```actionscript
package  {
	
	import flash.display.MovieClip;
	import flash.xml.XMLDocument;
	
	
	public class Test extends MovieClip {
		public function Test() {
			dump(new XMLDocument('<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN" "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >\n<list><item>a</item><item>b</item></list>').childNodes);
			trace("---");
			dump(new XMLDocument('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN" "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" ><list><item>a</item><item>b</item></list>').childNodes);
		}
		
		function dump(children: Array) {
			trace("// children.length");
			trace(children.length);
			trace("");
			
			for (var i = 0; i < children.length; i++) {
				trace("// children[" + i + "]");
				trace(children[i]);
				trace("");
			}
		}
	}
}
```
```
// children.length
3

// children[0]



// children[1]



// children[2]
<list><item>a</item><item>b</item></list>

---
// children.length
1

// children[0]
<list><item>a</item><item>b</item></list>


```

**Comment by Dinnerbone** [comment]
... actually, thinking about it, no it's just picking up each \n newline as a text node. This big XML document that Neopets is loading is many textnodes and many actual XML elements, interwoven.
