### ISSUE TITLE
Portal: The Flash Version - Missing Tutorial Text

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1129]
In Portal: The Flash Version, when you begin the first level there is tutorial text that plays at the top of the screen. In Ruffle you can see the bottom edge of the box slide in but it never slides in completely. There's also key commands that slide in below it and those are missing in Ruffle as well.

https://www.newgrounds.com/portal/view/404612/format/flash?emulate=flash

**Comment by n0samu** [comment]
This seems to be fixed now
