### ISSUE TITLE
Electirc Box 2: Broken text boxes

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11303]
### Describe the bug

https://www.newgrounds.com/portal/view/548266?emulate=flash
Game seems to work alright for the first level, but i'm noticing a weird bug where the text boxes cannot be interacted with past level 1, starting from level 2 it seems to get stuck.

![Ruffle EB](https://github.com/ruffle-rs/ruffle/assets/78768499/438dcd28-abee-4405-b7db-9af999177568)

Also sometimes the game seems to have trouble loading, tossing this up in the logs.
Unhandled AVM2 error in timer callback: Error: flash.display.Loader.unload - not yet implemented

### Expected behavior

The text box in level 2 should be dismissable or be able to be clicked through.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 113

**Comment by Computerdude77** [comment]
It appears that the text box issue is now fixed as of the 2023-06-01 nightly. The loading bug still occurs.

**Comment by waspennator** [comment]
Tested it out again on my end, yeah, I can click through the text boxes on level 2 properly now.

**Comment by waspennator** [comment]
Tested it again a few more times and can't seem to trip the loading bug.

@Computerdude77 Could you retest it a few times on your end to make sure?

**Comment by Computerdude77** [comment]
I have tested it on 2 different devices and the loading error has not shown up again, so I think we are good!

**Comment by waspennator** [comment]
Alright then, closing!
