### ISSUE TITLE
The Room Tribute - Button Layering Issue

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1130]
In The Room Tribute, in the Flash version the dialog box can be clicked from anywhere on screen and it's layered over other buttons so you can't click anything else. In Ruffle, you can only click the dialog box itself and other areas remain clickable, interrupting the dialog scenes. For example, in the first scene when Tommy walks out of the bank, in Ruffle you can click on the door of the bank and interrupt the intro with the "bank is closed" comment.

https://www.newgrounds.com/portal/view/547307/format/flash?emulate=flash

**Comment by Herschel** [comment]
Fixed by #1175.
