### ISSUE TITLE
Symphonic Tower Defense: Broken leaderboards and song analysis

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11304]
### Describe the bug

https://www.newgrounds.com/portal/view/576557?emulate=flash
Game seems to work alright with lag here and there, however there are 2 issues i'm noticing with this.

1: The Song Analysis on the top left in the menu does not work at all, normally as you scroll through the songs, its supposed to give you advice on which towers you should buy for a song, on flash, On flash it starts out blank, but as you start scrolling through songs, it shows up normally on there.
![Symphony Ruffle 2](https://github.com/ruffle-rs/ruffle/assets/78768499/57c02893-da68-41e1-b66d-fbdfcdecc809)

2: At the end of the song level, the leaderboards seem to be busted, dunno if its something fixable or not.

![Symphony Ruffle 1](https://github.com/ruffle-rs/ruffle/assets/78768499/4a7c9066-872e-4b0d-9180-4811a65d331e)

### Expected behavior

The leaderboards should be working and the song analysis chart should look something like this as you start scrolling through.

![Symphony Flash](https://github.com/ruffle-rs/ruffle/assets/78768499/624d062c-eeb5-4025-ad71-3a6a016aba49)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 113

**Comment by Lord-McSweeney** [comment]
I believe 1. is caused by unimplemented `flash.display.Graphics.drawPath`

**Comment by Lord-McSweeney** [comment]
Issue one is improved now, but there's no fill inside the lines yet:
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Fuploads ungrounded net%2F576000%2F576557_MusicTD swf%3F1550080162](https://github.com/ruffle-rs/ruffle/assets/84632019/35120647-0df8-40e7-96e5-9043fc8a2401)

**Comment by waspennator** [comment]
![Screenshot 2023-07-09 124750](https://github.com/ruffle-rs/ruffle/assets/78768499/3f7b5b47-3b8f-4797-84a4-95947f7d0457)
Part 1 of the issue seems to somehow get fully fixed by Dinnerbone's Glow and dropshadow PR.

**Comment by waspennator** [comment]
![Screenshot 2023-11-22 185652](https://github.com/ruffle-rs/ruffle/assets/78768499/dd88a9e5-6a17-4b7d-bb9c-0b6433b3f5bd)
Leaderboards are still broken as of latest nightly.

**Comment by Aaron1011** [comment]
I'm getting the same 'Newgrounds highscore is temporarily unavailable' message in the Flash Player projector (I don't have a browser set up to test the plugin with). This appears to be a static background image - are you sure that the high scores ever worked with the current SWF version?

**Comment by waspennator** [comment]
Quickly downloaded Pale Moon and Flash Player to check and as it turns out, it does the same behavior too, so i'm guessing this can be closed now.
