### ISSUE TITLE
Swords and Souls: game is broken after defeating the first enemy

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#11319]
### Describe the bug

I got this error:
``
Error dispatching event EventObject(EventObject { type: "charHeroAttack", class: flash.events::Event, ptr: 0x4c00aa4 }) to handler FunctionObject(FunctionObject { ptr: 0x720ca64 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: gotoAndStop)    at interfaces::Loot()    at interfaces::Loot$/loot()    at game::FightManager$/handleDeath()    at characters::Character/_die()    at characters::Enemy/_die()    at characters::Character/getHit()    at game::FightManager$/_handleHit()    at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()    at characters::Hero/_manageAttack()
``
Problem is @Aaron1011 's PR - https://github.com/ruffle-rs/ruffle/pull/11084

SWF - https://data.gameflare.com/games/6579/luK5epRvoY99b2.swf
Game - https://www.gameflare.com/online-game/swords-and-souls/

### Expected behavior

show second enemy

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by MartySVK** [comment]
Should be fixed by upcoming PR - https://github.com/ruffle-rs/ruffle/pull/11308

**Comment by Lord-McSweeney** [comment]
Fixed by #11308.
