### ISSUE TITLE
Ruffle Desktop Gui: Basic file picker bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11336]
### Describe the bug

If you open up the basic file picker through the browse option on the desktop client,  if you leave it open and try to click back onto the ruffle player itself, it will eventually go into a not responding state like this. It also just kinda freezes visually until you close the file picker , but I dunno if that's fixable or not (Moved file manager off screen for proper view)
![Ruffle_Player_2](https://github.com/ruffle-rs/ruffle/assets/78768499/70c070c4-d35f-4963-a498-42de52f0fd76)

It doesn't happen if you do it by clicking on the file tab on the menu bar, then press open, however it presents a new quirk where I can press the maximize, minimize, or exit buttons on the top right and it will initiate them as soon as you close the file picker, meaning you can accidentally close ruffle without warning this way.

### Expected behavior

I know other emulators prevent you from interacting with the gui until you open a file or close out of the file picker, so maybe temporarily prevent the player from being able to interact with the ruffle desktop client until the file manager browser is closed.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by d-air1** [comment]
On arch linux the window is frozen on launch and attempting to do anything sends the window into the not responding state.
