### ISSUE TITLE
Create an option/command to hide the GUI for desktop clients

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#11358]
As with the current builds the GUI is now present. This is a nice to have feature, however it's also something that would be nice to be able to hide as well for that that prefer to not see the additional padding when booting up ruffle via a command line or directly.

**Comment by vadosnaprimer** [comment]
Especially useful for making a video (in our case through libTAS).

**Comment by p0008874** [comment]
> Especially useful for making a video (in our case through libTAS).

You know FFmpeg can chop the GUI right?

**Comment by Lord-McSweeney** [comment]
Closed by #12511.
