### ISSUE TITLE
Error on https://porngames.zone/6dc08228bc27cdfcfdbab9a8d9835d81-sonic-inflation-escapade

### ISSUE THREAD

**Issue by xchancex** [ruffle-rs/ruffle#11356]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/3/a/b3a5377a4aa0c645b6d725ca0bcaf9ff/b3a5377a4aa0c645b6d725ca0bcaf9ff.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/3/a/b3a5377a4aa0c645b6d725ca0bcaf9ff/b3a5377a4aa0c645b6d725ca0bcaf9ff.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://porngames.zone/6dc08228bc27cdfcfdbab9a8d9835d81-sonic-inflation-escapade

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.35
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by n0samu** [comment]
Very old version of Ruffle, plus this seems to be a server error unrelated to Ruffle.
