### ISSUE TITLE
Sometimes getting white screen after 'close' and opening a game

### ISSUE THREAD

**Issue by Zinc-Exclamation** [ruffle-rs/ruffle#11364]
### Describe the bug

using 'close' on the Ruffle GUI and opening another or the same game, can sometimes cause a white screen instead of the game loading, even with working SWFs 
no game will ever load when it does this, so closing ruffle itself is the only way to fix it
It happened 3 times in a row, but when recording, it didn't happen, so not sure what cause is
It always seemed to happen if I press 'force' on advanced open for the shown all before opening the sef, not sure

also, when 'browse' for a swf to use, the file browser does not pop up after the first time

### Expected behavior

after closing a game, and opening a new one there should not be a white screen

### Affected platform

Desktop app

### Operating system

Linux Mint

**Comment by Lord-McSweeney** [comment]
I experienced the "white screen on starting SWF" issue even before the Ruffle desktop got the enhanced UI- it would log the "Loaded SWF file [swf metadata]" message, but just stay on a white screen after that.

**Comment by Zinc-Exclamation** [comment]
https://github.com/ruffle-rs/ruffle/assets/109034847/be51a4c7-0fc9-4e46-a532-266f71cafba2

**Comment by Zinc-Exclamation** [comment]
this also happens when clicking 'reload' 
but not when the window is not maximized, so the workaround is to open a game maximise, do testing, etc
then remember to unmaximise before reloading or switching games

if someone could please take a look at what causes the white screen issue, I would very much appreciate it
testing becomes tedious any annoying when I need to constantly close and reopen ruffle/ constantly maximise and unmaximise to make it work

**Comment by Zinc-Exclamation** [comment]
Thank you!
