### ISSUE TITLE
not saving anything

### ISSUE THREAD

**Issue by dessertie** [ruffle-rs/ruffle#11369]
I'm not sure if this is just ruffle or my computer, but any flash game I play will not save. My computer is a bit of a fossil, so it might just be me. Everything works fine as I play the game, but if I reload the page or otherwise leave and come back to the game, I have to start from the beginning. It's very frustrating. I've tried to troubleshoot it on my own without success, so I figured I bring it up to someone who knows what they're doing lol. My computer is a 2010-ish Mac with version 10.13.6 software. It's the most recent update the hardware can handle so if the problem is just my computer I wouldn't be surprised.

**Comment by Lord-McSweeney** [comment]
Which browser are you using?

**Comment by dessertie** [comment]
I use chrome—likely an outdated version bc of my computer’s age

**Comment by Lord-McSweeney** [comment]
Can you ask on the Ruffle discord? https://discord.gg/ruffle

**Comment by dessertie** [comment]
Yes I’ll do that rn

**Comment by Lord-McSweeney** [comment]
From Discord, this was a combination of two issues: one with some AS3 games not saving progress, and a second being the disabling of third-party cookies.
