### ISSUE TITLE
[Font] Cannot render non-English text such as Chinese and Japanese

### ISSUE THREAD

**Issue by wifi-left** [ruffle-rs/ruffle#11362]
### Describe the bug

Cannot render non-English text such as Chinese and Japanese

### Expected behavior

Display text correctly

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Version: 2023.6.3 Nightly
Screenshots: 
![image](https://github.com/ruffle-rs/ruffle/assets/63381531/d1ab8450-6125-4973-9f7f-3ee5a38a4442)

**Comment by Lord-McSweeney** [comment]
Closing in favor of #11234.

**Comment by n0samu** [comment]
@wifi-left This should be fixed in the latest nightly
