### ISSUE TITLE
Error on chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html

### ISSUE THREAD

**Issue by lisscodes** [ruffle-rs/ruffle#11367]
# Error Info
Error name: Error
Error message: panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:681:28
Error stack:
```
Error: panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:681:28
    at imports.wbg.__wbg_new_87297f22973157c8 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/339.js:2380:21)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h200f5155dea3b93b (wasm://wasm/02c1c046:wasm-function[8594]:0x828931)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (wasm://wasm/02c1c046:wasm-function[5637]:0x75094e)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (wasm://wasm/02c1c046:wasm-function[8461]:0x8245b5)
    at core::option::expect_failed::hc36a69366777ce0b (wasm://wasm/02c1c046:wasm-function[7223]:0x7bda8a)
    at ruffle_core::avm2::function::Executable::exec::hcfe01642d79b6b9f (wasm://wasm/02c1c046:wasm-function[800]:0x2a6d9e)
    at <ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::hc1909ed28d1383fb (wasm://wasm/02c1c046:wasm-function[977]:0x33754c)
    at ruffle_core::avm2::events::dispatch_event_to_target::h497ab6fc22aa0551 (wasm://wasm/02c1c046:wasm-function[827]:0x2ccea9)
    at ruffle_core::avm2::events::dispatch_event::h9402d74641d786a7 (wasm://wasm/02c1c046:wasm-function[1085]:0x372b40)
    at ruffle_core::avm2::Avm2::dispatch_event::ha9f8967720c287d2 (wasm://wasm/02c1c046:wasm-function[1057]:0x36230e)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) Graphics (ADL GT2), OpenGL 4.6)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fcdn.ghstatic.com%2Farchives%2F2627%2Fgameloader_640x480.swf%3FvisitID%3D2debdc7b%253A188833073b4%253A-6fd4%26language%3Den%26country%3DUS%26gameSetCountry%3DMC%26skinnedGameID%3D6177%26gameID%3D2627%26gameSetID%3D2%26isPremium%3Dfalse%26urlImage%3D%252Farchives%252Furl%252F_url_splash_US.gif%26errorPage%3Dhttps%253A%252F%252Fgame.zylom.com%252Fnocontent%253Ferror%253Dsecurityerror%26propertiesErrorPage%3Dhttps%253A%252F%252Fgame.zylom.com%252Fnocontent%253Ferror%253Dpropertyerror%26localURL%3Dwww.zylom.com%26autoRespond%3Dfalse%26playerOrigin%3DZYLOM%26hasDownloadable%3Dtrue%26showAds%3Dtrue%26downloadableURL%3Dhttps%253A%252F%252Fsecure.zylom.com%252Fservlet%252FDownloadable%253Fg%253D2%2526s%253D6177%26adUrl%3Dhttps%253A%252F%252Fsecure.zylom.com%252Fservlet%252FDownloadable%253Fg%253D2%2526s%253D6177%26cheatsEnabled%3Dfalse
SWF URL: https://cdn.ghstatic.com/archives/2627/gameloader_640x480.swf?visitID=2debdc7b%3A188833073b4%3A-6fd4&language=en&country=US&gameSetCountry=MC&skinnedGameID=6177&gameID=2627&gameSetID=2&isPremium=false&urlImage=%2Farchives%2Furl%2F_url_splash_US.gif&errorPage=https%3A%2F%2Fgame.zylom.com%2Fnocontent%3Ferror%3Dsecurityerror&propertiesErrorPage=https%3A%2F%2Fgame.zylom.com%2Fnocontent%3Ferror%3Dpropertyerror&localURL=www.zylom.com&autoRespond=false&playerOrigin=ZYLOM&hasDownloadable=true&showAds=true&downloadableURL=https%3A%2F%2Fsecure.zylom.com%2Fservlet%2FDownloadable%3Fg%3D2%26s%3D6177&adUrl=https%3A%2F%2Fsecure.zylom.com%2Fservlet%2FDownloadable%3Fg%3D2%26s%3D6177&cheatsEnabled=false

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-03
Channel: nightly
Built: 2023-06-03T00:25:51.214Z
Commit: 2cd518013c74044100407435284e2cf108e96dfe
Is extension: true

# Metadata
width: 640
height: 480
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 127931

**Comment by Lord-McSweeney** [comment]
After #10811 this needs `AVM1Movie`.

**Comment by Lord-McSweeney** [comment]
Looks like this is mostly working now
