### ISSUE TITLE
Bug-compatibility: weird behavior when using blend modes in an empty SWF

### ISSUE THREAD

**Issue by moulins** [ruffle-rs/ruffle#11375]
While writing the test for #11374, I've uncovered a weird Flash Player bug where programmatically manipulating blend modes gives different outputs depending on whether any objects are present on the stage.

Here is an ActionScript 2 reproducer:
[AVM1BlendModesAtRoot.zip](https://github.com/ruffle-rs/ruffle/files/11646724/AVM1BlendModesAtRoot.zip)
```as
// Compile with either:
//   mtasc -main Test.as -swf assets.swf -out non_empty.swf
//   mtasc -main Test.as -header 200:150:30 -swf empty.swf
class Test {
    static function main(self) {
        var mc1 = self.createEmptyMovieClip("mc1", self.getNextHighestDepth());
        var mc2 = self.createEmptyMovieClip("mc2", self.getNextHighestDepth());

        fillClip(mc1, 0x00AA00)
        fillClip(mc2, 0xFF0000)
        mc2._x = 33;
        mc2._y = 33;

        // This will give different results depending on the SWF:
        // - on `empty.swf`, the traces print `undefined` and setting
        //   the blend mode doesn't affect the visuals.
        // - on `non_empty.swf`, the traces print `normal`, and setting
        //   the blend mode works as expected.
        trace("mc1: " + mc1.blendMode);
        trace("mc2: " + mc2.blendMode);
        mc2.blendMode = "invert";
    }

    static function fillClip(mc, color) {
        mc.beginFill(color);
        mc.moveTo(0, 0);
        mc.lineTo(0, 100);
        mc.lineTo(100, 100);
        mc.lineTo(100, 0);
        mc.lineTo(0, 0);
        mc.endFill();
    }
}
```
![image](https://github.com/ruffle-rs/ruffle/assets/10963458/aff0d7df-1ed6-43d4-82e8-acd70e938efa)

(Ruffle will "incorrectly" display the same result in both cases)

----------

I don't expect this Flash bug to ever be relevant in practice, as fully empty stages aren't really a thing in the wild; still, it's better to know about the bug even if we decide to not reproduce its behavior in Ruffle.

**Comment by Toad06** [comment]
I opened the files with JPEXS and looked at the SWF versions. It is 15 for `non_empty.swf` and 7 for `empty.swf` (which doesn't implement the `blendMode` property). So I think this could be an unfortunate bug with the mtasc compiler?

**Comment by moulins** [comment]
You're absolutely right, setting the version to `8` fixes the issue, my bad.
