### ISSUE TITLE
Bejeweled Twist: Options menu EditTexts are not visible

### ISSUE THREAD

**Issue by crumblingstatue** [ruffle-rs/ruffle#11372]
### Describe the bug

![image](https://github.com/ruffle-rs/ruffle/assets/1521976/851e506d-cd85-46af-8497-b5129a75e8ee)

Swf: https://github.com/ruffle-rs/ruffle/files/10948592/bejeweled_twist.zip

### Expected behavior

The text should be visible.

### Affected platform

Desktop app

### Operating system

Arch Linux

**Comment by n0samu** [comment]
The game also requires this XML file: [data.zip](https://github.com/ruffle-rs/ruffle/files/11645229/data.zip)
To properly test the game, you need to place the SWF file and the XML file in the same folder.
Testing it this way, I see that in Flash Player, the game loads the XML file and the text displays fine. But Ruffle never even requests the XML file, and the text is not shown.

**Comment by crumblingstatue** [comment]
Ah, interesting, thank you

**Comment by n0samu** [comment]
Checked again and this is still occurring, unfortunately.

**Comment by n0samu** [comment]
This seems to be fixed now
