### ISSUE TITLE
CJK character rendering in desktop app UI

### ISSUE THREAD

**Issue by everything411** [ruffle-rs/ruffle#11373]
### Describe the bug

CJK character rendering as squares (tofu).
<img width="396" alt="CJK character bad rendering" src="https://github.com/ruffle-rs/ruffle/assets/32010059/4a3ff945-fd63-449c-b3b4-97c99bbcc374">

### Expected behavior

correct CJK character rendering

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

-

**Comment by Lord-McSweeney** [comment]
Closing in favor of #11234.

**Comment by n0samu** [comment]
@everything411 This should be fixed in the latest nightly
