### ISSUE TITLE
Micrics - Gamezhero Preloader not working

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11380]
### Describe the bug

In many games that has been sponsored by gamezhero, an endless loop in the pre loader is happening:

In this case with this error, dunno if it's always the same.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/micrics.swf

ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "api_ini_engine", class: com.gameallianz.api.as3::GameAllianzApiEvent, ptr: 0x3380284 }) to handler FunctionObject(FunctionObject { ptr: 0x123d3c4 }) : ReferenceError: Error #1069: Property flash.printing::PrintJob not found on global and there is no default value.

### Expected behavior

Load & Run

### Affected platform

Online demo

### Operating system

All

**Comment by n0samu** [comment]
Preloader was fixed by #10756. The game is still broken though (probably because of the void parameter issue)

**Comment by Lord-McSweeney** [comment]
Unfortunately, this now happens:
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Fwww spiele-umsonst de%2Fazad%2Fdownloads%2Fflashgames%2Fmicrics swf](https://github.com/ruffle-rs/ruffle/assets/84632019/8520971a-36e2-4294-b8a6-2cb646222ef3)
(I clicked the first level)

This might be because `NetConnection.call` is unimplemented.

**Comment by Lord-McSweeney** [comment]
This seems to have regressed slightly, now it errors
```
TypeError: Error #1010: A term is undefined and has no properties.
	at XML/XML::elements()
	at MethodInfo-1299()
	at Xml/firstElement()
	at Level()
	at Type$/createInstance()
	at Main$/gotoRoom()
	at MethodInfo-261()
	at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
	at flash.utils::Timer/onUpdate()
```
and is stuck on a solid pink screen with the Gamezhero logo after entering the first level.
