### ISSUE TITLE
Layering Error in Bubble Tanks 2

### ISSUE THREAD

**Issue by BananaAcid** [ruffle-rs/ruffle#11398]
### Describe the bug

The layering of movieclips seems to upside down 
<img width="498" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/1894723/fd65a7ea-8635-4446-b978-f5932c42aff8">

### Expected behavior

The layering to be fixed

### Affected platform

Self-hosted version

### Operating system

MacOS 13.0 (22A380)

### Browser

Chrome Browser

### Additional information

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: CLEAR_TEXTURE
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1000, height: 800, depth_or_array_layers: 1 }

# Page Info
Page URL: https://armorgames.com/play/1920/bubble-tanks-2?fp=b-shooting
SWF URL: https://cache.armorgames.com/files/games/bubble-tanks-2-1920.swf?v=1373587520

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-13
Channel: nightly
Built: 2023-03-13T00:19:09.191Z
Commit: b527054a1e2317d9e17ed0dfbfc0e9cceaafd760
Is extension: false

# Metadata
width: 500
height: 400
frameRate: 55
numFrames: 50
swfVersion: 8
backgroundColor: #288BD5
isActionScript3: false
uncompressedLength: 2278339

**Comment by Sonikkustar** [comment]
The issue appears to be fixed:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/a573db94-26e5-4493-8a71-6ebaa999cfb3)

Site now uses nightly-2023-12-17.
