### ISSUE TITLE
Nightly 2023-06-07 fails to build on Arm64

### ISSUE THREAD

**Issue by coreybruce** [ruffle-rs/ruffle#11403]
### Describe the bug

Nightly 2023-06-07 fails to build on Manjaro Arm64 

Log: https://gist.github.com/coreybruce/8f0bcac3a65eb259c04da223dbc177a1

### Expected behavior

Successfully builds without issues 

### Affected platform

Desktop app

### Operating system

Manjaro Arm64

**Comment by n0samu** [comment]
Please run `rustup update`

**Comment by coreybruce** [comment]
> Alternatively, if you're relying on the system package manager to handle your Rust installation (which is generally not recommended due to this exact problem), make sure you're running at least version 1.70.0 (the first version to support `once_cell`), and if the system repo doesn't have it yet then you'll probably just need to be patient.

Ah right I see, I have switched to rustup. I will let you know if I run into any other issues, thanks for letting me know. :smiley:
