### ISSUE TITLE
Luigi's Mansion silently stops working

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1140]
Edit 2020-11-29:
The game now works but there's still an unexpected behavior - please see the tests in the comments below.

----

After the ghost has reached the top of the screen, a sound effect plays and then nothing else happens anymore.
No error and no warning in the console.

Expected (Flash Player):
![expe](https://user-images.githubusercontent.com/14274782/92498379-d7088800-f1fa-11ea-85a5-c966abd67450.png)

Game:
[luigimansion.zip](https://github.com/ruffle-rs/ruffle/files/5189360/luigimansion.zip)

**Comment by CUB3D** [comment]
This failing test case may be causing some of the issues here, it seems like something to do with the order of onEnterFrame or onDestroy calls but I'm not sure.

Test:
[clip_destruction.zip](https://github.com/ruffle-rs/ruffle/files/5289270/clip_destruction.zip)

**Comment by Toad06** [comment]
Testing again and for some reason, the game "works" if you remove some `Destroy()` calls (`removeMovieClip`). But that's weird.

```
IntroScreen.prototype.onEnterFrame = function()
{
   if(IntroKong0._y < 168)
   {
      IntroKong0.removemovieclip();
      _root.attachMovie("StartScreen","StartScreen0",1);
      this.Destroy(); // remove this
   }
};
```
=> Removing this allows the game to start but platforms won't be visible.


```
StartScreen.prototype.onEnterFrame = function()
{
   var _local1 = this;
   _local1.DelayCount = _local1.DelayCount + 1;
   if(35 < _local1.DelayCount)
   {
      _root.attachMovie("Level1","Level10",1);
      _local1.Destroy(); // remove this
   }
};
```
=> Also removing this allows the platforms to be visible.

[luigismansion_edit.zip](https://github.com/ruffle-rs/ruffle/files/5379019/luigismansion_edit.zip)

**Comment by Toad06** [comment]
So I think I've finally found out what's wrong here: `attachMovie()` and `removeMovieClip()` are changing the value of `this` in Flash.

I've made two samples based on your original test:
[test_this.zip](https://github.com/ruffle-rs/ruffle/files/5585193/test_this.zip)


```
function A()
{
}
function B()
{
}
A.prototype = new MovieClip();
Object.registerClass("A",A);
A.prototype.onEnterFrame = function()
{
   trace(this + " - " + typeof this);
   _root.attachMovie("B","B0",1);
   trace(this + " - " + typeof this);
   this.removeMovieClip();
   trace(this + " - " + typeof this);
};
B.prototype = new MovieClip();
Object.registerClass("B",B);
attachMovie("A","A0",1); // depth is 2 in test_differentdepth.swf
```
----

`test_samedepth.swf`

Flash traces:
```
_level0.A0 - movieclip
 - movieclip
 - movieclip
```

Ruffle traces:
```
_level0.A0 - movieclip
_level0.A0 - movieclip
_level0.A0 - movieclip
```

----
`test_differentdepth.swf`

Flash traces:
```
_level0.A0 - movieclip
_level0.A0 - movieclip
 - movieclip
```

Ruffle traces:
```
_level0.A0 - movieclip
_level0.A0 - movieclip
_level0.A0 - movieclip
```

----

Note that replacing all instances of `this` in the samples with `_level0.A0` produces consistent results in Flash and Ruffle.

`Trace in test_samedepth.swf`
```
_level0.A0 - movieclip
undefined - undefined
undefined - undefined
```

`Trace in test_differentdepth.swf`
```
_level0.A0 - movieclip
_level0.A0 - movieclip
undefined - undefined
```

**Comment by Herschel** [comment]
Sounds like another case of #993 -- after a clip is removed/overwritten, the object should go into a "removed" state and return undefined for all properties, and "" when coerced to a string.
