### ISSUE TITLE
Busman Parking 3D - Black screen

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11408]
### Describe the bug

As it was some game liked by my audience I will post the error here in case it will get fixed :)

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/busmanparking3d.swf

ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xa0d4fc }) to handler FunctionObject(FunctionObject { ptr: 0xa0c38c }) : Error: Error #2030: End of file was encountered.

### Expected behavior

Load & Play

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
Same as a bunch of different issues, for example #11310

**Comment by n0samu** [comment]
Fixed by #12308, but see #12364 for the next problem with this game
