### ISSUE TITLE
Controls Broken on Pretentious Game

### ISSUE THREAD

**Issue by Rno-1** [ruffle-rs/ruffle#11426]
### Describe the bug

http://onemorelevel.com/static/games3/pretentious-game.swf
I click play and am unable to control the main character using keyboard controls.

The console gives these errors. The second one repeats ten more times with different pointer addresses.

`ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "render", class: flash.events::Event, ptr: 0x1867106fdd8 }) to handler FunctionObject(FunctionObject { ptr: 0x186704d7618 }) : Error: Error #2030: End of file was encountered.`

`ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "render", class: flash.events::Event, ptr: 0x18679c3e958 }) to handler FunctionObject(FunctionObject { ptr: 0x18679da5a08 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: b2World_new)`

### Expected behavior

The controls are supposed to work.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Using Nightly 2023-06-07

**Comment by n0samu** [comment]
Same problem as https://github.com/ruffle-rs/ruffle/issues/9681#issuecomment-1562620880

**Comment by n0samu** [comment]
Fixed by #12308
