### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by bruhcode68** [ruffle-rs/ruffle#11433]
# Error Info
Error name: Error
Error message: Ruffle is panicking!
Error stack:
```
Error: Ruffle is panicking!
    at Je.load (https://ruffle.rs/demo/index.js:2:245703)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36  
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-08
Channel: nightly
Built: 2023-06-08T00:20:14.155Z
Commit: 8ce8b775a70f291aadd534e7505e2ceae9b06557
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play when the error occurred?

**Comment by n0samu** [comment]
Closing in favor of #11498
