### ISSUE TITLE
A file is constantly requested for loading, leading to a critical issue (IP banned from server)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1145]
Open the browser's console and select the "Network" tab. Then go to the following page:
http://www.annie-cordy.com/disco/discographie80.html

You will notice the console gets flooded with endless "discographie80.html" requests. You should close the browser quickly after that, otherwise the server will ban your IP, assuming (I think) it's the victim of a denial-of-service attack.

![banned](https://user-images.githubusercontent.com/14274782/92597034-1391bd80-f2a7-11ea-84bc-d2fee682fea6.png)

**Comment by kmeisthax** [comment]
So, it appears you can `unloadMovie` by emitting a `GetUrl2` command with the right parameters. Amazing. We don't handle that correctly, so we wind up making a bunch of spurious requests.
