### ISSUE TITLE
Civilizations Wars - Soft locks after all huts are taken.

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11460]
### Describe the bug

https://www.newgrounds.com/portal/view/523882?emulate=flash - This game seems to work fine until you took over all the huts and stuff in the first level the level never ends and we can't proceed

There are also soft bugs like you can't drag & drop troops from more than one hut and some filters are missing. For gameplay video see:

https://www.youtube.com/watch?v=eaAA11VIi3g

### Expected behavior

To have the win screen after taken all and proceed

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
There is a trace in the console that said something like "`aGame.finished()`" (exact content unknown because I accidentally closed the tab) that appeared after capturing all the huts.

**Comment by Aaron1011** [comment]
This is fixed on the latest `master`
