### ISSUE TITLE
Control Craft - Armorgames Intro Sound Loop

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11464]
### Describe the bug

Someone stop this intro loop sound for the sake of my ear.  Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/controlcraft.swf

### Expected behavior

Stop The intro sound

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Seems like this was already fixed in nightly 2023-06-10. Can you test it again?
