### ISSUE TITLE
AdventureQuest: Cannot Teleport to Void Paintings

### ISSUE THREAD

**Issue by secret-shober** [ruffle-rs/ruffle#11474]
### Describe the bug

When you try to teleport to an owned Void Painting, it will fail to load due to a bad file path.
![Peek 2023-06-10 19-47](https://github.com/ruffle-rs/ruffle/assets/119772252/f7db1897-a0d1-4342-9b3d-3513b3f9bd3a)

It requests from `https://aq.battleon.com/game/flash/towns/undefined.swf` but it should really be requesting at `https://aq.battleon.com/game/flash/towns/void-FruitcakeZard.swf`

### Expected behavior

You should be able to enter a Void Painting like all other paintings.

All other teleporting paintings currently work as intended. This only affects Void Takeover Paintings.

### Affected platform

Desktop app

### Operating system

Linux

**Comment by secret-shober** [comment]
Useful debug information:

The teleport button controls this code: 
```
on(release){
   _root.town.TeleportViaCurrentPainting();
}
```
Which implementation is:
```
function TeleportViaCurrentPainting()
{
   var _loc2_ = dataHouse.paintings[numCurrentPainting].strHouseItemFilename2;
   if(!bIsOwner || _loc2_ == "" || _loc2_ == undefined || _loc2_.toLowerCase() == "none")
   {
      return undefined;
   }
   if(_loc2_.substr(0,5) == "shop:")
   {
      _root.shop.Load(Number(_loc2_.substr(5)));
   }
   else
   {
      if(_loc2_.substr(0,7) == "string:")
      {
         _loc2_ = _loc2_.substr(7,50);
         _loc2_ = _root.func.GString(_loc2_);
      }
      _root.quest.LoadTownFile(_loc2_,false);
   }
}
```

An example payload is:
```
<paintings>
  ...
  <strHouseItemFilename2>Void-fake2.swf?file=void-FruitcakeZard</strHouseItemFilename2>
</paintings>
```

It resolves to and attempts to load `https://aq.battleon.com/game/flash/towns/Void-fake2.swf?file=void-FruitcakeZard` which does:

```
onLoadComplete = function(mcHost, intErrorCode)
{
   gotoAndStop("Start");
};
onLoadError = function(mcHost, intErrorCode)
{
   _root.msg.Show("Error loading host file " + strHostFile + "!  Returning to town.");
   _root.quest.ReturnToTown();
};
var strHostFile;
stop();
bTakeoverActive = true;
strHostFile = file + ".swf";
trace(strHostFile);
trace(mcHost);
var hostLoader = new MovieClipLoader();
hostLoader.addListener(this);
hostLoader.loadClip("./towns/" + strHostFile,mcHost);
```

# 
Maybe helpful? Running the swf's from the intended webpage works as intended (load the background, then load the town)
```
var ruffle = window.RufflePlayer.newest().createPlayer()
var container = document.getElementById("main")
container.appendChild(ruffle)
ruffle.load({
    url: "https://aq.battleon.com/game/flash/towns/Void-fake2.swf?file=void-FruitcakeZard",
    base: "https://aq.battleon.com/game/flash/"
})
```

**Comment by secret-shober** [comment]
I was able to replace a button's functionality with the following code:
```
on(release){
   loadMovie("towns/Void-fake2.swf?file=void-FruitcakeZard","","GET");
}
```

The result is that this will fail to render the movie associated with Void Fake: `https://aq.battleon.com/game/flash/towns/void-FruitcakeZard.swf` but instead tries to go to `https://aq.battleon.com/game/flash/towns/undefined.swf` 

I am not sure if this is the same as the built-in `loadMovie` but I think it is a good idea to check if the built-in `loadMovie` function can pick up query parameters.

**Comment by n0samu** [comment]
> UPDATE: So on Discord, we found out that loadMovie has two different behaviors between the browser and the plugin. Hence projectors don't have access to query parameters and this is not yet implemented in Ruffle. So it'll have to be implemented. Once that is done I will follow up on this ticket and confirm/deny that this is indeed fixed.

Sorry, that was my mistake. The behavior in both the projector and the plugin is to pass the URL query parameters as flashvars, and this behavior is not yet implemented in Ruffle. I thought at first that the projector didn't have access to query params because I forgot to clear its cache, so it was using an old version of my test file.
