### ISSUE TITLE
ActionScript 3 support but the swf doesn't load

### ISSUE THREAD

**Issue by sorarjq** [ruffle-rs/ruffle#1147]
The swf file I downloaded: https://www.mcleodgaming.com/flash/?f=games/SSF2Beta_v1_2_3_2.swf
The original website: https://www.mcleodgaming.com/games/ssf2
![image](https://user-images.githubusercontent.com/71035795/92637088-3d3deb00-f28d-11ea-9966-b94c01f5b9e4.png)
I'm on a chrome browser, also not a tech person but I can provide any other pictures of the problem if needed.

**Comment by Herschel** [comment]
Uses `Vector`, we need to add TypeName multiname type (0x1D) to `swf`, see:
https://github.com/adobe/avmplus/blob/master/core/ActionBlockConstants.h#L50

Lots of good documentation about Vector and the applytype instruction here, for when we get around to implementing it:
https://github.com/adobe/avmplus/blob/master/core/VectorClass.h

**Comment by kmeisthax** [comment]
Huh. Didn't know AVM2 had parameterized typing - that'll be fun to implement.

**Comment by Herschel** [comment]
Thankfully it barely has parameterized typing -- it only supports types of `Vector.<T>` 😄

**Comment by Herschel** [comment]
Closing in favor of #1368.

**Comment by GamingAnimate** [comment]
It's not supported yet at this time, it is to be determined soon hopefully since I have to use that also.

**Comment by nlangdon1** [comment]
Absolutely dying for Action 3 to work...........
