### ISSUE TITLE
Error on https://www.spiele-kostenlos-online.de/strategiespiele/zeitmanagement/mommas-diner/

### ISSUE THREAD

**Issue by Kathy534** [ruffle-rs/ruffle#11514]
# Error Info
Error name: TypeError
Error message: undefined is not an object (evaluating 'e.headers.get')
Error stack:
```
@https://cdn.spiele-kostenlos-online.de/wp-content/themes/spiele-kostenlos-online/js/ruffle/2023_06_11/core.ruffle.da99993935f2914b006e.js:1:56111
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.spiele-kostenlos-online.de/strategiespiele/zeitmanagement/mommas-diner/

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/267.0.537056344 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-11
Channel: nightly
Built: 2023-06-11T00:20:00.881Z
Commit: dced6445eebbab1775578fdf0a9331012120f359
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Closing in favor of #11504 (same issue)
