### ISSUE TITLE
FF Chocobo Mix

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1152]
https://www.newgrounds.com/portal/view/58184

When I click the Ruffle Play button on the Chocobo Mix, it appears to be stuck on the white screen afterwards.

Interesting note - this SWF also appears to break in Swivel, it doesn't let me access any frames in there.

**Comment by kmeisthax** [comment]
I tried to open this in Ruffle Desktop and it immediately failed with the following error:

```Fatal error:
Error decompressing SWF, may be corrupt: failed to fill whole buffer
```

**Comment by Herschel** [comment]
The decompression is still funky (truncated stream?) but this now fails more gracefully and still seems to play okay with #2636.
