### ISSUE TITLE
Explosm Movies Redirecting to Explosm.net

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#11535]
### Describe the bug

https://www.newgrounds.com/portal/view/500149/format/flash?emulate=flash

Several Explosm movies are redirecting to a blank screen on their preloaders. It appears to be redirecting to Explosm.net, might be related to this issue:

"Mixed Content: The page at 'https://www.newgrounds.com/portal/view/500149/format/flash?emulate=flash' was loaded over HTTPS, but requested an insecure frame 'http://www.explosm.net/'. This request has been blocked; the content must be served over HTTPS."

### Expected behavior

Expected behavior is the preloader screen doesn't redirect to a blank screen and movie is able to be watched.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome Version 114.0.5735.110

**Comment by danielhjacobs** [comment]
Would it help to set the configuration option "upgradeToHttps" to `true`: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options? It should already be true when window.location.protocol === "https:" though, so I'm not sure this would change anything.

**Comment by Lord-McSweeney** [comment]
The SWF is opening the page `http://www.explosm.net/` in its own Newgrounds frame, which is causing the issue. I would guess that this is a failing sitelock.
