### ISSUE TITLE
Douchebag: Beach Club: Cannot access a property or method of a null object reference. (accessing field: 2)

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#11550]
### Describe the bug

The game is stuck on loading with the error:

``ERROR ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: 2)``

SWF - https://data.gameflare.com/games/4531/wcSAilhdbIZQcJ.swf
Game Online - https://www.zahraj.sk/online-hra/douchebag-beach-club/

### Expected behavior

progress game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
This is an issue with the IMA SDK, same as #1840.
