### ISSUE TITLE
LETTERBOX / FULL_SCREEN not working with main.stage.fullScreenSourceRect (AS2 & AS3)

### ISSUE THREAD

**Issue by Mennez** [ruffle-rs/ruffle#11552]
### Describe the bug

First of all: Ruffle is awesome  and developers -- THANKS A LOT! 

We are making our games Ruffle ready for our website. However there are two issues I see, which I can't really find on GitHub. First one is the **FULL_SCREEN option**. Ruffle supports FULL_SCREEN, but only the normal FULL_SCREEN option where you **do not have any black bars next to your viewport** (I think it ignores the set 'fullScreenSourceRect' value). 

<img width="2025" alt="no-black-bars" src="https://github.com/ruffle-rs/ruffle/assets/6833463/d5571737-4362-497c-91a9-9b29f79c5dcf">

The black bars were shown previously in our games in flash player and is the expected behaviour. Now it is not scaling the game content and using the native vector images (bad performance). Also it is not showing black bars when content is out of the viewport. 

Is this feature still in development? It is an issue for AS2 & AS3 games.

The second issue is related to Dynamic Fonts. The positioning and font types are not correct in our games anymore in the Ruffle player. We **did embed** them in Adobe Animate.

### Expected behavior

Ruffle should have a viewport for FULL_SCREEN, like the flash player previously had. Content outside the viewport should not be shown.

### Affected platform

Browser's extension

### Operating system

macOS Ventura 13.2.1

### Browser

Google Chrome 114.0.5735.106

**Comment by n0samu** [comment]
Since these two problems are unrelated to each other it would be better to create separate issues for them. fullScreenSourceRect is indeed unimplemented. Can you open a new issue for the dynamic font problem and attach a sample to demonstrate the problem?

**Comment by Mennez** [comment]
Okay, I will create an issue for the Dynamic Fonts. I saw something on the ruffle website about a [(LETTERBOX)](https://ruffle.rs/js-docs/master/enums/Letterbox.html) setting. This adds black borders around the viewport (exactly what we want). I tried implementing it on our website, but it isn't doing anything. 

I added ruffle on our website like this:

`<script src="https://unpkg.com/@ruffle-rs/ruffle"></script>
    <script>
        window.RufflePlayer = window.RufflePlayer || {};
        window.RufflePlayer.config = {
            "autoplay": "on",
            "unmuteOverlay": "hidden",
            **"letterbox": "on"**
        };
    </script>`

Setting autoplay to ON perfectly works however...

**Comment by n0samu** [comment]
Your Flash embed is using a transparent window mode, and Ruffle cannot letterbox content in this mode. To use letterboxing, you will need to remove the `wmode` attribute from your object/embed tag. For more information about window mode, see this article: https://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html#main_Using_Window_Mode__wmode__values_

**Comment by Mennez** [comment]
Ah perfect! That seems to work. I only got an error now when I exit FULL_SCREEN via the ESC key. When I use the CustomContextMenu and then press 'Exit full screen', it does not show the error. I this a Ruffle error or something I am missing in my config?

<img width="1982" alt="Screenshot 2023-06-17 at 11 20 35" src="https://github.com/ruffle-rs/ruffle/assets/6833463/b6aa4c9c-7afd-4e43-ac78-190e32477571">

**Comment by n0samu** [comment]
If the error does not cause any visible problem, it can be ignored. Otherwise, please let me know what visible problem it causes.

**Comment by Mennez** [comment]
I do not see any visible problem, only the error itself.
