### ISSUE TITLE
Tequila Zombies 2 - Can't start the level

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11566]
### Describe the bug

Hey, despite the heavy lag there are errors thrown when you get to level select menu and want to start it.

https://www.newgrounds.com/portal/view/600176?emulate=flash

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x521d37c }) to handler FunctionObject(FunctionObject { ptr: 0x3d86a1c }) : Error: Error #2030: End of file was encountered.
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x68fd494 }) to handler FunctionObject(FunctionObject { ptr: 0x3d86a1c }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: b2World_new)

### Expected behavior

Load & Run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Same problem as #11426 and #9681

**Comment by Lord-McSweeney** [comment]
(box2d/cmodule domain memory issue)

**Comment by n0samu** [comment]
Fixed by #12308
