### ISSUE TITLE
Mutilate-a-Doll 2: Failed to parse XML

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#11560]
### Describe the bug

It is just a black screen with the error:

``ERROR ruffle_core::display_object::movie_clip: Got "RustError("Failed to parse XML: TypeError: Error #1088: The markup in the document following the root element must be well-formed.")" when constructing AVM2 side of movie clip of type Main``

SWF - http://f3.silvergames.com/mutilate-a-doll-2_v4.swf

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Fixed by #11782.
