### ISSUE TITLE
Panic when parsing http://www.ferryhalim.com/orisinal/ad/ad.swf

### ISSUE THREAD

**Issue by kmeisthax** [ruffle-rs/ruffle#116]
panicked at 'index 4 out of range for slice of length 0', src/libcore/slice/mod.rs:2555:5

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function:289:21
console_error_panic_hook::hook::h4ae520498c7c86ef@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[382]:0xd41af
core::ops::function::Fn::call::h20e473265f2965a7@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1891]:0x11f0d5
std::panicking::rust_panic_with_hook::h6fe9d3817474ba5a@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[843]:0x10b2b3
std::panicking::continue_panic_fmt::h1b22eea7f33d6c0a@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1100]:0x1165ec
rust_begin_unwind@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1880]:0x11f06c
core::panicking::panic_fmt::h2daf88b2616ca2b2@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1314]:0x11b58d
core::slice::slice_index_len_fail::h4544fc57f3d8a7a0@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1120]:0x116e7f
ruffle_core::backend::render::remove_invalid_jpeg_data::hb2b397c9a4ce0ed6@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[503]:0xe8d4c
ruffle_core::library::Library::set_jpeg_tables::h1b218ae03cf118ae@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[864]:0x10c7d4
ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h52e43b3b39955e46@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[128]:0x3adb2
ruffle_core::tag_utils::decode_tags::hb4b79b4a14c8885d@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[445]:0xdfc3f
ruffle_core::display_object::movie_clip::MovieClip::preload::hfd75abe1b7acc24d@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[354]:0xcdc5e
ruffle_core::player::Player<Audio,Renderer,Navigator>::new::h15b886b5ee9f6fef@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[141]:0x5b4bb
ruffle_web::Ruffle::new::h977e07c2b9dc3107@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[275]:0xb68fa
ruffle_new@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function line 1028 > WebAssembly.instantiate:wasm-function[1028]:0x11434a
new@http://www.ferryhalim.com/orisinal/ line 619 > eval line 46 > Function:249:26
play_swf_data@webpack:///../js-src/ruffle-player.js?:121:36

**Comment by Herschel** [comment]
This was actually http://www.ferryhalim.com/orisinal/sunshine/all.swf caused by an empty JPEGTables tag (how do I get Flash to export this?)
