### ISSUE TITLE
Flight Simmerator: No obstacles show up

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11602]
### Describe the bug

https://www.numuki.com/game/flight-simmerator/
And a physical zip
[flight-simmerator.zip](https://github.com/ruffle-rs/ruffle/files/11780713/flight-simmerator.zip)

When testing the game out on Ruffle, it works fine up until you get in game, at which point nothing except clear skies seem to show up on screen at all, normally there's supposed to be obstacles you need to avoid showing up.

Ruffle logs from the site rehosting the game and running on the web demo.
[ruffle.rs-1687065910354.log](https://github.com/ruffle-rs/ruffle/files/11780716/ruffle.rs-1687065910354.log)
[www.numuki.com-1687065571980.log](https://github.com/ruffle-rs/ruffle/files/11780718/www.numuki.com-1687065571980.log)

![Flight Sim Ruffle](https://github.com/ruffle-rs/ruffle/assets/78768499/467ece7f-46ba-49f5-8c94-89082c40b61d)

### Expected behavior

Obstacles and such should properly be appearing as you fly down.

![Flight Sim Flash](https://github.com/ruffle-rs/ruffle/assets/78768499/112d69b2-4cc9-4c7b-9fa5-15551b73def2)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by waspennator** [comment]
[www.numuki.com-1696991518290.log](https://github.com/ruffle-rs/ruffle/files/12864204/www.numuki.com-1696991518290.log)
Still occuring as of latest nightly, providing log testing with recent nightly.

**Comment by Lord-McSweeney** [comment]
Unimplemented namespace/playerglobal versioning- unimplemented `DisplayObject.z` versioning.

**Comment by waspennator** [comment]
Seems to be working now.
