### ISSUE TITLE
Everything Goes Blank when i start to play the Demolition City game

### ISSUE THREAD

**Issue by DestructMarble250** [ruffle-rs/ruffle#11615]
### Describe the bug

I was trying to play the Demolition City game, but when i press the "Play" button after it's being loaded, the screen goes blank and it does nothing or stops the game.

Steps to reproduce:
1. go to the following link that i'll be sending to you: [/url](https://www.physicsgames.net/game/Demolition_City.html)
2. after it gets loaded, press the play button and you will see that the screen goes blank.

### Expected behavior

I've expecting for the game to work correctly...

### Affected platform

Desktop app

### Operating system

Linux Mint 21.1 Cinnamon

### Browser

Mozilla Firefox

### Additional information

If you try to fix this problem, or if you have any log of it, please reply to me, thanks!

**Comment by Lord-McSweeney** [comment]
Were you playing on the desktop app, using the Firefox extension, or did you go on the site without the extension installed?

**Comment by DestructMarble250** [comment]
> Were you playing on the desktop app, using the Firefox extension, or did you go on the site without the extension installed?

I have the extension installed. but the game doesn't seems to work, btw, here's the full debug info:
`
# Player Info
Allows script access: true
Renderer: Canvas

# Page Info
Page URL: https://www.physicsgames.net/game/Demolition_City.html
SWF URL: https://www.physicsgames.net/swf/demolitioncity.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-03
Channel: nightly
Built: 2023-06-03T00:25:51.214Z
Commit: 2cd518013c74044100407435284e2cf108e96dfe
Is extension: true

# Metadata
width: 700
height: 600
frameRate: 60
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2023431
`

**Comment by Lord-McSweeney** [comment]
> Renderer: Canvas
Did you switch the default renderer through Advanced Options? If not, can you check that webgl is enabled for you?

**Comment by DestructMarble250** [comment]
> > Renderer: Canvas
> 
> Did you switch the default renderer through Advanced Options? If not, can you check that webgl is enabled for you?

well, i think that i had the webgl disabled or not installed yet (i yet still don't know how can i update my graphics drivers in it...) but i think i switched the default renderer...

**Comment by n0samu** [comment]
See https://get.webgl.org/ and please try to enable WebGL in your browser

**Comment by n0samu** [comment]
Hmm, that's strange. Well, make sure you have the renderer set to to "Automatic" in your extension settings.

**Comment by DestructMarble250** [comment]
AH, now i know, i think i had to change the renderer settings!!!, from "Automatic" to "wgpu (using WebGL)", thanks!

**Comment by n0samu** [comment]
Hmm, Automatic should use wgpu over WebGL by default so there shouldn't really be a difference normally. But alright, glad it's resolved
