### ISSUE TITLE
RufflePlayer.setFullscreen(true) not working

### ISSUE THREAD

**Issue by Mennez** [ruffle-rs/ruffle#11633]
### Describe the bug

We are trying to implement a full screen toggle / play button on our website when you visit the game page. I am getting the RuffleEmbed object from the DOM via jquery. Then I call these functions:

```
const rufflePlayer = $("#game ruffle-embed").get(0);
        console.log('player.fullscreenEnabled: ', rufflePlayer.fullscreenEnabled);
        console.log('player.isPlaying: ', rufflePlayer.isPlaying);
        console.log('player.isFullscreen: ', rufflePlayer.isFullscreen);
        rufflePlayer.pause();
        rufflePlayer.play();
```

They do work perfectly fine. However when I use the '[enterFullscreen](https://ruffle.rs/js-docs/master/classes/RufflePlayer.html#enterFullscreen)' or '[setFullscreen](https://ruffle.rs/js-docs/master/classes/RufflePlayer.html#setFullscreen)' functions, I get this error from the inspector (and it is not setting Ruffle to full screen):

```
ruffle:2 Uncaught (in promise) TypeError: Permissions check failed
    at We.enterFullscreen (ruffle:2:313855)
    at We.setFullscreen (ruffle:2:313738)
    at play.js:381:58
```

It says permissions checks failed. However 'rufflePlayer.fullscreenEnabled' returns 'true'...

### Expected behavior

Go to full screen mode when calling the enterFullscreen() or setFullscreen() methods.

### Affected platform

Desktop app

### Operating system

macOS Ventura 13.2.1

### Browser

Google Chrome 114.0.5735.106

**Comment by n0samu** [comment]
`enterFullscreen` is the proper function to use. Browsers will only obey the command to go fullscreen if it comes directly from a user gesture (clicking a button). So make sure that your code is attached directly to a button click event listener.

**Comment by Mennez** [comment]
Ah thanks. I did this with an own custom button now and it works. However I got a error when doing this:

```
let rufflePlayer = $("#game ruffle-embed").get(0);
        if (rufflePlayer.fullscreenEnabled) {
            rufflePlayer.enterFullscreen();
            rufflePlayer.play();
        }
```

Results in this error in the inspector:

```
Uncaught (in promise) TypeError: Permissions check failed
    at We.enterFullscreen (ruffle:2:313855)
    at We.setFullscreen (ruffle:2:313738)
    at ruffle_web-wasm_extensions.js:606:14
    at T (ruffle_web-wasm_extensions.js:223:18)
    at U.n.wbg.__wbg_setFullscreen_85ac797b8823b727 (ruffle_web-wasm_extensions.js:605:76)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::set_fullscreen::h3f0527364218e449 (02c6cd7e:0x7a7878)
    at ruffle_core::display_object::stage::Stage::set_display_state::he5fb849493769752 (02c6cd7e:0x740c53)
    at ruffle_core::player::Player::set_fullscreen::h07812e9e02b596ea (02c6cd7e:0x431d64)
    at ruffle_set_fullscreen (02c6cd7e:0x837da5)
    at O.set_fullscreen (ruffle_web-wasm_extensions.js:447:14)
```

**Comment by n0samu** [comment]
Yes because your code is not running in response to a user gesture

**Comment by Mennez** [comment]
These lines of code are in the click event of a button.

**Comment by n0samu** [comment]
Oh, no idea then. I guess I'd have to see the actual webpage to understand the issue.

**Comment by Mennez** [comment]
Does this help?

```
"click #playBtnMobile": (event, template) => {
        let rufflePlayer = $("#game ruffle-embed").get(0);
        if (rufflePlayer.fullscreenEnabled) {
            rufflePlayer.enterFullscreen();
            rufflePlayer.play();
        }
    },
```

**Comment by n0samu** [comment]
Not really, sorry. That code looks fine
