### ISSUE TITLE
Path of Hercules - Stuck after first level

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11645]
### Describe the bug

https://www.spiele-umsonst.de/azad/downloads/flashgames/thepathofhercules.swf - Despite the typical performance issues and some other smaller issues the game does not proceed to the second level and is stuck. Errors dunno if they relate:

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1060129c }) to handler FunctionObject(FunctionObject { ptr: 0xa97d084 }) : ReferenceError: Error #1069: Property dispose not found on flash.display3D.Program3D and there is no default value.
ruffle_web-wasm_extensions.js:716 ERROR core/src/timer.rs:159 Unhandled AVM2 error in timer callback: ReferenceError: Error #1069: Property dispose not found on flash.display3D.Program3D and there is no default value.
ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xd2a6ba4 }) to handler FunctionObject(FunctionObject { ptr: 0xa97d084 }) : ReferenceError: Error #1069: Property dispose not found on flash.display3D.Program3D and there is no default value.

### Expected behavior

Move on to the next level

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Aaron1011** [comment]
This is working on the latest `master` (though with pretty bad performance).
