### ISSUE TITLE
Blackbeards Assault - Stuck when the level starts

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11644]
### Describe the bug

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/blackbeardsassault.swf - You can click through the menu but right when the game should start the "gate" does not open and load the level

### Expected behavior

Load and Play the level

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
The game's code catches and prints the error, so it's only logged at the Info level:
```
INFO run_frame:run_all_phases_avm2: avm_trace: ## [Tweener] Error: : [object Sprite] raised an error while executing the'onComplete'handler.
 ReferenceError: Error #1069: Property getLineText not found on flash.text.TextField and there is no default value.
        at StoryBoard()
        at dialog_Overworld/()
        at Function/apply()
        at caurina.transitions::Tweener$/

()
        at caurina.transitions::Tweener$/     ()
        at caurina.transitions::Tweener$/onEnterFrame()
```
Looks like the same problem as #10975 and #11208.
(Side note, this game's function names are quite weirdly obfuscated.)

**Comment by desertking** [comment]
Seems to work fine by now. Can be closed. If anyone wants to add what did it...

**Comment by Aaron1011** [comment]
`TextField.getLineText` was stubbed in https://github.com/ruffle-rs/ruffle/pull/14650
