### ISSUE TITLE
Super Crazy Guitar maniac Deluxe 4: level doesn't end at the end of the song

### ISSUE THREAD

**Issue by nivkner** [ruffle-rs/ruffle#11666]
### Describe the bug

SWF URL: http://fgn.cdn.serverable.com/common/flashes/ff/s/super_crazy_guitar_maniac_deluxe_4.swf?d=20120216203039

steps to reproduce: start the game, choose any song, wait for the song to end. the level stays without any more arrows, with whatever animation that was playing in the background by the end.

### Expected behavior

the level ends after the song ends (the exact duration specified during level selection), the score is displayed, and a menu given to choose the next song.

### Affected platform

Desktop app

### Operating system

Linux (Fedora Silverblue 38)

### Additional information

command line used: `ruffle -g gl super_crazy_guitar_maniac_deluxe_4.swf`

using `GeForce GTX 760` with `nouveau` driver.

ruffle nightly: `b3c40ecda107ee33cbc44868fcd7dfdbdc634775`

EDIT: reproduced in https://ruffle.rs/demo/ on `firefox 114.0.2  (flatpak)`

**Comment by Lord-McSweeney** [comment]
I don't see anything relevant logged except possibly the warning `Serialization is not implemented for class other than Object: ByteArrayObject`.

**Comment by nivkner** [comment]
implemented the missing serialization in #11687, didn't fix the issue

**Comment by nivkner** [comment]
added the missing serialization implementation in #11687, didn't fix the issue

**Comment by n0samu** [comment]
Related to this code:
```as
        public function StartPlayback(param1:int = 0) : void
        {
            this.musicChannel = this.music.play(param1);
            this.musicChannel.addEventListener(Event.SOUND_COMPLETE,this.PlaybackFinished);
            this.musicChannel.soundTransform.volume = 0.5;
        }
```
It seems like Ruffle is not firing the SOUND_COMPLETE event, which is strange because it is supposed to be implemented.

**Comment by nivkner** [comment]
checked by tracing `AudioManager::update_sounds` in `core/src/backend/audio.rs` (which produces the event):
after loading, when you press the button to start the game, there is only an early return at
https://github.com/ruffle-rs/ruffle/blob/6d77ff1fc41aa34848188aa79ddb8c283671df4a/core/src/backend/audio.rs#L315-L317

**Comment by nivkner** [comment]
confirmed that the following diff fixes the issue (as well as an audio glitch that was keeping an electric guitar sound from the failure screen in the main menu):

```diff
@@ -312,10 +312,6 @@ impl<'gc> AudioManager<'gc> {
 
     /// Update state of active sounds. Should be called once per frame.
     pub fn update_sounds(context: &mut UpdateContext<'_, 'gc>) {
-        let Some(root) = context.stage.root_clip() else {
-            return
-        };
-
         // We can't use 'context' to construct an event inside the
         // 'retain()' closure, so we queue the events up here, and fire
         // them after running 'retain()'
@@ -340,15 +336,17 @@ impl<'gc> AudioManager<'gc> {
                     object.set_position(context.gc_context, duration.round() as u32);
 
                     // Fire soundComplete event.
-                    context.action_queue.queue_action(
-                        root,
-                        crate::context::ActionType::Method {
-                            object: object.into(),
-                            name: "onSoundComplete",
-                            args: vec![],
-                        },
-                        false,
-                    );
+                    if let Some(root) = context.stage.root_clip() {
+                        context.action_queue.queue_action(
+                            root,
+                            crate::context::ActionType::Method {
+                                object: object.into(),
+                                name: "onSoundComplete",
+                                args: vec![],
+                            },
+                            false,
+                        );
+                    }
                 }
 
                 if let Some(object) = sound.avm2_object {
```
