### ISSUE TITLE
Full Screen on mobile not working with enterFullscreen(), but is working in-game and on iPads!

### ISSUE THREAD

**Issue by Mennez** [ruffle-rs/ruffle#11680]
### Describe the bug

We would like to make some of our old AS2 flash games playable on mobile phones. I've just updated our website with 3 games which are working completely with mouse / touch controls.

The full screen option works perfectly fine in the game. It also works in the browser (also when inspecting it as an iPhone for example). However once you try to go to full screen with my own custom made button on a iPhone, it does not work. Console logging of **rufflePlayer.fullscreenEnabled** results in 'false'. However, when running the games on an iPad (mini), it works perfectly fine and **rufflePlayer.fullscreenEnabled** results in 'true'.

<img width="1479" alt="Screenshot 2023-06-22 at 17 37 49" src="https://github.com/ruffle-rs/ruffle/assets/6833463/ec137ae7-756f-42eb-9f77-d4efaa2de7ec">
<img width="1278" alt="Screenshot 2023-06-22 at 17 26 00" src="https://github.com/ruffle-rs/ruffle/assets/6833463/fb1c35cc-270d-401e-8e6e-bb3ce09adebd">
<img width="1192" alt="Screenshot 2023-06-22 at 17 25 31" src="https://github.com/ruffle-rs/ruffle/assets/6833463/88b1ee37-184e-4090-9bfd-73bd72880ae8">

I would really really like to be able to have an external full screen option available for mobile devices as well. Ruffle Player is ready for this when going 'full screen' in the game itself, so technically it should not be a problem.

An example can be found here: [Clashflash.com game](https://www.clashflash.com/play/invasion)

Any way to fix this?

### Expected behavior

Ruffle's fullscreenEnabled should return true as well on mobile phones and enterFullScreen() should enter full screen on mobile phones' web browsers (like iOS Safari).

### Affected platform

Browser's extension

### Operating system

iOS 16.5

### Browser

Safari

**Comment by desertking** [comment]
As far as i know it's apple choice that fullscreen does not work on iphone but on ipad.

**Comment by danielhjacobs** [comment]
Yeah, Unfortunately you'll need to take this up with Apple itself: <https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled#browser_compatibility>

**Comment by desertking** [comment]
I think Apple did it on purpose to not give other "apps" "games" the experience to have a native like feeling... At least they cut off the edges of the browser when switching to landscape.

**Comment by Mennez** [comment]
Thanks for the reply's! Too bad Apple made this decision. Let's hope they will maybe support this in the near future...
