### ISSUE TITLE
Cross website now removed - please save back my now secure website again, sorry

### ISSUE THREAD

**Issue by aluetz** [ruffle-rs/ruffle#11708]
Im sorry, I have had a new website with cross URLs. I have them removed. And now, all should be correct with no cross URL. Thanks a lot to correct my domaines as secure:

www.rufflesafe.com
www.ruffleshop.de
www.ruffle.zip        ( is just corrected and has had wrong URS from php to swf  with implemented jpg 800 x 450 pixels 6000 items
www.ruffehops.com
www.ruffleapps.com
www.rufflelight.com
www.rufflesafe.de
www.langenthaler.com
www.langenthaler.ch
www.schweizerinnen.ch
www. schlossthunstetten.ch
www.kirchelangenthal.ch
www.stadtlangenthal.ch

My father and I are very happy to set alle back to secure. Thanks a lot to the GitHub Teams.
Andreas Lützenberger
support@a4whosting.ch

**Comment by aluetz** [comment]
Im sorry, I have had a new website with cross URLs. I have them removed. And now, all should be correct with no cross URL. Thanks a lot to correct my domaines as secure:

www.rufflesafe.com
www.ruffleshop.de
www.ruffle.zip        ( is just corrected and has had wrong URL from php to swf  with implemented jpg 800 x 450 pixels 6000 items
www.ruffehops.com
www.ruffleapps.com
www.rufflelight.com
www.rufflesafe.de
www.langenthaler.com
www.langenthaler.ch
www.schweizerinnen.ch
www. schlossthunstetten.ch
www.kirchelangenthal.ch
www.stadtlangenthal.ch

My father and I are very happy to set alle back to secure. Thanks a lot to the GitHub Teams.
Andreas Lützenberger
support@a4whosting.ch

**Comment by n0samu** [comment]
Closing in favor of #11706
