### ISSUE TITLE
Ruffle.zip is corrected. It's only a secure duplicate then as like as www.rufflesafe.com - please set all the toplevels free again.

### ISSUE THREAD

**Issue by aluetz** [ruffle-rs/ruffle#11711]
Im sorry, I have had a new website with cross URLs. I have them removed. And now, all should be correct with no cross URL. Thanks a lot to correct my domaines as secure:

www.rufflesafe.com
www.ruffleshop.de
www.ruffle.zip        (is just corrected and has had wrong URL from php to swf with implemented jpg 800 x 450 pixels 6000 items - now it's empty and then it will be only a duplicate as like as www.rufflesafe.com with better metatags)
www.ruffehops.com
www.ruffleapps.com
www.rufflelight.com
www.rufflesafe.de
www.langenthaler.com
www.langenthaler.ch
www.schweizerinnen.ch
www.schlossthunstetten.ch
www.kirchelangenthal.ch
www.stadtlangenthal.ch

My father and I are verry happy to set alle back to secure. Thanks a lot to the GitHub Teams.
Andreas Lützenberger
support@a4whosting.ch

**Comment by n0samu** [comment]
Closing in favor of #11706
