### ISSUE TITLE
(feature request) Built-in updater

### ISSUE THREAD

**Issue by TemaisgameNoobas** [ruffle-rs/ruffle#11744]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

This feature is about built-in Android app updater. It updates Ruffle, and other things if they are present in the update.
This would be useful, if you don't want to uninstall the app and install again.
Since Ruffle compiles almost every day, it would be useful so you don't have to uninstall and install again everyday.
In the UI, there would be an option to disable update check.
This feature would be only on Android, but if you want you could do it in the desktop app too.

**Comment by n0samu** [comment]
This feature request doesn't make much sense when we don't even have an official Android app yet.

**Comment by TemaisgameNoobas** [comment]
> This feature request doesn't make much sense when we don't even have an official Android app yet.

this is just a request, you could do that when there would be an android app

**Comment by Lord-McSweeney** [comment]
In that case, please request it on the Github Issues page for the unofficial and unstable Android app: https://github.com/torokati44/ruffle-android
