### ISSUE TITLE
Duck Life 1: Line issue bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11740]
### Describe the bug

https://www.kongregate.com/games/wixgames/ducklife
Posting here cause it's seperate from the filter issue on my S22, when running the game on steam deck, I can see various line glitches like in the site logos or during the opening cutscenes.

![Screenshot_20230625_192121](https://github.com/ruffle-rs/ruffle/assets/78768499/165d56d6-be0b-4b40-9127-fca748859a54)

### Expected behavior

The lines shouldn't be there and it should be looking normal.

### Affected platform

Browser's extension

### Operating system

SteamOS

### Browser

Edge 114

### Additional information

Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Custom GPU 0405 (vangogh LLVM 15.0.7), OpenGL 4.6)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 8192, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

Page Info
Page URL: https://game73523.konggames.com/games/WixGames/ducklife/frame/77fda1f8-38d1-4cea-bfdf-a2381bfba4de/?kongregate_host=www.kongregate.com
SWF URL: https://game73523.konggames.com/gamez/0007/3523/live/ducklife_kong.swf?kongregate_game_version=1267983078

Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
Platform: Linux x86_64
Has touch support: true

Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-26
Channel: nightly
Built: 2023-06-26T00:19:41.365Z
Commit: 8c40e97ab55590c4d78de37a3dfb51624d005062
Is extension: false

Metadata
width: 640
height: 480
frameRate: 50
numFrames: 57
swfVersion: 10
backgroundColor: #A5D8FF
isActionScript3: false
uncompressedLength: 1669267

**Comment by n0samu** [comment]
@waspennator says on Discord that the problem does not occur in the desktop app, only on web.

**Comment by waspennator** [comment]
@n0samu Excellent news! Latest Steamos update dropped, so I figured id retest this issue on edge and it seems totally fixed now from what I'm seeing.
