### ISSUE TITLE
Ninja Painter: Visual Issues

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11743]
### Describe the bug

https://armorgames.com/play/11591/ninja-painter
Game seems to be playable now, but it still seems to have some minor visual issues.

1: When on the level select screen, the levels that can be selected flicker alot instead of just being blacked out until you unlock access to them.
![Ninja Painter 1](https://github.com/ruffle-rs/ruffle/assets/78768499/6fb60dd1-f13d-4e37-9cc4-2b1d56f82798)

2: On the stage completed screen: it shows you earned 3 stars even if you don't collect a single star throughout the level.

3: If you hover over the level icon for a level, it shows the high score you got for a level is some high number like 999999.

### Expected behavior

The levels icons shouldn't be flickering, the stars shown during level clear should be accurate, and the record score should be accurate.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 114

**Comment by n0samu** [comment]
The stars issue is related to filter effects (see https://github.com/ruffle-rs/ruffle/issues/5538#issuecomment-1606261132). The score display issue is the same as #2181.

**Comment by n0samu** [comment]
I think the flickering level icons are related to the unimplemented bevel filter, which would make the flickering part invisible. The same problem also shows up with the locked achievements on the achievements screen, which also have a bevel filter applied.

**Comment by waspennator** [comment]
Testing out with the Blend and Dropshadow PR, the level icons still seem to be noticably flickering compared to flash.

**Comment by waspennator** [comment]
PR got updated, the level select flickering and stars issues are now 100% solved now, all that remains is the high scores when hovering over levels being incorrect.

**Comment by n0samu** [comment]
Closing in favor of #2181 for the remaining score display issue
