### ISSUE TITLE
Crash on farm-frenzy-3.swf

### ISSUE THREAD

**Issue by zachs18** [ruffle-rs/ruffle#11759]
### Describe what you were doing

https://data.gameflare.com/games/1208/fRDBYET5apjPb1.swf (downloaded and renamed).

0. (Have an integrated graphics card with 256M or less of VRAM. Unsure if this is related; I don't have access to another computer to test with atm.)
1. Start the game.
2. Open any level.
3. Place several pieces of grass.

This crash only occurs as of `nightly-2023-06-27`; I cannot reproduce it on `nightly-2023-06-26`. Specifically, I cannot reproduce it on commit 3057aa59d or before, but I can reproduce it on commit e37958351 and after

https://github.com/ruffle-rs/ruffle/assets/8355914/441080c1-aefa-4780-af60-7e154c4c9a18

### What does the crash message say?

panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    Not enough memory left

', /home/zachary/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5

### Ruffle Version

0.1.0-nightly (96e3d36a6ef22d233bed431dd23868d756b095c4 2023-06-26)

### Affected platform

Desktop app

### Operating system

Ubuntu 22.04 (jammy) [64-bit]

### Additional information

Filename: farm-frenzy-3.swf

### AVM2 Callstack
```
	at flash.display::BitmapData/flash::display::BitmapData::draw()
	at org.flintparticles.twoD.renderers::BitmapRenderer/drawParticle()
	at org.flintparticles.twoD.renderers::BitmapRenderer/renderParticles()
	at org.flintparticles.common.renderers::SpriteRendererBase/updateParticles()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD Unknown (RADV RENOIR)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "radv"
Adapter Driver Info: "Mesa 22.2.5-0ubuntu0.1~22.04.3"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by n0samu** [comment]
Yeah it may be hardware or OS-related. I can't reproduce it on my Windows 10 PC (also using Vulkan)

**Comment by zachs18** [comment]
I can no longer reproduce this on the same hardware/OS on current nightly or even on the original `nightly-2023-06-27`, perhaps it was a driver issue or something 🤷.
