### ISSUE TITLE
Ruffle Desktop cannot display the translation text when the System Display Language is not latin

### ISSUE THREAD

**Issue by lvyitian** [ruffle-rs/ruffle#11763]
### Describe the bug

Steps to reproduce:
  1.Set the System Display Language to be any non-latin language
  2.Launch the ruffle desktop
Ruffle Desktop cannot display the translation text when the System Display Language is not latin.

### Expected behavior

The translation text should be displayed properly

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Are you sure it is an encoding issue? As far as we know, the problem is just that the font we're using doesn't support CJK characters or Arabic. See #11370

**Comment by lvyitian** [comment]
> Are you sure it is an encoding issue? As far as we know, the problem is just that the font we're using doesn't support CJK characters or Arabic. See #11370

I'm not sure, it is possible to be a font issue.

**Comment by n0samu** [comment]
Fixed by #11924
