### ISSUE TITLE
Error on Doom Triple Pack

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11792]
Game page: https://www.newgrounds.com/portal/view/470460/format/flash?emulate=flash

The problem occurs after reloading the game and starting it for a second time.

# Error Info
Error name: Error
Error message: panicked at 'Reference still held to rc', /home/runner/.cargo/git/checkouts/rust-flash-lso-7db697fbf6bd96f3/8376453/flash-lso/src/amf3/read.rs:260:18

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1688039989%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F470000%2F470460_DoomGame.swf%3F1417242233%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22649d86b087056%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A800%2C%22height%22%3A500%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F470000%2Fflash_470460_card.png%3Ff1601082652%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/470000/470460_DoomGame.swf?1417242233

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-28
Channel: nightly
Built: 2023-06-28T00:20:07.985Z
Commit: 9f67d3c23887170427a8e62c33436009168bbee8
Is extension: false

# Metadata
width: 960
height: 600
frameRate: 35
numFrames: 2
swfVersion: 17
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26164748

**Comment by Lord-McSweeney** [comment]
Note that this is mentioned near the relevant spot:

https://github.com/ruffle-rs/rust-flash-lso/blob/3669a352c14192d0d301e594ae6047ae99725006/flash-lso/src/amf3/read.rs#L254

**Comment by n0samu** [comment]
This was fixed by something in [nightly 2023-11-11](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-11-11) (probably #13940)
