### ISSUE TITLE
Ruffle is on but flash does not run

### ISSUE THREAD

**Issue by priming54** [ruffle-rs/ruffle#11804]
![Screenshot 2023-06-29 165946](https://github.com/ruffle-rs/ruffle/assets/115122085/f5766ace-ea16-494e-9cb3-6064db633bd1)

**Comment by danielhjacobs** [comment]
https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#when-browsing-the-wayback-machine-i-see-a-box-saying-adobe-flash-player-is-no-longer-supported
