### ISSUE TITLE
Newgrounds Movie Crash

### ISSUE THREAD

**Issue by vfrufflissue** [ruffle-rs/ruffle#11809]
### Describe what you were doing

Attempted to view Newgrounds flash animation, crashed partway through.
[https://www.newgrounds.com/portal/view/310401](url)

### What does the crash message say?

"Ruffle has encountered a major issue whilst trying to display this Flash content."

### Ruffle Version

0.1.0

### Affected platform

Online demo

### Operating system

Chrome OS Version 114.0.5735.119 (Official Build) (64-bit)

### Additional information

Debug info:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1688039989%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F310000%2F310401_PICO_PICO_PICO_BACKUP.swf%3F1171978298%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%22649ed012671cd%22%2C%22NewgroundsAPI_SessionID%22%3A%220jXxf3BQC7F8NJvfdIOe1d9747147ba1399b87d8572606f42c5dc56ad28drtlY%22%2C%22NewgroundsAPI_UserName%22%3A%22VelarFricative%22%2C%22NewgroundsAPI_UserID%22%3A15760118%2C%22ng_username%22%3A%22VelarFricative%22%7D%2C%22width%22%3A450%2C%22height%22%3A250%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F310000%2Fflash_310401.png%3Ff1364556480%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-06-28
Channel: nightly
Built: 2023-06-28T00:20:07.985Z
Commit: 9f67d3c23887170427a8e62c33436009168bbee8
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Can you click "View Error Details" and tell us what it says?

**Comment by vfrufflissue** [comment]
There is no such option

**Comment by n0samu** [comment]
Can you send a screenshot of the error screen then?

**Comment by n0samu** [comment]
Closing due to insufficient information
