### ISSUE TITLE
Can not right click - debug window appears

### ISSUE THREAD

**Issue by jentak314** [ruffle-rs/ruffle#11810]
### Describe the bug

This game is controlled by clicking mouse, both left and right button. If I right click, instead of game detecting it, a debug window appears.

It happens immediately in tutorial.

https://www.superhry.cz/hra/2842-stick-war-2

![stick_wars_ruffle](https://github.com/ruffle-rs/ruffle/assets/138238090/4e999334-dd8a-4c75-ac58-f3b79eb582a3)

### Expected behavior

.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
Right-click controls are unsupported; see later comments in #11009. Closing in favor of #10288.
