### ISSUE TITLE
VP6 regression after merging FLV PR into master, broken ~150 NSFW games

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#11822]
### Describe the bug

Before the panic, logs were flooded by chain of `ruffle_core::display_object::video: Got error when seeking to video frame 1-45: Decoder error: InvalidData`

and then `thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2'`

Link: https://tiarawhy.com/swf/TFH_V1.swf

### Expected behavior

Games should work as usual

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Browser

Firefox Nightly

**Comment by torokati44** [comment]
Same as #11823, I bisected this regression to c86360a1, merged as part of #10756.
