### ISSUE TITLE
Random functions return the same values every time a file is run afresh

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1182]
Attached two samples using Math.random() and random():
[rand.zip](https://github.com/ruffle-rs/ruffle/files/5230817/rand.zip)

**Comment by Herschel** [comment]
Waiting for a new version of `rand` to get published on crates.io so we can add the `js` feature for `getrandom`, allowing us to call `from_entropy`. Alternatively we could just supply the seed to core from each platform.

**Comment by Justin-CB** [comment]
The way to get basic randomization(at least in C) is to seed the PRNG with the current time(cast to an integer somehow).

**Comment by sombraguerrero** [comment]
> The way to get basic randomization(at least in C) is to seed the PRNG with the current time(cast to an integer somehow).

I do not think it is the case that we don't know how to seed. It is instead the case that we are currently unable to seed in the preferred fashion due to lack of library features. I believe we are trying to avoid a lot of copy pasta, hence the wait.

**Comment by Dungeonation** [comment]
Didn't know this was reported already, yeah. Random integers are a big part of my game and while it doesn't render it unplayable, integers generated stay the same sometimes.

**Comment by Poopooracoocoo** [comment]
> Waiting for a new version of `rand` to get published on crates.io so we can add the `js` feature for `getrandom`, allowing us to call `from_entropy`. Alternatively we could just supply the seed to core from each platform.

btw what happened to this? the PR that closed this a workaround, or is it fully fixed? for some strange ass reason this was on my mind.

**Comment by sombraguerrero** [comment]
> > Waiting for a new version of `rand` to get published on crates.io so we can add the `js` feature for `getrandom`, allowing us to call `from_entropy`. Alternatively we could just supply the seed to core from each platform.
> 
> btw what happened to this? the PR that closed this a workaround, or is it fully fixed? for some strange ass reason this was on my mind.

Judging by the comments in the PR, this was definitely the latter (workaround), propagating across core. I think a more fluid implementation should still be on the roadmap.

**Comment by Herschel** [comment]
The PR that closed this is a good fix, but it would it's still a TODO to provide a way for a set seed (the TAS people would like this!).
