### ISSUE TITLE
Outpost Haven - cannot start

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#11835]
### Describe the bug

flash: 

https://github.com/ruffle-rs/ruffle/assets/103858019/8baa0f52-97ec-4ef2-9eab-43b02df064d6

ruffle:

https://github.com/ruffle-rs/ruffle/assets/103858019/b46eb40b-0d0d-4229-b523-19e3144e5165

### Expected behavior

the game should be playable

### Affected platform

Desktop app

### Operating system

windows 10 

### Additional information

[outpost-havenMTQwOQ.zip](https://github.com/ruffle-rs/ruffle/files/11926918/outpost-havenMTQwOQ.zip)

**Comment by Lord-McSweeney** [comment]
This needs `TextField.getLineText`.

**Comment by n0samu** [comment]
Fixed by #14650
