### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by gabogabogab** [ruffle-rs/ruffle#11830]
# Error Info
Error name: Error
Error message: Error loading movie: Couldn't read SWF: Invalid data: Invalid SWF
Error stack:
```
Error: Error loading movie: Couldn't read SWF: Invalid data: Invalid SWF
    at Ke.load (https://ruffle.rs/demo/index.js:2:275193)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa Intel(R) HD Graphics 2000 (SNB GT1)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-01
Channel: nightly
Built: 2023-07-01T00:19:59.882Z
Commit: 29a5c6a4cd9918d5e1eb89cc42ccd03d4e920931
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Can you upload the SWF you were using for this?

**Comment by gabogabogab** [comment]
sorry for not answering XD, here the swf:https://www.mediafire.com/file/ygbdfh5ydgpgzu0/pvz_9_15.swf/file

**Comment by Lord-McSweeney** [comment]
This is happening because the file is corrupt (not actually a SWF file). Here are the contents of the file:
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<h1>403 Forbidden</h1>
<ul>
<li>Code: AccessDenied</li>
<li>Message: Access Denied</li>
<li>RequestId: BB8684B6B252D5FF</li>
<li>HostId: mkgtGPXVuEa8J1GtleAJ0I7mbPsY5V2zX4WBOCt0JcoWpEmq+XH/eGGW2fRXEj1vJrFNtL60c3s=</li>
</ul>
<hr/>
</body>
</html>
```
