### ISSUE TITLE
A lot of Flash animations never get past the play button, just black screen.

### ISSUE THREAD

**Issue by PsychoGoldfishNG** [ruffle-rs/ruffle#1185]
**Example Submission:** https://www.newgrounds.com/portal/view/474093

**Console output (Chrome 85.0.4183.102 64-bit)**:
![ruffle_issue_blackscreen](https://user-images.githubusercontent.com/54905078/93498189-ae555200-f8ce-11ea-9f57-20433202ee29.png)

**OS:** Windows 10 (build 18363)

PC Specs:
https://www.newegg.com/aluminum-black-msi-ge-series-ge65-raider-431-gaming-entertainment/p/N82E16834155330?Item=N82E16834155330

**Comment by Dinnerbone** [comment]
Thanks for the report! We should more gracefully fall back to canvas if we get an error during webgl creation 🤔 

Do you have any extensions running that may try to block fingerprinting or webgl from working?

Failing that, it looks like maybe we're asking for capabilities your card can't provide, and we should handle this better.

**Comment by Dinnerbone** [comment]
@Herschel can we get a webgl label please?

**Comment by PsychoGoldfishNG** [comment]
I'm not sure why it didn't occur to me to test this in other browsers, but there are no problems in Edge or Firefox on this same hardware, it's specifically a Chrome issue.   I do have AdBlock Plus installed, but it's disabled for Newgrounds, so not sure if that would be causing any issue or not.

**Comment by Herschel** [comment]
Worked through it with @PsychoGoldfishNG and it looks like hardware acceleration was disabled in Chrome; re-enabling it fixed the issue. Interestingly, here's what it caused even when using the CPU fallback:
WebGL MAX_SAMPLES still returned 4 (up to 4x MSAA)
Creating the color renderbuffer with 4x MSAA succeeded
Creating the stecil renderbuffer with 4x MSAA failed with "samples out of range"

#1216 catches the error and falls back to canvas in this case which is probably the correct behavior, but it'd be nice to explicitly check if hardware acceleration is available.

**Comment by Herschel** [comment]
Fixed by #1216.
