### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by FlamedDogo99** [ruffle-rs/ruffle#11869]
# Error Info
Error name: Error
Error message: Error loading movie: Couldn't read SWF: Invalid data: Invalid SWF
Error stack:
```
@https://ruffle.rs/demo/index.js:2:275202
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-03
Channel: nightly
Built: 2023-07-03T00:19:40.432Z
Commit: 768eaa1a01e7a5a571cd5e99fb560fa37a02a1dc
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Hi, what SWF were you trying to play when the error occurred?

**Comment by n0samu** [comment]
No information provided, closing

**Comment by FlamedDogo99** [comment]
Sorry for the slow response. I was running cat ninja: quest for the magical energy crystals.

**Comment by n0samu** [comment]
@FlamedDogo99 can you provide a link or attachment to the SWF file and tell us where you got it from?

**Comment by FlamedDogo99** [comment]
Of course! http://arcade.flashgamearchive.com/FILES/Cat_Ninja.bytes

**Comment by n0samu** [comment]
Thanks! Are you on an iPad or Mac? If you're on a Mac, please try another browser such as Chrome or Firefox and let me know if it works there.

**Comment by FlamedDogo99** [comment]
Tried Chrome, Firefox and Safari on Mac. All iOS browsers are just a reskinned safari, which isn't work as well.

**Comment by n0samu** [comment]
Can you try redownloading the file and renaming the extension to .swf? Maybe something went wrong when you downloaded it last time.
