### ISSUE TITLE
Onda: Animacuentos (Cuentos - LL & LLSE) FLV Playback

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#11862]
### Describe the bug

Now that FLV support is coming in, I now realize that this section of the platform controls its playback via a handful of MX functions, (NCManager). Essentially, this section plays a FLV in the upper left and synchronizes it with SWF content to the right and below using a series of timeouts and seek-points.
![toto_debug](https://github.com/ruffle-rs/ruffle/assets/24618934/91858c4d-457e-4612-b96a-f7960545e7ad)
![toto_screen](https://github.com/ruffle-rs/ruffle/assets/24618934/856280a7-1cf5-4472-a12a-edf03e7680d6)
https://drive.google.com/drive/folders/163YKuJK_4Hf8bFpo5tAYp8mgzfVp74y8?usp=sharing

So thee FLV content loads, but it cannot be interacted with due to lack of support of the content within mx.video.NCManager

### Expected behavior

FLV should play with the corresponding SWFs being able to synchronize at their respective seek points.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chromium based or Firefox

**Comment by Lord-McSweeney** [comment]
Possibly the same thing that's happening here: http://labcenter.dnalc.org/labs/dnaextraction/dnaextraction_d.html

**Comment by sombraguerrero** [comment]
After spinning a VM in Azure to test this in a cleaner environment and then also testing it again on the staging site, it seems (separate from the problem this issue is meant to tackle), that there is a race condition of some kind where the FLV and the surrounding Flash content simply takes too long to load and it causes the FLV to just sort of fail to completely load. If you refresh the page, it will eventually come.
A testing site has been spun up at http://20.232.158.68/[toto](http://20.232.158.68/toto/)/

**Comment by n0samu** [comment]
I found that the Flash-compatible webpage is here: http://20.232.158.68/toto/flash.html
This can make testing/comparison easier.

**Comment by kmeisthax** [comment]
mx.video.VideoPlayer has a bunch of calls to unimplemented NetStream methods, I'm not sure if any of them actually get called though. It also sets up event handlers for `onMetaData` and `onCuePoint`, which are both `ScriptData` handlers that don't get called yet.

The FLV in the project does not have any `onCuePoint` calls, but it does have an ordinary `onMetaData` block. Not sure if MX requires the metadata block actually exist in order to play FLVs - bare `Video` objects will totally play movies without a metadata block.

This will need more investigation.

**Comment by sombraguerrero** [comment]
I would suspect that since this particular application relies on syncing particular frames at particular points, that mx requires timestamp data in order to know how and where to seek.

**Comment by sombraguerrero** [comment]
> I found that the Flash-compatible webpage is here: http://20.232.158.68/toto/flash.html This can make testing/comparison easier.

This will now be http://tototesting.eastus.cloudapp.azure.com/toto/flash.html

**Comment by torokati44** [comment]
I think the video and seeking part of this is fixed now - the remaining issue is that the SWF in the top right corner is obscured, unless zoomed in...?

**Comment by sombraguerrero** [comment]
Oh, no, that's just pathing stupidity with Azure Storage - ignore that 😛. 
If you substitute index.html for flash.html, that's my self-hosted version where I have the pathing adjusted for said stupidity, it works as expected there. Unsurprisingly, the synchronization does get out of whack if the tab/window defocuses, but that's not unlike a lot of our other stuff.
