### ISSUE TITLE
Box racers, repeating loading screen

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#11879]
### Describe the bug

The game Box Racers does not move beyond the loading screen, staying in an eternal loop:

http://www.freeworldgroup.com/games8/gameindex/boxracers.htm

### Expected behavior

Game should load as normal and get into the main menu. 

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
```
WARN Serialization is not implemented for class other than Object: ScriptObject(ScriptObject { name: localSave::PlayerInfo, ptr: 0x38301a4 })
WARN Got AVM2 error RustError("Error: Invalid object") when attempting to assign symbol class Main
```
which leads to a cascading chain of errors that stops the load process.

**Comment by freeworldgroup** [comment]
working ok now
