### ISSUE TITLE
Puzzle Freak 2 - very laggy when playing different puzzles in game

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#11883]
### Describe the bug

Game freezes or goes very slow when you get into the game and play individual puzzles as you travel around the game board. This was not the case a while back with previous updates. Appears like an update has affected the game in a negative way.

http://www.freeworldgroup.com/games6/gameindex/puzzle-freak-2.htm

### Expected behavior

As you travel around the board, new puzzles are loaded quickly and can be played. 

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by markman12345** [comment]
the game works fine for me

**Comment by freeworldgroup** [comment]
The issue seems to be resolved if you oscillate between full screen view and windowed view. Hopefully this can be fixed, as the game was working pretty well before this new issue turned up.

**Comment by freeworldgroup** [comment]
seems fine now
