### ISSUE TITLE
The menu bar is garbled from Nightly 2023-06-29 to the latest version

### ISSUE THREAD

**Issue by ShiN-K-278** [ruffle-rs/ruffle#11885]
### Describe the bug

The menu bar is garbled from Nightly 2023-06-29 to the latest version

![image](https://github.com/ruffle-rs/ruffle/assets/52000350/f06f8345-5b19-410e-9c96-ad6936a7d0b4)

### Expected behavior

![image](https://github.com/ruffle-rs/ruffle/assets/52000350/8c7d1768-03db-46ae-8d8c-e2b671fc25a1)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
This is because of your system locale, it's most likely Chinese/Arabic/Korean/Japanese. Changing it to English will fix the issue.

**Comment by n0samu** [comment]
This will be fixed by #11370 once it is finished and merged.

**Comment by n0samu** [comment]
This is fixed now!
