### ISSUE TITLE
stick figure badminton 3 - names of players are cut in half

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#11881]
### Describe the bug

![1](https://github.com/ruffle-rs/ruffle/assets/98996990/2499bc71-e3b6-43d8-80c9-f7af1bce0d66)
[1.zip](https://github.com/ruffle-rs/ruffle/files/11943721/1.zip)

### Expected behavior

![2](https://github.com/ruffle-rs/ruffle/assets/98996990/b0ea998f-419d-48c2-bdb7-6b1cf35b75e8)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Croworbit** [comment]
why is text like this with Ruffle
I see it all the time on oso many other games too
