### ISSUE TITLE
The Binding of Isaac: Wrath of the Lamb very slight glitch.

### ISSUE THREAD

**Issue by jackachu58** [ruffle-rs/ruffle#11903]
### Describe the bug

Alright so basically this isn't anything game breaking, from what I've seen you can play the whole wrath of the lamb eternal edition swf with ruffle, but basically I'm seeing one difference from ruffle and adobe flash player, is that the shadows are weird boxes and not rounded.

Basically on the menu they have shadows for the head and hand, basically those aren't rounded, they are just squares/rectangles.

I do have the steam version, but also like to play the browser edition (literally the same exact game, just one running on ruffle and the other an exe flash game, and saves progress to my pc.

anyway here is the link I used, if you download it and run it in the actual flash player, or on some other browser like waterfox or something (waterfox classic has flash player) it runs without this bug.
         
![image](https://github.com/ruffle-rs/ruffle/assets/38389811/c4c5f80d-a40b-41cf-aa7a-de39505950ee)
![image](https://github.com/ruffle-rs/ruffle/assets/38389811/dc4b4d01-44c7-41e9-96a4-ed5516df1bd5)
![image](https://github.com/ruffle-rs/ruffle/assets/38389811/458bed26-29b4-4e82-aa1e-55d9a9b9dfb3)
![image](https://github.com/ruffle-rs/ruffle/assets/38389811/ee6c997c-0cb0-4c87-8d47-21e48197b385)
[https://archive.org/download/tboiwotl-v1.666/tboiwotl-v1.666.swf](https://archive.org/download/tboiwotl-v1.666/tboiwotl-v1.666.swf)

### Expected behavior

when I'm playing using actual flash player or on the steam version (With wrath of the lamb DLC, it was like 2 dollars so i decided to get it) it shows a big round shadow, but in ruffle, its just a rectangle.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 114.0.5735.199 (Official Build) (64-bit)

### Additional information

from what I can tell, I don't see any problem with the game during gameplay, but I still thinks its important to address such things like this, because they are very important (or at least to me) for ruffle.

I couldn't find anyone else talking about this, but someone might have already mentioned the same bug in a different game, I tried, I couldn't find one lol so yeah if this is something already known about, my bad lol.

**Comment by n0samu** [comment]
Filters are currently being worked on and aren't perfect yet. This will likely improve soon.

**Comment by Lord-McSweeney** [comment]
Fixed by #11878.
