### ISSUE TITLE
Monopoly: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11902]
### Describe the bug

Link to SWF: https://www.spiele-kostenlos-online.de/static_games/monopoly3/monopoly.swf

[This German Monopoly game](https://www.spiele-kostenlos-online.de/brettspiele/wuerfelspiele/monopoly/) shows nothing but a black screen. The error is:
```
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x24cad1e6e68 }) to handler FunctionObject(FunctionObject { ptr: 0x24ca28a9168 }) : ReferenceError: Error #1069: Property nodeValue not found on flash.xml.XMLNode and there is no default value.
        at com.ea.monopolyclassic.common::StringManager$/parseStringsXML()
        at com.ea.monopolyclassic.common::StringManager$/loadComplete()
```

### Expected behavior

The game should start.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This was originally reported by a user on Discord.

**Comment by vollcom** [comment]
THX a lot :) !!!!
