### ISSUE TITLE
Papas Pastaria - tomato sauce is invisible

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#11928]
### Describe the bug

I noticed new regression in Pastaria, when I use tomato sauce, the texture is invisible while pouring. It will become visible at the end. This was working before.
The last working build is Nightly 2023-06-23. Probably caused by cacheAsBitmap - https://github.com/ruffle-rs/ruffle/pull/11638

SWF - https://data.gameflare.com/games/4643/LZA1w2C4888Z3a.swf

![image](https://github.com/ruffle-rs/ruffle/assets/10010569/5a12f53a-6939-422f-a573-875466a87956)
![image](https://github.com/ruffle-rs/ruffle/assets/10010569/61c77f99-c712-47ab-91d1-033334c8ea31)

### Expected behavior

visible tomato sauce while pouring.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by hoodamath** [comment]
i recently tested a new build of 8-6 and it is still not showing
