### ISSUE TITLE
Crash on BloonsTD5AS3v2DOT.swf

### ISSUE THREAD

**Issue by Aloso** [ruffle-rs/ruffle#11947]
### Describe what you were doing

I downloaded a flash game and opened it in Ruffle (playing it in the browser was way too laggy). In the middle of a level it suddenly crashed.

The flash game can be downloaded from [this link](https://cache.spiele-kostenlos-online.de/flashgames/BloonsTD5AS3v2DOT.swf). When opening, a warning appears that Ruffle doesn't yet support all of ActionScript 3, but the game works reliably (apart the crash).

### What does the crash message say?

panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    Not enough memory left

', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:3019:5

### Ruffle Version

0.1.0-nightly (c60742428c75fe42476dfe66d6f4f215bf8b773f 2023-07-06)

### Affected platform

Desktop app

### Operating system

Manjaro 23.0.0 (UltimaThule) [64-bit]

### Additional information

Filename: BloonsTD5AS3v2DOT.swf

### AVM2 Callstack
```
	at flash.display::BitmapData/flash::display::BitmapData::draw()
	at display::Frame/drawRotated()
	at display::Clip/drawRotated()
	at towers::Tower/draw()
	at framework::Scene/draw()
	at levels::Level/draw()
	at Main/frame()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD Radeon Graphics (RADV RENOIR)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "radv"
Adapter Driver Info: "Mesa 23.0.3"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 1191, height: 820, depth_or_array_layers: 1 }

**Comment by Lord-McSweeney** [comment]
You might be able to get around this by running Ruffle in the command line with the `-g gl` options (`ruffle -g gl [your file].swf`)

**Comment by Aloso** [comment]
@Lord-McSweeney that did indeed work, no more crashes. Thank you 🙂
