### ISSUE TITLE
Symphony: Blur filter regression

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11950]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/symphony.swf

In [Symphony](http://www.notdoppler.com/symphony.php), the blur filter no longer affects the particles, battery or force field objects.
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/5d34b975-9235-4398-a0bd-b8daff734986)

I've bisected this regression to commit 7e96a2fdad30dd04b26be623ec3a368bce9eeebe from #11769.

### Expected behavior

Objects should be blurred and the particles should be erased over time.
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/adcf5f47-f083-41c9-83fd-1841552922eb)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

See also: #9832

**Comment by Lord-McSweeney** [comment]
Fixed by #11878.
