### ISSUE TITLE
The CJK character display on Linux still has issues

### ISSUE THREAD

**Issue by ngdngdc** [ruffle-rs/ruffle#11960]
### Describe the bug

The display of CJK characters on the Windows side has been effectively solved by #11924. However, on the Linux side, Ruffle still cannot display CJK characters properly.
![截图 2023-07-09 13-38-28](https://github.com/ruffle-rs/ruffle/assets/61965178/96fa41c4-c9f5-4da8-9ea1-b7d5001acd51)

### Expected behavior

I hope that Ruffle can use the system font correctly on the Linux end or provide setting options for users to choose the font themselves, in order to provide Linux users with a consistent user experience with Windows users.

### Affected platform

Desktop app

### Operating system

Arch Linux

**Comment by n0samu** [comment]
This should be fixed by #11941 when it is merged
