### ISSUE TITLE
Recently played SWFS tab.

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11982]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

Mostly for desktop, would be cool to see a section under the file tab that lists the 9 most recently played SWFS through ruffle, Clicking on any of the 9 listed SWFS would automatically open it up (Perhaps with whatever settings you set for it, depending on whether you recently opened it up with Open or Open Advanced.)

**Comment by n0samu** [comment]
I also suggested this in https://github.com/ruffle-rs/ruffle/pull/10426#issuecomment-1487363749

**Comment by sleepycatcoding** [comment]
This has been implemented in #15943.
