### ISSUE TITLE
ActionScript tracking issue

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#12]
- [ ] AVM1 (ActionScript 1.0/2.0)
  - [x] Flash Player 4 actions
    - [x] Decoding
    - [x] Slash syntax
    - [x] gotoAndPlay/Stop
    - [x] Buttons
  - [ ] ActionScript 1.0/2.0
- [ ] AVM2 (ActionScript 3.0)

**Comment by danielhjacobs** [comment]
Closing this issue as redundant. AVM1 (ActionScript 1.0/2.0) support can be tracked by the more useful tracking issue #310. AVM2 (ActionScript 3.0) support can be tracked by the page https://ruffle.rs/compatibility/avm2
