### ISSUE TITLE
Mega Miner: Invisible buttons

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12008]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/megaminer.swf

[Mega Miner](http://www.notdoppler.com/megaminer.php) is playable now, but the Play button to start the game is invisible:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/7e49a404-61ad-4494-a16d-3fcc6f9b040a)
Clicking its area goes to the main menu, from which you can click the invisible menu buttons and start the game. From that point on the game works basically fine, but it continuously spams "Display object container has no child with name" warnings as noted in https://github.com/ruffle-rs/ruffle/issues/9956#issuecomment-1596207531.

### Expected behavior

The buttons should be visible (and Ruffle probably shouldn't be spamming warnings; it may be related).

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
These buttons use TLF text (DefineFont4), which is unimplemented in Ruffle.

**Comment by n0samu** [comment]
With #13957, the main menu button text is visible (though it doesn't use the correct font yet). The Play button is still mostly invisible though.

**Comment by evilpie** [comment]
See  #14749. The are still some rendering artifacts, but the button is definitely not invisible anymore.

**Comment by n0samu** [comment]
Fixed by #14749
