### ISSUE TITLE
ruffle crashes with wayland

### ISSUE THREAD

**Issue by yiitbrak** [ruffle-rs/ruffle#12011]
### Describe what you were doing

Trying to use ruffle with wayland causes a crash
running it with `env -u WAYLAND_DISPLAY ./ruffle <file>` works fine

### What does the crash message say?

panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:734:18

### Ruffle Version

0.1.0-nightly (f0607d6a1fc94c5c56230ab06ff612d883ebf14b 2023-07-11)

### Affected platform

Desktop app

### Operating system

Fedora 38.0.0 [64-bit]

### Additional information

Backtrace:
```
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:316:9
stack backtrace:
   0:     0x55ace89114aa - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ace89114aa - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ace89114aa - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ace89114aa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ace89396ce - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x55ace890b425 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x55ace8911275 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55ace8911275 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55ace8912b6f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x55ace89128ab - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x55ace7d80161 - ruffle_desktop::init::{{closure}}::h71fe27ef1059824d
  11:     0x55ace891329d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6e4950ba7c0fd82a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2032:9
  12:     0x55ace891329d - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:692:13
  13:     0x55ace8913019 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  14:     0x55ace891195c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x55ace8912d22 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  16:     0x55ace7d4e013 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  17:     0x55ace804b5c3 - wgpu::backend::direct::Context::handle_error_fatal::h5aae68c5738834d6
```

**Comment by torokati44** [comment]
Is this consistently reproducible, or was just a one-off?
Does the previous nightly also crash like this?
Could you tell us a bit more about the system, such as the GPU model?

**Comment by yiitbrak** [comment]
Sure thing!
I can reproduce this bug consistently, swf file doesn't seem to matter as long as ruffle is running, or rather trying to create a native window, on wayland. As for version, yes I can also reproduce it on latest nightly (which seems to be [this one](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-07-12) atm). As for my PC;

- GPU: NVIDIA GeForce MX550 / Intel® Graphics (ADL GT2)
- CPU: 12th Gen Intel® Core™ i7-1255U × 12
- Kernel: Linux 6.3.8-200.fc38.x86_64
- GNOME version: 44.2

Crash seems to happen with both integrated and discrete one (via DRI_PRIME=1)
if you need versions of any libraries let me know

**Comment by torokati44** [comment]
Great, thanks! Could you please also check with the nightly before that?
We just bumped some dependencies yesterday, perhaps that is the cause.

**Comment by torokati44** [comment]
Alright, well, you see, the reason I asked you to check with the next-to-last nightly (07-11, or 07-10 should also do fine) is because there is a chance that this just broke recently with #11978. :sweat_smile:

**Comment by yiitbrak** [comment]
Both 7-11 and 7-10 crashes on wayland

**Comment by torokati44** [comment]
Okay, tank you!
Now could you please also check with the  `-g gl` command line flags added?

**Comment by yiitbrak** [comment]
It works, playback seems alright

**Comment by torokati44** [comment]
In this case, it's likely the fault of your Vulkan drivers. Seeing that this is an NVIDIA GPU, you probably use their own proprietary driver. If so, you could try updating it if it's not already the latest version available for your device.
If it is, or updating it doesn't help, then I can only recommend using the above command line options as a workaround...

**Comment by yiitbrak** [comment]
Ok :(
