### ISSUE TITLE
can't enter the game

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12042]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/4de13c89-c34d-464d-8273-1a1b3009c3ee

[1.zip](https://github.com/ruffle-rs/ruffle/files/12045430/1.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/9a0ba5bb-ab73-442d-bffb-98f652fd219d

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by waspennator** [comment]
Swfs that use Stencyl don't work on ruffle yet.
