### ISSUE TITLE
BFXR - the editor does not load

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#12054]
### Describe the bug

the program simply does not start
flash:

https://github.com/ruffle-rs/ruffle/assets/103858019/dd336546-ca25-498f-9534-23dd83e20728

Ruffle

https://github.com/ruffle-rs/ruffle/assets/103858019/90a89eed-cae9-4249-a306-52360fa4a64c

```
 ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x1d9b17673d0 }) to handler FunctionObject(FunctionObject { ptr: 0x1d9b171ec20 }) : RustError("Cannot set prototype of class to null or undefined")
 ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1d9b1766330 }) to handler FunctionObject(FunctionObject { ptr: 0x1d9b171b3e0 }) : TypeError: Error #1034: Type Coercion failed: cannot convert "" to XMLList.
```

### Expected behavior

the program should start

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

the original site is still up, (make sure you have a flash plugin or ruffle)
https://www.bfxr.net/

or the SWF here
[Bfxr_Flash.zip](https://github.com/ruffle-rs/ruffle/files/12053009/Bfxr_Flash.zip)

**Comment by evilpie** [comment]
This needs the undocumented XML::notfication and XML::setNotification functions and TLF support.
