### ISSUE TITLE
ski safari flash preview - can't enter the game

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12074]
### Describe the bug

![1](https://github.com/ruffle-rs/ruffle/assets/98996990/2f5d54ff-eae9-4d68-817f-ab81dc5cb591)
game stuck here
[ski.zip](https://github.com/ruffle-rs/ruffle/files/12060057/ski.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/c796e20d-6d70-411d-b354-1bb858454067

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
This needs `Texture.uploadFromByteArray`

**Comment by Aaron1011** [comment]
This is now playable on `master`, with a low framerate.
