### ISSUE TITLE
Big Bucks - player money does not refresh as you buy properties or earn money

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#12080]
### Describe the bug

Once into the game, the amount of money a player has does not refresh as money is spent or if earnings are made. 

This game has been working fine for two or so years - this issue is only recent in the last couple of weeks. 

The issue seems to resolve if you move between full screen view and windowed view. But needs to be done again and again to see what your actual money levels are. 

http://www.freeworldgroup.com/games6/gameindex/big-bucks.htm

### Expected behavior

Money in the player's window will update as the player is playing on the game board. 

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

### Additional information

Hope this can be fixed. It's a very popular game and has been working very well until recently.

**Comment by Lord-McSweeney** [comment]
This sounds like a cacheAsBitmap regression.

**Comment by Lord-McSweeney** [comment]
This is unfortunately not yet fixed.

**Comment by freeworldgroup** [comment]
Hope this can be fixed soonish!

**Comment by Lord-McSweeney** [comment]
This is still occurring.

**Comment by Lord-McSweeney** [comment]
I'm not sure what fixed this issue, but I can't reproduce it anymore.

**Comment by freeworldgroup** [comment]
Yep, it's back to playing well again! Phew, a really fun game and very popular even after all these years! Hope graphical issues will be addressed one day!

**Comment by Lord-McSweeney** [comment]
Fixed, probably by #13923
