### ISSUE TITLE
Ancient Odyssey - Can't click play button

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#12107]
### Describe the bug

This happens for every Abroy game with the same intro.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/ancientodyssey.swf

### Expected behavior

Click Play and start

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
Note that the object(s) used for the buttons are MovieClips- there are no Avm2Buttons.
