### ISSUE TITLE
Mouse detection doesn't seem to work in Scrape (partial regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1211]
https://www.newgrounds.com/portal/view/312973/

The game was not really playable in the nightly build of 2020-09-15 and older (you usually exploded after a second or so), but since then you can no longer start a game at all (you get stuck on the "click anywhere in grey area to begin" instruction).

**Comment by Herschel** [comment]
Need to handle masks in shape hitTests

**Comment by Toad06** [comment]
The issue no longer happens as of [Nightly 2021-04-11](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-04-11), assume fixed by #3353.
