### ISSUE TITLE
Last Touchdown: Running in place

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#12134]
### Describe the bug

https://www.newgrounds.com/portal/view/435510?emulate=flash
Game seems to get to the title screen fine, but it all falls apart as soon as you get ingame as Power Max starts Power Running in place.

[www.newgrounds.com-1689652459561.log](https://github.com/ruffle-rs/ruffle/files/12075717/www.newgrounds.com-1689652459561.log)

I presume these errors that show up before you get to the actual gameplay might be having a hand in it?

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x4d057f0 }) to handler FunctionObject(FunctionObject { ptr: 0x4cab0c8 }) : RustError("Failed to lookup class Multiname { ns: Single(Namespace(Namespace(\"\"))), name: Some(\"void\"), param: None, flags: MultinameFlags(0x0) } during coercion")

Error dispatching event EventObject(EventObject { type: "timer", class: flash.events::TimerEvent, ptr: 0x469ba58 }) to handler FunctionObject(FunctionObject { ptr: 0xc8bf78 }) : RustError("Failed to lookup class Multiname { ns: Single(Namespace(Namespace(\"\"))), name: Some(\"void\"), param: None, flags: MultinameFlags(0x0) } during coercion")

### Expected behavior

Power Max should actually be running forward.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 114

**Comment by n0samu** [comment]
Needs the void type (#11520)

**Comment by n0samu** [comment]
Fixed by #11520
