### ISSUE TITLE
Learn to Fly 3: Flash Penguin logo is rendered incorrectly

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12136]
### Describe the bug

In [Learn to Fly 3](https://www.gameflare.com/online-game/learn-to-fly-3/), the Flash Penguin logo shown in the intro (immediately after the Light Bringer Games intro) is rendered in a wrong/corrupted way:

![image](https://github.com/ruffle-rs/ruffle/assets/71368227/4789bc90-4928-410a-8e69-054f46e3956f)

The penguin sprite is actually a DefineBitsJPEG3 tag with a very strange JPEG inside. Here is the sprite isolated as its own SWF, along with the JPEG data exported as a file: [sprite1930.zip](https://github.com/ruffle-rs/ruffle/files/12076077/sprite1930.zip)

This JPEG actually uses 32-bit CMYK colors. Maybe our JPEG decoder library doesn't support this, or maybe we aren't passing it the necessary options to make it decode correctly?

### Expected behavior

The Flash Penguin logo should look like this:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/db2fe8a7-ffe2-410b-ab10-e2c5c0044527)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by SuchAFuriousDeath** [comment]
uhhhh...

https://github.com/ruffle-rs/ruffle/blob/690ce110d84dcf8925d60247f685587d8c53adfc/render/src/utils.rs#L174-L177

The 256 seems to be the cuprit

**Comment by SuchAFuriousDeath** [comment]
The Barbie thingy is fixed by this too. PR on the way

**Comment by SuchAFuriousDeath** [comment]
@n0samu 
#12592 is merged, so this can be closed

**Comment by Lord-McSweeney** [comment]
Fixed by #12592.
