### ISSUE TITLE
Sushi Cat 2: Black screen on level start

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#12135]
### Describe the bug

https://www.newgrounds.com/portal/view/563966?emulate=flash
Game works up until you try and start the first level, at which you get a black screen and ruffle dumps this in the logs.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x6d5a810 }) to handler FunctionObject(FunctionObject { ptr: 0x1f925f0 }) : RustError("Failed to lookup class Multiname { ns: Single(Namespace(Namespace(\"\"))), name: Some(\"void\"), param: None, flags: MultinameFlags(0x0) } during coercion")

### Expected behavior

Level should start up like normal.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 114

**Comment by n0samu** [comment]
Needs the void type (#11520)

**Comment by Briellenoel123** [comment]
#11520 has merged in to master upcoming next nightly version.

**Comment by n0samu** [comment]
Fixed by #11520, but see #12421 for the next set of problems with this game.
