### ISSUE TITLE
Ancient Jewels Cleopatra - XML Error

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#12173]
### Describe the bug

https://www.spiele-umsonst.de/azad/downloads/flashgames/ancientjewelscleopatrastreasure.swf - After I click on Create nothing happens, also the loading bar of the game is out of the box.

ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x4d897b8 }) to handler FunctionObject(FunctionObject { ptr: 0x6e29760 }) : RustError("Cannot append non-XML value PrimitiveObject(PrimitiveObject { ptr: 0x41d4bf0 })")

### Expected behavior

Create the profile and continue play

### Affected platform

Desktop app

### Operating system

All

### Browser

All

**Comment by evilpie** [comment]
The error is now (after #12350):
```
ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x145eb88 }) to handler FunctionObject(FunctionObject { ptr: 0x6e9dcb8 }) : RustError("Modifying an XMLList object is not yet implemented: need to resolve") 339.js:825:21
```
