### ISSUE TITLE
Bullet Heaven 2 - can't enter the game

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12199]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/d7659c04-8090-41d3-9d25-e4abcffcfd9f

[BulletHeaven2.zip](https://github.com/ruffle-rs/ruffle/files/12115384/BulletHeaven2.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/b9400ef9-1cfe-49ed-9823-b878cac7313d

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by waspennator** [comment]
[ruffle.rs-1689911238593.log](https://github.com/ruffle-rs/ruffle/files/12116080/ruffle.rs-1689911238593.log)
Providing a log file of running the SWF through the web demo.

**Comment by n0samu** [comment]
With #12213, the game gets a bit farther, but this error softlocks the game after clicking the Start button:
```
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "mouseDown", class: flash.events::MouseEvent, ptr: 0x130db0c4dd0 }) to handler FunctionObject(FunctionObject { ptr: 0x130db143170 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: buildArmature)
        at Entity/createArmature()
        at Player/init()
        at Players::Matt()
        at Level/makePlayer()
        at Level/init()
        at Levels::Level1()
        at Game/init()
        at Main/startGame()
        at MainMenu/startGame()
        at MethodInfo-4929()
        at MethodInfo-4514()
```

**Comment by Aaron1011** [comment]
With https://github.com/ruffle-rs/ruffle/pull/12244, I was able to play the first stage (I didn't play long enough to finish it, though)

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/12244
