### ISSUE TITLE
Ruffle Web - Slowness when something has a faded effects

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1220]
I've found a strange bug that where you load an swf using the web code. If the file has a faded layer like the example below everything lags and takes time to do anything. 

It happens in Chrome manly but can sometimes happen in Safari and Firefox. 

<img width="889" alt="Screenshot 2020-09-25 at 12 14 02" src="https://user-images.githubusercontent.com/10291664/94260817-b9d8f680-ff28-11ea-99e0-14d2e52588fe.png">

**Comment by Herschel** [comment]
Could you provide a link to the SWF in question? Thank you!

**Comment by JamesAllgood** [comment]
https://ridesims.com/sites/default/files/2020-09/StealthV1.swf
