### ISSUE TITLE
Adventure Story - Filters Regress and fail on maximizing window

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#12211]
### Describe the bug

when playing Adventure Story, maximizing the window removes filters from displaying
the intro cutscene becomes no longer black and white, and the clouds and distant scenery of levels change colour/toggle blur.
Ruffle never used to do this.

https://github.com/ruffle-rs/ruffle/assets/103858019/9cd6f0af-9760-43a9-b897-58306f16fe20

### Expected behavior

Ruffle should not regress and continue to show filters regardless of window size

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

you may need to force show all
[586861_level01.swf.zip](https://github.com/ruffle-rs/ruffle/files/12126750/586861_level01.swf.zip)

**Comment by Lord-McSweeney** [comment]
This is because resizing the window invalidates all cacheAsBitmap-objects.

**Comment by n0samu** [comment]
This might be fixed by #12201. Please check in the upcoming nightly once it is released

**Comment by Kz-92** [comment]
it might be, but I did compile from source about an hour ago, so I'm not sure.

**Comment by n0samu** [comment]
Oh okay, then it is not fixed :(

**Comment by n0samu** [comment]
This is not a bug. Flash Player behaves exactly the same. SWFv9 has very low texture size limits for filters, so resizing the window can easily prevent them from appearing.

**Comment by Kz-92** [comment]
that doesn't seem right, I don't get this using flash player at all

**Comment by Kz-92** [comment]
https://github.com/ruffle-rs/ruffle/assets/103858019/07848958-196a-4915-9692-a194df9ab33b

**Comment by n0samu** [comment]
Well that's very confusing. It certainly happens in Flash Player for me.

https://github.com/ruffle-rs/ruffle/assets/71368227/56084423-cf5e-44d6-a9db-aacc4ba5bcfe

**Comment by n0samu** [comment]
Comparing your video with mine, your Flash Player window looks scaled. Do you have display scaling enabled? I don't think the Flash projector is DPI-aware, so it may be seeing a lower resolution and Windows may be scaling it up. On the other hand, Ruffle is DPI-aware and sees your actual screen resolution.

**Comment by Kz-92** [comment]
I do have scaling enabled, for 125% and it does seem to affect FP that way after reducing to 100%, interesting
this never used to happen with Ruffle previously at least as far back as 2023-07-13, (including at 100% scaling) which was much preferred to how Ruffle now acts

**Comment by n0samu** [comment]
This change was needed to match Flash's behavior, and also to improve performance in some games with large bitmaps. You can make a feature request to allow disabling/changing the cached bitmap size limit.

**Comment by Kz-92** [comment]
thanks for helping me figure this out!
I'll probably make a feature issue when I have more time, 
closing
