### ISSUE TITLE
Trails in the sky website gives a critical error

### ISSUE THREAD

**Issue by KuromeSan** [ruffle-rs/ruffle#1222]
im using Firefox when i try goto http://trailsinthesky.com/fc/ ruffle shows the following message 
![image](https://user-images.githubusercontent.com/39113159/94268996-20462f00-ff92-11ea-8344-8673f9547479.png)

**Comment by Dinnerbone** [comment]
Seems to work for me, can you update and try again? Maybe we fixed it already :D

**Comment by KuromeSan** [comment]
yep it has, well except for the music not playing anyway.
