### ISSUE TITLE
Bubble Dive: Stage scrolling issues after 2023-07-20 build

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#12253]
### Describe the bug

In **Bubble Dive**(Korean game, originally titled '버블 다이브'), When a stage begins, the goal of the game is for the character to step on a scaffold to descend down the stage. However, the moment the character descends, the interface and all game screens move upward instead of remaining stationary.

[bubble-dive.zip](https://github.com/ruffle-rs/ruffle/files/12138136/bubble-dive.zip)

This issue is very similar to the following issue that was resolved in the past: https://github.com/ruffle-rs/ruffle/issues/4117

This worked fine until Ruffle Nightly 2023-07-19, but started to break on [2023-07-20](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-07-20) build.

### (Working) Ruffle Nightly ~2023-07-19
https://github.com/ruffle-rs/ruffle/assets/75052171/37504eba-4926-4789-9a23-ec7189a92deb

### (Not Working) Ruffle Nightly 2023-07-20~
https://github.com/ruffle-rs/ruffle/assets/75052171/6c45083f-217f-49f1-95c3-15b6ac220a34

### Expected behavior

The game interface shouldn't affect the game.

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Google Chrome 115

**Comment by Jmousy** [comment]
I found another swf file with the same problem (also occurring since 2023-07-20)

[Son-Goku-Rock-Rock.zip](https://github.com/ruffle-rs/ruffle/files/12138152/Son-Goku-Rock-Rock.zip)

![image](https://github.com/ruffle-rs/ruffle/assets/75052171/90cea258-d48f-4990-a699-1926d5b49e41)

**Comment by n0samu** [comment]
This seems to be a regression caused by #12063. @CUB3D can you take a look?
