### ISSUE TITLE
Sonny 1 and 2: Performance leak

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#12254]
### Describe the bug

In either game, an initially gradual, but ultimately drastic performance degradation occurs as more battles are waged. The frame rate steadily plummets and by a third match, the game is approaching unplayable. 

### Expected behavior

The frame rate should remain steady and quite playable on what is otherwise a very capable system.

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

First desktop nightly affected is 7/16/23.
https://drive.google.com/file/d/1Saz4N_UCGiCry4mGFswW3VvCvw9cXGH3/view?usp=sharing

**Comment by sombraguerrero** [comment]
The zip file has been updated with an extremely verbose tracy dump, which runs through several battles to the end of a battle where the frame rate drops to single digits.

**Comment by Korne127** [comment]
This is a regression caused by #10792 and linked to #12265.
