### ISSUE TITLE
Submachine 10: Garbled text

### ISSUE THREAD

**Issue by angelo-wf** [ruffle-rs/ruffle#12267]
### Describe the bug

In Submachine 10: The Exit (SWF from [here](https://web.archive.org/web/20201108091548oe_/http://www.mateuszskutnik.com/submachine/swf/submachine_10.swf)), text that appears on screen-like objects in-game appears garbled, with characters overlapping strangely.

In Ruffle, it looks like this:
<img width="512" alt="Scherm­afbeelding 2023-07-23 om 23 00 57" src="https://github.com/ruffle-rs/ruffle/assets/32901471/512566b3-db91-4a2a-8d74-be63bacd5ffa">

It is supposed to look like this:
![Scherm­afbeelding 2023-07-23 om 23 00 45](https://github.com/ruffle-rs/ruffle/assets/32901471/c67ae7d7-8a22-4115-a61a-b03eb8caf14b)

To reproduce:
1. Start a new game (new game, then click the center wheel)
2. Go right 4 times (click edge of screen)
3. Click the round pedestal in the middle of this screen

### Expected behavior

The text to appear as is does in Flash, being readable.

### Affected platform

Desktop app

### Operating system

macOS Ventura 13.4.1 (c) [arm64]

### Additional information

I used the desktop-app download from the site: ruffle-nightly-2023_07_21-macos-universal

**Comment by kjarosh** [comment]
This issue is fixed as of today
