### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by scott20** [ruffle-rs/ruffle#12265]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:934:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:934:18
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.5d5402bad5c6c32381de.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hb515a2c9ffd29eb6 (wasm://wasm/02f374f6:wasm-function[9094]:0x8d2b0d)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f374f6:wasm-function[5944]:0x7d4d99)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f374f6:wasm-function[8938]:0x8cdfee)
    at core::panicking::panic::h42080e1e32ba4b73 (wasm://wasm/02f374f6:wasm-function[8577]:0x8bede6)
    at core::ops::function::FnOnce::call_once::ha1012893ada11b49 (wasm://wasm/02f374f6:wasm-function[933]:0x308aca)
    at ruffle_core::avm1::function::Executable::exec::h1f32892b0c38e4aa (wasm://wasm/02f374f6:wasm-function[629]:0x1a3c61)
    at <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::hf1a868053c3e88b9 (wasm://wasm/02f374f6:wasm-function[4899]:0x778511)
    at ruffle_core::avm1::activation::Activation::run_actions::h444b6ef06bd56a2a (wasm://wasm/02f374f6:wasm-function[515]:0x2428a)
    at ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_action::h4878291b4896b7dc (wasm://wasm/02f374f6:wasm-function[902]:0x2ef814)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1690114508%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F675000%2F675027_pd.swf%3F1464031405%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2296091150.8c3eb84687db46df2407d1a5e6dba56aea3d21aea8ea34%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264bd78648db2d%22%2C%22NewgroundsAPI_SessionID%22%3A%22Ax1JqEE2WxD6x0KeUCEQ1642c2da5dd6ccfbd4854d36fb67f91e07018d80r7G8%22%2C%22NewgroundsAPI_UserName%22%3A%22FoxUno%22%2C%22NewgroundsAPI_UserID%22%3A3129642%2C%22ng_username%22%3A%22FoxUno%22%7D%2C%22width%22%3A960%2C%22height%22%3A540%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F675000%2Fflash_675027_card.png%3Ff1610564399%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/675000/675027_pd.swf?1464031405

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-23
Channel: nightly
Built: 2023-07-23T00:19:43.292Z
Commit: 4219f3966874361b39032e8656997db277fff1cb
Is extension: false

# Metadata
width: 1920
height: 1080
frameRate: 60
numFrames: 6
swfVersion: 15
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 3351479

**Comment by n0samu** [comment]
Game is Pooper Deluxe: https://www.newgrounds.com/portal/view/675027

The crash happens when after collecting an item while flying. This is a regression caused by #10792.
