### ISSUE TITLE
The last shelter is broken.

### ISSUE THREAD

**Issue by Nq3hlolol** [ruffle-rs/ruffle#12285]
### Describe the bug

There is a game called The Last Shelter where you fight off bugs using gun towers.
It opens fine, it lets you create a game but when you open the first mission, you can place towers however when you click the go button to start the wave, the game freezes and you cannot play. 
before clicking:
![image](https://github.com/ruffle-rs/ruffle/assets/140423679/5b992722-f5f3-4aa4-8dd1-18ed5d399560)
after clicking:
![image](https://github.com/ruffle-rs/ruffle/assets/140423679/ef0bf56c-3c4d-44e1-8d96-2609719a4aa2)

### Expected behavior

When the go button is pressed to start the wave. the two boxes of text are meant to disappear and the bugs are meant to come attack. 
This is a video showing what is meant to happen:
https://www.youtube.com/watch?v=Vz-YQ-UqGfE&t=132s&ab_channel=vmplayportal
I hope this can be fixed as this is one of my favourite games.
( i tried on multiple browsers

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Opera GX, Google Chrome. using Kongregate

### Additional information

I've been told this is the error message:

ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x55e544d1c590 }) to handler FunctionObject(FunctionObject { ptr: 0x55e547a44d00 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: GetWorld)

**Comment by Lord-McSweeney** [comment]
This actually needs the `void` type.

**Comment by Nq3hlolol** [comment]
wdym

**Comment by Lord-McSweeney** [comment]
This is working now!
