### ISSUE TITLE
N v2.0 - Keyboard remains bound to episode selection menu after selecting episode

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#12294]
### Describe the bug

In [the web version of N v2.0](https://www.thewayoftheninja.org/nv2.html), the game can fail to fully relinquish keyboard controls from the episode selection menu to the gameplay, resulting in the keyboard controlling both the ninja and the (now invisible) menu. This means that pressing the Z (select/jump) key will load levels on top of the currently-loaded level, making it impossible to continue playing normally.

This issue does not seem to occur upon a fresh load. However, the following steps can be used to reproduce the issue consistently:
1. Enter an episode.
2. Exit or complete the episode.
3. Re-enter an episode. This can be the same or different episode.

It also appears to persist after reloading the page on web or relaunching the app on desktop, with the latter being more consistent as well as crash-prone due to memory limits.

https://github.com/ruffle-rs/ruffle/assets/58399748/30d6f46c-e624-481b-8afb-36df14b9573a

### Expected behavior

The keyboard should not continue to control the episode selection menu after an episode has been selected.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox Developer Edition 116.0b8

### Additional information

Tested with both the browser extension and desktop app.

**Comment by thedanbob** [comment]
By coincidence I had tried this myself just now (Ruffle + N v2) and encountered the same issue. I'm using the desktop app on macOS (M1). For me, the bug happened on the very first load.

**Comment by WumboSpasm** [comment]
A change between nightlies 10/28 and 10/29 (possibly 878f1fc64e5842895d11a32c558a20864665dc2d?) appears to have fixed this issue. Thanks!
