### ISSUE TITLE
N v2.0 - Level previews not displayed when hovering over episode

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#12292]
### Describe the bug

In [the web version of N v2.0](https://www.thewayoftheninja.org/nv2.html), moving the cursor over an episode on the Play Game screen does not display level previews in the blank space on the right.

![image](https://github.com/ruffle-rs/ruffle/assets/58399748/10909cc2-d3f5-4e4d-88b2-b37ce9f4ac62)

### Expected behavior

Moving the cursor over an episode on the Play Game screen should display level previews in the blank space on the right.

![image](https://github.com/ruffle-rs/ruffle/assets/58399748/13fe0cfc-9acc-4dd9-8837-6c039e97f5be)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox Developer Edition 116.0b8

### Additional information

Tested with both the browser extension and the standalone app.

**Comment by n0samu** [comment]
The error is:
```
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "mouseOver", class: flash.events::MouseEvent, ptr: 0x2099c0043b0 }) to handler FunctionObject(FunctionObject { ptr: 0x2098248a0f0 }) : RangeError: Starting position 1 does not exist in the child list (valid range is 0 to 1)
        at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::removeChildren()
        at com.metanet.screens.episodes::EpisodesScreenMediator/handleMouseOverEpisode()
```
