### ISSUE TITLE
Vanilla Nexus Title Screen is Purple instead of Grey

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#12301]
### Describe the bug

The developer of Vanilla Nexus noted the title screen is purple in the current version of Ruffle:

https://www.newgrounds.com/portal/view/846832

They linked to a version running via Ruffle from September 2022 where it is rendering as the expected grey:

http://www.flashjunkmind.com/nexustk/content/scrapGames/VNexusdemo.html

The traditional Flash player also renders the file as grey.

### Expected behavior

Title screen should be grey and not purple.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
I cannot reproduce this and couldn't reproduce it in https://ruffle-regressions.github.io . Can you try reproducing it again?

**Comment by TomFulp** [comment]
This does appear to be fixed now!
