### ISSUE TITLE
Web browser ruffle failing to load on mobile iOS.

### ISSUE THREAD

**Issue by Creative-name-NA** [ruffle-rs/ruffle#12312]
### Describe the bug

What happens is that when ever the browser version starts to load the loading bar fills up but the spinning loading animation is frozen. After it loads for a while the web page suddenly refreshes.

### Expected behavior

What I expected to happen was for Ruffle to load and the game it’s loading to load.

### Affected platform

Online demo

### Operating system

IPadOS 15.7.8

### Browser

Firefox for iOS version 115

**Comment by n0samu** [comment]
Hi, unfortunately our wgpu renderer does not play well with older iOS devices. If you own a website, you could try to detect these old devices and have them use the WebGL or Canvas renderer instead, using Ruffle's `preferredRenderer` option. [See our wiki for details](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options). Anyway, this has been reported before in #10620, so I'll close this in favor of that issue.
