### ISSUE TITLE
Strange error while playing Riddle School 5 on Newgrounds

### ISSUE THREAD

**Issue by OtterCodes101** [ruffle-rs/ruffle#12323]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to create texture object"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/device.rs:704:52
    at W.n.wbg.__wbg_new_d258248ed531ff54 (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.453aff4f9dae04ea1054.js:1:51449)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e63761b8083e365 (wasm://wasm/02f90642:wasm-function[9180]:0x8e657d)
    at std::panicking::rust_panic_with_hook::h5cee2a9564faeb6d (wasm://wasm/02f90642:wasm-function[6054]:0x7f6c92)
    at core::panicking::panic_fmt::h8a19fa1eb63fbb67 (wasm://wasm/02f90642:wasm-function[9024]:0x8e1f65)
    at core::result::unwrap_failed::h11ff2abd8d53a5bd (wasm://wasm/02f90642:wasm-function[7167]:0x850991)
    at <T as wgpu::context::DynContext>::device_create_texture::h8ebae247e35e00a7 (wasm://wasm/02f90642:wasm-function[6698]:0x8293d1)
    at wgpu::Device::create_texture::h4b9cbf9d083fdcfa (wasm://wasm/02f90642:wasm-function[5109]:0x7a40d5)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::create_empty_texture::h3f55e99c00210eb2 (wasm://wasm/02f90642:wasm-function[4948]:0x795efb)
    at ruffle_core::display_object::render_base::h8acad5ce717fa903 (wasm://wasm/02f90642:wasm-function[620]:0x194dfc)
    at <ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::render::hb19103dc2ec66145 (wasm://wasm/02f90642:wasm-function[6597]:0x81de43)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Mesa DRI Intel(R) HD Graphics 400 (BSW)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1690334776%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F532000%2F532179_Riddle_School_5.swf%3F1271086186%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264c1425582dd7%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A640%2C%22height%22%3A480%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F532000%2Fflash_532179_card.webp%3Ff1669676936%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/532000/532179_Riddle_School_5.swf?1271086186

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14816.17.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-26
Channel: nightly
Built: 2023-07-26T00:20:00.702Z
Commit: 3326aef6a8b7c2b496c4538d1674e5b14944baa7
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 41
swfVersion: 8
backgroundColor: #FFFFFF
isActionScript3: false
uncompressedLength: 20352338
![image](https://github.com/ruffle-rs/ruffle/assets/134523836/d5d781c2-2996-456e-9550-31b998243dd2)

**Comment by n0samu** [comment]
Thanks for the report - this probably means your device ran out of memory or other resources. It's more likely to happen on lower-end systems.

**Comment by OtterCodes101** [comment]
Thanks for the response, I will close this now.
