### ISSUE TITLE
Death vs Monstars: Cannot buy upgrades

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12333]
### Describe the bug

Download SWF (de-Mochicrypted version): [DeathVsMonstars_decrypted.zip](https://github.com/ruffle-rs/ruffle/files/12177417/DeathVsMonstars_decrypted.zip)

In [Death vs. Monstars](https://www.newgrounds.com/portal/view/485996/format/flash?emulate=flash), upgrade prices are shown as 0, and you cannot buy the upgrades even if you have enough money to afford them at their actual prices. The displayed upgrade descriptions are also incorrect.

Here is a screenshot to demonstrate:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/1502cda0-cb46-41cb-9acc-e8ee77b9a5ab)

### Expected behavior

Here is what it looks like in Flash Player:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/9c3984a5-5bf9-4c65-8ab3-285af64f1339)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 115

### Additional information

The problem also occurs in [Death vs. Monstars 2](https://www.newgrounds.com/portal/view/604356/format/flash?emulate=flash)

This was originally reported by @KupoGames on Discord.

**Comment by Aaron1011** [comment]
Are there any warning or errors in the logs?

**Comment by n0samu** [comment]
Nothing that seems relevant at all.

**Comment by n0samu** [comment]
Fixed by #12386
