### ISSUE TITLE
turkey run - turkey runs very slow and the chaser didn't appear

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12336]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/7dcd8bb9-bde8-4665-a069-1177243a348e

[turkeyrun.zip](https://github.com/ruffle-rs/ruffle/files/12178560/turkeyrun.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/f1acc6cf-8f44-4c02-8790-38e094f0d1a5

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Errors like this are constantly repeated:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x16318f43460 }) to handler FunctionObject(FunctionObject { ptr: 0x163182be760 }) : Error: 虚拟帧与真实帧对不上 -- 1 -- 2 -- [object Player] -- 站立
        at com.macrojoy.star.display::Abstract_frame/dummyFrame()
        at com.macrojoy.star.display::Abstract_basic/updateFrame()
        at com.macrojoy.star.sys::Manager/runUpdateFrame()
        at com.macrojoy.star.sys::Manager/mainUpdateEvent()
```
The first bit of Chinese text says "the virtual frame does not match the real frame." The next part varies, referring to the current state of the object (in this case "standing")
