### ISSUE TITLE
iStunt 2: RangeError: 0 is outside the range of the vector

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#12331]
### Describe the bug

First level is broken.

SWF - https://data.gameflare.com/games/1602/1QmaZoDrsO5NBB.swf
Game - https://www.gameflare.com/online-game/istunt-2/

error:

``ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x21ac239a8c0 }) to handler FunctionObject(FunctionObject { ptr: 0x21ac234ad00 }) : RangeError: 0 is outside the range of the vector``

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
This isn't fixed, but also needs the following: 
```
XML.name() namespaces
Graphics.drawTriangles()
DisplayObject.rotationY
```
