### ISSUE TITLE
Functionality of Right Click

### ISSUE THREAD

**Issue by P13A53F1X** [ruffle-rs/ruffle#12332]
On both ruffle demo and the ruffle desktop app, right clicking brings up the video quality menu. This was fine at first, until I realized that this completely negates the functionality of swf titles like Stick War Two where there are no alternate controls for right click. My suggestion is that there be a dropdown menu outside of the actual swf player area for those settings and that escape be used to exit fullscreen rather than the right click menu. Thank You!

**Comment by zohebnsr** [comment]
No right-click plan so far?

**Comment by kjarosh** [comment]
> No right-click plan so far?

Will be implemented in https://github.com/ruffle-rs/ruffle/pull/17022
