### ISSUE TITLE
Garden raider - Fails to load title screen.

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#12341]
### Describe the bug

(minor epilepsy warning)

http://www.flashpacman.info/pacman-garden-raider.php

Game briefly shows loading screen, then attempts to load home screen. The only two things that appear are the background under the trees (which you normally do not see) and the logo flashing.

Stage Info shows that the World and Local Bounds' first value are rapidly switching between 0.00 and -0.10, third value switching between 640.95 and 641.05, and the fourth value switching between 480.95 and 482.05.

Within the children of Stage\MovieClip "root1"\Loader Display (really not sure how to describe these) there is a graphic and movieclip instance incrementing quickly.

![ruffle_HFaM4iyvYI](https://github.com/ruffle-rs/ruffle/assets/138401463/629405f3-37ce-4fb9-bcfe-e4ae522dd20d)

### Expected behavior

This is what the title screen should look like:
![image](https://github.com/ruffle-rs/ruffle/assets/138401463/4dee0f7c-2af0-4a66-b677-7b0c804650bc)

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Additional information

Occurs on both 2023-07-26 Nightly Standalone and Extension (Firefox 115.0.2) versions.

**Comment by n0samu** [comment]
This is an AVM1 game encrypted with MochiCrypt, which uses AVM2. Ruffle does not correctly play AVM1 movies loaded by AVM2 movies right now, but this is being worked on in #11005. If the original AVM1 movie is extracted from the MochiCrypt wrapper and played on its own, Ruffle works fine.

**Comment by skiesofravens** [comment]
Ah! Sounds good then. I knew it used Mochi in someway but assumed that if it was making it past the loading bar then that wouldn't be the issue.
