### ISSUE TITLE
Papas Cheeseria[2023-05-09 Can Play]But [2023-07-27]Can't Play

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#12353]
### Describe the bug

Papas Cheeseria[2023-05-09 Can Play] But [2023-07-27] Can't Play...I don't know why ?

Play page : https://www.crazygames.com/game/papas-cheeseria

2023-05-09 self_host
https://files.crazygames.com/gameframe/ruffle/2023-05-09/ruffle.js

SWF:
https://files.crazygames.com/papas-cheeseria/3/game.swf

### Expected behavior

Papas Cheeseria[2023-05-09 Can Play] But [2023-07-27] Can't Play...I don't know why ?

Play page : https://www.crazygames.com/game/papas-cheeseria

2023-05-09 self_host
https://files.crazygames.com/gameframe/ruffle/2023-05-09/ruffle.js

SWF:
https://files.crazygames.com/papas-cheeseria/3/game.swf

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 115.0.5790.110 [64 bits]

**Comment by Lord-McSweeney** [comment]
Seems to be working fine, just a little slow to initialize:
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Ffiles crazygames com%2Fpapas-cheeseria%2F3%2Fgame swf](https://github.com/ruffle-rs/ruffle/assets/84632019/67092bed-c429-4180-9e8f-f3674215f2af)
(extension page player)

**Comment by olux997** [comment]
> Seems to be working fine, just a little slow to initialize: ![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Ffiles crazygames com%2Fpapas-cheeseria%2F3%2Fgame swf](https://user-images.githubusercontent.com/84632019/256533167-67092bed-c429-4180-9e8f-f3674215f2af.png) (extension page player)

:
Well...I don't know what I've been through....But I'm on now....Really like yours....It's totally normal....It's weird.... But I really....>_<

ok please close this request...
