### ISSUE TITLE
Test Failure: avmplus e4x QName suite

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#12356]
Completely passing suites are not shown.

## Testsuite `from_avmplus/e4x/QName/e13_3_2`
| Test | Passes? | Expected | Actual |
| ---- | ---- | ---- | ---- |
| 1 | :heavy_check_mark: | | |
| 2 | :heavy_check_mark: | | |
| 3 | :heavy_check_mark: | | |
| 4 | :heavy_check_mark: | | |
| 5 | :heavy_check_mark: | | |
| 6 | :heavy_check_mark: | | |
| 7 | :heavy_check_mark: | | |
| 8 | :heavy_check_mark: | | |
| 9 | :heavy_check_mark: | | |
| 10 | :heavy_check_mark: | | |
| 11 | :heavy_check_mark: | | |
| 12 | :heavy_check_mark: | | |
| 13 | :heavy_check_mark: | | |
| 14 | :heavy_check_mark: | | |
| 15 | :heavy_check_mark: | | |
| 16 | :heavy_check_mark: | | |
| 17 | :heavy_check_mark: | | |
| 18 | :heavy_check_mark: | | |
| 19 | :heavy_check_mark: | | |
| 20 | :heavy_check_mark: | | |
| 21 | :heavy_check_mark: | | |
| 22 | :heavy_check_mark: | | |
| 23 | :heavy_check_mark: | | |
| 24 | :heavy_check_mark: | | |
| 25 | :heavy_check_mark: | | |
| 26 | :x: | `\|attr1\|` | `\|attr1::attr1\|` |
| 27 | :heavy_check_mark: | | |
| 28 | :heavy_check_mark: | | |
| 29 | :x: | `\|http://foobar/::attr1\|` | `\|http://foobar/::attr1::attr1\|` |
| ns = new QName() | :x: | `` | `undefined` |
| typeof new QName('name') | :heavy_check_mark: | | |
| new QName('name') instanceof QName | :heavy_check_mark: | | |
| new QName('name') == 'name' | :heavy_check_mark: | | |
| ns = new QName('name'), ns.uri == '' | :heavy_check_mark: | | |
| ns = new QName('name'), ns.uri == null | :heavy_check_mark: | | |
| ns = new QName('name'), ns.uri == undefined | :heavy_check_mark: | | |
| ns = new QName('name'), typeof ns.uri | :heavy_check_mark: | | |
| ns = new QName('name'), ns.localName == 'name' | :heavy_check_mark: | | |
| ns = new QName(undefined) | :x: | `` | `undefined` |
| ns = new QName('') | :heavy_check_mark: | | |
| MYOB = new QName('nameofobj'),typeof new QName(MYOB) | :heavy_check_mark: | | |
| MYOB = new QName(null, 'nameofobj'); MYOB.toString() | :heavy_check_mark: | | |
| MYOB = new QName(null, 'nameofobj'); MYOB.uri | :heavy_check_mark: | | |
| MYOB = new QName(null, 'nameofobj'); MYOB.localName | :heavy_check_mark: | | |
| MYOB = new QName('namespace', undefined); MYOB.localName | :x: | `` | `namespace` |
| MYOB = new QName('namespace', ''); MYOB.localName | :heavy_check_mark: | | |
| q3 = y.name() | :x: | `http://someuri::attr1` | `attr1` |
| x1.bravo.@[q3] | :x: | `value3` | `` |

**Comment by Lord-McSweeney** [comment]
The following test is now passing:
- `QName/e13_3_1`

**Comment by Lord-McSweeney** [comment]
`e13_3_5` was fixed by #14075.
