### ISSUE TITLE
Test Failure: avmplus e4x Global suite 

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#12354]
Completely passing suites are not shown.

## Testsuite `from_avmplus/e4x/Global/e13_1_2_1`
> memory allocation of 137438953472 bytes failed

## Testsuite `from_avmplus/e4x/Global/isXMLNameTypeErr`
| Test | Passes? | Expected | Actual |
| ---- | ---- | ---- | ---- |
| Asserting for TypeError | :x: | ? | did not run |
| var object1 = { toString: function() { return this; } }; isXMLName(object1) | :x: | `Error #1050` | `TypeError not thrown` |
| Asserting for TypeError | :x: | ? | did not run |
| var object2 = { toString: function() { return String(object1); } }; isXMLName(object2) | :x: | `Error #1050` | `TypeError not thrown` |

**Comment by Lord-McSweeney** [comment]
This is because we don't support isXMLName.

**Comment by Lord-McSweeney** [comment]
The following tests are now passing:
- `Global/e13_1_2_1`
- `Global/isXMLNameTypeErr`
