### ISSUE TITLE
Error on BLYM

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12366]
# Error Info
Error name: Error
Error message: panicked at 'Unexpected non-object value in object vector', core/src/avm2/amf.rs:99:34

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ooooooooo.ooo/static/?e7c9bd7c-a6d8-b5f2-d6b5-01500034d9b0
SWF URL: http://www.gameshot.org/BLYM/BLYM0913_640x480.swf (Note: This is Flashpoint's faked URL, it does not really exist)

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-28
Channel: nightly
Built: 2023-07-28T00:19:35.903Z
Commit: 46d6d6724dc38a658cd9760b2e6ba799bd2028d9
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 40
numFrames: 2
swfVersion: 11
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 4863139

**Comment by Lord-McSweeney** [comment]
Note: The SWF returns 404 if you try to access it directly.

**Comment by Lord-McSweeney** [comment]
This should be fixed once ScriptObject serialization is implemented (`Serialization is not implemented for class other than Object: ScriptObject(ScriptObject { name: com.spilgames.api.core.tracking.ext.spilet.data.format::TrackedSession, ptr: 0x209ec48 })` is logged right before the panic)

**Comment by n0samu** [comment]
The panic started with #12240 (nightly 2023-07-26)

**Comment by n0samu** [comment]
The same error also happens in [Ticket](https://ooooooooo.ooo/static/?9666eb88-c307-4320-b4f0-ff1086beaf2c).

**Comment by n0samu** [comment]
This actually seems to be happening with all games that use the Spil Games API. Also including [Ninja Miner](https://ooooooooo.ooo/static/?02edac99-658b-a71f-e673-82baf69ebf83) and [Ninja Miner 2](https://ooooooooo.ooo/static/?4da970fc-3a8c-d454-639d-45d21267fd87), which were previously working perfectly.

**Comment by Lord-McSweeney** [comment]
Fixed by #11971.
