### ISSUE TITLE
Can't press New Game on Elephant Quest

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#12374]
### Describe the bug

On https://armorgames.com/play/10606/elephant-quest?ruffle , I cannot press play due to the error
`Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x8b16e8 }) to handler FunctionObject(FunctionObject { ptr: 0xf79820 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: hideLoginStatus)`

### Expected behavior

The Game would start

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla Firefox 115.0.3

**Comment by Lord-McSweeney** [comment]
Direct SWF link: https://cache.armorgames.com/files/games/elephant-quest-10606.swf?v=1373587525

**Comment by Lord-McSweeney** [comment]
This is because the AGI SWF fails to load: `GET https://cache.armorgames.com/assets/agi/AGI.swf net::ERR_TOO_MANY_REDIRECTS`

**Comment by Fancy2209** [comment]
> This is because the AGI SWF fails to load: `GET https://cache.armorgames.com/assets/agi/AGI.swf net::ERR_TOO_MANY_REDIRECTS`

it seems to be a CORS issue?
Also it seems https://cache.armorgames.com/assets/agi/AGI.swf?1 is a redirect to https://agi.armorgames.com/assets/agi/AGI.swf?1

**Comment by Fancy2209** [comment]
It seems to be fixed
