### ISSUE TITLE
Spurious failures of socket tests with writeObject

### ISSUE THREAD

**Issue by adrian17** [ruffle-rs/ruffle#12383]
Example 1:
https://github.com/ruffle-rs/ruffle/actions/runs/5694961606/job/15437188344
```
---- avm2/socket_write_little ----
test panicked: Received data did not match expected data
Expected: [1, 67, 255, 10, 20, 65, 246, 40, 92, 143, 194, 154, 191, 64, 205, 76, 153, 66, 174, 78, 58, 132, 72, 101, 108, 108, 111, 33, 10, 11, 1, 1, 3, 0, 0, 9, 255, 255, 158, 136, 8, 199, 115, 238, 25, 0, 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 82, 117, 102, 102, 108, 101, 32, 83, 111, 99, 107, 101, 116, 33, 82, 97, 119, 32, 85, 84, 70, 32, 105, 115, 32, 99, 111, 111, 108]
Actual: [1, 67, 255, 10, 20, 65, 246, 40, 92, 143, 194, 154, 191, 64, 205, 76, 153, 66, 174, 78, 58, 132, 72, 101, 108, 108, 111, 33, 10, 11, 1, 1, 16, 0, 0, 0, 0, 9, 255, 255, 158, 136, 8, 199, 115, 238, 25, 0, 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 82, 117, 102, 102, 108, 101, 32, 83, 111, 99, 107, 101, 116, 33, 82, 97, 119, 32, 85, 84, 70, 32, 105, 115, 32, 99, 111, 111, 108]
```

Example 2, ran locally:
```
---- avm2/socket_write_big ----
test panicked: Received data did not match expected data
Expected: [1, 67, 255, 10, 20, 65, 64, 191, 154, 194, 143, 92, 40, 246, 66, 153, 76, 205, 132, 58, 78, 174, 72, 101, 108, 108, 111, 33, 10, 11, 1, 1, 3, 0, 0, 9, 255, 255, 136, 158, 238, 115, 199, 8, 0, 25, 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 82, 117, 102, 102, 108, 101, 32, 83, 111, 99, 107, 101, 116, 33, 82, 97, 119, 32, 85, 84, 70, 32, 105, 115, 32, 99, 111, 111, 108]
Actual: [1, 67, 255, 10, 20, 65, 64, 191, 154, 194, 143, 92, 40, 246, 66, 153, 76, 205, 132, 58, 78, 174, 72, 101, 108, 108, 111, 33, 10, 11, 1, 1, 16, 0, 0, 0, 0, 9, 255, 255, 136, 158, 238, 115, 199, 8, 0, 25, 72, 101, 108, 108, 111, 32, 102, 114, 111, 109, 32, 82, 117, 102, 102, 108, 101, 32, 83, 111, 99, 107, 101, 116, 33, 82, 97, 119, 32, 85, 84, 70, 32, 105, 115, 32, 99, 111, 111, 108]
```

As far as I can see, the differing bytes land in one of the two `socket.writeObject(new Object());`.

The weird part is, they happen extremely rarely and we've never noticed these in existing ByteArray serialization code.

Pinging @CUB3D and @sleepycatcoding for this.

**Comment by sleepycatcoding** [comment]
Does this only happen on MacOS or other platforms too?

**Comment by sleepycatcoding** [comment]
As far as I looked into it it seems AMF0 encoded writeObject() seems to usually write [3, 0, 0, 9] which matches flash and in the failure [16, 0, 0, 0, 0, 9].
Is there non-deterministic behavior in AMF0 serializer?

**Comment by Dinnerbone** [comment]
Looked through actions history, it seems to only happen on mac for our runners - but Adrian has reproduced it and does not own a mac. It's likely a timing issue and the mac runners are more susceptible to those.

**Comment by adrian17** [comment]
My test was on an Ubuntu VM.
But it happened only on the very first run after pulling from `master`, and never repeated after that (so far).

**Comment by sleepycatcoding** [comment]
Well as far as I see the existing writeObject test for ByteArray only checks if it can read it back with readObject() so we don't actually know if that has failed before: https://github.com/ruffle-rs/ruffle/blob/c8e4ec98f08a6fb732d4c64977d530bc4f88e970/tests/tests/swfs/avm2/bytearray_writeobject/Test.as#L23

**Comment by sleepycatcoding** [comment]
I could reproduce the issue with a simple program that used `flash-lso` crate, which means the bug is not in Ruffle at all.

**Comment by sleepycatcoding** [comment]
Also the weird timing issue is because the timeouts for the socket navigator were too high 🤦‍♂️

**Comment by sleepycatcoding** [comment]
> As far as I looked into it it seems AMF0 encoded writeObject() seems to usually write [3, 0, 0, 9] which matches flash and in the failure [16, 0, 0, 0, 0, 9]. Is there non-deterministic behavior in AMF0 serializer?

Oh interesting, I read a bit of the `flash-lso` crate source and I think why the output mismatches, but I really do not know how to fix it. It seems when writing a object flash uses object serialization: https://github.com/ruffle-rs/rust-flash-lso/blob/3669a352c14192d0d301e594ae6047ae99725006/flash-lso/src/amf0/write.rs#L49, but we are using typed object serialization instead https://github.com/ruffle-rs/rust-flash-lso/blob/3669a352c14192d0d301e594ae6047ae99725006/flash-lso/src/amf0/write.rs#L102
