### ISSUE TITLE
B.L.A.C.K. - Game Freezes

### ISSUE THREAD

**Issue by theonlypwner** [ruffle-rs/ruffle#12389]
### Describe the bug

1. Download SWF from https://uploads.ungrounded.net/308000/308750_BLACK.swf
2. Load SWF at https://ruffle.rs/demo/
3. Start the game.
4. Press 6 to switch to the assault rifle.
5. Move around and shoot a few times.

The game goes into an infinite loop and freezes, while CPU usage is high.

### Expected behavior

I expect the game not to freeze.

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Chrome 115.0.5790.102

**Comment by n0samu** [comment]
Game link: https://www.newgrounds.com/portal/view/308750/
