### ISSUE TITLE
Tower of Doom: Multiple failures

### ISSUE THREAD

**Issue by rdrpenguin04** [ruffle-rs/ruffle#1239]
SWF Link: https://cache.armorgames.com/files/games/tower-of-doom-6071.swf

Platform: Online demo (Chrome, Linux Mint)

Category: Seems to be AS3 related.

List of errors:
- Before "PLAY!", something throws:
```js
Uncaught Error: closure invoked recursively or destroyed already
    at Object.Ru (1.index.js:1)
    at __wbindgen_throw (index.js:1)
    at /builds/web-demo/364bfc88a16ac7afaef8.module.wasm:wasm-function[4209]:0x2cb682
    at h (/builds/web-demo/364bfc88a16ac7afaef8.module.wasm:wasm-function[3920]:0x2c9fd6)
    at S (1.index.js:1)
    at f (1.index.js:1)
```
- After "PLAY!", there is an AVM2 error:
```
AVM2 error: Property does not exist: Some(AvmString { source: Owned("TweenPlugin") })
```
- There are a few warnings that stem directly from the AVM2 error.

Let me know if I can help get any more information, I'll look around some to see if I can get TweenPlugin up and running.

**Comment by rdrpenguin04** [comment]
Okay, looks like TweenPlugin should actually be in the SWF somewhere, as it's from an AS3 library (https://github.com/greensock/GreenSock-AS3), which means the first issue is the real problem. I'll look into that then.

**Comment by rdrpenguin04** [comment]
Confirmed on desktop, but I didn't get the first error. May be a parsing error somewhere?
Desktop Error:
```
[2020-09-29T13:12:34Z ERROR ruffle_core::avm2::activation] AVM2 error: Property does not exist: Some(AvmString { source: Owned("TweenPlugin") })
```

**Comment by Toad06** [comment]
1/ Since you're using the online demo, I'd say this first issue is the same as #876 (also see comments).
2/ ActionScript 3 files are not yet supported, so this should explain these warnings and errors.

**Comment by rdrpenguin04** [comment]
Ah, okay. I'll close this then and see if I can find either more basic AS3 files to start implementing or some AS2 files that don't work.
