### ISSUE TITLE
THE KING OF FIGHTERS VS DNF ,just get Black Screen.

### ISSUE THREAD

**Issue by olux997** [ruffle-rs/ruffle#12405]
### Describe the bug

THE KING OF FIGHTERS VS DNF ,just get Black Screen.

URL:
https://www.kongregate.com/games/FightGaming/the-king-of-fighters-vs-dnf

SWF:
https://game192321.konggames.com/gamez/0019/2321/live/The_King_of_Fighters_vs_DNF_November_29th_2010-y8-fix.swf?kongregate_game_version=1385200928

### Expected behavior

THE KING OF FIGHTERS VS DNF ,just get Black Screen.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome 115.0.5790.110 [64 bits]

**Comment by Lord-McSweeney** [comment]
Similar issue to #12093 and #10505
