### ISSUE TITLE
Next page button goes to last page instead of first page in NASA's The Hydrologic Cycle

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#1242]
https://www.pbslearningmedia.org/asset/ess05_int_hydrocycle/

Here's a recording comparing flash vs ruffle :) That update pending is just a security update. I'm on Chrome 85. 
![3lUrfic56r](https://user-images.githubusercontent.com/51363864/94662781-30705c80-034c-11eb-92d6-40b0c77938f4.gif)

Edit:
I am running Chrome 86 on Windows 10. This is AVM1 according to the previous issue on this same SWF. 

P.S. It'd be nice if there were an issue template that included the information in https://github.com/ruffle-rs/ruffle/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by Herschel** [comment]
Thanks for the report!
