### ISSUE TITLE
Overhaul - can't start

### ISSUE THREAD

**Issue by theonlypwner** [ruffle-rs/ruffle#12448]
### Describe the bug

1. Download SWF from https://uploads.ungrounded.net/599000/599683_overhaul_ng.swf
2. Load SWF at https://ruffle.rs/demo/
3. Try to start the game.

The game doesn't start.

### Expected behavior

I expect the game to start.

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Chrome 115.0.5790.102

### Additional information

Clicking the start button will result in 2 errors in the DevTools console:

```
ERROR core/src/avm2/globals/flash/net/shared_object.rs:54 SharedObject::get_local: Movie was None
ruffle_web-wasm_extensions.js:716 ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "mouseUp", class: flash.events::MouseEvent, ptr: 0xbcd38f8 }) to handler FunctionObject(FunctionObject { ptr: 0xcb1f350 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: data)
```

Each time the button is clicked, the value of the first `ptr` changes, while the second `ptr` value remains the same.

**Comment by Lord-McSweeney** [comment]
For some reason, this only worked on desktop Ruffle with `--spoof-url http://uploads.ungrounded.net/599000/599683_overhaul_ng.swf` for me.
