### ISSUE TITLE
web: Sound Only Plays Once 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1245]
In a few of the simulators ive played on ridesims.com the audio will only play once? On the Stealth simulator, the 3..2..1.. audio when the train launches only plays the one time. Where as in flash it plays it on every launch. 

**Source file:** https://ridesims.com/sites/default/files/2020-09/StealthV1.swf
**Steps to replicate:** 
Turn the power on
Hold R until it flashes as complete 
Click maintenance mode
Click blocks and turn them all on 
Press down and wait 
Press Space to launch 
When it comes all the way back around, press up
Then space to enter load again 
Then press down and wait again 
Press space to launch the train again and it doesn't play the sound clip

**Comment by JamesAllgood** [comment]
Think I just found the issue with the sounds not replaying:

think i just found the sound bug! 
It doesn't loop sounds if in my swish i have an option ticket which is called 'do not play if already playing'

so basically ruffle is not saying a sound has finished playing so it won't play as it thinks its still playing.

**Comment by Herschel** [comment]
Need to fix event sounds with the "NoMultiple" flag on web; seems like sound instances get "leaked" and never get removed from the instances list.

The clicking seems to be in the actual sound's MP3 data, but the sample count in the DefineSound tag causes it to cut of before the click plays in the official Flash Player; will take a little bit of time to fix.

**Comment by Herschel** [comment]
Split out the first issue into #1304.

**Comment by Herschel** [comment]
Fixed by #1303.
