### ISSUE TITLE
Games - 8 Planet - Arantius.com https://games.arantius.com/game.86.8+planet.html Level 

### ISSUE THREAD

**Issue by cmlad26** [ruffle-rs/ruffle#12452]
Where can we found the level record for the game?.
Previously there was a file mykaka_starBall.sol found in c:\Users\CURRENT USER\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\QXHRYVW2\static.arantius.com\games\8planet.swf\mykaka_starBall.sol.
It was very useful to save the file in order to preserve the last level achieved on other computer or after the reinstal the os.

The game works well now .

BR,

**Comment by n0samu** [comment]
Hi, the site you linked uses quite an old version of Ruffle. Newer versions of Ruffle have a Save Manager that allows you to import your save data from Flash Player. Here is an alternate site that uses the latest version of Ruffle: https://ooooooooo.ooo/static/?9ea350f0-e082-4e8d-ab64-162b7868c73f

To import your save data:
1. Start the game (getting to the main menu is enough).
2. Reload the page. Ruffle will create a save file.
3. Once the game has loaded again, right-click it and click "Open Save Manager".
4. Click the "Replace" button and select your .sol file.
5. Reload the page one more time, and your progress will be restored!

**Comment by cmlad26** [comment]
Great work, many thanks, now it's working like the old full version.BR,Cristian
    Pe luni, 31 iulie 2023, 11:26:34 EEST, nosamu ***@***.***> a scris:  
 
 


Hi, the site you linked uses quite an old version of Ruffle. Newer versions of Ruffle have a Save Manager that allows you to import your save data from Flash Player. Here is an alternate site that uses the latest version of Ruffle: https://ooooooooo.ooo/static/?9ea350f0-e082-4e8d-ab64-162b7868c73f

To import your save data:
   
   - Start the game (getting to the main menu is enough).
   - Reload the page. Ruffle will create a save file.
   - Once the game has loaded again, right-click it and click "Open Save Manager".
   - Click the "Replace" button and select your .sol file.
   - Reload the page one more time, and your progress will be restored!
