### ISSUE TITLE
3 Pandas in Fantasy: Coercion failed: cannot convert Object@00000000000 to Array

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#12458]
### Describe the bug

The game is stuck at the end of the first level

SWF - https://data.gameflare.com/games/6700/Corve3JZ8rUgtr.swf
Game - https://www.gameflare.com/online-game/3-pandas-in-fantasy/

Same error in the test for Vector - https://github.com/ruffle-rs/ruffle/issues/12321

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Note that this error also appears, but it's unrelated (stubbing it doesn't help): `ReferenceError: Error #1069: Property uncaughtErrorEvents not found on flash.display.Loader and there is no default value.`

**Comment by Lord-McSweeney** [comment]
Should be fixed by #12470
