### ISSUE TITLE
Asterius: The intro dialogue only shows "undefined" as its text

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#12463]
### Describe the bug

Tested on Ruffle Nightly 2023-07-31
How To Raise A Dragon SWF used: [asterius.zip](https://github.com/ruffle-rs/ruffle/files/12217815/asterius.zip)

This is what the game looks like in the Ruffle Demo.

https://github.com/ruffle-rs/ruffle/assets/36887711/f8d0a1bf-bd9b-4807-b126-ddbe755df7c0

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://github.com/ruffle-rs/ruffle/assets/36887711/3ba0257b-27c6-4f27-9f11-628a96b6aabb

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 115

**Comment by ArbestRiAgain** [comment]
Is this for AVM2?
