### ISSUE TITLE
LoZ: Forgotten Battle: Unkown Panic on menu screen

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1248]
LoZ: Forgotten Battle was previously noted for the Play button not working. In the latest Ruffle build, it gets an Unknown panic error when the menu screen appears.

https://www.newgrounds.com/portal/view/296880/format/flash?emulate=flash

# Error Info
Error name: Error
Error message: Unknown panic
Error stack:
```
Error: Unknown panic
    at Object.Y (https://www.newgrounds.com/js/ruffle/lib/core.ruffle.4ed2bf53bae7fdd931e6.js:1:31344)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:808)
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[1409]:0x22f6bd
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[1315]:0x221253
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3452]:0x2c0d23
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[2724]:0x2a6576
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3623]:0x2c3d00
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3748]:0x2c57ea
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3554]:0x2c2a92
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[700]:0x19373f
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.newgrounds.com/portal/view/296880/format/flash?emulate=flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Herschel** [comment]
Looks like libflate is failing to decompress one of the images inside this data. Might be worth switching over to flate2 (as this has a pure Rust backend now and seems to work successfully).
