### ISSUE TITLE
Siblings Untitled 04 - Second "Play Movie" button doesn't work.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1249]
Siblings Untitled 04 has an initial play button that works but then you arrive on a menu where the menu options are upside-down. None of the buttons work on this screen (I imagine this menu itself has been vertically flipped, if that could be part of it).

https://www.newgrounds.com/portal/view/566355/format/flash?emulate=flash

**Comment by waspennator** [comment]
Tested out on my end and cannot replicate the issue anymore, both of the upside down menu buttons seem to work fine now. I can click play to watch the movie or the scrap book button, as well as the captions button too.
