### ISSUE TITLE
setVolume Support, with example games

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1251]
Ruffle doesn't appear to have setVolume support. It's important to note that in AS2, setVolume will set the volume for everything unless you are setting the volume for a sound attached to a dedicated movieclip.

In Dad 'n Me, you will hear two songs playing at once - one of these songs is meant to have a volume of zero, so the game can crossfade between them. Both songs are playing at all times so they remain in-sync.

https://www.newgrounds.com/portal/view/254456/format/flash?emulate=flash

In The Room, when you enter a shop you will hear both songs play for a moment during what should be the crossfade transition:

https://www.newgrounds.com/portal/view/547307/format/flash?emulate=flash

There may be similar issues with support for getVolume, getPan and setPan.

**Comment by Herschel** [comment]
Fixed by #2825.
