### ISSUE TITLE
the tickey game on one more level . com doesint load at all its stuck at 0%

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#12533]
### Describe the bug

http://www.onemorelevel.com/game/ticket

https://github.com/ruffle-rs/ruffle/assets/136838819/cd908e77-b833-4482-9253-ab07dd7fbf92

here is the bug in action

### Expected behavior

for the game to load past 0%

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by n0samu** [comment]
This happens because the game relies on the Spil Games API, which no longer exists. In Flashpoint, Ruffle panics due to a different problem, see #12366
