### ISSUE TITLE
splitting chapter 1 not working

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#12531]
### Describe the bug

cant start game while pressing space bar on splitting chapter 1  http://www.onemorelevel.com/game/splitting_chapter_1 

https://github.com/ruffle-rs/ruffle/assets/136838819/7b69b715-e66a-4e24-98bb-2522218d9fae

### Expected behavior

for the game to work while pressing spacebar like the game says too

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by Lord-McSweeney** [comment]
This seems to work fine for me.

**Comment by Lord-McSweeney** [comment]
No one on Discord could reproduce this- can you try again? I would guess that the tab was not focused.

**Comment by Lord-McSweeney** [comment]
Closing as no one could reproduce this.
