### ISSUE TITLE
bros. adventure - can't enter the game

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#12542]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/02e5997b-501b-40c5-ab53-adf15fd9b5f8

[bros.zip](https://github.com/ruffle-rs/ruffle/files/12256383/bros.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/179c155a-8ce1-468b-abd5-ae7ab5e4a162

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by SuchAFuriousDeath** [comment]
For some reason it's trying to coerce a function into an XML.

**Comment by Aaron1011** [comment]
It looks like this uses a `for each` loop on an `XML` object. A quick test shows that this produces exactly one element - the object itself.

**Comment by Lord-McSweeney** [comment]
I think this was fixed by #13954.
