### ISSUE TITLE
the demo isn't working

### ISSUE THREAD

**Issue by Shadoe12** [ruffle-rs/ruffle#1255]
the demo isn't working here's the details.
# Error Info
Error: Error loading movie: Invalid data: Invalid SWF

# Player Info
Allows script access: false

# Page Info
Page URL: http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html?file=synj1.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 12239.92.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.136 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Poopooracoocoo** [comment]
I don't get that error when I erase `?file=synj1.swf` from the URL.
btw is that chrome 76 or have you modified your user agent? just curious

**Comment by Shadoe12** [comment]
I did what you said and the demo's working. Thanks for the advice, and as
to what version this is, it's this Version 76.0.3809.136. So you're right.

**Comment by Poopooracoocoo** [comment]
Chrome is on 85 now. You may want to check for updates!

**Comment by Shadoe12** [comment]
My chromebook is Version 76.0.3809.136. I think that's the final version
for the chrmoebook I have.

**Comment by Shadoe12** [comment]
My chromebook is Version 76.0.3809.136. I think that's the final version
for the chromebook I have.

**Comment by Herschel** [comment]
The 'file' query parameter was no longer supported; I removed it so that in no longer displays an error. The proper URL for the demo is now: http://ruffle.rs/demo/

**Comment by Poopooracoocoo** [comment]
@Shadoe12 It's back! See issue #1642 and its PR #1680 :)
