### ISSUE TITLE
Audio badly out of sync

### ISSUE THREAD

**Issue by Dwedit** [ruffle-rs/ruffle#12567]
### Describe the bug

Streamsound is badly out of sync on Ruffle Nightly 2023-08-05.  Video is playing a whole second ahead of the audio.

### Expected behavior

Audio is supposed to be reasonably in sync, no more than 150ms away from the visuals.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 116.0.1

### Additional information

Nightly from 2023-03-01 is syncing much better, but even that build has some audio sync problems.

**Comment by n0samu** [comment]
Hi @Dwedit, can you provide a link to content that exhibits this problem?
