### ISSUE TITLE
Fancy Pants Advntures: world 2 crashes the Web Player

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#1257]
Fancy Pants world 2 crashes ruffle web player demo, this is the error code:
# Error Info
Error name: Error
Error message: Unknown panic
Error stack:

Error: Unknown panic
    at Object.H (http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/1.index.js:1:31471)
    at __wbg_new_df6e6ab7a65c4c4d (http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.js:1:655)
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[1399]:0x234f4d
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[1306]:0x226c7d
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[3480]:0x2c97b3
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[2874]:0x2b5a63
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[3654]:0x2cc858
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[3781]:0x2ce3bc
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[3161]:0x2c1b3c
    at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/0e266e83b669e8a84726.module.wasm:wasm-function[2600]:0x2a67c8

# Player Info
Allows script access: false

# Page Info
Page URL: http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Here is the .swf of world 2 I was using for testing:** 

[FPA 2.zip](https://github.com/ruffle-rs/ruffle/files/5321840/FPA.2.zip)

**Comment by Mohamed-moneim-said** [comment]
Fancy Pants Adventures: world 2 it's made in avm2 as3 and ruffle player not supported avm2 yet

**Comment by Fancy2209** [comment]
No it uses ActionScript 2, the first Fancy Pants game who uses ActionScript 3 is **World 1** **Remix**

**Comment by Fancy2209** [comment]
Oh, AVM2, maybe it can use that idk, sorry

**Comment by Fancy2209** [comment]
Oh, AVM2, maybe it can use that idk

**Comment by torokati44** [comment]
The `.swf` in the attached `.zip` no longer seems to crash the [web demo player](https://ruffle.rs/demo/).
It takes a long time to load, the framerate is quite bad, and many graphical elements are missing, but it is "playable", and I see no sign of a crash.
The `ruffle_nightly_2020_10_20_linux` desktop build produces the same result, and spams some error messages to the console:
`ERROR ruffle_render_wgpu] Tessellation failure: TooManyVertices`
and then a couple instances of
`ERROR ruffle_core::library] Tried to instantiate non-registered character ...`

**Comment by Fancy2209** [comment]
I tried it, since it wasn't working on the demo I tried with the extension, it gives me this error
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
    at Object.Y (chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/core.ruffle.js:1:20274)
    at __wbg_new_df6e6ab7a65c4c4d (chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/ruffle.js:1:29866)
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[1204]:0x226a96
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[1352]:0x241151
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[3564]:0x2eb8c8
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[2807]:0x2cf2b7
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[3908]:0x2f0d68
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[3863]:0x2f058c
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[3909]:0x2f0d91
    at chrome-extension://adfembigocbejaonafnhheedgbhahnae/dist/24c205d8648502b1d521.module.wasm:wasm-function[1939]:0x28cac6
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://uploads.ungrounded.net/420000/420606_FPAWorld2.swf?123
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=5fa44dea42f70&NewgroundsAPI_SessionID=5D2WAWo5GvLAA5koKDVZ70b5ea9eb31c5445a664981294ef4c1820861802IteQ&NewgroundsAPI_UserName=P-Medeiros&NewgroundsAPI_UserID=7920581&ng_username=P-Medeiros
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
Attribute 5: [object Attr]

# Page Info
Page URL: https://www.newgrounds.com/portal/view/420606

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.58
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by torokati44** [comment]
In Firefox 82.0.2, with the latest Nightly build, I get this:
![image](https://user-images.githubusercontent.com/288816/98291838-0bef4c00-1fac-11eb-995c-826639a66078.png)

**Comment by desertking** [comment]
Sadly still not working yet. It mostly is back and has this kind of errors:

ruffle-object.js:81 Tried to instantiate non-registered character tehgroundMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character surfaceMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character aPlatzMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character SBLayerMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character tehhangzMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character BLayerMenus1
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character aPlatzMenus2
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character SBLayerMenus2
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81 Tried to instantiate non-registered character tehhangzMenus2
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:81
ruffle-object.js:81

**Comment by n0samu** [comment]
This is working in the desktop app now, and should work on web as well once it's switched over to wgpu.
