### ISSUE TITLE
Kongregate API (Konduit) doesn't work with ruffle 

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#12582]
### Describe the bug

The Kongregate API does not work on ruffle due to some functions being stubbed, preventing some functionality of those games from working.
```
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.system.Capabilities.os getter
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.system.Security.allowDomain()
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.system.Security.allowInsecureDomain()
WARN core/src/stub.rs:126 Encountered stub: AVM2 XML.settings()
WARN core/src/stub.rs:126 Encountered stub: AVM2 XML.setSettings()
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.xml.XMLNode.nodeName setter
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.media.Sound constructor with arguments
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.net.LocalConnection.allowDomain()
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.net.LocalConnection.allowInsecureDomain() 
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.net.LocalConnection.connect()
```

### Expected behavior

Konduit would work properly, allowing for example badges to be unlocked

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla Firefox 115.2.1

**Comment by Fancy2209** [comment]
I got confused, Konduit doesn't work anymore and is not the API for Kongregate
Which means I gotta figure out why the hell ruffle never tells me they load the Kongregate API

**Comment by colin-i** [comment]
Konduit doesn't work with Ruffle on Kongregate site, yes.

Flash Player is making:
`Attempting to connect to Kongregate API`
...
`[Konduit] API connection established!`
...
`[Game:JS] Message received: Object { opcode: "hello", params: Object }` with success=true at Object
...
Same for `kongregate.stats.submit();`
