### ISSUE TITLE
Text on Shootorial does not work properly

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#12603]
### Describe the bug

I only tested Part 1 of Shootorial
https://game24537.konggames.com/gamez/0002/4537/live/FlashGameTutorialShell.swf?kongregate_game_version=1224203434
![imagem](https://github.com/ruffle-rs/ruffle/assets/64917206/a7e6d6e5-f849-4676-8e9b-c5c70f554ab3)

### Expected behavior

![imagem](https://github.com/ruffle-rs/ruffle/assets/64917206/2c986395-9832-481b-b051-88f69364efec)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla Firefox 116.0.1

**Comment by Lord-McSweeney** [comment]
Fixed by #13923.
