### ISSUE TITLE
File Browser Won’t Open in s2online.github.io

### ISSUE THREAD

**Issue by FlamedDogo99** [ruffle-rs/ruffle#12613]
### Describe the bug

s2online.github.io contains a copy of the original scratchflash editor and player. Loading the website with ruffle causes no errors, however many features are broken, such as uploading a file or moving blocks in the editor.
Here is the swf file: https://github.com/FlamedDogo99/FlamedDogo99.github.io/blob/main/Scratch.swf

### Expected behavior

Expected behavior:
![Showing file picking menu](https://github.com/ruffle-rs/ruffle/assets/96555444/3c2006e5-ab8c-4cf0-8f2c-63f75f1f99e9)
Current behavior: (no prompt is displayed)
![Not showing file picking menu](https://github.com/ruffle-rs/ruffle/assets/96555444/66519324-d112-4663-a3de-e90f52deb441)

### Affected platform

Browser's extension

### Operating system

MacOS Ventura

### Browser

Brave 1.56.14

### Additional information

I’m assuming this is just due to AMV2 features that haven’t been implemented yet, but I thought it wouldn’t hurt to report this.

**Comment by Lord-McSweeney** [comment]
Continuing from #9058 (original Scratch 2 issue). A list of issues:
`XML.setName` unimplemented, causing issues with drawing sprites
`DisplayObject.getObjectsUnderPoint` (#11970) unimplemented, causing the block dragging issues
`FileReference.browse` unimplemented in AVM2, causing the file browsing issue

**Comment by FlamedDogo99** [comment]
Shoot didn't realize this was a duplicate, thanks!

**Comment by Lord-McSweeney** [comment]
Currently this mostly works but starts up slowly due to `by.blooddy.crypto.image::PNG24Encoder.encode` taking a long time to run.

**Comment by FlamedDogo99** [comment]
Also downloading just doesn't work, although I don't know if that was being addressed with this originally

**Comment by FlamedDogo99** [comment]
Everything appears to be functional now.
