### ISSUE TITLE
Does the latest version of rule still not support the display of Simplified Chinese?

### ISSUE THREAD

**Issue by wangyang12611** [ruffle-rs/ruffle#12674]
### Describe the bug

Does the latest version of rule still not support the display of Simplified Chinese? I'm trying to solve the problem of Chinese not being able to display effectively by using like ：
player.registerFont('MyFont', '/font/NotoSansSC-Regular.otf');

 fonts: {
    		        'Font1': {src: '/font/NotoSansSC-Medium.otf'},
    		        'Font2': {src: '/font/NotoSansSC-Regular.otf'}
    		      } 

None of the above has any effect

### Expected behavior

Want to display correct Chinese in flash

### Affected platform

Self-hosted version

### Operating system

win10

### Browser

google chrome

### Additional information

no

**Comment by wangyang12611** [comment]
# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics P630 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://localhost:8080/srm/test6.jsp
SWF URL: http://localhost:8080/srm//isop/jsp/designer/flexflow/flowmonitor.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.125 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-10
Channel: nightly
Built: 2023-08-10T00:23:43.496Z
Commit: fb01473bb3a096d9afca4e464ce6961a45b09045
Is extension: false

# Metadata
width: 500
height: 375
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 377670

**Comment by Lord-McSweeney** [comment]
Ruffle does not currently implement a way to convert font files to SWF font tags. This would be a great addition, though!

**Comment by fgott** [comment]
waiting

**Comment by evilpie** [comment]
Fixed by #17668.
