### ISSUE TITLE
Snailiad - Freeze after first cutscene

### ISSUE THREAD

**Issue by GTcreyon** [ruffle-rs/ruffle#12688]
### Describe the bug

The game freezes after the opening cutscene.

Steps:
- Start the game
- Start a new game
- Either watch the cutscene or skip it with Esc

https://www.snailiad.com/Snailiad.swf

### Expected behavior

The game should boot into the gameplay area.

### Affected platform

Online demo

### Operating system

Linux, EndeavourOS

### Browser

Mozilla Firefox 116

### Additional information

Error log:

![image](https://github.com/ruffle-rs/ruffle/assets/67928545/099f7ff3-d78b-4a41-b2eb-5bcd0e789101)

Sample: `ERROR core/src/avm2/events.rs:424 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x161d4cb8 }) to handler FunctionObject(FunctionObject { ptr: 0x4249cb8 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: visible)`

These errors appear continuously.

**Comment by GTcreyon** [comment]
> This is a performance issue, particularly in Chromium-based browsers. Increasing the `maxExecutionDuration` or using Firefox or the desktop app solves the problem.

Are you sure? I've never used a Chromium-based browser with Ruffle.

**Comment by n0samu** [comment]
Performance may also vary depending on your device. Please try increasing the "Maximum allowed ActionScript execution duration (in seconds)" setting in the browser extension, then running the SWF through the extension's SWF player. Let me know if that resolves the problem.

**Comment by GTcreyon** [comment]
> Performance may also vary depending on your device. Please try increasing the "Maximum allowed ActionScript execution duration (in seconds)" setting in the browser extension, then running the SWF through the extension's SWF player. Let me know if that resolves the problem.

I don't use the extension, I was using the online demo. Should I use the extension instead, to test this?

**Comment by n0samu** [comment]
Yes please

**Comment by GTcreyon** [comment]
Both the extension and the web app now work with no alterations. They both freeze for a while, but they eventually get through to the game, and no errors are reported. I assume that either the bug was fixed already, or moving to a new system (laptop running Arch instead of desktop PC running EndeavourOS) since I reported this has resolved the issue for me. I apologize for taking so long to respond.
