### ISSUE TITLE
Morningstar does not automatically continue after intro video

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#12686]
### Describe the bug

In [Morningstar](https://ooooooooo.ooo/static/?7a673991-f6e5-4c0f-86e1-6dc1b14cfe80), immediately after the intro video is over, the title and menu are supposed to appear. But in Ruffle, the game doesn't detect when the intro video has finished, so you have to manually click the Skip button in the lower-right corner to start the game.

### Expected behavior

See above

### Affected platform

Browser's extension

### Operating system

Windows 10

### Additional information

Tested with #12091.

**Comment by Lord-McSweeney** [comment]
This is still not working.

**Comment by n0samu** [comment]
Fixed by #13168
