### ISSUE TITLE
Knighttron - screen is shifted

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#12683]
### Describe the bug

like https://github.com/ruffle-rs/ruffle/issues/12485 , the screen is shifted

flash:

https://github.com/ruffle-rs/ruffle/assets/103858019/e267a4d0-3733-455b-94b9-010513536c2c

Ruffle : 

https://github.com/ruffle-rs/ruffle/assets/103858019/7d7c42f7-b77a-4e01-a4f8-b60a735f0d3a

`ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x5635073d6a40 }) to handler FunctionObject(FunctionObject { ptr: 0x5634f8b60b90 }) : ArgumentError: Error #2015: Invalid BitmapData.
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x56350cd11760 }) to handler FunctionObject(FunctionObject { ptr: 0x5634f8b60b90 }) : ArgumentError: Error #2015: Invalid BitmapData.
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x563503a226a0 }) to handler FunctionObject(FunctionObject { ptr: 0x5634f8b60b90 }) : ArgumentError: Error #2015: Invalid BitmapData.
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x56350533f0d0 }) to handler FunctionObject(FunctionObject { ptr: 0x5634f8b60b90 }) : ArgumentError: Error #2015: Invalid BitmapData.
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x5635093338c0 }) to handler FunctionObject(FunctionObject { ptr: 0x5634f8b60b90 }) : ArgumentError: Error #2015: Invalid BitmapData. `

### Expected behavior

the main menu animation should play and allow you to press the sword to begin

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

[Knighttron.swf.zip](https://github.com/ruffle-rs/ruffle/files/12318255/Knighttron.swf.zip)

**Comment by Fewnity** [comment]
It's fixed now, but the game has poor performances
