### ISSUE TITLE
ruffle tries and fails to load, even when flash is usable

### ISSUE THREAD

**Issue by griffen2** [ruffle-rs/ruffle#12691]
### Describe the bug

I have been using Pale Moon for about a year now, and I've had the latest working version of flash installed. Recently I have discovered that flash games/animations work on archives of newgrounds, at least they did for a week, recently it has been trying to load Ruffle instead, which doesn't work, I keep receiving the error "Ruffle failed to load the required ".wasm" file component."

The issue only seems to affect archive.org (I also receive the issue on the Ruffle website) no other websites as far as I'm aware. I don't know why this is happening, I have tried clearing the cache, removing all my archive.org related cookies, I have tried enabling/disabling WebAssembly things in the settings for Pale Moon.

### Expected behavior

Flash should load, on most websites I've used it works fine, it is just archive.org and it has only been recently. It might be an archive.org issue, but I at least want to check and see if there's a solution before just giving up.

If you ask for proof that flash worked at any point, please ask me and I can provide (just not immediately, I am kind of busy right now)

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Pale Moon 32

**Comment by Dinnerbone** [comment]
Modern versions of Ruffle has specific checks in place to make sure that it lets Flash take over if Flash is present - but unfortunately the version on the Wayback Machine predates those checks. We're hoping to see them update soon.

**Comment by danielhjacobs** [comment]
See also https://forum.palemoon.org/viewtopic.php?f=70&t=30109&p=241715

**Comment by mrflarion33** [comment]
thank you for not only showing me how to fix the issue but also explaining why it was an issue in the first place, this has been driving me crazy! thank you again
