### ISSUE TITLE
Mondo Mini Shows

### ISSUE THREAD

**Issue by Pedroformance48463** [ruffle-rs/ruffle#12695]
### Describe the bug

I want to see old cartoon on there!

### Expected behavior

Good Nice and Nice

### Affected platform

Online demo

### Operating system

Android

### Browser

Google Chrome

### Additional information

I don't know...

**Comment by Lord-McSweeney** [comment]
As far as I know the shows are still available on https://mondomedia.com/ . I couldn't find them on the Wayback Machine (not archived? iframes fail to load), so I'm closing the issue.
