### ISSUE TITLE
Black screen with audio on Factory Balls (Old Coolmath Games Version)

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#12713]
### Describe the bug

https://web.archive.org/web/20110928225127/http://www.coolmath-games.com/0-factory-balls-1/factory-balls-1.swf

In Web Ruffle, attempting to run Coolmath Games' old copy of Factory Balls results in a black screen (the coolmath logo never appearing) and the main menu music playing. The games works fine on Standalone Nightly 8-12-2023, but fails on Web Nightly 2023-08-09 and the Web Demo.

Here is what appears in the console:
![image](https://github.com/ruffle-rs/ruffle/assets/138401463/463c73db-5933-4d1c-9a22-5de94526876d)

### Expected behavior

Coolmath Games logo appears, and then main menu appears.

### Affected platform

Online demo

### Operating system

Windows 10 22H2

### Browser

Firefox 116.0.2 64-bit

**Comment by n0samu** [comment]
This is a sitelock, not a bug:
```as
if(domain != "" && domain != "coolmath-games.com")
{
    _root._x = 50000;
    _root._y = 40000;
}
```
