### ISSUE TITLE
stick war ruffle doesnt work

### ISSUE THREAD

**Issue by SpaceWallaby936** [ruffle-rs/ruffle#12726]
### Describe the bug

on the websites ive been to including my own, the button at the start of the first level arnt registerd as there

### Expected behavior

i wish the bug could be fixed

### Affected platform

Browser's extension

### Operating system

windows

### Browser

chrome

**Comment by n0samu** [comment]
Already reported in #12115 and #5126

**Comment by SpaceWallaby936** [comment]
> Already reported in #12115 and #5126

then can it be fixed?

**Comment by n0samu** [comment]
Eventually yes, but I don't know when yet.
