### ISSUE TITLE
does not work rene gade racing on flashstore .com

### ISSUE THREAD

**Issue by kakalakabaka** [ruffle-rs/ruffle#12762]
### Describe the bug

does not work rene gade racing on flashstore .com

### Expected behavior

does not work rene gade racing on flashstore .com

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

gogle

### Additional information

does not work rene gade racing on flashstore .com

**Comment by Lord-McSweeney** [comment]
Closing in favor of #12761.
