### ISSUE TITLE
Mega Miner Fail to load

### ISSUE THREAD

**Issue by ruizdavid120** [ruffle-rs/ruffle#12809]
### Describe the bug

When starting the game Mega Miner, the options for "Load Game" and "New Game" will not appear. Instead, Gems will be on the ends of where the words should be. They used to previously still load the game if clicked but now do not load the game at all. The links below those options still work to send you to armor games but not the buttons to start playing.

### Expected behavior

It is expected that the Load and New Game words appear and for them to actually load the game.

### Affected platform

Online demo

### Operating system

Windows 11 Pro

### Browser

Google Chrome

**Comment by n0samu** [comment]
This was regressed by #12326

**Comment by n0samu** [comment]
Seems like this is fixed now.
