### ISSUE TITLE
SSF2 is stuck in 100%

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#12815]
### Describe the bug

Go to https://www.supersmashflash.com/play/ssf2/

Wait until it gets to 100%

It doesnt even start at all or even get past the loading screen

### Expected behavior

When it reaches 100%,it should start and we can play the game.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 115

**Comment by Lord-McSweeney** [comment]
It is not fully loaded at 100%. For whatever reason, SSF2 loads over 4 times more assets after it hits 100% compared to when the progress percentage is between 0% and 100%. SSF2 has been reported to work very slowly on some devices, but both other users and I can confirm that it _does_ work, you just need to wait (and probably also increase the script timeout duration).

Closing in favor of #12671 (also performance-related).
