### ISSUE TITLE
Stealth Hunter 2 - Can't click on buttons on Main menu

### ISSUE THREAD

**Issue by Molisson** [ruffle-rs/ruffle#12826]
### Describe the bug

The bug happens when I try to click any of the buttons on the main menu.

![bug](https://github.com/ruffle-rs/ruffle/assets/81079603/ea3535d8-f966-42aa-9d76-026b2646d05f)

Here are the steps to reproduce just in case
1. Click the start button, it takes you straight to the main menu.
2. Click on any of the buttons I mentioned marked with the red line.

Here's the self-hosted version where I tried to play Steath Hunter 2.
https://www.newgrounds.com/portal/view/592710?emulate=flash

### Expected behavior

The buttons can be clicked and can play level 1 as usual.

### Affected platform

Self-hosted in Browser

### Operating system

Windows 11

### Browser

Microsoft Edge (Chromium)

### Additional information

Here is the error I got when trying to click on one of any buttons.
```ERROR core/src/avm2/events.rs:424 Error dispatching event EventObject(EventObject { type: "mouseDown", class: flash.events::MouseEvent, ptr: 0xb858720 }) to handler FunctionObject(FunctionObject { ptr: 0xee037d0 }) : RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)")```

I have no clue as to why it errored there

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/12242
