### ISSUE TITLE
What is the Ruffle logo font??

### ISSUE THREAD

**Issue by TemaisgameNoobas** [ruffle-rs/ruffle#12840]
What is the Ruffle logo font?? Or is it custom?? Thanks for the best flash emulator by the way.

**Comment by torokati44** [comment]
AFAIK the logo was custom drawn, not using any font.
And thanks!

**Comment by TemaisgameNoobas** [comment]
Alright, I am sure someone out there will make a font!! Should I close this issue??

**Comment by torokati44** [comment]
Your question was answered, so I think so. :)
I considered converting it to a discussion, as it should have been that really, but it was short lived, so it's fine...

**Comment by TemaisgameNoobas** [comment]
Ok, I want to convert it, but I dont know how to do that. I don't know Github like a master, so how do I convert this issue??

**Comment by torokati44** [comment]
I think it can stay here now. I'm just going to close it. :)
