### ISSUE TITLE
Amorphous+ not playable

### ISSUE THREAD

**Issue by joey2264** [ruffle-rs/ruffle#12877]
### Describe the bug

Game is not playable because it doesn't respond to mouse movement or clicks once in a game (the menu is navigable with a mouse).  https://jayisgames.com/games/amorphous/

### Expected behavior

the character follows the mouse cursor in the game and swings the weapon when you click

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Chrome 116

**Comment by Lord-McSweeney** [comment]
This is a regression caused by #12063. Versions after (but not including) nightly 07-19-2023 repeat this error: `Error: A 'with' action failed because the specified object did not exist.`

**Comment by Lord-McSweeney** [comment]
@CUB3D, pinging you as the author of the PR that caused the regression.

**Comment by bobjrsenior** [comment]
#12253 has two more examples of games affected by this.
