### ISSUE TITLE
Error on https://www.g7r.com/hacked/action/madness-project-nexus-v1-8-by-0neuser/

### ISSUE THREAD

**Issue by popoluarshark** [ruffle-rs/ruffle#12887]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at a.wbg.__wbg_new_df6e6ab7a65c4c4d (https://www.g7r.com/js/ruffle.js?1111:1:6553)
    at std::sync::once::Once::call_once::{{closure}}::hce6501f6f20767e4 (wasm://wasm/0148da5e:wasm-function[1471]:0x2bfd2d)
    at std::sync::once::Once::call_inner::hd3d269a4946f2df2 (wasm://wasm/0148da5e:wasm-function[1752]:0x2f41ec)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h6ed7686ed76cb258 (wasm://wasm/0148da5e:wasm-function[5184]:0x3fa7b7)
    at std::panicking::rust_panic_with_hook::h4f753dc70b771d8e (wasm://wasm/0148da5e:wasm-function[3968]:0x3cc3d0)
    at std::panicking::begin_panic_handler::{{closure}}::h5c9fc29957309ae8 (wasm://wasm/0148da5e:wasm-function[4676]:0x3ed57f)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h92808941d97e9b21 (wasm://wasm/0148da5e:wasm-function[5556]:0x4004f0)
    at rust_begin_unwind (wasm://wasm/0148da5e:wasm-function[5427]:0x3feafd)
    at core::panicking::panic_fmt::hbd8a975261a5f466 (wasm://wasm/0148da5e:wasm-function[5557]:0x400526)
    at ruffle_web::Ruffle::tick::hcc9377f967fc44c7 (wasm://wasm/0148da5e:wasm-function[714]:0x1dddae)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.g7r.com/hacked/action/madness-project-nexus-v1-8-by-0neuser/
SWF URL: https://www.hackedarcadegames.com/swf/mc_nexus.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-19
Channel: nightly
Built: 2021-03-19T00:19:11.729Z
Commit: 7eb4c1440abc39360d4de148311b5fad46b92696

I turned off the browser's blocking advertisement and still couldn't get in.

**Comment by n0samu** [comment]
This is a very old version of Ruffle. Please test in a more recent version of Ruffle.

**Comment by popoluarshark** [comment]
> This is a very old version of Ruffle. Please test in a more recent version of Ruffle.这是一个非常古老的Ruffle版本。请在最新版本的 Ruffle 中进行测试。

How can I test in the latest edition

**Comment by popoluarshark** [comment]
> This is a very old version of Ruffle. Please test in a more recent version of Ruffle.这是一个非常古老的Ruffle版本。请在最新版本的 Ruffle 中进行测试。

Excuse me, does ruffle have Android?

**Comment by popoluarshark** [comment]
> This is a very old version of Ruffle. Please test in a more recent version of Ruffle.这是一个非常古老的Ruffle版本。请在最新版本的 Ruffle 中进行测试。

# Error Info
Error name: Error
Error message: RuntimeError: unreachable
Error stack:
```
Error: RuntimeError: unreachable
    at Ve.load (https://ruffle.rs/demo/index.js:2:273658)
    at async Ve.reload (https://ruffle.rs/demo/index.js:2:272766)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Qualcomm, Adreno (TM) 650, OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 4096, max_texture_dimension_2d: 4096, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1600, height: 1980, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 12; DBY-W09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Linux armv8l
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-22
Channel: nightly
Built: 2023-08-22T00:19:54.090Z
Commit: 3de4b4e989afb873b207eb885177b193a4d53b4e
Is extension: false

# Metadata
The latest version seems to have some bugs?

**Comment by n0samu** [comment]
When exactly does that error happen for you?

**Comment by popoluarshark** [comment]
> When exactly does that error happen for you?该错误究竟何时发生在您身上？

Sometimes it happens.

**Comment by popoluarshark** [comment]
The old version will be smoother. Is there a solution?

> > When exactly does that error happen for you?该错误究竟何时发生在您身上？
> 
> Sometimes it happens. 有时它会发生。
