### ISSUE TITLE
Movie Not Loading?

### ISSUE THREAD

**Issue by DecieverJinn** [ruffle-rs/ruffle#1288]
[This page](https://www.newgrounds.com/portal/view/562894) contains a Flash file which is supposed to be ran by Ruffle, but it is not working. Please take care of that.

**Comment by Herschel** [comment]
Disabled Ruffle on the NG submission for now. Will investigate what the issue is (this is an AS2 SWF, so should hopefully work).

**Comment by Herschel** [comment]
Looks like this is working on master (need to update the Ruffle build on NG).
