### ISSUE TITLE
Problems with parla.cat

### ISSUE THREAD

**Issue by shinmai-rookie** [ruffle-rs/ruffle#12903]
### Describe the bug

Parla.cat is an online service to learn Catalan, a Romance language with 9 million speakers which uses the Latin alphabet with some non-ASCII characters (sort of like Spanish+French and a middle point). When running this course (which is probably one of the few non-abandoned sites that still use Flash) with Ruffle, it fails to show these characters properly (all instances of Ã by itself or followed by "fancy" characters here are mojibake):

![Screenshot_20230731_152020](https://github.com/ruffle-rs/ruffle/assets/11900662/442a9145-5f0a-4f4e-be20-001b91d4e269)

This is in the logged in part of the site, as the demo part doesn't load at all (not as important, but it *is* a bug).

### Expected behavior

This is what that same course looks like in Flash Player in Windows 7:

![Screenshot_20230731_152349](https://github.com/ruffle-rs/ruffle/assets/11900662/55beacbc-cecd-4726-9a4d-46796a99cec1)

Incidentally, I think it might be a good idea to just add a menu to pick an encoding, so that even if a user finds an encoding problem (which is something that will probably never be 100% fixed) they have a fighting change to at least make it do immediately, without (or in addition to) resorting to a bug report.

### Affected platform

Browser's extension

### Operating system

Debian 12

### Browser

Firefox 102.14.0esr

**Comment by n0samu** [comment]
This seems to be fixed by #12893 (but please let me know if I missed anything!). The fix won't be available in Firefox for some time, since Mozilla's update approval process is slow. I've opened a new issue (#12928) for the problem with the demo.
