### ISSUE TITLE
[Feature Request] Implement a way to disable Local Storage

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#12943]
Certain Flash titles only allow you [one chance](https://www.newgrounds.com/portal/view/555181) to complete it.
However those titles also allowed Local Storage to be disabled in web browsers.
So the suggestion is to have a simple way to disable local storage as well as having it as a command line for that single instance of playing the title.

Flash Player's implementation:
![image](https://github.com/ruffle-rs/ruffle/assets/12412764/a0e7a036-41d2-4fc6-85da-eb5671107724)

**Comment by n0samu** [comment]
Right-click => Open Save Manager => Delete the relevant save file

**Comment by n0samu** [comment]
We don't have a save manager in the desktop app yet, but that feature request is already covered by #8470

**Comment by Spikestuff** [comment]
The other request and mine are different.
Mine is a request for a more permanent disable/deletion for a session instead of a temporary one which would restore practically immediately.

**Comment by n0samu** [comment]
Ah okay, I understand now. Actually this would also be useful for testing games that break with an existing save file, such as Learn to Fly 3 (#10888)

**Comment by sleepycatcoding** [comment]
This has been implemented in #15785.

**Comment by sleepycatcoding** [comment]
> Just for knowledge what's the command line for it (as that was also part of the request)?

`--storage` with options being `disk` (save data is stored as was previously) or `memory` (saves data to memory for this session, no reads from disk, no writes to disk).
