### ISSUE TITLE
Error on https://y.hentaichan.live/games/e/1356699096_eroani-2//7603-eroani-2-iroiro.html

### ISSUE THREAD

**Issue by AlexButuzov** [ruffle-rs/ruffle#12949]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://y.hentaichan.live/games/e/1356699096_eroani-2//7603-eroani-2-iroiro.html?cacheId=1356699069

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-07
Channel: nightly
Built: 2023-07-07T00:20:07.173Z
Commit: c60742428c75fe42476dfe66d6f4f215bf8b773f
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing, network error is not an issue with Ruffle.
