### ISSUE TITLE
Error on https://z0r.de/1741

### ISSUE THREAD

**Issue by seisenreich** [ruffle-rs/ruffle#13007]
# Error Info
Error name: TypeError
Error message: TypeError: Load failed
Error stack:
```
error@[native code]
@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://z0r.de/1741

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-14
Channel: nightly
Built: 2023-07-14T13:29:48.707Z
Commit: 5a8b40445c37517cbfa5dd97eceb85682586b5b7
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Looks like a transient server error. If this problem is happening consistently, please leave a comment and we can look into it.
