### ISSUE TITLE
Random function in actionscript 2 

### ISSUE THREAD

**Issue by charco57** [ruffle-rs/ruffle#13016]
### Describe the bug

I have some AS2 that works fine in flash player, but does not return a randomised array in ruffle. 
I am using it to randomise an array. The two variables element and stack are arrays.
The stack array contains a list of values (e1, e2, e3, e4 etc.)
The shuffle() function is supposed to randomise the array order.

The function is: 

function shuffle(element, stack):Number {
	var num:Number = Math.round(Math.random()*2)-1;
	return num;
}

It is called using:

element = stack.sort(shuffle);

The element array is then supposed to contain the values of the stack array in randomised order.
This works in flash player, but not in ruffle.

Any ideas?

### Expected behavior

I can provide a link to the flash:

http://localhost/colsol/fun/swf/pt_test1.htm

When level 1 is clicked the elements that appear one after the other should be randomised, but they are more or less in the same order 1 ==> 20, although there is _some_ mixing.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

FF116.03 64 bit version

**Comment by charco57** [comment]
Sorry, I left a local link - it should be 
https://www.colourful-solutions.com/fun/swf/pt_test1.htm

**Comment by Dinnerbone** [comment]
Can you please try updating your version of Ruffle? That version is turning 3 years old soon!

**Comment by charco57** [comment]
I've just updated to the latest version and now nothing works! I can't even see the flash onscreen!!

Here is the embed code that I was/am using:

<!DOCTYPE html><html>
<head>

 
<title>Periodic table familiarity test 1</title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="../css/swf.css" type="text/css">
<script type="text/javascript" src="../../chemistry/IB25/ruffle/ruffle.js"></script>
</head>

<body bgcolor="#eeeeee" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

 
<div class="flash">
  <embed src="pt_test1.swf"  width="100%" height="100%" wmode="transparent">
  </embed> 
 </div>

</body>

</html>

I have not changed anything except the ruffle package (all files) and now it does not show. The path has to be correct, as I uploaded the unzipped files to the same ruffle directory online.

**Comment by Dinnerbone** [comment]
You'll need to change your `flash.css` file, add the following marked line:

```css
.flash{
    position: absolute;
    top:0;
    left:0;
    width:100%;
    height:100%; // <--------- this line
}
```

**Comment by charco57** [comment]
I have put the old version of ruffle back and the flash files on https://www.colourful-solutions.com/fun/
all work (but not the random function) 
I can include a link to the new ruffle version on the website on the same page...
In the first box there are identical versions of swf files that point to the new build of Ruffle but do not render.
https://www.colourful-solutions.com/fun/
The path is identical except the new ruffle is in a directory called ruffle_new.

**Comment by Dinnerbone** [comment]
The ones with new ruffle appear to be working for me, and the random also seems to work. I see you've applied the css fix I mentioned - have you cleared your browser cache to make sure that works? (try ctrl+F5 on the page)

**Comment by charco57** [comment]
Dinnerbone - the change in swf.css did the trick - wow!
AND the new Ruffle is behaving itself with the randomising function, so all's right with the world.
Thanks a lot guys - I would never have got there on my own.
CC
