### ISSUE TITLE
slow loading on new build

### ISSUE THREAD

**Issue by charco57** [ruffle-rs/ruffle#13022]
### Describe the bug

Hi, I recently updated to the latest build of ruffle and it shows all of the flash animations with the ruffle splash screen for an appreciable amount of time before the content renders. I am using the "run now" code that I used with the older version of ruffle.

I have this placed at the end of the ruffle.js file

window.RufflePlayer = window.RufflePlayer || {};
    window.RufflePlayer.config = {
    "autoplay": "on", 
    "splashscreen": false, 
    "unmuteOverlay":"hidden",
    "Transparent":"transparent"
};

### Expected behavior

I would like the flash content to load with the page without the ruffle splash screens being so visible.
Is it possible?

An example of the issue can be seen at: https://www.colourful-solutions.com/chemistry/IB25/04.13.php

It needs a login email: "graeme@ibchem.com" and password: "kenneth"

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

FF117.0 64 bit

### Additional information

Prior to the upload of the latest build, the flash content displayed with no ruffle splash screen.

**Comment by charco57** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/129694258/5be8e6cf-4bd1-4b23-9ae4-6524297ad09e)

**Comment by n0samu** [comment]
- I see that you changed the Ruffle configuration by editing the ruffle.js file. Please do **not** do this; instead you should place the code within a <script> tag on the webpage or a separate .js file.
- The correct configuration option to disable the splash screen is `splashScreen`, not `splashscreen`. It is case sensitive!
- "Transparent" is not a valid configuration option. Were you thinking of `"wmode": "transparent"`?
- When many Flash elements are placed on the page, Ruffle tends to initialize slowly when using its default renderer. If you want Ruffle to initialize faster, and your content only uses very basic graphics, I'd suggest trying out some of the other preferredRenderer options, specifically "webgl" or "canvas". [See our wiki for details](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options).

**Comment by charco57** [comment]
OK - I have made a separate ruffle_mod.js file, linked everything and modified the configuration options as advised.
I will read up on preferred Rendered options - thanks for the heads-up and all your help.
Charco
