### ISSUE TITLE
Ruffle executable reports as a Trojan in Windows

### ISSUE THREAD

**Issue by GK6475** [ruffle-rs/ruffle#13032]
### Describe the bug

Ruffle's x64 executable is detected as a Trojan in Windows 11. Specifically, Trojan:Win32/Bearfoos.B!ml.

### Expected behavior

There should not be any indication that Ruffle is a Trojan at all.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by GK6475** [comment]
Nevermind, the 09/01 release fixed this. It was an issue with 08/31.

**Comment by Lord-McSweeney** [comment]
There have been various reports of Ruffle being detected as various different trojans, probably due to chunks of the executable code resembling trojans.
