### ISSUE TITLE
Error on https://prestige777.xyz/game/n-game

### ISSUE THREAD

**Issue by TheR1000** [ruffle-rs/ruffle#13068]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://prestige777.xyz/game/n-game

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-24
Channel: nightly
Built: 2023-08-24T00:20:48.719Z
Commit: 1b03ce9ae668ea2b40f03f24ad38af95d1e92e80
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing, network error is not an issue with Ruffle.
