### ISSUE TITLE
Domo-Kun Angry Smashfest - Script Times Out in Golden Axe stage

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1307]
https://www.newgrounds.com/portal/view/73449/format/flash?emulate=flash

The Golden Axe stage is unfortunately several levels into the game but this build skips directly there:

https://www.newgrounds.com/dump/item/a01ef9f27c2f69921a24c121e757204c

This build also does a weird skip ahead to Death Adder so if you get to him, you're past the part where it freezes. It froze for me on my second attempt, though, so should be pretty common. Bonus points if you can solve why it skips ahead to Death Adder before you get to ride the dragon!

Early in the level while fighting the first batch of enemies, the game may freeze and eventually time out.

A script in this movie has taken too long to execute and has been terminated.
dr @ core.ruffle.2112eb18f69d2e0727a6.js:1

No more actions will be executed in this movie.
dr @ core.ruffle.2112eb18f69d2e0727a6.js:1

My guess is that I went out of the bounds of an array, something Flash handles gracefully.

**Comment by Herschel** [comment]
Seems like this occurs when the player walks off the bottom of the platform. They are supposed to fall to their death but Ruffle hangs here.

I think this is another case of #893. The player code calls `_parent.gotoAndStop("fall")` which should immediately stop further execution of the code on the current frame, but this doesn't happen in Ruffle; the rest of the code continues to execute, which puts the game into an infinite frame loop as it switches between walk and fall frames.

**Comment by Herschel** [comment]
Dixed by #1320.
