### ISSUE TITLE
Error on https://www.txori.com/dbdevolution

### ISSUE THREAD

**Issue by Dennisttt** [ruffle-rs/ruffle#13084]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: true

Player type: Object
SWF URL: https://www.txori.com/data/documents/dbz/dbdev_dev.swf?id=1655667956
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.txori.com/dbdevolution

# Browser Info
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-03
Channel: nightly
Built: 2023-09-03T00:19:43.518Z
Commit: 2996f97578f4b9541029f0318d7b87a60664cf23
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing (most likely was a temporary network issue).
