### ISSUE TITLE
Learn to fly 2 - sounds issue

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#13086]
### Describe the bug

when playing after some time, you can increase the length of the ramp. when it is long enough, the sound of sliding down it repeats, until you jump off the ramp, but Ruffle keeps looping the sound

additionally, some ads continue to play audio even when they are no longer in view, overlapping the game audio, and sometimes repeating. I couldn't get the ads to play any sound at all on flash player,  even on browser since I think projectors may block some internet connectivity. 

flash: 

https://github.com/ruffle-rs/ruffle/assets/103858019/45e5fd13-ca6c-45cb-8fe6-8cd51fb74d8e

Ruffle

https://github.com/ruffle-rs/ruffle/assets/103858019/d558550b-39dd-44b3-ac52-7be89145e1df

### Expected behavior

the sliding sound should not loop, but for the ads, I'm not sure if they should be playing sound at all, or if they should, but the audio should stop after closing it and starting the game

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

[learntofly2.zip](https://github.com/ruffle-rs/ruffle/files/12540325/learntofly2.zip)

**Comment by Lord-McSweeney** [comment]
The ads issue is related to mixed AVM.

**Comment by Lord-McSweeney** [comment]
I think the ads issue is related to an issue where orphaned MC's (not sure if unloaded ones also count) shouldn't move frames forward.
