### ISSUE TITLE
In Scratch 2, cannot drag blocks

### ISSUE THREAD

**Issue by Secret-chest** [ruffle-rs/ruffle#13108]
### Describe the bug

I cannot drag blocks in the Scratch 2 editor, they simply will refuse to stay where I put them.

### Expected behavior

To be able to drag and run blocks.

### Affected platform

Browser's extension

### Operating system

Linux Mint 21.2 (Cinnamon 5.8.4, Kernel 6.2.0-26-generic)

### Browser

Ungoogled Chromium 112.0.5615.165

**Comment by Lord-McSweeney** [comment]
(This is because `DisplayObjectContainer.getObjectsUnderPoint` is unimplemented)

**Comment by Lord-McSweeney** [comment]
Fixed by #11970.
