### ISSUE TITLE
Error on https://www.getgames.io/games/BleachVsNaruto/2.6/index.html

### ISSUE THREAD

**Issue by Kayden1234x** [ruffle-rs/ruffle#13113]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.getgames.io/games/BleachVsNaruto/2.6/index.html

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-27
Channel: nightly
Built: 2023-08-27T00:20:08.420Z
Commit: 378b415a3b76603a92a00d81d21f128763b6bd8f
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Looks like a transient network error.
