### ISSUE TITLE
Arrow of time Unplayable

### ISSUE THREAD

**Issue by Gnomecromancer** [ruffle-rs/ruffle#13119]
### Describe the bug

When you run Arrow of time, if you attempt to create a save it will show that it is created and you can't get past the menu screen.

Edit: [link](http://www.xgenstudios.com/game.php?keyword=the-arrow-of-time)

### Expected behavior

I want it to actually run and be playable

### Affected platform

Desktop app

### Operating system

macOS Monterey

### Browser

Google Chrome Version 116.0.5845.179 (Official Build) (x86_64)

**Comment by Lord-McSweeney** [comment]
Closing in favor of #9419.
