### ISSUE TITLE
"obfuscated_event_prefix" uninitialized variable error on some sites

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#1311]

**Comment by Herschel** [comment]
Is this self-hosted or the extension? What site causes the error?

**Comment by Toad06** [comment]
I was able to reproduce this issue on github.com and ebay.com.

The error seems to be located in: `web/packages/extension/js/index.js`, so eventually the line `if (obfuscated_event_prefix) {` could just be replaced with `if (window.obfuscated_event_prefix) {` ... However, Ruffle will still display "Checking Ruffle status on current tab", so it may be a deeper issue.

**Comment by Justin-CB** [comment]
I think I know what's going on now. I think that we get this error if `index.js` runs before the code that sets `obfuscated_event_prefix` in `lv0.js` runs. I think I can fix it by changing the condition to `window.obfuscated_event_prefix`, wrap the `if` block in a function, & re-run it after 500 ms or so if it fails.

**Comment by g8up** [comment]
I got the error in `ruffle_nightly_2020_11_20_extension.zip` : 
```
ruffle.js:1 Uncaught ReferenceError: obfuscated_event_prefix is not defined
    at Object.243 (ruffle.js:formatted:883)
    at di (ruffle.js:formatted:901)
    at ruffle.js:formatted:2181
    at ruffle.js:formatted:2183
```
- error locale at 
```js
{
    243: (e,t,n)=>{
      "use strict";
      var r = n(162);
      window.RufflePlayer = r.PublicAPI.negotiate(window.RufflePlayer, "extension", new r.SourceAPI),
      obfuscated_event_prefix && document.addEventListener(obfuscated_event_prefix + "_request", (function(e) {
        JSON.parse(e.detail).action;
        let t = new CustomEvent(obfuscated_event_prefix + "_response",{
          detail: JSON.stringify({})
        });
        document.dispatchEvent(t)
      }
      ))
    }
  }
}
```

test page: http://news.cctv.com/2019/02/02/VIDElbNwaQHikrCN3qVtNIsx190202.shtml
