### ISSUE TITLE
Crash with amd drivers in linux

### ISSUE THREAD

**Issue by AirDog46** [ruffle-rs/ruffle#13145]
### Describe what you were doing

This mostly happens every time I start ruffle, not just Run 3.

Steps to reproduce:
1. Start ruffle
2. Move the mouse in the window or try to interact
3. It crashes

Hardware config:
Ryzen 7 5800x with an RX 6900xt
tested with AMD pro and amdvlk drivers. Doesn't ouccur with radv drivers

Tested on the website release and AUR package

### What does the crash message say?

panicked at 'Surface became unavailable: Timeout', desktop/src/gui/controller.rs:198:14

### Ruffle Version

0.1.0-nightly (f092fa5809b76c6f6ba5f6dc2f07ce0b73b3427b 2023-09-11)

### Affected platform

Desktop app

### Operating system

Arch Linux Rolling Release [64-bit]

### Additional information

Filename: Run3.swf

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD Radeon RX 6900 XT"
Adapter Device Type: DiscreteGpu
Adapter Driver Name: "AMD proprietary driver"
Adapter Driver Info: "(AMD proprietary shader compiler)"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 8192, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by dekrain** [comment]
I have been encountering the same issue for some time now. I suspected it might have to do with Wayland instead of vulkan drivers.
I made a workaround that seems to be working most of the time:
```diff
diff --git a/desktop/src/gui/controller.rs b/desktop/src/gui/controller.rs
index 2b3e57892..903d54396 100644
--- a/desktop/src/gui/controller.rs
+++ b/desktop/src/gui/controller.rs
@@ -192,10 +192,25 @@ impl GuiController {
     }
 
     pub fn render(&mut self, mut player: Option<MutexGuard<Player>>) {
-        let surface_texture = self
-            .surface
-            .get_current_texture()
-            .expect("Surface became unavailable");
+        let mut counter = 0usize;
+        let surface_texture = loop {
+            counter += 1;
+            let result = self
+                .surface
+                .get_current_texture();
+            match result {
+                Ok(texture) => break texture,
+                Err(wgpu::SurfaceError::Timeout) => {
+                    std::thread::sleep(std::time::Duration::from_millis(10));
+                    continue;
+                }
+                Err(err) => panic!("Surface became unavailable: {err}")
+            }
+        };
+        if counter > 1 {
+            counter -= 1;
+            tracing::error!("Surface timeouted {counter} times");
+        }
 
         let raw_input = self.egui_winit.take_egui_input(&self.window);
         let show_menu = self.window.fullscreen().is_none() && !self.no_gui;

```

**Comment by sebastien46** [comment]
Still happens on latest version of `amdvlk` & ruffle-git `0.1.0-nightly (41ddb316a2b0a91c0d32e8f54eb0f020be42831f 2023-12-07)`
