### ISSUE TITLE
Ruffle extension doesn't intercept .swf files

### ISSUE THREAD

**Issue by kotenok2000** [ruffle-rs/ruffle#13147]
### Describe the bug

Open https://www.mspaintadventures.ru/storyfiles/hs2/cascade/cascade_loaderExt.swf
Chrome downloads it.

### Expected behavior

Ruffle intercepts it and plays.

### Affected platform

Browser's extension

### Operating system

Microsoft Windows [Version 10.0.22621.2215]

### Browser

Chrome 116.0.5845.180

### Additional information

Ruffle extension version: 0.1.0 nightly 2023-09-09

**Comment by Dinnerbone** [comment]
It is not possible to intercept swf files in Manifest V3, so we unfortunately had to remove that feature.

In lieu of it, there's a new "Open SWF Player" button in the ruffle menu, which you can use to open arbitrary SWFs and SWF URLs.
