### ISSUE TITLE
web: Music does not stop on game over screen in Luigi's Day (regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1315]
This issue only affects the Web backend and is not present in nightly builds <= 2020-10-12.

Steps to reproduce:
- Let Luigi fall in the water (game over screen).
- OR hit the "?" block and enter the cave (next level).

https://www.newgrounds.com/portal/view/44505

**Comment by Herschel** [comment]
The music track is throwing the AudioNode "ended" event prematurely for some reason.

**Comment by Toad06** [comment]
Weird. Note that if you click "Replay" at the game over screen, two instances of the sound will then play, but if you fall again in the water, then the last instance created will stop.

**Comment by Toad06** [comment]
Copter is also affected by this bug (http://www.donpixel.com/play/041012152052/). When you maintain the left button down and release it, the game will sometimes continue to play the "climbing up" sound effect.
