### ISSUE TITLE
Ruffle object has no width and height properties available

### ISSUE THREAD

**Issue by robinheidrich** [ruffle-rs/ruffle#13176]
The `<object>` tag has width and height properties available ([see here](https://www.w3schools.com/jsref/dom_obj_object.asp)), but since `<ruffle-object>` is not a real object it does not. For compatibility reasons, it might be a good idea to do this (if possible).

For example, I use a JavaScript code to adapt the object to the screen size (to make it responsive to the website) using the width and height properties of the object.

If this is not planned, I would have to fallback to clientWidth and clientHeight 🙁.

```js
document.querySelector("object").height
480
```

```js
document.querySelector("ruffle-object").height
undefined
```

Tested in Chrome 117.

**Comment by danielhjacobs** [comment]
Also worth noting, this applies to multiple properties listed on https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement and https://developer.mozilla.org/en-US/docs/Web/API/HTMLEmbedElement#browser_compatibility
