### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by BwenedianJr** [ruffle-rs/ruffle#13190]
Hi,
Can you add the ability to download requested files in ruffle?
https://scratchflash.bwenedianbanan1.repl.co This is the website that embeds the swf but I can’t download projects inside!
The swf file is here: https://github.com/BwenedianJr/Scratch-for-ruffle/raw/main/Scratch%202.0.swf

**Comment by Lord-McSweeney** [comment]
I'm unsure, what do you mean? Do you mean that clicking the download button (exporting a Scratch project) doesn't work?

**Comment by BwenedianJr** [comment]
Yes, and the same for upload

**Comment by Lord-McSweeney** [comment]
In that case, closing in favor of #12613 (same issue)
