### ISSUE TITLE
Audio streams in different movies with the same character ID will overwrite each other

### ISSUE THREAD

**Issue by kmeisthax** [ruffle-rs/ruffle#1319]
`AudioBackend` was implemented way before multiple movie support, so SWF character IDs are used directly to identify audio streams during the `preload` step. This results in a potential conflict: if a movie with audio characters in it loads another movie with audio characters, any characters in the latter will overwrite the former's sounds if they share the same ID. e.g.

1. `main.swf` registers a ding sound in character 3, some BGM in character 5, and a crash sound in character 8
2. `main.swf` loads `level1.swf`
3. `level1.swf` registers a jump sound in character 5
4. The game's BGM is overwritten with the sound of jumping

The above is a hypothetical example: I don't have a test-case movie with music that breaks when it loads a new movie in. However, we do have a number of issues floating about involving sound in multi-load movies and this may be the cause of at least some of them.

**Comment by Herschel** [comment]
This only affects web because the clip ID is used for aggregating the stream when preloading.  It could just be an increasing ID. On desktop the ID is ignored.

(Might be better to finally bite the bullet and use ScriptProcessor/AudioWorklet for streams on web, instead of decoding everything ahead of time).

**Comment by Herschel** [comment]
Fixed in #2825 and various other changes; character ID is no longer used to identify a stream on web.
