### ISSUE TITLE
web: dynamic box with text is shown in "fast dia show" instead triggered by object position

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#1321]
In Flash, you can drag the earth and the info text changes accordingly to its position

In ruffle the the info text switches automatically very fast.

See http://www.webgeo.de/k_021/#4
(on http://www.webgeo.de you can switch between using ruffle or using flash)

Version: ruffle_web_2020-10-11
Video with wrong behavior: [k_021-4_ruffle_avi.zip](https://github.com/ruffle-rs/ruffle/files/5384407/k_021-4_ruffle_avi.zip)
![k_021-4_flash](https://user-images.githubusercontent.com/1667683/96116979-a1d21280-0ee9-11eb-89b5-3ecef7f7b1d5.png)
Flash-File: [k_021_04.zip](https://github.com/ruffle-rs/ruffle/files/5384414/k_021_04.zip)

**Comment by KMicha** [comment]
This is a relative new behaviour.
The earth is now no longer draggable at all (see #681). 
The labels are somehow shown, but with wrong content.

**Comment by Herschel** [comment]
Thanks for the reports!
