### ISSUE TITLE
Inspector Wombat: after 2023-07-20 nightly, the main menu is not clickable.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#13210]
### Describe the bug

[inspector-wombat.zip](https://github.com/ruffle-rs/ruffle/files/12640301/inspector-wombat.zip)

In the game **'Inspector Wombat'**, the main menu is not clickable.  As a result, i can't start the game.
This was not an issue up until Ruffle Nightly `2023-07-19`, but since the `2023-07-20` build it has been a problem.
(Tested on desktop build, self-hosted build)

In Adobe Flash Player, the mouse cursor appears as a regular cursor, and clicking on a menu takes you to that screen without any problems.

However, in Ruffle, the mouse cursor looks like the photo below. When you hover over the menu, a weird blue square appears, which is not visible in the original. Subsequent clicks on the menu are unresponsive.

![image](https://github.com/ruffle-rs/ruffle/assets/75052171/50e4ac5a-cb07-4e65-819b-084ab61f4657)

Here are the changes from Nightly `2023-07-20`:

![image](https://github.com/ruffle-rs/ruffle/assets/75052171/5cd313d1-0a83-4b8d-bd40-d59f178627dd)

### Expected behavior

Clicking on the main menu should work.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 117

**Comment by n0samu** [comment]
Another regression probably caused by #12063 :(
