### ISSUE TITLE
happl wheel was unable to exec by ruffle

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#1322]
website: http://totaljerkface.com/happy_wheels.tjf

error is too many, I believe you can go to that website by yourself, and you will see that issue

**Comment by Toad06** [comment]
That seems to be a Cross-Origin Request Sharing (CORS) issue. Ruffle cannot get the file at http://swf.totaljerkface.com/hw_preloader_bf.swf because CORS header "Access-Control-Allow-Origin" is missing.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by l12436** [comment]
Is there anything we can do or fix?

**Comment by l12436** [comment]
and there is one thing, happy wheel is also could not be start on offline.

**Comment by Justin-CB** [comment]
I think that Happy Wheels uses AS3, which is not really supported by ruffle yet & is separate from the CORS issue.

**Comment by Herschel** [comment]
AS3 content. Closing in favor of #1368.

**Comment by p0008874** [comment]
```
ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x2ae8078 }) to handler FunctionObject(FunctionObject { ptr: 0xcb12530, name: Ok("com.totaljerkface.game::PreLoaderNew/openGame()") }) : RustError("Character id doesn't exist")
```
