### ISSUE TITLE
ruffle was unable to show flash for embed flash website

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#1323]
website: http://gameschool.cc/game/736/
the flash is embed by those website.

Serious error loading Ruffle: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
堆疊追蹤
dist/ruffle.js:1 (匿名函式)
Serious error occurred loading SWF file: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
Asynchronous error occurred: Could not fetch movie http://swf.totaljerkface.com/hw_preloader_bf.swf

**Comment by Justin-CB** [comment]
This looks like a CORS issue from my cursory look at it.

**Comment by l12436** [comment]
I have disable that CORS and enable webassembly, game still show empty
and it show 
Asynchronous error occurred: Could not fetch movie http://www.gamedesign.jp/flash/radio/radio_en.swf

**Comment by Herschel** [comment]
AS3, closing in favor of #1368.

**Comment by aeivin3085-cloud** [comment]
What about this website https://flashthemes.net/
