### ISSUE TITLE
Error on https://www.gameflare.com/embed/the-last-stand-union-city/

### ISSUE THREAD

**Issue by UndeadRacist** [ruffle-rs/ruffle#13266]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/the-last-stand-union-city/

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-19
Channel: nightly
Built: 2023-09-19T00:26:29.263Z
Commit: 65d1ba48037290619bc8f1bef0eb931342e2c10c
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing since this was most likely a transient network error.
