### ISSUE TITLE
Work stiff - text issue

### ISSUE THREAD

**Issue by Croworbit** [ruffle-rs/ruffle#13280]
### Describe the bug

the text is either cut off of misaligned to the left

https://github.com/ruffle-rs/ruffle/assets/138729134/33c1c994-ce8c-49e2-8a14-9dee7a069c25

### Expected behavior

the text should work

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

https://www.newgrounds.com/portal/view/591299

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/18332
