### ISSUE TITLE
Error on https://www.minigiochi.com/helpers/game/sandbox.php

### ISSUE THREAD

**Issue by milano-007** [ruffle-rs/ruffle#13354]
# Error Info
Error name: Error
Error message: panicked at 'Unimplemented opcode LogicalAnd', render/naga-pixelbender/src/lib.rs:1235:29

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1600, height: 1100, depth_or_array_layers: 1 }

# Page Info
Page URL: https://www.minigiochi.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=22305&mp_game_uid=cargo-bridge-2&mp_game_url=https%3A%2F%2Fwww.minigiochi.com%2Fembed%2Fcargo-bridge-2&mp_int=1&mp_locale=it_IT&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvY2FyZ29icmlkZ2UyLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.minigiochi.com%2F&mp_site_name=minigiochi.com&mp_site_url=https%3A%2F%2Fwww.minigiochi.com%2F&mp_timezone=Europe%2FRome&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/cargobridge2.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-29
Channel: nightly
Built: 2023-09-29T00:21:45.562Z
Commit: ec7a8ac6453cbc48d12aaffc125dd4de79340f5b
Is extension: false

# Metadata
width: 800
height: 550
frameRate: 30
numFrames: 2
swfVersion: 12
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 2383667

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/13375
