### ISSUE TITLE
Martian Chase not displaying text properly

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#13364]
### Describe the bug

[martianchase.zip](https://github.com/ruffle-rs/ruffle/files/12772494/martianchase.zip)
Most text in Martian Chase just does not display at all, or what it does display is broken.
![ruffle_UdsmMljSax](https://github.com/ruffle-rs/ruffle/assets/138401463/c56b18f2-5ace-49f5-8adc-7b97e59e35ec)
![ruffle_iMYNRys5AV](https://github.com/ruffle-rs/ruffle/assets/138401463/34e43ebe-5d61-4043-9de3-d3efe01c2df2)
![ruffle_CcCpt7fDuP](https://github.com/ruffle-rs/ruffle/assets/138401463/e6621867-c653-4adb-b090-f87f5dd3e9bd)

When running on the web demo, this appears in the console:
![image](https://github.com/ruffle-rs/ruffle/assets/138401463/bc59c0d7-5a07-446c-8b83-ae6b1857e2a8)

### Expected behavior

![flashplayer_32_sa_WYUmdORzNS](https://github.com/ruffle-rs/ruffle/assets/138401463/37afd382-e7cd-4068-b195-69ff21831dff)
![flashplayer_32_sa_fDXBPHwFeP](https://github.com/ruffle-rs/ruffle/assets/138401463/beb8465f-80aa-4802-8fe8-1dcd96f2ff9c)
![flashplayer_32_sa_g7ym8FzADd](https://github.com/ruffle-rs/ruffle/assets/138401463/d33d4da8-9765-4d61-b1d9-248ae67ac382)

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Mozilla Firefox 118.0.1 64-bit

### Additional information

Tested on Nightly Standalone 9-29-2023 and Ruffle Web Demo.

**Comment by skiesofravens** [comment]
To enable duck mode, simply type in duck on the title screen.

**Comment by n0samu** [comment]
Text shows up more or less fine now
