### ISSUE TITLE
Error on https://web.archive.org/web/20130424214432/http://trickster.gametree.co.kr/

### ISSUE THREAD

**Issue by onidenki** [ruffle-rs/ruffle#13410]
# Error Info
Error name: TypeError
Error message: t[e] is not a function
Error stack:
```
TypeError: t[e] is not a function
    at Function.a (https://web.archive.org/_static/js/ruffle.js:2:97207)
    at Function.apply (https://web.archive.org/_static/js/wombat.js?v=txqj7nKC:21:64701)
    at https://web.archive.org/web/20130424214432js_/http://trickster.gametree.co.kr/Js/trickster.framework.js:81:103
    at async https://web.archive.org/_static/js/ruffle.js:2:105265
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://web.archive.org/web/20130424214432/http://trickster.gametree.co.kr/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.41
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-08-02
Channel: nightly
Built: 2023-08-02T00:22:54.390Z
Commit: 006393c5816e68b54c6720fcd8e657009cfb90d8
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing in favor of #13291
