### ISSUE TITLE
Ruffle freezes when loading any swf

### ISSUE THREAD

**Issue by kreudom** [ruffle-rs/ruffle#13422]
### Describe the bug

When trying to run any swf file in Ruffle, nothing is displayed and the window freezes, sometimes causing the whole desktop to freeze for a while.

Ruffle runs without any problems if I launch it without specifying a swf file, but as soon as I try to load one, Ruffle freezes.

When I specify a swf file as a command line argument, Ruffle freezes immediately.

The freeze happens on every swf file I tried, even on Ruffle's test swf files (like `tests/tests/swfs/avm1/add/test.swf`).

I tried both the latest nightly release and building from source.

### Expected behavior

Ruffle should be able to open files without freezing.

### Affected platform

Desktop app

### Operating system

Arch Linux x86_64

### Additional information

I used git bisect to track down the first commit that doesn't work for me: 2dcd78326144920bb6f0f39e05757fc1c077faf3

I further narrowed down the issue: The previous commit works. If I update wgpu-hal to 0.17.1 using `cargo update -p wgpu-hal`, the freezing occurs again.

I then used cargo's patching mechanism to track down which wgpu commit of the 0.17.1 release introduced the issue. This is the first commit that causes the freezing for me: gfx-rs/wgpu@1d0a22b1a8f38d9c9fe3418c543ee2bfaa046cb2

I confirmed that Ruffle does not freeze on the latest commit if I revert gfx-rs/wgpu@1d0a22b1a8f38d9c9fe3418c543ee2bfaa046cb2.

I am not sure if this is a bug in Ruffle or wgpu, but I figured I'd report it here. Let me know if you need any additional information.

**Comment by Lord-McSweeney** [comment]
You should probably report this to wgpu on their repository page. If the issue was caused by a regression in wgpu, then we can't fix it.

**Comment by kreudom** [comment]
Fixed in wgpu 0.17.2

It would just need to be merged into your ruffle-rs/wgpu fork

**Comment by kreudom** [comment]
Fixed in #13561
