### ISSUE TITLE
Crash on Air%20Tax%20Japan.swf

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#13446]
### Describe what you were doing

Game loads a bit on Mochi Ads loading bar, then crash.

Game from https://archive.org/details/air-tax-japan (which also crashes, but felt standalone was better to report for as this is the latest Nightly and IA is still on an old version :v

### What does the crash message say?

panicked at C:\Users\runneradmin\.cargo\git\checkouts\wgpu-c26c9ef766f7dc30\c4b8787\wgpu\src\backend\direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Sample count 10 is invalid

### Ruffle Version

0.1.0-nightly (3a658f5dec872218032a9545ae985dcbadd5c3d4 2023-10-05)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Home) [64-bit]

### Additional information

Filename: Air%20Tax%20Japan.swf

### AVM2 Callstack
```
	at flash.display3D::Context3D/flash::display3D::Context3D::configureBackBuffer()
	at starling.core::Starling/updateViewPort()
	at starling.core::Starling/initializeGraphicsAPI()
	at starling.core::Starling/initialize()
	at starling.core::Starling/onContextCreated()
	at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
	at flash.display::Stage3D/flash::display::Stage3D::requestContext3D_internal()
	at MethodInfo-1704()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD Radeon RX 6500 XT"
Adapter Device Type: DiscreteGpu
Adapter Driver Name: "AMD proprietary driver"
Adapter Driver Info: "22.20.27.09"
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_BC | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 8192, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by Aaron1011** [comment]
With https://github.com/ruffle-rs/ruffle/pull/13764 and https://github.com/ruffle-rs/ruffle/pull/13762, this is playable
