### ISSUE TITLE
Unable to select cards in Uno^3

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#13448]
### Describe the bug

[unoonline.zip](https://github.com/ruffle-rs/ruffle/files/12836034/unoonline.zip)

Input works when initiating gameplay, but once the game of Uno begins, no input, clicking or hovering, works.

![bXyOqwHsdf](https://github.com/ruffle-rs/ruffle/assets/138401463/639c11be-edfa-4630-8070-4fd72d023947)

Also occurs in browser as can be seen here: https://ooooooooo.ooo/static/?fb24ef48-00b6-b34f-098b-e5f75a296301

Console spams this:
![image](https://github.com/ruffle-rs/ruffle/assets/138401463/be2475ed-5fb0-4d12-bd77-febe00da79e7)

### Expected behavior

![Mwk1tqi3Mg](https://github.com/ruffle-rs/ruffle/assets/138401463/3f8dd45e-a529-4c9b-8023-da7949a8fb30)

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Mozilla Firefox 118.0.1 64-bit

### Additional information

Occurs on standalone nightly 10-6-2023

**Comment by Benman2785** [comment]
maybe this fixes "Obama vs Zombies" too ;)
