### ISSUE TITLE
Error on https://game14871.konggames.com/games/gameinabottle/gemcraft/frame/e906d24d-1f48-4355-b226-80f316493fd3/

### ISSUE THREAD

**Issue by shmup** [ruffle-rs/ruffle#13444]
# Error Info
Error name: Error
Error message: panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
339/V/n.wbg.__wbg_new_d258248ed531ff54@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:51724
core::ops::function::FnOnce::call_once{{vtable.shim}}::h73a0ca99bc054b64@:wasm-function[9652]:0x974d3a
std::panicking::rust_panic_with_hook::h3aa054d35a0817d7@:wasm-function[6335]:0x87ad8c
core::panicking::panic_fmt::h3e1dd3d08288569e@:wasm-function[9459]:0x96fc97
core::panicking::assert_failed_inner::hef8aa9140ed3b15c@:wasm-function[4561]:0x79c598
core::panicking::assert_failed::had88df7f4704db4c@:wasm-function[9480]:0x970ed6
ruffle_core::loader::Loader::movie_loader::{{closure}}::h5b5ec6e39cbab9bd@:wasm-function[562]:0x1187ef
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h3a286544bc2b345a@:wasm-function[1243]:0x4175ed
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd0cc05c5829d97cc@:wasm-function[4339]:0x77ff14
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1e9e983b40afc870@:wasm-function[10424]:0x9912a8
closure4221 externref shim@:wasm-function[10756]:0x996448
D@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:2866
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:2511
339/V/n.wbg.__wbg_open_7a2a86bf6285507d/<@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:24869
T@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:3019
339/V/n.wbg.__wbg_open_7a2a86bf6285507d@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:24836
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::navigate_to_url::ha9a93282999613f1@:wasm-function[598]:0x17a015
core::ops::function::FnOnce::call_once::h1ac07e13391aad5d@:wasm-function[1337]:0x452843
ruffle_core::avm1::function::Executable::exec::h8bdcd4e8b115646b@:wasm-function[663]:0x2030a7
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha31ec7791c6c0085@:wasm-function[6658]:0x88e56e
ruffle_core::avm1::activation::Activation::run_actions::ha9d5eb4a2103629c@:wasm-function[520]:0x23cbf
ruffle_core::avm1::function::Executable::exec::h8bdcd4e8b115646b@:wasm-function[663]:0x202f2e
<ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::ha31ec7791c6c0085@:wasm-function[6658]:0x88e56e
ruffle_core::avm1::runtime::Avm1::run_stack_frame_for_method::hcc9631248abc076d@:wasm-function[2538]:0x62daef
ruffle_core::player::Player::run_actions::h6785ee12c0a8becb@:wasm-function[905]:0x33ce14
ruffle_core::player::Player::update_mouse_state::h206726d401554e2e@:wasm-function[599]:0x1804a3
ruffle_core::player::Player::handle_event::hd1fe5aa84fd9c18c@:wasm-function[575]:0x13b674
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h09eb7870e39b95e9@:wasm-function[919]:0x348969
wasm_bindgen::convert::closures::invoke1_mut::h20802efe150ad39a@:wasm-function[10407]:0x991094
closure449 externref shim@:wasm-function[10755]:0x996433
v@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:2635
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.938208e886cb0e3d2cec.js:1:2511

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Intel(R) HD Graphics 400"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://game14871.konggames.com/games/gameinabottle/gemcraft/frame/e906d24d-1f48-4355-b226-80f316493fd3/?kongregate_host=www.kongregate.com
SWF URL: https://game14871.konggames.com/gamez/0001/4871/live/gemcraft-kongregate.swf?kongregate_game_version=1214663642

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-06
Channel: nightly
Built: 2023-10-06T00:21:25.739Z
Commit: 3a658f5dec872218032a9545ae985dcbadd5c3d4
Is extension: false

# Metadata
width: 640
height: 480
frameRate: 30
numFrames: 5
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 4520780

**Comment by shmup** [comment]
I've noticed it happens on Gemcraft with a few of in game tabs atop, Stats and Amulets

**Comment by n0samu** [comment]
Closing in favor of #12151
