### ISSUE TITLE
crash upon startup under Wayland + Hybrid GPU setup

### ISSUE THREAD

**Issue by cjrusko** [ruffle-rs/ruffle#13463]
### Describe what you were doing

Attempted to run Ruffle as soon as it was successfully installed

### What does the crash message say?

panicked at /home/main-builder/.cargo/git/checkouts/wgpu-c26c9ef766f7dc30/c4b8787/wgpu/src/backend/direct.rs:771:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

### Ruffle Version

0.1.0-nightly (b877a39c47cfd4155bf5a19e6e27b8bc40da09b3 2023-10-07)

### Affected platform

Desktop app

### Operating system

Arch Linux Rolling Release [64-bit]

### Additional information

The associated desktop environment is Hyprland (Wayland) ran by a hybrid graphics setup: an NVIDIA RTX 3050 Ti dGPU + Intel Tigerlake-H GT1 iGPU, running in "hybrid" mode as set by envycontrol, using the proprietary NVIDIA drivers, version 535.113.01. I get the same error when attempting to run the Rio terminal app.

**Comment by Firlaev-Hans** [comment]
Does it work when you run it with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json`?

I get the same error when running ruffle on my NVIDIA GPU in native Wayland mode, so I run Ruffle on my Intel iGPU (it's better for battery life anyways and Ruffle usually doesn't need much GPU power).
Alternatively you can set `WINIT_UNIX_BACKEND=x11` to force XWayland mode which should work with NVIDIA drivers.

I recall having the same issue with the game Veloren (also written in Rust and wgpu, just like oth Ruffle and Rio Terminal) so I doutb this is Ruffle's fault directly.

**Comment by cjrusko** [comment]
Both of those solutions, independently, worked beautifully, thank you! I just had to install the _vulkan-intel_ and _lib32-vulkan-intel_ drivers first before setting that first environmental variable. 

I agree that running ruffle on an Intel iGPU makes more sense: _nvtop_ was reporting ~5% gprocessor and 134MiB mem usage for ruffle to play a local .swf on _High (16x16)_ settings; the NVIDIA-Wayland driver was being a silly goose trying to delegate this to the dGPU. 

tangent: I'm really impressed by how lean and performant the Rust + wgpu combo is for emulating Flash compared to how I remember original, native Flash content performed on its era's contemporaneous hardware. It's not apples-to-apples of course, but even on 2023 hardware, og Flash would still be bound to a single CPU core and bottlenecked by that core's clock speed. So the ruffle devs are cooking with some potent necromancy here.
