### ISSUE TITLE
Capital letters don't render and menu items unclickable in Trick or Treat Adventure Quest

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#1346]
https://www.newgrounds.com/portal/view/408167/format/flash?emulate=flash

Current: When emulating the above via ruffle the capitalized letters in the in-game text boxes do not render. This game implements its own text-rendering scheme using MovieClips, so possibly a capital vs. lowercase namespace issue.

Expected: Text boxes render capital letters

Current: Nested buttons are not clickable (main menu website links and in-game actions)

Expected: All buttons clickable

**Comment by Herschel** [comment]
The buttons on the title screen are broken even in the Flash Player.
The in-game action buttons are doing `get("this.button")`, and it looks like Ruffle doesn't correctly support `this` in GetVariable.

**Comment by Herschel** [comment]
All of the above issues seem to be fixed. There are other issues with loading the save data (#1363).
