### ISSUE TITLE
AS3 Mouse Wheel Events Plz

### ISSUE THREAD

**Issue by KupoGames** [ruffle-rs/ruffle#13466]
Mouse Wheel events would be nice to have for my new game.
It's not urgent, but I'll need it eventually.

I need to detect that the mouse wheel is being used, to add a zooming feature in the game.
Probably not a lot of browser games used it, but it's helpful for desktop games!

Thanks.

**Comment by Lord-McSweeney** [comment]
AFAIK we've implemented mouse wheel events in AVM1, but not in AVM2.
