### ISSUE TITLE
Missing stub_setter import in TextRenderer.as causes stubs to not actually stub.

### ISSUE THREAD

**Issue by baconwaifu** [ruffle-rs/ruffle#13483]
### Describe the bug

When a script sets `TextRenderer.maxLevel`, which is supposed to be stubbed (it's implemented as a call to stub_setter) it instead crashes the script with "undefined variable stub_setter". Issue occurs in both web and desktop versions.

### Expected behavior

stub_setter does it's logging magic and the game continues as normal. 

### Affected platform

Desktop app

### Operating system

Debian testing

### Additional information

Confirmed to be resolved by adding the respective `import __ruffle__.stub_setter;` and `stub_getter` to TextRenderer.as and rebuilding, game then progresses as normal. (as it stands, TextRenderer currently only imports `stub_method` despite using all three)

**Comment by torokati44** [comment]
Thank you for the report and the included fix!
