### ISSUE TITLE
Typing/Writing doesn't Work

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1348]
First of all, Thank You Guys for the hard work you all doing to keep flash alive. 

I have a mini Education game and I tested on your Demo by uploading the flash file. Everything seems to be working fine, but it doesn't let type Name and Answer. So the only issue I see is typing/keyboard doesn't respond to text writing field. 

I am not sure if this area is still under development, but just though to let you guys know. If you need the flash file, here is Google Drive URL (github didn't let me upload flash).

https://drive.google.com/file/d/1H7L9ZcZeBEaV86A_7O6m6OEgGLHPu5Vy/view?usp=sharing

**Comment by Poopooracoocoo** [comment]
btw i think you can upload flash files in zips to github

**Comment by zohebnsr** [comment]
Thanks for the tip. I have uploaded now.
[Karappan_Poochi.swf.zip](https://github.com/ruffle-rs/ruffle/files/5414954/Karappan_Poochi.swf.zip)

**Comment by Dinnerbone** [comment]
Should be fixed with #1447
