### ISSUE TITLE
No Blending Modes

### ISSUE THREAD

**Issue by bbpanzu** [ruffle-rs/ruffle#135]
Here's from the original swf
![blednmode00](https://user-images.githubusercontent.com/45317642/69284596-fb886a80-0bbc-11ea-8562-4a7929bbf2e7.gif)

Here's from the emulator
![blednmode01](https://user-images.githubusercontent.com/45317642/69284601-fdeac480-0bbc-11ea-969a-52eab9836714.gif)

**Comment by Herschel** [comment]
Closing in favor of #58
