### ISSUE TITLE
SpinIn not loading game field

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#13542]
### Describe the bug

https://www.newgrounds.com/portal/view/665172/format/flash?emulate=flash

![image](https://github.com/ruffle-rs/ruffle/assets/138401463/d5920bf2-e6ed-4eb0-9a84-dbfd107799f3)

Error Messages From Console:
![image](https://github.com/ruffle-rs/ruffle/assets/138401463/22687e75-4dd3-46ac-baf2-d1edfba47b56)

### Expected behavior

![H6llkdN7rv](https://github.com/ruffle-rs/ruffle/assets/138401463/ac93e86a-3944-4598-b933-584cfca9f616)

### Affected platform

Browser's extension

### Operating system

Windows 10 22H2

### Browser

Mozilla Firefox 118.0.2 64-bit

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/13626
