### ISSUE TITLE
Give Up 2 - regression

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#13564]
### Describe the bug

game stuck after pressing play

https://github.com/ruffle-rs/ruffle/assets/98996990/4402c025-135b-40b5-94aa-f30042421673

[giveup2_viral.zip](https://github.com/ruffle-rs/ruffle/files/12909387/giveup2_viral.zip)

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/9e081c07-2cc2-4b29-96bf-847ba03bfa17

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Chrome 117.0.5938.152

**Comment by Lord-McSweeney** [comment]
I don't think this is a regression, but a very precise timing issue, similarly to other issues that have been recently reported. I can reproduce it on `10-02`, `10-05`, and `10-16`.
