### ISSUE TITLE
Carve 'n Share - PNG generation failure

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#13575]
### Describe the bug

https://www.newgrounds.com/portal/view/551135?emulate=flash

Carve 'n Share allows players to carve their own virtual pumpkin and share it with everyone. At the moment, when you try to save your pumpkin, the browser console error implies it's a CORS issue preventing the save from working. From what we're seeing on our end, however, we think something is failing with the PNG image generation in Ruffle, where it's not sending a proper file to our server and is getting rejected. Ruffle might not have support for this image generation feature yet.

### Expected behavior

Expected behavior is that users can save their pumpkins without error.

### Affected platform

Self-hosted version

### Operating system

Windows 7

### Browser

Chrome 109.0.5414.120

**Comment by Aaron1011** [comment]
I think this is a legitimate CORS issue on the Newgrounds side. Looking at the browser console, the cors OPTIONS request receives a response with the following response header:

```
access-control-allow-headers: Accept, X-Access-Token, X-Application-Name, X-Request-Sent-Time
```

This doesn't contain `Content-Type`, so the browser doesn't allow the POST to go through (the SWF manually `Content-Type: multipart/form-data; boundary="chphprjscpebnxowcmkddplxhrltwtpl"` when it tries to upload the file).

**Comment by TomFulp** [comment]
You're right and this is fixed on our end now, switching Carve n' Share to default to Ruffle!
