### ISSUE TITLE
SpongeBob: Pro Sk8r: Stuck on Preloader loop

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#13580]
### Describe the bug

https://www.numuki.com/game/spongebob-pro-sk8r/
Game seems to get stuck preloading with these 3 errors
Error dispatching event EventObject(EventObject { type: "creationComplete", class: mx.events::FlexEvent, ptr: 0x82a6780 }) to handler FunctionObject(FunctionObject { ptr: 0x5e85470 }) : ReferenceError: Error # 1065: Variable halfpipeCharacterMotion_mc is not defined.

Error dispatching event EventObject(EventObject { type: "creationComplete", class: mx.events::FlexEvent, ptr: 0x82a6eb8 }) to handler FunctionObject(FunctionObject { ptr: 0x5ea7c30 }) : ReferenceError: Error # 1065: Variable halfpipeCharacterMotion_mc is not defined.

Error dispatching event EventObject(EventObject { type: "creationComplete", class: mx.events::FlexEvent, ptr: 0x82a7560 }) to handler FunctionObject(FunctionObject { ptr: 0x5dc4f50 }) : ReferenceError: Error # 1065: Variable halfpipeCharacterMotion_mc is not defined.

### Expected behavior

For the game to actually load and be playable.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 117

**Comment by Aaron1011** [comment]
This seems to be loading now

**Comment by waspennator** [comment]
Yep, seems like its working now.
