### ISSUE TITLE
Spongebob: Sub-Zero Hero

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#13583]
### Describe the bug

https://ooooooooo.ooo/static/?2379cd1b-b5a1-41b3-b9ad-9fe2117671aa
Game softlocks into preloader loop as soon as you try to play the game.

[donbcfbmhbcapadipfkeojnmajbakjdc-1697511880471.log](https://github.com/ruffle-rs/ruffle/files/12923810/donbcfbmhbcapadipfkeojnmajbakjdc-1697511880471.log)

### Expected behavior

The game should be playable.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 117

**Comment by Lord-McSweeney** [comment]
This needs playerglobal/namespace versioning: `RustError("VerifyError: Trait z in class BaseCamera has same name as trait z in class DisplayObject, but does not override it")`

**Comment by Lord-McSweeney** [comment]
This is working now.
