### ISSUE TITLE
Letters missing on https://content.dnalc.org/content/1719/1719_fruitfly.swf

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#13602]
### Describe the bug

Text in the animation is missing the following letters, numbers, and punctuation:
- A C H I M S T U (all that appear except D)
- b c d k q v w x z
- 0 1 2 9 (all that appear)
- . , – - “ ” ! (all that appear except opening and closing parentheses)

Page is https://dnalc.cshl.edu/view/1719-Fruit-fly-Drosophila-melanogaster

SWF is https://content.dnalc.org/content/1719/1719_fruitfly.swf
![Screenshot from 2023-10-18 10-04-39](https://github.com/ruffle-rs/ruffle/assets/29206584/96feacef-859f-4678-a353-ed6d0627260f)

### Expected behavior

The full text corresponding to the transcript should appear in the animation.
![Screenshot from 2023-10-18 10-16-46](https://github.com/ruffle-rs/ruffle/assets/29206584/73db3ccd-2595-411c-a729-cd7fa9fa7d5a)

### Affected platform

Self-hosted version

### Operating system

Linux Fedora 37

### Browser

Mozilla Firefox 117

**Comment by danielhjacobs** [comment]
There is also https://dnalc.cshl.edu/view/1717-Rat-Rattus-norvegicus-.html, which is missing different letters. That one is missing:

- A I T (all that appear except R)
- b d f h k l m p w x y
- . -

**Comment by danielhjacobs** [comment]
Found the reasoning. Only those characters appearing in the heading are shown, with repeated instances of those same letters being show too.

The fruit fly animation shows:

- a e f g h i l m n o p r s t u y D ( )

The rat animation shows:

- a c e g i n o r s t u v R ( )

**Comment by danielhjacobs** [comment]
The fruit fly animation is using the Arial Bold font for everything, when the text content below the heading should be using Arial. See screenshots:
![Screenshot from 2023-10-18 11-17-40](https://github.com/ruffle-rs/ruffle/assets/29206584/ef0bb448-90c5-4a10-8158-89e0314ef20d)
![Screenshot from 2023-10-18 11-17-57](https://github.com/ruffle-rs/ruffle/assets/29206584/7367f0ec-2aa6-4e53-90f0-0d1c01ee2172)

**Comment by danielhjacobs** [comment]
Following discussion on Discord, it was established that this relates to some of the issues mentioned in https://github.com/ruffle-rs/ruffle/pull/13361, specifically the information labelled "Multiple fonts per... font..."

**Comment by Dinnerbone** [comment]
It looks like we're incorrectly thinking that all of the text should be bold, when it's actually not. This makes us look for bold fonts (even with my correct lookup PR), but that's the wrong one to use here.
