### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by FrolovSergey96** [ruffle-rs/ruffle#13619]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1697719279%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F637000%2F637838_PixeloForWebNewGround.swf%3F1407818942%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2265315c4910e7f%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A920%2C%22height%22%3A640%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F637000%2Fflash_637838_card.webp%3Ff1679278640%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-19
Channel: nightly
Built: 2023-10-19T00:23:16.593Z
Commit: fd4d6921d851e788b1386affae1498e46cda939c
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing since this was very likely a transient network error.
