### ISSUE TITLE
Super Drift 3D: Variable playhubLogo is not defined

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#13653]
### Describe the bug

The screen is black with the error:

```Variable playhubLogo is not defined```

Game URL - https://www.gameflare.com/online-game/super-drift-3d/
SWF - https://data.gameflare.com/games/1956/CUvD5sII8jA9qr.swf

### Expected behavior

progress the game

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
```
Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x55c53f8829b0 }) to handler FunctionObject(FunctionObject { ptr: 0x55c53f9e1d60 }) : ReferenceError: Error #1065: Variable playhubLogo is not defined.
	at flash.system::ApplicationDomain/flash::system::ApplicationDomain::getDefinition()
	at games.SuperDrift3D::PreloaderPlayhub/initPlayHubLogo()
	at games.SuperDrift3D::PreloaderPlayhub/loadingFinished()
	at games.SuperDrift3D::PreloaderPlayhub/checkFrame()
```

**Comment by Aaron1011** [comment]
This is a tricky interaction between preloaders and `Loader.loadBytes`. When running `Loader.loadBytes`, the loaded clip always appears to finish loading after the `exitFrame` for the current frame, and *before* the `enterFrame` for the next frame. This SWF relies on that behavior, as it calls `Loader.loadBytes` and expects the loaded class to be accessible in the very next call of an `enterFrame` handler.
