### ISSUE TITLE
Sounds not playing in SWF loading other SWFs

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#1365]
some of my larger flash game use wav as sound file.
ruffle seems not support this, and cause no sound on certain situation.

.wav also embed in swf.

platform: LInux Ubuntu 20.04
Ruffle: master commit 41f77fade1b10c0952a014ebb311a6b1d6708bd8
audio: pulseaudio with asound config.
```
pcm.!default pulse
ctl.!default pulse
```

**Comment by Herschel** [comment]
WAV PCM audio should be supported, could you post the SWF in question?

**Comment by l12436** [comment]
https://h-flash.com/octopus-pod/
this flash, although ruffle seems unable to run on web, I execute it offlline.

**Comment by Herschel** [comment]
These SWFs contain MP3 data, and the audio works here.

**Comment by l12436** [comment]
yes, but some charactor audio did not play the sfx is play normally.
This screen should has sound.
![Screenshot_20201023_102626](https://user-images.githubusercontent.com/2596649/96949359-4bcd2280-151a-11eb-85c1-9238d9c5da2b.png)

One thing forget to say, I run ruffle under linux, not windows.

**Comment by Herschel** [comment]
I think this is a case of sounds loaded from other SWFs not playing correctly, but needs investigation.

**Comment by l12436** [comment]
I just accidentally found that maybe this issue is due to the name of directory
the sound file original lay in the directory name SoundFIle but it seems work when it name as SoundFile
upper case "i" and lower case "i" issue
