### ISSUE TITLE
Stealth Hunter 2 - text is cut off on some places

### ISSUE THREAD

**Issue by Croworbit** [ruffle-rs/ruffle#13651]
### Describe the bug

![sc3r](https://github.com/ruffle-rs/ruffle/assets/138729134/c0debb69-0707-4708-a9de-8940504a1e6e)
![sc2r](https://github.com/ruffle-rs/ruffle/assets/138729134/2ffed937-223b-496c-b57a-bfed49525336)
![sc1r](https://github.com/ruffle-rs/ruffle/assets/138729134/6b0d84cd-896a-4c60-922d-a0187c53b334)

### Expected behavior

the text that is cutoff shouldn't be

### Affected platform

Desktop app

### Operating system

windows 10

**Comment by kjarosh** [comment]
This seems to be fixed after the recent batch of text fixes

**Comment by Croworbit** [comment]
I'll try it

**Comment by Croworbit** [comment]
the game crashes before I can get to the pistol, but the text is correct on achievements page

**Comment by kjarosh** [comment]
Could you file a separate issue for the crash? It makes organization easier

**Comment by Croworbit** [comment]
> Could you file a separate issue for the crash? It makes organization easier

@kjarosh I can open a new issue, but this looks like the same one https://github.com/ruffle-rs/ruffle/issues/14744
do you want me to make a new one anyway?

**Comment by kjarosh** [comment]
You're probably right! No need to create a new issue then

**Comment by Croworbit** [comment]
okay thanks. I'll test the gun tutorial once I can get there again!
