### ISSUE TITLE
avm2: Behavior difference with XMLList [[Put]] at length + string

### ISSUE THREAD

**Issue by evilpie** [ruffle-rs/ruffle#13676]
I tried to implement XML::appendChild like the spec suggests. Doing that I found a behavior difference between Ruffle and Flash. I think what Flash is doing might not match the spec in this case? @sleepycatcoding 

```as3
var xml:XML = <root><a/></root>
var xml_list = xml.*;
xml_list[xml_list.length()] = "foobar";
trace("xml: " + xml);
```
This produces the following in Flash
```xml
<root>
  <a/>
  <a>foobar</a>
</root>
```
and the following in Ruffle:
```xml
<root>
  <a/>
  foobar
</root>
```

**Comment by Lord-McSweeney** [comment]
I implemented this behavior correctly in `appendChild`- I guess the logic should be moved to `[[Put]]`.

**Comment by sleepycatcoding** [comment]
avmplus does something strange when XMLList has been appended to: https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/XMLListObject.cpp#L621

**Comment by evilpie** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/13678.
