### ISSUE TITLE
Stunt Master: Variable  is not defined

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#13671]
### Describe the bug

In the first level, the screen is black with the error:

```
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2a627dc2650 }) to handler FunctionObject(FunctionObject { ptr: 0x2a627f08af0 }) : ReferenceError: Error #1065: Variable  is not defined.
```

I have in my notes, that before it was - ```Variable valueOf is not defined```, but for some reason `valueOf` disappeared in the current build. You can see 2 spaces in the error, so something is definitely missing.

Game URL - https://www.gameflare.com/online-game/stunt-master/
SWF - https://data.gameflare.com/games/895/Um3E6sXaD5s29W.swf

### Expected behavior

progress to the first level

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Dinnerbone** [comment]
Sorry, I can't reproduce this. I played through the first level with no issues. Which version of Ruffle have you tested this on, and is there anything specific I need to do to reproduce the error?

**Comment by MartySVK** [comment]
I can see the error in 2023-10-22, bit looks like the game is working in 2023-10-23. Some of the latest PRs fixed the issue
