### ISSUE TITLE
Can't run https://asentientbot.github.io/converter/ (a Sractch .sb2 to .swf converter tool)

### ISSUE THREAD

**Issue by illusoryMechanist** [ruffle-rs/ruffle#13683]
### Describe the bug

Steps to reproduce:
1. Go to https://asentientbot.github.io/converter/
2. Download and unzip archive of tool
3. Attempt to launch Converter.html
4. See error (1/2).
![image](https://github.com/ruffle-rs/ruffle/assets/134031386/7ef4bc5d-4215-4210-976a-c94592e2554c)
5. Attempt to launch Converter.swf file using Ruffle's SWF player
6. Click "Open Scratch File"
7.  See error (2/2)
![image](https://github.com/ruffle-rs/ruffle/assets/134031386/2d08cb0c-1fc7-4492-9ac0-7ae8c25405bc)

### Expected behavior

Expected behavior:
For error 1, the expectation is for the flash file to run within the browser window- this seems to be a technical limitation for the moment, so may not be fixable.
For error 2, while I have not seen what is supposed to happen, I believe some form of file browser is supposed to open up so that one may select which .sb2 file is to be converted.

### Affected platform

Browser's extension

### Operating system

Pop!_OS 22.04 LTS x86_64 (Linux)

### Additional information

Debug info:

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Intel(R) HD Graphics"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: moz-extension://355e332e-82ce-489a-9885-7298e713da47/player.html

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-06
Channel: nightly
Built: 2023-10-06T00:21:25.739Z
Commit: 3a658f5dec872218032a9545ae985dcbadd5c3d4
Is extension: true

# Metadata
width: 500
height: 275
frameRate: 24
numFrames: 1
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 6561399

**Comment by Lord-McSweeney** [comment]
This is because the `FileReference` class is currently unimplemented.

**Comment by illusoryMechanist** [comment]
This now works.
