### ISSUE TITLE
Error on https://mysexgamer.com/game/orange-girls-are-easy

### ISSUE THREAD

**Issue by polo5976** [ruffle-rs/ruffle#13695]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(RangeError: Out of memory
undefined)', web/src/navigator.rs:189:18
Error stack:
```
@https://mysexgamer.com/assets/ruffle/ruffle.js:1:7035
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h99e47643887ee5a5]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h03201bc01a0ed891]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hd44f353696296fec]@[wasm code]
<?>.wasm-function[core::option::expect_none_failed::hf7dab2706f1a5551]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha37798b6e2eb822f]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h120ccdeae3267ee4]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h72d7af3bf06f1fd6]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4014bfc4ca727422]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h69dd9711782f1b19]@[wasm code]
wasm-stub@[wasm code]
T@https://mysexgamer.com/assets/ruffle/ruffle.js:1:4274
a@https://mysexgamer.com/assets/ruffle/ruffle.js:1:2799
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/d/1/0/d10a62836f53475346f21820663f26f1/d10a62836f53475346f21820663f26f1.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/d/1/0/d10a62836f53475346f21820663f26f1/d10a62836f53475346f21820663f26f1.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://mysexgamer.com/game/orange-girls-are-easy
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/d/1/0/d10a62836f53475346f21820663f26f1/d10a62836f53475346f21820663f26f1.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/285.0.570543384 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by Lord-McSweeney** [comment]
Old version of Ruffle, please ask the site owner to update to the latest version.
