### ISSUE TITLE
A Tale of Colours: Black Screen After Booting Up

### ISSUE THREAD

**Issue by MultiResearcher** [ruffle-rs/ruffle#13694]
### Describe the bug

The first seconds after the game loads up in Ruffle seem normal. The loading bar and the stencyl logo appear just fine, but once the game gets pass those it's just pure black screen.

This bug can be found in every copy of the game that I tested using the Firefox extension, the desktop app and the online demo.

### Expected behavior

Once the above mentioned loading bar and stencyl logo go away, the title of the game and a colorful "Play" button should appear.

### Affected platform

Desktop app

### Operating system

Windows 10 Pro

### Browser

Mozilla Firefox 118.0.2 (64-bit)

### Additional information

[A_Tale_of_Colours_Version_1.35.zip](https://github.com/ruffle-rs/ruffle/files/13079735/A_Tale_of_Colours_Version_1.35.zip)

**Comment by Lord-McSweeney** [comment]
`RustError("Ruffle does not support sparse arrays yet.")`

**Comment by Lord-McSweeney** [comment]
Fixed by #16051, though it's slow
