### ISSUE TITLE
Error on http://web.archive.org/web/.../https://scratch.mit.edu/projects/editor/?tip_bar=getStarted

### ISSUE THREAD

**Issue by bjames082** [ruffle-rs/ruffle#13692]
### Describe the bug

Objects reset position after click off of them during drag, only possible alternative is to click movement blocks;
Blocks disappear when you drop them into the coding area;
I can't find other issues at the time of writing

Video Evidence:
https://youtu.be/yh_jXn8lzTU

### Expected behavior

Blocks and Sprites appear in expected position after dragging.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Opera 103.0.4928.34

**Comment by Lord-McSweeney** [comment]
Closing in favor of #12613 and #13108.
