### ISSUE TITLE
Input Box not losing focus after clicking off

### ISSUE THREAD

**Issue by squash4932** [ruffle-rs/ruffle#13708]
### Describe the bug

Input Box isn't listening to clicking off event, so it stays focused.
It also interrupts gameplay by stealing focus

Reproduction:
Click on a Input Box, then try clicking off. The Input box will keep focus

### Expected behavior

Input Box supposed to lose focus after clicking off

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
What was the issue?

**Comment by squash4932** [comment]
When i type something in a input box, i am unable to remove it's focus. (Sorry for closing it yesterday)
