### ISSUE TITLE
Regressions in Steppenwolf series

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1370]
The following issues are not present in nightly builds <= 2020-10-15.

**Episode 1-1**
**Issue:** The character gets stuck in a wall.
**Steps to reproduce:** Go up (also keep pressing the shift key to run). When the screen changes, the character will become unresponsive (you can press "I", this will open the inventory and unlocks her).

**Episode 2-1**
**Issue:** The character completely disappears (and game softlocks).
**Steps to reproduce:** Go left, break the glass (space), take the steel rod, use the steel rod on the broken window; now you can either enter the building and exit it immediately or go down and press "I" on the next screen. In both cases, the character will have disappeared.

**Episode 3-3**
**Issue:** The game does not start.
**Steps to reproduce:** Click "Play the game". The screen changes to a black background and nothing else happens anymore.

----

Files (edited to bypass the loading screen):
[steppen_files.zip](https://github.com/ruffle-rs/ruffle/files/5431316/steppen_files.zip)

Web (regular files):
https://www.y8.com/games/steppenwolf_chapter_1_episode_1
https://www.y8.com/games/steppenwolf_chapter_2_episode_1
https://www.y8.com/games/steppenwolf_chapter_3_episode_3

**Comment by Herschel** [comment]
Looks like this regression was caused by #1320.

**Comment by Herschel** [comment]
For chapter1, the code that exits next scene does this:
```
   tellTarget("/")
   {
      gotoAndStop("Poupe");
      play();
   }
```
the change in #1320 causes the "play" to never run although it does in the Flash Player. Seem like tellTarget-gotos (GotoFrame action) which destroy a clip do not halt the execution (compared to, for example, `_root.gotoAndStop("Poupe");`)
