### ISSUE TITLE
Incorrect rendering of text in screen capture presentation

### ISSUE THREAD

**Issue by ArcaneNibble** [ruffle-rs/ruffle#13727]
### Describe the bug

I was trying to view an old (~2010 era) screen recording and discovered that it has incorrect text rendering on its annotations. Unfortunately, I don't know what software was used to generate this screen recording (but perhaps somebody else can recognize it from the player controls?)

The particular file I was trying to view was `Unpacking Tutorials/Themida + WinLicense 1.x - 2.x Multi Pro Edition v1.0.rar/Video Tutorials/01.Unpacking TM WL.swf` from the "Tuts 4 You - Collection 2011" torrent, which can be obtained from `magnet:?xt=urn:btih:slpgvubkpp4dyhxbaxpmogludkgmw7wi`. The actual .swf file is somewhat fiddly to obtain, but I am not sure about this project's stance on whether or not I should attach the file to this issue (i.e. I don't have explicit permission to redistribute said file, although it was originally published with the intention of being shared)

In case it is relevant, I am loading this file into ruffle by using `python3 -m http.server 8888` and then opening the corresponding .htm file in Firefox via a localhost URL.

I have attached a screenshot showing the incorrect rendering. Notice the text that should be inside the yellow note is offset down and right and with incorrect spacing. In many cases, this results in text missing entirely because it is off the edge of the screen.
<img width="1027" alt="Screen Shot 2023-10-26 at 8 35 16 PM" src="https://github.com/ruffle-rs/ruffle/assets/732574/6d3ac2e7-dfa7-43e7-84d7-f8ec6c7fd049">

### Expected behavior

Text should be rendered inside the yellow box.

### Affected platform

Browser's extension

### Operating system

macOS 12

### Browser

Firefox 118

### Additional information

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple M1"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: best
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://localhost:8888/Themida%20%2B%20WinLicense%201.x%20-%202.x%20Multi%20Pro%20Edition%20v1.0/Video%20Tutorials/01.Unpacking%20TM%20WL.htm
SWF URL: http://localhost:8888/Themida%20%2B%20WinLicense%201.x%20-%202.x%20Multi%20Pro%20Edition%20v1.0/Video%20Tutorials/01.Unpacking%20TM%20WL.swf?build=1

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
Platform: MacIntel
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-10-06
Channel: nightly
Built: 2023-10-06T00:21:25.739Z
Commit: 3a658f5dec872218032a9545ae985dcbadd5c3d4
Is extension: true

# Metadata
width: 508
height: 382
frameRate: 20
numFrames: 6487
swfVersion: 6
backgroundColor: undefined
isActionScript3: false
uncompressedLength: 2170753

**Comment by n0samu** [comment]
Please do zip and attach the SWF file, thanks!

**Comment by ArcaneNibble** [comment]
Here is the .swf file

[Archive.zip](https://github.com/ruffle-rs/ruffle/files/13192683/Archive.zip)

**Comment by ArcaneNibble** [comment]
I was once again accidentally reminded that these old recordings exist, so I decided to do a bit more digging. It would appear that these old screen recordings were all recorded with a piece of proprietary software called [Instant Demo](https://www.instant-demo.com/).

Loading the SWF into https://github.com/jindrapetrik/jpexs-decompiler *does* seem to render all of the text correctly. None of the text rendering seems to be controlled by ActionScript.

Unfortunately I don't know anything about SWF and don't know how to investigate any further.

**Comment by ArcaneNibble** [comment]
@kjarosh thank you for fixing this!

**Comment by kjarosh** [comment]
I'm glad I could help! :)
