### ISSUE TITLE
hey ruffle when the actionscript 3 ruffle coming out?

### ISSUE THREAD

**Issue by pinkyladyworld** [ruffle-rs/ruffle#13729]
I tried to play hannah montana and other favourite disney website on wayback machine but it says error all the time how do you get the actionscript 3.0 to fix in progress on ruffle emulator?

**Comment by squash4932** [comment]
Not being rude, but i have a feeling it won't be finished by the end of the year

**Comment by pinkyladyworld** [comment]
Oh I mean end of 2023 the all of actionscript adobe flash will make ruffle
emulator work all day for January 2024??

**Comment by Croworbit** [comment]
what you typed isn't coherent
Actionscript 3 already works on ruffle, but its not complete
adobe is not part of ruffle, 
there is no date it will start to work fully
you just need to wait

**Comment by pinkyladyworld** [comment]
OK that's ok let me know when it's complete I'll be very patient

**Comment by pinkyladyworld** [comment]
Hi ruffle team I already send you the old disney website you have to fix
and make it work very good like flash player. Here's the snapshot of hannah
montana 2009 official website from Disney channel that I found and it says
it's still loading for so long so i know I'll just wait for it to be all
complete. It is from kiwi browser app. And the final one I'll send you high
school musical 3 official website from disney back in 2009. Make all
wayback machine website to be all fixed and I'll just still wait.


Best
Grace
