### ISSUE TITLE
Error on http://www.gamekidgame.com/christmas_games/deep_freeze.html

### ISSUE THREAD

**Issue by Pparisa1998** [ruffle-rs/ruffle#13721]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.gamekidgame.com/christmas_games/deep_freeze.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-04
Channel: nightly
Built: 2021-08-04T00:13:29.267Z
Commit: d40cf5aee4ca7a82120bb9b7fffef72a01c6980e
Is extension: false

**Comment by Lord-McSweeney** [comment]
Closing because of old Ruffle version and generic network error.
