### ISSUE TITLE
Gaia Online Games/Worlds hung loading (Flash) 

### ISSUE THREAD

**Issue by TylerMcIntyre** [ruffle-rs/ruffle#13758]
### Describe the bug

This website is kinda gaming and interactive. A lot of features now work thanks to Ruffle, but some still are buggy or stuck on loading infinite loops after server selection. For example, if you go to this page http://www.gaiaonline.com/launch/towns2/
It goes to the server selection, then you get stuck on hang screen but it's supposed to load you into the server where people are. There are some games like this. Here are some images.
![rally1](https://github.com/ruffle-rs/ruffle/assets/37143402/4f11d57b-fa48-40df-8f99-e682946ac66e)
![rally3](https://github.com/ruffle-rs/ruffle/assets/37143402/cc6505ec-5088-4c8e-8c73-1cc47087f988)

Below is what it is supposed to look like on a normal basis when loaded in say, waterfox classic. 

![rally2](https://github.com/ruffle-rs/ruffle/assets/37143402/c65bc250-51a4-453d-8f7f-d3b8841a8dec)

### Expected behavior

The function is supposed to fully load into the server and user finds themselves in the world as found in the image provided. 

### Affected platform

Desktop app

### Operating system

Windows 11 Build 25982.1000

### Browser

Google Chrome Version 118.0.5993.117 (Official Build) (64-bit)

**Comment by Lord-McSweeney** [comment]
I've created an account for testing:
`ruffle1`
`Password1`

**Comment by Lord-McSweeney** [comment]
I've created a test account for testing this.
`ruffle1`
`Password1`

This seems to use `Socket`, which doesn't work in the browser (yet).

**Comment by TylerMcIntyre** [comment]
Thanks, please keep updated when you can.

**Comment by TylerMcIntyre** [comment]
> I've created a test account for testing this. `ruffle1` `Password1`
> 
> This seems to use `Socket`, which doesn't work in the browser (yet).

Hello, again. Just got a Private Message from the site's owner, the owner is just waiting on a reply from a ruffle dev on the website. 
![Ruffle1](https://github.com/ruffle-rs/ruffle/assets/37143402/24f25751-1d6c-4e1a-a353-a5094a54915e)

**Comment by TylerMcIntyre** [comment]
Was fixed a on update 2023-11-16!
