### ISSUE TITLE
Ruffle JavaScript API for SWF file width and height dimensions.

### ISSUE THREAD

**Issue by Renat2571** [ruffle-rs/ruffle#1376]
Hello! Is it possible to get swf file dimensions width and height by player integrated inside web? When Ruffle JavaScript API is used the SWF file is not shown with correct internal dimensions in the container.

**Comment by Herschel** [comment]
We should definitely provide a way to get the SWF dimensions (possibly all of the attributes in the SWF header could be useful).

I also wonder if we should add some sort of "auto-size" API that resizes the player itself to fill the container with correct aspect ratio; but not sure what the API for this would look like. (Should the user provide us with the dimensions of the container? Should we automatically try to detect the dimensions of the container?)

**Comment by Renat2571** [comment]
We would like if e.g. the swf file has internal dimensions 1200px by 800px the player will open automatically with the same dimensions 1200 х 800 in div container. That's Okey for us and outer player container might be resized later by CSS for example.
So API gets swf width and height from the header and resizes the player automatically with received dimensions.

**Comment by Herschel** [comment]
Added in #4084.
