### ISSUE TITLE
This is Madness 2010 - `Unknown AVM1 opcode: Unknown { opcode: 252, data: [3, 0] }`

### ISSUE THREAD

**Issue by Molisson** [ruffle-rs/ruffle#13787]
### Describe the bug

Steps to reproduce:
1. Click the play logo
2. Check the console with F12 on a Chromium browser

If done correctly, you should see the error message like this:
![image](https://github.com/ruffle-rs/ruffle/assets/81079603/7a8967d6-8cd1-44f2-8a3b-783d2927a645)

This is Madness 2010 link: https://www.newgrounds.com/portal/view/548839

### Expected behavior

It shouldn't log that, or at least it shouldn't

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Microsoft Edge

### Additional information

Error logs when playing the game or in the preloader
```
ERROR
core/src/avm1/activation.rs:2420
Unknown AVM1 opcode: Unknown { opcode: 252, data: [3, 0] }
```
One error log in the preloader I found (probably not related to this issue)
```
ERROR core/src/library.rs:216
Tried to instantiate non-registered character Asset_Login_Warning
```

**Comment by Lord-McSweeney** [comment]
Is this causing an issue with gameplay/menu display? I don't notice anything broken.

**Comment by Molisson** [comment]
> Is this causing an issue with gameplay/menu display? I don't notice anything broken.

No, but I noticed that collision doesn't reset in the game and I don't know if that opcode is the one trying to reset it from
By the way GitHub doesn't allow me to share a 10MB video so here's a compressed zip file instead
[this_is_madness_2010.zip](https://github.com/ruffle-rs/ruffle/files/13216256/this_is_madness_2010.zip)

@Lord-McSweeney

**Comment by Lord-McSweeney** [comment]
The "Unknown AVM1 opcode" errors are only being fired during loading (at the title screen), and once during gameplay. The game's title screen seems to display fine. So it's likely that that error was intentionally added by an obfuscator to prevent people from disassembling/decompiling the SWF (we've seen many other cases of this, see for example #8979 and #2280). If there's only an issue with collisions, I would suggest closing this issue and opening an issue specific to that.
