### ISSUE TITLE
Implementation mistake in ECMA-357 9.1.1.12 [[Replace]]

### ISSUE THREAD

**Issue by evilpie** [ruffle-rs/ruffle#13780]
Our [implementation of [[Replace]]](https://github.com/ruffle-rs/ruffle/blob/5bebebddbe3c39362ba520cb0c9c28b3cb7f72a3/core/src/avm2/e4x.rs#L491) doesn't seem to match the spec;
> Step 5. If Type(V) is XML and V.[[Class]] ∈ {"element", "comment", "processing-instruction", "text"}

In our code the `if` only checks the first part `Type(V) is XML` and not the second:
```rust
if let Some(xml) = value.as_object().and_then(|x| x.as_xml_object()) {
```
The next line returns early for attributes, which doesn't seem to correspond to anything in the specification.

@sleepycatcoding

**Comment by sleepycatcoding** [comment]
This is equivalent of this line in `avmplus`: `if (xml && (xml->getClass() & (kElement | kComment | kProcessingInstruction | kText | kCDATA)))`

Since E4X Node has 6 kinds and avmplus checks for five of them I opted to check for attribute and for the return, that is a mistake on my part.

**Comment by evilpie** [comment]
No, it's not. In avmplus the if condition would be false (for attributes) and thus the else branch would be taken. In our implementation we just return early for attributes (inside the if body).

**Comment by sleepycatcoding** [comment]
Yeah, sorry, just my late night brain wording stuff very confusingly :sweat_smile:
