### ISSUE TITLE
(Design suggestion) Replace the OpenJDK dependency by a Rust alternative

### ISSUE THREAD

**Issue by hardBSDk** [ruffle-rs/ruffle#13808]
Currently Ruffle use headless JRE from OpenJDK as dependency, probably to mimic the AVM behavior?

Do you have Rust candidates in mind?

**Comment by Dinnerbone** [comment]
It's needed to compile actionscript3 to SWF, which we use for our version of playerglobals. We use the official AS3 compiler to do so, but it required Java.

Maybe one day there'll be a Rust alternative to the compiler, but it seems unlikely - in any case, it doesn't exist today unfortunately.

**Comment by hardBSDk** [comment]
@Croworbit It's not written in Rust and follow the Java language rules.

**Comment by Croworbit** [comment]
do all dependencies have to be in rust for some reason?

**Comment by hardBSDk** [comment]
@Dinnerbone Thanks for the answer, the ActionScript 3 compiler dependency.

**Comment by hardBSDk** [comment]
@Croworbit The main reason for Rust dependencies is to obtain the Rust benefits, like memory-safety and efficiency.

**Comment by Croworbit** [comment]
Ruffle already has memory safety, regardless of the dependencies used to build it
Open jdk isn't going to change that

**Comment by hardBSDk** [comment]
@Croworbit I agree, I wasn't aware that it was the compiler dependency.

**Comment by Dinnerbone** [comment]
Going to close this for now as it's not really something we can action on. If you come up with an alternative please feel free to let us know :)
