### ISSUE TITLE
On self-hosted, scale seems to always be 'exact fit'

### ISSUE THREAD

**Issue by AndrewPixel** [ruffle-rs/ruffle#13814]
### Describe the bug

I'm using the self-hosted web version of Ruffle. I set a size (sometimes in pixels and sometime using %) for the player. And then I tested out all the various scale values : exact fit, no border, no scale, and show all.

### Expected behavior

That the SWF will display within the bounding area while honouring the current scale value. For example, if I set a square bounding area and the SWF is rectangular and scale is set to 'show all' then the all of the SWF will be visible within the bounding box and not be distorted.

Instead what happens is that the SWF only completely fills the bounding area (as though scale = 'exact fit').

I think I should be able to set a size, a scale and to then align it within size I set.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google chomre 118

**Comment by n0samu** [comment]
By default, Ruffle follows Flash Player's behavior, which is to respect whatever scaling setting is explicitly set by the Flash content over the setting in the HTML embed. To force the Flash content to obey the scaling setting you set, you can use Ruffle's `forceScale` option; see https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options

**Comment by AndrewPixel** [comment]
Thanks that fixed it.
