### ISSUE TITLE
error on wishology games

### ISSUE THREAD

**Issue by bugs-glitch** [ruffle-rs/ruffle#13848]
### Describe the bug

the fonts load properly, but the game crashes after loading

### Expected behavior

its supposed to load and start the game, it runs really slow on flash 10- (for some reason) 

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

opera gx

### Additional information

i like sausages

**Comment by bugs-glitch** [comment]
here's a link to the game 
http://bugs-glitch.github.io/shows/data/fairlyoddparents/fairly-oddparents-wishology3/main.swf

**Comment by Dinnerbone** [comment]
Closing as it seems to work, please feel free to report back if there's more info to reproduce the crash
