### ISSUE TITLE
chat box text display formatting error

### ISSUE THREAD

**Issue by lanzer-gaia** [ruffle-rs/ruffle#13851]
### Describe the bug

Game URL - http://www.gaiaonline.com/launch/fishing

To reproduce bug:

1. login to Gaia https://www.gaiaonline.com/ (registration required)
2. access game http://www.gaiaonline.com/launch/fishing
3. Select any game server (eg Angelic fishing)
4. Select CREATE for a new room
5. Select PLAY to start game
6. Send 10 messages, and your messages will eventually show up but formatting is bad 
(your own messages are being sent and displayed correctly on other player's chat window)

Issue:
Welcome message is not displayed unless you scroll up on the scroll bar.  It should be displayed without needing to scroll up.
![Screen Shot 2023-11-03 at 12 46 12 AM](https://github.com/ruffle-rs/ruffle/assets/24685877/933b9e6f-5313-40fc-89ff-df5d732ec8d8)

Formatting on welcome message is incorrect. In particular, line breaks are not displayed, and the last 18 or so characters on each line is covered by the next line of text.
![Screen Shot 2023-11-03 at 12 46 32 AM](https://github.com/ruffle-rs/ruffle/assets/24685877/fe49325d-fe2e-4afc-8cb1-46f0f631c0fc)

When enough messages are sent, messages will show up, but formatting is bad
![Screen Shot 2023-11-03 at 12 47 43 AM](https://github.com/ruffle-rs/ruffle/assets/24685877/b28bb2c7-fd0c-4e1c-8372-47c67fc2ffbc)

### Expected behavior

This is what expected text formatting should look like:

<img width="640" alt="Screen Shot 2023-11-03 at 12 26 38 AM" src="https://github.com/ruffle-rs/ruffle/assets/24685877/786b477e-db48-4a2a-8f3a-40da7233f234">
<img width="640" alt="Screen Shot 2023-11-03 at 12 27 19 AM" src="https://github.com/ruffle-rs/ruffle/assets/24685877/dd709cad-a520-42c7-bd18-72bd95baf487">

### Affected platform

Self-hosted version

### Operating system

macOS

### Browser

Chrome Version 118.0.5993.88 (Official Build) (x86_64)

**Comment by lanzer-gaia** [comment]
Another game also use the same chat system.  For this game, the user list on the right hand side does not display any usernames at all.
Game URL: http://www.gaiaonline.com/launch/blackjack

![Screen Shot 2023-11-03 at 1 24 33 AM](https://github.com/ruffle-rs/ruffle/assets/24685877/a248a4d1-9fa8-474d-a904-a795702bf18c)

Expected output

<img width="641" alt="Screen Shot 2023-11-03 at 1 23 03 AM" src="https://github.com/ruffle-rs/ruffle/assets/24685877/7c93d62d-607e-4c31-9a36-14f0474273ea">

**Comment by Dinnerbone** [comment]
Somewhat minimal reproduction attached.

It's just an empty text box with the following AS2 code:
```actionscript
text.html = true;
text.htmlText += "<br><br><br><b><font color=\'#0000FF\'>Reminder! Room Names and in-game chat must follow the <font color=\'#FF0000\'><u><A HREF=\'http://www.gaiaonline.com/info/tos.php\' TARGET=\'_blank\'>Terms of Service</a></u></font> and <font color=\'#FF0000\'><U><A HREF=\'http://www.gaiaonline.com/info/tos.php?info=rules\' TARGET=\'_blank\'>Rules & Guidelines</A></U></font>. <font color=\'#FF0000\'><U><A HREF=\'http://www.gaiaonline.com/forum/viewtopic.php?t=11856831\' TARGET=\'_blank\'>Click here to read more</A></U></font>.</font></b>";
```

**Comment by lanzer-gaia** [comment]
Thank you for fixing the text formatting.  However the recent fix seemed to have introduced a different problem.

Currently no line breaks are printed on screen, so the initial welcome message is one long line cutting off after 360 characters.

All incoming messages are added to the same line, causing them to not be visible as the line is already cut off.

Hope we can get the line break situation sorted then chat should be working properly.

**Comment by lanzer-gaia** [comment]
The text formatting issues have been fixed!  Thank you Dinnerbone and all who helped on the issue.
