### ISSUE TITLE
Missing gameplay mechanics in pinball game

### ISSUE THREAD

**Issue by lanzer-gaia** [ruffle-rs/ruffle#13852]
### Describe the bug

Game URL - http://www.gaiaonline.com/launch/gameshell?game=gPinball

To reproduce bug:

login to Gaia https://www.gaiaonline.com/ (registration required)
access game http://www.gaiaonline.com/launch/gameshell?game=gPinball
Select any room (eg Anime Cafe 1)
Select JOIN ROOM to start

Issues:
1. Drop targets have no collision.  The green bunny and yellow fish targets should disappear when the ball bump against them.
2. Captive area does not function.  If a ball roll into the captive area, it will hold the ball for 1 second as various bonuses are deployed.  Currently nothing happens if ball bumps into the captive area.
![Screen Shot 2023-11-03 at 1 41 38 AM](https://github.com/ruffle-rs/ruffle/assets/24685877/493c2e82-4ddf-4102-837f-434f926d2482)

No idea how to even go about debugging something like this, good luck. :)

### Expected behavior

1. Drop targets should disappear when colliding with ball
2. When ball rolls into captive area, the ball will be captured for 1 second as player receive point bonus

### Affected platform

Self-hosted version

### Operating system

macOS

### Browser

Chrome Version 118.0.5993.88 (Official Build) (x86_64)

**Comment by Lord-McSweeney** [comment]
I'm seeing this error repeated a few times on load: `ArgumentError: Error #1063: Argument count mismatch on com.gaiaonline.games.gPinball.compound_elements::Bumper/bumperInit(). Expected 0, got 1.`

**Comment by lanzer-gaia** [comment]
Oh I should had checked console log first.
I'm surprised that this still ran in the first place.  Will see about finding someone who can build our 15 year old fla file and see if fixing that bug will be the solution.  Thank you.
