### ISSUE TITLE
Text in flash only show English, other message other than English will all missing.

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#13863]
### Describe the bug

I have some flash that is not design under English, like Japanese/Chinese.
when text show on those flash, all text other than symbol/English are all missing
I have font install on system of course, if not, the windows also could not able to shown.

Screen shot of this problem, Left is flash player from windows. Right is ruffle.
![image](https://github.com/ruffle-rs/ruffle/assets/2596649/aa797780-1cf4-40d4-a905-7f558b6f2153)

Flash I tested.
[WC.swf.gz](https://github.com/ruffle-rs/ruffle/files/13256532/WC.swf.gz)

### Expected behavior

I should be able to show font that did not English based.

### Affected platform

Desktop app

### Operating system

Ubuntu 22.04

**Comment by n0samu** [comment]
This game uses system (device) fonts to display text, but the Ruffle desktop app does not yet support system font access. You can make Ruffle display the text on the web by following the instructions here to create an SWF containing the needed fonts: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-do-i-change-the-fonts-used-by-flash-on-my-website

**Comment by gritggun** [comment]
@n0samu 
I'm looking forward to an update to the system font access feature, do you have any plans to update it?

**Comment by n0samu** [comment]
Device font loading has been implemented a few days ago in #14535! But this particular SWF seems to use a font that Ruffle doesn't know how to find yet: https://zh.wikipedia.org/zh-hant/%E6%96%B0%E7%B4%B0%E6%98%8E%E9%AB%94
Hopefully we can improve this soon!
