### ISSUE TITLE
Issues with depth (z-index)

### ISSUE THREAD

**Issue by ChaseWaylon** [ruffle-rs/ruffle#13876]
### Describe the bug

Replaced the old (2021-09-06) self hosted ruffle version to a newest (2023-11-05) and some bugs surfaced in my SWFs.

All code is AS2.

First, loadClip() couldn't load the swf, because the container for it was created in a depth that new ruffle version is not supporting anymore:

createEmptyMovieClip("container", -99999);

I increased the depth to -9999 and swf is being loaded now (but now it covers all other MCs as they are by default lower than -9999).

So it looks like the problem is in the new max limit of the depth and it broke my original SWF created back in the Flash era.

### Expected behavior

Thank you for the good work!

### Affected platform

Self-hosted version

### Operating system

Win 11

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
This is probably a regression caused by #8873.

**Comment by n0samu** [comment]
@ChaseWaylon This should be fixed in the latest releases thanks to #13889. Can you check and let us know? Thanks!

**Comment by Lord-McSweeney** [comment]
Closing as probably resolved.
