### ISSUE TITLE
My SWF Compatibility Tests

### ISSUE THREAD

**Issue by SirAxolot** [ruffle-rs/ruffle#1389]
This is a review of the compatibility of some of my [favorite flash games](https://gitlab.com/SirAxolot/SWFs). I don't know how to format this properly.
Bonk.io - Hangs on the loading screen.
Fancy Pants Adventure - The game is slow (may just be my computer), otherwise fine(?)
WonderPutt - The game doesn't load.
Run 1 - "You need a newer version of Flash to play this game."
Run 2 - Everything bugs out, sprites are displaying and hiding themselves seemingly at random.
Run 3 - Doesn't even load, (possibly just my computer).
::The Game:: - Hangs on the loading screen
Replaying ::The Game:: - Really laggy/slow, like FPA. The gun control level's floor blood splats drift separately from the floor. Cutscenes didn't lag, but the audio is desynchronized from the visuals. The platform hitbox was weird, making me fall earlier than possible, but it fixed itself between the Firefly thing and the last level.

**Comment by Herschel** [comment]
Thanks for the reports! If you'd like, could you make a separate issue for these?

Fancy Pants slowness is probably an instance of #1020.

**Comment by SirAxolot** [comment]
Yes sir!
