### ISSUE TITLE
[Unimplemented] Property connected not found on flash.net.URLStream and there is no default value.	

### ISSUE THREAD

**Issue by d34d633f** [ruffle-rs/ruffle#13901]
### Describe the bug

According to the [official documentation](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/URLStream.html#connected), it seems there should be a connected attribute

### Expected behavior

The flash works fine

### Content Location

http://www.4399.com/flash/seer.htm

### Affected platform

Browser's extension

### Operating system

Windows 10

**Comment by torokati44** [comment]
Perhaps this is just a matter of the browser extension stores always lagging a couple days behind `master`.

**Comment by evilpie** [comment]
@d34d633f I implemented `connected` in #15594, could you re-test this?
