### ISSUE TITLE
Ruffle sends TCP/WebSocket messages twice

### ISSUE THREAD

**Issue by robinheidrich** [ruffle-rs/ruffle#13934]
### Describe the bug

I noticed that the latest version of Ruffle sends WebSocket messages twice. To check if this was a bug in Ruffle, I went through all versions and checked if this happened there.

It seems that the problem occurs since [Nightly 2023-10-29](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-10-29) and all subsequent versions, the previous versions do not have the problem.

I have tried both web (self-hosted) and desktop and in both cases the problem occurred.

### Expected behavior

It should only send once.

### Content Location

Unfortunately, I don't have any Flash content to share, but if necessary I can create something specifically for this.

In any case, it should be enough to send something to the server and check if it has been sent twice.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 119

**Comment by n0samu** [comment]
Please do share some specific content/project that reproduces this issue, thanks!

**Comment by Dinnerbone** [comment]
Tried https://habbolegacy.com/flash_client (in 2023-11-09, latest version at time of writing) and no duplicate messages appear in the websocket

Same for http://www.gaiaonline.com/launch/fishing (2023-11-03), no duplicate websocket traffic

**Comment by robinheidrich** [comment]
It is actually only sent once in the reproduction, so it must be related to something else. In any case, it's due to something introduced with nightly.2023.10.29. Any version before that works fine.

There is another error that also occurs since this version:

```
Error dispatching event EventObject(EventObject { type: "init", class: flash.events::Event, ptr: 0x8326480 }) to handler FunctionObject(FunctionObject { ptr: 0x5eda008 }) : ReferenceError: Error #1069: Property removeCore not found on com.pandaland.features.FeatureFacade and there is no default value.
```

I use PureMVC in my project and `removeCore` should normally only be called when the facade has already been created.

However, I have not yet been able to find out whether this has anything to do with the double sending of messages.

I will try to find the real cause. Should this issue be closed until then?

**Comment by robinheidrich** [comment]
@Dinnerbone @n0samu I just couldn't reproduce the bug outside the game, even with the same code. So I have prepared and attached a stripped down version of the game, AMF and server.

It contains only what is needed for reproduction. You need Node.js and PHP:

1. start the PHP web server with `php -S localhost:8080`.
2. start the node.js server with `node server.js`.
3. navigate to `localhost:8080`

The HTML already contains Ruffle and is ready for testing. I have only made a WebSocket server, but the bug also occurs via TCP.

If you want to have a look at it in JPEXS, you can find the relevant code in `com.pandaland.util.sockets` and `com.pandaland.mvc.model.ConnectionProxy`.

I have noticed that the `ConnectionConsts.ON_CONNECT` notification is sent twice, even though the `onConnect` function in `ConnectionProxy` that sends the notification is only called once.

I hope you can do something with it!

[Ruffle Reproduction.zip](https://github.com/ruffle-rs/ruffle/files/13316253/Ruffle.Reproduction.zip)

**Comment by Lord-McSweeney** [comment]
I just tested using the server and the SWF remains on a loading screen- six AMF calls are made (to `/amf/`), but no messages are sent over the WebSocket. All requested files return HTTP 200. No error logs are printed in either server. Node.JS server logs this:
```
Server is listening on port 5555
Client connected
Received message: 0;0;123456789;0|
Received message: 301|
Received message: 0;0;123456789;0|
Received message: 301|
Received message: 1050|
```
[Fri Nov 10 14:00:39 2023] PHP 7.4.3-4ubuntu2.19 Development Server (http://localhost:8080) started
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45694 Accepted
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45694 [200]: (null) /
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45694 Closing
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45706 Accepted
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45706 [200]: (null) /flashclient/Panfu.swf
[Fri Nov 10 14:01:02 2023] 127.0.0.1:45706 Closing
[Fri Nov 10 14:01:03 2023] 127.0.0.1:45718 Accepted
[Fri Nov 10 14:01:03 2023] 127.0.0.1:45718 [404]: (null) /favicon.ico - No such file or directory
[Fri Nov 10 14:01:03 2023] 127.0.0.1:45718 Closing
[Fri Nov 10 14:01:05 2023] 127.0.0.1:45722 Accepted
[Fri Nov 10 14:01:05 2023] 127.0.0.1:45722 [200]: (null) /flashclient/Panfu.swf
[Fri Nov 10 14:01:05 2023] 127.0.0.1:45722 Closing
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45730 Accepted
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45730 [200]: (null) /flashclient/rsl/library.swf
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45730 Closing
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45744 Accepted
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45744 [200]: (null) /flashclient/conf/config.xml
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45744 Closing
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45758 Accepted
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45758 [200]: (null) /flashclient/conf/allSnippets/DE.zip
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45758 Closing
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45764 Accepted
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45764 [200]: (null) /flashclient/conf/assets.xml
[Fri Nov 10 14:01:06 2023] 127.0.0.1:45764 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45766 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45766 [200]: (null) /flashclient/conf/poster_preloader/snippets/preloader_preview_DE.xml
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45766 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45782 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45782 [200]: (null) /flashclient/conf/poster_preloader/conf/configuration.xml
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45782 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45794 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45794 [200]: (null) /flashclient/conf/log.xml
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45794 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45806 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45806 [200]: (null) /flashclient/fonts/DE/verdana.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45806 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45820 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45820 [200]: (null) /flashclient/fonts/DE/verdanaBold.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45820 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45822 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45822 [200]: (null) /flashclient/fonts/DE/hiruko.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45822 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45830 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45830 [200]: (null) /flashclient/fonts/DE/hirukoBlack.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:45830 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41528 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41528 [200]: (null) /flashclient/assets/ui/menues/SubMenuClip.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41528 Closing
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41530 Accepted
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41530 [200]: (null) /flashclient/assets/ui/emote.swf
[Fri Nov 10 14:01:07 2023] 127.0.0.1:41530 Closing
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41538 Accepted
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41538 [200]: (null) /flashclient/assets/ui/preload_poster_collection.swf
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41538 Closing
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41550 Accepted
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41550 [200]: (null) /flashclient/assets/ui/serverSelect.swf
[Fri Nov 10 14:01:08 2023] 127.0.0.1:41550 Closing
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41558 Accepted
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41558 [200]: (null) /flashclient/assets/ui/preload_poster_collection.swf
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41558 Closing
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41568 Accepted
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41568 [200]: POST /amf/
[Fri Nov 10 14:01:09 2023] 127.0.0.1:41568 Closing
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41576 Accepted
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41576 [200]: POST /amf/
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41576 Closing
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41584 Accepted
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41584 [200]: POST /amf/
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41584 Closing
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41594 Accepted
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41594 [200]: POST /amf/
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41594 Closing
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41600 Accepted
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41600 [200]: POST /amf/
[Fri Nov 10 14:01:10 2023] 127.0.0.1:41600 Closing
[Fri Nov 10 14:03:01 2023] 127.0.0.1:39558 Accepted
[Fri Nov 10 14:03:01 2023] 127.0.0.1:39558 [200]: POST /amf/
[Fri Nov 10 14:03:01 2023] 127.0.0.1:39558 Closing
```

**Comment by robinheidrich** [comment]
That's correct, there should be no errors, it's about the messages sent twice. Both packets (0 and 301) should only be sent once each, as is the case in Flash.

If there is interest, I could make a video of what it looks like in the real game, where other packets are often sent up to 10 times or more, making the game completely unplayable and glitchy.

**Comment by robinheidrich** [comment]
I just want to clarify that this is **not** directly related to TCP/Websocket, as I originally thought. The title should probably be updated.

The game uses PureMVC and for some reason at a certain point `sendNotification` gets called twice or more. Even though the function it is used in only runs once.

Would be great if someone could take the time to look into this!

**Comment by robinheidrich** [comment]
I can confirm that #14158 fixed the bug. Many thanks for your work!
