### ISSUE TITLE
Cannot run flash games under www.4399.com

### ISSUE THREAD

**Issue by yangganger** [ruffle-rs/ruffle#13943]
### Describe the bug

Hi. The https://www.4399.com/ is a famous flash game website (https://www.similarweb.com/website/4399.com/#overview). I found the flash games under the site cannot play by using Ruffle. Most of them are using ActionScript 3. Do you have any idea to support them?

For example:
https://news.4399.com/aoyazhiguang/
https://www.4399.com/flash/18012.htm

Thank you.

### Expected behavior

The flash games can run by Ruffle.

### Content Location

https://news.4399.com/aoyazhiguang/
https://www.4399.com/flash/18012.htm

### Affected platform

Browser's extension

### Operating system

Windows10, Windows11

### Browser

Edge, Chrome

**Comment by n0samu** [comment]
Hi, the Plants vs. Zombies game (from your second link) does appear to work fine. And the first link is only broken due to CORS, which 4399 would need to fix on their end.

**Comment by mohamedmansour** [comment]
I was looking into this and debugging why it doesn't work especially plants vs zombies. While looking at the JS, the current file https://www.4399.com/jss/flashopen_cpp.js determines whether flash is available. It does that by calling:
```
flashenabled = document.getElementById("testplayer1").checkflash();
```

where `testplayer1` is the ruffle web component which loads this SWF file https://www.4399.com/jss/objtest.swf  which calls an exception cause `checkflash()` doesn't exist.

 What I did to quickly unblock is by doing this in the inspector:
```
Object.prototype.checkflash = function() {
  return true;
};
```

And it worked. So the question is how can JS call into the <object> when called via JS.

**Comment by n0samu** [comment]
Like I said, Plants vs Zombies (at the provided link) does work for me with the Ruffle extension. What problem are you having with it?

**Comment by mohamedmansour** [comment]
> Like I said, Plants vs Zombies (at the provided link) does work for me with the Ruffle extension. What problem are you having with it?

How are you not seeing this?
![image](https://github.com/ruffle-rs/ruffle/assets/68524/e6b17425-dde4-4fda-ad1e-4f213d41453f)

**Comment by n0samu** [comment]
With the Ruffle extension enabled in my browser and "Play Flash content in Ruffle" turned on, that warning goes away.

**Comment by mohamedmansour** [comment]
Interesting, I don't see that unfortunately:
![image](https://github.com/ruffle-rs/ruffle/assets/68524/7c33540a-1fcf-4128-883d-03d52fa7a46d)

To make it work, I have to add to the page and then it works:
```
Object.prototype.checkflash = function() {
  return true;
};
```
Once the Ruffle replaces the <embed>in the webpage with <ruffle-embed>, and the JavaScript is calling `checkflash()` on that `<ruffle-embed>` how does Ruffle.rs translate that?

**Comment by mohamedmansour** [comment]
I just updated to `0.1.0 nightly 2023-12-02` and it now works.
