### ISSUE TITLE
Detective Grimore - Regression

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14004]
### Describe the bug

This game worked fine once but it's stuck on the police officer in the "intro". Game is stuck when you click next.

### Expected behavior

run on

### Content Location

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/detectivegrimoire.swf

### Affected platform

Desktop app

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/2583#issuecomment-1501235659. Unless you can point to a specific Ruffle version where this worked, I don't believe this is a regression.
