### ISSUE TITLE
Big and Small House: Model did not display.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#14035]
### Describe the bug

Latest nightly.

https://github.com/ruffle-rs/ruffle/assets/75534590/c2236b77-4b63-4475-ac09-6acdd7584003

### Expected behavior

Nightly 11-11

https://github.com/ruffle-rs/ruffle/assets/75534590/069c2eb0-8ec6-453f-94f7-0646f27bfcb4

### Content Location

Multi-Assets, Can be found on BlueMaxima's Flashpoint.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
https://github.com/ruffle-rs/ruffle/compare/nightly-2023-11-11...nightly-2023-11-12
