### ISSUE TITLE
web: Music unexpectedly stops in some games (regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1405]
This issue doesn't happen in nightly builds <= 2020-10-26. Desktop backend doesn't seem to be affected.
It also seems like the issue only happens when the music is the first sound being played in the game and another sound (eg. a sound effect) is then played.

Streets of Fire (the music stops after you set a house on fire - if you keep playing, the music will play again and won't stop this time):
https://www.newgrounds.com/portal/view/225944

Luigi's Revenge 1.0 (the music stops on title screen):
https://www.newgrounds.com/portal/view/209380

Hydrophobia (the music stops after the frog swallows a fly):
http://www.ferryhalim.com/orisinal/g2/frog.htm

**Comment by Herschel** [comment]
Hopefully got it this time :-)
