### ISSUE TITLE
Regression: Wake Up The Box 3 is stuck on loading screen

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#14067]
### Describe the bug

The game is currently stuck on the loading screen, last working build is ruffle-nightly-2023_11_10

### Expected behavior

start the game

### Content Location

Game URL - https://www.gameflare.com/online-game/wake-up-the-box-3/
SWF URL - https://data.gameflare.com/games/2231/8IcAVEucA3EXcc.swf

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by MartySVK** [comment]
looks like the problem is @Aaron1011 's PR https://github.com/ruffle-rs/ruffle/pull/12386

**Comment by Lord-McSweeney** [comment]
This is SWFv10

**Comment by Aaron1011** [comment]
This was caused by my PR - the avm2 button frame is still different with SWF > 9.

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/14073
