### ISSUE TITLE
Massive lag spike when opening SpongeBob: Plankton's Pernicious Plot

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1406]
Link: http://static.nickjr.com/games/data/spongebob/sb_plankton/spongebob.swf

The game will freeze for 10-20 seconds upon opening. It used to do this whenever you chose an option on the title screen instead of right at the beginning, so I don't know what's up with that.

(tested in the Ruffle desktop app)

**Comment by Herschel** [comment]
@WumboSpasm Is this still an issue?

**Comment by Lord-McSweeney** [comment]
This is still an issue with the latest version of Ruffle, at least on web.

**Comment by Toad06** [comment]
Alternative link: https://cdn.flasharch.com/uploads/archived/2021/10/18/891419655bb798ad389adbe358268474/main.swf

Lowering the ActionScript execution duration to 1 prevents the lag from happening (obviously) and the game still works after that (surprisingly).

**Comment by WumboSpasm** [comment]
The freeze no longer occurs even with the ActionScript execution duration set to a high value, so it's safe to assume this has been fixed. Closing.
