### ISSUE TITLE
Ruffle Error on https://freeinvaders.org/

### ISSUE THREAD

**Issue by SB-P** [ruffle-rs/ruffle#14070]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(timeout: https://turbo.freevideogames.org/includes/js/flash-emulator/core.ruffle.5e850f90e6e2fab0bb54.js)
Error stack:
```
vi.f.j@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:36903
vi.e/<@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35299
vi.e@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35276
o@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2595
o/i</<@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2895
o/i<@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2631
o@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:2918
E@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:14261
createPlayer@https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:34640
@https://freeinvaders.org/:75:26

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeinvaders.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Croworbit** [comment]
This website uses a version of ruffle from 2020, thats 4 years out of date!

they broke CORS, and they need to update their site and they need to update Ruffle. let them know!

their email is `hello@freevideogames.org `
