### ISSUE TITLE
Constructor called at the wrong time

### ISSUE THREAD

**Issue by rogual** [ruffle-rs/ruffle#14094]
### Describe the bug

- Define a Sprite subclass with a timeline; let's call it `Scene`.
- Give `Scene`'s timeline a single frame that instantiates a child of class `A` and a child of class `B`.
- `A` extends `MovieClip` and its constructor calls `gotoAndStop(1)`.
- `B` extends `Sprite` and its constructor does nothing.
- Now create an instance of `Scene`. You don't even need to add it to the display list to trigger the bug.

Observed behaviour:

In Ruffle, with this setup, A's constructor will be called, and then before it returns, inside the call to `gotoAndStop`, B's constructor will be called.

### Expected behavior

A's constructor should be called, and after it returns, B's constructor should be called. This is what Flash Player does.

### Content Location

Here's a commit that adds a failing test SWF that triggers the bug: https://github.com/rogual/ruffle/commit/7ab4edc972d14f479c878aad1916c5cdf78c6dfd

This breaks [this game](https://foon.uk/farcade/jig12/), because objects in the scene refer to their sibling objects from their constructors via `parent.someOtherObject`, but if the constructors don't run in the right order, the expected objects are sometimes not there yet. 

### Affected platform

Desktop app

### Operating system

MacOS 13.5 (22G74)

### Additional information

This seems to be related to Ruffle's handling of "orphan objects".

When `Scene` is constructed, it's an orphan. `gotoAndStop` triggers Ruffle to iterate all orphans and do initialization-type things like running child constructors. But we're already constructing `Scene`, working our way through its children, so we shouldn't let `B`'s constructor jump the gun just because we called `gotoAndStop`.

**Comment by Aaron1011** [comment]
Thank you for the very detailed issue report! I previously added logic that was supposed to handle this kind of case, but it looks like there's a bug in it. I'll take a look at this later today.

**Comment by Aaron1011** [comment]
You're right - we should be setting that flag in `native_instance_init`. I've opened https://github.com/ruffle-rs/ruffle/pull/14121, which fixes your test. Thanks again!
