### ISSUE TITLE
Regression: Shopaholic Hawaii - can't start the first level

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#14101]
### Describe the bug

When I try to start the first level with OK button, I get this error:

```Error dispatching event EventObject(EventObject { type: "SHOPSTREET", class: zlong.Hawaii_Events::Hawaii_event, ptr: 0xb4a9860 }) to handler FunctionObject(FunctionObject { ptr: 0xac8ae88 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: removeEvents)	at zlong.hawaii_view::Hawaii_creditCard/removeEvent()	at zlong.hawaii_view::Hawaii_creditCard/destroy()	at zlong.manager::Hawaii_UIManager/clearScreen()	at zlong.manager::Hawaii_UIManager/toStreet()	at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()	at zlong.hawaii_view::Hawaii_DailyChallenge/toChooseChallenge()```

Last working build is 2023-11-12
SWF version 14

### Expected behavior

start the level

### Content Location

GAME URL - https://www.gameflare.com/online-game/shopaholic-hawaii/
SWF URL - https://data.gameflare.com/games/6633/7NoWsdgnMZbMlv.swf

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by MartySVK** [comment]
looks like the problem is @Aaron1011 's PR https://github.com/ruffle-rs/ruffle/pull/13966

**Comment by Lord-McSweeney** [comment]
From Aaron, in #14007:
> I think we need to implement the 'default namespace' logic for non-qname Multinames, which in this case will end up appending the public namespace to the incoming Multiname: https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/Toplevel.cpp#L287

**Comment by evilpie** [comment]
Fixed by #14801.
