### ISSUE TITLE
Top Level class takes precedence over local package class

### ISSUE THREAD

**Issue by JordanPlayz158** [ruffle-rs/ruffle#14127]
### Describe the bug

If you have a class, `JSON` in the same package as another class, `Main`. Then if you reference `JSON.decode()` and it is a function in your local `JSON` class, the code will fail as Ruffle seems to use the Top Level class over the Local Package class (either that or it doesn't know which class to use).

### Expected behavior

Ruffle should choose the local package SWF if one is present and if not, **then** use the top level class.

### Content Location

There is a test.swf provided below but it does not seem suitable for testing (see comments below) and unfortunately while I will upload the SWF I see the issue in, it needs a server running on port `3001` so it is not optimal for testing either.
[game-v128.v5690-changed-urls.zip](https://github.com/ruffle-rs/ruffle/files/13453898/game-v128.v5690-changed-urls.zip)

### Affected platform

Self-hosted version

### Operating system

Nobara (Fedora) Linux 38

### Browser

Ungoogled Chromium 119.0.6045.123

### Additional information

I have made a github repo of the test swf https://github.com/JordanPlayz158/RuffleTopLevelClassConflict there is a release with the pre-compiled SWF but as stated in the commit message, the test code **should** work but upon inspection of the SWF, MXML does not seem to include the `JSON` class in the SWF output but I know it is possible because Backyard Monsters (a real world example SWF, uploaded above) has a `JSON` class in it's default package so there may be a way to force it to include a class that I am not aware of.

**Comment by Lord-McSweeney** [comment]
This is probably just namespace versioning not being implemented for `JSON` (added in SWFv13, but given SWF is v11); I remember that we confirmed that the first defined class takes precedence.

**Comment by JordanPlayz158** [comment]
Got a Testing SWF (https://github.com/JordanPlayz158/RuffleTopLevelClassConflict/releases/download/1.0-TRACE-ONLY/TopLevelClassConflict-TRACE-ONLY.swf) that appears to work fine on Flash and not on Ruffle although Ruffle fails with the `NonTopLevelClass#decode` on Ruffle. So now I am not sure if it is due to the function name being `decode` or if it is due to Ruffle always populating the JSON top level class regardless of playerglobal/swf version
