### ISSUE TITLE
Ruffle on AskaboutIreland.ie doesn't work, but it does work on the Internet Archive saved version of the site.

### ISSUE THREAD

**Issue by padraic7a** [ruffle-rs/ruffle#14133]
### Describe the bug

My organisation has a legacy website https://askaboutireland.ie which contains a number of Flash games and assets. Hosting Ruffle on the site would be difficult. However we would like to be able to tell users how to access the games. 

I have installed the Ruffle extension on Firefox and Chrome.  The flash game [here](https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/) doesn't fully load and isn't playable. However the [cached page on the Internet Archive](https://web.archive.org/web/20171120013621/https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/) works fine.

What can I do to get things working?

### Expected behavior

I would expect the flash game [here](https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/) to load and be playable. It isn't.

### Content Location

https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/

### Affected platform

Browser's extension

### Operating system

Windows 10 Enterprise

### Browser

Moilla Firefox 120, Chrome 119.0.6045.160

### Additional information

I have installed the Ruffle extension on Firefox and Chrome.  The flash game [here](https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/) doesn't fully load and isn't playable. However the [cached page on the Internet Archive](https://web.archive.org/web/20171120013621/https://www.askaboutireland.ie/learning-zone/secondary-students/games-3d-tours/the-irish-writers-game/) works fine.

**Comment by Lord-McSweeney** [comment]
You're using Mootools on the site, which conflicts with Ruffle.
