### ISSUE TITLE
Mouse position reported to ActionScript should sometimes be rounded

### ISSUE THREAD

**Issue by rogual** [ruffle-rs/ruffle#14144]
### Describe the bug

Ruffle doesn't ever round mouse positions to the nearest integer before reporting them to ActionScript.

### Expected behavior

Flash Player usually reports mouse positions to ActionScript (via `_xmouse`, `mouseX`, etc.) as integers.

In the case of scaled or rotated clips, though, fractional positions are reported, although they still don't seem to be affected by any fractional positioning of the clip in question.

That is, a clip scaled to 200% will report mouse positions 1, 1.5, 2, 2.5 etc. as the mouse moves across it, even if the clip's own position ends in, say, .1.
[tracemousepos.swf.zip](https://github.com/ruffle-rs/ruffle/files/13462363/tracemousepos.swf.zip)

### Content Location

SWF attached.

### Affected platform

Desktop app

### Operating system

MacOS 13.5 (22G74)

**Comment by Lord-McSweeney** [comment]
Does this also happen in AVM2 (AS3)?

**Comment by n0samu** [comment]
Possibly related to #7660

**Comment by rogual** [comment]
Fixed with https://github.com/ruffle-rs/ruffle/pull/14243.
