### ISSUE TITLE
Insane Orb - Initial Background Gradient Incorrect

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1415]
![image](https://user-images.githubusercontent.com/35991016/97411347-40cc2500-1954-11eb-95af-35aaa6ef2da5.png)

The right side is ruffle.rs, the left is the Adobe Flash projector, showing the background gradient is incorrect.

**Comment by Lord-McSweeney** [comment]
The background is now correct on the first gamemode, but not on the second.

**Comment by n0samu** [comment]
I just played through the game for a bit and the first and second backgrounds both seem to match Flash Player. So I think this bug is fixed, but please leave a comment if anything is still incorrect and I can reopen the issue.
