### ISSUE TITLE
Sinjid: Shadow of the Warrior - Scrollbars Inoperative

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1416]
In Sinjid SOTW, on the first screen and other screens after, there are long scroll boxes with a lot of text to read. In Flash it appears like the scroll bar on a browser's right edge; two up and down arrows, and a box between them to click-and-drag to any point in the text. In Ruffle, the box disappears and the up and down arrows don't do anything when clicked.

**Comment by Poopooracoocoo** [comment]
looks to be fixed! :)
