### ISSUE TITLE
Amorphous+ - Loading Screen Incorrect

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1417]
![image](https://user-images.githubusercontent.com/35991016/97412313-80474100-1955-11eb-9adc-353c4d50ffd7.png)

It should be obvious which one is incorrect at the moment...

**Comment by NotWearingPants** [comment]
Also the score popups are staying on screen (and also the one on the bottom right):
![image](https://user-images.githubusercontent.com/26556598/98298511-cbe59480-1fbe-11eb-996a-48b756c1d24e.png)

**Comment by adrian17** [comment]
It appears to be working now, so I'm closing this issue.
