### ISSUE TITLE
Website still lagging when playing games with Ruffle extenmsion and enabling hardware acceleration in google chrome settings.

### ISSUE THREAD

**Issue by GamerEXER** [ruffle-rs/ruffle#14197]
### Describe the bug

I keep getting laggy games when trying to boost Ruffle even though I have followed the faqs channel on Discord adn they told me to open a report issue here.
This is thr website link I was trying to play in https://www.arcadeprehacks.com/game/25348/zombotron-2-time-machine.html 

### Expected behavior

I was expecting it to work, but instead it was still lagging.

### Content Location

Ruffle is the problem or maybe it's my computer.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome

**Comment by n0samu** [comment]
Ruffle's performance is not always the best, but we are working on improving it. Closing in favor of #13027
