### ISSUE TITLE
Demo saves were erased

### ISSUE THREAD

**Issue by serkonda7** [ruffle-rs/ruffle#14193]
### Describe the bug

Lately I used the demo (https://ruffle.rs/demo/) to upload and play SWFs.

The progress has always been saved properly but was reset from 2023-11-26 to 2023-11-27.

For me it's not important to get my savegames back. I'd just like to know that this won't happen again or have some way to export and restore the saves from files.

### Expected behavior

Progress should not be reset

### Content Location

Mainly this swf:
[strike-force-heroes-1.zip](https://github.com/ruffle-rs/ruffle/files/13473265/strike-force-heroes-1.zip)

### Affected platform

Desktop app

### Operating system

Arch Linux

**Comment by n0samu** [comment]
Hi, you can use Ruffle's save manager to back up and restore your save files. Just right-click => Open Save Manager.

**Comment by serkonda7** [comment]
Thanks. Did not know about this feature
