### ISSUE TITLE
The Slaying of Sandy Hook Elementary - Children Don't Die When Shot

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1420]
In The Slaying of Sandy Hook Elementary, most of the time, when a child is in the path of a bullet that's been shot, they're shot, whether they're running, standing, hiding or sitting. In the Ruffle web demo though, bullets seem to go right through them most of the time. Children sitting in seats tend to be completely invincible.

**Comment by Herschel** [comment]
Still occurring as of 10/2021.

**Comment by Lord-McSweeney** [comment]
Seems to be fixed.
