### ISSUE TITLE
Error on https://zonzaemgame.com/bbs/board.php

### ISSUE THREAD

**Issue by jamminTv** [ruffle-rs/ruffle#14224]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://zonzaemgame.com/bbs/board.php?bo_table=kidsgame&wr_id=552

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-23
Channel: nightly
Built: 2023-11-23T00:14:23.315Z
Commit: d1784dc7c89a1f30d54907b4e3008377bb1110de
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing as likely transient network error unrelated to Ruffle.
