### ISSUE TITLE
Pressing 'Watch Video' does nothing

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#14239]
### Describe the bug

When I press 'Watch Video' nothing happens.

### Expected behavior

I expected a video to play.

### Content Location

https://web.archive.org/web/20180601190834/http://pbskids.org/wildkratts/games/frogfish-feast
or just the affected file: https://web.archive.org/web/20150819112010/http://www-tc.pbskids.org/wildkratts/games/frogfish-feast/FrogFish.swf

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 119.0.2151.93

**Comment by n0samu** [comment]
This doesn't seem to be a Ruffle bug. The button calls the `showVideo()` function, which calls a JavaScript function via ExternalInterface: `ExternalInterface.call("showVideo")`. That all works fine, but an error occurs on the JavaScript side:
```
Uncaught ReferenceError: PKG is not defined
    showVideo https://web.archive.org/web/20150402000816js_/http://pbskids.org/wildkratts/js/main.js:154
```
I'm not sure why the function doesn't work on Wayback. But if it did, it would open this page in an overlay frame:
https://web.archive.org/web/20160725200326/http://pbskids.org/wildkratts/videoplayer/?keyword=hummingbirdgame
Unfortunately the video seems not to have been saved.
