### ISSUE TITLE
Intro endlessly loops in Lunar Mouse

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1424]
Both desktop and web backends are affected. 
No error and no warning in the browser's console.

Game: [lmh.zip](https://github.com/ruffle-rs/ruffle/files/5455035/lmh.zip)

**Comment by BestPresident** [comment]
I found a similar bug in this game.

[99catchthewitch.zip](https://github.com/ruffle-rs/ruffle/files/5456812/99catchthewitch.zip)

**Comment by Herschel** [comment]
The preloader relies on the `construct` clip event even though this was only added in SWFv7 and this is a v6 SWF. The new players allow the event to run regardless.

**Comment by Herschel** [comment]
Looks like it relies on hitTesting + masks (same as #1211).
