### ISSUE TITLE
.htmlText property on flash.text.TextField failing to interpret HTML tags.

### ISSUE THREAD

**Issue by React-1** [ruffle-rs/ruffle#14249]
### Describe the bug

Given a simple TextField, if we implement something along the lines of:

```actionscript
TextField text = new TextField();
text.htmlText = "Join the <b>Backyard Monsters Refitted Discord</b> community. "
```

The output on Ruffle, is the entire text in bold. A screenshot is attached showing the comparison on Flash Player 32:

![image](https://github.com/ruffle-rs/ruffle/assets/134884194/8de62a57-80be-4652-a7d4-9c04f6aca765)

### Expected behavior

The TextField to correctly interpret HTML tag elements within a given body of text.

### Content Location

SWF:
[testswf.zip](https://github.com/ruffle-rs/ruffle/files/13509403/testswf.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by evilpie** [comment]
The SWF just says "Logging in" and seem to have trouble finding a specific domain.

**Comment by React-1** [comment]
> The SWF just says "Logging in" and seem to have trouble finding a specific domain.

Yeah, unfortunately there's no server for it just yet, working on emulating it.

**Comment by evilpie** [comment]
@React-1 could you test this again? It should hopefully be much better now.

**Comment by React1-X** [comment]
> @React-1 could you test this again? It should hopefully be much better now.

Yep looks good now, thanks! :)
