### ISSUE TITLE
Blank Scene for Away3D 4.1.6 Water example

### ISSUE THREAD

**Issue by FlashBacks1998** [ruffle-rs/ruffle#14256]
### Describe the bug

The entire scene is blank with the exception of the debug stats and signature swf. There isnt a warning screen or anything showing of invalid avm2 either.

In the code, it seems as if all of the code executes fine, but any and all functions after _initFluid_ and any code after _FluidDisturb_ fails to execute. 
```
		/**
		 * Global initialise function
		 */
		private function init():void
		{
			initEngine();
			initLights();
			initMaterials();
			initObjects();
			initFluid();
			initGUI();
			initListeners();
		}
```		
```		
		 /**
		 * Initialise the fluid
		 */
		private function initFluid():void
		{		
			// Fluid.
			var dt:Number = 1 / stage.frameRate;
			var viscosity:Number = 0.3;
			var waveVelocity:Number = 0.99; // < 1 or the sim will collapse.
			fluid = new ShallowFluid(gridDimension, gridDimension, gridSpacing, dt, waveVelocity, viscosity);
			
			// Disturbance util.
			fluidDisturb = new FluidDisturb(fluid);
			
		}
```

### Expected behavior

The scene should be a example demo showing the Shallow Water Equation. Its fully implemented with images in the water, ripple effects, and shaders.

### Content Location

https://www.newgrounds.com/portal/view/908537
http://www.mediafire.com/file/wc15vah7qnf6ild/Advanced_ShallowWaterDemo.zip
https://www.mediafire.com/file/jr3ami8rqt7v229/Advanced_ShallowWaterDemo.swf/file

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Brave

**Comment by n0samu** [comment]
Currently this gets stuck because it needs setters for flash.display.ShaderInput width/height. But with those added, we can see that it needs a lot more:
`WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.display.ShaderJob constructor`
`WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.display.ShaderJob.start() async execution and non-BitmapData inputs`
```
panicked at core\src\avm2\globals\flash\display\shader_job.rs:110:61: ShaderInput.input is not a BitmapData (FIXE - support other types)
        at flash.display::ShaderJob/flash::display::ShaderJob::start()
        at shallowwater::ShallowFluid/evaluate()
        at Advanced_ShallowWaterDemo/onEnterFrame()
```

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/14302

**Comment by evilpie** [comment]
Seems to work now.
