### ISSUE TITLE
Crash on Load3DS.swf

### ISSUE THREAD

**Issue by GiantSnail** [ruffle-rs/ruffle#14250]
### Describe what you were doing

example project of away3d-openfl

### What does the crash message say?

panicked at render\wgpu\src\context3d\current_pipeline.rs:537:22:
not implemented

### Ruffle Version

0.1.0-nightly (78c34c1be9b8e0089058f1b14ced2f5f9f34107b 2023-11-30)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Enterprise) [64-bit]

### Additional information

Filename: Load3DS.swf

### AVM2 Callstack
```
	at flash.display3D::Context3D/flash::display3D::Context3D::setSamplerStateAt()
	at away3d.materials.methods::BasicDiffuseMethod/activate()
	at away3d.materials.passes::CompiledPass/activate()
	at away3d.materials.passes::SuperShaderPass/activate()
	at away3d.materials::MaterialBase/activatePass()
	at away3d.core.render::DefaultRenderer/drawRenderables()
	at away3d.core.render::DefaultRenderer/draw()
	at away3d.core.render::RendererBase/executeRender()
	at away3d.core.render::DefaultRenderer/executeRender()
	at away3d.core.render::RendererBase/render()
	at away3d.containers::View3D/render()
	at Main/onEnterFrame()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "NVIDIA GeForce RTX 2060"
Adapter Device Type: DiscreteGpu
Adapter Driver Name: "NVIDIA"
Adapter Driver Info: "531.79"
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 32768, max_texture_dimension_2d: 32768, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by Lord-McSweeney** [comment]
This is triggering the `unimplemented!` in this function:
```
    pub(crate) fn update_sampler_state_at(
        &mut self,
        sampler: usize,
        wrap: ruffle_render::backend::Context3DWrapMode,
        filter: ruffle_render::backend::Context3DTextureFilter,
    ) {
        let sampler_override = SamplerOverride {
            wrapping: match wrap {
                Context3DWrapMode::Clamp => Wrapping::Clamp,
                Context3DWrapMode::Repeat => Wrapping::Repeat,
                Context3DWrapMode::ClampURepeatV => Wrapping::ClampURepeatV,
                Context3DWrapMode::RepeatUClampV => Wrapping::RepeatUClampV,
            },
            filter: match filter {
                Context3DTextureFilter::Linear => Filter::Linear,
                Context3DTextureFilter::Nearest => Filter::Nearest,
                _ => unimplemented!(),
            },
            // FIXME - implement this
            mipmap: naga_agal::Mipmap::Disable,
        };
        if self.sampler_override[sampler] != Some(sampler_override) {
            self.dirty.set(true);
            self.sampler_override[sampler] = Some(sampler_override);
        }
    }
```

**Comment by Lord-McSweeney** [comment]
Can you please ZIP and upload the SWF that you were trying to run?

**Comment by torokati44** [comment]
I heard this is your area of expertise, @Aaron1011 ... :)

**Comment by GiantSnail** [comment]
> Can you please ZIP and upload the SWF that you were trying to run?

[Load3DS.zip](https://github.com/ruffle-rs/ruffle/files/13509913/Load3DS.zip)
