### ISSUE TITLE
Poor desktop rendering performance due to excessive calls to ResolveSubresource

### ISSUE THREAD

**Issue by ZingBallyhoo** [ruffle-rs/ruffle#1427]
Movie url: https://binweevilscheatsbincheats.weebly.com/uploads/1/0/7/4/10749225/catsanddogs_comp1.swf

This issue is purely based off my observations of a frame capture because I have absolutely no idea how ruffle/wgpu renders internally. 

For me rendering this movie with any of the desktop rendering backends (vulkan least of all, unless I enlarge the window) results in quite poor performance. D3D11 is the only render backend that doesn't crash both RenderDoc and Nsight for this movie, which is where I'm getting ResolveSubresource from. Presumably something equivalent is happening on the other backends too but I have no way of checking right now.

![image](https://user-images.githubusercontent.com/13888932/97508411-73d3e000-1977-11eb-8e24-4e90368b4562.png)
See above, after almost every call to Draw* there is a call to ResolveSubresource from current rendertarget into the swapchain's backbuffer. As I said I don't know how ruffle renders, but at least in this capture there are no reads from the backbuffer which means in 1100/1101 calls to ResolveSubresource in this capture the copied data is simply overwritten after the next draw when it is copied again.

The folowing images show the render output, FPS and CPU/GPU usage of the Nsight capture exported to a standalone application
**Stock render**
![image](https://user-images.githubusercontent.com/13888932/97504205-52bac180-196e-11eb-9585-f1f85ba6d795.png)
![image](https://user-images.githubusercontent.com/13888932/97504216-59493900-196e-11eb-8fd9-52f6a79c9a43.png)

**All but last call to ResolveSubresource removed**
![image](https://user-images.githubusercontent.com/13888932/97504238-66662800-196e-11eb-88cb-eefd250c7556.png)
![image](https://user-images.githubusercontent.com/13888932/97504242-69611880-196e-11eb-860e-342c2981edc5.png)

**Comment by Herschel** [comment]
Thanks for the report!
