### ISSUE TITLE
Crystal Story 2 unable to finish loading 

### ISSUE THREAD

**Issue by Crystalcollector** [ruffle-rs/ruffle#14298]
### Describe the bug

Apon opening the game half of the screen is pure white with a loading bar at the bottom then never finishes completely.

### Expected behavior

The white part of the screen is supposed to be a snowboarding mini game the player can do while the main game loads. Once the green bar loads a button should appear to allow the player to proceed to the main game.

### Content Location

[crystal-story-ii-15779cd85.zip](https://github.com/ruffle-rs/ruffle/files/13540051/crystal-story-ii-15779cd85.zip)

### Affected platform

Browser's extension

### Operating system

Android 13

**Comment by n0samu** [comment]
This is a sitelock. You can use the desktop app's `--spoof-url` option or play the game on Armor Games: https://armorgames.com/play/15779/crystal-story-ii?ruffle
