### ISSUE TITLE
(AS3 Game) Error dispatching event EventObject

### ISSUE THREAD

**Issue by Lujek69** [ruffle-rs/ruffle#14294]
### Describe the bug

There is an EventObject error in the browser console when trying to enable the game

Full error text:
>ERROR core/src/avm2/events.rs:424 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x3005f28 }) to handler FunctionObject(FunctionObject { ptr: 0x2095aa0 }) : ReferenceError: Error #1056: Cannot create property needsSoftKeyboard on flash.text.TextField.
![screenshotbug](https://github.com/ruffle-rs/ruffle/assets/54140042/5a51e904-7fc4-460e-9a27-edfde4e28212)

### Expected behavior

After loading successfully, the game displays the character creation screen as in the screenshot
![runned](https://github.com/ruffle-rs/ruffle/assets/54140042/403512f2-28bd-43b6-a2cd-e3a0e7748f7c)

### Content Location

https://crazyisland.5v.pl/play/

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Mozilla Firefox 120.0.1

**Comment by Aaron1011** [comment]
This seems to be working now
