### ISSUE TITLE
Crash on brainyplex.swf

### ISSUE THREAD

**Issue by UncleRus** [ruffle-rs/ruffle#14328]
### Describe what you were doing

Run the game

### What does the crash message say?

panicked at render/wgpu/src/context3d/current_pipeline.rs:451:21:
Total size of bound vertex attributes 36 exceeds data_bytes_per_vertex 32

### Ruffle Version

0.1.0-nightly (40b92e69f7d44932874f7caab7f95ad20af5b3f4 2023-12-05)

### Affected platform

Desktop app

### Operating system

Debian n/a (trixie) [64-bit]

### Additional information

Filename: brainyplex.swf

### AVM2 Callstack
```
	at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
	at starling.extensions::ImageBatch/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.display::Sprite/render()
	at starling.display::DisplayObjectContainer/render()
	at starling.core::Starling/render()
	at starling.core::Starling/nextFrame()
	at starling.core::Starling/onEnterFrame()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "NVIDIA GeForce RTX 3070 Ti"
Adapter Device Type: DiscreteGpu
Adapter Driver Name: "NVIDIA"
Adapter Driver Info: "525.147.05"
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH_CLIP_CONTROL | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | DEPTH32FLOAT_STENCIL8 | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX)
Current limits: Limits { max_texture_dimension_1d: 32768, max_texture_dimension_2d: 32768, max_texture_dimension_3d: 16384, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 64, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: low
Surface samples: 1
Surface size: Extent3d { width: 800, height: 600, depth_or_array_layers: 1 }

**Comment by UncleRus** [comment]
[brainyplex.zip](https://github.com/ruffle-rs/ruffle/files/13589642/brainyplex.zip)

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/14345
