### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Hfjfhfjgjgkgjgjgjvj** [ruffle-rs/ruffle#14332]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-yDH7kfI6.js:2:54524
wasm-stub@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h628850da41a271a5]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hc20eadded6bfe687]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h7a368385936888dc]@[wasm code]
<?>.wasm-function[core::ops::function::Fn::call::h71a9c0a4e0d490f3]@[wasm code]
<?>.wasm-function[wgpu::backend::direct::ErrorSinkRaw::handle_error::ha092a543a3700a3d]@[wasm code]
<?>.wasm-function[<T as wgpu::context::DynContext>::device_create_buffer::he79a3f447ef1b6da]@[wasm code]
<?>.wasm-function[<wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hd97b1f6a94925920]@[wasm code]
<?>.wasm-function[ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::h21a0ec7aede4186f]@[wasm code]
<?>.wasm-function[<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::h950a93890e620eb1]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::ha41577d24362b550]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::haedb831de8113829]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::tick::h79392301d2470d8b]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h3f7f9ca2b718d588]@[wasm code]
<?>.wasm-function[wasm_bindgen::convert::closures::invoke1_mut::h91e0670a8accff4d]@[wasm code]
wasm-stub@[wasm code]
J@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-yDH7kfI6.js:2:355
c@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-yDH7kfI6.js:2:115
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Apple GPU"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/logo-anim.swf

# Browser Info
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Platform: MacIntel
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-06
Channel: nightly
Built: 2023-12-06T00:14:39.182Z
Commit: 40b92e69f7d44932874f7caab7f95ad20af5b3f4
Is extension: false

# Metadata
width: 720
height: 540
frameRate: 60
numFrames: 3
swfVersion: 28
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 22132440

**Comment by n0samu** [comment]
Generic error with no attached file, closing
