### ISSUE TITLE
Knightmare Tower does not go past the loading screen

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#14340]
### Describe the bug

N/A as it does not go past the loading screen

![loading screen](https://github.com/ruffle-rs/ruffle/assets/64484245/468fc235-968e-420b-a19e-5a376b0a9b74)

### Expected behavior

to be able to test the game

### Content Location

https://www.maxgames.com/play/knightmare-tower.html

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 118.0.5993.164 (Official Build) (64-bit)

### Additional information

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html#https://farm.maxgames.com/knightmaretowerMTYyOQ==.swf
SWF URL: https://farm.maxgames.com/knightmaretowerMTYyOQ==.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-07
Channel: nightly
Built: 2023-12-07T00:15:04.300Z
Commit: 41ddb316a2b0a91c0d32e8f54eb0f020be42831f
Is extension: true

# Metadata
width: 720
height: 480
frameRate: 45
numFrames: 142
swfVersion: 10
backgroundColor: #222B37
isActionScript3: true
uncompressedLength: 6948295

**Comment by Aaron1011** [comment]
This appears to be a preloader bug - running this in the desktop player with `--load-behavior blocking` progresses to the main menu.
