### ISSUE TITLE
Another Mission - Regression where Flash Forward 2021 game no longer works.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#14369]
### Describe the bug

Ruffle:Another Mission was created for Flash Forward 2021 and it ran fine at the time. Something since then has caused it to not work.

Once you get past the intro, the game appears to be a blank screen with the tutorial instructions visible. The HUD movies around when you press ASDW but you can't see the actual player or level.

![image](https://github.com/ruffle-rs/ruffle/assets/45497010/efb84efd-8314-40f6-b35d-07fe36908967)

### Expected behavior

Expected behavior is to see the player and level.

### Content Location

https://www.newgrounds.com/portal/view/782076

### Affected platform

Self-Hosted Web

### Operating system

Windows 11

### Browser

Chrome Version 119.0.6045.160

**Comment by n0samu** [comment]
Looks like another regression caused by #12063 😦
