### ISSUE TITLE
ActionScript 1.0 Adobe Flash Game Fails to Run Any Network Connection

### ISSUE THREAD

**Issue by TechXPlays** [ruffle-rs/ruffle#14388]
### Describe the bug

when opening the SWF file for my game, which connects to a server to check version number, it never makes the network connection. Game is based on AS1.0, game originally came out in 2001, final update (version we are using) was 2006, a game called Nitto 1320 Challenge. Also tried adding URL for main server to the Advanced section of ruffle

### Expected behavior

Connect to server, check version number and other network connections in the game

### Content Location

[Tourney2.zip](https://github.com/ruffle-rs/ruffle/files/13664156/Tourney2.zip)
Here's the swf for the full game.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

local Windows Player

**Comment by n0samu** [comment]
It doesn't work in Flash Player either. The server responds with 401 Unauthorized.

**Comment by TechXPlays** [comment]
> It doesn't work in Flash Player either. The server responds with 401 Unauthorized.

I know it works in regular flash player because I'm playing it right now with Flash Player 7. 
![image](https://github.com/ruffle-rs/ruffle/assets/5988347/3fb28be9-9527-4f94-959d-f2cf76bedfce)

we generally use this site to combine the swf with an exe for our players who download the game, but it gives false positives on virus scans, so i wanted to try ruffle to see if that would fix it
https://pdfrecover.herokuapp.com/swftoexe/

**Comment by n0samu** [comment]
The server is also returning 401 Unauthorized to Ruffle. I think your server has a user agent rule set up to only accept the Flash projector and not browsers. If you have control over the server you will need to disable rules like this to properly test whether there is a bug. Until then I cannot help you.

**Comment by TDelmore** [comment]
Just confirming that I did indeed have a check for the User Agent as a rudimentary anti-cheat - I've removed that now.

**Comment by n0samu** [comment]
And that fixed the game in Ruffle, correct? I see the login screen showing up now.
