### ISSUE TITLE
Bitmaps are not rendering anymore on Android

### ISSUE THREAD

**Issue by Txori** [ruffle-rs/ruffle#14381]
### Describe the bug

I discovered the bug yesterday, but this might be a regression from the last few days.
I'm loading ruffle on my website using: <script src="[https://unpkg.com/@ruffle-rs/ruffle">](https://unpkg.com/@ruffle-rs/ruffle%22%3E)</script>

When displaying games that are using bitmapdata on Ruffle / Chrome / Android, everything images that should be displayed are broken.

Display this game on your phone: https://www.txori.com/juju-adventure

![Screenshot_20231212-122105](https://github.com/ruffle-rs/ruffle/assets/3765943/5696fda5-0ffa-4026-9f4d-d9ff053419c3)

### Expected behavior

Bitmap should display correctly, just like before:

![Screenshot 2023-12-12 122029](https://github.com/ruffle-rs/ruffle/assets/3765943/c8d54c7f-d955-4f09-aa0e-b60288b23924)

### Content Location

You can see the bug by trying those Ruffle demos from Android:
https://ruffle.rs/demo/
FlyGuy or WastedSky

### Affected platform

Browser's extension

### Operating system

Android 12

### Browser

Chrome 120.0.6099.43

**Comment by Dinnerbone** [comment]
Seems to work on Firefox for android, likely specific to Chrome

![Screenshot_20231212_122643_Firefox Nightly.jpg](https://github.com/ruffle-rs/ruffle/assets/317625/3bf3f05f-5a11-4c1f-8a80-d58cccfe6ad3)

**Comment by Txori** [comment]
You are right, I just tried, and it's working perfectly with Firefox.
But it's broken on Brave too :/

**Comment by Dinnerbone** [comment]
Opened https://github.com/gfx-rs/wgpu/issues/4868

**Comment by Dinnerbone** [comment]
It's a chrome bug, unrelated to wgpu: https://bugs.chromium.org/p/chromium/issues/detail?id=1510149

**Comment by waspennator** [comment]
I can also confirm I'm seeing this on my s22 with chrome, but not on Firefox or edge.

**Comment by Txori** [comment]
Everything is repaired with Chrome latest update!
(version 120.0.6099.193)
