### ISSUE TITLE
ggggggggggggggggggggggggggggggggggggggggggg

### ISSUE THREAD

**Issue by Mihajlix09** [ruffle-rs/ruffle#14405]
### Describe what you were doing

gggggggggggggggggggggggggggggggggggggggggggg

### What does the crash message say?

gggggggggggggggggggggggggggggggggggggggggg

### Ruffle Version

ggggggggggggggggg

### Affected platform

Desktop app

### Operating system

gg

### Additional information

ggggggggggggggggggggggggg

**Comment by Lord-McSweeney** [comment]
Please stop opening new issue reports.
