### ISSUE TITLE
Ultimate Flash Sonic: Skidding sound never stops playing

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1441]
When you're going down a slope in Ultimate Flash Sonic, and press the key opposite to the direction you're moving, Sonic lets out a skidding sound while he slows down. This sound loops and does not stop playing in Ruffle until another sound, like a jump, overrides it.

**Comment by relrelb** [comment]
This also happened to me, should be fixed by https://github.com/ruffle-rs/ruffle/pull/1445/commits/af1ed5d8163940e31130a318db30b61b02da55fb.

**Comment by Herschel** [comment]
Fixed by #2825.
