### ISSUE TITLE
AS2 Regression in text masking: Portal Defenders - Fast Break

### ISSUE THREAD

**Issue by pestoforce** [ruffle-rs/ruffle#14434]
### Describe the bug

AS2:
In previous versions of Ruffle, you could have an animated shape-tween mask over text to reveal the text underneath.

Now, in the current version of Ruffle, animated shape-tween masks over text do not reveal the text (the text remains hidden).

This can be seen in https://www.newgrounds.com/portal/view/881545
At half time, "Tom" in the bottom left corner appears to offer tips via on-screen text, but that text is no longer visible.

This game was made for the Flash Forward Jam, so this was definitely working recently.

### Expected behavior

Animated masks over text should reveal the text.

### Content Location

https://www.newgrounds.com/portal/view/881545

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chrome

### Additional information

![missingmaskedtext](https://github.com/ruffle-rs/ruffle/assets/40042480/a29ccbd8-4a34-42f2-b8d1-90f612f1b608)

**Comment by Lord-McSweeney** [comment]
One of these commits is responsible: https://github.com/ruffle-rs/ruffle/compare/nightly-2023-08-04...nightly-2023-08-07

**Comment by n0samu** [comment]
This was actually regressed by #12955, specifically commit 8d71ab34368516cefa225cc58679d4602d4c637d. Here is a minimal reproduction of the issue (exported from the original SWF using JPEXS):
[sprite6746.zip](https://github.com/ruffle-rs/ruffle/files/13698975/sprite6746.zip)

The text should appear after a few seconds, but in Ruffle 2023-09-09 and later, it does not.
