### ISSUE TITLE
Divine Intervention: Logo holes aren't empty as they should be

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1443]
![image](https://user-images.githubusercontent.com/35991016/97771993-8f690180-1b96-11eb-8972-af8094b30248.png)

In the logo of Divine Intervention during the startup sequence, the holes in the D and O are filled for a moment until the logo animation finishes playing out. In Flash normally, they don't do that.

**Comment by relrelb** [comment]
Fixed by #5692.
