### ISSUE TITLE
Commando Assault no longer works

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#14446]
### Describe the bug

The nightly 2023-12-18 release broke [Commando Assault](https://ooooooooo.ooo/static/?d38fcefb-89c5-4977-91ba-14237ca5e6e4); it now shows nothing but a blank screen. The error is:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Got "ReferenceError: Error #1069: Property flash.events:IEventDispatcher::addEventListener not found on com.miniclip._MiniclipGameManager and there is no default value.
        at com.macrojoy.zgd::Document/checkDomainAndStartGame()
        at com.macrojoy.zgd::Document()" when constructing AVM2 side of movie clip of type com.macrojoy.zgd::Document
```

### Expected behavior

The game should load.

### Content Location

Page URL: https://ooooooooo.ooo/static/?d38fcefb-89c5-4977-91ba-14237ca5e6e4
SWF: [Commando_Assault.zip](https://github.com/ruffle-rs/ruffle/files/13699067/Commando_Assault.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 120

**Comment by Lord-McSweeney** [comment]
Weird, this shouldn't be `VM_INTERNAL`: `Rejecting namespace match due to versions: Namespace("flash.events:IEventDispatcher", VM_INTERNAL) Namespace("flash.events:IEventDispatcher", AllVersions)`

**Comment by ThrowAwaySDXR11** [comment]
I've been having similar issues loading Commando Assault. Inspecting the code of other websites that successfully load it "ex: Gameflare", the game seems to run on multiple SWF files "/game.swf" along with the five maps "/resource/map_easy.swf, /map_normal.swf, hard.swf, hell, final". I tried plugging all six SWFs into Ruffle but it still showed up as black. Maybe there is a way to get it to work this way, but I am not sure.

**Comment by n0samu** [comment]
@ThrowAwaySDXR11 the game is sitelocked

**Comment by ThrowAwaySDXR11** [comment]
Oh I see. So its impossible to get it working on another site. Good to know!

**Comment by ThrowAwaySDXR11** [comment]
You have to modify the document file in the main swf to not crash when its not on miniclip.com. Also ruffle can only load the map files on (wgpu-webgl) so set that as the preferred renderer. It should work after that, I got it working on mine.
