### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/dress-up-hentai-games/cosplay-hentai/

### ISSUE THREAD

**Issue by DarkDragon2232133** [ruffle-rs/ruffle#14468]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: error
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: error
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/dress-up-hentai-games/cosplay-hentai/

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
OS: Linux armv81

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by n0samu** [comment]
Transient network error
