### ISSUE TITLE
swf is zoomed in and there is no way to fix it

### ISSUE THREAD

**Issue by dantheman121** [ruffle-rs/ruffle#14471]
### Describe the bug

the swf file is zoomed in to the point of me not being able to see all of it

### Expected behavior

the swf file should not be zoomed in

### Content Location

N/A

### Affected platform

Online demo

### Operating system

Linux

### Browser

Google Chrome

**Comment by n0samu** [comment]
@dantheman121 What SWF are you trying to play? Have you tried downloading the desktop app and changing the Scale Mode in the Player Settings?

**Comment by n0samu** [comment]
No information provided, closing

**Comment by dantheman121** [comment]
@n0samu it was test.swf

**Comment by n0samu** [comment]
Please zip and upload the SWF file.

**Comment by dantheman121** [comment]
@n0samu i can't its not supported

**Comment by dantheman121** [comment]
@n0samu ruffle doesn't work it keeps crashing

**Comment by n0samu** [comment]
@dantheman121 You need to make a zip file, put the SWF file in the zip file, and upload the zip file. Does that make sense?

**Comment by dantheman121** [comment]
[balk.zip](https://github.com/ruffle-rs/ruffle/files/13920676/balk.zip)
@n0samu

**Comment by n0samu** [comment]
It looks the same in Flash Player - this is not a Ruffle bug. The SWF's header indicates that it is 20x20 pixels. You'd need to edit the SWF's display rect using JPEXS Decompiler.
