### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Nido-nid** [ruffle-rs/ruffle#14484]
# Error Info
Error name: Error
Error message: panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/wasm/../unsupported/locks/mutex.rs:20:9:
assertion `left == right` failed: cannot recursively acquire mutex
  left: true
 right: false
Error stack:
```
j/n.wbg.__wbg_new_a64e3f2afc2cf2f8@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-61fBEJg-.js:2:54464
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0c2b013ac3c02c9d@:wasm-function[9877]:0x9cd27f
std::panicking::rust_panic_with_hook::hbf46ef0245cc9589@:wasm-function[6321]:0x8bd4fc
core::panicking::panic_fmt::h14c85a61aa3d538e@:wasm-function[9667]:0x9c7e90
core::panicking::assert_failed_inner::h4ee8cb46314b5c9b@:wasm-function[4335]:0x7c3efb
core::panicking::assert_failed::h42e1c94449d31389@:wasm-function[9692]:0x9c9182
ruffle_core::loader::Loader::movie_loader::{{closure}}::h2fe7373084bb2388@:wasm-function[793]:0x296cc5
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::ha1693e4315f42b30@:wasm-function[1262]:0x4281f0
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hee8d58dba3b26db3@:wasm-function[3602]:0x7584b7
wasm_bindgen::convert::closures::invoke1_mut::ha9a30d0d24e166d7@:wasm-function[10600]:0x9e8be6
closure4477 externref shim@:wasm-function[10944]:0x9f4a9c
ee@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-61fBEJg-.js:2:817
c@https://ruffle.rs/demo/assets/ruffle_web-wasm_extensions-61fBEJg-.js:2:114

```
AVM2 stack:
```
    at cactusGame.data::LevelData/prepareXMLcycle()
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/bitey1.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-21
Channel: nightly
Built: 2023-12-21T00:15:25.348Z
Commit: a5560587da4a9816a5c36cd93671f3d62550f004
Is extension: false

# Metadata
width: 608
height: 480
frameRate: 30
numFrames: 20
swfVersion: 10
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 10955768

**Comment by n0samu** [comment]
Is this Cactus McCoy? Looks like the same issue as #9736
