### ISSUE TITLE
(Question) Probably the dependencies list to build from source is outdated

### ISSUE THREAD

**Issue by hardBSDk** [ruffle-rs/ruffle#14487]
The Ruffle GUI is using egui, thus the GTK3 dependency doesn't makes sense.

**Comment by torokati44** [comment]
The GTK dependency is not directly for Ruffle, it's for [Rusty File Dialogs](https://github.com/PolyMeilex/rfd), which we use to get the file picker dialogs for every supported platform.

**Comment by hardBSDk** [comment]
@torokati44 There's no Rust alternative for file dialogs?

**Comment by torokati44** [comment]
There probably is, but this was the easiest solution, I don't see anything wrong with it personally, and provides a familiar experience for users on all platforms.

**Comment by torokati44** [comment]
Closing as answered.
If you have further questions, feel free to reopen, or start a topic in [Discussions](https://github.com/ruffle-rs/ruffle/discussions).
