### ISSUE TITLE
browser extension crashes the browser through oom seemingly without flash content involved

### ISSUE THREAD

**Issue by galtgendo** [ruffle-rs/ruffle#14486]
### Describe the bug

Upon a visit on https://poczta.o2.pl/ (login page of an email service), the browser starts leaking memory until it oom crashes.
The page (AFAIK) doesn't have any flash content.
No action is necessary - just entering the page triggers it.
Disabling ruffle prevents the problem from happenning.

### Expected behavior

Not to leak/crash.

### Content Location

no flash content (AFFAIK)

### Affected platform

Browser's extension

### Operating system

linux

### Browser

vivaldi 6.4.3160.47

### Additional information

Adblock Plus, Tampermonkey, Stylus, a couple more, but likely irrelevant

**Comment by Lord-McSweeney** [comment]
I cannot reproduce this- can you disable _all_ of your other extensions and test? Also, can you send a full list of extensions you have installed?

**Comment by n0samu** [comment]
I was able to reproduce this in Chrome with adblock off. It seems to be caused by a misbehaving tracking script somehow.

**Comment by n0samu** [comment]
Hi @galtgendo, the next release should hopefully fix this problem. The release (nightly 2023-01-09) should reach your Chrome browser in about 8-9 hours. Please try it and let us know if the problem is fixed!

**Comment by galtgendo** [comment]
Was bit slow to check.
Seems to work.

PS: looking forward to you making Realm Grinder work.
