### ISSUE TITLE
Emulator information

### ISSUE THREAD

**Issue by rikkoooo** [ruffle-rs/ruffle#14555]
Please allow movies to know that they are running on where (Flash Player or Ruffle). When getUrl("EmulatorDetection") command is executed, go to the next frame in the movieclip (or the master timeline) that command is runned. So, movies can know they are running on witch player, and they can deny Ruffle or want Ruffle.

**Comment by torokati44** [comment]
While I'm nowhere near authoritative on this matter - at least IMHO, this should be an explicit anti-goal of basically any emulator, including Ruffle, mostly for reasons of [principle/philosophy.](url)
But I can't/won't stop anyone adding this if they want to.

**Comment by n0samu** [comment]
Sorry, this is not a feature we would be willing to implement. There are some ways to detect whether Ruffle is in use already, but they are unsupported. Feel free to open a discussion if you want details on that.
