### ISSUE TITLE
Error on https://www.gameflare.com/embed/papas-bakeria/

### ISSUE THREAD

**Issue by joliewithcats** [ruffle-rs/ruffle#14558]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.gameflare.com/embed/papas-bakeria/

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-27
Channel: nightly
Built: 2023-12-27T00:14:54.557Z
Commit: 28a3c7178a805ddb7027d30738b0e58acf94147e
Is extension: false

# Metadata

**Comment by Lord-McSweeney** [comment]
Closing as this is likely a network error unrelated to Ruffle.
