### ISSUE TITLE
Interpolation Selection

### ISSUE THREAD

**Issue by rikkoooo** [ruffle-rs/ruffle#14556]
Please allow movies and users to select the interpolation (linear, zero-older hold, and brighter). When getUrl("interpolateLinear") command is executed, switch to linear. Do the smilar thing with getUrl("interpolateZOH") and getUrl("interpolateBrighter") commands. Allow users to change the interpolation tech until getUrl("interpolationForce") command is executed.

Also please allow users and movies to select different interpolations for different audio types (ADPCM, MP3, ASAO, raw, etc), different modes (stream, event, start/stop, action-controlled), and different speeds (5512, 11025, 22050, 44100). Please set interpolate-setting of forcing commands to affect only the spesific type if runned after commands like these:

getUrl("interpolateAffectedTypeADPCM")
getUrl("interpolateAffectedTypeMP3")
getUrl("interpolateAffectedTypeLittle")
getUrl("interpolateAffectedTypeNative")
getUrl("interpolateAffectedTypeAsao")
getUrl("interpolateAffectedTypeSpeex")
getUrl("interpolateAffectedTypeAll")

getUrl("interpolateAffectedModeStream")
getUrl("interpolateAffectedModeEvent")
getUrl("interpolateAffectedModeStartStop")
getUrl("interpolateAffectedModeAction")
getUrl("interpolateAffectedModeAll")

getUrl("interpolateAffectedSpeed5512")
getUrl("interpolateAffectedSpeed8000")
getUrl("interpolateAffectedSpeed11025")
getUrl("interpolateAffectedSpeed16000")
getUrl("interpolateAffectedSpeed22050")
getUrl("interpolateAffectedSpeed44100")
getUrl("interpolateAffectedSpeedAll")

**Comment by rikkoooo** [comment]
Addition: Info about brighter interpolation

It's like anti-interpolation, just for increasing trebles and making sound brighter. Each endpoint of ZOH segment must be on the position of 2x-amplituded.

**Comment by Dinnerbone** [comment]
Sorry I need a bit more context here - are `getUrl("interpolateAffectedSpeedAll")` etc commands that work in Flash? I'm guessing it's AS2? Is there any documentation on this? I can't find anything by googling these names.

**Comment by rikkoooo** [comment]
It's working fully standardly, just opens a new tab on browser. I think Ruffle will be better if Ruffle can run these commands in a non-standard way.

**Comment by n0samu** [comment]
If this were to be implemented, it would be implemented as standard Ruffle options, not with getUrl. [See our wiki](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options).

**Comment by rikkoooo** [comment]
Are these options accessible by the movie? The movie must be able to deny external preferences.

**Comment by rikkoooo** [comment]
ADDITION: For movies that don't know Ruffle, getUrl("interpolationForce") must be assumed to runned already when the movie is started and the movie must be able to release this by executing getUrl("interpolationRelease")

**Comment by n0samu** [comment]
> The movie must be able to deny external preferences.

That doesn't make sense. Why would you have control over the movie but not the Ruffle options?

**Comment by rikkoooo** [comment]
The movie author may be do not want some usages of their movie (for example, cheating a game), and because of this, the movie author should be able to force the player to something. The permission-disabling way (in this way, permissions are gived to the user and movie can disable this permissions) is not fair because movie-owners they don't know Ruffle will can not disable permissions. Because of that, permissions must be disabled at start.

**Comment by n0samu** [comment]
That has nothing to do with audio interpolation methods.

**Comment by rikkoooo** [comment]
In fact, audio interpolation methods (and actually everything) can be used for cheating, hacking, and etc. in some cases. For example, assume i made a 5512Hz audio clip and it has an easter egg. Assume that audio made for PAL composite, and the TV will show colored lines due to PAL composite YUV coding if that signal given to it via composite input and a ZOH interpolation (no interpolation), but the TV will show only BW lines if that sound is transmitted with linear interpolation. And, assume a password is hidden in that colored swirls. Assume the user must convert linear interpolation to ZOH to find the password. What will happen if the user simply sets the interpolation option to ZOH? Of course, Cheat!

**Comment by n0samu** [comment]
I'm very impressed that you were able to come up with that scenario. If this is legitimately how you are using Ruffle, I should give you some type of award or something. Anyway, this is not a reasonable request. Closing

**Comment by Lord-McSweeney** [comment]
@rikkoooo If your game is really that complex, you can make a fork of Ruffle and implement the commands yourself.
