### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Iskander0** [ruffle-rs/ruffle#14597]
### Describe what you were doing

Simply ran program

### What does the crash message say?

panicked at desktop/src/gui/controller.rs:200:14:
Surface became unavailable: Timeout

### Ruffle Version

0.1.0-nightly (8b414c48c74497d015290a277fcf35d48b8912f4 2024-01-02)

### Affected platform

Desktop app

### Operating system

EndeavourOS Rolling Release (rolling) [64-bit]

**Comment by n0samu** [comment]
This is likely a problem with your video driver. Please make sure hardware acceleration is working.

**Comment by Iskander0** [comment]
All hardware acceleration works. If you wish, I can provide further system info

**Comment by n0samu** [comment]
Sure, go ahead. And please check if running Ruffle with `-g gl` or `-g vulkan` makes any difference.
