### ISSUE TITLE
web: Use standard JS naming conventions

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1460]
Change the public JavaScript API to use JavaScript naming conventions:
 * `UpperCamelCase` for classes
 * `lowerCamelCase` for properties and functions
 * `UPPER_SNAKE_CASE` for constants
 * Set up eslint to verify these, if possible.
This should apply at least to all public-facing APIs.

The Rust bindings could use [`js_name`](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/js_name.html) to set the exported JS names.

**Comment by Dinnerbone** [comment]
This has been done with the recent typescript PR.
