### ISSUE TITLE
Bubble Shooter Classic - Error after loading

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14600]
### Describe the bug

Thought I already posted the error here.

ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3e33e40 }) to handler FunctionObject(FunctionObject { ptr: 0x163bd08, name: Ok("jground.core::jGround/onEnterFrame()") }) : ReferenceError: Error #1069: Property getCharBoundaries not found on flash.text.TextField and there is no default value.

### Expected behavior

Load & Run

### Content Location

https://www.spiele-umsonst.de/azad/downloads/flashgames/bubble-shooter-classic.swf

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by torokati44** [comment]
Should be fixed by https://github.com/ruffle-rs/ruffle/pull/14694.
