### ISSUE TITLE
Add Socket Proxy to the Desktop Advanced Options

### ISSUE THREAD

**Issue by CanIGetaPR** [ruffle-rs/ruffle#14608]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

Desktop build, is missing the Socket Proxy option for command line options and advanced options in the GUI, which the javascript version has.

Related to: https://github.com/ruffle-rs/ruffle/issues/13896

**Comment by n0samu** [comment]
The socket proxy option is only useful on the web, where sockets can't be used directly. On desktop, Ruffle makes direct socket connections, just like Flash Player. So a proxy like websockify is unnecessary.
