### ISSUE TITLE
4 Elements 2 - Error after loading

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#14619]
### Describe the bug

The console throws an error after the game is loaded and you can't play

core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "load_game_error", class: game.api::ApiEvent, ptr: 0x5b286b0 }) to handler FunctionObject(FunctionObject { ptr: 0x5afb118, name: Ok("game::Game/onLoadGame()") }) : ArgumentError: Error #2008: Parameter align must be one of the accepted values.

### Expected behavior

load & play

### Content Location

https://data.gameflare.com/games/2532/8QspNCHbEwQTm6.swf

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by Lord-McSweeney** [comment]
This attempts to get the `@align` property of some XML to use for the `TextField` setting. However, it gets it like this:
```
getproperty MultinameL([PrivateNamespace(null,"10"), PrivateNamespace(null,"114"), PackageNamespace(""), PackageNamespace("com.playrix.util"), PackageInternalNs("com.playrix.util"), ...])
```
(`com.playrix.util::XMLUtility$/getString`)
I'm not sure but I think this doesn't pass the first check, `!name.has_nonempty_namespace()`, in this part of `XMLObject::get_property_local`, which handles special multinames:
```
        let multiname = if !name.has_nonempty_namespace()
            && !name.is_attribute()
            && !name.is_any_name()
            && !name.is_any_namespace()
        {
            name.local_name()
                .map(|name| string_to_multiname(activation, name))
        } else {
            None
        };
```

**Comment by evilpie** [comment]
Seems like https://github.com/ruffle-rs/ruffle/pull/13966 changed this from `has_explicit_namespace` to `has_nonempty_namespace`.
