### ISSUE TITLE
Cocolani - Chat box 

### ISSUE THREAD

**Issue by cmdocmd** [ruffle-rs/ruffle#14641]
### Describe the bug

Message is not being sent when pressing Enter
![image](https://github.com/ruffle-rs/ruffle/assets/55096480/975af803-6b74-4539-a6e2-710bbdae2f96)

### Expected behavior

When pressing Enter it should send the message

### Content Location

https://safariislandsgame.com/play/

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by mohammadalshikh** [comment]
@cmdocmd Hey I have a question for you could you send me your discord/any social media you have? thx

**Comment by cmdocmd** [comment]
@mohammadalshikh my discord is sy963
