### ISSUE TITLE
RPG Shooter Starwish: text box display bug

### ISSUE THREAD

**Issue by ku7698234** [ruffle-rs/ruffle#14668]
### Describe the bug

Game location here: [https://www.gamesflow.com/jeux.php?id=2185451](https://www.gamesflow.com/jeux.php?id=2185451)
When the game is started by clicking "Game Start" then "New Game" then "Confirm Normal", after the text finishes scrolling, the dialog box text cannot be displayed.

### Expected behavior

All dialog box text should appear normally

### Content Location

https://www.gamesflow.com/jeux.php?id=2185451
or here:
[3935.zip](https://github.com/ruffle-rs/ruffle/files/13863937/3935.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Mozilla Firefox 121.0

**Comment by kjarosh** [comment]
Should be fixed now thanks to https://github.com/ruffle-rs/ruffle/pull/14722, after https://github.com/ruffle-rs/ruffle/pull/16906 it should work even better!
