### ISSUE TITLE
Error on http://www.superflashbros.net/as3sfxr/

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#14674]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/globals/flash/display/graphics.rs:1192:18:
missing data: RangeError: Error #1125: The index 8 is out of range 8.

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Radeon R9 200 Series"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: as3sfxr.swf
Param menu: false
Param scale: noboarder
Param allowFullscreen: true
Param allowScriptAccess: always
Param bgcolor: #c0b090
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://www.superflashbros.net/as3sfxr/
SWF URL: http://www.superflashbros.net/as3sfxr/as3sfxr.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-30
Channel: nightly
Built: 2023-12-30T00:15:06.603Z
Commit: 583327ff6255913bdc48ae93fb78d58016c8f763
Is extension: true

# Metadata
width: 640
height: 500
frameRate: 25
numFrames: 1
swfVersion: 14
backgroundColor: #C0B090
isActionScript3: true
uncompressedLength: 52520

**Comment by torokati44** [comment]
I believe this error was introduced by https://github.com/ruffle-rs/ruffle/pull/14644.

**Comment by torokati44** [comment]
The current check, while seems entirely logical and correct. Perhaps too correct, to match FP...
Is it possible that Flash accepts the last XY pair even if it can only read the X part of it? 🤔 And then who knows what Y will be...

**Comment by Croworbit** [comment]
is this duplicate or related to #12055
