### ISSUE TITLE
Font on web doesn't work anymore.

### ISSUE THREAD

**Issue by cmdocmd** [ruffle-rs/ruffle#14675]
### Describe the bug

After following the guide on wiki for changing font on web it worked on 8-1-2024
![image](https://github.com/ruffle-rs/ruffle/assets/55096480/eae4f111-e608-4151-a200-8256f8c5f41c)
but on 9-1-2024 without change anything it stopped working.

### Expected behavior

![image](https://github.com/ruffle-rs/ruffle/assets/55096480/7c214696-3617-425a-a9ad-831e6be10e73)

### Content Location

you can test it here.

http://www.cocolaniisland.com

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Most likely regressed by #14535- @evilpie can you take a look at this?

**Comment by evilpie** [comment]
The config doesn't specify the default fonts to use, so we fallback to our built-in "Noto Sans".

The config needs to be changed to:
```js
window.RufflePlayer.config = {
	fontSources: ["rufont.swf"],
        defaultFonts: {
           serif: ['Arial'],
           sans: ['Arial']
       }
...
```

**Comment by cmdocmd** [comment]
changing config did fix this thanks.

**Comment by Dinnerbone** [comment]
> I think this is an unfortunate side-effect, of us now treating "Arial" like an alias for the default _sans_ font.

Do we need to? 🤔

**Comment by evilpie** [comment]
Not necessarily. It's just convenient to re-use the same fallback list for them as well. I think we should just move that to the end of `resolve_font` were we currently always use `DefaultFont::Serif`, and instead select based on the name.
