### ISSUE TITLE
Trait removeChildren in class MainTimeline has same name as trait removeChildren

### ISSUE THREAD

**Issue by danielkorte** [ruffle-rs/ruffle#14704]
### Describe the bug

ERROR core/src/display_object/movie_clip.rs:954 Got AVM2 error RustError("VerifyError: Trait removeChildren in class MainTimeline has same name as trait removeChildren in class DisplayObjectContainer, but does not override it") when attempting to assign symbol class website_fla.MainTimeline

### Expected behavior

No bug

### Content Location

Private

### Affected platform

Self-hosted version

### Operating system

Chrome

### Browser

Chrome

**Comment by torokati44** [comment]
If you could also tell us where have you encountered this error (which SWF or web page), that would help a lot.

**Comment by Lord-McSweeney** [comment]
Can you share the private SWF? Or at least the source code for the MainTimeline class?

**Comment by Lord-McSweeney** [comment]
Nevermind, this just needs version-gated `removeChildren` (should be gated to FP 11 and above)
