### ISSUE TITLE
Ruffle failed to load Flash SWF file

### ISSUE THREAD

**Issue by buddydelegal** [ruffle-rs/ruffle#14710]
### Describe the bug

When I go to the webpage where I'm trying to view the SWF file, I get an error message saying, "Ruffle failed to load Flash SWF file."

### Expected behavior

I expected Ruffle to load the SWF file.

### Content Location

https://web.archive.org/web/20130219060104/http://copiousnotes.bloginky.com/2010/07/24/willy-wonka-hard-work-at-the-fun-factory

### Affected platform

Browser's extension

### Operating system

Mac OS Sonoma

### Browser

Mozilla Firefox

**Comment by Lord-McSweeney** [comment]
This is expected, the SWF file was not archived by the Wayback Machine.
