### ISSUE TITLE
Cursor selection no longer appears over whitespace

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#14713]
### Describe the bug

Whitespace in the selection is never rendered. For example, if the text "Hello world" is selected, "Hello" and "world" will have an opaque black rectangle rendered under the text, but the space will not have it. I suspect this is due to the device font changes (not #14690), but I'm not sure.

### Expected behavior

The selection is rendered on whitespace.

### Content Location

Any basic reproduction works

### Affected platform

Desktop app

### Operating system

Ubuntu 20.04

### Browser

Irrelevant

**Comment by kjarosh** [comment]
I ran bisect over this, which reports 4db87a9643e23e3f0ae91694d89a67c9b566074d as the culprit (which appears to be from #14535). Also it does not always happen, I guess for some fonts only (perhaps the default ones?).
