### ISSUE TITLE
Touch screens on Windows are not supported

### ISSUE THREAD

**Issue by SnDream** [ruffle-rs/ruffle#14729]
### Describe the bug

Using a Windows touch screen device to run the desktop version of the Ruffle player does not allow you to use touch as a left mouse click to manipulate Flash animations.

### Expected behavior

Touch can be recognised as a mouse click

### Content Location

Any swf that supports mouse clicks (I think)

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

Touch can control Ruffle's own menus.
Not sure if Flash has a dedicated touch API, but touch can be used normally as a left mouse click in the Web Demo and the official player.

**Comment by Lord-McSweeney** [comment]
Duplicate of #2162.
