### ISSUE TITLE
TypeError: Error #1115: LzApplication is not a constructor.

### ISSUE THREAD

**Issue by antonlindgren** [ruffle-rs/ruffle#14734]
### Describe the bug

Flash page for CIMC (Cisco Integrated Management Controller) won't load using Ruffle.
Tried both the web extension and the binary.

It shows the loading bar and the ruffle icon and then the loading bar and a big play-icon (on web extension), whilst the console spams this message:

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1fe3808 }) to handler FunctionObject(FunctionObject { ptr: 0x8d9418, name: Ok("LzPreloader/enterFrame()") }) : TypeError: Error #1115: LzApplication is not a constructor.
  at LzSpriteApplication()
  at LzPreloader/enterFrame() 339.js:843:21`
  
  Using the original adobe flash player everything seems to work OK.

### Expected behavior

I expect to see the UI as I do with the original adobe flash player (test through binary, not web extension)

### Content Location

Attached here -v

[cimc-swf.zip](https://github.com/ruffle-rs/ruffle/files/13928970/cimc-swf.zip)

### Affected platform

Browser's extension

### Operating system

Debian 12

### Browser

Google chrome 120 and Ruffle binary

### Additional information

Not at the moment, but I can test and provide if necessary.

**Comment by Lord-McSweeney** [comment]
The main issue is this, which will be fixed by #14732:
`VerifyError: Trait removeChildren in class LzSprite has same name as trait removeChildren in class DisplayObjectContainer, but does not override it`

**Comment by antonlindgren** [comment]
Dang, that's a fast reply, @Lord-McSweeney! Thanks for the information. Do you know when this commit will be available in beta/release so I can test and verify? Cheers

**Comment by Lord-McSweeney** [comment]
It made it into today's nightly release, which will be released in 5-6 hours. The web extension for Firefox will be updat

**Comment by Lord-McSweeney** [comment]
Next this needs `XML.namespaceDeclarations()`.

**Comment by evilpie** [comment]
This now actually shows an UI. I assume for this application to work you actually need something for it to connect to?

There is still this error:
```
2024-01-16T09:34:24.641965Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "ioError", class: flash.events::IOErrorEvent, ptr: 0x557140657250 }) to handler FunctionObject(FunctionObject { ptr: 0x5571318fbd40, name: Ok("LzHTTPLoader/ioErrorHandler()") }) : ReferenceError: Error #1069: Property function Function() {} not found on flash.events.IOErrorEvent and there is no default value.
	at flash.events::Event/formatToString()
	at flash.events::IOErrorEvent/toString()
	at LzHTTPLoader/ioErrorHandler()
```

Somehow `formatToString` when iterating over `arguments`, gets a property named `"Function() {}"`, so something somewhere must have added this on `prototype`, I guess?

**Comment by antonlindgren** [comment]
> This now actually shows an UI. I assume for this application to work you actually need something for it to connect to?
> 

Can confirm that the UI now works, and I can click around on it.

Getting these errors in the console tho, not sure how important they are:

`
ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "open", class: flash.events::Event, ptr: 0xc446388 }) to handler FunctionObject(FunctionObject { ptr: 0x17a8bf78, name: Ok("LzHTTPLoader/openHandler()") }) : ReferenceError: Error #1069: Property function Function() {} not found on flash.events.Event and there is no default value.
`

`
embed-compressed.js:417 Uncaught TypeError: $4.CallFunction is not a function
    at lz.embed.dojo.Communicator._chunkArgumentData (embed-compressed.js:417:57)
    at lz.embed.dojo.Communicator._execFlash (embed-compressed.js:428:6)
    at lz.embed.dojo.Communicator.$1 [as callMethod] (embed-compressed.js:405:51)
    at Object._callMethodSWF [as callMethod] (embed-compressed.js:169:37)
    at Object.__gotload (embed-compressed.js:577:20)
    at HTMLIFrameElement.onload (index.html:1:24)
`

**Comment by antonlindgren** [comment]
After some more testing, appears that everything works as intended :)
