### ISSUE TITLE
Grand Theft Grotto - presents don't disappear upon collection

### ISSUE THREAD

**Issue by BeardedFish** [ruffle-rs/ruffle#14751]
### Describe the bug

When playing the game Grand Theft Grotto with Ruffle, any time a present is collected it does not disappear from the map:

![Present not Disappearing on Collection](https://i.imgur.com/S9Be0JE.png)

### Expected behavior

On native Flash Player 32, when collecting presents they disappear from the map:

![Present Disappearing on Collection](https://i.imgur.com/7FPAZc7.png)

### Content Location

https://andkon.com/arcade/obstacles/grandtheftgrotto/

### Affected platform

Browser's extension

### Operating system

Microsoft Windows 10 Version 22H2 (OS Build 19045.3930)

### Browser

Microsoft Edge Version 120.0.2210.133 (Official build) (64-bit)

**Comment by n0samu** [comment]
The error is:
`WARN core/src/avm1/activation.rs:1878 RemoveSprite: Source is not a display object`

**Comment by n0samu** [comment]
This is a regression caused by commit 7461c030495706af93b8a4abc4fabaf0c30a18cb (#14276)
