### ISSUE TITLE
Hosting ruffle-rs crashes, but using the extension does not?

### ISSUE THREAD

**Issue by KuromeSan** [ruffle-rs/ruffle#1475]
Hello, i recently tried accessing http://famita.ml/pc/ with Ruffle extension and it seems one of the newer updates just made it work, so i tried including it on the site, but then it crashes ?

`# Error Info
Error name: TypeError
Error message: Response has unsupported MIME type

# Player Info
Allows script access: false

# Page Info
Page URL: http://famita.ml/pc/flashless.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
`

webpage is up here, http://famita.ml/pc/flashless.html

**Comment by Dinnerbone** [comment]
You need to configure your webserver to correctly serve wasm files. We have some instructions on our wiki: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-wasm-mime-type

**Comment by Toad06** [comment]
Seems you've managed to fix the issue.
