### ISSUE TITLE
Ruffle Selfhosted Not Working

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1477]
So here is what I have tried:

I download the latest Nightly build self-hosted version.
uploaded on the server (under root folder: All files are here: https://www.forkids.education/ruffle_web/ ). I have enabled temporarily to let you guys have a look if I am missing something.

Then I put this before </body> (also tried in the header but same) : 

<script src="https://www.forkids.education/ruffle_web/ruffle.js"></script>

Here is the page where Flash meant to play:
https://www.forkids.education/test-file/

I am getting this error (Attached Screenshot)
![Screen Shot 2020-11-04 at 4 56 52 AM](https://user-images.githubusercontent.com/45603200/98057155-0afad500-1e5b-11eb-864a-515239847ffa.jpg)

I would really appreciate if you gus can guide me to fix this. I know I am doing something wrong because your web demo is playing and mine should too.

**Comment by Herschel** [comment]
Your server is serving the WebAssembly file with the incorrect MIME type; try [these instructions in the wiki](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-wasm-mime-type) and see if it helps.

**Comment by zohebnsr** [comment]
I use VPS and contacted my host to edit Apache config. He said it requires Root access that is not available with a managed VPS hosting plan. Any other solution to make the server handle .wasm without editing Apache configuration?

**Comment by Dinnerbone** [comment]
You can likely place a .htaccess file with the needed configuration in the same folder.

**Comment by zohebnsr** [comment]
I tried editing .htaccess file, but that doesn't seem to work, Tried adding this

<IfModule mod_mime.c>
  AddType application/wasm .wasm
</IfModule>

in the root as well as inside folder, but none seem to work

**Comment by Dinnerbone** [comment]
I think the syntax for a `.htaccess` would be this, based on some googling (but I don't use apache myself, could be wrong)

```apache
<IfModule mod_mime.c>
  AddType application/wasm .wasm
</IfModule>
```

If that doesn't work, see if there's any error logs on the server. It's possible your host has disabled using htaccess like this, which would be quite unfortunate.

**Comment by zohebnsr** [comment]
That what I wrote. But Github seemed to remove that part (probably because I didn't select code block. 

.htaccess editing is not disabled coz I use hotlink protection and that woks fine. But, this one isn't working.

**Comment by Dinnerbone** [comment]
Aha okay, sorry about that!

Well, darn. I'm not sure what to do here, if your host can't help you fix that or add this to the global config. There's a fallback option that we can investigate but it comes at a performance cost. We can try to investigate how to enable that, but ideally with an opt in config option and not by default.

**Comment by zohebnsr** [comment]
Still talking with Host (Dreamhost) via Trouble Ticket. I will update if they do something.

**Comment by Dinnerbone** [comment]
Their documentation suggests that htaccess should work: https://help.dreamhost.com/hc/en-us/articles/216736088-MIME-Types

Huh!

**Comment by Dinnerbone** [comment]
Oh, goodness me, sorry. I just checked your page and it looks like your htaccess *does* work, there's just a different error now (if you expand "view error details")

```
# Error Info
Error name: CompileError
Error message: wasm validation error: at offset 0: failed to match magic number
Error stack:
```

This is an odd one. Suggests the file that you've got uploaded isn't correct? It's showing as 0 bytes for me, which is an empty file.

**Comment by zohebnsr** [comment]
Thanks for checking. well, It worked now. I reuploaded all files creating a fresh folder and now it doesn't even have htaccess file inside. I am using the same code yo gave (only in root htaccess file). Game is working now. 

The game loads fine on Chrome (checked on wife's laptop). It's my Chrome who had this issue earlier as well as game won't load. I did  a fresh install of Chrome and worked. It's not working again (It's a chrome issue I think). Console screenshot attached if you can identify:

![Screen Shot 2020-11-05 at 3 43 28 AM](https://user-images.githubusercontent.com/45603200/98179878-4065f800-1f19-11eb-8b32-b5e859b5b01e.jpg)
![Screen Shot 2020-11-05 at 3 43 52 AM](https://user-images.githubusercontent.com/45603200/98179884-42c85200-1f19-11eb-92c3-85f7c444db25.jpg)

**Comment by Dinnerbone** [comment]
Do you get the same panic screen when it doesn't work? If so, can you copy paste everything from the details page?

**Comment by zohebnsr** [comment]
Not sure if I created confusion here. The game is working now (tested on my Safari and My Wife's Chrome). It just doesn't work on my Chrome (if I reinstall it, it will work: I know because it has happened in the past when I tested earlier). The welcome screen is same on my Chrome (with play button). No Error. When I click Play button, it doesn't bring content. Keep showing be blank black screen. No Error, nothing.

**Comment by Dinnerbone** [comment]
Aha, okay, I understand. So in one case you don't get any error messages, but it simply doesn't work after you hit play.

I suspect this is an issue with webgl on that device. It's unfortunate that there's no warnings in the console to guide us on that, as this is a very tricky one to track down.

If you try our demo on your chrome, do those animations/games work? https://ruffle.rs/demo/

**Comment by zohebnsr** [comment]
No, it doesn't work on my Chrome. I gotta reinstall again now. Hahaha! Thanks for your help buddy,
