### ISSUE TITLE
Error on https://f.silvergames.com/ruffle/player.php

### ISSUE THREAD

**Issue by DustyBagel** [ruffle-rs/ruffle#14777]
So I was just minding my own business, playing the flash game "Maga Miner" and then the game crashed and gave me this error. Not sure if this is because of ruffle or not. When this error occurred, I was mining stuff in the game and then it crashed. Hope this bug report can help fix the issue.
Here is the error info.

# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left

Error stack:
```
Error: panicked at /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fb4f9c5/wgpu/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    Not enough memory left


    at H.n.wbg.__wbg_new_ab87fd305ed9004b (https://f.silvergames.com/ruffle/03122023/core.ruffle.c315785ec851d1863ad5.js:1:56255)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h56e6782497447280 (wasm://wasm/03397206:wasm-function[9812]:0x9ba2d4)
    at std::panicking::rust_panic_with_hook::hc20eadded6bfe687 (wasm://wasm/03397206:wasm-function[6300]:0x8ac218)
    at core::panicking::panic_fmt::h7a368385936888dc (wasm://wasm/03397206:wasm-function[9617]:0x9b51f0)
    at core::ops::function::Fn::call::h46339f784de59ad5 (wasm://wasm/03397206:wasm-function[6554]:0x8bf462)
    at wgpu::backend::direct::ErrorSinkRaw::handle_error::h3e8cccfbe237fe9f (wasm://wasm/03397206:wasm-function[5342]:0x85993a)
    at <T as wgpu::context::DynContext>::device_create_buffer::h211cf00f11a8c7dd (wasm://wasm/03397206:wasm-function[7331]:0x909660)
    at <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hbe1a2c1095148f91 (wasm://wasm/03397206:wasm-function[1704]:0x4ffba9)
    at ruffle_render_wgpu::buffer_builder::BufferBuilder::finish::hae6d3dfc28a2db3f (wasm://wasm/03397206:wasm-function[7602]:0x918e78)
    at <ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::register_shape::hbfacbe53f39a2ebd (wasm://wasm/03397206:wasm-function[1421]:0x47ec4c)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1000, height: 750, depth_or_array_layers: 1 }

# Page Info
Page URL: https://f.silvergames.com/ruffle/player.php?id=1320
SWF URL: https://f.silvergames.com/mega-miner.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-12-03
Channel: nightly
Built: 2023-12-03T00:15:50.278Z
Commit: 947785607955e8b2a39d5dbb7cb98f0d37f38eb2
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 31
numFrames: 6
swfVersion: 10
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 1366200

**Comment by DustyBagel** [comment]
I have noticed that the crash happens when the game is lagging pretty bad, but I seem to be able to avoid the problem by waiting a bit for the game to stop lagging then continuing when it stops. I also noticed that Ui elements like the options for the start menu aren't in their correct places, like the "New Game" and other buttons have been moved slightly to the left. Also, the buttons in game for things like upgrades in the upgrades menu sometimes lose their text. This happens in game with other buttons too.

**Comment by n0samu** [comment]
The crash you got was probably caused by #14589. And the issues with text happen because TLF support is not fully implemented - see #12008.

**Comment by DustyBagel** [comment]
Oh, I see. Sorry about reporting a problem that has been reported already.

**Comment by n0samu** [comment]
No worries, thanks for taking the time to report an issue!
