### ISSUE TITLE
Into Space 1 Problems

### ISSUE THREAD

**Issue by Esortsyt** [ruffle-rs/ruffle#14778]
### Describe the bug

Whenever I use the spaceship, it won't stop going right, the engine shuts off randomly, and for some reason the space ship appears as a black box whenever my ship dies in into space or when the game is loading up. It also shut off the engine for the spaceship when I pressed wasd.

### Expected behavior

The spaceship should not appear as a black box when the game loads up and when my ship crashes and dies. The spaceship should also not constantly go to the right or left and it should not shut off the engine randomly. It also should not shut off my engine when I press wasd.

### Content Location

https://ooooooooo.ooo/static/?87bb5983-d02a-43a9-bbbf-fca8f0854d6e

^Link to Into space on flashpoint archive

### Affected platform

Self-hosted version

### Operating system

Chrome Os

### Browser

Google Chrome

**Comment by Esortsyt** [comment]
In the describe bug, I meant to say  "it won't stop going right or left", my mistake.

**Comment by n0samu** [comment]
Looks like you accidentally selected mouse control instead of keyboard control:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/8503e368-1d15-4d22-af3f-5b2db6dc0187)

Took me a while to realize this too 😅

**Comment by n0samu** [comment]
The black box is also expected behavior, that's the CPMStar ad box shown when the game is not played on the sponsor site (NotDoppler)
