### ISSUE TITLE
I Can't Draw - Crashes at start

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1478]
https://www.newgrounds.com/portal/view/570428/format/flash?emulate=flash

The movie "I Can't Draw" gets a crash screen as soon as it starts. Error details:

# Error Info
Error name: Error
Error message: panicked at 'not implemented', core/src/display_object/movie_clip.rs:261:41
Error stack:
```
Error: panicked at 'not implemented', core/src/display_object/movie_clip.rs:261:41
    at Object.Y (https://www.newgrounds.com/js/ruffle/lib/core.ruffle.e964ca96e06f7bbe7aa2.js:1:20276)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:29625)
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[1204]:0x22696b
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[1351]:0x240d29
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[3564]:0x2eb803
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[2807]:0x2cf1f2
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[3926]:0x2f0f98
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[3871]:0x2f062e
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[3922]:0x2f0ef7
    at https://www.newgrounds.com/js/ruffle/lib/2bae128c75aad5841970.module.wasm:wasm-function[275]:0x35043
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.newgrounds.com/portal/view/570428/format/flash?emulate=flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by relrelb** [comment]
Doesn't panic since #1813. However, still unimplemented.
