### ISSUE TITLE
Run 3: Blank screen during gameplay with WebGPU renderer

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#14787]
### Describe the bug

With Ruffle's WebGPU renderer enabled in Chrome, Run 3 shows a blank screen during gameplay:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/7bacecfd-08d4-4809-9a6c-0c7ac8792785)

The errors (deduplicated) are:
```
The sample count (2) of the texture is not supported.
 - While validating [TextureDescriptor].
 - While calling [Device].CreateTexture([TextureDescriptor]).
[Invalid Texture] is invalid.
 - While calling [Invalid Texture].CreateView([TextureViewDescriptor]).
The sample count (2) of the texture is not supported.
 - While validating [TextureDescriptor "Context3D depth texture"].
 - While calling [Device].CreateTexture([TextureDescriptor "Context3D depth texture"]).
[Invalid Texture "Context3D depth texture"] is invalid.
 - While calling [Invalid Texture "Context3D depth texture"].CreateView([TextureViewDescriptor]).
Multisample count (2) is not supported.
 - While validating multisample state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor]).
[Invalid TextureView] is invalid.
 - While validating colorAttachments[0].
 - While encoding [CommandEncoder].BeginRenderPass([RenderPassDescriptor "Context3D render pass"]).
[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[CommandBuffer], [Invalid CommandBuffer]])
```

Tested with the Chrome extension built from #14682, in its SWF player page.

### Expected behavior

The game should look like this:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/037f43b9-f162-4e97-82c4-8417ae3b828e)

### Content Location

[run3.zip](https://github.com/ruffle-rs/ruffle/files/13956530/run3.zip)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chromium 120

**Comment by Aaron1011** [comment]
We need to query for [get_texture_format_features](https://docs.rs/wgpu/latest/wgpu/struct.Adapter.html#method.get_texture_format_features), and round our desired value down.

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/14880
