### ISSUE TITLE
Error on https://www.comdotgame.com/play/kopa

### ISSUE THREAD

**Issue by alex63063** [ruffle-rs/ruffle#14783]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Failed to read from a ReadableStream.
```

# Player Info
Allows script access: true

Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/c78dcefe6d6d8727823974193b0ee2c6.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/kopa

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/104.0.0.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-09-05
Channel: nightly
Built: 2023-09-05T00:23:52.734Z
Commit: dabc2d56b91e677f4a08fa166968db8d5dff4e8d
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Probably a transient network error

**Comment by alex63063** [comment]
But this is happening with most similar games, and I don't know what to do.

**Comment by n0samu** [comment]
@alex63063 Try disabling other browser extensions and make sure your network is not blocking the site from loading properly. If you can't get it working, right-click the page and click Inspect to open Developer Tools, then click the Console tab and copy all messages from there. Then paste them into a text document and attach it here for us to look at.
