### ISSUE TITLE
Ruffle is Loading only first image from folder

### ISSUE THREAD

**Issue by sidmike** [ruffle-rs/ruffle#14786]
### Describe the bug

Ruffle loads only first two images (i see it in Chrome's network tab). But actually only one shows up. All the rest (third, fourth, etc.) are not even beeing loaded at all. Check my screen video , it must be clear what i am talking about.
https://github.com/ruffle-rs/ruffle/assets/41926797/695e0c82-da62-4eb6-bdcf-92ebab690c0d

### Expected behavior

Ruffle should load and show images all the time. It doesnt matter will it be second or third or 5th click, the image must be taken from corresponding folder (in my case "img") and loaded and showed. 

### Content Location
Demo page: https://astroday.lt/orakulas/
SWF: [Archive.zip](https://github.com/ruffle-rs/ruffle/files/13956391/Archive.zip)

### Affected platform

Self-hosted version

### Operating system

macOs Sonoma

### Browser

 Chrome 120

**Comment by n0samu** [comment]
This is probably another instance of #11554.

**Comment by sidmike** [comment]
> This is probably another instance of #11554.

looks like it is! Thanks
