### ISSUE TITLE
Bubble Guinea Pop loads extremely slowly in Firefox

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#14785]
### Describe the bug

After the ArmorGames intro and before the main menu appears, [Bubble Guinea Pop](https://armorgames.com/play/4846/bubble-guinea-pop?ruffle) seems to load some data. In the Ruffle desktop app this is almost instantaneous and in Chrome it takes about 2-3 seconds. But in Firefox, it takes *nearly 2 minutes* for the main menu screen to appear. I tested this by increasing the "Maximum allowed ActionScript execution duration (in seconds)" to 120 in the Ruffle extension settings, then loading the SWF URL into the extension's SWF player:
`https://cache.armorgames.com/files/games/bubble-guinea-pop-4846.swf`

### Expected behavior

The game should load in a reasonable amount of time in Firefox.

### Content Location

Page URL: https://armorgames.com/play/4846/bubble-guinea-pop?ruffle
SWF URL: https://cache.armorgames.com/files/games/bubble-guinea-pop-4846.swf

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 121

**Comment by evilpie** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1875046

**Comment by n0samu** [comment]
Seems like Mozilla has disabled WebGL OOP in Firefox, so the issue already was not reproducible. But it should be fixed by https://github.com/gfx-rs/wgpu/pull/6427 via #18431
