### ISSUE TITLE
Street Fighter Flash used to work with older version

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#14798]
### Describe the bug

The game used to work with older ruffle version, can't really tell which. 

Now the sound is working, and at the start of the game you can see some assets - after 1-2 seconds, all goes blank.

I've uploaded all the files from the game + 2 ruffle emulated versions. 

### Expected behavior

The game should open.

### Content Location

[streetfighterflash.zip](https://github.com/ruffle-rs/ruffle/files/13963329/streetfighterflash.zip)
[Ruffle Version 1](https://www.getgames.io/games/ruffle/?swf=random/streetfighterflash/streetfighter.swf&name=Street%20Figher%20Flash)
[Ruffle Version 2](https://www.getgames.io/games/ruffle/?swf=random/streetfighterflash/game.swf&name=Street%20Figher%20Flash)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

Version 1: ERROR core/src/loader.rs:911 Error during movie loading of "https://server.cpmstar.com/adviewas2.swf?poolid=731&amp;subpoolid=11302&instance7=_level0.instance1.ng_ad.instance7": FetchError("Got JS error")

Version 2: No error.

**Comment by n0samu** [comment]
This is already fixed by #14764, you should update the Ruffle version on your site.
