### ISSUE TITLE
Failed to fetch on Localhost

### ISSUE THREAD

**Issue by fabiomb** [ruffle-rs/ruffle#14805]
### Describe the bug

It´s a very simple problem, when i test the script on localhost I get the failed to fetch error, on a server it works fine. (example: https://www.fabio.com.ar/test.html)

i don´t know if this is important but is very useful when devs tests plugins or addons like this and get it to work is ideal, put below the whole dump of the player

### Expected behavior

this https://www.fabio.com.ar/test.html

### Content Location

downloads/badger.swf

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

### Additional information

# Error Info
Error name: Error
Error message: Failed to fetch: http://localhost/postrev/downloads/badger.swf
Error stack:
```
Error: Failed to fetch: http://localhost/postrev/downloads/badger.swf
    at it.displayRootMovieDownloadFailedMessage (https://unpkg.com/@ruffle-rs/ruffle:2:381791)
    at H.n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3 (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7b4e7a982553b1c826b2.js:1:7518)
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h4ba2f76c221b0bd4 (wasm://wasm/0366db4a:wasm-function[12994]:0xa782d9)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h95bbede504606b91 (wasm://wasm/0366db4a:wasm-function[963]:0x358303)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::hd35475b3eeab484b (wasm://wasm/0366db4a:wasm-function[1274]:0x4453ec)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h48fd070f12b3fc32 (wasm://wasm/0366db4a:wasm-function[3712]:0x787d76)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd0b5dfa4f8b00eef (wasm://wasm/0366db4a:wasm-function[11773]:0xa436c0)
    at closure5656 externref shim (wasm://wasm/0366db4a:wasm-function[12088]:0xa4ee9b)
    at E (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7b4e7a982553b1c826b2.js:1:3204)
    at f (https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.7b4e7a982553b1c826b2.js:1:2503)
```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: http://localhost/postrev/test.html
SWF URL: http://localhost/postrev/downloads/badger.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-17
Channel: nightly
Built: 2024-01-17T00:16:31.868Z
Commit: 6c420fa5d509b7428b7d00eebd13a2b0800fd0c0
Is extension: false

# Metadata

**Comment by Dinnerbone** [comment]
This is a limitation set by browsers, we cannot control it.

I thought we had a custom error message put in place to explain it... Huh.

https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-can-i-use-ruffle-with-local-html-files

**Comment by Dinnerbone** [comment]
Actually sorry maybe I misread. You're serving from a server already? Then your server may be misconfigured

**Comment by fabiomb** [comment]
the server is my own computer, localhost (127.0.0.1), it´s perfectly configurated: all in, no block permissions, no security, not even ssl.

in that easy scenario, it fails to load (the file exists and i can download it directly), but Ruffle can´t load it

I put the same file in my usual webserver and it works fine.

I don´t know if the problem is the lack of SSL certificate or the use of a local Apache and localhost url

**Comment by Dinnerbone** [comment]
If you go directly to http://localhost/postrev/downloads/badger.swf does it download the swf?

When loading the page http://localhost/postrev/test.html and opening your dev tools, what does the browser say for the swf in the Networking tab? How about Console tab?

**Comment by fabiomb** [comment]
yes, it exists but now i see, there´s a 403 error
that´s a forbidden, but why? Webassembly can´t access some files?
![image](https://github.com/ruffle-rs/ruffle/assets/1328787/6a6fbcf8-df11-4e74-a649-c3c63895e038)

it´s strange

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.1.17 Server at localhost Port 80</address>
</body></html>

the response, there´s no config at all at the apache webserver, it´s a default XAMPP instalation without any security

**Comment by Dinnerbone** [comment]
Impossible for us to say really, that's 100% an issue with your server. It's not allowing you to view the file for whatever the reason (maybe it doesn't exist, maybe it's blocking wasm files, maybe it doesn't want to serve them if javascript requested them) - could be anything, but it's not a problem with Ruffle or anything Ruffle can fix.
