### ISSUE TITLE
Movies with NG API and Loader that don't connect and finish

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1480]
Here's a list of some movies that all appear to have the same bug, where the NG API never connects to the gateway and the loader is stuck around 70%:

https://www.newgrounds.com/portal/view/577452/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/558219/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/567680/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/549389/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/579818/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/571318/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/600640/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/578083/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/553977/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/558929/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/552680/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/568456/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/575775/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/573649/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/572033/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/596131/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/554525/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/552744/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/557372/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/565142/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/569717/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/571817/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/578280/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/579972/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/586349/format/flash?emulate=flash

**Comment by Herschel** [comment]
These are all trying to do https->http loading. Forgot I had made a custom build for NG that swapped http->https! Closing in favor of #1486 for a general solution.
