### ISSUE TITLE
The Amazing Spider-Man Online Movie Game [Unrecognized file signature]

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#14819]
### Describe the bug

The game is loading ok, movie ad plays, it download level1.swf, and after that it is freezing and stops loading the rest of the files for the first level.

In console I see the following error at the start of the game:

`ERROR core/src/streams.rs:795 Unrecognized file signature: [0, 0, 0]`

### Expected behavior

The game should start level 1.

### Content Location

[Ruffle ](https://www.getgames.io/games/ruffle/?swf=marvel/spiderman/theamazingspiderman/2/main.swf&params=&name=The%20Amazing%20Spiderman%20Movie)| [Old browsers with Flash](https://www.numuki.com/game/spider-man-online-movie-game/)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

All the files from the game can be found on Flashpoint too.

**Comment by torokati44** [comment]
Those zeros _may_ be part of an AnnexB start code in an MP4 file/stream. Just a blind guess.

**Comment by n0samu** [comment]
@torokati44 Yes, the game uses an F4V asset for its video ad at the beginning. That and the console message mentioned are both irrelevant to whether the actual game works, though.

**Comment by n0samu** [comment]
@Stefannag There is something wrong with the copy of the game on your site. NuMuKi's copy of the game works fine in the Ruffle desktop app:
`ruffle https://media.numuki.com/spider-man/games/online-movie-game/main.swf --dummy-externalinterface`
But your site's copy doesn't work.
