### ISSUE TITLE
Preloader Option

### ISSUE THREAD

**Issue by JuanCaiza** [ruffle-rs/ruffle#14810]
Hey,
With this (avm2: Run most of Loader.loadBytes immediately) update, all loader screens we made for Ruffle are garbage. It was a nice option to have a loader screen for systems running on the web. I understand that you are trying to have the same features as flash, but you can get some features ahead of flash.
For example, for preloaders, you can at least enable a parameter to stay on the loader screen without loading the entire file.

**Comment by Lord-McSweeney** [comment]
Can you share an example, please?

**Comment by JuanCaiza** [comment]
Of course;
Swf link;
https://ptd.lol/ruffle/ptd2.swf

In the old version;
https://ptd.lol/ruffle/old.mp4

Old version link;
https://ptd.lol/ruffle/playold.php

In the new version;
https://ptd.lol/ruffle/new.mp4

New version link;
https://ptd.lol/ruffle/play.php

**Comment by Lord-McSweeney** [comment]
The loading screen does appear on Flash, right?

**Comment by n0samu** [comment]
It does, yes

**Comment by JuanCaiza** [comment]
No, no. Flash has a very short open time;

Flash video;
https://ptd.lol/ruffle/flash.mp4

**Comment by JuanCaiza** [comment]
any progress? @Lord-McSweeney @Aaron1011

**Comment by Aaron1011** [comment]
I didn't realize that flash player had a very similar behavior. Unfortunately, some SWF rely on the current behavior (the entire loadBytes swf preloading immediately).

I'll see how difficult it would be to add the option restoring the 'wrong' behavior.

**Comment by JuanCaiza** [comment]
@Aaron1011 'wrong' behavior? flash player loads instantly, waiting time is almost 0.
if you expect ruffle to be 100% the same as flash player everyone will keep using flash player because it's much more stable and faster.
Ruffle has to show that it is superior to flash player and add innovations.

Ruffle's waiting time is so long that you can see in the video that for a game of almost 10 MB you wait 30 seconds on a white screen and the browser gives a warning.

When users see the white page, they think there are too many errors and either change tabs, which prevents Ruffle from loading, or close the tab.

The solution is actually very simple: Either you allow preloading in swf files, like you used to, or you add the preloading screen as a feature of Ruffle itself.

**Comment by n0samu** [comment]
@JuanCaiza the latter is one of the very first planned features (#18), but still hasn't been implemented (yet!). And we are also working to speed up Ruffle's AVM2 interpreter, which will help this game's loading screen.

**Comment by JuanCaiza** [comment]
@n0samu Ruffle already has its own loader screen. I think it can be easily integrated.

**Comment by n0samu** [comment]
Streaming playback of SWFs is not as simple as it sounds!

**Comment by JuanCaiza** [comment]
Not streaming! I'm talking about taking Ruffle's own loader screen and integrating it into the swf loading screen.

Instead of waiting on a white screen, it would be much better to have at least a screen that shows what percentage of swfs are loaded. and it's not that hard to do! If I knew the Rust language, I would have done it myself by now for sure!

**Comment by n0samu** [comment]
You could write your own loading screen in JS and create/expose a JS function to hide the loading screen and show the game. Then call that function from your loader SWF using ExternalInterface once the loading is complete. That's my recommendation for now.

**Comment by JuanCaiza** [comment]
Is it possible to see with javascript how many percent Ruffle loads the swf?
This is not a solution. It doesn't even make sense.

**Comment by n0samu** [comment]
That wouldn't really help you because the real slowdown you're seeing is the AVM2 interpreter, not the download time. Anyway, I see that you deleted your comment providing the information needed to understand this issue, so it is now invalid. Thus I am closing it.

**Comment by torokati44** [comment]
Anyway, maybe https://github.com/ruffle-rs/ruffle/pull/8542 (and therefore  https://github.com/ruffle-rs/ruffle/issues/4091) was related...?
