### ISSUE TITLE
Mega-Hurtz - White Screen after clicking play

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1481]
https://www.newgrounds.com/portal/view/598926/format/flash?emulate=flash

This movie goes to a white screen after clicking the play button, nothing else happens.

These other examples may or may not be related - they all go to white screens after the play button.

https://www.newgrounds.com/portal/view/551818/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/552125/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/551739/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/610943/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/578793/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/582798/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/582396/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/591133/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/569914/format/flash?emulate=flash

**Comment by waspennator** [comment]
All of the animations listed seem to start up now, kinda hard to tell the visual accuracy between ruffle and flash considering they seem to crash the flash projector if I try loading one of these up in it, also can't tell if it's intentional that some skip the preloader or not after the white screen.

I had to test animation 582396 on internet archive (Clogged Tubes Episode 1) cause it was deleted off NG for some reason, but that seems to play normally as well.

**Comment by Lord-McSweeney** [comment]
https://www.newgrounds.com/portal/view/578793/format/flash?emulate=flash requires you to use the context menu and click "Play" to play the SWF, similar to many Flex applications.

There's a minor graphical issue in https://www.newgrounds.com/portal/view/578793/format/flash?emulate=flash where the text doesn't have an outline around it.

Apart from those, the rest of the animations play correctly.

Strangely, https://www.newgrounds.com/portal/view/591133/format/flash?emulate=flash uses Flex components and has the Flex loading screen where you normally have to click "Play" on the context menu, but this one doesn't require that. It starts up without user interaction after a few seconds waiting there.

**Comment by waspennator** [comment]
I retested "https://www.newgrounds.com/portal/view/578793/format/flash?emulate=flash" again to make sure and at least on my end, I did not need the context menu to play the SWF, it took around 5 seconds to transition from the white screen to the preloader, but the swf itself seems to work.

**Comment by Lord-McSweeney** [comment]
Fully fixed by #11878.
