### ISSUE TITLE
"Text field is cut off" in the Ruffle. The text field height in Flash player appears correctly.

### ISSUE THREAD

**Issue by sergo-zu** [ruffle-rs/ruffle#14824]
### Describe the bug

[cent-55.zip](https://github.com/ruffle-rs/ruffle/files/13978376/cent-55.zip)
![IMG_20240117_174034](https://github.com/ruffle-rs/ruffle/assets/138346697/00a786d6-f65f-44da-b5fb-3620b8e8c7bf)

### Expected behavior

The text field height have to appear in full size and show all lines. In Flash playerit appears correctly. In Ruffle it is cut off a lot of lines.

### Content Location

(https://github.com/ruffle-rs/ruffle/files/13978376/cent-55.zip)

### Affected platform

Self-hosted version

### Operating system

windows 7, windows 10

### Browser

Yandex, Google Chrome

**Comment by sergo-zu** [comment]
All files in zip.file (*. swf and *.fla sourses to see the original code and inspect the behavour in the standlone player.

**Comment by n0samu** [comment]
This happens because Ruffle's `getTextExtent()` function returns an incorrect value. Here is the relevant code in the Content movieclip:
```as
	var size_object:Object = style.getTextExtent(a12, 900); // MAKES THE TEXT FIELD _WIDTH AND _HEGHT
	pole._width=size_object.textFieldWidth; 
	pole._height=size_object.textFieldHeight;
```
The textFieldHeight value is too small in Ruffle, so the text field ends up cut off at the bottom.

**Comment by sergo-zu** [comment]
it can be fixed only for this case by muliplying the value. pole._height=size_object.textFieldHeight *2.5;
But nobody knows how this kind of cure will behave in other cases and other values of the textfield height .

**Comment by kjarosh** [comment]
I believe the text is now shown in full. However, there are issues related to the scroll (scrolling through empty space) and the text field with variables not showing
