### ISSUE TITLE
The Mighty B! Mighty Dreams [Error dispatching event EventObject]

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#14836]
### Describe the bug

Ruffle will throw the following error: 

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "fileFinishedEvent", class: net.hitf.core.load.events::FileFinishedEvent, ptr: 0xd45208 }) to handler FunctionObject(FunctionObject { ptr: 0xc998a0, name: Ok("net.hitf.nic.mightydreams::Main/onFileFinished()") }) : RustError("VerifyError: Trait id3 in class net.hitf.core.sound.music::MusicTrack marked as override, does not override any other trait")`

### Expected behavior

Load all the files.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=nick/MightyB/mightydreams/2/main.swf&params=&name=The%20Mighty%20B!%20Mighty%20Dreams)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

I couldn't find a page with the actual flash game, just the emulated one with Ruffle.

**Comment by Lord-McSweeney** [comment]
This needs `Sound.id3`

**Comment by evilpie** [comment]
`Sound.id3` was implemented in #14916. Now the game hangs at 33% with no obvious error.

**Comment by Lord-McSweeney** [comment]
The game is now playable.
