### ISSUE TITLE
Ruffle Web - Click right doesn't appear where cursor is 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1484]
Hi, 

The new click right function where it shows you about ruffle doesn't appear where someone clicks right. If I click right just under where it says fast lane it appears at the bottom of the page. 

Running on 4th Novembers code. 

https://ridesims.com/ride-simulators/Vampire 

<img width="1126" alt="Screenshot 2020-11-04 at 10 10 38" src="https://user-images.githubusercontent.com/10291664/98098887-d43ab400-1e86-11eb-8d5d-5d356761dd88.png">

**Comment by Dinnerbone** [comment]
I'm sure I fixed this two days ago, and I tested on your site to confirm. Absolutely sure it's the nightly from this morning?

**Comment by Toad06** [comment]
It seems it works as expected if the document hasn't been scrolled vertically, otherwise the issue happens.

**Comment by JamesAllgood** [comment]
Yep its last nights code because the sound bug you fixed works now
