### ISSUE TITLE
TLF regression in MLP game on latest nightly build

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#14922]
### Describe the bug

Text boxes no longer works, last stable nightly for Gotta Catch em All one more time was 2024_01_23

### Expected behavior

Everything should work correctly

### Content Location

[Gotta.Catch.em.All.one.more.time.zip](https://github.com/ruffle-rs/ruffle/files/14031259/Gotta.Catch.em.All.one.more.time.zip)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

**Comment by evilpie** [comment]
Text boxes should appear when hovering over the characters.

Regressed by https://github.com/ruffle-rs/ruffle/commit/e014d7c023db5085e57e0d784dafdd961ef0ea80. @moulins
