### ISSUE TITLE
5 Shades of Orange - Menu Buttons don't work

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1493]
https://www.newgrounds.com/portal/view/530603/format/flash?emulate=flash

The menu buttons have rollover responses but don't play anything when you click them.

**Comment by n0samu** [comment]
The buttons are working now! Though the rollover responses have become a bit glitchy for some reason.

**Comment by Lord-McSweeney** [comment]
Possibly fixed by #9146.
