### ISSUE TITLE
Hallo...what - White screen after Ruffle Play

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1494]
https://www.newgrounds.com/portal/view/552125/format/flash?emulate=flash

After clicking the Ruffle play button, the screen goes white and it never gets to the movies loading screen.

**Comment by waspennator** [comment]
Testing on my end, seems like it loads up to the movie in question after a second or so. Can't really compare how it's supposed to act on flash since it crashes the flash projector tryin to test out this swf.
