### ISSUE TITLE
web: display_file_save_dialog is non-functional

### ISSUE THREAD

**Issue by Victo-2350703** [ruffle-rs/ruffle#14949]
# Error Info
Error name: Error
Error message: panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.13.0/src/file_handle/web.rs:55:17:
This File Handle doesn't support reading. Use `pick_file` to get a readable FileHandle
Error stack:
```
339/z/n.wbg.__wbg_new_3a66822ed076951c@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:70044
core::ops::function::FnOnce::call_once{{vtable.shim}}::h61e7c84c3ecc6317@:wasm-function[11302]:0xa78281
std::panicking::rust_panic_with_hook::h62090d3fc0630473@:wasm-function[6906]:0x938fe6
core::panicking::panic_fmt::hd79411a297d06dc8@:wasm-function[11024]:0xa719de
rfd::file_handle::web::FileHandle::read::{{closure}}::{{closure}}::h1e64924434865afa@:wasm-function[5393]:0x8a4d00
wasm_bindgen::convert::closures::invoke2_mut::h1cbe87ffa8499fd4@:wasm-function[12247]:0xa961e0
closure9655 externref shim@:wasm-function[12251]:0xa96271
339/z/n.wbg.__wbg_new_1d93771b84541aa5/t</<@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:71434
339/z/n.wbg.__wbg_new_1d93771b84541aa5/t<@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:71470
339/z/n.wbg.__wbg_new_1d93771b84541aa5@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:71364
js_sys::Promise::new::h0dd111e06e5da0e5@:wasm-function[13654]:0xaccfca
ruffle_web::ui::WebFileDialogResult::new::{{closure}}::h00e737636dad6760@:wasm-function[3672]:0x76aeb8
<ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_file_save_dialog::{{closure}}::hd8c1a27a1adb6579@:wasm-function[2476]:0x630240
ruffle_core::loader::Loader::file_save_dialog_loader::{{closure}}::h73621b6ebfb502e1@:wasm-function[2814]:0x697bc3
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h780e14a2797d204b@:wasm-function[1438]:0x44ed59
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb2787988f9230ff5@:wasm-function[3935]:0x7a9a8c
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8f9281141bc1db13@:wasm-function[12299]:0xa96863
closure8479 externref shim@:wasm-function[12616]:0xaa24af
P@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:3258
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.2e2fb3ce7210bdd35fc9.js:1:2503

```

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(FLOAT32_FILTERABLE | TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 400, 1)

# Page Info
Page URL: https://w8.snokido.com/games/flash/ruffle.html?g=strike-force-heroes-2&v=231027
SWF URL: https://w8.snokido.com/games/flash/strike-force-heroes-2.swf?161123

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-25
Channel: nightly
Built: 2024-01-25T00:15:18.655Z
Commit: 917c1c08f73b68d6ab7c48736060960b095d4b75
Is extension: false

# Metadata
width: 800
height: 600
frameRate: 30
numFrames: 25
swfVersion: 15
backgroundColor: #999999
isActionScript3: true
uncompressedLength: 16361371

**Comment by evilpie** [comment]
Turns out `display_file_save_dialog` in the web backend is just totally non-functional. We try to read from a FileDialog that is meant for saving, which rfd doesn't support with wasm. Furthermore even after bypassing this, we never actually write anything!

**Comment by evilpie** [comment]
#7596 (breaks AVM1 FileReference::download) and #14157 (breaks AVM2 FileReference::save)

**Comment by BarbourSmith** [comment]
I just want to voice a +1 for supporting this bug. We're working to revive this awesome open source CAD/CAM program which lets you take .svg files and convert them to gcode for CNC routers (big robots) to cut out of wood.

<img width="1512" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/81d9081d-97fc-4173-aaeb-00f3be451205">

Generally the software to do this kind of thing is expensive and not easy to use, so bringing back to life a simple online version would be a big deal for our community. It's currently working in every way except for the last step where you download the generated file 😀

Let me know if there is anything that I can do to get anyone excited about working on this bug
