### ISSUE TITLE
BTD5 Does not start new rounds

### ISSUE THREAD

**Issue by MathMan05** [ruffle-rs/ruffle#14970]
### Describe the bug

BTD5 does not start the second round plus, it instead just continues the first round indefinatly. Using this URL [http://assets.ninjakiwi.com/Games/gameswfs/btd5-dat.swf?v=20190114](http://assets.ninjakiwi.com/Games/gameswfs/btd5-dat.swf?v=20190114) 

### Expected behavior

Second round

### Content Location

http://assets.ninjakiwi.com/Games/gameswfs/btd5-dat.swf?v=20190114

### Affected platform

Desktop app

### Operating system

Arch Linux ruffel-bin-nightly

**Comment by Lord-McSweeney** [comment]
This is #14947, there's an error about reading a field `flavorText` off `undefined`
