### ISSUE TITLE
Play button escapes the game canvas in portrait-oriented windows or phones

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1497]
[Link to image because GitHub displays screenshots of portrait phones weirdly](https://user-images.githubusercontent.com/58399748/98262880-1e3d9b80-1f54-11eb-8970-d87d6ee57af4.jpg)

The play button should really be scaling itself based on the width and height of the canvas instead of relying on offsets.

**Comment by n0samu** [comment]
Seems like this was fixed a long time ago
