### ISSUE TITLE
TextFields mouse control for text select

### ISSUE THREAD

**Issue by ReFaller** [ruffle-rs/ruffle#14996]
### Describe the bug

You can't select text with the mouse in text fields (for Input text fields and for Dynamic text fields), selection works only for the keyboard (Shift + Left/Right key buttons). Also, no useful features exist, such as double-clicking to select a word between space delimiters (available in Flash Player).
![image](https://github.com/ruffle-rs/ruffle/assets/39001461/afeb08de-be3a-4f6e-be0d-40113eef2826)

### Expected behavior

You should be able to highlight text by holding down the mouse anywhere and double clicks for worlds should work too for selecting it.

### Content Location

[test.zip](https://github.com/ruffle-rs/ruffle/files/14086781/test.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by ReFaller** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/39001461/e5319970-b75d-4937-8d22-e1f6f543370b)

**Comment by waspennator** [comment]
I was able to highlight text using the mouse as of build 5/27/24, however it seems that double clicking to highlight text only works on flash still.
