### ISSUE TITLE
`flash.utils.Timer` not handling setting the `delay` properly

### ISSUE THREAD

**Issue by MarcinZukowski** [ruffle-rs/ruffle#15005]
### Describe the bug

Seems the Timer class is not properly handling setting the `delay` property while it's running, in particular during the event handler.

Here's a simple repro

```
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.utils.Timer;
	import flash.events.TimerEvent;
	
	public class Main extends Sprite 
	{
		private var timer:Timer;
		private var cnt:int = 0;
		
		public function Main() 
		{
			if (stage) init();
			else addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function timerEvent(e:TimerEvent):void
		{
			cnt++;
			trace("timerEvent", cnt);
			timer.delay = 500;         //  <<< Problem
		}

		private function timerComplete(e:TimerEvent):void
		{
			trace("timerComplete", cnt);
		}

		private function init(e:Event = null):void 
		{
			removeEventListener(Event.ADDED_TO_STAGE, init);

			// entry point
			trace("Starting");
			
			timer = new Timer(500, 3);
			timer.addEventListener(TimerEvent.TIMER, timerEvent);
			timer.addEventListener(TimerEvent.TIMER_COMPLETE, timerComplete);
			timer.start();
		}		
	}
}
```

In the FlashPlayer, this produces the expected sequence:
```
Starting
timerEvent 1
timerEvent 2
timerEvent 3
timerComplete 3
```

However, in Ruffle it generates this:
```
Starting
timerEvent 1
timerEvent 2
timerEvent 3
timerComplete 3
timerEvent 4
timerComplete 4
```

Note, if I don't set the `delay` in the code, everything works as expected.

I tried to debug it, and it seems it's related to the fact that `Timer::set delay` is actually running a `stop/start` sequence, which results in a new id assigned to Timer (through `timers.addTimer`), and that confuses the logic inside `update_timers` (`expected_id` is different). Or so I think 😄  I'm new to Ruffle so this is just based on some trace-based debugging.

### Expected behavior

The timer completion should be properly handled

### Content Location

Repro attached

### Affected platform

Desktop app

### Operating system

MacOS

**Comment by lvyitian** [comment]
Probably related: https://github.com/ruffle-rs/ruffle/pull/14352/commits/aa3175037a3425188e89db97895b337172a5a8f7

**Comment by torokati44** [comment]
Ooh, good catch! Thanks for the investigation and the test case! Will try to look into it in the next couple days...

**Comment by torokati44** [comment]
Actually I think the issue here manifested as the "_repeatCount" being reset to 0 when the timer was re-added as if it was new, with the new ID and `delay`.
Anyway, randomly changing the ID of a timer surely also caused a lot more issues here and there.

**Comment by torokati44** [comment]
> Probably related: https://github.com/ruffle-rs/ruffle/commit/aa3175037a3425188e89db97895b337172a5a8f7

Thankfully this didn't regress with the mentioned commit, it was like this even before that.

**Comment by MarcinZukowski** [comment]
Thank you for fixing this. 
I'm happy to report that the app which manifested the error seems to be working fine now!
