### ISSUE TITLE
Missed context menu for selected text in the text fields (copy/past/select all)

### ISSUE THREAD

**Issue by ReFaller** [ruffle-rs/ruffle#15000]
### Describe the bug

![context](https://github.com/ruffle-rs/ruffle/assets/39001461/daba7438-0e7e-4473-8f86-87253b6b50a6)

### Expected behavior

By default, it was set to the right mouse button.

### Content Location

[test.zip](https://github.com/ruffle-rs/ruffle/files/14087180/test.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/16622
