### ISSUE TITLE
Cannot access a property or method of a null object reference. (accessing field: toLowerCase)

### ISSUE THREAD

**Issue by BarbourSmith** [ruffle-rs/ruffle#15045]
### Describe the bug

I am excited to see the AV3 file loading is working! 

I am trying to revive a flash based 2D modeling program, but when I go to open a file I encounter the error message:

`ruffle_web-wasm_extensions-8sjk2hps.js:2 ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x4254048 }) to handler FunctionObject(FunctionObject { ptr: 0x424d120, name: Ok("com.partkart::SVGLoader/onLoadComplete()") }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: toLowerCase)`

To replicate the issue click `File -> Open SVG File`

<img width="1054" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/7feb3b11-6032-487c-a6d8-e579a54680db">

And select the included .svg file (or any .svg file really)

<img width="381" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/090bef85-60fa-4eef-a29d-cae0d5f2c506">

### Expected behavior

I would expect the .svg file to be opened and display in the window

### Content Location

[File loading issue.zip](https://github.com/ruffle-rs/ruffle/files/14116536/File.loading.issue.zip)

### Affected platform

Online demo

### Operating system

MacOS Sonoma

### Browser

Chrome and Firefox tested

**Comment by evilpie** [comment]
So this SWF has code like:
```
         XML.ignoreWhitespace = false;
         this.svg = new XML(this.fr.data);
         XML.ignoreWhitespace = true;
```

If we just ignore what `ignoreWhitespace` says and force `ignore_white` to true in `E4XNode::parse`, the parsing succeeds. Obviously that isn't really correct. My theory right now is that for some reason Flash is reparsing the XML after the initial parse?

**Comment by Lord-McSweeney** [comment]
I can't check right now but is it possible that this was regressed by #13106?

**Comment by Aaron1011** [comment]
Calling `Xml.copy()` actually looks at some of the XML settings:

https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/E4XNode.cpp#L713-L716

**Comment by evilpie** [comment]
I tried to extract only the relevant code from the original SWF and create my own smaller SWF. But doing that actually triggers the same issue in flashplayerdebugger?! I am a bit stumped.

**Comment by BarbourSmith** [comment]
Tricky!

**Comment by BarbourSmith** [comment]
Is there anything that I can do to encourage someone to investigate this issue further? A bug bounty?

**Comment by adrian17** [comment]
Hey, there's an early attempt at fixing this in https://github.com/ruffle-rs/ruffle/pull/15846 .

**Comment by BarbourSmith** [comment]
If it works the bounty offer is still standing! 🤞 I'm holding out hope!

**Comment by BarbourSmith** [comment]
I gave it a test and it works beautifully! How do I pay up?

**Comment by BarbourSmith** [comment]
Despite the helpful link I still somehow messed up adding the note...I'm sorry! 

<img width="278" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/2bf41241-eab1-43b6-bdd1-c04b8a5b240f">
