### ISSUE TITLE
[web] Error in load-ruffle.js on bootstrap

### ISSUE THREAD

**Issue by NotWearingPants** [ruffle-rs/ruffle#1504]
I followed the web build instructions - ran `npm run bootstrap`
It failed when running webpack:
```
ERROR in ./src/load-ruffle.js 29:30-59
Module not found: Error: Can't resolve '../../../pkg/ruffle' in 'C:\git\ruffle\web\packages\core\src'
```
It seems to look for a `pkg` directory under `web`, but mine was under `core`.
So I changed this line:
https://github.com/ruffle-rs/ruffle/blob/dab79107b2948f2312a7eb8b5d7cd6342b551467/web/packages/core/src/load-ruffle.js#L29
to have just `../pkg/ruffle`, and it fixed the error.

But for some reason this `ruffle.js` file in there is completely empty, so I got an error in runtime.
Something is wrong here with the packaging, and I really don't understand your setup enough to fix it.

This seems to be similar to #122 but the structure of the project has changed since.

**Comment by n0samu** [comment]
Project structure changed again and I don't think this issue applies anymore.
