### ISSUE TITLE
Extension debug build eval error when loaded unpacked

### ISSUE THREAD

**Issue by wsxarcher** [ruffle-rs/ruffle#15064]
The extension compiled with `npm run build:debug`, and loaded as unpacked extension in developer mode fails to do anything in the popup or the settings giving:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Context

extension://lecnpjmonjilblobmocglkbflfmggpdc/popup.html
```

The error is visible both in the extensions error page or in the inspector while the ruffle settings are open.

Browser:
Edge/Chrome 121

**Comment by riku-42** [comment]
Adding `devtool: 'source-map'` in the webpack config should solve the issue.
