### ISSUE TITLE
Guardicalogia now displays a set of alphabet letters

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#15068]
### Describe the bug

![image](https://github.com/ruffle-rs/ruffle/assets/38821724/2f00cc61-59ba-4338-bb9a-7ab4874e0181)

after bisecting commits, i found the problem in commit 2e0e7aec5c7c492a5641b6da21bb58cafaa2b17c 

wgpu: Remove the readback-upgrade path. It's now slower than normal drawing

 render/wgpu/src/backend.rs | 101 +++++++++++----------------------------------
 1 file changed, 25 insertions(+), 76 deletions(-)

### Expected behavior

![image](https://github.com/ruffle-rs/ruffle/assets/38821724/628b697e-c24e-42b1-9d71-9063c5ddee66)

### Content Location

[Guardicalogia_r4.zip](https://github.com/ruffle-rs/ruffle/files/14135213/Guardicalogia_r4.zip)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

**Comment by torokati44** [comment]
gasp, @Dinnerbone !
