### ISSUE TITLE
NYT 2008 Election Results: "Something went wrong :(" error

### ISSUE THREAD

**Issue by albertsun** [ruffle-rs/ruffle#1507]
Testing this page: https://www.nytimes.com/elections/2008/results/president/map.html
Version: 11/6 nightly Chrome extension.

![Screen Shot 2020-11-06 at 10 59 37 AM](https://user-images.githubusercontent.com/382862/98387445-6249a280-201f-11eb-9fb7-068ae4e60fd4.png)

Error info is pasted below.

```
# Error Info
Error name: TypeError
Error message: ai[e] is not a function
Error stack:
```
TypeError: ai[e] is not a function
    at Function.di (chrome-extension://nigohgchpleckkhljmjlpoekemlmekjg/dist/ruffle.js:1:26732)
    at https://static01.nyt.com/packages/js/elections/2008/results/nytint/lib/prototype-compressed.js:1:3410
    at async chrome-extension://nigohgchpleckkhljmjlpoekemlmekjg/dist/ruffle.js:1:1349
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.nytimes.com/elections/2008/results/president/map.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
OS: MacIntel

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

```

🙏

**Comment by Toad06** [comment]
Interesting, there's no crash in nightly builds <= 2020-10-16 (though the file itself still doesn't work - uses AS3).

**Comment by albertsun** [comment]
Ah, interesting. Is there an easy way to tell if a file is AS3 so I can skip over filing issues on things that would be known to not work?

**Comment by Toad06** [comment]
In the browser's console, you would get this warning:
`This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended.`
(it's very likely that you would also get other errors, eg. `Got AVM2 error [...]`)

**Comment by Toad06** [comment]
The page is using the same JS library (https://static01.nyt.com/packages/js/elections/2008/results/nytint/lib/prototype-compressed.js - though this one is minified) as https://github.com/ruffle-rs/ruffle/issues/1630#issuecomment-731592794.
Blocking this file allows Ruffle to start.
