### ISSUE TITLE
GemCraft Labyrinth fails to start

### ISSUE THREAD

**Issue by emorozov** [ruffle-rs/ruffle#15074]
### Describe what you were doing

Downloaded gemcraft labyrinth from the https://gameinabottle.com/ website.
Installed ruffle-bin-2024.01.22-1 from Arch AUR (ruffle-bin package)
Started using `ruffle gcl-gs.swf` command which immediately crashed.

### What does the crash message say?

panicked at /home/corey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.0/src/instance.rs:521:39:
called `Option::unwrap()` on a `None` value

### Ruffle Version

0.1.0-nightly (205741782495274bce600434ee79284ee79f5f06 2024-01-22)

### Affected platform

Desktop app

### Operating system

Arch Linux [64-bit]

**Comment by emorozov** [comment]
Note: started when started with option `-g gl`.

**Comment by rafrafek** [comment]
Hi,

Were you able to save and load the game save in GemCraft Labyrinth when playing on Arch Linux? It doesn't work for me on Windows/Mac/Web so maybe I should switch to Linux?
