### ISSUE TITLE
createEmptyMovieClip overrides existing MovieClip with the same depth

### ISSUE THREAD

**Issue by relrelb** [ruffle-rs/ruffle#1509]
In [Free Rider 2](http://www.onemorelevel.com/games3/freerider2x.swf), the bike and player disappear when hit.
After digging into this, I think I found the root cause of the problem:
```js
class vehicle {
    ...
    function vehicle() {
        this.mymc = _root.createEmptyMovieClip("vehiclemc", 3);
        ...
    }
    ...
}
```
```js
class bmx extends vehicle {
    function bmx() {
        super();
        ...
    }
    ...
    function createRagDoll() {
        _root.gui.message("Ouch! [Press Enter]",16764108);
        ...
        _root.player = new splitBike(this,this.getStick());
    }
    ...
}
```
```js
class ragdoll extends vehicle {
    function ragdoll(pStick, pmc) {
        super();
        this.mymc = pmc;
        ...
    }
    ...
}
```
At the beginning, a new `bmx` is created. When hit, `bmx.createRagDoll` is called, which in turn creates a new `ragdoll` (during the creation of a new `splitBike`).
Since both `bmx` and `ragdoll` inherit from `vehicle`, the call to `_root.createEmptyMovieClip("vehiclemc", 3)` occurs multiple times.
The second call removes the `MovieClip` of `bmx`, just because a new `MovieClip` is created with the same depth.
The removal happens in [`add_child_from_avm`](https://github.com/ruffle-rs/ruffle/blob/1a230bda09848ed0ce93b78cd8ca6c1fe81e9cac/core/src/display_object/movie_clip.rs#L953).

The inherent problem here is that `MovieClip`s store their children in a `BTreeMap` indexed by their depth, so children with the same depth cannot co-exist.
I tried to convert the `BTreeMap` to a simple `Vec`, but it was just too much to rewrite.

**Comment by Herschel** [comment]
Not sure what's going on in this specific case, (I'll have to take a look) but in general creating a movie on an already occupied depth removes the previous clip. A simple example:

```
var mc = createEmptyMovieClip("mc", 0);
mc.lineStyle(3, 0);
mc.lineTo(100, 100);

// mc2 is placed on the same depth as mc, so mc is destroyed
var mc2 = createEmptyMovieClip("mc2", 0);
mc2.lineStyle(3, 0xff0000);
mc2.lineTo(100, 200);
// Only mc2 is visible
```

**Comment by Herschel** [comment]
Seems like this is a case of the original reference `mymc` auto-updating to the newly created clip. The clip does indeed get recreated when it uses the same depth, but since it uses the same path `_root.vehiclemc`, the `mymc` reference automatically points to the new clip. Closing in favor of #1513.
