### ISSUE TITLE
Dragging Doesn't work

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1511]
I have attached a file to test. A short education game. The first question requires you to drag to answer. However, dragging doesn't work when used with Ruffle.

[perim-bots (1).swf.zip](https://github.com/ruffle-rs/ruffle/files/5503908/perim-bots.1.swf.zip)

**Comment by sombraguerrero** [comment]
There are a few other tickets like this, and because it probably has to do with the DragEvent and its handlers, it's probably an AS3 thing, but here's another example.
[zookeeper2.zip](https://github.com/ruffle-rs/ruffle/files/5505811/zookeeper2.zip)
