### ISSUE TITLE
Pressing Enter Key Doesn't Work

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1512]
Everything works. However, when you press Enter after typing name. It doesn't take any input while loaded with Ruffle.
[Protractor_Set_01.swf.zip](https://github.com/ruffle-rs/ruffle/files/5503954/Protractor_Set_01.swf.zip)

**Comment by mzeo** [comment]
Same problem with dontshityourpants.swf (http://swfchan.com/10/49302/?dontshityourpants.swf)

**Comment by Herschel** [comment]
This is all working now (probably needed `Key.getAscii`). Please re-open if not the case.
