### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/avatar-katara-rape/

### ISSUE THREAD

**Issue by jlind351** [ruffle-rs/ruffle#15149]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Response body loading was aborted
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Response body loading was aborted
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/meet-and-fuck-hentai-games/avatar-katara-rape/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by Lord-McSweeney** [comment]
This was probably a transient network error
