### ISSUE TITLE
Madness Accelerant regression: Red glowing trail around Tricky is missing

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#15146]
### Describe the bug

In Madness Accelerant, if you start a new game and shoot Tricky at the hot dog stand, he falls down a pit and re-emerges as a giant red monster. This monster has a code-generated red glowing trail that previously worked in Ruffle but is not working at the moment. I haven't tested this game in a while so I'm not sure when the regression happened.

### Expected behavior

Tricky should have a red glowing trail as he moves around.

### Content Location

https://www.newgrounds.com/portal/view/512407

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome 121.0.6167.140

**Comment by waspennator** [comment]
Still occurring as of latest nightly I believe. I did some testing on my end and it seems like the last build the glowing appeared was on 2024-02-01, on all builds past that it seems to be gone.

Providing visuals to demonstrate, first picture is from versions 2024-02-01 and before.

![Screenshot 2024-06-29 001250](https://github.com/ruffle-rs/ruffle/assets/78768499/abc4fa78-f67b-4397-8c98-782a3cb7118e)


This is starting from around 2024-02-02 and current.
![Screenshot 2024-06-29 001130](https://github.com/ruffle-rs/ruffle/assets/78768499/497e2f2d-9dbf-4897-915e-30a2325ace0f)

**Comment by torokati44** [comment]
Regressed by https://github.com/ruffle-rs/ruffle/commit/2e0e7aec5c7c492a5641b6da21bb58cafaa2b17c, which was part of https://github.com/ruffle-rs/ruffle/pull/15032 (@Dinnerbone).

**Comment by waspennator** [comment]
Still a problem as of latest nightly.

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/19066
