### ISSUE TITLE
Ruffle immediately disconnects from game server

### ISSUE THREAD

**Issue by ThePizza1k** [ruffle-rs/ruffle#15152]
### Describe the bug

Upon logging in to Platform Racing 3 (or playing as guest), the player customization screen briefly shows before dropping the connection.

### Expected behavior

The main menu of the game remains open, and you remain connected to the server.

### Content Location

https://pr3hub.com/files//preloader/game_preloader_30.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Also occurs on windows 11.

**Comment by Lord-McSweeney** [comment]
Analyzing a Wireshark dump, I can see that first the client sends this data to the server:
`{"t":"guest_login"}`

Then this:
`{"type":"confirm_connection"}`

Then the server sends a large blob of data back, starting with
`{"socketID":3150,"userID":0,"userName":"Guest_594439","permissions":[],"vars":{"guest"`...
                  
To which the client replies with
`{"t":"mv","action":"get","id":"0","user_vars":["rank","hatArray","headArray","bodyArray","feetArray","exp"],"location":"user"}`

(note that there's a small binary chunk before every JSON sent)

To which the server sends a tiny bit of data back. This is the raw TCP payload, in hexadecimal:
`00 02 00 2c`

Then the client replies with another tiny bit of data:
`00 06 00 21 00 00 01 9b`

Then the server disconnects.

**Comment by ThePizza1k** [comment]
This is fixed now
