### ISSUE TITLE
some doswf encrypted swf doesn't work now

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#15181]
### Describe the bug

![1](https://github.com/ruffle-rs/ruffle/assets/98996990/24efaca0-7dc5-40f9-a90e-7a75d8f0132a)

### Expected behavior

![2](https://github.com/ruffle-rs/ruffle/assets/98996990/3a0aceac-cd8a-40cf-b36a-c0efb75155c8)

### Content Location

[最强大脑.zip](https://github.com/ruffle-rs/ruffle/files/14227585/default.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
`VerifyError: Error #1011: Method contained illegal opcode.`
