### ISSUE TITLE
TEXT DISAPPEARED ON THE WARNER BROS. WEBSITE!

### ISSUE THREAD

**Issue by tj60466** [ruffle-rs/ruffle#15197]
I was using the Wayback Machine on Google Chrome on Windows to go to http://www2.warnerbros.com/main/company_info/company_info.html. But then, there are no words. Each section of the company's info I clicked on, it doesn't show the whole details about the entire Studio. Can u please help me NOW?

![Screenshot 2024-02-12 034632](https://github.com/ruffle-rs/ruffle/assets/159768178/922a8b5e-bfc7-4fc8-9998-81a31fc26b3e)

**Comment by danielhjacobs** [comment]
This isn't working on a Flash-enabled browser either. It relies on the URL https://web.archive.org/web/main/xml_variables/companyinfo_variables.jsp, which was unable to be properly archived and so doesn't work on the Wayback Machine.

**Comment by tj60466** [comment]
> This isn't working on a Flash-enabled browser either. It relies on the URL https://web.archive.org/web/20040924010408/http://www2.warnerbros.com/main/xml_variables/companyinfo_variables.jsp, which was unable to be properly archived and so doesn't work on the Wayback Machine.

What browser?
And who do u work 4?

**Comment by danielhjacobs** [comment]
If you're on Windows, you can use https://archive.org/details/basilisk-portable-with-flash.

Personally, I tested with Pale Moon with Adobe Flash installed.

**Comment by tj60466** [comment]
> If you're on Windows, you can use https://archive.org/details/basilisk-portable-with-flash.
> 
> Personally, I tested with Pale Moon with Adobe Flash installed.

I tried Basilisk, but it's still not showing me the entire text on the Warner Bros. Company website.

**Comment by tj60466** [comment]
Can u just contact the authorities who work 4 ruffle?

**Comment by danielhjacobs** [comment]
Like I said, this media was never archived. It's lost media and cannot work. That's why Basilisk is not working either even though it uses Adobe Flash.

**Comment by danielhjacobs** [comment]
Also, there are no "authorities who work 4 ruffle". This is an open source project with volunteer contributors. You could work on Ruffle too if you wanted to do so.

**Comment by danielhjacobs** [comment]
Let me try to explain. The Wayback Machine archives webpages and the media on those webpages, but sometimes media is not archived even though the webpages themselves are archived. The simplest example of that is images. When images are not archived they will not be able to be displayed on archived webpages.

This is another example of that. The webpage and a container for the text content on the Warner Bros website were both archived, but there was external media containing the text content which was never archived, so no text can be displayed within the container.

It's an issue with the content, not with Ruffle.
