### ISSUE TITLE
External Interface callback is missing arguments

### ISSUE THREAD

**Issue by teampanfu** [ruffle-rs/ruffle#15221]
### Describe the bug

The following error occurs when you call an external interface callback with an object as an argument:

```
Unhandled error in External Interface callback purchaseItem: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: itemId)
```

JavaScript:

```js
document.getElementById('flash-container').purchaseItem({
    itemId: id,
    itemHash: hash
});
```

AS3:

```as3
ExternalInterface.addCallback("purchaseItem", onPurchaseItem);

private function onPurchaseItem(tEvent: Object): void
{
    sendNotification(AppConsts.PURCHASE_ITEM, {
        id: tEvent.itemId,
        hash: tEvent.itemHash
    });
}
```

### Expected behavior

The object should be passed along to the external interface callback.

### Content Location

The bug can be reproduced on [our website](https://www.panfu.us) by clicking on the catalog at the top, then going to the last catalog in the dropdown and buying something from there.

An account and completion of the tutorial are required.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 121

**Comment by Lord-McSweeney** [comment]
We haven't implemented JavaScript-ActionScript object transfer yet
