### ISSUE TITLE
Usage in react

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [ruffle-rs/ruffle#15264]
### Describe the bug

```ts
<RufflePlayer address='./assets/zombie3.swf'/>
```

```ts
import React, { useEffect, useRef } from "react";

interface RufflePlayerProps {
	address: string;
}

export default function RufflePlayer(props: RufflePlayerProps) {
	const { address } = props;
	const ref = useRef<HTMLDivElement>(null);
	useEffect(()=>{
		// @ts-ignore
		const ruffle = window.RufflePlayer.newest();
		const player = ruffle.createPlayer();
		player.load(address);
		ref.current!.appendChild(player);
	},[])

	return (
		<div ref={ref} >
			
		</div>
	)
}
```

![image](https://github.com/ruffle-rs/ruffle/assets/60914359/6cbc9eca-6bfc-462c-93b7-abe0dcd42dbd)

### Expected behavior

Show flash correctly.

### Content Location

Not related to specific flash file.

### Affected platform

Self-hosted version

### Operating system

windows 10

### Browser

chrome

**Comment by S-N-O-R-L-A-X** [comment]
BTW, Any update on this comment? https://github.com/ruffle-rs/ruffle/issues/3952#issuecomment-817652664
I have installed `"@ruffle-rs/ruffle": "^0.1.0-nightly.2024.2.13",` but I don't know how to use this.

**Comment by Lord-McSweeney** [comment]
Are you sure the player element is attached to the document in some way? That's the usual cause of that message.

**Comment by S-N-O-R-L-A-X** [comment]
@Lord-McSweeney  I think it is in the document. 
![image](https://github.com/ruffle-rs/ruffle/assets/60914359/034b9bd6-61e6-43bb-adfb-dea6c944326d)

**Comment by S-N-O-R-L-A-X** [comment]
Thanks to @adrian17 
This works. 

```ts
import React, { useEffect, useRef } from "react";

interface RufflePlayerProps {
	address: string;
}

export default function RufflePlayer(props: RufflePlayerProps) {
	const { address } = props;
	const ref = useRef<HTMLDivElement>(null);
	useEffect(()=>{
		// @ts-ignore
		const ruffle = window.RufflePlayer.newest();
		const player = ruffle.createPlayer();
		ref.current!.appendChild(player);
		player.load(address);
	},[])

	return (
		<div ref={ref} >
			
		</div>
	)
}
```
