### ISSUE TITLE
Snailiad - Play button on preloader no longer goes to the title screen menu.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#15285]
### Describe the bug

In previous Ruffle builds, on the Snailiad preloader screen you could click PLAY and advance to the NG sponsor logo and then the title screen.

In the current build, when you click PLAY, the preloader box vanishes and a new tab opens with the NG games page. It appears that the NG sponsor link that follows the preloader is getting activated and it's never getting to the part where it plays the intro or advances to the title screen.

### Expected behavior

On the Snailiad preloader screen, clicking PLAY should advance to the NG sponsor logo and then the title screen.

### Content Location

https://www.newgrounds.com/portal/view/573352/format/flash?emulate=flash

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Google Chrome 121.0.6167.184

**Comment by adrian17** [comment]
Small observation: if I click the button before the ad rectangle shows up, the game still starts.
That said, I can't reproduce it working on earlier versions of Ruffle yet :(

**Comment by Lord-McSweeney** [comment]
> That said, if the ad rectangle shows up, I can't reproduce it working on earlier versions of Ruffle yet :(
I remember this being quite janky to test- @TomFulp can you try to reproduce it working on an earlier version of Ruffle?
