### ISSUE TITLE
Tom and Jerry: Rig-a-Bridge: Black screen issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#15329]
### Describe the bug

Game gets stuck on a black screen playing music when getting into gameplay, just click play, next, and you'll see it happen.

### Expected behavior

The game shouldn't go all black.

### Content Location

https://ooooooooo.ooo/static/?9b8a52a9-5f48-5991-23cb-8324d4a9288d

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 122

**Comment by Aaron1011** [comment]
This needs the correct API versioning applied to `rotationZ`

**Comment by waspennator** [comment]
Seems to be fixed as of recent nightly.
