### ISSUE TITLE
Steppenwolf 4-3 cannot be parsed

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1533]
https://www.y8.com/games/steppenwolf_chapter_4_episode_3

When you click "Play the game", "Play regular game" (also "Skip intro" if you wish), the game crashes and starts looping through all its frames:
`Couldn't parse SWF. This may or may not be a bug in Ruffle, please help us by reporting it to https://github.com/ruffle-rs/ruffle/issues and include the swf that triggered it.`

I've found a "magic" way to fix the game in JPEXS:
- Go to frame 1332 (`scripts` tab).
- Click `PlaceObject2 (1624) Depth: 1737 (Variables)`, then `onClipEvent(load)`.
- Click `Edit P-code`, type any character you want and remove it, so that enables the `Save` button.
- Save everything and... the game will work in Ruffle though no ActionScript has been changed.

I've no idea what's going on... The only changes I can see are the values associated to `If`s and `Jump`s (eg. `If loc1c9d` or `Jump loc1c26`)... so I suppose that matters?

Edit: A non-ASCII character is actually used (`…`) - this is likely the problem.

**Comment by Herschel** [comment]
Fixed by #2636.
