### ISSUE TITLE
avm1: Unload clip event handlers should cause clips to be destroyed later

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1535]
In the official Flash Player, movieclips with an `unload` clip event handler seem to "stay alive" for one frame longer than normal when they are removed. In Ruffle, they are destroyed immediately.

Say there is a movieclip named "clip" on frame 1. On frame 2, if you remove the clip and `trace(clip);`, normally this prints the empty string as the clip no longer exists. However, if you add an `unload` event handler to the clip, such as:
```
onClipEvent(unload) {
	trace("unload clipEvent");
}
```
then the `trace(clip)` will work and print `_level0.clip`, even though the clip no longer exists on frame 2. All properties of the clip also remain accessible, even though it's no longer visible. It seems that the clip is kept alive for an extra frame. This also happens if you use `clip.onUnload = function() { .. }`. On frame 3, these all return `undefined` as expected.

This can also cause some confusing behavior. Say that there is an entirely new movieclip named "clip" on frame 2. `clip` would still refer to the previous frame 1 clip, including all of its properties (for example, `trace(clip._x)` would print the previous clip's position). Removing the unload handler causes it to correctly refer to the frame 2 clip.

Example SWF:
[unload.zip](https://github.com/ruffle-rs/ruffle/files/5513020/unload.zip)

**Comment by Lord-McSweeney** [comment]
Closed by #8873.
