### ISSUE TITLE
Toss the Turtle - Missing background

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1536]
https://www.newgrounds.com/portal/view/508440/format/flash?emulate=flash

In Toss the Turtle, the background art during gameplay (trees and sky) is missing. Could be an image format or blend mode?

**Comment by Herschel** [comment]
Looks like this uses setMask, will be fixed by #1483.

**Comment by Herschel** [comment]
Fixed by #1483.
