### ISSUE TITLE
web: Ruffle doesn't load anymore.

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#1541]
https://www.spiele-umsonst.de/ruffle/

It used to run fine now it's not anymore. What's happening here?

ruffle.js:1 Serious error loading Ruffle: CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+1884159
(anonymous) @ ruffle.js:1
Promise.catch (async)
ensure_fresh_instance @ ruffle.js:1
stream_swf_url @ ruffle.js:1
connectedCallback @ ruffle.js:1
f @ ruffle.js:1
t.polyfill @ ruffle.js:1
polyfill @ ruffle.js:1
init @ ruffle.js:1
ruffle.js:1 Serious error occurred loading SWF file: CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+1884159
stream_swf_url @ ruffle.js:1
async function (async)
stream_swf_url @ ruffle.js:1
connectedCallback @ ruffle.js:1
f @ ruffle.js:1
t.polyfill @ ruffle.js:1
polyfill @ ruffle.js:1
init @ ruffle.js:1
ruffle.js:1 Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+1884159
async function (async)
stream_swf_url @ ruffle.js:1
connectedCallback @ ruffle.js:1
f @ ruffle.js:1
t.polyfill @ ruffle.js:1
polyfill @ ruffle.js:1
init @ ruffle.js:1

**Comment by Txori** [comment]
I just tried on my phone and it loads just fine.

**Comment by x3fold** [comment]
I've just tried running this in Chrome and it works fine

**Comment by desertking** [comment]
Hmm okay maybe it's local problem then. I just checked on my phone there it works. strange

**Comment by Herschel** [comment]
Could you provide some more info? What browser/version? Could you take a peek in the Network inspector (F12) and see if the WASM file is successfully downloading?

**Comment by desertking** [comment]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): unexpected end of stream @+1884159
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+1884159
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.spiele-umsonst.de/ruffle/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by desertking** [comment]
![image](https://user-images.githubusercontent.com/23042167/98728185-6b2cd200-2399-11eb-9b16-cd73def95246.png)

**Comment by Toad06** [comment]
By any chance, does it work if you run the page in private mode? If so, try clearing the cache.

**Comment by desertking** [comment]
Hmm yeah that seemed to be a cache problem. It works now. The problem is that could occur to other users as well. A new ruffle version should once trigger the clear to be re-chaced. Dunno if it's possbile thou via the http header

**Comment by Herschel** [comment]
The core Wasm files already have a hash in their file name to prevent stale caches. `ruffle.js` =could still be cached, but I don't think there is more we can do. Common practice is for the site to add a query parameter to the URL for cache-busting (for example, `ruffle.js?v=abcdef`), but this would be up to the website admin. We don't want to completely kill the cache either, as we want the large Wasm file to be cached normally when the version doesn't change.

**Comment by desertking** [comment]
Hmm okay then I may do it like that and know for the next time :)
