### ISSUE TITLE
Teen Titans Go: Grab the Grub

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15421]
### Describe the bug

The game is stopping from loading. 

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x19e2820 }) to handler FunctionObject(FunctionObject { ptr: 0xaf8e68, name: Ok("org.flixel::FlxGame/create()") }) : RustError("Ruffle does not support sparse arrays yet.")`

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x404fec8 }) to handler FunctionObject(FunctionObject { ptr: 0xaf8e68, name: Ok("org.flixel::FlxGame/create()") }) : ArgumentError: Error #2025: The supplied DisplayObject must be a child of the caller.`

### Expected behavior

To load correctly. 

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=cn/teentitans/grabthegrub.swf&params=&name=Grab%20the%20Grub)
[Flash](https://www.y8.com/games/grab_that_grub)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by evilpie** [comment]
Playable now thanks to #16051.
