### ISSUE TITLE
(Bug) The Last Stand can't load

### ISSUE THREAD

**Issue by hardBSDk** [ruffle-rs/ruffle#15428]
The loading bar stay at "00"

- OS - Fedora 39
- Variant - Linux native binary
- Ruffle version - 05-03-2024
- SWF - http://cache.armorgames.com/files/games/the-last-stand-269.swf

![image](https://github.com/ruffle-rs/ruffle/assets/55782009/5403fa56-4c51-4336-bf81-817d46703cb5)

**Comment by adrian17** [comment]
For me this SWF loads on both desktop and web. Can you show the console logs, if there are any?

**Comment by hardBSDk** [comment]
@adrian17 I think it's a race condition when you open the SWF, try to load it many times to see different behavior.

I opened the Ruffle binary from terminal but it don't show a log.

**Comment by hardBSDk** [comment]
https://github.com/ruffle-rs/ruffle/issues/15436
