### ISSUE TITLE
Ruffle Demo Bug

### ISSUE THREAD

**Issue by turbo852** [ruffle-rs/ruffle#1542]
I tried to load a local SWF and got this bug:

The SWF in question is this:
http://supermariobroscrossover.com/media-old/flash/SmbcPreloader.swf

I don't know what version of Flash/Action Script was used to create this. I am running Chrome in incognito mode. 
Version 86.0.4240.193 (Official Build) (64-bit)

# Error Info
Error: Error loading movie: Invalid data: Invalid SWF

# Player Info
Allows script access: false

# Page Info
Page URL: http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html?file=synj1.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Toad06** [comment]
This is the new link for the demo: https://ruffle.rs/demo/
(no crash but the game gets stuck on the loading screen)

**Comment by Herschel** [comment]
AS3 file, closing in favor of #1368.
