### ISSUE TITLE
(Bug) Ruffle hangs while loading a Zombotron 2 level

### ISSUE THREAD

**Issue by hardBSDk** [ruffle-rs/ruffle#15438]
- OS - Fedora 39
- Variant - Linux native binary
- Ruffle version - 05-03-2024
- SWF - http://armorgames.com/zombotron2/zombotron-2-13457ec92.swf

**Comment by adrian17** [comment]
The link 404s so I can't reproduce that version - but the version from https://www.newgrounds.com/portal/view/598023?emulate=flash works on both desktop and web for me. Can you try there?

**Comment by hardBSDk** [comment]
@adrian17 It loaded normally, I think it's just slow or there's a race condition causing random hangs.

**Comment by hardBSDk** [comment]
https://github.com/ruffle-rs/ruffle/issues/15436
