### ISSUE TITLE
Amazon Adventure

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15452]
### Describe the bug

The game stops loading.

`ERROR core/src/display_object/movie_clip.rs:2245 Got "ReferenceError: Error #1065: Variable PreloadDistractor is not defined." when constructing AVM2 side of movie clip of type main`

### Expected behavior

To load correctly.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=archive/2/TheOctonauts/flash/minigames/amazon_adventure.swf&params=&name=Amazon%20Adventure)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

No flash version online.

**Comment by Lord-McSweeney** [comment]
This seems to be because of missing flashvars, specifically `preloadDistractorClass`. It works if manually passed, except then it hits another error, this time to do with a missing XML file. Closing as the site doesn't seem to have archived necessary assets.

**Comment by Stefannag** [comment]
> This seems to be because of missing flashvars, specifically the flashvar `preloadDistractorClass`. It works if manually passed, except then it hits another error, this time to do with a missing XML file. Closing as the site doesn't seem to have archived necessary assets.

Indeed, it was missing a path, now it have it: [Amazon Adventure](https://www.getgames.io/games/ruffle/?swf=archive/2/TheOctonauts/flash/minigames/amazon_adventure.swf&params=configPath%3Dhttps%3A%2F%2Fwww.getgames.io%2Fgames%2Fswf%2Farchive%2F2%2FTheOctonauts%2Fflash%2Fminigames%2Fresources%2Famazon_adventure%2Fconfig.xml%26preloadDistractorClass%3DAmazonAdventureDistractor&name=Amazon%20Adventure)

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "complete", class: com.greensock.events::LoaderEvent, ptr: 0x2905b08 }) to handler FunctionObject(FunctionObject { ptr: 0x1e3b558, name: Ok("net.pluginmedia.brain.greymatter::GreyMatterApplication/handleCommonLoadComplete()") }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: removeEventListener)`
