### ISSUE TITLE
non-ASCII chars in file name not properly displayed

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#15454]
### Describe the bug

1. Rename [öæáßñ.txt](https://github.com/ruffle-rs/ruffle/files/14499392/oaeassn.txt) to `öæáßñ.swf`.
2. Open it with the desktop program.
3. At least in Linux (nightly 2024-03-05), file name is displayed as:

    ![wrong-non-ascii](https://github.com/ruffle-rs/ruffle/assets/203767/7223515e-2e0c-4855-a339-26a0884ae0bf)

### Expected behavior

The window title should read _Ruffle - öæáßñ.swf_.

### Content Location

https://github.com/ruffle-rs/ruffle/files/14499392/oaeassn.txt (as explained, replace the extension with `.swf`).

### Affected platform

Desktop app

### Operating system

Fedora 37

**Comment by torokati44** [comment]
Huh, I guess we're supposed to `urldecode` it before setting it as a window title. :) Good catch!

**Comment by TheDecimeter** [comment]
I was looking at this same issue, did you happen to come across: https://docs.rs/urlencoding/latest/urlencoding/

(you are correct about the location of the bug)
