### ISSUE TITLE
Shopkins Shoppies Peppa Mint Dress Up

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15467]
### Describe the bug

There are some errors like this, in a loop.

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x728c78 }) to handler FunctionObject(FunctionObject { ptr: 0x4a8030, name: Ok("ϓ/skip()") }) : VerifyError: Error #1011: Method contained illegal opcode.`

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xb727d0 }) to handler FunctionObject(FunctionObject { ptr: 0x9638e0, name: Ok("ϓ/skip()") }) : VerifyError: Error #1011: Method contained illegal opcode.`

### Expected behavior

To load and work.

### Content Location

[Ruffle](https://www.play-games.com/game/15695/shopkins-shoppies-peppa-mint-dress-up.html)

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

No flash version online.

**Comment by Lord-McSweeney** [comment]
Looks fixed now
