### ISSUE TITLE
DC Super Hero Girls Super Girl \ DC Super Girl Dress Up

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15464]
### Describe the bug

There is just a blank scene after Ruffle loads.

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xa30eb8 }) to handler FunctionObject(FunctionObject { ptr: 0x960260, name: Ok("ͱ/loaderEventsHandler()") }) : VerifyError: Error #1011: Method contained illegal opcode.`

### Expected behavior

To load and work.

### Content Location

[Ruffle](https://www.play-games.com/game/7937/dc-super-girl-dress-up.html)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

Couldn't find a flash version online.

**Comment by Lord-McSweeney** [comment]
This seems to be fixed now
