### ISSUE TITLE
In-game play button can be clicked multiple times (regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1547]
This issue affects desktop and web backends.
Nightly builds <= 2020-11-02 were unaffected.

In [Garfield Coop Catch](https://www.y8.com/games/garfield_coop_catch), the "click here to play" button is now executed every time you click it (should only trigger a single time). This even works if the button no longer exists: make a "partial" double-click on the button (a single full click, and clicking again but without releasing the mouse button this time), and wait until the first level starts; when you release the mouse button, you'll go back to the title screen.

**Comment by Herschel** [comment]
It looks like being able to click the button multiple times is a bug in the game itself (this occurs in the official Flash Player as well).

Being able to trigger a button after it's removed is indeed a bug on our side, though.

**Comment by Toad06** [comment]
Whooops, sorry, it seems like I've a different version of this game on my PC - and only this version is affected by the regression (no issue in the official Flash Player). My bad!

Attaching the file: [alt_coop_catch.zip](https://github.com/ruffle-rs/ruffle/files/5540707/alt_coop_catch.zip)

**Comment by Toad06** [comment]
I've run a bisect checking the previous attached file. The issue was introduced in commit 1a230bda09848ed0ce93b78cd8ca6c1fe81e9cac.

**Comment by MrCheeze** [comment]
Looks like as you suggested, this was the same issue as the 1603 and is working now also.

**Comment by Toad06** [comment]
@MrCheeze Thanks for the fix (#1633)! 👍
