### ISSUE TITLE
Hazel Eyes

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15473]
### Describe the bug

The game is loading correctly, but after pressing "EASY" or any other game mode, it will return an error:

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x17d1ce0 }) to handler FunctionObject(FunctionObject { ptr: 0x1150e650, name: Ok("hoolib.fx::ScreenFader/continueFade()") }) : ReferenceError: Error #1056: Cannot create property metaData on flash.display.Sprite.`

### Expected behavior

To load and run the game correctly.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=archive/4/LittleCharmers/hazelEyes.swf&params=&name=Hazel%20Eyes)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

No flash file online.

**Comment by evilpie** [comment]
We seem to be missing `metaData` in the DisplayObject: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/DisplayObject.html#metaData
