### ISSUE TITLE
An error occurred on the Locke Kingdom login screen

### ISSUE THREAD

**Issue by haozhi6** [ruffle-rs/ruffle#15481]
### Describe the bug

ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "confLoadOk", class: flash.events::Event, ptr: 0xb59958 }) to handler FunctionObject(FunctionObject { ptr: 0x6036140, name: Ok("AngelMainRelease/onConfLoadOk()") }) : ReferenceError: Error #1069: Property connected not found on flash.net.URLStream and there is no default value.

### Expected behavior

Normal login

### Content Location

![image](https://github.com/ruffle-rs/ruffle/assets/45025597/511ddf4f-561c-40b3-9e05-a9b43de60ae2)

### Affected platform

Browser's extension

### Operating system

win10

### Browser

edge 版本 122.0.2365.80

**Comment by haozhi6** [comment]
Game address:  https://17roco.qq.com/qzone.html

**Comment by haozhi6** [comment]
Game address:  https://17roco.qq.com/qzone.html

**Comment by evilpie** [comment]
@haozhi6 Does this work now? `connected` was added in #15594.

**Comment by haozhi6** [comment]
![搜狗截图20240813165951](https://github.com/user-attachments/assets/0918102c-186a-4e33-ae8e-d2c3d64bb2a2)
This issue appears to have been resolved, but there are still other issues causing login failures
