### ISSUE TITLE
Ruffle Web - Drawing Issue 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1554]
Ruffle seems to add extra lines to some swf's I'm testing. 

When selected the lines don't appear. 

Could it be adding a border that isn't actually there? 

<img width="238" alt="Screenshot 2020-11-14 at 15 36 31" src="https://user-images.githubusercontent.com/10291664/99150932-8fd1c400-268f-11eb-8453-75c4279b36db.png">

Then when I select it: 
<img width="270" alt="Screenshot 2020-11-14 at 15 36 36" src="https://user-images.githubusercontent.com/10291664/99150933-9102f100-268f-11eb-88a6-94cb9c5b892d.png">

https://ridesims.com/ride-simulators/Revenge-of-the-Mummy 

File: 
https://ridesims.com/sites/default/files/2020-11/ROTM_V3.1.swf

**Comment by Toad06** [comment]
There's no rendering issue in nightly builds <= 2020-10-16.
I've run a bisect and it seems the bug was introduced in commit 4558be948ef23c650205d9aa1a7c949d6604f554.

**Comment by JamesAllgood** [comment]
fixed by #2128
