### ISSUE TITLE
Toy Story Marbelous Missions

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15554]
### Describe the bug

The game is stuck at loading.

`ERROR core/src/loader.rs:1040 Error during movie loading of "https://831.c.distralytics.com/node/tracking/trackerAS3.swf?c=831&r=1367427064&d=www.play-games.com&p=32&as=3": FetchError("Got JS error")`

`ERROR core/src/display_object/movie_clip.rs:2245 Got "ReferenceError: Error #1065: Variable da is not defined." when constructing AVM2 side of movie clip of type Main`

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x1f4a5f8 }) to handler FunctionObject(FunctionObject { ptr: 0x13a18d8, name: Ok("Main/onLoadMain()") }) : TypeError: Error #1006: elements is not a function of class XMLList.`

### Expected behavior

To load correctly the SWF and run.

### Content Location

[Ruffle](https://www.play-games.com/game/18072/toy-story-marbelous-missions.html)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

### Additional information

I didn't find a flash version online.

**Comment by evilpie** [comment]
After #15572 was merged, this is the remaining error:

```
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Got "ReferenceError: Error #1065: Variable da is not defined.
	at com.memecounter::Tracker$/init()
	at Main()" when constructing AVM2 side of movie clip of type Main
```

I had a look at the SWF file and it wasn't really obvious to me where `da` is supposed to come from.

**Comment by Lord-McSweeney** [comment]
This plays fine for me now, I'm guessing the `da` ReferenceError is actually a mistake, since it shows up in FP too.
However, Ruffle also throws this error, while FP doesn't. It doesn't stop the game from progressing, though.
```
TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: playing)
	at Nav/setMode()
	at Nav()
	at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
	at Main/onLoadConfig()
	at Main/onLoadMain()
```
Finally, there are some minor performance issues, but nothing to make the game unplayable.

**Comment by evilpie** [comment]
For me it seems to get stuck.
![image](https://github.com/ruffle-rs/ruffle/assets/296445/0dbaf82a-e704-433a-b5fd-4383ab2596c6)

**Comment by Stefannag** [comment]
> For me it seems to get stuck. ![image](https://private-user-images.githubusercontent.com/296445/313320168-0dbaf82a-e704-433a-b5fd-4383ab2596c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzQ0NDksIm5iZiI6MTcxMTAzNDE0OSwicGF0aCI6Ii8yOTY0NDUvMzEzMzIwMTY4LTBkYmFmODJhLWU3MDQtNDMzYS1iNWZkLTQzODNhYjI1OTZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxNTE1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjhiNDk3N2JiMjNiN2MzODgyOWJlZTAxNTFiNmYwZDJkMDI4ODU0ZDM0NTE4MzMzMzM2MjMzNGFlYmRjNjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jDhp5T6BxJ6YRa7bnwSsCx66xPcKye_nK70oyoHAOg4)


I can play it, no error, but If I die, there is no replay/restart button, and the game will stop there.
