### ISSUE TITLE
Regular Show: Dimensional Drift [AVM2]

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#15559]
### Describe the bug

The game is not loading, having the following error:

`ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x15aa860 }) to handler FunctionObject(FunctionObject { ptr: 0x15a9dd0, name: Ok("Main/init()") }) : TypeError: Error #2007: Parameter alphas must be non-null.`

### Expected behavior

To load and work.

### Content Location

[Ruffle](https://www.getgames.io/games/ruffle/?swf=cn/RegularShow/dimensional-drift/game.swf&params=&name=Regular%20Show%20Dimensional%20Drift)

[Flash](https://www.numuki.com/game/dimensional-drift/)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by MartySVK** [comment]
Same error when I try to play World Soccer Cup 2018
https://data.gameflare.com/games/8478/7KJnVZ8yu8uhUV.swf

```
Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x3951f80 }) to handler FunctionObject(FunctionObject { ptr: 0x1cbe120, name: Ok("Main/btn_handler()") }) : TypeError: Error #2007: Parameter alphas must be non-null.
at flash.display::Graphics/flash::display::Graphics::beginGradientFill()
at flare.core::Light3D/setColors()
at flare.core::Light3D/setParams()
at flare.core::Light3D()
at flare.materials.filters::LightFilter()
at flare.basic::Scene3D()
at Main/setup_3d()
at Main/btn_handler()
```
