### ISSUE TITLE
Bejeweled 2 (Scoop Away) Broken Hint button

### ISSUE THREAD

**Issue by Nyehmeh** [ruffle-rs/ruffle#15569]
### Describe the bug

Hint button is completely bugged. Clicking on it makes every jewel you try to click on change into an unusable hypercube

### Expected behavior

The hint button should show what matches you can make, just like in regular bejeweled 2.

### Content Location

https://ars.wildtangent.com/20100503_SCOOPAWAY/index.html

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Waterfox G6.0.9

**Comment by Lord-McSweeney** [comment]
Can you take a screen recording? I can't reproduce this on latest FF.

**Comment by Nyehmeh** [comment]
Apologies that I didn't reply back message, but it seems to work for me now.
