### ISSUE TITLE
Error running definition tag: DefineFont3, got Invalid data: Invalid fill style

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1560]
Using https://ruffle.rs/demo/ to load https://www.mejorar-presentaciones.tk/mejorar-presentaciones-presentation.swf, text on the first slide isn’t displayed.

Error message reads as follows:

```
Error running definition tag: DefineFont3, got Invalid data: Invalid fill style.
```

Adobe FP displays it fine. It was generated with _SWFTools_.

I get the same error using the desktop application.

BTW, text in https://www.mejorar-presentaciones.tk/mejorar-presentaciones-loader.swf is displayed perfectly fine.

Both SWF slides are generated from the same PDF document using `pdf2swf` included in _SWFTools_. Weird.

Many thanks for your help.

**Comment by Toad06** [comment]
I'm not sure but it's possible the last characters of the font cause this issue (two characters in one?):
![font4](https://user-images.githubusercontent.com/14274782/99949890-11a2ab00-2d7c-11eb-9339-7c178e3fa7d9.png)

**Comment by ousia** [comment]
@Toad06,

many thanks for your comment.

_Carlito_ (the font used) contains many ligatures, such as these:

![Screenshot from 2020-11-23 17-51-27](https://user-images.githubusercontent.com/203767/99991122-eab49b00-2db4-11eb-9b63-e864acb4ce68.png)

Of course, TeX subset the font when generating the PDF document.

I converted the PDF document into SWF with `pdf2swf` from SWFTools.

I don’t know whether non-standard ligatures were a problem here.

**Comment by Elementtair** [comment]
Same problem for me .
 SWF were made with pdf2swf and I got sligthly the same error
"Error running definition tag: DefineFont2, got Invalid data: Invalid fill style."  and not text is displayed

I don't know what was the font used on those documents, few examples here:
https://www.mercedes-anciennes.fr/forummb/00ff.swf
https://www.mercedes-anciennes.fr/forummb/05-M110calage.swf

**Comment by ousia** [comment]
I’m closing this issue, since I don’t get the error with the loader and Ruffle isn’t able to load the presentation.

Opening two new issues.

**Comment by ousia** [comment]
I’m afraid that GitHub has issues with the page, so I’m providing the [direct link to the SWF file](https://github.com/ousia/mejorar-presentaciones/raw/gh-pages/mejorar-presentaciones-presentation.swf).

Dragging and dropping the downloaded file in https://ruffle.rs/demo, I get the following error message:

``` js
Error running definition tag: DefineFont3, got Invalid data: Invalid fill style.
ruffle_web.js:1154:8
    __wbg_error_e325755affc8634b ruffle_web.js:1154
    h6866e22c28130846 20dc23cfffed12aba637b533134b1c67.wasm:3563501
    hb93898b1bf2099cf 20dc23cfffed12aba637b533134b1c67.wasm:3436174
    <console_log::WebConsoleLogger as log::Log>::log::h25daef10efceece3 20dc23cfffed12aba637b533134b1c67.wasm:3559387
    h197e5d9168817bb7 20dc23cfffed12aba637b533134b1c67.wasm:3438334
    h72b383fe68294325 20dc23cfffed12aba637b533134b1c67.wasm:2466540
    h35f372165bc26848 20dc23cfffed12aba637b533134b1c67.wasm:1867681
    h8a999d20ec8d3c8d 20dc23cfffed12aba637b533134b1c67.wasm:743168
    h377ff112ce922d82 20dc23cfffed12aba637b533134b1c67.wasm:2758664
    h18f2f6a7a2166fcc 20dc23cfffed12aba637b533134b1c67.wasm:2734320
    ruffle_load_data 20dc23cfffed12aba637b533134b1c67.wasm:3499437
    load_data ruffle_web.js:369
    load ruffle-player.js:361
    a ruffle-player.js:4
Unknown tag code: 40
```

BTW, I don’t know whether last line is related to this issue, but https://www.m2osw.com/swf_tag_namecharacter explains the tag code.

I get this as first frame (no sans-serif font):

![no-sans](https://user-images.githubusercontent.com/203767/106391047-a6b0c880-63eb-11eb-9024-85415888a901.png)

And I should get this:

![full-sans](https://user-images.githubusercontent.com/203767/106391056-b4664e00-63eb-11eb-8e23-e60561d2ea79.png)

Sorry, but after inspecting the SWF file with both JPEXS and `swfdump` (from SWFTools), I don’t know what the fill style is when related to fonts in this animation.

Would anyone be so kind to engligthen me where to start searching to provide a more meaningful report?

Many thanks for your help.

**Comment by ousia** [comment]
@Toad06, is there any way to know which is the fill style Ruffle considers invalid?

**Comment by Elementtair** [comment]
Nice explanation ! 
I suppose #3115 with Definefont 2 come from same behaviour, isn't it?

**Comment by ousia** [comment]
@Toad06, many thanks for your extremely helpful explanation.
