### ISSUE TITLE
[AS2] loader doesn’t work

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1561]
http://www.mejorar-presentaciones.tk/mejorar-presentaciones-loader.swf loads http://www.mejorar-presentaciones.tk/mejorar-presentaciones-presentation.swf.

I assume the relevant AS2 code in the loader reads:

``` js
the_presentation = "./{filename:output}";
first_loading = new Object();
first_loading.onMouseDown = function () {
        load_swf = new MovieClipLoader();
        load_swf.loadClip(the_presentation, placeholder);
        listen_loading = new Object();
listen_loading.onLoadStart = function(target) {
    _root.dlprogress_mvclip.bar._xscale = 0;
    _starttime = gettimer();
};
listen_loading.onLoadError = function(){
    _root.load_text = "Presentation cannot be loaded!";
};
listen_loading.onLoadProgress = function(target, bytesLoaded, bytesTotal) {
   downldtime = (gettimer() - _starttime) / 1000;
   _root.load_text = (String (Math.round ((bytesLoaded * 100) / bytesTotal)) + "% (" + Math.round((bytesLoaded / 1024) / downldtime) + " KB/s)");
   _root.dlprogress_mvclip.bar._xscale = Math.round(bytesLoaded/bytesTotal*100);
   keeping_awake = setInterval(function(){}, 1000);
};
listen_loading.onLoadComplete = function(target) {
   clearInterval(keeping_awake);
   _root.load_text = "";
   _root.dlprogress_mvclip._visible = 0;
   _root.dlprogress_mvclip.bar._visible = 0;
   _root.first_slide._visible = 0;
};
            load_swf.addListener(listen_loading);
    };
    Mouse.addListener(first_loading);
```

I get two errors and no loading:

```
Unknown tag code: 40
Stop: Target is not a MovieClip
```

I wonder why target isn’t a movieclip for Ruffle.

Many thanks for your help.

**Comment by Toad06** [comment]
```
load_swf = new MovieClipLoader();
load_swf.loadClip(the_presentation,placeholder);
```

In Flash, "placeholder" is `_level0.presentation_sprite` but in Ruffle the value is `undefined`. The variable doesn't seem to be set anywhere but I've found out "placeholder" was the name of a shape element.

**Comment by ousia** [comment]
Many thanks for your comment, @Toad06.

`placeholder` in `swfc` (from SWFTools) code is:

``` js
.box placeholder width={presentation:width} height={presentation:height}
...
.sprite images
.put placeholder alpha=0%
```

`images` is only used later in AS2 code related to the same sprite:

``` js
this.attachMovie("images","presentation_sprite",1);
```

`presentation_sprite` isn’t defined or used anywhere else.

**Comment by CUB3D** [comment]
The "placeholder" variable seems to be set based on the value used for the name in the PlaceObject2 tag inside of the sprite, in ruffle this seems to work fine when the tag is at the root but fail when it's part of a sprites actions. 

Minimal example: 
[1561_example.zip](https://github.com/ruffle-rs/ruffle/files/5721393/1561_example.zip) 

Output in Flash Player:
```
placeholder = _level0.other_mc_instance
other_mc_instance = _level0.other_mc_instance
```

Output in Ruffle:
```
placeholder = undefined
other_mc_instance = _level0.other_mc_instance
```

**Comment by ousia** [comment]
@CUB3D,

many thanks for your reply and sorry for not having answered before.

I’m afraid I don’t know how to attach a movie outside the sprite (I’m on Linux, using `swfc` [the SWF compiler from _SWFTools_]).

It would be great that _Ruffle_ could solve `placeholder` inside the sprite.

Many thanks for your help.

**Comment by kmeisthax** [comment]
@CUB3D Am I to interpret this to mean that if a `PlaceObject` happens with a given name, but the object that was placed isn't representable in AVM1 (e.g. it's a shape), then it's supposed to return itself?

I can implement that behavior, but I'm confused. Why would this be working in `root` if that were the case?

**Comment by ousia** [comment]
@relrelb,

considering https://github.com/ruffle-rs/ruffle/issues/1561#issuecomment-947371500, could #6004 solve also this issue?

Many thanks for your help.
