### ISSUE TITLE
nick jr festive coloring all there is is a black screen

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15656]
### Describe the bug

all you get is a black screen and i reloaded the game and the issue still happens

### Expected behavior

to be able to color

### Content Location

https://www.numuki.com/game/nick-jr-festive-coloring/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by adrian17** [comment]
Does it even load Ruffle?
From what I see, the page is broken here, it doesn't load any game at all, or Ruffle?

**Comment by n0samu** [comment]
This is an old and broken HTML5 game.
