### ISSUE TITLE
stuck at black screen but you can hear music playing

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15666]
### Describe the bug

above says it

### Expected behavior

for the black screen to go away

### Content Location

https://www.numuki.com/game/spongebob-invasion-of-the-lava-king/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by n0samu** [comment]
This problem occurs due to CORS. For valid issues affecting this game, see #11612 and #12727.
