### ISSUE TITLE
the game spongebob bedtime in bikini bottom you cant start the game and stuck on a yellow screen

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15669]
### Describe the bug

above descripes it

### Expected behavior

for the game to actually function

### Content Location

https://www.numuki.com/game/bedtime-in-bikini-bottom/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by Lord-McSweeney** [comment]
This looks like it isn't and was never a Flash game
