### ISSUE TITLE
sponge-star-patrick-pants games sticks to black screen no music refreshing does nothing 

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15675]
### Describe the bug

above explains it

### Expected behavior

for the game to actually work

### Content Location

https://www.numuki.com/game/sponge-star-patrick-pants/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by n0samu** [comment]
This is an HTML5 game, not a Flash game!
