### ISSUE TITLE
operation-holiday-hero does not function at all and a black screen and reloading does nothing to resolve it

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15674]
### Describe the bug

above explains it

### Expected behavior

for the game to actually work

### Content Location

https://www.numuki.com/game/operation-holiday-hero/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by Lord-McSweeney** [comment]
This tries to parse some bad XML:
```
<?xml version="1.0" encoding="utf-8" ?>
<fonts>
	<font>General</font/>
	<font>Korean</font/>
	<font>Japanese</font/>
	<font>Arabic</font/>
	<font>Hebrew</font/>
	<font>Chinese</font/>
</fonts>
```
(note the malformed `<font>` closing tags)

Somehow FP allows this.
