### ISSUE TITLE
Error on https://gaymes.net/humplex-manful-the-pro-wrestler/

### ISSUE THREAD

**Issue by LinhNekmn** [ruffle-rs/ruffle#15681]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: true

# Page Info
Page URL: https://gaymes.net/humplex-manful-the-pro-wrestler/

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-03-19
Channel: nightly
Built: 2024-03-19T00:05:39.978Z
Commit: 9dc45b3aced673dde2ee3efe88df58f46e07377e
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Looks like a device or network issue unrelated to Ruffle
