### ISSUE TITLE
Dungeons and Dungeons swf causes crash

### ISSUE THREAD

**Issue by gryftir** [ruffle-rs/ruffle#1569]
Downloaded https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/17072/original/dungeons_and_dungeons.swf tried to use on ruffle, and the game crashed.  Firefox 82.0.3 on mac os x Catalina

**Comment by n0samu** [comment]
No crash now but all I get is a black screen. Looks like the game's preloader uses some AVM2 features that aren't implemented yet.

**Comment by Lord-McSweeney** [comment]
This game needs `NetConnection`.

**Comment by Lord-McSweeney** [comment]
This doesn't work (still black screen) even after stubbing `NetConnection`, though there are no errors.

**Comment by Lord-McSweeney** [comment]
Still not working.

**Comment by Lord-McSweeney** [comment]
Seems like the SWF needs to load an FLV video, but it's missing (http://i.cdn.turner.com/adultswim/games/game/tools/swf/wsg-700x500.flv).

**Comment by n0samu** [comment]
Here is a version of the game hacked to load the FLV from a relative URL, along with the FLV grabbed from Wayback:
[dungeons-and-dungeons-hacked.zip](https://github.com/ruffle-rs/ruffle/files/12179621/dungeons-and-dungeons-hacked.zip)

The game is basically playable now. It's a very lame platformer with a weird theme. Closing issue
