### ISSUE TITLE
super-megaforce-legacy it keeps saying oops an error occured please try again

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15696]
### Describe the bug

above says it 

### Expected behavior

to be able to play the game

### Content Location

https://www.numuki.com/game/super-megaforce-legacy/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by adrian17** [comment]
Can you screenshot the message?

**Comment by n0samu** [comment]
This page is using the WAFlash emulator, not Ruffle! The error message you mentioned is the message WAFlash displays when it exceeds its hardcoded memory limit.
