### ISSUE TITLE
the-thundermans-make-a-scene/ continous black screen

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15706]
### Describe the bug

above describies it 

### Expected behavior

to play the game

### Content Location

https://www.numuki.com/game/the-thundermans-make-a-scene/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by adrian17** [comment]
Again: are you sure that this is even a Flash game? I don't see Ruffle there at all.

**Comment by n0samu** [comment]
Indeed not a Flash game
