### ISSUE TITLE
thor-frost-giant-frenzy black sreen and nothing works by clicking

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15707]
### Describe the bug

above says it

### Expected behavior

game to not be black

### Content Location

https://www.numuki.com/game/thor-frost-giant-frenzy/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by Lord-McSweeney** [comment]
There are no errors, but there is this stub: `ExternalInterface.objectID`
