### ISSUE TITLE
peppa-pig-find-the-differences cannot play the game and clicking does nothing

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15726]
### Describe the bug

above says it 

### Expected behavior

for the game to work

### Content Location

https://www.numuki.com/game/peppa-pig-find-the-differences/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by adrian17** [comment]
Again, it's not even a Flash game, there's no Ruffle here as far as I can see.
