### ISSUE TITLE
bubble-guppies-classroom-play does not load at all

### ISSUE THREAD

**Issue by markman12345** [ruffle-rs/ruffle#15736]
### Describe the bug

above says it

### Expected behavior

for the game to load

### Content Location

https://www.numuki.com/game/bubble-guppies-classroom-play/

### Affected platform

Browser's extension

### Operating system

windows 11

### Browser

microsoft edge

**Comment by adrian17** [comment]
Loads for me. (and even without Ruffle, the website uses waflash instead of Ruffle.)
Closing for now. Please reopen if you can obtain console logs when opening this.

https://github.com/ruffle-rs/ruffle/assets/4729533/efb410d2-0d7e-45c8-a5b3-7a86f4f2e676
