### ISSUE TITLE
I would like a customized made version of ruffle player but act like a special web browser please.

### ISSUE THREAD

**Issue by KaineRecycler** [ruffle-rs/ruffle#15746]
Hi my name is Kaine Dube and I would like a customized made version of ruffle player but acting like between a offline website browser
And a built in emulator at once for handling between the offline web and play flash content and other related webpage content that
Features navigation arrows on the top left corner of the ruffle app and drag and drop file uploader that would only accept two file formats
Which are in my custom case example ZIP and HTML files that should be very helpful to playing my offline webpages that I have in my Microsoft OneDrive account on my PC computer 💻 that I have sitting on the floor next to my bed so this custom ruffle player that I just need would be very helpful but it just needs to be made with a bit a few custom features and be ready for me to download onto my bedroom laptop PC computer by I think by this early April so please let me know if you could make it customization for me so that
I can download my customized version of ruffle player but acting like bit between a offline web browser and ruffle player emulator at once so that I can start using it for browsing my websites that I have in my Microsoft OneDrive account for free without showing any errors or problems with using my customized version of ruffle player but acting between a offline web browser and emulator at once
Please.

**Comment by adrian17** [comment]
I'm sorry, but I don't think anyone is going to make a custom application just for you. Especially with specific requirements and a deadline like "by early April".

That said, I also don't really understand how everything you say can't be handled by opening your local HTML pages in the browser (possibly via an ad-hoc localhost server).
