### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/lavindor-kingdom/

### ISSUE THREAD

**Issue by yechaoyun** [ruffle-rs/ruffle#15743]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/meet-and-fuck-hentai-games/lavindor-kingdom/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.46
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by Lord-McSweeney** [comment]
Closing as old Ruffle version and probably network error.
