### ISSUE TITLE
Error on https://learn.genetics.utah.edu/content/addiction/mouse/

### ISSUE THREAD

**Issue by kbleuberry** [ruffle-rs/ruffle#15764]
# Error Info
Error name: TypeError
Error message: WebAssembly compilation aborted: Network error: Response body loading was aborted
Error stack:
```
TypeError: WebAssembly compilation aborted: Network error: Response body loading was aborted
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://learn.genetics.utah.edu/content/addiction/mouse/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-11-23
Channel: nightly
Built: 2021-11-23T00:14:22.573Z
Commit: cf1d0e7624fb84d23087bc0611e3dbf92dcb65e7
Is extension: false

**Comment by Lord-McSweeney** [comment]
Closing as old Ruffle version and probably network error.
