### ISSUE TITLE
Major difference in tab key behavior on https://www.dnai.org/timeline/index.html?m=1

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#15853]
### Describe the bug

In Ruffle, the order seems slightly arbitrary (different depending on my horizontal scroll perhaps, even though that has no bearing in Flash), and the only tab-able elements are:

Morgan and the Genetics of Fruits Flies
Rediscovering Mendel's Laws
Miescher and the isolation of DNA
Mendel and pea plants
Nobel Winner (1933)
Minimized storage window icon

### Expected behavior

The tab-able elements are as follows in Flash player, in this order:

1\) Gregor Mendel
2) Miescher and the isolation of DNA
3) Friedrich Miescher
4) Mendel and pea plants
5) Rediscovering Mendel's Laws
6) Hugo de Vrie
7) Carl Correns
8) Morgan and the genetics of fruit flies
9) Erich von Tschermak-Seysenegg
10) Thomas Morgan
11) go to 1920-49
12) Nobel Winner (1933) (no click event)
13-18) Small squares aboves pre 1920s and 1920-49 label, from left to right (no click event)
19) pre 1920s label
20-22) Small squares above early 50s label, from left to right (no click event)
23) 1920-40 label
24-27) Small squares above late 50s label, from left to right (no click event)
28) early 50s label
29-30) Small squares above 1960s label, from left to right (no click event)
31) late 50s label
32) 1960s label
33) 1970s label
34) Minimized storage window icon
35) 1980s label
36) 1990-2000- label
37) ??? (only sometimes is there something tab-able after the last label and before Mendel's biography, and if it exists it is not clickable)

### Content Location

https://www.dnai.org/timeline/index.html?m=1

For https://www.dnai.org/timeline/year_pre20.swf, numbers 1-12 from the expected behavior apply.

### Affected platform

Self-hosted version

### Operating system

Linux Fedora 38

### Browser

Mozilla Firefox 123

**Comment by danielhjacobs** [comment]
Pinging @kjarosh

**Comment by kjarosh** [comment]
Matching FP's automatic order will perhaps be the most difficult and laborious part, I tried finding some generic patterns behind it but failed miserably. That is covered by "Analysis and implementation of a proper automatic order" from https://github.com/ruffle-rs/ruffle/issues/5443#issuecomment-1992075171. Currently Ruffle just orders tabbable items by the top-left corners of their bounds as it seemed simple enough and somewhat similar to what FP is doing.

It's interesting though that some items are not tabbable in Ruffle, as I employed a rather liberal approach to what's tabbable... Will look at it for sure!

**Comment by kjarosh** [comment]
After https://github.com/ruffle-rs/ruffle/pull/16323 it seems that Ruffle and FP behave identically.

Regarding the non-tabbable items, I suspect they were in fact tabbable, but the highlight was not shown (see https://github.com/ruffle-rs/ruffle/pull/16287, they were buttons with invalid self bounds, but with proper hit bounds).
