### ISSUE TITLE
Can't render very complex vector image

### ISSUE THREAD

**Issue by olamcbola** [ruffle-rs/ruffle#1588]
Game: https://www.dolldivine.com/fairy-maker.php

Click on the little "mountain" icon, bottom-right a few times.
These backgrounds are photos that were vectorized using "Trace Bitmap" in Flash, then put into a movieclip which had a blur effect added on top.  There's a lot of vectors there.

**Comment by Dinnerbone** [comment]
Issue is that there's one (well, a few) shapes that are very very complex, and we're going over lyon's hardcoded u32::max limit for number of vectors.

We need to figure out how to split these up
