### ISSUE TITLE
_About Ruffle_ window cannot display PNG image

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#15905]
### Describe the bug

Go to the _About Ruffle_ window in the desktop application.

At least on Linux (with nightly from 2024-04-06), I get:

![wrong-png-format-fs8](https://github.com/ruffle-rs/ruffle/assets/203767/18542a15-ff44-46f3-90e0-46cd0795cc24)

### Expected behavior

No error message.

I wonder whether SVG would work better.

### Content Location

This issue requires no content.

### Affected platform

Desktop app

### Operating system

Linux Fedora

**Comment by sleepycatcoding** [comment]
This is a known issue, see: #15836.
