### ISSUE TITLE
Provide TypeScript declarations (or provide an example with TypeScript)

### ISSUE THREAD

**Issue by damil42** [ruffle-rs/ruffle#15911]
The NPM package [@ruffle-rs/ruffle](https://www.npmjs.com/package/@ruffle-rs/ruffle) has no `TS` label (declarations / d.ts). Are we able to include the d.ts in this project? Otherwise you can't use it in TypeScript properly.

Add an exmaple using the package `@ruffle-rs/ruffle` with TypeScript. You use `ruffle-core` in [demo](https://github.com/ruffle-rs/ruffle/tree/master/web/packages/demo) (React TypeScript) but replacing it with the npm does not work. I wonder how you was able to work with it (`ruffle-core` package).

**Comment by travisvn** [comment]
I am having this _exact_ issue, and I also tried to reference the demo's usage. It's very validating to see I wasn't the only one unable to reconcile `ruffle-core` with what was available.

**Comment by Dinnerbone** [comment]
As of #16928, `ruffle-core` is now usable as a module. You need to run `installRuffle("local")` somewhere to initialize it though.

We aren't yet publishing the module on npm though - that will come shortly.
