### ISSUE TITLE
iframe not working on nginx server

### ISSUE THREAD

**Issue by ricardoseb** [ruffle-rs/ruffle#1591]
hi, please help me!
I have the following code running on an nginx server:
`<head>`
   `<meta charset="utf-8">` 
    `<title>WEB</title>`
    `<script>`
        `window.RufflePlayer` = window.RufflePlayer || {};
        `window.RufflePlayer.config` = {
           ` "polyfills": ["static-content", "plugin-detect", "dynamic-content", "static-frames"]`
       `};`
   `</script>`
    `<script src="ruffle/ruffle.js"></script>`
`</head>`

`<iframe name="content" src="http://columnize.cl/conducete/modulo1/modulo_01_a/modulo_a.html" width="550" height="400"></iframe>`

When loading http: // localhost: 8080 it asks me to enable flash, Am I missing any additional configuration?
I leave you screenshots of the code inspector:
![test1](https://user-images.githubusercontent.com/31752537/99606252-25e75080-29e8-11eb-9806-d13589348095.png)

**Comment by Toad06** [comment]
The polyfills setting is now a boolean, so unless you're using a very old build you can just replace this line:
`"polyfills": ["static-content", "plugin-detect", "dynamic-content", "static-frames"]`
to:
`"polyfills": true`
(note that "true" is the default value anyway)

However, I'm not sure this would work in your case considering the [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) restrictions.

**Comment by ricardoseb** [comment]
@Toad06 Finally I have downloaded the swf files since I can not reproduce in the suggested way. Thanks!
