### ISSUE TITLE
Treating Touch and Click alike

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1593]
As you guys have made Flash load first time on the mobile devices, let's implement a feature that consider finger tap also a click (if possible). 'Coz games do load on Mobiles, but most of them are playable because they don't register finger taps.

**Comment by Herschel** [comment]
This should be working already -- if this isn't working for you, could you post which device and browser your are using?

**Comment by zohebnsr** [comment]
Thanks. It might be the game then. I checked some times ago. However, just tested now a couple files and working fine. Thanks for responding.

**Comment by parkerlreed** [comment]
Touch to click works for me on Android (Kiwi browser and Chrome extension)

However on desktop Linux standalone, tap to click is ignored.

**Comment by parkerlreed** [comment]
Example video https://streamable.com/cbkjgc

**Comment by Poopooracoocoo** [comment]
@parkerlreed are you using wayland (idk if it matters)?

**Comment by parkerlreed** [comment]
@Poopooracoocoo Nope just X11
