### ISSUE TITLE
Idk what to call it

### ISSUE THREAD

**Issue by MrFrankHardy** [ruffle-rs/ruffle#15945]
### Jacksmith or Papa's Freezeria

idk how it happened but it popped up and said to file a report
maybe it popped up due to me having two windows open but I'm unsure

### Expected behavior

for the game to continue as planned

### Content Location

Files? idk what to put

### Affected platform

Desktop app

### Operating system

windows 10

### Additional information

![Screenshot 2024-04-09 192428](https://github.com/ruffle-rs/ruffle/assets/166566779/768f8f2d-52d5-48af-bc13-b7c9b923c711)

**Comment by MrFrankHardy** [comment]
edited it multiple times but still no clue what to do never opened one

**Comment by sleepycatcoding** [comment]
Should be fixed by #16699.
