### ISSUE TITLE
  Error on archive.org defendyourcastle

### ISSUE THREAD

**Issue by jaredly** [ruffle-rs/ruffle#1597]
https://archive.org/details/defendyourcastle_flash
this happened a couple of times, no definite repro though :/

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
    at Object.Y (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278)
    at __wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106)
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/defendyourcastle_flash

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
OS: MacIntel

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by timtadh** [comment]
I got this as well

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
Error stack:
```
Error: panicked at 'already mutably borrowed: BorrowError', C:\Users\Michael Welsh\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\gc_cell.rs:54:21
    at Object.Y (https://cors.archive.org/cors/emularity_engine_v1/core.ruffle.a8f0d0fd0a0f0ab41246.js:1:20278)
    at __wbg_new_df6e6ab7a65c4c4d (https://cors.archive.org/cors/emularity_engine_v1/ruffle.js:1:31106)
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1208]:0x227539
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[1363]:0x242e78
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3581]:0x2eccfd
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[2807]:0x2cf748
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3878]:0x2f1969
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3906]:0x2f1e53
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3781]:0x2f04e6
    at https://ia801902.us.archive.org/cors_get.php?path=%2F18%2Fitems%2Femularity_engine_v1%2Ff3eba4b49159e759c4ba.module.wasm:wasm-function[3908]:0x2f1eb7
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/defendyourcastle_flash

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Toad06** [comment]
Thanks for reporting this issue.

I think it's related to #1580: if you click on a selectable text (a text that changes the cursor to I-beam), there are high chances the game crashes. In this game specifically, a crash happens at the end of the level if, at some point, you've clicked one of the digits on the towers. Please let us know if you've actually experienced a different crash.

**Comment by timtadh** [comment]
@Toad06 I believe that is the same error I got. I accidentally clicked on the text in the tower when the game first loaded.

**Comment by jaredly** [comment]
oh yeah that sounds like the same thing! sorry for the dup

**Comment by Toad06** [comment]
No worries! The issue is now fixed in current master by the way, so hopefully everything will work very soon on archive.org.
