### ISSUE TITLE
Add AVM1 execution order tests

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#16]
Run hand-crafted SWFs through official Flash Player and Ruffle and compare the trace output. In particular, we need to figure out the order of execution for scripts when many display objects are interacting.

A simple example would be having a parent and a child clip, each tracing a string on frame 1, and verify that the order is accurate.

More examples:
 * Order of parent vs. newly placed/removed child (this affects the order!)
 * Order when parent calling `child.gotoAndStop`
 * Order when child calling `parent.gotoAndStop`
 * etc.

**Comment by kmeisthax** [comment]
I made a set of tests here: [ruffle-tests.zip](https://github.com/ruffle-rs/ruffle/files/3612933/ruffle-tests.zip). This file includes three tests, exported with MX 2004, to every Flash Player runtime I could get my hands on. Passing each test is determined by matching the trace output against the `passing-trace.txt` file in each folder. Each test consists of one 3-frame movie clip on a 3-frame timeline.

The tests are:

 * parent-child-order: The child clip is on the parent for frames one and two, but is missing in frame 3.
 * parent-stops-child: The parent issues a `gotoAndStop(1)` on the child.
 * child-stops-parent: The child issues a `gotoAndStop(1)` on the parent.

There's also a template `fla` for generating more tests in this form.

**Comment by Herschel** [comment]
More accurate goto ordering was implemented along with the various regression tests (`goto_advance` etc.) Any remaining issues are bugs and can be filed separately.
