### ISSUE TITLE
Ed Edd n Eddy - Lunchroom Rumble

### ISSUE THREAD

**Issue by scoronado12** [ruffle-rs/ruffle#1601]
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
Y@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/core.ruffle.js:1:20274
__wbg_new_df6e6ab7a65c4c4d@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/ruffle.js:1:29854
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[1209]:0x22731d
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[1361]:0x2423ee
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[3580]:0x2ec98d
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[2807]:0x2cf4a8
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[3925]:0x2f1e49
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[3879]:0x2f1644
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[3924]:0x2f1e1c
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[1551]:0x25f127
@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/290155aba9ea7303f353.module.wasm:wasm-function[4065]:0x2f3646
F@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/core.ruffle.js:1:17951
f@moz-extension://ddf6199e-341a-42df-8ea9-e66f20b02677/dist/core.ruffle.js:1:17374

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://i.cartoonnetwork.com/games/ed-edd-n-eddy/lunchroom-rumble/game.swf
Param quality: high
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
Attribute 5: [object Attr]

# Page Info
Page URL: https://www.cartoonnetwork.com/games/ed-edd-n-eddy/lunchroom-rumble/index.html

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
OS: Linux x86_64

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Lord-McSweeney** [comment]
Works fine now, but doesn't get into the game due to the missing file `global.xml`, which was not archived.

**Comment by Sonikkustar** [comment]
The web link doesn't appear to work, however I was able to boot up the SWF on desktop.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/a5feb532-4f05-41e6-934c-cab68e9a25eb)

Tested on ruffle-nightly-2023_12_04-windows-x86_64

I was able to boot up the game, however I did notice that it took a while for it to start (with ruffle almost crashing on me at one point).
