### ISSUE TITLE
LEGO.com Ruffle Player Not Playing Games

### ISSUE THREAD

**Issue by ipsterobo18** [ruffle-rs/ruffle#16013]
### Describe the bug

The official LEGO website was my bread and butter as a kid growing up in the early 2000s. Logging into Wayback Machine from at least 2007 on, the Ruffle player does not load the games and videos, etc. Please help!! Need that nostalgia back ASAP! Looking out for all classic LEGO fans as well!

### Expected behavior

Expected the game to load and be able to play right away/after some load time.

### Content Location

https://web.archive.org/web/20080710104747/http://indianajones.lego.com/en-US/games/default.aspx

### Affected platform

Browser's extension

### Operating system

macOS Sonoma 14.4.1

### Browser

Google Chrome 124.0.6367.62

**Comment by danielhjacobs** [comment]
This game relies on the page https://web.archive.org/web/20080710104747/http://cache.lego.com/en-us/games/gameWrapper.aspx, which was never archived. It doesn't work in Flash-enabled browsers either.
