### ISSUE TITLE
Clicking a button to change frames has a different behaviour from Flash Player.

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#1603]
The issue can be seen in this flash: https://uploads.ungrounded.net/582000/582345_cascade_loaderExt.swf

In Flash Player, mousing down on the red buttons on the bottom-right will bring you to another frame of the flash with a yes/no prompt. You will then stay on that frame until you select yes or no.

In Ruffle, mousing down on the red buttons will still bring you to the yes/no frame, but as soon as you mouse up you go back to the original frame again, and are therefore unable to ever select the Yes or No options.

I'm guessing what's happening here has to do with the fact that clicking the red button takes you to a frame where the button no longer exists. (Visually it looks like it does, but it's not interactable anymore.) I'm thinking that Ruffle still allows you to "unclick" a button in that circumstance, undoing it's effect, but that Flash Player doesn't. I could be totally off-base with this, though.

Testing this on Windows Firefox, from the web demo https://ruffle.rs/demo/ (nightly 2020-11-20)

**Comment by MrCheeze** [comment]
Looked into the flash in a bit more detail. It seems like there's a button (or possibly 2 in the same position) that have this behaviour:
1) on press: change to frame X
2) on rollout: change to frame Y

In Ruffle, mouse down will trigger the press event, and mouse up will trigger the rollout event.
In flash player, mouse down will trigger the press event, but the rollout event doesn't trigger.

**Comment by Toad06** [comment]
Seems similar to #1547 (the red buttons also work as expected in nightly builds <= 2020-11-02).
