### ISSUE TITLE
Cactus Mccoy2 v2.1: "Unknown AVM2 opcode" with multiple "Property does not exist" error

### ISSUE THREAD

**Issue by Trung0246** [ruffle-rs/ruffle#1606]
![image](https://user-images.githubusercontent.com/11626920/99754145-a10a3e80-2a9c-11eb-9bac-bb0d1fbc2c1d.png)

Here is the file (since github did not allow to upload .swf so have to replace that manually): [cactusmccoy2_v2_1_swf.txt](https://github.com/ruffle-rs/ruffle/files/5571039/cactusmccoy2_v2_1_swf.txt)

Most of the "Property does not exist" error are Sound, BitmapData and SimpleButton. Possible unimplemented feature?

**Comment by Herschel** [comment]
AS3 support not implemented quite yet, closing in favor of #1368

**Comment by Lord-McSweeney** [comment]
This now get stuck at "Loading levels".
