### ISSUE TITLE
 Boxhead The Nightmare: Red line around the text/buttons

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#16072]
### Describe the bug

In the menu scene, you can see red lines around the text/ buttons.

In Ruffle:
![image](https://github.com/ruffle-rs/ruffle/assets/10010569/f82e55ec-b43b-4cfc-82f4-38ae8f23f355)

In Flash:
![image](https://github.com/ruffle-rs/ruffle/assets/10010569/1a33863a-b7ce-43a3-a601-1b8b9fa0a5e1)

### Expected behavior

Game online - https://www.gameflare.com/online-game/boxhead-the-nightmare/
SWF - https://data.gameflare.com/games/2038/NZgxE0rRkmU3GS.swf

### Content Location

Show text/buttons without red lines

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by kjarosh** [comment]
My comment from Discord:

> Unfortunately it looks like it has been like that for a long time, it's difficult to tell whether the red box was introduced by some commit, as this game has just started working very recently. I verified that the red box was there as early as November 2023, the game worked very poorly before that
