### ISSUE TITLE
End of file was encountered

### ISSUE THREAD

**Issue by aojiaoxiaolinlin** [ruffle-rs/ruffle#16073]
### Describe what you were doing

Open the game web page
http://103.19.232.93:89/frame.htm

### What does the crash message say?

ERROR core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x1095870 }) to handler FunctionObject(FunctionObject { ptr: 0x101b328, name: Ok("MethodInfo-9()") }) : Error: Error #2030: End of file was encountered.

### Ruffle Version

nightly 2024-04-22

### Affected platform

Browser's extension

### Operating system

windows11

### Additional information

console log
New Ruffle instance created (Version: nightly 2024-04-22 | WebAssembly extensions: ON | Used renderer: wgpu-webgl)

**Comment by n0samu** [comment]
I can no longer reproduce this, I guess it is fixed
