### ISSUE TITLE
avm1: .swf file does not save to .sol file on ruffle self-hosted on web server and scroll code in .swf file doesn't work

### ISSUE THREAD

**Issue by Ghost-Program** [ruffle-rs/ruffle#16115]
### Describe the bug

.sol file doesn't do a save update when saving input text...

### Expected behavior

.sol file doesn't do a save update when saving input text to it on my web server using self-hosted ruffle. Also scroll code does not work in buttons to navigate up and down inside a .txt and .sol file using loadVariables to see those files in the .swf file during runtime. This is the scroll code for the buttons:

```
_root.TextFile.scroll++;
_root.TextFile.scroll--;

_root.SolFile.scroll++;
_root.SolFile.scroll--;
```

And this is the code to view those files in the .swf during live runtime:

```
_root.TextFile.loadVariables ("TextFile.txt", "/");

_root.SolFile.loadVariables ("SolFile.sol", "/");
```

Codes above work in flash player but not in ruffle player.

### Content Location

[Save File Scrolling Issue.zip](https://github.com/ruffle-rs/ruffle/files/15102543/Save.File.Scrolling.Issue.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 10 and up.

### Browser

Latest Chome and Firefox web browsers.

**Comment by Ghost-Program** [comment]
Wow! It has been a week and no one is looking into this issue I have dealing with .txt and .sol files not being saved on my server using ruffle.

**Comment by Ghost-Program** [comment]
Just realized I sent the wrong .zip file. Here is the right one: 
[Save File Scrolling Issue 2.zip](https://github.com/ruffle-rs/ruffle/files/15271473/Save.File.Scrolling.Issue.2.zip)

**Comment by Ghost-Program** [comment]
You guys haven't yet looked into this issue? Months has past, and It's still not fixed.

**Comment by adrian17** [comment]
Also, lots of `Warning: loadVariables is not a function` in flashlog, presumably because `_root.Words1` etc are strings?

**Comment by n0samu** [comment]
yeah, I'm 99% sure loadVariables does not support .sol.

**Comment by Ghost-Program** [comment]
> Hi, the SWF file you uploaded does not work in Flash Player either. The text boxes appear blank and clicking the Send button does nothing. Please upload something that properly reproduces the bug.

> Also, lots of `Warning: loadVariables is not a function` in flashlog, presumably because `_root.Words1` etc are strings?

> And in general, I wasn't aware that `loadVariables` is supposed to support .sol (and no source I can find suggests that to be the case). Further, I don't think the file generated by `SharedObject.getLocal("SolFile")` has necessarily anything to do with the SolFile.sol that you try to load via loadVariables...?
> 
> EDIT: the ".sol" file in your second zip doesn't look like a valid .sol, it looks like someone took a real shared object file and prepended `Words1=` at the beginning...?

> yeah, I'm 99% sure loadVariables does not support .sol.

Yes loadVariables do work with .sol files not only in flash player but also in your ruffle program. I loaded it up in the ruffle demo and it works. The thing is, the .sol files on my server does not update online like it would do offline on my local computer. Instead, it saves in ruffle's save manager in the context menu and that's not what i want it to do. I want it to save directly from the .swf file in ruffle to the .sol file one my server. I'm gonna take another look at the zip I uploaded here of a recreate from the actual one that works. I will message you guys/girls later. Thanks for finally responding after so long.

**Comment by adrian17** [comment]
> The thing is, the .sol files on my server does not update online like it would do offline on my local computer

> I want it to save directly from the .swf file in ruffle to the .sol file one my server.

It's never worked like that and it's not going to work like that. Flash can't just edit files on the server.

**Comment by adrian17** [comment]
> How do you think I know how to do it and I have it working right now on my server using the .swf via ruffle.

I don't know, you examples you attached don't work with real FP either, checked by two people.

> Flash and flashplayer has always been able to do it.

Flash's `SharedObject.getLocal` is local by definition, it has no ability to save anything on remote servers, this kind of thing is always a server-side operation.
This kind of thing _is_ possible if you had Flash Media Server running on the server and the Flash file used `SharedObject.getRemote()`, but your examples are not doing that.
If `getRemote` is what you're actually asking for, then indeed we don't have that implemented, but we'd need to see an SWF that works in real FP.

**Comment by Ghost-Program** [comment]
I'm going to re check the re created setup .zip file I uploaded on here above. There might of been something I missed in the recreation I made for it. I will be right back.

**Comment by Ghost-Program** [comment]
Ok I am 100 percent certain that this 3rd re-created version works. I had checked and re-checked this over 50 times now to make sure I re-created it right like the original one with all the extra elements in them. Now, you should see what I am talking about when I said that this .swf file will not save to the .sol file on my own server and it saves to ruffle save manager (which I do not want) but, it will save over and over again in the same .sol file on my local computer (which is what I do want).[Save File Scrolling Issue3.zip](https://github.com/user-attachments/files/17281819/Save.File.Scrolling.Issue3.zip)

**Comment by Lord-McSweeney** [comment]
Can you list the steps required to reproduce the behavior in Ruffle and FP?

**Comment by Ghost-Program** [comment]
If you download and load those re-created files up on any web server you got running a self-hosted ruffle and then try to type something in the "type here" input box and then send it. What is suppose to happen is the variable data you typed is suppose to be sent to the SolFile.sol file and any new send data as well input in the "Type Here" box but the thing is in ruffle, any send data in the "Type Here" box will not be in the SolFile.sol on my server. Instead, it saves all send data in ruffle's save manager (which should not happen because flashplayer always sends directly to the SolFile.sol where ever it is located at on my local PC machine via same folder as .swf.) Which is how the configuration is suppose to work just like flashplayer, but it only is working offline like flashplayer when it should be working the same way online like flashplayer. Also, the up and down buttons you can press on in the SaveFileScrollingIssue.swf do not work in ruffle.

**Comment by adrian17** [comment]
This still doesn't work with a real Flash Player. I did a quick demo with a running webserver:
https://github.com/user-attachments/assets/3bb834b7-4358-43c7-a17c-a7f063b15962

It creates a local shared object file as usual, and the file on the server side is not modified (also, again, the file in your .zip is not even a SOL file - from FP's `loadVariables` point of view, it's just a text file with `key=value` format that happens to be called .sol and happens to contain random bytes that'd make sense in a real SOL file); and again, with any normal web server (with one exception being Flash Media Server mentioned above), it's impossible for the client to modify a server's file on its own.

**Comment by Ghost-Program** [comment]
> This still doesn't work with a real classic in-browser Flash Player. I did a quick demo with a running webserver: https://github.com/user-attachments/assets/3bb834b7-4358-43c7-a17c-a7f063b15962
> 
> It creates a local shared object file as usual, but the file on the server side is not modified (also, again, the file in your .zip is not even a SOL file - from FP's `loadVariables` point of view, it's just a text file with `key=value` format that happens to be called .sol and happens to contain random bytes that'd make sense in a real SOL file); and again, with any normal web server (with one exception being Flash Media Server mentioned above), it's impossible for the client to modify a server's file on its own.
> 
> If you tested this yourself, can you show via screenshots/video how it's supposed to work?

I just realized something from looking at your video from the link. The data being sent is going to the wrong file path. In your video it's going to the #sharedobjects folder instead of the folder path on my server where the file is located. This might fix that part of the problem for SaveFileScrollingIssue.swf in my ruffle self-hosted. Going to check that out now. Meanwhile, the red up and down arrow buttons still need to be fixed in ruffle self-hosted though because they do not work like how they do in OG flash player.
