### ISSUE TITLE
dispatching event EventObject(EventObject { type: "change", class: flash.events::Event, ptr: 0x187e2b8 }) to handler FunctionObject(FunctionObject { ptr: 0x150dbe8, name: Ok("Main/menuSelect()") }) : Error: Error #2174: Only one download, upload, load or save operation can be active at a time on each FileReference.

### ISSUE THREAD

**Issue by BarbourSmith** [ruffle-rs/ruffle#16159]
### Describe the bug

I have a follow on to issue #15045 (huge thank you for the help there. 

Fixing that issue allowed me to open a file successfully and everything works perfectly, but now we have an issue on the other end with saving a file. When we try to save a file we get the error message:

`core/src/avm2/events.rs:428 Error dispatching event EventObject(EventObject { type: "change", class: flash.events::Event, ptr: 0x187e2b8 }) to handler FunctionObject(FunctionObject { ptr: 0x150dbe8, name: Ok("Main/menuSelect()") }) : Error: Error #2174: Only one download, upload, load or save operation can be active at a time on each FileReference.`

To replicate the issue with the following .swf file

[partkam.swf.zip](https://github.com/ruffle-rs/ruffle/files/15153421/partkam.swf.zip)

Click on insert and then circle (or any shape really)

<img width="1146" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/715f6dd2-1abb-44df-80a7-bdb7705f8ac7">

Then click File -> Save SVG File

<img width="1141" alt="image" src="https://github.com/ruffle-rs/ruffle/assets/9359447/89feece0-57da-4a35-9e5c-bf36318bae71">

The expected behavior would be that we would download a .svg file, but the error is preventing the download from happening.

Thanks! 

Happy to offer a bug bounty again if it motivates someone to be excited about this issue 😀 

I really appreciate the work yall are doing which is making it possible for us to bring this old open source project back to life.

### Expected behavior

A download of a .svg file to be triggered 

### Content Location

[partkam.swf.zip](https://github.com/ruffle-rs/ruffle/files/15153421/partkam.swf.zip)

### Affected platform

Online demo

### Operating system

OSX

### Browser

Firefox

**Comment by adrian17** [comment]
(Looks like this is https://github.com/ruffle-rs/ruffle/issues/14949 .)

**Comment by evilpie** [comment]
Yep, duplicate.
