### ISSUE TITLE
The Ritual: Yellow border bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#16204]
### Describe the bug

Yellow border randomly shows up when starting the game, seems to go away when clicking or tapping a certain spot.

![Screenshot_20240503_112721_Chrome](https://github.com/ruffle-rs/ruffle/assets/78768499/50830a0d-951d-4cf6-abf7-4a1a5ece0249)

### Expected behavior

Yellow border shouldn't show up when starting the game.

### Content Location

https://www.newgrounds.com/portal/view/682870?emulate=flash

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 124

**Comment by kjarosh** [comment]
Probably related to https://github.com/ruffle-rs/ruffle/issues/5443

Will investigate it tomorrow
