### ISSUE TITLE
text input still not working in Caravaneer

### ISSUE THREAD

**Issue by tanriol** [ruffle-rs/ruffle#1621]
Game: Caravaneer (downloaded from http://gamesofhonor.com/caravaneer as I could not try it in place due to CORS).
Player: Ruffle web demo (Nightly 2020-11-20).
Problem: when starting the game in story mode it's not possible to edit the character name in the character creation screen.
Possibly related problem: if I go with the default name, it's still visible on all screens after that, and that was not the case with Flash.

**Comment by Herschel** [comment]
Need to implement `TextField.type`

**Comment by Herschel** [comment]
Implemented in #1650 -- name text field still seems to stick on the screen, will investigate.

**Comment by Herschel** [comment]
Fixed in #1650 & #1652.
