### ISSUE TITLE
incorrect orientation of an UI element

### ISSUE THREAD

**Issue by tanriol** [ruffle-rs/ruffle#1622]
Game: Caravaneer (downloaded from http://gamesofhonor.com/caravaneer as I could not try it in place due to CORS).
Player: Ruffle web demo (Nightly 2020-11-20).
Problem: in the doctor menu, the character miniature is on its side (see screenshot) while it should be oriented normally.
![Screenshot_20201120_171535](https://user-images.githubusercontent.com/1027034/99809899-053c0980-2b54-11eb-8a50-8a71b691fbb5.png)
How to get to it: Story mode, click to dismiss the intro text, you automatically get to the starting city. Press the building with cross above the central square.

**Comment by Herschel** [comment]
The status bar is rotated sideways, and the game has code the flip the icons back to the correct direction:
```
      if(this._rotation == 90)
      {
         eval("Item" + i)._rotation = -90;
      }
```
Our calculation of _rotation is a little off/has some precision issues and returns 90.00000250447816` .
