### ISSUE TITLE
 [web] issue with full screen in context menu

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1624]
@relrelb,

many thanks for your pull request #1515.

I have tried to check the new functionality with https://ruffle.rs/demo/ (nightly 2020-11-20).

I’m afraid I don’t get either the full screen or the version info working.

Am I the only one experiencing this or have I hit a bug?

Many thanks for your help.

**Comment by relrelb** [comment]
Could you please explain in more detail?
The only thing that comes into my mind is a cache problem, so maybe try to reload the demo page with Ctrl+F5?

**Comment by parkerlreed** [comment]
Yeah showing up fine here in Chrome.

**Comment by Dinnerbone** [comment]
Which browser and what operating system are you using?

**Comment by ousia** [comment]
Many thanks for your replies, @relrelb, @parkerlreed and @Dinnerbone.

I’m using Firefox 66 for Fedora.

I have just realized that this may be too old for the new feature.

But even in that case, since the addition of full screen option, I cannot follow the nformation version. I was able to do that, as reported in issue #1508.

Or does the addition of the full screen option require also another Firefox version to follow the information version?

**Comment by Dinnerbone** [comment]
Very strange, it shouldn't impact that. If you view the web console (menu -> web developer -> web console), are there any warnings or errors after you try to bring the context menu up?

**Comment by ousia** [comment]
> Very strange, it shouldn't impact that. If you view the web console (menu -> web developer -> web console), are there any warnings or errors after you try to bring the context menu up?

I’m afraid there isn’t any warning or error in the web console.

But I have just tested it with latest Firefox (for latest Fedora) and both options work fine.

Just closing the issue myself.
