### ISSUE TITLE
Game Progress Not Saved Locally

### ISSUE THREAD

**Issue by dabuside** [ruffle-rs/ruffle#16241]
### Describe the bug

First of all, it's a a fantastic Flash emulator.
But Ruffle lacks the ability to save game progress locally, unlike the original Flash Player or older browsers. This results in lost progress upon returning to the main menu.

steps to reproduce
1. load game in Ruffle desktop version or javascript version [https://ruffle.rs/demo/](https://ruffle.rs/demo/)
2. start a game in a slot and play a field
3. return to main menu
4. the game progress lost

![image](https://github.com/ruffle-rs/ruffle/assets/7280952/c7c77662-e95b-4dd0-89af-7f14b5c1c8cc)

- The original Flash Player saves game progress to a specific location on the user's device (e.g.,`AppData\Roaming\Macromedia\Flash Player\#SharedObjects\MKUE5DPD\#localWithNet`). So game progress saved when app restart or system reboot.
- I confirm that older browsers supports flash can save progress locally.
- Ruffle currently lacks this functionality, leading to lost progress.

![image](https://github.com/ruffle-rs/ruffle/assets/7280952/158f2066-ed38-43b9-9bf8-d9603f0d2572)

This missing feature significantly hinders the user experience, as players cannot resume their progress after exiting the game.

### Expected behavior

The game progress should be saved.

### Content Location

GemCraft: Lost Chapter: Labyrinth
https://gameinabottle.com/_misc/giab-old-games.zip
open `gcl-gs.swf` with `flashplayer_29_sa.exe`

### Affected platform

Online demo

### Operating system

win11

### Browser

chrome 124

**Comment by Croworbit** [comment]
Ruffle does save locally, the functionality has bern added in for a while now

try to check your browser, I t may have a 'delete data on close' option checked
it could also be the game you're playing does not save or ruffle does not support at the moment (please attach any swfs that do not work)

**Comment by Croworbit** [comment]
additionally Ruffle does not store local data in the same location as flash.
the feature is not missing, but this game's saving may be broken on Ruffle

if you can right click on the game you can usually save the flash game save to your PC in the meantime

**Comment by n0samu** [comment]
Ruffle does save progress locally, but there is a bug preventing it from doing so in Gemcraft Labyrinth specifically. See #13773 - closing in favor of that issue.
