### ISSUE TITLE
Ultimate Flash Sonic : Collision Issues

### ISSUE THREAD

**Issue by vulpEclipse** [ruffle-rs/ruffle#1626]
Various collision and physics issues, especially notable in the second act of the first zone, in which the player can collide with and stand on background interior tiles that they should infact incur no collision with. In addition, it seems possible to jump out of S-Tunnels, which does not appear possible when using native flash.

Version:
Ruffle Nightly - 2020-11-18
used on Archive.org

**Comment by Toad06** [comment]
Thanks for reporting an issue.

I've been able to reproduce both of these bugs with the Flash Player though, so they don't seem to be exclusive to Ruffle.
![bug1](https://user-images.githubusercontent.com/14274782/99879693-b2735800-2c0e-11eb-8b29-5d7a37a36d14.png)
_(screenshot using Flash Player)_


A thing that doesn't work (and actually make the bug in the screenshot easier to get) is the corkscrew loops (Sonic unexpectedly falls):
![loop](https://user-images.githubusercontent.com/14274782/99879742-054d0f80-2c0f-11eb-95ba-4507f302fcd3.png)
_(screenshot using Ruffle)_

**Comment by vulpEclipse** [comment]
My apologies, then! I did try the game with normal flash player and was unable to reproduce it. Perhaps the version of the game I tested with on native flash difers to the one on archive?
