### ISSUE TITLE
Property softKeyboardRect not found on flash.display.Stage

### ISSUE THREAD

**Issue by falpi** [ruffle-rs/ruffle#16297]
### Describe the bug

Trying to run an Adobe Flex application generates the following error:
ERROR core\src\avm2\events.rs:428 Error dispatching event EventObject(EventObject { type: "creationComplete", class: mx.events::FlexEvent, ptr: 0x9f3b758 }) to handler FunctionObject(FunctionObject { ptr: 0x8238208, name : Ok("mx.controls::Alert$/static_creationCompleteHandler()") }) : ReferenceError: Error #1069: Property softKeyboardRect not found on flash.display.Stage and there is no default value.

I believe it depends on a partial implementation of what is necessary for the correct management of the "CreationComplete" event in the context of the "mx.controls.Alert" control.

### Expected behavior

No exception.

### Content Location

It's a complex application that cannot be run outside the enteprise environment because of early interaction with Electron runtime and integration web services. 

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 125

**Comment by kjarosh** [comment]
What version of Ruffle do you use? `softKeyboardRect` should be stubbed since nightly-2024-04-25

**Comment by falpi** [comment]
New Ruffle instance created (Version: nightly 2024-05-04 | WebAssembly extensions: ON | Used renderer: wgpu-webgl)

**Comment by falpi** [comment]
I apologize: actually until recently I was using an older self-hosted version. Now that I have switched to the Firefox extension the problem no longer occurs. I'll close the ticket.

**Comment by falpi** [comment]
I apologize: actually until recently I was using an older self-hosted version. Now that I have switched to the Firefox extension the problem no longer occurs. I'll close the ticket.
