### ISSUE TITLE
The game appears then goes black

### ISSUE THREAD

**Issue by Craozz** [ruffle-rs/ruffle#16294]
### Describe the bug

The game appears then goes black

### Expected behavior

The game appears then goes black

### Content Location

https://game24h.vn/tinh-diem/chiec-cau-cua-jerry-c145g742b16.html

### Affected platform

Desktop app

### Operating system

Windows 10 Enterprise

### Browser

Microsoft Edge Version 117.0.2045.31 (Official build) (64-bit)

**Comment by Lord-McSweeney** [comment]
Duplicate of #13263
