### ISSUE TITLE
add a presentation to the demo

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1629]
@Herschel.

I would love to add this talk (direct link: https://github.com/lhl/free_culture/raw/master/free_culture.swf [content licensed under CC BY-SA]) to the demo.

```
    {
      "location": "swfs/free_culture.swf",
      "title": "Free Culture",
      "author": "Lawrence Lessig",
      "authorLink": "https://www.lessig.org/",
      "type": "Presentation"
    }
```

But I’m afraid I don’t know where to add, since [ruffle-rs/demo](https://github.com/ruffle-rs/demo) seems to be an automatically generated repository.

This talk from the Open Source Conference 2002 in San Diego. I can only recommend watching it (about 30min long).

BTW, as far as I can tell (from a fast check with the demo site), this presentation has feature parity in both Ruffle and Flash.

Congratulations for the nice work.

**Comment by Herschel** [comment]
You should be able to make a PR to the demo repo, adding the SWF and change to swf.json, and it should be good; the nightly build should leave these files intact -- it does an amend commit that specifically avoids touching non-Ruffle related files.

**Comment by parkerlreed** [comment]
Funnily enough there's a bug with the movie. If you click pause and unpause it restarts the entire audio. Flash Player proper pauses correctly.

**Comment by ousia** [comment]
@parkerlreed, thanks for noticing this. I’d totally forgotten it.

This is caused because `Sound.position()` isn’t implemented yet (as I reported in #340).

I hope that, once PR #1445 is merged, `Sound.position()` could be implemented and the presentation would be ready to be added.

**Comment by ousia** [comment]
I posted an experimental version at https://www.free-culture.tk/fc.html.

**Comment by ousia** [comment]
Closing this issue myself.
