### ISSUE TITLE
Property setNamespace not found on String and there is no default value.

### ISSUE THREAD

**Issue by falpi** [ruffle-rs/ruffle#16298]
### Describe the bug

Trying to run an Adobe Flex application generates the following error:
ERROR core\src\avm2\events.rs:428 Error dispatching event EventObject(EventObject { type: "load", class: mx.rpc.soap::LoadEvent, ptr: 0xa362968 }) to handler FunctionObject(FunctionObject { ptr: 0x513260 , name: Ok("com.terna.utils::WebService/InternalLoadHandler()") }) : ReferenceError: Error #1069: Property setNamespace not found on String and there is no default value.

The custom function "com.terna.utils::WebService/InternalLoadHandler()" is nothing more than a handler of the "mx.rpc.soap::LoadEvent" event which should be invoked by the "mx.rpc.soap.mxml.WebService()" class when you want to invoke a SOAP WebService, at the time the WSDL is loaded, after the "loadWSDL" method has been executed.

The error also occurs when leaving the event handler empty, so it probably occurs right before or right after its invocation.

### Expected behavior

No exception and correct management of WSDL loading and parsing.

### Content Location

It's a complex application that cannot be run outside the enteprise environment because of early interaction with Electron runtime and integration web services.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 125

**Comment by falpi** [comment]
In fact at the moment I'm not using the self-hosted version but the firefox extension. The version is as follows:
New Ruffle instance created (Version: nightly 2024-05-04 | WebAssembly extensions: ON | Used renderer: wgpu-webgl)

**Comment by evilpie** [comment]
#16533 should fix this.

**Comment by evilpie** [comment]
@falpi can you test if it's working for you now?

**Comment by falpi** [comment]
Dear @evilpie , I just did a rebuild of the master and everything is fine! Communication via WS SOAP works. Congratulations for the solution and thanks for what you are doing with the Ruffle project! ❤️
