### ISSUE TITLE
Very tall flashes only render as pure white in the Windows Desktop version

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#1631]
Example flash: https://www.homestuck.com/flash/hs2/05492/05492.swf

This flash works perfectly in the web player. However, when opening it using ruffle.exe, nothing renders and you can only see the white background. You can still hear that the flash is working correctly based on the background sound effects.

Testing ruffle.exe nightly version 2020-11-20 on Windows 10.

**Comment by parkerlreed** [comment]
Noting that it does work on Linux

![image](https://user-images.githubusercontent.com/841440/99868551-73eb8800-2b91-11eb-8d18-9375dbe0dc15.png)

**Comment by Toad06** [comment]
I can't reproduce this issue on my PC (Windows 10); possibly a driver thing?

**Comment by MrCheeze** [comment]
Quite possibly, here's my hardware information as output by DxDiag. https://pastebin.com/3rdN4AiL

If this only happens in my particular hardware combination on the desktop version, though, then this seems pretty minor.

**Comment by Herschel** [comment]
Does this issue occur if you run with the dx12 backend vs the vulkan backend? (`-g dx12` on the command line)

**Comment by parkerlreed** [comment]
The edit makes it seems like yeah DX12 is working. Just Vulkan on Windows on Nvidia it seems. (If I'm reading everything correctly)
