### ISSUE TITLE
The Clockmaker: Broken Copy paste

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#16374]
### Describe the bug

As mentioned in the description and from testing, it seems like you can't copy and paste your finished story, just fill in the boxes with any words or just hit clock out, then try to highlight and copy your story.

### Expected behavior

Copy and paste should work.

### Content Location

https://www.newgrounds.com/portal/view/873121?emulate=flash

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 124

**Comment by kjarosh** [comment]
I debugged this a little and you actually _can_ copy and paste the story. It's just that the caret and selection is not being rendered, so that's a rendering issue here.

**Comment by kjarosh** [comment]
Just noticed that after invalidating cached bitmap, the selection is being rendered.

**Comment by kjarosh** [comment]
After https://github.com/ruffle-rs/ruffle/pull/16422 the selection is rendered, but there's still the issue of https://github.com/ruffle-rs/ruffle/issues/14713. The caret is neither being rendered in FP nor in Ruffle.

Note that until https://github.com/ruffle-rs/ruffle/pull/16418 is merged one has to use Shift+Left/Right or Ctrl+A to select the text.
