### ISSUE TITLE
Ultra Lag Since Last Update - Ride Sims - Crashes Webpage 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1639]
Since updating to the latest code with fullscreen everything seems to be running really slow. 

The worst / best example would be this sim / swf file. 

If you open the sim and turn the power on and turn the blocks on you can see how it all struggles and eventually the page will crash out. 

https://ridesims.com/sites/default/files/2020-11/MotorbikeAdventure_V1.2_0.swf

https://ridesims.com/ride-simulators/Motorbike-Adventure

**Comment by Herschel** [comment]
Unable to repro this -- what browser? Do you see anything in the dev console (F12)?

**Comment by JamesAllgood** [comment]
Chrome and Safari MacOS 

Target not found: Target=".." Base="_level0"
core.ruffle.7f6d216454b6a4a07936.js:1 Unimplemented property _quality
dt @ core.ruffle.7f6d216454b6a4a07936.js:1
__wbg_warn_d05e82888b7fad05 @ VM43:1
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f7524
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2de7ee
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f6660
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2d0437
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2efe04
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1cd941
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1b3f3c
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2af462
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2ab0ef
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1c62bd
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0xdd34
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2b33e0
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1e23d1
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0xfedf2
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1dd42f
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2e1c18
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1b9877
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f2c1d
_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he933ec52218c6d5f @ 85f5e4a29d83ee43a391.module.wasm:0x2f5b37
P @ core.ruffle.7f6d216454b6a4a07936.js:1
f @ core.ruffle.7f6d216454b6a4a07936.js:1
core.ruffle.7f6d216454b6a4a07936.js:1 Unimplemented property _quality
dt @ core.ruffle.7f6d216454b6a4a07936.js:1
__wbg_warn_d05e82888b7fad05 @ VM43:1
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f7524
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2de7ee
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f6660
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2d0437
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f5c6b
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1b6541
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x154038
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2b6e6e
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1f28b9
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x12d7b
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2b33e0
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1e23d1
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0xfedf2
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1dd42f
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2e1c18
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x1b9877
(anonymous) @ 85f5e4a29d83ee43a391.module.wasm:0x2f2c1d
_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he933ec52218c6d5f @ 85f5e4a29d83ee43a391.module.wasm:0x2f5b37
P @ core.ruffle.7f6d216454b6a4a07936.js:1
f @ core.ruffle.7f6d216454b6a4a07936.js:1
3VM43:1 error loading ruffle player into frame: Blocked a frame with origin "https://ridesims.com" from accessing a cross-origin frame.

**Comment by JamesAllgood** [comment]
**Just found the error that's causing this:** 

2/ruffle/core.ruffle.23a55957507c641be559.js:1 Unimplemented property _quality
dt @ /ruffle/core.ruffle.23a55957507c641be559.js:1
609[Violation] 'requestAnimationFrame' handler took <N>ms
 core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 462ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 488ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 460ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 459ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 451ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 449ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 478ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 454ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 472ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 474ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 465ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 438ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 430ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 430ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 427ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 430ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 431ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 435ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 432ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 1673ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 1128ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 443ms

 core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 445ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 449ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 457ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 448ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 452ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 463ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 463ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 448ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 457ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 444ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 451ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 430ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 443ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 439ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 438ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 442ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 432ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 439ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 436ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 433ms
core.ruffle.23a55957507c641be559.js:1 [Violation] 'requestAnimationFrame' handler took 2218ms
Core.ruffle.23a55957507c641be559.js:1

The previous AnimationFrame handler error continues in a never ending loop bogging down everything in addition to the rest of the errors on the page.
[Violation] 'setTimeout' handler took 72ms

**Comment by JamesAllgood** [comment]
this has improved since posting this. going to close this issue
