### ISSUE TITLE
[swfs.json] identifiers for simpler URLs

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1642]
I wonder whether it would be possible to add an `identifier` field to `swfs.json` in the demo, such as:

```
    {
     "identifier": "alien"
      "location": "swfs/alien_hominid.swf",
      "title": "Alien Hominid",
      "author": "Tom Fulp and Dan Paladin",
      "authorLink": "https://www.newgrounds.com",
      "type": "Game"
},
```

I wonder whether the identifier could be used to invoke the presentation directly in the URL, such as https://ruffle.rs/demo/?alien.

**Comment by Herschel** [comment]
We did support a `?file=blah.swf` back before swfs.json was added, but it was removed. I think it'd be nice to re-add it, e.g. `?file=alien_hominid.swf`, and do an `endsWith` check. Then no extra id parameter is needed.
