### ISSUE TITLE
"Sound.setVolume: Unimplemented"- Sounds continue to play at full volume after they should end, multiple games

### ISSUE THREAD

**Issue by JessFairbairn** [ruffle-rs/ruffle#1646]
I've come across this problem in two games:

- [FlyGuy](https://archive.org/details/flyguy_flash) (nearby objects will continue to make noise at full volume, rather than fading as you move away)
- [Nanaca Crash](https://archive.org/details/nanaca-crash_v110) (Intro menu music continues to play after a game begins, at the same time as in-level-music)

The warning `Sound.setVolume: Unimplemented` is printed in the javascript console. This is happening in both Firefox and Chromium, on Ubuntu 18.04

**Comment by ricardoseb** [comment]
I have the same problem, I have the audio files in mp3 format in a folder called audios, also I notice that if the audio is not played the animation does not continue.
These alerts are presented in my case:
![image](https://user-images.githubusercontent.com/31752537/99893363-e88bf880-2c5d-11eb-864c-3012d9677bba.png)

**Comment by GreenReaper** [comment]
This (fairly obviously) breaks in-game volume sliders - resulting in the sound being louder than intended when it is initially set at half, as is the case sometimes. Of course the user can always lower the sound outside the UI, but it is confusing if it doesn't work.

**Comment by Herschel** [comment]
Fixed by #2825.

**Comment by JessFairbairn** [comment]
Fantastic, thanks for your work everyone!
