### ISSUE TITLE
Helicopter Game crashes when clicking on text

### ISSUE THREAD

**Issue by fafrd** [ruffle-rs/ruffle#1647]
Helicopter Game (https://archive.org/details/helicoptergame_flash) will crash under the following conditions:

Start playing the game. Crash the helicopter.
In the ~3 seconds before the game automatically restarts, click on the number next to 'Distance' or 'Best' at the bottom of the screen.
The game will crash.

**Comment by parkerlreed** [comment]
This has already been reported

https://github.com/ruffle-rs/ruffle/issues/1607

Been fixed in master, archive.org just hasn't updated ruffle yet.

**Comment by Herschel** [comment]
I think archive.org just updated, so this should be good now.

**Comment by parkerlreed** [comment]
Be sure to clear cache before retrying. It was still crashing when trying from Chrome where I had loaded it before but worked fine in a fresh Firefox session.
