### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by psykzz** [ruffle-rs/ruffle#1648]
Happy to see this project, and tried it out on some old flash sites (in this case z0r.de)

https://z0r.de/7910 is an example of something that just doesn't load.

Using version: `ruffle nightly 2020-11-20`

**Comment by parkerlreed** [comment]
Here's the errors from desktop ruffle

```
[2020-11-21T22:35:07Z ERROR ruffle_core::library] Tried to instantiate non-registered character ID 0
[2020-11-21T22:35:07Z ERROR ruffle_core::display_object::movie_clip] Unable to instantiate display node id 0
```

**Comment by system2k** [comment]
Same exact issue occurs with this SWF:
[https://thebest404pageeverredux.com/swf/49_Racing.swf](url)

> Tried to instantiate non-registered character ID 0
> Unable to instantiate display node id 0

**Comment by Toad06** [comment]
Thanks for your bug report.

The animation is actually a video. Ruffle has no video implementation at all currently (cc #723).
