### ISSUE TITLE
One Page Can't play 2 Flashes?

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1651]
If I put 2 flashes on a single page, Ruffle crashes. So it's not allowed to use 2 Flashes on the page or this is a bug?

**Comment by Herschel** [comment]
If this is the case, it's a bug; do you have an example page?

**Comment by zohebnsr** [comment]
Sorry to trouble you. Just uploaded the latest build and seems to be working fine. :)
