### ISSUE TITLE
Ruffle Error on https://happyhopper.org/

### ISSUE THREAD

**Issue by GemmyInSpace** [ruffle-rs/ruffle#16548]
# Error Info
Error name: TypeError
Error message: NetworkError when attempting to fetch resource.

# Player Info
Allows script access: false

# Page Info
Page URL: https://happyhopper.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by n0samu** [comment]
This is a problem with the website, they broke their CORS setup for WASM files. Please try contacting the site owner or playing the game on a different site.
