### ISSUE TITLE
Extension cannot be installed on Chromium 87.0.4280.66 on Arch Linux

### ISSUE THREAD

**Issue by patrakov** [ruffle-rs/ruffle#1656]
I have tried to follow the official instructions from the bottom of https://ruffle.rs/

I have successfully enabled developer mode, unpacked the zip, and selected the folder where I unpacked it. Result: "Локализация используется, однако в манифесте не указан атрибут default_locale." = "Localization used, but default_locale wasn't specified in the manifest." Of course it is there - maybe in the wrong place?

**Comment by parkerlreed** [comment]
Maybe try setting the locale to en_US.UTF-8 for Chrome to test? Working on the same distro and browser combination here.

**Comment by patrakov** [comment]
Same error.

![image](https://user-images.githubusercontent.com/2943163/99928537-46f2cd00-2d6b-11eb-879c-87b8aa4de3fc.png)

**Comment by parkerlreed** [comment]
What's directly under the ~/ruffle folder file wise?

**Comment by patrakov** [comment]
```
[aep@aep-haswell ruffle]$ ls
128.png  328.png  85f5e4a29d83ee43a391.module.wasm  en     ja              _locales  manifest.json  popup.js   ruffle.js
16.png   32.png   core.ruffle.js                    es     LICENSE_APACHE  logo      messages.json  README.md  settings.htm
180.png  48.png   dist                              icons  LICENSE_MIT     lv0.js    popup.html     ru         settings.js
```

**Comment by parkerlreed** [comment]
Looks like you extracted it without keeping the folder structure. There should be subfolders with those other files within.

![image](https://user-images.githubusercontent.com/841440/99929542-9ad5c580-2d1b-11eb-9ae5-33c0d52305d0.png)

Try removing the files there and just running `unzip` on the file in the same directory

```
[aep@aep-haswell ruffle]$ rm *
[aep@aep-haswell ruffle]$ unzip path/to/ruffle_extension.zip
```

**Comment by patrakov** [comment]
Done, it works now.
