### ISSUE TITLE
Farm Loops Blast - Stuck on Preloader

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#16575]
### Describe the bug

There is a similar bug posted here with the same assests not being loaded 
Failed to load resource: net::ERR_CONNECTION_CLOSED https://api.configar.org/cf/pb/1/settings/0/0/abdc3bb534880d9606d4de23e5ff3619?type=live&nocache=213&version_id=default

The question is can it be bypassed?

### Expected behavior

Load and Run

### Content Location

https://www.spiele-umsonst.de/azad/downloads/flashgames/farmloopsblast.swf

### Affected platform

Desktop app

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Games that rely on the Spil Games Flash API (api.configar.org) no longer work on the live web because the API has been taken down. The game works fine in Flashpoint though: https://ooooooooo.ooo/static/?895ec1eb-81e5-4a80-8675-27049e5ffaf2
