### ISSUE TITLE
HitBox: Tab key should not highlight items on the stage

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#16589]
### Describe the bug

In [HitBox](http://www.notdoppler.com/hitbox.php), pressing the Tab key on the main menu highlights items.

### Expected behavior

In Flash Player, once you close the ad in the bottom-left corner (which is a separate movie), pressing the Tab key does not highlight anything. That's because the main menu sets `stage.tabChildren = false`.

### Content Location

Page URL: http://www.notdoppler.com/hitbox.php
SWF URL: http://i.notdoppler.com/files/hitbox.swf

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by kjarosh** [comment]
`stage.tabChildren = false` is ignored:

https://github.com/ruffle-rs/ruffle/blob/091aa2361f989c067a922b0e9603f78050b325ba/core/src/avm2/globals/flash/display/Stage.as#L151-L154

The test [tab_ordering_properties](https://github.com/ruffle-rs/ruffle/tree/091aa2361f989c067a922b0e9603f78050b325ba/tests/tests/swfs/avm2/tab_ordering_properties) suggests that FP ignores setting `tabChildren`, however that may be conditional.

**Comment by kjarosh** [comment]
Okay, I think figured this out. Turns out that `stage.tabChildren` always returns `true`, and `stage.tabChildren = ...` sets `tabChildren` of AVM2's root, not the stage. That probably explains why some of the items are tabbable.
