### ISSUE TITLE
Poor font rendering

### ISSUE THREAD

**Issue by falpi** [ruffle-rs/ruffle#16598]
### Describe the bug

The font rendering is terrible and the characters do not respect the bold style and expected dimensions, causing the visual alignments of the controls to fail. 

Attached is a comparison between the output of the application with Tahoma 11px font, on the Flash Player runtime and on Ruffle.

![immagine](https://github.com/ruffle-rs/ruffle/assets/44287719/fb4e84e5-7a51-42b0-92eb-8a6fafa3f0c7)

### Expected behavior

One would expect font rendering to follow the pixel-precise rendering typical of the Adobe Flash Player runtime on Firefox (unfortunately on Chrome, following the removal of the flag to disable DirectX rendering, font rendering was blurry even with the Flash Player).

### Content Location

It's a complex application that cannot be run outside the enteprise environment because of early interaction with Electron runtime and integration web services.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 126.0.1

**Comment by Croworbit** [comment]
a likely issue is that the font is not embedded in the SWF or that the font is not installed

**Comment by falpi** [comment]
Hi @Croworbit , the Tahoma font is present by default on Windows 10, even in the bold style. I also tried embedding it with no luck. I'm not very familiar with font embedding.. can you show me a sample code snippet to embed a font the correct way for Ruffle? Thank you

**Comment by falpi** [comment]
I tried to create the simplest MXML application possible with Flash Builder 4.6, with all the default settings and a single text label, without specifying any special fonts. The rendering is always blurred.

**Comment by evilpie** [comment]
We can't support device fonts on the web. We have a tutorial on how to work around this by providing the font yourself: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-do-i-change-the-fonts-used-by-flash-on-my-website

**Comment by falpi** [comment]
Thank you @evilpie ... I managed to create an Embedded version of Tahoma font... It render... but always blurry... There is a chance to obtain in some way a clean pixel-precise rendering ? 
![immagine](https://github.com/ruffle-rs/ruffle/assets/44287719/4a29220a-b45b-4597-abc6-c91dcf4f1725)

**Comment by n0samu** [comment]
Pixel-perfect font rendering would be very difficult, the project has much more pressing issues to focus on at the moment. The text is perfectly readable, after all

**Comment by falpi** [comment]
I understand. I hope that sooner or later there will be time to improve the rendering because for an enterprise application it is difficult to read.

**Comment by rotaercz** [comment]
I discovered Ruffle a few days ago and I'm pleasantly surprised how well it works. I just put my old www.typographist.com site back online. (Guestbook is not hooked up yet)

I also noticed my fonts aren't crisp. When I made my site I painstakingly made sure every single font xy position ended up as a perfect integer using bitmap fonts. Is there a way to make it look crisp or is it still a work in progress?

**Comment by Croworbit** [comment]
> I discovered Ruffle a few days ago and I'm pleasantly surprised how well it works. I just put my old [www.typographist.com](http://www.typographist.com) site back online. (Guestbook is not hooked up yet)
> 
> I also noticed my fonts aren't crisp. When I made my site I painstakingly made sure every single font xy position ended up as a perfect integer using bitmap fonts. Is there a way to make it look crisp or is it still a work in progress?

you should open a new issue, since this one was closed.
then they can determine if they want to keep open the new one
