### ISSUE TITLE
Game loads on desktop Windows app but won't load on self-hosted version

### ISSUE THREAD

**Issue by Shadic78** [ruffle-rs/ruffle#16629]
### Describe the bug

I have a game that was made with [Stencyl](https://stencyl.com/) v3.4 in 2018. (ActionScript 3)

The desktop app of Ruffle freezes for a few seconds before loading the game but after that everything works fine. Meanwhile, in the web self-hosted version of Ruffle the game won't load and will throw this error:

`Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2a95568 }) to handler FunctionObject(FunctionObject { ptr: 0x2a95290, name: Ok("Universal/onAdded()") }) : RustError("A script in this movie has taken too long to execute and has been terminated.")`

Followed by thousands of the next error:

`Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x21aee10 }) to handler FunctionObject(FunctionObject { ptr: 0x2f84128, name: Ok("com.stencyl::Engine/onUpdate()") }) : TypeError: Error #1009: Cannot access a property or method of a null object reference.`

### Expected behavior

The game should run on both versions of Ruffle. (Windows app and web self-hosted)

### Content Location

[JonathanQuest.zip](https://github.com/user-attachments/files/15741609/JonathanQuest.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Microsoft Edge 125, Google Chrome 122

### Additional information

Windows version tested:
- ruffle-nightly-2024_06_07-windows-x86_64 (v0.1.0)

Web self-hosted version tested:
- 0.1.0-nightly.2024.06.06

**Comment by Lord-McSweeney** [comment]
The game runs fine on the demo (https://ruffle.rs/demo/) for me. Can you show the first few errors of the error log?

**Comment by Shadic78** [comment]
This is the console log of the self-hosted version

![image](https://github.com/ruffle-rs/ruffle/assets/43481488/54363aed-e5aa-44bd-9b61-ee716a2a2e49)

**Comment by Lord-McSweeney** [comment]
The first log explains it- the game took too long to load. There's a setting `maxExecutionDuration` that you can change to allow the game to load for longer before Ruffle stops it, check the documentation: https://ruffle.rs/js-docs/master/interfaces/BaseLoadOptions.html#maxExecutionDuration

**Comment by Shadic78** [comment]
> The first log explains it- the game took too long to load, so Ruffle terminated the loading. There's a setting `maxExecutionDuration` that you can change to allow the game to load for longer before Ruffle stops it, check the documentation: https://ruffle.rs/js-docs/master/interfaces/BaseLoadOptions.html#maxExecutionDuration

This fixes the error, thanks.
