### ISSUE TITLE
Missing functionality Portal Game otherwise works great

### ISSUE THREAD

**Issue by rufflue** [ruffle-rs/ruffle#1662]
the portal game works great on ruffle except some minor issues

the archive.org version the instructions never show up and there is this annoying beeping. 
[https://archive.org/details/portal_flash_version](url)
![download](https://user-images.githubusercontent.com/64484245/99929600-6c53ec80-2d13-11eb-8c53-73b87d7dbabd.png)

the one used with the offical flash player zero issues.
[https://armorgames.com/play/107/portal-the-flash-version?t=1606105735](url)
![download (1)](https://user-images.githubusercontent.com/64484245/99929665-a1603f00-2d13-11eb-90e2-43873aea05e5.png)

**Comment by relrelb** [comment]
The beeping issue was fixed by #2825, so only the text issue remains.
