### ISSUE TITLE
Grow Island: String path in removeMovieClip doesn't resolve

### ISSUE THREAD

**Issue by relrelb** [ruffle-rs/ruffle#1665]
In [Grow Island](http://www.eyezmaze.com/game/grow_island.swf), when hearts are shown in the "Environmental" step of the [solution](http://www.mostlymuppet.com/2007/09/19/grow-island-walkthrough/), there is a heavy lag.

In DefineSprite 1044/frame 1/PlaceObject2 1043/onClipEvent(enterFrame), `removeMovieClip` is called with `this` as a string and not as an object, like in the rest of the code. As a result, [`action_remove_sprite`](https://github.com/ruffle-rs/ruffle/blob/eb0b16790c79d1740009ab202216ec71c5e23c5f/core/src/avm1/activation.rs#L1799) mistakenly doesn't recognize the target as a movie clip, and doesn't remove it, causing a lag. Adding `GetVariable` after `Push "this"` works as expected and removes the lag.

I'm not sure how to fix it, but it seems that invoking [`resolve_target_path`](https://github.com/ruffle-rs/ruffle/blob/eb0b16790c79d1740009ab202216ec71c5e23c5f/core/src/avm1/activation.rs#L2459) from [`resolve_target_display_object`](https://github.com/ruffle-rs/ruffle/blob/7ac53be24fe3de0a1a75671c845c1356742fd48e/core/src/avm1/activation.rs#L2421) with `first_element` set to `true` solves the issue.

**Comment by Herschel** [comment]
Trying a simple test with `removeMovieClip("this");` doesn't seem to remove the clip; not sure what the difference is, so requires some more investigation.

[removethis.zip](https://github.com/ruffle-rs/ruffle/files/5585927/removethis.zip)

**Comment by BurstingBrain** [comment]
With the 13th of January 2021 release as a Firefox extension it works flawlessly for me on Windows 10

**Comment by relrelb** [comment]
While most of the time the game works properly, there are some situations like mentioned above which cause lags.

Unfortunately, this bug still occurs.

**Comment by relrelb** [comment]
Apparently, this is fixed between [nightly-2021-01-16](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-01-16) and [nightly-2021-01-17](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-01-17). However, the only commit between them (c2b768c453f281a988c71a829e7a71bb106302fa) doesn't seem related.
Also, this occurs only on web.
@Herschel Do you have any idea how it was resolved?

**Comment by Herschel** [comment]
My guess would be #2636 since this was an obfuscated SWF and I believe the code was in an `onClipEvent` handler, but haven't bisected myself.
