### ISSUE TITLE
web: Cannot paste from context menu

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#16678]
### Describe the bug

Unfortunately, browsers only allow reading the clipboard contents while handling the [paste event](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event), which is only fired after pressing Ctrl-V or pressing Paste in the browser's native context menu. So Ruffle handles the JS paste event, saving the pasted text to the web UI backend's `clipboard_content` variable; [here's how I implemented it in #11059](https://github.com/ruffle-rs/ruffle/pull/11059/files#diff-7e944172be0a590e61b7f2453657708dcc8233b5d19d6d2749a24fcfde682ab9R33). But clicking the Paste button in Ruffle's (non-native) context menu does not fire the JS paste event, so Ruffle's `clipboard_content` variable is not updated, and the text that shows up is the stale/outdated value of `clipboard_content`. This doesn't cause problems if you're pasting text copied previously from Ruffle, because Ruffle also updates the `clipboard_content` variable when you copy to the clipboard. But if you're pasting text from another location/tab/application, you'll notice that it does not work correctly:

https://github.com/ruffle-rs/ruffle/assets/71368227/93f33515-6fd6-41dd-a3ba-fec3ae7eec47

### Expected behavior

Pasting text using the context menu should always work.

### Content Location

I was testing with this SWF: http://i.notdoppler.com/files/golphysics.swf

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Firefox 126

### Additional information

The problem also occurs in Chromium/Edge. I found a [tutorial on web.dev](https://web.dev/patterns/clipboard/paste-text/) which seems to bring up a special native context menu in Firefox that allows clipboard pasting from a custom button (with an extra, somewhat nonintuitive step). But it doesn't seem to work in Chromium/Edge. On the other hand, pasting in Google Docs works in Chromium/Edge but not Firefox, but I haven't looked into how that is implemented.

Edit: It looks like this implementation works in all browsers, but in Firefox it still spawns the extra context menu you need to click, and in Chromium it requests clipboard access which the user needs to allow.
https://stackoverflow.com/questions/50633601/is-it-possible-to-paste-from-clipboard-onclick-in-javascript

**Comment by Croworbit** [comment]
when it asks for clipboard, does one get to choose what in the clipboard is revealed? or is it all exposed?

**Comment by kjarosh** [comment]
> when it asks for clipboard, does one get to choose what in the clipboard is revealed? or is it all exposed?

Upon giving access, the whole clipboard is revealed.

My testing shows that Firefox asks for permission every time the clipboard contents change (with a menu pop-up), whereas Chromium asks once and then the website has either full access to the clipboard (even if it changes), or no access at all.

**Comment by n0samu** [comment]
However, you'll still be able to press Ctrl-V to paste if you don't want to give the website full access to your clipboard in a Chromium-based browser.
