### ISSUE TITLE
Regression in z0r.de 7140 pokemon animation

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#16670]
### Describe the bug

Displacement filter doesn't work properly now, i found root of the problem in nightly build 2024_02_02 (looks like wgpu with change bitmapdraw)

![image](https://github.com/ruffle-rs/ruffle/assets/38821724/c9aa0510-8bb1-425e-a6e3-f52f5536767f)

### Expected behavior

nightly build 2024_02_01
![image](https://github.com/ruffle-rs/ruffle/assets/38821724/e1141bad-a982-409b-af5b-fbd77953493e)

### Content Location

https://z0r.de/7140

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Browser

Firefox Nightly 128.0a1

**Comment by waspennator** [comment]
I can also confirm this happens on my S22 too.

**Comment by torokati44** [comment]
Regressed by https://github.com/ruffle-rs/ruffle/commit/bac78442fca34ce912bf7c4155f9e1235ab1a8ad, which was part of https://github.com/ruffle-rs/ruffle/pull/15032 (@Dinnerbone).

**Comment by waspennator** [comment]
Still broken as of latest nightly.

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/19066
