### ISSUE TITLE
Unstable input in Numeric Stepper

### ISSUE THREAD

**Issue by rkontra** [ruffle-rs/ruffle#16684]
### Describe the bug

The desired numeric stepper input values are not being retained and the values fluctuate not allowing the desired input. This is occurring with latest release of the ruffle.js. I am not sure when this issue was introduced to the ruffle code base, but the ruffle.js from February 23, 2022 does not have this issue.

### Expected behavior

When the numeric stepper value is increased or decreased using the UI it should either increment by 1 or decrement by 1 and value should only change by the user interacting with UI.

### Content Location

Please vis the following url: [https://udico.co/dct/die-configuration-tool-testing](https://udico.co/dct/die-configuration-tool-testing). The password to access this page is 'ruffle'

### Affected platform

Desktop app

### Operating system

macOS Sonoma

### Browser

Safari

### Additional information

I will be trying newer versions of the ruffle on our stable application to see at what date it breaks.

**Comment by Dinnerbone** [comment]
Bisected to 516e10ae26c0386da98bc494774e516e1bfe023d
You should be able to use 2024-06-03 for now

**Comment by rkontra** [comment]
***@***.***_1e79c141-a8e6-4c0a-b66f-9ba53516d522.png]   From the desk of Richard Kontra
an ISO-9001:2015 Company - Founded 1940 About Us<https://udico.co/company/about-us>     Products<https://udico.co/products/products>    Sustainability<https://udico.co/company/sustainability><https://www.uniteddie.com/design.html>

I can confirm that the nightly download for 2024-06-03 does not have this issue.

Regards,
Rick


Richard Kontra
IT Engineer

Tel: 800-428-5462
Fax: 201-997-3297
Mail: ***@***.******@***.***>
***@***.***>
This message and any attachments are solely for the intended recipient. If you are not the intended recipient, disclosure, copying, use or distribution of the information included in this message is prohibited -- Please immediately and permanently delete.
On Jun 11, 2024, at 11:04 AM, Nathan Adams ***@***.***> wrote:


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>



Bisected to 516e10a<https://github.com/ruffle-rs/ruffle/commit/516e10ae26c0386da98bc494774e516e1bfe023d>
You should be able to use 2024-06-03 for now

**Comment by kjarosh** [comment]
Should be fixed in [2024-06-13](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-06-13).
