### ISSUE TITLE
Play button positioning is almost always off-center

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1669]
[Example 1](https://www.dell.com/html/us/products/ces/) - [Image](https://user-images.githubusercontent.com/58399748/100007261-d31be900-2d99-11eb-8ff9-7b7f319a5818.png)
[Example 2](http://www.nick.com/games/data/spongebob/sb_trailsnail/index.html) - [Image](https://user-images.githubusercontent.com/58399748/100007262-d3b47f80-2d99-11eb-8d77-12a3b4a904b8.png)

Tested on Firefox Developer Edition with the Ruffle extension.

**Comment by aswiseman** [comment]
Yes - seems to be the case everywhere (I've tested on my site using web assembly for Chrome on Windows & iPadOS, Firefox on Windows/iPadOS/Android 11.) It would be nice to fix this :-)
