### ISSUE TITLE
Ruffle Error on https://freetennis.org/

### ISSUE THREAD

**Issue by robotiaproject** [ruffle-rs/ruffle#16705]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at n.fetch (chrome-extension://nimlmejbmnecnaghgmbahmbaddhjbecg/libs/requests.js:1:4065)
    at chrome-extension://nimlmejbmnecnaghgmbahmbaddhjbecg/executers/vi-tr.js:1:1800
    at new Promise (<anonymous>)
    at fetch (chrome-extension://nimlmejbmnecnaghgmbahmbaddhjbecg/executers/vi-tr.js:1:1771)
    at https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:67050
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:66977)
    at https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://turbo.freevideogames.org/includes/js/flash-emulator/ruffle.js:1:35276)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freetennis.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by TemaisgameNoobas** [comment]
why is the Ruffle build from 2020?? you should update it and try it on the newest version

**Comment by Croworbit** [comment]
This website uses a version of ruffle from 2020, thats 4 years out of date!

they broke CORS, and they need to update their site and Ruffle. let them know!

**Comment by danielhjacobs** [comment]
According to @n0samu on Discord, freevideogames fixed their sites, so this issue should be resolved.

If it comes back, do note that it is an issue on the site's end and you should contact the site owners directly.
