### ISSUE TITLE
The Last Stand 2

### ISSUE THREAD

**Issue by NBKRedSpy** [ruffle-rs/ruffle#1671]
The Last Stand 2 has the following issues vs native flash.

Pausing:  The game will occasionally pause for 2+ seconds when running.  Later it will pause for 10+ seconds.

Rendering issue:  When using the chain saw or UMP-5, There is a Yellow rectangle rendered when firing.  I think it is supposed to be a muzzle flash / weapon effect.

Video Flashing:  The intro video flashes instead of playing.

Zombies disappear.  Some Zombies will disappear.  Shooting will show blood effects as if they are there.

https://armorgames.com/play/1443/the-last-stand-2

**Errors listed from the extension:**
Cannot delete property onEnterFrame from Undefined
Cannot enumerate Undefined
Object method gameStopStart is not callable
Object method setVolume is not callable
RemoveSprite: Source is not a movie clip
Sound.attachSound: Sound 'sound_chainsawFire' not found
Sound.attachSound: Sound 'sound_chainsawReload' not found
Sound.attachSound: Sound 'sound_dogDeath_2' not found
Sound.attachSound: Sound 'sound_dogDeath_3' not found
Sound.attachSound: Sound 'sound_dogDeath_4' not found
Sound.attachSound: Sound 'sound_dogDeath_5' not found
Sound.attachSound: Sound 'sound_hitChainsaw2' not found
Sound.attachSound: Sound 'sound_hitHead2' not found
Sound.attachSound: Sound 'sound_revolverReload' not found
Sound.attachSound: Sound 'sound_zombieDeath_10' not found
Sound.attachSound: Sound 'sound_zombieDeath_11' not found
Sound.attachSound: Sound 'sound_zombieDeath_6' not found
Sound.attachSound: Sound 'sound_zombieDeath_7' not found
Sound.attachSound: Sound 'sound_zombieDeath_8' not found
Sound.attachSound: Sound 'sound_zombieDeath_9' not found
Sound.getVolume: Unimplemented
Sound.start: No sound is attached
Stage.showMenu: unimplemented
System.security.allowDomain() not implemented
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
Tried to instantiate non-registered character snubnose_Icon
Tried to instantiate non-registered character survivorHand2
Tried to instantiate non-registered character survivorHand3
Tried to instantiate non-registered character undefined_Icon
Unable to attach 'snubnose_Icon'
Unable to attach 'survivorHand2'
Unable to attach 'survivorHand3'
Unable to attach 'undefined_Icon'
Uncaught ReferenceError: obfuscated_event_prefix is not defined
Uncaught RuntimeError: unreachable
Unhandled FSCommand: allowscale
Unimplemented property _quality
panicked at 'called `Result::unwrap()` on an `Err` value: "WebGL: Error in renderbuffer_storage_multisample (color): 1286"', render/webgl/src/lib.rs:739:35 Stack: Error

**Comment by Toad06** [comment]
Thanks for this bug report!

I think most of the rendering issues are related to unimplemented filters.

The most annoying thing is that the game panicks in the recent nightly builds (>= 2020-11-28) just after a few seconds of gameplay, possibly the "zombies disappearing" bug which turns into something worse:
`panicked at 'called Option::unwrap() on a None value', core\src\display_object\container.rs:779:18`

I tried to bisect, but had to skip most of the commits, unfortunately. However, compiling with 6e565d4da26bbbee15dde1f4129b81d713a8c615 surprisingly shows none of these problems.

**Comment by dginovker** [comment]
Working link to the game: https://games.crazygames.com/en_US/the-last-stand-2/index.html

(Issues mostly still present per 0.1.0.544)

**Comment by Lord-McSweeney** [comment]
None of the issues appear to be present anymore (0.1.0.703), except for unimplemented blend modes (especially blur).

**Comment by NBKRedSpy** [comment]
Looks correct.  The remaining issue is the flickering videos and pause menu not being visible.  Maybe that is the blend items that were mentioned?

I was able to test with the chainsaw, but not the UMP yet.  It looked correct.

Performance can get to be pretty choppy here and there.

**Comment by Lord-McSweeney** [comment]
With Dinnerbone's latest optimizations, as well as #9134, all of the issues may be fixed, including the performance.

**Comment by Lord-McSweeney** [comment]
One issue remaining is that the buttons in the main menu should be blurred until you hover over them, while they are currently not.

**Comment by Lord-McSweeney** [comment]
Last remaining issue is previously mentioned filter effects.

**Comment by Lord-McSweeney** [comment]
Closing as everything looks almost identical to Flash at this point.
