### ISSUE TITLE
Epos - Frozen on title screen menu

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#16717]
### Describe the bug

Epos currently freezes on the the title screen menu. Console output:

WARN core/src/stub.rs:144 Encountered stub: AVM2 flash.display.Loader.load() addChild at the correct time
ruffle_web-wasm_extensions.js:1190 

WARN core/src/stub.rs:144 Encountered stub: AVM2 flash.display.Loader.unload()
ruffle_web-wasm_extensions.js:1190 

ERROR core/src/display_object/movie_clip.rs:2743 Error occurred when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: stop)

### Expected behavior

Expected behavior is for the menu to be able to advance past the title screen.

### Content Location

https://www.newgrounds.com/portal/view/540610/format/flash?emulate=flash

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome 125.0.6422.142 (Official Build) (64-bit)

**Comment by adrian17** [comment]
Hmm, it appears to work for me.

Just to be sure, were you interacting with the keyboard? According to the description:
> NOTE: THIS GAME IS ENTIRELY KEYBOARD-CONTROLLED. Do not mistake a lack of response upon clicking on "New Game" as the game freezing on you, because this game does not allow mouse input

**Comment by TomFulp** [comment]
I was indeed using the mouse... I should have read the author comments! I turned on Ruffle for this game now.
