### ISSUE TITLE
Pulling flash game from Kongregate

### ISSUE THREAD

**Issue by MiyagiGames** [ruffle-rs/ruffle#1672]
I currently embed flash games on my site from Kongregate. Here's a sample link - https://smallpondgames.com/puzzles/n3wton/

After I added the Ruffle script, I receive two errors (pasted below) that I'm not sure how to fix. The flash games work on the site without the Ruffle script (and if the flash plugin is allowed on your browser).  Any ideas on how to fix this issue?

I think the idea of saving Flash is great, but I'm not sure it will be feasible if there are too many hurdles to jump. Let me know if there's anyway to help.

Thanks!

Error 1:
Access to fetch at 'https://external.kongregate-games.com/gamez/0000/4041/live/embeddable_4041.swf' from origin 'https://smallpondgames.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Error 2:
ruffle.js:1 Refused to load the script 'https://smallpondgames.com/wp-content/themes/myarcadetheme/js/ruffle/ruffle.js' because it violates the following Content Security Policy directive: "script-src https://cdn.ampproject.org/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by Herschel** [comment]
Unfortunately, security restrictions of modern web browsers prevent Ruffle from loading data from a different domain by default. These restrictions did not exist in the original Flash Player, but Ruffle is at the mercy of the browser itself.

You must either a) store the SWF on your own domain, or b) the domain you are loading from must respond [with proper CORS headers](https://enable-cors.org/index.html) to allow the request.

See also #1500,

**Comment by MiyagiGames** [comment]
Thanks for the response. That makes sense.  Might be a futile effort, but I guess I can try contacting Kongregate and ask them to respond with proper CORS headers.
