### ISSUE TITLE
Gray background for RatherGood "katjusha.swf"

### ISSUE THREAD

**Issue by digamejh** [ruffle-rs/ruffle#1674]
See attached file.

Thank you!

[katjusha.zip](https://github.com/ruffle-rs/ruffle/files/5586389/katjusha.zip)

**Comment by Toad06** [comment]
Thank you for reporting an issue.

The background (as displayed in the official Flash Player) is actually a video. Ruffle has no video implementation at all currently, so it only shows the SWF background color.
I'm going to close this in favor of #723.

Thanks again.
