### ISSUE TITLE
Loading delay for hosted flash game

### ISSUE THREAD

**Issue by MiyagiGames** [ruffle-rs/ruffle#1675]
I'm hosting a swf on my site. When I use the flash plugin from the Chrome browser, the page works as expected.

When I try loading the site with the Ruffle script included (and flash plugin disabled in browser), the page takes a long time to load. Page actually seems like it's frozen for about 10 seconds (cannot scroll, click, anything). 

After 10 seconds, the game loads fine.  I don't see any errors in the console.

Here's a link to my site. 
https://smallpondgames.com/uncategorized/test-flappy-bird/

Any ideas what might be causing this? Thanks!

**Comment by Herschel** [comment]
Thanks for the report, we unfortunately hang the browser for some time when loading certain SWFs currently. Closing in favor of #1338.
