### ISSUE TITLE
Content cropped left and right

### ISSUE THREAD

**Issue by fkohrt** [ruffle-rs/ruffle#16775]
### Describe the bug

The simulation appears cropped when run with Ruffle.

![Screenshot from 2024-06-19 04-50-31](https://github.com/ruffle-rs/ruffle/assets/12914806/6cbd4f8a-996d-4acc-8f57-6590768f3498)

### Expected behavior

A full view of the lock and controls.

![mhVisualizer_V2 1_p_screenshot](https://github.com/ruffle-rs/ruffle/assets/12914806/c2829af3-6e6a-4ff6-9c81-4338cd40d699)

### Content Location

http://visualizer.theopensourcelock.org/

https://archive.org/details/mhVisualizer_V2.1_p

https://github.com/mh-/AxisVisualizer

### Affected platform

Online demo

### Operating system

Fedora Linux 40

### Browser

Mozilla Firefox 126, Chromium 125

**Comment by Lord-McSweeney** [comment]
Running with `--letterbox off` and resizing the window displays the whole content

**Comment by fkohrt** [comment]
I used the [preview image from archive.org](https://archive.org/serve/mhVisualizer_V2.1_p/mhVisualizer_V2.1_p_screenshot.gif) and for Flash Player 32 I need to resize the window in order to see the full content.

**Comment by Lord-McSweeney** [comment]
Selfhosted supports the letterbox config option already, if you want you can open a separate feature request issue for the web demo.
