### ISSUE TITLE
Hands of War 3 Item box persisting

### ISSUE THREAD

**Issue by Charumu** [ruffle-rs/ruffle#16777]
### Describe the bug

When player hovers over or clicks certain items in shops or as quest rewards their information box persists after cursor no longer being over the item. the only ways to fix it is by exiting to main menu and loading save or restarting game as a whole.
![obraz](https://github.com/ruffle-rs/ruffle/assets/170186282/4d2193ec-ab67-4f42-84cc-626f8dcdd787)

### Expected behavior

Expected behaviour is that information box of it disappears after cursor is no longer over it.

### Content Location

I lauched the game by using flashpoint nano which launches with ruffle by using this entry from their database:
https://flashpointproject.github.io/flashpoint-database/search/#3e74dcc3-9ced-dbc5-97e1-16416e919635

### Affected platform

Desktop app

### Operating system

Nobara 39 x86_64

### Additional information

I simply downloaded flashpoint-nano and launched it with this command:
flashpoint-nano-master$ ./flashpoint.sh 3e74dcc3-9ced-dbc5-97e1-16416e919635
          directory                        command

**Comment by n0samu** [comment]
@Charumu can you provide detailed steps to reproduce the problem starting from a new game? Thanks!

**Comment by Charumu** [comment]
Here ya go @n0samu

**Comment by Charumu** [comment]
https://github.com/ruffle-rs/ruffle/assets/170186282/3515ba20-8bfc-4c78-af60-b1fee90ea366
