### ISSUE TITLE
Asteroids on line game orange screen

### ISSUE THREAD

**Issue by Edmundwadeson** [ruffle-rs/ruffle#16846]
Every time I attempt to play the online game ASTEROIDS I see an orange screen with text that tells me that Ruffle has encountered a problem and would I please, 'REPORT A BUG'
I am reporting the bug to you here, FOR ABOUT THE 5TH TIME!!
Please FIX this issue
Thank You..

**Comment by Croworbit** [comment]
Welcome and thanks for making an issue.
We appreciate reporting a bug, you only need to do it once though.

Unfortunately, that website that is using Ruffle is broken, and it also uses a version of Ruffle that is out of date. 

the only way to fix it is if the website owner updates their website. 

remember that this is a project that people contribute to in their spare time, posting duplicates of existing issues doesn't make anything go faster.

please let the website owner know they need to fix it.

**Comment by Dinnerbone** [comment]
We actually added a different error message some years ago explaining that its the websites fault and how they should fix it... but they're using such an old version that they don't have that.

Sorry, there's really nothing Ruffle can do - their website is broken and it's making Ruffle break :(
