### ISSUE TITLE
Ruffle Error on https://freesimon.org/

### ISSUE THREAD

**Issue by nicolasc30** [ruffle-rs/ruffle#16855]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: false

# Page Info
Page URL: https://freesimon.org/

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by n0samu** [comment]
This is a problem with the website, they broke their CORS setup for WASM files. Please try contacting the site owner or playing the game on a different site.
