### ISSUE TITLE
desktop app input regression since nightly 2024-01-17

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#16859]
### Describe the bug

while pressing shift whatever input has keycode 0
while pressing other keys, pressing shift causes keyup not detected

https://github.com/ruffle-rs/ruffle/assets/98996990/c2b03216-bfca-4cb9-bf59-ed2c1fe75e7e

### Expected behavior

https://github.com/ruffle-rs/ruffle/assets/98996990/d4b8411e-ab7f-4843-9a6c-a2f878c86966

### Content Location

[Main.zip](https://github.com/user-attachments/files/15955499/Main.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

browser extension is not affected
i think this may be caused by #14703

**Comment by kjarosh** [comment]
The reason is that `winit_to_ruffle_key_code` translates only `Key::Character` with lowercase letters (e.g. `Key::Character("a")`), and the character inside is uppercase when Shift is down (e.g. `Key::Character("A")`).

**Comment by zjk261** [comment]
https://github.com/ruffle-rs/ruffle/assets/98996990/68f971b1-4d50-4ad0-8db1-93d589feb4c1

i found another bug
when the window is not focused, focus on it sends a keycode 133
also a regression since nightly 2024-01-17

**Comment by kjarosh** [comment]
> i found another bug
> when the window is not focused, focus on it sends a keycode 133
> also a regression since nightly 2024-01-17

That unfortunately I cannot reproduce, perhaps it's a Windows-specific bug. Could you file a separate issue for that?
