### ISSUE TITLE
Ruffle not working on private Club Penguin server

### ISSUE THREAD

**Issue by gorbyhail** [ruffle-rs/ruffle#16886]
### Describe the bug

Apologies if this turns out not to be a Ruffle issue, however my diagnostics have led me here - for a bit of fun I've been trying to get an old self-hosted private Club Penguin server running again using Ruffle. I've checked in every now and then and from what I can see this should now work as far as Ruffle is concerned, however I'm sadly still having an issue here - I get past the initial blue screen to a loading animation, then it hangs for about ten seconds and this error appears in the dev console:

`Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x16e1598 }) to handler FunctionObject(FunctionObject { ptr: 0x48c1300, name: Ok("com.clubpenguin.main.service.webservice::WebServiceZipLoader/onLoad()") }) : RustError("A script in this movie has taken too long to execute and has been terminated.")`

Please let me know if any additional info is required, I realise I'm probably missing out a lot but not sure where to begin. I'm using the self-updating website package of Ruffle.

### Expected behavior

I was hoping it would simply work!

### Content Location

https://penguin.frodle.net/play/#/login

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome

**Comment by Dinnerbone** [comment]
The loading of Club Penguin is a bit slow in ruffle still, you need to adjust the max script execution time to let it work, until we're more optimised.

It's the config `maxExecutionDuration` listed on the wiki: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle

**Comment by gorbyhail** [comment]
Ah thank you! my bad for not looking into it deeply enough
