### ISSUE TITLE
Some fonts not appearing on iOS

### ISSUE THREAD

**Issue by neave** [ruffle-rs/ruffle#1688]
I own a Flash game at [hexxagon.com](https://hexxagon.com//) written in AS1. All works wonderfully on desktop browsers but on iOS the fonts fail to display. Is this a known issue?

Thank you so much for a fantastic emulator!

**Comment by Toad06** [comment]
Thanks for your bug report and your kind comment.

I confirm this is a known issue: #900
I invite you to add a comment there, so we'll make sure to test your game when a pull request is ready.

Thanks!

**Comment by neave** [comment]
Great thanks, I will. Closing this issue.
