### ISSUE TITLE
Cannot open "MassiveDynamic" flash web-site

### ISSUE THREAD

**Issue by GregS1000RR** [ruffle-rs/ruffle#16910]
### Describe the bug

Tried to open this old website (http://massivedynamic.com/) via Chrome and FireFox using latest plug-in
Tried also using latest nightly build (20240628) of ruffle.exe (32 and 64bit ver) on Win10 

Result same : Tries to do something (High CPU load), but it remains a white screen 

Thanks for your review

### Expected behavior

Flash web site should at least show something

### Content Location

[md_main.zip](https://github.com/user-attachments/files/16024308/md_main.zip)

http://massivedynamic.com/

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

FireFox and Chrome

**Comment by Lord-McSweeney** [comment]
This needs version-gating (playerglobal/namespace versioning) of `DisplayObject.rotationY`

**Comment by GregS1000RR** [comment]
Thank you for the reply, but I'm not sure to understand if there is something I can do about it ?

**Comment by n0samu** [comment]
Hi @GregS1000RR, thanks to evilpie's work in the PR linked above, this issue should be fixed in the next day or two. You should be notified by email when this issue is closed, and then the fix will be live in the next release.
