### ISSUE TITLE
Text appearing as undefined, Cannot enumerate String?

### ISSUE THREAD

**Issue by jkluk** [ruffle-rs/ruffle#1691]
Trying to preserve flash e-article here: https://www.sscnet.ucla.edu/soc/faculty/emigh-flash/unmaking_markets/

Getting the following error:
core.ruffle.23a55957507c641be559.js:1 Cannot enumerate String(AvmString { source: Owned("[type Object],[type Object],[type Object],[type Object],[type Object]") })

Ruffle output:
<img width="969" alt="Screen Shot 2020-11-25 at 3 23 15 AM" src="https://user-images.githubusercontent.com/549557/100221610-c3052600-2ecd-11eb-9dbb-a5e1e985af81.png">

Original:
<img width="961" alt="Screen Shot 2020-11-25 at 3 23 59 AM" src="https://user-images.githubusercontent.com/549557/100221626-c8fb0700-2ecd-11eb-83e2-aac4fdeed0bc.png">

Console log for reference:
[www.sscnet.ucla.edu-1606268043627.log](https://github.com/ruffle-rs/ruffle/files/5593827/www.sscnet.ucla.edu-1606268043627.log)

Full zip of content is available for debugging if necessary.

**Comment by n0samu** [comment]
This seems to be fixed now! The only issues left are with text styling/layout; for example, the line spacing in Ruffle is larger than it should be. Probably related to something in #1167.
