### ISSUE TITLE
Error on http://www.dadsproject.com/pacnum/pacnum.php

### ISSUE THREAD

**Issue by skiesofravens** [ruffle-rs/ruffle#16931]
# Error Info
Error name: Error
Error message: panicked at core/src/avm2/amf.rs:152:18:
called `Result::unwrap()` on an `Err` value: Error: Unknown Property: '-1'.

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0), or similar"
Adapter Device Type: Other
Adapter Driver Name: "WebGL"
Adapter Driver Info: "2.0"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(DEPTH32FLOAT_STENCIL8 | PUSH_CONSTANTS | CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 65536, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 120, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: (550, 650, 1)

# Page Info
Page URL: http://www.dadsproject.com/pacnum/pacnum.php
SWF URL: http://www.dadsproject.com/pacnum/pacnum.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-06-15
Channel: nightly
Built: 2024-06-15T00:05:26.496Z
Commit: 30cc299ed6fd74225420372f8698490532ce8652
Is extension: true

# Metadata
width: 550
height: 650
frameRate: 24
numFrames: 2
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1146947

**Comment by evilpie** [comment]
The problem here is that `ProxyObject`'s `get_next_enumerant` never returns None instead it returns Some(0) when finished. [This comment](https://github.com/ruffle-rs/ruffle/blob/5addb6e34946718e8b8e4dfc65b486c3135569da/core/src/avm2/object.rs#L778) says None and Some(0) is treated the same by AVM2, but in [`op_has_next_2`](https://github.com/ruffle-rs/ruffle/blob/5addb6e34946718e8b8e4dfc65b486c3135569da/core/src/avm2/activation.rs#L2570-L2575) we will continue iterating using the proto for None, but not `Some(0)`.

I am not sure what the "right" fix is: Should we fix the caller to handle 0, or the callee to return None instead?
