### ISSUE TITLE
Regression in FlxSpriteFilters demo

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#16983]
### Describe the bug

Glow filter is now broken

![image](https://github.com/ruffle-rs/ruffle/assets/38821724/4ae1f225-f57f-44cf-a580-5bbf11b727d1)

Last stable build [Nightly 2024-02-01](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-02-01)
Broken [Nightly 2024-02-02](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-02-02)

### Expected behavior

Everything should work correctly

### Content Location

[FlxSpriteFilters.zip](https://github.com/user-attachments/files/16086706/FlxSpriteFilters.zip)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Browser

Firefox Nightly

**Comment by torokati44** [comment]
How is this not covered by regression tests?! :scream:

**Comment by waspennator** [comment]
Same problem as #16670?

**Comment by SN902** [comment]
> Same problem as #16670?

It looks like the same problem, we need to check later

**Comment by waspennator** [comment]
I also forgot to mention, but I have a feeling #15146 was also broken by the "wgpu: Don't submit for every single BitmapData.draw()" too

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/19066
