### ISSUE TITLE
Hide the Android navigation bar when the player is fullscreen

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#1698]
FullscreenOptions: https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions
NavigationUI

ya need to make the change somewhere around here ;) https://github.com/ruffle-rs/ruffle/blob/master/web/packages/core/src/ruffle-player.ts#L493

May also be worth reading this: https://github.com/jwplayer/jwplayer/issues/3446

wow it had been a while since i looked at the fullscreen apis. i forgot that safari had a few prefixes for apis and didn't handle fullscreen like other browsers on iOS. 

----

something else to consider is that mobile browsers tend to automatically rotate from portrait to landscape when in fullscreen to the fit the video. 

oh and the browse button isn't available on mobile on the demo.

and navigating directly to `ruffle.rs/demo` doesn't redirect to the https site!

lmk if i should open new issues for the above three if there aren't already.

**Comment by Poopooracoocoo** [comment]
@Herschel should I file new issues for those three points at the bottom? :)

**Comment by Herschel** [comment]
Fixed the HTTPS on the demo page. Browse button not visible on mobile is intentional. Please go ahead and open an issue about portrait/landscape (what is the current behavior of Ruffle? Does it display in landscape after fullscreening?)
