### ISSUE TITLE
Dead Maze: Right click opens context menu instead of triggering player action

### ISSUE THREAD

**Issue by JediFay** [ruffle-rs/ruffle#16991]
### Describe the bug

Right click opens context menu
![image](https://github.com/ruffle-rs/ruffle/assets/174175668/7b0117cb-9ef5-4536-a5b6-2e58c716f77e)

### Expected behavior

It should trigger player action
![image](https://github.com/ruffle-rs/ruffle/assets/174175668/ab502c50-dde6-4f9b-957a-15f848516423)

### Content Location

http://deadmaze.com/alpha/chargeur-deadmeat.swf

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by torokati44** [comment]
Hmm, interesting, I can't reproduce on Linux, neither on Wayland, nor on X11.
Is this perhaps due to some kind of accessibility setting that is turned on?

**Comment by JediFay** [comment]
Only happens on Windows 10/11

**Comment by torokati44** [comment]
I know you don't have Windows eother, @kjarosh, but is it possible that we _do_ get some double-click events after all, it's just misinterpreted/disguised as something else in a çūr$ėd way somewhere before it gets to us? 😱

**Comment by kjarosh** [comment]
Unfortunately that game requires login, but by analyzing the code, the only possibility for the context menu to open is when the right mouse button is released. I'm not sure whether we are talking about LMB or RMB double-click, if LMB then I really do not see a possibility how that could happen, but if it's RMB then I suspect it might have something to do with this TODO:

https://github.com/ruffle-rs/ruffle/blob/23b7810a0761728c9e7c03114cb549cb309b3479/desktop/src/app.rs#L260

**Comment by torokati44** [comment]
> Unfortunately that game requires login,

Nah, I was able to get in game just by leaving the input fields empty... 🤷‍♂️

**Comment by JediFay** [comment]
Yes

**Comment by kjarosh** [comment]
So it seems that in general right click events are not implemented (`rightClick`, `rightMouseUp`, `rightMouseDown`)
