### ISSUE TITLE
All context menu items are disabled

### ISSUE THREAD

**Issue by robinheidrich** [ruffle-rs/ruffle#17001]
### Describe the bug

Except for the quality settings, which are only displayed later, all items in the context menu of Ruffle are disabled. You can still click on them and they work, but they are grayed out and have no hover effect.

This regression starts from the latest version 2024-07-05, as you can see here: 

https://ruffle-regressions.github.io/?version=0.1.0-nightly.2024.7.4

![image](https://github.com/ruffle-rs/ruffle/assets/23118399/bd0ffb14-d272-43fb-bc9c-5b9a91373c62)

https://ruffle-regressions.github.io/?version=0.1.0-nightly.2024.7.5

![image](https://github.com/ruffle-rs/ruffle/assets/23118399/bcfaa29c-0204-421a-b2c8-8ebd04ddbb77)

### Expected behavior

These should not be disabled.

### Content Location

Can also be reproduced on the Ruffle Demo.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 126.0.6478.127

**Comment by kjarosh** [comment]
Regressed by https://github.com/ruffle-rs/ruffle/commit/ff3d8744f01f9c795bf9691707f1f4fab507050d:

* https://github.com/ruffle-rs/ruffle/pull/16945
