### ISSUE TITLE
jinsei owata no daibouken 2 - yellow line in map 11

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#17034]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/98996990/50529fe5-91b0-4909-9437-0d7f942da02f

### Expected behavior

there should be no line

### Content Location

[owata2.zip](https://github.com/user-attachments/files/16119930/owata2.zip)
[owata2_save.zip](https://github.com/user-attachments/files/16119931/owata2_save.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I didn't press tab key

**Comment by kjarosh** [comment]
The yellow line is a focus rect. The element is properly focused and has proper focus rect settings. The issue here is about timing – at the time the element is being focused, the focus rect should not be visible, but is. When the element is re-focused, FP also shows the line.
