### ISSUE TITLE
Paniking on Dynamic test as mask

### ISSUE THREAD

**Issue by molleindustria** [ruffle-rs/ruffle#1708]
Ruffle for web crashes upon encountering a dynamic textfield inside a mask.

```
core.ruffle.9c7a56b6c7f7b0cf8972.js:1 panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1214:9
```

Dynamic text can be used as mask only if it's inside a movieclip and the font is embedded.

If the text is static the masking works. 
If the text is dynamic it renders well outside of the mask layer.
It's just the combination of the two that causes panic.

If the implementation is too complicated a fallback could be to just render the text without the mask attribute and make the masked layers invisible.

Attached a .fla and a .swf showing the 3 cases mentioned above
[maskBug.zip](https://github.com/ruffle-rs/ruffle/files/5598798/maskBug.zip)

**Comment by Herschel** [comment]
Thanks for the report and test cases! Merging into #1347.
