### ISSUE TITLE
Actionsceupt 1, 2, 3 support

### ISSUE THREAD

**Issue by OverflAI** [ruffle-rs/ruffle#17093]
use ruffle_core::{
    backend::render::RenderBackend,
    player::{Player, PlayerBuilder},
    tag_utils::SwfMovie,
};
use std::sync::Arc;
use wasm_bindgen::prelude::*;
use web_sys::HtmlElement;

#[wasm_bindgen]
pub struct RuffleInstance {
    player: Player,
}

#[wasm_bindgen]
impl RuffleInstance {
    #[wasm_bindgen(constructor)]
    pub fn new(swf_data: &[u8], container: HtmlElement) -> Result<RuffleInstance, JsValue> {
        let movie = Arc::new(SwfMovie::from_data(swf_data, None, None).map_err(|e| JsValue::from_str(&e.to_string()))?);
        
        let mut player_builder = PlayerBuilder::new()
            .with_movie(movie)
            .with_autoplay(true)
            .with_letterbox(ruffle_core::config::Letterbox::On);

        let renderer = create_webgl_renderer(&container)?;
        player_builder = player_builder.with_renderer(renderer);

        let player = player_builder.build();
        
        Ok(RuffleInstance { player })
    }

    pub fn play(&mut self) {
        self.player.play();
    }

    pub fn pause(&mut self) {
        self.player.pause();
    }

    pub fn is_playing(&self) -> bool {
        self.player.is_playing()
    }

    pub fn seek(&mut self, frame: u32) {
        self.player.seek(frame);
    }

    pub fn call_as_function(&mut self, name: &str, args: &[JsValue]) -> Result<JsValue, JsValue> {
        let args: Vec<ruffle_core::avm2::Value> = args.iter()
            .map(|arg| convert_js_to_avm2(arg))
            .collect::<Result<_, _>>()?;

        match self.player.call_internal_interface(name, &args) {
            Ok(result) => Ok(convert_avm2_to_js(&result)),
            Err(e) => Err(JsValue::from_str(&format!("Error calling function: {:?}", e))),
        }
    }

    pub fn set_variable(&mut self, path: &str, value: &JsValue) -> Result<(), JsValue> {
        let avm2_value = convert_js_to_avm2(value)?;
        self.player.set_variable(path, avm2_value)
            .map_err(|e| JsValue::from_str(&format!("Error setting variable: {:?}", e)))
    }

    pub fn get_variable(&self, path: &str) -> Result<JsValue, JsValue> {
        match self.player.get_variable(path) {
            Ok(value) => Ok(convert_avm2_to_js(&value)),
            Err(e) => Err(JsValue::from_str(&format!("Error getting variable: {:?}", e))),
        }
    }

    pub fn set_fullscreen(&mut self, is_full: bool) {
        self.player.set_fullscreen(is_full);
    }

    pub fn screenshot(&self) -> Result<web_sys::ImageData, JsValue> {
        let (width, height) = self.player.movie_size();
        let pixels = self.player.screenshot(width, height)
            .map_err(|e| JsValue::from_str(&format!("Screenshot error: {:?}", e)))?;
        
        web_sys::ImageData::new_with_u8_clamped_array_and_sh(
            wasm_bindgen::Clamped(&pixels),
            width,
            height,
        )
    }
}

fn create_webgl_renderer(container: &HtmlElement) -> Result<Box<dyn RenderBackend>, JsValue> {
    let canvas = web_sys::window()
        .ok_or_else(|| JsValue::from_str("No window found"))?
        .document()
        .ok_or_else(|| JsValue::from_str("No document found"))?
        .create_element("canvas")?
        .dyn_into::<web_sys::HtmlCanvasElement>()?;

    container.append_child(&canvas)?;

    let context = canvas
        .get_context("webgl")?
        .ok_or_else(|| JsValue::from_str("Failed to get WebGL context"))?
        .dyn_into::<web_sys::WebGlRenderingContext>()?;

    Ok(Box::new(ruffle_render_webgl::WebGlRenderBackend::new(context)?))
}

fn convert_js_to_avm2(value: &JsValue) -> Result<ruffle_core::avm2::Value, JsValue> {
    if let Some(num) = value.as_f64() {
        Ok(ruffle_core::avm2::Value::Number(num))
    } else if let Some(bool_val) = value.as_bool() {
        Ok(ruffle_core::avm2::Value::Bool(bool_val))
    } else if let Some(string) = value.as_string() {
        Ok(ruffle_core::avm2::Value::String(string.into()))
    } else if value.is_null() {
        Ok(ruffle_core::avm2::Value::Null)
    } else if value.is_undefined() {
        Ok(ruffle_core::avm2::Value::Undefined)
    } else {
        Err(JsValue::from_str("Unsupported JS value type"))
    }
}

fn convert_avm2_to_js(value: &ruffle_core::avm2::Value) -> JsValue {
    match value {
        ruffle_core::avm2::Value::Undefined => JsValue::UNDEFINED,
        ruffle_core::avm2::Value::Null => JsValue::NULL,
        ruffle_core::avm2::Value::Bool(b) => JsValue::from_bool(*b),
        ruffle_core::avm2::Value::Number(n) => JsValue::from_f64(*n),
        ruffle_core::avm2::Value::String(s) => JsValue::from_str(s),
        _ => JsValue::NULL, // Handle other types as needed
    }
}

#[wasm_bindgen]
pub fn init_panic_hook() {
    console_error_panic_hook::set_once();
} It is my job to contribute to Ruffle here is some good code, you can integrate it however you want, thank you.

**Comment by Dinnerbone** [comment]
Hi there!

I'm sorry but I don't know what you're trying to convey with this issue.

This looks like a copy paste of a conversation with ChatGPT...?

**Comment by Dinnerbone** [comment]
> So, it is not ChatGPT

Before your edit, it contained text like someone was talking to chatGPT and getting responses back. That's why I assumed.


Thank you for trying to be helpful, but unfortunately this code just doesn't help us. It looks vaguely based on some existing code snippets.

If you want to contribute code (your own code, that you wrote) to fix a certain issue or implement a missing feature, please feel free. Here's some resources to get started:

- [Our contributing guidelines](https://github.com/ruffle-rs/ruffle/blob/master/CONTRIBUTING.md)
- [How to make a pull request to suggest code changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
