### ISSUE TITLE
A question about the progress and what to add in Ruffle

### ISSUE THREAD

**Issue by OverflAI** [ruffle-rs/ruffle#17094]
Hmm, so I would humbly urge the people involved in this project to add as much functionality and game support for the Adobe Flash Player and Adobe AIR support like there is a emulator that emulates ActionScript 2 perfectly called SWF native on the play store, I want you to intergrate the features from there and also the app called SWF player free and it's premium version. Here are the images of the products that also have Adobe AIR emulation.

![Screenshot_2024-07-12-19-38-02-17_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/d8d2d136-0cad-44de-ad1c-dbca5805beef)

And, I know Adobe AIR is not the main functionality that the program is supposed to support, but I would like it, and please inform me if the work is complete and when, and please complete the ActionScript 3 work quickly. And, please update me about what is left, and if it is functionalities, please add the functionalities that need to be added urgently. I would also urge you to see my other issue posted, I updated it. The code in there has wrong indentation, please fix it and intergrate it, thankyou! ActionScript 3 is also there in SWF Native and Adobe AIR in SWF player free

**Comment by Dinnerbone** [comment]
> add as much functionality and game support for the Adobe Flash Player

That's the goal.

> Adobe AIR support

We're open to adding this, but it's less of a priority. Contributions are welcome.

> there is a emulator that emulates ActionScript 2 perfectly called SWF native on the play store

That app appears to use Ruffle.

> SWF player free and it's premium version

That app also seems to use Ruffle.

> please inform me if the work is complete and when

We cannot individually tell every interested party when we're "done". You're welcome to watch our blog posts and our [compatibility](https://ruffle.rs/compatibility) page!

> please complete the ActionScript 3 work quickly

We're working as fast as we can. We're just volunteers doing this in our own time. If there's a specific game you're trying to get working, please search for an issue about that game (or open one *if* none exists). We will likely never be "complete" - no game requires 100% of ActionScript 3 to exist, most games only need a small small percent of the API to work.

**Comment by OverflAI** [comment]
Yeah, but how much percentage of ActionScript 3 and ActionScript 2 is done?

**Comment by Dinnerbone** [comment]
Please see the page that I linked, which shows exactly that.
