### ISSUE TITLE
Unable to login to stick arena private server with Ruffle

### ISSUE THREAD

**Issue by SmileyBoy321** [ruffle-rs/ruffle#17108]
### Describe the bug

**Account credentials to log in**
**Username:** test5
**Password:** test1234
Link to the game: http://3.145.15.34/sad.swf

I created an account named test5 and tried to log in with it but it returns connection error.
![image](https://github.com/user-attachments/assets/843c1df0-5860-4a87-bbee-cbf92a94d929)

In the FlashBrowser, everything works just fine as you can see in the below image, it logged in just fine.
![image](https://github.com/user-attachments/assets/4626e2b3-fc42-4f01-94c5-c38b6791b3f6)

Please fix it as we deem it to be Ruffle problem, not our server problem because if our server works with FlashBrowser but does not work with Ruffle then yeah.

Please advise as well.

### Expected behavior

Login works and shows the below screen that the user logged in successfully.
![image](https://github.com/user-attachments/assets/1790d65d-24ea-460d-9a0e-49aab56f0bf8)

### Content Location

SWF file uploaded in the ZIP file sad.zip
[sad.zip](https://github.com/user-attachments/files/16201803/sad.zip)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by Dinnerbone** [comment]
Appears to connect for me.
![image](https://github.com/user-attachments/assets/a8f06fcf-39eb-43c9-9641-80b2d1ebb3c5)

You mentioned doing this on the web, but did not link to the page that contains this swf - are you sure that you set up a WebSocket proxy? There's instructions on the wiki: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-can-i-connect-to-a-tcpsocket-or-xmlsocket-from-the-web

This is unfortunately needed for the web to work around browser functionality.

**Comment by SmileyBoy321** [comment]
The link that contains this swf is this: http://3.145.15.34/sad.swf

If not then I do not understand your question and I need clarification.

If we need to tell our new users to set up websocket proxy then that will make them go away. It's supposed to be a seamless process.

Your image shows ruffle client aka desktop version via the .exe file. Please try it with ruffle extension instead which is supposed to look like this: 
![image](https://github.com/user-attachments/assets/c5c39a7f-24eb-4240-9baa-88fd0f2e59cc)

Please advise.

**Comment by Dinnerbone** [comment]
> WARN web/src/navigator.rs:389 Missing WebSocket proxy for host 3.145.15.34, port 1138

That's it.


You, or whomever owns the server/website, are the ones who are supposed to set up the proxy. It's invisible for users, they don't know or care that it exists, but whomever hosts the game should set up a proxy and Ruffle will take care of the rest for you.

**Comment by SmileyBoy321** [comment]
I see, we'll set it up and close this issue in 2-3 days if all good. Give us a bit of time before closing this issue.

**Comment by Dinnerbone** [comment]
No worries, good luck and please feel free to let us know if you need further help.

**Comment by SmileyBoy321** [comment]
In that case, I'll ask one more question.

The https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-can-i-connect-to-a-tcpsocket-or-xmlsocket-from-the-web shows a guide with a Python. We use Java as our backend. Do we just convert the python guide to java and proceed onwards from there?

**Comment by lvyitian** [comment]
You can implement your own websocket proxy of course, the wiki just uses Websockify as an example for non-technical users.

**Comment by Dinnerbone** [comment]
The program that we recommend is written in Python, but there may be others that do a similar thing. Similarly, if you own the server software itself, you *could* just skip the external proxy and write support for WebSocket into your server directly. You still need to tell Ruffle to use it as if it were a proxy - but you skip the need for maintaining an extra service. No guide on how to do that though, it's too case-by-case, but it's not crazy difficult.

The way it works is something like this:
- The **client** (the swf, written in ActionScript) tries to open a **tcp socket** to 1.2.3.4:56
- Ruffle instead opens a **websocket** to a configured address, eg 1.2.3.4:99
- The client sends a packet, ruffle just sends it to the websocket instead
- The websocket replies, ruffle pretends the tcp server replied

And then if you use `websockify` like in the FAQ:
- You host a websockify instance somewhere (eg 1.2.3.4:99), pointed at 1.2.3.4:56
- When a connection opens to websockify, it opens a new tcp connection to the real server
- When a packet comes in from the client to websockify, it sends it to the real server
- When the real server replies with a packet, it sends it to the client

**Comment by lvyitian** [comment]
This is a proxy implementation written in Java for example: https://github.com/syed/java-websockify

**Comment by Dinnerbone** [comment]
> This is a proxy implementation written in Java for example: https://github.com/syed/java-websockify

Please note that we can't guarantee that this works, we only have experience with Websockify and people who've coded it themselves. It may or may not be functionally complete, we can't make certainties about random 7 year old projects.

**Comment by SmileyBoy321** [comment]
Thank you, it's something to use as an inspiration and check out how it was done.
Wish us luck! We'll work on it and close the issue in 2-3 days if all good.

**Comment by Kawaxte** [comment]
In my case, both the `sab2.swf` und `sad.swf` cannot sign into the servers, telling me there're connection errors, but if there'st a time where it attempts to, both .swf files will freeze und crash the entire executable.

**OS:** Fedora Linux 40.20240713.0 (Silverblue)
**Ruffle version:** nightly-2024_07_13-linux-x86_64

When loading the .swf files directly, they can't get past the game's loading screens (checking for updates), but if loaded via the URLs, they either refuse to connect to servers oder crash Ruffle itself.

**Comment by Dinnerbone** [comment]
That may be something to do with our "do you want to connect to x.x.x.x" dialog? It blocks the application until you click yes or not, so if you can't see the dialog for some reason then it will behave the way you described.
If in the Open Advanced screen you change it to always allow TCP connections, does it work?
![image](https://github.com/user-attachments/assets/d9c07c51-7215-4d00-9083-027eed6d4a0a)

**Comment by Kawaxte** [comment]
> That may be something to do with our "do you want to connect to x.x.x.x" dialog? It blocks the application until you click yes or not, so if you can't see the dialog for some reason then it will behave the way you described. If in the Open Advanced screen you change it to always allow TCP connections, does it work?)

Unfortunately, it got to the "Connecting to <x>" panel und crashed immediately.
