### ISSUE TITLE
Math.floor(Math.random) generated integers seem to "stick" between game plays?

### ISSUE THREAD

**Issue by Dungeonation** [ruffle-rs/ruffle#1712]
Whenever you play my game Face It! with Ruffle for the first time, get to a point where it generates random integers (the random face on How To Play) and then exit the tab and open the game back up, and go back to that screen...the random integers seem to be exactly the same? It happens to me on (Windows) PC and mobile (Safari on iOS).

My game: https://www.newgrounds.com/portal/view/772159

**Comment by rdrpenguin04** [comment]
Thank you for the report!

Math.random being deterministic is a known issue, see [this issue](https://github.com/ruffle-rs/ruffle/issues/1182) for details.
