### ISSUE TITLE
[web] API support to detect the AVM1/2 version of the currently running flash

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#1713]
Thanks to the ruffle team for working hard to preserve the flash!

It would be useful to be able to figure out whether the currently running Flash uses ActionScript 1/2 or 3 using the API (or another way).

Thank you.

**Comment by relrelb** [comment]
This is now exposed thanks to #4399:
```js
player.addEventListener("loadedmetadata", () => {
    console.log(player.metadata.isActionScript3);
});
```
