### ISSUE TITLE
Regression: Lists cannot be selected Blame: nightly-2024-07-13

### ISSUE THREAD

**Issue by CanIGetaPR** [ruffle-rs/ruffle#17131]
### Describe the bug

**Main Game Page (Nightly July 12)**: https://pawngame.com/web/pawn/
**Bug Demo Page (Nightly July 13)**: https://pawngame.com/web/ruffle-test/pawn/
**Bug Tracking Page (Nightly live)**: https://pawngame.com/web/ruffle-live/pawn/

Browsers Tested: Firefox, Chromium

Starting with [Nightly July 13](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-07-13) list items can no longer be selected by clicking. 

The only method I found to select a list item was by typing the first letter of the item using the keyboard.

I had rollback to [Nightly July 12](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-07-12) for the time being.

I created a temporary game page running Nightly July 13 to demonstrate the bug: https://pawngame.com/web/ruffle-test/pawn/

1. Load https://pawngame.com/web/ruffle-test/pawn/
2. Click Quick Play
3. Click Host
4. Try selecting a map name in the list.

Repeat on https://pawngame.com/web/pawn/ to see that July 12 build works and July 13 build doesn't. 

Added another game page running latest nightly to track when the bug gets fixed. https://pawngame.com/web/ruffle-live/pawn/

![image](https://github.com/user-attachments/assets/3efb5939-a0e0-44c4-91ff-3b7b4f55bdc9)

### Expected behavior

Clicking should allow list item selection.

### Content Location

Game running Nightly July 13 with bug: https://pawngame.com/web/ruffle-test/pawn/

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Firefox 128

**Comment by kjarosh** [comment]
Regressed by 250bf64a92d173d00cdb78bdf0c1ee70d654e475 (https://github.com/ruffle-rs/ruffle/pull/17022).
