### ISSUE TITLE
banana.swf: audio, but no video

### ISSUE THREAD

**Issue by xnaas** [ruffle-rs/ruffle#1714]
# **WARNING: NSFW!**

I'm guessing everyone was too embarrassed to put in an issue for [banana.swf](https://postarchives.entensity.net/040805/flash.php?flash=banana.swf) (alternate file: [banana.zip](https://github.com/ruffle-rs/ruffle/files/5600062/banana.zip)).

Simply: audio works fine, but there's no video.

**Comment by Guy-Sowden** [comment]
ruffle at the moment is incapable of playing video.

**Comment by xnaas** [comment]
Interesting. Thought it was strange since so many games and such work.

Thanks for the info.

**Comment by xnaas** [comment]
Aha, found the issue for it: #723
