### ISSUE TITLE
Keyboard on Mobile having trouble focusing

### ISSUE THREAD

**Issue by AllinolCP** [ruffle-rs/ruffle#17155]
### Describe the bug

When using mobile (in my case im using an S23 Ultra), the textfield gets unfocused when tapped and I am not able to type anything into the field.

https://github.com/user-attachments/assets/554ea668-051b-4071-aa52-508756a0a014

### Expected behavior

I should be able to type into the text field.

### Content Location

https://newcp.net/plays

### Affected platform

Desktop app

### Operating system

Android 14, OneUI 6.1

### Browser

Chrome 126.0.6478.122

**Comment by kjarosh** [comment]
Probably regressed by
* https://github.com/ruffle-rs/ruffle/pull/17051
