### ISSUE TITLE
Regression: Game Loses Focus When "Unable to lock Ruffle core" Blame: Nightly July 13 

### ISSUE THREAD

**Issue by CanIGetaPR** [ruffle-rs/ruffle#17162]
### Describe the bug

Starting with Nightly July 13 when we open the chat bar in our game, focus is lost while an error is logged in the web console. Have to click the game to regain focus. 

ERROR `web/src/lib.rs:1071` Unable to lock Ruffle core [core.ruffle.284838efa5867135890a.js:1:17048](https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.284838efa5867135890a.js)

Step 1 Validating Nightly July 13 is the blame:

1. Visit https://pawngame.com/web/ruffle-broken/pawn/ (Nightly July 13)
2. Click Quick Play
3. Click Host
4. Click on the map list and press A on your keyboard so it jumps to abyss then click the -> button and click OK. (this was the build with broken click event yes, but we can work-around that bug for this demo)
5. The game launches, press K on your keyboard to open chat. 
6. Observe the web console: 
ERROR `web/src/lib.rs:1071` Unable to lock Ruffle core [core.ruffle.284838efa5867135890a.js:1:17048](https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.284838efa5867135890a.js)
7. Try to type text using your keyboard. The game is not allowing us to type in the chat bar.
8. Click anywhere on the game, focus is restored and we can type again.

Step 2 Repeat the steps on Nightly 12 deployment: https://pawngame.com/web/ruffle-working/pawn/
The game is working correctly in this version.

Optional Step 3 Repeat on the latest Nightly (July 18 at the time of this issue creation): https://pawngame.com/web/pawn/
Observe the issue still exists. 

### Expected behavior

Press K in a match and the game immediately allows typing without having to click on the game.

### Content Location

Main Game Page Running Latest Nightly (Not Working): https://pawngame.com/web/pawn/
Demo Running Nightly July 12 (Working): https://pawngame.com/web/ruffle-working/pawn/
Demo Running Nightly July 13 (Not Working): https://pawngame.com/web/ruffle-broken/pawn/

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Firefox 128

**Comment by torokati44** [comment]
This will possibly be fixed by https://github.com/ruffle-rs/ruffle/pull/17158.

**Comment by kjarosh** [comment]
I confirm, it will be fixed by https://github.com/ruffle-rs/ruffle/pull/17158.
