### ISSUE TITLE
DefineEditText (HTML) - Text layout problems - Paragraph breaks use wrong font size

### ISSUE THREAD

**Issue by Dwedit** [ruffle-rs/ruffle#1717]
SWF File: (Text element isolated and reduced down to 8K)
https://www.dwedit.org/files/jamezbond_lastframe_nomask.swf
With the mask shape: https://www.dwedit.org/files/jamezbond_lastframe.swf
(Originally from flash movie https://www.dwedit.org/flash/jamezbond.php )

Rendered in Flash Player: https://www.dwedit.org/files/jb_flash.png
Rendered in Ruffle: https://www.dwedit.org/files/jb_ruffle.png

It looks like Paragraph Breaks are being treated as the initial Font Size rather than the only font size used on that line.  The text is also a few pixels out of position.

The original flash file used a mask shape to hide the black periods.  With text layout being incorrect, most of the text is missing when viewed through the mask.

**Comment by n0samu** [comment]
Seems like this was fixed a long time ago.
