### ISSUE TITLE
Sound error while playing "Escaping the Prison" (NewGrounds)

### ISSUE THREAD

**Issue by GreenStarShooter** [ruffle-rs/ruffle#17180]
### Describe the bug

So, I was playing the game "Escaping the Prison" (in Newgrounds), and went to the badass way. 

Here, the player selects _Drill_, so that Henry uses a drill to escape from his cell to the bathroom below, then the player selects _Crowbar_, so that Henry uses a crowbar to get through a tube, but falls from one of the tubes in front of two policemen, and Henry sees himself forced to run away.

**Here is where the bug takes place:** There is a quick time event in which the player must select one of two arrows (two times). A sound comes in alongside the arrows. Unfortunately, this sound appears to be looping constantly, even after failing, succeeding, or selecting another path.

Also, I noticed that the background music doesn't stop when Henry gets a fail in this part.

### Expected behavior

The sound that comes alongside the arrows should only play twice (once every time the arrows appear; I said twice because the arrows appear twice) and the background music should stop when failing. 

### Content Location

This bug occurs in the game "Escaping the Prison" by "Puffballs United" on Newgrounds; specifically the badass way.

To get to the part where the bug takes place, select _Drill_, and then _Crowbar_.

You can go to the game by clicking [here](https://www.newgrounds.com/portal/view/533001).

### Affected platform

Browser's extension

### Operating system

Microsoft Windows 10 Pro (64-bit Edition)

### Browser

Microsoft Edge 126.0.2592.102

### Additional information

This was already reported before on previous tickets (specifically the #8067 and #2185 tickets), but it's still to be fixed to this day.

**Comment by Croworbit** [comment]
already reported on https://github.com/ruffle-rs/ruffle/issues/8067

**Comment by GreenStarShooter** [comment]
To CroworBit:

I know; but I pressed _Enter_ accidentally, submitting this ticket accidentally (grave mistake isn't it). If it is necessary that I contribute to the other ticket and close this one, please let me know. I'll be happy to help.

**Comment by GreenStarShooter** [comment]
Yeah, you know what? I'm closing this. Dumb mistake by me to press _Enter_ accidentally.

**Comment by GreenStarShooter** [comment]
Yeah, you know what? I'm closing this. Dumb mistake by me to press _Enter_ accidentally.
