### ISSUE TITLE
web: stopAllSounds() affects any file currently playing on a same page

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1721]
Sample: [stopAllReallyStopsAll.zip](https://github.com/ruffle-rs/ruffle/files/5604117/stopAllReallyStopsAll.zip)

- Click Ruffle's button for both games if autoplay is not enabled.
- Click "Play" in Luigi's Day: audio will stop for both files.

**Comment by Dwedit** [comment]
I seem to remember that in much older flash player versions, stopAllSounds would work across different players, but at some point, this behavior changed.  This memory may be fuzzy and wrong.

**Comment by Herschel** [comment]
Fixed by #4273.
