### ISSUE TITLE
ioError" bubbles-false cancelable—false eventPhase=2 #2032: Stream Error"

### ISSUE THREAD

**Issue by 2gn** [ruffle-rs/ruffle#17217]
### Describe the bug

On [a specific website on webarchive](https://web.archive.org/web/20120316033955/http://www.blackwidowrockband.co.uk/hailsatan/), ruffle crashes with the following error:

`ioError" bubbles-false cancelable—false eventPhase=2 #2032: Stream Error"`

You can see the error code in the loaded ruffle screen

possibly related: #2032

### Expected behavior

I don't know what was supposed to be shown, but should display something, I don't know. 

### Content Location

https://web.archive.org/web/20120316033955/http://www.blackwidowrockband.co.uk/hailsatan/

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Confirmed on Firefox and Edge

### Additional information

Debug Info

```
# Player Info
Allows script access: true
Renderer: Canvas
Player type: Object
SWF URL: http://cdn.topspin.net/widgets/email2/swf/TSEmailMediaWidget.swf?timestamp=1318855057
Param allowScriptAccess: always
Param allowfullscreen: true
Param quality: high
Param movie: http://cdn.topspin.net/widgets/email2/swf/TSEmailMediaWidget.swf?timestamp=1318855057
Param flashvars: widget_id=http://cdn.topspin.net/api/v1/artist/13268/email_for_media/106317?timestamp=1318855057&theme=black&highlightColor=0xfafafa&&playMedia=true&
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web.archive.org/web/20120316033955/http://www.blackwidowrockband.co.uk/hailsatan/
SWF URL: http://cdn.topspin.net/widgets/email2/swf/TSEmailMediaWidget.swf?timestamp=1318855057

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-08
Channel: nightly
Built: 2024-01-08T00:15:28.895Z
Commit: 47db84473a639c405289bb86ce238a83af574137
Is extension: false

# Metadata
width: 500
height: 375
frameRate: 31
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 219887
```

**Comment by Lord-McSweeney** [comment]
This is because of a failing request to https://web.archive.org/web/20120316033955/https://cdn.topspin.net/api/v1/artist/13268/email_for_media/106317?timestamp=1318855057 ; it wasn't archived.

**Comment by n0samu** [comment]
And a similar error occurs in Flash Player, so this doesn't seem to be a Ruffle bug.
