### ISSUE TITLE
hasOwnProperty not working for Object and ObjectProxy class

### ISSUE THREAD

**Issue by GonzalezAtWork** [ruffle-rs/ruffle#17265]
### Describe the bug

when using hasOwnProperty on objects, it always return "false".

### Expected behavior

should return true when the property exists

### Content Location

![image](https://github.com/user-attachments/assets/df540ab1-036e-42ce-9b74-d63b62730178)
[test.zip](https://github.com/user-attachments/files/16392895/test.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by evilpie** [comment]
Thanks for providing a simple test case.
