### ISSUE TITLE
Tell users that an SWF they've played on the demo is AVM2/AS3 by telling them to check the console

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#1732]
Tell users somewhere, such as on the demo page, contributing.md, in an issue template or the readme, to check the console in devtools if they have any errors with the web demo. 

Or you could perhaps display the warning right on the demo page or player?? 

it's _far_ from necessary of course! it'd be temporary and people using ruffle likely already know to check! :)

**Comment by rdrpenguin04** [comment]
I think someone was thinking of adding a warning at the start screen if a game has unsupported features. Would that solve this?

**Comment by Poopooracoocoo** [comment]
@rdrpenguin04 yeah that would solve this! ~oh hey we're around the same age!~

**Comment by Poopooracoocoo** [comment]
#1978
