### ISSUE TITLE
Ruffle not working; Cpanel, linux based web server; wasm extension already setup

### ISSUE THREAD

**Issue by reppy31** [ruffle-rs/ruffle#1735]
Hey, I'm not really sure what this contributes, but the error told me to open a bug report.

So basically I extracted ruffle into my website and linked it in my pages that had flash content, specifically these pages are php.
After that I configured my MIME types and set wasm up.

That's where I'm at now, with this error:

# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: http://cameronsch.com/core.ruffle.js)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(error: http://cameronsch.com/core.ruffle.js)
    at Object._i.f.j (http://cameronsch.com/ruffle/dist/ruffle.js:1:33328)
    at http://cameronsch.com/ruffle/dist/ruffle.js:1:31746
    at Array.reduce (<anonymous>)
    at Function._i.e (http://cameronsch.com/ruffle/dist/ruffle.js:1:31723)
    at i (http://cameronsch.com/ruffle/dist/ruffle.js:1:5431)
    at i.next (<anonymous>)
    at http://cameronsch.com/ruffle/dist/ruffle.js:1:5731
    at new Promise (<anonymous>)
    at http://cameronsch.com/ruffle/dist/ruffle.js:1:5467
    at s (http://cameronsch.com/ruffle/dist/ruffle.js:1:5754)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://cameronsch.com/swf?f=Prized_Children/PathOfTheWind.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-27
Channel: nightly
Built: 2020-11-27T00:30:29.363Z
Commit: 1d648a1d557d8d692becf9cbb12922dcb1f5db17

One thing I'm pretty confused about is that there is no "core.ruffle.js" in my main directory.

**Comment by reppy31** [comment]
So I tried moving "core.ruffle.js" to my main directory (lol) and I am now getting this error:

# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://cameronsch.com/swf?f=Prized_Children/PathOfTheWind.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-27
Channel: nightly
Built: 2020-11-27T00:30:29.363Z
Commit: 1d648a1d557d8d692becf9cbb12922dcb1f5db17

**Comment by Toad06** [comment]
Before:
`<script src="./ruffle/dist/ruffle.js"></script>`

try adding:
```
window.RufflePlayer = window.RufflePlayer || {};
window.RufflePlayer.config = {
    "publicPath": "/ruffle/dist"
};
```

**Comment by reppy31** [comment]
Unfortunately after adding that there is no change. The first error will still appear when "core.ruffle.js" is where it is natively, and the second error will appear when it is in the main directory.

**Comment by reppy31** [comment]
Update, I looked into the console and as well as "core.ruffle.js" throwing a 404, the WASM file was also throwing a 404 error.
After moving both files to my main directory it works perfectly!
