### ISSUE TITLE
Ruffle encountered a fatal error

### ISSUE THREAD

**Issue by aelianix** [ruffle-rs/ruffle#17427]
### Describe the bug

Was playing Papa's Cheeseria, finished day 1 and tried to backup my save. instead i received this popup: 
<img width="266" alt="Screenshot 2024-08-08 at 5 56 47 PM" src="https://github.com/user-attachments/assets/31337b0b-b037-4a25-b49a-b9a4ac842985">

### Expected behavior

Pressed 'save a backup', expected to receive a save backup but that did not happen. 
I tried on both the save-selection screen as well as the end-of-day screen. 

### Content Location

[papascheeseria_102.swf.zip](https://github.com/user-attachments/files/16554029/papascheeseria_102.swf.zip)

### Affected platform

Desktop app

### Operating system

macOS Sonoma 14.6.1

**Comment by aelianix** [comment]
Forgot to mention but I am using the 2024/08/08 version of ruffle, figured that that is important information to know

**Comment by n0samu** [comment]
Thanks for reporting! This seems to be a longstanding issue with the Ruffle desktop app that I wasn't aware of before now. Closing in favor of #15615 (same issue)
