### ISSUE TITLE
Change default value for "Open Links" on the desktop app to "Ask"

### ISSUE THREAD

**Issue by Tiagoquix** [ruffle-rs/ruffle#17432]
Hello there.

Currently, "Open Links" on desktop has "Allow" as the default value.
I want to suggest to change it to "Ask" for two reasons:

1. Security: you maybe wouldn't want to accesss a random link from 10 years ago and expose your IP address and other info to that website.
2. Annoyance: sometimes I click on Flash elements that I have no idea that they are links. A confirmation in this case would be nice.

Also, "Open Links" option does not follow the pattern of having a checkbox to be able to modify the default value.
![image](https://github.com/user-attachments/assets/98238913-8211-4141-8b65-194d40ce0d08)

Not sure if making "Upgrade HTTP to HTTPS" enabled by default would be a good idea, but since Ruffle runs 100% locally on the Desktop (AFAIK) then it wouldn't be necessary, but would be cool nonetheless.

For the "Open Links" request, I believe changing "allow" to "ask" [here](https://github.com/ruffle-rs/ruffle/blob/b9054c4f45240a46d1bc91659944b78c87a4348a/desktop/src/cli.rs#L169) would be sufficient.

Thanks in advance for your attention.

**Comment by Korne127** [comment]
When I introduced that feature (in #10625), there was a discussion on which value to use as the default
The consensus in the end was that it's okay to change it to Ask, but that we should then add a "Save this preference" checkbox so users don't get the prompt each time. I planned on doing that, but other things got in the way and then I forgot.
That was mostly about the web version though, but I think we should keep it consistent, and if we resolve this, change the option and add such a checkbox in both desktop and web.
