### ISSUE TITLE
java and shockwave support?

### ISSUE THREAD

**Issue by powerpuffboysz** [ruffle-rs/ruffle#17447]
Is it within the scope of the project to also support shockwave and java "flash" games for lack of a better term?

**Comment by n0samu** [comment]
No, sorry

**Comment by Dinnerbone** [comment]
Sadly, no. They're just too different and they'd both be completely new projects on the scale of what Ruffle already has.

There's some emulators for Shockwave:
- I heard about https://github.com/igorlira/dirplayer-rs recently
- https://www.scummvm.org/ has (some) shockwave support

**Comment by n0samu** [comment]
For Java applets, there is CheerpJ: https://cheerpj.com/cheerpj-applet-runner/
