### ISSUE TITLE
Differences with Flash Player in mouse interactions

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1745]
Web and desktop backends are both affected.
Nothing critical though.

- When the cursor is over a button and you move the mouse outside of the canvas (or game window) quickly enough, then the button remains as if the cursor was still over it.
=> In [Mini-Putt 2](https://www.newgrounds.com/portal/view/38598), click "Practice", then check the issue with the "Continue" button.

- (FIXED) When you click a button (mouse down only) and release it outside of the button area (can also be outside of the canvas), then the action of the button is executed.
=> [Mini-Putt 2](https://www.newgrounds.com/portal/view/38598) can also be used here; or in [Luigi's Day](https://www.newgrounds.com/portal/view/44505), check the issue with the "Play" or "Controls" button.

- (FIXED) When you click a button, the cursor may not go back to the default one; on affected files, it would usually keep displaying the pointer cursor.
=> In [Bubble Gum Run](https://www.y8.com/games/bubble_gum_run), check the issue with the second "Play" button.

**Comment by Herschel** [comment]
As of 10/2021, these all seem fixed except the third cursor-not-resetting issue.

**Comment by relrelb** [comment]
Did #6262 solve this?

**Comment by Toad06** [comment]
Not completely, the first item is still an issue but it only happens if you don't hold down any mouse button. If you press the left button and release it outside of the canvas, then the state of the "Continue" button will change as expected.

**Comment by Toad06** [comment]
First item fixed by #10622.
