### ISSUE TITLE
Non-looping audio

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#1751]
So I'm testing this particular version of Tetris I like with the 11/27 nightly self-host and I'm noticing issues that are similar to #1245 #1303 where audio is not looping as intended, but still only playing once. I don't particularly care if the audio loops on this game or not, but given how many issues are around audio, I thought this was worth bringing up.
[tetris.zip](https://github.com/ruffle-rs/ruffle/files/5610040/tetris.zip)

**Comment by relrelb** [comment]
Looks like this is the same case as #396.

**Comment by sombraguerrero** [comment]
Ah, fair, so many interrelated issues logged here, I find it almost impossible to not  have dupes.
