### ISSUE TITLE
Audio plays before Begin button is pressed in French Erotic Film

### ISSUE THREAD

**Issue by Sgeo** [ruffle-rs/ruffle#1754]
https://archive.org/details/frencheroticfilm-tmst

Audio plays before Begin button is pressed. Pressing Begin restarts the audio.

**Comment by Dwedit** [comment]
Pull request #1750 just got merged in, that might have fixed it already.  Just waiting for my build to finish before I can see if it worked.

**Comment by Toad06** [comment]
Thanks for this bug report.

No issue in master, this has certainly been fixed by #1750.
The fix will be included in tomorrow's release (archive.org will have to update their build), so I'm going to close this.

Thanks again.

**Comment by Dwedit** [comment]
Just tested French Erotic Film in the new version of the player, no issues.
