### ISSUE TITLE
swf is not loaded

### ISSUE THREAD

**Issue by Wahrheit26** [ruffle-rs/ruffle#1755]
Hello,

First of all many thanks for ruffle.js.

I have created an example, but it does not work.
My example can be found here:
http://lena91567.bplaced.net/Hellblau/
why does my example not work?
Am I using the wrong ruffle.js?

Please help me.
Thanks a lot!

**Comment by Poopooracoocoo** [comment]
<details>
<summary>Error details + console logs</summary>
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: http://lena91567.bplaced.net/Hellblau/404/core.ruffle.1e0190933879cdfea690.js)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(error: http://lena91567.bplaced.net/Hellblau/404/core.ruffle.1e0190933879cdfea690.js)
    at Object.li.f.j (http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:33918)
    at http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:32314
    at Array.reduce (<anonymous>)
    at Function.li.e (http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:32291)
    at i (http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:1536)
    at i.next (<anonymous>)
    at http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:1836
    at new Promise (<anonymous>)
    at http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:1572
    at i (http://lena91567.bplaced.net/Hellblau/404/ruffle.js:1:1859)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: pinnwand.swf
Param movie: 404/006699.swf
Param allowScriptAccess: sameDomain
Param quality: high
Param scale: noscale
Param bgcolor: 006699
Param menu: false
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: http://lena91567.bplaced.net/Hellblau/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-27
Channel: nightly
Built: 2020-11-27T00:30:29.363Z
Commit: 1d648a1d557d8d692becf9cbb12922dcb1f5db17

![image](https://user-images.githubusercontent.com/51363864/100498876-6d749600-31b9-11eb-9f0a-94b0e4c0fad3.png)
this is me trying to be helpful
</details>

**Comment by Sgeo** [comment]
Did you upload the core.ruffle file and the .wasm too? I see 404s.

**Comment by Wahrheit26** [comment]
No, I have not uploaded these files.
Can you please tell me the exact names of the files and where I can find them (in which directory)?
I thought I just need ruffle.js

**Comment by Sgeo** [comment]
https://github.com/ruffle-rs/ruffle/releases

They should be in the selfhosted version of the release (I believe that's the one you want).

Where did you get ruffle.js by itself?

**Comment by Poopooracoocoo** [comment]
Check out the wiki: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#web

**Comment by Wahrheit26** [comment]
Thanks for your answers.
I downloaded the selfhosted version and uploaded the files into my directory.
But where can I find the core.ruffle.js ?
I have read the wiki, but I don't know what else to do.

http://lena91567.bplaced.net/Hellbl/

**Comment by Poopooracoocoo** [comment]
Where in your directory have you placed them? Are they in your main directory?

**Comment by ousia** [comment]
Welcome, @Wahrheit26.

Many thanks for what it seems to be your first contribution to Ruffle.

[I beg your pardon, if I’m wrong and my explanation is too basic and verbose.]

“Page not found” as page title may point to missing files. BTW, did you type the HTML code or did you use a graphical application?

It might be that some things might be missing. The SWF isn’t loaded, since it cannot be found (at least, not one of the two you mention).

I see now that you try to load two SWF files loaded, see your code:

``` html
<object data="pinnwand.swf" type="application/x-shockwave-flash" width="116" height="120">
  <param name="movie" value="006699.swf" />
  <param name="allowScriptAccess" value="sameDomain" />
    <param name="quality" value="high" />
    <param name="scale" value="noscale" />
    <param name="bgcolor" value="006699" />
    <param name="menu" value="false" />
</object>
```

Just in case, the code above is all Greek to you:

1. http://lena91567.bplaced.net/Hellbl/pinnwand.swf cannot be found. But I’m not sure this missing file will be a problem (once the main issue is solved).

1. http://lena91567.bplaced.net/Hellbl/006699.swf seems to be the SWF file you want to load. 

But in your case, the error reads:

> Error message: WebAssembly is not defined

Well, you need to [Configure WebAssembly MIME Type](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type).

This basically means that you need to configure http://lena91567.bplaced.net, so that web browsers may be able to know how to deal with Ruffle.

Let us know whether you need help or info about how to configure that.

**Comment by ousia** [comment]
@Wahrheit26,

you also need to update file names for SWFs in your code. So your relevant lines should read:

``` html
<object data="./006699.swf" type="application/x-shockwave-flash" width="400" height="400">
    <param name="movie" value="./006699.swf" />
    <param name="allowScriptAccess" value="sameDomain" />
    <param name="quality" value="high" />
    <param name="scale" value="noscale" />
    <param name="bgcolor" value="006699" />
    <param name="menu" value="false" />
</object>
```

At least, `<object data="[...]">` must contain the right name (the name of an existing file).

As far as I have checked, your file works fine: https://github.com/ousia/ruffle-demo.

Feel free to copy what you see it fits for you.

Contents of that repository contain:

1. Uncompressed _Ruffle_ standalone.
1. `index.md` which generates the `index.html` that contains the animation.
1. Your `006699.swf ` animation.

`index.md` contains the code copied above.

Result is served at https://ousia.github.com/ruffle-demo/.

Well, this is also the first time I deploy _Ruffle_ standalone.

**Comment by Wahrheit26** [comment]
Thank you very much for your answers and your help!
I have created a new example.
You can find it here:
http://lena91567.bplaced.net/Tennis/ 
Unfortunately the file does not start automatically. Why not?
you can download the example with all files here:
http://lena91567.bplaced.net/Tennis.zip

**Comment by ousia** [comment]
http://lena91567.bplaced.net/Tennis/ starts the SWF animation automatically on my computer.

`autoplay` is the default with the standalone player. You would need something like this to disable it:

``` js
<script>
window.RufflePlayer.config = {
    "autoplay": "never"
};
</script>
```

And your address has nothing similar to it.

**Comment by Wahrheit26** [comment]
Thanks a lot for your help!
Of course I want the file to play automatically.
Unfortunately the following examples are not played automatically on my computer.
http://lena91567.bplaced.net/Tennis/
http://lena91567.bplaced.net/Tennis/2.html
http://www.ousia.tk/ruffle-demo/
	
Screenshots in the attachment
does anyone have any idea why it does not play automatically on my computer?

![screencapture-lena91567-bplaced-net-Tennis-2020-11-30-09_16_27](https://user-images.githubusercontent.com/63494519/100590660-f9d7a380-32f4-11eb-9dda-bd0785a62858.png)
![screencapture-ousia-tk-ruffle-demo-2020-11-30-09_28_53](https://user-images.githubusercontent.com/63494519/100590666-fb08d080-32f4-11eb-9c62-9ee43559e3f6.png)

**Comment by Poopooracoocoo** [comment]
for me the only one that doesn't autoplay is http://lena91567.bplaced.net/Tennis/2.html I tested them on Chrome and Firefox for Windows.

**Comment by Toad06** [comment]
Autoplay has been implemented in #1556, not in #1161, so the options are different:
```
window.RufflePlayer.config = {
	autoplay: "val", // (val can be "auto" - the default value, Ruffle checks if the browser supports autoplay - "off" or "on" -)
	unmuteOverlay: "val" (val can be "visible" or "hidden" - this option is only useful if autoplay is "on" AND the browser doesn't support autoplay)
};
```

**Comment by Wahrheit26** [comment]
Autoplay does not work in my Google Chrome, but it works in Mozilla Firefox.

**Comment by Wahrheit26** [comment]
I asked some friends to test the following examples on their devices.
http://lena91567.bplaced.net/Tennis/
https://ruffle.rs/demo/
	
This is the result:
no autoplay in Google Chrome und Microsoft Edge
autoplay in Mozilla Firefox und Opera
	
Screenshots of Google Chrome see above.
	
And they said that they would only click the play icon (in Google Chrome) on a friend's Website.
	
You can close this issue.

**Comment by ousia** [comment]
> This is the result:
> no autoplay in Google Chrome und Microsoft Edge
> autoplay in Mozilla Firefox und Opera

@Wahrheit26,

I don’t know whether Chrome and Edge (and other browsers, such as Opera and Safari) disable autplay by default.

If that were the case, I’m afraid there might not be much to be done to solve the issue

Maybe other experienced users can confirm this.

> And they said that they would only click the play icon (in Google Chrome) on a friend's Website.

Totally agree with them.

When Firefox didn’t disable Flash playing by default, many of us had extensions that disabed Flash autoplay.

**Comment by Wahrheit26** [comment]
My cousin told me in his Microsoft Edge autoplay works.
I just wanted to tell you what my cousin told me.
	
**ruffle is great. Fantastic work. Thanks a lot!**

**Comment by Wahrheit26** [comment]
suggestion:
how about setting the background color?
The background color of RufflePlayer is black.
See http://www.ousia.tk/ruffle-demo/
It would be great if its possible to set the RufflePlayer background color, in order to have the same background color as on the page, for example.

`
<script>
window.RufflePlayer.config = {
    "backgroundcolor": "006699"
};
</script>

`

**Comment by ousia** [comment]
@Wahrheit26, as far as I can remember, this is also a feature in Flash.

I found it: [`SetBackgroundColor`](https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf#search=SetBackgroundColor).

I wonder whether it would make more sense to add this information into the Flash animation.

**Comment by Wahrheit26** [comment]
Of course, you can also set the background color in Flash. I have done this as well.
Please have a look at the screenshot.
The background color of the page is green.
And also the background color of the swf to green.
But without autoplay (screenshot from Apple iPhone) there are black bars.
	
I think the black color is the background color of ruffleplayer and therefore it is useful to be able to set the background color of ruffleplayer in my opinion.
	
Or please look at the following example:
http://www.ousia.tk/ruffle-demo/ 
the background color of the page is white.
The background color of the swf is blue.
When the swf is played there are black bars here too. This is very bad in my opinion.

![IMG_1915](https://user-images.githubusercontent.com/63494519/101779946-2f9b3a00-3af6-11eb-8736-14ec5f510031.PNG)

**Comment by ousia** [comment]
@Wahrheit26, if Ruffle doesn’t honor [SetBackgroundColor](https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf#search=SetBackgroundColor), then we should open another issue report.

I can do that, but please provide me with the address in which the SWF document has backgroundcolor set to green.

**Comment by ousia** [comment]
@Wahrheit26, pull request #2453 has fixed the issue #1755.

Could you update _Ruffle_ at http://lena91567.bplaced.net/Tennis/2.html to check whether it works when auto-play isn’t enabled?

**Comment by ousia** [comment]
@Wahrheit26, according to https://ousia.github.io/ruffle-demo/, the player doesn’t get `SetBackgroundColor` from SWF file, but it gets it from the `bgcolor` parameter.

![bgcolor](https://user-images.githubusercontent.com/203767/104604764-fe2a0700-567d-11eb-8b21-f5e5c95cf470.png)

**Comment by ousia** [comment]
Sorry, I forgot to mention: if you update the player, the issue will be fixed.
