### ISSUE TITLE
Ruffle Web: Error name: CompileError WebAssembly.Module doesn't parse at byte 0

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1756]
Morning All, 

Since updating to the latest code. Previously I was using code from 22nd November, I'm getting errors. Not sure what needs to be changed in my code? 

**Safari Error Log:**
`# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'

# Player Info
Allows script access: false

# Page Info
Page URL: https://ridesims.com/ride-simulators/Galactica

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-11-28
Channel: nightly
Built: 2020-11-28T00:31:04.155Z
Commit: 602a343995df0dea6fa73121b90f5f68a0804e77`

**Implementation code:** 
`		$output .= "<script>";
		$output .= "window.RufflePlayer = window.RufflePlayer || {};";
		$output .= "window.RufflePlayer.config = {";
		$output .= "    'public_path': '/ruffle',";
		$output .= "    'polyfills': 'true',";
		$output .= "    'autoplay': 'on',";	
		$output .= "}";
		$output .= "</script><script src='https://ridesims.com/ruffle/ruffle.js?a=".date('Y-m-d-h-i')."'></script>";`

**Comment by Toad06** [comment]
Try changing `public_path` to `publicPath`.

**Comment by JamesAllgood** [comment]
Thanks Toad06! that was my issue
