### ISSUE TITLE
angry birds space regression since nightly 2024-02-28

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#17564]
### Describe the bug

the sounds of pigs are played abnormally frequenly

https://github.com/user-attachments/assets/3b1246d7-c07c-4ced-b538-806a0402d101

### Expected behavior

https://github.com/user-attachments/assets/423fef8a-f473-439b-ade2-592ac895d7c4

### Content Location

[angry-birds-space.zip](https://github.com/user-attachments/files/16661128/angry-birds-space.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by torokati44** [comment]
This was probably due to https://github.com/ruffle-rs/ruffle/pull/15316 then...
