### ISSUE TITLE
Syncing the timeline back to a streamsound with inactive tab

### ISSUE THREAD

**Issue by Dwedit** [ruffle-rs/ruffle#1760]
I'm still wondering what can be done about skipping frames when the browser tab is inactive.  This is only a concern when a Stream Sound is playing, otherwise, skipping ahead isn't as important.

You know the timestamp of the last time you successfully executed a frame, and you know how long the streamsound has been playing, so you can calculate how many frames will need to skip to catch up.

So rather than literally skipping ahead (like gotoAndPlay), we'd want to run frames very quickly.

You can obviously skip the drawing process.

For placing things on the stage, you can skip shapes and text just like it is seeking.  Buttons and Movie Clips are visible to Actionscript, so their placement, removal, and timelines must be simulated.  Any OnClipEvent handlers for EnterFrame must be handled.  So if you skip 1000 frames, that may result in running EnterFrame handlers 1000 times.

In the event that ActionScript needs to do a hit test on a pixel of a Movie Clip or something like that, then you'll have to go back to calculating the positions of shapes and the like.

Fortunately, chances are good that if you're playing a streaming sound, it's more of a Flash Movie than a Flash Game, so there won't be that much ActionScript code executing every frame.

So the above text described what to do when you return to a formerly backgrounded-tab, and time has passed, and you need to skip ahead.

As for what you can do while the tab is in the background:

You can keep running the ActionScript code on the timeline and the EnterFrame clip events.  But if you run out of CPU time, and lose the ability to continue running code, just Pause the stream sound.

This is not a good workaround, but if there is a plain old "Stop" on the timeline, perhaps stop the stream sound at that time, so it won't play past the end.

**Comment by Herschel** [comment]
Thanks for the report! Closing in favor of #347.

Unfortunately modern browsers do not like to allow Javascript to run when a tab is not visible -- we are the mercy of the browser in this case, so we are unable to update the movie. And in general I think we should obey this, so we need to completely pause the player when invisible.

As Flash movie clips are delta-encoded, even seeking to a position involves fully simulating every frame up to that point (additionally commonly use code like V-Cams blurs the distinction between animation and game).
