### ISSUE TITLE
can't exit fullscreen with ESC in desktop app

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#17617]
### Describe the bug

can't exit fullscreen with ESC in some games that enter fullscreen at launch

### Expected behavior

exit fullscreen when pressing ESC

### Content Location

[pong.zip](https://github.com/user-attachments/files/16730534/pong.zip)
[china-checkers.zip](https://github.com/ruffle-rs/ruffle/files/12286235/china-checkers.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by kjarosh** [comment]
It seems that this behavior was there before https://github.com/ruffle-rs/ruffle/pull/17595 and https://github.com/ruffle-rs/ruffle/pull/17592.

For pong, it seems that Ruffle incorrectly assumes that the game is not in full screen at the beginning.

CC @torokati44 @sleepycatcoding

**Comment by sleepycatcoding** [comment]
Both SWFs use the fullscreen fscommand to make Ruffle fullscreen and we (for some reason?) bypass the player (desyncing the fullscreen state) and set it on the window directly.
https://github.com/ruffle-rs/ruffle/blob/d17b29c1652edcb47b55f30ffc6d912e28eb22fb/desktop/src/backends/fscommand.rs#L19-L24
