### ISSUE TITLE
view recieved assets in ruffle debug

### ISSUE THREAD

**Issue by Croworbit** [ruffle-rs/ruffle#17621]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

this is probably only useful on desktop

when I load a newgrounds medal game using flash player, the medal icons don't appear, but ruffle does show them

I then found out that the SWFs don't actually have the medal icon data, its all just pulled from NG's api
in some games, I want the icons of the medals, but obviously decompiling the swf wouldn't work.

of course, going to newgrounds and getting the images is pretty simple, either look at the network tab and get the file, or copy the images off the desciption that shows them (minus hidden medals)

but it got me thinking, does ruffle have a log that shows what network resources it has grabbed?

this would be kinda handy for things like this, not necessarily just images and not just from newgrounds
a log, or something like the network tab on browsers but just in ruffle's debug section?

https://github.com/user-attachments/assets/d9ceb2dd-fad3-4934-88be-fcbc84c1033f

it'd be pretty handy to see what values are being pulled in, or images being downloaded that aren't part of the swf directly
I know ruffle isn't about this kind of preservation specifically, but It would be handy

**Comment by n0samu** [comment]
Ruffle already lists loaded images in the "Known Movie List", see #12033. As indicated in that issue, I do hope we can separate images out into their own list.

If you can provide a valid example of Ruffle not listing loaded external images there, please do so. But your video shows medal images loaded via the webpage itself, not Ruffle. You can see that the initiators of those requests are img tags, and that they are webp images, which Flash does not support!

**Comment by Croworbit** [comment]
hmm. I guess I was confused also by the problem in that issue

on another note, the video was an example
I do like the popup image preview from that tab
I'll make a different issue
