### ISSUE TITLE
A list of flashes working and not on z0r.de

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#1766]
Hi everyone.
I stumbled upon this Ruffle project, and remembered that I saved a loooong ago the list of z0r.de links which contain short flashes.
I will do the list of working ones and those with issues here in one place because:
1) I do believe filing the massive amounts of issues for generally short flash movies could clog this place
2) I think the reviewer of this will know better what kinds of actual technical issue reports to create afterwards 
Also I don't know how to determine if there are ActionScript 3 things in the flash or not, and I see the ability to see that in Ruffle is in a recently opened issue (https://github.com/ruffle-rs/ruffle/issues/1713). Or maybe there is a possibility to know that already, without decompiling and stuff (I have no technical knowledge of Flash whatsoever)?

Please tell me if one-flash-per-issue is a thing you really want, instead of this list.
And be aware before reviewing this that it may contain a huge amounts of dumb (:

I will include the other z0rs (either in a separate issue, or I can pile them up right here) after I see the feedback on this issue. Maybe for example I'll stop reporting the "blank video" stuff if I get the message that it's a clear sign of an unsupported-yet-feature, and not a bug of something currently implemented.

Run in Chrome
Build: https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-28

Working ones (actually in Ruffle they mostly work better as it doesn't paint the out-of-bounds area in white and AdobeFlash does that for some reason):
https://z0r.de/2715
https://z0r.de/2829
https://z0r.de/2789 
https://z0r.de/118
https://z0r.de/1216
https://z0r.de/1352
https://z0r.de/1415 (EPILEPSY WARNING)
https://z0r.de/1755
https://z0r.de/2186
https://z0r.de/2196 (working fine, but there is a dotted line present far left and far right in Adobe, but not in Ruffle. I guess it's out-of-bounds, but it's shown in Adobe?)
https://z0r.de/2234 (much of the out-of-bounds non-white stuff seen in Adobe again, but not in Ruffle)
https://z0r.de/2272

Issues:
https://z0r.de/3084  
https://z0r.de/3030
https://z0r.de/2989
https://z0r.de/2954
https://z0r.de/2285
https://z0r.de/2811
https://z0r.de/2809
https://z0r.de/2779
https://z0r.de/2770
https://z0r.de/1176
https://z0r.de/1889
https://z0r.de/2156
https://z0r.de/2183
https://z0r.de/2202
https://z0r.de/2263
https://z0r.de/2307
https://z0r.de/2327
https://z0r.de/2339
The sound is present, but the screen is **white** blank. I guess many of those have some sort of recorded video in them, which isn't supported in Ruffle yet? Some of the "recorded video" stuff actually works in Ruffle though.

https://z0r.de/1585
https://z0r.de/2062
https://z0r.de/2214
The sound is present, but the screen is **black** blank.

https://z0r.de/3000
The sound is present, but the screen is **black** blank. Only thing shown is "Inv" text at the top-left.

https://z0r.de/2097
Sound is present, the screen is white before the properly shown text string "YOU FAILED". I guess unsupported video stuff?

https://z0r.de/3070
In the Ruffle playback, Russian letters in the floating string are missing. The only thing is left to show from a floating string is "!!!"

https://z0r.de/2817
The Chinese characters are showing in Ruffle, but in a strange way where the intersections between strokes in the characters are transparent. Not the issue in Adobe playback (all the characters are of solid color).
![image](https://user-images.githubusercontent.com/75184268/100526699-7dea3800-31dc-11eb-8c8d-6cd807aad34a.png)

https://z0r.de/2816
There is a strange horizontal alignment issue if you look at the falling snow and the screen borders. Also there is something about green out-of-bounds in the Adobe playback, which Ruffle doesn't have

With Adobe:
![image](https://user-images.githubusercontent.com/75184268/100526755-fe109d80-31dc-11eb-8e8f-ad42a9c342e7.png)
With Ruffle:
![image](https://user-images.githubusercontent.com/75184268/100526741-dde0de80-31dc-11eb-8989-464de6ba82aa.png)

https://z0r.de/2073
https://z0r.de/2118
https://z0r.de/2240
Those are the ones which got my attention, but maybe it's noticeable in others.
This is working fine visually, but the sound is definitely different in Adobe and Ruffle playbacks. It's certainly not played with 1:1 accuracy to the original. Ruffle playback sounds muffled. Either because of some sort of codec/bitrate issues or Ruffle has some filtering applied. If it's the intended way the music should sound in Ruffle, a toggle option could be great which turns sound playback to the original.

https://z0r.de/2330
This has sound, but the visuals are all gray. The difference between the others which fail to show the "video" part is that the first frame of the "video" (and the black string which is briefly shown on top of the "video" part) is clearly seen before turning into all-gray in Ruffle.

**Comment by Herschel** [comment]
Thanks for the reports! You can press F12 to bring up the Chrome developer console, which will have a warning message if you are trying to play an AS3 file.

**Comment by Diatonator** [comment]
Thanks for response! Apparently there is no mention of AS3 in the console. Typical console for "blank" videos is like this:

![image](https://user-images.githubusercontent.com/75184268/100536661-17443900-3233-11eb-8a85-5696bc477b74.png)
[z0r.de-1606636914512.log](https://github.com/ruffle-rs/ruffle/files/5611854/z0r.de-1606636914512.log)

Thus I'll continue to report those files as of now

**Comment by Diatonator** [comment]
Working ones:
https://z0r.de/2347
https://z0r.de/2398
https://z0r.de/2409
https://z0r.de/2432

Issues:
https://z0r.de/2350
https://z0r.de/2361
https://z0r.de/2448
https://z0r.de/2458
https://z0r.de/2460
https://z0r.de/2463
https://z0r.de/2516
https://z0r.de/2497
Sound present, the screen in **white** blank

https://z0r.de/2358
Sound present, the screen in **black** blank

https://z0r.de/2365
https://z0r.de/2389
https://z0r.de/2436
Working fine, but noticeable muffled sound (as I described earlier)

https://z0r.de/2370
Not only the screen is white blank, but also the sound is heavily glitched

https://z0r.de/2464
Working fine, but on that clip I found an interesting issue. If you switch out of the tab where the flash plays, the flash should continue playing, and it fully does in Adobe player. In Ruffle though, the sound is non-interrupted, but the video bit pauses before you jump back to the tab, and it creates a desync issue. This was very noticeable as this is a sort of "karaoke" clip.

**Comment by Diatonator** [comment]
Working ones:
https://z0r.de/2545
https://z0r.de/2657
https://z0r.de/341
https://z0r.de/380
https://z0r.de/439
https://z0r.de/1024
https://z0r.de/1042
https://z0r.de/105
https://z0r.de/1068
https://z0r.de/1089
https://z0r.de/110
https://z0r.de/113

Issues:
https://z0r.de/2588
https://z0r.de/2598
https://z0r.de/2624
https://z0r.de/2636
https://z0r.de/2663
https://z0r.de/2664
https://z0r.de/870
https://z0r.de/1035
https://z0r.de/1071
Sound present, the screen in **white** blank

https://z0r.de/2530
https://z0r.de/2601
https://z0r.de/2615
https://z0r.de/832
https://z0r.de/1002
https://z0r.de/1025
https://z0r.de/1118
Sound present, the screen in **black** blank

https://z0r.de/2622
https://z0r.de/422
https://z0r.de/98
https://z0r.de/1026
https://z0r.de/1088 (fairly minor sound difference)
https://z0r.de/1124 (fairly minor but noticeable in hi-hats)
Working fine, but noticeable muffled sound (as I described earlier)

**Comment by Diatonator** [comment]
Ok it's apparent that the issues with blank video and muffled sound are the most prevalent, and I think I've put quite enough examples.
I'll look again at them when the other more finished build will be available.
From now I'll report in this issue only the unique problems.

https://z0r.de/1348 (EPILEPSY WARNING)
The flash is working, except the text in the top-left is not shown ("Powered by Namo FreeMotion").

https://z0r.de/1490
This has the visual issue - Ruffle's video playback is much more "blocky" than the Adobe's. The muffled audio is here as well.

https://z0r.de/1526
The flash is working, the text at the bottom-left clearly has a different font in Ruffle

https://z0r.de/1785
This one is pretty minor, but in Ruffle this little "crack" between "buildings" in the flash clip is more noticeable because it flashes over time, when in Adobe it's fairly solid and inanimate. I decided to report this, because who knows maybe some other clips may show this issue in a more irritating manner.

In Adobe
![1785_Adobe](https://user-images.githubusercontent.com/75184268/100540204-f2f55600-324c-11eb-9b75-b23d30dcb7c6.gif)
In Ruffle
![1785_Ruffle](https://user-images.githubusercontent.com/75184268/100540176-b164ab00-324c-11eb-9188-314b359025a6.gif)

https://z0r.de/1875
1) The sound is not present at all.
2) While overall the visuals are fine, there is an issue with the "glow" effect on the text at "night" cycle

Adobe
![1875_Adobe](https://user-images.githubusercontent.com/75184268/100540568-1faa6d00-324f-11eb-87d7-6da06155ed95.gif)
Ruffle
![image](https://user-images.githubusercontent.com/75184268/100540534-e2de7600-324e-11eb-9d99-4e1648e42c14.png)

**Comment by Diatonator** [comment]
https://z0r.de/1953
Works fine, but there is a clear absence of any blur in the Ruffle playback. Not that it makes those visuals much worse :) Although that's a clear difference. Something unimplemented yet?

Adobe
![image](https://user-images.githubusercontent.com/75184268/100542862-cbf35000-325d-11eb-88ee-285e64c98bb1.png)
Ruffle
![image](https://user-images.githubusercontent.com/75184268/100542878-f04f2c80-325d-11eb-8834-3cff2110bfc5.png)

**Comment by Diatonator** [comment]
https://z0r.de/3249
https://z0r.de/150

The video part is playing faster on Ruffle than on Adobe while the sound is of the same speed. I'm actually not really sure which is the intended way. My guess is that there is some kind of speed-up feature in the Flash which was used for these clips, but maybe Ruffle processes this wrongly?

With Adobe:
![3249_Adobe](https://user-images.githubusercontent.com/75184268/100544535-7fad0d80-3267-11eb-902c-208dc33c405a.gif)

With Ruffle:
![3249_Ruffle](https://user-images.githubusercontent.com/75184268/100544537-83409480-3267-11eb-8420-48253db1d8b1.gif)

https://z0r.de/1495
The text at the bottom-left doesn't have the black shade.

With Adobe:
![image](https://user-images.githubusercontent.com/75184268/100545050-e67ff600-326a-11eb-8a01-4c52501c12e8.png)

With Ruffle:
![image](https://user-images.githubusercontent.com/75184268/100545036-ca7c5480-326a-11eb-8819-8e5544087e17.png)

**Comment by grishka** [comment]
> The text at the bottom-left doesn't have the black shade.

The general issue, it seems, is that Ruffle doesn't support these, iirc, so-called "raster effects" — blur, glow/shadow, etc. This causes this sort of incorrect rendering in *many* SWFs.

**Comment by Diatonator** [comment]
https://z0r.de/2063

Look closely at the right panel - some of the outlines from BGM are bleeding onto the panel

![2063_Ruffle](https://user-images.githubusercontent.com/75184268/100546338-ef27fa80-3271-11eb-8125-7b6e6e477308.gif)

**Comment by Diatonator** [comment]
https://z0r.de/3346
Sound level control doesn't work. I seen the open issue regarding this, I'll test this on a later builds.

**Comment by Diatonator** [comment]
https://z0r.de/2264
This have a AS3 warning, but I'll leave it here for just how bizzare it now looks in Ruffle

Adobe
![2264_Adobe](https://user-images.githubusercontent.com/75184268/101995938-199c9d80-3cdf-11eb-9499-ce33c47e9fb7.gif)

Rufle
![2264_Ruffle](https://user-images.githubusercontent.com/75184268/101995960-3fc23d80-3cdf-11eb-9844-5a718d69b702.gif)

**Comment by Diatonator** [comment]
https://z0r.de/3098
Won't put GIFs because fairly eyedamaging, but the Ruffle playback doesn't have the "negative photofilter" frames, where Adobe does have.
No AS3 warning.

**Comment by Diatonator** [comment]
https://z0r.de/1589
This has AS3 warning, but again some interesting stuff happens

![image](https://user-images.githubusercontent.com/75184268/101998680-75b6f000-3ce6-11eb-9ec4-e462f86257e6.png)

Adobe
![1589_Adobe](https://user-images.githubusercontent.com/75184268/101998705-b57dd780-3ce6-11eb-9017-5004eda2df8e.gif)

Ruffle
![1589_Ruffle](https://user-images.githubusercontent.com/75184268/101998710-b9a9f500-3ce6-11eb-9dfa-ae3d21b15f16.gif)

**Comment by Diatonator** [comment]
https://z0r.de/6883
No AS3 warning

Something apparently is going on here:
![image](https://user-images.githubusercontent.com/75184268/101998831-ca0e9f80-3ce7-11eb-8af7-7c0eb8049fa6.png)

While visually I can't see any real difference!
The flash loop have many rotating, stretching numbers appearing, moving and disappearing randomly. Also it has an imitation of the wall clock. Maybe the actual visual difference is buried somewhere between all this stuff and barely noticeable.

**Comment by Diatonator** [comment]
https://z0r.de/5218

1) Apparent problem in some JPEG? Maybe it's the "road" one?
![image](https://user-images.githubusercontent.com/75184268/101998931-c0d20280-3ce8-11eb-831e-6adaae82463c.png)

2) Clouds doesn't have any color gradient - they are just solid gray.

Adobe
![image](https://user-images.githubusercontent.com/75184268/101998945-dcd5a400-3ce8-11eb-8690-e0b34efe3847.png)

Ruffle
![image](https://user-images.githubusercontent.com/75184268/101998937-d2b3a580-3ce8-11eb-93bf-f8de4adcf59e.png)

**Comment by Diatonator** [comment]
https://z0r.de/4072 (EPILEPSY WARNING)
There is the foreground animation (or gif) which should be normally transparent

Adobe
![image](https://user-images.githubusercontent.com/75184268/101999224-03e1a500-3cec-11eb-8fe9-246d3bb318e7.png)

Ruffle
![image](https://user-images.githubusercontent.com/75184268/101999220-f88e7980-3ceb-11eb-9e11-9a118d7ddd1f.png)

**Comment by JMcKiern** [comment]
> https://z0r.de/3098

> https://z0r.de/5218
> Clouds doesn't have any color gradient - they are just solid gray.

I'm going to guess these are blend mode issues

> https://z0r.de/5218
> Apparent problem in some JPEG? Maybe it's the "road" one?

This looks like it could be an issue with the jpeg_decoder crate.

> https://z0r.de/4072 (EPILEPSY WARNING)
> There is the foreground animation (or gif) which should be normally transparent

The character uses multiply blend mode. These are not implemented as far as I know

**Comment by Diatonator** [comment]
https://z0r.de/6728
The issue in the playback is minor. Just an interesting issue, which probably may occur more severely on some other flashes.
On Adobe the flash loop is loaded instantly, but in Ruffle - with some delay.
To be exact, in Ruffle it waits before a bunch of errors occurs, only then starts the playback:
![6728_Ruffle](https://user-images.githubusercontent.com/75184268/102016328-721c7b00-3d71-11eb-81d9-32ddf946d400.gif)

**Comment by Diatonator** [comment]
https://z0r.de/2015
Same a above, but with a slight twist, and also the flash was loading for like 5 solid seconds in Ruffle! Adobe - again, instant load.
![2015_Ruffle](https://user-images.githubusercontent.com/75184268/102263562-87d2a180-3f25-11eb-8885-7c2681a83ca3.gif)

**Comment by Diatonator** [comment]
https://z0r.de/985
This flash has some bizzare problem. When you open it normally from Adobe or Ruffle, it plays ok. But when you try to play this flash while F12 developer console is on, and you press F5 (Refresh the page), in Ruffle the flash greatly slows down, while Adobe playback is unaffected.
Both happens on Firefox and Chrome.

Adobe:
![985_Adobe](https://user-images.githubusercontent.com/75184268/102265450-2fe96a00-3f28-11eb-90ac-5186e834c45f.gif)

Ruffle:
![985_Ruffle](https://user-images.githubusercontent.com/75184268/102265463-337cf100-3f28-11eb-9956-274b602512ad.gif)

**Comment by Diatonator** [comment]
https://z0r.de/1547
Something funky with the text, again. Probably related to many above.
1) Different font
2) The text placed (spaced) differently

Adobe:
![1547_Adobe](https://user-images.githubusercontent.com/75184268/102267447-f9611e80-3f2a-11eb-8422-40a535b5c771.gif)

Ruffle:
![1547_Ruffle](https://user-images.githubusercontent.com/75184268/102267458-fc5c0f00-3f2a-11eb-8f3d-8b54057a281a.gif)

**Comment by Diatonator** [comment]
https://z0r.de/2275
Perfectly working interactive flash
Except few small details:

1) text on the top lext box isn't shown
2) the number under this text has different font

I'm hard pressed to find any other difference.

Adobe:
![image](https://user-images.githubusercontent.com/75184268/103033605-e32f1000-4573-11eb-9fde-56f557948490.png)

Ruffle:
![image](https://user-images.githubusercontent.com/75184268/103033456-8af80e00-4573-11eb-8c36-ea59bc6d7d66.png)

**Comment by Diatonator** [comment]
https://z0r.de/2362

1) No text glow (i guess related to some above and unimplemented)
2) The number in the middle is positioned incorrectly and has other font. That's strange here because the left and right strings are perfectly normal font-wise.

Adobe: 
![image](https://user-images.githubusercontent.com/75184268/103034816-d829af00-4576-11eb-8bb8-af5f757ddfd8.png)

Ruffle:
![image](https://user-images.githubusercontent.com/75184268/103034610-5174d200-4576-11eb-8961-b9b7f050ed6a.png)

**Comment by Diatonator** [comment]
https://z0r.de/441 (EPILEPSY WARNING)
This flash works OK, but writes interesting stuff in Console:

![image](https://user-images.githubusercontent.com/75184268/103038042-6fdecb80-457e-11eb-9b5f-105f771f22fa.png)

Do I understand correctly that it's some sort of troll flash which is intended to mess with the one who would open it? Like, forcebly going fullscreen and disabling keyboard keys? Although I certainly don't really remember the oldest of days of Flash, maybe it was possible back then?

**Comment by Diatonator** [comment]
https://z0r.de/2010
This has similar problems as https://z0r.de/985 (https://github.com/ruffle-rs/ruffle/issues/1766#issuecomment-745528254) - with the open F12 console (sometimes without) it can slow down drastically (as it's an interactive flash - slows down only if you move mouse over it, but otherwise plays perfect), while Adobe playback is fine everytime.
Also some huge amount of some sort of errors, maybe they are totally unrelated:

![2010_Ruffle](https://user-images.githubusercontent.com/75184268/103039626-5e97be00-4582-11eb-93c0-b181b65c0575.gif)

**Comment by Diatonator** [comment]
OK, I don't think this issue is worth keeping open.
Everything here works either in full, with minor barely noticeable problems (like blur, glow), or problems like font issues or sound issues which are long known.
What can I say - congratulations for everyone for such an achievement in actually getting a huge amount of stuff working over this time!
I'll branch out only https://z0r.de/1589 because it's still kinda broken in the same strange way and now seems like actually reporting some useful (maybe) errors.
