### ISSUE TITLE
Sound.loadSound: Unimplemented / Apache and NGINX 

### ISSUE THREAD

**Issue by ricardoseb** [ruffle-rs/ruffle#1768]
Hello!
When I try to use your library on a web server (I have tested it in apache and nginx) the flash plays without problems until the moment when an audio (mp3 format) must be played, generating the following alerts:
![image](https://user-images.githubusercontent.com/31752537/100530738-555e4000-31d4-11eb-8d74-dd4d31e7a133.png)

The swf and mp3 files can be found in the following url if you want to try them yourself:

[http://columnize.cl/conducete/modulo1/modulo_01_a/modulo_a.html](url)

**Comment by wcbx** [comment]
Would be nice to have this.

**Comment by n0samu** [comment]
This feature was added in #6738. I cannot check if it works on this specific site since the link no longer works. Leave a comment if something is still missing and I can reopen the issue.
