### ISSUE TITLE
[Regression] Text boxes stop music playback in Super Mario Bros Z Episode 6

### ISSUE THREAD

**Issue by crumblingstatue** [ruffle-rs/ruffle#17718]
### Describe the bug

In [Super Mario Bros Z Episode 6](https://github.com/user-attachments/files/16826051/smbzep6.zip), when a text box appears to show dialogue, the music playback is stopped. This is a regression as this didn't use to happen, and it isn't supposed to happen.
The music is supposed to keep playing while the text box is open.
The adobe flash player also keeps playing the music.

I'm not exactly sure when the regression was introduced, but I remember playing the episode back in June, and this issue wasn't present back then.

### Expected behavior

The music should keep playing

### Content Location

[smbzep6.zip](https://github.com/user-attachments/files/16826051/smbzep6.zip)

Also, https://www.newgrounds.com/portal/view/380713/format/flash

The ruffle web player on newgrounds also exhibits the regression.

### Affected platform

Desktop app, Web player

### Operating system

Linux (X11, ALSA/Pipewire)

**Comment by Lord-McSweeney** [comment]
@Dinnerbone this was probably regressed by #17016
