### ISSUE TITLE
[Feature Request] Add Volume Controls to Right-Click Menu

### ISSUE THREAD

**Issue by Miserlou** [ruffle-rs/ruffle#1771]
Awesome project, great work!

Since lots of old flash projects weren't very well mixed, they can end up being much louder or quieter than other things going on in the system. It'd be great if the Ruffle right click menu could have some volume controls to avoid unintentional ear damage.

Cheers!
Rich

**Comment by sauntheninja2** [comment]
I'm assuming we will need to use different API's depending on the platform for linux and Windows for volume controls?
