### ISSUE TITLE
Hot BBQ Party: ReferenceError: Error #1069: Property startDrag not found on element.Food and there is no default value.

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#17725]
### Describe the bug

When you start the first level, it is not possible to drag the food.

```
Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x363fe88 }) to handler FunctionObject(FunctionObject { ptr: 0x31f26a8, name: Ok("main::UI_Ingame/clickfood()") }) : ReferenceError: Error #1069: Property startDrag not found on element.Food and there is no default value.
at logic::SetFollowMouseFoodPos/startSetProperty()
at logic::SetFollowMouseFoodPos/clickfood()
at logic::SetFollowMouseFoodPos/getFollowMouseFoodAndClick()
at main::UI_Ingame/clickfood()

```

or

```
Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x342d968 }) to handler FunctionObject(FunctionObject { ptr: 0x31fe008, name: Ok("main::UI_Ingame/clickmc()") }) : ReferenceError: Error #1069: Property stopDrag not found on element.Food and there is no default value.
at logic::SetFollowMouseFoodPos/resumeProperty()
at logic::SetFollowMouseFoodPos/clickmc()
at main::UI_Ingame/clickmc()
```

### Expected behavior

drag the food

### Content Location

Game URL - https://www.gameflare.com/online-game/hot-bbq-party/
SWF URL - https://data.gameflare.com/games/1002/ZnOy81zTtMgS7n.swf

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
`element.Food` extends Sprite which implements `startDrag` and `stopDrag`, are you sure you're using the latest version of Ruffle?

**Comment by MartySVK** [comment]
> `element.Food` extends Sprite which implements `startDrag` and `stopDrag`, are you sure you're using the latest version of Ruffle?

yes, you can try it online here - https://www.gameflare.com/online-game/hot-bbq-party/
just skip the tutorial and start the first level

Built: 2024-09-01

**Comment by Aaron1011** [comment]
The API version applied to `startDrag`/`stopDrag` seems to be incorrect (despite what the flash playerglobal shows)

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/17732
