### ISSUE TITLE
Add file dialogs when the Ruffle desktop app is opened

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1774]
Lots of people don't realize that the desktop app is a command line program (and to be honest, it isn't very obvious). That's why it might be a good idea to add file prompts whenever the program is opened outside of the command line. [nfd-rs](https://github.com/saurvs/nfd-rs) might help with achieving this, though if you want URL support as well then it might take some more effort.

**Comment by SamMorrowDrums** [comment]
@WumboSpasm feel free to give my branch a try - it works well, and it's not super weird that it just pops open a file dialogue. That's a much better UX than error message.
