### ISSUE TITLE
Files without extension part in their name aren't shown to be opened

### ISSUE THREAD

**Issue by PavanLuca** [ruffle-rs/ruffle#17776]
Any file without its extension format in its name isn't shown in the file picker.

Zorin OS Core 17.1, X11

**Comment by kjarosh** [comment]
It appears that rfd just does not support filters for files without a dot in their name:

https://github.com/PolyMeilex/rfd/blob/42dcc7d61fc5e278b4ed76bb9720ba4d89266f01/src/backend/xdg_desktop_portal.rs#L31
