### ISSUE TITLE
Fail example

### ISSUE THREAD

**Issue by ursi** [ruffle-rs/ruffle#1777]
This is one of my favourite games and sadly ruffle doesn't seem to make it work. Every other game I've tried so far has worked. I thought an example of a non-working flash app could be of some use.

I'm using 2020-11-29 on Brave "Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)"

http://www.vivalagames.com/play/pel/

**Comment by zanzlanz** [comment]
That game uses AS3, which is currently not supported - see #1368
