### ISSUE TITLE
No OpenGL support on native?

### ISSUE THREAD

**Issue by Subsentient** [ruffle-rs/ruffle#1782]
I understand why it works in browsers with WebGL, but it appears that if your hardware doesn't natively support Vulkan, as the Mali 400 GPU in my PinePhone does not, you cannot use Ruffle. My phone is capable of at least desktop OpenGL in addition to OpenGL ES. Ruffle runs very poorly on limited hardware as WASM, so I was trying to get a more usable experience with native code.

I think that due to the sheer number of OpenGL capable GPUs, Ruffle needs OpenGL support.

**Comment by Herschel** [comment]
The [OpenGL backend](https://github.com/gfx-rs/wgpu-rs/pull/606) has recently been merged into wgpu, so we will hopefully get OpenGL support back soon.

**Comment by relrelb** [comment]
I have updated `wgpu` in https://github.com/ruffle-rs/ruffle/pull/1510/commits/80b6e882c9065164e3f0e4550d9ec050fdb2c4a7, currently as part of #1510, but it can be split into a separate PR.

**Comment by Futurama39** [comment]
would you please? i’ve tried to use ruffle in conjunction with libTAS but as of now it supports only OpenGL rendering

**Comment by torokati44** [comment]
I made a report about this, but I don't know enough about the Ruffle internals to help them fix it... :/
https://github.com/gfx-rs/gfx/issues/3562

**Comment by LorenDB** [comment]
Is this coming along at all?

**Comment by torokati44** [comment]
It should be in place now, try adding `--graphics gl` as command line arguments.

**Comment by LorenDB** [comment]
Hm, maybe I should try upgrading my install. I installed it from some random openSUSE repo on OBS and I think it is a bit old :P

**Comment by LorenDB** [comment]
OK, GL now does work.

**Comment by torokati44** [comment]
For the record: I find the OpenGL renderer backend to be really glitchy on Wayland, but works perfectly fine on X11. Perhaps a `winit` issue...?

**Comment by LorenDB** [comment]
Wayland has been working fine for me except for some issues with the window going semi-transparent under some objects.

**Comment by torokati44** [comment]
That's one of the glitches, yeah... 😃 And then there's resizing...
