### ISSUE TITLE
Pulseaudio buffer underrun warning and broken audio

### ISSUE THREAD

**Issue by SamMorrowDrums** [ruffle-rs/ruffle#1785]
Pulseaudio on Ubuntu gave me buffer underrun warnings - so I tried editing `/etc/pulse/daemon.conf` and restarted my machine.

I set default-fragments from 4 to 5

```
; default-fragments = 5
```

I'm reporting this as an error because it potentially means that some users may find Ruffle doesn't work OOTB on Linux, and this fixed it for me. Of course there is also a small chance that restarting the machine resolved an extraneous issue, so I'm interested to see if anyone else has encountered this.

It is currently unclear to me if there is anything that ruffle should do, or perhaps it should be an issue in https://github.com/RustAudio/cpal

I might try changing the default setting back, and seeing if I can repro and if it's possible to adjust audio buffering to fix - but I have successfully played a swf now - so I can also close the issue if nobody else encounters it. I also don't know if release builds would repro - so I'm possibly posting this issue a little prematurely.

I'm currently getting the project ready for future collaboration, and I'm not quite ready to get stuck in today - but I didn't want to overcome an issue and then fail to at least mention how I got past it.

**Comment by SamMorrowDrums** [comment]
I think this was just constrained system resources TBH.

**Comment by parkerlreed** [comment]
Yeah some flash games tend to spike CPU usage. Might be some possible optimizations that could be done there.
