### ISSUE TITLE
Make a CORS Proxy to work with ftp sites that don't support cross origin on other sites

### ISSUE THREAD

**Issue by testing-platform-games** [ruffle-rs/ruffle#17880]
**Describe the feature**
Make a CORS Proxy to work with ftp sites that don't support cross origin (ex: drv2web, archive.org) so that these site work with websites from another origin (ex: Google Sites)

**Comment by n0samu** [comment]
This is outside the scope of the Ruffle project, but you can use a service such as https://corsproxy.io/
