### ISSUE TITLE
2Advanced v5 won't run past loader

### ISSUE THREAD

**Issue by sardaukar** [ruffle-rs/ruffle#17892]
### Describe the bug

Visiting the [2Advanced website from 2005 (v5)](https://web.archive.org/web/20060823035223/http://2advanced.com/) it won't progress past "Autokern init" 
![image](https://github.com/user-attachments/assets/415434a1-0a5d-4f0c-b8f0-8813565f5d8b)

### Expected behavior

Website should load past the splash screen (I think, not sure if it needs additional downloads that are not on the Wayback machine). The console does say `ERROR core/src/library.rs:213 Tried to instantiate non-registered character undefined`

### Content Location

https://web.archive.org/web/20060823035223/http://2advanced.com/

### Affected platform

Browser's extension

### Operating system

macOS 14.6.1

### Browser

Firefox 103

**Comment by evilpie** [comment]
The SWF requests three following pages, which are all missing from archive.org. There is probably nothing we can do.

https://web.archive.org/web/20060823035223/https://2advanced.com/getData.php?lang=en&rand=1156305154074&args=uiconfig
https://web.archive.org/web/20060823035223/https://2advanced.com/getData.php?lang=en&rand=1156305154074&args=touts
https://web.archive.org/web/20060823035223/https://2advanced.com/getData.php?lang=en&rand=1156305154074&args=fonts

**Comment by redkit75** [comment]
Maybe they can add it here.
https://www.patreon.com/2Advanced/shop
