### ISSUE TITLE
Theme detection on startup stopped working

### ISSUE THREAD

**Issue by kjarosh** [ruffle-rs/ruffle#17986]
### Describe the bug

When you start Ruffle it's always in dark mode

### Expected behavior

It should be in light mode when the system theme is light

### Content Location

N/A

### Affected platform

Desktop app

### Operating system

Linux

### Additional information

Theme changes dynamically when system theme changes, it just does not work on startup

**Comment by miguellords** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by kjarosh** [comment]
That was regressed by https://github.com/ruffle-rs/ruffle/commit/490c02bb58d2c8ebc11233dbf9d6dacfd8f025cc in https://github.com/ruffle-rs/ruffle/pull/17401

CC @torokati44

**Comment by torokati44** [comment]
Yeah, that PR was my immediate suspect... :/

**Comment by kjarosh** [comment]
More info: it also does not work when the theme is set to light in the preferences. When debugging I can see that the proper theme is detected, it just seems that setting the theme on start in egui does nothing.
