### ISSUE TITLE
Pretentious Game 4: Arrow keys dont work

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#17995]
### Describe the bug

From others testing, arrow keys in game don't work.

`ReferenceError: Error # 1069: Property setRequestedUpdateInterval not found on flash.sensors.Accelerometer and there is no default value.`

### Expected behavior

Game should work

### Content Location

https://www.newgrounds.com/portal/view/634588?emulate=flash

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 128

**Comment by evilpie** [comment]
I almost suspect the author of this SWF somehow used this API accidentally, because the rest of the calling class does something with velocity and acceleration of robots?
