### ISSUE TITLE
The deal of the gods: Preloader issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#17992]
### Describe the bug

Game gets stuck on 100% on the preloader

### Expected behavior

Game should work 

### Content Location

https://www.newgrounds.com/portal/view/635604?emulate=flash

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 128

**Comment by Lord-McSweeney** [comment]
This is broken because the Spil API is down; the Flashpoint version (9o3o: https://ooooooooo.ooo/static/?f1b86d3d-c2e6-24c6-541d-36b1b72be25a) works fine.
