### ISSUE TITLE
Cego-online

### ISSUE THREAD

**Issue by sailerco** [ruffle-rs/ruffle#1800]
When I try to run this application ([https://www.cego-online.de/cego-spielen.html](https://www.cego-online.de/cego-spielen.html)) an Error pops up.
Could it be that not every website will be compatible with ruffle?
# Error Info
Error: Error creating player

# Player Info
Allows script access: true
Player type: Object
SWF URL: tl_files/cegoclient/CegoLoader.swf
Param quality: high
Param allowScriptAccess: always
Param wMode: window
Param swLiveConnect: true
Param flashVars: resourceRoot=https%3A%2F%2Fwww.cego-online.de%2Fcms%2Ftl_files%2Fcegoclient%2F&hash=&cmsHost=https%3A%2F%2Fwww.cego-online.de
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.cego-online.de/cego-spielen.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-01
Channel: nightly
Built: 2020-12-01T00:32:23.173Z
Commit: d06bbf23ce477d24f2e3758204d05f35e560601c

**Comment by Toad06** [comment]
It seems like the file at https://www.cego-online.de/system/scripts/e53a815ab435.js overwrites some built-in JS methods (eg. `Function.prototype.bind`). This may cause the issue here.
