### ISSUE TITLE
Ruffle Error on https://freeinvaders.org/

### ISSUE THREAD

**Issue by 4517794873** [ruffle-rs/ruffle#18017]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeinvaders.org/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by 4517794873** [comment]
This page wasn't working and I was trying to play space invaders in my chromebok

**Comment by 4517794873** [comment]
I was trying to play space invaders in this Chromebook but this page wasn't working for some error that happened

**Comment by 4517794873** [comment]
And the HTTP status code wasn't OK

**Comment by danielhjacobs** [comment]
This website uses a version of ruffle from 2020, thats 4 years out of date! This is an issue with their website and not with Ruffle. Please report this to them.

Their email is hello@freevideogames.org
