### ISSUE TITLE
[Web] Missing £ from UK keyboards

### ISSUE THREAD

**Issue by x3fold** [ruffle-rs/ruffle#1802]
When typing into an input all seem to be fine but the £ symbol (shift+3)

With shift held and the numbers 123456 typed you should get !"£$%^
but instead, you get !" $%^

just a space where the £ should be

**Comment by x3fold** [comment]
Looked into a bit further

The flash character code for £ is 163 
String.fromCharCode(163) 

I think it's just ruffle isn't looking that far up the code list... I may be wrong tho (I have been many times before)

**Comment by JMcKiern** [comment]
After looking into this issue for a while, I think I have found two causes.

First, Rust uses UTF-8 whereas ActionScript uses Extended Ascii. In Rust, a `£` is `[194, 163]` but in ActionScript it just has an Ascii code of `163`. This causes the check of `key.len() == 1` on line 314 below to fail. To solve this, `key.len() == 1` should be replaced with `key.chars().count() == 1`.

https://github.com/ruffle-rs/ruffle/blob/16b9c77d0232f9dcf80ca0727343eff8f2ffb2c4/web/src/input.rs#L314

The second issue is that the dummy device font of Noto Sans doesn't include a `£` glyph. As a result, the Font::get_glyph_for_char function fails to find a glyph for `£` and therefore `£` cannot be rendered in an EditText object.

https://github.com/ruffle-rs/ruffle/blob/764b76389c6546eafe634f578f5cbedf2b003b17/core/src/font.rs#L166

Text objects can still render `£` glyphs and I'm still not sure how

**Comment by Herschel** [comment]
Thanks for thoroughly looking into the issue, @JMcKiern! Fixed the multibyte input in #1860.

Our limited device font rendering is unfortunately a known issue that will take some effort to solve. Flash will automatically embed glyphs for normal text objects, which is why you may see £ rendered in that case. Dynamic text fields without the font embedded will use the OS to render on the other hand, and we currently fake this (#1862).

As a stopgap, I will probably more Latin characters and symbols to our embedded device font.

**Comment by JMcKiern** [comment]
Sweet. 

You're correct on the embedded glyphs. The SWF I was using did indeed embed £.

**Comment by x3fold** [comment]
One dirty way of temporarily fixing this is that I've created a custom font and changed the # key [35] to having the £ assigned to it
not pretty at all but it works for the time being

**Comment by x3fold** [comment]
After reading over @JMcKiern comments again I've had a dig around in the code and realize (as was stated) rust uses [194, 163] for the £ sign.

If you embed the font and increase the range of the text input characters from 126 to 194 then the £ sign does work.
https://github.com/ruffle-rs/ruffle/blob/70e7894a14b5271e1a836e6840c2f346e538621e/core/src/display_object/edit_text.rs#L1051

However, while this works it creates further issues if you continue to type into the input field.

An example can be found here [http://www.mathsworkout.co.uk/issues/test.zip](url)

After a £ has been added to the input field, on the next keypress all the text disappears. On pressing the backspace key the text will return, but with two copies of whatever key was press (proceeding the £). If you then press the delete key those two chacters are duplicated and if you keeping doing it enough times ruffle panics

`Error message: panicked at 'byte index 1 is not a char boundary; it is inside '£' (bytes 0..2) of `£1111111111111111`', core\src\font.rs:334:39`

**Comment by JMcKiern** [comment]
> `byte index 1 is not a char boundary; it is inside '£' (bytes 0..2)`

Looks like Ruffle is expecting a single byte char but is getting a multibyte char. My guess is that there's some assumption that a char is supposed to be a single byte which is causing the errors.

Interestingly, for input (not when typing in a text field), Flash uses a some form of Extended ASCII. This is supported by the fact that there is a [`Key.getAscii()`](https://open-flash.github.io/mirrors/as2-language-reference/Key.html#getAscii()) function to get the ascii code of the most recent keypress.

# Extended ASCII key press

![image](https://user-images.githubusercontent.com/9341692/101687404-5871ef80-3a62-11eb-9d4e-d9e95c924b71.png)

The relevant AS2 code is `result_txt.text = String.fromCharCode(Key.getAscii()) + ", ascii: " + Key.getAscii().toString() + ", code: " + Key.getCode().toString();` Note, these are all run in Flash not Ruffle.

# € key press

![image](https://user-images.githubusercontent.com/9341692/101689036-c91a0b80-3a64-11eb-93e4-49dfaf3d74e8.png)

I think it's interesting to note that the char code of `8364` for `€` (confirmed by `"€".charCodeAt(0)`) is different from it's ASCII value as determined from Key.getAscii() of `128`

# Key presses outside of the Extended ASCII range.

If I press `A` while using an Arabic keyboard it generates `ش` (UTF+0634) character. In Flash, the actual character is replaced with `?`.
. 

![image](https://user-images.githubusercontent.com/9341692/101691734-0aabb600-3a67-11eb-8d27-7b3ea0cdc8b0.png)

# Text field input with various characters

I embedded all _typewriter glyphs in your `pound.swf` and it shows that text fields can various UTF-8(?) characters:

![image](https://user-images.githubusercontent.com/9341692/101692648-6d518180-3a68-11eb-9af5-284b7e7eda72.png)

**Comment by JMcKiern** [comment]
Anyway, the takeaways are:
- `KeyCode` needs to extend up to 255
- Some characters will need to be converted from UTF-8 representation in Rust to their ASCII keycode in Flash (eg. `£` and `€`)
- TextFields need to be able to receive (at least) UTF-8 input

**Comment by Herschel** [comment]
This should be working correctly now when the font is embedded with the pound glyph. Device font support is pending on #1862.
