### ISSUE TITLE
There will be a large offset when you click on the Sprite

### ISSUE THREAD

**Issue by aschord** [ruffle-rs/ruffle#18038]
### Describe the bug

Because SpriteSheet technology is used in the game as a display, it is normal to click the flag when playing demo game.swf with FlashPlayer, but it will be greatly offset when playing the flag with RufflePlayer (presumably because the Bitmap not displayed is also considered as the click range).  The click range is not accurate

### Expected behavior

I want it to be as accurate when I click on the flag as it is in FlashPlayer

### Content Location

**BUG example file source code :** [demo game.swf](https://github.com/aschord/RuffleTest/blob/master/demo%20game.swf)   AND  [demo game src.7z](https://github.com/aschord/RuffleTest/blob/master/demo%20game%20src.7z)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome 93

**Comment by kjarosh** [comment]
Could you describe in detail how to reproduce the problem? It's not obvious what "the flag" means. A screenshot with a specific point where to click would be also appreciated.

**Comment by aschord** [comment]
> Could you describe in detail how to reproduce the problem? It's not obvious what "the flag" means. A screenshot with a specific point where to click would be also appreciated.

When starting the game, the flag is not accurate in RufflePlay, because the flag is a Bitmap object, the part that can not be seen when clicked will also have click events, resulting in a lot of click accuracy offset! You can test with RuffePlayer by clicking on the flag and see that it doesn't turn over the flag where the mouse is.

**Comment by aschord** [comment]
When will this problem be solved? thank you

**Comment by kjarosh** [comment]
@torokati44 FYI after clicking a flag in this SWF, the following debug assert fails (https://github.com/ruffle-rs/ruffle/pull/14352):

https://github.com/ruffle-rs/ruffle/blob/7ed23b04b9bae0b39ee2754f1e8b99e3d6790863/core/src/timer.rs#L179-L182
