### ISSUE TITLE
git having a hard time with always changing .wasm

### ISSUE THREAD

**Issue by erikyuzwa** [ruffle-rs/ruffle#1804]
This might likely be more of a deployment issue vs. a Ruffle issue, but I'm trying to get this amazing piece of tech within my environment. The web server is updated to support `.wasm` files, however I'm noticing that whenever I switch between branches, the `.wasm` file is being updated...which messes up my deployment pipeline..

I've tried adding it to the `.gitignore` but obviously it's required by Ruffle. How / Why is it being constantly updated?

**Comment by Herschel** [comment]
Sorry, I'm unclear about the specific problem you are having; is the question why the filename of the core.ruffle.wasm file changes?

**Comment by erikyuzwa** [comment]
my apologies for being so unclear. I realize that the generated files change between builds of Ruffle, but I'm noticing that when I bring the self-hosted files into my project, then change git branches for other features, the `.wasm` file is always being updated / touched which causes deployment pipeline struggles. Are there plans to get the Ruffle self-hosted put on a CDN?

**Comment by Herschel** [comment]
I am not sure why changing git branches would touch the wasm file; it's a static file and should be able to be stored in the repo like any other (for example, our demo page: https://github.com/ruffle-rs/demo). Do you perhaps have different or no versions of the file stored on the other branches? Then naturally switched branches would remove or modify the file.

No plans to put Ruffle self-hosted on a CDN currently.

**Comment by erikyuzwa** [comment]
thanks @Herschel - might be a windows environment behaviour? 🤷 - thanks for the help!
