### ISSUE TITLE
Error message: panicked at 'not implemented', core/src/display_object/movie_clip.rs:265:41

### ISSUE THREAD

**Issue by fenxlol** [ruffle-rs/ruffle#1805]
# Error Info
Error name: Error
Error message: panicked at 'not implemented', core/src/display_object/movie_clip.rs:265:41
Error stack:
```
Error: panicked at 'not implemented', core/src/display_object/movie_clip.rs:265:41
    at Object.D (https://ruffle.rs/demo/662.index.js:1:20360)
    at __wbg_new_df6e6ab7a65c4c4d (https://ruffle.rs/demo/index.js:1:36567)
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[1054]:0x2057b3
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[1375]:0x243c18
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[3691]:0x2f77c8
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[2920]:0x2da271
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[4054]:0x2fcfec
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[4000]:0x2fc69c
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[4051]:0x2fcf71
    at https://ruffle.rs/demo/3056e7c7d29075eca876.module.wasm:wasm-function[277]:0x35915
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.441 (Edition globalgames-sd)
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-01
Channel: nightly
Built: 2020-12-01T00:32:23.173Z
Commit: d06bbf23ce477d24f2e3758204d05f35e560601c

Swf https://github.com/JasonWibbo/HabboSwfOpenSource/blob/master/PRODUCTION-202010201406-28704071.swf

**Comment by Herschel** [comment]
Thanks for the report!

DefineFont4 not supported; we need to at least handle this gracefully and not panic for now.

**Comment by Herschel** [comment]
Should no longer panic, but won't otherwise run currently pending AVM2 (#1368) and TLF/FTE text (DefineFont4). Thank you!
