### ISSUE TITLE
Game "Heli Attack 3" stuck

### ISSUE THREAD

**Issue by evandrix** [ruffle-rs/ruffle#1809]
Expected:
![image](https://user-images.githubusercontent.com/169669/100790693-1ee22880-3453-11eb-906d-9e0366095f2a.png)

Actual:
![image](https://user-images.githubusercontent.com/169669/100790645-0a9e2b80-3453-11eb-89c7-06fc1a85fbc1.png)

Attached:
[ha3miniclip.swf.zip](https://github.com/ruffle-rs/ruffle/files/5625145/ha3miniclip.swf.zip)

**Comment by JMcKiern** [comment]
It's able to get to the menu with both the extension and on desktop. Seems to only be an issue with demo although I haven't tested selfhosted

**Comment by dginovker** [comment]
Works on 0.1.0.544

**Comment by n0samu** [comment]
The game has a sitelock and only works if run from miniclip.com or a file:/// URL; the demo page is neither of those. It doesn't work from `localhost://` URLs either, so I think it can only work in the desktop app. It would need something like #859 to be implemented, which seems not to be planned.
