### ISSUE TITLE
WebAssembly.instantiateStreaming(): invalid function length (0)

### ISSUE THREAD

**Issue by erikyuzwa** [ruffle-rs/ruffle#1810]
Apologies in advance. I'm not sure by this error message if it's a Ruffle issue or if my environment is setup correctly for webassembly.

I do see the `(i)frame already has RufflePlayer` console message.

```
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): invalid function length (0) @+2416226
Error stack:

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Win32
# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-01
Channel: nightly
Built: 2020-12-01T00:32:23.173Z
Commit: d06bbf23ce477d24f2e3758204d05f35e560601c
```

**Comment by erikyuzwa** [comment]
If there's documentation on how to troubleshoot errors like this vs. bugging the Ruffle devs for everything, then I'm all for trying to track this down myself.

**Comment by Herschel** [comment]
Could you look in the Chrome network inspector (F12 -> Network) and reload the page, and see if the wasm files are  being requested and found? It's possible that it's hitting a 404 and/or the MIME type is not being served correctly.

**Comment by erikyuzwa** [comment]
Thanks @Herschel :bow:

Yes, I've reloaded with the network tab on and can see that `ruffle.js`, `core.ruffle.js` and the `.wasm` are being found with 200's.

From the `polyfills.js` I am seeing a lot of `polyfills.js:167 error loading ruffle player into frame: Blocked a frame with origin "<my.domain.org>" from accessing a cross-origin frame.` 

I do have all the content hosted on the same domain, so I'm not sure if this is a red herring or a valuable clue...

**Comment by n0samu** [comment]
Ruffle falls back to `WebAssembly.instantiate()` now so I don't think this issue can occur anymore. Please leave a comment if this is still occurring for you and I can reopen the issue.
