### ISSUE TITLE
Unnecessary permission dialog when opening an SWF file

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#18142]
### Describe the bug

To reproduce:
1. Run the Ruffle desktop app
2. Click File => Open and choose any SWF file

Ruffle will ask for permission to access the file that you just chose to open. This is annoying and unnecessary.
![image](https://github.com/user-attachments/assets/5c500d75-6872-42ae-9b46-1a730457936d)

### Expected behavior

Ruffle should only ask for permission before accessing other files that the user didn't explicitly choose to open.

### Content Location

N/A

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Related to #17875. According to @Lord-McSweeney, this issue is *not* reproducible on Linux. So it may be a separate issue from #18141.

**Comment by kjarosh** [comment]
This bug has been fixed and the dialog should not show for the SWF file you're opening. For other files it's not possible yet to allow access and remember it for more than the session.

**Comment by kjarosh** [comment]
You can file an issue about that, I think eventually we want it done, but it requires also a UI that lists all persisted permissions and allows removing them.

Currently the dialog should be shown only when the SWF tries to access a weird location.

**Comment by hamzaelbarmaki1994** [comment]
@kjarosh  done : https://github.com/ruffle-rs/ruffle/issues/19790
