### ISSUE TITLE
Once again: avm1: .swf file does not save to .sol file........

### ISSUE THREAD

**Issue by Ghost-Program** [ruffle-rs/ruffle#18188]
### Describe the bug

https://github.com/ruffle-rs/ruffle/issues/16115

### Expected behavior

https://github.com/ruffle-rs/ruffle/issues/16115

### Content Location

https://github.com/ruffle-rs/ruffle/issues/16115

### Affected platform

Self-hosted version

### Operating system

windows 10 or above

### Browser

latest chrome

**Comment by adrian17** [comment]
Duplicate of https://github.com/ruffle-rs/ruffle/issues/16115 .
