### ISSUE TITLE
I'm trying to build ruffle on Glitch.com, however I keep getting this error

### ISSUE THREAD

**Issue by CBGamesdev** [ruffle-rs/ruffle#1819]
So, I own a Google Site for flash games and I'm building ruffle on glitch.com using the self hosted nightly build. However I keep getting this error:

**# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://chilibloxgames.glitch.me/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13421.102.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.199 Safari/537.36
OS: Linux x86_64

# Ruffle Info

Any help on this? I can walk you through on what I did if needed.
Version: 0.1.0
Name: nightly 2020-11-28
Channel: nightly
Built: 2020-11-28T00:31:04.155Z
Commit: 602a343995df0dea6fa73121b90f5f68a0804e77**

**Comment by Herschel** [comment]
Unfortunately, security restrictions of modern web browsers prevent Ruffle from loading data from a different domain by default. These restrictions did not exist in the original Flash Player, but Ruffle is at the mercy of the browser itself.

You must either a) store the SWF on your own domain, or b) the domain you are loading from must respond with proper CORS headers to allow the request.

See also #21, #1500.

**Comment by Herschel** [comment]
Closing as issue on the website's side; please let me know if more info is necessary. Thank you!
