### ISSUE TITLE
Properties should be case insensitive on SWF v6 and below

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#182]
For SWF files version 6 and below, all property access is case insensitive. For example, `clip.foo` and `cLiP.FoO` will result in the same value.

Related to #153, we'll probably implement our own `PropertyMap` type that wraps around some underlying hash map and handles the case insensitivity and version dependent behavior.

**Comment by RePod** [comment]
Are methods included?

Instances of `Object method gotoandplay is not callable` and other improperly cased variants appear in the console on web, though desktop acts similarly.

Properly camel casing with ffdec fixes the issue.

**Comment by Herschel** [comment]
Yep, methods are included.

**Comment by Herschel** [comment]
Fixed by #182. There is some potential for a better underlying data structure to make this more performant (interning strings and/or pre-computing hashes in our string representation for example).
