### ISSUE TITLE
avm1: .swf file does not save to .sol file on ruffle self-hosted on web server

### ISSUE THREAD

**Issue by Ghost-Program** [ruffle-rs/ruffle#18204]
### Describe the bug

https://github.com/ruffle-rs/ruffle/issues/16115

### Expected behavior

https://github.com/ruffle-rs/ruffle/issues/16115

### Content Location

https://github.com/ruffle-rs/ruffle/issues/16115

### Affected platform

Self-hosted version

### Operating system

Windows 10 and up. All the way up!

### Browser

Latest Chrome browser and any other latest browser known to man.

**Comment by n0samu** [comment]
Stop opening duplicate issues. If you continue with this behavior we may block you from
the repo. Wait for us to respond to your comments on the original issue.
