### ISSUE TITLE
Crash on tanki2.swf

### ISSUE THREAD

**Issue by Pyogenics** [ruffle-rs/ruffle#18202]
### Describe what you were doing

The crash happened a few seconds after launching the SWF, the crash happens on the loading screen of the application. The SWF and its resources can be found [here](https://github.com/MapMakersAndProgrammers/alternativa-demos/tree/master/alternativa/Tanki2.0/arena/v2). The SWF uses the opensource Alternativa3D engine available [here](https://github.com/AlternativaPlatform/Alternativa3D), some other demos based on this engine can display some graphics under ruffle.

### What does the crash message say?

panicked at /home/corey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In RenderPass::end
    In a pass parameter
      Multiview layer count must match

### Ruffle Version

0.1.0-nightly (0729e796597e05e43d29601549a483f7709a1cc9 2024-09-18)

### Affected platform

Desktop app

### Operating system

Arch Linux Rolling Release [64-bit]

### Additional information

Filename: tanki2.swf

### AVM2 Callstack
```
	at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
	at _-Jt::_-Hj$/_-4R()
	at _-Jt::_-Hj$/http://alternativaplatform.com/en/alternativa3d::_-HW()
	at _-Jt::_-Hj$/http://alternativaplatform.com/en/alternativa3d::_-HW()
	at _-Jt::_-Hj/_-FT()
	at _-Jt::_-Hj/update()
	at _-Jt::_-1p/update()
	at TankiOnline2Demo/_-D8()
```

### Render Info
Renderer: wgpu
Adapter Backend: Vulkan
Adapter Name: "AMD Radeon Vega 8 Graphics (RADV RAVEN)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: "radv"
Adapter Driver Info: "Mesa 24.2.4-arch1.1"
Enabled features: Features(TEXTURE_COMPRESSION_BC | FLOAT32_FILTERABLE | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
Available features: Features(DEPTH_CLIP_CONTROL | DEPTH32FLOAT_STENCIL8 | TEXTURE_COMPRESSION_ETC2 | TIMESTAMP_QUERY | INDIRECT_FIRST_INSTANCE | SHADER_F16 | RG11B10UFLOAT_RENDERABLE | BGRA8UNORM_STORAGE | TEXTURE_FORMAT_16BIT_NORM | PIPELINE_STATISTICS_QUERY | TIMESTAMP_QUERY_INSIDE_ENCODERS | TIMESTAMP_QUERY_INSIDE_PASSES | MAPPABLE_PRIMARY_BUFFERS | TEXTURE_BINDING_ARRAY | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING | UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING | PARTIALLY_BOUND_BINDING_ARRAY | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | PUSH_CONSTANTS | ADDRESS_MODE_CLAMP_TO_ZERO | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_TEXTURE | SPIRV_SHADER_PASSTHROUGH | MULTIVIEW | TEXTURE_FORMAT_NV12 | SHADER_F64 | SHADER_I16 | SHADER_PRIMITIVE_INDEX | DUAL_SOURCE_BLENDING | SHADER_INT64 | SUBGROUP | SUBGROUP_VERTEX | SUBGROUP_BARRIER | PIPELINE_CACHE | SHADER_INT64_ATOMIC_MIN_MAX | SHADER_INT64_ATOMIC_ALL_OPS)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 2147483648, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 32, max_inter_stage_shader_components: 128, max_color_attachments: 8, max_color_attachment_bytes_per_sample: 32, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, min_subgroup_size: 0, max_subgroup_size: 0, max_push_constant_size: 0, max_non_sampler_bindings: 1000000 }
Surface quality: low
Surface samples: 1
Surface size: (800, 600, 1)

**Comment by adrian17** [comment]
While closed, the game unfortunately still doesn't work - it's super slow, and the screen is mostly black.
I'm pretty sure this is caused by missing support for compressed textures.
