### ISSUE TITLE
"Fingertips" slowdowns

### ISSUE THREAD

**Issue by digamejh** [ruffle-rs/ruffle#1821]
The animation slows to a crawl during the "Who's that standing at the window" sequence.

[fingertips.zip](https://github.com/ruffle-rs/ruffle/files/5632578/fingertips.zip)

**Comment by n0samu** [comment]
@digamejh can you check if this still occurs for you? I'm not noticing any issue with that sequence.

**Comment by digamejh** [comment]
Yep, thank you!
