### ISSUE TITLE
desktop app bug

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#18236]
### Describe what you were doing

I opened an swf that requests connection to localhost
then i drag drop another swf file to app(seems that reloading the swf also triggers this)
then i clicked cancel of the request dialog

### What does the crash message say?

panicked at D:\a\ruffle\ruffle\frontend-utils\src\backends\navigator.rs:345:30:
working channel send: Closed(..)

### Ruffle Version

0.1.0-nightly (66a909d539470e7586e1f5ca5ef22e441cead9ad 2024-10-09)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Home China) [64-bit]

### Additional information

if click allow the message is
panicked at D:\a\ruffle\ruffle\frontend-utils\src\backends\navigator.rs:378:26:
working channel send: Closed(..)

**Comment by n0samu** [comment]
Can reproduce this. For example, try loading [PaintWorld](http://i.notdoppler.com/files/paintworld.swf) and then loading another SWF file after it.
