### ISSUE TITLE
Issue running typing-maniac.swf

### ISSUE THREAD

**Issue by jrversteegh** [ruffle-rs/ruffle#18234]
### Describe what you were doing

Trying to run typing maniac (old facebook game) and got error.[type.zip](https://github.com/user-attachments/files/17333995/type.zip)

### What does the crash message say?

panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-22.1.0/src/device/queue.rs:299:22:
called `Result::unwrap()` on an `Err` value: OutOfMemory

### Ruffle Version

0.1.0-nightly (66a909d539470e7586e1f5ca5ef22e441cead9ad 2024-10-09)

### Affected platform

Desktop app

### Operating system

Linux Mint 22.0.0 (wilma) [64-bit]

**Comment by jrversteegh** [comment]
This error occurs even when running without parameter so has nothing to do with the flash file, but with amdgpu interaction it looks like:

2024-10-10T20:42:42.051488Z  INFO ruffle_desktop::gui::controller: Using preferred backend Vulkan
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 0 bytes
radv/amdgpu:    alignment : 0 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 0 bytes
radv/amdgpu:    alignment : 0 bytes
radv/amdgpu:    domains   : 4
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-22.1.0/src/device/queue.rs:299:22:
called `Result::unwrap()` on an `Err` value: OutOfMemory
stack backtrace:
   0:     0x587f06c79205 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
   1:     0x587f06ca755b - core::fmt::write::h4b5a1270214bc4a7
   2:     0x587f06c747df - std::io::Write::write_fmt::hd04af345a50c312d
   3:     0x587f06c7a741 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
   4:     0x587f06c7a41c - std::panicking::default_hook::h3cacb9c27561ad33
   5:     0x587f05866be1 - ruffle_desktop::init::{{closure}}::h48897d5c450ac19e
   6:     0x587f06c7afdf - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   7:     0x587f06c7ac07 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   8:     0x587f06c796c9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   9:     0x587f06c7a894 - rust_begin_unwind
  10:     0x587f056fff03 - core::panicking::panic_fmt::h3d8fc78294164da7
  11:     0x587f057003d6 - core::result::unwrap_failed::hfa79a499befff387
  12:     0x587f0690d70b - wgpu_core::device::resource::Device<A>::new::he598b2b22a773260
  13:     0x587f0681e307 - wgpu_core::instance::Adapter<A>::create_device_and_queue::he1ae56793b229920
  14:     0x587f068dffc2 - wgpu_core::instance::<impl wgpu_core::global::Global>::adapter_request_device::h279e13ace7e32707
Aborted (core dumped)

**Comment by adrian17** [comment]
FYI, I ran your SWF and I think it won't work anyway, as it's trying to load some SWF from an URL that no longer works?

That said, it's still a weird error you got.
Can you send us your `vulkaninfo --summary`? I'll probably pass them to wgpu library folks as it feels like an issue on their side, this happens on early graphics initialization on their side.

**Comment by jrversteegh** [comment]
`vulkaninfo --summary` produces the same error, so probably related to my graphics setup. Closing.

```
$ vulkaninfo --summary
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so. Skipping this driver.
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 0 bytes
radv/amdgpu:    alignment : 0 bytes
radv/amdgpu:    domains   : 4
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.275


Instance Extensions: count = 23
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 7
--------------------------
VK_LAYER_INTEL_nullhw             INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select       Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay             Mesa Overlay layer           1.3.211  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
	apiVersion         = 1.3.274
	driverVersion      = 24.0.9
	vendorID           = 0x8086
	deviceID           = 0xa780
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Intel(R) Graphics (RPL-S)
	driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName         = Intel open-source Mesa driver
	driverInfo         = Mesa 24.0.9-0ubuntu0.2
	conformanceVersion = 1.3.6.0
	deviceUUID         = 868080a7-0400-0000-0002-000000000000
	driverUUID         = ce784419-227b-749c-8c4d-49ad2a77726e
GPU1:
	apiVersion         = 1.3.274
	driverVersion      = 24.0.9
	vendorID           = 0x1002
	deviceID           = 0x738c
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Instinct MI100 (RADV MI100)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 24.0.9-0ubuntu0.2
	conformanceVersion = 1.2.7.1
	deviceUUID         = 00000000-0300-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU2:
	apiVersion         = 1.3.274
	driverVersion      = 24.0.9
	vendorID           = 0x1002
	deviceID           = 0x66af
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Radeon VII (RADV VEGA20)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 24.0.9-0ubuntu0.2
	conformanceVersion = 1.2.7.1
	deviceUUID         = 00000000-0600-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU3:
	apiVersion         = 1.3.274
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 17.0.6, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 24.0.9-0ubuntu0.2 (LLVM 17.0.6)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3234-2e30-2e39-2d3075627500
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000

```
