### ISSUE TITLE
SWF library loading?

### ISSUE THREAD

**Issue by TooManyFactoryResets** [ruffle-rs/ruffle#18240]
**Web build feature:  SWF library loading?**
Some Flash apps/games compile to multiple SWF files and I'm not sure if this is built in already but, it'd be nice if a feature was added that could load the libraries or external files on a server or host.

**Comment by adrian17** [comment]
We already support multi-SWF games. As long as they worked on Flash Player, they should also work with Ruffle. (and if they don't, the reason is probably not related to them being multi-swf)
