### ISSUE TITLE
Extension Prevents chewy.com from loading

### ISSUE THREAD

**Issue by bonn2** [ruffle-rs/ruffle#18265]
### Describe the bug

When the extension is enabled it causes https://chewy.com/ to just load a blank page, only if the browser has no cache of the website. I am not sure why this is happening as Chewy does not have any Flash on it (that I know of) because it is a modern pet supply website.
## Steps to reproduce
1. Have Ruffle installed and enabled on Firefox.
2. Clear all cookies / cache / history of the website https://chewy.com/ (I used the forget this site feature of Firefox to do this). 
3. Attempt to load https://chewy.com/ and a blank white page will appear instead of the normal website.

### Expected behavior

I expect Ruffle to do nothing, as this website should not contain any flash anything. Another option would be the ability to blacklist a domain so that Ruffle won't try to do anything.

### Content Location

As far as I know there is no SWF content, that is what makes this so confusing.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Firefox 132.0b6 (64-bit)

### Additional information

As far as I can tell this is the only website this happens on and it really baffles me as to why this would happen since again, Chewy shouldn't contain Flash.

**Comment by n0samu** [comment]
Looks like they are using Kasada's bot detection script (KPSDK). You can learn more about it here: https://www.nullpt.rs/devirtualizing-nike-vm-1
Really this kind of stuff is going to be a game of whack-a-mole until we stop modifying the page DOM unnecessarily. With Manifest V3 we should be able to avoid DOM manipulation except when we actually polyfill Flash elements. But that'll take a lot of work to accomplish I guess.
