### ISSUE TITLE
web: Handles not working to drag element

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#1828]
In flash you can drag the coordinates in the right side 3d-plot by using the small yellow handles.
In ruffle you can't.

See http://www.webgeo.de/k_024_en/#5
(on http://www.webgeo.de you can switch between using ruffle or using flash)

Version: ruffle_web_2020-12-03
![k_024_en_5_flash](https://user-images.githubusercontent.com/1667683/101018649-1af5f980-356c-11eb-917f-173c60e909fd.png)
![k_024_en_5_ruffle](https://user-images.githubusercontent.com/1667683/101018682-234e3480-356c-11eb-814b-918e11075f55.png)
[k_024_05.zip](https://github.com/ruffle-rs/ruffle/files/5636056/k_024_05.zip)

**Comment by Herschel** [comment]
Fixed by #4584.
