### ISSUE TITLE
[Linux] Audio stream cancelling

### ISSUE THREAD

**Issue by YukiXXL** [ruffle-rs/ruffle#18327]
### Describe the bug

https://github.com/user-attachments/assets/e1164f71-74ef-4cfb-a2ba-32bfbc22d73e

### Expected behavior

https://github.com/user-attachments/assets/15830c2f-8aed-432e-9e8e-d6c51e96eba8

### Content Location

https://cache.armorgames.com/files/games/hobo-7-heaven-14404.swf

### Affected platform

Desktop app

### Operating system

Linux Mint 22

### Additional information

Started happening at version "ruffle-nightly-2024_07_08".
Using "linux-x86_64.tar.gz".

**Comment by torokati44** [comment]
To reproduce, start a new game in easy mode, skip the intro, and use the combo "ASW".

The regressing commit is 1ffb9d2ab94b94e90011c76ffd9204e51eef46c2 (part of https://github.com/ruffle-rs/ruffle/pull/17016, by @Dinnerbone) , so I doubt it's specific to Linux.
