### ISSUE TITLE
Azalea's Dress Up Dolls

### ISSUE THREAD

**Issue by DBSeamz** [ruffle-rs/ruffle#1833]
Ruffle encountered a "major issue" when I tried to use it on the Azalea's Dolls Heroine Creator game.

**Comment by neonpixii** [comment]
i am getting a similar error for this website:
https://www.deviantart.com/generalzoi/art/Pony-Creator-Full-Version-254295904

```
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29
Error stack:
```

**Comment by n0samu** [comment]
Both of these problems seem to be fixed now. If it's still occurring, please leave a comment and I can reopen the issue.

Note that Pony Creator uses ActionScript 3, so although it no longer crashes, it is not working properly yet.
