### ISSUE TITLE
Text is not rendered on Android

### ISSUE THREAD

**Issue by georgsh** [ruffle-rs/ruffle#1834]
Desktop (ok):
![image](https://user-images.githubusercontent.com/75171112/101089588-6b01aa00-35c6-11eb-92e1-e97f0849f5ae.png)
Android (TOP: *no text*):
![image](https://user-images.githubusercontent.com/75171112/101089617-7523a880-35c6-11eb-8f64-a369a74b42b6.png)
Demo:
https://georgsh.github.io/swfdemo.html?game=yeti1

All `DefineEditText`s not rendering
![image](https://user-images.githubusercontent.com/75171112/101094813-09453e00-35ce-11eb-978d-70913b070b52.png)

But all `DefineText` objects displays ok

**Comment by Toad06** [comment]
Thank you for this bug report.

This is a known issue that affects certain mobile devices: #900
I invite you to add a comment there, so we'll make sure to test this game when a pull request is ready.

Thanks again.

**Comment by Txori** [comment]
I made a simple fla example. It was for a virtual joystick test, but we see clearly the android text problem on Android.
In my example, the dynamic text is inside a clip.
https://www.txori.com/stuff/ruffle/debug/

I have a Pixel 3A, Android 11, Chrome 87.0.4280.86
