### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by wolfe4656** [ruffle-rs/ruffle#1843]
Your bug reporting is worthless. The plugin crashes.

**Comment by rdrpenguin04** [comment]
Could you please give an example of something the plugin crashes on? Thanks!

**Comment by wolfe4656** [comment]
Hi thanks for the quick reply. What i have is a nvr online that i use to
check my cameras at home when away. It uses flash to display the cameras
online in chrome. When i have the plugin turned on and open my campera
program i get the error attached below. I have flash setup to run when
asked so i dont ask it to run. Any ideas?
Thank You
Dave....

**Comment by parkerlreed** [comment]
There is no attachment coming through on the GitHub issues page.

**Comment by wolfe4656** [comment]
Sorry about that, here it is, they are png files. I just pasted them to
Github.

**Comment by rdrpenguin04** [comment]
Where did you post them?

**Comment by wolfe4656** [comment]
https://github.com/ruffle-rs/ruffle/issues/1843

**Comment by wolfe4656** [comment]
I dont see them either and i also attached them to my email response.

**Comment by wolfe4656** [comment]
do i need to hit comment or close with comment

**Comment by wolfe4656** [comment]
i am attaching again. under preview.
<img width="988" alt="Ruffle error 2" src="https://user-images.githubusercontent.com/75267008/101202315-1ba79200-3637-11eb-883d-491cabc3e6f1.PNG">
<img width="1015" alt="Ruffle error" src="https://user-images.githubusercontent.com/75267008/101202440-40036e80-3637-11eb-8e67-a83da3e452a4.PNG">

**Comment by wolfe4656** [comment]
I will try again.
<img width="988" alt="Ruffle error 2" src="https://user-images.githubusercontent.com/75267008/101202814-c61fb500-3637-11eb-9f20-afe171b7827e.PNG">
<img width="1015" alt="Ruffle error" src="https://user-images.githubusercontent.com/75267008/101202850-d0da4a00-3637-11eb-9129-a22660d986da.PNG">

**Comment by rdrpenguin04** [comment]
Why did you close the report?

**Comment by wolfe4656** [comment]
in error

**Comment by wolfe4656** [comment]
hit the worng button.

**Comment by rdrpenguin04** [comment]
Anyways, the error looks like `GL_INVALID_VALUE`. I'll look at the code quick.

**Comment by wolfe4656** [comment]
Thanks

**Comment by rdrpenguin04** [comment]
@Herschel One of three things is happening here:
1. `self.msaa_sample_count` is higher than supported by some systems; this could be caught and fixed potentially.
2. `width` or `height` is greater than `gl.MAX_RENDERBUFFER_SIZE`; this can definitely be checked, but I don't know what the best thing to do if this isn't supported is.

**Comment by wolfe4656** [comment]
It is a online NVR camera system with 16 channels. That could be why.

**Comment by rdrpenguin04** [comment]
The camera shouldn't have anything to do with it.

**Comment by Herschel** [comment]
@rdrpenguin04 gl MAX_SAMPLES is already checked, and gl.drawingBufferWidth is used to ensure we don't make a renderbuffer bigger than what the browser gives us. Originally I had added a check for MAX_RENDERBUFFER_SIZE in #1787 but I took it out as it didn't specifically seem to help much. (The issue with most of these parameters is that they can line, or don't ereally give you enough info to know under which conditions things will fail).

@wolfe4656 What is the version number of the Ruffle build you are using? You should be able to paste the full text from the error dialog into this issue, which includes the version.

Also if your Flash requires support for video (cameras), it may not function in Ruffle because video is not supported yet. Thanks for the report!

**Comment by wolfe4656** [comment]
the plugin for chrome is Ruffle 0.1.0. That could be why too i thik the flash is required with the video. It will not allow me to copy the text from the error log.

**Comment by Herschel** [comment]
Specifically I'm looking for to build date for the Ruffle build (all of the info under Ruffle Info). Is it the latest nightly build?

**Comment by wolfe4656** [comment]
Where can i find the build info?
Version
0.1.0
Size
3.6 MB
ID
nbamcodkicaamabefdobidlhlhkjhcoc
Inspect views
No active views
Permissions
Site access
Allow this extension to read and change all your data on websites you visit:
On click
On specific sites
On all sites
Allow in incognito
Warning: Google Chrome cannot prevent extensions from recording your browsing history. To disable this extension in incognito mode, unselect this option.
Allow access to file URLs
Collect errors
Extension options
Source
Unpacked extension
Loaded from: E:\Downloads\Flashpoint Adobe flash repl\Flash repl for browser ruffle\ruffle_nightly_2020_11_20_extension

**Comment by rdrpenguin04** [comment]
`ruffle_nightly_2020_11_20_extension` <-- And there we have it!

**Comment by parkerlreed** [comment]
Update. There's a 12/04 nightly

**Comment by wolfe4656** [comment]
Better i get a black screen now with 12/04.
This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended.

**Comment by Herschel** [comment]
ActionScript 3 support is still a work in progress, sorry for the trouble. Closing in favor of #1843.

**Comment by parkerlreed** [comment]
Closing in favor of this same issue? :P

**Comment by Herschel** [comment]
Oops :-) Closing in favor of #1368
