### ISSUE TITLE
Super smash flash 2 fails to boot

### ISSUE THREAD

**Issue by eltomas2003** [ruffle-rs/ruffle#1845]
tried standalone package, doesn't work.

**Comment by relrelb** [comment]
AS3 is still a work in progress, please refer to #1368.

**Comment by waspennator** [comment]
https://www.supersmashflash.com/play/ssf2/
Tested it out with the latest nightly on web, doesn't seem to get past the preloader screen with the burning 2 symbol. I do see a percentage sign, but no numbers appear beside it and I see this when I go into the console log.

"Got RustError("Cannot set undefined property ::fullScreenSourceRect on Some(flash.display::Stage)") when constructing AVM2 side of movie clip of type com.mcleodgaming.ssf2::Main"

**Comment by Lord-McSweeney** [comment]
With #9265, this now fails with `ERROR ruffle_core::timer: Unhandled AVM2 error in timer callback: RustError("EOFError: Reached EOF")`.

**Comment by Dinnerbone** [comment]
> With #9265, this now fails with `ERROR ruffle_core::timer: Unhandled AVM2 error in timer callback: RustError("EOFError: Reached EOF")`.

This might be fixed with the most recent changes, but I can't test the game right now to confirm

**Comment by Lord-McSweeney** [comment]
The SSF files are missing, which makes the game unplayable. They have not been archived on the Wayback Machine, but might be available on Flashpoint.

**Comment by Lord-McSweeney** [comment]
This is now playable! Though there are performance problems and the max execution timeout needs to be bumped for initialization to finish.
