### ISSUE TITLE
Incorrect hit detection in Bowman

### ISSUE THREAD

**Issue by XXLuigiMario** [ruffle-rs/ruffle#185]
Bowman appears to be detecting collisions at an offset of where they should actually occur.
This can be seen in the Practice mode of the game, where you have to aim at a target. If you hit the target, the arrow goes past it but if you miss, you may end up hitting an invisible object in mid air.

![Floating arrow](https://user-images.githubusercontent.com/7153662/71136634-bc722700-2205-11ea-8023-c7ad99b0d189.png)

**Video**: https://streamable.com/uq3nv
**Game file**: https://cache.armorgames.com/files/games/bowman-133.swf

**Comment by Herschel** [comment]
@XXLuigiMario Could you verify that this specific issue is fixed? Thanks!

**Comment by XXLuigiMario** [comment]
Works perfectly 👍
