### ISSUE TITLE
ExternalInterface.call returns undefined when sending an object.

### ISSUE THREAD

**Issue by VisheshSood** [ruffle-rs/ruffle#18543]
### Describe the bug

If you call ExternalInterface.call and pass an object like below:

```
ExternalInterface.call("emit",{
  "id":"sw",
  "f":"s",
  "d": "data"
});
```

It returns undefined instead of the object itself.

### Expected behavior

It should return { id: 'sw', f: 's', d: 'data' } but it returns undefined.

### Content Location

I have no idea about this, its just something I had in my flash file as attached.[game.swf.zip](https://github.com/user-attachments/files/17689053/game.swf.zip)

### Affected platform

Self-hosted version

### Operating system

OSX

### Browser

Chrome Version 130.0.6723.117 (Official Build) (arm64)

**Comment by Dinnerbone** [comment]
What's the source code to the `emit` js callback? Is it just returning the first parameter?

**Comment by Toad06** [comment]
https://github.com/ruffle-rs/ruffle/blob/5954c1b0f99616e551ff7e3c78808d3168b611a0/core/src/external.rs#L214

I suppose this should be the reason?

**Comment by Dinnerbone** [comment]
That certainly looks relevant! :D

**Comment by VisheshSood** [comment]
> What's the source code to the `emit` js callback? Is it just returning the first parameter?

It calls my server and passes the parameters for me to then use in my website. For example id - sw is for me to know the game is swapples (sw). I have a workaround that I just pass everything as a string and parse the string in javascript, but the issue comes when there are certain things I want to pass as a map (key value pairs) from the flash game, but I cant do that because the string parsing would be crazy.
