### ISSUE TITLE
Ruffle failed to load the required ".wasm" file component

### ISSUE THREAD

**Issue by 1239447108** [ruffle-rs/ruffle#18587]
### Describe what you were doing

we use ruffle to load swf file on mobile device,  we found in IOS 17 or IOS 18, it worked , but in IOS 15 or IOS 16, the crash came out, we have set  option 'allowScriptAccess' and 'publicPath', but it did't work ![Image](https://github.com/user-attachments/assets/0b0e260f-ca3f-4613-a9b1-1dc8eb5e0697)

### What does the crash message say?

IOS 15:

# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 655 failed.
(error: http://10.81.1.63:36008/ruffle/core.ruffle.a5a1d8b6f354ae816ca4.js)
Error stack:
```
@http://10.81.1.63:36008/ruffle/index.js:1:6378
@http://10.81.1.63:36008/ruffle/index.js:1:4696
reduce@[native code]
@http://10.81.1.63:36008/ruffle/index.js:1:4680
@http://10.81.1.63:36008/ruffle/index.js:1:306849
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://10.81.1.63:36008/swf/WJGY/4/

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.53(0x18003530) NetType/WIFI Language/zh_CN
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-13
Channel: nightly
Built: 2024-11-13T00:06:11.308Z
Commit: 9e51cc47bdc6216e47c2e80b8b07710eee7c8c0a
Is extension: false

# Metadata

IOS 16:

# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 655 failed.
(error: http://10.81.1.63:36008/ruffle/core.ruffle.a5a1d8b6f354ae816ca4.js)
Error stack:
```
@http://10.81.1.63:36008/ruffle/index.js:1:6378
@http://10.81.1.63:36008/ruffle/index.js:1:4696
reduce@[native code]
@http://10.81.1.63:36008/ruffle/index.js:1:4680
@http://10.81.1.63:36008/ruffle/index.js:1:306849
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://10.81.1.63:36008/swf/WJGY/4/

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.53(0x18003530) NetType/WIFI Language/zh_CN
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2024-11-13
Channel: nightly
Built: 2024-11-13T00:06:11.308Z
Commit: 9e51cc47bdc6216e47c2e80b8b07710eee7c8c0a
Is extension: false

# Metadata

### Ruffle Version

nightly-2024-11-13

### Affected platform

Desktop app

### Operating system

IOS 15 or IOS 16

**Comment by danielhjacobs** [comment]
Did you include every file that came in the Ruffle self-hosted zip, including both wasm files, on your server? Ruffle loads one of the wasm files on newer browsers with support for more WebAssembly extensions, and the other one on older browsers like Safari 15 or Safari 16.3 or below (parsing the user agent, you have WeChat 8 on iOS 16.3, which is like Safari 16.3).

If you only include the wasm file with support for the WebAssembly extensions you could get an error like the one mentioned.

**Comment by danielhjacobs** [comment]
It's worth noting, you're iOS 16 version is not the newest version of iOS 16 available, so you should be able to update it.

**Comment by 1239447108** [comment]
thank you
