### ISSUE TITLE
Game Scaling Issue: Games Not Sizing Correctly to Container

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#18595]
### Describe the bug

I noticed that some games are not sizing correctly to the container where they are. This cause the game to hide important parts, buttons, and so  on.

To reproduce the problem, you can shrink the window of the browser / tab.

1. Canyon Defense 2: here the loader is well sized, but after that the game will start way bigger.
2. Super Mario Crossover: there the game will have a fixed size

I tried to add different styling / parameters, but from what I've tried, nothing worked.

### Expected behavior

To resize to available width/height of the container.

### Content Location

- https://www.archive.play-games.com/games/ruffle/?swf=miniclip/canyondefense/2v4.swf&params=&name=Canyon%20Defense%202
- https://www.play-games.com/embed/8018.html

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by Benman2785** [comment]
i highly suspect either the swf has a "no_scale" option internally enabled (you can usually change this easily with "JPEXS Free Flash Decompiler") or you use the wrong scaling option for your swf (exact-fit, showall etc)

**Comment by Stefannag** [comment]
> i highly suspect either the swf has a "no_scale" option internally enabled (you can usually change this easily with "JPEXS Free Flash Decompiler") or you use the wrong scaling option for your swf (exact-fit, showall etc)

It is possible to take a look at config? Maybe you can see if I write something wrong.. I can't find what is not correct. 

I created a testing page for those 2 games: 
1. https://www.archive.play-games.com/games/ruffle/test.php?swf=mario/super-mario-crossover.swf
2. https://www.archive.play-games.com/games/ruffle/test.php?swf=miniclip/canyondefense/2v4.swf

This is the config: 

```
window.RufflePlayer = window.RufflePlayer || {};
  window.addEventListener("load", (event) => {
    const ruffle = window.RufflePlayer.newest();
    const player = ruffle.createPlayer();
    const container = document.getElementById("game");

    container.appendChild(player);

    container.style.display = "flex";
    container.style.justifyContent = "center"; 
    container.style.alignItems = "center";
    player.style.width = "100%";
    player.style.height = "100%";

    player.load({
        url: swfPath,
        parameters: gameParameters,
        allowScriptAccess: allowScriptAccessVar
    });

  });

  window.RufflePlayer.config = {
    // Options affecting the whole page
    "publicPath": undefined,
    "polyfills": true,

    // Options affecting files only
    "autoplay": "on",
    "unmuteOverlay": "hidden",
    "wmode": "window",
    "letterbox": "fullscreen",
    "warnOnUnsupportedContent": warn,
    "contextMenu": true,
    "showSwfDownload": false,
    "upgradeToHttps": window.location.protocol === "https:",
    "maxExecutionDuration": {"secs": 15, "nanos": 0},
    "logLevel": "error",
    "base": basePath,
    "menu": true,
    "salign": "center",
    "openUrlMode": openUrlMode,
    "scale": "showAll",
    "quality": "best",
    "preloader": true,
    "backgroundColor": "#000000",
    "allowNetworking": "all",
    "allowScriptAccess": true,
    "forceAlign": "true",
    "forceScale": "true"
  };
```

I tried to add directly here too, but this won't work either:

```
player.load({
        url: swfPath,
        parameters: gameParameters,
        scale: "showAll",
        align: "center",
        allowScriptAccess: allowScriptAccessVar
    });
```


I tried WaFlash, seems to center well 'Canyon Defense', but is not working. So I assume the SWF file is ok. You can check that by pressing the right top button > and hit the 'waflash' button. 

I didn't set something correctly?

**Comment by Stefannag** [comment]
Somehow, I wrote the wrong commands: 
```
"forceAlign": "true",
 "forceScale": "true"
```

Boolean should be without comma. 

And `"letterbox": "fullscreen"`, should be set with `on`.
