### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by killynathan** [ruffle-rs/ruffle#1861]
# Error Info
Error name: TypeError
Error message: _i[e] is not a function
Error stack:
```
TypeError: _i[e] is not a function
    at Function.fi (chrome-extension://okkachkgefoiphefognhffhdofhfcnab/dist/ruffle.js:1:31635)
    at http://www.bluffave.com/css/scriptaculous/prototype.js:1:915
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.bluffave.com/porquenolosdos

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-06
Channel: nightly
Built: 2020-12-06T00:33:07.355Z
Commit: 16b9c77d0232f9dcf80ca0727343eff8f2ffb2c4

**Comment by Toad06** [comment]
Thanks for the report.

I'm going to close this in favor of #1507 and #1630, as this issue implies the same library (prototype.js).

Thanks again.
