### ISSUE TITLE
problem with text color on Yojijukugo Flash (四字熟語 Flash)

### ISSUE THREAD

**Issue by pingval** [ruffle-rs/ruffle#1863]
With Ruffle, text of panel is displayed in not BLACK but GREEN.
I tested with Ruffle Nightly 2020-12-06 on Windows 10 Home 64bit.

Yojijukugo Flash (四字熟語 Flash): https://www.gamedesign.jp/flash/yojifla/yojifla.html

Adobe Flash Player 32:
![capture_06122020_191757](https://user-images.githubusercontent.com/40169989/101277780-20687380-37fa-11eb-936d-2a6483ddffb9.png)

Ruffle Nightly 2020-12-06:
![capture_06122020_191912](https://user-images.githubusercontent.com/40169989/101277785-28c0ae80-37fa-11eb-9ae9-0190ba642158.png)

**Comment by JMcKiern** [comment]
The issue is that EditText.textColor doesn't seem to be implemented.

The initial color of the Kanji sprite is `#ff00ff33` (green) as in the image in the Ruffle Nightly screenshot.

This gets changed to black by setting `tfKanji.textColor = 0;`. Ruffle fails to update the color here.
