### ISSUE TITLE
Gift Grab fails to register class

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1864]
When the game starts, the following warning is displayed in the console:
`Tried to register_class on an unknown export SantaDropSymbol`

As a consequence, the game is unplayable.

The code is located in `\SantaDropSymbol`:
`Object.registerClass("SantaDropSymbol",SantaDrop);`

Wrapping this piece of code inside a setTimeout fixes the issue.
This game has possibly been edited with an external app, as another version exists and this one shows no issue.

[gift_grab.zip](https://github.com/ruffle-rs/ruffle/files/5649034/gift_grab.zip)

**Comment by Herschel** [comment]
The ExportAssets tag that links the export name to the symbol appears before the DoInitAction tag, but this works in the Flash Player. Need to investigate whether the a) you can register a class at any point, and it will work if that export is later defined; or b) the DoInitAction is queued to run at the end of the frame it's seen on, so the ExportAssets would have to appear on the same frame, at the latest.

**Comment by Toad06** [comment]
FWIW, while taking a look at #1989, I noticed that the code in `\Symbol 605`:
`Object.registerClass("Symbol 605",ActiveProp);`

was immediately run in Ruffle. In Flash Player, you have to start a game and enter the cave.

**Comment by Herschel** [comment]
Fixed by #2367.
