### ISSUE TITLE
Error playing files

### ISSUE THREAD

**Issue by germanrudnev** [ruffle-rs/ruffle#1865]
https://web.archive.org/web/20070304115859/http://www.vh1.ru/

**Comment by Toad06** [comment]
This is likely a duplicate of #1507 and #1630, though the library at fault is different here.

Blocking this file:
https://web.archive.org/web/20070210172343js_/http://vh1.ru/lib/fValidate/fValidate.core.js
allows Ruffle to start.

**Comment by Toad06** [comment]
Fixed by #2051.
