### ISSUE TITLE
Animation Transformation unable to  finish load on Archive.org

### ISSUE THREAD

**Issue by mariojuggernaut22** [ruffle-rs/ruffle#1866]
Hello. After Uploading Animation Transformation on Archive.Org. It refuses to finish load and Play. How can this be resolved?

https://archive.org/details/578280-film-v-2

**Comment by Herschel** [comment]
This animation uses the Newgrounds API in its preloader, which will be unable to work from a different domain (the Internet Archive), even in the standard Flash Player.
