### ISSUE TITLE
Regression in vertical text alignment

### ISSUE THREAD

**Issue by 123jjck** [ruffle-rs/ruffle#18668]
### Describe the bug

1. Open https://xarium.cc/playtest.php
2. Text is not displayed correctly
3. ![Image](https://github.com/user-attachments/assets/5cc14ee2-5dbf-4694-97c9-98cc585d707a)

### Expected behavior

Normal messagebox:
![Image](https://github.com/user-attachments/assets/a972e3d9-7f0e-4f32-b225-9fa4c635bdc7)
(you can test at https://xarium.cc/playtestold.php with [nightly-10-03](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-10-03))

### Content Location

https://xarium.cc/playtest.php

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 131.0.6778.70 

### Additional information

Script that creates MessageBoxes: (method `CreateTextField`):
[MessageBoxConfig.txt](https://github.com/user-attachments/files/17812638/MessageBoxConfig.txt)

Probably due to https://github.com/ruffle-rs/ruffle/pull/18162, since versions before [nightly-2024-10-04](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-10-04) works fine

**Comment by kjarosh** [comment]
No easy way of reproducing it on desktop. SWF requires a lot of files, the website somehow detects Ruffle Desktop and returns 403.

**Comment by 123jjck** [comment]
> website somehow detects Ruffle Desktop and returns 403

This is due to CloudFlare's JS challenge.
I modified the game client to display a messagebox every time it initializes (don't pay attention to the "undefined" button)
[serial_experiments_lain.zip](https://github.com/user-attachments/files/17822990/serial_experiments_lain.zip)

![Image](https://github.com/user-attachments/assets/37ad3497-2293-4b73-b893-b32504d1f86f)

**Comment by kjarosh** [comment]
@123jjck thank you! That makes debugging a lot easier.

So I don't believe the main reason this renders wrong is text alignment issues (before https://github.com/ruffle-rs/ruffle/pull/18162 it must have looked better by accident). The text field is generated programmatically and the result is different in Flash and in Ruffle. Most notably, the font size is 20 instead of 19, and the height is 48.95 instead of 61.75.

**Comment by 123jjck** [comment]
> the font size is 20 instead of 19

Isn't the font size 19.5 according to the code? (maybe different rounding in Flash and in Ruffle?)
```as
   function CreateTextField(name, depth, text)
   {
      var _loc5_ = this.content_mc.createTextField(name,depth,MessageBoxConfig.OFFSET_LEFT,0,this.data.width - MessageBoxConfig.OFFSET_LEFT - MessageBoxConfig.OFFSET_RIGHT,30);
      _loc5_.antiAliasType = "normal";
      _loc5_.multiline = true;
      _loc5_.wordWrap = true;
      _loc5_.autoSize = "left";
      _loc5_.embedFonts = true;
      _loc5_.selectable = false;
      var _loc6_ = new TextFormat("Rotonda Bold",19.5,16777215); <----
      _loc6_.align = "center";
      _loc5_.setNewTextFormat(_loc6_);
      _loc5_.html = true;
      _loc5_.htmlText = text;
      return _loc5_;
   }
```
and is the different height of the text field caused by the ``autoSize`` bug?

**Comment by kjarosh** [comment]
Yeah, you're right!

Indeed, Ruffle uses a different rounding than Flash; it's related to the fact that Flash rounds these numbers differently in the constructor vs in the setter. The height issue probably results from the fact that Ruffle ignores the first empty line when calculating the height in autosize, but I haven't confirmed it yet.
