### ISSUE TITLE
[desktop] File picker dialog is blurry on Windows with HiDPI display

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#1867]
Display scaling set to 150% on a 1920x1080 display on Windows 10 20H2. 

![image](https://user-images.githubusercontent.com/51363864/101351202-597d1280-38e4-11eb-89b8-0d0f5c0831b6.png)

<3 y'all!

**Comment by Herschel** [comment]
Thanks for the report! This is probably a wontfix as we rely on the `tinyfiledialogs` crate to handle this cross-platform, which uses older Win32 file API. We're stuck with this unless we find a different crate that doesn't complicate the build process too much.

**Comment by Poopooracoocoo** [comment]
@Herschel Is there anywhere else I should file this? Should I send an email to the author of tinyfiledialogs?

**Comment by Herschel** [comment]
@Poopooracoocoo You would have to report an issue to `tinyfiledialogs` upstream: (https://sourceforge.net/projects/tinyfiledialogs/)

**Comment by Poopooracoocoo** [comment]
Okie doke. So Guillaume replied to my email and said that the solution that Microsoft recommends is beyond what he can do in tinyfiledialogs and that he's looking into newer dialogs, but can't confirm anything, like when it'll be ready.
