### ISSUE TITLE
read AS from SWF files

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#187]
@Herschel,

I would like to report another issue from https://randomfoo.net/oscon/2002/lessig/free_culture.swf.

To provide a more accurate report of what isn’t working, I need to read the AS code from the file.

Do you know a tool that can extract the AS code from the SWF file? (I’m on Linux only 😅.)

Many thanks for your help and for your excellent work (also many thanks to you, @kmeisthax and @Dinnerbone).

**Comment by Dinnerbone** [comment]
I use JPEXS when I want to inspect the actionscript of a movie: https://github.com/jindrapetrik/jpexs-decompiler/wiki/Installation

Not every file can be easily decoded, as some are obfuscated. It's helpful to run ruffle with `--feature avm_debug` and `RUST_LOG=debug` to see what leads up to any error or warning in the log, and you can try to identify which actionscript it's running at a given moment.

I'd love to experiment with both an actionscript compiler & decompiler in ruffle codebase someday though :D

**Comment by ousia** [comment]
Many thanks for your reply, @Dinnerbone.

Do you know whether there is any way to get a single file with all AS code in JPEXS?

**Comment by ousia** [comment]
@Dinnerbone, excuse me for my stupid question 😥, but I have to ask it 😅.

How should I invoke `RUST_LOG=debug` and `--feature avm_debug`.

I get an error with:

```
RUST_LOG=debug ./ruffle  free_culture.swf --feature avm_debug
```

Many thanks for your help.

**Comment by Herschel** [comment]
You supply the feature to the Rust compiler, this enables a compile-time flag:
`cargo build --features=avm_debug`
Then you can run with logging:
`RUST_LOG=debug ./ruffle foo.swf`
Our debug logging/tools are still fairly minimal :-)

In JPEXS decompiler, you can either navigate through the script tags manually, or there is an "Export All" button in the toolbar at the top, which brings up a dialog where you can select "ActionScript". Hope this helps!

**Comment by ousia** [comment]
@Herschel, would it be possible that the nightly builds are compiled with `--features=avm_debug`?

**Comment by Herschel** [comment]
@ousia Unfortunately it causes quite a lot of debug spew and performance impact on games, and it's mostly intended for developers, so I prefer to have it disabled by default.

**Comment by ousia** [comment]
@Herschel, this is fine.

I think I have to investigate further on this (how to get all AS code into a single file in Linux).
