### ISSUE TITLE
1-2039388553

### ISSUE THREAD

**Issue by gagerr124** [ruffle-rs/ruffle#18706]
### Describe what you were doing

121335456656577577

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: Parent device is lost

### Ruffle Version

0.1.0-nightly (c901b967473ab9810e6b654b997ef757bcf456c5 2024-11-18)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Pro) [64-bit]

**Comment by evilpie** [comment]
Duplicate of #18690
