### ISSUE TITLE
Regression in Rainbow Dash Shooter Project on nightly build 2024-11-24

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#18734]
### Describe the bug

We can now see all the hidden 2D pony models on the game's title screen

![Image](https://github.com/user-attachments/assets/f8b51ed5-b60d-4927-b6ff-a1cd20365b71)

### Expected behavior

![Image](https://github.com/user-attachments/assets/c0c622b0-52a6-494a-b2c3-0dd8154854b3)

### Content Location

[Rainbow Dash Shooter Project.zip](https://github.com/user-attachments/files/17891325/Rainbow.Dash.Shooter.Project.zip)

### Affected platform

Desktop app

### Operating system

Windows 11 x64

### Browser

Firefox nightly 134.0a1

**Comment by n0samu** [comment]
Fixed by #18742
