### ISSUE TITLE
Can't install extension on Firefox

### ISSUE THREAD

**Issue by nailuj29gaming** [ruffle-rs/ruffle#1876]
When I try to download the .xpi file, Firefox attempts to install it, and fails due to the extension being unsigned.

**Comment by WumboSpasm** [comment]
You need [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) to use unsigned extensions.

**Comment by bbb651** [comment]
Alternatively, you can load a temporary addon from [this page](about:debugging#/runtime/this-firefox).

**Comment by nailuj29gaming** [comment]
@WumboSpasm I have firefox developer edition
@bbb651 it won't even. Let me download it without attempting to install it

**Comment by Toad06** [comment]
Just right-click the .xpi and save to disk. Then you can install the extension as per above comments.

**Comment by nailuj29gaming** [comment]
@toad06 `save link as`

**Comment by Sethbarrie** [comment]
Would putting it on the AMO be possible? That way it could be signed, still be hosted on github, and make it available to a wider set of people. They even have a dev mode for nightly builds

https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

**Comment by nailuj29gaming** [comment]
@Sethbarrie I think that is a great idea. Not many people want to fiddle around in the debugging section of firefox just to play flash games

**Comment by nailuj29gaming** [comment]
@Sethbarrie I think it also might be a good idea to submit it to the Chrome extensions store, if possible. Many more people use chrome than Firefox.

**Comment by Justin-CB** [comment]
To install the nightly extension on FireFox, you need FireFox developer or FireFox nightly & you need to go into about:config & change xpinstall.signatures.required to false. Else you need to wait for the official release or temporarily set it up using about:debugging.

**Comment by LOuroboros** [comment]
> 
> 
> Would putting it on the AMO be possible? That way it could be signed, still be hosted on github, and make it available to a wider set of people. They even have a dev mode for nightly builds
> 
> https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

This would be great.

I'm not quite fond of being forced to use the Developer, Unbranded or Nightly versions of Firefox myself, and the solution involving loading the .xpi via about:debugging is inconvenient as the addon deletes itself as soon as you close Firefox.

**Comment by relrelb** [comment]
Fixed by #4021.

**Comment by LOuroboros** [comment]
> 
> 
> Fixed by #4021.

Neither the .xpi present in the Releases section of https://ruffle.rs/ nor the one in the Releases section of this repository can be installed on Firefox 87.0 x86, as Firefox still complains the addon is unverified though.

Wouldn't it be better to wait until the next release happens so it can be properly confirmed that the issue was effectively addressed, before closing it?
