### ISSUE TITLE
Chuzzle -- "Tried to instantiate non-registered character"

### ISSUE THREAD

**Issue by thenickman100** [ruffle-rs/ruffle#18778]
### Describe the bug

The game fails to fully load and provides an error message 
"Tried to instantiate non-registered character Naked".  
![Image](https://github.com/user-attachments/assets/a92c8385-1aa9-4841-a453-899801c64473)

### Expected behavior

The game should load.

### Content Location

[chuzzle.zip](https://github.com/user-attachments/files/17932760/chuzzle.zip)

### Affected platform

Self-hosted version

### Operating system

Windows 11 Home

### Browser

Edge Version 131.0.2903.70 (Official build) (64-bit)

**Comment by n0samu** [comment]
Closing in favor of #18796
