### ISSUE TITLE
Game Content not fully working on Nightly 12-7-2020 build.

### ISSUE THREAD

**Issue by SeaMac** [ruffle-rs/ruffle#1880]
I've installed the latest nightly build on my own server and started hosting .SWF Files I've had for a LONG Time.
So, the file jewel_quest.swf is PARTIALLY Working ... but I'm hard pressed to describe the weird nature of the error ... Pieces aren't displaying properly and sometimes unexpected gaps appear in the board. (This is a simple "Match 3" type game.)
If you want to see the error in action my little page is at: https://thetruthabouthemp.com/arcade/jewel_quest.html 
It takes a minute or less to load. And the Fault might be entirely in the Embed Code on that page.
(I've tried 2 games so far - the Other game isn't working either because the Enter Key doesn't start the game over here:  https://thetruthabouthemp.com/arcade/frogger.html )
And, neither of those SWF files plays nicely with The Ruffle Demo.

**Comment by JMcKiern** [comment]
Looks like Jewel Quest is showing multiple pieces on the same tile. This tile for example has both a red and green piece:

![image](https://user-images.githubusercontent.com/9341692/101420120-736d2400-38e9-11eb-903e-00ab4e35c3b9.png)

For Frogger, if you press Enter before clicking on the text box, it proceeds to Level 1. Maybe the Enter keypress isn't being propagated out of the TextField?

Also, Frogger is printing some issues to the console, I'll need to look at these when I get more time

All of this behavior is the same on the desktop application so there doesn't seem to be any problems with the embedding code

**Comment by SeaMac** [comment]
Yeah, Jewel Quest has some very interesting bugs: as each type piece has several sprites assigned to it (eyes flashing - shrinking away when matched - different # of sprites per tile type?) and sometimes "gaps" appear in the playing field where nothing can be swapped into. The Errors compound upon each other as the game limps bravely along ... though I've tried several times it isn't possible to complete the first level ... like playing Fairy Chess in Bizzaro World.

I have an ARCHIVE of 251 Common SWF Games at https://archive.org/download/pssst and I'm slowly placing them one-by-one in a test Arcade https://thetruthabouthemp.com/arcade/ 

Thank you for the tip about Frogger ... as soon as I post this I'm going to go try that out again.

I'll update my "Self Hosted" nightly build every few days (or a week) so I'm testing with a 'very recent' build. If I find other games of those 251 in that Archive that have issues (most likely), do I start a new topic for each "Broken" game? Or would you prefer I just respond to this Topic with the Details of the "New" test failure?

Where is the ruffle console? I'd attach dumps of errors with my notice of 'file funniness' in SWF - if I knew how. I'd love to see the madness progress as Jewel Quest gets more and more fouled up ... LOL! 

I haven't been this excited about any emulator project since I first found MAME Decades? ago ... And I make a good Beta Tester.

**Comment by SeaMac** [comment]
I can't get Frogger started when there is no Cursor in the input field either. Nothing I do can start it.
I'm using Firefox 83.0 (64-bit) with Mac OS 10.13.6 on PowerMac5,1

**Comment by JMcKiern** [comment]
I'm currently taking a look at Jewel Quest in JPEXC Flash Decompiler, so I'll update here if I find anything. Some of these errors are mad and the random nature of both the initial and dropped symbols make it fairly difficult to test!

Ruffle prints logs some stuff to the console (on web open Dev Tools with F12) if you build it with the avm_debug feature enabled. There are supposed to be [keybinds associated with debugging](https://github.com/ruffle-rs/ruffle/blob/master/CONTRIBUTING.md#debugging-actionscript-content) but I haven't been able to get that to work properly.

I've found that on the start page of Frogger, you can focus the text field and still use the arrow keys to move the frog.

Regarding the opening new issues, I would guess that it makes sense to have a different issue for different bugs. So maybe if two games are causing the same graphical glitch, it makes sense to open one issue. But if they are unrelated, open up two different issues. That's how I'd do it anyway.

**Comment by SeaMac** [comment]
Yeah, Jewel Quest is an Advanced Nightmare as far as debugging goes. (Yet, Those are often the most satisfying to untangle - and most fruitful!)
I met a 'joke' SWF file which I thought should be exceedingly simple (It is Tetris with a round instead of Flat bottom) ... tetrisinhell.swf which gave one of those scary looking "Something went Wrong! {Please file a Bug}" panels ... I filed it as a New Bug #1902 https://github.com/ruffle-rs/ruffle/issues/1902 

I'll keep bringing you interesting new bugs to troubleshoot as I unearth them.

**Comment by n0samu** [comment]
Both of the bugs reported here seem to be fixed now. Please leave a comment if something is still broken and I'll reopen the issue.
