### ISSUE TITLE
DN8:Pulse black screen after preloader

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#18846]
### Describe the bug

After the preloader screen, DN8:Pulse appears to be stuck on a black screen.

### Expected behavior

After the preloader, it should advance to sponsor and developer intros.

### Content Location

https://www.newgrounds.com/portal/view/594814/format/flash?emulate=flash

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome Version 130.0.6723.119 (Official Build) (64-bit)

**Comment by Aaron1011** [comment]
This SWF assumes that at least two `Stage3D` instances are always available:
```
         var _loc2_:Boolean = ApplicationDomain.currentDomain.hasDefinition("flash.display.Stage3D");
         if(_loc2_ == true)
         {
            stage.stage3Ds[1].addEventListener(Event.CONTEXT3D_CREATE,this.onContext3DCreate);
            stage.stage3Ds[1].addEventListener(ErrorEvent.ERROR,this.onStage3DError);
            stage.stage3Ds[1].requestContext3D();
         }
```

I'll need to see how many Flash Player typically provides, and adjust our code to provide that many.
