### ISSUE TITLE
web: Add "Download SWF" and "Reload SWF" options to the context menu

### ISSUE THREAD

**Issue by JMcKiern** [ruffle-rs/ruffle#1885]
Maybe these should just be in a debug build but I think it'd be useful to have a "Download SWF" and a "Reload SWF" option

Are there potential problems with facilitating easy downloading of SWFs? Would people get upset?

**Comment by bbb651** [comment]
I also think a "Download SWF" is a useful option, as it would make it more convenient to quickly backup and preserve games from websites, but "Reload SWF" doesn't sound that useful (at least for the web version) as you can just reload the page..? As for the desktop version from what I understand currently the instance of ruffle is closely tied with the instance of the game running, meaning you can't easily close the game without closing the emulator, so I'm not sure how hard it would be to implement (also there's no context menu on desktop yet).

**Comment by Fancy2209** [comment]
> I also think a "Download SWF" is a useful option, as it would make it more convenient to quickly backup and preserve games from websites, but "Reload SWF" doesn't sound that useful (at least for the web version) as you can just reload the page..? As for the desktop version from what I understand currently the instance of ruffle is closely tied with the instance of the game running, meaning you can't easily close the game without closing the emulator, so I'm not sure how hard it would be to implement (also there's no context menu on desktop yet).
> I don't think there's a problem with allowing you to download games, it's encouraged to archive flash content and there already are huge flash archives like flashpoint (if it's a problem with a specific site some kind of blacklist can solve it).

well, reload swf or reload game would be useful indeed 
you can't reload [the web demo](https://ruffle.rs/demo/) when an swf is loaded for example

**Comment by Txori** [comment]
SWF embed inside SWF won't work. Also, Flashpoint already "preserved" games.

**Comment by JMcKiern** [comment]
@bbb651 Good point about the reloading difficulty. I noticed that in the web implementation, the `load_data()` and `stream_from()` functions should only be called once:

https://github.com/ruffle-rs/ruffle/blob/021194875a2897a56d3dc961597e5f75b8369ec6/web/src/lib.rs#L131-L132

So, I'd imagine there's a bit of work to detach the Ruffle instance from the game instance.

> well, reload swf or reload game would be useful indeed
> you can't reload [the web demo](https://ruffle.rs/demo/) when an swf is loaded for example

Yeah, that's where I'd like to use it: load up an swf, try a few things until it breaks, reload and repeat.

Regarding the download feature, I do know that Nitrome isn't allowing Flashpoint to archive their games. Maybe they'd dislike a download button in Ruffle too. Still, it'd be useful to be able to quickly download an SWF that's causing issues in Ruffle to do further local testing/debugging.

**Comment by KuromeSan** [comment]
> @bbb651 Good point about the reloading difficulty. I noticed that in the web implementation, the `load_data()` and `stream_from()` functions should only be called once:
> 
> https://github.com/ruffle-rs/ruffle/blob/021194875a2897a56d3dc961597e5f75b8369ec6/web/src/lib.rs#L131-L132
> 
> So, I'd imagine there's a bit of work to detach the Ruffle instance from the game instance.
> 
> > well, reload swf or reload game would be useful indeed
> > you can't reload [the web demo](https://ruffle.rs/demo/) when an swf is loaded for example
> 
> Yeah, that's where I'd like to use it: load up an swf, try a few things until it breaks, reload and repeat.
> 
> Regarding the download feature, I do know that Nitrome isn't allowing Flashpoint to archive their games. Maybe they'd dislike a download button in Ruffle too. Still, it'd be useful to be able to quickly download an SWF that's causing issues in Ruffle to do further local testing/debugging.
> 
> > SWF embedded inside SWF won't work.
> 
> With downloading you mean? Yeah, good point
> 

But you can download such SWFs from the network tab anyway.. so not having a download option doesn't mean you can't download it

**Comment by jcha1600** [comment]
> so not having a download option doesn't mean you can't download it

Ease of access is the key in this context.
First, Not every people know that the network tab even exists.
Besides, hit F12, head to network, hit F5, and figure out which files are which and get the file VS. A simple right click to get the file you want.
I think we know the clear winner.

**Comment by relrelb** [comment]
Download functionality was implemented in #5602. Keeping open for the reload functionality.

**Comment by JergenRoss** [comment]
> > so not having a download option doesn't mean you can't download it
> 
> Ease of access is the key in this context. First, Not every people know that the network tab even exists. Besides, hit F12, head to network, hit F5, and figure out which files are which and get the file VS. A simple right click to get the file you want. I think we know the clear winner.

100% working. this is USEFUL, thank you!
also you can copy URL from file then flash player standalone open to paste URL and enjoy.

I need this put to instruction page in GitHub or Ruffle website for people looking "how to get download .swf in both ruffle ext. and embedded."

**Comment by n0samu** [comment]
Requested features implemented in #5602 and #10480
