### ISSUE TITLE
keyListener.onKeyUp is called when it shouldn't

### ISSUE THREAD

**Issue by Txori** [ruffle-rs/ruffle#1886]
I made a simple key listener using:

```
keyListener = new Object();
keyListener.onKeyUp = function()
{
	var release_key = Key.getCode();
	if (release_key == Key.SPACE)
	{
		// do thing
	}
}
Key.addListener(keyListener);
```

On Ruffle, keyListener.onKeyUp is called after a few frames, even if the SPACE key is still pressed, then it starts a virtual button smash.

You'll find the stripped example at this address: https://www.txori.com/stuff/ruffle/debug/
You can compare the Flash version, Ruffle version and download the source.

**Comment by PsychoGoldfishNG** [comment]
This is also causing onKeyDown to fire rapidly.   It's behaving like when you hold a key on a text input where you get 1 char, a small pause, then it starts mass-printing the character, so you get a rapid up/down pattern.
