### ISSUE TITLE
The Flash version spoofing feature is not working.

### ISSUE THREAD

**Issue by minusmulticoloredper** [ruffle-rs/ruffle#18884]
### Describe the bug

The Flash version spoofing feature is not working.
![Image](https://github.com/user-attachments/assets/da3f48f6-91fa-4459-9f86-be7af90ab744)

### Expected behavior

The Flash version was successfully read by the detection tool.

### Content Location

https://www.sioe.cn/xinqing/flash

### Affected platform

Browser's extension

### Operating system

Windows 7

### Browser

Microsoft Edge 109

**Comment by kjarosh** [comment]
Are you sure you have the extension installed and enabled? It works for me and shows 32.0.0

**Comment by minusmulticoloredper** [comment]
I am sure that the extension has been enabled, and the extension version is Nightly 2024-12-06.

**Comment by minusmulticoloredper** [comment]
![Image](https://github.com/user-attachments/assets/63f54e65-1d62-4229-b68b-cea4486c1f68)
![Image](https://github.com/user-attachments/assets/1b69fd4b-316a-4d5a-b7ac-908615dae4ba)

**Comment by minusmulticoloredper** [comment]
I just tried exiting InPrivate mode and found that the Flash version was successfully read. However, once I re-entered InPrivate mode, even with the extension allowed to run in InPrivate mode, the Flash version could not be read. What could be the issue? Is it a problem with InPrivate mode or with the extension?

**Comment by kjarosh** [comment]
Weird... it does work for me in Chromium and Firefox, in private browsing too. That might be a bug related to Microsoft Edge (somehow).

I'm sorry, I don't understand Chinese, but according to the translator, the extension is enabled in private browsing right?

**Comment by minusmulticoloredper** [comment]
Yes, I have indeed allowed the extension to be enabled in InPrivate mode.
Actually, I don't know English; I use ChatGPT for translation.

**Comment by kjarosh** [comment]
> This issue might be related to the browser version.

That is consistent with tests done by others. It probably was a bug in MS Edge in older versions. :)

I'm closing the issue then, I'm glad it works with a newer version!
