### ISSUE TITLE
Ruffle scanner panics on known good SWF

### ISSUE THREAD

**Issue by tsunamistate** [ruffle-rs/ruffle#18898]
### Describe what you were doing

Running a scanner on my SWF collection, it produced a result that 41 (out of 86) SFW panicked or crashed the scanner
All the panic messages are the same, listed below
I have bisected these messages to d63214f7575db2611c7159a9bc9cb509d3f6d56d (https://github.com/ruffle-rs/ruffle/pull/18708)

Here's a couple of SWF's that causes the scanner to panic
[panic.zip](https://github.com/user-attachments/files/18049212/panic.zip)

### What does the crash message say?

```
thread 'main' panicked at core\src\html\layout.rs:394:48:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Ruffle Version

https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-11-25

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Croworbit** [comment]
Ruffle cannt scan .SFW files, only .SWF or .SPL

**Comment by Lord-McSweeney** [comment]
This should also be fixed by #18814

**Comment by tsunamistate** [comment]
> Ruffle cannot scan .SFW files, only .SWF or .SPL

Sorry, typo

**Comment by Lord-McSweeney** [comment]
@tsunamistate can you retest this in a few hours, when the nightly 2024-12-08 is released?

**Comment by tsunamistate** [comment]
Confirmed fix after https://github.com/ruffle-rs/ruffle/pull/18814 was merged
