### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Laye2806** [ruffle-rs/ruffle#18942]
### Describe what you were doing

I just wanted to start up the application and it kept crashing.

### What does the crash message say?

panicked at desktop\src\app.rs:466:14:
GUI controller should be created: Parent device is lost

### Ruffle Version

0.1.0-nightly (f24fcc2020309eff1fedb4b4529a4593b1eb2650 2024-12-10)

### Affected platform

Desktop app

### Operating system

Windows 10.0.19045 (Windows 10 Home) [64-bit]

**Comment by kjarosh** [comment]
Hi, thanks for reporting the issue. Could you paste here logs of Ruffle? Do you have a GPU?
