### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by themisadventuresofjason** [ruffle-rs/ruffle#18943]
Hi so I really enjoy the ruffle program but when I tried implementing some ruffle code into my site it wouldn’t work and I was wondering how to fix this? Help would be greatly appreciated! 

https://themisadventuresofjason.github.io/tmoj/

**Comment by Lord-McSweeney** [comment]
Hi, the code on your page
```
<object data="/tmoj/docs/webpage.swf" type="application/x-shockwave-flash" width="720" height="620">
```
tries to load the SWF from `/tmoj/docs/webpage.swf`, but it's actually at `/tmoj/webpage.swf`. If you change that line to
```
<object data="/tmoj/webpage.swf" type="application/x-shockwave-flash" width="720" height="620">
```
then it should work.

**Comment by themisadventuresofjason** [comment]
Thanks! It works now. 

Appreciate your help man 8)
