### ISSUE TITLE
"Gateway"-Game  HTTP/S Issue

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#1895]
I already filed an issue about games not working so I tested a few of them. I digged deeper into the game "Gateway" and found it, it tries to load the nested files in http and not https which stops the browser from loading those files and thus the game can never work. I also write about adding the "base"-feature for such things so you can chose an "patch" where such nested .swfs should load from. Dunno if that could also help with this http issue.

But is there a chance that ruffle could change the http to https in case it's loaded via https or is it better to wait for the implement of the "base"-feature.

![image](https://user-images.githubusercontent.com/23042167/101597074-77d33300-39f6-11eb-836f-9abd354b29a9.png)

**Comment by Herschel** [comment]
Thanks for the report, would be covered by #1486, closing in favor of that issue.
