### ISSUE TITLE
Add instructions for "without a bundler" wasm building and usage

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#19]
Add simple instructions (either in README or the wiki) on how to build and use the web frontend without a bundler, using simple `<script>` tags. It can be based on the instructions [in the Rust Wasm book](https://rustwasm.github.io/wasm-bindgen/examples/without-a-bundler.html).

**Comment by utsudashinou** [comment]
I wrote the demo for "without a bundler".
https://github.com/utsudashinou/ruffle/tree/wasm-without-a-bundler

**Comment by Herschel** [comment]
This is documented now (https://github.com/ruffle-rs/ruffle/blob/master/web/README.md).
