### ISSUE TITLE
Habbo Hotel Flash Version is dead in Dec, 2020

### ISSUE THREAD

**Issue by joelemanoel** [ruffle-rs/ruffle#1901]
@Herschel and others, your possible Ruffle and Habbo Hotel working together?
Habbo Hotel could be a sponsor of Ruffle and could implement it in a deprecated version.

I am not part of Sulake Corporation, but it is a suggested partnership attempt.

**Comment by damiendawreck** [comment]
Won't be necessary anymore since Habbo is oficcially switching towards Unity instead of flash for their client. It would be nice for all the "alternative habbo websites" that still use the old flash version.
