### ISSUE TITLE
Something Went wrong (in Hell)

### ISSUE THREAD

**Issue by SeaMac** [ruffle-rs/ruffle#1902]
this https://softwaresanta.com/sssmf/images/tetrisinhell.swf  file made ruffle web demo CRY ... It is not working in the self-hosted version but throws no BIG Errors.

**Comment by SeaMac** [comment]
http://www.erif.org/code/Hell/ SWF file is rendered as a black box - using Firefox Nightly Build .xpi 12-18-2020 temporary plugin.

**Comment by n0samu** [comment]
This may be the same issue as #7209 - hopefully someone can check again after #7956 is merged.

**Comment by kmeisthax** [comment]
That PR does fix the problem (it uses `mx.flex.BitmapAsset`) but now it gives a black screen with no output or errors.

Looking at the SWF it appears to use MochiAd in the preloader, and I know that said ad network is a bit of a challenge for Flash games nowadays...

**Comment by Lord-McSweeney** [comment]
The image displays, but the file is not interactive in Ruffle.

**Comment by n0samu** [comment]
@Lord-McSweeney Are you sure about that? The game is working for me, although it gets unplayably slow when calculating physics interactions between several tetris pieces. Nevertheless, if you can confirm that the game is working, I think the issue should be closed.
