### ISSUE TITLE
Error running definition tag: DefineEditText, got Invalid data

### ISSUE THREAD

**Issue by Daveman3d** [ruffle-rs/ruffle#1903]
Hello,
I've got an error with this swf.
It's a match questionaire,  the generation of the elements is done programmatically but ruffle is not able to load it correctly.
i've got multiple errors on the developer console:
ruffle_web_bg.js:1255 Error running definition tag: DefineEditText, got Invalid data: Invalid string data
ruffle_web_bg.js:1255 Tried to instantiate non-registered character ID 22
ruffle_web_bg.js:1255 Unable to instantiate display node id 22
ruffle_web_bg.js:1255 Couldn't parse SWF. This may or may not be a bug in Ruffle, please help us by reporting it to https://github.com/ruffle-rs/ruffle/issues and include the swf that triggered it.

I tried it with nighty build as of 2020-12-9 selfhosted.
[habilidad1.zip](https://github.com/ruffle-rs/ruffle/files/5672259/habilidad1.zip)

Thank you for your support.

**Comment by JMcKiern** [comment]
Ruffle is trying to read all strings from SWFs as UTF-8. However, for SWF versions 5 and earlier, strings are formatted as either ANSI or shift-JIS (determined by the machine's locale).

While the most common ANSI characters are the same in UTF-8 (they are both supersets of ASCII), there are some outliers. This SWF uses a `0xED (í)` character which fails in `String::from_utf8()`. Instead, `byte as char` should be used.

The relevant code is here:
https://github.com/ruffle-rs/ruffle/blob/4358e52af746929abcbbd5f05e577b98a0992fdd/swf/src/read.rs#L269-L281

I will submit a pr later this week if no one else fixes it first.

**Comment by Herschel** [comment]
Thanks for the report! Fixed by #2636.
