### ISSUE TITLE
Color setTransform gets undone in Dad 'n Me

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1906]
The kids in Dad 'n Me have a variety of colors but in Ruffle, they sometimes revert to the default pink after a color change has been performed.

https://www.newgrounds.com/projects/games/1561373/preview/filetype/0

In Flash, this character will always remain beige. In Ruffle, the character reverts to default pink after initially updating to beige.

FLA file:
https://www.newgrounds.com/dump/item/f5f675da38dad16df9f6c471be316ed5

Frame 1 has some code snippets from Dad 'n Me related to color swapping. Frame 30 calls the function to update the hud.

**Comment by Herschel** [comment]
Color transform seems to get reset when the inner kid clip loops.
