### ISSUE TITLE
Super Mario 63 crashes after first part of the tutorial level

### ISSUE THREAD

**Issue by AnnoyedArt1256** [ruffle-rs/ruffle#1909]
weird

**Comment by Poopooracoocoo** [comment]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1332:9
Error stack:
```
Error: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1332:9
    at Object.Y (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.efe183f76847e3a3efc0.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1608688541:1:36567)
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[1109]:0x225944
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[1460]:0x269bae
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[3955]:0x3293e2
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[3096]:0x308595
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4319]:0x32eced
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4266]:0x32e3cb
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4320]:0x32ed16
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/5a9a20d03ac9672b3fd2.module.wasm:wasm-function[4265]:0x32e39d
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1608688541%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F498000%2F498969_Super_Mario_63__2009_.swf%3F1353774292%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%225fe2f4248c36e%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A450%2C%22height%22%3A300%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F498000%2Fflash_498969.gif%3Ff1281597958%22%7D
SWF URL: https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?1353774292

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-22
Channel: nightly
Built: 2020-12-22T00:39:03.522Z
Commit: f7797f85d6a2c340b0dfb97c42a3cc04be32b997

**Comment by Poopooracoocoo** [comment]
#1347

**Comment by Toad06** [comment]
Merging into #1347 as this is the same issue. Thanks for reporting.
