### ISSUE TITLE
two issues with SetBackgroundColor

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1913]
https://github.com/ousia/ruffle-demo/blob/master/006699.swf contains:

```
SETBACKGROUNDCOLOR (00/66/99)
```

It is displayed in <https://ousia.github.io/ruffle-demo/>.

But if background color is blue, there should be no black bars.

**Comment by ousia** [comment]
From https://github.com/ruffle-rs/ruffle/issues/1755#issuecomment-742529474:

![IMG_1915](https://user-images.githubusercontent.com/63494519/101779946-2f9b3a00-3af6-11eb-8736-14ec5f510031.PNG)

`SetBackgroundColor` of the SWF file is set to green.

@Wahrheit26 comments that the black bars should have the same color as the background color of the SWF file.

**Comment by Redondo26** [comment]
It would be really great to be able to set the background color for the ruffleplayer.

**Comment by ousia** [comment]
@Redondo26, many thanks for your first contribution to Ruffle.

Being able to set the background color (independent from the information contained in the SWF file itself) would be a third issue, or a whole new different one.

A JavaScript way to set this (also for the player) would be helpful, no doubt.

**Comment by Redondo26** [comment]
thanks for your answer

**Comment by ousia** [comment]
@Redondo26. I didn’t know that, but Flash allows to set the background color (independent from the SWF file itself).

According to https://github.com/ruffle-rs/ruffle/issues/2135#issue-775488092:

> The background is set by this in the OBJECT
> `<param name="bgcolor" value="#0000ff">`
> and by this in the EMBED
> `bgcolor="#0000ff"`

I hope it helps.

**Comment by Redondo26** [comment]
thank you !!!

**Comment by eabigelow** [comment]
Hi--

As mentioned above, the black bars should have the same color as the background color of the SWF file. This is not the case, even when we use (as noted above), as follows:

The background is set by this in the OBJECT
<param name="bgcolor" value="#0000ff">
and by this in the EMBED
bgcolor="#0000ff"

Is there a way to fix this?

Many thanks for your help!

**Comment by ousia** [comment]
@eabigelow,

many thanks for your comment.

I think your issue is perfectly described in #2135.

Or am I missing something? (Let me know in that case.)

Just in case it might help.

**Comment by eabigelow** [comment]
Thank you for your message. I went to #2135 but I do not see any clear way to have the wasm default background color (which is black) to be changed into the intended background color for the .swf file. For example, see here (and attached image): https://webyarns.com/pangram.html
<img width="1280" alt="Screen Shot 2021-01-04 at 2 02 19 PM" src="https://user-images.githubusercontent.com/1393069/103569601-97466a00-4e95-11eb-97a0-072679f90928.png">

Thank you for your advice!

**Comment by Redondo26** [comment]
Unfortunately, this does not work with the background color.
Here is an example:
https://www.nailartansbach.de/Beispiel/

can you please tell me what code you are using?

**Comment by ousia** [comment]
@eabigelow and @Redondo26, I’m afraid the code won’t work with Ruffle unless issue #2135 is solved.

**Comment by Redondo26** [comment]
@ousia 
thanks

**Comment by eabigelow** [comment]
Ok, thanks very much for the feedback!

**Comment by ousia** [comment]
@eabigelow, @Redondo26 & @Wahrheit26, #2453 will fix this issue (at least, partially).

**Comment by Herschel** [comment]
On web, letterboxing is now off by default, and the bgcolor is now honored, so this should be working correctly.

**Comment by ousia** [comment]
@Herschel, many thanks for fixing both issues.

**Comment by eabigelow** [comment]
This looks great. Thanks so much!

**Comment by ousia** [comment]
@nima-amin, the issue you mention in #2001 has been solved by @Herschel in #2453 (just reporting here, since I wonder notifications reach the recipient).

Although really the color mismatch isn’t caused by Ruffle, but it seems to be due to the SWF player you use.

**Comment by Herschel** [comment]
This should be working correctly now, as letterboxing is off by default on web, and bgcolor of the HTML embed is respected.

One thing left TODO is to implement `Stage.scaleMode`.
