### ISSUE TITLE
Non-ASCII characters not shown

### ISSUE THREAD

**Issue by chrysn** [ruffle-rs/ruffle#1918]
In some German language SWF files I tested, non-ASCII characters (eg. "ä") were not shown.

A publicly hosted example is https://mathe-online.at/galerie/grenz/folgenz/folgenz.swf -- In its initial state it says "Whlen Sie eine..." while it should say "Wählen Sie eine...", and after first having clicked on an expression it says "... um das nchste ..." instead of "... um das nächste ...".

Inspecting the file in a hex dump shows that the original text is in there in an UTF-8 encoded Unicode string that encodes for the right characters; only in display, that character is skipped.

**Comment by Herschel** [comment]
Thanks for the report, requires #1862, closing in favor of that issue.
