### ISSUE TITLE
Low frame rate when using my flash file on the demo page

### ISSUE THREAD

**Issue by alex7070m** [ruffle-rs/ruffle#1926]
Hello! When I upload my flash file, the flash plays at a low frame rate. In reality, it should play faster.
![11122020](https://user-images.githubusercontent.com/69157204/101908098-37291480-3bc4-11eb-930a-9a81cd8207a9.jpg)

**Comment by relrelb** [comment]
Can you please provide the SWF file itself (or a link referring it)?

**Comment by alex7070m** [comment]
http://monamour-dating.com/games/asteroids/game3.swf

**Comment by rdrpenguin04** [comment]
Ruffle's current priority is getting things working, not necessarily getting them working fast.

**Comment by alex7070m** [comment]
OK, thanks for your replay. I will wait for a solution so that the flash files work at normal speed.

**Comment by jhwgh1968** [comment]
@alex7070m, I tried downloading it and using the `ruffle_desktop` client. It seems to play okay there with a release build of the current master 4358e52af. Could it be your computer, or your browser?

Also, GitHub does not let you attach arbitrary files. Put your SWF in a GZ or a ZIP file, and then it will let you attach it.

**Comment by alex7070m** [comment]
Hi! I try to install ruffle for windows from https://ruffle.rs/#releases  but the installation failed:

![16122020](https://user-images.githubusercontent.com/69157204/102373496-eb61db00-3fc8-11eb-9222-2bd960df8381.jpg)

**Comment by alex7070m** [comment]
Hello! The game works on one site, but not on the other. Both sites are on the same server .  What could be the problem?

http://monamour-dating.com/games/asteroids/asteroids.htm

http://shalom-friends.com/games/asteroids/asteroids.htm

**Comment by alex7070m** [comment]
I figured out the problem, now everything works, thanks for the help!

**Comment by parkerlreed** [comment]
What was the issue?

**Comment by alex7070m** [comment]
I don't know for sure, I rewrote all the files. Before that, I contacted the hosting service to set up the server.

**Comment by Herschel** [comment]
Glad you solved it! Closing issue unless more info comes up.
