### ISSUE TITLE
Matrix and other structures should match Flash's internal representation

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#193]
Currently our Matrix uses float, but this causes some inaccuracies compared to Flash, which uses twips and fixed point values for its internal representation. For example, the value of `_x` will be slightly different between Ruffle and Flash Player due to this.

Color transforms are another area we should try to match, IIRC they use 8.8 fixed point values. For example, _alpha only increments in units of 1/256.

**Comment by MrCheeze** [comment]
The following flash's can't get past the initial screen because of this issue:

https://www.dolldivine.com/othergames/post-apocalyptic-duo-rin.swf

It contains the following ActionScript code:

```
onEnterFrame = function()
{
   ...
   if(this._alpha > 0)
   {
      this._alpha = this._alpha + (- this._alpha) / 4;
   }
   else
   {
      _root.removeMovieClip(adBox);
      _root.image._visible = true;
      _root.button._visible = true;
      delete this.onEnterFrame;
   }
};
```

_alpha will eventually converge to zero in flash player, but not ruffle.
