### ISSUE TITLE
emulating defunct high score / UGC services

### ISSUE THREAD

**Issue by TylerGlaiel** [ruffle-rs/ruffle#1933]
A number of old games used services like mochibot / armorbot / various custom services to host and keep track of high scores or other user-generated content like sharing levels and whatnot. A lot of these services have also gone defunct since then, and many more will in the future.

I'm not sure if emulating all these different backends to restore that functionality to those old games is within the scope of ruffle or not, but regardless that should be possible in some way, so I'd suggest there be some way to rewrite URL requests to other domains via a config file to allow for this in the future (ex, rewrite "mochibot.com" in URL requests to "mochibot.whatever.com")

This would also be useful for games that load SWFs from specific domains that may no longer exist in the future

**Comment by Herschel** [comment]
Closing in favor of #1486.
