### ISSUE TITLE
boys life blockbuster

### ISSUE THREAD

**Issue by thistleshire** [ruffle-rs/ruffle#1934]
immediately fails when playing https://boyslife.org/section/games/online-games/
on firefox.

Let me know if you want me to run it again, etc.

**Comment by n0samu** [comment]
Provided link no longer works, but the game is archived here: https://web.archive.org/web/20200730130919/https://boyslife.org/games/online-games/16255/block-busters/
The game seems to run fine now. If it doesn't work for you, please leave a comment and I can reopen the issue.
