### ISSUE TITLE
Implement Sound.setPan and sound.setVolume

### ISSUE THREAD

**Issue by veso266** [ruffle-rs/ruffle#1938]
I have a flash program controling my radio: http://radio1.dxing.si/gt/interface/radio.php?if=vk4fsgw&no-flash
I have no source unfortunately

but when I start the progam with ruffie, I get a lot Sound.setPan and sound.SetVolume not implemented (and a lot of undefined errors (but I cannot configrm if theese are present in flash as well as I have no flash-debugger (flash-firebug); http://o-minds.com/flash-debugger

license)

so if you maybe can take a look and implement Sound.setPan and sound.setVolume, but I am not sure if only theese are problematic, since it is generaly realy slow to start and the it (swf) only sits on the title screen

BTW: if you want to run it in flash, just remove &no-flash: http://radio1.dxing.si/gt/interface/radio.php?if=vk4fsgw

Thanks for Anwsering and Best Regards

**Comment by Herschel** [comment]
Fixed by #2825.
