### ISSUE TITLE
Background Music missing in "Robotic Unicorn Attack"

### ISSUE THREAD

**Issue by JayFoxRox** [ruffle-rs/ruffle#1939]
Game can be found here: https://www.crazygames.com/game/robot-unicorn-attack

*Edit: I did not try this version of the game in Flash player, as @Toad06 reports below, this might be an issue with this version of the game. Sorry for the confusion.*

**Comment by Toad06** [comment]
I've tested the game with the official Flash Player and the background music is also not played. I assume this file: https://www.crazygames.com/gameframe/music.swf should play the music but it doesn't exist (404). This is probably not a problem with Ruffle.

**Comment by JayFoxRox** [comment]
You are right. Sorry for the confusion.
Audio works in another copy, namely https://unicorn.jocke.no/

Closing this issue.
