### ISSUE TITLE
Faulty collision detection in Super Tank

### ISSUE THREAD

**Issue by XXLuigiMario** [ruffle-rs/ruffle#194]
When you begin a new game in Super Tank your vehicle is pushed off the game area and the only thing you can do is drive out of bounds. It's as if the game thinks you're inside a solid object.

![Floating Tank](https://user-images.githubusercontent.com/7153662/71211638-d7997100-22af-11ea-860b-f4a75ba14e8a.png)
**Video**: https://streamable.com/3lfal
**Game file**: https://cache.armorgames.com/files/games/super-tank-889.swf

**Comment by Herschel** [comment]
Might be because of #177

**Comment by Herschel** [comment]
Fixed by #1079.
