### ISSUE TITLE
Some graphic effects appear as black shapes in "Robotic Unicorn Attack"

### ISSUE THREAD

**Issue by JayFoxRox** [ruffle-rs/ruffle#1940]
Game can be found here: https://www.crazygames.com/game/robot-unicorn-attack (broken music, see #1939) and https://unicorn.jocke.no/

During jump:
![Broken jump](https://user-images.githubusercontent.com/360330/101984316-f511d880-3c80-11eb-9f27-5ee03a3d4889.png)

During dash:
![Broken dash](https://user-images.githubusercontent.com/360330/101984313-f0e5bb00-3c80-11eb-9d52-a8f37c6e09a6.png)

*(The green round shape should probably be blurred, but I believe this is a separate bug - either in ruffle or the game itself)*

Reference videos of how it should look can be found on YouTube: https://www.youtube.com/watch?v=-n-GvhmSMnU

---

I assume the broken effect is supposed to make the colors more saturated; potentially a multiplication; maybe some some blur?

Probably related to #58 or similar.

**Comment by Lord-McSweeney** [comment]
I cannot reproduce this issue anymore, not even on old builds on https://ruffle-regressions.github.io (dating back to January 2022).

**Comment by JayFoxRox** [comment]
Yes. Appears to be fixed.

Closed.
