### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by EdelMacias** [ruffle-rs/ruffle#1941]
# Error Info
Error: Error loading movie: Invalid data: Invalid SWF

# Player Info
Allows script access: false

# Page Info
Page URL: http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html?file=synj1.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

Using Brave Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by ousia** [comment]
Can you play https://ruffle.rs/demo/?file=synj1.swf?

**Comment by EdelMacias** [comment]
Yes, from the link you provided it works as one expect

**Comment by ousia** [comment]
I can play http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html (selecting then the same animation).

I think this is an older version of the extension and it might be that it has problems to pass the value of `?file=synj1.swf`.

Unless you cannot play the animation as described on the first paragraph, or you find another issue, I think this issue could be closed for now.

**Comment by Herschel** [comment]
That demo URL is no longer valid. May I ask where you got the URL? I'm wondering if we have a stale link in the docs somewhere.

The new demo URL is:
https://ruffle.rs/demo
I've changed the old URL into a redirect to the Ruffle homepage.

**Comment by EdelMacias** [comment]
The link I got from this article, under the _Emulating Flash Online With Ruffle_ section, it seems that they link that URL specifically.
https://www.online-tech-tips.com/computer-tips/flash-player-in-chrome-is-dead-in-2020-how-to-play-flash-files/

**Comment by ousia** [comment]
@Herschel, I wonder whether it would make more sense to redirect to https://ruffle.rs/demo.

I tried to provide a patch, but now I realize that server is outside the public repositories (at least).
