### ISSUE TITLE
Sinjid Text Box with Scrollbar

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1943]
https://www.newgrounds.com/portal/view/209736/format/flash?emulate=flash

On the introduction screen there is a text box with a story. In the Flash player there is a scrollbar you can use to scroll the story, however this is not available in Ruffle.

**Comment by JMcKiern** [comment]
Similar thing happens in Motherload after clicking "Instructions" on the main menu

**Comment by craniumcadoo** [comment]
I'm having the exact same issue with a website I work on, just posting here to stay updated.

**Comment by Herschel** [comment]
We need to implement `TextField.scroll` and other related properties.

**Comment by adrian17** [comment]
Related: https://github.com/ruffle-rs/ruffle/issues/1033
