### ISSUE TITLE
autoplay with audio on?

### ISSUE THREAD

**Issue by akosmaroy** [ruffle-rs/ruffle#1949]
Hi,

I'm looking to migrate our old flash-based web site http://tyrell.hu/ to ruffle, and I'd like to mimic the original behavour, which was starting the paly the flash content automatically with audio. I managed to get autoplay working, but the audio is muted at start. See for example the ruffle-enabled version of one of the pages here: http://tyrell.hu/ruffle/enter.html and the original flash-based here: http://tyrell.hu/enter.html

I looked around the config options, and I saw an option to remove the muted overlay, but no option to enable audio at start. I wonder how it can be achieved that the audio is on from the start of the autoplay?

Best regards,

Ákos

**Comment by ajayyy** [comment]
Chrome doesn't allow autoplaying audio anymore.

**Comment by Herschel** [comment]
Yes, unfortunately we are at the whims of browsers here, and modern browsers will generally not allow audio to play without a user interaction (hence Ruffle having various options enforcing a play button or mute overlay).

**Comment by akosmaroy** [comment]
if I would want to create a 'user interaction' myself for this, instead of the default ruffle 'click to unmute' overlay, how would I go about it?
