### ISSUE TITLE
Compatibility with Gamedesign's Flash Mahjong

### ISSUE THREAD

**Issue by phoe** [ruffle-rs/ruffle#1950]
https://www.gamedesign.jp/flash/mahjong/mahjong_e.swf is a self-contained Flash implementation of Japanese four-player mahjong. It is currently not working on Ruffle.

Attempting to run this file on https://ruffle.rs/demo/ results in a blank screen of the proper color, but the initial loading bar or anything afterwards does not appear.

I am a complete newbie to Ruffle and I do not know how or where to begin debugging this. Is there any more information regarding this file that I can provide?

**Comment by phoe** [comment]
I just took a look at the browser console which shows:

> This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended.

So it seems that this issue directly depends on https://github.com/ruffle-rs/ruffle/issues/1368 which implements AS3.

**Comment by n0samu** [comment]
Looks like this game is working now! If not, please leave a comment and I can reopen the issue.
