### ISSUE TITLE
String.fromCharCode(163) should return '£'

### ISSUE THREAD

**Issue by JMcKiern** [ruffle-rs/ruffle#1954]
Ruffle doesn't return anything from `String.fromCharCode(163)`, it should return a '£'.

### Relevant code

`result_txt.text = "String.fromCharCode(163): " + String.fromCharCode(163);`

### .fla and .swf files

[String.fromCharCode(163).zip](https://github.com/ruffle-rs/ruffle/files/5685130/String.fromCharCode.163.zip)

### Ruffle:

![image](https://user-images.githubusercontent.com/9341692/102020015-785d2800-3d6e-11eb-9b2e-b247c25e9a70.png)

### Flash:

![image](https://user-images.githubusercontent.com/9341692/102020024-8743da80-3d6e-11eb-918f-fc9b907bf85a.png)

**Comment by Herschel** [comment]
`String.fromCharCode` works (you can `trace(result_txt.text);` to check), it's that the faux-device-font does not contain the pound glyph (cc #1862).
