### ISSUE TITLE
Can't play flash games such as Super Stacker (2008) and Where Is My Beard (2014), Box Clever 2 (2016, updated 2018)

### ISSUE THREAD

**Issue by bedriczwaleta** [ruffle-rs/ruffle#1956]
I have a SWF file player and I will uninstall it together with SWF-HTML5 and Flashpoint. I was so scared in July 2017, and the Adobe employees even strongised the language - blocking Adobe in 12 January 2021!!!

I can't play some Flash games, they are just black colour. That situation must be analyzed. The. Black. Colour.

SWF Files
Link for where is my beard: http://i.notdoppler.com/files/whereismybeard.swf
Link for super stacker: https://www.andkon.com/arcade/puzzle/superstacker/superstacker.swf

Internet Versions
https://www.kongregate.com/games/gamezhero/where-is-my-beard
https://www.kongregate.com/games/inXile_ent/super-stacker

Chrome 87 - when I put this issue

**Comment by JMcKiern** [comment]
Both of those games use Actionscript 3, which isn't supported by Ruffle yet. But they're working on it!

**Comment by bedriczwaleta** [comment]
Oh thanks, how many time will take.

**Comment by n0samu** [comment]
Super Stacker seems to be working perfectly now! Where is My Beard is still broken though.

**Comment by Lord-McSweeney** [comment]
Error on Where Is My Beard: `Got "RustError("ArgumentError: Cannot remove object from display list it is not a child of.")" when constructing AVM2 side of movie clip of type GamezHeroPreloader`

**Comment by Lord-McSweeney** [comment]
Where Is My Beard now needs `flash.printing::PrintJob`.

**Comment by n0samu** [comment]
Where is My Beard is working fine now! 🎉
