### ISSUE TITLE
Screen turns black/white/blue when starting the game

### ISSUE THREAD

**Issue by MaxThunderscore** [ruffle-rs/ruffle#1965]
While testing some flash games prior to uploading them to archive.org I ran into this issue with the following games.

Commando: once the game starts the screen turns black; there is still music and sound effects playing though
GunRun: once the game starts the screen turns black; there is still music and sound effects playing though
Ninjaman: upon starting the game the screen turns black
Metal Slug 4: upon starting the game the screen turns white
RoboBugBlaster: upon starting the game, the screen turns blue

[Flash games.zip](https://github.com/ruffle-rs/ruffle/files/5687676/Flash.games.zip)

**Comment by n0samu** [comment]
Sorry for the long delay triaging this issue. It looks like the first 4 games are working fine now. As for Robobug Blaster, it is missing important assets and exhibits the same behavior in real Flash Player. Please leave a comment if you find further valid issues with any of these games and I can reopen this issue.
