### ISSUE TITLE
Game freezes at loading screen

### ISSUE THREAD

**Issue by MaxThunderscore** [ruffle-rs/ruffle#1967]
While testing some flash games prior to uploading them to archive.org I ran into this problem with the following games:

Heli Attack 3: game freezes right after squareco intro
Thing Thing 3: freezes at loading screen
Thing Thing Arena 2: freezes at loading screen

[Flash games.zip](https://github.com/ruffle-rs/ruffle/files/5687719/Flash.games.zip)

**Comment by n0samu** [comment]
The issue with Heli Attack 3 is covered by #1809. And the other issues don't seem to be occurring anymore. Please leave a comment if there are further problems and I can reopen this issue.

**Comment by Kippykip** [comment]
Seems to still be happening (Thing Thing Arena 3)
