### ISSUE TITLE
Bug report on loading a game

### ISSUE THREAD

**Issue by bdygrd** [ruffle-rs/ruffle#1970]
# Error Info
Error name: Error
Error message: panicked at 'byte index 1 is not a char boundary; it is inside '\u{a0}' (bytes 0..2) of `                                                                                                                         `', core/src/font.rs:334:39
Error stack:
```
Error: panicked at 'byte index 1 is not a char boundary; it is inside '\u{a0}' (bytes 0..2) of `                                                                                                                         `', core/src/font.rs:334:39
    at Object.$ (chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/core.ruffle.js:1:20404)
    at __wbg_new_df6e6ab7a65c4c4d (chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/ruffle.js:1:34597)
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[1074]:0x2158e4
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[1397]:0x254528
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[3731]:0x3093cc
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[2936]:0x2eb05c
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[4026]:0x30e003
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[4056]:0x30e566
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[3932]:0x30cc09
    at chrome-extension://iplhjmhiiklkgcgphlcmkngmpnpjdmep/dist/43dfd26cf6e20b0913c3.module.wasm:wasm-function[4057]:0x30e59c
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /sites/default/files/flash_games/ragdollcannon2.swf
Param menu: false
Param allowscriptaccess: always
Param allownetworking: all
Param movie: /sites/default/files/flash_games/ragdollcannon2.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.addictinggames.com/shooting/ragdoll-cannon-2

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13655.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4343.0 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-12
Channel: nightly
Built: 2020-12-12T00:33:23.026Z
Commit: 4358e52af746929abcbbd5f05e577b98a0992fdd

**Comment by dginovker** [comment]
Working link to game: https://www.bubblebox.com/play/1098/ragdoll-cannon-2.htm

Game is AS3

**Comment by n0samu** [comment]
Seems like this issue is not occurring anymore. But the game still doesn't load because it needs URLVariables implemented.

**Comment by Lord-McSweeney** [comment]
The game loads, but none of the buttons on the title screen can be clicked due to an error: `ReferenceError: Error #1069: Property init not found on global and there is no default value.`

**Comment by Lord-McSweeney** [comment]
This seems to work correctly now, though it has performance issues.
