### ISSUE TITLE
Desktop Version 2020-12-14: Systemfehler missing vcruntime140_1.dll 

### ISSUE THREAD

**Issue by nima-amin** [ruffle-rs/ruffle#1971]
I don't know whether I did this correct, however I downloaded the zip file for Windows (Windows 10 Professional) and extracted the content, double clicked on the exe file and expected the installation process to begin. Instead I first got a "Windows has blocked an unknown application" message, and after I have clicked on "run anyway", got a Systemfehler about a missing / not found vcruntime140_1.dll.

![Ruffle Systemfehler](https://user-images.githubusercontent.com/75982635/102076950-d3435d80-3e08-11eb-9302-ce00555d181e.png)

I repeated the entire procedure from the point of extracting the content from the zip.file with the same result. Any idea what could cause this?
I have run a search for the allegedly missing dll and have it twice, once included in Edge Browser, and once in a programme called Paint.Net, which makes it seem to me that it obviously comes as part of the programmes thatneed it and so should have been included in the programme package.

**Comment by torokati44** [comment]
You could try installing the latest version of the "Microsoft Visual C++ Redistributable for Visual Studio 2019" package for your machine:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
It helped others with similar issues.

**Comment by nima-amin** [comment]
I have these
![MS Visual](https://user-images.githubusercontent.com/75982635/102077657-f15d8d80-3e09-11eb-9486-0510ce8c1f3a.png)
and it says on the linked page they are the same?

**Comment by torokati44** [comment]
There still could be newer versions of it, might worth a try to install the newest one too.

**Comment by nima-amin** [comment]
No, the outcropped are the Microsoft Health Tools, what ever that is.

So, do I need the entire programme (to be found by clicking one page further seems pretty big) or just those updates? And which ones 32 or 64, as I have obviously the 2015 as 32 and th 2017 as 64. While I cannot find a prgramme folder at all. There is one among the Program Files x86 but with practically no content. No exe, for example. Confusing.

**Comment by nima-amin** [comment]
Installing the update file was enough, there is fortunately no need to install the entire big Visual Studio programme. Thank you very much.
