### ISSUE TITLE
Disable right-click menu on mobile

### ISSUE THREAD

**Issue by rmertens** [ruffle-rs/ruffle#1972]
On many mobile phones, tap & hold is equivalent to right click. This opens the Ruffle menu. But many games also use a click & hold mechanic (e.g. [the classic Helicopter game](https://archive.org/details/helicoptergame_flash)). So, these games at the moment work perfectly on mobile devices, except for the menu appearing unwanted.

Proposed solution:
* disabling the menu on mobile

Other possible solutions:
* removing the right-click menu and moving it to a menu bar or something like that
* giving developers using the Ruffle library an option to disable the menu on right-click

**Comment by Toad06** [comment]
Yes, this is annoying. Also, `oncontextmenu` isn't supported on iPadOS, so we'd need to make something consistent across mobile devices anyway. I wonder if we could use a similar approach that would require a double long touch (assuming that Flash doesn't permit multi-touch).

**Comment by x3fold** [comment]
> * giving developers using the Ruffle library an option to disable the menu on right-click

I would second this, being able to disable the menu totally (not just on mobile) would be very useful

**Comment by Herschel** [comment]
* There doesn't seem to be any API for determining whether a context menu was triggered by touch or not; therefore, we have to do some detection based on whether the device is touch and/or change the context menu shortcut completely.
 * How should this menu be summoned on mobile? Double long touch could work, although later AS3 content does in fact support touch events. This might be fine along with the disable-context-menu setting.
 * Even properly differentiating between "mobile" and "non-mobile" is not trivial; might want to bring in an npm package for this. There's also the issue of touch screen on desktop PCs.

**Comment by rmertens** [comment]
Good points @Herschel. 
* Maybe https://github.com/ruffle-rs/ruffle/issues/1977 is a better-defined issue. Then the user of the library can still decide whether they want to detect mobile vs non-mobile with an NPM package and disable the menu based on that.
* The menu could then be triggered via an API call, leaving it up to the user of the library what the UI should be and wether the menu is needed or not.

**Comment by Herschel** [comment]
#3967 disables the context menu as soon as a touch event is seen. This means context menu can not be used at all on mobile, but this is preferable to having it appear unexpectedly from long presses, interrupting content. There's still a question of if/how we want to trigger the context menu on mobile.
