### ISSUE TITLE
Add options to disable right-click context menu

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1977]
Similar to #1972, users may want to disable the right-click menu completely. Adding a JS config option for this would be useful.

`showContextMenu: true/false`

**Comment by ousia** [comment]
Sorry, @Herschel, I don’t know whether this is a good idea.

It raises a question: is this possible when loading the file with standard Flash?

It wouldn’t make sense (at least to me) that Ruffle and Flash behaved differently when dealing with this.

Disabling the menu on mobile may make sense if unusable (#1972), but maybe a general feature should be avoided.

**Comment by Txori** [comment]
In good old AS, one could disable the right click menu with fscommand("showmenu", "false");
This method isn't implemented yet, but I believe it's the same as passing <param name="menu" value="false" /> in the holding HTML page. So letting the user disabling the usage of right click makes sense to me.

**Comment by ROBERT-MCDOWELL** [comment]
or in As2
_root.menu = new ContextMenu();
_root.menu..hideBuiltInItems();

**Comment by ousia** [comment]
@Txori and @ROBERT-MCDOWELL, many thanks for your replies.

> In good old AS, one could disable the right click menu with `fscommand("showmenu", "false");`
> [...] in Flash, when right click menu is disabled, the items "Settings" and "About Adobe Flash Player" will still display.

As you mention, this method only disabled some items, but not all.

And I think it didn’t include a method to add custom items (such as in AS2).

> or in AS2
> ``` js
> _root.menu = new ContextMenu();
> _root.menu..hideBuiltInItems();
> ```

This doesn’t prevent the addition and display of new custom menu items.

Custom menu items are the main reason why I think that it might be an unwise decision to depart from standard Flash behavior.
