### ISSUE TITLE
Stick RPG - Title Screen Launches new tab (Ruffle only)

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1985]
https://www.newgrounds.com/portal/view/76020/fomat/flash?emulate=flash

When you start Stick RPG in Ruffle, it immediately loads this in a new tab:
http://www.xgenstudios.com/404.php

In the Flash player, no URL is loaded in a new tab.

**Comment by turicfr** [comment]
I get the same behavior in Flash Player as well.

**Comment by Toad06** [comment]
Yeah, this also happens to me on the official Flash Player. There's this code in frame 1:
`getUrl("http://www.xgenstudios.com/srpg/default.htm", "_new");`

Most of the time, browsers will detect this as a pop-up ad and block it, but Chrome will sometimes open it anyway (maybe it allows this after a click somewhere on the page - which is something required to start Ruffle on Newgrounds).

**Comment by Herschel** [comment]
Yep, happens in offical player too. (We could perhaps add a feature to prevent new tabs/navigation without a user click).
