### ISSUE TITLE
Red Baron - Sword doesn't collide with enemies

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1986]
https://www.newgrounds.com/portal/view/347399/fomat/flash?emulate=flash

When you swing your sword at an enemy in Ruffle, it passes through them with no collision reaction.

**Comment by Herschel** [comment]
I've been looking at this one for a long time; I believe it's a frame-execution-order issue. This would probably be solved by moving the execution order list to be a single global list, instead of per-display-object.

**Comment by Herschel** [comment]
Fixed by #4452.
