### ISSUE TITLE
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok

### ISSUE THREAD

**Issue by artificialbutter** [ruffle-rs/ruffle#1987]
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok

Any help would be nice.

**Comment by Herschel** [comment]
This sounds like you are missing some files and Ruffle is unable to load the wasm file. Do you have all of the following files in the directory:

ruffle.js
core.ruffle.XXXXX.js
core.ruffle.XXXXX.wasm

**Comment by Poopooracoocoo** [comment]
@artificialbutter Have you resolved your issues?

**Comment by artificialbutter** [comment]
sorry, I kinda forgot about this. I have fixed the issue :)
