### ISSUE TITLE
Zelda Lampshade - Plug doesn't always pull

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#1989]
https://www.newgrounds.com/portal/view/253819/fomat/flash?emulate=flash

Enter the dungeon, then walk up to the outlet and press Space.

In Flash, the outlet is removed, boss defeated, then it says "Wow, that was easy..."

In Ruffle this works sometimes but other times the outlet doesn't move, the boss remains but it still says "Wow, that was easy..", at which point the player is stuck.

**Comment by Poopooracoocoo** [comment]
https://www.newgrounds.com/portal/view/253819/fomat/flash?emulate=flash 
that link didn't work for me but this one does :)

**Comment by Toad06** [comment]
The code that should be run in this situation is located in `\__Packages\ActiveProp`:
```
else if(this == _root.plug && _root.plugpulled != true)
{
    _root.condition = true;
    _root.textbox.txt.text = "You pulled the plug...";
    _root.plugpulled = true;
}
```
But for some reason, the condition is never met. I've added some `trace`s:

`trace(this);` shows: `_level0.plug`
`trace(_root.plug);` shows: `_level0.plug`
`trace(this == _root.plug);` shows: `false` (!)

The last trace is sometimes `true`, in that case the issue doesn't happen, as Tom mentioned.

**Comment by Herschel** [comment]
Still an issue as of 10/2021.
