### ISSUE TITLE
Ruffle Error on Tor Browsers

### ISSUE THREAD

**Issue by VasilisThePikachu** [ruffle-rs/ruffle#1992]
This error appears when you try to load anything when on the tor browser with the extension or not
Tor browsers security level was set the standard and NoScript was turned off

While this may be useless as most people won't view flash on tor browser it will be nice to have

Reproduction:
1: Start Tor browser
2: Set security level to Standard
3: Visit https://ruffle.rs/demo/

Reproduced on:
Windows 10 Tor browser 10.0.5 (based on Mozilla Firefox 78.5.0esr)
Tails OS 4.14 Tor browser 10.0.7 (based on Mozilla Firefox 78.6.0esr)

If more info is needed tell me in comments

**On demo (without the extension installed):**
# Error Info
Error name: ReferenceError
Error message: webkitAudioContext is not defined
Error stack:
```
624@https://ruffle.rs/demo/662.index.js:1:15436
bi@https://ruffle.rs/demo/index.js:1:34398
662@https://ruffle.rs/demo/662.index.js:1:12310
bi@https://ruffle.rs/demo/index.js:1:34398

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-15
Channel: nightly
Built: 2020-12-15T00:33:46.121Z
Commit: 709561a25557520b5c537aad32e6b78512127cdb

**Comment by yakagami** [comment]
Is web assembly allowed in the Tor browser? I would think not. based on an unrelated project here https://github.com/PrivateBin/PrivateBin/issues/454 at least in 2019 Tor didn't have webasm.

**Comment by rdrpenguin04** [comment]
This doesn't look like a WASM-related issue. Tor disabled AudioContext for security reasons, as the Web Audio API is now available.

**Comment by rdrpenguin04** [comment]
Source: https://gitlab.torproject.org/legacy/trac/-/issues/12212

**Comment by VasilisThePikachu** [comment]
Seems like that was the case as enabling `dom.webaudio.enabled ` in `about:config` fixes it
is there anything that can be done about this?

also, while it now can do playback it seems like you can't interact with it at all

**Comment by Herschel** [comment]
Tor can disable many features for security reasons, so I don't think Ruffle will be officially supported on Tor. But we should try to fail more gracefully in these cases (for example, in the audio context case, we could play without audio if web audio isn't available).

**Comment by KuromeSan** [comment]
TOR disables alot of stuff to try prevent fingerprinting and whatever. right?

**Comment by Herschel** [comment]
Looked into this a bit more; the issue is that `wasm-bindgen` generates JS with this line:

`const lAudioContext = (typeof AudioContext !== 'undefined' ? AudioContext : webkitAudioContext);`

which causes an error because AudioContext/webkitAudioContext are undefined in Tor. This will take a change to `wasm-bindgen` to fix. Then we can catch the error normally and disable audio.

Opened https://github.com/rustwasm/wasm-bindgen/issues/2437 on wasm-bindgen.

**Comment by Herschel** [comment]
I've bumped to the latest wasm-bindgen, and Ruffle will now run without audio when the audio context can't be created (such as the Tor Browser w/ default settings).
