### ISSUE TITLE
IQ traveller Challange Doesn't load

### ISSUE THREAD

**Issue by tikito94** [ruffle-rs/ruffle#1994]
I tried to play IQ traveller Challange, on this website

The loading bar from the game appeared, but it stayed there and never really begun

This is the website:

https://www.travelark.org/tiq?game=game1

**Comment by tikito94** [comment]
Actually, I forgot to say: I tried on Nightly Firefox Browser, with 15/12 version of Ruffle.

**Comment by dginovker** [comment]
Works as of 0.1.0.544 :tada:
