### ISSUE TITLE
Device font not rendering in loaded SWF

### ISSUE THREAD

**Issue by cvandevelde** [ruffle-rs/ruffle#1995]
In this excellent mutlispectroscopy training module:

http://www.chemgapedia.de/multispektroskopie/en/multispectroscopy.html

you have to input the molecular formula via a set of bullets. The bullets light up when you hover the mouse over them, but if you click them, they don't get selected, and the input doesn't get sent through.
![chemgapedia1](https://user-images.githubusercontent.com/76148070/102452714-1c7af380-403b-11eb-89c8-e11bd8d60218.png)

(you get there by clicking the play button, selecting an exercise, then clicking the button "molecular formula")
With flash running normally, you can select a letter, then enter the tens and units via the bullets, select another letter, etc, until you have entered a molecular formula, e.g. C11H18O3 or something along those lines.

Thanks for developing this tool!

Cris

**Comment by Herschel** [comment]
Thanks for the report. The buttons themselves are working, but there seems to be an issue with the text field binding not updating, so the numbers aren't displayed.
