### ISSUE TITLE
Unknown tag code: 41 

### ISSUE THREAD

**Issue by matrix3d** [ruffle-rs/ruffle#20]

**Comment by Herschel** [comment]
Hi @matrix3d, could you share a link to an SWF with this tag for testong? It's not documented in the official SWF spec. Looks to be https://www.m2osw.com/swf_tag_productinfo

Thank you!

**Comment by matrix3d** [comment]
https://github.com/matrix3d/matrix3d.github.io/blob/master/assets/gl3d/test_light/FlashShader.swf

**Comment by Herschel** [comment]
This tag is now properly supported (it just contains metadata and is ignored). However, the SWF uses both ActionScript 3.0 and Stage3D so it is currently unsupported. See #12 for tracking on ActionScript support. Stage3D support will be a longer-term goal once ActionScript 3 support is functional.

**Comment by matrix3d** [comment]
@Herschel 
Please allow me to ask a few questions here. 1, this project can support as3 and stage3d this year, because there are many stage3d projects, such as starling and away3d. 2 How fast is this project expected to run the as3 project smoothly? Because there is a flashplayer virtual machine written by js, the speed is very slow, so I have this question.

**Comment by Herschel** [comment]
AS3 support is a goal and I hope AS3 content will be running within a year. However Stage3D is much more complex and will require research. It will be significantly longer before any Stage3D support is added, and I would not expect it soon. We will have a better estimate once we begin adding AS3 support.

Thanks for your interest!
