### ISSUE TITLE
Fetch-A-Fruit Hangs after selecting a Game Mode

### ISSUE THREAD

**Issue by ItsMaximum** [ruffle-rs/ruffle#2005]
[fetchafruit.zip](https://github.com/ruffle-rs/ruffle/files/5712436/fetchafruit.zip)

This flash game works fine initially, but the game hangs after the first voice line when selecting a game mode. There are no crashes or errors thrown; the game just stops progressing.

**Comment by Herschel** [comment]
Requires `Sound.onSoundComplete` to be implemented. Closing in favor of #396.

**Comment by Herschel** [comment]
Fixed by #2825.
