### ISSUE TITLE
Unable to select items from a drop-down menu

### ISSUE THREAD

**Issue by adriano-vilela** [ruffle-rs/ruffle#2006]
I'm unable to select items from the drop-down menu in http://www.fonologia.org/exercicios_estruturas.php

The flash content in the page above is here: www.fonologia.org/flash/exercicios/exercicio1.swf

The same problem happens here: http://www.fonologia.org/exercicios_classificacao_consoantes.php

The flash content in the page above is here: www.fonologia.org/flash/exercicios/exercicio2.swf

**Comment by Herschel** [comment]
Thanks for the report. There is some issue with the MX controls (maybe the PopUpManager, or masking as the list appears)?

**Comment by adriano-vilela** [comment]
I'm sorry; I don't even understand the question (I don't know anything about Flash). Please let me know if there's anything I can do to help with this issue.

**Comment by Herschel** [comment]
Sorry, I wasn't asking a question, only writing notes to myself or others to look into the problem. Thank you!

**Comment by digitalf0x** [comment]
This appears to affect the [flashVMS height visualizer](https://vms.bigfurs.com/flashVMS3.swf ) at [vms.bigfurs.com](https://vms.bigfurs.com/ ) as well, as noted [in an issue I filed on hitbox detection](https://github.com/ruffle-rs/ruffle/issues/3180 ).  Visually comparing the Flash content, it appears to be the same set of standard controls causing the problem, with the same symptoms - opening the menu works, but hover, select, or arrow keys don't change the options.

If there's any additional troubleshooting steps I could take, let me know!

**Comment by Padre2** [comment]
@ Herschel
I have been watching this for some time as I have a similar issue as posted in Drop-down menus and selections #3700.
Is anyone able to look at this issue, or give some pointers regarding of what to look for, or to try?

**Comment by desuwa** [comment]
This happens because the clickable areas have a size of 0 in Ruffle.

When you set the width/height on an completely empty object in Ruffle (like clips created by `createEmptyMovieClip`) there are some divisions by zero happening and the scale ends up being NaN, which in turn prevents you from resizing the object ever again.

**Comment by Padre2** [comment]
@desuwa
Many thanks for shedding some light on this issue. I understand why a NaN value will stop the process. Is this happening when the ruffle.js runs?  I could not find any specific place to start and from researching NaN issues, I see it has some confusing properties.

Can you explain why the clickable areas are sized at zero in Ruffle and whether this can be changed to prevent the NaN issue.

**Comment by desuwa** [comment]
@Padre2
It looks like a bug inside the `set_width` and `set_height` functions of [display objects](https://github.com/ruffle-rs/ruffle/blob/master/core/src/display_object.rs#L612).
Making sure new_scale_x/new_scale_y is finite (and if not, set it to 0) should fix this particular issue. Though there is probably a more thorough way to make those functions match Flash's behavior properly.

What happens in ActionScript is that if you do something like
```
this.createEmptyMovieClip('mc', this.getNextHighestDepth());
mc._width = 100;
```
it'll confuse Ruffle and lock your clip to 0 width / 0 height.
That drop down menu does something similar and basically when it creates the clickable areas, they get stuck with zero dimensions forever.

**Comment by Padre2** [comment]
@desuwa
Thank you for the more detailed information and link to the _display_objects.rs_ file. I assume that changes need to be made to this  file. Is it possible that you, or some of the contributors to this file can take a look at this issue to see if it can be resolved? I will be happy to assist with any testing.  I have attached a simple menu example that could be used for initial testing.
[testComboBox.zip](https://github.com/ruffle-rs/ruffle/files/6262016/testComboBox.zip)

**Comment by sombraguerrero** [comment]
Onda also has several components reliant on several mx controls and related event handlers akin to the ones mentioned here. The user side of the Morfosintaxis application, as an example, expects to be able to type text into a text box, hit a save button, have that added to a combo box, and then be able to select and interact with that element in turn.

[selector_de_evaluador_alumno_sesion.zip](https://github.com/ruffle-rs/ruffle/files/6268474/selector_de_evaluador_alumno_sesion.zip)
