### ISSUE TITLE
Ruffle Error on https://dethi.violet.vn/present/to-trinh-xin-mo-lop-xmc-nam-2020-truong-tieu-hoc-12966441.html

### ISSUE THREAD

**Issue by nguyenthekhoig7** [ruffle-rs/ruffle#2011]
# Error Info
Error name: TypeError
Error message: bi[e] is not a function
Error stack:
```
TypeError: bi[e] is not a function
    at Function.hi (<anonymous>:3:32170)
    at https://dethi.violet.vn/opcode/dc299c9acef9f9bb317dcf1c3cc0f020_1602207970.js:18:907
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://dethi.violet.vn/present/to-trinh-xin-mo-lop-xmc-nam-2020-truong-tieu-hoc-12966441.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Toad06** [comment]
Fixed by #2051.
