### ISSUE TITLE
Missing background, layers, blur effects.

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#2013]
Here regression in recent update Nightly 2020-12-18 for https://www.deviantart.com/empalu/art/Rd-flying-609955880 previously game worked fine on 2020-12-15 (atleast colorful rainbow from pony tail was missing and blur effect on clouds). 

![15](https://user-images.githubusercontent.com/38821724/102588647-9db3b280-412f-11eb-9953-ff26d9bce1bb.jpg)
![18](https://user-images.githubusercontent.com/38821724/102588664-a3a99380-412f-11eb-8d39-c4e54413e7cf.jpg)

**Comment by ousia** [comment]
I would say this is a [valid address for the animation](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/69237cc5-2d9c-48f3-8b9b-998d957d9bc4/da35gyw-b650619c-282b-4992-9360-1fa765554715.swf?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNjkyMzdjYzUtMmQ5Yy00OGYzLThiOWItOTk4ZDk1N2Q5YmM0XC9kYTM1Z3l3LWI2NTA2MTljLTI4MmItNDk5Mi05MzYwLTFmYTc2NTU1NDcxNS5zd2YifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.WmcxUkgaGyFCLF1cUKI3xV-ft6kFCp6fI4wq3Z21yxk) (direct link to SWF file).

**Comment by paq** [comment]
#1577 may be the cause.

**Comment by paq** [comment]
I would guess that this is not a regression.
This is probably because the implementation of BitmapData allows us to see effects that were not visible before.
Since the effects are needed to be displayed on screen blendMode, they are displayed in black.
#58 is required.

**Comment by SN902** [comment]
unimplemented BlendMode.SCREEN

**Comment by Lord-McSweeney** [comment]
Blend modes have been implemented on desktop, but this game is slow enough to be unplayable (it also uses BitmapData.draw).

**Comment by Lord-McSweeney** [comment]
I think this still needs the following:
```
Encountered stub: AVM1 BitmapData.applyFilter()
Encountered stub: AVM1 BitmapData.draw() with clip rect
```

**Comment by Lord-McSweeney** [comment]
I think this still needs the following:
```
Encountered stub: AVM1 BitmapData.applyFilter()
Encountered stub: AVM1 BitmapData.draw() with clip rect
```

**Comment by Kippykip** [comment]
Appears to be working fine on my side, other than the slightly buggy blur filter.
