### ISSUE TITLE
Visible content area limited by stage size

### ISSUE THREAD

**Issue by ChaseWaylon** [ruffle-rs/ruffle#2015]
![](https://pasteimg.com/images/2020/12/18/ruffle_black_bars.png)

Flash player:
when I expand the swf window (or go full screen) and aspect ratio changes, ui elements adapt to window size and move to the corner (like in this example).

Ruffle:
in the same situation black bars appear, only the stage size remains visible, ui elements move to the window corner, but are covered by black bars.

Flash reveals more background when changing aspect ratio, ruffle just covers extra space in black.

The fix would be most appreciated.

**Comment by ousia** [comment]
@ChaseWaylon, the address of the file is required to be able to test it.

Many thanks for your help.

**Comment by ousia** [comment]
From http://main.miracle-cn.com/ruffle/lesson4.swf, Flash displays:

![flash](https://user-images.githubusercontent.com/203767/102626084-a6fc4980-4146-11eb-9dd4-79b9e99c2119.png)

Ruffle displays:

![ruffle](https://user-images.githubusercontent.com/203767/102626088-a794e000-4146-11eb-90fb-4374af038199.png)

I’m afraid that Ruffle might be misreading the image dimensions.

Although the header contains the following info (which I would say is wrong):

```
[HEADER]        Movie width: 1024.00
[HEADER]        Movie height: 768.00
```

**Comment by Herschel** [comment]
Currently Ruffle displays a letterbox around the content intentiomnally. We need to add a setting to disable this, and disable it by default. Additionally, `Stage.scaleMode` needs to be implemented.

**Comment by ousia** [comment]
Just in case they might help, two more animations (which might have the right dimensions):

1. http://main.miracle-cn.com/ruffle/lesson1.swf (although this one even has issues with the Flash player).
1. http://main.miracle-cn.com/ruffle/2.swf.

**Comment by Poopooracoocoo** [comment]
ooo i hope this gets fixed by #2303 ^w^

**Comment by ousia** [comment]
@Poopooracoocoo, I have tried to check http://main.miracle-cn.com/ruffle/lesson4.swf at https://ruffle.rs/demo/ and I don’t get the wider stage.

Could you check whether it has been fixed by #2303?

Many thanks for your help.

**Comment by Poopooracoocoo** [comment]
The PR said that it doesn't change letterboxing on the demo, but http://www.ousia.tk/ruffle-demo/ (your website) has lost the letterboxing!! :D

**Comment by ousia** [comment]
> The demo page turns letterboxing on to match the previous behavior.

@Poopooracoocoo, I should have read this before asking 😅.

Many thanks for your explanation and your help.

**Comment by ousia** [comment]
@ChaseWaylon,

I wonder if your issue is fixed now.

Could you check it to see whether this issue may be closed?

Many thanks for your help.

**Comment by Herschel** [comment]
Stage scale mode is now supported thanks to #4033, in addition to the letterbox setting for more fine tuned control. Letterbox is disabled by default on web builds, but enabled by default on the demo site. Thank you!

**Comment by GroovyGamer1000** [comment]
hello. i am 4 YEARS LATE but how can i enable a a letterbox in this embed code? 

<html>
<head>
<script src="https://unpkg.com/@ruffle-rs/ruffle"></script>
<style>
html, body {
margin:0px;
}
</style>
</head>
<body>
<script>
window.RufflePlayer = window.RufflePlayer || {};
//Below code forces autoplay, no splashscreen and allows sound

window.RufflePlayer.config = {
"autoplay": "on","splashScreen": false,"unmuteOverlay": "hidden","quality": "medium" };
// End custom configuration code above
window.addEventListener("load", (event) => {
const ruffle = window.RufflePlayer.newest();
const player = ruffle.createPlayer();
const container = document.getElementById("container");
container.appendChild(player);
player.load("https://groovygamer1000.github.io/wubbzy-flash-games/wubbgirlz_main.swf");
player.style.width = "100%";
player.style.height = "100%";
});
</script>
<div id="container"></div>
</body>
</html>

**Comment by kirbysayshi** [comment]
@GroovyGamer1000 I was wondering too, so I looked at the enum in the source. This should do it:

```diff
window.RufflePlayer.config = {
- "autoplay": "on","splashScreen": false,"unmuteOverlay": "hidden","quality": "medium"
+ "autoplay": "on","splashScreen": false,"unmuteOverlay": "hidden","quality": "medium", letterbox: "on" };
```

You might want to consider formatting that code so it's a little easier for yourself to read 🤓 :

```js
window.RufflePlayer.config = {
  autoplay: 'on',
  splashScreen: false,
  unmuteOverlay: 'hidden',
  quality: 'medium',
  letterbox: 'on'
}
```
