### ISSUE TITLE
Ruffle has encountered a major issue whilst trying to display this flash content

### ISSUE THREAD

**Issue by drj4242** [ruffle-rs/ruffle#2022]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:779:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:779:18
    at Object.D (https://static.arantius.com/ruffle/core.ruffle.75408f40d9423287edd6.js:1:20372)
    at __wbg_new_df6e6ab7a65c4c4d (https://static.arantius.com/ruffle/ruffle.js:1:34986)
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[1054]:0x2057b3
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[1375]:0x243c18
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[3691]:0x2f77c8
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[2920]:0x2da271
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[3988]:0x2fc475
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[4018]:0x2fc9d8
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[3893]:0x2fb045
    at https://static.arantius.com/ruffle/3056e7c7d29075eca876.module.wasm:wasm-function[4019]:0x2fca0e
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: //static.arantius.com/games/8planet.swf
Param movie: //static.arantius.com/games/8planet.swf
Param quality: high
Param bgcolor: #FFFFFF
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://games.arantius.com/game.86.8+planet.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-01
Channel: nightly
Built: 2020-12-01T00:32:23.173Z
Commit: d06bbf23ce477d24f2e3758204d05f35e560601c

**Comment by Toad06** [comment]
Thanks for the report.

I'm closing this in favor of #1991, as this is the same issue.

Thanks again.
