### ISSUE TITLE
much thicker strokes in Ruffle

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#2023]
From http://main.miracle-cn.com/ruffle/2.swf (besides the wrong dimensions already reported in #2015 by @ChaseWaylon).

Ruffle displays a hand with much thicker strokes

![ruffle](https://user-images.githubusercontent.com/203767/102661675-a501ad00-417d-11eb-92be-d8340bcfb7bd.png)

than Flash itself actually does

![flash](https://user-images.githubusercontent.com/203767/102661683-a8953400-417d-11eb-9f6b-ca1363b1b461.png)

As an exercise to the viewer, I wonder whether the mustache and goatee are also affected by the same issue.

This is a rendering issue only tested with nightly from 2020-12-18 at https://ruffle.rs/demo.

Just in case it helps.

**Comment by relrelb** [comment]
Duplicate of #751?

**Comment by ousia** [comment]
@relrelb, probably this is a duplicate.

I hope not to forget to test this again, once #751 is fixed 😅.
