### ISSUE TITLE
Ruffle Error on https://helpx.adobe.com/flash-player.html

### ISSUE THREAD

**Issue by nagayev** [ruffle-rs/ruffle#2032]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
916/qt<@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:31875
G/<@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:19295
__wbg_drawImage_801ad094f4734689@https://helpx.adobe.com/flash-player.html:3:57273
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4012]:0x32650f
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[962]:0x1ff050
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[438]:0x126eeb
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[2902]:0x2f9db2
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1128]:0x2278c6
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3122]:0x306283
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[2902]:0x2f9dd9
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[975]:0x20271a
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[806]:0x1d0d45
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4180]:0x3290f3
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4449]:0x32c1c3
C@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:18533
f@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:17643
)', render/canvas/src/lib.rs:740:14
Error stack:
```
Y@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:20605
__wbg_new_df6e6ab7a65c4c4d@https://helpx.adobe.com/flash-player.html:3:35267
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1104]:0x22216b
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1447]:0x264d52
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3944]:0x3250b3
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3088]:0x30450a
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4249]:0x329f87
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4279]:0x32a4ea
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4152]:0x328adf
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4280]:0x32a520
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3659]:0x31e2b0
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[962]:0x1ff1e6
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[438]:0x126eeb
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[2902]:0x2f9db2
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1128]:0x2278c6
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3122]:0x306283
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[2902]:0x2f9dd9
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[975]:0x20271a
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[806]:0x1d0d45
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4180]:0x3290f3
@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4449]:0x32c1c3
C@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:18533
f@moz-extension://91d60e77-c136-4d4b-9d4f-7b889c05162f/dist/core.ruffle.js:1:17643

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /content/dam/help/en/flash-player/assets/flash_tree.swf
Param quality: high
Param bgcolor: #FAF6ED
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowscriptaccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://helpx.adobe.com/flash-player.html
SWF URL: https://helpx.adobe.com/content/dam/help/en/flash-player/assets/flash_tree.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-19
Channel: nightly
Built: 2020-12-19T00:34:27.448Z
Commit: 042e9a444b98f7dbf920a070ffe240ad01e7cbe4

**Comment by Poopooracoocoo** [comment]
@nagayev I don't see this error. I'll reopen if you do :)

**Comment by nagayev** [comment]
@Poopooracoocoo Okey, I'll check it tomorrow.
