### ISSUE TITLE
[SUGGESTION] Implement disabling Action Script 3

### ISSUE THREAD

**Issue by nagayev** [ruffle-rs/ruffle#2033]
Hello.
The support of ActionScript is at a very low level.
So maybe it's a good idea to add option to disable support of AS3?
And if user visit website with content using AS3 user will see screen with the text:
"Sorry, We don't support AS3 now"

**Comment by Herschel** [comment]
Duplicate of #1978

**Comment by nagayev** [comment]
@Herschel Sorry.

**Comment by Herschel** [comment]
@nagayev No worries :-)
