### ISSUE TITLE
Backgrounds are shown

### ISSUE THREAD

**Issue by phistuck** [ruffle-rs/ruffle#2036]
This small penguins game - [penguins.zip](https://github.com/ruffle-rs/ruffle/files/5719628/penguins.zip) - shows up differently with Ruffle.
Flash -
![image](https://user-images.githubusercontent.com/184400/102692869-53553300-420e-11eb-95e9-0bc79502bf21.png)

Ruffle -
![image](https://user-images.githubusercontent.com/184400/102692874-5d773180-420e-11eb-8a6e-b8399809e1e7.png)

Note that this is not my Flash game, so I cannot provide the source.

**Comment by Herschel** [comment]
Pending setMask being implemented, closing in favor of #1944
