### ISSUE TITLE
Run 2 flashes elements

### ISSUE THREAD

**Issue by LegitDax009** [ruffle-rs/ruffle#2039]
Run 2 doesn't work in Ruffle, it just flashes the elements really fast.
[run2.zip](https://github.com/ruffle-rs/ruffle/files/5719992/run2.zip)

Flash:
![image](https://user-images.githubusercontent.com/38143460/102697103-bc31b080-41f8-11eb-9e07-be0445103c63.png)

Ruffle (flashing buttons and stuff, you've been warned):
https://user-images.githubusercontent.com/38143460/102697118-dec3c980-41f8-11eb-8ad9-885b0bb8e920.mp4

**Comment by rdrpenguin04** [comment]
Run 2 uses AVM2, which is not yet supported. Thank you for the report!

**Comment by Toad06** [comment]
Closing in favor of #1368 as per above comment. Thank you.
