### ISSUE TITLE
Game freezes after pressing play

### ISSUE THREAD

**Issue by Scrooge2000** [ruffle-rs/ruffle#2040]
Game: http://f.jeu.info/057/165.swf

In Bart SimpSon Rambo Dwarf, pressing "Play" shows an image and then Bart parachuting down. In the live Flash version, Bart lands, a "Ready?" screen appears with a "Go" button, and then the game can be played as normal. However, playing through the Ruffle executable, he gets stuck before hitting the ground and hangs in midair, softlocking the game.

**Comment by Toad06** [comment]
Thanks for the report!

I'm not sure but there are chances that the issue related to obfuscation: if I change anything in the P-code source in `\frame 16\PlaceObject2 (154) Depth: 26 (flyer)\onClipEvent(enterFrame)`, then the issue happens on the official Flash Player as well.

**Comment by Toad06** [comment]
This will be fixed by #2636.

**Comment by Herschel** [comment]
Fixed by #2636.
