### ISSUE TITLE
Worrying question, does this work on SWF v10

### ISSUE THREAD

**Issue by GhbSmwc** [ruffle-rs/ruffle#2047]
I was wondering, since we're getting close to the date that Adobe will stop supporting the plugin. I'm worried about SWF v10+ files and if no adoption was made, could result in those access to these files be lost forever.

(It's stupid that adobe even stops distributing the software and even blocks it (remotely disables you from using it) if installed on the machine, because when software/code gets depreciated, it is usually archived and preserved for future references, just with a label saying “not recommended”).

**Comment by ROBERT-MCDOWELL** [comment]
I heard from a lead project manager that Adobe is still stuck with some patents used during the last 20 years and have
no time and resources to solve it and release Flash in open source.

**Comment by GhbSmwc** [comment]
And with bad licensing restrictions in place, this shows the problem if you give centralized control to a company, making a component of the internet like a dictatorship controlling how the internet works.

So far, I tested this page: https://www.furaffinity.net/view/12329836/ using google chrome, using this: https://github.com/ruffle-rs/ruffle/releases/download/nightly-2020-12-20/ruffle_nightly_2020_12_20_extension.zip and the FA page's flash player shows a white screen.

**Comment by GhbSmwc** [comment]
Also, this: http://askiisoft.com/games/pause-ahead/

**Comment by Herschel** [comment]
AS3 support is currently a WIP, so most SWF10 files are not currently functional, but we're working on it (cc #1368).

As far as archival, there are great projects such as [Flashpoint](https://bluemaxima.org/flashpoint/) which are attempting to archive all the SWFs and players, so the files will not be lost.
