### ISSUE TITLE
Game Content ALMOST Correct - eyeballdropper.swf

### ISSUE THREAD

**Issue by SeaMac** [ruffle-rs/ruffle#2054]
The game initializes OK and does the instructions screen with no problem ... but when the main game loop starts: the playing area suddenly turns red (which paints over the game elements).
There is a thin sliver of the game that can still be seen just above the bleeding.
download this file from: https://thetruthabouthemp.com/hempity/flash/eyeballdropper.swf

**Comment by Toad06** [comment]
This should be fixed once #1483 is merged.

**Comment by relrelb** [comment]
Fixed by #1483.
