### ISSUE TITLE
https://s2online.github.io/ is just a white screen

### ISSUE THREAD

**Issue by VFDan** [ruffle-rs/ruffle#2055]
Ruffle doesn't throw an error but https://s2online.github.io/ is a white screen like this:
![image](https://user-images.githubusercontent.com/44413950/102728222-75c37b00-42f8-11eb-98e6-2d38c8b7a508.png)
when it should look like this:
![image](https://user-images.githubusercontent.com/44413950/102728140-077eb880-42f8-11eb-9af6-0a03a895985a.png)

**Comment by Toad06** [comment]
Thank you for reporting an issue.

This file uses AS3 which is still a work in progress, so I'm closing this in favor of #1368.

**Comment by kena006** [comment]
Yeah. i wish this can work sometime soon.

**Comment by ScratchOld** [comment]
This is the worst!

**Comment by Lord-McSweeney** [comment]
See https://github.com/ruffle-rs/ruffle/issues/9058 for progress on Scratch 2.
