### ISSUE TITLE
Using/Implementing Ruffle Extension with MSFT Windows 10 Edge

### ISSUE THREAD

**Issue by deehill** [ruffle-rs/ruffle#2066]
Tried to install the nightly build of ruffle.zip
2020_12_21

Setup Edge to manage local extensions.

Downloaded the ruffle.zip extension. Unzipped the zipfile to a dir.

Went into Edge, invoked the Extension section of the menu, pointed the install/download extension to the dir.

Got the error:
Manifest parsing error: invalid field
'browser_style' found in 'browser_action'

Any ideas/thoughts...???

thanks

I'm looking to be able to test/run the test site http://livenewschat.eu --> flash stock
--->https://livenewschat.eu/stock-flashroom/

Much appreciation on this.

**Comment by Poopooracoocoo** [comment]
Installing the extension in Edge is no different to any other Chromium based browser. 
I was able to install the extension by getting the latest nightly extension.zip from the releases page, and then by enabling developer mode in the extensions page in Edge, and then by dragging and dropping the zip into the extensions page. 
It's an alternative, easier method :P I used Edge stable which is currently on version 87. 

>Went into Edge, invoked the Extension section of the menu, pointed the install/download extension to the dir.

I don't understand what you mean by this. It sounds like you clicked on the 'Load unpacked' button?

Do you perhaps have the 'Allow extensions from other stores' option disabled?

By the way the devtools console says that is SWF v10 and is written in ActionScript 3, which means that it doesn't work in Ruffle right now.

**Comment by Poopooracoocoo** [comment]
@deehill Just checking in to see if you saw my above message.

**Comment by Poopooracoocoo** [comment]
@deehill Just checking in again

**Comment by Poopooracoocoo** [comment]
@deehill Checking AGAIN. (sorry everyone!)

**Comment by Poopooracoocoo** [comment]
Closing due to no author feedback.
