### ISSUE TITLE
HRWiki logo doesn't function as intended (Web)

### ISSUE THREAD

**Issue by captainnintendo** [ruffle-rs/ruffle#2067]
The Homestar Runner Wiki's Halloween, Decemberween (Christmas), and Winter logos don't work like they're supposed to. Instead of you having to click on Homestar to change characters or outfits, it just does it by itself automatically and rapidly. You can't even click to go to the main page.

How to replicate:

1. Go to [http://www.hrwiki.org/wiki/Special:Logos](http://www.hrwiki.org/wiki/Special:Logos), then see the logos.

**Comment by Poopooracoocoo** [comment]
![sRj2PKfPE5](https://user-images.githubusercontent.com/51363864/102962775-a7785400-453b-11eb-8234-217611803955.gif)

**Comment by n0samu** [comment]
Aside from not going to the wiki main page when clicked, 7 out of the 8 logos seem to be working fine now.
The Valentine's Day logo still does not play/pause when clicked like it should.

**Comment by Lord-McSweeney** [comment]
With #9506 there is an endless spam of `ReferenceError: Error #1069: Property http://adobe.com/AS3/2006/builtin::hasOwnProperty not found on Class and there is no default value.`.

**Comment by n0samu** [comment]
Actually that error spam has been happening for months and only affects some of the other logos, not the Valentine's Day logo.

**Comment by Lord-McSweeney** [comment]
After #10812, the last issue will be on http://www.hrwiki.org/w/skins/common/images/wiki-val.swf, which needs playerglobal versioning.
