### ISSUE TITLE
BitmapData.applyFilter, BitmapData.scroll, BitmapData.copyPixels not yet implemented

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2073]
As I see that in 2020-12-23 some work was done for BitmapData, I'll leave this flash as one which uses some of the unimplemented features of Bitmap:

https://z0r.de/7463

![image](https://user-images.githubusercontent.com/75184268/103032709-cbef2300-4571-11eb-965c-df601215b616.png)

Maybe it could be helpful to people who will try to implement this.

No AS3 warning here.

**Comment by Diatonator** [comment]
https://z0r.de/6372
Here I also see this: 
![image](https://user-images.githubusercontent.com/75184268/103038697-28593f00-4580-11eb-9380-89d6e84338b7.png)

This is the different sort of unimplemented, I guess?

**Comment by Lord-McSweeney** [comment]
#5482 implemented Sound.position.

**Comment by Lord-McSweeney** [comment]
https://z0r.de/7463 looks like it's working fine now. BitmapData.scroll and BitmapData.copyPixels were both implemented. https://z0r.de/6372 looks okay, except it needs both hardlight and multiply blendmodes, as well as BitmapData.applyFilter.

**Comment by n0samu** [comment]
All required features have been implemented, and both movies look fine now!
