### ISSUE TITLE
No sound in flash clip

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2074]
https://z0r.de/975
![image](https://user-images.githubusercontent.com/75184268/103035758-0c9e6a80-4579-11eb-9ece-2c5c520ef5e0.png)

**Comment by Herschel** [comment]
Sound is encoded with Nellymoser, pending #1920.
Closing in favor of #5.
(I think this may also be a case where the sample rate of the audio is different than what is encoded in the audio, so this may also be affected by #335).
