### ISSUE TITLE
Sound can become distorted if `StreamSoundBlock` tags are intermittent

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2075]
Heavy distortion (a full-on crust) in some flash clips on z0r.de
Browser Chrome 87.0.4280.88

https://z0r.de/2506
https://z0r.de/2370
NOTE: when I click off the tab which plays the flash - the crust disappears! When I click back - it's crust again.
No visuals here too but it looks like typical unimplemented stuff.

**Comment by Herschel** [comment]
Thanks for the report. `SoundStreamBlock` is intermittent on some frames but not on others, causing the stream to stop and restart on Ruffle. I guess we should allow for a frame of wiggle room of 1-2 frames for a Stream sound.

**Comment by Diatonator** [comment]
+ https://z0r.de/2344

**Comment by Diatonator** [comment]
The issue persists on Nightly 2021-12-30

**Comment by Diatonator** [comment]
Nightly 2022-07-29 - fixed!
