### ISSUE TITLE
None of the Papa Louie games work that i've played, they won't even start

### ISSUE THREAD

**Issue by Lgamer2500** [ruffle-rs/ruffle#2076]

**Comment by Herschel** [comment]
Thanks for the report! These game need ActionScript 3 support, closing in favor of #1368.

**Comment by Lgamer2500** [comment]
> Thanks for the report! These game need ActionScript 3 support, closing in favor of #1368.

Will Ruffle ever support ActionScript 3?

**Comment by Herschel** [comment]
Working on it!
