### ISSUE TITLE
Sound Issues - Audio file loops when its told to stop playing

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#2078]
On a SWf file I've got, if you load up the simulator and press S an announcement will start playing. 

If you press R it will reset the system and the sound file should stop playing / fade out like it does in flash. 

https://ridesims.com/sites/default/files/2019-04/TestTrack2_1.0_0.swf

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
(Note for readers: testing this requires an account on ridesims.com.)
