### ISSUE TITLE
Serious Santa Falls Through the Snow

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2083]
https://www.newgrounds.com/portal/view/291630/fomat/flash?emulate=flash

In Serious Santa, the player falls through hills of snow, instead of standing on them.

**Comment by Herschel** [comment]
I think this is another case of hitTest with a clip containing a mask (#1211).

**Comment by torokati44** [comment]
I can no longer reproduce this.
This too might have been fixed by #3353.
