### ISSUE TITLE
Christmas Run Santa Won't Follow the Mouse

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2084]
https://www.newgrounds.com/portal/view/283703/fomat/flash?emulate=flash

In Christmas Run on Ruffle, not a creature is stirring, not even a mouse... However in Flash player, Santa will lock to your mouse position and move around freely. In the Ruffle version he hangs out at the bottom of the screen and will pop to your mouse location for one frame when you click the mouse button, only to return to the bottom afterwards.

**Comment by Herschel** [comment]
`attachMovie` has an initObject parameter that changes `_width` and `_height`, but this is set before the first frame of the clip is constructed, so the clip has no children and ends up with 0 width and height. Need to set the initObject after the first frame is run (but also need to verify this is the same for clips with classes that might be constructed immediately).
