### ISSUE TITLE
can't find -lshcore with mingw64

### ISSUE THREAD

**Issue by gyorokpeter** [ruffle-rs/ruffle#2087]
It fails at this step:
```
  Compiling ruffle_desktop v0.1.0 (...)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  Running `rustc --crate-name ruffle_desktop --edition=2018 ...
```
...
```
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
```
...
```
  = note: D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lshcore
          collect2.exe: error: ld returned 1 exit status
```

And it looks like the mingw64 installation doesn't include this file, although I could find it in an older 32-bit version, obviously that wouldn't work as it's 32-bit.

**Comment by Herschel** [comment]
Looks like this is linked by tinyfiledialogs. I filed an issue about it here: https://github.com/jdm/tinyfiledialogs-rs/issues/28 Seems like the library stills compiles and functions if I remove the shcore lib from the `build.rs` in tinyfiledialog-rs.

Perhaps we could make this an optional feature and disable it when using the gnu toolchain.

**Comment by n0samu** [comment]
Looks like this was fixed a long time ago by https://github.com/jdm/tinyfiledialogs-rs/pull/33. Please leave a comment if this is still broken and I can reopen the issue.
