### ISSUE TITLE
Chrome fresh installation - Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by prburger** [ruffle-rs/ruffle#2090]
Hi Guys,

I run Chrome 87.0.4280.88 (Official Build) (64-bit) on Win10. I downloaded your extension for Chrome, unpacked it into a local folder and ran Load Unpacked from the chrome://extensions. I went to a website that uses Flash audio filles. But I heard no sound. I found the following error in my extension tab

<code>
(()=>{var e={495:e=>{e.exports={get_i18n_string:function(e){return chrome&&chrome.i18n&&chrome.i18n.getMessage?chrome.i18n.getMessage(e):browser&&browser.i18n&&browser.i18n.getMessage?browser.i18n.getMessage(e):void console.error("Can't get i18n message: "+e)},set_sync_storage:function(e){chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.set?chrome.storage.sync.set(e):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.set?browser.storage.sync.set(e):console.error("Can't set settings.")},get_sync_storage:function(e,r){let o;o="string"==typeof e?[e]:Array.isArray(e)?e:Object.keys(e);let s=e=>{for(const r of o)void 0===e[r]&&(e[r]=t[r]);return r(e)};chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.get?chrome.storage.sync.get(e,s):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.get?browser.storage.sync.get(e,s):console.error("Couldn't read setting: "+e)},reload_tab:function(e,t){chrome&&chrome.tabs&&chrome.tabs.reload?chrome.tabs.reload(e,t):browser&&browser.tabs&&browser.tabs.reload?browser.tabs.reload(e,t):console.error("Couldn't reload tab.")},dict_equality:function(e,t){let r=!0;for(var o in e)Object.prototype.hasOwnProperty.call(e,o)&&(r=r&&e[o]===t[o]);for(let o in t)Object.prototype.hasOwnProperty.call(t,o)&&(r=r&&e[o]===t[o]);return r},tab_query:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.query?browser.tabs.query.apply(this,arguments):new Promise((function(t){let r=Array.prototype.slice.call(e);r.push(t),chrome.tabs.query.apply(this,r)}))},tab_sendmessage:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.sendMessage?browser.tabs.sendMessage.apply(this,arguments):new Promise((function(t,r){let o=Array.prototype.slice.call(e);o.push((function(e){void 0!==chrome.runtime.lastError&&r(chrome.runtime.lastError.message),t(e)})),chrome.tabs.sendMessage.apply(this,o)}))},add_storage_change_listener:function(e){chrome&&chrome.storage&&chrome.storage.onChanged&&chrome.storage.onChanged.addListener?chrome.storage.onChanged.addListener(e):browser&&browser.storage&&browser.storage.onChanged&&browser.storage.onChanged.addListener?browser.storage.onChanged.addListener(e):console.error("Couldn't add setting change listener")},open_settings_page:function(){chrome&&chrome.tabs&&chrome.tabs.create?chrome.tabs.create({url:"/settings.htm"}):browser&&browser.runtime&&browser.runtime.openOptionsPage?browser.runtime.openOptionsPage():console.error("Can't open settings page")},set_message_listener:function(e){chrome&&chrome.runtime&&chrome.runtime.onMessage&&chrome.runtime.onMessage.addListener?chrome.runtime.onMessage.addListener(e):browser&&browser.runtime&&browser.runtime.onMessage&&browser.runtime.onMessage.addListener?browser.runtime.onMessage.addListener(e):console.error("Couldn't add message listener")},get_extension_url:function(){return chrome&&chrome.extension&&chrome.extension.getURL?chrome.extension.getURL("dist/ruffle.js").replace("dist/ruffle.js",""):browser&&browser.runtime&&browser.runtime.getURL?browser.runtime.getURL("dist/ruffle.js").replace("dist/ruffle.js",""):void console.error("Couldn't get extension URL")}};const t={ruffle_enable:!0,ignore_output:!1}}},t={};function r(o){if(t[o])return t[o].exports;var s=t[o]={exports:{}};return e[o](s,s.exports,r),s.exports}(()=>{const{get_i18n_string:e,set_sync_storage:t,get_sync_storage:o,add_storage_change_listener:s,reload_tab:n,dict_equality:a,tab_query:i,tab_sendmessage:c,open_settings_page:g}=r(495);let d,l,u={},b={};function m(){let e=!a(u,b);void 0!==d&&(d.disabled=!e)}function h(r){let n=r.name;r.nextSibling.textContent=e("settings_"+n),o(n,(function(e){r.checked=e[n],u[n]=e[n],m()})),s((function(e){Object.prototype.hasOwnProperty.call(e,n)&&(r.checked=e[n].newValue,u[n]=e[n].newValue,m())})),r.addEventListener("click",(function(){let e={};e[n]=r.checked,u[n]=e[n],m(),t(e)}))}async function _(){let t=document.getElementById("ruffle_status");t.textContent=e("status_init");let r=null;try{if(r=await i({currentWindow:!0,active:!0}),r.length<1)return void(t.textContent=e("status_no_tabs"));r.length>1&&console.warn("Got "+r.length+" tabs in response to active tab query")}catch(r){throw t.textContent=e("status_tabs_error"),r}try{l=r[0],t.textContent=e("status_message_init");let o=await c(l.id,{action:"get_page_options"});b=o.tab_settings,m(),void 0!==o&&o.loaded?t.textContent=e("status_result_running"):void 0===o||o.loaded?t.textContent=e("status_result_error"):b.ruffle_enable?t.textContent=e("status_result_optout"):t.textContent=e("status_result_disabled")}catch(r){throw t.textContent=e("status_result_protected"),d&&(d.disabled=!0),r}}document.addEventListener("DOMContentLoaded",(function(){var t,r=document.getElementById("settingsbutton");h(document.getElementById("ruffle_enable")),h(document.getElementById("ignore_optout")),(t=document.getElementById("reload")).textContent=e("action_"+t.id),t.disabled=!0,t.addEventListener("click",(function(){n(l.id,(function(){window.setInterval(_,1e3)}))})),d=t,r.innerHTML=e("open_settings_page"),r.onclick=g,_()}))})()})();
</code>
<p>
<br>
Can I do something to resolve this error?
</p>
<p>
Cheers, Paul
</p>

**Comment by runeka** [comment]
I get the same errormessage when trying to run the management interface on a videoencoder.

**Comment by SebastianBraun01** [comment]
I have tried many different sites with flash content and I get this same error every time and I get only a black screen with no sound.

**Comment by n0samu** [comment]
Not enough information is provided to diagnose any of the issues raised here. Please open a new issue and provide a link/attachment to the Flash content where the problem is occurring.
