### ISSUE TITLE
Unable to load extension on Chrome OS - Not Unpackable

### ISSUE THREAD

**Issue by ibuddy66** [ruffle-rs/ruffle#2094]
Nightly builds are not able to be unpacked on Chrome OS to install extensions in developer mode.  It will not give you an install file.   Zip opens to only display full contents without the proper Chrome OS install file included.  Doesn't matter if you copy and paste contents to new folder on system.  Will not work or be installed.  Load Unpacked will not find anything able to be installed.  

![Screenshot 2020-12-25 at 6 27 53 PM](https://user-images.githubusercontent.com/36145958/103143146-20fc7780-46df-11eb-8bc3-496b4ddd57d6.png)
Doe

**Comment by Poopooracoocoo** [comment]
Did you go to chrome://extensions and click on 'load unpacked extension' and then selected that folder in your downloads folder? I'm not sure how different Chrome OS is, but I imagine that it's similar :)

**Comment by ibuddy66** [comment]
installing it on Chrome OS with the files provided does not work because
Chrome OS does not have an unpacker per se like windows and Mac does.  It's
very different and simply just opens the folder and doesn't truly unpack it
to locate the install file.  It doesn't provide a .crx install file for the
extension anywhere and there's no way to load the unpacked file into the
extensions chrome section in developer mode because the file isn't properly
packed for Chrome OS to begin with. It is quite a big issue as many
educational institutions and other such places rely on Chrome OS and flash.
Instead of it just providing the install file for the extension, the
nightly release is just giving tons of regular files with no install file
overall.

**Comment by ibuddy66** [comment]
It just worked.  The issue was with the December 25th release, but today the 27th release worked perfectly as planned.  Not sure why but it seems to reject the December 25th one pretty consistently.  Thanks again.  I'll close out the issue.  :)

**Comment by Poopooracoocoo** [comment]
Did you get a .crx install file? I'm a bit confused.
