### ISSUE TITLE
Trying to play autobot stronghold

### ISSUE THREAD

**Issue by marcio-silva-franca** [ruffle-rs/ruffle#2095]
This is the file you asked me.

**Comment by Poopooracoocoo** [comment]
https://www.newgrounds.com/portal/view/498895?emulate=flash

It's AS3. That warning dialog came in handy!

**Comment by Toad06** [comment]
Thanks for the report.

As previously mentioned, this game uses AS3 which is still a work in progress. I'm closing this in favor of #1368.
