### ISSUE TITLE
Audio and animation mismatch

### ISSUE THREAD

**Issue by akimikimikimikimikimikimika** [ruffle-rs/ruffle#2099]
I was playing https://archive.org/details/flash_Caramelldansen in Safari, the lyrics and the audio did not match in some condition.

This always occurred in these steps:
* Play the Flash animation (it works correctly)
* Switch to other apps, or tabs
* Switch back to the browser or the tab

The animation seemed to stop or become slow in background.  
Same problem happened in other browsers (Chrome, Edge, Firefox). 
I downloaded the .swf file and played it with Flash Plugin in Chromium browsers (Chrome, Edge), the problem did not happen.

**Comment by akimikimikimikimikimikimika** [comment]
* macOS: 11.1
* Safari: 14.0.2
* Chrome: 87.0.4280.88
* Edge: 87.0.664.66
* Firefox: 84.0.1

**Comment by Poopooracoocoo** [comment]
Is this the same as #347?

**Comment by Herschel** [comment]
Thanks for the report, closing in favor of #347.
