### ISSUE TITLE
Ruffle menu doesn't appear on iPadOS

### ISSUE THREAD

**Issue by aswiseman** [ruffle-rs/ruffle#2114]
This was mentioned as part of another issue, but I'm not sure it's got its own ticket...

The Ruffle menu that currently allows viewing full-screen and shows the current build number is available by right-clicking on a desktop/laptop or by a long hold on Android. 

However, there appears no way to summon this menu on an iPad (and I presume this is the same for iPhones).

Is there a way to enable a long hold for iPadOS (and iOS as necessary) or some other mechanism of enabling the menu for Apple's tablets and phones?

**Comment by Poopooracoocoo** [comment]
also see: https://github.com/ruffle-rs/ruffle/issues/1972#issuecomment-744457227

**Comment by Herschel** [comment]
Going to merge with #1972, thank you!
