### ISSUE TITLE
Ruffle Error on http://henweekend.ellieharrison.com/jeanie/diann.html

### ISSUE THREAD

**Issue by eharrison79** [ruffle-rs/ruffle#2115]
# Error Info
Error name: TypeError
Error message: NetworkError when attempting to fetch resource.

# Player Info
Allows script access: false

# Page Info
Page URL: http://henweekend.ellieharrison.com/jeanie/diann.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-27
Channel: nightly
Built: 2020-12-27T00:42:03.499Z
Commit: c3811b30f5bf27e1c33939e76f0c4b01ff93c1ef

**Comment by Herschel** [comment]
Same CORS issues as #2112 , closing in favor of that issue.
