### ISSUE TITLE
Shadow effects missing in Ruffle Wasm emulator

### ISSUE THREAD

**Issue by aswiseman** [ruffle-rs/ruffle#2118]
I have some Flash-based clocks. On some of them, the shadows under the hands are missing when using the WebAssembly emulator.

Examples:
Flash original - https://625.uk.com/tv_logos/flash/granada_clouds_clock.asp
Ruffle version - https://625.uk.com/tv_logos/flash/granada_clouds_clock.asp?wasm=1

Flash original - https://625.uk.com/tv_logos/flash/stv_bw_clock.asp
Ruffle version - https://625.uk.com/tv_logos/flash/stv_bw_clock.asp?wasm=1

This seems to be true across devices and OSes

Shadows are working fine in other files, for example:
Flash original - https://625.uk.com/tv_logos/flash/rediffusion_clock.asp
Ruffle version - https://625.uk.com/tv_logos/flash/rediffusion_clock.asp?wasm=1

If it helps, files with missing shadows all seem to have
`Init Action sprite ID`
lines showing in the browser Console output.

**Comment by Herschel** [comment]
Filter effects re not implemented yet; closing in favor of #15.
