### ISSUE TITLE
Ruffle doesn't respond to spacebar in some Flash files - onKeyUp is not callable?

### ISSUE THREAD

**Issue by aswiseman** [ruffle-rs/ruffle#2120]
I have some Flash files which you can interact with by clicking on the animation and then pressing the space bar.

Sometimes this works in Ruffle and other times it doesn't.

Example that works
(Flash) https://625.uk.com/tv_logos/flash/tcf_2.asp
(Ruffle) https://625.uk.com/tv_logos/flash/tcf_2.asp?wasm=1

Here, clicking on the image and then pressing space causes a digit to countdown from 9 to 0 on screen. This works fine on Windows 10 in Firefox. (Doesn't seem to be a way of getting it to work on Android or iOS, but that's another issue!)

Example that doesn't work
(Flash) https://625.uk.com/tv_logos/flash/ou_clock.asp
(Ruffle) https://625.uk.com/tv_logos/flash/ou_clock.asp?wasm=1

Here, clicking on the image and hitting space bar adds a "Follows shortly" caption on screen. But in Ruffle, nothing happens.

Here, the Console says:
`Object method onKeyUp is not callable`

This also Flash File also shows "Init Action sprite ID" lines in the Console.

**Comment by Herschel** [comment]
`onKeyDown` is fired twice, turning the clip visible and then back invisible immediately.
