### ISSUE TITLE
Editable text not editable on mobile and text is invisible on Android

### ISSUE THREAD

**Issue by aswiseman** [ruffle-rs/ruffle#2121]
For this Flash file...

(Flash) https://625.uk.com/tv_logos/flash/itv_schools_clock_79.asp
(Ruffle) https://625.uk.com/tv_logos/flash/itv_schools_clock_79.asp?wasm=1

In Flash, it's possible to click on the text at the bottom of the screen and edit it, using cursor keys, Home, End, Backspace, select etc. The text cursor is the same colour as the text.

In Ruffle, it's still possible to edit the text (at least on a Windows 10 desktop running Firefox), although the text cursor is black and editing keys (aside from Backspace) don't work, so the experience isn't as good. (And the Console shows Ruffle getting focus.)

Editing text doesn't work on my iPad or my Android phone, which is a shame - hopefully one day this can be implemented.

But the issue I'm most concerned about is that on my Android phone (Google Pixel 3a running Android 11), the caption text doesn't appear on the screen at all.

**Comment by Herschel** [comment]
Closing in favor of #1532 and #900.
