### ISSUE TITLE
Portal Defenders - Bomb toss causes Ruffle Panic

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2131]
https://www.newgrounds.com/portal/view/484931/format/flash?emulate=flash

Start a new game of Portal Defenders. Press D to throw a bomb. When the bomb explodes, Ruffle panics with this error:

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
    at Object.X (https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.bbb40c85e6191179c48b.js:1:20832)
    at __wbg_new_df6e6ab7a65c4c4d (https://uploads.ungrounded.net/ruffle_wrapper/lib/ruffle.js?1609160124:1:37870)
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[1313]:0x253c0b
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[1480]:0x271881
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[4019]:0x333f07
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[3134]:0x3121d4
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[4329]:0x338f35
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[4359]:0x339498
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[4231]:0x337a4c
    at https://uploads.ungrounded.net/ruffle_wrapper/lib/587e6d0a42036d642c1e.module.wasm:wasm-function[4360]:0x3394ce
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1609160124%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F484000%2F484931_peeps.swf%3F1509024282%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2233466112.59f9778d3e9ef5efcd7b4889868e6a75a8499156a7a5eb%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%225fe9e3dfddc91%22%2C%22NewgroundsAPI_SessionID%22%3A%22RZD6qwPvCuGhh8GY9Fbc356a192b7913b04c54574d18c28d46e6395428abWJd0%22%2C%22NewgroundsAPI_UserName%22%3A%22TomFulp%22%2C%22NewgroundsAPI_UserID%22%3A1%2C%22ng_username%22%3A%22TomFulp%22%7D%2C%22width%22%3A640%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F484000%2Fflash_484931.gif%3Ff1275530805%22%7D
SWF URL: https://uploads.ungrounded.net/484000/484931_peeps.swf?1509024282

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-28
Channel: nightly
Built: 2020-12-28T00:42:22.474Z
Commit: 8d707bc6ab747ae5039ce629f07c09aabfac2553

**Comment by Herschel** [comment]
Fixed by #2228
