### ISSUE TITLE
bgcolor parameter not working for single SWF file?

### ISSUE THREAD

**Issue by aswiseman** [ruffle-rs/ruffle#2135]
I have a single SWF which I can show with a blue background or a black one by passing in a different BGCOLOR parameter. But in Ruffle, it only ever shows as black...

Here's the Flash file with the blue background
https://625.uk.com/tv_logos/flash/bbc2_stripes_blue.asp

Here's the same file rendered using Ruffle's WASM, but it shows with a black background
https://625.uk.com/tv_logos/flash/bbc2_stripes_blue.asp?wasm=1

The background is set by this in the OBJECT
`<param name="bgcolor" value="#0000ff">`
and by this in the EMBED
`bgcolor="#0000ff"`

This looks similar to https://github.com/ruffle-rs/ruffle/issues/2133, but there, there's an inner SWF overriding the colour for an outer SWF. Here, there is only a single SWF file.

**Comment by ousia** [comment]
Analyzing your SWF file, it contains:

```
[045]         4 FILEATTRIBUTES
[009]         3 SETBACKGROUNDCOLOR (00/00/00)
```

I didn’t know that parameters could override `SetBackgroundColor` from SWF file.

**Comment by Herschel** [comment]
The HTML embeds could specify their own bgcolor, which would override the SWF bgcolor (as well as the bgcolor prior to loading), so our polyfill code should respect this.
On desktop, we could provide an option to override the SWF bg color.

**Comment by Herschel** [comment]
Here's a page on Internet Archive where bgcolor is used to adjust the background on different pages:
https://discord.com/channels/610531541889581066/722872096002408529/793258625157169254
(Posted in Discord)

**Comment by ousia** [comment]
@aswiseman & @Herschel, many thanks for your information and explanations.

I didn’t know that Flash allowed to ignore the background color set in the SWF file.
