### ISSUE TITLE
Ruffle Desktop not loading any .swf file at all

### ISSUE THREAD

**Issue by canttinkoanam** [ruffle-rs/ruffle#2138]
Every .swf file I try to load with the desktop client just ends in an error:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `-2005270523`,
right: `0`: error on command list creation: 887a0005', C:\Users\runneradmin\.cargo\git\checkouts\gfx-e86e7f3ebdbc4218\0244e34\src\backend\dx12\src\pool.rs:50:17
```
What I think is happening is that it's trying to create something in a directory that doesn't exist (I don't have a user called runneradmin, so C:\Users\runneradmin doesn't exist). I'm not a coder, so I don't really know, but it seems like that is what is trying to do.
My OS is Windows 10 build 2004 and the desktop client version is Ruffle 0.1.0-nightly (8d707bc6 2020-12-27). I could only test this on Windows, but if I can, I'll post what happens with the Linux desktop client, although I think this issue is specific to the Windows version. Also, attached down below is a zip file containing all three .swf files I tested. They all fully work with Ruffle, so the issue has to be with the desktop client.

[Tested SWFs.zip](https://github.com/ruffle-rs/ruffle/files/5748417/Tested.SWFs.zip)

**Comment by parkerlreed** [comment]
That path is just referring to a file on the system that compiled the program. It's just to let them know what file is throwing the error.

Since it mentions DX12, try using another rendering backend

**Comment by canttinkoanam** [comment]
Thanks! As I said, I'm not a coder, so I don't understand this stuff very well.

**Comment by parkerlreed** [comment]
So did that fix it? Might want to leave it open if it's a new DX12 issue.

**Comment by canttinkoanam** [comment]
Yes, switching to another graphics backend worked.
