### ISSUE TITLE
Layering issue

### ISSUE THREAD

**Issue by littleguystar** [ruffle-rs/ruffle#2144]
Seems to constantly improperly layer
Example: 
![unknown 1](https://user-images.githubusercontent.com/76085046/103244627-78365e00-4912-11eb-9a24-8c5300511299.png)

**Comment by Herschel** [comment]
Could you post the SWF you are testing with? Thank you!

**Comment by littleguystar** [comment]
> Could you post the SWF you are testing with? Thank you!


[https://cdn.discordapp.com/attachments/722866209682620521/794323876338597928/772648_echidna-ruins.swf](url)
Hope this works

**Comment by littleguystar** [comment]
> Could you post the SWF you are testing with? Thank you!

[https:\/\/uploads.ungrounded.net\/443000\/443187_FFSX6_Part_2.swf?f1212882468](url)
