### ISSUE TITLE
Incomplete flash file

### ISSUE THREAD

**Issue by mataucarre** [ruffle-rs/ruffle#2145]
Hello,

Can I tell me why the file is not completely readable?
[https://www.mataucarre.fr/ecligne/meca/01_modelisation/1_les_contacts/02.php](https://www.mataucarre.fr/ecligne/meca/01_modelisation/1_les_contacts/02.php)

The flash file is not usable, normally we should find this image:

![Capture d’écran du 2020-12-29 02-12-17](https://user-images.githubusercontent.com/4775064/103252073-8e2c3900-497b-11eb-8eb7-a8b32c95089b.png)

But with Ruffle:

![Capture d’écran du 2020-12-29 02-12-43](https://user-images.githubusercontent.com/4775064/103252104-9e441880-497b-11eb-86ea-dbdef80aa41b.png)

**Comment by Herschel** [comment]
The image is actually an embedded video, which Ruffle does not yet support (#723).

**Comment by mataucarre** [comment]
I'm sorry, but I don't  understand.
It is a swf file, not a video. The user can interact with this swf file but we cannot interact with a video...

swf link: https://mataucarre.fr/ecligne/meca/01_modelisation/1_les_contacts/contact_exo.swf

Sorry if my answer seems incorrect

**Comment by Herschel** [comment]
The video is contained inside the SWF file. The video is the top left image that is missing inside Ruffle, because Ruffle currently does not support video inside SWF files. Hope this explains the problem.

**Comment by kmeisthax** [comment]
I have a branch with a video decoder for H.263 in it: https://github.com/kmeisthax/ruffle/tree/video-h263

It's currently not in upstream Ruffle because the video decoder still has a few bugs and it's very not well optimized at all. If this is a static video it should work; if the movie expects to be able to interact with it via ActionScript it won't (yet).

**Comment by Herschel** [comment]
The video is a static DefineVideoStream so could be a useful test case (not sure which codec ID).

**Comment by kmeisthax** [comment]
I have tested and can confirm that the H.263 decoder will work here

**Comment by relrelb** [comment]
This works now, thanks to #2173.
