### ISSUE TITLE
Several Issues Relating to Mouse Operations

### ISSUE THREAD

**Issue by UnknownOriginal** [ruffle-rs/ruffle#2146]
Just want to say, "WAY TO GO RUFFLE!!!"

Most all of my .swf files work online now, but I have run across issues where some do not work as expected, or simply don't function at all.  One in particular is "disc-golf".  The file works completely when played as a stand-alone, but will not work as expected online in a webpage.  For those not familiar, the user clicks and holds the left mouse button and adjusts the flight path and the strength.  THEN, when the user lets go of the left mouse button. the disc is released and flies in the direction it was aimed at.  HOWEVER, online usage when the user unclicks the left mouse button, the disc just falls to the ground INSTEAD of flying and makes the game unplayable.  Hope this describes an issue with the mouse operations???  I've included the file for those that can resolve this issue.  Please let me know when this is fixed!  Thanks!
[disc-golf.zip](https://github.com/ruffle-rs/ruffle/files/5749885/disc-golf.zip)

**Comment by Toad06** [comment]
When the disc is clicked and the mouse is still on the disc when the button is released, then Flash Player triggers a "release" event. In this case, the disc doesn't move.
When the disc is clicked and the mouse is no longer on the disc when the button is released, then Flash Player triggers a "releaseOutside" event. In this case, the disc moves in the appropriate direction.

Ruffle doesn't respect this and always triggers the "release" event, so the disc never moves.

This can be verified by adding `trace(which);` in `\DefineSprite (170)\frame 1\DoAction`.

**Comment by UnknownOriginal** [comment]
Thanks for the feedback Toad06!

So is this "fixable"?

**Comment by UnknownOriginal** [comment]
Still awaiting an answer on what can be done to repair this issue.

Thanks!

**Comment by UnknownOriginal** [comment]
BUMP...

**Comment by UnknownOriginal** [comment]
BUMP...

**Comment by UnknownOriginal** [comment]
BUMP...

**Comment by Herschel** [comment]
@UnknownOriginal Please don't spam the topics, thank you! It's fixable; the various button events such as `releaseOutside` need to be implemented.

**Comment by UnknownOriginal** [comment]
And this will be fixed WHEN???

**Comment by sombraguerrero** [comment]
Tagging this defect for the sake of my own tracking on behalf of Onda Educa.

**Comment by UnknownOriginal** [comment]
"It's fixable; the various button events such as releaseOutside need to be implemented."

SO WHEN THE HELL WILL THIS EVER BE IMPLEMENTED??????????

**Comment by Herschel** [comment]
Fixed by #4584.

@UnknownOriginal Please be respectful of developers and abide by the [Code of Conduct](https://github.com/ruffle-rs/ruffle/blob/master/CODE_OF_CONDUCT.md).  Thank you!
