### ISSUE TITLE
N (Pre-v2.0) - Slopes are intangible and have unpredictable side effects

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#2160]
[n.zip](https://github.com/ruffle-rs/ruffle/files/5752721/n.zip)

When falling through a sloped surface, one of several things may happen:

- You will die upon touching a non-sloped surface.
- You will be transported behind the level and fall indefinitely off-screen.
- You will gain momentum at a rapid pace.
- Nothing happens.

Tested on Ruffle Desktop.

**Comment by adrian17** [comment]
Looks like the reason is here:

```
return Test_PointTile[_loc1_.CTYPE](x,y,_loc1_);
```

`_loc1_CTYPE` is a number, but `CallMethod` action only accepts strings (and null/undefined). I'm guessing a string-coercion is missing.
