### ISSUE TITLE
Art-Games saved (sort-of) with Ruffles! Thank you to all (mostly!). ISSUES......

### ISSUE THREAD

**Issue by dpoetry** [ruffle-rs/ruffle#2161]
I'm an art-game maker and digital poet (yes that is a thing).  And I've been testing Ruffles on a few of my older art-games. 

There are some issues with loading FLV files and loading SWF files on top of the original SWF file (each level has a video "prize")

But I thought I would share the results of my tests to date:

Title:  game, game, game and again game. 
URL: http://www.dpoetry.com/ruffletest/gamegame/
Results:  The sounds, interaction and other bits work great.  The loadMovie for Swf files with Videos in them....don't work so well......although oddly the sounds of the videos work....just not the video. 

Title:  Evidence of Everything Exploding
URL: http://www.dpoetry.com/ruffletest/explode/everything.html
Results:  Again everything works great!  Thanks!  The only major issue are the video clips between the levels. Those do not load. 

Title: Nothing you have done deserves such praise
URL:  http://www.dpoetry.com/ruffletest/nothing/nothing44.html
Results:  Most everything works.  The oddest issue is that some of the text comes up as giant and the background colour then changes for parts of the game.  There are lots of small, minor issues like that. But the damn thing works!

I'll test more bits and load the results later!

cheers, Jason Nelson

**Comment by n0samu** [comment]
Video playback is working in *game, game, game and again game* thanks to VP6 video support added in #5369.

Strangely, I cannot get the videos to work in *Evidence of Everything Exploding* even in the real Adobe Flash Player. It seems like the button that would start video playback doesn't actually have any script attached to it. Any idea what's going on here?

I'm not noticing any text sizing issues in *Nothing you have done deserves such praise*, can you confirm that issue is fixed?

**Comment by n0samu** [comment]
@dpoetry I'm closing this issue since all fixable problems seem to be addressed. Please let us know if we can help with anything else - I'd be glad to test the interstitial videos in your game if you put up a version that works in Flash Player.

**Comment by n0samu** [comment]
Okay, I found that the videos are working in the main copy of the game located here: http://www.secrettechnology.com/explode/evidence.html

And the videos seem to be working fine in the latest version of Ruffle, too! 🎉
