### ISSUE TITLE
Handling direct links to swf files (extension)

### ISSUE THREAD

**Issue by Couchy** [ruffle-rs/ruffle#2167]
If I open a link to a swf file in a new tab, is it possible to play it instead of downloading, which is what the browser does by default?

**Comment by parkerlreed** [comment]
Spitballing here

Somehow use the downloads manifest to intercept and display the swf on a bundled html page

https://developer.chrome.com/docs/extensions/reference/downloads/

If I knew more about extensions, I would try to take a stab at it.

**Comment by evilpie** [comment]
The simplest option is probably to redirect to an extension page that just embeds the SWF. Our Livemarks extension does something similar for previewing RSS feeds: https://github.com/nt1m/livemarks/blob/master/background/background.js#L440

**Comment by Couchy** [comment]
> The simplest option is probably to redirect to an extension page that just embeds the SWF. Our Livemarks extension does something similar for previewing RSS feeds: https://github.com/nt1m/livemarks/blob/master/background/background.js#L440

I tried a quick hack to do exactly this, and it's half working, however, it suffers greatly from the CORS issue I raised here in that unless the server the swf is on explicitly sets a header to allow it to be embeded anywhere, Chrome will refuse to fetch it from the extension page.

#1008

**Comment by Couchy** [comment]
[ruffle_nightly_2020_12_28_WEBREQUEST.zip](https://github.com/ruffle-rs/ruffle/files/5762011/ruffle_nightly_2020_12_28_WEBREQUEST.zip)

So I got this working reasonably well on /f/ and swfchan by using webRequest in a background script. Direct links to swfs open in a minimal extension page (player.html), and it also fixes the embedding CORS problem in #1008. I was too lazy to set up the Ruffle repo and make an official patch, so please feel free to borrow from this and clean up as you see fit.

- background.js
- player.html
- player.js
- Some modifications to manifest.json to accommodate the above

**Comment by caydenpri44** [comment]
Your reopening the .swf file in a new tab from the source code which will cause the file to download.
Either that or the .swf file is not supported and crashed which lead to a download.
Or the Ruffle emulator might have not supported the file.
Could be the emulator just deosn't like you.
FILLER

**Comment by relrelb** [comment]
I've made a working prototype in my fork: https://github.com/relrelb/ruffle/tree/direct_swf.
Since it's based upon #3426, I'll open a PR once it gets merged.
Also, it currently relies on Manifest V3 features (i.e. `declarativeNetReuqest`), so it doesn't work on Firefox which supports only MV2 by now. I need to re-implement it in MV2 API (should be even easier with the more powerful `webRequest` API), and keep the MV3 implementation to when we'll perform the actual migration.
