### ISSUE TITLE
Ruffle Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by sonicnod** [ruffle-rs/ruffle#2169]
# Error Info
Error: Error loading movie: Invalid data: Invalid SWF

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-30
Channel: nightly
Built: 2020-12-30T00:36:39.747Z
Commit: 5b5d9810c9acb67ba6f869a81642e9ab64725509

**Comment by Herschel** [comment]
Seems like you tried to load something that wasn't an SWF file?

**Comment by Poopooracoocoo** [comment]
These two issues can be closed now, right? Neither of the author have provided more details.

**Comment by sonicnod** [comment]
Oh sorry. Yes I tried to load the actual page that linked to the swf.
Thanks for the help.



Don Friesen
*1and4studio.com* <http://1and4studio.com>
646.707.9237
