### ISSUE TITLE
Ruffle Error on https://e621.net/posts/789222?q=w0lfb0ne

### ISSUE THREAD

**Issue by secretbearaccount** [ruffle-rs/ruffle#2170]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:64232
    at Array.forEach (<anonymous>)
    at Object.hi.f.wasm (<anonymous>:3:63840)
    at <anonymous>:3:32398
    at Array.reduce (<anonymous>)
    at Function.hi.e (<anonymous>:3:32375)
    at i (<anonymous>:3:5393)
    at i.next (<anonymous>)
    at <anonymous>:3:5693
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/789222?q=w0lfb0ne

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by GreenReaper** [comment]
This one, like most on e621.net, will need the NSFW tag. 😅

It loads on Windows desktop with a nightly, but the left side and probably right side appears clipped.

**Comment by Herschel** [comment]
Closing in favor of #2201.
