### ISSUE TITLE
Bug report: Click Jogos site

### ISSUE THREAD

**Issue by AnaBlue00** [ruffle-rs/ruffle#2178]
Hello, 
First of all, I would like to congratulate you all on your initiative to keep Flash and try to recover games that will be damaged due to the removal of this extension. I came by this email to report a bug that happened when I entered a brazilian website of games called Click Joos, wich is looking for ways to keep games active and applied Ruffle extension as a try. I tried to play the game (the name of the game is Pack the house - Level 4 - Frenzy kitchen, if this is relevant) and it has not been reproduced. Instead, a screen appeared with the message that something went wrong and that it was not supposed to happen. The function of view error details said the following:
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/0/06cb453ce3748b7036b28ee4d1694a5b/src.swf
Param movie: https://img.clickjogos.com.br/dl/0/06cb453ce3748b7036b28ee4d1694a5b/src.swf
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/jogos/pack-the-house-level-4-frenzy-kitchen

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

I would be very grateful if you could take action on this so that we can maintain our nostalgia. And I apologize if this error occurred due to my computer system and if that is the case, I would appreciate if you let me know what I could do to make it work. 
I'm sorry again for bothering you and thanking you for your work, it really means a lot to me and I'm sure I'm not the only one. 
Have a nice day,
Ana.

**Comment by ousia** [comment]
@AnaBlue00, it seems that https://www.clickjogos.com.br/ hasn’t the server properly configured for _Ruffle_ (as explained in https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type).

**Comment by Toad06** [comment]
Thanks for the report. This was an issue on Clickjogos's end - now fixed.
