### ISSUE TITLE
Prizma Puzzle Challenges always shows score of 99999

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#2181]
SWF URL: http://i.notdoppler.com/files/prizmapuzzlechallenges.swf

The level select screen always shows a score of 99999 for each level, regardless of whether the level has been played or not.
Below is an image showing the incorrect behavior.
![image](https://user-images.githubusercontent.com/71368227/103400002-2ad01180-4b09-11eb-8e9a-d33184583705.png)

To see this behavior, load the game and click "Start Game," then mouse over Level 1.

**Comment by Toad06** [comment]
These texts are defined in:
`DefineEditText (474)` (default value: "99999",  variable name: `rec`)
`DefineEditText (476)` (default value: "/99999", variable name: `maxrec`)

These values are then changed in `\DefineSprite (631)\frame 3\DoAction`.
For instance, `z.maxrec = "/" + _root.lvlmax[i];` correctly traces "/100" in Flash and Ruffle. But for some reason, the text is not updated in Ruffle.

**Comment by Herschel** [comment]
I suspect this is related to the text being inside the mouseover state for the button.

**Comment by sombraguerrero** [comment]
There appears to be a variant of this behavior in an old Nick Jr. classic I found. When decompiled in JPEXS, I find the following code under the raw edit of DefineEditText(342) and (365) as the main examples:
`variableName: String = mcMJ.vScore
initalText: String = 9999`

In this game's case, the invocation of the variable in question happens in methods that are Pushed in the P-code source.
[tuga.zip](https://github.com/ruffle-rs/ruffle/files/6001835/tuga.zip)

**Comment by sombraguerrero** [comment]
Upon further inspection, it does seem that the underlying variable is being set _after_ the text element, so perhaps what this is, is an additional scenario that needs to be covered by

https://github.com/ruffle-rs/ruffle/blob/master/core/src/display_object/edit_text.rs#L940

**Comment by sombraguerrero** [comment]
The only other AVM related errors I could find from my game were
[2021-02-27T04:47:04Z WARN  ruffle_core::avm1::object] Object method setFrame is not callable -- in [Actions Parent] / [Frame]
[2021-02-27T04:47:04Z WARN  ruffle_core::avm1::object] Object method setFrame is not callable -- in [Actions Parent] / [Frame]
