### ISSUE TITLE
Ruffle Error on https://www.newgrounds.com/portal/view/533001

### ISSUE THREAD

**Issue by AwakeSoda** [ruffle-rs/ruffle#2185]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:157:18
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Failed to fetch
TypeError: Failed to fetch)', web/src/navigator.rs:157:18
    at Object.z (chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/core.ruffle.js:1:20865)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:37606)
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1324]:0x254c8e
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1491]:0x272a47
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4066]:0x338300
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3161]:0x315621
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4375]:0x33d2f1
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4405]:0x33d854
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4277]:0x33be08
    at chrome-extension://fekekjplfobbbpoehblabmmpehalogge/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4406]:0x33d88a
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://uploads.ungrounded.net/533000/533001_PrisonNG.swf?123
Param wmode: direct
Param allowscriptaccess: never
Param allowfullscreen: true
Param allowfullscreeninteractive: true
Param flashvars: NewgroundsAPI_PublisherID=1&NewgroundsAPI_SandboxID=5fedd4550d1b3&NewgroundsAPI_SessionID=&NewgroundsAPI_UserName=&lt;deleted&gt;&NewgroundsAPI_UserID=0&ng_username=&lt;deleted&gt;
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.newgrounds.com/portal/view/533001
SWF URL: https://uploads.ungrounded.net/533000/533001_PrisonNG.swf?123

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Poopooracoocoo** [comment]
@AwakeSoda Still seeing this error?

**Comment by bottle2** [comment]
I'm not sure if that's the problem reported here, but when choosing Drill and then Crowbar in Escaping the Prison, the sound that plays for the arrows in the run scene won't stop playing and accumulate as you try more and more again. Keeping the browser console open reports no error during this part of the game. Right clicking on the game says "About Ruffle (nightly 2021-07-28)". Apart from that, everything looking fantastic!

User agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36`

**Comment by AwakeSoda** [comment]
@bottle2 This was made back when it crashed all the time with ruffle

**Comment by Poopooracoocoo** [comment]
@AwakeSoda um lmk if you want to close this.

**Comment by bottle2** [comment]
Oh ok, then I shall open a separate issue to report the bug I experienced!

**Comment by n0samu** [comment]
I've created a new issue #8067 for the sound problem. Closing this issue since the panic seems to be fixed.
