### ISSUE TITLE
Text Fields Height Issues - Information being cut short 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#2186]
Text fields look like there being cut short, I dunno if the height isn't being set somewhere or if its being overridden? 

In flash you can see all of the data. 

<img width="365" alt="Screenshot 2020-12-31 at 09 48 23" src="https://user-images.githubusercontent.com/10291664/103412935-6a314900-4b6f-11eb-9ad6-8b6dacfae7eb.png">

**File:** 
https://ridesims.com/ride-simulators/WDW-Monorail

**Replication steps:**
Click Start, Click start time afternoon, click X on all the pop ups, click on operation hours in the top left of the screen. 

<img width="76" alt="Screenshot 2020-12-31 at 13 55 41" src="https://user-images.githubusercontent.com/10291664/103413096-08bdaa00-4b70-11eb-8255-a93104841be6.png">

**Comment by n0samu** [comment]
This bug seems to be fixed now. Please leave a comment if something is still broken and I can reopen the issue.
