### ISSUE TITLE
Bug on the Game Record Tripping

### ISSUE THREAD

**Issue by Tatsuya-GTI** [ruffle-rs/ruffle#2188]
The page: https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Record-Tripping

# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/e/e002abfe4a8f3876a09ee88ea5ba43e2/src.swf
Param movie: https://img.clickjogos.com.br/dl/e/e002abfe4a8f3876a09ee88ea5ba43e2/src.swf
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Record-Tripping

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

![Record Tripping](https://user-images.githubusercontent.com/76817378/103415334-634f0a00-4b60-11eb-87a3-c3a4128fc30b.png)

**Comment by Futurama39** [comment]
Tried to load on Mozilla with ruffle 2021-01-12 and works without issues

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
