### ISSUE TITLE
Ruffle Error on https://gamcore.com/games/mio_f_series

### ISSUE THREAD

**Issue by hadewych** [ruffle-rs/ruffle#2194]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:541:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:541:5
    at Object.z (chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/core.ruffle.js:1:20865)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:37606)
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1324]:0x254c8e
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1491]:0x272a47
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4066]:0x338300
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3161]:0x315621
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4375]:0x33d2f1
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4405]:0x33d854
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4277]:0x33be08
    at chrome-extension://dmfbjopmjfkcenmgcnohlhbicoibmblk/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4406]:0x33d88a
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: //fgn.cdn.serverable.com/common/flashes/ff/m/mio_f_series.swf?d=20100810002119
Param wmode: gpu
Param allowFullScreen: true
Param allowfullscreeninteractive: true
Param bgcolor: #ffffff
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://gamcore.com/games/mio_f_series
SWF URL: https://fgn.cdn.serverable.com/common/flashes/ff/m/mio_f_series.swf?d=20100810002119

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Toad06** [comment]
Closing in favor of #2193 as this is the same issue. Thanks for reporting.
