### ISSUE TITLE
ruffle embedded in html throws error on any flash file

### ISSUE THREAD

**Issue by fuzzbuzzbay999** [ruffle-rs/ruffle#2195]
# file system
```
main folder  ───────────────────┐
   │  └───────────┐             │
website files   ruffle          │
 (.html, .css)    │             |
               ruffle files     │
                           flashGames
```
# code

```
<!doctype HTML>
<html>
    <head>
        <title>flash games</title>
        <link rel="stylesheet" type="text/css" href="sytle.css">
    <script src="ruffle/ruffle.js"></script>
    </head>
    <body>
        <h1>Games</h1>
        <embed
       src="flashGames/the-i-of-it-11371f2f2.swf"
               width="800"
               height="600">
    </body> 
</html>
````
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:67050
    at Array.forEach (<anonymous>)
    at Object.vi.f.wasm (file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:66977)
    at file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at Function.vi.e (file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:35276)
    at o (file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: file:///home/chronos/u-a7c5114a31ec3ac4b513d8ed91e322036d7d581c/MyFiles/websites/flash%20games/flashgames.html

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13505.73.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.109 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by ak65234** [comment]
It appears you are trying to run everything directly from local files stored on your computer. This is resulting in a [CORS error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp#Local_File_Security_in_Firefox_68) loading the files.

You can either turn off the feature, which would have potential security ramifications, or you can run a local webserver, such as apache, lighttpd, nginx, etc. and host your files from there.

**Comment by fuzzbuzzbay999** [comment]
Thank you!
