### ISSUE TITLE
Cirno's math training that makes the brain ⑨ cannot be opened

### ISSUE THREAD

**Issue by kenkendensi** [ruffle-rs/ruffle#2199]
When I try to open Cirno's math training where my brain becomes ⑨, I get an error.
![Screenshot_2021-01-01-11-36-49-75_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/51988985/103432663-39f8b180-4c26-11eb-9377-334cd6a2fa19.png)
https://game-tansaku.net/free/braintraining/chiruno/

**Comment by kmeisthax** [comment]
Sites embedding Ruffle need to configure their server to serve WASM files as MIME type `application/wasm`, see https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type

Ruffleを使っているサイトは、サーバの設定は必要です。WASMのファイルのMIMEタイプは、「`application/wasm`」型で転送しなければ、効けない。生憎、この文書化は英語だけです。

If this isn't your website, I don't think there's anything you can do to fix this error.

そのエラーは、あなたのサイトじゃなければ、しょうがないです。
