### ISSUE TITLE
Terminology: Emulator vs. virtual machine vs. runtime?

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#22]
I wasn't sure what to use as the primary "official" terminology for the project:

 * Emulator
   * Behaves like a different system
   * Implies archival + documentation of an outdated platform
   * But implies emulating actual, physical hardware
 * Virtual machine
    * Used to describe other platform-independent runtimes as Java and the AVM itself
    * Not based on physical hardware
    * But implies a single component of the overall runtime (AVM vs. Flash as a whole) 
    * Overloaded term, often means system virtualization (e.g. VirtualBox)
 * Runtime
   * Emphasizes the code as a whole that is necessary to run a Flash file

I chose "emulator" to place the emphasis on the archival+documentation of a legacy platform, and to set expectations that it will probably not be completely accurate. But I don't feel strongly one way or another. So I figure I'd open this up to discussion in case anyone has opinions (and to head off any potential flame wars 😄)

**Comment by larsiusprime** [comment]
I vote hard for EMULATOR. Even though I get what you're talking about in terms of technicalities, what's really important here is how the general public perceives this.

In pure technical terms, it's a "Flash Player Reimplementation" which as you say is a runtime/vm. But I think Emulator is the right word as it sets the right expectations from the get go and positions it alongside other projects (Mame, Dolphin, etc) that people already understand in terms of its purpose -- preserving our ability to play games and watch cartoons that were tied to a specific aging platform in danger of going extinct.

**Comment by Serentty** [comment]
What about “alternative”? Ruffle is a Flash alternative that lets you view old Flash content on modern devices and software.

**Comment by wizzwizz4** [comment]
Except, it's not really an _alternative_. It's a reimplementation of Flash.

**Comment by Serentty** [comment]
It's an alternative to Flash Player, the software. It's not an alternative to Flash as a platform.

**Comment by Manderby** [comment]
Hi. Don't know if it is allowed to just comment like that, but what about "Engine"? Otherwise, also would prefer "Emulator" over "Virtual Machine". "Runtime" sounds too technical and is probably too misleading. Other (mostly technical) terms might be "Driver", "Canvas", "Context".

**Comment by luser** [comment]
FWIW, [Adobe's Flash Player site](https://www.adobe.com/products/flashplayer.html) has in its `<meta name="description">` tag:
> Adobe® Flash® Player is a lightweight browser plug-in and rich Internet application runtime that delivers consistent and engaging user experiences, stunning audio/video playback, and exciting gameplay.

**Comment by NekoEd** [comment]
"Reimplementation" could work.

**Comment by Herschel** [comment]
Seems like everyone is okay with "reimplementation" for precise descriptions and "emulator" for casual descriptions. Thanks for the feedback!
