### ISSUE TITLE
Ruffle Error on https://e621.net/posts/65250?q=parent%3A58018

### ISSUE THREAD

**Issue by sgtsharki** [ruffle-rs/ruffle#2207]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:66344
    at Array.forEach (<anonymous>)
    at Object.gi.f.wasm (<anonymous>:3:65952)
    at <anonymous>:3:34393
    at Array.reduce (<anonymous>)
    at Function.gi.e (<anonymous>:3:34370)
    at i (<anonymous>:3:6066)
    at i.next (<anonymous>)
    at <anonymous>:3:6366
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/65250?q=parent%3A58018

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-28
Channel: nightly
Built: 2020-12-28T00:42:22.474Z
Commit: 8d707bc6ab747ae5039ce629f07c09aabfac2553

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
