### ISSUE TITLE
A number of z0r.de clips outputting audio differently (muffled)

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2211]
Chrome 87.0.4280.88

While listening closely to some of the audio from z0r.de clips (I guess they are predominantly MP3s), I noticed that some audio is played noticeably muffled, like you play 64 kbps bitrate MP3 instead of say 256 kbps, or 22050Hz sample rate instead of 44100Hz. For some clips the difference is slightly noticeable, but for some it's really heard.
If you have no good listening hardware or bad ears, you can see a noticeable difference in a high-end when comparing both playback capture spectrums, which is a typical thing for a lower fidelity audio files.

There is a number of those where my ears caught the issue:

https://z0r.de/2073
https://z0r.de/2118
https://z0r.de/2240
https://z0r.de/2365
https://z0r.de/2389
https://z0r.de/2436
https://z0r.de/2622
https://z0r.de/422
https://z0r.de/98
https://z0r.de/1026
...many more if you search

I seen here somewhere talks about wrongly interpreted bitrate and stuff (wrong metadata set on MP3s?), maybe that's also the case here?

**Comment by torokati44** [comment]
On Desktop (using `minimp3`), the sound output from at least z0r.de/2073 exactly matches that of the Adobe player. Down to the individual sample level.
On Web, there is indeed a noticeable difference.
So to me it looks like this only affects the `puremp3` decoder.

**Comment by Diatonator** [comment]
That's true! The audio played on desktop Ruffle is outputting the audio as per 2nd spectrum, while the audio taken from the swf in mp3 format using decompilation (JPEXS) is playing muffled (1st spectrum) on my mp3 program players.
Not really sure what's going on here

**Comment by torokati44** [comment]
And I think it comes down how the low samplerate is resampled to (in my case) 44100Hz.
See:
![image](https://user-images.githubusercontent.com/288816/103669294-7276f300-4f78-11eb-9b43-53a91a9d6636.png)

- Adobe and minimp3 uses a fast and simple, but "bad" resampler. The noisy high frequencies come from those jagged transitions.
- While puremp3 and ffplay uses a "better" resampler, which just ends up being "different" in this case.

The difference might also come down to whether they do the resampling themselves internally, vs. if they open an output stream with a low samplerate, and let the sound server itself (in my case, PulseAudio) do the resampling - and possibly if they can/do set some resampling hints for the sound server.

**Comment by Diatonator** [comment]
Well, now it makes sense.
While playing through various mp3-filled flashes, I definitely noticed the difference between Ruffle (web) and Adobe playbacks, but at times it was a bit puzzling which one sounds better and which is worse.
For 2073 it's surely sounds better in Adobe, because the style of the music benefits from added high-end spectrum distorsions, while some other tracks may benefit from "better resampling". And it's overall louder, which is again better here.

Also another thought is that because of such low bitrate/sample rate tracks may benefit from every little thing added to higher-end spectrum, as I often find those tracks sounding dull where there is no frequencies above 4kHz (which is understandable for 16 kbps / 11025Hz of course)

I do believe Ruffle may benefit from some sort of user parameter - either user wants "pure Adobe" or a "better resampling", if it's ever possible to implement.

**Comment by torokati44** [comment]
According to `pactl list | grep Hz` these applications use the following output formats, again, with z0r.de/2073:

- Adobe player: `s16le 2ch 44100Hz` - looks like linear resampling is done internally
- Ruffle desktop: `float32le 2ch 44100Hz` - looks similar, so this also might have an internal resampler somewhere
- Ruffle web (in Firefox or Chrome): `float32le 2ch 44100Hz` - I have no idea in which format Ruffle hands the data over to the browser, or what either of them does to the data
- ffplay: `s16le 1ch 11025Hz` - No resampling or upmixing, so this is the only one that was affected by adding `resample-method = trivial` to `/etc/pulse/daemon.conf`

**Comment by Herschel** [comment]
Thanks for investigating!

We don't use `puremp3` at all currently (and actually it should be removed from the dependency tree). Currently MP3 audio on web is decoded using Web Audio `decodeAudioData` APIs, so the difference comes from whatever the web browser is doing in there.

(Probably in the future we may switch to [symphonia](https://github.com/pdeljanov/Symphonia) to decode MP3 stream live, or experiment with using the [Media Source API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API).)

**Comment by torokati44** [comment]
Oops, I missed that.

**Comment by torokati44** [comment]
This should be fixed by #4273. Could you please confirm, @Diatonator?
(The demo page will only have these changes a couple hours from now.)

**Comment by Diatonator** [comment]
Yes indeed - fixed on Nightly 2022-07-31
The crust is back!
