### ISSUE TITLE
Functions not working and skipping frames? 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#2213]
We've got a file that's using AS1 and is having major issues with functions being executed. 

```
function NewPeeps() {
//code
}
```

It works fine in flash but as soon as you try run the file in ruffle, the function isn't run and you can see the train in the station is full of people. (Pressing the view button in the bottom left, will let you see this) I'm not sure if its not running the function or skipping to an incorrect frame? 

**SWF File:**
https://ridesims.com/sites/default/files/2020-12/SkyScreamv1_8.swf]

We've had this before and I think Dinnerbone and Mike had a look at it?

**Comment by Herschel** [comment]
Hi @JamesAllgood, what was the resolution here? Did you workaround the issue, or was it fixed by some change in Ruffle?

**Comment by JamesAllgood** [comment]
@Herschel we ended up changing the code so the issue is still in ruffle. I can reopen this and leave it with you guys if you want?
