### ISSUE TITLE
Question: Desktop ARM compatibility? 

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#2219]
ARM is picking up on desktop because of Apple. Does Ruffle's desktop builds work on it? 

I don't have an ARM desktop device, I'm just curious. :)

**Comment by kmeisthax** [comment]
Nothing in Ruffle is CPU specific as far as I know, but I've yet to actually try building it on ARM. Any platform that provides a `wgpu` supported API should work.

**Comment by Herschel** [comment]
Specifically for Apple Silicon, you can follow along with upstream support in Rust (https://github.com/rust-lang/rust/issues/73908). `aarch64-apple-darwin` is currently a tier 2 target for Rust and support should continue to improve. `wgpu` already supports Metal, so this should be a smooth transition for us. (Maybe someone with a new Mac can test this out for us).

At some point, we might try to make builds specifically for the `aarch64-apple-darwin` target.

**Comment by parkerlreed** [comment]
Yeah I've been compiling Ruffle on AArch64 Arch Linux ARM without any issues. As long as you have rust available, everything should be fine.
