### ISSUE TITLE
Flash files with multiple sound tracks are played at the same time

### ISSUE THREAD

**Issue by milekpl** [ruffle-rs/ruffle#2224]
I'm trying to use Ruffle to run a logic tutorial for my students (I have to resort to online teaching this year, with no access to the computer lab), which was programmed in old Macromedia Flash. However, the sound gets garbled under Chrome because all sound gets played at the same time). This is not the case for the offline desktop player, under which this works fine. 

An example file is added. 

[1101.zip](https://github.com/ruffle-rs/ruffle/files/5760096/1101.zip)

**Comment by ousia** [comment]
@milekpl,

I have no problem loading your attached SWF file at https://ruffle.rs/demo/ and playing it with Firefox.

It works perfectly fine, but I don’t use Chrome.

**Comment by milekpl** [comment]
It works fine under the demo install but not using the nightly build (I
used the most recent version). The demo also works under Opera, in contrast
to the nightly build.

niedz., 3.01.2021, 16:21 użytkownik Pablo Rodríguez <
notifications@github.com> napisał:

**Comment by ousia** [comment]
Sorry, @milekpl, I took for granted that https://ruffle.rs/demo/ always contained the latest released version.

**Comment by milekpl** [comment]
> Sorry, @milekpl, I took for granted that https://ruffle.rs/demo/ always contained the latest released version.

I would also think so, but it's difficult to find out which version is served. Most likely, it's not overwritten by the nightly build…

**Comment by ousia** [comment]
@milekpl,

https://ruffle.rs/demo/ contains version 2021-01-06 and Firefox (at least the version I use) plays sound perfectly fine.

I’m afraid it might be an issue with Chrome.

**Comment by milekpl** [comment]
@ousia 

I uploaded this version (01-06) right now to my server and it has the same effect under Opera (clearing the cache worked), Chrome, Edge, and Firefox. I also got the same effect under Chrome and Dolphin on Android.

The demo, however, does work. This is really strange… My flash website is password-protected due to copyright reasons but I could share the link and the pass in private, if you want to see this yourself. Here's how it looks to me:

https://www.loom.com/share/d9e36b1c0d5f406c9c160fb291460ff9

**Comment by ousia** [comment]
> I uploaded this version (01-06) right now to my server and it has the same effect under Opera (clearing the cache worked), Chrome, Edge, and Firefox. I also got the same effect under Chrome and Dolphin on Android.

@milekpl, sorry, but is it the same effect as mine (presentation working in Firefox) or the same effect as you previously got in Chrome (audio misbehaving)?

> The demo, however, does work. This is really strange…

If the demo works, it might be related on how the SWF files are embedded or how Ruffle is invoked.

> My flash website is password-protected due to copyright reasons but I could share the link and the pass in private, if you want to see this yourself.

Thanks, but this isn’t required (I cannot code, I’m just an average computer user).

Maybe I could try to create a sample site with your file, so you could check whether it works for you or not.

Remind me in a couple of do that, if I haven’t done it yet.

**Comment by ousia** [comment]
https://ousia.github.io/another-ruffle-demo/ contains your demo.

**Comment by milekpl** [comment]
@ousia 

Thanks. Your demo works just fine. 

When I mentioned that I have audio misbehaving, I meant that the effect can be replicated under a number of browsers. Apparently, this is related to the fact that this file is loaded by another SWF file (the main one). I'll create a minimal version of my setup and see what happens – now I guess the bug is related to file functions.

**Comment by milekpl** [comment]
@ousia 

OK, so the problem is only when the file is loaded via the main subsection file. The bug appears as soon as you have 11.swf as your main object file, which then loads 1101.swf from the same directory. See the file attached. If you change your script to load 11.swf (instead of 1101.swf), it should break.

[11.zip](https://github.com/ruffle-rs/ruffle/files/5781080/11.zip)

**Comment by ousia** [comment]
> The bug appears as soon as you have 11.swf as your main object file, which then loads 1101.swf from the same directory. See the file attached. If you change your script to load 11.swf (instead of 1101.swf), it should break.

@milekpl,

well, I guess this happens after pressing some button on `11.swf`.

I cannot load it even using Adobe Flash.

Which is the button that loads `1101.swf`? (Sorry, but otherwise it is impossible to show the issue to the developers.)

**Comment by milekpl** [comment]
Yeah, sorry, the topmost button on the left. It says "Arguments and
Conclusion Indicators".


czw., 7.01.2021, 15:14 użytkownik Pablo Rodríguez <notifications@github.com>
napisał:

**Comment by Toad06** [comment]
Thanks for the report.

I've been able to reproduce the issue. Here's the full sample, with both `11.swf` and `11/1101.swf`:
[full_sample.zip](https://github.com/ruffle-rs/ruffle/files/5782629/full_sample.zip)

The root SWF (`11.swf`) has a frame rate value of `12` but the inner SWF (`11/1101.swf`) has a frame rate value of only `2`. The issue is that Ruffle doesn't take the inner SWF's frame rate into account, so the file actually runs six times faster than it should. This is likely the reason why sound tracks play on each other.

If I lower the root SWF's frame rate to `2`, then everything seems normal (here's the edited file if you're interested, but please make to sure to keep a copy of the original: [11_edit.zip](https://github.com/ruffle-rs/ruffle/files/5782736/11_edit.zip)).

Also, kinda related to #2134.

**Comment by milekpl** [comment]
@Toad06 

Thanks for this. I tried using the edited file under Windows standalone ruffle app (which has exactly the same problem) but the loading process is stuck forever for all inner files. Note: this does not happen if I call 11.swf from the main.swf file (the main app file).

Is there some free software I could use to set the frame rate on binary SWF files? I could test this for the whole thing.

**Comment by Toad06** [comment]
Sure, you could use JPEXS (https://github.com/jindrapetrik/jpexs-decompiler/releases/tag/version11.3.0). Then, when you load a SWF, you can see and change the frame rate in the "header" section.

**Comment by milekpl** [comment]
@Toad06 Thanks!

The weird thing is that changing the frame rate setting on the main app file (and some other files) helps for the self-hosted version but not for the desktop app, which still has the sound broken (at least under Windows).

**Comment by ousia** [comment]
> The bug appears as soon as you have `11.swf` as your main object file, which then loads `1101.swf` from the same directory.

Just for the record `1101.swf` needs to be placed `11/1101.swf` (relative to `11.swf`).

I updated the sample, including corrected version by @Toad06.

BTW, I wonder whether the title should be replaced with something that mentions the different frame rate in loader and loaded files.

Just in case it helps.
