### ISSUE TITLE
3 Foot Ninja II - Fall through the floor in Ruffle

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2227]
https://www.newgrounds.com/portal/view/192451/format/flash?emulate=flash

In the first level of 3 Foot Ninja II, jump to the far left of the screen and you should consistently fall through the floor and off the screen. In the Flash player this doesn't appear to happen and it keeps you on-screen.

**Comment by n0samu** [comment]
This seems to be fixed now
