### ISSUE TITLE
One Quick Question

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#2230]
Some flash files run but goes too heavy on Computer and slow down the whole system until you close Ruffle. Does this also consume lots of memory on server or it's just computer?

**Comment by torokati44** [comment]
Once the .swf is downloaded (even if just into memory without saving it to disk), the server is out of the picture - unless it's a multiplayer game / networked application. Its execution is usually entirely within your computer, without doing anything with the server.
And I'm just guessing, but I imagine in most cases the server gets exactly the same load whether the .swf file is downloaded by Ruffle, by the Adobe Flash plug-in, or by your browser itself when you save it to disk.

**Comment by torokati44** [comment]
Although, this issue tracker is not really meant for these kinds of questions. The Discord server is more appropriate for these things I believe.

**Comment by zohebnsr** [comment]
Thanks for the explanation

**Comment by Herschel** [comment]
Yes, Ruffle is completely client side. For the server, it is the same as downloading any other file.
