### ISSUE TITLE
Ruffle Error on https://www.supersmashflash.com/play/ssf1/?ruffle=true

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#2234]
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
    at Object.Y (chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/core.ruffle.js:1:20605)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:35267)
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1104]:0x22216b
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1447]:0x264d52
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3944]:0x3250b3
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[3088]:0x30450a
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4300]:0x32a87b
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4252]:0x32a008
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[4302]:0x32a8cd
    at chrome-extension://mmbekggmiffgmfhbjhcjklhjlnmjjffm/dist/0b7a6832a6f80b4f3ff4.module.wasm:wasm-function[1707]:0x28b9e0
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /flash/games/SuperSmash
Param movie: /flash/games/SuperSmash
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.supersmashflash.com/play/ssf1/?ruffle=true
SWF URL: https://www.supersmashflash.com/flash/games/SuperSmash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-19
Channel: nightly
Built: 2020-12-19T00:34:27.448Z
Commit: 042e9a444b98f7dbf920a070ffe240ad01e7cbe4

**Comment by Poopooracoocoo** [comment]
@Fancy2209 Can you still repro?

**Comment by Fancy2209** [comment]
let me see

**Comment by Fancy2209** [comment]
yes
