### ISSUE TITLE
Issues in Music Mania (might be related to timing)

### ISSUE THREAD

**Issue by NY00123** [ruffle-rs/ruffle#2235]
Hi all,

I've recently checked Ruffle out. From what I've seen, this is a very impressive project! It already has a great level of compatibility with a small set of games tested by me.

I've found a couple of problems in Music Mania. Feel free to split this report if it turns out that these are separate bugs, technically.

Link to Music Mania: https://www.newgrounds.com/portal/view/386313
Ruffle extension in use: ruffle_nightly_2021_01_02_firefox.xpi

1. In the mini-game "Midnight", when a game ends, it can take a variable amount of additional time until you're back to the game's menu. The exact time of wait seems to depend on the amount of time passing without colliding with a gear in-game; It looks like longer play times correlate with longer waits.

2. I can't play "Beat Masher", since the game appears to freeze near the beginning.

Thanks for the work on the project!

**Comment by adrian17** [comment]
1. Is probably caused by https://github.com/ruffle-rs/ruffle/issues/193 - the wait is caused by `_alpha_` being changed every frame, and Ruffle processing it differently than Flash;

2. Probably caused by `Sound.position: Unimplemented`.

**Comment by adrian17** [comment]
1. Is now fixed.

**Comment by NY00123** [comment]
Confirming the aforementioned timing problem in "Midnight" as fixed. Thanks for anyone involved in the work!
I keep the issue open for "Beat Masher".

**Comment by ChaseWaylon** [comment]
> 1. Is now fixed.

Can you also fix 2. please :)

**Comment by ousia** [comment]
`Sound.position()` has been implemented.

I wonder whether 2 has been fixed.

**Comment by NY00123** [comment]
I checked with nightly build 2022-01-11 (Firefox extension), and the situation did improve in comparison to 2021-01-02. The rectangular shapes are falling down and you may press on the notes.

There still seems to be a problem with registering most of the matching note presses. With the exception of the first few, I don't seem to be successful with getting points in-game.

Question is if this issue should remain open, or if a new one can be used instead. It'll remain open for now.

Either way, thanks again for the efforts!

**Comment by NY00123** [comment]
Fixed now, all mini-games are playable! The main issue (this might vary across web browsers) is that the animation isn't necessarily smooth. It's probably timing-related again, and chances are it was already reported for another SWF file.

Thanks again!

Alternative links in case the game isn't loaded via the original URL:

https://www.newgrounds.com/portal/view/386313/format/flash?emulate=flash
https://uploads.ungrounded.net/386000/386313_musicmania.swf

**Comment by NY00123** [comment]
I think this issue can be closed; The games seem to work as I remember. More UI elements may be revealed and gameplay may be impacted if changing Scale Mode to "Unscaled (100%)" and/or toggling Letterbox off, but that might be a more general thing.

Thanks again for all of your work!
