### ISSUE TITLE
Rendering bug with cardiac simulation tool

### ISSUE THREAD

**Issue by ssylvan** [ruffle-rs/ruffle#2239]
Running the cardiac training simulation here: http://pie.med.utoronto.ca/Edwards/content/POPS_vent_EV1000.html

Select any of the patient scenarios and hit "play patient" and click past the tutorial screen. Notice how the EKG looks as it updates. That same EKG looks wrong with ruffle. Here's an example, first flash player:
![image](https://user-images.githubusercontent.com/1365415/103490210-16bd3600-4dcf-11eb-8e00-185c8e151510.png)
Then ruffle_nightly_2021_01_03_windows:
![image](https://user-images.githubusercontent.com/1365415/103490223-2d638d00-4dcf-11eb-89b1-903782565cbe.png)

There seem to be several visual bugs going on there.

**Comment by Poopooracoocoo** [comment]
seems to be fixed, at least on the extension.
