### ISSUE TITLE
BitmapData.merge, BitmapData.perlinNoise, BitmapData.copyPixels  - not yet implemented

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2240]
Creating the issue similar to https://github.com/ruffle-rs/ruffle/issues/2073

copyPixels is present both in this and https://github.com/ruffle-rs/ruffle/issues/2073, but perlinNoise and merge are unique to this.

The link:

https://z0r.de/282

![image](https://user-images.githubusercontent.com/75184268/103491416-dabcbc00-4e34-11eb-9c25-73577f23c6e8.png)

The visual consequence of this not implemented is the absence of this sort of liquid motion:

Adobe:
![282_Flash](https://user-images.githubusercontent.com/75184268/103491537-aa295200-4e35-11eb-982c-3f685cd70e58.gif)

Ruffle:
![282_Ruffle](https://user-images.githubusercontent.com/75184268/103491539-adbcd900-4e35-11eb-90ae-d348660e616c.gif)

**Comment by torokati44** [comment]
This loop also uses `BitmapData.draw()`, and will not work any better without it.
Unfortunately it passes a `MovieClip` to it as parameter (as opposed to a `BitmapData`), so a hacky temporary solution that simply copyes pixels around won't do either; this will need the actual full off-screen rendering.

**Comment by torokati44** [comment]
Upon closer inspection, this loop also needs the `filters` property, and `DisplacementMapFilter`.

**Comment by Lord-McSweeney** [comment]
Everything has been implemented for this SWF, but for some reason, the DisplacementMapFilter is static in Ruffle, while the filter on the text seems to change in FP.

**Comment by torokati44** [comment]
See also: #12149

**Comment by torokati44** [comment]
The initial post cropped the screenshots to their bottom parts.
The loop is square in Flash Player too, and has that top text:

![image](https://github.com/ruffle-rs/ruffle/assets/288816/f3215347-f9bd-40bf-9bb3-7e02ac7360fa)

**Comment by firoball** [comment]
Oh, that's interesting :D
I thought inbetween some ruffle versions I noticed the exact window layout as initially shown, just without effects.

Nevermind then, sorry for the ping.
