### ISSUE TITLE
Publish nightly builds to the AUR

### ISSUE THREAD

**Issue by relrelb** [ruffle-rs/ruffle#2246]
I used to maintain the [`ruffle-nightly-bin`](https://aur.archlinux.org/packages/ruffle-nightly-bin) package in the Arch Linux [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository), but recently my Google Cloud free trial has expired and it no longer gets updates.

I think this process can fit well in the existing nightly workflow. It has to do something similar to [`update.sh`](https://aur.archlinux.org/cgit/aur.git/tree/update.sh?h=ruffle-nightly-bin), which requires an Arch Linux environment (for `updpkgsums` and `makepkg`).

If this is something we want to do, I can open a PR for it.

**Comment by Herschel** [comment]
Sure, this would be welcome if you are willing to maintain it. Thank you!
