### ISSUE TITLE
Scrolling text is not working in the Weebl's stuff (?) loop

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2251]
https://z0r.de/775

Scrolling text at the bottom is not working.

Adobe:
![775_Adobe](https://user-images.githubusercontent.com/75184268/103530277-2bb1cc00-4e98-11eb-9a52-9bf83858e0d0.gif)

Ruffle:
![775_Ruffle](https://user-images.githubusercontent.com/75184268/103530283-2e142600-4e98-11eb-9f35-60ec9d033299.gif)

- You can see that this text is interactable. You can click on it and it stops, or starts. It appears that in a broken Ruffle playback you can still stop "something" - some white dots at the bottom of this moving ribbon.

- The amount of errors of various types outputted to F12 console is just huge, and is growing the longer it plays:
![image](https://user-images.githubusercontent.com/75184268/103530448-80eddd80-4e98-11eb-87fe-2be0befb6baf.png)

No AS3 warning or something

**Comment by Toad06** [comment]
Should work once `setMask` is implemented (cc. #1483).

**Comment by Herschel** [comment]
Fixed by #1483.
