### ISSUE TITLE
Dynamic text is not positioned correctly

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#227]
Dynamic text fields created with the DefineEditText tag are sometimes not positioned correctly. Here's an example from Marvin Spectrum:
![image](https://user-images.githubusercontent.com/36278/71841651-c6ed4700-3074-11ea-914b-698f03700645.png)

Has to do with the text alignment in the text box. We may need a full text layout engine to implement this 100%, but we could at least improve it by implementing some basic text metrics for now.

Main tracking issue is #41.

**Comment by ousia** [comment]
@Herschel,

I’d rather say it seems to be fixed (probably after merging #615):

![mv-fixed](https://user-images.githubusercontent.com/203767/107087971-8a9e9400-67fc-11eb-9dff-b748f4b744b7.png)
