### ISSUE TITLE
"Invalid string data" when encountering a string with '(c)'

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2283]
https://z0r.de/1656

In the left-bottom the string should appear

![image](https://user-images.githubusercontent.com/75184268/103631728-6b3dee00-4f54-11eb-9836-3a7b6cbe4d4c.png)

But it's not here, and we see the "invalid string data" error in console:

![image](https://user-images.githubusercontent.com/75184268/103631826-8a3c8000-4f54-11eb-9ca7-c1b01905ae3d.png)

**Comment by Diatonator** [comment]
for now (Nightly 2021-02-06) it looks like the string is mostly output, but (c) character is missing
![image](https://user-images.githubusercontent.com/75184268/107146928-34e0fd80-695c-11eb-8fd6-c35777968119.png)

**Comment by Diatonator** [comment]
The issue is persisting on Nightly 2021-12-30

**Comment by relrelb** [comment]
This was fixed by #6224, and works in the latest nightly. Note that z0r.de haven't updated their Ruffle build yet.
