### ISSUE TITLE
VG Exiles Episode 3 - White Screen

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2286]
https://www.newgrounds.com/portal/view/579863/format/flash?emulate=flash

This movie is stuck on a white screen, never getting to the preloader.

**Comment by waspennator** [comment]
On my end, I cannot seem to replicate this issue anymore, the movie preloads up just fine now and I can start it up on my laptop with edge and firefox and on my S22 with Chrome.
