### ISSUE TITLE
Stuck on "Loading Assets 100%"

### ISSUE THREAD

**Issue by LadyGrace05** [ruffle-rs/ruffle#2288]
I'm a science teacher and use a lot of Glencoe Virtual Labs in my class, especially now that we've been doing virtual learning. The end of Flash was kind of devastating and I've been kind of in denial that I'll have to figure something else out, especially after I found Ruffle. I just installed it as an extension on my school Chromebook, and tried to open a lab. I see the "loading" screen that always starts a lab, so that is a good sign (it's not the grey box that shows if Flash isn't working), but it isn't moving past this screen. I'll include a couple of links to Glencoe Labs for anyone who wants to give it a try.  Thanks in advance to anyone who is able to help me solve this issue. 

http://www.glencoe.com/sites/common_assets/science/virtual_labs/ES09/ES09.html
http://www.glencoe.com/sites/common_assets/science/virtual_labs/ES14/ES14.html

**Comment by limeysoda** [comment]
These probably use newer standards than Ruffle supports right now, I think some of these are in Flashpoint if that helps

**Comment by LadyGrace05** [comment]
> These probably use newer standards than Ruffle supports right now, I think some of these are in Flashpoint if that helps

Thanks. I've heard of Flashpoint as well, but it didn't seem like a viable option because you couldn't limit access to the whole billion+ games that Flashpoint saved? I also tried to find the labs that I use on their master list, but their master list was utterly epic, and I got tired.... I didn't find any that I used, but did some that I didn't know about before. Please correct me if I'm not understanding how Flashpoint works.
