### ISSUE TITLE
Ruffle Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Slaybad** [ruffle-rs/ruffle#2289]
# Error Info
Error name: Error
Error message: Unreachable code should not be executed (evaluating 'r.ruffle_load_data(this.ptr,u(e),D(_))')
Error stack:
```
<?>.wasm-function[4898]@[wasm code]
<?>.wasm-function[3043]@[wasm code]
<?>.wasm-function[2816]@[wasm code]
<?>.wasm-function[302]@[wasm code]
<?>.wasm-function[378]@[wasm code]
<?>.wasm-function[1241]@[wasm code]
<?>.wasm-function[344]@[wasm code]
<?>.wasm-function[420]@[wasm code]
<?>.wasm-function[2703]@[wasm code]
<?>.wasm-function[1152]@[wasm code]
<?>.wasm-function[488]@[wasm code]
<?>.wasm-function[282]@[wasm code]
<?>.wasm-function[1462]@[wasm code]
<?>.wasm-function[778]@[wasm code]
<?>.wasm-function[320]@[wasm code]
<?>.wasm-function[1642]@[wasm code]
<?>.wasm-function[1029]@[wasm code]
<?>.wasm-function[3818]@[wasm code]
wasm-stub@[wasm code]
ruffle_load_data@[native code]
load_data@https://ruffle.rs/demo/662.index.js:1:20005
https://ruffle.rs/demo/index.js:1:18286
generatorResume@[native code]
c@https://ruffle.rs/demo/index.js:1:12790
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-05
Channel: nightly
Built: 2021-01-05T00:48:08.020Z
Commit: de761f5b7c6753ad140018cbc38ba777201f739d

**Comment by Poopooracoocoo** [comment]
@Slaybad What were you trying to do/play?

**Comment by Slaybad** [comment]
Attachment available until Feb 4, 2021
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FASlQXbte38Ks5E_PvROwnLdPNNGGAbIfcw_YK-uYGSJ1GNQNcxFKJbxh%2F%24%7Bf%7D%3Fo%3DApwZD3TwrO7bn_OQbm3_OdyGrPeCR3bMQNErAhyR6FIl%26v%3D1%26x%3D3%26a%3DCAogPYJzn3598_Ir5PHV0HUT5hw8-Sv9UGKBMjb-kXEbKwwSdhDO5OSb7S4YzvTf7_YuIgEAKgkC6AMA_1Y7BbZSBE800YZaBEolvGFqJc9o18OqE99E-1ifRR4QIVE9jd7txc-WAqhGmD-T_OU9vGfNd3ZyJZJk2A8vd3hem1T0za2CqZpi_Bv5UWuqxUkouPGEK7TjopIXazc%26e%3D1612457704%26fl%3D%26r%3D93570911-6C78-4A5A-BC3F-ACC94FEAD0FC-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D9D1E9E50-E963-4794-9D04-989270B2EFE3%26p%3D13%26s%3DkV15AVfIqhx3sgJnJZUqMRG8kwQ&uk=iesimG5q8UueY74zKh-DXA&f=CK5_v1.7.swf&sz=101481141>CK5_v1.7.swf
101.5 MB
 I was trying to use this, it worked for the web extension version of ruffle.

**Comment by Poopooracoocoo** [comment]
@Slaybad Mind uploading it again? The developers haven't gotten the chance to look at it. You could upload it to GitHub in a zip.

**Comment by Poopooracoocoo** [comment]
Closing due a lack of a response from reporter.
