### ISSUE TITLE
Stuck on a white screen before the game starts

### ISSUE THREAD

**Issue by pnkapadia64** [ruffle-rs/ruffle#2290]
Before the gameplay starts, the game gets stuck for a bit on a blank white screen. Can we get a callback if that is the loading/emulation phase, or a spinner for the user to know that it is being loaded?
Game: https://archive.org/details/flash_breaking_the_bank
On our platform: https://www.crazygames.com/game/breaking-the-bank

**Comment by Poopooracoocoo** [comment]
also see #875

**Comment by Herschel** [comment]
Closing in favor of #875.
