### ISSUE TITLE
Windows Doors - Serial Key text fields don't auto-tab

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2292]
https://www.newgrounds.com/portal/view/512482/format/flash?emulate=flash

At the start of Windows Doors, it shows a serial key and has text fields where you fill it in. In the Flash player, it will auto-tab to the next text field when you've filled the current field. In Ruffle you need to click each individual text field.

**Comment by britt-j** [comment]
This seems to be fixed now
