### ISSUE TITLE
BitmapData.applyFilter, BitmapData.perlinNoise, BitmapData.paletteMap not yet implemented

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2295]
Similar to https://github.com/ruffle-rs/ruffle/issues/2240 and https://github.com/ruffle-rs/ruffle/issues/2073

https://z0r.de/1906

![image](https://user-images.githubusercontent.com/75184268/103682977-a2cf8900-4f9a-11eb-945a-79e2d7875c69.png)

https://github.com/ruffle-rs/ruffle/issues/2240 also has perlinNoise, https://github.com/ruffle-rs/ruffle/issues/2073 also has applyFilter
paletteMap is unique to this

Visually - a thing, I would call "morphing strings" for absence of the better name, is missing

Adobe:
![1906_Adobe](https://user-images.githubusercontent.com/75184268/103684174-33f32f80-4f9c-11eb-8b51-79663ac72cd7.gif)

Ruffle:
![1906_Ruffle](https://user-images.githubusercontent.com/75184268/103684189-3a81a700-4f9c-11eb-92cd-89b67f42efea.gif)

**Comment by firoball** [comment]
This loop appears to be working with latest z0r build.

**Comment by torokati44** [comment]
Yes it's almost perfect now. The only minor difference is that the purple wobbly strings are barely glowing (if at all), while it's more prominent in Flash Player.

**Comment by torokati44** [comment]
Anyway, I think all problems described in the original issue are fixed now, the minor glow (blur, really) inaccuracies are a known area in need of improvement.
