### ISSUE TITLE
The Mind Bender - Level art is invisible

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2296]
https://www.newgrounds.com/portal/view/409380/format/flash?emulate=flash

When you start the game, the level is just a white screen but you can see the player and run around and jump on invisible objects.

**Comment by Toad06** [comment]
This will require `BitmapData.draw` to be implemented.

**Comment by Lord-McSweeney** [comment]
Thanks to #9134, the issue is fixed, but there are still performance issues.
