### ISSUE TITLE
Loading of SWF files freezes at startup of mineral Lab simulation (code archive and error console log attached)

### ISSUE THREAD

**Issue by kpmadden1953** [ruffle-rs/ruffle#2300]
This Flash application runs in the standalone Adobe Flash player well. I've tried to run it in the windows 10 version of Chrome with the Ruffle extension, and in the Windows Ruffle standalone version, but the loading of assets stops at the 100% progress bar of the ES03.swf file. The other SWF files in the directory need to load as well, but do not. I've attached a Zip file showing the flash source, and the output of the Chrome console error dump. Thanks for your help!

[labMineral.zip](https://github.com/ruffle-rs/ruffle/files/5773900/labMineral.zip)
[kpmadden.ddns.net-1609905210086.log](https://github.com/ruffle-rs/ruffle/files/5773902/kpmadden.ddns.net-1609905210086.log)

**Comment by n0samu** [comment]
Just tested this in the Ruffle desktop app and it seems to be fixed now. Please leave a comment if something is still broken and I can reopen the issue.
