### ISSUE TITLE
Ruffle freezes on 32 bit OS

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ruffle-rs/ruffle#2315]
wherever website where Ruffle is installed stalls my computer for 30 sec, then alert saying if I continue, debug or stop the script.
the JS error below
ReferenceError: reference to undefined property "RufflePlayer"[Learn More]  
ruffle.js:1:35169

I have to stop the script to unlock my computer activity.
This behavior is on firefox 68, windows 7 32 bits

**Comment by Poopooracoocoo** [comment]
also see #2016

**Comment by ROBERT-MCDOWELL** [comment]
ha ok I see. it's a HW accel. apparently.
I use an old nvidia quadro FX 2700M
