### ISSUE TITLE
Ruffle Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by roshanjhegde** [ruffle-rs/ruffle#2316]
# Error Info
Error: Error loading movie: Invalid data: Invalid SWF

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-07
Channel: nightly
Built: 2021-01-07T00:50:17.728Z
Commit: 02c591958e4623398b8f283cd56f123b7fdb6788

**Comment by roshanjhegde** [comment]
Unable to run SWF files in the demo.

**Comment by Poopooracoocoo** [comment]
Does this happen with a specific SWF? You could provide a link to it, or put it in a ZIP and attach it to a comment here.
