### ISSUE TITLE
Disabling warning for Action Script 3 content

### ISSUE THREAD

**Issue by einsz** [ruffle-rs/ruffle#2321]
It it possible to disable the warning displayed for Action Script 3 content introduced in #1978 ?
I'm getting tons of 'false positives', where ruffle detects some Action Script 3 but the animation actually plays completely fine. I've had to roll back to an earlier version of ruffle before this was introduced.

Some examples where this is happening:
https://z0r.de/L/z0r-de_7436.swf
https://z0r.de/L/z0r-de_7527.swf
https://z0r.de/L/z0r-de_6168.swf
https://z0r.de/L/z0r-de_7837.swf
https://z0r.de/L/z0r-de_3659.swf

**Comment by macfrombv** [comment]
Bump, I'd like to be able to disable this in special cases.

**Comment by Poopooracoocoo** [comment]
also see #2021

**Comment by Poopooracoocoo** [comment]
I wonder what triggers it. I think it looks for anything that runs in AVM2. Would exceptions need to be made or would the AS3 detection need an overhaul?

**Comment by Diatonator** [comment]
From what I can see in the code (I'm not that familiar with Flash or Rust yet), it just reads for certain file attributes to determine the fact. The check is not very deep certainly. Adding anything deeper than this will require some work I think.
