### ISSUE TITLE
Does Ruffle play videos embedded within the swf file?

### ISSUE THREAD

**Issue by eabigelow** [ruffle-rs/ruffle#2324]
Hi--

Thank you so much for Ruffle. This is helping many of us to to preserve Flash works which we thought were otherwise lost!

Question: Does Ruffle play videos embedded within the swf file? I have a piece at https://webyarns.com/ThisIsNotAPoem.html where, once all the words have been "scattered" off the page, a video is supposed to play at the center of the circle. 

Is video support still being worked on?

Again, my thanks for this great emulator!

**Comment by torokati44** [comment]
While playing at least H.263 videos is being worked on (see: #2173 - it is not that far from being "done" IMHO, but at least usable enough), the video in your .swf file is encoded with VP6, which is a bit further down the line: #723

**Comment by eabigelow** [comment]
Thank you very much for your reply. Much appreciated!

**Comment by torokati44** [comment]
@eabigelow VP6 decoding was just added, so you could try your content with the upcoming nightly release.

**Comment by eabigelow** [comment]
Thanks!
