### ISSUE TITLE
IDP.ARES.Generic?!

### ISSUE THREAD

**Issue by MintKakapo** [ruffle-rs/ruffle#2325]
I tried running the .exe from the official ruffle.rs site, and Avast blocked it stating there was a Trojan in it, with the name above. Anyone else have this problem? <:\

**Comment by Elementtair** [comment]
Nothing here
Tried it on virus Total , and none of the 69 engines detect anything (including Avast).
Also Avast heuristic engine tend to be very sensitive, and give false positive a bit too often.

**Comment by Herschel** [comment]
Yes, this is a false positive. I submitted a false positive report on the Avast form here: https://www.avast.com/en-us/false-positive-file-form.php
