### ISSUE TITLE
Error on https://e621.net/posts/347530?tags=flash++

### ISSUE THREAD

**Issue by poleofmail** [ruffle-rs/ruffle#2327]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:67568
    at Array.forEach (<anonymous>)
    at Object.mi.f.wasm (<anonymous>:3:67176)
    at <anonymous>:3:35333
    at Array.reduce (<anonymous>)
    at Function.mi.e (<anonymous>:3:35310)
    at i (<anonymous>:3:6438)
    at i.next (<anonymous>)
    at <anonymous>:3:6738
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/347530?tags=flash++

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-08
Channel: nightly
Built: 2021-01-08T00:51:10.664Z
Commit: cb9bdcdfdbc3ca2e5812f176713f7976b62fc28f

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
