### ISSUE TITLE
Ruffle Error on https://h-flash.com/mio-f-series/

### ISSUE THREAD

**Issue by cuadern0** [ruffle-rs/ruffle#2330]
# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:541:5
Error stack:
```
Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:541:5
    at Object.X (https://h-flash.com/data/ruffle/core.ruffle.bbb40c85e6191179c48b.js:1:20832)
    at __wbg_new_df6e6ab7a65c4c4d (https://h-flash.com/data/ruffle/ruffle.js:1:37870)
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[1313]:0x253c0b
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[1480]:0x271881
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[4019]:0x333f07
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[3134]:0x3121d4
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[4329]:0x338f35
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[4359]:0x339498
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[4231]:0x337a4c
    at https://h-flash.com/data/ruffle/587e6d0a42036d642c1e.module.wasm:wasm-function[4360]:0x3394ce
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://h-flash.com/mio-f-series/
SWF URL: https://h-flash.com/data/swf/2012/12/mio-f-series.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-28
Channel: nightly
Built: 2020-12-28T00:42:22.474Z
Commit: 8d707bc6ab747ae5039ce629f07c09aabfac2553

**Comment by Toad06** [comment]
Closing in favor of #2193 as this is the same issue. Thanks for reporting.
