### ISSUE TITLE
link to database possible?

### ISSUE THREAD

**Issue by eabigelow** [ruffle-rs/ruffle#2339]
Hi--

Very much LOVE Ruffle and how it is keeping Flash alive. Thank you!

QUESTION: I have a .swf page that is supposed to link to a database (so users can leave messages that will show on the flash page). That database is no longer accessible via the flash page and nothing will save into the database. 

Is this a problem currently in the pipe for fixing?

Thanks again!

**Comment by Herschel** [comment]
Hi, it depends on the specific method used to query the database. We support some methods already. If possible, could you post a link to the SWF? Thank you!

**Comment by eabigelow** [comment]
Hi--

Thank you very much for your offer. Much appreciated!

Here is the link to the .swf: webyarns.com/MYTHWATCH2/MythWatch.swf

Thanks again!

**Comment by Herschel** [comment]
Looks like the file it uses `loadVariables` which should hopefully work. The current issue is that it is trying to load from https://webyarns.com/MYTHWATCH2/get_random.phtml which does not exist.

**Comment by eabigelow** [comment]
Wow, my bad. Thank you for the catch! It works now. Many thanks!
