### ISSUE TITLE
"Armor mayhem" on click jogos don't start

### ISSUE THREAD

**Issue by Buuhzerah** [ruffle-rs/ruffle#2341]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/9/96660d064302cae7550eacc5a232d6cf/src.swf
Param movie: https://img.clickjogos.com.br/dl/9/96660d064302cae7550eacc5a232d6cf/src.swf
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/Jogos-online/Tiro/Armor-Mayhem

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.459
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by Futurama39** [comment]
Proposing for close in favour of #1368 

![image](https://user-images.githubusercontent.com/12499845/104366268-66aba380-5519-11eb-8c39-a25920ef50bd.png)

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
