### ISSUE TITLE
Ruffle Error on http://127.0.0.1:5500/www/index.html

### ISSUE THREAD

**Issue by AshleyDDB** [ruffle-rs/ruffle#2345]
I'm just trying to run ruffle on localhost

# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: http://127.0.0.1:5500/www/js/core.ruffle.9eec0e753f06015bcd55.js)
Error stack:
```
vi.f.j@http://127.0.0.1:5500/www/js/ruffle.js:1:37224
vi.e/<@http://127.0.0.1:5500/www/js/ruffle.js:1:35620
vi.e@http://127.0.0.1:5500/www/js/ruffle.js:1:35597
o@http://127.0.0.1:5500/www/js/ruffle.js:1:2623
o/i</<@http://127.0.0.1:5500/www/js/ruffle.js:1:2923
o/i<@http://127.0.0.1:5500/www/js/ruffle.js:1:2659
o@http://127.0.0.1:5500/www/js/ruffle.js:1:2946
E@http://127.0.0.1:5500/www/js/ruffle.js:1:14289
F@http://127.0.0.1:5500/www/js/ruffle.js:1:23984
fromNativeEmbedElement@http://127.0.0.1:5500/www/js/ruffle.js:1:25279
W@http://127.0.0.1:5500/www/js/ruffle.js:1:28802
Y@http://127.0.0.1:5500/www/js/ruffle.js:1:30287
polyfill@http://127.0.0.1:5500/www/js/ruffle.js:1:34876
init@http://127.0.0.1:5500/www/js/ruffle.js:1:34022

```

# Player Info
Allows script access: true

# Page Info
Page URL: http://127.0.0.1:5500/www/index.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-07
Channel: nightly
Built: 2021-01-07T00:50:17.728Z
Commit: 02c591958e4623398b8f283cd56f123b7fdb6788

**Comment by Herschel** [comment]
It seems like you are missing some files. Does your directory contain all of:
 * `ruffle.js`
 * `core.ruffle.*.js`
 * `*.module.wasm`

**Comment by Herschel** [comment]
Solved via e-mail.
