### ISSUE TITLE
Defend the North Pole - Stuck on Loading Screen

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#2346]
https://www.newgrounds.com/portal/view/284847/format/flash?emulate=flash

Defend the North Pole is stuck on the loading screen in Ruffle. It loads successfully with Flash player.

**Comment by TomFulp** [comment]
This problem only seems to crop up in games by this dev that were sponsored by CrazyMonkeyGames - maybe something is failing with an API connection. They do work in Flash player, could be an http vs https issue.

https://www.newgrounds.com/portal/view/351400/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/291408/format/flash?emulate=flash

**Comment by n0samu** [comment]
All of these games seem to load fine now!
