### ISSUE TITLE
Ruffle Error on http://www.classicgamesarcade.com/game/21679/red-plane.html

### ISSUE THREAD

**Issue by samuelsamuel22** [ruffle-rs/ruffle#2347]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://www.classicgamesarcade.com/games/red-plane-shooter.swf
Param movie: https://www.classicgamesarcade.com/games/red-plane-shooter.swf
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: http://www.classicgamesarcade.com/game/21679/red-plane.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by Herschel** [comment]
This is a HTTP/HTTPS CORS issue on the classicgamesarcade website. Using HTTPS works:
https://www.classicgamesarcade.com/game/21679/red-plane.html

To fix the issue, classicgamesarcade.com should serve the SWF from HTTP instead of HTTPS in this case.
