### ISSUE TITLE
getURL links take over entire Ruffle embed once clicked

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#2353]
To reproduce:
1. Have an swf that has an external link using getURL (AS2) and "_blank"
2. Click the link (a new window opens to the url)
3. Return to the Ruffle tab - Now any clicks on the Ruffle embed (ANYWHERE, not just the clickable clip) re-open the link

Expected: Returning to the Ruffle embed allows user to resume normal interaction.

A good example of this is clicking "click here to visit Luis' user page" in Luis Launch (during the in-between rounds upgrade dialogue): https://www.newgrounds.com/portal/view/503361

<img width="495" alt="Screen Shot 2021-01-09 at 1 25 45 PM" src="https://user-images.githubusercontent.com/40899110/104108986-4dd39180-527e-11eb-920d-e40b2ee2fb6b.png">

**Comment by PastoTreering** [comment]
New info on this topic, I think it would be an easy fix:

In Ruffle, when as2 `getURL` with target `_blan` or `new` is called from an `onPress` or `press` event, the mouse release event is lost due to the new window opening while the mouse press is still down, so when you return to ruffle, the entire screen is now clickable and always links to the previously-called URL.

When I use the same code and an `onRelease` or `release` event, there is no issue.

**Comment by n0samu** [comment]
This seems to be fixed now. If not, please leave a comment and I can reopen the issue.
