### ISSUE TITLE
Buttons-inside-buttons are not handled properly

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2354]
Hello,

wanted to bring this up again since it has not been fixed yet. The Reincarnation-series is a pretty big one and well executed. 2-3 of those games works fine but those with the BG Group Loop and are unplayable. Here is an example:

https://www.newgrounds.com/portal/view/523891?emulate=flash

**Comment by Herschel** [comment]
The issue seems to be a button-inside-button; the entire intro animation is a button, with the Skip button inside of it, which we don't seem to handle properly.

If you let the intro play naturally past the quote without skipping, it functions correctly.

**Comment by desertking** [comment]
Yeah but people tend to click it away. And there is a skip button that screems "click me" :D
