### ISSUE TITLE
BR5 Synergy – Auto-death

### ISSUE THREAD

**Issue by SelixGithub** [ruffle-rs/ruffle#2356]
https://user-images.githubusercontent.com/77213983/104110235-85e0d180-528a-11eb-93e8-5cac4818c9e0.mov

When starting the game, the player repeatedly dies when the game is running.
This does not occur when the game is paused.

**Comment by Toad06** [comment]
https://www.newgrounds.com/portal/view/391914

Possibly the same issue as #1211.

**Comment by Toad06** [comment]
The issue no longer happens as of nightly-2021-04-11, assume fixed by #3353.
