### ISSUE TITLE
Orb/Orb 2 – Issues with visual effects

### ISSUE THREAD

**Issue by SelixGithub** [ruffle-rs/ruffle#2357]
The examples here are from Orb 1. The working version may still look slightly different, as the "working" images are from a custom version for Coolmath. I do not have Flash on my computer, so sorry about that.
More footage of the custom versions: https://www.youtube.com/watch?v=2uJyp1eYjIA
The primary differences with the custom version are small level design changes and different appearances of some effects for walls and ground textures, however, the only 'missing' textures are some ground textures iirc. Color effects, shadow effects, and most textures should be the same.

![Screen Shot 2021-01-09 at 3 09 30 PM](https://user-images.githubusercontent.com/77213983/104110583-d4439f80-528d-11eb-8a08-1ab243ad1e50.png)
The background effect should have a grayscale effect here. In Orb2, there are similar animations, however, there, they were meant to appear orange. 
There are other instances of failed color effects in the games, however, those would hopefully be fixed with similar code.

![Screen Shot 2021-01-09 at 3 12 50 PM](https://user-images.githubusercontent.com/77213983/104110671-d1957a00-528e-11eb-8aef-a5c41db2cddb.png)
![Screen Shot 2021-01-09 at 3 10 22 PM](https://user-images.githubusercontent.com/77213983/104110677-dce8a580-528e-11eb-8b27-eb6c61026c5b.png)
Missing effects

![Screen Shot 2021-01-09 at 3 26 09 PM](https://user-images.githubusercontent.com/77213983/104110695-07d2f980-528f-11eb-91cb-ed3f29fb1a8f.png)
![Screen Shot 2021-01-09 at 3 11 29 PM](https://user-images.githubusercontent.com/77213983/104110696-09042680-528f-11eb-86be-2dc9b032627f.png)
More missing effects

Also I think the Orb might be registering collision with the crate, which is not supposed to happen.

**Comment by Herschel** [comment]
Thanks for the report, needs filter effects, closing in favor of #15.
