### ISSUE TITLE
Canyon Defense issue

### ISSUE THREAD

**Issue by liberodark** [ruffle-rs/ruffle#2358]
Hi,

First thanks for this great project.
But i can play on Canyon Defense.
Menu work sound work but when you play missile don't move is a tower defense game.
https://armorgames.com/play/1305/canyon-defense
Tested with : Nightly 2021-01-09

Best Regards

**Comment by liberodark** [comment]
Same issue on new build.

Tested with : Nightly 2021-11-27

**Comment by n0samu** [comment]
This was fixed in #7699, see #7667 (same issue).
