### ISSUE TITLE
Homestar Runner faq page goes into an infinite loop, possibly due to textHeight inaccuracies

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#2363]
The Homestar Runner FAQ page ([html](https://homestarrunner.com/faq), [swf](https://homestarrunner.com/media/pages/faq/c520544a2d-1609441320/faq.swf), [AS decompilation](https://pastebin.com/Jxi5ic2a)) contains some automatic pagination logic for dynamically spacing out the questions and answers, and putting them onto new pages when there's no more room on the old page.

Unfortunately, Ruffle seems to incorrectly calculate that the fourth question/answer pair is too large to fit on any page, even if it has a dedicated page to itself. Therefore the script gets into an infinite loop of trying to create a new blank page to put the question and answer onto, which never works. "drawPages(): category 0 question 3" gets spammed in the logs forever as a result.

**Comment by n0samu** [comment]
Similar issue: #6086

**Comment by n0samu** [comment]
Although the above mentioned issue is fixed, this issue is still occurring.

**Comment by Sonikkustar** [comment]
Seems like this might've been fixed. I was able to thumb through the FAQ without any issues & the fourth question appears to render without any issues:

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/eb1db915-32c0-4118-a1cb-7ebeece06661)

Site now uses **nightly-2023-11-24**.

**Comment by MrCheeze** [comment]
Looks like you're right. Not sure when it was fixed, but it definitely was - the swf itself was not changed.

(Note: I can see that textHeight is still not accurate to the exact pixel, but either that was not the cause of the issue, or the result is now close enough to work.)
![image](https://github.com/ruffle-rs/ruffle/assets/6541413/9206e512-c702-4bd6-ae15-5024fd96b7a1)
