### ISSUE TITLE
web: Alice is Dead Chapter 2 - Mouse interaction can't click on buttons

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2368]
Hey,

wanted to bring this up again as I was going through some games that could potentially work
At least chapter 1 worked.:

https://www.newgrounds.com/portal/view/524348?emulate=flash

Check this out. can't interact with the buttons.

**Comment by Toad06** [comment]
Thanks for the report. The source code is heavily obfuscated which is causing "unknown tag codes" errors. Once Ruffle handles that, the game will likely work.

**Comment by relrelb** [comment]
Fixed by #2636.
