### ISSUE TITLE
[NSFW] problems with pulling things with a left click in a Japanese game

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2375]
Nightly 2021-01-10

http://eye.swfchan.com/flash.asp?id=449&n=doctor.swf

1) Quite a lot of Japanese is missing (I think the "text" Japanese is missing, but not the "image" Japanese). You could tell by a blank balloons at the intro:
![image](https://user-images.githubusercontent.com/75184268/104134810-fd068a80-539c-11eb-8af8-2740a26fd313.png)
I believe it's a known issue that not all text is yet able to be displayed considering different languages and characters.

2) You cannot perform certain actions (they are available right away in Flash), like
- You cannot spead legs (click roughly here and pull left)
![image](https://user-images.githubusercontent.com/75184268/104134975-2247c880-539e-11eb-910b-ed452ff472bc.png)
- You are unable to take off stockings (click on top of them and pull down)

You can still take off the blazer by clicking on the buttons from top to bottom, and then pressing the arrow when prompted.
So I guess the types of actions which doesn't require pulling something with a mouse are working.

P.S. Never in a thousand years I would think that I'll be creating the bug report similar to this, but hey - it's still Flash!

**Comment by zohebnsr** [comment]
May be it's same related to to this game "Perim Bot". The area I need to expand by dragging and holding the pointer of square, but it won't drag at all. So it kinda dragging thing I guess, that's what you trying to do, right? Dragging to pull?

I have attached the flash and screenshot. If you start the game and select the first option "Right Leg" that option appears.

![Screen Shot 2021-01-11 at 4 13 26 AM](https://user-images.githubusercontent.com/45603200/104139251-9e083c00-53c3-11eb-8897-fd22eeb4412c.jpg)


[perim-bots.swf.zip](https://github.com/ruffle-rs/ruffle/files/5793573/perim-bots.swf.zip)

**Comment by Diatonator** [comment]
@zohebnsr Yes, the issue looks silimar. I can't drag things with a mouse left click, in both flashes.

**Comment by Herschel** [comment]
Dragging implemented in #4584. Device text rendering for CJK glyphs still needs to be implemented, tracking in #1862. Thank you!
