### ISSUE TITLE
Error loading additional swf files after main swf starts running in a multi-swf file application

### ISSUE THREAD

**Issue by kpmadden1953** [ruffle-rs/ruffle#2379]
I have a simulation I'd like to run that has a main swf that then loads others. The first loads fine from my website under Ruffle self-hosted, but as it tries to load the next, an error is reported in the browser console:

Error: Tried to instantiate non-registered character tableContent.swf    ruffle_web_bg.js:1279:12

Is this a fixable condition? What does the development team need as further information?

Thanks, Keith

**Comment by n0samu** [comment]
Looks like the same issue as #2300, which was fixed. Please let me know if I made a mistake and I can reopen the issue.
