### ISSUE TITLE
Error on https://web.archive.org/web/20140704132645/http://clickjogos.uol.com.br/Jogos-online/Acao-e-Aventura/Run-Bolt-Run/

### ISSUE THREAD

**Issue by Caio029** [ruffle-rs/ruffle#2400]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://img.clickjogos.uol.com.br/dl/1/160d4829b862126732f8d1f1553ee127/src.swf?1295677433
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://web.archive.org/web/20140704132645/http://clickjogos.uol.com.br/Jogos-online/Acao-e-Aventura/Run-Bolt-Run/
SWF URL: http://img.clickjogos.uol.com.br/dl/1/160d4829b862126732f8d1f1553ee127/src.swf?1295677433

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by Poopooracoocoo** [comment]
#3686
