### ISSUE TITLE
Error on http://photoshop-online.biz/edit_photo/

### ISSUE THREAD

**Issue by alexz006** [ruffle-rs/ruffle#2412]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://photoshop-online.biz/edit_photo/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by alexz006** [comment]
The HTTP status code is now ok, but there are many errors in the browser console and the flash player is not working (

**Comment by Poopooracoocoo** [comment]
Where is the flash player?

**Comment by alexz006** [comment]
> Where is the flash player?

I had to leave flash technology in the past as I haven't found a solution yet...
