### ISSUE TITLE
Fbook Game via Chrome fails to load

### ISSUE THREAD

**Issue by JFK27772** [ruffle-rs/ruffle#2413]
When trying to access the facebook game 'Legend of Kings - Arthur Age' via Chrome it gets stuck loading with a white screen.  I can see the following 2 errors:
1. - Asynchronous error occurred: Could not fetch movie https://d2bvxmh5dshsh8.cloudfront.net/flash/Shell.swf?v=2020082601
Context
https://apps.facebook.com/legendofkingsarthur/?fb_mail_reward=fb_fans_mail&world=153
2. - The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
Context
https://apps.facebook.com/legendofkingsarthur/?fb_mail_reward=fb_fans_mail&world=153

**Comment by n0samu** [comment]
This error occurs because the game files no longer exist on the server. Sorry, but there is nothing we can do about that.
