### ISSUE TITLE
Sound effect bugs on desktop version of Ruffle

### ISSUE THREAD

**Issue by chuu2-shakaijin** [ruffle-rs/ruffle#2414]
I found a bug in the latest version of Ruffle as of 2021-01-12 in the desktop version.
The sound effect is sounding normally in the firefox extension.

Page URL:http://www.stickpage.com/animatorvsanimationplay.shtml

The sound effect of pouring water and the sound effect of expanding the window do not sound.
![image](https://user-images.githubusercontent.com/77331544/104312462-fd786000-5519-11eb-8a67-b31004b5a5a0.png)
![image](https://user-images.githubusercontent.com/77331544/104312671-44665580-551a-11eb-9561-1eba0ab73558.png)

The sound effect that binds stick figures is ringing too long.
![image](https://user-images.githubusercontent.com/77331544/104313225-12a1be80-551b-11eb-912f-f03d20917fc5.png)

**Comment by ousia** [comment]
@chuu2-shakaijin, could you check sound issues with version 2021-01-28?

Sound of pouring water seems fixed to me.

**Comment by chuu2-shakaijin** [comment]
I checked sound issues with version 2021-01-28.
I confirmed that the sound of pouring water and the sound effect that binds stick figures was heard properly.

The sound effect of expanding the window wasn't fixed yet. 
Please also correct this. 
Thank you!

**Comment by Herschel** [comment]
minimp3 fails to decode the window expanding sound for some reason. Here's an SWF with just that sound for testing:
[sound.zip](https://github.com/ruffle-rs/ruffle/files/5890504/sound.zip)

**Comment by chuu2-shakaijin** [comment]
I checked the SWF test that uploaded it.
It played fine in the firefox extension, but not in the desktop version.

**Comment by n0samu** [comment]
Fixed by switching to Symphonia for MP3 decoding (#7894 and #4273)
