### ISSUE TITLE
Error on https://ngpc.cnh.com/CStoneEPC/launch.sls?csreqid=ae1026c6-49f4-423a-8d94-a69e41e6ddcd&locale=en

### ISSUE THREAD

**Issue by WengParts** [ruffle-rs/ruffle#2418]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(undefined: undefined)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(undefined: undefined)
    at Object.yi.f.j (<anonymous>:3:36866)
    at <anonymous>:3:35282
    at Array.reduce (<anonymous>)
    at Function.yi.e (<anonymous>:3:35259)
    at i (<anonymous>:3:6444)
    at i.next (<anonymous>)
    at <anonymous>:3:6744
    at new Promise (<anonymous>)
    at <anonymous>:3:6480
    at a (<anonymous>:3:6767)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: cnh_cornerstone_web_client_2.17.2.swf
Param quality: high
Param bgcolor: #FFFFFF
Param allowscriptaccess: sameDomain
Param allowfullscreen: true
Param flashvars: csreqid=ae1026c6-49f4-423a-8d94-a69e41e6ddcd&locale=en
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://ngpc.cnh.com/CStoneEPC/launch.sls?csreqid=ae1026c6-49f4-423a-8d94-a69e41e6ddcd&locale=en

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Herschel** [comment]
Hi, did you unzip all of the files from the Ruffle self-hosted zip? Ruffle requires all of:
 * ruffle.js
 * core.ruffle.*.js
 * *.module.wasm

**Comment by n0samu** [comment]
No response and the website seems to no longer exist.
