### ISSUE TITLE
web: Blackbeard Island - Errors - Missing integrations?

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2422]
Hey,

this game could potentially work. It has some flaws and errors.

https://www.newgrounds.com/portal/view/421234?emulate=flash

Well executed Zuma-styled game. Would be nice if you could fix these errors to get it running.

**Comment by desertking** [comment]
still open after 2 years :)

**Comment by n0samu** [comment]
Currently, after clicking the Start button to begin the game, it goes to a blank screen instead. So the game is unplayable.
