### ISSUE TITLE
Flash movie doesn't work with web extension. Only on desktop

### ISSUE THREAD

**Issue by Futurama39** [ruffle-rs/ruffle#2428]
[Page URL](https://htwins.net/goime500/)
[SWF URL](https://htwins.net/goime500/goime500type14.swf)
For this game for example while running desktop versions of the file it runs smoothly. Tested on Manjaro and Windows 10 (both 64-bit)

With the web extension (w/ Chrome dev) gives the following log:

https://gist.github.com/Futurama39/3600398d452cb6f5a7551efe67210d05

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
