### ISSUE TITLE
Não posso jogar BILLIARDS no CLICKJOGOS por falta do ADOBE FLASH PLAYER

### ISSUE THREAD

**Issue by JRKUNTURCC** [ruffle-rs/ruffle#2433]
Gente, gostaria saber como eu vou jogar meu BILLIARDS agora que tiraram o ADOBE FLASH PLAYER? vcs me indicam ai na pagina pra usar seu plug-in RUFFLE, mais dá problema e não funciona na pagina e sai um aviso de vcs que vem a seguir;

# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
# Player Info
Allows script access: false
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/5/569e8830d78c9a0c0d3a4feb52c2cb6c/src.swf
Param movie: https://img.clickjogos.com.br/dl/5/569e8830d78c9a0c0d3a4feb52c2cb6c/src.swf
Param allowScriptAccess: never
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]
# Page Info
Page URL: https://www.clickjogos.com.br/Jogos-online/Esportes/Billiards
# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32
# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined
....sim e aí, como faço pra jogar de agora em adiante heim!?

**Comment by JRKUNTURCC** [comment]
....então esperando uma pronta resposta, fico no aguardo de vcs me resolverem este problema que pra futuro será muito maior, viu ai gente!!.....e se liguem manos, eu heim!!

**Comment by ousia** [comment]
@JRKUNTURCC, eu non falo portugués.

O problema é que https://www.clickjogos.com.br/ parece que non configurou ben _Ruffle_ (https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type),

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
