### ISSUE TITLE
Eletric box 2 fail

### ISSUE THREAD

**Issue by vinzin1silva** [ruffle-rs/ruffle#2437]
eletric box 2 on click jogos doesnt work right

**Comment by Futurama39** [comment]
Proposing for deletion in favour of #1368 
 
![image](https://user-images.githubusercontent.com/12499845/104366694-0d903f80-551a-11eb-85df-b1b7d53f2883.png)

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
