### ISSUE TITLE
EdibleCastle doesn't work

### ISSUE THREAD

**Issue by shentino** [ruffle-rs/ruffle#2438]
http://www.ediblecastle.com/backtothecubeture1.html gives me a complete blank

**Comment by Futurama39** [comment]
relevant to #1368

**Comment by Lord-McSweeney** [comment]
Archive available at http://web.archive.org/web/20170920191802/http://www.ediblecastle.com/games/backtothecubeture/1.swf . The game appears to work without problems now, despite needing the unimplemented AVM2 opcode `GetDescendants`.
