### ISSUE TITLE
Masks not working in original Chibi Knight

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#2439]
Masks not working as-intended in original chibi knight (see attached image). Colored squares display around dynamically-colored player/enemies.

https://www.newgrounds.com/portal/view/526470

<img width="643" alt="Screen Shot 2021-01-12 at 12 55 07 PM" src="https://user-images.githubusercontent.com/40899110/104373705-a486d880-54d5-11eb-9d99-8441876ff9a0.png">

```
function freshMe()
{
    cul=new Color(col);
    cul.setRGB(_root.armorarray[_root.curarmor]);
    col.cacheAsBitmap=true;
    col.setMask(masker);
    col._alpha=100;
}
if (!this.inited)
{
    freshMe();
    this.inited=true;
}
```
![image](https://user-images.githubusercontent.com/40899110/104374245-7229ab00-54d6-11eb-8b8a-ba7c856fe989.png)

**Comment by Herschel** [comment]
Fixed by #1483.
