### ISSUE TITLE
Funktioniert nicht

### ISSUE THREAD

**Issue by 19lupo** [ruffle-rs/ruffle#2440]
http://www.zigiz.com/de-DE/brettspiele/21/rabbitrace.html

**Comment by Futurama39** [comment]
Could you provide any more detail? Looking at the provided link shows an image about their games being ported to HTML5. Could you clarify what this has to do with ruffle?

**Comment by 19lupo** [comment]
Rabbit Race und Four Fourteen funktionieren nicht mit Rüschen und auch nicht mit HTML5.
