### ISSUE TITLE
site not working, says report bug to ruffle

### ISSUE THREAD

**Issue by gyaru-chan** [ruffle-rs/ruffle#2457]
sending the link here, there was a message in the site telling me to come and report. 
https://www.gamesofdesire.com/hentai/the-sleeping-rape/
this is it.
and dont judge me by seeing the link. just some methods for stress relief, you know.
![Screenshot 2021-01-13 162456](https://user-images.githubusercontent.com/77388756/104444096-53521400-55bd-11eb-9ccd-46324b9bf504.png)

**Comment by Toad06** [comment]
Closing in favor of #2460 as this is the same issue. Thanks for reporting.
