### ISSUE TITLE
Error on https://e621.net/posts/1276087?q=onegai_my_melody

### ISSUE THREAD

**Issue by rainchery** [ruffle-rs/ruffle#2461]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:67736
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (<anonymous>:3:67344)
    at <anonymous>:3:35282
    at Array.reduce (<anonymous>)
    at Function.yi.e (<anonymous>:3:35259)
    at i (<anonymous>:3:6444)
    at i.next (<anonymous>)
    at <anonymous>:3:6744
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1276087?q=onegai_my_melody

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
