### ISSUE TITLE
Error on https://www.cego-online.de/cego-spielen.html

### ISSUE THREAD

**Issue by alklad** [ruffle-rs/ruffle#2463]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(undefined: undefined)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(undefined: undefined)
    at Object.yi.f.j (<anonymous>:3:36866)
    at <anonymous>:3:35282
    at Array.reduce (<anonymous>)
    at Function.yi.e (<anonymous>:3:35259)
    at i (<anonymous>:3:6444)
    at i.next (<anonymous>)
    at <anonymous>:3:6744
    at new Promise (<anonymous>)
    at <anonymous>:3:6480
    at a (<anonymous>:3:6767)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: tl_files/cegoclient/CegoLoader.swf
Param quality: high
Param allowScriptAccess: always
Param wMode: window
Param swLiveConnect: true
Param flashVars: resourceRoot=https%3A%2F%2Fwww.cego-online.de%2Fcms%2Ftl_files%2Fcegoclient%2F&hash=0bc498c90b44f1e026ad11ad683169c3b43c3796&cmsHost=https%3A%2F%2Fwww.cego-online.de
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.cego-online.de/cego-spielen.html

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by n0samu** [comment]
This is the same issue as https://github.com/ruffle-rs/ruffle/issues/7358#issuecomment-1174994331. The site uses MooTools, which overrides the Request function: https://www.cego-online.de/system/scripts/e53a815ab435.js. This interferes with Ruffle loading its files.

**Comment by danielhjacobs** [comment]
The site owner removed this content from this site. I can't test whether #14215 would have fixed this. It would have if it this was using MooTools version 1.11. Unfortunately, now this can't work because the content was removed.
