### ISSUE TITLE
Error on file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/NI1_05519.htm

### ISSUE THREAD

**Issue by ruffle-question** [ruffle-rs/ruffle#2465]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:68047
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:67974)
    at file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at Function.yi.e (file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:35865)
    at o (file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/script/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true

# Page Info
Page URL: file:///C:/LN/LabSoft/BooksDEU/1B09/NI1/NI1_05519.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by Herschel** [comment]
Due to security restrictions in web browsers, you can not run Ruffle from a file:/// URL. You must upload it to a webserver, or [run it from a local test server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server).
