### ISSUE TITLE
Error on Website

### ISSUE THREAD

**Issue by bheda91** [ruffle-rs/ruffle#2469]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(AbortError: The operation was aborted. 
)', web/src/navigator.rs:201:18

# Player Info
Allows script access: true

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by Futurama39** [comment]
Thanks for submitting the issue! Could you please provide the website that you encountered the error on?
