### ISSUE TITLE
Error on https://hry.kubayt.ml/cmc2/

### ISSUE THREAD

**Issue by kubaeu** [ruffle-rs/ruffle#2472]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://hry.kubayt.ml/cmc2/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by Futurama39** [comment]
Hello thank you for your bug report! I've went and looked at the site with the firefox ruffle plugin which gives the following popup.
![obrazek](https://user-images.githubusercontent.com/12499845/104499970-19453a00-55de-11eb-8c25-0dc2e02421ce.png)
As of now ruffle cannot play AS3 files. As it is not implemented yet. Proposing for close in favour of #1368

**Comment by Toad06** [comment]
The website is hosted `hry.kubayt.ml`, but the .wasm is hosted on `kubayt.ml`. Unfortunately the security restrictions of modern web browsers prevent data from being loaded across different domains. You must either host the files on the same domain (`hry.kubayt.ml`) or properly configure your web server to allow the CORS requests (https://enable-cors.org/server.html).
