### ISSUE TITLE
[NSFW] Problems switching on/off sound or music in a flash, sounds can get badly layered

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2473]
http://eye.swfchan.com/flash.asp?id=239119&n=Uzaki-Chan+Not+Here+Not+Now%21.swf

1) Listener is blasted with a sound if he tries to meddle with Music on/off, Ambience on/off switches, probably because the sounds are played at the max volume (sound volume is unimplemented yet AFAIK)
![image](https://user-images.githubusercontent.com/75184268/104501553-efe1d980-55f0-11eb-8a0a-1496e02360c6.png)

2) If you repeatedly (more than once) press Music off or Ambience off button, the sounds will layer depending on how many times you pressed the button, and it basically becomes an earrape (and its stoppable only if you turn down the volume/switch the sound on the tab)

**Comment by Futurama39** [comment]
Able to replicate on chrome 89 with 2021-01-12 , also to note at least for me the music and ambiance are off by default and pressing the off button turns them on.

**Comment by Diatonator** [comment]
seems to be not fixed by https://github.com/ruffle-rs/ruffle/pull/2825, maybe some other stuff is needed

**Comment by ntoonio** [comment]
Without trying out your example the description matches what happens with https://legacywebgames.static.svt.se/spel/drakens-varld/ which is a game from a Swedish kids-show.

Could be useful if someone wants to debug this in a SFW fashion

**Comment by Diatonator** [comment]
The issue persists on Nightly 2021-12-30

**Comment by Diatonator** [comment]
Still inserting the needles into the earholes on Nightly 2022-08-02

**Comment by Dinnerbone** [comment]
> 2\. If you repeatedly (more than once) press Music off or Ambience off button, the sounds will layer depending on how many times you pressed the button, and it basically becomes an earrape (and its stoppable only if you turn down the volume/switch the sound on the tab)

This happens in Flash Player too, it's just not as obvious without it being super loud.
