### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nacull** [ruffle-rs/ruffle#2475]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/3/37ae0fb9b0670148f4923e8e15fe09d4/src.swf
Param movie: https://img.clickjogos.com.br/dl/3/37ae0fb9b0670148f4923e8e15fe09d4/src.swf
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/jogos/sky-serpents

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

What does this mean ._.

**Comment by Futurama39** [comment]
Hello thank you for your bug report! I've went and looked at the site with the firefox ruffle plugin which gives the following popup.
![obrazek](https://user-images.githubusercontent.com/12499845/104506487-bfe10900-55e5-11eb-8aff-3bcc7d412b1f.png)

As of now ruffle cannot play AS3 files. As it is not implemented yet. Proposing for close in favour of #1368

**Comment by Futurama39** [comment]
However notable is that the sound does start playing even before the continue button is pressed.

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
