### ISSUE TITLE
Newgrounds preloaders with frameskip code animate incorrectly

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#2479]
Some old Newgrounds preloaders (http://www.newgrounds.com/downloads/preloaders/) have code using timers and updateAfterEvent to animate the logo independent of the SWF framerate. This does not function correctly in Ruffle currently:

https://user-images.githubusercontent.com/36278/104512432-0eb97f00-55a3-11eb-9e98-40a39db43655.mp4

**Comment by Herschel** [comment]
Still an issue as of 10/2021. Attaching preloader SWF here:
[ng_alternate_preloader.zip](https://github.com/ruffle-rs/ruffle/files/7362278/ng_alternate_preloader.zip)

**Comment by n0samu** [comment]
Testing different Ruffle builds, I see this was fixed at some point in December 2021. Not sure how though!
