### ISSUE TITLE
this SWF contains ActionScript 3 which is not yet supported by Ruffle

### ISSUE THREAD

**Issue by i008817** [ruffle-rs/ruffle#2480]
Hello
this Message appears when the SAP IQ Cockpit Application is called now, which is based on SWF without replacement so far.
details of the Application can be found here - [SAP First Guidance – SAP NLS Solution with SAP IQ](http://go.sap.com/documents/2013/03/d2ff3a4c-577c-0010-82c7-eda71af511fa.html)

any Ideas to overcome the issue?

best Regards roland

**Comment by Herschel** [comment]
ActionScript 3.0 support is still in progress, you can follow along in #1368. Closing in favor of that issue.

**Comment by i008817** [comment]
Hello Mike
Thanks for coming back to me so quickly and following - https://github.com/ruffle-rs/ruffle/issues/1368

Best Regards Roland

Roland Kramer
SAP Platform Architect for Intelligent Data & Analytics
SAP SE | Dietmar-Hopp-Allee 16 | DE-69190 Walldorf | Germany
[cid:image001.png@01D6EA02.EA7F6520]
t +49 6227 758189 | m +49 151 4260 3219 | @ roland.kramer@sap.com<mailto:roland.kramer@sap.com>
SL BW Page<https://blogs.sap.com/2016/10/11/software-application-lifecycle-management-sap-bw/> I BW on HANA first guidance<https://blogs.sap.com/2016/10/11/sap-first-guidance-collection-sap-bw-hana/> I SAP-NLS<https://blogs.sap.com/2016/10/12/sap-nls-solution-sap-bw/>
Join me online: Xing<https://www.xing.com/profile/Roland_Kramer> I Linkedln<http://de.linkedin.com/in/rolandkramer> I Online Meeting<https://lync.co.sap.com/meet/roland.kramer/EW9GO2AI> | Twitter<mailto:@RolandKramer>
Online meetings made simple with Microsoft Lync. Check out the Quick Start<https://jam4.sapjam.com/wiki/show/0baQTp887gb7rPAZhM4PyU> guide to begin.
