### ISSUE TITLE
Happy testing after the end-of-life!! Ruffle Error on https://armorgames.com/play/14404/hobo-7-heaven

### ISSUE THREAD

**Issue by 02030pllolipop** [ruffle-rs/ruffle#2492]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.J (https://agi.armorgames.com/ruffle/core.ruffle.9eec0e753f06015bcd55.js:1:20928)
    at __wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/ruffle.js:1:38584)
    at wasm-function[1474]:166
    at wasm-function[1491]:675
    at wasm-function[4122]:67
    at wasm-function[3198]:224
    at wasm-function[3748]:159
    at wasm-function[4464]:40
    at wasm-function[4339]:89
    at wasm-function[4435]:48
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/14404/hobo-7-heaven
SWF URL: https://cache.armorgames.com/files/games/hobo-7-heaven-14404.swf?v=1373587528

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by dginovker** [comment]
Works as of 0.1.0.544
