### ISSUE TITLE
Error when trying to play http://www.arcadeprehacks.com/game/14293/Vulpin-Adventure.html

### ISSUE THREAD

**Issue by gladoscore** [ruffle-rs/ruffle#2496]
Tonight I downloaded Ruffle, because I wanted to go back and play some games on arcadeprehacks. But when I open the webpage, the game doesn't load. It's just stuck on a white screen. Ruffle says its loaded the content, though. Testing/Trying to play this on Chrome, using my Windows 10 laptop. Unsure if this is an error on arcadeprehacks end. Or maybe I did something wrong? 
https://cdn.discordapp.com/attachments/670453109516140565/799196757065465866/unknown.png (screenshot of website)
And when I checked my extensions in chrome, Ruffle had two errors
https://cdn.discordapp.com/attachments/670453109516140565/799197426145558528/unknown.png (screenshot of first error)
https://cdn.discordapp.com/attachments/670453109516140565/799197474560147516/unknown.png (screenshot of second error)
I'm not good at coding things so I have no clue what these errors are referring to...

**Comment by dginovker** [comment]
Arcadeprehacks looks like a collection of games (each will either work or have their unique problems) - Create independent issues for each game instead

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
