### ISSUE TITLE
"Download SWR" button when right clicking

### ISSUE THREAD

**Issue by 10Meisterbaelle** [ruffle-rs/ruffle#2500]
I would like that if you right click, it shows a button that says "Download SWR" which downloads the SWR file so you can play it on Flashpoint if it doesn't work in Ruffle.

**Comment by torokati44** [comment]
See this similar issue: https://github.com/ruffle-rs/ruffle/issues/1885

**Comment by Toad06** [comment]
Closing as per above comment. There's also an open PR for this: #1889.
