### ISSUE TITLE
New nightly builds do not improve the emulator, they only make it worse.

### ISSUE THREAD

**Issue by vlad185** [ruffle-rs/ruffle#2501]
After the update, some games stopped working. In build 12/25/20, they worked. I thought updates would improve functionality and not vice versa.

**Comment by Herschel** [comment]
Nightly builds are unstable, so sometimes there will be regressions. Could you provide more information or a link to the content your are trying? Thank you!

**Comment by vlad185** [comment]
Thanks for the clarification.
I cannot provide a link to this content for moral and ethical reasons.
