### ISSUE TITLE
Error on https://creforma.fr/plateformeflash.php

### ISSUE THREAD

**Issue by Entretoize** [ruffle-rs/ruffle#2502]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://creforma.fr/ruffletest.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.87 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by Futurama39** [comment]
Hello thank you for your bug report! I've went and looked at the site with the firefox ruffle plugin which gives the following popup and furthermore more AVM2 Errors.
![obrazek](https://user-images.githubusercontent.com/12499845/104580878-1be77400-565e-11eb-9523-5579a1541872.png)
As of now ruffle cannot play AS3 files. As it is not implemented yet. Proposing for close in favour of #1368

**Comment by Entretoize** [comment]
Ok, I didn't have this error, thank you.

**Comment by Futurama39** [comment]
The popup only happens when using the browser extension on the local system. It does not appear when running ruffle from the server's side.
