### ISSUE TITLE
Web: Problem in playing swf file: DefineEditText

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#2509]
When opening the page:
 http://www.webgeo.de/k_021/#1
there is a message: 
 ruffle_web_bg.js:1288 Error running definition tag: DefineEditText, got Invalid data: Invalid string data

The swf-file on page #1 starts to play, but the play-button (large yellow circle) remains there.

**Comment by KMicha** [comment]
[www.webgeo.de-1610628465723.log](https://github.com/ruffle-rs/ruffle/files/5814484/www.webgeo.de-1610628465723.log)

**Comment by Herschel** [comment]
Fixed by #2636.
