### ISSUE TITLE
Erro ao tentar usar o ruffle-rs em substituição ao adobe flash.

### ISSUE THREAD

**Issue by fptarso** [ruffle-rs/ruffle#2513]
Erro ao tentar usar o ruffle-rs em substituição ao adobe flash.

**Comment by ousia** [comment]
@fptarso, non falo portugués, pero cal é o enderezo do xogo? Obrigado polo informe.

**Comment by fptarso** [comment]
www.clickjogos.com.br

**Comment by ousia** [comment]
Tódolos xogos dan o mesmo error? Se non fose así, cal e o xogo que deu o erro?

**Comment by manokara** [comment]
Precisamos do link direto para o jogo pra poder descobrir o que pode ser. Se for um jogo  recente, ele deve ser feito em ActionScript 3, que o Ruffle não suporta bem ainda.

**Comment by fptarso** [comment]
o Jogo é o BILLIARDS.

Em qui., 14 de jan. de 2021 às 16:26, Mark Nokalt <notifications@github.com>
escreveu:

**Comment by ousia** [comment]
@fptarso, non é un duplicado do informe #2433?

E mellor que peche este informe e faga unha subscripción o outro informe.

**Comment by Poopooracoocoo** [comment]
@Herschel mind closing this? this was an issue on Click Jogos' end and has since been fixed as per the above issue. :)
