### ISSUE TITLE
Tank Trouble display issues

### ISSUE THREAD

**Issue by seannorris** [ruffle-rs/ruffle#2516]
# Steps to reproduce:
- Ruffle Version: 2020-01-14
- Visit https://www.breadalbanestudy.club/game.php?ID=44&forceruffle=true
   ( SWF: https://www.breadalbanestudy.club/SWFs/TankTroubleDeathmatch.swf )
- Select a 2 player game.
- Press m and q keys to enter game.

# Issue:
Screen is partially black; scores and bullets are obscured.
![image](https://user-images.githubusercontent.com/56354169/104627778-5cabb100-568f-11eb-9342-96535983ddb7.png)

**Comment by ellieeet123** [comment]
Can confirm as of august 30, 2021

**Comment by ellieeet123** [comment]
Just checked this again, on the latest version of ruffle (14 feb 2022) it seems to be fixed.

**Comment by Toad06** [comment]
Thanks for checking. The issue was fixed by #5736.
