### ISSUE TITLE
http://webcam.zp.ua/index.php?l193#camera does not open

### ISSUE THREAD

**Issue by aba8abb** [ruffle-rs/ruffle#2519]
Error
Контекст
http://webcam.zp.ua/index.php?l193#camera
Трассировка стека
dist/core.ruffle.js:1 (dt)
dist/ea023900695f5748b1e9.module.wasm:1 (web_sys::features::gen_console::console::warn_1::h08b90512c52bb832)
dist/ea023900695f5748b1e9.module.wasm:1 (console_log::log::h3895d6ed151f462d)
dist/ea023900695f5748b1e9.module.wasm:1 (<console_log::WebConsoleLogger as log::Log>::log::h0f9658dd9a2e7510)
dist/ea023900695f5748b1e9.module.wasm:1 (log::__private_api_log_lit::h8001168094f3a2b2)
dist/ea023900695f5748b1e9.module.wasm:1 (ruffle_core::display_object::movie_clip::MovieClip::preload::{{closure}}::h10d9baddd5f93654)
dist/ea023900695f5748b1e9.module.wasm:1 (ruffle_core::tag_utils::decode_tags::hc3017a050e57c165)
dist/ea023900695f5748b1e9.module.wasm:1 (ruffle_core::display_object::movie_clip::MovieClip::preload::h35b8b7c4b420523f)
dist/ea023900695f5748b1e9.module.wasm:1 (ruffle_core::player::Player::set_root_movie::h4f161c55cd5ae1c0)
dist/ea023900695f5748b1e9.module.wasm:1 (<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc9da86c0200815b6)
dist/ea023900695f5748b1e9.module.wasm:1 (<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd5d1298760c99f41)
dist/ea023900695f5748b1e9.module.wasm:1 (wasm_bindgen_futures::task::singlethread::Task::run::hf61719043c941cb5)
dist/ea023900695f5748b1e9.module.wasm:1 (wasm_bindgen_futures::queue::Queue::new::{{closure}}::he1caab9384257aa6)
dist/ea023900695f5748b1e9.module.wasm:1 (<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd0dd9605a857d885)
dist/core.ruffle.js:1 (O)
dist/core.ruffle.js:1 (f)
1
(self.webpackChunkruffle_extension=self.webpackChunkruffle_extension||[]).push([[662],{662:(e,_,n)=>{"use strict";n.r(_),n.d(_,{Ruffl

**Comment by hatal175** [comment]
Site not available, old issue. I recommend closing unless bug owner can update the issue.

**Comment by n0samu** [comment]
In particular, neither the RTMP stream (`rtmp://91.219.52.20:1935/live/mp4:l193.stream`) nor the domain that the SWF relies on (`kirillovka.ua`) are available anymore. The [main SWF file](http://webcam.zp.ua/vid/uppod.swf) is still online though and the original webpage can be found in Wayback Machine: https://web.archive.org/web/20170824143720/http://webcam.zp.ua/index.php?l193
