### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by Bigheadmouse** [ruffle-rs/ruffle#2526]
tried opening up a game on https://escapefan.com/cons/first-escape-games/ and the advertisement would play then the page would just go to a white blank page. hope this helps out.

**Comment by Poopooracoocoo** [comment]
Were you using the extension? If so, which version?

**Comment by Bigheadmouse** [comment]
Yes I was using the extension V1 and all updates from Jan 14 - 20 and still the same result Adds would
play through then it goes to a white blank page where the game should be coming up and any adds that
are in flash also go to a white blank. Here is the website if that helps.
 https://escapefan.com/hidden-away-01/
I also sent your website to them so they could put in the ruffle on their end.

________________________________

**Comment by n0samu** [comment]
This was fixed a long time ago by #4665
