### ISSUE TITLE
Error on http://meinbrutalo.muxxu.com/t/36561

### ISSUE THREAD

**Issue by Syvio** [ruffle-rs/ruffle#2528]
# Error Info
Error: Ruffle is panicking!

# Player Info
Allows script access: true

# Page Info
Page URL: http://meinbrutalo.muxxu.com/t/36561

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by n0samu** [comment]
No information about the panic provided, closing
