### ISSUE TITLE
Plugin polyfill not always executing early enough

### ISSUE THREAD

**Issue by adrian17** [ruffle-rs/ruffle#2530]
Based on a report from Discord.
On http://markmarek.org/ANIMATIONS/KABLAM.html , with the extension installed on FF, it appears that sometimes the Flash version check happens before the extension installs the polyfill? It does work after refreshing once or twice, though.
I heard it's even worse on Chrome.

**Comment by n0samu** [comment]
I can no longer reproduce this problem, I guess the issue can be closed?

**Comment by n0samu** [comment]
Comment from Dinnerbone:
> Should have been fixed by the version negotiation; and then reinforced by mv3/"main world"
