### ISSUE TITLE
Some flash loops (or maybe any normal file with constant sound) in the browser...

### ISSUE THREAD

**Issue by TheAlienDrew** [ruffle-rs/ruffle#2532]
... when leaving the tab, the visuals will tend to lag behind the audio.

**Comment by torokati44** [comment]
This is also an issue on: https://z0r.de/2282
Just switching away from the tab for a couple seconds completely throws the animation and the music out of sync.

**Comment by torokati44** [comment]
Maybe a duplicate of #347?

**Comment by TheAlienDrew** [comment]
Might as well close this then.
