### ISSUE TITLE
Games on 2keysgames.com not viewable

### ISSUE THREAD

**Issue by wheresthecrow** [ruffle-rs/ruffle#2533]
After attempting to run flash games from the 2keysgames site, I was unable to play any of the games on the site using Ruffle (usually if a game is not yet playable, it will let me know beforehand). I don't think they are Actionscript 3 games as they are much older and once again, I was not notified of this. I've had a similar issue with dressupgames.com also (at least with their older games).

I figured I would report this in case these games are of a file type not yet recognised by Ruffle.

Thank you so much for keeping nostalgic flash games alive! 😁

Edit: I'm using the Nightly 2021-01-15 update

**Comment by n0samu** [comment]
Seems like the website does not exist anymore and the games are sitelocked, preventing archived versions from working. I'll test again once #8185 is merged.

**Comment by n0samu** [comment]
Just tested it and spoofing the URL works! With the Ruffle desktop app, you can play these games by downloading the SWF files and running commands like this:
`ruffle --spoof-url http://www.2keysgames.com/games/escape_goldenrod_room.swf escape_goldenrod_room.swf`
