### ISSUE TITLE
Some sounds missing from flash content

### ISSUE THREAD

**Issue by wheresthecrow** [ruffle-rs/ruffle#2534]
When playing some games, I have noticed that some sounds are missing from them (usually sounds the game will play when interacting with something (e.g. the pouring sound missing when dragging a bowl to another object in a cooking game). One game I have noticed with this issue is this one: https://web.archive.org/web/20111228000407/http://tubegame.com/how_to_make_california_pizza.html

Some games with the background music playing on a loop become silent after the music has played through once also. This is not a consistent issue as most games work OK but I figured it was worth reporting in case anything could be done about it.

Edit: I am using the Nightly 2021-01-15 update

**Comment by n0samu** [comment]
These problems seem to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
