### ISSUE TITLE
web: Battle of Lemolad - Mouse cursor invisible / Buttons can't be clicked

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2547]
Hello,

want to report another AS2 game not working correctly. The mouse cursors is invisible, the game uses a custom one. Also the loader is a little bugged and you can't click on some buttons:

https://www.newgrounds.com/portal/view/519168?emulate=flash

**Comment by adrian17** [comment]
I can see the mouse and the buttons seems to work, so looks like it's fixed. Let us know if that's not the case for you.
