### ISSUE TITLE
Web: Ruffle couldn't parse SWF.

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#2550]
On http://www.webgeo.de/g_003/#2  ruffle shows error:

Couldn't parse SWF. This may or may not be a bug in Ruffle, please help us by reporting it to https://github.com/ruffle-rs/ruffle/issues and include the swf that triggered it.

The images on the flash-module flicker and the play-button doesn't disappear.

[www.webgeo.de-1610718385952.log](https://github.com/ruffle-rs/ruffle/files/5820847/www.webgeo.de-1610718385952.log)

**Comment by KMicha** [comment]
Seems to work now...

**Comment by Toad06** [comment]
Yup, this one was also fixed by #2636.
