### ISSUE TITLE
Crash when using TextField.wordWrap and autoSize

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#2551]
I tried sheppards software, and tried to use geography Africa. It worked for a bit, but then it crashed and stopped working and it happens over and over.

**Comment by ousia** [comment]
@poyo77, many thanks for your report.

Could you provide the address of the Flash animation you tested?

**Comment by poyo77** [comment]
Well do only thing I have is a link to that animation. Maybe try to see whats wrong. https://www.sheppardsoftware.com/Africa/Africa_G1_1024_768.html

**Comment by Toad06** [comment]
When dropping a country to a wrong place, the browser freezes right after `incorrect_txt.htmlText = incorrectMsg_str;` (inside `function createIncorrectText`) is executed.

Here's a sample that crashes in Ruffle:
```
_root.createTextField("crashtest",1,0,0,200,20);
_root.crashtest.autoSize = true;
_root.crashtest.wordWrap = true;
_root.crashtest.html = true;
_root.crashtest.htmlText = "Hello!";
trace("No crash?");
```

There seems to be an issue when the `autoSize` and `wordWrap` properties are both set to true, as removing any of them (or setting it to `false`) prevents the crash from happening.

**Comment by squiddy** [comment]
Doesn't crash anymore with https://github.com/ruffle-rs/ruffle/commit/efdb9c153dff2d4339c6cddbb6f9adaa0ffa8411 applied. It is not showing anything though.

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
