### ISSUE TITLE
Web: Missing 'Umlaute' in navigation menu at the bottom of the page

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#2552]
There is some text on the page, that misses special characters:

"zurck"  instead of  "zurück"   
"Lsung" instead of "Lösung"

This is probably because of different character code?
Other areas on the page show the 'Umlaute' in the right way, i.e. "zusätzlich lösbare" above the diagram.
![umlaute](https://user-images.githubusercontent.com/1667683/104746294-5b41bd80-574f-11eb-97cb-fd4d87eb37a7.png)

http://www.webgeo.de/g_002/#4

**Comment by MrCheeze** [comment]
Sounds like another instance of https://github.com/ruffle-rs/ruffle/issues/1862.

**Comment by ousia** [comment]
@KMicha, would it be possible that missing characters rely on device fonts?

Device fonts are fonts not embedded in the SWF file.

_zusätzlich lösbare_ could be using an embedded font in the SWF file.

**Comment by torokati44** [comment]
The mentioned missing characters were added in #6224.
