### ISSUE TITLE
windows 7 not compatible

### ISSUE THREAD

**Issue by imoulas** [ruffle-rs/ruffle#2554]
I'm trying to run ruffle.exe to a windows 7 32 bit machine and i'm getting the error 

This version of ruffle.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

i'm using the latest version (nightly 2021-1-15)

any ideas!?

**Comment by Herschel** [comment]
Currently we don't supply 32-bit builds, only 64-bit, so a 64-bit machine is required for the nightly build. Sorry for the trouble.
If you can build from source, you could build for the `stable-i686-pc-windows-msvc` target to get a 32-bit build.
There's an open issue for us to do automated 32-bit builds as well (https://github.com/ruffle-rs/ruffle/issues/1850).

**Comment by Herschel** [comment]
32-bit x86 nightly builds are now available thanks to #4105.
