### ISSUE TITLE
Error on https://e621.net/posts/1661822?q=sylveon+pok%C3%A9philia+animated

### ISSUE THREAD

**Issue by Tenki156** [ruffle-rs/ruffle#2555]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:68257
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (<anonymous>:3:67865)
    at <anonymous>:3:35558
    at Array.reduce (<anonymous>)
    at Function.Si.e (<anonymous>:3:35535)
    at i (<anonymous>:3:6450)
    at i.next (<anonymous>)
    at <anonymous>:3:6750
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1661822?q=sylveon+pok%C3%A9philia+animated

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-15
Channel: nightly
Built: 2021-01-15T01:03:45.335Z
Commit: 09a48a71d8608803fd5dba4343c5f10c928f9652

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
