### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by galocorno** [ruffle-rs/ruffle#2562]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/6/640af57d30370490a5ed5391afa08b2f/src.swf
Param movie: https://img.clickjogos.com.br/dl/6/640af57d30370490a5ed5391afa08b2f/src.swf
Param allowScriptAccess: never
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/jogos/super-mario-flash-2-desert-edition

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by ousia** [comment]
@galocorno, it seems that https://www.clickjogos.com.br/ hasn’t the server properly configured for _Ruffle_ (as explained in https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type).

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
