### ISSUE TITLE
Worked at first, but then crashed

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#2569]
[Screenshot from 2021-01-15 19-43-52](https://user-images.githubusercontent.com/72718908/104793923-28f18980-576a-11eb-95c6-f3712ec45b68.png)
It worked at first, but then when I tried dragging a random country it crashed and stopped working. I'm not sure if it used action script 3 since it didn't warn me. 
![Screenshot_2021-01-15 Raft Wars](https://user-images.githubusercontent.com/72718908/104796289-7b3aa680-577a-11eb-8316-95453ce36ffb.png) For raft wars, when I skipped or the cut scene ends it cuts to black.

**Comment by ousia** [comment]
@poyo77, which is the address of the animation that gives problems to you?

**Comment by poyo77** [comment]
I have a link to the game. The games still hasn't been converted to html5 yet, so I still don't know. The same issues also happen in other flash animations/games. It didn't say anything about action script3.

**Comment by ousia** [comment]
The address seems to be https://www.coolmathgames.com/games/raftwars_coolmath2_0.swf.

But it displays a message about Raft Wars being site locked (which I’m afraid it might not help to fix the issue).

I even wonder whether this isn’t intended to avoid being played and copied by another SWF player.

**Comment by n0samu** [comment]
Looks like Coolmath moved the SWF here to avoid the sitelock: https://www.coolmath-games.com/sites/cmatgame/files/games/raftwars_coolmath2_0.swf
(It's the same SWF file as above, just a different URL.)
Anyway, the game seems to be working fine now, so I'll close the issue. Please leave a comment if anything is still broken and I can reopen it.
