### ISSUE TITLE
Error on https://e621.net/posts/440614?pool_id=3682

### ISSUE THREAD

**Issue by RosettaMoon66** [ruffle-rs/ruffle#2571]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:68257
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (<anonymous>:3:67865)
    at <anonymous>:3:35558
    at Array.reduce (<anonymous>)
    at Function.Si.e (<anonymous>:3:35535)
    at o (<anonymous>:3:2085)
    at o.next (<anonymous>)
    at <anonymous>:3:2385
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/440614?pool_id=3682

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
