### ISSUE TITLE
Error on https://inkbunny.net/s/1017520

### ISSUE THREAD

**Issue by rainchery** [ruffle-rs/ruffle#2572]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:68257
    at Array.forEach (<anonymous>)
    at Object.Si.f.wasm (<anonymous>:3:67865)
    at <anonymous>:3:35558
    at Array.reduce (<anonymous>)
    at Function.Si.e (<anonymous>:3:35535)
    at o (<anonymous>:3:2085)
    at o.next (<anonymous>)
    at <anonymous>:3:2385
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://hk.ib.metapix.net/files/full/1400/1400159_obor_usagimono.swf
Param movie: https://hk.ib.metapix.net/files/full/1400/1400159_obor_usagimono.swf
Param allowScriptAccess: never
Param wmode: direct
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://inkbunny.net/s/1017520

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by GreenReaper** [comment]
Needed unsafe-eval on Chrome due to their interpretation of CSP, resolved by us self-hosting and finding that out ourselves.
wasm-[unsafe-]eval would be better but right now it's not a thing.
