### ISSUE TITLE
Error on https://mailstudent.bmstu.ru/Pronto4/

### ISSUE THREAD

**Issue by sashaqwert** [ruffle-rs/ruffle#2574]
![изображение](https://user-images.githubusercontent.com/24974508/104808045-afeb4400-57f4-11eb-9dbd-618d977a418e.png)

OS: Windows 10 x64
Firefox 84.0.2
URL:  https://mailstudent.bmstu.ru/Pronto4/

**Comment by Toad06** [comment]
Thanks for the report. ActionScript 3.0 support is still in progress, you can follow along in #1368. Closing in favor of that issue.
