### ISSUE TITLE
Error on http://jmkit.com/games/jinx&minx'stowerescape

### ISSUE THREAD

**Issue by jinxbunny** [ruffle-rs/ruffle#2577]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(missing: http://jmkit.com/ruffle/core.ruffle.fb39aa46f71a4c17d772.js)
Error stack:
```
http://jmkit.com/ruffle/ruffle.js:1:37554
http://jmkit.com/ruffle/ruffle.js:1:35939
reduce@[native code]
http://jmkit.com/ruffle/ruffle.js:1:35922
http://jmkit.com/ruffle/ruffle.js:1:2646
generatorResume@[native code]
http://jmkit.com/ruffle/ruffle.js:1:2949
Promise@[native code]
http://jmkit.com/ruffle/ruffle.js:1:2709
o@http://jmkit.com/ruffle/ruffle.js:1:2968
C@http://jmkit.com/ruffle/ruffle.js:1:14386
A@http://jmkit.com/ruffle/ruffle.js:1:24308
createElement@[native code]
fromNativeEmbedElement@http://jmkit.com/ruffle/ruffle.js:1:25611
H@http://jmkit.com/ruffle/ruffle.js:1:29143
Y@http://jmkit.com/ruffle/ruffle.js:1:30607
polyfill@http://jmkit.com/ruffle/ruffle.js:1:35195
init@http://jmkit.com/ruffle/ruffle.js:1:34349
init@[native code]
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://jmkit.com/games/jinx&minx'stowerescape

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-09
Channel: nightly
Built: 2021-01-09T00:51:37.925Z
Commit: 828dbcb00c0a25b861ad844a49ac058bb63c73c1

**Comment by Poopooracoocoo** [comment]
Have you fixed the issue? That link now 404s.

**Comment by llacb47** [comment]
Works fine: `https://www.jmkit.com/towerescape/index.html`

**Comment by Poopooracoocoo** [comment]
Closing as issue has been fixed because site has updated their version of Ruffle.
