### ISSUE TITLE
Error on http://runouw.com/games/sm63/

### ISSUE THREAD

**Issue by Pengwino** [ruffle-rs/ruffle#2578]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1301:9

# Player Info
Allows script access: true

# Page Info
Page URL: http://runouw.com/games/sm63/
SWF URL: http://runouw.com/games/sm63/sm63game.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z
Commit: c1c1c59bb51d2d20d2e601b5e4ff75ddfca528cb

**Comment by Toad06** [comment]
Fixed by #2529. The game still has other issues (cc. #2448) but it should no longer crash. Thanks for reporting.
