### ISSUE TITLE
avm1: target_clip behavior difference depending on SWF version

### ISSUE THREAD

**Issue by relrelb** [ruffle-rs/ruffle#2580]
On SWF6, calling a function changes the active `target_clip` according to the *callee's* definition location.
Currently Ruffle handles this behavior as expected:
https://github.com/ruffle-rs/ruffle/blob/9df7facdb8d37a5d007a13c25efcc176ed4675e0/core/src/avm1/function.rs#L324

However SWF5 seems to behave differently. Instead of changing the active `target_clip`, it remains unchanged and same as the *caller's* `target_clip`.
Ruffle doesn't handle this behavior and always behaves like SWF6.

The attached examples are identical except for their SWF version (5 vs. 6).
Notice that only the yellow circle moves in `target_clip_swf5.zip`, but both the yellow circle and the green square move in `target_clip_swf6.zip`.

[target_clip_swf5.zip](https://github.com/ruffle-rs/ruffle/files/5824916/target_clip_swf5.zip)
[target_clip_swf6.zip](https://github.com/ruffle-rs/ruffle/files/5824918/target_clip_swf6.zip)

Changing the line mentioned above from `af.base_clip,` to `activation.base_clip,` (plus making it `pub`) seem to change the behavior from SWF6 to SWF5. I feel like selecting either `af.base_clip` or `activation.base_clip` depending on the SWF version is the proper fix, but I'm not 100% sure about it.

**Comment by Herschel** [comment]
Seems accurate to me, would you like to make a PR with the fix and test case? Here's another test case using `gotoAndPlay` (which affects the target clip):
[gotoandplay_swf5.zip](https://github.com/ruffle-rs/ruffle/files/5825366/gotoandplay_swf5.zip)
