### ISSUE TITLE
Trollface Quest makes a loud noise and flashing screen upon loading

### ISSUE THREAD

**Issue by SexySpai** [ruffle-rs/ruffle#2586]
Title, I got the .swf file from Internet Archive so I'm not sure if it's legit. It's not an AS3 game so I didn't get a warning

UPDATE: It actually does use ActionScript3 the warning just didn't pop up.

**Comment by Toad06** [comment]
If it's AS3, then let's close this in favor of #1368 since it's still a work in progress. Thanks for reporting.
