### ISSUE TITLE
make build.rs easy. Add more than information with build-time ？e.g shadow-rs

### ISSUE THREAD

**Issue by baoyachi** [ruffle-rs/ruffle#2587]
make [build.rs](https://github.com/ruffle-rs/ruffle/blob/master/desktop/build.rs) write easy.

Consider https://github.com/baoyachi/shadow-rs

**Comment by Herschel** [comment]
Thanks for the link, our build.rs is fairly stable and easy right now so I don't think it's worth pulling in an additional dependency. I will keep your crate in mind for future projects.
