### ISSUE TITLE
NVM. Thank You Btw

### ISSUE THREAD

**Issue by shooooji** [ruffle-rs/ruffle#2595]
Maybe because it happens due to the fact that it needs to be opened in a microsoft.

**Comment by manokara** [comment]
We're going to fix it when we can, but first you have to tell us what happened and where (game link).

**Comment by shooooji** [comment]
Here is the name of the game "RE5 Chris’ Capture" and the link for this is
here:
https://www.yaoihavenreborn.com/animation/bara-animation/re5-chris-capture
