### ISSUE TITLE
Error on http://www.gizdic.com/freegames/

### ISSUE THREAD

**Issue by gnet-lara** [ruffle-rs/ruffle#2596]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.gizdic.com/freegames/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Toad06** [comment]
Answered in #2597.
