### ISSUE TITLE
render directory location

### ISSUE THREAD

**Issue by relrelb** [ruffle-rs/ruffle#2601]
As of #533, the rendering backends are located under the top-level [`render/`](https://github.com/ruffle-rs/ruffle/tree/master/render) directory.
But I wonder whether `core/src/backend/render/` is a more suitable location, because while it still remains platform-agnostic, it also has some pros:
1. Consistent with the existing [`core/src/backend/audio/`](https://github.com/ruffle-rs/ruffle/tree/master/core/src/backend/audio) directory.
2. Reduces the number of top-level directories in the repository and therefore improves its organized structure.

**Comment by Herschel** [comment]
Putting a sub-crate in a `src` directory feels odd to me (`src` should be other .rs files, and this pattern is also followed by [other Rust multi-crate projects](https://github.com/servo/pathfinder)). But maybe moving these into `core/render` or core/backend/render` would be good?

I was originally considering doing to opposite, and turning all backends into separate crates (`audio/web`, etc.), but it seemed like overkill, even moreso now that we have quite a few backend types.

**Comment by shentino** [comment]
Why is this closed?
