### ISSUE TITLE
The swf file inserted with another site link does not run at all. I'll ask for the revision.

### ISSUE THREAD

**Issue by hoiung1** [ruffle-rs/ruffle#2603]
Hello. If I upload the flash swf file directly to the hosting I run and run it, it works normally, but if I try to upload a linked file from another place, the screen is not displayed. We will fix it to run normally with swf linked to other sites. I checked the link to the site, but I never blocked it, but it doesn't work with ruffle.
example URL)
http://zonzaemgame.com/bbs/board.php?bo_table=game_Kids_EDU&wr_id=5
Source Code)
<ruffle-embed width="100%" height="550" style="display: block !important;" src="http://cfile30.uf.tistory.com/media/ 99D9DB4E5D5BF0FF2AEE45" type="application/x-shockwave-flash" allownetworking="internal" allowscriptaccess="never"></ruffle-embed>

**Comment by hoiung1** [comment]
Hello. If I upload the flash swf file directly to the hosting I run and run it, it works normally, but if I try to upload a linked file from another place, the screen is not displayed. We will fix it to run normally with swf linked to other sites. I checked the link to the site, but I never blocked it, but it doesn't work with ruffle.


example URL)
http://zonzaemgame.com/bbs/board.php?bo_table=game_Kids_EDU&wr_id=5

Source Code)
<embed width="100%" height="550" style="display: block !important;" src="http://cfile30.uf.tistory.com/media/ 99D9DB4E5D5BF0FF2AEE45" type="application/x-shockwave-flash" allownetworking="internal" allowscriptaccess="never"></embed>

**Comment by Herschel** [comment]
Unfortunately, this is due to security restrictions in modern browsers. CORS restrictions prevent data from being loaded across domains.
The SWF file must be hosted on the same domain, or the domain it is hosted on must be configured to allow the appropriate CORS requests (https://enable-cors.org/).
