### ISSUE TITLE
ActionScript3 is not supported by Ruffle

### ISSUE THREAD

**Issue by hj200724** [ruffle-rs/ruffle#2611]
This SWF contains ActionScript3 which is not yet supported by Ruffle.The movie may not work as intended.
By Installing the browser extension.

**Comment by bls1999** [comment]
This is a message notifying you that the SWF you're viewing isn't supported by Ruffle yet.

**Comment by hj200724** [comment]
How long can support it?

**Comment by 10Meisterbaelle** [comment]
Look at this issue: #1368

**Comment by hj200724** [comment]
OK,Thanks

**Comment by Toad06** [comment]
ActionScript 3.0 support is still in progress, you can follow along in #1368. Closing in favor of that issue.
