### ISSUE TITLE
Error on https://vb.jiggmin2.com/

### ISSUE THREAD

**Issue by bls1999** [ruffle-rs/ruffle#2612]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://vb.jiggmin2.com/volly-bounce.swf
Param scale: noscale
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://vb.jiggmin2.com/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Poopooracoocoo** [comment]
New error: 
![image](https://user-images.githubusercontent.com/51363864/105367757-e68de800-5c54-11eb-8e96-dbcf6053bcf7.png)

**Comment by bls1999** [comment]
> New error:
> ![image](https://user-images.githubusercontent.com/51363864/105367757-e68de800-5c54-11eb-8e96-dbcf6053bcf7.png)

I'll close this issue and open a new one with the new error, referencing this one.

**Comment by Poopooracoocoo** [comment]
@bls1999 This issue is actually something that needs to be fixed on the site. :) 
Ruffle can't do anything on their end because of how security works on the web. I don't know much about it other than that though. :(

**Comment by bls1999** [comment]
> @bls1999 This issue is actually something that needs to be fixed on the site. :)
> Ruffle can't do anything on their end because of how security works on the web. I don't know much about it other than that though. :(

Yeah, I realized that as soon as you showed the new error. I wonder why it was showing the old error before...

At any rate, thanks a bunch for the update! I'll look at how I can fix it in my environment.
