### ISSUE TITLE
Emulation on Newgrounds doesn't work at all (Extension)

### ISSUE THREAD

**Issue by 10Meisterbaelle** [ruffle-rs/ruffle#2613]
If I'm on the Newgrounds website and try playing a game, it doesn't show the Ruffle play icon and doesn't do anything. This issue was not there since an update

**Comment by 10Meisterbaelle** [comment]
That happens on three browsers I have tried it on: Chrome, Firefox and
Safari.
I think it's a problem on the website, because it no longer shows "Flash
Player is no longer supported" when I don't use the extension.

Am Do., 21. Jan. 2021 um 01:21 Uhr schrieb Mike Welsh <
notifications@github.com>:

**Comment by ousia** [comment]
https://www.newgrounds.com/portal/view/775160 doesn’t display any Flash animation, either with Ruffle, or not (no Flash deprecatntion message).

@10Meisterbaelle, could you provide the address of a game that displays “Flash Player is no longer supported” when the extension is disabled.

Otherwise, it is really hard to check the same contents.

**Comment by ousia** [comment]
https://www.newgrounds.com/portal/view/284305 doesn’t provide any Flash animation either.

Just in case it helps.

**Comment by ousia** [comment]
Confirmed, https://www.newgrounds.com/portal/view/593275 doesn’t work either.

I’m using Firefox on Linux.

**Comment by ousia** [comment]
@Herschel,

as mentioned by @Alfernus in #2774, https://sonucais.newgrounds.com/news/post/1137244 explains that appending `/format/flash?emulate=flash` to the URL makes NG work again.

According to the explanation, this seems to be the way to force Ruffle emulation.

I hope it might help.

**Comment by 10Meisterbaelle** [comment]
https://de.y8.com/games/bubbels (I just took a random flash game from
google, also this only shows in Chrome and other Chromium based browsers)

Am Fr., 22. Jan. 2021 um 23:24 Uhr schrieb Pablo Rodríguez <
notifications@github.com>:

**Comment by n0samu** [comment]
This doesn't seem to be an issue anymore as far as I can tell
