### ISSUE TITLE
Error on https://www.txori.com/index.php?static5/dbdevolution

### ISSUE THREAD

**Issue by StClairSSBlueKaioken** [ruffle-rs/ruffle#2625]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 72 65 73 65 @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 72 65 73 65 @+0
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: data/documents/dbz/dbdev.swf?id=1610632776
Param quality: high
Param AllowScriptAccess: sameDomain 
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://www.txori.com/index.php?static5/dbdevolution

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13020.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.119 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by danielhjacobs** [comment]
This issue is very old, but in general, this error message usually means a cached version of Ruffle is interfering with a newer version. If encountering this issue, it's best to clear your cache and reload the page.
