### ISSUE TITLE
Ruffle Error on https://www.sploder.com/games/members/geoff/ruffle/crystal-chamber/

### ISSUE THREAD

**Issue by lizardbxyte** [ruffle-rs/ruffle#2639]
# Error Info
Error name: ReferenceError
Error message: Can't find variable: WebAssembly
Error stack:
```
https://www.sploder.com/ruffle/ruffle.js:1:66918
forEach@[native code]
wasm@https://www.sploder.com/ruffle/ruffle.js:1:66567
https://www.sploder.com/ruffle/ruffle.js:1:34977
reduce@[native code]
e@https://www.sploder.com/ruffle/ruffle.js:1:34960
https://www.sploder.com/ruffle/ruffle.js:1:2230
generatorResume@[native code]
https://www.sploder.com/ruffle/ruffle.js:1:2533
initializePromise@[native code]
Promise@[native code]
r@https://www.sploder.com/ruffle/ruffle.js:1:2293
o@https://www.sploder.com/ruffle/ruffle.js:1:2596
E@https://www.sploder.com/ruffle/ruffle.js:1:13940
R@https://www.sploder.com/ruffle/ruffle.js:1:24971
createElement@[native code]
fromNativeObjectElement@https://www.sploder.com/ruffle/ruffle.js:1:27047
$@https://www.sploder.com/ruffle/ruffle.js:1:28074
z@https://www.sploder.com/ruffle/ruffle.js:1:29645
polyfill@https://www.sploder.com/ruffle/ruffle.js:1:34233
init@https://www.sploder.com/ruffle/ruffle.js:1:33387
init@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /fullgame_b12.swf?onsplodercom=true&s=k2tpjz1n
Param base: https://www.sploder.com
Param bgcolor: #333333
Param scale: noscale
Param salign: tl
Param menu: false
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined

# Page Info
Page URL: https://www.sploder.com/games/members/geoff/ruffle/crystal-chamber/

# Browser Info
Useragent: Mozilla/5.0 (Nintendo Switch; WifiWebAuthApplet) AppleWebKit/606.4 (KHTML, like Gecko) NF/6.0.1.16.10 NintendoBrowser/5.1.0.20923
OS: Nintendo Switch

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-28
Channel: nightly
Built: 2020-12-28T00:42:22.474Z
Commit: 8d707bc6ab747ae5039ce629f07c09aabfac2553

**Comment by Toad06** [comment]
Thanks for the report. Unfortunately, it seems like this browser lacks the `WebAssembly` feature. Ruffle won't be able to run without it, but should probably fail more gracefully.

**Comment by danielhjacobs** [comment]
The Nintendo Switch browser does not have the necessary features to support Ruffle. There is now a better error message when WASM is unsupported.
