### ISSUE TITLE
Movies on Bridgebase at https://www.bridgebase.com/store/movies/viewer.php?id=171

### ISSUE THREAD

**Issue by Don4Bridge** [ruffle-rs/ruffle#2640]
Hi, there is a collection of Movies athttps://www.bridgebase.com/store/movies/ which require flash.  When attempting to run them, we get the "This SWF contains  Action Script 3 which is not yet supported by Ruffle"message.

This seems so standalone, I would hope it could be an easy fix.

Thanks
Don

**Comment by Toad06** [comment]
Thanks for reporting an issue. As you mentioned, ActionScript 3.0 support is still in progress, you can follow along in #1368. Closing in favor of that issue.
