### ISSUE TITLE
Error on https://server/pluginfile.php/3926326/mod_scorm/content/1/runtime/rtleo/scorm-flo.html?sco=..%2F..%2Fcontent%2Fedit_les_asp.flo&width=800&height=570&recording=true

### ISSUE THREAD

**Issue by imatotek** [ruffle-rs/ruffle#2643]
# Error Info
Error name: CompileError
Error message: wasm validation error: at offset 4: failed to match magic number

# Player Info
Allows script access: true

# Page Info
Page URL: https://server/pluginfile.php/3926326/mod_scorm/content/1/runtime/rtleo/scorm-flo.html?sco=..%2F..%2Fcontent%2Fedit_les_asp.flo&width=800&height=570&recording=true

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by n0samu** [comment]
URL provided seems to be a local URL
