### ISSUE TITLE
web: Mahjong Tower - Unknown tag code: 253 / Avm1::pop: Stack underflow

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2644]
Hey,

a much liked game on my site is not working. Stuck on the pre-loader. It's made in AS2

https://www.newgrounds.com/portal/view/384031?emulate=flash

**Comment by Toad06** [comment]
This will be fixed by #2636.

**Comment by Herschel** [comment]
Fixed by #2636, thank you!
