### ISSUE TITLE
Web: Images are flickering (instead of dynamically triggered)

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#2650]
A lot of flash-files show flickering images.
Instead their visibility should be triggered by events like toggling buttons.

Examples:

http://www.webgeo.de/g_001/#2
http://www.webgeo.de/g_001/#3
http://www.webgeo.de/g_001/#6
http://www.webgeo.de/g_003/#4

Maybe related to "Error running definition tag: PlaceObject2, got Invalid data: Invalid string data"

[www.webgeo.de-1611060805370.log](https://github.com/ruffle-rs/ruffle/files/5835940/www.webgeo.de-1611060805370.log)

**Comment by KMicha** [comment]
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z

**Comment by Toad06** [comment]
Good news, this will also be fixed by #2636.

**Comment by Herschel** [comment]
Fixed by #2636, thank you!
