### ISSUE TITLE
Web: Quiz is flickering, toggles between possible solutions.

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#2652]
The quiz on 
 http://www.webgeo.de/g_045/#5
is not static, but toggles between different states.

In the console-log there is a message:
 "ruffle_web_bg.js:1288 Couldn't parse SWF. This may or may not be a bug in Ruffle..."

[www.webgeo.de-1611061088967.log](https://github.com/ruffle-rs/ruffle/files/5835970/www.webgeo.de-1611061088967.log)

**Comment by KMicha** [comment]
Version: 0.1.0
Name: nightly 2021-01-14
Channel: nightly
Built: 2021-01-14T01:08:37.174Z

**Comment by Toad06** [comment]
This will be fixed by #2636.

**Comment by Herschel** [comment]
Fixed by #2636.
