### ISSUE TITLE
Papa's pizzeria almost playable

### ISSUE THREAD

**Issue by CorneliusCornbread** [ruffle-rs/ruffle#2656]
Papa's pizzeria almost playable on coolmathgames: https://www.coolmathgames.com/0-papas-pizzeria

Small UI glitches, unable to get past the first level. Otherwise completely playable. Reproduced with Ruffle nightly 2021-1-17

**Comment by Poopooracoocoo** [comment]
In Ruffle the pizza toppings don't appear. 
Ruffle:
![image](https://user-images.githubusercontent.com/51363864/105567552-c9593680-5d86-11eb-94b9-4209bbe24f67.png)


Flash Player:
![image](https://user-images.githubusercontent.com/51363864/105567543-b3e40c80-5d86-11eb-905d-6fbbe2ab4277.png)

In Ruffle dragging and dropping doesn't work, and so requires another click. Dropping toppings outside of the pizza doesn't return the topping to its container and instead puts it on the station.

Video with Flash on the left and Ruffle's web demo in Chrome on the right: 

https://user-images.githubusercontent.com/51363864/105567657-a418f800-5d87-11eb-9c59-cd77d271f834.mp4

And as you can see in that video and screenshot, there's a lot of empty space around the game. Especially above it.

**Comment by n0samu** [comment]
These problems seem to be fixed now!
