### ISSUE TITLE
Firefox and Chrome Plug-In's

### ISSUE THREAD

**Issue by nlangdon1** [ruffle-rs/ruffle#2657]
Hello,

I am very anxious to get Ruffle working in Firefox or Chrome.  I have Hauppauge Computerwork's Broadway devices that stream my DVR to my phone and/or computer.  When I have Ruffle installed on Chrome or Firefox I get the error below when I try to stream video. 

![image](https://user-images.githubusercontent.com/77511703/105075811-1c598380-5a3f-11eb-89ff-54bd68d57d9e.png)

In case the file doesn't work the verbiage in the error is "TheSWF contains ActionScript 3 which is not yet supported by Ruffle.  The movie may not work as intended."

Will this functionality eventually work, and is a Ruffle eventually work on my Samsung Note 10+?

I will happily donate if you get this working!   :)

**Comment by Herschel** [comment]
ActionScript 3.0 is a work in progress with no definite timeline yet (how soon depends on the complexity of the content). You can follow along at #1368. Closing in favor of that issue.

**Comment by nlangdon1** [comment]
Thanks, will the plugins eventually be easier to install?


Sent from my Samsung Note 10+


From: Mike Welsh <notifications@github.com>Sent: Tuesday, January 19, 2021, 6:28 PMTo: ruffle-rs/ruffleCc: nlangdon1; AuthorSubject: Re: [ruffle-rs/ruffle] Firefox and Chrome Plug-In's (#2657)
ActionScript 3.0 is a work in progress with no definite timeline yet (how soon depends on the complexity of the content). You can follow along at #1368. Closing in favor of that issue.
