### ISSUE TITLE
Recent Nightly Build - Self Hosting - Missing 2 Files

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#2660]
Not sure if this is how it supposed to work, but it is missing these 2 files:

core.ruffle.0197a207ce1d77ef54e9.js
core.ruffle.0197a207ce1d77ef54e9.js.map

**Comment by Herschel** [comment]
This is expected, this file was merged into ruffle.js and is no longer necessary as part of #2561.
