### ISSUE TITLE
Smash flash only working in training mode.

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#2662]
I decided to play smash flash 1,(smash flash 2 doesn't work with ruffle yet since it uses action script 3). It only works with training mode. Anywhere else where I win or lose crashes. I'm using the extension, since it's easier to use. The page slows down or sometimes rarely with my pc, it crashes my entire computer and I have to restart.(more of me problem) Ruffle usually crashes or the games are action script 3. Here's the link for the game https://www.supersmashflash.com/play/ssf1/
[Screenshot_2021-01-19 Super Smash Flash – Super Smash Flash.pdf](https://github.com/ruffle-rs/ruffle/files/5839451/Screenshot_2021-01-19.Super.Smash.Flash.Super.Smash.Flash.pdf)
![Screenshot_2021-01-19 Super Smash Flash – Super Smash Flash](https://user-images.githubusercontent.com/72718908/105111650-f1931d80-5a86-11eb-9325-32ffe0492d68.png)
![Screenshot from 2021-01-19 18-09-23](https://user-images.githubusercontent.com/72718908/105111664-ffe13980-5a86-11eb-8608-bf93f0144b24.png)

**Comment by micpap25** [comment]
Just want to add, you can still download either of the Smash Flash games to desktop if you want to play them.

**Comment by poyo77** [comment]
OK, it's just that sometimes I prefer playing on browser, and that other flash games I played that aren't action-script 3, tend to crash when you get to the end/winning screen or mess up on sheppards software.

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
