### ISSUE TITLE
Error on http://museumrudana.org/default.asp

### ISSUE THREAD

**Issue by yogatir** [ruffle-rs/ruffle#2663]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://museumrudana.org/default.asp

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-20
Channel: nightly
Built: 2021-01-20T01:07:01.467Z
Commit: 75967e377576cad9a679f1172d0b7f6e5ffd85c0

**Comment by n0samu** [comment]
Looks like the website uploaded Ruffle incorrectly, but it is impossible to check because they have since removed Ruffle from the site.
