### ISSUE TITLE
Error on http://www.easyworldofenglish.com/picdic/lpicdic.aspx?c=8589b881363b670c&l=0a489bff58f80c70&ls=b68b5cd3c76c188a

### ISSUE THREAD

**Issue by marcovcy67** [ruffle-rs/ruffle#2665]
[Ruffle-Bug.docx](https://github.com/ruffle-rs/ruffle/files/5840466/Ruffle-Bug.docx)
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.easyworldofenglish.com/picdic/lpicdic.aspx?c=8589b881363b670c&l=0a489bff58f80c70&ls=b68b5cd3c76c188a

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by n0samu** [comment]
Looks like the website uploaded Ruffle incorrectly, but it is impossible to check because they have since removed this page from the site.
