### ISSUE TITLE
The House 2 doesn't display properly

### ISSUE THREAD

**Issue by randomperson189** [ruffle-rs/ruffle#2672]
When I try to play The House 2, the screen is white for some reason but I can still click things.

Platform: Web (Google Chrome)

Site: https://www.sinthaistudio.com/thehouse2/
SWF: Site: https://www.sinthaistudio.com/thehouse2/Intro.swf

**Comment by n0samu** [comment]
Ruffle logs this warning:
`[WARN  ruffle_core::display_object] Blend mode 'multiply' is unsupported and will not render correctly.`
Blend modes are not implemented yet, see #58.
