### ISSUE TITLE
Ruffle Error on https://armorgames.com/play/3241/bunny-invasion-2?fp=b-shooting

### ISSUE THREAD

**Issue by eflorentino25** [ruffle-rs/ruffle#2676]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
Error: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
    at Object.J (https://agi.armorgames.com/ruffle/core.ruffle.9eec0e753f06015bcd55.js:1:20928)
    at __wbg_new_df6e6ab7a65c4c4d (https://agi.armorgames.com/ruffle/ruffle.js:1:38584)
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[1474]:0x278771
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[1491]:0x27b7e8
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[4122]:0x345dcc
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[3198]:0x3223f0
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[3748]:0x33c41e
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[4464]:0x34b42e
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[4339]:0x349acb
    at https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm:wasm-function[4435]:0x34aef4
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/3241/bunny-invasion-2?fp=b-shooting
SWF URL: https://cache.armorgames.com/files/games/bunny-invasion-2-3241.swf?v=1373587521

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by n0samu** [comment]
Looks like this game is working fine now, can you confirm?

**Comment by Sonikkustar** [comment]
The game appears to work now without any errors popping up:

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/18e8c41b-74cc-4a85-81cc-e2b24c1f7600)

Site uses **nightly-2023-11-13**.
