### ISSUE TITLE
Bug when the emulation starts. |  Version: Nightly 2021-01-20

### ISSUE THREAD

**Issue by Karapatakis106** [ruffle-rs/ruffle#2680]
When I load the . swf game the emulations starts, then, Windows says "Ruffle is not responsing" for a second and the app closes. I updated Ruffle today. 

**Version: Nightly 2021-01-20**

**Comment by Herschel** [comment]
Are you able to share which SWF you are trying to run? Thank you!

**Comment by Karapatakis106** [comment]
Sports Head Football 1/9/11 & epic war 4

**Comment by ousia** [comment]
Sorry, @Karapatakis106, could you provide the actual SWF animation or the address?

**Comment by Karapatakis106** [comment]
[Uploading Sports Heads Football_September_1st_2011&epic-war-4.zip…]()
Here you are :)

**Comment by Karapatakis106** [comment]
[Sports Heads Football_September_1st_2011&epic-war-4.zip](https://github.com/ruffle-rs/ruffle/files/5882813/Sports.Heads.Football_September_1st_2011.epic-war-4.zip)
Here you are =)

**Comment by Poopooracoocoo** [comment]
that's because they're both AS3!
