### ISSUE TITLE
ruffle_web.js:1140 Couldn't parse SWF. This may or may not be a bug in Ruffle,

### ISSUE THREAD

**Issue by miltonlaufer** [ruffle-rs/ruffle#2683]
Hi!
I'm getting that error with these files:

http://www.miltonlaufer.com.ar/milton/img/sil_zar.swf
http://www.miltonlaufer.com.ar/rotarotalapelota6.swf

***But not with these***: 
http://www.miltonlaufer.com.ar/milton/img/sil_tho.swf
http://www.miltonlaufer.com.ar/alejandrinos.swf

I think the problem could be related with the special characters that the first two have. Any ideas? Thank you very much in advance.

**Comment by Toad06** [comment]
Thanks for the report. "rotarotalapelota6.swf" seems to play correctly already. "sil_zar.swf" will work once #2636 is merged.

**Comment by miltonlaufer** [comment]
Thank you very much for the (super) quick response. I made a mistake, instead of "rotarotalapelota6.swf", this is the other file that doesn't work: http://www.miltonlaufer.com.ar/milton/img/sil_ojo.swf

Any idea when #2636 will be merged?

Thanks again!

**Comment by Herschel** [comment]
Both of the files seem to work now, fixed by #2636.
