### ISSUE TITLE
ActionScript 3

### ISSUE THREAD

**Issue by nightsmusic** [ruffle-rs/ruffle#2685]
Installed perfectly in Windows 10 but when trying to run anything that previously used flash, I'm getting this same message:

![Ruffle Error](https://user-images.githubusercontent.com/77744136/105207412-817fa880-5b15-11eb-9698-d6fe1a8108de.jpg)

I'm not a programmer, I'm a user so I wanted to let someone who is a programmer know and maybe get some insight into what's going on.

**Comment by torokati44** [comment]
See: https://github.com/ruffle-rs/ruffle/issues/1368

**Comment by nightsmusic** [comment]
Thank you.

**Comment by Herschel** [comment]
ActionScript 3 is from newer Flash files (~post 2007). Closing in favor of #1368.
