### ISSUE TITLE
Error on http://localhost/emgfa/

### ISSUE THREAD

**Issue by Twody7** [ruffle-rs/ruffle#2688]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): BufferSource argument is empty
Error stack:
```
CompileError: WebAssembly.instantiate(): BufferSource argument is empty
    at http://localhost/emgfa/js/ruffle/ruffle.js:1:32461
    at async e (http://localhost/emgfa/js/ruffle/ruffle.js:1:31933)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://localhost/emgfa/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4385.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Herschel** [comment]
Could you provide some information on what you were trying to do/what SWF you were trying to load?
