### ISSUE TITLE
Write words with an accent

### ISSUE THREAD

**Issue by rogerrey** [ruffle-rs/ruffle#2691]
Error in some applications they do not allow you to write words with an accent and letter Ñ

Ex. http://genmagic.net/repositorio/displayimage.php?pos=-167

**Comment by ousia** [comment]
Duplicate of #1778.

**Comment by ousia** [comment]
I don’t know whether #2081 might fix this.

**Comment by ousia** [comment]
@rogerrey, this issue has been probably fixed by #6224.

At least, the link @n0samu provided works perfectly fine with nightly from 2022-10-06.

**Comment by ousia** [comment]
@n0samu, #6224 was merged a year and a month after this issue was filled.

I think it is pretty safe to close this issue.

**Comment by n0samu** [comment]
Alright thanks!
