### ISSUE TITLE
Error when playing Red Ball

### ISSUE THREAD

**Issue by ghbeth** [ruffle-rs/ruffle#2698]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://img.clickjogos.com.br/dl/f/f4c87a11bbc998b9102c97de2175300a/src.swf
Param movie: https://img.clickjogos.com.br/dl/f/f4c87a11bbc998b9102c97de2175300a/src.swf
Param allowScriptAccess: always
Attribute 0: [object Attr]
Attribute 1: [object Attr]
Attribute 2: [object Attr]
Attribute 3: [object Attr]
Attribute 4: [object Attr]

# Page Info
Page URL: https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Red-Ball

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

**Comment by manokara** [comment]
Dear lord, they haven't fixed it yet?

**Comment by Herschel** [comment]
Ruffle is implemented incorrectly on the website (WASM file is missing).
