### ISSUE TITLE
Support PNG/GIF data in DefineBitsJPEG tags

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#27]
According to the [SWF spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf), DefineBitsJPEG2+ tags also allow for PNG and GIF data (as opposed to JPEG). I wasn't sure how to convince Flash to export these variants or of any cases in the wild, so I didn't implement it.

~~Ego Orb on Discord was kind of enough to share an example SWF with PNG data:
[281463_plus.zip](https://github.com/ruffle-rs/ruffle/files/3521651/281463_plus.zip)~~

**Comment by Herschel** [comment]
The above SWF wasn't actually a case of the mysterious PNG DefineBitsJPEG3 tag, it was just a normal JPEG3 tag (with alpha data), and this wasn't working on web. Fixed in 5fdc716. It was working fine on the desktop client.

Leaving this open because the SWF spec still says that PNG/GIF data is valid here, and we should implement it. The hunt for a PNG/GIF DefineBitsJPEG3 tag in the wild remains... :)

**Comment by Justin-CB** [comment]
The fix for this issue has been merged.

**Comment by Herschel** [comment]
Fixed by #532.
