### ISSUE TITLE
glitched pizza

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#2703]
I can now progress with papa pizzaria(sort of just to the second day), but the topping selection I can't really see it and the misclicked toppings, become glitched.
![glitchedpizza](https://user-images.githubusercontent.com/72718908/105279233-c71b9000-5b6c-11eb-9326-868380ae66ab.png)
https://www.coolmathgames.com/0-papas-pizzeria
I misclicked the sausages, because I didn't see the location and it crashed again. 
![image](https://user-images.githubusercontent.com/72718908/105279528-5de84c80-5b6d-11eb-9a04-a91a9f9f309f.png) I'm using extension.

**Comment by desertking** [comment]
Isn't it AS3?

**Comment by desertking** [comment]
https://www.newgrounds.com/portal/view/540919?emulate=flash This is the version I know that's AS3 and there is nothing happening. Wondering what kind of version that is.

**Comment by Poopooracoocoo** [comment]
I got the version from BlueMaxima's Flashpoint and I can now see the toppings in the containers! Drag and drop still isn't working properly though and it still gets stuck on the results screen.

**Comment by poyo77** [comment]
I'm not sure that this is as3 as it didn't warn me.

**Comment by desertking** [comment]
The version on newgrounds is definitely AS3.

**Comment by n0samu** [comment]
These problems are all fixed now as far as I can tell. Maybe a separate issue should be opened for the version on Newgrounds though. I think the game itself is still not AS3, but the Mochi preloader is. Anyway if there are further problems with the Coolmath Games version, please leave a comment and I can reopen the issue.
