### ISSUE TITLE
Image not showing up on https://www.ultrasounds.com/US.html

### ISSUE THREAD

**Issue by IDKhowToScript** [ruffle-rs/ruffle#2712]
![Ruffle](https://user-images.githubusercontent.com/54986336/105345307-63cd4480-5be4-11eb-9e6f-f1748dfd366d.png)
![Flash_Player](https://user-images.githubusercontent.com/54986336/105345309-64fe7180-5be4-11eb-8fdf-b97f2944d667.png)
The image is not showing up on https://www.ultrasounds.com/US.html
Compare
Ruffle.png = With Ruffle 2021_1_21
Flash Player = With adobe flash player 32.0.0.465 (64 bit)

**Comment by n0samu** [comment]
Fixed by #6547
