### ISSUE TITLE
web: Darts - Unknown AVM1 opcode: Unknown { opcode: 137, data: [213, 72] }

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2717]
Hey,

there is an old Darts game which still does not work. It just loops through the whole game. You can check here if you need more informations

https://www.spiele-umsonst.de/darts-t1551.html

Unknown AVM1 opcode: Unknown { opcode: 137, data: [213, 72] }
a.wbg.__wbg_error_e325755affc8634b @ ruffle_web.js:1140

**Comment by Herschel** [comment]
Obfuscated SWF has some bogus ops using valid opcodes (ActionTry with bad length). I think if we ignore these and skip past the bad ops, this would be fixed.

**Comment by Lord-McSweeney** [comment]
This SWF is also using the obfuscated opcode 244, which appears to have 94 KB of operands in Ruffle.

**Comment by desertking** [comment]
This game still just cycles through the frames by now.
