### ISSUE TITLE
Error on https://www.langangen.com/index.php?option=com_jvarcade&task=game&id=9778&Itemid=153

### ISSUE THREAD

**Issue by Magnewi** [ruffle-rs/ruffle#2723]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.langangen.com/images/jvarcade/games/BunnyCatchThoseEggs15minv32XPH.swf
Param movie: https://www.langangen.com/images/jvarcade/games/BunnyCatchThoseEggs15minv32XPH.swf
Param FlashVars: pn_uname=magne&pn_gid=9778
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: opaque
Param scale: showall
Param menu: false
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.langangen.com/index.php?option=com_jvarcade&task=game&id=9778&Itemid=153

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-20
Channel: nightly
Built: 2021-01-20T01:07:01.467Z
Commit: 75967e377576cad9a679f1172d0b7f6e5ffd85c0

**Comment by Magnewi** [comment]
It works in FF, not in Crome and Edge :)

**Comment by Herschel** [comment]
Working on all browsers here for me, the error makes it seemed like it was a 404 (Possibly a cached version). Could you clear your cache and try again?

**Comment by Magnewi** [comment]
Yes, it was a cached version. Deleted my cache on Crome and it works. Thanks :)
