### ISSUE TITLE
Building Firefox extension is broken on Node v15.6.0

### ISSUE THREAD

**Issue by Aaron1011** [ruffle-rs/ruffle#2724]
Due to https://github.com/archiverjs/node-archiver/issues/491, trying to build the Firefox extension with `npm run build` is broken on Node v15.6.0. The resulting archive contains a `manifest.json` with an invalid CRC.

Attempting to load the built `firefox_unsigned.xpi` into Firefox results in the following error:

```
There was an error during the temporary add-on installation.
Error details

Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available]
```

**Comment by Aaron1011** [comment]
The root cause is https://github.com/nodejs/node/issues/37027

**Comment by relrelb** [comment]
Closing as https://github.com/archiverjs/node-archiver/issues/491 was resolved a long time ago.
