### ISSUE TITLE
Error on https://z0r.de/2674?flash

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#2725]
# Error Info
Error name: Error
Error message: panicked at 'range end index 3520298905 out of range for slice of length 92088', core/src/tag_utils.rs:295:26

# Player Info
Allows script access: true

# Page Info
Page URL: https://z0r.de/2674?flash
SWF URL: https://z0r.de/L/z0r-de_2674.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-21
Channel: nightly
Built: 2021-01-21T01:06:17.627Z
Commit: dc2b4fcc42e447097d6432479a122b34fcbc3999

**Comment by llacb47** [comment]
There is something wrong with that SWF, even in flash player it is extremely buggy. The pickle only displayed once in 10 reloads.

**Comment by torokati44** [comment]
Yeah, for me, it crashes the flashplayer... :) But that doesn't mean that Ruffle needs to crash too!
