### ISSUE TITLE
Ruffle Error Screen

### ISSUE THREAD

**Issue by ogiwon** [ruffle-rs/ruffle#2726]
Sorry to bother you again. This is the error screen:
[http://planeta42.com/ruffleerror.jpg](http://planeta42.com/ruffleerror.jpg)
this is the content of the .htaccess file located in the ruffle folder

Header set Access-Control-Allow-Origin "*"
AddType application/wasm .wasm

What else am I missing? :)

**Comment by Herschel** [comment]
Hi, the error indicates that the WASM file is blocked due to CORS restrictions. Due to security restrictions in modern browsers, you must host the JS and WASM files on the same domain (http://plaenta42.com), or enable the appropriate CORS settings on your server to allow the cross-domain requests (https://enable-cors.org/server.html).

**Comment by ogiwon** [comment]
> Hi, the error indicates that the WASM file is blocked due to CORS restrictions. Due to security restrictions in modern browsers, you must host the JS and WASM files on the same domain (http://plaenta42.com), or enable the appropriate CORS settings on your server to allow the cross-domain requests (https://enable-cors.org/server.html).

Yes I did that, the ruffle is located on https://planeta42.com/ruffle/
I have access only to the .htaccess file 
I'm not sure if the server reads it correctly but I just recieved a word I can access the MIME Types on apache 2.2. Wll check and update. Thanks! :)

**Comment by Herschel** [comment]
If you are accessing the page from `http://planeta42.com` but loading ruffle from `https://planeta42.com`, (http vs https) this is not allowed by CORS.  An easy way to allow it to work from both HTTP and HTTPS is to use a URL like this:
`//planeta42.com/ruffle/ruffle.js`

**Comment by ogiwon** [comment]
waaaaaa! it's working!! http://planeta42.com/history/uspresidents/game1.html
You are awesome!
Indeed I added the MIME Type application/wasm trough cPpanel,
then I made the relative URL
**Thank you**
now I need to do that for all the games, a lot of happy work work :)
