### ISSUE TITLE
Super Mario 63: Water is on wrong places

### ISSUE THREAD

**Issue by 10Meisterbaelle** [ruffle-rs/ruffle#2727]
https://user-images.githubusercontent.com/45918080/105407267-c565d100-5c2d-11eb-9b1a-d8b1b73b72d7.mp4

**Comment by Newbytee** [comment]
I can't reproduce this. Maybe it has been fixed?

**Comment by 10Meisterbaelle** [comment]
Probably, I might test it again

**Comment by 10Meisterbaelle** [comment]
It has been fixed
