### ISSUE TITLE
How do you uninstall the extension?

### ISSUE THREAD

**Issue by MWstudios** [ruffle-rs/ruffle#2728]
I removed Ruffle from Chrome's extensions, deleted the folder I originally unpacked and restarted Chrome several times, but all Flash content is still running under Ruffle. I tried to search for any remains in Chrome's folder, the AppData folder, but there's nothing Ruffle-related left.

**Comment by parkerlreed** [comment]
Are you sure whatever site you are visiting isn't using ruffle themselves? (Since there's the self hosted version as well)

**Comment by Herschel** [comment]
If the extension is not listed in `chrome://extensions/`, then it's uninstalled. If you're still seeing it active, the site you are looking at is possibly using its own version of Ruffle.

**Comment by MWstudios** [comment]
It seems that I've solved the problem: I edited the Flash player files in SysWOW64 [as described in this article](https://superuser.com/questions/1616866/use-flash-player-after-12-jan-2021) and the Truffle container has changed into the default Flash one. Not sure what caused it but it helped.

**Comment by Kytin** [comment]
MWstudios how do i edit the flash player files in SysWOW64 so i can find the ruffle container that was changed into the default flash one on my computer?

**Comment by MWstudios** [comment]
> MWstudios how do i edit the flash player files in SysWOW64 so i can find the ruffle container that was changed into the default flash one on my computer?

As the article explained, I went to C:\Windows\SysWOW64\Macromed\Flash\Flash.ocx, then searched for 000040463E6F7742 (using a Hex editor plug-in for Notepad++) and replaced it with 000000000000F87F. If you don't have the permission to edit the file, you need to do it outside of SysWOW64. Then I made a file called mms.cfg and added this:
```
SilentAutoUpdateEnable=1
AutoUpdateDisable=0
AllowListUrlPattern=*
EOLUninstallDisable=1
```
(If there's mmc.cfg, delete that.)
That unlocked the Flash player's timed lockdown (at least on Internet Explorer, on Chrome it doesn't exist anymore). I tested it on some games using ActionScript 3 and it worked.

**Comment by Herschel** [comment]
For reference, if the Ruffle extension is not installed, it has no way of activating itself.

A website can instead choose to embed Ruffle on itself, in which case it will use Ruffle, and you would have to ask the website owner to provide standard Flash embeds. (They'll generally not use Ruffle for AS3 games, as Ruffle simply doesn't work there quite yet).

Some websites let you choose between Ruffle or the traditional Flash embeds For example, on Newgrounds, you can change whether it serves you a Flash Player embed or Ruffle in your account settings page.

On desktop, Ruffle does not mark itself to be the app for SWF files. You can set/unset this yourself using the standard OS options. On Windows, right click an SWF -> Open With -> Always use this app to open .swf files -> Select your standard Flash Player.exe (that is either an older version without the timebomb, or edited mm.cfg as above, do at your own risk.)

Going to close this as solved, thank you!
