### ISSUE TITLE
Ruffle doesn't know how to count in "CoolioBeat2.swf", I got x2 combo when I should get x4, got x50 when I should get x100, etc...

### ISSUE THREAD

**Issue by WingFoxie** [ruffle-rs/ruffle#2732]
This game works, apart from missing text outlines, the core gameplay mechanics (hit detection, etc.) works correctly. 
But I keep getting a very low score.

Turns out, the combo isn't counting correctly. 
When I hit 10 notes in a row, the combo count should be like:
x1 x2 x3 x4 x5 x6 x7 x8 x9 x10
But in Ruffle, it's like:
x0 x1 x1 x2 x2 x3 x3 x4 x4 x5

I don't find this problem happening in any other games, tried "CoolioBeat.swf" and "CoolioDJ.swf", the combo counter works correctly.
(In Coolio DJ the missing text outline makes it impossible to see the combo count, but I can just all combo a song and compare the score to using Adobe Flash Player, they are identical.)

(I didn't report this problem instantly, waited a week or two, tried few different night releases. This problem exists consistently. )
(I should try the online version and verify once more. but I can't get Ruffle.xpi to work at https://www.newgrounds.com/portal/view/424469 )

**Comment by hatal175** [comment]
I found what the issue is with this one. After calling removeMovieClip(_parent), in flash _parent is undefined while ruffle still keeps the value.
As I understand, @n0samu, this is an existing issue. Link the main issue?

**Comment by n0samu** [comment]
After discussion on Discord, it sounds like this is yet another thing that needs #5492 to work properly 😢 
I don't know if we have an open issue for it, I generally just link that PR
