### ISSUE TITLE
Ruffle Error on https://armorgames.com/play/12145/engage

### ISSUE THREAD

**Issue by comisora** [ruffle-rs/ruffle#2733]
# Error Info
Error name: TypeError
Error message: NetworkError when attempting to fetch resource.

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/12145/engage

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by Toad06** [comment]
Closing in favor of #2734 as this is the same issue (the error message is just different between Firefox and Chrome). Thanks for reporting.
