### ISSUE TITLE
Ruffle Error on https://armorgames.com/play/1920/bubble-tanks-2?tag-referral=shooting

### ISSUE THREAD

**Issue by HungryEdgar** [ruffle-rs/ruffle#2734]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/1920/bubble-tanks-2?tag-referral=shooting

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by Toad06** [comment]
This is an issue on Armor Games side:
`Access to fetch at 'https://agi.armorgames.com/ruffle/cc0a08d53db75ad5d75f.module.wasm' from origin 'https://armorgames.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

For some reason, this issue may not happen every time.

**Comment by Herschel** [comment]
I'm going to forward this along to AG.

**Comment by lmcnearney** [comment]
@Herschel The proper CORS headers should be returned now when requesting Ruffle files from our CDN.
