### ISSUE TITLE
Ruffle Error on https://armorgames.com/play/134/bowman-2?fp=b-shooting

### ISSUE THREAD

**Issue by AuspiciousFaxMachine** [ruffle-rs/ruffle#2739]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/134/bowman-2?fp=b-shooting

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by Toad06** [comment]
Closing in favor of #2734 as this is the same issue. Thanks for reporting.
