### ISSUE TITLE
Demo not working if Sample SWF set to None

### ISSUE THREAD

**Issue by Padre2** [ruffle-rs/ruffle#2744]
On 18 - 20 January, I found that I could not open files in **Demo Local SWF**. Since the **Demo** always opens with the **Sample SWF** menu showing and I am not interested in the content, I always set **Sample SWF:  None.** I assumed there was an issue with the **Demo** and on 21 January was about to post the issue, but decided to try one more time and after setting **Sample SWF:  None**, I was delighted to find that I could open SWF files again. This had been occurring with the latest versions of Chrome, Edge and Firefox, now all OK, so I thought the issue was fixed.

Today the problem has occurred again and I found it hard to believe that I was the only person with the problem.  I had scoured the issues and discussions previously and found nothing about it. Today in Actions, I found the topic _web: Fix error in demo when selecting None for sample (close #2416) Test Rust #2979_.  Although it appeared to be closed, I decided to see if I could open the **Local SWF** without first closing the **Sample SWF** and I could, so I see that the issue still persists.

**Comment by TheAlienDrew** [comment]
From the looks of it, the actual website itself hasn't yet gotten the commit update, even though the codebase has been updated:
![image](https://user-images.githubusercontent.com/19640692/105462942-3b753280-5c44-11eb-86a4-76c79c407ce9.png)

This just means that they haven't regenerated the website yet is all.

**Comment by TheAlienDrew** [comment]
I'd say maybe give them a day to a week or so to push out any and all website changes.

**Comment by Padre2** [comment]
Yes, although it was ok yesterday, but has occurred again today, so wanted to report the current status.
I am 15 hourrs ahead of the server time too.
Its no longer a problem for me, now that I know the cause.

**Comment by TheAlienDrew** [comment]
It seems to be fixed now, but it created another new issue, where it creates a second instance of it. I think I already figured out the issue of the new fix, and sent in a pull request to fix the new issue (https://github.com/ruffle-rs/ruffle/pull/2775). Otherwise though, selecting none does appear to work.

**Comment by relrelb** [comment]
Fixed by #2775.
