### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by Redondo26** [ruffle-rs/ruffle#2746]
autoplay does not always work in Google Chrome.
This is not optimal in my opinion.

I think most users will not press the play button.
Flash files always played automatically.
This works with ruffle in Mozilla Firefox, but not in Google Chrome.

There is the parameter
`	<param name="play" value="true" />`

it would be great if this parameter would be considered by ruffle. 
If this parameter is present in the HTML code, then the play button should not be displayed and the swf file should be played right away. That would be really great.

https://www.nailartansbach.de/Uhrzeit/
![screencapture-nailartansbach-de-Uhrzeit-2021-01-21-16_17_01](https://user-images.githubusercontent.com/76692239/105463181-f971de00-5c8f-11eb-9d3a-f4a2b9ad0d1a.png)

**Comment by einsz** [comment]
Chrome does not allow autoplay with sound. The default setting is not autoplaying in that case. Since your example has no sound, it should be fine if you set autoplay to 'on'.
See https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configuration-options

**Comment by Redondo26** [comment]
Thank you for your reply.
But my example has no sound.

**Comment by Redondo26** [comment]
How about an additional script to enable autoplay in Google Chrome as well??? Also for files with sound.

**Comment by einsz** [comment]
Yes, i know that your example has no sound. I wrote in my response, that your example has no sound. I linked you the configurable options for ruffle. One of them is 'autoplay'.
It reads:

> autoplay A string, indicating how files should start playing. Possible values are:
>
>    "auto": Ruffle checks if the user's browser allows audio autoplay. If it does, then the file is automatically played, otherwise a button is displayed.
>    "off": Ruffle always displays a button that the user has to click to actually play the file.
>    "on": Ruffle always plays the file, even if the user's browser doesn't allow audio autoplay.

The default is auto, it will not play if your browser does not allow autoplay with sound. Set it to on and you should be fine.


> How about an additional script to enable autoplay in Google Chrome as well??? Also for files with sound.
That would be nice, but but its impossible. See #1949

**Comment by Toad06** [comment]
Before the `script` tag that loads Ruffle, add:
```
<script>
window.RufflePlayer = window.RufflePlayer || {};
window.RufflePlayer.config = {
    "autoplay": "on",
    "unmuteOverlay": "hidden",
};
</script>
```
Closing this now as einsz said it all. Thank you.

**Comment by scottybcoder** [comment]
> Before the `script` tag that loads Ruffle, add:
> 
> ```
> <script>
> window.RufflePlayer = window.RufflePlayer || {};
> window.RufflePlayer.config = {
>     "autoplay": "on",
>     "unmuteOverlay": "hidden",
> };
> </script>
> ```
> 
> Closing this now as einsz said it all. Thank you.

Thank you so much I have been trying to accomplish this forever!
