### ISSUE TITLE
web: Detective Grimoire - Officer stuck in a loop

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2748]
Hello,

dunno what black hole causes the officer to stay in that loop 📦 

https://www.newgrounds.com/portal/view/386799?emulate=flash

#happens right after the beginning if you start playing the game

**Comment by Poopooracoocoo** [comment]
And you can't click on the next button either!

https://user-images.githubusercontent.com/51363864/105568325-8d28d480-5d8c-11eb-846d-c808d3345e3c.mp4

**Comment by ousia** [comment]
Duplicate of #2583.
