### ISSUE TITLE
supersoldier - random stutters/teleports

### ISSUE THREAD

**Issue by RadikAlice** [ruffle-rs/ruffle#2774]
So I was playing supersoldier [https://www.newgrounds.com/portal/view/284305](url) to see how well it ran under Ruffle
More or less flawless, no audio problems. I did notice something that's not been reported yet.
I should also clarify I used the wrapper that can be accessed by adding `/format/flash?emulate=flash`
at the end of a link as pointed out in [this post](https://sonucais.newgrounds.com/news/post/1137244) about workarounds to make the NG player work again

At seemingly random points it will stutter for about 1 or 2 seconds
and then it returns to being playable with the following three possible outcomes
- Resumes as normal
- Character gets teleported back 
- Character gets teleported out of bounds, as shown in the GIF below

Link to GIF: [https://imgur.com/pg8AgQQ](url)

In my very limited knowledge, it might have something to do with how objects are spawned
And speaking of spawns, sometimes an enemy helicopter spawns in right above you

**Comment by ousia** [comment]
@Alfernus, could you update the `.gif` image here?

**Comment by n0samu** [comment]
Looks like the teleporting issue has been fixed. Just want to note though that it is very difficult to click the Play button to start the game, likely due to #1108.

**Comment by RadikAlice** [comment]
> Looks like the teleporting issue has been fixed. Just want to note though that it is very difficult to click the Play button to start the game, as mentioned in #1108.

Yep, still true
