### ISSUE TITLE
demo: Add visual indicator to file picker for dragging and dropping

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#2776]

**Comment by relrelb** [comment]
Can you please clarify this? What's wrong with the current approach and how you expect it to be?

**Comment by Poopooracoocoo** [comment]
@relrelb I meant this 
![image](https://user-images.githubusercontent.com/51363864/105580406-495fba80-5de0-11eb-8320-4bab1d5f9156.png)
Sorry, should've provided a screenshot 😅

**Comment by yakagami** [comment]
somewhat related to this, I think yandex has a good system for both drag and drop and file picker. (attachment). I think we could use something like this.
![yandex file-pciker](https://user-images.githubusercontent.com/48779381/134710606-4bce11a9-72e3-413a-8a63-79baf977e044.PNG)
