### ISSUE TITLE
International Keyboard, Accents for Languages

### ISSUE THREAD

**Issue by sotoco** [ruffle-rs/ruffle#2794]
I have found that sometime different accent do not show up with ruffle

Here is a website University Maryland Baltimore County https://doit.umbc.edu/itnm/consulting/imc/keyboard/ with some keyboard accent

Microsoft website https://support.microsoft.com/en-us/office/keyboard-shortcuts-to-add-language-accent-marks-in-word-3801b103-6a8d-42a5-b8ba-fdc3774cfc76

https://usefulshortcuts.com/alt-codes/accents-alt-codes.php

https://sites.psu.edu/symbolcodes/windows/codealt/#accent

**Comment by ousia** [comment]
@sotoco, do you mean accented characters in input text?

In that case this would be a duplicate of #2691.

**Comment by ousia** [comment]
And probably both issues are duplicated from #1778.

**Comment by ousia** [comment]
I wonder whether #2081 might fix this.

**Comment by sotoco** [comment]
Sometimes the accent shows up another time it's does not.  These are the three that in my case happens the most. For example ó, á, é

**Comment by ousia** [comment]
Are _ó, á, é_ displayed or not? What is what happens with them most of the time?

**Comment by sotoco** [comment]
50/50 but I have ask the server tech to make sure the ruffle is updated daily. I think based on the comments ruffle may not have been update will check and report back?

Thanks to the ruffle teams

**Comment by ousia** [comment]
@sotoco, could you provide a SWF animation that shows the issue?

This is also important to be able to reproduce the issue.

**Comment by sotoco** [comment]
Hello Pablo

 
Here is a copy of the swf 

This is part of online course 

If you need I could give you access to the whole course

I hope this helps 

 
Roberto

**Comment by sotoco** [comment]
Pablo

Explanation

 
1st line   5th word              should read “línea”                                         show “l nea”

2nd line   1st  word              should read “administración”                     show  “administraci n”

3rd line    3rd word             should read “área”                                          show “ rea”

 
Roberto

**Comment by sotoco** [comment]
I tried pasting swf

**Comment by sotoco** [comment]
Unable to paste swf file

**Comment by ousia** [comment]
> [Explanation in Spanish to ease communication.]

Hola Roberto,

te respondo en español, por si fuera más fácil la comunicación (asumo que es tu lengua materna [sorry if I’m wrong 😅, ask me to translate the following into English]).

1. _GitHub_ sólo permite que añadas cierto tipo de archivos. Lo detecta por de extensión de archivo.

    https://github.com/ruffle-rs/ruffle/discussions/2783#discussioncomment-306127 contiene el ejemplo de cómo hacerlo.

    Sencillamente tienes que añadir la extensión `.zip` al archivo. _GitHub_ considera que es un archivo comprimido, simplemente hay que avisar de que no está comprimido (para que nadie intente descomprimirlo).

2. Si no pudieras añadir la extensión `.zip` al archivo, prueba a comprimirlo. En ese caso, tendrías que avisar que el archivo está comprimido.

2. En cuanto a los caracteres que se muestren o no, no tiene nada que ver en cómo se introduzcan (con la disposición del teclado).

    Si has trabajado con documentos PDF, habrás visto que a veces el texto se muestra con las tipografías que tiene el documento y a veces las que tiene el ordenador instalado.

    Tecleando letras en _Flash_   no es distinto. Si lo que se llama texto editado (el texto que se escribe) usa una tipografía incluida en el archivo SWF, funcionará bien con _Ruffle_. Si tiene que usar tipografías del sistema, @Herschel (el programador principal de este proyecto) explica en #1862 que el sistema actual funciona a medias.

Para comp comprobar esto último, tienes el siguiente archivo [archivo para descarga](https://github.com/ruffle-rs/ruffle/files/5862209/editcolors.swf.zip).

1. No está comprimido (como te he dicho antes, es para que _GitHub_ lo acepte).
2. Descárgalo y tal como está, con el botón derecho del ratón y selecciona «Guardar enlace como…».
3. Suelta el archivo descargado en https://ruffle.rs/demo/.
4. Ponte en medio de la presentación, pincha con el ratón y empieza a escribir. 
5. Sólo te dejará escribir aquellos caracteres que tiene la tipografía en el SWF (son `αβγδεασöñáçß`).

En cuanto a tu archivo, lo mismo pasará con el texto del archivo, si _Ruffle_ tiene que usar su tipografía propia del programa (no la propia del archivo SWF, que estaría dentro de el archivo SWF concreto), la mayoría de caracteres acentuados no saldrán (porque tiene los necesarios para escribir en inglés [es un parche temporal]).

La solución vendrá cuando haya una contribución para arreglar #1862. Hay un programador inglés interesado en hacerla. A ver si hay suerte y pronto va todo bien.

Como regla general, personalmente después de varios años trabajando con documentos PDF (y algunos archivos SWF) es que las tipografías se deben incluir siempre. Porque no te aparecen este tipo de sorpresas.

Espero que te sirva. Por cierto, creo que esta incidencia es un duplicado de #1862, cuando esté todo aclarado, te pediría que la cierres. Te lo digo ahora, porque yo no puedo hacerlo por ti.

Muchas gracias y espero que SWF te pueda llegar a ser muy útil.

**Comment by sotoco** [comment]
todo salio muy bien en el demo.
Going to double check the updates

Gracias
