### ISSUE TITLE
Links open at once

### ISSUE THREAD

**Issue by Tagadacouincoin** [ruffle-rs/ruffle#2815]
Hello, 

When i open this page : 

https://lesmathematiquescpasautomatique.fr/wp-content/wp-mep/6eme/pages/numerique/chap1/serie1/exo1/exo1.htm

There are 3 swf one for the exercice and 2 swf are for helping
![image](https://user-images.githubusercontent.com/77745264/105637533-5dea9400-5e6e-11eb-9dd3-0f59a0bfce74.png)

In the first swf (N1S1Ex1.swf) there are links for others swfs. 
![image](https://user-images.githubusercontent.com/77745264/105637444-def55b80-5e6d-11eb-9926-755fc0b69725.png)

But i can't do nothing, the 2nd swf open at once automatically... and it freezes. 
![image](https://user-images.githubusercontent.com/77745264/105637502-27ad1480-5e6e-11eb-835e-0029d5637584.png)

Thanks

**Comment by Toad06** [comment]
This appears to work as expected now, was fixed by one of these commits: https://github.com/ruffle-rs/ruffle/compare/nightly-2021-04-26...nightly-2021-04-27
