### ISSUE TITLE
Error on simple animation

### ISSUE THREAD

**Issue by borrougagnou** [ruffle-rs/ruffle#2817]
Hello !

I give you the error !
also, really thank you for your project !!! I love it !

I'm just sad about "rust" language... really complicated language for me, but, it's okay ^^"

# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.anime-ultime.net/
SWF URL: http://www.anime-ultime.net/radioV3/Radio_V3.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.283 (Edition beta)
OS: Windows

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-24
Channel: nightly
Built: 2021-01-24T01:05:42.228Z
Commit: 86b4c20809d8778d498474a26601aeda4cec87c4

**Comment by Herschel** [comment]
This SWF is ActionScript 3, closing in favor of #1368.

**Comment by Lord-McSweeney** [comment]
This SWF also needs `NetConnection`.
