### ISSUE TITLE
Ruffle Error on https://armorgames.com/play/588/bowmaster-prelude?tag-referral=upgrade

### ISSUE THREAD

**Issue by jdrThoughtworks** [ruffle-rs/ruffle#2827]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://armorgames.com/play/588/bowmaster-prelude?tag-referral=upgrade

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-06
Channel: nightly
Built: 2021-01-06T00:49:08.191Z
Commit: b84ed23106b764d1dad0ed682ad7e6789a95009a

**Comment by Sonikkustar** [comment]
Game appears to work now:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/961c2c7b-563d-49be-8669-20264b29c77b)

Site now uses **nightly-2023-11-13** for this game.

**Comment by n0samu** [comment]
This was probably a transient server error.
