### ISSUE TITLE
[all versions] Drag & Drop not working properly

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#2833]
Hello, recently I have tested three different games:

https://funkypotato.com/3-in-1-checkers/
https://funkypotato.com/koala-checkers/
https://funkypotato.com/mutant-fighting-cup/

In each of the above, player has to drag and drop an element - a checkers piece, or DNA piece, and place it somewhere. For some reason, this functionality doesn't work - selected elements return to the original position as soon as mouse button is released.

Tested on nightly builds from 21-01-2021 to 25-01-2021, on Windows & Mac, on Chrome & Firefox.

**Comment by Herschel** [comment]
Fixed by #4584.
