### ISSUE TITLE
action scripts 3 not working

### ISSUE THREAD

**Issue by kamalsaini2787** [ruffle-rs/ruffle#2838]
I am trying to access my internet device with ruffle but is says "This SWF contains ActionScripts 3 which is not yet supported by ruffle"
please help !!!!

**Comment by Poopooracoocoo** [comment]
Please view the pinned issue and the roadmap. AS33 support may take months, or even years.

**Comment by ogiwon** [comment]
ActionScript 3 is 5% implemented so far. Be patient :)

**Comment by Toad06** [comment]
ActionScript 3.0 support is still in progress, you can follow along in #1368. Closing in favor of that issue.
