### ISSUE TITLE
web: Boxhead - The Rooms - Red Screen after start

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2842]
Hello,

I posted it in my bigger List back then. Many games work now but this is one of those which are not working:

https://www.spiele-umsonst.de/boxhead-the-rooms-t11.html

It has a red screen after you started the game.

**Comment by n0samu** [comment]
These errors are repeated in the log:
```
[WARN  ruffle_core::avm1::globals::bitmap_data] BitmapData.draw with blend mode - not implemented
[WARN  ruffle_core::avm1::globals::bitmap_data] BitmapData.draw with clip rect - not implemented
```

**Comment by voltrare** [comment]
happens the same with boxhead 2 play rooms
https://www.crazymonkeygames.com/Boxhead-2Play-Rooms.html

**Comment by Lord-McSweeney** [comment]
No longer a black screen, but there is at least a second of lag when entering rooms.
