### ISSUE TITLE
List of sites ruffle works on?

### ISSUE THREAD

**Issue by VictoriaDemuysereLaptop** [ruffle-rs/ruffle#2848]
Hello, I was wondering if you would be able to release a list of sites that have installed ruffle into their hosting so I do not need the browser extension? I really love your program but randomly searching a site and hoping the games work is time consuming! You could possibly have a link on your download site or something? I am also just curious as to what websites you are negotiating with for them to add ruffle in the future!

**Comment by Herschel** [comment]
I think this is a good idea! Having a list of "People using ruffle-rs" linking to sites using it would be a good showcase.

**Comment by Poopooracoocoo** [comment]
But the sponsor list is pretty good ;D
