### ISSUE TITLE
RIght click on content

### ISSUE THREAD

**Issue by FemurTG** [ruffle-rs/ruffle#2856]
I have happily found Ruffle and am now using it on a website to run an old bit of Flash content that wouldn't run any other way. It's working great and looks good.  My one question is when you right-click on the SWF file on the page.  It shows that you can view it fullscreen, which is nice, but also has a link to the nightly build of Ruffle, which doesn't seem like something I'd like to turn off.  I didn't any documentation about this option, so I thought I would ask about it.  

Thanks so much!

**Comment by Poopooracoocoo** [comment]
I think you could disable the context menu and add a button to make the player fullscreen using JavaScript.

**Comment by relrelb** [comment]
Thanks for using Ruffle!
As @Poopooracoocoo said, you can use the `{ contextMenu: false }` option to disable the right-click menu entirely.

Currently there are 3 places where this option can be configured:
1. `window.RufflePlayer.config = { contextMenu: false };` - Affects all players in the current page.
2. `player.config = { contextMenu: false };` - Affects only a specific player.
3. `player.load({ url: "...", contextMenu: false });` - Also affects a specific player, but also for a specific SWF.

You may choose the best fit for your website.
Feel free to re-open this issue if you have any further questions.
