### ISSUE TITLE
Error in papa pizzaria(extension)

### ISSUE THREAD

**Issue by poyo77** [ruffle-rs/ruffle#2864]
![Screenshot_2021-01-25 Papa's Pizzeria](https://user-images.githubusercontent.com/72718908/105796562-b300d580-5f54-11eb-82ed-ea9a753b236b.png)
Again on papa pizzaria, it worked fine, and I can easily see the pepperoni toppings, but then of course froze on the results sceen. When I reloaded the page it, had the yes and no menu, and of course in making the pizza, the pepperoni toppings texture was gon again. It then froze when I clicked or go to a different tab. Also for it froze again and didn't even switch tabs.
![stuck](https://user-images.githubusercontent.com/72718908/105786510-d884e380-5f42-11eb-8715-a0fccacdbb81.png)
![Screenshot_2021-01-25 Papa's Pizzeria](https://user-images.githubusercontent.com/72718908/105786551-eaff1d00-5f42-11eb-972b-b683fc72257b.png)

![nooryes](https://user-images.githubusercontent.com/72718908/105786581-fa7e6600-5f42-11eb-8f1e-6f254ee8a341.png)
![enj](https://user-images.githubusercontent.com/72718908/105786603-0407ce00-5f43-11eb-9d2c-26d66f4c1503.png)
https://www.coolmathgames.com/0-papas-pizzeria, here's the link. Usually when I tab out, it stops working, so as a results screen.

**Comment by Poopooracoocoo** [comment]
#2703 #2656

**Comment by Poopooracoocoo** [comment]
I can now see the toppings in the containers! It still gets stuck on the results screen and drag and drop still doesn't work

**Comment by n0samu** [comment]
These problems seem to be fixed now!
