### ISSUE TITLE
1, 2, & 3 John Squares - Text Problem

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#2869]
Ruffle Desktop Version: ruffle_nightly_2021_01_08_linux
OS: Ubuntu 20.04 with Xfce
Flash Bible Game 016 [Direct Link]: [1, 2, & 3 John Squares](http://web.archive.org/web/20110909140902fw_/http://www.danlim.com/FBG/flashgames/123John/BibleSquares_123John-fin.swf)
Game Type: Squares
_All text is not bold and should be_
Question: _Text Too Large_
Answers Stage 1: _Multiple Choice Answers (text) Don’t Show_
Answers Stage 2: _Multiple Choice Answers (text) Too Large_
_Game # of # (red) is covered by the “o” in the word "of "_
Warning in Terminal After Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
Error in Terminal After Closing:
`[2021-01-08T03:11:15Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
![A016-123John_Squares swf](https://user-images.githubusercontent.com/59814178/105788676-fa846300-5f4e-11eb-8362-116f6c3450a5.png)
![R016-123John_Squares swf](https://user-images.githubusercontent.com/59814178/105788682-fbb59000-5f4e-11eb-9379-c6f65238b4c9.png)

**Comment by dogtopus** [comment]
The one and like 10 other issues you opened are clearly belong to a series made by the same dev. It would probably be more appropriate to just open 1 issue and list all of them in the description.

**Comment by C4C-Web** [comment]
Points Taken. This is the original issue: https://github.com/ruffle-rs/ruffle/issues/2085
