### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php?i=6

### ISSUE THREAD

**Issue by wowaka2** [ruffle-rs/ruffle#2871]
#Error信息nError名称：Error nError消息：在‘断言失败时惊慌失措：’(左=右)‘n左：’true‘，n右：’false`：不能递归地获取互斥物‘，/rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9 nError堆栈：n``nError：在断言失败时惊慌失措：’(左==右)‘n左：’true‘，n右边：’False‘：不能递归地获取互斥，/rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9 n at Object.q(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)n at__wbg_(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)_df6e6ab7a65c4c4d(https://flash.porno-apk.com/ruffle/11-01-2021/ruffle.js:1:38981)n at std：：(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)：：(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:21164)：：ONE：：Call_ONE：：{闭包}：：h7141d078b1e013f(wasm-function[1279]：169)n at std：：sync：：once：：Once：：call_inner：：h02eac160d339afc2(wasm-function[1537]：675)n at core：：ops：：function：：FnOnce：：call_once{{vtable.shim}}：：hf48d3d3ee3d10801(wasm-function[4274]：67)n at std：：panicking：：rust_panic_with_hook：：h123718ba3bf480af(wasm-function[3304]：在std：：panicking：：begin_panic_handler：：{{closure}}：：hf393a82e58397bd2(wasm-function[3885]：159)n在std：：sys_common：：backtrace：：__rust_end_short_backtrace：：h2ff2cfc953878925(wasm-function[4618]：40)n在锈蚀_BEGIN_unwind(wasm-function[4492]：89)n at std：：panicking：：begin_panic_fmt：：h96153d9dc0e882ed(wasm-function[4588]：48)Ruffle_web：：Ruffle：：new_internal：：{{closure}}：：{{closure}}：：h1511fa0d1c7e612c(wasm-function[1280]：870)n位于<dyn核：：ops：：function：：FnMut<(A，)>+Output=R作为wasm_bindgen：：closure：：WasmClosure>：：describe：：invoke：：h1f21aa1d3ee449d6(wasm-function[4798]：14)n at T(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:17997)n at HTMLCanvasElement.f(https://flash.porno-apk.com/ruffle/11-01-2021/core.ruffle.3be12cf6e13daeeedf58.js:1:17873)n`n`n#Player Info nAllowsScript Access：真nPlayer类型：对象nSWFURL：GAME/6.swfnParam电影：Games/6.swfnParam质量：高nParam播放：True nParam循环：true nParam wmode：Window nParam Scale：Displayall nParam l.FullScreen：True nParam devicefont：https://flash.porno-apk.com/game/6.swf nParam devicefont：false nParam ScriptAccess：All nAttribute 0：未定义的nAttribute 1：未定义的nAttribute 2：未定义的Atntribute 3：未定义的n n#Page nPage URL：https://flash.porno-apk.com/game/6.swf nSWFURL：https://flash.porno-apk.com/game/6.swf n n#Browser Info nUseragent：Mozilla/5.0(Linux；APpleWebKit/537.36(KHTML，类似壁虎)版本/4.0 Chrome/66.0.3359.126 MQQBrowser/10.5 Mobile Safari/537.36 NOS：linux armv8l n n#RuInfo nVersion：0.1.0 nname：2021-01-11 nChannel：每晚构建：2021-01-11T00：53：04.486Z nCommit：cce3a8199decbce536a049efd501da2b370

**Comment by Poopooracoocoo** [comment]
@wowaka2 Hi there. Ruffle supports Chrome version 87 and up. QQ Browser is based on Chromium 66 which does not have the web technologies that Ruffle uses. If you can still reproduce this issue with an up to date browser (which you can find an APK for, as I understand you do not have Google Play in China), please let us know.
