### ISSUE TITLE
ActionScript 3

### ISSUE THREAD

**Issue by BLA5T3RProductions** [ruffle-rs/ruffle#2872]
There is this site Kisekae that I used to use all the time for my DeviantArt page. However, due to the tragic of Adobe Flash, it is no longer usable. The only thing it needs now to be functional is ActionScript 3.
Here is a link to the site:
http://pochi.x.fc2.com/kisekae/k_kisekae2.html

**Comment by Poopooracoocoo** [comment]
Please take a look at the pinned issue. Any kind of AS3 support will take at least several months to develop.

**Comment by Toad06** [comment]
Closing in favor of #1368.
