### ISSUE TITLE
Error on https://www.crazygames.com/gameframe/robot-unicorn-attack?v13bb=&locale=nb_NO

### ISSUE THREAD

**Issue by CasperTheDog666** [ruffle-rs/ruffle#2878]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.crazygames.com/gameframe/robot-unicorn-attack?v13bb=&locale=nb_NO
SWF URL: https://files.crazygames.com/robot-unicorn-attack/1/robot%20unicorn%20attack.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Toad06** [comment]
Thanks for the report. This is the same error as #2870, so I'm closing in favor of that issue.
