### ISSUE TITLE
Error on http://www.crazygames.com/gameframe/sonny?

### ISSUE THREAD

**Issue by marshdugan** [ruffle-rs/ruffle#2883]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.crazygames.com/gameframe/sonny?
SWF URL: https://files.crazygames.com/sonny.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
@marshdugan should be fixed now! mind closing this issue?

**Comment by jhwgh1968** [comment]
In fact, I have specifically verified this is fixed in nightly 1c249200.
