### ISSUE TITLE
My Favorite Teacher

### ISSUE THREAD

**Issue by qxiaolong** [ruffle-rs/ruffle#2889]
# Error Info
Error name: RangeError
Error message: WebAssembly Instantiation: Out of memory: wasm memory
Error stack:
```
RangeError: WebAssembly Instantiation: Out of memory: wasm memory
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/8.swf
Param movie: game/8.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=8

# Browser Info
Useragent: Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; OPPO R9sk Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/10.4 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by ARYANTECH123** [comment]
It could be a bug with your web browser. Try switching to something not based on Chromium, like Firefox.

**Comment by Poopooracoocoo** [comment]
QQ Browser 10.4 based on Chromium 66. It doesn't support WASM at all or properly. 

I don't know much about QQ Browser other than that it has a very low Play Store rating, that it's outdated in most places I saw it like on the Play Store and APK Pure, and that it's from Tencent: the Chinese company notorious for abusing privacy.

Let us know if you can reproduce with the latest version of Chrome or another Chromium based browser like Brave/Edge/Vivaldi/Bromite/Ungoogled-Chromium, etc.

**Comment by Poopooracoocoo** [comment]
#2888
