### ISSUE TITLE
Error on http://sargas.sts.nuskin.io:8020/sap(ZT1RbGRDVlZKVVQwNWZYMTlmTVRKZk9GOWZBa3Zqak13c0h0dVlnOEtNSVUwN3dRPT0=)/bc/bsp/sap/crm_ui_frame/BSPWDApplication.do?sap-client=080&sap-language=EN&sap-domainrelax=min&sap-domainrelax=min

### ISSUE THREAD

**Issue by bwburton** [ruffle-rs/ruffle#2892]
# Error Info
Error name: TypeError
Error message: e[r] is not a function
Error stack:
```
TypeError: e[r] is not a function
    at Function.n (<anonymous>:3:207)
    at http://sargas.sts.nuskin.io:8020/sap(====)/bc/bsp/sap/thtmlb_scripts/scripts.js?sap-client=080&sap-language=EN&sap-domainRelax=min&20151105140501:34847:9
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://sargas.sts.nuskin.io:8020/sap(ZT1RbGRDVlZKVVQwNWZYMTlmTVRKZk9GOWZBa3Zqak13c0h0dVlnOEtNSVUwN3dRPT0=)/bc/bsp/sap/crm_ui_frame/BSPWDApplication.do?sap-client=080&sap-language=EN&sap-domainrelax=min&sap-domainrelax=min

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by n0samu** [comment]
The webpage is inaccessible and was never archived :(
