### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by andremichelle** [ruffle-rs/ruffle#29]
As a former flash-enthusiast I would like to show my appreciation for your project. I still have many flash sandboxes and tiny projects I would like to keep online when the flashplayer is ultimately deactivated in 2020. Since my knowledge of Rust is rather limited and my time is needed for other projects, I wonder if you considered a fundraiser to help you maintaining the development. I am pretty sure many people would contribute to protect a piece of good old quirky web-history.

**Comment by Herschel** [comment]
Thanks for the kind words, André! Your Flash experiments will make excellent test cases :-)

I've had a few people approach about funding, but I'm a little uncomfortable accepting it this early in the project. I will do some research into the different crowdfunding platforms. Does anyone have any opinions? Should I wait for GitHub Sponsors to come out of beta?

**Comment by jkanchelov** [comment]
Patreon should be good and easy enough

**Comment by Herschel** [comment]
GitHub Sponsors recently left beta, so I hopped on to try it out. You can contribute here:

https://github.com/sponsors/Herschel

Contributions are never expected but always appreciated. Thank you! :-)
