### ISSUE TITLE
Web demo can not be installed

### ISSUE THREAD

**Issue by 317607692** [ruffle-rs/ruffle#2900]
web demo: 
npm i:

 Not Found - GET https://registry.npmjs.com/ruffle-core - Not found
npm ERR! 404
npm ERR! 404  'ruffle-core@0.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Herschel** [comment]
Try `npm run bootstrap` in the `web` folder to install and link the packages.

Then you can `npm run build` and `npm run demo`.

**Comment by 317607692** [comment]
i try npm run bootstrap in the web folder but there is new error: 
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\lodash-54480fa3\lodash.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\stylelint-3c8ad4ce\lib\rules\color-named\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\stylelint-3c8ad4ce\lib\rules\function-whitelist\index.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\stylelint-3c8ad4ce\lib\rules\function-whitespace-after'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\typescript-a5a24705\loc\lcl\FRA\TypeScriptDebugEngine'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\typescript-a5a24705\loc\lcl\JPN'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Luigi\Documents\WorkPlace\vscode\Study\Ruffle-github\ruffle\web\node_modules\.staging\typescript-a5a24705\loc'
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @wdio/static-server-service@6.10.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'web'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luigi\AppData\Roaming\npm-cache\_logs\2021-01-30T02_06_05_061Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ruffle@0.1.0 bootstrap: `npm install && lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ruffle@0.1.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luigi\AppData\Roaming\npm-cache\_logs\2021-01-3

**Comment by relrelb** [comment]
I think this problem is not relevant by now. Web build has significantly changed since then, and specifically `npm run bootstrap` no longer exists. Hence closing.
