### ISSUE TITLE
web: Forbidden Arms - Protected or bugged?

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2905]
Hello,

is this game bugged or is this game protected and that's why it's bugged?

https://www.newgrounds.com/portal/view/635209?emulate=flash

**Comment by Herschel** [comment]
Looks like we're choking on this obfuscated SWF at some point.

**Comment by Herschel** [comment]
Currently AVM1 reader throws an error whenever it encounters an incorrect length, and this error halts all further execution in the SWF. We should just skip over the length and not error in this case, because obfuscated SWFs like this make bogus instructions with  a large length.

**Comment by relrelb** [comment]
Seems like it was fixed by #6688.
