### ISSUE TITLE
System.security.allowDomain() not implemented

### ISSUE THREAD

**Issue by JointKush** [ruffle-rs/ruffle#2917]
Whenever I try to run this specific swf I run into an issue where in debug mode i'm greeted with ```System.security.allowDomain() not implemented```
![P6TIRIg](https://user-images.githubusercontent.com/26471704/106085364-065a5b80-60ee-11eb-9c37-6e012e5dcbfe.png)

Not sure why this happening cause I have it in the swf

**Comment by Herschel** [comment]
This message means Ruffle doesn't support `security.allowDomain()`, so calling it has no effect. (Ruffle on web is subject to the browser's CORS restrictions nowadays; so I'm not sure if we even need to honor Flash cross-domain sandboxing on web, by default at least).

**Comment by JointKush** [comment]
> This message means Ruffle doesn't support `security.allowDomain()`, so calling it has no effect. (Ruffle on web is subject to the browser's CORS restrictions nowadays; so I'm not sure if we even need to honor Flash cross-domain sandboxing on web, by default at least).

Probably be a good idea but removing it still doesn't load my swf completely either. It loads then stops and continues but doesn't proceed to the login screen whatsoever. 
![uZ1THTc](https://user-images.githubusercontent.com/26471704/106086418-1a06c180-60f0-11eb-975e-f5a6443fce39.gif)

**Comment by Herschel** [comment]
Could you provide a link to the SWF? Thank you!

**Comment by JointKush** [comment]
> Could you provide a link to the SWF? Thank you!

Thanks for the reply! It's on localhost but I managed to fix it I had to modify some things in the shell to get it load properly.

**Comment by Poopooracoocoo** [comment]
It's Club Penguin, ain't it! Ah, the memories...
