### ISSUE TITLE
Not able to show .swf - Problem is Domain base href in the header of a page. Bug in Chrome ?

### ISSUE THREAD

**Issue by ooozooo** [ruffle-rs/ruffle#2920]
Until Version from 17. January 2021 it works all fine. New tested Version from 28. January is no longer finding the  .swf files.

**Comment by Poopooracoocoo** [comment]
Are you referring to the extension? Do you have link to website to test it on?

**Comment by ooozooo** [comment]
Self hosted. I had it on my own page online but took your older version again. In Chrome came the issue - In Firefox it worked. https://www.x-oo.com/flash-online-games/brettspiele/world-wars-2.html - This page for example. In the header you can see the base href - I think this was the problem. Maybe a htaccess modRewrite bug ? hmmm ....

**Comment by n0samu** [comment]
Hi @ooozooo, is this problem still occurring for you? I might have fixed it in #7365.

**Comment by n0samu** [comment]
Closing since this is likely fixed
