### ISSUE TITLE
web: Gemcraft - Black Screen after Start

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2927]
Hello,

Gemcraft was a pretty well played and executed Tower Defense game back then. After you start the game the main screen is only black.

https://www.newgrounds.com/portal/view/446232?emulate=flash

**Comment by SarahKirksey** [comment]
I'd like to provide... significantly more information and context to this.

I have tested this particular game in the standalone player (nightly builds 2021_05_09-windows-x86_64 and 2022_03_08-windows-x86_64), using the Chrome browser plugin (nightly builds 2021_05_09-windows-x86_64) on both the Newgrounds link listed above and on the ArmorGames link https://cache.armorgames.com/files/games/gemcraft-1716.swf , and on the Firefox browser plugin (nightly 2022-03-02) on the Newgrounds link posted above. I can also confirm that the version of the game I was playing on the standalone player is identical to the version on ArmorGames, though I am not able to make that confirmation for the file hosted on Newgrounds. (I can say, however, that the title screens always say "v. 1.11" in the bottom-right corner.)

Some of the issues I've experienced are specific to my Chrome-based testing (one of which, strangely, only appears when I use the ArmorGames link), but I won't be discussing those in much detail here. I'll say that the game loads perfectly well, until I attempt to play a level. Attempting to open a level brings up a several-second delay, after which the combat screen appears, only partially loaded. During this lag spike, a large number of "BitmapData.draw - not yet implemented" warnings appear in the console. Once the level is more-or-less loaded, the combat screen is so incomplete that the game is literally unplayable.

Of more interest and importance, I believe, are the behaviors encountered outside of my Chrome-specific issues. Namely, upon entering a level, the battlefield is completely black. Visible monsters will spawn and follow the path laid out in the level's design, and it's possible to fight these monsters, but fighting them is quite a bit trickier when you're unable to see the path the monsters will follow or the locations of any traps/towers you've placed.

**Comment by desertking** [comment]
This Issue sadly still exists. I've posted a few games here and sadly some of the errors still occur after a year. Maybe especially some of those Tower Defense games needs some more love from the coders here. Many still don't work due to "small issues",, Xeno Tactic, Vector Tower Defense, Gemcraft etc. Just to name a few...

**Comment by n0samu** [comment]
BitmapData.Draw has been implemented in the Ruffle desktop app. Please try the game in the latest desktop app and let me know if there are any more issues!

**Comment by tanriol** [comment]
The background mostly renders. However, there are at least two problems.
First, the shadows around buildings render much darker than I seem to remember and than screenshots one can find on the internet show.
Second, after one finishes one level and starts another, the buildings from both levels are rendered on the map at once (non-functional, obviously).

**Comment by n0samu** [comment]
Alright thanks for your reply!

**Comment by Lord-McSweeney** [comment]
The building issue appears to be no longer present, but the game does lag for a few seconds because of the `BitmapData.draw`.
