### ISSUE TITLE
Build error web extension

### ISSUE THREAD

**Issue by haraldbre** [ruffle-rs/ruffle#2961]
Building the web extension via npm run build gives the error:
>>
ruffle-core: error: 
ruffle-core: it looks like the Rust project used to create this wasm file was linked against
ruffle-core: a different version of wasm-bindgen than this binary:
ruffle-core:   rust wasm file: 0.2.69
ruffle-core:      this binary: 0.2.70
ruffle-core: Currently the bindgen format is unstable enough that these two version must
ruffle-core: exactly match, so it's required that these two version are kept in sync by
ruffle-core: either updating the wasm-bindgen dependency or this binary. You should be able
ruffle-core: to update the wasm-bindgen dependency with:
ruffle-core:     cargo update -p wasm-bindgen
ruffle-core: or you can update the binary with
ruffle-core:     cargo install -f wasm-bindgen-cli
<<
Neither "cargo update -p wasm-bindgen" nor "cargo install -f wasm-bindgen-cli" fied this.

**Comment by torokati44** [comment]
According to https://github.com/ruffle-rs/ruffle/pull/2849 ( https://github.com/ruffle-rs/ruffle/pull/2849/commits/1791f4d67b32ddd2ca466b4928dd37b32e840d9f ) doing a `cargo install wasm-bindgen-cli --version 0.2.69` might help.

**Comment by haraldbre** [comment]
Thanks, that did it!
