### ISSUE TITLE
Video from security camera

### ISSUE THREAD

**Issue by EHS329** [ruffle-rs/ruffle#2979]
My security camera uses Flash if I want to view the cam via a browser. When I try to do so now, the message appears "This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended." It is right, I can't view the cam's output.

Any idea whether this will be addressed, and, if so, when?

**Comment by Herschel** [comment]
ActionScript 3.0 is a work in progress. You can follow along on #1368. Security camera software also requires video support and possibly more, which will be a long time before its implemented (months or longer).

My recommendation in the meantime is to try an alternate browser that still enables you to use the classic Flash plugin, such as [Waterfox](https://waterfox.net).
