### ISSUE TITLE
Aliasing in resampling of bitmap images

### ISSUE THREAD

**Issue by jedikalimero** [ruffle-rs/ruffle#2981]
The intro of my website www.artofwalls.com shows a background with a superimposed image of a fence. The fence is a rectangle filled with a transparent bitmap repeating the pattern of the fence wires.
With the original flash player, the fence is properly resampled and looks right, but with ruffle, the resampling is not good and there appear visual artifacts in the shape of diamonds that didn't appeared in Flash Player.

This is how it looks in Ruffle:
![2021-01-30 (3)](https://user-images.githubusercontent.com/18701653/106370600-6c93e800-6353-11eb-805b-3f7a1918943e.png)

And this is how it looks in Adobe Flash (Using the player from Adobe Animate):
![2021-01-31](https://user-images.githubusercontent.com/18701653/106371499-1035c600-635d-11eb-8f8a-5bbb7a6728c1.png)

Also, in the page that opens after the intro, http://www.artofwalls.com/home.html there was a glow around the circled images when the mouse hovers them.

**Comment by jedikalimero** [comment]
I would attach here the .fla file or the .swf but I don't know how to do it

**Comment by jedikalimero** [comment]
Added the .FLA and .SWF files to help debugging the issue:
[intro.zip](https://github.com/ruffle-rs/ruffle/files/5899061/intro.zip)

**Comment by n0samu** [comment]
Thanks for the report and sorry for the late response. The background rendering issue seems to be fixed now, can you confirm? As for the hover glow effect, it is missing because the glow filter is unimplemented (#15).

**Comment by jedikalimero** [comment]
Thank you!
Yes, the fence looks correct now!
