### ISSUE TITLE
test: Thickness of red vertical line is incorrect

### ISSUE THREAD

**Issue by beemagnet** [ruffle-rs/ruffle#2982]
The HTML and SWF file can be found at
http://bonniehill.net/uploads/sq9-orig/sq9-orig.html

All the movable red lines should be narrow, but you will see the (almost) vertical red line is quite thick. I have attached a ZIP file as well.
[SQ9-orig.zip](https://github.com/ruffle-rs/ruffle/files/5899011/SQ9-orig.zip)

**Comment by Herschel** [comment]
Closing in favor of #1955.
