### ISSUE TITLE
Glow effects don't work

### ISSUE THREAD

**Issue by jedikalimero** [ruffle-rs/ruffle#2984]
In this page http://www.artofwalls.com/home.html there was a glow around the circled images tht changed colour when the mouse hovers them.

With Flash:
![2021-01-31 (1)](https://user-images.githubusercontent.com/18701653/106371742-f6e24900-635f-11eb-9af2-a1aa02317daa.png)

With Ruffle:
![2021-01-31 (2)](https://user-images.githubusercontent.com/18701653/106371746-06fa2880-6360-11eb-9842-3187518a1df6.png)

I can provide the .fla file if needed.

**Comment by jedikalimero** [comment]
Added the .FLA and .SWF files to help in solving the issue:
[home.zip](https://github.com/ruffle-rs/ruffle/files/5899059/home.zip)

**Comment by Herschel** [comment]
Closing in favor of #15.
