### ISSUE TITLE
Text buttons only work in the rendered pixels

### ISSUE THREAD

**Issue by jedikalimero** [ruffle-rs/ruffle#2987]
In this page http://www.artofwalls.com/home.html there are 5 buttons that are composed of a circular picture and a text that is in part outside of the circle. There is also a text button with an e-mail at the bottom.

In Flash, a rectangular area around the text is clikable area of the button, but in Ruffle, only the pixels that are part of the letters are clickable. Any hole or space between the letters is not clickable, making it very difficult to click on a text button.

**Comment by Herschel** [comment]
Seems like this behavior is actually dependent on SWF version. v7 and earlier `hitTest`s text based on the shape of the glpyhs, but v8 and higher uses the bounding box.

**Comment by Herschel** [comment]
Okay, it's actually the CSMTextSettings tag that controls this (specifically the useFlashType field, which in the Flash IDE is "Anti-alias for animation" (useFlashType = false) vs. "Anti-alias for readability" (useFlashType = true). Only the "animation" setting hit tests based on glyph shape.
