### ISSUE TITLE
Error on https://evilgames.eu/flashgames/tails-nightmare.htm

### ISSUE THREAD

**Issue by rufflue** [ruffle-rs/ruffle#2988]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32283
    at r (<anonymous>:3:32773)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/tails-nightmare.swf
Param wmode: direct
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/tails-nightmare.htm

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13597.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.109 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-29
Channel: nightly
Built: 2021-01-29T00:34:32.424Z
Commit: bb4240ad1f9705b080c9f7861e38b6677a62d76b

**Comment by Poopooracoocoo** [comment]
#2201 

This is an issue with that website and CSP. Read that issue for more information.

**Comment by Herschel** [comment]
Closing in favor of #2201.
