### ISSUE TITLE
Error on file:///C:/Users/Owner/Downloads/TITS_ImagePack_0.8.128.swf

### ISSUE THREAD

**Issue by SanguineSkral** [ruffle-rs/ruffle#2989]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9

# Player Info
Allows script access: true

# Page Info
Page URL: file:///C:/Users/Owner/Downloads/TITS_ImagePack_0.8.128.swf
SWF URL: file:///C:/Users/Owner/Downloads/TITS_ImagePack_0.8.128.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-27
Channel: nightly
Built: 2021-01-27T00:33:31.688Z
Commit: a0159a5efaf9cb29f3d0e5b4a1e1173ad811728a

**Comment by Poopooracoocoo** [comment]
Could you please upload that SWF?

**Comment by SanguineSkral** [comment]
it is the SWF file for a text based sci-fi furry porn game just as a warning,also it is way too big to post as it is over 500MB so I will have to post a download link, https://mega.nz/file/coN3nQTB#r0dinZTM9Ji_X-IWnh29vBBeSVMOtTHATHgsrYVwMkY

**Comment by Poopooracoocoo** [comment]
The MEGA file linked is no longer available.
