### ISSUE TITLE
Graphic issues on Android

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#2992]
This problem happen only on android in some specific swf files, but on PC everything works perfectly.

Mediapad M5 lite 8 (2019)
CPU: Kirin 710 (Cortex A73 4 cores @2.2Ghz) performance mode
GPU: Mali G51
RAM: 3GB
OS: Android 9 pie
Browser: Firefox 87 (nightly)

[follow_me_by_drakkira-d5zwb4c.zip](https://github.com/ruffle-rs/ruffle/files/5899211/follow_me_by_drakkira-d5zwb4c.zip)

![Screenshot_20210131_093904_org mozilla fenix](https://user-images.githubusercontent.com/38821724/106375196-ed7ece00-63ab-11eb-9b5d-2004d9ae1fde.jpg)

**Comment by ousia** [comment]
@SN902, I guess this is what you mean:

![fme](https://user-images.githubusercontent.com/203767/106398796-2f902a00-6415-11eb-9bee-556902e62fc0.png)

Sorry, but otherwise it is impossible to know which issues you might be facing.

**Comment by SN902** [comment]
Yes, your picture correct, it must look like this

**Comment by SN902** [comment]
![Screenshot_20210204_092118_org mozilla fenix](https://user-images.githubusercontent.com/38821724/106845649-347f0300-66cd-11eb-9224-a9013c721bbf.jpg)
![Screenshot_20210204_092912_org mozilla fenix](https://user-images.githubusercontent.com/38821724/106845659-38ab2080-66cd-11eb-9dbb-78e63fc4311b.jpg)

Suddenly these problems gone, now swf works correctly. ^_^

**Comment by Herschel** [comment]
Might have been fixed by #3049. Thanks for the report.
