### ISSUE TITLE
https://www.y8.com/games/tower_bloxx

### ISSUE THREAD

**Issue by kienvn** [ruffle-rs/ruffle#2996]
I installed ruffle version Nightly 2021-01-31 on firefox

**Comment by Poopooracoocoo** [comment]
SWF URL: https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/8403/original/tower_bloxx.swf?1521316944

Ran in Ruffle demo, version 2021-02-01. The game never gets past, what I think is, the preloader.

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
