### ISSUE TITLE
Error on https://e621.net/posts/591392?q=charizard+straight+order%3Ascore+animated

### ISSUE THREAD

**Issue by JakeSanchez** [ruffle-rs/ruffle#3010]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32283
    at r (<anonymous>:3:32773)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/591392?q=charizard+straight+order%3Ascore+animated

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-31
Channel: nightly
Built: 2021-01-31T00:37:01.589Z
Commit: 07fbacc4fb3ce1e416c643b965eecbf71c09659c

**Comment by Poopooracoocoo** [comment]
Hi. Thanks for the report. This issue is the same as #2201 as it's a site wide issue because of its Content Security Policy that doesn't allow WebAssembly to run. Please view that issue for more information.

**Comment by Toad06** [comment]
Closing in favor of #2201. Thanks for reporting.
