### ISSUE TITLE
Fun Bible Stuff: Map Quest, Bookshelf & Spin the Wheel Games

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#3011]
OS: Ubuntu 20.04 with Xfce
Map-Quest-New-Testament.swf
Map-Quest-Old-Testament.swf
Old-Testament-Bookshelf.swf
Spin-the-Wheel-New-Testament.swf
Spin-the-Wheel-Old-Testament.swf
Ruffle Desktop Version: ruffle_nightly_2021_01_31_linux
Games _play_ perfectly in Ruffle Desktop but, each shows a Warning in Terminal after Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
And an Error in Terminal after Closing:
`[2021-01-31T19:47:44Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
And with Ruffle Browser Extension: ruffle_nightly_2021_01_31_firefox.xpi
http://www.funbiblestuff.com/flashgames/mapquestnt.htm
http://www.funbiblestuff.com/flashgames/mapquestot.htm
http://www.funbiblestuff.com/flashgames/bookshelfnt.htm
http://www.funbiblestuff.com/flashgames/bookshelfot.htm
http://www.funbiblestuff.com/flashgames/spinwheel.htm
http://www.funbiblestuff.com/flashgames/spinwheelot.htm
All games play perfectly. _No errors or warnings_.

**Comment by n0samu** [comment]
No problem reported, closing
