### ISSUE TITLE
[AVM1] Music only plays out of the left audio channel

### ISSUE THREAD

**Issue by bls1999** [ruffle-rs/ruffle#3017]
**Describe the bug**
Stereo *music* in this flash file only plays out of the left sound channel. The right ear doesn't hear anything. Oddly enough, this doesn't happen with sound effects -- only the music.

Game Link: https://jiggmin2.com/games/uber-pool
SWF Link: https://jiggmin2.com/games/uber-pool/uber-pool.swf

**Expected behavior**
All sounds should play out of both audio channels.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, latest (nightly 2021-02-01).

**What platform are you using?**
Desktop -- Brave Browser, Mac OS X Mojave.

**Comment by Herschel** [comment]
On my side, this seems to match the behavior of the Flash Player. The game's music code randomly changes the pan of the music for some reason over time:
```
pan = pan + (Math.random() * panChange - panChange / 2);
music.setPan(pan);
```
Is this what you're hearing?

**Comment by Herschel** [comment]
Any remaining weirdness is the game randomly panning the music :-)

**Comment by bls1999** [comment]
Thanks @Herschel!
