### ISSUE TITLE
Trying to connect to a Stanley tool controller and get this error PLEASE HELP

### ISSUE THREAD

**Issue by cbr7703** [ruffle-rs/ruffle#3022]
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

**Comment by cbr7703** [comment]
(()=>{var e={495:e=>{e.exports={getI18nString:function(e){return chrome&&chrome.i18n&&chrome.i18n.getMessage?chrome.i18n.getMessage(e):browser&&browser.i18n&&browser.i18n.getMessage?browser.i18n.getMessage(e):void console.error("Can't get i18n message: "+e)},setSyncStorage:function(e){chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.set?chrome.storage.sync.set(e):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.set?browser.storage.sync.set(e):console.error("Can't set settings.")},getSyncStorage:function(e,r){let o;o="string"==typeof e?[e]:Array.isArray(e)?e:Object.keys(e);let n=e=>{for(const r of o)void 0===e[r]&&(e[r]=t[r]);return r(e)};chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.get?chrome.storage.sync.get(e,n):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.get?browser.storage.sync.get(e,n):console.error("Couldn't read setting: "+e)},reloadTab:function(e,t){chrome&&chrome.tabs&&chrome.tabs.reload?chrome.tabs.reload(e,t):browser&&browser.tabs&&browser.tabs.reload?browser.tabs.reload(e,t):console.error("Couldn't reload tab.")},dictEquality:function(e,t){let r=!0;for(var o in e)Object.prototype.hasOwnProperty.call(e,o)&&(r=r&&e[o]===t[o]);for(let o in t)Object.prototype.hasOwnProperty.call(t,o)&&(r=r&&e[o]===t[o]);return r},tabQuery:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.query?browser.tabs.query.apply(this,arguments):new Promise((function(t){let r=Array.prototype.slice.call(e);r.push(t),chrome.tabs.query.apply(this,r)}))},tabSendmessage:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.sendMessage?browser.tabs.sendMessage.apply(this,arguments):new Promise((function(t,r){let o=Array.prototype.slice.call(e);o.push((function(e){void 0!==chrome.runtime.lastError&&r(chrome.runtime.lastError.message),t(e)})),chrome.tabs.sendMessage.apply(this,o)}))},addStorageChangeListener:function(e){chrome&&chrome.storage&&chrome.storage.onChanged&&chrome.storage.onChanged.addListener?chrome.storage.onChanged.addListener(e):browser&&browser.storage&&browser.storage.onChanged&&browser.storage.onChanged.addListener?browser.storage.onChanged.addListener(e):console.error("Couldn't add setting change listener")},openSettingsPage:function(){chrome&&chrome.tabs&&chrome.tabs.create?chrome.tabs.create({url:"/settings.html"}):browser&&browser.runtime&&browser.runtime.openOptionsPage?browser.runtime.openOptionsPage():console.error("Can't open settings page")},setMessageListener:function(e){chrome&&chrome.runtime&&chrome.runtime.onMessage&&chrome.runtime.onMessage.addListener?chrome.runtime.onMessage.addListener(e):browser&&browser.runtime&&browser.runtime.onMessage&&browser.runtime.onMessage.addListener?browser.runtime.onMessage.addListener(e):console.error("Couldn't add message listener")},getExtensionUrl:function(){return chrome&&chrome.extension&&chrome.extension.getURL?chrome.extension.getURL("dist/ruffle.js").replace("dist/ruffle.js",""):browser&&browser.runtime&&browser.runtime.getURL?browser.runtime.getURL("dist/ruffle.js").replace("dist/ruffle.js",""):void console.error("Couldn't get extension URL")},camelize:function(e){return e.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g,((e,t)=>t.toUpperCase()))}};const t={ruffleEnable:!0,ignoreOptout:!1}}},t={};function r(o){if(t[o])return t[o].exports;var n=t[o]={exports:{}};return e[o](n,n.exports,r),n.exports}(()=>{const{getI18nString:e,setSyncStorage:t,getSyncStorage:o,addStorageChangeListener:n,reloadTab:s,dictEquality:a,tabQuery:i,tabSendmessage:c,openSettingsPage:g,camelize:l}=r(495);let d,u,b={},m={};function h(){let e=!a(b,m);void 0!==d&&(d.disabled=!e)}function w(r){let s=r.name;r.nextSibling.textContent=e("settings_"+s),s=l(s),o(s,(function(e){r.checked=e[s],b[s]=e[s],h()})),n((function(e){Object.prototype.hasOwnProperty.call(e,s)&&(r.checked=e[s].newValue,b[s]=e[s].newValue,h())})),r.addEventListener("click",(function(){let e={};e[s]=r.checked,b[s]=e[s],h(),t(e)}))}async function p(){let t=document.getElementById("ruffle_status");t.textContent=e("status_init");let r=null;try{if(r=await i({currentWindow:!0,active:!0}),r.length<1)return void(t.textContent=e("status_no_tabs"));r.length>1&&console.warn("Got "+r.length+" tabs in response to active tab query")}catch(r){throw t.textContent=e("status_tabs_error"),r}try{u=r[0],t.textContent=e("status_message_init");let o=await c(u.id,{action:"get_page_options"});m=o.tabSettings,h(),void 0!==o&&o.loaded?t.textContent=e("status_result_running"):void 0===o||o.loaded?t.textContent=e("status_result_error"):m.ruffleEnable?t.textContent=e("status_result_optout"):t.textContent=e("status_result_disabled")}catch(r){throw t.textContent=e("status_result_protected"),d&&(d.disabled=!0),r}}document.addEventListener("DOMContentLoaded",(function(){var t,r=document.getElementById("settingsbutton");w(document.getElementById("ruffle_enable")),w(document.getElementById("ignore_optout")),(t=document.getElementById("reload")).textContent=e("action_"+t.id),t.disabled=!0,t.addEventListener("click",(function(){s(u.id,(function(){window.setInterval(p,1e3)}))})),d=t,r.innerHTML=e("open_settings_page"),r.onclick=g,p()}))})()})();

**Comment by Herschel** [comment]
Hi, please fill out the bug description, providing more information so that we can help. (What is the Stanley tool controller? Can you provide a link to it?)
