### ISSUE TITLE
Something that the Ruffle team should keep in mind.

### ISSUE THREAD

**Issue by obscurerev** [ruffle-rs/ruffle#3030]
So there was a full port of Intrusion 2 to flash. It's over 40MB, it is an Actionscript3 game, and for some reason, it displays a grey screen when I attempt to load it into the Cloud SWF flash player. I used the latest PC release of Adobe Flash and it somehow loaded fine on that.

The Cloud SWF Flash player website loads flash content natively through the flash player itself. So I can narrow it down to two reasons why it only works on the PC release, 1: The Cloud SWF flash player is faulty, or 2: The SWF or game is too large to process in an emulator or the online SWF player.

This is not to report a bug, but something the Ruffle team should be aware of when trying to implement Actionscript3 support.

The cloud SWF player: http://flashplayer.fullstacks.net/
The SWF file: https://www.dropbox.com/s/z8e1wr51cae30j1/intrusion-2.swf?dl=0

**Comment by Herschel** [comment]
Thanks for the heads up; looking through the SWF, I don't see anything too out of the ordinary (no Stage3D etc.), but we can keep an eye on it as we work towards support. Nothing left actionable here currently.
