### ISSUE TITLE
Bookworm Game Same Letter

### ISSUE THREAD

**Issue by summerock** [ruffle-rs/ruffle#3031]
Hi I was playing Bookworm, a very educational game ,  at https://kdata1.com/2021/01/bookworm/ using ruffle, but instead of displaying the correct letter for each box, all the box appears as the letter "A". Anyone understand why? 

Thanks in advance

**Comment by Herschel** [comment]
Thanks for the report. Fixed by #3034.

**Comment by summerock** [comment]
Thanks a lot.
