### ISSUE TITLE
on loading of ruffle, the context menu is a 2px by 2px square at the bottom left hand side of the instance

### ISSUE THREAD

**Issue by kingemocut** [ruffle-rs/ruffle#3032]
**Describe the bug**
At the start of any ruffle instance, the context menu will not be hidden on load, and instead will be a 2px by 2px square at the bottom left most section of the div. right clicking will correctly apply the display:none; . this can be tested by having the element inspector open as you refresh the web page.

**Expected behavior**
on loading of the instance of ruffle, it's expected to be hidden, and then when right clicked to pop up as the context menu

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

originally found on a self hosted (but kept up to date) release of ruffle, however it also shows on the demos on the ruffle website itself.

**What platform are you using?**

web version, chrome, on windows 10

an image as the web page loads, before any clicks on the webpage
![image](https://user-images.githubusercontent.com/4548839/106521245-d936f000-64d5-11eb-8f7b-be658649d242.png)

after a left click, showing that it correctly gets hidden
![image](https://user-images.githubusercontent.com/4548839/106521323-fa97dc00-64d5-11eb-83c3-b4fc551fdc6b.png)

same issue on the ruffle demo page
![image](https://user-images.githubusercontent.com/4548839/106522315-72b2d180-64d7-11eb-819c-27468f1286af.png)

showing that you don't need to click on the instance itself to fix it
![image](https://user-images.githubusercontent.com/4548839/106522483-b9083080-64d7-11eb-89d1-8b64e1fa1469.png)

it can be a click on the ruffle player, or a left click on the rest of the web page. right clicking on the ruffle player works as intended and brings up the context menu where it's meant to be.

**Comment by torokati44** [comment]
This should be fixed by https://github.com/ruffle-rs/ruffle/pull/3096
