### ISSUE TITLE
12 Apostles Quiz and Memory Game on Ubuntu Linux

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#3036]
12 Apostles Quiz and Memory Game
OS: Ubuntu 20.04 with Xfce
**Ruffle _Desktop_ Version: ruffle_nightly_2021_02_02_linux**
The_Twelve_Apostles.swf
Game plays perfectly but, Warning in Terminal After Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
Error in Terminal After Closing:
`[2021-02-02T03:06:38Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
**Ruffle _Browser Extension_ Version: ruffle_nightly_2021_02_02_firefox.xpi**
http://christiancliparts.net/viewclip.php?id=g060701
Game plays perfectly. No errors or warnings.

**Comment by n0samu** [comment]
No problem reported, closing
