### ISSUE TITLE
pink layer and subtitle not render correctly

### ISSUE THREAD

**Issue by Oversomebody** [ruffle-rs/ruffle#3041]
link
https://uploads.ungrounded.net//624000//624099_Smile_HD_Final.swf
ruffle version Nightly 2021-02-02 5783021
Windows

-subtitle pink outer layer didnt render
-pink glow didnt render correctly
-right click on title bar will stop frame from rendering and cause audio and video out of sync(audio faster than video)

![Screenshot (28)](https://user-images.githubusercontent.com/31456329/106624037-32735200-65b0-11eb-942b-7c9be949f92c.png)

![Screenshot (23)](https://user-images.githubusercontent.com/31456329/106623830-f9d37880-65af-11eb-8600-121a9f82ab8c.png)

**Comment by Herschel** [comment]
Requires filter effects/blend modes. Closing in favor of #15.
