### ISSUE TITLE
Error on https://e621.net/posts/257069?q=flash+order%3Ascore

### ISSUE THREAD

**Issue by u0ipokdzc0ok** [ruffle-rs/ruffle#3046]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32406
    at r (<anonymous>:3:32896)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/257069?q=flash+order%3Ascore

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
