### ISSUE TITLE
ci: Nightly web builds not run throguh wasm-opt

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#3052]
Since https://github.com/ruffle-rs/ruffle/pull/2974, wasm-opt no longer runs on the web build:

https://github.com/ruffle-rs/ruffle/runs/1818813238?check_suite_focus=true#step:9:280

Compared to:
https://github.com/ruffle-rs/ruffle/runs/1803127700?check_suite_focus=true#step:9:260

If possible, it'd be nice if we can error in this case on CI, while still keeping it optional for end-users building on their own machines.

**Comment by relrelb** [comment]
Turns out that `shell: bash -l {0}` is necessary after all. Will get to this today. Also requirement of `wasm-opt` in CI is a good idea.

**Comment by torokati44** [comment]
I should have commented those lines better right when they were added... :no_mouth:
