### ISSUE TITLE
Menu effect obscures content (transparency/layer bug?)

### ISSUE THREAD

**Issue by bls1999** [ruffle-rs/ruffle#3061]
**Describe the bug**
In this game, the main menu is completely covered by what looks to be some kind of wavy visual effect that would normally appear under the menu. [Here's a video side-by-side of what it should look like and what it actually looks like](https://youtu.be/QAiJE-a_reQ).

Game Link: https://jiggmin2.com/games/kimblis-the-blue
SWF Link: https://jiggmin2.com/games/kimblis-the-blue/kimblis-the-blue.swf

**Expected behavior**
See video ^^

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, nightly 2021-02-03.

**What platform are you using?**
Desktop -- Brave Browser, Mac OS X Mojave.

**Comment by torokati44** [comment]
Looks like this needs blend modes: https://github.com/ruffle-rs/ruffle/issues/58

**Comment by Lord-McSweeney** [comment]
Fixed by #8262.
