### ISSUE TITLE
Graphics flash in a checkered pattern

### ISSUE THREAD

**Issue by bls1999** [ruffle-rs/ruffle#3062]
**Describe the bug**
In a few games I've tested, there's an odd graphical glitch that looks like a checkerboard is flashing on the screen. [Here's a video of what I'm talking about](https://youtu.be/fdJF7lMczBM).

Games Shown:
 - Kimblis the Blue ([Game Link](https://jiggmin2.com/games/kimblis-the-blue) | [SWF Link](https://jiggmin2.com/games/kimblis-the-blue/kimblis-the-blue.swf))
 - The Game of Disorientation ([Game Link](https://jiggmin2.com/games/the-game-of-disorientation) | [SWF Link](https://jiggmin2.com/games/the-game-of-disorientation/the-game-of-disorientation.swf))
 - Red Earth ([Game Link](https://jiggmin2.com/games/red-earth) | [SWF Link](https://jiggmin2.com/games/red-earth/red-earth.swf))

**Expected behavior**
The graphics should be displayed without flashing.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, nightly 2021-02-03.

**What platform are you using?**
Desktop -- Brave Browser, Mac OS X Mojave.

**Comment by n0samu** [comment]
I'm not seeing this problem anymore in Red Earth - can you confirm that the problem is fixed?
I can't check Kimblis the Blue because I can't get the game to work at all in Ruffle. All I see is a fog animation, not the actual menu.

**Comment by n0samu** [comment]
Kimblis the Blue needs the 'overlay' blend mode (#58). With #8262, it looks great!

**Comment by n0samu** [comment]
@bls1999 asking again now, is the checkerboard graphics problem fixed for you?

**Comment by bls1999** [comment]
> @bls1999 asking again now, is the checkerboard graphics problem fixed for you?

Seems to be! I'll re-open if it appears again. Thanks for circling back!
