### ISSUE TITLE
Item combinations fail in all Steppenwolf games.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#3070]
**Describe the bug**
![steppenwolf-drag-and-drop-issue](https://user-images.githubusercontent.com/75052171/106844910-1c1ee080-66ed-11eb-924f-d79608574f30.png)

I don't know if this corresponds to the already reported Drag&Drop issue, but in all of Steppenwolf's series, the item combination failed and the game cannot proceed any further.

- Adobe Flash Player: Item combination cutscene played
- Ruffle: Item combination failed (recognized as a simple click and replaced with a liquor bottle)

[steppenwolf-1-1.zip](https://github.com/ruffle-rs/ruffle/files/5936689/steppenwolf-1-1.zip)

**Expected behavior**
Item combination cutscene played & combined item is created

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Probably for all versions.

**What platform are you using?**
Desktop, Windows 10 x64, Google Chrome Lastest build, Ruffle Nightly 2021-02-04

**Comment by jooy0224** [comment]
It is temporarily share the Steppenwolf 1-1 file for reproduction.

https://cdn.flasharch.com/files/shared/steppenwolf-1-1.swf

**Comment by Toad06** [comment]
Thanks for the report. `_droptarget` needs to be implemented for this to work (#795, #1451).

**Comment by jooy0224** [comment]
Thanks for the clarity. If this feature is implemented, it will solve the problem in many Dress up games, Jigsaw Puzzle games, and more!

**Comment by Herschel** [comment]
Fixed by #4584.
