### ISSUE TITLE
Top Striker game: the ball is not rendered properly (white square or no ball at all)

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3075]
**Describe the bug**

There's a bug with the ball animation that looks different on Firefox and Chrome in the Top Striker game (https://funkypotato.com/top-striker/):

- Firefox: the ball is a white square (as seen on the screenshot below)
- Chrome: the ball is not visible at all

**Expected behavior**

Fixing ball rendering so that it looks like a ball :)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

This affects all Ruffle versions.

**What platform are you using?**
 Mac OS X, Firefox 85 & Chrome 88
 
<img width="825" alt="striker_bug" src="https://user-images.githubusercontent.com/22566535/106880516-bdea0180-66dc-11eb-806d-ed479caa3899.png">

**Comment by Toad06** [comment]
Thanks for the report.

The following error is logged into the browser's console, I believe it's related to this issue:
`Error running definition tag: DefineBitsJpeg3, got invalid JPEG format: 4 components without Adobe APP14 metadata to indicate color space`

This message is logged 66 times, it appears that other sprites are also affected.
