### ISSUE TITLE
Change appearance of web context menu a bit

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#3078]
4, maybe 5 px (or maybe 0.6em?) border radius for both the context menu and the hovered state of menu items.

Light gray instead of gray border.

Exo 2 instead of Arial.

![image](https://user-images.githubusercontent.com/51363864/106885871-57460180-6737-11eb-9850-e84e00188fa3.png)

![image](https://user-images.githubusercontent.com/51363864/106885942-704eb280-6737-11eb-8c6b-cfe0d70173f8.png)

![image](https://user-images.githubusercontent.com/51363864/106886642-3a5dfe00-6738-11eb-898d-7ab3e9d7ed29.png)

Looks softer and maybe even macOS-like. 

What're your thoughts?

**Comment by rvh1986** [comment]
Sorry if this should be in a separate issue, but when fullscreen is not allowed, the bar above it is still visible, which looks odd imo.

![Untitled-1](https://user-images.githubusercontent.com/20386982/106892718-c1858480-66ec-11eb-9fd9-f3ca829438f3.png)

**Comment by Poopooracoocoo** [comment]
@rvh1986 defs a separate issue. In #2814 Adrian did say that the separator code was ugly and needs a refactor down the line.
