### ISSUE TITLE
Scrabble Blast game bug: letter tiles not visible

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3082]
**Describe the bug**
Scrabble Blast game located here: http://www.wiredarcade.com/game/502/Scrabble-Blast.html has a weird bug.

After getting through the two first screens, there should be many Scrabble letter tiles and other objects visible  on the right-hand side of the screen. Ruffle doesn't render them, there's only a brown rectangle. The tiles are there and can be selected by clicking on the brown screen and dragging the mouse, so game logic is intact, but tiles themselves are invisible.

This behavior can be seen on the video here: https://youtu.be/Qi00kUXcelQ or on the screenshot below:

<img width="618" alt="105326502-19d96400-5bce-11eb-9d34-f438d1c66aeb" src="https://user-images.githubusercontent.com/22566535/106902421-1c24dd80-66f9-11eb-8b9c-147cb2f177c9.png">

**Expected behavior**
The letter tiles and additional objects should be visible.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
The problem affects all Ruffle versions.

**What platform are you using?**
 Windows 7, 10, Mac OS X, Firefox 85 and Chrome 88

**Comment by ousia** [comment]
@perelowski,

GitHub allows attaching videos:

https://user-images.githubusercontent.com/203767/106942984-1e049600-6725-11eb-9d88-89b73629eae7.mp4

**Comment by torokati44** [comment]
With the latest nightly, the tiles are visible, and the game looks perfectly playable to me. Can you verify, @perelowski?

**Comment by perelowski** [comment]
@torokati44 - yes, the game is perfectly playable now. The issue can be closed.
