### ISSUE TITLE
Error on https://archive.org/details/minecraft-tower-defence-2

### ISSUE THREAD

**Issue by Qerim-iseni09** [ruffle-rs/ruffle#3091]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:838:49

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/minecraft-tower-defence-2

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-03
Channel: nightly
Built: 2021-02-03T00:18:37.586Z
Commit: 59966348c6e7adf88f2cf28e5ebdcebc9f2c0881

**Comment by Poopooracoocoo** [comment]
When do you encounter the crash? 

Can you reproduce this on a new browser? If you don't want to update Firefox, consider installing Chrome/Brave/Vivaldi, etc to test this on.

**Comment by Poopooracoocoo** [comment]
Ruffle requires Firefox 84 and above to function.
