### ISSUE TITLE
SWF does not open, but downloads instead

### ISSUE THREAD

**Issue by berthold1983** [ruffle-rs/ruffle#3093]
**Describe the bug**

URL: http://jiddischkurs.org/index2.htm
Menue: Zeitbezug, there try either "Zur Geschichte des Jiddischen" or "Gegenwartsbezüge".
Instead of playing the SWF, it showed me the downloadwindow 
Downloades files:
gegenwart.swf
geschichte.swf

both files are ok and displayed correctly in https://ruffle.rs/demo/
[files.zip](https://github.com/ruffle-rs/ruffle/files/5928170/files.zip)

Version:
ruffle_nightly_2021_02_04_firefox.xpi
Browser: Mozilla Firefox for Ubuntu 85.0 (64 bit) 
OS: Description:	Ubuntu 18.04.5 LTS

**Comment by relrelb** [comment]
Duplicate of #2167?

**Comment by caydenpri44** [comment]
Your reopening the .swf file in a new tab from the source code which will cause the file to download.

**Comment by berthold1983** [comment]
Yes, ist should be a duplicate of #2167
