### ISSUE TITLE
docs: make AS3/AVM2 info on ruffle.rs and FAQ match

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#3100]
https://ruffle.rs/#compatibility:~:text=AVM%202,-AVM2 
https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content

**Comment by n0samu** [comment]
I just noticed that this is the only open issue with the "docs" label. I don't understand what you were trying to point out here, do you remember?

**Comment by Poopooracoocoo** [comment]
Nope. Closing this.
