### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/guerra-de-papel.html

### ISSUE THREAD

**Issue by dannvader** [ruffle-rs/ruffle#3103]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
    at Object.Y (https://www.juegosarea.com/js/ruffle/core.ruffle.8523be3f1afb3ed16c0c.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (https://www.juegosarea.com/js/ruffle/ruffle.js:1:35853)
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1117]:0x22cea9
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[1457]:0x26f425
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3876]:0x329523
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[3036]:0x3092fe
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4179]:0x32e379
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4209]:0x32e8dc
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4082]:0x32cecc
    at https://www.juegosarea.com/js/ruffle/dbf98fe6de1f14b77b7a.module.wasm:wasm-function[4210]:0x32e912
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/guerra-de-papel.html
SWF URL: https://cdn.juegosarea.com/files/games/gu/er/guerra-de-papel.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by adrian17** [comment]
This was already fixed in january (https://github.com/ruffle-rs/ruffle/pull/2228). juegosarea.com needs to update its hosted version of Ruffle.

**Comment by relrelb** [comment]
Seems to have been fixed.
