### ISSUE TITLE
Error on https://www.crazygames.com/gameframe/sonny-2

### ISSUE THREAD

**Issue by stranger777** [ruffle-rs/ruffle#3110]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3108:14

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.crazygames.com/gameframe/sonny-2
SWF URL: https://files.crazygames.com/sonny2.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 YaBrowser/20.12.3.140 Yowser/2.5 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
@stranger777 when did you see the panic? immediately? after a certain event/action? Also note that Crazy Games has updated their version of Ruffle to a slightly newer one.

**Comment by stranger777** [comment]
@Poopooracoocoo I saw the panic immediately. Now I don't see it. Thanks for your amazing emulator! I miss the Flash...
