### ISSUE TITLE
Error running definition tag: DefineFont2, got Invalid data: Invalid fill style - No Text is displayed

### ISSUE THREAD

**Issue by Elementtair** [ruffle-rs/ruffle#3115]
I already posted my issue on Oussia thread  #1560 but as it's not exactly the same I submit it more precisely.
Only difference is #1560 is DefineFont3
Otherway it was made with swftools pdf2swf quite some time ago
with flash it gives the expected rendering :
<a href="https://ibb.co/tLZ8Lc0"><img src="https://i.ibb.co/tLZ8Lc0/m110-Flash.jpg" alt="m110-Flash" border="0"></a>

Rendered with Ruffle webhosted, latest nighly build or win64 Ruffle.exe give this:
<a href="https://ibb.co/1zYRc2P"><img src="https://i.ibb.co/1zYRc2P/m110-Ruffle.jpg" alt="m110-Ruffle" border="0"></a>
... All the text is missing.

The console give this error ( mentionned in title)
![m110 Console Ruffle](https://user-images.githubusercontent.com/75228621/107086165-e3b8f880-67f9-11eb-9d72-d5330e52297d.JPG)

here is the pictured swf files (but it does  this with most our flash files from that time).
[05-M110calage.zip](https://github.com/ruffle-rs/ruffle/files/5935024/05-M110calage.zip)

Great job for Ruffle anyway!

**Comment by ousia** [comment]
I wonder what might be the fill style that Ruffle cannot handle as valid.

**Comment by Elementtair** [comment]
Here is the DefineFont2 I can see from JPEXS Flash Decompiler
![m110 DefineFont2](https://user-images.githubusercontent.com/75228621/107098909-a57b0380-6810-11eb-97af-b15c3587dddd.JPG)

Don't know it it's a normal one, but the soft read&display the file correctly.

Those swf that don't display text well have all been made with pdf2swf from an old version, possibly 0.8.1
I see no issue with Flash files made with latest version of SWFTools

**Comment by ousia** [comment]
@Elementtair,

could you provide a new SWF from the same PDF document (using latest pdf2swf version)?

I have issues with latest released SWFTools version (namely 0.9.2).

Which version do you use? Current master from https://github.com/matthiaskramm/swftools?

Many thanks for your help.

**Comment by Elementtair** [comment]
@ousia 
I don't own the original pdf so I can't test.
I'm using the 2013-04-09-1007 release of swftools on windows10 x64.

And in fact, I forgot in my previous comment but I didn't really tried with a direct conversion of pdf;
Latest pdf I coberted where made of image and there's no error with images... that's why I have no issue for now.

The same result could be obtain with the  -S option of pdf2swf (I think, but I didn't tested).

You could also try with -F or -f option, to see if there's an effect on fonts.

**Comment by ousia** [comment]
@Elementair,

many thanks for your suggestion, since `-f` seems to solve the issue.

I need to investigate this further, but this is rather weird.

The PDF source already embeds a subset font, so I don’t know why subsetting is required again.

This refers to #1560. But if there is an issue with subsetting, the fix could be applied here too.

**Comment by Elementtair** [comment]
@ousia
From what I understand, without -f the font is reduced to used character only ( like you can see in the posted Definefont2 I posted earlier), while with -f the full font is stored in the resulting flash file.

=> I think your test will be an interesting step further for developers.

It's possible that Ruffle struggle on those missing characters, expecting the full font all the time.
... and that's was my first impression, that #1560 seemed very similar

**Comment by ousia** [comment]
@Elementtair, the font in the PDF document only contains the embedded glyphs.

From what I understand from `swfdump -D` output, it might be that handling blank spaces could be problematic for Ruffle.

But this is the proper matter for #2999.

**Comment by Elementtair** [comment]
Is there a way to change the label from "bug" to "text" ?  Can't find the way it has to be done...

**Comment by Elementtair** [comment]
For now, with latest ruffle versions, there's no change for this bug.

**Comment by ousia** [comment]
I’m afraid this has to be done by any of the main developers.

Anyway, I wonder why the JPEXS Flash Decompiler can read the font (I wonder whether its author know what could be done to fix this bug).

**Comment by relrelb** [comment]
Fixed by #6444.

**Comment by Elementtair** [comment]
Very well. This one is fixed. I got other files with similar error that did't get fixed by this update. 

'Will fill an issue tonight.
