### ISSUE TITLE
Add Support for FlashVars

### ISSUE THREAD

**Issue by PsychoGoldfishNG** [ruffle-rs/ruffle#312]
A lot of SWFs rely on external variables being passed in. 

Ruffle will need to look for a few things when replacing existing embeds:
<PARAM NAME="FlashVars" VALUE="..."> in the <OBJECT> tag
or
FashVars attribute in <EMBED> tag

Other implementations may be passing a query string directly with the swf url, eg myFlash.swf?var1=value1&var2=value2

**Comment by PsychoGoldfishNG** [comment]
Should probably add a way to pass these vars directly through the JS config as well

**Comment by Herschel** [comment]
For the desktop player, these could be passed via command line, as a query string (or JSON?).

For the polyfill web player, we need to grab these out of the embed/object tags.
For the web JS API, we should provide an API `RufflePlayer.set_flash_vars` to set this. It could take a JS object or query string.

On the Rust side, we need to add an API to core to set the flash vars. The flash vars just get some as vars on `_level0` (or in the `LoaderInfo` object in AVM2).
