### ISSUE TITLE
Transparent SWF background support on webpages?

### ISSUE THREAD

**Issue by ShikiSuen** [ruffle-rs/ruffle#3124]
I tried this webpage and found that the transparent SWF backgrounds are all shown in non-transparent:

http://swd.joypark.com.tw/SWDHC/intro/intro05_4.aspx

**Comment by ousia** [comment]
http://swd.joypark.com.tw//SWDHC/globalNav.swf is embedded using the following code:

``` html
<param name="bgcolor" value="#ffffff" />
<param name="wmode" value="transparent" />
```

According to the following code by @Herschel,

https://github.com/ruffle-rs/ruffle/blob/60f29719d36432e305a1b568035f7b97ffc08cbb/render/canvas/src/lib.rs#L119

I’d say that this is an unimplemented feature.

**Comment by Herschel** [comment]
Duplicate of #1752.
