### ISSUE TITLE
MIME type incorrect

### ISSUE THREAD

**Issue by SirTifficat** [ruffle-rs/ruffle#3125]
You asked for the names of servers that gave the error about incorrect MIME type. I get that message on my PC and Kindle. Interestingly on my iphone I do not get that message. But the flash file works erratically. I have only one page with the ruffle script in at the moment.
 https://www.pennygames.org.uk/swf%20animations/pgna.htm 
My flash files are very simple stop start animations controlled by a toggle button. Hope this helps.

Here's my site details from Hostinger. I have been in touch with them but no joy.

**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

**Comment by SirTifficat** [comment]
Hosting plan
Single
Server
Lithuania, server241
IP address
46.17.175.81
Main Domain
pennygames.org.uk
Home root
/home/u281947892
Web Server
LiteSpeed
Hostinger nameservers
ns1.dns-parking.com
ns2.dns-parking.com
MySQL version
10.2
MySQL Databases
Disk Usage
1%
Inodes
1%
Email Accounts
Subdomains

**Comment by Herschel** [comment]
Try updating to the latest Ruffle. Serving the file with the proper MIME is not a strict requirement anymore, and the file should hopefully work regardless.

**Comment by Herschel** [comment]
Thanks for the kind words! Marking as resolved. Improved performance and streaming support are logged in #18.
