### ISSUE TITLE
Drag/Drop not registering drop

### ISSUE THREAD

**Issue by p616** [ruffle-rs/ruffle#3139]
**Describe the bug**
http://aztec.sakura.ne.jp/escapefromoctlien/index.html
This game requires you to drag and drop items from your inventory to where you want to use them, but the drop is igored (item just gets sent back to inventory without being used).  Makes it impossible to progress.
Easiest way to repro is to pick up the shovel on the left side of first scene then drag it from your inventory to the "check" button, which would normally show you item details.  Nothing happens.
Another is to move the rock on the right side and pick up the "wheel'.  Ride the crane up one level and try to drag the wheel to the box with the white circle on it to attach.  Again nada.

**Expected behavior**
Drag and drop items from inventory to the "check" button should show item details.  
Drag and drop items from inventory to appropriate place in-game should "use".

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension.

**What platform are you using?**
Chrome 88.0.4324.146 64-bit on Windows 10.

**Comment by brain-death** [comment]
Same thing (AS2)? Arch Linux, Firefox extension.

https://astrologywizard.com/gameone.htm

https://astrologywizard.com/gametwo.htm

**Comment by p616** [comment]
> Same thing (AS2)? Arch Linux, Firefox extension.
> 
> https://astrologywizard.com/gameone.htm
> 
> https://astrologywizard.com/gametwo.htm

looks the same to me

**Comment by Herschel** [comment]
Fixed by #4584.
