### ISSUE TITLE
Errors on AS2 Rollovers

### ISSUE THREAD

**Issue by brain-death** [ruffle-rs/ruffle#3144]
https://astrologywizard.com/signs.htm

**Expected Behaviour**

Sign symbols change colour (I think) and play a sound on rollover.

**Describe The Bug**

Rollovers don't work. Sound doesn't play and colours only visible sporadically, else everything is grey.

All sounds appear to play on page load. Links work though...

**Platform Etc...**

Arch Linux. Firefox extension.

**Comment by n0samu** [comment]
This problem occurs because Ruffle is not firing rollout events on objects within the movie when the mouse leaves the content area. Thus the button stays in the rollover state all the time instead of toggling between these states when the mouse enters/leaves the content area.

**Comment by torokati44** [comment]
I think this is the same fundamental issue as https://github.com/ruffle-rs/ruffle/issues/7113 .

**Comment by Lord-McSweeney** [comment]
Still occurring.

**Comment by Lord-McSweeney** [comment]
Fixed by #10622.
