### ISSUE TITLE
The Beginner's Bible: Match Game

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#3146]
Ruffle Desktop Version: ruffle_nightly_2021_2_06_linux
OS: Ubuntu 20.04 with Xfce
zon_match.swf
Clicking stars (tiles) does nothing. Game is unplayable.
Warning in Terminal After Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
Error in Terminal After Closing:
`[2021-02-07T22:56:47Z ERROR ruffle_core::library] Tried to instantiate non-registered character 
[2021-02-07T23:00:46Z ERROR ruffle_core::library] Tried to instantiate non-registered character 
[2021-02-07T23:00:53Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
Ruffle Browser Extension Version: ruffle_nightly_2021_02_06_firefox.xpi
Base web page http://www.thebeginnersbible.com/kids.php
www.thebeginnersbible.com/games/match/
White square where game should be.
![The-Beginners-Bible-Match-Game](https://user-images.githubusercontent.com/59814178/107163785-746a1280-6979-11eb-834e-8084be23999b.png)

**Comment by Lord-McSweeney** [comment]
This looks like it works fine in the latest versions of Ruffle.
