### ISSUE TITLE
The Beginner's Bible: Jigsaw Puzzle

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#3147]
Ruffle Desktop Version: ruffle_nightly_2021_2_06_linux
OS: Ubuntu 20.04 with Xfce
zon_puzzle1.swf
Game essentially works, all three levels (easy, medium, hard) but, sometimes a puzzle piece is selected far from where the user clicked. It seems the user has no control over which piece is selected - at least not at first. The user can click right on the piece that was selected and started moving already. In this screen shot, the puzzle piece selected is the one with the shadow cast behind it; well below the cursor. When this same game is played with Adobe stand-alone Flash Player 32,0,0,414 the puzzle pieces clicked are selected and clicking elswhere does nothing.
Warning in Terminal After Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
Error in Terminal After Closing:
`[2021-02-07T23:24:13Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
Ruffle Browser Extension Version: ruffle_nightly_2021_02_06_firefox.xpi
Base web page http://www.thebeginnersbible.com/kids.php
www.thebeginnersbible.com/games/puzzle/01.php/
White square where game should be.
![The-Beginners-Bible-Jigsaw-Puzzle](https://user-images.githubusercontent.com/59814178/107163826-ba26db00-6979-11eb-9c1b-84c89eb68e9d.png)
![The-Beginners-Bible-Jigsaw-Puzzle-Adobe](https://user-images.githubusercontent.com/59814178/107163830-beeb8f00-6979-11eb-9a16-8884b7fa2261.png)

**Comment by Lord-McSweeney** [comment]
This looks like it works fine in the latest versions of Ruffle.
