### ISSUE TITLE
The Beginner's Bible: Spot the Difference

### ISSUE THREAD

**Issue by C4C-Web** [ruffle-rs/ruffle#3148]
Ruffle Desktop Version: ruffle_nightly_2021_2_06_linux
OS: Ubuntu 20.04 with Xfce
zon_spot_diff_1.swf
Game works perfectly - once. A successful turn (spotting all the differences) brings the user back to s screen where they may choose to play again. Clicking the "Play Again" button however, does nothing. In the Terminal, clicking that button results in the following error, `[2021-02-07T23:40:02Z ERROR ruffle_desktop::navigator] Could not parse URL because of relative URL without a base, the corrupt URL was: 02.php`
Of course, that's likely because it's not intended to be played on the Desktop. Clicking the "Play Again" button on the SWF file played through the Adobe stand-alone Flash Player 32,0,0,414 doesn't do anything either.
Warning in Terminal After Opening:
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`
Error in Terminal After Closing:
`[2021-02-07T23:47:08Z ERROR gpu_descriptor::allocator] `DescriptorAllocator` is dropped while some descriptor sets were not deallocated`
Ruffle Browser Extension Version: ruffle_nightly_2021_02_06_firefox.xpi
Base web page http://www.thebeginnersbible.com/kids.php
www.thebeginnersbible.com/games/difference/01.php
White square where game should be.
![The-Beginners-Bible-Spot-the-Difference](https://user-images.githubusercontent.com/59814178/107163901-2c97bb00-697a-11eb-987d-e58d2771037a.png)

**Comment by n0samu** [comment]
Working now - I think this was fixed by #10777
