### ISSUE TITLE
Error on https://e621.net/posts/1638779

### ISSUE THREAD

**Issue by Animentaiku** [ruffle-rs/ruffle#3154]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32414
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1638779

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-06
Channel: nightly
Built: 2021-02-06T00:17:26.623Z
Commit: 60f29719d36432e305a1b568035f7b97ffc08cbb

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
