### ISSUE TITLE
web: Live Puzzle - Font bug & Tiles bugged

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#3159]
Hello,

the font is bugged in the title and the tiles are bugged and not where they should be.

https://www.newgrounds.com/portal/view/615696?emulate=flash

Best Regards
Marcel

**Comment by ousia** [comment]
@desertking,

I guess you mean the title on the upper right corner:

![wrngglpyhs](https://user-images.githubusercontent.com/203767/107283096-35f95400-6a5c-11eb-83b7-90de1169f19a.png)

Adobe Flash displays it this way:

![right gyphs](https://user-images.githubusercontent.com/203767/107283149-44477000-6a5c-11eb-9ffe-1b8227211f77.png)

I hope it helps.

**Comment by desertking** [comment]
Yeah thanks. That's what I meant, also the puzzles are broken as they completely overlap and are not framed into the tile :)

**Comment by relrelb** [comment]
The problem with the tiles is that `MovieClip.scrollRect` is currently unimplemented.

**Comment by n0samu** [comment]
Fixed by #7770
