### ISSUE TITLE
Crash in original Chibi Knight when leaving dungeon area: Called `Option::unwrap()` on a 'None' value

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#3161]
**Describe the bug**
In the original Chibi Knight (https://www.newgrounds.com/portal/view/526470) - when you leave the dungeon area after beating the 3 knights, Ruffle crashes.

Here is a screenshot of the console after the crash:
![chibi knight crash](https://user-images.githubusercontent.com/40899110/107260613-24c82d00-69f3-11eb-9e0b-5767926de1b5.png)

**Expected behavior**
No crash.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted on Newgrounds

**What platform are you using?**
 - PC, Chrome

**Comment by n0samu** [comment]
Reported to be fixed, almost certainly by #9447. 🎉
