### ISSUE TITLE
Web builds launched from non-bash-like shells (e.g. CMD.EXE) fail without wasm-opt

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#3162]
This is (not unexpectedly) caused by #3111.
Originally @Toad06 reported here: https://github.com/ruffle-rs/ruffle/pull/3111#issuecomment-774516847

This issue is mostly "for the record", and also bit to calm my conscience.

Either installing `wasm-opt` (`binaryen`), or switching to a bash-like shell (or both...) avoids the failure.

I am fine with reverting #3111 if this regression is considered serious enough, compared to its slight advantage - I still couldn't come up with a more portable solution since.
Otherwise, hopefully this issue will be of help for others running into this failure in the future, for finding an easy workaround: just remove that check for `$GITHUB_ACTIONS`. :)

**Comment by hcs64** [comment]
I'm also encountering this even though I'm running from `bash` and my SHELL=bash.

```
ruffle-core: > echo 'NOTE: Since wasm-opt could not be found (or it failed), the resulting module might not perform that well, but it should still wo
rk.' && [[ $GITHUB_ACTIONS != true ]]
ruffle-core: NOTE: Since wasm-opt could not be found (or it failed), the resulting module might not perform that well, but it should still work.
ruffle-core: sh: 1: [[: not found
```

Somehow it ends up starting `sh`. If I change it to use `[ \"$GITHUB_ACTIONS\" != true ]` it works, though this wouldn't help on Windows.
