### ISSUE TITLE
Error on https://e621.net/posts/712362

### ISSUE THREAD

**Issue by scott12330** [ruffle-rs/ruffle#3166]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32414
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/712362

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-09
Channel: nightly
Built: 2021-02-09T00:17:51.319Z
Commit: 16bd7fade68e1f42df84414e3d76a593c64dc09a

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
