### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by harunalikadic** [ruffle-rs/ruffle#3167]
Hi, I have tried the ruffle player to load my two flash games (website self hosted), but all I see is a black screen. On one game I can hear music being loaded:
http://public.harun.it/snowinvaders/

Is there something I can do to debug and test?
Thanks.
Harun.

**Comment by Herschel** [comment]
Hi,
On my PC this seems to work correctly (I see Ruffle running on the website).
Could you provide more information about what system you are running? (OS and browser).
Do you see any output in the browser console (if you press F12)?

**Comment by harunalikadic** [comment]
Hi, I am on Chrome 88.0.4324.96 on Mac OS 11.1.
Yes, I get this msg in console:
```
ruffle_web.js:434 `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
Is it because, as ruffle website points out, the server needs to support .wasm, and mine, for some reason, doesn't?
Then, why are you viewing it correctly? Maybe because you are using some additional player (chrome extension or local)?

Tnx.

**Comment by Herschel** [comment]
This sounds like another case of https://github.com/ruffle-rs/ruffle/issues/671 where Chrome on certain MacOS devices gets a black screen.

**Comment by harunalikadic** [comment]
Works perfectly on Safari

**Comment by Herschel** [comment]
Okay, thanks for the report! Closing in favor of #671 since it appears to be the same issue.
