### ISSUE TITLE
CVS pharmacy tech flash player training - loading bar only

### ISSUE THREAD

**Issue by hubuser2156** [ruffle-rs/ruffle#3178]
Good afternoon,
I do not know much about the technology that goes into ruffle or coding, it is not my area. I am a pharmacy technician trying to get my national certification, and saw that ruffle can help me access the flash player content I need to complete my training thru my employer, CVS. But, when I installed the Chrome extension, all I get is a white page with a grey loading bar. Usually, before 2021, the page was interactive where you click on different things to go from one assignment to another. I do not know if this is already a known bug or not or if there is a known workaround. Thank you

**Comment by llacb47** [comment]
URL of the page? Are you allowed to share it?

**Comment by hubuser2156** [comment]
That is a very good point. I don't think it would be advisable given that
it's a secured website area only for employee training. maybe I'm stuck
with this. *facepalm* On the other hand I found out that I do not
absolutely have to complete these trainings before testing, although it
would definitely help with learning, so that's good.

**Comment by adrian17** [comment]
Impossible to debug without access, and probably long overdue - closing.
