### ISSUE TITLE
Cannot drag click in any game-- found out in https://www.comdotgame.com/play/tekken-miguel-caballero-rojo (WARNING- Sexual content)

### ISSUE THREAD

**Issue by SadCart** [ruffle-rs/ruffle#3183]
**Describe the bug**
I cannot drag click :(

**Expected behavior**
I expected to be able to click and drag my mouse but when I do so I get no progression on the game.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension.

**What platform are you using?**
Browser, Windows 10

**Comment by Herschel** [comment]
Fixed by #4584.
