### ISSUE TITLE
Preloaded sounds (mp3) are not played 

### ISSUE THREAD

**Issue by ondaeduca** [ruffle-rs/ruffle#3188]
Platform "Espacio Onda".
Our apps, preload an array of sounds (FX and activity sounds), to avoid delays in the use of the games streaming. I think Ruffle does not load them and therefore they are not played.

Attached is a video showing how it works with FP in an own browser (electron) and later in crhome.

Example: "Espacio Onda"/ app- Oposiciones
link: https://espacioonda.ondaeduca.com

Browser: chrome 88
System: windows PC

video: https://www.ondaeduca.com/videos_ruffle/sonido_mp3.mp4
          https://www.ondaeduca.com/videos_ruffle/sonido mp3_animacuentos_fonemas.mp4

**Comment by sombraguerrero** [comment]
I have tested this further and confirmed that it is indeed because the MP3s are being externally loaded. As long as the original encoding matches, I can replace the MP3s with anything via FTP and Flash will play it on-shot. This would indicate that there's an alternate path in Flash to parsing from the SWF SoundStream block as we are currently doing.

**Comment by sombraguerrero** [comment]
Talked this one over with Mike and confirmed that this is due to the Sound class being unimplemented.
Posting oposiciones -> caseta4.swf as an example.
[caseta_4.zip](https://github.com/ruffle-rs/ruffle/files/6178382/caseta_4.zip)

`reproducir_sonido = function()
                                 {
                                    trace("reproducir sonido");
                                    if(_global.sound_enabled == true)
                                    {
                                       var my_sound1 = new Sound();
                                       my_sound1.loadSound(sonido,true);
                                       my_sound1.onLoad = function(success)
                                       {
                                          if(success)
                                          {
                                             my_sound1.start();
                                          }
                                       };
                                    }
                                 };`

**Comment by sombraguerrero** [comment]
#273

**Comment by sombraguerrero** [comment]
This is fundamentally resolved as of the merging of #6738.

**Comment by ondaeduca** [comment]
external audio loading, works fantastic. 
thanks!!
