### ISSUE TITLE
The drag and drop function  not work

### ISSUE THREAD

**Issue by ondaeduca** [ruffle-rs/ruffle#3191]
The drag ad drop function of our activities does not work. When trying to drag and drop a tile to its destination, it is not validated and the game crashes. Attached is an example of two activities.

System: windows pC
browser: chrome 88

Video: https://www.ondaeduca.com/videos_ruffle/drag&drop.mp4

**Action scrip:**
[example_ drag&drop.zip](https://github.com/ruffle-rs/ruffle/files/5960608/example_.drag.drop.zip)
!!(the files cannot be opened outside your main app, but I attach them for help see the code)

function dragSetup(clip, targ, finalx, finaly, ficha_ver)
{
   clip.onPress = function()
   {
      _root.nivel = _root.nivel + 1;
      this.swapDepths(_root.nivel);
      _root.nivel = _root.nivel + 1;
      _root.solucion_1.swapDepths(_root.nivel);
      _root.nivel = _root.nivel + 1;
      _root.solucion_2.swapDepths(_root.nivel);
      startDrag(this,0);
   };
   clip.onRollOver = function()
   {
      this.gotoAndPlay("activo");
   };
   clip.onRollOut = function()
   {
      this.gotoAndPlay("activoFin");
   };
   clip.myHomeX = clip._x;
   clip.myHomeY = clip._y;
   clip.myFinalX = finalx;
   clip.myFinalY = finaly;
   clip.onRelease = clip.onReleaseOutside = function()

**Comment by sombraguerrero** [comment]
Note to self to retest this in the next couple days as PR #3893 may address this.

**Comment by sombraguerrero** [comment]
3893 is not relevant to this as the onRelease and onReleaseOutside handlers need to be implemented.

**Comment by sombraguerrero** [comment]
#263 
#243

**Comment by sombraguerrero** [comment]
I won't bother logging a separate defect, but Morfosintaxis does require several event handlers from MovieClip as well as the loadMovie function.

**Comment by ondaeduca** [comment]
I think it would be better to create an issue for new Morfosintaxis, since no the problem is not related to the drag & drop function

 

 

 

De: Robert Setter ***@***.***> 
Enviado el: viernes, 09 de abril de 2021 8:29
Para: ruffle-rs/ruffle ***@***.***>
CC: Javier Yañez ***@***.***>; Author ***@***.***>
Asunto: Re: [ruffle-rs/ruffle] The drag and drop function not work (#3191)

 

I won't bother logging a separate defect, but Morfosintaxis does require several event handlers from MovieClip as well as the loadMovie function.

**Comment by Herschel** [comment]
Should be implemented in #4584, can you please check and verify that this is fixed? Thank you!

**Comment by ondaeduca** [comment]
Hi Mike,

I have checked the new functionality and it works great. 

 

It is happening to me in some cases, that the mouse disappears in the browser when it is over the SWF, and I think it has to do with the new function. I have not found the routine that generates the failure, but I am going to investigate it.

 

Great job Mike! Thank you!

 

Un saludo

 

Javier Yáñez

Director Técnico


ONDA EDUCA

 

 

De: Mike Welsh ***@***.***> 
Enviado el: miércoles, 16 de junio de 2021 22:18
Para: ruffle-rs/ruffle ***@***.***>
CC: Javier Yañez ***@***.***>; Author ***@***.***>
Asunto: Re: [ruffle-rs/ruffle] The drag and drop function not work (#3191)

 

Should be implemented in #4584 <https://github.com/ruffle-rs/ruffle/pull/4584> , can you please check and verify that this is fixed? Thank you!
