### ISSUE TITLE
import flash.display.BitmapData;    -  colorPicker not working

### ISSUE THREAD

**Issue by delta04** [ruffle-rs/ruffle#3193]
I have this colorPicker, that works well in flash, but unfortunately not in ruffle (yet).
It seems to be a problem with "the import flash.display.BitmapData;"

[ColorPicker.zip](https://github.com/ruffle-rs/ruffle/files/5961355/ColorPicker.zip)

**Comment by torokati44** [comment]
More specifically the problem seems to be the missing `BitmapData.draw()` function.

**Comment by delta04** [comment]
I wouldn't know how to solve that. I found another solution by changing the flash file. I added a little invisible button to each colour, and made it work without the BitmapData.draw(). 
It doesn't work like a proper colourPicker though, and thats a pity.

I don't know if the issue should be closed by this?

**Comment by n0samu** [comment]
BitmapData.Draw was implemented and this is working now.
