### ISSUE TITLE
Error on http://i.pcbeta.com/home.php?mod=spacecp&ac=avatar

### ISSUE THREAD

**Issue by qdpan** [ruffle-rs/ruffle#3195]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at <anonymous>:3:32330
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://i.pcbeta.com/home.php?mod=spacecp&ac=avatar

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-11
Channel: nightly
Built: 2021-02-11T00:18:16.959Z
Commit: 09c6def7f0df64f3868631be6b2c188c6b61ae75

**Comment by n0samu** [comment]
Looks like the browser had WebAssembly disabled?
