### ISSUE TITLE
Clicking Weapon Toggle buttons in UFA causes game to freeze.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#320]
During gameplay in UFA, if you click the weapon toggle buttons (as opposed to pressing the 'z' key to toggle), the game will freeze.

Link: https://www.newgrounds.com/portal/view/183575

**Comment by Herschel** [comment]
Seems to be fixed. Also fixed an issue with the buttons not toggling correctly in 881581e.
