### ISSUE TITLE
https://www.crazygames.com/game/swords-and-sandals-2

### ISSUE THREAD

**Issue by SecularSteve** [ruffle-rs/ruffle#3210]
**Describe the bug**
[unplayable]
All kinds of visual/audio bugs once you get past the character creator, and start playing the game. It can't get past the first battle because of a corruption problem.

**Expected behavior**
None of the above.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted (I think), it's a nightly build.

**What platform are you using?**
Windows 10, Mozilla Firefox, PC

**Comment by Sonikkustar** [comment]
Got it working on my end. I was able to make it past the first battle, though I'm unfamiliar with this game so I don't know what's to be expected here.

![image](https://user-images.githubusercontent.com/22226938/189457297-a323d80b-ea20-41e7-a594-bd6a5f2a82c0.png)

**Tested On**
ruffle-nightly-2022-09-09-windows-x86_64
Windows 10, PC

Also tried on the website via Google Chrome and it seemed to have worked as well.

**Comment by SecularSteve** [comment]
They finally fixed it to the point of being playable (I forgot I even made this issue at this point). Though a few visual glitches are still present. Like the transparency, blur and gradient issues.

But that's minor compared to the obvious progress made here after a Year and a half.

**Comment by n0samu** [comment]
Glad to hear the game is working now!
