### ISSUE TITLE
Error on https://e621.net/posts/1943336?q=dark_nek0gami

### ISSUE THREAD

**Issue by cejotin** [ruffle-rs/ruffle#3217]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32414
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1943336?q=dark_nek0gami

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-12
Channel: nightly
Built: 2021-02-12T00:17:25.708Z
Commit: da86f7fc5afbe93c8b378366c550a0622f59d5b6

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
