### ISSUE TITLE
Selfhosted not displaying in Edge

### ISSUE THREAD

**Issue by Tempy111** [ruffle-rs/ruffle#3231]
Hi, I've setup Ruffle for self hosting on my own website, and it's reported to work fine with everything I got their but while it's working in some browsers, it's not working in Edge. the Docs say the Ruffle will 'override' the default for running the flash plugin, but it always uses the flash plugin for me and not Ruffle.. When I tell Edge to disable flash, the files don't load at all.

I know this is a kinda minor issue in the long run, but I don't seam to see it as a noted issue.

**Comment by Poopooracoocoo** [comment]
If you're still able to toggle Flash in Edge, then perhaps you're still running the old, deprecated, UWP/EdgeHTML-based Edge?

**Comment by Tempy111** [comment]
Ah... I didn't think it was out of date since i regularly update but.. pretty much all browsers seam to be moving to a pretty annoying way so i couldn't seam to easily check.. installed new version and works fine ^_^

sorry for the bother but.. maybe a small note about this is needed?

**Comment by craniumcadoo** [comment]
Probably doesn't need a note since Microsoft will force uninstall legacy Edge on April 13th anyway: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge

**Comment by Poopooracoocoo** [comment]
And using the top sites will tell you that UWP Edge is out-of-date and unsupported. Google Search comes to mind.

**Comment by Tempy111** [comment]
for some resaon, it wasn't telling me, but all fine now
