### ISSUE TITLE
Error on http://www.juegosjuegos.com/embed/jennifer-romantic-library

### ISSUE THREAD

**Issue by Yamilet-Zetina** [ruffle-rs/ruffle#3232]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): unknown section code #0x87 @+18525
Error stack:
```
CompileError: WebAssembly.instantiate(): unknown section code #0x87 @+18525
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.juegosjuegos.com/embed/jennifer-romantic-library

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Poopooracoocoo** [comment]
Error on Juegos Juegos's side. Please report this to them
