### ISSUE TITLE
Shadow the hedgehog flash game does not function except for menu

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#3236]
the shadow the hedgehog flash game is not functining correctly there are annoying machine gun sounds that are constant the game does not start the menu of the game works perfectly but clicking to start the game does nothing

**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
the flash game in question is at this link
http://mariosonicgames.com/Games/ShadowHedgehog/ShadowHedgehog.htm
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

the game to start and function and shadow to be able to jump on platforms and use various  guns to kill the bad guys

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?** 
issue is with extension version 2021-02-12

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

i am using chrome os and google chrome
![shadow3](https://user-images.githubusercontent.com/64484245/107838700-a78f1600-6d6c-11eb-831a-f36fa197fc23.png)
![shadow 2](https://user-images.githubusercontent.com/64484245/107838706-b2e24180-6d6c-11eb-88ce-0d067f796fab.png)
![shadow](https://user-images.githubusercontent.com/64484245/107838883-bde9a180-6d6d-11eb-9396-ff5fe542c8e9.png)

**Comment by rufflue** [comment]
i updated ruffle to 2021-02-18 and now the game does not even pop up at all
![blank screen](https://user-images.githubusercontent.com/64484245/108390935-c5c69d00-71d6-11eb-856f-f62b287a1835.png)

**Comment by relrelb** [comment]
Seems to be working as of latest nightly.
