### ISSUE TITLE
Guns don't work in Alien Hominid using non-Newgrounds SWF (probably old)

### ISSUE THREAD

**Issue by Serentty** [ruffle-rs/ruffle#324]
Playing Alien Hominid in the version of Ruffle currently deployed to the demo on the website, neither the player's gun nor the enemies' guns work. I sometimes see projectiles which should have been launched by the player floating frozen in the air, but the enemies never seem to shoot at all.

**Comment by Herschel** [comment]
Is this in the web demo? What browser/OS?

**Comment by Serentty** [comment]
The web demo, on Firefox, on Windows 10.

**Comment by Herschel** [comment]
Hmm, it's working here on the same system. What version of Firefox? I'm on Firefox 72.0.1. Does it work in Ruffle on Newgrounds? (https://www.newgrounds.com/portal/view/59593/format/flash?emulate=flash)

**Comment by Serentty** [comment]
That's interesting. The version on Newgrounds works just fine. The SWF I have doesn't though, even though it works fine in the official Flash Player.

**Comment by Herschel** [comment]
Could you attach the SWF file? Are you using the web demo at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html and are sure it's not cached?

Thanks!

**Comment by Serentty** [comment]
I got it from [here](http://www.freetheflash.com/games/alien-hominid.php). I think it might be an older version of the game. Regardless, the fact that it works in Flash but not Ruffle seems indicative of some kind of bug.

**Comment by Herschel** [comment]
Ok, can repro the issue now on the SWF in question (http://www.freetheflash.com/games/source/33.swf). Thanks!

**Comment by Serentty** [comment]
I've renamed the issue to be more descriptive.

**Comment by Herschel** [comment]
Looks like this version is doing `GetVariable` with a dot-syntax path, so this is caused by #317.
