### ISSUE TITLE
Error on https://e621.net/posts/188434?q=wakfu+female%2Ffemale+animated

### ISSUE THREAD

**Issue by kotenok2000** [ruffle-rs/ruffle#3251]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32414
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/188434?q=wakfu+female%2Ffemale+animated

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
