### ISSUE TITLE
GE.NE.SIS Game Intro - parsing errors and little part of visuals are wrong

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#3253]
Chrome 88.0.4324.150
Nightly 2021-02-14

http://eye.swfchan.com/flash.asp?id=60656&n=GE.NE.SIS.+-+Game+Intro.swf

When loading, the parsing errors appear:

![image](https://user-images.githubusercontent.com/75184268/107889371-21690000-6f23-11eb-9ee8-26e4effee54b.png)

When entering the part of the flash where some visual problems happen, those are logged in the console:

![image](https://user-images.githubusercontent.com/75184268/107889420-7ad12f00-6f23-11eb-92ec-12e3895f835b.png)

The visual problems (happen in the middle of ~2min clip):

Adobe:
![GE NE SIS_Adobe](https://user-images.githubusercontent.com/75184268/107889540-5f1a5880-6f24-11eb-8258-e67fa3c42fcf.gif)

Ruffle:
![GE NE SIS_Ruffle](https://user-images.githubusercontent.com/75184268/107889542-62addf80-6f24-11eb-9180-eff0c3096c51.gif)

**Comment by Diatonator** [comment]
The issue seems fixed in Nightly 2021-12-30 - closing.

**Comment by relrelb** [comment]
Likely fixed by #5804.
