### ISSUE TITLE
Multi-asset games don't work

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [ruffle-rs/ruffle#3254]
So I was playing _Mission in Snowdriftland_ (hosted on snowdriftland.live) using the latest version of Ruffle. The only problem is that this is a multi-asset game and therefore, wouldn't work.

I was expecting the assets to load.

I used the Ruffle extension.

I used Windows 10 x64, using the Chromium-based version of Microsoft Edge.
<img src="https://i.imgur.com/gDojr0X.png">

**Comment by EmperorBale** [comment]
Could you share a link to the website with that flash content, or the SWF? Thanks

**Comment by EmperorBale** [comment]
Looks like its checking if the SWF is loaded using methods that require SWF steaming to be implemented (like getBytesLoaded, etc) which has not been implemented yet. See #18 for more info

**Comment by Lord-McSweeney** [comment]
The original site is down; the SWF can now be found at https://web.archive.org/web/20201229213851/https://snowdriftland.live/misnowdriftland_final.swf

**Comment by n0samu** [comment]
Mission in Snowdriftland works fine in Ruffle now!
