### ISSUE TITLE
Black square appearing in SWFs using MX components

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#326]
A black square appears in SWFs using Flash MX components. For example, in Marvin Spectrum (https://www.newgrounds.com/portal/view/270585):

![image](https://user-images.githubusercontent.com/36278/72511112-6a6df280-37ff-11ea-85fb-48c530b03a43.png)

This appears to be created by the `FocusManager` class as part of handling tabs. Seems like we support enough AS for it to halfway-initialize itself, but not enough for it to clean up this dummy button.

**Comment by Dinnerbone** [comment]
I think we can consider this resolved. The square is gone, and MX elements are on their way to being functional. There's individual issues blocking them from working (such as text rendering), but no general "MX as a whole is broken" anymore.
