### ISSUE TITLE
ByteArray

### ISSUE THREAD

**Issue by Zaseth** [ruffle-rs/ruffle#327]
Hi. This is probably far from being worked on, but I wrote a fully complete ByteArray implementation with AMF0/AMF3. It's in Javascript though, but should be easy to be done in Rust. Hoping it's useful.

https://github.com/Zaseth/bytearray-node

**Comment by Herschel** [comment]
Thanks! This could be helpful when we get there.

**Comment by Zaseth** [comment]
A note: I'm currently working on an AMF3 implementation in Typescript aiming to also support Node and the browser without any dependencies. I already did this for AMF0. I hope these come to help on this project.

https://github.com/Zaseth/AMF0-TS
https://github.com/Zaseth/AMF3-TS
