### ISSUE TITLE
RISK WORLD CONQUEST - Black screen, assets are loaded

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3274]
**Describe the bug**

Hello! I tried to run a Flash version of the RISK: WORLD CONQUEST game:

https://juegospot.com/gamez/risk-world-conquest/

The SWF loads fine, then launches and loads other assets: splash screen JPG, and a bunch of game assets through "data:" requests. The problem is that none of these items is visible - the screen stays black all the time. Please see  screen recording from Chrome on YT: 

https://youtu.be/44kvDTwfZas

where I try to load the game and you can see the 'Network' and 'Console' tabs and open some of the "data:" assets in new tabs. As you can see, there are no JS errors and all resources are loaded properly by the browser.

**Expected behavior**
The game assets should be visible on the screen and game should be playable, of course :)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
The problem affects all Ruffle versions

**What platform are you using?**
Web version, Firefox 85, Chrome 85-88, Mac Os X and Windows 10

**Comment by Toad06** [comment]
Thanks for the report. I'm closing it in favor of #4549 as this is the same issue.

**Comment by perelowski** [comment]
Hello. Thanks for refreshing this bug report. I may add that after the first "Play", the console logs the following error, three times:

Tried to instantiate non-registered character preloader:
Tried to instantiate non-registered character preloader ruffle_web-wasm_extensions.js:1294:16
    __wbg_error_cc38ce2b4b661e1d ruffle_web-wasm_extensions.js:1294
    hbe56dd46e4162966 8136578cccbaf4758176.wasm:5137718
    <console_log::WebConsoleLogger as log::Log>::log::h4f7db98edde3d308 8136578cccbaf4758176.wasm:4782913
    hbdcd9a8863c89007 8136578cccbaf4758176.wasm:4840811
    h6fdc91e934e3b500 8136578cccbaf4758176.wasm:2635968
    h3bb94337442bafb9 8136578cccbaf4758176.wasm:1323217
    <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h74544ea9563647a7 8136578cccbaf4758176.wasm:1701493
    h07f2242128234aad 8136578cccbaf4758176.wasm:296750
    h22c8af94557c5815 8136578cccbaf4758176.wasm:4635895
    h3bb94337442bafb9 8136578cccbaf4758176.wasm:1328125
    <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h74544ea9563647a7 8136578cccbaf4758176.wasm:1699615
    h07f2242128234aad 8136578cccbaf4758176.wasm:296750
    h22c8af94557c5815 8136578cccbaf4758176.wasm:4635895
    h3bb94337442bafb9 8136578cccbaf4758176.wasm:1328125
    <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h74544ea9563647a7 8136578cccbaf4758176.wasm:1699615
    h07f2242128234aad 8136578cccbaf4758176.wasm:296750
    h22c8af94557c5815 8136578cccbaf4758176.wasm:4635895
    h3bb94337442bafb9 8136578cccbaf4758176.wasm:1328125
    <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::construct::h3b2382ba64b8335a 8136578cccbaf4758176.wasm:4141866
    h07f2242128234aad 8136578cccbaf4758176.wasm:254064
    h22c8af94557c5815 8136578cccbaf4758176.wasm:4635895
    h3bb94337442bafb9 8136578cccbaf4758176.wasm:1328125
    <ruffle_core::avm1::object::Object as ruffle_core::avm1::object::TObject>::call_method::h74544ea9563647a7 8136578cccbaf4758176.wasm:1705660
    h07f2242128234aad 8136578cccbaf4758176.wasm:296750
    h22c8af94557c5815 8136578cccbaf4758176.wasm:4635895
    h3672d0baa6296ff5 8136578cccbaf4758176.wasm:3254592
    h64e0ea011a76d899 8136578cccbaf4758176.wasm:1815027
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2218234
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
    k ruffle_web-wasm_extensions.js:240
    c ruffle_web-wasm_extensions.js:201
    (Async: FrameRequestCallback)
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:782
    I ruffle_web-wasm_extensions.js:265
    __wbg_requestAnimationFrame_71638ca922068239 ruffle_web-wasm_extensions.js:781
    hf8a4913ed3d1fe2b 8136578cccbaf4758176.wasm:2211162
    h66b090fd1f9bd1c2 8136578cccbaf4758176.wasm:5136767
    <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb36bbfafe0278747 8136578cccbaf4758176.wasm:5092950
