### ISSUE TITLE
Error on http://gamezone.2001jeux.fr/play-03868-l-robot-unicorn-attack-heavy-metal.html

### ISSUE THREAD

**Issue by JCV2b** [ruffle-rs/ruffle#3278]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): unexpected end of stream @+5596211
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+5596211
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://gamezone.2001jeux.fr/play-03868-l-robot-unicorn-attack-heavy-metal.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-14
Channel: nightly
Built: 2021-02-14T00:19:03.523Z
Commit: ecd873eb39c141f9bf2e41454c7a47d5f7e9507c

**Comment by n0samu** [comment]
Looks like the website had uploaded Ruffle's WASM file incorrectly.
