### ISSUE TITLE
Error on https://evilgames.eu/flashgames/deadly-venom.htm

### ISSUE THREAD

**Issue by Netherbrine5902** [ruffle-rs/ruffle#3282]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32414
    at r (<anonymous>:3:32904)
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: ../swf/deadly-venom.swf
Param wmode: direct
Param quality: high
Param allowNetworking: internal
Param AllowScriptAccess: never
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://evilgames.eu/flashgames/deadly-venom.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-16
Channel: nightly
Built: 2021-02-16T00:17:10.309Z
Commit: 85069f6ccf3fbbe88de6d40094aa9e9dba616e2a

**Comment by Poopooracoocoo** [comment]
#2201
