### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by Tagadacouincoin** [ruffle-rs/ruffle#3283]
Hello,

A bug ? 

There is missing character on this swf : The character is " - "  

In the screenshot it must be 10 **-** 3  ...

[https://lesmathematiquescpasautomatique.fr/wp-content/wp-mep/6eme/pages/numerique/chap2/serie1/exo4/exo4.htm](url)

The swf is here : [https://lesmathematiquescpasautomatique.fr/wp-content/wp-mep/6eme/pages/numerique/chap2/serie1/exo4/N2s1ex4.swf](url)

![image](https://user-images.githubusercontent.com/77745264/108066881-44e59500-7060-11eb-8b7f-21f74220e1eb.png)

Testing on self-hosted version and on demo-mode.

Thanks to all

**Comment by ousia** [comment]
@Tagadacouincoin,

many thanks for reporting the issue.

The direct link to the SWF file reads https://lesmathematiquescpasautomatique.fr/wp-content/wp-mep/6eme/pages/numerique/chap2/serie1/exo4/N2s1ex4.swf.

I think this is a duplicate of issue #1862.

**Comment by ousia** [comment]
It seems that _Tahoma_ is embedded in the SWF file and the character looks like proper minus sign (`−`, U+2212).

The font has the character `−` but it has been removed when embedding in the SWF file.

From the AS code:

``` js
moins = unescape("%E2%88%92");
```

Once the issue #1862 is implemented, this issue will be fixed.

**Comment by ousia** [comment]
@Tagadacouincoin,

if you allow me a suggestion, I’d close this issue and subscribe to #1862.

Many thanks for your report.

**Comment by Tagadacouincoin** [comment]
No problem ! Thank you !

**Comment by Tagadacouincoin** [comment]
No problem i close ! Thank you !
