### ISSUE TITLE
Re-enable touch-action

### ISSUE THREAD

**Issue by SoftCreatR** [ruffle-rs/ruffle#3285]
In #1039, `touch-action` has been set to `none`. While this results in the expected behavior, it also results in a side effect, because it prevents swiping on mobile devices.

So if you tap on the shadow-root and swipe up or down, it doesn't work. Tested on Android 10 (Chrome 88) as well as on Windows 10 (Chrome 88, using the developer tools).

EDIT:

I ended up setting `player.style.touchAction = "initial";`

**Comment by EmperorBale** [comment]
Did setting it to initial fix the issue? If so, maybe you should open a PR

**Comment by SoftCreatR** [comment]
Partially. The canvas within the ruffle element has this property set, too. This leads to the same problem, but just while the file is playing. Furthermore I'm not sure, if reverting this change may cause some unwanted behavior under certain circumstances. That's why I chose to manually "fix" it for me and my Usecase.

**Comment by desertking** [comment]
Preventing swiping on the "player" itself is a must. Otherwise you swipe all the time when interacting with the game which is not what it should do ofc. Every HTML5 game does the same for that reason.

**Comment by SoftCreatR** [comment]
Good point.
