### ISSUE TITLE
Erro em https://www.clickjogos.com.br/Jogos-online/Meninas/Beauty-Resort

### ISSUE THREAD

**Issue by aclaratx** [ruffle-rs/ruffle#3287]
Nightly 2021-02-16 Extensão do Navegador 

Não funcionou, deu erro.

**Comment by Poopooracoocoo** [comment]
#1368

**Comment by Poopooracoocoo** [comment]
Ruffle does not yet support ActionScript 3 content. View #1368 for more information.
