### ISSUE TITLE
web: Milk Quest - Grey Screen on Intro starting

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#3297]
The game stays grey after the intro starts loading until the intro is finished

https://www.newgrounds.com/portal/view/565830?emulate=flash

ruffle-object.js:107 Tried to instantiate non-registered character ID 53
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:107

**Comment by relrelb** [comment]
The intro uses VP6 video codec, which is currently unimplemented: #723.

**Comment by torokati44** [comment]
Now that https://github.com/ruffle-rs/ruffle/pull/5369 is merged, the intro video plays back fine.
