### ISSUE TITLE
Image stretched incorrectly on z0r.de/630 (texture larger than vulkan/webgl limit)

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#3299]
On Linux desktop (Vulkan backend) Ruffle shows this really stretched image for [z0r.de/630](https://z0r.de/L/z0r-de_630.swf):

![image](https://user-images.githubusercontent.com/288816/108217327-c0644680-7133-11eb-9a14-ed72ed48c5b9.png)

In the web version (like on the demo page), it's just solid black, with the following message in the console:
`WebGL warning: texImage: Requested size at this level is unsupported.`
This might be just about the size of the texture (image) itself, in pixels, and not the transformation (pan/stretch?) applied to it.

I haven't tested the canvas backend.

**Expected behavior**

Flash Player shows this in the very beginning, then scrolls it up for a long time:

![image](https://user-images.githubusercontent.com/288816/108216674-05d44400-7133-11eb-93b8-c1aaece70b20.png)

**Comment by torokati44** [comment]
A completely wild guess, but this might also be related: https://z0r.de/6812
The video is in only one quadrant, as opposed to filling the entire player area.

**Comment by torokati44** [comment]
New development:
In `WgpuRenderBackend::register_bitmap`, the RGBA data in the :cow: is correct before it is uploaded into the texture.
However, RenderDoc shows that at runtime, the captured texture itself is stretched.
It is the correct size (300x17700), and it is drawn with all the correct transforms. Only the image data itself is stretched. Only vertically, by a factor of around 13.5.

So this:

![image](https://user-images.githubusercontent.com/288816/108282895-ae5dc480-7182-11eb-9ccf-fee065a04baf.png)

Becomes (approximately) this:

![image](https://user-images.githubusercontent.com/288816/108282850-95551380-7182-11eb-963e-bd924cd8f923.png)

As a result, the texture only contains the top ~7.5% of the image content.

All of this is with **RADV**.
Whan switching to **Lavapipe**, the loop is displayed **correctly**.

This looks like a `wgpu-rs` bug?

**Comment by torokati44** [comment]
Or worse, a RADV bug... :/
I had hoped that https://github.com/ruffle-rs/ruffle/pull/3066 would fix this, but just checked, and no.

**Comment by torokati44** [comment]
Oh, I think I got it...

According to `vulkaninfo`, both RADV and Lavapipe report the `maxImageDimension2D` device limit to be `16384`.

And 17700 silently wraps around to 17700 % 16384 = 1316, which in turn is ~7.43% of 17700.
With Lavapipe, it just "accidentally" works, even though the reported image is exceeded.

How come none of the potential validation layers, nor wgpu catches this?

**Comment by ubitux** [comment]
The issue appears to be present in 7765 and 7766:
- https://z0r.de/L/z0r-de_7765.swf 
- https://z0r.de/L/z0r-de_7766.swf

These fail with `Dimension 10000 value 10000 exceeds the limit of 8192`, same issue as 630 (with different values).

Those are regressions, there were not present before.

**Comment by torokati44** [comment]
The regression might be because `wgpu-rs` seems to always use 8192 as an image dimension limit, even if the device has a larger limit, say, 16384.
So, in this case, for any size between those values, there will be a regression.
While z0r.de/630 exceeds both of these limits, the other two linked loops don't.

**Comment by Lord-McSweeney** [comment]
Fixed by #10908.
