### ISSUE TITLE
Animations are now huge with February 18th nightly release - found on http://www.dnai.org/

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#3305]
**Describe the bug**
The animation was normally sized, but now all the SWFs are giant. I downloaded the Nightly extension and Firefox releases from https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-02-18 the moment I saw them, before they were listed on https://ruffle.rs/, to test them since I had previously found an issue with the video branch, which I knew was being merged today, so I wanted to see if that issue had been fixed, and instead found a new issue I did not expect.

**Expected behavior**
Normal size (compare to February 16th release)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Browser extension

**What platform are you using?**
Windows, Google Chrome and Firefox

**Comment by bls1999** [comment]
This exact bug is happening on most pages on https://jiggmin2.com as well.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, nightly 2021-02-18.

**What platform are you using?**
Desktop -- Brave Browser, Mac OS X Mojave.

**Comment by bls1999** [comment]
Looked closer. I think it has to do with this: https://github.com/ruffle-rs/ruffle/commit/1c21856980872bf9714ae0e5f346cd0ff18d60d8#diff-a1efba9c610ac8ebb664f99add91ffe414cd4f6793c0cbc11d834366f073a720R44

**Comment by danielhjacobs** [comment]
Considering that this does seem like a CSS issue, that seems likely. I've never been good at CSS myself though. Tagging @relrelb.

**Comment by relrelb** [comment]
Oops, totally my bad. Will look at this throughout the day.

**Comment by relrelb** [comment]
@Herschel Can you please revert #3239 since I probably wouldn't have time of this by the end of the day?

**Comment by perelowski** [comment]
All of Flash gaming pages are broken with the Chrome extension 2021-02-18 release (the emulator doesn't respect CSS div/object size).

**Comment by relrelb** [comment]
This should be fixed now as a new release is available.

**Comment by bls1999** [comment]
> This should be fixed now as a new release is available.

Seems to be good! Thanks @relrelb!
