### ISSUE TITLE
polyfill issues on http://www.dan-dare.org/

### ISSUE THREAD

**Issue by rufflue** [ruffle-rs/ruffle#3318]
**Describe the bug** 
there are polyfill issues on [http://www.dan-dare.org/](url) i used ultimate flash sonic the control factor as its been documented to be compatible with ruffle 
![sonic space ](https://user-images.githubusercontent.com/64484245/108393262-15a66380-71d9-11eb-867e-50518fd6335b.png) the game should be polyfilled in this area instead the game is popped up above
![sonicpolyfill](https://user-images.githubusercontent.com/64484245/108393645-7766cd80-71d9-11eb-90e2-fc0dcb0825ca.png)
![sonicpolyfill2](https://user-images.githubusercontent.com/64484245/108393663-7b92eb00-71d9-11eb-8fdd-98ee64bb335f.png)

Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
[http://www.dan-dare.org/Dan%20Sonic/Dan%20Sonic%20Hi.htm](url)

you should be able to see the polyfill issues on the link above
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

the game should be poly-filled in between the how to play and the game tiles

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
ruffle extension 2021-02-18

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).
 - ChromeOS Google chrome

**Comment by relrelb** [comment]
Duplicate of #3305?

**Comment by rufflue** [comment]
well thank you the issue has been fixed on poly-fill
