### ISSUE TITLE
[ruffle-selfhosted] Add event(s) to receive player status

### ISSUE THREAD

**Issue by SoftCreatR** [ruffle-rs/ruffle#3324]
I know, that there's `lastActivePlayingState`, but it's somewhat unreliable (and not meant to be used) in order to check if an instance is currently playing or paused. Thus, I would like to request a publicity available function that returns, if a given instance is currently playing, or paused.

Thank you.

**Comment by relrelb** [comment]
This will be possible with the upcoming nightly of March 1st, using the `isPlaying` property of `RufflePlayer`.
