### ISSUE TITLE
Error on https://e621.net/posts/297226?q=purplemantis

### ISSUE THREAD

**Issue by darthrenatus** [ruffle-rs/ruffle#3331]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/297226?q=purplemantis

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-23
Channel: nightly
Built: 2021-01-23T01:07:06.024Z
Commit: 0cf3a4abedae45a31db9764f74026dcab48cd05e

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
