### ISSUE TITLE
A regular video SWF just shows as white and only audio

### ISSUE THREAD

**Issue by obscurerev** [ruffle-rs/ruffle#3334]
This is only about 5.8 mb or something and it won't display any video, just audio. This also happens to any swf video file I put in the web demo.
[https://www.dropbox.com/s/f1sfhp57q90qv2a/The%20Bad%20Dream%20-%20Creepypasta.swf?dl=0](url)

**Comment by danielhjacobs** [comment]
None of the video codecs are supported yet: #723.

H.263 will be supported by #2173 once it gets merged
VP6 will be supported by #3004 once it gets merged.

Both of those are not ready to be released yet.
