### ISSUE TITLE
Error on https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=4093

### ISSUE THREAD

**Issue by Mau-99** [ruffle-rs/ruffle#3335]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm1/object/stage_object.rs:92:14

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=4093
SWF URL: https://www.forum-thueringen.de/games/AlienAbductorEVH.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-19
Channel: nightly
Built: 2021-02-19T00:17:04.316Z
Commit: 75fca8f6b6ae38303de294051bd560b20c183258

**Comment by relrelb** [comment]
Fixed by #3322.
