### ISSUE TITLE
Error on https://ruffle.rs/demo/ when playing Desktop tower defense

### ISSUE THREAD

**Issue by DependentAppearance0** [ruffle-rs/ruffle#3348]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/movie_clip.rs:956:10

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/
SWF URL: https://ruffle.rs/demo/swfs/synj1.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-20
Channel: nightly
Built: 2021-02-20T00:17:48.025Z
Commit: ff1aff607af793851e8d2bea5d9b6e1f210972a7

# Other Info
I used [this](https://we.tl/t-t3FL9TOdmx) swf file and the game crashes any time I click any of the difficulty selectors. It also appears that this game has been broken fairly recently as I do recall this game working in ruffle a few weeks ago.

**Comment by Herschel** [comment]
The SWF file is no longer available, but I assume fixed by #3454.
