### ISSUE TITLE
Error on https://e621.net/posts/1310285?q=fav%3ALuio_The_Lucario+flash

### ISSUE THREAD

**Issue by LuioTheLucario** [ruffle-rs/ruffle#3349]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/1310285?q=fav%3ALuio_The_Lucario+flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4424.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-20
Channel: nightly
Built: 2021-02-20T00:17:48.025Z
Commit: ff1aff607af793851e8d2bea5d9b6e1f210972a7

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
