### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php?i=13

### ISSUE THREAD

**Issue by 123456lljsh** [ruffle-rs/ruffle#3350]
#错误信息nError名称：TypeError nError消息：无法下载wasm模块nError堆栈：n`nTypeError：无法下载wasm模块n`n#Player信息nAllow脚本访问：True nPlayer类型：Object nSWF URL：Games/13.swf nParam电影：Games/13.swf nParam质量：High nParam Play：true nParam循环：true nParam循环：Window nParam缩放：showall nParamFullScreen：true nParam/fl.porno-apk.com/game.php？i=13 n#Browser Info nUseragent：Mozilla/5.0(Linux；安卓10；zh-cn；Hlk-AL00 Build/HONORHLK-AL00)AppleWebKit/537.36(KHTML，类似壁虎)版本/4.0 Chrome/77.0.3865.120 MQQBrowser/11.2 Mobile Safari/537.36 COVC/045518

**Comment by Poopooracoocoo** [comment]
Can you reproduce the crash on the latest version of Chrome or Firefox for Android? QQ Browser is based on an older version of Chromium that may not support WebAssembly fully. You may not have the Play Store in China, but you can easily sideload them from a website :)
