### ISSUE TITLE
Error on https://hunterstoryt.webs.com/game.htm

### ISSUE THREAD

**Issue by ForgottenAngel** [ruffle-rs/ruffle#3355]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hunterstoryt.webs.com/game.htm

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-20
Channel: nightly
Built: 2021-02-20T00:17:48.025Z
Commit: ff1aff607af793851e8d2bea5d9b6e1f210972a7

**Comment by Poopooracoocoo** [comment]
Hi @ForgottenAngel! Please view #2201 for more information on this error.

**Comment by rufflue** [comment]
i was able to acces the game with ruffle extension version 2021-02-21
i have no idea why i am able to access it but you are not

**Comment by Poopooracoocoo** [comment]
@rufflue i was probably wrong then. i'm not a ruffle developer. i just saw the error message and drew that conclusion

**Comment by n0samu** [comment]
Closing because the website no longer exists
