### ISSUE TITLE
web: Crash screen text align is broken in recent builds.

### ISSUE THREAD

**Issue by jooy0224** [ruffle-rs/ruffle#3356]
**Describe the bug**
![img_0001](https://user-images.githubusercontent.com/75052171/108613542-5f3fba00-7436-11eb-92da-90dbf5895cc6.png)
In recent Ruffle, some styles of the crash screen are broken.
The title and footer widths are not 100%, so it seems that they are not aligned in the middle. (It is described in the attached image.)

**Expected behavior**
The title, content, and footer text should all be centered.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted Version (Web)

**What platform are you using?**
Windows 10 x64, Google Chrome, Ruffle Nightly 2021-02-21

**Comment by relrelb** [comment]
Probably caused by #3332.
