### ISSUE TITLE
web: AS3 warning message background and button style are broken in recent builds

### ISSUE THREAD

**Issue by jooy0224** [ruffle-rs/ruffle#3358]
**Describe the bug**
![issue-as3](https://user-images.githubusercontent.com/75052171/108616235-f7e23400-744e-11eb-9358-a1b05df25dcb.png)

The background of the AS3 warning message has disappeared in recent builds. As a result of this, the game screen appears behind the text as shown in the attached image, or the warning message is not clearly visible if the background is white.

**Expected behavior**
The blue background of the AS3 warning message should appear.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
I'm using Self-hosted Version (Web)

**What platform are you using?**
Windows 10 x64, Google Chrome, Ruffle Nightly 2021-02-21

**Comment by relrelb** [comment]
Probably caused by #3332.

**Comment by bls1999** [comment]
Yep, this is happening on my site https://jiggmin2.com as well.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted version, nightly 2021-02-21.

**What platform are you using?**
Desktop -- Brave Browser, Mac OS X Mojave.

**Comment by bls1999** [comment]
https://github.com/ruffle-rs/ruffle/pull/3332/files#diff-a1efba9c610ac8ebb664f99add91ffe414cd4f6793c0cbc11d834366f073a720R8

The only problem is that the `:root` variables aren't taking effect. Probably some sort of scope issue -- should be an easy fix. @relrelb
