### ISSUE TITLE
[suggestion] Opus as sound file format?

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#336]
@Herschel,

this rambling is loosely related to #10.

Speex was introduced in SWF 10/11 (https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf#page=194) and the codec itself is obsolete and superseded by Opus.

Just a crazy though, how about implementing Opus in SWF? Or even crazier, how about proposing Adobe to implement Opus in SWF without ignoring rates and channels? (Audio format number could read `12`.)

Well, I think this would be the best feature to implement in Flash before deprecating it forever.

Many thanks for your help.

**Comment by Herschel** [comment]
It's possible to add custom tags and formats to an SWF (In fact, some other technologies that use SWF such as Scaleform and Iggy do this to bake in assets in their desired format).

However, I don't think this is within the scope of our project. The goal of Ruffle is archival and accessibility of existing content, not for extending the format. Changes to the SWF format require us to write custom tooling to generate these SWFs and would create incompatibilities with the official Flash Player. And there's more than enough work already! :-)

Instead, I'd prefer features that don't modify the original format, but can be helpful even for legacy content. This could include features such as: writing audio to disk, volume/equalizer controls, even swapping sounds out for other sounds based on a user config when an SWF loads.

Thank you for the feedback!
