### ISSUE TITLE
Ruffle Error on http://www.115xyx.cn/swf.htm?gamepath=/uploads/flash/20111208/231334.swf&gamevar=&gamemark=1|0|0|0|0|0|0|0|0|0&method=%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cli%3E%3Cspan%20class=%22i_mouseleft%22%3Emouseleft%3C/span%3E%E4%BD%BF%E7%94%A8%E9%BC%A0%E6%A0%87%E6%93%8D%E4%BD%9C%E3%80%82%3C/li%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/ul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20

### ISSUE THREAD

**Issue by LeonardHalf** [ruffle-rs/ruffle#3364]
# Error Info
Error name: Error
Error message: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object.<anonymous> (chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/core.ruffle.js:1:32071)
    at Object.<anonymous> (chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/core.ruffle.js:1:19555)
    at __wbg_drawImage_801ad094f4734689 (<anonymous>:3:59626)
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4135]:0x3397a8
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[989]:0x209512
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1157]:0x232951
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3198]:0x317633
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[2979]:0x30b362
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1157]:0x23285f
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3198]:0x317633)', render/canvas/src/lib.rs:740:14
Error stack:
```
Error: panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object.<anonymous> (chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/core.ruffle.js:1:32071)
    at Object.<anonymous> (chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/core.ruffle.js:1:19555)
    at __wbg_drawImage_801ad094f4734689 (<anonymous>:3:59626)
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4135]:0x3397a8
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[989]:0x209512
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1157]:0x232951
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3198]:0x317633
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[2979]:0x30b362
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1157]:0x23285f
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3198]:0x317633)', render/canvas/src/lib.rs:740:14
    at Object.z (chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/core.ruffle.js:1:20865)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:37606)
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1324]:0x254c8e
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[1491]:0x272a47
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4066]:0x338300
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[3161]:0x315621
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4375]:0x33d2f1
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4405]:0x33d854
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4277]:0x33be08
    at chrome-extension://bbaplclbegekdgbdbklnchepjlcmicka/dist/0e37dcbc9e0877161fee.module.wasm:wasm-function[4406]:0x33d88a
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.115xyx.cn/swf.htm?gamepath=/uploads/flash/20111208/231334.swf&gamevar=&gamemark=1|0|0|0|0|0|0|0|0|0&method=%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cli%3E%3Cspan%20class=%22i_mouseleft%22%3Emouseleft%3C/span%3E%E4%BD%BF%E7%94%A8%E9%BC%A0%E6%A0%87%E6%93%8D%E4%BD%9C%E3%80%82%3C/li%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C/ul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20
SWF URL: http://www.115xyx.cn/uploads/flash/20111208/231334.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

PS: I just click the report bug button and I know nothing about the content.

**Comment by Poopooracoocoo** [comment]
are you using the extension?

**Comment by Poopooracoocoo** [comment]
please update your version of the extension.

**Comment by relrelb** [comment]
Fixed by #7026.
