### ISSUE TITLE
Interactive Buddy won't Interact

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#338]
https://www.newgrounds.com/portal/view/218014

Interactive Buddy is on the screen and makes comments but you can't actually drag them around.

**Comment by Dinnerbone** [comment]
Lots of unimplemented stuff here, but I think that things are failing during initialization based on how much stack underflows are happening in the first frame.

Based on log output I'd hazard a guess that we need quite a few methods from #275 (`charAt`, `toUpperCase`, `substr`) and `registerClass` from #268 before we see any progress here

**Comment by Dinnerbone** [comment]
This has now progressed to the point where he *sometimes* interacts. Not sure why it's inconsistent.

**Comment by Toad06** [comment]
For me, interaction has worked the first time I've tried the game (in Firefox and Chrome). Then nothing.

However, it always works when I run the game in a new private tab (only the first time, interaction will no longer work if I refresh the page - opening a new private tab again will be required).

Disabling the cache in the browser's console seems to do nothing.

**Comment by Herschel** [comment]
Interactive Buddy seems to work correctly now with recent SharedObject fixes (#2063). Very close to playable, but the MX menubars aren't fully functioning yet (they display, but are unable to be clicked).

**Comment by adrian17** [comment]
The entire UI seems to be working with https://github.com/ruffle-rs/ruffle/pull/3917 , minor graphical issues aside.

**Comment by parkerlreed** [comment]
I am getting no interaction again on current desktop (web seems to work fine)

![Image](https://github.com/user-attachments/assets/f3bbe5cd-ec48-4eb5-852b-27717eaab3c4)

Arch Linux, Plasma Wayland

**Comment by parkerlreed** [comment]
I have narrowed this down to only occurring if Flashpoint Launcher is the one loading this game in ruffle. ruffle loading by itself works fine.

Other games in Flashpoint + ruffle work fine with mouse though which is weird.

**Comment by billbeans** [comment]
This game doesn't work at all for me and I just compiled ruffle_desktop from source on Debian Linux. The buddy gravitates toward my mouse occasionally, but none of the drop down menu options work. The terminal output says "Cannot enumerate undefined" whenever I try selecting them.

**Comment by parkerlreed** [comment]
@billbeans This is being tracked separately https://github.com/ruffle-rs/ruffle/issues/23174

The default tool is just weak gravity which is why you see the behavior with the buddy,
