### ISSUE TITLE
unstoppable beeping noise in Portal: Flash Version

### ISSUE THREAD

**Issue by labbo-lab** [ruffle-rs/ruffle#3384]
`Game: Portal: Flash Version` ([online](https://the-flash-library.labbolab.repl.co/portal.html)) ([sfw](https://the-flash-library.labbolab.repl.co/portal.swf))
(happens on all versions of ruffle that i know of)

when you start a New Game, the alarm clock beeping noise doesnt stop beeping, and the only way to turn it off is to mute sound
(sorry if i missed something, if you need any more info, just ask and i would be happy to provide it)

**Comment by relrelb** [comment]
This should be fixed now. Can you please confirm?

**Comment by jhwgh1968** [comment]
I didn't hear the specific beeping noise referred to, but all sound seems to work fine with nightly version 1c249200.
