### ISSUE TITLE
sonic plus mega collection mini platforms not showing up using vershion 2021-02-21

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#3387]
the platforms do not show up and neither does the character sonic the hedgehog

**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
http://mariosonicgames.com/Games/SonicHedgehog/SonicHedgehog.htm
If this is a visual issue, please attach a screenshot of the problem.
![sega block](https://user-images.githubusercontent.com/64484245/108749440-700b3100-7505-11eb-84af-a2fabe693547.png)

**Expected behavior**
for the platforms to show up

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
extension vershion 2021-02-21
**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

ChromeOS Google Chrome

**Comment by relrelb** [comment]
Seems to be working as of latest nightly.
