### ISSUE TITLE
"Visible" option in Flash Pro properties tab is ignored

### ISSUE THREAD

**Issue by KupoGames** [ruffle-rs/ruffle#3403]
I found a minor problem. Ruffle seems to ignore the "visible" option in the Flash Pro MovieClips properties tab. MovieClips with this turned off still appear in Ruffle, and they do not appear in Flashplayer. Probably quite a rarely used feature though.

See attached swf and fla files:
[test invisible.zip](https://github.com/ruffle-rs/ruffle/files/6031744/test.invisible.zip)

**Comment by sombraguerrero** [comment]
When decompiled in JPEXS, the property is exposed as an integer as opposed to a Boolean. I would make the conjecture that this is what causes Ruffle to not respect it.
