### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/pacman.html

### ISSUE THREAD

**Issue by nenuco66** [ruffle-rs/ruffle#3404]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/pacman.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment]
This is an issue on Juegos Area. Could you please contact the website informing them this? Tell them to also update their version of Ruffle.

**Comment by Toad06** [comment]
Thanks for the report. As mentioned above, this is an issue on Juegos Area's side, as the .wasm file cannot be found. It's up to the website's administrator to fix that.
