### ISSUE TITLE
Error on https://flash.porno-apk.com/game.php?i=18

### ISSUE THREAD

**Issue by lbwnb438** [ruffle-rs/ruffle#3406]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/18.swf
Param movie: game/18.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://flash.porno-apk.com/game.php?i=18

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; JSC-AN00; HMSCore 5.1.1.303) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 HuaweiBrowser/11.0.7.302 Mobile Safari/537.36
OS: Linux armv8l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by jhwgh1968** [comment]
Downloading it manually, it runs fine with nightly 1c249200. I believe this is a web site issue, and not a bug in Ruffle.
