### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/miragine-war.html

### ISSUE THREAD

**Issue by carlosjavi1986** [ruffle-rs/ruffle#3410]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/miragine-war.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by carlosjavi1986** [comment]
quiero jugar

**Comment by Poopooracoocoo** [comment]
@carlosjavi1986 Please contact the website informing them of this. It's something they need to fix on their side.
