### ISSUE TITLE
Trouble with dragging & dropping elements

### ISSUE THREAD

**Issue by ambicerebral** [ruffle-rs/ruffle#3411]
Hi! I'm brand new to Github and Ruffle, please let me know any information I left out that might be useful.

I've been trying several flash games I enjoyed as a kid and have noticed that whenever a game requires me to drag something and drop it onto a specific area, I can't do it. I can click on the object and drag it, but when I go to drop it in the specific area it needs to go, it doesn't end up there.

**Comment by Poopooracoocoo** [comment]
I think it's because onDragOut() and onDragOver() aren't supported yet?

**Comment by Herschel** [comment]
Fixed by #4584.
