### ISSUE TITLE
Error on https://www.addictinggames.com/zombie/sonny

### ISSUE THREAD

**Issue by maxmckittrick** [ruffle-rs/ruffle#3412]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:3134:14

# Player Info
Allows script access: true
Player type: Object
SWF URL: /sites/default/files/flash_games/sonny_0.swf
Param menu: false
Param allowscriptaccess: always
Param allownetworking: all
Param movie: /sites/default/files/flash_games/sonny_0.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.addictinggames.com/zombie/sonny
SWF URL: https://www.addictinggames.com/sites/default/files/flash_games/sonny_0.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-29
Channel: nightly
Built: 2021-01-29T00:34:32.424Z
Commit: bb4240ad1f9705b080c9f7861e38b6677a62d76b

**Comment by Poopooracoocoo** [comment]
can you also repro by playing the swf in the demo? the demo has a newer version of ruffle where it might've been fixed.

**Comment by maxmckittrick** [comment]
thanks for the tip, I can't reproduce this in the demo build after a few minutes of testing. I used the swf attached as well as a copy of sonny 2 which I downloaded from the same archive. 

for reference, the error originally occurred after saving, after clicking the `Load Game` button from the start menu.

**Comment by maxmckittrick** [comment]
closing this as it appears to be resolved in the latest nightly build
