### ISSUE TITLE
ActionScript3 SWF not playing

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [ruffle-rs/ruffle#3413]
hi, i tried to play a flash which contains actionscript3. but it doesn't work .

**Comment by ymypl** [comment]
known. actionscript 3 is not supported as of right now.

**Comment by Poopooracoocoo** [comment]
@Siddhant-Mashalkar you removed the entire template just to say that... you knew what you did... please understand that it'll take time and that this is a hobby/passion project by the devs. consider contributing somehow. there are so many issues that just keep piling up.

**Comment by Siddhant-Mashalkar** [comment]
oops sorry
