### ISSUE TITLE
attachMovie width and height not recognized

### ISSUE THREAD

**Issue by foumart** [ruffle-rs/ruffle#3414]
**Describe the bug**
AS2
this.attachMovie("movieID", "movie_mc", this.getNextHighestDepth(), {_x:48, _y:120});// ruffle does not support setting _width and _height through the passed object. This is not a big issue, as I can set those explicitly, but content that uses this approach will fail - the movie doesn't get displayed at all.

**Expected behavior**
Resizing the movieclip should be possible by providing _width and _height along the _x and _y in the fourth argument.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
 - self-hosted version

**What platform are you using?**
 - Chrome Version 88.0.4324.190 (Official Build) (64-bit) (Win10)

**Comment by Herschel** [comment]
Also causes #2084.
