### ISSUE TITLE
web: Quick Sand - Loop Error - Codec Error - Opcode Error

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#3428]
Hey,

another dead game :)

https://www.newgrounds.com/portal/view/539093?emulate=flash

ruffle-object.js:107 Error running definition tag: DefineVideoStream, got Invalid data: Invalid video codec.
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:107

ruffle-object.js:107 Unknown AVM1 opcode: Unknown { opcode: 252, data: [3, 0] }
a.wbg.__wbg_error_e325755affc8634b @ ruffle-object.js:107

**Comment by relrelb** [comment]
Closing since it no longer loops on master.
