### ISSUE TITLE
Javascript scheme checking needs more sanitizing, could cause XSS

### ISSUE THREAD

**Issue by EmperorBale** [ruffle-rs/ruffle#3444]
This bug is similar to #3132. I want to first of all apologize for not also reporting this bug in my last issue, I genuinely did not notice it until now. The check for the javascript scheme needs to also check for tabs and newlines, for example:
```as
getURL("jav\tascript:alert('hello')");
```
Also,
```as
getURL("jav\nascript:alert('hello')");
```
This will execute javascript, even when allowScriptAccess is disabled.

To fix this issue completely, the best way would probably be to actually allow malformed javascript url's to pass the check, then just encode all url's before using them. Also, instead of running the javascript url's by injecting the javascript in the page, they should just be used like a normal URL (but be blocked if allowScriptAccess is false).

**Comment by EmperorBale** [comment]
If it helps, I can make a PR with the changes I mentioned and let you guys review it to make sure it's good

**Comment by relrelb** [comment]
Another suggestion: The URL can be sanitized with [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL), so not only it's guaranteed to be valid, it would also be possible to allow/block specific schemes using `url.scheme`.

**Comment by EmperorBale** [comment]
> Another suggestion: The URL can be sanitized with [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL), so not only it's guaranteed to be valid, it would also be possible to allow/block specific schemes using `url.scheme`.

I don't see a scheme property in the documentation, are you sure it exists?
