### ISSUE TITLE
Error in the game Woobies   --  https://www.spiele-thueringen.de

### ISSUE THREAD

**Issue by buh1m** [ruffle-rs/ruffle#3449]
**Describe the bug**
Game Woobis
All balls are displayed in the same color.
Error image: https://www.forum-thueringen.de/thread.php?postid=1018814#post1018814

https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=3122
https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=3123
https://www.forum-thueringen.de/ufp_start.php?do=playgame&gameid=3124

**Expected behavior**
Normal are different colors to find the right one.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Nightly 2021-02-27 - Self Hosted
https://www.forum-thueringen.de/portal.php?id=140
Login required.

**What platform are you using?**
Ubuntu 20.04.2 - Firefox 85

**Comment by desertking** [comment]
This error is still open, sadly =) In the other thread there is this mentioned: ColorMatrixFilter?

**Comment by desertking** [comment]
Just in case anyone cares, which I doubt since this bug is open since 2021: https://www.spiele-umsonst.de/azad/downloads/flashgames/MouseChain.swf - This game seems to have the same issue. At least every mouse is the same color which should not be the case.

**Comment by n0samu** [comment]
See #15

**Comment by Lord-McSweeney** [comment]
ColorMatrixFilter on display objects has been implemented by #11702; I was unable to test Woobies because I could not find a SWF and the original site requires registration to play games. However, Mouse Chain displays correctly now.
