### ISSUE TITLE
Ball sprite not visible on most games on DeusX.com

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3465]
DeusX.com is the author of various sports games, built on the same engine. Ruffle (in all versions) doesn't properly render the ball sprite - you can see players, goal, field etc, but not the ball. Example URLs:

https://www.deusx.com/copa-america/
https://www.deusx.com/football-champions/
http://www.deusx.com/top-striker/

I have attached the screenshot, on which I marked ball shadow sprite, ...and the ball is not visible at all.

<img width="702" alt="Screen Shot 2021-02-28 at 10 11 42 AM" src="https://user-images.githubusercontent.com/22566535/109413438-ac2f0d80-79ad-11eb-9739-50ce89e633d6.png">

**Comment by Toad06** [comment]
Thanks for the report.

These issues are the same as #3075.

**Comment by relrelb** [comment]
Fixed by #6595.
