### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/bomb-it-5.html

### ISSUE THREAD

**Issue by eeblandonf** [ruffle-rs/ruffle#3474]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/bomb-it-5.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment]
@eeblandonf 
Bomb It 5 is written in ActionScript 3, the newer language of SWFs which Ruffle does not yet support. 

Juegos Area ought to update their version of Ruffle. Please contact them telling them so.

**Comment by Toad06** [comment]
Thanks for the report. This is an issue on Juegos Area's side, as the .wasm file cannot be found. It's up to the website's administrator to fix that.
