### ISSUE TITLE
Error on e926/e621 flash files

### ISSUE THREAD

**Issue by drummerdude2003** [ruffle-rs/ruffle#3476]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/2582509?q=type%3Aswf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-01
Channel: nightly
Built: 2021-03-01T00:19:40.301Z
Commit: e7d7e19c24edd0d77ffcb5edd8ce0c8ab9d5cf46

**Comment by Poopooracoocoo** [comment]
#2201

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
