### ISSUE TITLE
Transparent Art that should appear solid

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#348]
The madness dude in this preloader is rendering transparent instead of solid:

https://www.newgrounds.com/portal/view/580505

**Comment by TomFulp** [comment]
This tank preloader has a similar issue: https://www.newgrounds.com/portal/view/406574

**Comment by Herschel** [comment]
Seems to only occur on the web client.

**Comment by Herschel** [comment]
The art in question is masked, and the masking clip has alpha on it. In the canvas backend, this alpha incorrectly gets applied to the masked content.

**Comment by Herschel** [comment]
Fixed by setting a color transform to max out the alpha of the mask clip. Unfortunately this doesn't work on Safari because of #25.
