### ISSUE TITLE
Error on https://e621.net/posts/22326

### ISSUE THREAD

**Issue by LovelyRamonaKitty** [ruffle-rs/ruffle#3486]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/21525?q=sound

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-27
Channel: nightly
Built: 2021-02-27T00:17:48.863Z
Commit: 8500a676cfb694dc46fd258c0802c3dee4d61f66

All E621 flash games were all prohibited.

**Comment by Toad06** [comment]
Closing in favor of #2201 as this is the same issue. Thanks for reporting.
