### ISSUE TITLE
Request: Meaningful version numbers in nightly extension build manifest

### ISSUE THREAD

**Issue by albertsun** [ruffle-rs/ruffle#3493]
This is not a big deal, but in the chrome://extensions menu Ruffle always says `0.1.0` after loading the unpacked extension, so I have no idea how long ago I actually updated the extension.

<img width="426" alt="Screen Shot 2021-03-01 at 7 01 51 PM" src="https://user-images.githubusercontent.com/382862/109575831-95c5a680-7ac0-11eb-9c6f-6f20db7f17fb.png">

Not sure what is possible as far as version numbers here, but having some that change would be really nice in helping debug things!

**Comment by Poopooracoocoo** [comment]
also see #575

**Comment by relrelb** [comment]
Fixed by #4021.
