### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/mahjong-shanghai-dinasty.html

### ISSUE THREAD

**Issue by manuelbalbin** [ruffle-rs/ruffle#3510]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/mahjong-shanghai-dinasty.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by manuelbalbin** [comment]
QUIERO ENTRAR A JUGAR MAHJON DINASTY Y NO ME PERMITE , ME PUEDEN INFORMAR LA CAUSA

**Comment by manuelbalbin** [comment]
EL JUEGO ES MAHJONG-SHANGAI-DINASTY

**Comment by manuelbalbin** [comment]
DINASTY

**Comment by Poopooracoocoo** [comment]
@manuelbalbin You need to tell Juegos Arena to fix this.

**Comment by danielhjacobs** [comment]
Este es un problema con el sitio web. Utilice este enlace para informar el problema: https://www.juegosarea.com/contacto/. Ruffle no puede arreglarlo.

**Comment by relrelb** [comment]
Seems to have been fixed.
