### ISSUE TITLE
Implement [html]Text property in Flash text fields

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#3522]
We've encountered some games that take in HTML from XML files. Per discussion on the Discord server, there is in AS2 an attribute to Flash text fields that enables them to accept basic HTML tags. It sounds as though this needs to be implemented and/or Ruffle's html parsing needs improvement.

According to JPEXS, the field is a Boolean called simply 'html'. That appears to be AS2's approach.
AS3 uses the property htmlText as a string to contain a subset of allowed tags.

Tested using Desktop app, extension, and self-host from 2/27/21 and 3/2.
 Windows 10 64-bit Chromium based browsers, Firefox, and desktop app.
[http://www.bbc.co.uk/history/interactive/games/gladiator/index_embed.shtml](url)
![dressed_to_kill](https://user-images.githubusercontent.com/24618934/109902066-83ce3a00-7c5f-11eb-84ef-d45877f481a8.png)
[gladiator.zip](https://github.com/ruffle-rs/ruffle/files/6080484/gladiator.zip)

**Comment by jacs123** [comment]
Hi,

I am encountering a similar problem with this game : [https://educationalgames.nobelprize.org/educational/medicine/split-brain/splitbrainexp.html](url)
When it comes to a part where a letter is shown, the words do not appear, so I cannot proceed with the game. 
![Screenshot (55)](https://user-images.githubusercontent.com/20255407/110746559-f189ef80-8277-11eb-9dcb-db4b34ce5497.png)

I have tried on the Windows and Mac Chrome browsers using the extension from 3/10. Using the Desktop version of Ruffle with this swf [https://educationalgames.nobelprize.org/educational/medicine/split-brain/splitBrain_main.swf](https://educationalgames.nobelprize.org/educational/medicine/split-brain/splitBrain_main.swf) did not work either.
