### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/gran-premio-de-cocina-con-rachel-tartas.html

### ISSUE THREAD

**Issue by wenjho** [ruffle-rs/ruffle#3523]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/gran-premio-de-cocina-con-rachel-tartas.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by danielhjacobs** [comment]
Can you please close this issue and report it by using https://www.juegosarea.com/contacto/. Hopefully the website administrator will fix it. It's on the website's side, not Ruffle.

**Comment by danielhjacobs** [comment]
En español (sólo sé un poco de español)

Este es un problema con el sitio web. Utilice este enlace para informar el problema: https://www.juegosarea.com/contacto/. Ruffle no puede arreglarlo.

**Comment by relrelb** [comment]
Seems to have been fixed. The SWF loads but doesn't play well probably due to AVM2 support.
