### ISSUE TITLE
Difference issue between the mid-February and March Ruffle builds

### ISSUE THREAD

**Issue by stekar77** [ruffle-rs/ruffle#3532]
Hi I am using the 2021_02_13 build and have been playing fine many of my long-time downloaded flash games with almost the same results as the flash player. Then I tried 03_02 to 04 builds and I have two problems:

- in WOW Connect (1) v.1.7 (T45 Games - www.playitontheweb.com/games/WOW-Connect-game.htm) I now get stuck on a screen of a non-existing "Advertisement: _ sec" with no way to proceed.
- in Mah Jong Connect v.1.10 (Front Network) I get a terrible flickering between the intro page and the actual game with no way to interfere.

Because these are my most played flash games I have to stay on the february build. I haven't found other issues within the playable swf games, and hope these issues will eventually be corrected or I will have to stay behind in the Ruffle builds.

**Comment by Poopooracoocoo** [comment]
also see #3501 and #3525

**Comment by stekar77** [comment]
Thank you Poopooracoocoo, glad to know it is a known issue. Since you mentioned this thread in #3501 and #3525, I add here that I run **Windows 10 Pro v.20H0** x64. I also use Firefox, but this is not about the browser add-on.

**Comment by Poopooracoocoo** [comment]
yeah it's an issue over on the rust side which is the core of ruffle as i understand it.

**Comment by torokati44** [comment]
Fixed by #3566.
