### ISSUE TITLE
Animation stuck - nsfw

### ISSUE THREAD

**Issue by fmue11er** [ruffle-rs/ruffle#3536]
https://www.furaffinity.net/view/15344791/

nsfw, 

The game stucks in the start animation. 
I'm not sure how far/detailed i should go. What is needed to help ^^.

Normaly:
the door opens with an one way animation.
- followed by a shown animation. 
- Animations continues by click
- followed by an animation
this repeats a few times.
- at the end animation, there is a possibility to reset and start from beginning.

**Comment by torokati44** [comment]
Playing the game for testing requires a login it seems.
I'm not sure how many people would create an account just for this. At least I don't really want to.
Do you know if the game is playable in any other way/place without such requirement?

**Comment by fmue11er** [comment]
I'm srry. i dont know an other way.
I thought it's a good represent for Action Scripts. 

I'm srry for the disturbance.

**Comment by danielhjacobs** [comment]
@torokati44 It seems the downloading the SWF (http://d.furaffinity.net/art/endium/1419926082/1419926082.endium_creeperani02.swf) doesn't require logging in. However, a quick check shows me this SWF is AS3, so that is likely the root cause, since AS3 is unsupported.

**Comment by fmue11er** [comment]
Thank for the help. I guess its a matter of time till AS3 is next in the row of goals. 
i hope i can/could help.
