### ISSUE TITLE
Two problems in BOOKWORM game

### ISSUE THREAD

**Issue by perelowski** [ruffle-rs/ruffle#3538]
Hello,

Tested with all Ruffle versions (self-hosted, extension) on Chrome, Firefox, on Windows and Mac.

Tested URL: https://juegospot.com/gamez/bookworm/

I was trying to revive the classic BOOKWORM game and identified two problems:

1) On the home screen, labels on buttons (PLAY, LEARN etc.) are missing, you can see only book edges (screenshot 1 below)

<img width="703" alt="Screen Shot 2021-03-05 at 10 06 33 AM" src="https://user-images.githubusercontent.com/22566535/110095284-090b3900-7d9d-11eb-8c64-bed298928361.png">

2) During gameplay, there are only pieces with letter "A" (screenshot 2 below). 

After clicking on any piece and trying to drag the cursor to create a word, console throws such errors as:
- Tried to instantiate non-registered character ID 68
- Unable to instantiate display node id 68

<img width="617" alt="Screen Shot 2021-03-05 at 10 04 47 AM" src="https://user-images.githubusercontent.com/22566535/110095240-fee93a80-7d9c-11eb-849b-ed4a9955d7d7.png">

**Comment by perelowski** [comment]
Hello,

I just wanted to know if anyone from Ruffle dev team has seen this issue? I am not pushing for solving it right now, of course - just out of curiosity, I'd like to know if such reports are something valuable for your team and can help in Ruffle development?

**Comment by Toad06** [comment]
Hello and thanks for reporting a bug. Sorry that it fell through the cracks...

The game appears to work as expected now as both of the issues you mentioned no longer occur in the last releases, so I'm going to close this and take a look at your other bug reports.
