### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Myobu1** [ruffle-rs/ruffle#3543]
# Error Info
Error name: TypeError
Error message: WebAssembly.instantiate is not a function
Error stack:
```
TypeError: WebAssembly.instantiate is not a function
    at https://ruffle.rs/demo/index.js:1:43597
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
Useragent: Mozilla/5.0 (Linux; Android 10; SM-T860) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-04
Channel: nightly
Built: 2021-03-04T00:17:59.511Z
Commit: f64e5d5b4113249417570c9bb905be75c8401fb3

**Comment by Myobu1** [comment]
I'm using the Kiwi browser and have tried every demo on the website. Nothing works. I've cleared my browser cache, installed older versions of the extension, tried desktop mode, and checked that Javascript was enabled. Nothing helped.

**Comment by adrian17** [comment]
Kiwi Browser has webassembly support disabled by default - see https://github.com/kiwibrowser/src/issues/197#issuecomment-706790668 . User needs to opt-in manually.
Closing this issue as there's nothing we can do :(
