### ISSUE TITLE
Ruffle Error on https://www.juegosarea.com/grand-prix-go.html

### ISSUE THREAD

**Issue by githubDaw1** [ruffle-rs/ruffle#3550]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.juegosarea.com/grand-prix-go.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment]
@githubDaw1 Mind closing this and then reporting this issue to Juegos Area? This is an issue on their side and not with Ruffle.

**Comment by relrelb** [comment]
Seems to have been fixed. The SWF loads but a black screen appears probably due to AVM2 support.
