### ISSUE TITLE
Ruffle Error on https://www.meninasjogos.com.br/selena-gomez-no-salao-de-beleza/

### ISSUE THREAD

**Issue by anavihh** [ruffle-rs/ruffle#3552]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.meninasjogos.com.br/selena-gomez-no-salao-de-beleza/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment]
@anavihh This looks like an issue on Meninans Jogos's side. Please contact them asking them to fix how Ruffle was implemented on it.
