### ISSUE TITLE
 http://www.cengage.com/statistics/book_content/1285463188_utts/watch_it/UHMS2_16_01_01_00.html

### ISSUE THREAD

**Issue by pharmdoc** [ruffle-rs/ruffle#3555]
http://www.cengage.com/statistics/book_content/1285463188_utts/watch_it/UHMS2_16_01_01_00.html

I'm unable to play a flash video using Ruffle extension Nightly 2021-03-06 on Google Chrome Version 89.0.4389.72  on a mac. 

The webpage loads, I click the play button, then the window says "Loading..."

**Comment by Poopooracoocoo** [comment]
Fixed for me. Using Ruffle 2023-01-26 Chrome 109 on Windows 10
