### ISSUE TITLE
FluidAnims Loader - Play button opens new URL instead of playing animation

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#356]
https://www.newgrounds.com/portal/view/535884
https://www.newgrounds.com/portal/view/536322
https://www.newgrounds.com/portal/view/587071

Clicking the play button on these submissions opens a new browser tab that is quickly taken over by an ad exchange redirect. Expected behavior: Animation should play without a new tab opening.

**Comment by Herschel** [comment]
Fixed by #1079.
