### ISSUE TITLE
Error on https://www.supergames.cz/online-hra/4197/bola/

### ISSUE THREAD

**Issue by MSGCZ** [ruffle-rs/ruffle#3561]
Hello,

SWF game **Bola** working on [https://www.supergames.cz/online-hra/4197/bola/](https://www.supergames.cz/online-hra/4197/bola/) with **Ruffle Nightly 2021-02-16**, but in new version **Ruffle Nightly 2021-03-01** and later is NOT working. Why?

Best regards
Martin

**Comment by Toad06** [comment]
Thanks for the report. This issue is probably related to https://github.com/ruffle-rs/ruffle/issues/3501#issuecomment-788886944.

**Comment by Poopooracoocoo** [comment]
@MSGCZ should now be fixed! :)

**Comment by MSGCZ** [comment]
Great... Thanks ;)
