### ISSUE TITLE
Error on https://www.coolmath-games.com/gameFrame?u=sites/cmatgame/files/games/papastacomia_coolmath.swf&f=papastacomia_coolmath.swf

### ISSUE THREAD

**Issue by Anyucpouakot64** [ruffle-rs/ruffle#3565]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
Error stack:
```
Error: panicked at 'already borrowed: BorrowMutError', web/src/lib.rs:836:49
    at r.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:11028)
    at wasm-function[1265]:169
    at wasm-function[1528]:675
    at wasm-function[4309]:67
    at wasm-function[3299]:224
    at wasm-function[3916]:159
    at wasm-function[4655]:40
    at wasm-function[4526]:89
    at wasm-function[4657]:48
    at wasm-function[3996]:123
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/papastacomia_coolmath.swf
Param allowScriptAccess: always
Param movie: papastacomia_coolmath.swf
Param menu: false
Param quality: high
Param wmode: direct
Param scale: exactfit
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.coolmath-games.com/gameFrame?u=sites/cmatgame/files/games/papastacomia_coolmath.swf&f=papastacomia_coolmath.swf
SWF URL: https://www.coolmath-games.com/sites/cmatgame/files/games/papastacomia_coolmath.swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by Poopooracoocoo** [comment]
@Anyucpouakot64  Woah! That's a really old version of Chrome! Chrome started to add support for the modern web technologies such as WebAssembly that Ruffle uses in around version 70 and onwards. Please consider updating Chrome or using a different, up to date, browser. 

Unfortunately browsers have dropped support for Mac OS X Mavericks (version 10.9), but I think Firefox's last version for it may have better support for WebAssembly. It may be worth browsing about:config or chrome://flags for feature flags related to WebAssembly.

But note that Papa's Taco Mia is written in ActionScript 3, the newer language for SWFs written after 2006. Ruffle does not yet support AS3.

**Comment by danielhjacobs** [comment]
This SWF uses AS3 which is not yet supported: #1368. A warning message should appear when attempting to load it.
