### ISSUE TITLE
Sounds repeating when they shouldn't

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#357]
https://www.newgrounds.com/portal/view/547061

During the intro before the song, the girl says "Can I have  a glass of water please" but it plays twice in Ruffle - same with the bartender reply. Mike thinks it may be streamed sounds not being stopped properly when a clip is removed.

**Comment by Herschel** [comment]
Looks like these are event sounds instead of stream sounds like I originally thought. Doesn't seem like they have a SOUNDINFO set, but are still looping for some reason.
