### ISSUE TITLE
AVM1 error: Expected Object

### ISSUE THREAD

**Issue by goldenratio** [ruffle-rs/ruffle#36]
Hi,

I was checking AVM1 functionality. I am getting below error,

![image](https://user-images.githubusercontent.com/3019293/63543337-44337780-c52b-11e9-8cef-6a7b363711da.png)

SWF file: https://drive.google.com/file/d/14cn4VqL2KyISsMtmU7rk42WPQ6_Ayps8/view?usp=sharing
Browser: Firefox 68
OS: Windows 10

**Comment by goldenratio** [comment]
Added .swf file,
https://drive.google.com/file/d/14cn4VqL2KyISsMtmU7rk42WPQ6_Ayps8/view?usp=sharing

**Comment by Dinnerbone** [comment]
This specific error has been fixed, but the game will be unplayable until we have the `Mouse` object implemented.

**Comment by Herschel** [comment]
Looks like this game is working now.
