### ISSUE TITLE
The game does not work anymore on https://www.dolldivine.com/mega-fantasy-avatar-creator.php

### ISSUE THREAD

**Issue by Bulle-Bulle** [ruffle-rs/ruffle#3600]
Ruffle error message appears.

# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```
# Player Info
Allows script access: false

# Page Info
Page URL: https://www.dolldivine.com/mega-fantasy-avatar-creator.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

It was operational until 10/03/2021

**Comment by Poopooracoocoo** [comment]
That error usually means it's an issue with how Ruffle is hosted on the website :/ hmm

**Comment by Poopooracoocoo** [comment]
Seems to working again :)
