### ISSUE TITLE
Error on https://e621.net/posts/342770

### ISSUE THREAD

**Issue by dsa4315** [ruffle-rs/ruffle#3601]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/342770?q=flash+female+cum

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-10
Channel: nightly
Built: 2021-03-10T00:18:18.876Z
Commit: 934f95cd52838387ea1281fbf72be81ffb8e7903

**Comment by Poopooracoocoo** [comment]
#2201
