### ISSUE TITLE
Problem building Ruffle for the web version

### ISSUE THREAD

**Issue by ficristo** [ruffle-rs/ruffle#3609]
I tryed to follow the [wiki](https://github.com/ruffle-rs/ruffle/wiki/Building-Ruffle) to build the web version but without much results.

For the selfhosted version it says:
```sh
cd web/packages/selfhosted/
npm run bootstrap
npm run build
```
but when running `npm run bootstrap` I get:
`missing script: bootstrap`

For the selfhosted version it says:
```sh
cd web/packages/selfhosted/
npm run bootstrap
npm run build
```
but when running `npm run build` I get:
``error[E0463]: can't find crate for `core` ``

This is on Windows 10.

I'm missing something?

Also I didn't find information about which is the minimum needed NodeJS version: I suppose is 15 or more recent.

**Comment by torokati44** [comment]
Run the `npm` commands in `web/`. That will build both extensions and selfhosted as well.

**Comment by adrian17** [comment]
I just updated the wiki.

**Comment by ficristo** [comment]
I still get:
error[E0463]: can't find crate for `core`

**Comment by ficristo** [comment]
Full output of `npm run build`
```
> ruffle@0.1.0 build
> lerna run build --stream

lerna notice cli v4.0.0
lerna info Executing command in 4 packages: "npm run build"
ruffle-core: > ruffle-core@0.1.0 build
ruffle-core: > npm run build:cargo && npm run build:wasm-bindgen && npm run build:wasm-opt && npm run build:ts
ruffle-core: > ruffle-core@0.1.0 build:cargo
ruffle-core: > cargo build --release --target wasm32-unknown-unknown
ruffle-core:    Compiling cfg-if v1.0.0
ruffle-core:    Compiling itoa v0.4.7
ruffle-core:    Compiling bitflags v1.2.1
ruffle-core:    Compiling libc v0.2.84
ruffle-core: error[E0463]: can't find crate for `core`
ruffle-core:   |
ruffle-core:   = note: the `wasm32-unknown-unknown` target may not be installed
ruffle-core: error: aborting due to previous error
ruffle-core: For more information about this error, try `rustc --explain E0463`.
ruffle-core: error[E0463]: can't find crate for `core`
ruffle-core:   |
ruffle-core:   = note: the `wasm32-unknown-unknown` target may not be installed
ruffle-core: error: aborting due to previous error
ruffle-core: For more information about this error, try `rustc --explain E0463`.
ruffle-core: error: could not compile `cfg-if`
ruffle-core: To learn more, run the command again with --verbose.
ruffle-core: warning: build failed, waiting for other jobs to finish...
ruffle-core: error: build failed
lerna ERR! npm run build exited 101 in 'ruffle-core'
```

**Comment by torokati44** [comment]
Looks like the wiki is still not entirely up to date. You also need to add the wasm target for the rust compiler, install wasm-bindgen, and optionally binaryen...
These instructions are more complete:
https://github.com/ruffle-rs/ruffle/blob/master/web/README.md#building-from-source
