### ISSUE TITLE
Error on https://www.cartoonnetworkme.com/ 

### ISSUE THREAD

**Issue by VictoriaDemuysereLaptop** [ruffle-rs/ruffle#3632]
I am so excited that you guys have partnered with this site, some of my all time favorite games are here! When I tried to run one however I got this error, I have no idea what it means as I only have basic knowledge on computer coding. I hope this gets figured out, and I wish you luck as I know how finicky coding can be!

this is the url for the game: https://www.cartoonnetworkme.com/games/chowder-bookin-cook/play

# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://cn.i.cdn.ti-platform.com/cnemea/content/96/game/bookin-cook/za/bookincook/preload.swf
Param allowscriptaccess: always
Param allownetworking: all
Param allowfullscreen: false
Param wmode: OPAQUE
Param bgcolor: #8d8d8d
Param base: https://cn.i.cdn.ti-platform.com/cnemea/content/96/game/bookin-cook/za/bookincook/preload.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.cartoonnetworkme.com/games/chowder-bookin-cook/play

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by Poopooracoocoo** [comment]
I'm not sure what partnership you're talking about (I'm just a fellow user) as it looks like Cartoon Network isn't using Ruffle on their own website, at least on my side. Are you using the extension? I don't get an error on the latest version of the Ruffle extension for Chrome for Windows 10 but the game just has a blank screen.
