### ISSUE TITLE
Error on http://www.flashpacman.info/pacman-pac-xon.php

### ISSUE THREAD

**Issue by Asdfguy86** [ruffle-rs/ruffle#3641]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): not all code section bytes were used @+906243
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): not all code section bytes were used @+906243
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.flashpacman.info/pacman-pac-xon.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-13
Channel: nightly
Built: 2021-03-13T00:18:20.687Z
Commit: 1c2492005c30e0f6bf867211307484e9c23da7c6

**Comment by Poopooracoocoo** [comment]
@Asdfguy86 Do you mind closing this issue and reporting it to Pac-Xon instead? 

As you saw in the error message, this is not an issue with Ruffle but with some JavaScript code that conflicts with Ruffle. The server administrator of Pac-Xon must therefore handle this.

**Comment by Asdfguy86** [comment]
seems like they fixed the issue on the site anyway 👍
