### ISSUE TITLE
Some big issue

### ISSUE THREAD

**Issue by ruffle-fan** [ruffle-rs/ruffle#3646]
Hy. I use ruffle player on my flash gamesites, (thank you very much ;) ) but i get too many message due to some popular games. 

1. Mahjong Connect v1.3 - freez in the end of level one, because some tile(s) is unmatched.
http://mahjongall.com/mahjong-connect_v1_3.swf

2. Wow connect v1.4 - freez in the end of 4 or 6, because some tile(s) is unmatched.
http://mahjongall.com/wow-connect_v1_4.swf

3. super mario flash 
http://mahjongall.com/super-mario-flash_v3.swf
Mario don't move in the level select screen. (arrow keys don't working)

This 3 games is so important my visitors. Thanks for help, and so many thanks for the ruffle player.

**Comment by n0samu** [comment]
Looks like all of these issues have been fixed. Can you verify?
