### ISSUE TITLE
Error on https://yaldagames.com/game.php?i=808

### ISSUE THREAD

**Issue by mishelik777** [ruffle-rs/ruffle#3648]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:68100
    at Array.forEach (<anonymous>)
    at Object.mi.f.wasm (https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:67753)
    at Promise.all.Object.keys.reduce (https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:35882)
    at Array.reduce (<anonymous>)
    at Function.mi.e.e (https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:35859)
    at o (https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:2645)
    at o.next (<anonymous>)
    at https://yaldagames.com/ruffle/11-01-2021/ruffle.js:1:2945
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: game/808/808.swf
Param movie: game/808/808.swf
Param quality: high
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param allowFullScreen: true
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://yaldagames.com/game.php?i=808

# Browser Info
Useragent: Mozilla/5.0 (Linux; U; Android 9; ru; Redmi 8A Build/PKQ1.190319.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.10.0.1163 UCTurbo/1.10.3.900 Mobile Safari/537.36
OS: Linux armv7l

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by adrian17** [comment]
> Chrome/57.0.2987.108 UCBrowser/12.10.0.1163

From what I can see, you are using a pretty old browser, which is the reason why nothing loads at all.
Check out https://github.com/ruffle-rs/ruffle/wiki#web
