### ISSUE TITLE
A Dragon's Flight - Black Screen after hitting Preloader Play button

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#366]
https://www.newgrounds.com/portal/view/577610

The loading screen for this animation works but it cuts to black after you click Play. This seems different from some of the common issues here such as having a bad preloader or cutting to video.

**Comment by Herschel** [comment]
V-Cam causes a double borrow panic (cc #398)

**Comment by Herschel** [comment]
Was fixed by #399.
