### ISSUE TITLE
Animation is faster than sound

### ISSUE THREAD

**Issue by Leon2110** [ruffle-rs/ruffle#3663]
I have educational flash games on the site. 
URL: 
https://karinagerman.ru/games/vol1/
https://karinagerman.ru/games/vol2/
https://karinagerman.ru/games/vol3/
...

For example, take this one: https://karinagerman.ru/games/vol2/
This flash consists of several files. MENU.SWF, COLOURS.SWF, and more...
From the MENU.SWF file, you can access other SWF files. You can use the menu or open each file separately.

That's how it works well. I open the json and select "Colors", and then select "song". The music starts. The sound matches the animation, great.
![001](https://user-images.githubusercontent.com/80687074/111149493-00d1ab80-859e-11eb-913d-73cd3c37fc3e.jpg)
![002](https://user-images.githubusercontent.com/80687074/111149499-029b6f00-859e-11eb-8fa1-0273afe1dad7.jpg)

Here's the same thing. Only I go to "Colors" via the SWF file menu. I also click "song". Animation goes faster than sound ((This is a problem on all these games. They all have menus.
![003](https://user-images.githubusercontent.com/80687074/111149908-85242e80-859e-11eb-9a11-379c78f55422.jpg)
![004](https://user-images.githubusercontent.com/80687074/111149918-86555b80-859e-11eb-8fe9-1c7532217569.jpg)

**Comment by firoball** [comment]
Guessing here: Might be fixed with #3485 ?

**Comment by haraldbre** [comment]
Sorry to say #3485 doesn't fix this.

**Comment by Michael82548** [comment]
Its slightly off sync for me also

**Comment by haraldbre** [comment]
Actually it is a bit more complicated:
ruffle-desktop with fix #3485 also fixes this. 
However firefox-extension doesn't.
After setting the new frame_rate the extension seems to go back to the root video frame rate.

**Comment by haraldbre** [comment]
Actually it is a bit more complicated:
ruffle-desktop with fix #3485 also fixes this. 
However firefox-extension doesn't.
The reason seems to be that https://karinagerman.ru/games/vol2/ comes packaged with its own ruffle.js version. That has the advantage that the ruffle extension has not be explicitly loaded by the user to run the web page, but the disadvantage that explicitly loading another ruffle version has no effect.

**Comment by Herschel** [comment]
Fixed by #5486.
