### ISSUE TITLE
Error on https://playporngames.com/farmers-daughter/

### ISSUE THREAD

**Issue by SiikShotCJ** [ruffle-rs/ruffle#3666]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://playporngames.com/farmers-daughter/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.400
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by Poopooracoocoo** [comment]
this looks like an issue with the website

**Comment by Poopooracoocoo** [comment]
fixed, at least for me.
