### ISSUE TITLE
Error on http://www.juegosjuegos.com/embed/papas-pancakeria

### ISSUE THREAD

**Issue by ahitana** [ruffle-rs/ruffle#3678]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): unknown section code #0x87 @+18525
Error stack:
```
CompileError: WebAssembly.instantiate(): unknown section code #0x87 @+18525
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.juegosjuegos.com/embed/papas-pancakeria

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by Poopooracoocoo** [comment]
@ahitana This is an issue with Juegos Juegos and not with Ruffle. Ruffle was not correctly configured. Could you please close this issue and report this to them? 

In addition to that, Papa's Pancakeria is written in ActionScript 3, the newer language for SWFs that Ruffle does not yet support. Ruffle started with support for AS1 and AS2, which use the same "virtual machine" that basically runs the code on your system.
