### ISSUE TITLE
Caret/cursor continues to blink in text fields when text field is not focused

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#3682]
**Describe the bug**
Caret/cursor continues to blink in text fields when text field is not focused

**Expected behavior**
Cursor should disappear

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted

**What platform are you using?**
 - Windows 10
 - Chrome 89
 - Ruffle version 2021-03-14

off topic side note:
I was just reading this: https://news.ycombinator.com/item?id=26334595 and this: https://news.ycombinator.com/item?id=23774515
Flutter is rendered with canvas and textareas and input controls and still has this issue.

**Comment by kjarosh** [comment]
That should be fixed as of today. If you have any content that still does not work, please create a new issue referencing it.
