### ISSUE TITLE
Drag and drop swf

### ISSUE THREAD

**Issue by sotoco** [ruffle-rs/ruffle#3690]
I am trying to run a "Self scoring drag and drop"

It loads in ruffle web demo 
I can drag the answer to the box but it does not snap in. It does not score or the reset button does not show 

I am using the ruffle self host

**Comment by Poopooracoocoo** [comment]
I think it's because onDragOut() and onDragOver() aren't supported yet?

**Comment by sotoco** [comment]
Thank you for you reply

I understand the ruffle emulator project will take some time. Wish them the best. I just wait until more people need the some solution

**Comment by Herschel** [comment]
Fixed by #4584.
