### ISSUE TITLE
Enter Key from Numpad not working

### ISSUE THREAD

**Issue by q2apro** [ruffle-rs/ruffle#3696]
**Describe the bug**
It is not a bug but a usability thing. Instead of the enter key I am using the enter key on the numpad pretty often.

Problem: Ruffle does not recognize this key.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

Self-hosted (web).

**What platform are you using?**
Windows 10, Chrome latest

**Comment by Lord-McSweeney** [comment]
Fixed by #9204.
