### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by karliss** [ruffle-rs/ruffle#37]
It would be nice to have basic developer documentation with information required to work on ruffle.

* Is ruffle using rustfmt 
* 1-2 sentence high level modules (core, desktop, web, swf-rs)
* The kinds of test suits and how to run them
*  Useful documents describing flash player, probably the the SWF spec, later AVM2 document. What are the latest versions and where to get them. Any other documents.
 * Useful tools for analyzing swf files third party flash dissembler/decompiler or some kind of dump command in ruffle or swf-rs, tool for creating test swf files or anything else that  helps making, testing or debugging ruffle.

**Comment by Herschel** [comment]
Would the GitHub wiki be a good place for this info?

**Comment by karliss** [comment]
Either Github wiki or a markdown file in repository is fine with me. This project is probably for from point where it will need anything bigger.

**Comment by Herschel** [comment]
Added some early documentation to the [wiki](https://github.com/ruffle-rs/ruffle/wiki). We're still sussing out the framework for testing, but hopefully this is a good start!

**Comment by karliss** [comment]
Looks greats! That's more than what I hope for.
