### ISSUE TITLE
Three Little Dogs - Audio Doesn't Loop

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#370]
https://www.newgrounds.com/portal/view/688130

This animation loops but the audio only plays the first time around.

**Comment by Herschel** [comment]
My first guess was that this was some sort of event sound with loop settings not working correctly, but it's actually a normal stream sound that doesn't restart for some reason. Need to verify that a stream restarts when a MC loops normally (i.e. not with ActionScript).
