### ISSUE TITLE
Bug with Super Mario Flash 2.0

### ISSUE THREAD

**Issue by Vantoss** [ruffle-rs/ruffle#3703]
Starts off normal, can select which character I would like to play. However, in the world map screen, I can't move the character at all, making the game unplayable as I cannot select the levels.

Here's a link to the game https://www.clickjogos.com.br/Jogos-online/Acao-e-Aventura/Super-Mario-Flash-20

Probably a bug with the Ruffle extension.

I'm using the desktop version. on Windows 10.

**Comment by Toad06** [comment]
Fixed by #6082.
