### ISSUE TITLE
Ruffle

### ISSUE THREAD

**Issue by balance200** [ruffle-rs/ruffle#3704]
I found a game that I wanted to do and switched to ruffle but when I did I did not see anything except a white screen, there was sound and I am sure I have the lastest of Chrome but I still have no visual.  Please help.

**Comment by EmperorBale** [comment]
Send a link to the game

**Comment by balance200** [comment]
https://www.comdotgame.com/play/hervy
The link of the game.

**Comment by danielhjacobs** [comment]
That animation uses unsupported video codec VP6: #723. That codec will be supported by PR #3004, which is still a draft. The author of that PR has stated that's they're holding up with the finalization of it until PR #2173 gets merged. The author of PR  #2173 (a different person than the author of #3004) and the main maintainer for Ruffle have not stated what needs to be done before it will get merged.

I would also love for VP6 support to be implemented, as some of my websites rely it, but I can't give you an accurate timeline.

**Comment by balance200** [comment]
Okay, I too hope it works.

**Comment by torokati44** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/5369.
_(My eyes could have used an NSFW warning before testing, but no judgement.)_
