### ISSUE TITLE
Error on http://www.thejohnnycashproject.com/

### ISSUE THREAD

**Issue by JMY1000** [ruffle-rs/ruffle#3705]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://www.thejohnnycashproject.com/pub/n/swf/release/Bootstrap.swf?v=115
Param bgcolor: #000000
Param allowfullscreen: true
Param scale: noscale
Param salign: tl
Param wmode: opaque
Param flashvars: pluginURL=http%3A%2F%2Fwww.thejohnnycashproject.com%2Fpub%2Fn%2Fxml%2Fplugins%2Fcom.rad.plugins.PreloadBoot.plugin.xml.php%3Fv%3Ddfb188e00b6b8bc35c6e8149ec076013
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: http://www.thejohnnycashproject.com/
SWF URL: http://www.thejohnnycashproject.com/pub/n/swf/release/Bootstrap.swf?v=115

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-19
Channel: nightly
Built: 2021-03-19T00:19:11.729Z
Commit: 7eb4c1440abc39360d4de148311b5fad46b92696

**Comment by relrelb** [comment]
Fixed by #4422.
