### ISSUE TITLE
Look at this AMAZING live MotionBlur demo using Just ActionScript 2 !!! Even today's "Game Engine" would be jealous !

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#3717]
[Demo.zip](https://github.com/ruffle-rs/ruffle/files/6176393/Demo.zip)

The reason I brought this up was because it works fine on the Standard Flash Player but not on Ruffles.

To understand this, I looked into the documentation, fortunately the explanation was laid out before us by greensock, hope this helps:
MotionBlurPlugin provides an easy way to apply a directional blur to a MovieClip based on its velocity
and angle of movement in 2D (_x/_y). This creates a much more realistic effect than a standard BlurFilter for
several reasons:

A regular BlurFilter is limited to blurring horizontally and/or vertically whereas the motionBlur gets applied at the angle at which the object is moving.</li>

A BlurFilter tween has static start/end values whereas a motionBlur tween dynamically adjusts the values on-the-fly during the tween based on the velocity of the object. So if you use a Strong.easeInOut for example, the strength of the blur will start out low, then increase as the object moves faster, and reduce again towards the end of the tween.</li>

motionBlur even works on bezier/bezierThrough tweens!<br /><br />

 * To accomplish the effect, MotionBlurPlugin creates a Bitmap that it places over the original object, changing 
 * _alpha of the original to [almost] zero during the course of the tween. The original MovieClip still follows the 
 * course of the tween, so Mouse events are properly dispatched. You shouldn't notice any loss of interactivity. 
 * The MovieClip can also have animated contents - MotionBlurPlugin automatically updates on every frame. 
 * Be aware, however, that as with most filter effects, MotionBlurPlugin is somewhat CPU-intensive, so it is not 
 * recommended that you tween large quantities of objects simultaneously.
 * 
I have made the example demo super simple, it is just a single button so during de-compilation, there will be no excessive bloat nonsense/decorative codes to go through.

**Comment by Poopooracoocoo** [comment]
also see #2247

**Comment by waspennator** [comment]
Filters are currently being implemented, however they don't seem to be showing up properly cause some functions aren't properly implemented yet, looking through the console log.

Encountered stub: AVM1 BitmapData.draw() with clip rect
Encountered stub: AVM1 BitmapData.applyFilter()

**Comment by n0samu** [comment]
Fixed by #12176
