### ISSUE TITLE
Onda Educa - Missing layer of objects

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#3721]
**Describe the bug**
Without going into too much detail, this is likely another example of #58
The puzzle activity in Animacuentos calls for the puzzle pieces (evidently on their own layer) to be sitting to the right of the empty puzzle board. They are not present when running in Ruffle. Also, the "Mezclar" button is supposed to shuffle the strewn positions of those puzzle pieces.  

**Expected behavior**
Layer with puzzles pieces should be present and able to be shuffled ("mixed").

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Desktop and web builds - 3/20/21 nightlies
.
**What platform are you using?**
Windows 10, Nvidia GPU, Chromium based browsers and Firefox.
![toto_memoria](https://user-images.githubusercontent.com/24618934/111898062-a8613a80-89f1-11eb-9eae-a8a48650bc47.png)
![toto_memoria_ruffle](https://user-images.githubusercontent.com/24618934/111898063-a8613a80-89f1-11eb-97fc-01317d1f59a5.png)
[puzle_micuento.zip](https://github.com/ruffle-rs/ruffle/files/6177033/puzle_micuento.zip)

**Comment by torokati44** [comment]
Running in the desktop build, the warning it gives is:
```
[2021-03-21T12:19:02Z WARN  ruffle_core::avm1::object] Object method beginBitmapFill is not callable
```

**Comment by sombraguerrero** [comment]
Unsurprising. I almost feel like Bitmap.draw should be included in the bug template text at this point ;)

**Comment by torokati44** [comment]
That's not the same thing. I also suspected `BitmapData.draw` for this too, but I believe `beginBitmapFill` is the "other way around": drawing a bitmap onto a MovieClip. At least that's what I think.

**Comment by sombraguerrero** [comment]
Yeah, I just mean, the entire Bitmap class should probably be called out in the template at this point, because even though there's not a central tracking issue for it, I think it's well known throughout the devs and testers that we've got a lot of work to do in that whole namespace.

**Comment by sombraguerrero** [comment]
The Bitmap.draw and BitmapData elements we have so far keep slowly pushing Animacuentos along, but we still need Fill. The matching game, for instance, now has generic background color tiles in the deck, but the images are still missing and they are not interactable tiles.

**Comment by n0samu** [comment]
`beginBitmapFill` is implemented now, yet this still doesn't work for some reason.

**Comment by sombraguerrero** [comment]
New screenshot of the issue in its current state (6/19 builds)
![image](https://github.com/ruffle-rs/ruffle/assets/24618934/61c3791b-49db-4be0-a923-ceef9a3a8181)

**Comment by sombraguerrero** [comment]
All the other jigsaws in the module:
[more_jigsaws.zip](https://github.com/ruffle-rs/ruffle/files/11785020/more_jigsaws.zip)
