### ISSUE TITLE
Flash interactive animations not displaying properly

### ISSUE THREAD

**Issue by Visiteur205** [ruffle-rs/ruffle#3758]
Hi,

I've tried using Ruffle to display teaching animations for power engineering on www.machines.ac.me - some pages work flawlessly with this however others with more complicated interactive graphs are not properly displayed (e.g. http://www.machines.ac.me/ind_opspeed.htm and http://www.machines.ac.me/ind_char.htm and a fair few others - on these dragging the buttons should results in displaying another curve(s) on the graph that changes with the button position).

Not sure what the bug is *(my coding days are well behind me) however thought I should raise this in case the people behind Ruffle are monitoring this forum and can have a look

Many thanks in advance

**Comment by Herschel** [comment]
Fixed by #4584.
