### ISSUE TITLE
(NSFW) https://www.newgrounds.com/portal/view/755134 wont play and was wondering if its a Ruffle issue or I did something wrong in installation

### ISSUE THREAD

**Issue by BattleSteam3821** [ruffle-rs/ruffle#3785]
**Describe the bug**
I put the link in my search bar and select play game as it is a Adult rated game and it wont load or show anything exept a black screen
Seen here
![Screenshot 2021-03-24 at 21 03 06](https://user-images.githubusercontent.com/81337247/112403216-64698080-8ce4-11eb-9997-82f339d88ae4.png)

![Screenshot 2021-03-24 at 21 05 02](https://user-images.githubusercontent.com/81337247/112403372-a98db280-8ce4-11eb-9376-5e617348a238.png)

and if this helps
![Screenshot 2021-03-24 at 21 07 29](https://user-images.githubusercontent.com/81337247/112403563-08ebc280-8ce5-11eb-8e75-2c3590e4f2be.png)

Edit: I tried another game made by the same person and that worked for the time I was there so my guess some sort of incompatibility

Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
Potential reproduction process
1. Copy the link here-> https://www.newgrounds.com/portal/view/755134
2. Paste into Google Chrome browser with the 2021-3-24 version of the extension
3. Attempt to play (only recommend if you dont have worry about mom walking in on you)

**Expected behavior**
I thought with the extension I put the link in the game would play with no effort outside the installation process

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Im using the extension

**What platform are you using?**
Im on Chrome OS using the Google Chrome browser

Thanks in advance as im new to this stuff

**Comment by Poopooracoocoo** [comment]
Which version of Chrome OS?

**Comment by BattleSteam3821** [comment]
> Which version of Chrome OS?
Version 77.0.3865.120 (Official Build) (32-bit)

**Comment by rvh1986** [comment]
Visiting [https://www.newgrounds.com/portal/view/755134?emulate=flash](https://www.newgrounds.com/portal/view/755134?emulate=flash) it took over a minute to finally show something and I got the blue "not supported by Ruffle yet" screen.

**Comment by BattleSteam3821** [comment]
> Visiting https://www.newgrounds.com/portal/view/755134?emulate=flash it took over a minute to finally show something and I got the blue "not supported by Ruffle yet" screen.

So I got wait for it to be supported
