### ISSUE TITLE
A note about SharedObjects

### ISSUE THREAD

**Issue by PsychoGoldfishNG** [ruffle-rs/ruffle#379]
I imagine this isn't on the radar just yet, but wanted to make a note about having Flash SharedObjects use something like localStorage.

On portal sites, like Newgrounds, SharedObjects never had any issues because they were always tied to the url of the swf file.

When using localStorage, however, all key/value pairs are tied to the hosting domain.  To prevent collisions, Ruffle might need to prefix any key names with the URL of the swf file, or something to that effect.

**Comment by Herschel** [comment]
cc #272

**Comment by relrelb** [comment]
Isn't this issue should be closed?
