### ISSUE TITLE
Firefox incorrectly renders additive alpha in color transforms

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#38]
fecb981b135f45b98ec54c450bc135f72a030695 added `color-interpolation-filters="sRGB"` to the `feColorMatrixFilter` to correct colors on Firefox. However, this attribute makes Firefox incorrectly render color transforms with an additive alpha component. See the Firefox rendering of synj vs. horrid 1 here:
![image](https://user-images.githubusercontent.com/36278/63549982-78d11000-c4e6-11e9-8273-da1dc587639b.png)

Correct Chrome rendering:
![image](https://user-images.githubusercontent.com/36278/63549988-7d95c400-c4e6-11e9-9655-b25122dc9227.png)

This seems to be some Firefox issue involving filters doing sRGB interpolation and possibly converting to/from premultiplied alpha? The zero alpha pixels end up having alpha and color. This also occurs when I tried the `feComponentTransfer` filter instead. The issue goes away if you remove `color-interpolation-filters`, but then the colors aren't correct.

**Comment by Herschel** [comment]
022a074 is a hack to avoid this issue at the cost of not 100% accurate rendering of additive alpha on Firefox.

**Comment by Herschel** [comment]
I think this is [Firefox bug #1421537](https://bugzilla.mozilla.org/show_bug.cgi?id=1421537).

**Comment by Herschel** [comment]
Still happens in Firefox 69.

**Comment by torokati44** [comment]
On Firefox 83.0, I get this, which looks about right:
![image](https://user-images.githubusercontent.com/288816/101270286-ece50500-3777-11eb-9b5e-32ac5008b979.png)
I also can't reproduce the linked Firefox bug #1450262.

**Comment by torokati44** [comment]
Even after setting `use_color_transform_hack` to `false`, and disabling WebGL, I still don't see any weird colors in synj1.swf in Firefox.

**Comment by Herschel** [comment]
Yep, seems like this has been fixed so I'll remove this hack. I'm guessing this was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1618345.

**Comment by Herschel** [comment]
Removed this Firefox-specific hack in #7029, not an issue anymore.
