### ISSUE TITLE
Choppy sound when SoundStreamBlock isn't in every frame

### ISSUE THREAD

**Issue by desuwa** [ruffle-rs/ruffle#3817]
FFmpeg sometimes generates swf files without a SoundStreamBlock tag in each frame. This causes Ruffle to constantly interrupt the audio stream.

Commenting out the lines below fixes the issue but I'm not sure what side effects it'll have elsewhere. It looks like it's safe to remove though.

https://github.com/ruffle-rs/ruffle/blob/f96a41403697d362aa051d0977873489269300b3/core/src/display_object/movie_clip.rs#L1087-L1090

Also, I wonder if stopping the stream like this doesn't cut off the audio too early sometimes just before the stream ends (previous frame data is still playing but the next frame doesn't have a SoundStreamBlock tag).

test swf: 
[sound_stream_block.zip](https://github.com/ruffle-rs/ruffle/files/6215647/sound_stream_block.zip)
looks like this mostly happens with high fps videos (60fps here).

**Comment by torokati44** [comment]
Haven't investigated this SWF, but deleting those 3 lines also fixes the choppy audio in https://z0r.de/7645

**Comment by torokati44** [comment]
I think you can go ahead and submit a PR for this, given how there is a `(?)` in the comment for those lines, so the author must not have been that confident about it having to be there; and deleting them makes some content better.
You can even do this from the web interface of GitHub!

**Comment by desuwa** [comment]
Turns out removing those lines would break things as explained here https://github.com/ruffle-rs/ruffle/pull/3819#issuecomment-816091845 but isn't this happening because Ruffle doesn't care about gaps in SoundStreamBlocks and will play all the samples in sequence regardless of where they are on the timeline?
Is it not possible to buffer in data only when a SoundStreamBlock is encountered in a frame? Seems like this way there will be no need to care about gaps at all.
