### ISSUE TITLE
Generating individual projectors (exe) of any swf game in the executable of the Windows desktop.

### ISSUE THREAD

**Issue by dmazinger1** [ruffle-rs/ruffle#3826]
Please. Enter in the executable of the Windows desktop, the possibility of generating individual projectors (exe) of any swf game.

Thank you very much in advance.

**Comment by Poopooracoocoo** [comment]
also see #3593 and #2279

**Comment by ousia** [comment]
Aren’t the latter issues duplicates from the first one?

**Comment by Poopooracoocoo** [comment]
ah yeah they are. wasn't sure if they were the same or just similar :)
