### ISSUE TITLE
Roadmap Update?

### ISSUE THREAD

**Issue by vbhayden** [ruffle-rs/ruffle#383]
Morning team,

Stumbled across this effort a few weeks ago and am pretty impressed with it.  Flash deprecation across the web presents a significant challenge to both public and private sectors, so it'd be great if Ruffle can help relieve some of folks' mitigation / conversion concerns.

For the **[Project Roadmap](https://github.com/ruffle-rs/ruffle/wiki/Roadmap)**, is there an updated or more granular version available?  The last update was in August of 2019, so many of those efforts have passed their estimated durations.  

Thanks!

**Comment by Herschel** [comment]
@pocketonion was kind enough to update the roadmap -- how does it look now? Is there any specific info that is missing?

**Comment by vbhayden** [comment]
Looks good, thanks guys!
