### ISSUE TITLE
AVM1, removeMovieClip should delete ALL props from target

### ISSUE THREAD

**Issue by eXponenta** [ruffle-rs/ruffle#3839]
Hi, i'm from AwayFL and we fix similar bug in our runtime.
I spent a lot of time to figure out why this was happened, and found one of source.

**Describe the bug**
`removeMovieClip` should destroy MC with deleting all properties from target.
`toString` after this should return empty string

**Example**
```
var mc = this.createEmptyMovieClip("test", 20);
trace('create mc:' + mc); // => 'create mc: _level0.test'
mc.filed = true;
trace('assign field:' +mc.filed); // => true
mc.removeMovieClip();
trace('remove mc:' + mc); // => ''
trace('read field:' + mc.field); // => read field:undefined
mc.filed = true;
trace('assign field again:' +mc.filed); // => assign field again:undefined
```

**Expected behavior**
All properties return 'undefined' when try to read it and assignments not update it.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Ruffle demo site

**Why this is so important?**
To many games use a this behaviour for track a livetime of MC . They store a MSc or their containers in array and check a fields like `active` from MC in `update` loop, then `splice` MCs that is invalid.

(code from real game, i can't share game)
![image](https://user-images.githubusercontent.com/12572222/112811604-e959ee80-9084-11eb-8165-e1276250ada3.png)
![image](https://user-images.githubusercontent.com/12572222/112811757-0c849e00-9085-11eb-86a1-631178ad639e.png)

[removeMovieClipTest.zip](https://github.com/ruffle-rs/ruffle/files/6220381/removeMovieClipTest.zip)

**Comment by adrian17** [comment]
(for the record, known in several issues like https://github.com/ruffle-rs/ruffle/issues/993#issuecomment-675182938, just wasn't explicitly reported before)
