### ISSUE TITLE
wrong pixel format in Windows binary

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#384]
I’m afraid I get the following error when I try to use [ruffle for Windows](https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/windows/ruffle_windows_latest.zip):

 ```
>ruffle.exe free_culture.swf
Fatal error:
Couldn't find any pixel format that matches the criteria.
```

It happened every time I wanted to use it.

**Comment by Herschel** [comment]
Could you provide more info about your system (OS, video card, etc.?)

We should improve our window creation to choose the the closest pixel format that matches (can I even enumerate these with glutin?), and/or allow specifying from the command line or config. My guess is that the current issue is trying to use 4xMSAA or an sRGB surface.

If you'd like, you can try commenting out desktop/src/main.rs line 55 (`.with_multisampling(4)`) or line 56 (`.with_srgb(true)`) and see if it solves the issue.

**Comment by ousia** [comment]
It’s an old computer at work (otherwise I don’t have access to other than Linux 😎), running Win7.

Is any way that I can have a portable environment (no installation or admin rights required) to compile ruffle?

**Comment by adrian17** [comment]
For the record, I'm getting a similar error on a VirtualBox Linux guest with limited graphics acceleration.

```
libEGL warning: DRI2: failed to authenticate
Fatal error:
Received multiple errors. Errors: `[NoAvailablePixelFormat, NoAvailablePixelFormat]`
```

I can actually solve it by commenting out this line:

https://github.com/ruffle-rs/ruffle/blob/cd94486f7ef0df0869b3bf66cf9c075950392fc4/desktop/src/main.rs#L55

Although that may or may not be related at all.

**Comment by ousia** [comment]
@Herschel, I’m afraid I’m not able to compile _Ruffle_ myself.

Would it be possible to provide a _Windows_ binary not compiled with `.with_multisampling(4) `?

From what @adrian17 reports, this seems to be a probable source for issues.

BTW, I tested _Ruffle_ on another _Windows 10_ computer and I got the same problem.

**Comment by ousia** [comment]
Closing the issue myself, as this computer seems not to have hardware-accelerated graphics.
