### ISSUE TITLE
Key and me level 8

### ISSUE THREAD

**Issue by KaneRex41** [ruffle-rs/ruffle#3852]
**Describe the bug**
you have to light all the circles in the ball but clicking on the ball only lights up one circle no matter where

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Don't know i was playing on cool math games

**What platform are you using?**
os: windows 10
Web browser: chrome

**Comment by n0samu** [comment]
Oh, and this was a duplicate of #3558 as well.
