### ISSUE TITLE
Error on https://www.juegosjuegos.com/embed/papas-bakeria

### ISSUE THREAD

**Issue by evamary127** [ruffle-rs/ruffle#3855]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): unknown section code #0x87 @+18525
Error stack:
```
CompileError: WebAssembly.instantiate(): unknown section code #0x87 @+18525
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.juegosjuegos.com/embed/papas-bakeria

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by adrian17** [comment]
Hello,
Unfortunately, this issue turns out to be entirely on juegosjuegos.com 's side. (they appear to have corrupted Ruffle's files while trying to upload it to their servers)
Please contact the site's admins about this instead, for example on https://www.juegosjuegos.com/contact .
