### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by BustlingLi** [ruffle-rs/ruffle#3863]
错误
全部清除
错误
Uncaught TypeError: Cannot read property 'id' of null

(()=>{var e={495:e=>{e.exports={getI18nString:function(e){return chrome&&chrome.i18n&&chrome.i18n.getMessage?chrome.i18n.getMessage(e):browser&&browser.i18n&&browser.i18n.getMessage?browser.i18n.getMessage(e):void console.error("Can't get i18n message: "+e)},setSyncStorage:function(e){chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.set?chrome.storage.sync.set(e):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.set?browser.storage.sync.set(e):console.error("Can't set settings.")},getSyncStorage:function(e,r){let o;o="string"==typeof e?[e]:Array.isArray(e)?e:Object.keys(e);let n=e=>{for(const r of o)void 0===e[r]&&(e[r]=t[r]);return r(e)};chrome&&chrome.storage&&chrome.storage.sync&&chrome.storage.sync.get?chrome.storage.sync.get(e,n):browser&&browser.storage&&browser.storage.sync&&browser.storage.sync.get?browser.storage.sync.get(e,n):console.error("Couldn't read setting: "+e)},reloadTab:function(e,t){chrome&&chrome.tabs&&chrome.tabs.reload?chrome.tabs.reload(e,t):browser&&browser.tabs&&browser.tabs.reload?browser.tabs.reload(e,t):console.error("Couldn't reload tab.")},dictEquality:function(e,t){let r=!0;for(var o in e)Object.prototype.hasOwnProperty.call(e,o)&&(r=r&&e[o]===t[o]);for(let o in t)Object.prototype.hasOwnProperty.call(t,o)&&(r=r&&e[o]===t[o]);return r},tabQuery:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.query?browser.tabs.query.apply(this,arguments):new Promise((function(t){let r=Array.prototype.slice.call(e);r.push(t),chrome.tabs.query.apply(this,r)}))},tabSendmessage:function(){let e=arguments;return window.browser&&browser.tabs&&browser.tabs.sendMessage?browser.tabs.sendMessage.apply(this,arguments):new Promise((function(t,r){let o=Array.prototype.slice.call(e);o.push((function(e){void 0!==chrome.runtime.lastError&&r(chrome.runtime.lastError.message),t(e)})),chrome.tabs.sendMessage.apply(this,o)}))},addStorageChangeListener:function(e){chrome&&chrome.storage&&chrome.storage.onChanged&&chrome.storage.onChanged.addListener?chrome.storage.onChanged.addListener(e):browser&&browser.storage&&browser.storage.onChanged&&browser.storage.onChanged.addListener?browser.storage.onChanged.addListener(e):console.error("Couldn't add setting change listener")},openSettingsPage:function(){chrome&&chrome.tabs&&chrome.tabs.create?chrome.tabs.create({url:"/settings.html"}):browser&&browser.runtime&&browser.runtime.openOptionsPage?browser.runtime.openOptionsPage():console.error("Can't open settings page")},setMessageListener:function(e){chrome&&chrome.runtime&&chrome.runtime.onMessage&&chrome.runtime.onMessage.addListener?chrome.runtime.onMessage.addListener(e):browser&&browser.runtime&&browser.runtime.onMessage&&browser.runtime.onMessage.addListener?browser.runtime.onMessage.addListener(e):console.error("Couldn't add message listener")},getExtensionUrl:function(e){return chrome&&chrome.extension&&chrome.extension.getURL?chrome.extension.getURL(e):browser&&browser.runtime&&browser.runtime.getURL?browser.runtime.getURL(e):void console.error("Couldn't get extension URL")},camelize:function(e){return e.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g,((e,t)=>t.toUpperCase()))}};const t={ruffleEnable:!0,ignoreOptout:!1}}},t={};function r(o){var n=t[o];if(void 0!==n)return n.exports;var s=t[o]={exports:{}};return e[o](s,s.exports,r),s.exports}(()=>{const{getI18nString:e,setSyncStorage:t,getSyncStorage:o,addStorageChangeListener:n,reloadTab:s,dictEquality:a,tabQuery:i,tabSendmessage:c,openSettingsPage:g,camelize:d}=r(495);let u,l,b={},m={};function h(){let e=!a(b,m);void 0!==u&&(u.disabled=!e)}function w(r){let s=r.name;r.nextSibling.textContent=e("settings_"+s),s=d(s),o(s,(function(e){r.checked=e[s],b[s]=e[s],h()})),n((function(e){Object.prototype.hasOwnProperty.call(e,s)&&(r.checked=e[s].newValue,b[s]=e[s].newValue,h())})),r.addEventListener("click",(function(){let e={};e[s]=r.checked,b[s]=e[s],h(),t(e)}))}async function y(){let t=document.getElementById("ruffle_status");t.textContent=e("status_init");let r=null;try{if(r=await i({currentWindow:!0,active:!0}),r.length<1)return void(t.textContent=e("status_no_tabs"));r.length>1&&console.warn("Got "+r.length+" tabs in response to active tab query")}catch(r){throw t.textContent=e("status_tabs_error"),r}try{l=r[0],t.textContent=e("status_message_init");let o=await c(l.id,{action:"get_page_options"});m=o.tabSettings,h(),void 0!==o&&o.loaded?t.textContent=e("status_result_running"):void 0===o||o.loaded?t.textContent=e("status_result_error"):m.ruffleEnable?t.textContent=e("status_result_optout"):t.textContent=e("status_result_disabled")}catch(r){throw t.textContent=e("status_result_protected"),u&&(u.disabled=!0),r}}document.addEventListener("DOMContentLoaded",(function(){var t,r=document.getElementById("settingsbutton");w(document.getElementById("ruffle_enable")),w(document.getElementById("ignore_optout")),(t=document.getElementById("reload")).textContent=e("action_"+t.id),t.disabled=!0,t.addEventListener("click",(function(){s(l.id,(function(){window.setInterval(y,1e3)}))})),u=t,r.innerHTML=e("open_settings_page"),r.onclick=g,y()}))})()})();
上下文 settings.html
堆叠追踪
dist/main.js:1 (匿名函数)
Ruffle 0.1.0
将 Flash 重新带回网络。

权限 选项 Reload (Ctrl+R)  
错误
ID: lihlcpkdojeefdnbjgpocmajgolkfjoi
加载来源： F:\Program Files\ruffle_nightly
 
 
 
警告：360极速浏览器无法阻止扩展程序记录您的浏览记录。要在隐身模式下停用此扩展程序，请取消选中此选项。

**Comment by Poopooracoocoo** [comment]
this is so hard to read oml

try using chrome instead. 360 Secure Browser must be based on an old version of Chromium
