### ISSUE TITLE
Streets of Fire - Odd missing collision

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#387]
https://www.newgrounds.com/portal/view/225944

This game is really close to work as it does with the Flash plugin.

However, when playing, you will notice the character cannot jump to the right middle floor (while this is possible for the left one). If you reach the right middle floor from the top floor, the collision will occur as expected.

**Comment by Herschel** [comment]
Seems to be an incorrect bounding box size/precision issue on the middle right platform. If I move the platform downward a few pixels, I'm able to jump on it successfully. The platforms are made with the line tool, so perhaps need to check we are including line width when calculating hitTest bounds (edge bounds vs. shape bounds).

**Comment by Herschel** [comment]
Actually looks like this is because of #193 -- the player jumps slightly higher in the official Flash Player because the position gets clamped to twips.
