### ISSUE TITLE
Build a user script to run Ruffle anywhere

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ruffle-rs/ruffle#3895]
It would be awesome if you write a user script to allow user to load and run Ruffle from ruffle.rs, anyone who installed browser extensions as Greasemonkey, Tampermonkey and so on would be allowed to run the latest version of Ruffle on every website, and help you to debug.

**Comment by relrelb** [comment]
You might find the [browser extension](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#browser-extension) useful. If not, can you please clarify what you look for?
