### ISSUE TITLE
Add Playback Controls on Context menu

### ISSUE THREAD

**Issue by achmadsutardi441953** [ruffle-rs/ruffle#3915]
In Real flash Player Context menu with playback Controls
![screenshot_b](https://user-images.githubusercontent.com/30205044/113862507-ae696080-97d2-11eb-998e-44f81b12c289.jpg)

in Ruffle Flash player Emulator Context Menu Without playback Controls
![image](https://user-images.githubusercontent.com/30205044/113862686-ef617500-97d2-11eb-94a6-68e737423b6d.png)
Why have forgot add Playback controls Play/Pause, Rewind, Forward, Back, etc... menus?

**Comment by achmadsutardi441953** [comment]
> In Real flash Player Context menu with playback Controls
> ![screenshot_b](https://user-images.githubusercontent.com/30205044/113862507-ae696080-97d2-11eb-998e-44f81b12c289.jpg)
> 
> in Ruffle Flash player Emulator Context Menu Without playback Controls
> ![image](https://user-images.githubusercontent.com/30205044/113862686-ef617500-97d2-11eb-94a6-68e737423b6d.png)
> Why have forgot add Playback controls Play/Pause, Rewind, Forward, Back, etc.. menus?

**Comment by achmadsutardi441953** [comment]
In Real flash Player Context menu with playback Controls
![screenshot_b](https://user-images.githubusercontent.com/30205044/113862507-ae696080-97d2-11eb-998e-44f81b12c289.jpg)

in Ruffle Flash player Emulator Context Menu Without playback Controls
![image](https://user-images.githubusercontent.com/30205044/113862686-ef617500-97d2-11eb-94a6-68e737423b6d.png)
Why have forgot add Playback controls Play/Pause, Rewind, Forward, Back, etc... menus?.

**Comment by relrelb** [comment]
Closing in favor of #488.
