### ISSUE TITLE
Kodachrome - Looping Sound

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#3916]
https://www.newgrounds.com/portal/view/600078

Playing Kodachrome in Chrome on Win 10 with Ruffle, there is a persistent looping sound that starts at the very beginning of the game and it doesn't exist when playing in a traditional Flash player.

**Comment by Toad06** [comment]
Ruffle continuously runs the `type()` function in `\DefineSprite (503: wise)\frame 1\DoAction` but Flash never runs it. The same thing also happens in `\DefineSprite (240: msg)\frame 1\DoAction`. So Ruffle loops two instances of the text sound effect while Flash plays none.

The `type()` function in `\DefineSprite (516: prostitute_balls)\frame 1\DoAction` runs when the text is displayed on screen. This works correctly in Flash and Ruffle.

In the "frames" tab, removing `RemoveObject2 Depth: 21` (msg) and `RemoveObject2 Depth: 206` (wise) from the frame 3 makes the game work the same in Flash and Ruffle (with the same audio issues). Not completely sure but I'd say this is related to #3839 and #993.
