### ISSUE TITLE
Ruffle Error on https://www.princesadosjogos.com/barbie-rapunzel.html

### ISSUE THREAD

**Issue by LihKth** [ruffle-rs/ruffle#3918]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.princesadosjogos.com/barbie-rapunzel.html

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Lord-McSweeney** [comment]
Looks like this works fine now.
