### ISSUE TITLE
Error on https://artsymedia.github.io/

### ISSUE THREAD

**Issue by ArtsyMedia** [ruffle-rs/ruffle#3920]
# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'

# Player Info
Allows script access: false

# Page Info
Page URL: https://artsymedia.github.io/

# Browser Info
Useragent: Mozilla/5.0 (iPad; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
OS: iPad

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-07
Channel: nightly
Built: 2021-04-07T00:42:04.218Z
Commit: 1020aa84d6f9fb4be215411a5517cc49721c8a3a

**Comment by adrian17** [comment]
From what I can see, you're not hosting the .wasm file at all, the request 404s and it's not at https://github.com/ArtsyMedia/artsymedia.github.io at all.
