### ISSUE TITLE
Xml.sendAndLoad not working

### ISSUE THREAD

**Issue by AnaLuciaOliveira** [ruffle-rs/ruffle#3942]
Does Ruffle support “Xml.sendAndLoad”?

My code is:
```
var post:XML = new XML();
post.ignoreWhite = true;
var node:XMLNode = post.createElement("root");
post.appendChild(node);

var resp:XML = new XML();
resp.ignoreWhite = true;

var listener:Object = new Object();
listener.load = function(event:Object) {		
	//my_code
}
resp.addEventListener("load", listener);
post.sendAndLoad("rpc/key/", resp);

```
The “rpc/key” must invoke the rpc/key/key.py in the remote server.

This code works successfully in with Adobe Flash Player. I confirm this seeing the syslog message.

When execute my code in Ruffle, the server does not receive the call (in this case, I don’t see any related message in syslog).

**Comment by relrelb** [comment]
`XML.sendAndLoad` is currently unimplemented (#286).

**Comment by AnaLuciaOliveira** [comment]
Is there plan/date to implement this method?
