### ISSUE TITLE
Mini-Putt 2 - Audio does not start automatically

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#395]
https://www.newgrounds.com/portal/view/38598/

Flash : Music is played after you click "Practice" at the title screen.
Ruffle : Music does not start automatically - it can be played by clicking the icon at the top left corner though.

**Comment by Herschel** [comment]
This is because the "music" variable is initially set to "on" by the "Music" text box on the main title screen using a text field variable. Text field variables are not implemented yet (cc #315), so the variable starts off as undefined in Ruffle.

**Comment by Herschel** [comment]
Fixed by #759.
