### ISSUE TITLE
Nightly 2021-04-13 preview Windows version renders Shift 3 upside-down

### ISSUE THREAD

**Issue by Grossley** [ruffle-rs/ruffle#3993]
**Describe the bug**
Nightly 2021-04-13 preview Windows version renders Shift 3 upside-down (visual only, as the objects seem to remain in their proper places hitbox-wise), while the browser version does not do so.

Link to the game: https://cache.armorgames.com/files/games/shift-3-1846.swf?v=1373587520

Screenshot below: 
<img width="376" alt="Capture" src="https://user-images.githubusercontent.com/42724744/114612076-848ebe80-9c56-11eb-91c6-a1bb4a21cef4.PNG">

**Expected behavior**

The game to render properly right-side up, with the hitboxes that are interactable with the mouse also being right-side up.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

Ruffle desktop app for Windows.

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 
Windows 10

**Comment by torokati44** [comment]
Possible duplicates: https://github.com/ruffle-rs/ruffle/issues/3589, https://github.com/ruffle-rs/ruffle/issues/3038, https://github.com/ruffle-rs/ruffle/issues/2419

**Comment by torokati44** [comment]
Could also be relevant: https://github.com/gfx-rs/wgpu-rs/issues/518

**Comment by Grossley** [comment]
When the program is run from the command line as ``ruffle.exe --graphics vulkan -- shift-3-1846.swf`` it renders upside down, other graphics methods of running, such as ``ruffle.exe --graphics dx11 -- shift-3-1846.swf`` and ``ruffle.exe --graphics dx12 -- shift-3-1846.swf`` do not render the game upside down.

**Comment by torokati44** [comment]
As mentioned in https://github.com/gfx-rs/wgpu-rs/issues/518#issuecomment-676668445, this could be because of the `KHR_MAINTENANCE1` extension missing, as that added this:
 
> Allow negative height to be specified in the VkViewport::height field to perform y-inversion of the clip-space to framebuffer-space transform. This allows apps to avoid having to use gl_Position.y = -gl_Position.y in shaders also targeting other APIs.

( https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_maintenance1.html )

And a fix for a similar issue was: https://github.com/gfx-rs/wgpu-rs/pull/594/commits/c4d7ce146f5b242542674d00244df7b40d761bbe

**Comment by Grossley** [comment]
Updating my drivers, including the gpu graphics drivers for my computer, seems to have resolved the issue.
