### ISSUE TITLE
Error on http://abobosbigadventure.com/fullgame.php

### ISSUE THREAD

**Issue by Bruno-Noobador** [ruffle-rs/ruffle#4002]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32390
    at r (<anonymous>:3:32880)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://abobosbigadventure.com/fullgame.php

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-03-03
Channel: nightly
Built: 2021-03-03T00:17:40.233Z
Commit: 48baf6f76bd1929daebb573969e879379e117b3f

**Comment by danielhjacobs** [comment]
This issue seems to be resolved. It's likely the CSP blocked `unsafe-eval` back when we used that, but we now use `wasm-unsafe-eval` which is not blocked.
