### ISSUE TITLE
Sound duration and position works differently in Ruffle (AS2)

### ISSUE THREAD

**Issue by ChaseWaylon** [ruffle-rs/ruffle#4010]
```var mysound = new Sound()```
Now checking ```mysound.duration``` shows 'undefined' in Flash player and in Ruffle it shows '0'
```mysound.attachSound("somesound")```
With the wav sound file I tested Flash shows ```mysound.duration``` equal to 1080, Ruffle shows it equal to 1079.
```mysound.start()```
After sound is finished playing, ```mysound.position``` in Flash is 1080, in Ruffle it shows 0.
That's why checking if sound has finished playing before playing it again doesn't work in some old code with Ruffle:
```if (mysound.duration == mysound.position) { mysound.start(); }```

P. S.
Also if I do ```stopAllSouds()``` in a middle of playing sound, it's position stays where it was at that moment in Flash, in Ruffle it resets to 0.

**Comment by ousia** [comment]
@ChaseWaylon, according to #340, `Sound.position()` isn’t implemented yet.
