### ISSUE TITLE
Support for LZMA compressed SWFs is not enabled.

### ISSUE THREAD

**Issue by ohze-thanhpv** [ruffle-rs/ruffle#405]
```
panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported("Support for LZMA compressed SWFs is not enabled.")', src/libcore/result.rs:1188:5
```
Error log when I test my own SWFs.

**Comment by Herschel** [comment]
LZMA support is disabled by default currently. You can enable it on the desktop build for testing via:
`cargo run --features=lzma`.

**Comment by ohze-thanhpv** [comment]
How can I enable features LZMA for web version?

**Comment by Herschel** [comment]
Not supported on web currently; research is needed for a pure Rust implementation of LZMA to allow easy compilation to wasm. https://github.com/gendx/lzma-rs looks like a good possibility, but it doesn't yet support streaming.

**Comment by Hydroper** [comment]
Which part of the API streams LZMA?

**Comment by plaes** [comment]
> LZMA support is disabled by default currently. You can enable it on the desktop build for testing via:
> `cargo run --features=lzma`.

Would it be possible to enable lzma feature for nightlies?

**Comment by GreenReaper** [comment]
> https://github.com/gendx/lzma-rs looks like a good possibility, but it doesn't yet support streaming.

I asked them to review another developer's pull request for this and it has now been merged - is that enough?
