### ISSUE TITLE
Watermark doesn't unroll completely in aBowman gadgets

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#4051]
**Describe the bug**
Some gadgets at abowman.com such as [this one](https://cdn.abowman.com/widgets/fish/fish.swf) contain a watermark that unrolls when hovered over. When played in Ruffle, the "N" gets cut off.

**Expected behavior**
The watermark is supposed to fully unroll while hovering.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension

**What platform are you using?**
Firefox Developer Edition on Windows 10

**Comment by Herschel** [comment]
Fixed by #6460.
