### ISSUE TITLE
Broken collision on https://www.y8.com/games/crazy_koala

### ISSUE THREAD

**Issue by thatsprettygood** [ruffle-rs/ruffle#4064]
**Describe the bug**
Collision is broken on level 2, making it impossible to beat.
**Expected behavior**
Collision is fine and the level can be beaten.
**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Desktop
**What platform are you using?**
OS: Windows 10

**Comment by starblinky** [comment]
Issue is with HitTest when checking for hittest on a point. 
`if(mc_wall.hitTest(mc_hero.__x,mc_hero._y+1, true)){`

It can occasionally return true even if it isn't hitting anything. I found that it thought it was hitting other parts of the level that was no where near the x/y coordinates. If you smooth out the graphics as much as you can, it will vastly improve this issue although won't fix it entirely. Or if you erase chunks of the level/wall to find what parts it thinks it's hitting.

**Comment by Herschel** [comment]
Seems like this is actually another case of #5492, where the ground on level1 is still hitTested even on level2. Both clips have the instance name `ground`, but the variable isn't reset when the old one is destroyed and the new one is created.

**Comment by relrelb** [comment]
This was fixed by #9447, so closing.
