### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/622078

### ISSUE THREAD

**Issue by wallac7** [ruffle-rs/ruffle#4094]
This game does not play correctly when emulated in ruffle. normally you would right click to get the play button to show up but since this is used for ruffle to enter fullscreen or get info on it, this creates issues. Thus the game cannot be started. Please find a way to fix this.

**Comment by adrian17** [comment]
Fixed with https://github.com/ruffle-rs/ruffle/pull/4141 .
