### ISSUE TITLE
Meat Boy on NG has much slower performance lately than previous builds

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#4101]
**Describe the bug**
https://www.newgrounds.com/portal/view/463241 is slowwww

**Expected behavior**
Smooth performance. It used to be great

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
Firefox 88 and Chrome 90 on Windows 10 20H2.
Ruffle nightly 2021-04-23

**Comment by relrelb** [comment]
It works fine for me with the 2021-04-24 release on Chrome. Does it still happen for you?

**Comment by Poopooracoocoo** [comment]
tried again today and strangely its working perfectly fine again? weird. maybe it was strained on memory.
