### ISSUE TITLE
Bungee Rescue - Game panicks because of CORS issue

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#411]
https://www.newgrounds.com/portal/view/372306/

Something has changed between the nightly builds of 2020-02-23 and 2020-02-25.

- On Windows, the music no longer plays in the title screen.

- On the Web build, the game no longer reaches the title screen and panicks: 
> RuntimeError: unreachable executed
> panicked at 'cannot recursively acquire mutex', src/libstd/sys/wasm/mutex.rs:22:9

For the Web build, it seems the issue occurs because the game now tries to load an ad from MochiMedia (x.mochiads.com/srv/1/ec507afa2dae464f.swf), leading to a CORS issue.

If you edit the domain in a way that prevents CORS issues, then the game will reach the title screen as expected. Note that if the file returns a 404 code, the game will continue to run but will also log the following message in the console:
> panicked at 'called `Result::unwrap()` on an `Err` value: InvalidData("Invalid SWF")', src/libcore/result.rs:1188:5

**Comment by Herschel** [comment]
When doing `mc.loadMovie("foo.swf");` on the same frame that mc is created, the original movieclip will fire its initial load clip event after the loadMovie call, which can cause the `LoadManager` to think the load has finished and to remove the load handle. When the load actually does complete, the load handle is gone and it panics.

There should be a check in `LoadManager::movie_clip_on_load` to verify that the load event is actually from the async load and the clip has actually been replaced. Could be as simple as a bool is `Loader::Movie`, or storing `Handle` in the clip itself when it gets replaced and checking for that.

**Comment by kmeisthax** [comment]
Sounds like a plan, I'll go implement that now.

**Comment by kmeisthax** [comment]
#413's merger should also close this issue
