### ISSUE TITLE
`LoaderInfo` is created anew on each access

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#4112]
`LoaderInfo` objects should be created once per SWF file, and re-used. Currently Ruffle recreates the `LoaderInfo` on each access of the `DisplayObject.loaderInfo` propety:

`trace(loaderInfo == loaderInfo); // true in Flash Player, false in Ruffle.`

Occurs on https://github.com/ruffle-rs/ruffle/commit/c422a66aa64dc25bb7313f2f305a0a3513aab17a.

**Comment by Aaron1011** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/7472
