### ISSUE TITLE
'Option::unwrap()' panic occurs intermittently in late April builds

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4116]
**Describe the bug**
![unknown](https://user-images.githubusercontent.com/75052171/115990870-98e09d00-a600-11eb-97b2-8ed0a4d97dec.png)

It seems to be from build 2021-04-24 (probably..?), but the above problem often occurs when running the file.

One peculiar thing was that I only got a black screen without the Ruffle Crash Screen, and I was able to see the error message only on console errors.
It occurs in a random flash file, and when refreshed, it works again.

I haven't found an exact reproduction point, but it seems that the problem occurs at certain timings when the file is closed (when you navigate to another page, or when the previous file is closed by opening another file).

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Identified on self-hosted.

**What platform are you using?**
 - Desktop (Windows 10 20H1)
 - Chrome (latest)
 - I also had a problem with build 2021-04-25.

**Comment by Herschel** [comment]
Thanks for the report!
Panic occurs because of unwrap added in `d34b72cc476039f68d0acf01139051c2718527e7`. Possibly the page is navigated away from and the Ruffle instance is destroyed before the metadata is loaded. We should probably get rid of most of these `unwrap`s when trying to grab an instance by ID.

**Comment by Herschel** [comment]
@Jmousy Could you try the latest builds and see if this is improved? Thank you!

**Comment by Jmousy** [comment]
@Herschel Based on my execution environment, the recent Nightly build (checked on 2021-05-05) doesn't seem to cause any more problems!

It was running well without any error messages even while going back and forth between pages with fast timing. It looks good to mark this issue as resolved.

Thanks for solving this problem!
