### ISSUE TITLE
Nothing stands in the way of your victory in 'Super Pang'.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4118]
**Describe the bug**
[Super Pang.zip](https://github.com/ruffle-rs/ruffle/files/6371812/Super.Pang.zip)
![super-pang](https://user-images.githubusercontent.com/75052171/115991757-de9f6480-a604-11eb-90e6-bac0db9c80c7.gif)

(Refer to the attached gif at the top)

'In Super Pang: The island tournament' game, bouncing balls do not appear on the stage.
Therefore, when you start the game, the game determines that all balls have been removed, and the stage is cleared.

You can immediately check the problem by pressing the space bar after starting the game.

**Expected behavior**
Bouncing balls should appear on the stage depending on the difficulty level.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Checked in self-hosted version.

**What platform are you using?**
 - Windows 10 20H1 x64
 - Google Chrome (latest)
 - Ruffle Nightly 2021-04-25

**Comment by Toad06** [comment]
This seems related to #3839, so hopefully the game will work once #5492 gets merged (this currently works when using this PR).
