### ISSUE TITLE
Caching on web causes various rendering issues

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#412]
On the web target, if you play a movie once, and then reload the page, various issues can occur with the images:
http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html?file=uniwar.swf

Correct, first run:
![image](https://user-images.githubusercontent.com/36278/75384777-6075ef80-5893-11ea-8b40-3a084dbdbe4e.png)

Incorrect, after reload:
![image](https://user-images.githubusercontent.com/36278/75384808-6bc91b00-5893-11ea-9a7f-a95f18a94fcc.png)

This has something to do with caching and may be caused by the janky way we are loading images in the web backend. (This should probably be rewritten now that we can properly use `async`).

Occurs in both Firefox and Chrome.

(originally reported in #400)

**Comment by Herschel** [comment]
@Toad06 Could you please check that this is fixed on your end too? Thanks!

**Comment by Toad06** [comment]
Thanks for the fix!

Tested using today's nightly build (2020-03-26) and all good in:

Windows:
- Firefox 74
- Chrome 80

iPadOS 13.3.1:
- Safari
- Chrome 80

Android 7.0:
- Chrome 80
