### ISSUE TITLE
At 'Dolphin Olympics', dolphins do not move after one performance.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4121]
**Describe the bug**
![dolphin](https://user-images.githubusercontent.com/75052171/115993068-03e3a100-a60c-11eb-8f5c-608525f1ff9c.gif)
(The gif shown at the top explains the problem.)

At Dolphin Olympics, keystrokes get stuck after a dolphin performs one stunt.
**After that, the dolphin does not respond to any keystrokes.**
(Dolphins are controlled with the arrow keys.)

**(How to reproduce): Press the arrow key to jump over the sea, then come back to the sea and try to press the key.**

In the developer console, the following log is output every time a key is input.
```
Object method onKeyUp is not callable
```

Also, the following console log is continuously output.
```
clearInterval: Timer 0 does not exist
```

[Dolphin Olympics.zip](https://github.com/ruffle-rs/ruffle/files/6371894/Dolphin.Olympics.zip)

**Expected behavior**
Dolphins must always be moved by keystrokes.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Checked in self-hosted version.

**What platform are you using?**
 - Windows 10 20H1 x64
 - Google Chrome (latest)
 - Ruffle Nightly 2021-04-25

**Comment by Toad06** [comment]
#4668 seems to have fixed the issue. Could you please give a try to the game to confirm it also works on your end? Thank you. 😉

**Comment by Jmousy** [comment]
I wrote it a long time ago, so I haven't been able to check it recently!
I've confirmed that the issue has been resolved as of 31 Jan 2022. thank you.
