### ISSUE TITLE
Error on https://www.bubblebox.com/game/1213/fishing-girl.htm

### ISSUE THREAD

**Issue by Emilykt24** [ruffle-rs/ruffle#4125]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:280:5

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.bubblebox.com/game/1213/fishing-girl.htm
SWF URL: https://www.bubblebox.com/swf6/1213/fishing-girl.swf?gameVersion=1

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-26
Channel: nightly
Built: 2021-04-26T00:14:53.853Z
Commit: 3e9ae40b175a671dade3f49be9369956c6bdd73c

**Comment by relrelb** [comment]
Fixed by #4422.
