### ISSUE TITLE
avm1 GetVariable doesn't resolve with scope chain with pathed variables

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#414]
Whilst investigating what's blocking MX after registerClass, it looks like Flash tries to lookup MX components with pathed variables: `GetVariable "mx.controls.listclasses.DataProvider"`

This fails because `"mx"` is defined in `_global`, not `this`.

A simple test to reproduce:
```actionscript
_global.a = {b: {c: "success"} };
trace(eval("a.b.c"));
```
This will trace `"success"` in Flash, but `undefined` in Ruffle.

Just to make things a little more interesting, it looks like scope resolution happens at every step, not just the first entry.

```actionscript
_global.a = {b: {c: "from global"} };
a = {b: "from this"};

trace(eval("a.b.c")); // "from global"
trace(eval("a.b")); // "from this"
```

**Comment by Herschel** [comment]
So `GetVariable` will try to resolve a path relative to each scope in the scope chain, falling back to the parent scope if it fails. Now the question is: does this apply to every op/function that can resolve a path, or just `GetVariable`? For example, does `CloneSprite` do the same thing? My initial tests indicate that no, other ops only resolve the path on `this`.
