### ISSUE TITLE
Error on https://ipsproarcade.com/index.php

### ISSUE THREAD

**Issue by C-Listensprechen** [ruffle-rs/ruffle#4148]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/function_object.rs:281:5

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://ipsproarcade.com/arcade/HappyEasterMahAS3v2HM.swf
Param movie: https://ipsproarcade.com/arcade/HappyEasterMahAS3v2HM.swf
Param pluginspage: http://www.macromedia.com/go/getflashplayer/
Param bgcolor: #000000
Param quality: high
Param menu: true
Param wmode: direct
Param allowScriptAccess: always
Param play: true
Param loop: true
Param hasPriority: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://ipsproarcade.com/index.php?ipsproarcade/playgame/30261-happy-easter-mahjong
SWF URL: https://ipsproarcade.com/arcade/HappyEasterMahAS3v2HM.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-15
Channel: nightly
Built: 2021-04-15T00:40:58.997Z
Commit: b2bed7a18d064232b6767cf6839c18637cb766d2

**Comment by C-Listensprechen** [comment]
Good thing I established a Github account with the last automated bug report or this report would not have been possible.

**Comment by relrelb** [comment]
Fixed by #4422.
