### ISSUE TITLE
right click menu doesn't work

### ISSUE THREAD

**Issue by gamer191** [ruffle-rs/ruffle#4153]
**Describe the bug**
In level 19 of https://www.coolmathgames.com/0-me-and-the-key you are supposed to right-click and then click "key" (according to https://www.youtube.com/watch?v=UENCxzuvL4k) however, in Ruffle that option doesn't come up when right-clicking
![Screenshot 2021-04-27 192720 - Copy](https://user-images.githubusercontent.com/83270075/116219309-cf4c2280-a78e-11eb-8738-df8745881f24.jpg)

**Expected behavior**
That "key" will come up in the right-click menu

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension

**What platform are you using?**
OS:
Edition:		Windows 10 Home
Version:		20H2
OS build:		19042.928
Experience:	Windows Feature Experience Pack 120.2212.551.0

Browser:
Firefox 88.0 (64-bit)

Device: surface pro 6

**Side note**
My touchpad setup makes it impossible to do level 15, so I skipped that level (by typing in "key" on levels 11,12,13,14&15). As such, it is entirely possible that level 15 is also broken. I did, however, do levels 12-14 separately, so I know that they work (level 11 requires you to type "key", so I wasn't skipping it)

**Comment by gamer191** [comment]
Thanks Adrian17

**Comment by rufflue** [comment]
it should also fix #4094 which looks like a similar issue
