### ISSUE TITLE
Riven Elementary

### ISSUE THREAD

**Issue by ReNardier** [ruffle-rs/ruffle#4161]
this guy https://www.riumplus.com/contact/
as he explained here(nearly 9 years ago) https://youtu.be/XN5Ht3epf1M?t=2617
got a hold of this really old game made in shockwave, but because(as he explains in the video) there is a lot of trouble getting it to run on modern browsers/flash players... he sort of has kept the game to himself on that "real myst book" of his(and i would presume another copy on a thumb-drive for safekeeping... and i presume that only because i genuinely do not know how to feel at the prospect that the only copy is on that book)
do you think you guys could get in contact with him(through the contact methods on his page that i have linked) and try to make it work in ruffle(i already made an issue on the lightspark git)... and hopefully convincing him to release it once and for all?
id really love for Riven Elementary to stop being located-but-inaccessible media(the less mysterious but equally frustrating cousin of lost media)

**Comment by n0samu** [comment]
Sorry, this has nothing to do with Ruffle - Ruffle is a Flash Player emulator, and running Shockwave content is not in scope.
