### ISSUE TITLE
Scrolling text doesn't work on Nobel Prize ECG game

### ISSUE THREAD

**Issue by hansmehlin** [ruffle-rs/ruffle#4217]
Hello!

On the Nobel Prize ECG game at
https://educationalgames.nobelprize.org/educational/medicine/ecg-ruffle/ecg.html
some text areas with scrollable text at the bottom of the screen doesn't work.
It is not possible to scroll and read the complete text.

SWF file at
https://educationalgames.nobelprize.org/educational/medicine/ecg-ruffle/ekg.swf

Original Flash version at
https://educationalgames.nobelprize.org/educational/medicine/ecg/ecg.html

Running ruffle-nightly-2021_04_29-web-selfhosted and tested of several clients.

![ecg](https://user-images.githubusercontent.com/12083993/116861914-32610d80-ac04-11eb-9c3a-0c850f516deb.jpg)

Hans

**Comment by danielhjacobs** [comment]
I'm fairly sure this is due to #1033. It's a problem on a site I maintain as well.

**Comment by achmadsutardi441953** [comment]
[Ultrasounds](http://ultrasounds.com/US.html) no have Scrollbar fix please

**Comment by sombraguerrero** [comment]
> [Ultrasounds](http://ultrasounds.com/US.html) Scrollbar Not work fix please?

Agreed. PR 4827 almost fixed the scrollbars here, but there seems to be a case where, if the length delta is not large enough, the text pane still won't move. So in this example, it works perfectly now on the Gallery page, but not on the About page.

**Comment by midgleyc** [comment]
Filed #4847 for the Ultrasounds thing. It's not related to #4827: that fixes the case where the text is assigned to a textbox after creation. In Ultrasounds, the textbox already has the text.
