### ISSUE TITLE
Texts does not appear in Nobel Prize Split brain experiments game, XML load error?

### ISSUE THREAD

**Issue by hansmehlin** [ruffle-rs/ruffle#4220]
Hello!

After the first experiment and entering the "coffee break" there are grant proposals and results shown. These are blank, no text is shown and there is no possibility to continue the game. This might be due to a problem loading the texts from an XML file. 

URL:
https://educationalgames.nobelprize.org/educational/medicine/split-brain-ruffle/splitbrainexp.html

SWF file:
https://educationalgames.nobelprize.org/educational/medicine/split-brain-ruffle/splitBrain_main.swf

Original flash page:
https://educationalgames.nobelprize.org/educational/medicine/split-brain-ruffle/splitbrainexp.html

Version: ruffle-nightly-2021_04_29-web-selfhosted.

![split-brain](https://user-images.githubusercontent.com/12083993/116874384-8aeed580-ac19-11eb-8cff-abdf9b38d613.jpg)

The same problem might be the case for the initial lecture in the PCR game
https://educationalgames.nobelprize.org/educational/chemistry/pcr-ruffle/game/index.html

**Comment by Herschel** [comment]
Thanks for the report, fixed by #4212
