### ISSUE TITLE
Link to html page does not work in Nobel Prize Prisoners of war game.

### ISSUE THREAD

**Issue by hansmehlin** [ruffle-rs/ruffle#4221]
Hello!

A little bit into the game there is a link at the top of the page to view "The Geneva Convention III". This link does not work. There is an error shown in the console when you press this button. The links at the end of the game does not work either, but that is not as important for the game as we easier can provide them outside the game. These are all external html documents that doesn't open.

URL:
https://educationalgames.nobelprize.org/educational/peace/redcross-ruffle/game.html

SWF file:
https://educationalgames.nobelprize.org/educational/peace/redcross-ruffle/pow_load.swf

Original flash page:
https://educationalgames.nobelprize.org/educational/peace/redcross/game.html

Version: ruffle-nightly-2021_04_29-web-selfhosted

![red-cross](https://user-images.githubusercontent.com/12083993/116876091-33059e00-ac1c-11eb-9be0-a3dfaf6d4685.jpg)

**Comment by adrian17** [comment]
> There is an error shown in the console when you press this button

Could you please send a screenshot of the error? For the record, I just tested this (with an extension on Firefox and Chrome) and it appears to be working:


https://user-images.githubusercontent.com/4729533/116885164-ddcf8980-ac27-11eb-8dda-fd4d0e28e83d.mp4

**Comment by hansmehlin** [comment]
Thanks. Very interesting. Below is the error I get. The last row appears when clicking on the link in Chrome 90.0.4430.93 on Windows 10 and running from https://educationalgames.nobelprize.org/educational/peace/redcross-ruffle/game.html that is the  selfhosted version.
![redcross-2](https://user-images.githubusercontent.com/12083993/116900794-702c5900-ac39-11eb-87af-fd77030d7804.jpg)

**Comment by adrian17** [comment]
It appears that the original site's HTML has the following snippet:
```js
function showconvention(url) {
    window.open(url,'geneva','scrollbars=yes');
}
```
Which is missing from the Ruffle-based website.
(note that there are more differences, like another missing function called `popUp` - I don't know if the SWF uses it though.)

**Comment by hansmehlin** [comment]
Ah. Right. I had a gut feeling the the error was on my side :-) I just couldn't find it. I will test it and confirm.

**Comment by hansmehlin** [comment]
Yep. That was the problem. Fixed now. Thanks a lot for spotting this!

**Comment by hansmehlin** [comment]
Closing this ticket. The error was on my side, not Ruffle.
