### ISSUE TITLE
Ruffle Javascript Loader not working

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#4223]
Hey,

only the polyfill works. Wonder what's the problem with the loader not working. Maybe anyone knows:

https://www.spiele-umsonst.de/ruffle/test3.php

test3.php:28 Uncaught TypeError: Cannot read property 'appendChild' of null
    at test3.php:28
(anonymous) @ test3.php:28
load (async)
(anonymous) @ test3.php:24

**Comment by adrian17** [comment]
```js
const container = document.getElementById("container");
```

There's no "container" element in your HTML.

**Comment by desertking** [comment]
Wow, stupid :) Thanks. Maybe you should update the example to "fool-proof"

**Comment by adrian17** [comment]
Might consider it, as the selfhosted API might be updated at some point anyway :)
