### ISSUE TITLE
Are flash games supported yet?

### ISSUE THREAD

**Issue by murrconn036** [ruffle-rs/ruffle#4224]
Are games on coolmathgames.com or any other game website supported, or do they use the AVM 2 format. (sorry I'm using Github, I don't have discord.) 

I am using the chrome extension on a Windows OS PC. 
[ruffle-nightly-2021_05_03-web-extension.zip](https://github.com/ruffle-rs/ruffle/files/6416463/ruffle-nightly-2021_05_03-web-extension.zip)

**Comment by Herschel** [comment]
It depends on the game in question; older games will be AVM1, but newer games will be AVM2 and show the unsupported warning.

**Comment by murrconn036** [comment]
Thanks
