### ISSUE TITLE
FR: Add general multiplayer support

### ISSUE THREAD

**Issue by poly000** [ruffle-rs/ruffle#4231]
A server should identify host and guest. Host could set keys a guest permitted to use, e.g.

The server is used to share keys entered, and the keys can be mapped (WASD to ARROW, i.e.)

This is for local multiplayer games.

**Comment by Herschel** [comment]
Thanks for the request, this is a cool idea but a little out of scope for the project at the moment. Also seems less important because software like Parsec can be used to do this. Maybe in the distant future when we are more full-featured, we could consider it.
