### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by lajbel** [ruffle-rs/ruffle#4250]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1620075578%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F592000%2F592473_MadnessGame_ULTIMATE.swf%3F1507662264%22%2C%22vars%22%3A%7B%22ngio_session_id%22%3A%2276876603.973f9c3a533906a4ec9a22b905178666b99384c11d36e5%22%2C%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226093376486965%22%2C%22NewgroundsAPI_SessionID%22%3A%2225dGmUdiceDlNXNIAT0je3a4bd42e8f0189612f755b0947a55ad62e3d409UE97%22%2C%22NewgroundsAPI_UserName%22%3A%22TereDeJugo%22%2C%22NewgroundsAPI_UserID%22%3A9008270%2C%22ng_username%22%3A%22TereDeJugo%22%7D%2C%22width%22%3A850%2C%22height%22%3A530%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F592000%2Fflash_592473_card.png%3Ff1608170534%22%7D

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-05-03
Channel: nightly
Built: 2021-05-03T00:12:09.006Z
Commit: f2256a661be22fd12ae1ec3b40574d7cca670a27

**Comment by Poopooracoocoo** [comment]
Link to Madness: Project Nexus (Classic) on Newgrounds:
https://www.newgrounds.com/portal/view/592473

**Comment by Poopooracoocoo** [comment]
@lajbel Do you still see this issue?

**Comment by lajbel** [comment]
> @lajbel Do you still see this issue?

nop 👍
