### ISSUE TITLE
Ruffle Web Player will not start

### ISSUE THREAD

**Issue by mash1570** [ruffle-rs/ruffle#4252]
Today I tried to play Super Mario Flash using the Ruffle Web Player, as it is an older game and it has worked before. 

Usually, when I open the game it sits there for a couple of seconds and then loads without a hitch. Right now though, it refuses to load. I've let it sit there for about 10 minutes, yet nothing.

I don't know if this is a problem on my end or yours, but I'm posting it here to let all of you know.

**Comment by Herschel** [comment]
Could you post/attach a link to the SWF you are trying? Thank you!

**Comment by mash1570** [comment]
It says that you don't support that file type.

Also, it started working for me again today. Not sure what the issue was.

**Comment by Poopooracoocoo** [comment]
@mash1570 You can attach SWFs to GitHub by adding the .zip suffix or by putting it in a zipped folder.
