### ISSUE TITLE
Cannot toggle words in Nobel Prize Split brain experiments game

### ISSUE THREAD

**Issue by hansmehlin** [ruffle-rs/ruffle#4253]
Hello!

A bit into the game, after the "coffee break", you are presented a text for a grant proposal. Your task is to get the words "left" and "right" correct in the text. However, there is no way to change the text. Nothing happens and since you cannot change the words, you can't get it correct. If you try to proceed anyway, the application is denied (as it should), and you cannot proceed in the game.

URL:
https://educationalgames.nobelprize.org/educational/medicine/split-brain-ruffle/splitbrainexp.html

SWF file:
https://educationalgames.nobelprize.org/educational/medicine/split-brain-ruffle/splitBrain_main.swf

Original Flash page:
https://educationalgames.nobelprize.org/educational/medicine/split-brain/splitbrainexp.html

![split-brain](https://user-images.githubusercontent.com/12083993/117316544-fbe7f480-ae88-11eb-93db-b8bc5bb69e0a.jpg)

Hans

**Comment by hansmehlin** [comment]
Version: ruffle-nightly-2021_05_05-web-selfhosted tested on several clients.

**Comment by adrian17** [comment]
I think it's because it uses `<a>` in HTML text, which Ruffle doesn't implement at all yet.

**Comment by hansmehlin** [comment]
I see it in my XML file that contain the texts. For example:
<a href="asfunction:iRoot.game1.currScene.RLFlip,1"><b>LEFT</b></a>
So this was a functionallity Flash had, that it intepreted html <a href..> and called an internal function? I guess that also means that I cannot change this XML text into something that is supported by Ruffle today?

**Comment by Herschel** [comment]
Yes, unfortunately we don't check for clicks on <a> links in text quite yet. The only solution currently would be to add separate buttons to do this in the original SWF content.

(Note to self: we also have to handle the `asfunction` protocol in the link. I believe this only works in `<a>` tags in text, but check if this works with `getURL` etc. too).
