### ISSUE TITLE
Information texts not visable in the Nobel Prize PCR game

### ISSUE THREAD

**Issue by hansmehlin** [ruffle-rs/ruffle#4254]
Hello!

A bit into the game, after you have broken the PCR machine, placed the water baths on the bench and turned on the power, you are supposed to write a title, the name of the step of the procedure, on each water bath and after that set the temperature and time for each step. However, all the feedback dialogue texts are empty from now on. Therefore you do not know what to do and you cannot continue the game. Up until this point, the texts have been working fine.

URL:
https://educationalgames.nobelprize.org/educational/chemistry/pcr-ruffle/game/index.html

SWF file:
https://educationalgames.nobelprize.org/educational/chemistry/pcr-ruffle/game/main.swf

Original Flash page:
https://educationalgames.nobelprize.org/educational/chemistry/pcr/game/index.html

Version: ruffle-nightly-2021_05_05-web-selfhosted tested in several browsers.

![pcr-2](https://user-images.githubusercontent.com/12083993/117319702-d90b0f80-ae8b-11eb-8a53-8ecb430327c4.jpg)

Hans

**Comment by adrian17** [comment]
Blocked on unimplemented `__resolve` (script used it on XMLNode).

**Comment by n0samu** [comment]
Should be fixed by #16284
