### ISSUE TITLE
successful_troll_2.swf is not nearly successful enough (colour tint missing)

### ISSUE THREAD

**Issue by CounterPillow** [ruffle-rs/ruffle#4255]
**Describe the bug**
The troll figure is missing its blue tint, which is present in flash player.

Link to the SWF file: https://fratti.ch/bugdemos/ruffle/successful_troll_2.swf

Screenshot of the issue:

![Screenshot_20210506_172448](https://user-images.githubusercontent.com/308818/117324336-fd68eb00-ae8f-11eb-913d-070b9917d8b1.png)

**Expected behavior**
It should look like this:
![Screenshot_20210506_172534](https://user-images.githubusercontent.com/308818/117324448-15d90580-ae90-11eb-9a15-50d2bbfe447d.png)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?** Desktop version

**What platform are you using?**
Linux x86_64, ruffle git master commit `b82391726` aka `0.1.0.4634`

**Comment by Herschel** [comment]
Requires ColorMatrixFilter, closing in favor of #15.
