### ISSUE TITLE
Support magic button frame labels in movie clips

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#4261]
In a MovieClip, you can place magic frame labels of `_up`, `_over` and `_down`. If the clip is in "button mode", it will automatically toggle between these frames as the mouse hovers, like a standard `Button`/`SimpleButton`.

This can be done in both AVM1 and AVM2. In AVM1, "button mode" is triggered by attaching any button event handler to the clip, such as `on(release)`. In AVM2, there is an explicit `Sprite.buttonMode` property that can be set to `true`.

Sample SWFs:
[button-clip.zip](https://github.com/ruffle-rs/ruffle/files/6438189/button-clip.zip)

**Comment by midgleyc** [comment]
I think this causes #3821.

**Comment by depPat** [comment]
Hi ! i'had a look on your button clip.... and things seem missing : script is'nt full.... Go and see this (as2 only.... I don't like/use as3 !)
[buttonClip-fix.zip](https://github.com/ruffle-rs/ruffle/files/6481071/buttonClip-fix.zip)

**Comment by Lord-McSweeney** [comment]
This is working now on both avm1 and avm2.
