### ISSUE TITLE
There should be a way in js to start (and stop) 'Play'

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#429]
web-player:
When a swf-file is handled by ruffle, it needs to be started manually by clicking on it.
There should be a way to start it from javascript (and may be stop it again).

See i.e. www.webgeo.de/k_024_en/

**Comment by Toad06** [comment]
Yes, this would be a nice feature to have in the future.

I suppose this should also consider the case of multiple files on a same page - so possibly different behaviors (eg. a file being part of a webdesign that would be autoplayed, and another file - say a game - that would require a user gesture).
There's also the rare case of 1x1 / invisible files that cannot be played currently (some sold royalty free music as .swf to be included in an html page - though it's veeeeery old now).

So giving my 2 cents, I suppose something as below would be very simple to use (and so very difficult to code? 😅) while covering all possible cases?

```
window.RufflePlayer.config = {
	autoplay: {
		"default": "value",
		"files": "value"
	}
};
```

"default" value could be one of the following string:
- "never" => the current behavior.
- "always" => this one could create issues with stuff requiring a user gesture (eg. audio), so would be at user's risk.
- "usergesture" => play all available files after a user gesture somewhere on the page (not necessarily on a Ruffle element). After the user gesture, any Ruffle element that would be appended to the DOM would act as "always". Useful in cases of 1x1 / transparent files (eg. a file that just plays music).
- "autodetect" => autoplay if Ruffle detects the file can be played safely (eg. the browser allows audio autoplay). If it fails, fallback to "usergesture".

"files" => an array of specific files that would overwrite and reverse the default behavior:
- If default is "always", files in the array would act as the "never" behavior.
- All other cases would act as the "always" behavior. This could be useful for elements that are just graphics (eg. something being part of a webdesign).

**Comment by Toad06** [comment]
I've tried implementing this though it's more a demo actually. :)
But all cases as described in my previous post work. I hope this could be useful for a future implementation.

The attached file below contains:
- "ruffle-player.js" which has been edited (you can search for "// CHANGE" in the file).
- and demo files to test the different behaviors.

[autostart-demo.zip](https://github.com/ruffle-rs/ruffle/files/4547236/autostart-demo.zip)

**Comment by Toad06** [comment]
Not the priority, but any thoughts on the overall idea and the different options? (the implementation itself is probably bad anyway lol) @Dinnerbone

**Comment by Dinnerbone** [comment]
There's a `play` method, and autoplay options now.

**Comment by KMicha** [comment]
I added the play() and pause() function to www.webgeo.de and it works as expected.
Seems to be a little bit faster this way as well.

Thank you for the great work
