### ISSUE TITLE
Pico's School not loading right

### ISSUE THREAD

**Issue by MasterAdams70** [ruffle-rs/ruffle#4343]
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.
![2021-05-16 (1)](https://user-images.githubusercontent.com/84290818/118411851-9267a300-b64b-11eb-8cb0-5445eb50f1d7.png)

**Expected behavior**
The school hallway should have loaded 
I am using the browser extension

**What platform are you using?**
  Windows 10 Home Google Chorme

**Comment by Herschel** [comment]
Hi @MasterAdams70, does this problem still occur?

**Comment by relrelb** [comment]
Closing as this no longer occurs.
