### ISSUE TITLE
Black Background on https://www.supergames.cz/online-hra/2298/combat-hero-adventures/

### ISSUE THREAD

**Issue by MSGCZ** [ruffle-rs/ruffle#4355]
Hello all, this game is function with Ruffle (2021-05-18) but when I try to play the background of the game is black.

<img src="https://www.yoom.cz/img/93imsfce_source.png" />

**Comment by Sonikkustar** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/31ba6ae7-3053-4e45-b11f-757f9bfa6aaa)

The site currently uses Ruffle (nightly 2023-11-14) which appears to have the issue fixed now.
