### ISSUE TITLE
Does ruffle not work with older GPUs?

### ISSUE THREAD

**Issue by Hui-Lui** [ruffle-rs/ruffle#4361]
I just tried the Desktop-Version of ruffle to start some old Flash-Games from my external HDD, when I start it sometimes on some games an empty transparent window appears and on others nothing happens.

The error code:

```
[2021-05-18T16:19:18Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0x0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 0x556f0aadb470)
    
[2021-05-18T16:19:18Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0x0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 0x556f0aadb470)
    
[2021-05-18T16:19:18Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
Fatal error:
Ruffle requires hardware acceleration, but no compatible graphics device was found supporting Vulkan, DirectX 12, Metal or Web GPU
Error: "Ruffle requires hardware acceleration, but no compatible graphics device was found supporting Vulkan, DirectX 12, Metal or Web GPU"
```

So, my GPU is simply too old?

My OS:
Fedora 32 64bit

My GPU:
Nvidia 8600m GT
Installed driver version: 340.108
Has no Vulkan support

Ruffle version:
Ruffle 0.1.0-nightly (30f088d 2021-05-17)

If you need any further information, I will be happy to provide it.
-----
Appended a picture of the transparent window, which appears on some games.
![ruffle_issue_01](https://user-images.githubusercontent.com/84400360/118689841-b839a700-b807-11eb-8753-780deec726b0.png)

**Comment by adrian17** [comment]
> So, my GPU is simply too old?

Currently, unfortunately yes.  This is not a fundamental issue with your GPU though, it's rather that Ruffle currently doesn't support OpenGL, which would let most older graphics cards work. It's not that we don't want to do this, it's rather issues with the tooling we happen to use. There already exists an issue for that: https://github.com/ruffle-rs/ruffle/issues/1782

**Comment by Hui-Lui** [comment]
Ah, thank you. Sorry I did not see that.
Then I will wait until ruffle will support OpenGL and try now the Browser-Extension.

I will close this issue then.
