### ISSUE TITLE
Error on https://www.x-oo.com/flash-online-games/jump-and-run/fancy-pants.html

### ISSUE THREAD

**Issue by erenaktas733** [ruffle-rs/ruffle#4376]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 662 failed.
(error: https://www.x-oo.com/cms/ruffle/core.ruffle.0197a207ce1d77ef54e9.js)
Error stack:
```
ChunkLoadError: Loading chunk 662 failed.
(error: https://www.x-oo.com/cms/ruffle/core.ruffle.0197a207ce1d77ef54e9.js)
    at Object.Si.f.j (https://www.x-oo.com/cms/ruffle/ruffle.js:1:37770)
    at https://www.x-oo.com/cms/ruffle/ruffle.js:1:36164
    at Array.reduce (<anonymous>)
    at Function.Si.e (https://www.x-oo.com/cms/ruffle/ruffle.js:1:36141)
    at o (https://www.x-oo.com/cms/ruffle/ruffle.js:1:2657)
    at o.next (<anonymous>)
    at https://www.x-oo.com/cms/ruffle/ruffle.js:1:2957
    at new Promise (<anonymous>)
    at https://www.x-oo.com/cms/ruffle/ruffle.js:1:2693
    at o (https://www.x-oo.com/cms/ruffle/ruffle.js:1:2980)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: upload/Onlinespiele/fancypantsadventures.swf
Param src: upload/Onlinespiele/fancypantsadventures.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.x-oo.com/flash-online-games/jump-and-run/fancy-pants.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T01:09:33.302Z
Commit: 9df7facdb8d37a5d007a13c25efcc176ed4675e0

**Comment by Sonikkustar** [comment]
Game works fine now:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/b28f4102-189a-4658-8533-eac14efe53ff)

Site now uses a 2023 build of ruffle. I'm not sure what initially triggered this but it's probably good to say that it's been fixed now.
