### ISSUE TITLE
thousands of "unable to lock ruffle core"

### ISSUE THREAD

**Issue by Elementtair** [ruffle-rs/ruffle#4392]
I run into this issue with that file ( Not sure but I think it's avm1):

[file.zip](https://github.com/ruffle-rs/ruffle/files/6526447/file.zip)

This swf is supposed to show a text manual.

works fine with adoble flash but neither with the latest selfhosted (22.05.2021):
Doesn't load, nor give Ruffle error. It give this in firefoxX64 console :
![error](https://user-images.githubusercontent.com/75228621/119227832-2d5ef200-bb10-11eb-88e7-e2a9b94dc806.JPG)

Nor with a ruffle.exe I have on my W10 64 pro (it s an old version from 05.02.2021) it just crash the player displaying nothing.

Just tried with actual Ruffle Windows X64, it just take a little longer to crash, but it does, displaying nothing, no file no error.

**Comment by sombraguerrero** [comment]
This works fine for me using 5/23 self-host and desktop builds. Perhaps we need to inspect your environment. Do you have the entire self-host package in the same folder that references ruffle,.js? Also, what type of graphics card does your computer have and do you have any trouble running WebGL content? Feel free to come into the Discord chat for help with these types of things.

**Comment by Elementtair** [comment]
Didn't think to try with another computer...
First one is a 3630QM, 12 Go RAM, HD4000 IGC, W10 x64

Tried with other one I5 3470, 8Go RAM, RX460 GC, W10x64
So it work fine with the desktop build 5/23 on the second computer but still make same error with selfhosted (that I updated to 5/23 too)

Tried with chrome and works well on both computer, only issue is with firefox latest x64

I have around 800 flash files on the server and this is the first one I have this kind of trouble with.

Made a direct link to try the selfhosted: https://www.mercedes-anciennes.fr/forummb/test.php

Edit: it just worked on the first computer with selfhosted, didn't touch anything...
the only message on console was this:
![error2](https://user-images.githubusercontent.com/75228621/119716883-ec474480-be65-11eb-9aa0-3a2c214f0159.JPG)

Still not workink with lot of "unable to lock ruffle core" on the second computer with firefox.
not working with desktop build on the first (selfhosted seems to intermitently work... )

I'm kind of lost for now. Both computers works perfectly fine with up to date system and drivers.

**Comment by sombraguerrero** [comment]
Your self-host test continues to work for me in both FF and Chrome. Your console output supports my suspicions, that both your computers do not support advanced graphical backends. You are likely falling back to the canvas backend, which is likely crashing core due to how large this file is.
Try to go to this page: [WebGL Test](https://get.webgl.org/)
If your computers don't pass this test, that is likely your culprit.

**Comment by Elementtair** [comment]
Both computer passes this test.

The first computer who was failling first on self hosted, then worked giving the latest console error,  today again displays nothing with "unable to lock rufle core errors" in firefox.

I have around 800 files of that type on the server, some are easily twice bigger than this one without any issue.

Still displaying correctly with chrome. 
Also, the file display perfectly fine with flash player.

**Comment by sombraguerrero** [comment]
You may want to come into the Discord chat if you want further help with this. As this is clearly environmental, I don't think continuing to troubleshoot from this issue is productive.

**Comment by Elementtair** [comment]
I don't really understand how you threat that by calling a bug "environmental".

As it's only one file on 800, it's not really a bother to me. I'll just wait for a fix... or not.

**Comment by adrian17** [comment]
I see this explode in memory use on both FF and on desktop version, on my 8GB machine; will keep it open for this.

(also some `unknown tag code 40` - jpexs sees the bad tag 777 but not tag 40, so there might be something with swf parsing...? Or just extremely inefficient asset loading.)

**Comment by sombraguerrero** [comment]
My desktop is somewhat oversaturated with RAM, which is all I really meant when I called the bug environmental. I would suspect an asset loading problem. If it were parsing, I wouldn't think it would work at all.

**Comment by adrian17** [comment]
Tag 40 is a non-issue I think, at least not relevant.

From what I can see, it just unpacks/decompresses all the images in the SWF - like, it unpacks a 100kB compressed 8-bit bitmap into a 35MB 32-bit bitmap - and keeps it in RAM after loading into VRAM, in case it's ever needed by `BitmapData.loadBitmap` - so no surprise it explodes.

The solution would probably be to lazify `BitmapData.loadBitmap` I guess? I wonder if Flash decodes this stuff on-demand or loads everything ahead of time...

(also for some reason I see Windows reported memory usage grow ~2x faster than what I'd guess looking at the decoded image sizes, so that's interesting too, I think I see the reason so can at least handle that)

**Comment by sombraguerrero** [comment]
*sigh* More pie in the sky with BitmapData, not surprising in the least, I'd say.
Given how much of a resource hog Flash always was, I would venture to say that it just loads everything at once. Like, flipping through the pages of this manual, there's no delay after it's done, so I have to assume it's all in memory already.

**Comment by Elementtair** [comment]
Thanks for watching.
I made some try last evening;
 - it now seems to load correctly with firefox  with both computer, selfhosted was 2021-06-15
 - It crashs the latest desktop version on the IGC computer, load fine with the other (4GB of VRAM).

Updated to today build (2021-06-18) give same results.

**Comment by Elementtair** [comment]
I tried to reproduce the "unable to lock ruffle core" by putting back the 2021-05-22 selfhosted:
- it's now working every time on both computer with Firefox 89.0.1
- tried to downgrade to Firefox 88.0.1 with no luck, the document doesn't load, but it's just a blank page with no console error.

This swf was created with SWFtools, possibly 0.8.1 at the time

**Comment by Elementtair** [comment]
It's now working perfectly for me since a while on both computer, also on the phone.
It also seemed to me you already resolved the unwanted memory growth of bitmap allocation.
@adrian17 if it s good for you, it is for me, and this issue can now be closed
