### ISSUE TITLE
HTML tag parameter "loop=false" not resulting in expected behaviour?

### ISSUE THREAD

**Issue by martinlnd** [ruffle-rs/ruffle#4394]
Ahoy, Rufflers!

I'm back with a quite simple bug report, after the medium #3698 one (next I will report the most complicated one):

In one of my smallest but most effective intros I used the "loop" parameter set to false:

```
<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
 codebase="http://active.macromedia.com/flash2/cabs/swflash.cab#version=4,0,0,0"
 ID=intro_v7 WIDTH=100% HEIGHT=100%>
 <PARAM NAME=movie VALUE="intro_v7.swf?IE=0">
 <PARAM NAME=loop VALUE=false>
 <PARAM NAME=quality VALUE=high>
 <PARAM NAME=bgcolor VALUE=#FFFBEE>

 <EMBED src="intro_v7.swf?IE=0" loop=false quality=high bgcolor=#FFFBEE
  WIDTH=100% HEIGHT=100% TYPE="application/x-shockwave-flash"
  PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">
 </EMBED>
```

As you can see, it is set to "false" in both instances and it indeed does so from Flash 4 onwards up until e.g. Firefox 48 with an unbroken Flash extension.

But using Ruffle it keeps looping forever:

http://www.abrahama-sama-clara.at

This should be easy to fix, if Ruffle even parses the HTML parameters correctly?

Keep up the good work! After issuing my three bug reports (one more to go) I intend to maybe join the effort, if I am up to it.

**Comment by danielhjacobs** [comment]
I believe this ties into #4258.

**Comment by martinlnd** [comment]
> I believe this ties into #4258.
Ah, indeed - thanks!

**Comment by Herschel** [comment]
Closing in favor of #4258, thanks for the report.
