### ISSUE TITLE
(Etherena) Option value changes are handled, but screen text is not updated.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4403]
## Describe the bug
![image](https://user-images.githubusercontent.com/75052171/119248653-935d7f00-bbcd-11eb-8aa7-2c8a9e082027.png)

When I click on the area shown in the photo in "Etherena Beta", the value actually appears to have been applied, but the changed value does not update to the screen.

If you click and change the 'Stage' option displayed as TreeTop, the Stage will definitely change, but the value will still appear as TreeTop.

There were no errors in the console.

[Etherena Beta.zip](https://github.com/ruffle-rs/ruffle/files/6527546/Etherena.Beta.zip)

## Expected behavior
When the option value fluctuates, it must be displayed correctly on the screen.

## Is the problem with the Ruffle desktop app, extension, or self-hosted version?
Tested on self-hosted.

## What platform are you using?
 - OS: Windows 10 20H2 x64
 - Browser: Chrome Latest
 - Ruffle: 2021-05-23 Nightly

**Comment by Toad06** [comment]
Thanks for the report.

I took a look at the "Stage" option as I assume the other ones are exactly related to the same issue:

- In the "texts" tab, `DefineEditText(750)` has a `variablename` property with value "lvls".

- The variable "lvls" is used in many button scripts and is also supposed to affect the text being displayed (the name of the level) as it does in Flash, but this doesn't work on Ruffle.

**Comment by Jmousy** [comment]
As of the 2023-08-27 build (I don't know when it was fixed), this issue is no longer reproduced. Hooray!
I'll close the issue.

**Comment by n0samu** [comment]
Fixed by #12541
