### ISSUE TITLE
(Little Soldiers) The game freezes when the first stage is completed.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4404]
## Describe the bug
![image](https://user-images.githubusercontent.com/75052171/119249270-2dbfc180-bbd2-11eb-90ed-5706b60e3f7a.png)
After completing the first stage in Little Soldiers, the game freezes without a clear screen.

[little-soldiers.zip](https://github.com/ruffle-rs/ruffle/files/6527579/little-soldiers.zip)

## Expected behavior
![image](https://user-images.githubusercontent.com/75052171/119249309-6b244f00-bbd2-11eb-8b78-4665d2326ac4.png)
The following screen is displayed and should continue

### Is the problem with the Ruffle desktop app, extension, or self-hosted version?
Tested on self-hosted.

## What platform are you using?
 - OS: Windows 10 20H2 x64
 - Browser: Chrome Latest
 - Ruffle: 2021-05-23 Nightly

**Comment by relrelb** [comment]
Likely related to https://github.com/ruffle-rs/ruffle/issues/993#issuecomment-675182938.

When the level ends, the soldier clip is removed by the second `DoAction` of frame 25:
```as
function winFunc() {
    if (this.gfx._currentframe == this.gfx._totalframes) {
        this.removeMovieClip("");
        through++;
    }
}
```
This affects the `moving` function in the same script:
```as
var _loc1_ = smap[_loc3_][_loc2_]; // loads soldier clip
if (!_loc1_.MESKIP) { // In Flash, this if is taken because _loc1_.MESKIP is undefined
    _loc1_ = _loc1_.frame(); // In Flash, _loc1_.frame is undefined, so _loc1_ becomes undefined
    if (_loc1_) {
        if (_loc1_ == 32) {
            _loc4_ = 1;
            smap[_loc3_][_loc2_].MESKIP = true;
        }
        _loc5_ = true;
    }
}
```
In Ruffle, however, `_loc1_.frame` continues to be a valid function even after the solider clip is removed, causing `_loc5` to never end up as `0`.

Here's a simplified showcase that demonstrates the incorrect behavior:

```as
var mc = this.createEmptyMovieClip("mc", this.getNextHighestDepth());
mc.hi = "hi";

trace(mc); // traces "_level0.mc" in both Flash and Ruffle
trace(mc.hi); // traces "hi" in both Flash and Ruffle

mc.removeMovieClip();

trace(mc); // still traces "_level0.mc" in Ruffle but nothing in Flash
trace(mc.hi); // still traces "hi" in Ruffle but "undefined" in Flash
```
