### ISSUE TITLE
Scrolling of text is broken in submachine games

### ISSUE THREAD

**Issue by DependentAppearance0** [ruffle-rs/ruffle#4416]
**Describe the bug**
In some submachine games there are scrollable texts which aren't scrollable / don't scroll in ruffle. These issues can make the games significantly harder to beat or nearly impossible to beat as important information is contained outside of the viewable area.

So far I have noticed this bug in submachine 4 and 8.

To reproduce in submachine 4 https://www.y8.com/games/submachine_4_the_lab

Click play
Skip intro
Go left and take the hammer
Go right twice and down
Go right and break the lock
Go inside and downwards
Go right twice and pick up the chimneybrush behind the box on the right of the screen
Go back outside and use the brush on the chimney one left from the window
Go back inside and pick up the key from the screen on the right 
Go left until you reach the door
Use key on the door
Go down 2 times or until you reach the floor where the doorframe is gray
Go left
Click on the computer
Press on the light button on the computer

Text will now appear on the screen until it overflows off the screen without scrolling.
![kuva](https://user-images.githubusercontent.com/68330228/119379960-c6386d80-bcc8-11eb-970d-8ad07c3dfa5b.png)
The font also appears to be wrong which could be linked to the issue

**Expected behavior**
Expected behaviour is that the text would scroll or be scrollable however it is not
![kuva](https://user-images.githubusercontent.com/68330228/119380029-df411e80-bcc8-11eb-9aaf-c2a604569182.png)
Screenshot of a walkthrough showing the text scrolled

**What platform are you using?**
I am using the extension on firefox 88.0.1 with the currently latest version of the extension

**Comment by adrian17** [comment]
Related: https://github.com/ruffle-rs/ruffle/issues/1033
