### ISSUE TITLE
Have we reached a stage where we can use ruffles like this or are we still in mythical stage?

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#442]
https://github.com/ienaga/swf2js

Allows you to actually use it in production like this: 
<script type="text/javascript" src="swf2js.js"></script> 
<script type="text/javascript"> 
    swf2js.load('SET SWF PATH'); 
</script>   

Yes, that is all that is required to let your website host swf content, granted it is limited to AS2 but that was rather amazing in its simplicity no ? It is so simple it is almost embarrassing.

Have we reached this stage in ruffles yet or do we still need a whole host of libs/make/builds/wasm-pack/wasp-pack/npm-ing all the libraries in the world/dilithium crystals/interfacing with unimatrix zero-one for your average web designer to just use it already ?

**Comment by Herschel** [comment]
You can try the wiki instructions for using Ruffle on your own site here:
https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#web

The latest nightly build of Ruffle for web is available here:
https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/web/ruffle_web_latest.zip

Let us know if there are any issues or if any instructions are unclear. Thanks!

**Comment by BracerJack** [comment]
The instructions are not clear at all.
  <script>
    window.RufflePlayer = window.RufflePlayer || {};
    // Update the paths below to the directory containing the Ruffle files on your web server.
    window.RufflePlayer.config = {
      "public_path": "path/to/ruffle/"
    };
  </script>
  <script src="path/to/ruffle/ruffle.js"></script>

Paste where ?
1: In the head tag ?
2: Before the 
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="550" height="400" id="Untitled-1" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="Untitled-1.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /><embed src="Untitled-1.swf" quality="high" bgcolor="#ffffff" width="550" height="400" name="Untitled-1" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>
that flash produces ?
3: Within the object tag that flash produces ?
4: After the object tag that flash produces ?
You can't just say "paste this in" and expect people to know where to paste.

It is not clear at all.
It is almost confirmed that designers will be using the first Polyfill method and that part is just like "paste this in bye !", you can't do that, we will be lost !

**Comment by Herschel** [comment]
Try placing it before the closing `</body>` tag. 
(Really you can place it most anywhere, and it should work; it will automatically apply to any `<object>`/`<embed>` on the page.)

Thanks for the feedback, it's still early for us, so we'll try to improve the docs!

**Comment by BracerJack** [comment]
https://a.uguu.se/3vlsFxCkKOxg_Newfolder.7z
Here is the file for 24 hours only, there are only three file a simple flash file with a single button that plays a sound, the html file with the modification you specified and ruffle.js.

It doesn't work, please make deployment simpler.
swf2js is only: swf2js.load('SET SWF PATH'); 
Why do we need to add so much "STUFF" just to make ruffles work and it still doesn't work ?

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled-1</title>
</head>
<body bgcolor="#ffffff">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="550" height="400" id="Untitled-1" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="Untitled-1.swf" />
<param name="quality" value="high" />
<param name="bgcolor" value="#ffffff" />
<embed src="Untitled-1.swf" quality="high" bgcolor="#ffffff" width="550" height="400" name="Untitled-1" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>

<script>
	window.RufflePlayer = window.RufflePlayer || {};
	// Update the paths below to the directory containing the Ruffle files on your web server.
	window.RufflePlayer.config = {"public_path": ""};
</script>
<script src="ruffle.js"></script>

</body>
</html>

==========================================
why is there a window.RufflePlayer.config = {"public_path": ""}; to specify the source folder of ruffle.js AND THEN another <script src="ruffle.js"></script> to ONCE AGAIN RE-SPECIFY the actual file itself ?
Why is there duplication ?

**Comment by Herschel** [comment]
You need to place all the .js and .wasm files in the folder. This is 3 files: `ruffle.js`, `core.ruffle.*.js`, and `*.module.wasm`. The docs need to be changed to make this clearer.

In your case, if all files are in the same folder, you can just do:
`<script src="ruffle.js"></script>`

The other tags with `public_path` are necessary if you place the Ruffle files in a different folder.

We are slightly more complicated because this is a WebAssembly project, so more files are required. But I agree with you about the duplication, and that hopefully we can make it simpler. Thank you for the patience!

(@kmeisthax, could we default `public_path` to be based on `document.currentScript.src`? This could simplify the polyfill case to a single script tag for more cases).

**Comment by BracerJack** [comment]
Ok I have:
ruffle.js
core.ruffle.89f0de90816238544089.js
6b5410df0c15875e206c.module.wasm

In the folder.
And I have:
<script>
	window.RufflePlayer = window.RufflePlayer || {};
	window.RufflePlayer.config = {"public_path": ""}; //Is this line even needed still if the three files are in the root folder ?
</script>
<script src="ruffle.js"></script>

And it STILL doesn't work.

This is everything:
======================================================================================================
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled-1</title>
</head>
<body bgcolor="#ffffff">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="550" height="400" id="Untitled-1" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="Untitled-1.swf" />
<param name="quality" value="high" />
<param name="bgcolor" value="#ffffff" />
<embed src="Untitled-1.swf" quality="high" bgcolor="#ffffff" width="550" height="400" name="Untitled-1" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>

<script>
	window.RufflePlayer = window.RufflePlayer || {};
	// Update the paths below to the directory containing the Ruffle files on your web server.
	window.RufflePlayer.config = {"public_path": ""};
</script>
<script src="ruffle.js"></script>

</body>
</html>

**Comment by Herschel** [comment]
The zip file you posted was working for me. Could you press F12 and see if there are errors in the console? Where are you hosting the files?

**Comment by BracerJack** [comment]
I use python -m http.server to create a temporary server situation.
Hold on:
Here you go:
https://imgur.com/KWoLqxy

**Comment by ROBERT-MCDOWELL** [comment]
@BracerJack 
you are welcome to improve the doc btw! :D

**Comment by BracerJack** [comment]
https://imgur.com/xp8NRlD - More error report.

I would be MORE THAN HAPPY to improve the doc, check that, I would MAKE A straight to the point no nonsense VIDEO to explain it here in my channel:
https://www.youtube.com/user/Bracerjack/videos

But first it have to work !

**Comment by Herschel** [comment]
It looks like Python http.server does not serve WebAssembly files with the correct MIME Type. This is out of our control, but we should improve our docs to provide guidance about it (see #400).

Possibly updating your Python may fix the issue (I'm not a Python user, so I'm not sure) -- otherwise, try a different web server.

**Comment by BracerJack** [comment]
I tried python-3.8.2, and it is still not working.
So now we are at the dread stage where I have no choice but to ask:
How to do make the python server or any serve WebAssembly files with the correct MIME Type ?
This is such a dread question because it's like one of those "why is this even a problem" situation.

**Comment by BracerJack** [comment]
Update: I even tried: 
#!/usr/bin/env python3

import http.server
import socketserver

PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler
Handler.extensions_map.update({
    '.wasm': 'application/wasm',
    '.swf': 'application/x-shockwave-flash'
})

socketserver.TCPServer.allow_reuse_address = True
with socketserver.TCPServer(("", PORT), Handler) as httpd:
    httpd.allow_reuse_address = True
    print("serving at port", PORT)
    httpd.serve_forever()

Not working.

**Comment by ROBERT-MCDOWELL** [comment]
this is offtopic, you should ask your question to python forums or google it.
for exemple
https://bugs.python.org/issue35403

**Comment by Herschel** [comment]
Make sure to try a hard refresh ignoring cache by pressing Ctrl+F5, it's possible a 404 page from earlier attempts may be cached. You can also press F12 and look in the Network Inspector to see if the files are being found.

This is my specific Python version:
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32

You can also try this web server as an alternative: https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb

**Comment by Herschel** [comment]
Hi @BracerJack, is this still an issue? The documentation has improved some to address the above concerns.

**Comment by BracerJack** [comment]
It's fixed, I will close the case now.
THANK YOU :D
