### ISSUE TITLE
S key does not work in Disorderly

### ISSUE THREAD

**Issue by chrisparton1991** [ruffle-rs/ruffle#4446]
**Describe the bug**
Disorderly (https://www.newgrounds.com/portal/view/121896) seems to work great, except for when pressing the `S` key, which is used to open doors.

**Expected behavior**
Pressing the `S` key performs the appropriate in-game action.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
This is on Newgrounds, which is running the latest Ruffle nightly (currently 2021-05-24).

**What platform are you using?**
I've tested on latest Chrome+Firefox, on Windows 10 and OSX 10.15.7 (Catalina). Others have reported the same issue in the comments on Newgrounds.

<img width="981" alt="Screen Shot 2021-05-29 at 8 51 24 pm" src="https://user-images.githubusercontent.com/13063119/120067612-efd60800-c0bf-11eb-882b-fb8b732ebc45.png">

P.S. Thanks for your phenomenal work on this project!

**Comment by Herschel** [comment]
Fixed by #4452.
