### ISSUE TITLE
The Queen of Snakes: Blue triangles everywhere

### ISSUE THREAD

**Issue by angstsmurf** [ruffle-rs/ruffle#4464]
**Describe the bug**
In Ruffle, this game throws up distorted blue triangles everywhere, which apart from being ugly hide information and make the game unplayable. They seem to cover all mouse-click responsive hotspots.

<img width="1136" alt="Skärmavbild 2021-06-01 kl  00 07 11" src="https://user-images.githubusercontent.com/5066755/120245516-b511d280-c26d-11eb-9354-a0b862e93808.png">

Game: http://www.jo99.fr/wp-content/uploads/2013/05/templeserpent11.swf

**Expected behavior**
There should only be a blue triangle at the edge where you can go. See https://youtu.be/jYqShMqJOoU?t=13

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
This is the Ruffle desktop app, nightly 2021-05-31.

**What platform are you using?**
macOS 11.4, Macbook Pro 15", 2016.

**Comment by angstsmurf** [comment]
Thanks for looking into this!

**Comment by Lord-McSweeney** [comment]
Fixed by #8262.

**Comment by angstsmurf** [comment]
Have you tested it? Definitely not fixed here.

<img width="1136" alt="Skärmavbild 2023-01-13 kl  04 46 58" src="https://user-images.githubusercontent.com/5066755/212232730-768a1c34-7a35-459b-9ff7-d9cfc6a24e5b.png">

**Comment by ActionWavele** [comment]
yeah, I think things need to be tested if you're closing issues.

**Comment by pdewacht** [comment]
I've spent some time poking at this. The problem seems to be that ruffle doesn't render BlendMode::Erase correctly if there's no BlendMode::Layer first. This is a reduced test case:
[templeserpent11-testcase.zip](https://github.com/ruffle-rs/ruffle/files/11009478/templeserpent11-testcase.zip)

**Comment by angstsmurf** [comment]
Seems to be fixed by 0786727.
