### ISSUE TITLE
web: Select fields not working

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#447]
Select fields are not working - they don't show the available options.

See i.e.  http://www.webgeo.de/k_024_en/#3

[k_024_03.zip](https://github.com/ruffle-rs/ruffle/files/4336882/k_024_03.zip)
![k_024_select](https://user-images.githubusercontent.com/1667683/76735198-b0462900-6764-11ea-8788-a28a61518c5f.png)

**Comment by Herschel** [comment]
Requires text field variables to be implemented (cc #315)

**Comment by Herschel** [comment]
Text field variable bindings were implemented, but these select boxes are still not functioning and require some investigation.

**Comment by Herschel** [comment]
Looks like this needs `onClipEvent(initialize)`, which we haven't implemented yet. Can probably just fire this alongside `construct`.

**Comment by Herschel** [comment]
Seems like this works now, although performance is slow due to the slow text rendering currently.

**Comment by KMicha** [comment]
Works fine now - also performance is fine for me....
