### ISSUE TITLE
Freeze in Raft Wars after Shooting

### ISSUE THREAD

**Issue by tsamisaherb** [ruffle-rs/ruffle#4484]
**Describe the bug**
Raft Wars: https://www.miniclip.com/games/raft-wars/en/#privacy-settings

Freezes after shooting. It is not consistent, but happens every 30-40 shots or so, right after you shoot the game freezes. I've never been able to get through the whole game without it happening. 

**Expected behavior**
The game should not freeze when I shoot.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self hosted

**What platform are you using?**
Web version, Windows 10 Microsoft Edge.
![raft-wars-1-freeze](https://user-images.githubusercontent.com/14360616/120356014-e0c6a400-c2d1-11eb-90b6-8aa30e79ec79.gif)

**Comment by n0samu** [comment]
Seems like this has been fixed for some time
