### ISSUE TITLE
missing allot of stuff getting working https://www.japonin.com/quiz2/test_quizzes/intro_vocabulary1.html

### ISSUE THREAD

**Issue by greatlord** [ruffle-rs/ruffle#4497]
https://www.japonin.com/quiz2/test_quizzes/intro_vocabulary1.html
version : Nightly 2021-06-02 preview
OS Debian bulleye

**Describe the bug**
The image place in worng postions

New Ruffle instance created. ruffle.js:1:49752
Loading SWF file intro_vocabulary1.swf ruffle.js:1:51649
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient interpolation mode ruffle.js:1:25131
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient spread mode 3 ruffle.js:1:25131
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient interpolation mode 4 ruffle.js:1:25131
Error running definition tag: DefineVideoStream, got Invalid data: Invalid video codec. ruffle.js:1:25131
Tried to instantiate non-registered character ID 318 ruffle.js:1:25131
Unable to instantiate display node id 318, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character ID 322 ruffle.js:1:25131
Unable to instantiate display node id 322, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character ID 320 ruffle.js:1:25131
Unable to instantiate display node id 320, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character grey_btnQuestionsComboboxDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character ID 318 ruffle.js:1:25131
Unable to instantiate display node id 318, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefined ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_closeVideoButtonDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_nullUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_nullOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_nullDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_nullDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character ID 237 ruffle.js:1:25131
Unable to instantiate display node id 237, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character grey_choiceItemDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_choiceItemDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131
Tried to instantiate non-registered character ID 237 ruffle.js:1:25131
Unable to instantiate display node id 237, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character grey_choiceItemDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_choiceItemDisabled ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedUp ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedOver ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDown ruffle.js:1:25131
Tried to instantiate non-registered character grey_undefinedDisabled ruffle.js:1:25131

**Comment by greatlord** [comment]
I am using now ruffer lates version from chrome store may 6 2022

it start working now 
but the audio can not be play 

follow errors are gone now
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient interpolation mode ruffle.js:1:25131
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient spread mode 3 ruffle.js:1:25131
Error running definition tag: DefineShape4, got Invalid data: Invalid gradient interpolation mode 4 ruffle.js:1:25131


all errores simlare like this are gone
Tried to instantiate non-registered character ID 318 ruffle.js:1:25131
Unable to instantiate display node id 318, reason being: Character id doesn't exist ruffle.js:1:25131
Tried to instantiate non-registered character ID 322 ruffle.js:1:25131


here is the new error logs
966.js:1 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ 966.js:1
ruffle.js?id=25634406034:1 New Ruffle instance created (WebAssembly extensions: ON)
ruffle.js?id=25634406034:1 Loading SWF file intro_vocabulary1.swf
966.js:1 Error running definition tag: DefineVideoStream, got Invalid data: Invalid video codec.
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_btnQuestionsComboboxDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefined
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_closeVideoButtonDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_nullUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_nullOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_nullDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_nullDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_choiceItemDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_choiceItemDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_choiceItemDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_choiceItemDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedUp
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedOver
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDown
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1
966.js:1 Tried to instantiate non-registered character grey_undefinedDisabled
c.wbg.__wbg_error_8ff19d586a987aef @ 966.js:1

**Comment by n0samu** [comment]
>  but the audio can not be play

Where is the audio supposed to play? I tried opening the quiz with Adobe Flash Player and there doesn't seem to be any audio there either.

**Comment by greatlord** [comment]
It is no audio only text what I figout out. so it working now with chrome version of ruffle i tested with is nightly 2024-06-11
I have not follow this upp seen  2021, sorry for late replay. I am closing it now
