### ISSUE TITLE
Just a white screen at https://www.furaffinity.net/view/23804315/

### ISSUE THREAD

**Issue by TheSofox** [ruffle-rs/ruffle#4505]
FurAffinity uses Ruffle, but submission https://www.furaffinity.net/view/23804315/ just shows a blank screen, no action or movement.

Direct link to the SWF is here: https://d.furaffinity.net/download/art/redflare500/1497190290/1497189544.redflare500_pone.swf

**Comment by adrian17** [comment]
Looks like it loads a H.263 video, so support hangs on https://github.com/ruffle-rs/ruffle/pull/2173 .

**Comment by torokati44** [comment]
With #2173 merged, the video in the linked SWF now plays, and looks correct. Can you verify this, and close the issue if you agree, @TheSofox?

**Comment by TheSofox** [comment]
Tested using Windows 64 bit Nightly (2021-08-24) and it worked fine! Video and audio there! Great work!
