### ISSUE TITLE
Ruffle browser extension error

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#454]
I was testing out the ruffle extension, & on a site that had me click a button to load the flash version of an animation, it showed this error in the console:
Serious error encountered when polyfilling native Flash elements: TypeError: Cannot read property 'value' of undefined

**Comment by Herschel** [comment]
Could you share a link to the site in question? Thanks!

**Comment by Justin-CB** [comment]
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/ghost.php
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/fire.php
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/fire2.php
There is a HTML5 video at the top, then some text, then a button to load the flash version. If I press the button on a browser with the real flash player, the animation loads & runs, but on a browser without flash with orwithout the ruffle extension, it shows the "This plugin is not supported" message.

**Comment by ROBERT-MCDOWELL** [comment]
Ruffle never been an extension.

**Comment by Justin-CB** [comment]
I think that this may be different, & may be due to the dynamic insertion because the error shows up before the button is clicked(The pages have javascript that inserts the embed code with innerHTML).

**Comment by Justin-CB** [comment]
I have looked a little closer into what was making it break on that site & will create new issues with the underlying causes.
