### ISSUE TITLE
Graphics are messed up in a few games (regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#4545]
Graphics in [Ultimate Flash Sonic](https://uploads.ungrounded.net/151000/151706_ultimate_sonic.swf?1077899965) can be messed up as of [nightly-2021-06-10](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-06-10). This also affects gameplay.

It looks like the issue was introduced in commit b1318ecb012cdfc24733275280c8954f0d7b967e.

Screenshots of the first level without and with the mentioned commit:
![good](https://user-images.githubusercontent.com/14274782/121498078-5d493900-c9dc-11eb-9657-d2e1278778fa.png) ![bad](https://user-images.githubusercontent.com/14274782/121498096-61755680-c9dc-11eb-91ba-804760c0a3aa.png)

**Comment by Toad06** [comment]
The issue also happens in a couple of other games.

- In [Steppenwolf 3-3](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/495/original/steppenwolf_chapter_3_episode_3.swf?1521281325), press I to open the inventory. Click the code key (the last item), then any other item, and the code key again. Notice the issue with the font.

![step_good](https://user-images.githubusercontent.com/14274782/121915388-754def00-cd33-11eb-854b-be35ab8b82b8.png) ![step_new](https://user-images.githubusercontent.com/14274782/121915405-797a0c80-cd33-11eb-8910-5c6e3e588b60.png)

- In [The Waitress](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/637/original/the_waitress.swf?1521281821), the issue makes the game looking like an horror game. 😄

![waitress_good](https://user-images.githubusercontent.com/14274782/121915995-0755f780-cd34-11eb-9c9b-c61551d8b979.png) 
![waitress_new](https://user-images.githubusercontent.com/14274782/121916012-0c1aab80-cd34-11eb-889c-b0bf4b0ee3c5.png)

**Comment by ousia** [comment]
@Toad06, many thanks for your help in #4593 (which I closed in favor of this issue).

I wonder whether the title of this issue should also include texts (not only graphics are messed in a few animations).

Many thanks for your help again.
