### ISSUE TITLE
Error on https://e621.net/posts/591392?q=zonkpunch+charizard

### ISSUE THREAD

**Issue by MineCraftFNAFFanBalin** [ruffle-rs/ruffle#4552]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:31957
    at r (<anonymous>:3:32235)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/591392?q=zonkpunch+charizard

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13904.41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.81 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by adrian17** [comment]
We know about it and, unfortunately, can't currently do anything about it.
Check out the comments here: https://github.com/ruffle-rs/ruffle/issues/2201#issuecomment-754751614
Closing to deduplicate reports.
