### ISSUE TITLE
Ruffle only Showed a white screen

### ISSUE THREAD

**Issue by ghost** [ruffle-rs/ruffle#4557]
I downloaded the ruffle extension and It only showed a white screen on the place where the flash game is.

<img width="881" alt="Screen Shot 2021-06-11 at 10 44 46 AM" src="https://user-images.githubusercontent.com/85757850/121721942-0d34aa00-caa2-11eb-9c33-c3c378b63e57.png">

1. Download the extension. 2. go to a site that has flash games. 3. turn on ruffle. 4. there should be a white screen.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**
I expected it to let me play the game and it didn't.

Problem with the self hosted extension version.

Mac OS

**Comment by danielhjacobs** [comment]
Which site? As a user of Ruffle I can tell you for a fact that it doesn't always white-screen, and a white screen is often a CORS issue.

**Comment by I-Miss-Flash** [comment]
this is the site https://sites.google.com/site/unblockedgameworld i even tried other sites and still no.

**Comment by danielhjacobs** [comment]
As I said: [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). The JavaScript console on that page says Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://5e3e6150-a-62cb3a1a-s-sites.googlegroups.com/site/unblockedgameworld/amberial.swf](https://5e3e6150-a-62cb3a1a-s-sites.googlegroups.com/site/unblockedgameworld/amberial.swf?attachauth=ANoY7cpFWX5Jvs6V5dktJDkrp6I6-3N6O93ySkg_6gEc--2PQRMn0uoaOmswulIhLRaUgJGXyhD2CGgaZmmDU1z6Xx83X8vGPAsEAJz_Ab_ydnNv-KcWbxemFuZRPqckAtmEyOQ1QnxPAZvRjI_hJ_fCjj4QH98WusDBDsPiM80uOxxlcgsMQqS_mon9Q-s4Nohoj4Cs5lWkrT53dS3N8lPcgeCphIWzGA%3D%3D&attredirects=0). See #2201.

**Comment by I-Miss-Flash** [comment]
weird CORS i use Google Chrome and that is a lot different from Firefox so this is kind've a pickle,

**Comment by danielhjacobs** [comment]
The website I linked is Mozilla's description of internet standards, it has nothing to do with Firefox, CORS exists on every modern browser. Adobe Flash was one of the few web technologies that didn't have to worry about it, but Ruffle is subject to the same restrictions of the web as any other script.

**Comment by danielhjacobs** [comment]
If you go directly to the swf with the browser extension enabled you'll see it does work. Click this: https://5e3e6150-a-62cb3a1a-s-sites.googlegroups.com/site/unblockedgameworld/amberial.swf?attachauth=ANoY7cpFWX5Jvs6V5dktJDkrp6I6-3N6O93ySkg_6gEc--2PQRMn0uoaOmswulIhLRaUgJGXyhD2CGgaZmmDU1z6Xx83X8vGPAsEAJz_Ab_ydnNv-KcWbxemFuZRPqckAtmEyOQ1QnxPAZvRjI_hJ_fCjj4QH98WusDBDsPiM80uOxxlcgsMQqS_mon9Q-s4Nohoj4Cs5lWkrT53dS3N8lPcgeCphIWzGA%3D%3D&attredirects=0.

**Comment by n0samu** [comment]
This was fixed long ago by #4665
