### ISSUE TITLE
Error on http://www.juegosjuegos.com/embed/spiderman-dark-side

### ISSUE THREAD

**Issue by oscarar1** [ruffle-rs/ruffle#4560]
# Error Info
Error name: CompileError
Error message: wasm validation error: at offset 18520: expected code section

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.juegosjuegos.com/embed/spiderman-dark-side

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-02-02
Channel: nightly
Built: 2021-02-02T00:21:23.909Z
Commit: 5783021d99477357a1d291d47fc0fd16082fbd98

**Comment by danielhjacobs** [comment]
> Problem is on the juegosjuegos website (I believe wasm file was mistakenly uploaded in ASCII mode). Please contact https://www.juegosjuegos.com/contact

Information about this error is on the Ruffle Wiki: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#addressing-a-compileerror

**Comment by Poopooracoocoo** [comment]
>Problem is on the juegosjuegos website (I believe wasm file was mistakenly uploaded in ASCII mode). Please contact https://www.juegosjuegos.com/contact

Information about this error is on the Ruffle Wiki: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#addressing-a-compileerror
