### ISSUE TITLE
Ruffle sometimes fails to detect object and embed tags

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#457]
A notable case is when the object/embed tag is missing the "type" attribute (or when its value is different than "application/x-shockwave-flash").

There are a couple of other cases in the attached file below (test_cases.txt sums up the issue). #454 may also be related to this issue (but this is speculation as I wasn't able to reproduce that one).

[convertfails.zip](https://github.com/ruffle-rs/ruffle/files/4357213/convertfails.zip)

**Comment by Herschel** [comment]
Thanks for the excellent bug reports!

**Comment by Justin-CB** [comment]
My guess is that both this bug and #454 are bugs in the flash embed detection logic: it probably doesn't use the DOM to detect the presence of object & embed tags(the error message I got was before the javascript that inserted the flash version was even run) and it assumes that all flash embeds are done in the standard way(with type="application/x-shockwave-flash" & classid on object tags).

**Comment by Herschel** [comment]
Fixed, thanks! It seems okay that the object99 case works (raw object tag would work in classic IE).
