### ISSUE TITLE
LG K51 Android phone does not display or load swf file on website in Chrome.

### ISSUE THREAD

**Issue by kimvanzandt** [ruffle-rs/ruffle#4583]
I haven't checked in a while but seems the Ruffle emulator stopped displaying my flash game on my Android supported phone. It does work on iPhones and an older Android supported tablet. When I installed a Firefox app it did work but not in Chrome. Do you know the reason for this? Thank you.

**Comment by torokati44** [comment]
There was a discussion about a similar issue on the Ruffle Discord.
The conclusion of that was that this is most likely an issue in Android Chrome 91.
Can you try it in Chrome 92 beta? It's also available in the Play Store AFAIK.

**Comment by torokati44** [comment]
Or Firefox could also work.

**Comment by kimvanzandt** [comment]
Hi, I tried your suggestion and installed the Chrome Beta app and the games now display and work! I thought something was wrong with my files. Thank you!

________________________________
