### ISSUE TITLE
[regression] text heavily misplaced from nightly 2021-06-10

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#4593]
Up to nightly from 2021-06-09 (Firefox extension), text in https://www.free-culture.tk/free_culture.swf was displayed perfectly fine (in all frames).

From 2021-06-10, text is heavily misplaced almost on every frame.

Among many others, when you load the SWF file and press _[Continue]_, second frame should read (as displayed before 2021-06-10):

![before-placeobject](https://user-images.githubusercontent.com/203767/122256912-c72b7c00-cecf-11eb-90d0-04ca7ec80bec.png)

But starting with 2021-06-10, second frame is displayed as:

![after-placeobject](https://user-images.githubusercontent.com/203767/122257035-e75b3b00-cecf-11eb-8c38-f5161bc82632.png)

@Herschel, I don’t know whether this might been have caused by #4543.

Many thanks for your help.

**Comment by ousia** [comment]
Sorry, the second frame is rendered fine with 2021-06-15.

But text is misplaced in other frames.

1. Load https://www.free-culture.tk/free_culture.swf.
2. Click three times to start presentation, so sound starts to play.
3. Click the button to advance frames (`[>>]`) nine times.
4. See the misplaced text.

With 2021-06-15, I get:

![afterplaceobject](https://user-images.githubusercontent.com/203767/122258722-a8c68000-ced1-11eb-85b5-ef4fb66f53f9.png)

Right rendering with 2021-06-09:

![beforeplaceobject](https://user-images.githubusercontent.com/203767/122259017-fb07a100-ced1-11eb-8ccb-796c9b4913a1.png)

**Comment by Toad06** [comment]
Thanks for the report.

The cause seems to be the same as the issues described in #4545 (related to commit b1318ecb012cdfc24733275280c8954f0d7b967e).

**Comment by ousia** [comment]
Closing in favor of #4545.
