### ISSUE TITLE
Crush the Castle 2 blink problem and I wasn't able to "play"

### ISSUE THREAD

**Issue by cagozz** [ruffle-rs/ruffle#4602]
When I start the game(Crush the Castle 2), screen of ruffle starts to blink quickly. Also I can't press play button.

I wasn't able to find this game, and I expected to be able to play
With desktop app ruffle_nightly_2021_06_17_windows_x86_64

Windows 10 20H2 (64 bit)

[Crush the Castle 2.zip](https://github.com/ruffle-rs/ruffle/files/6672636/Crush.the.Castle.2.zip)

**Comment by danielhjacobs** [comment]
That's AS3, which is unsupported. See #1368. Unfortunately, that does not seem to work in Lightspark either. You can probably play it with Standalone Flash Player: https://www.adobe.com/support/flashplayer/debug_downloads.html.
