### ISSUE TITLE
Ruffle Extension Throws Error With Non-Flash Embeds

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#463]
These 3 pages:
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/ghost.php
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/fire.php
https://justinbesterportfolio.000webhostapp.com/DArts/Animate/fire2.php
Use an avi embed as a fallback for html5 video. This causes the ruffle browser extension to have this error(from the browser console):
Serious error encountered when polyfilling native Flash elements: TypeError: Cannot read property 'value' of undefined

**Comment by Herschel** [comment]
Could you try again with the latest build? This was fixed by 099c497a91ed0d565d476eca0b55aba0b576e49d.
