### ISSUE TITLE
Ruffle don't work on Google Chrome for android (91.0.4472.101) 

### ISSUE THREAD

**Issue by def-3** [ruffle-rs/ruffle#4642]
Hi,

With the last version of Google Chrome for Android Ruffle dont work anymore. You got a black screen instead of the game.

Ruffle  version : Nightly 2021-06-21

Google Chrome version : 91.0.4472.101

Android Version : 10

Url for test : https://ruffle.rs/demo/

Console logs : 
ruffle_web.js:1200 Unable to construct AVM2 Stage: TypeError: undefined is not an Object
t.wbg.__wbg_error_9ff84d33a850b1ef @ ruffle_web.js:1200
ruffle-player.js:399 Serious error occurred loading SWF file: Error creating player
(anonymous) @ ruffle-player.js:399
ruffle-player.js:5 Uncaught (in promise) Error creating player

Best regards.

**Comment by danielhjacobs** [comment]
Yes there's been a few issues saying that this doesn't work but it's actually a Chrome bug.  If you download the Chrome Beta app for android you'll notice it's fixed in version 92.

**Comment by Poopooracoocoo** [comment]
Closing as bug has since been fixed.
