### ISSUE TITLE
Fancy pants 2 background not showing up on ruffle extension nightly 2021-06-22

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#4646]
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

the game audio and the movements work great but the back ground is not there
![fancypants2](https://user-images.githubusercontent.com/64484245/122967317-f61e7380-d34f-11eb-906b-f034a394b891.png)

https://www.newgrounds.com/portal/view/420606/emulate/flash

**Expected behavior**
to be able to see the background its hard to play the game without the background.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?** ruffle extension nightly 2021-06-22
**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).
 - ChromeOS Google Chrome

**Comment by eXponenta** [comment]
Ruffle not support BitmapData drawing API yet.
FP2 and newest use a lot of Bitmaps.

**Comment by relrelb** [comment]
Related to #290.

**Comment by Sonikkustar** [comment]
Looks like this works now. I'm getting some performance issues on my end, though that's probably an unrelated issue.

![image](https://user-images.githubusercontent.com/22226938/190014744-10b69453-bc45-440f-b5a1-80886e965630.png)

**Version Used**
ruffle-nightly-2022-9-10-windows-x86-64

**Comment by LukeSaward1** [comment]
![image](https://user-images.githubusercontent.com/55454721/193771048-e814bd94-75aa-45f0-a075-f07fade5c20b.png)
Still happens on Nightly 2022-10-04

**Comment by n0samu** [comment]
@LukeSaward1 My comment only applied to the desktop app. If this is occurring on web, it would be caused by something else. Maybe you have hardware acceleration disabled in your browser, for example.
