### ISSUE TITLE
Unsupported video codec type H263

### ISSUE THREAD

**Issue by Lonewolf953** [ruffle-rs/ruffle#4657]
There's a load of flash animations that cannot be loaded with ruffle and as far as I've seen all of them give the same error message in console on Firefox as well as Chrome

`Unsupported video codec type H263`

Would it be possible to add support for this type?

**Comment by torokati44** [comment]
The H.263 decoder is basically done, waiting for review and merging: #2173

**Comment by danielhjacobs** [comment]
> The H.263 decoder is basically done, waiting for review and merging: #2173

Tangential, but I've seen this message on a website I maintain, yet the H.263 branch doesn't make it work, but your VP6 branch does, which seems odd to me.

**Comment by torokati44** [comment]
That is rather strange... Have you enabled the `h263` feature? I'm not sure if it's enabled by default.
But how the VP6 branch could have fixed it if the error message is about H.263, I have no idea.

**Comment by torokati44** [comment]
Can you share a link to where you saw this?

**Comment by danielhjacobs** [comment]
> Can you share a link to where you saw this?

http://www.dnai.org/timeline/, click 1950-54, click the movie clip symbol that when hovered over says "Chargraff remembers", click "large" (or "Small", but not "Audio Only").

You'll see "Got error when post-instantiating video: Unsupported video codec type H263" in the console. Try the same process with an extension built from the VP6 branch, and the video will play.

If the H.263 feature is not enabled by default, I probably did forget to enable it, but it definitely did work with the VP6 branch alone.

**Comment by danielhjacobs** [comment]
Fairly recent, less than a month ago iirc, and the only changes since then have been fixing merge conflicts I think.

**Comment by torokati44** [comment]
With #2173 merged, this issue should be resolved, and hopefully can be closed. Can you verify, @Lonewolf953?

**Comment by Lonewolf953** [comment]
Yep, this is fixed now, thanks. Closing the issue ^^
