### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18

### ISSUE THREAD

**Issue by cmlad26** [ruffle-rs/ruffle#4664]
It does not work the update from 24.06.2021.

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/container.rs:780:18
    at Object.Y (https://static.arantius.com/ruffle/core.ruffle.dd338b559c70010995b3.js:1:20416)
    at __wbg_new_df6e6ab7a65c4c4d (https://static.arantius.com/ruffle/ruffle.js:1:35177)
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[1074]:0x2158e4
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[1397]:0x254528
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[3731]:0x3093cc
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[2936]:0x2eb05c
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[4026]:0x30e003
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[4056]:0x30e566
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[3932]:0x30cc09
    at https://static.arantius.com/ruffle/db77e9b3a74d57a3cbd2.module.wasm:wasm-function[4057]:0x30e59c
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: //static.arantius.com/games/8planet.swf
Param movie: //static.arantius.com/games/8planet.swf
Param quality: high
Param bgcolor: #FFFFFF
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://games.arantius.com/game.86.8+planet.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-12
Channel: nightly
Built: 2020-12-12T00:33:23.026Z
Commit: 4358e52af746929abcbbd5f05e577b98a0992fdd

**Comment by adrian17** [comment]
> It does not work the update from 24.06.2021.

Are you using the extension? The error message says it's using the december version (the self-hosted one).

**Comment by cmlad26** [comment]
Yes you are right, there is a glich when i change the version (first remove the old version and after that install - load the new one) sometimes reloads the version from December 2020.
Anyway i manage to reinstall the last version but the game does not work, there are no errors on the screen but the game does not pass to the next level.
You can find the game here (i think it is also a very god ideea to verify ruffle player i'm trying each new version of ruffle but still does not work).You don't need to install the geme, it is online:https://games.arantius.com/game.86.8+planet.html

Best regards,Cristian
    On Friday, June 25, 2021, 12:03:49 AM GMT+3, Adrian Wielgosik ***@***.***> wrote:  
 
 



It does not work the update from 24.06.2021.


Are you using the extension? The error message says it's using the december version (the self-hosted one).

**Comment by n0samu** [comment]
Closing in favor of #3271
