### ISSUE TITLE
I want to be able to download the flash game ruffle runs

### ISSUE THREAD

**Issue by Kxeo** [ruffle-rs/ruffle#4670]
Self explanatory. I want to download the flash game that I want to run.
(Is this a feature already?)

**Comment by danielhjacobs** [comment]
You mean when you open the swf in a new tab, correct? You can currently just temporarily disable the extension to download the swf, then re-enable it.

This was an issue that compounded itself, I'd say. There was some work put into adding an SWF download link context menu item in #1889, but it was written to always be enabled, which is often unwanted, so it was never merged, and the context menu was later disabled on mobile devices anyway: #3967.

It wasn't as big a deal until #4018, which has Ruffle take over when an SWF is loaded and stop the download.

**Comment by Kxeo** [comment]
No, I mean downloading the swf while playing it on the site that it was on. Was that what you meant?

**Comment by danielhjacobs** [comment]
That's not what I meant, so I mis-intrepreted your issue, but #1889 is about that (not merged - AKA not live).

You can do it currently though, just not through Ruffle.

> You can usually find the SWF if you keep the Network tab open and reload the page.

If you then open the link ending with .swf in a new tab with the Ruffle extension disabled, the swf will download.

**Comment by adrian17** [comment]
We've added a context menu option to download the playing SWF :)
