### ISSUE TITLE
[Web] Chrome can add or change the title attribute

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#468]
With Flash, if an object tag has a "title" attribute, then this title will be displayed when the cursor is over the file.

With Ruffle, the behavior will depend on the browser. Firefox will be a good boy while Chrome will act as below:

- If the cursor always stays outside the area of the file until Ruffle has finished loading, then everything will be fine.

- If the cursor gets inside the area and goes back outside again before the end of the loading, Chrome will remove the title attribute. This should not really be an issue for anyone though.

- Finally, if the cursor is still inside the area when Ruffle starts, Chrome will replace or even add a title attribute with value "Adobe Flash Player" which is then passed to Ruffle. This one can be pretty much annoying.

Attached a sample:
[chrometitle.zip](https://github.com/ruffle-rs/ruffle/files/4382357/chrometitle.zip)

**Comment by Herschel** [comment]
I'm having a little trouble reproing this one; in your test page, do I wait until the timeout kicks in and move the cursor onto the element as Ruffle gets swapped in? What version of Chrome?

**Comment by Toad06** [comment]
Version 80.0.3987.149 (64 bits)


Actually, this is happening when Flash is blocked or requires a user gesture. In these cases, Chrome should show one of the following messages instead of the Flash file:
"Adobe Flash Player is blocked" or "Click to enable Adobe Flash Player"

If you move the cursor on the area where Chrome displays this text, it should show "Adobe Flash Player". Now, if you don't move the cursor away before Ruffle loads, the title will be "Adobe Flash Player". Otherwise, it will be blank.

**Comment by Herschel** [comment]
I see it now, thanks!

Seems like Chrome has some weird behavior where it totally wipes out the title attribute when you mouseover the Flash blocker (you can see it disappear in the inspector)... Since the attribute is totally gone, I'm not sure if there's a way for us to recover it. This might just be a WONTFIX and hope that this behavior disappears when Flash is totally removed.

**Comment by Herschel** [comment]
I guess we could at least special case the "Adobe Flash Player" and throw it out so it doesn't pop up. :-)

**Comment by Toad06** [comment]
Yes, probably not worth the effort anyway (I doubt anyone would want a title being shown over his file or use the value of this attribute to make stuff using Javascript). Also, I've just tested on a live site and even if Ruffle is loaded a bit lately (eg. using a window.onload event), it's really difficult to reproduce the issue if Ruffle has already been cached from a previous load.

Yes, this would be a good idea to throw the attribute out in this case. I will check from time to time if Chrome changes his behavior.
