### ISSUE TITLE
Dynamic Insertion Still Doesn't Work With Extension

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#469]
Even the latest build of the extension, which was built with #466 merged in, still doesn't work with dynamically inserted flash embeds. I verified that the dynamically inserted embed does in fact trigger a mutationobserver event handler(using https://github.com/Justin-CB/DOMwatcher-test ), & that it still doesn't work with that extension removed. I also verified that the embed works if statically inserted by setting ruffle's "This extension can read & modify site data" to "When you click on the extension" & clicking on ruffle after the flash embed was loaded: it worked. I also noticed that #463 appears to be resolved.

**Comment by Herschel** [comment]
Seems to be working for me on the 03/26 nightly build on the site from the original issue (https://justinbesterportfolio.000webhostapp.com/DArts/Animate/ghost.php) -- possibly you grabbed a build from the interval before the change was integrated (the nightly builds only happen once every 24 hrs).

Could you try with this version?
https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/extension/ruffle_extension_2020-03-26_774aa59.zip

**Comment by Justin-CB** [comment]
Yes, it works now, my mistake.
