### ISSUE TITLE
Incorrect rendering in "FlashSavingTestKit.swf"

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#47]
This SWF completely renders incorrectly.  To start, there looks to be issues with the text rendering.

http://www.stevenchorney.com/del/FlashSavingTestKit.swf
(courtesy of @BracerJack)

**Comment by WillBrindle** [comment]
FYI link is dead :(

**Comment by Herschel** [comment]
[FlashSavingTestKit.zip](https://github.com/ruffle-rs/ruffle/files/3688361/FlashSavingTestKit.zip)

**Comment by Herschel** [comment]
Noticed this while investigating #77. DefineFont3 coordinates are 20x the size of DefineFont1/2. Fixing this fixes this giant text. The rest of this file is AS3, which will come later (see the roadmap).
