### ISSUE TITLE
Error on https://gamesofdesired.com/c0dc03c2522ffe180af56a684caf5563-mom-chun-li-hentai/index.html

### ISSUE THREAD

**Issue by wanghan2222** [ruffle-rs/ruffle#4703]
#Error Info nError名称：Error nError消息：惊慌失措地在`Result：：unack()‘上对“错误”值：JsValue(TypeError：未能获取nTypeError：未能获取)，web/src/Naviator.rs：189：18 nError堆栈：n``nError：慌乱at’Result：：un环绕()‘对`Err’值：JsValue(TypeError：未能获取nTypeError：未能获取)，Wwbg.__wbg._wbg_new_df6e6ab7a65c4c4d(https://gamesofdesired.com/assets/ruffle/ruffle.js:1:7026)n at std：：sync：：once：：Once：：call_once：：{{closure}}：：h6e694fc45f651103(wasm-function[1085]：0x28c132)n at std：：sync：：once：：Once：：call_inner：：h99e47643887ee5a5(wasm-std：：sync：：once：：Once：：call_inner：：h99e47643887ee5a5[960]：0x26329f)n：ops：：function：：FnOnce：：call_once{{vtable.shim}}：：hb552ca3003b47989(wasm-function[3856]：0x41f24c)n at std：：panicking：：rust_panic_with_hook：：h03201bc01a0ed891(wasm-Function[3008]：0x3bacee)n at锈蚀_BEGIN_unwind(wasm-function[4064]：0x424b97)n在核心：：恐慌：：惊恐：：fmt：：hd44f353696296fec(wasm-function[4212]：0x42b594)n位于核心：：选项：：Expect_NONE_FMT：：hf7dab2706f1a5551(wasm-function[3448]：0x40d618)n in<core：：from：FROM：FROM：FROM<T>as core：：future：：future：：Future>：：poll：：ha37798b6e2eb822f(wasm-function[579]：0x19b250)n at<core：：Future：：FROM<T>as core：：future：：future：：Future>：：poll：：h120ccdeae3267ee4(wasm-Function[519]：0x177b85)n`n#Player信息nAllowscript Access：true nPlayer类型：Object nSWFURL：https://v8p5i7f9.nSWFURLSsl.hwcdn.net/games/swf/b/7/f/b7f801d723c6a7a9bd55d5ea6f5580c3/b7f801d723c6a7a9bd55d5ea6f5580c3.swf nParam电影：https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/7/f/b7f801d723c6a7a9bd55d5ea6f5580c3/b7f801d723c6a7a9bd55d5ea6f5580c3.swf nParam质量：高nParambgcolor：#000000 nParamPlay：真nParamWMode：Window nParamScale：DisplayallnParam菜单：true nParamdevicefont：false nParamDevicefont：False nParamDevicefont：false nParamScale未定义的n#页面信息nPage网址：https://gamesofdesired.com/c0dc03c2522ffe180af56a684caf5563-mom-chun-li-hentai/index.html nSWFURL：https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/7/f/b7f801d723c6a7a9bd55d5ea6f5580c3/b7f801d723c6a7a9bd55d5ea6f5580c3.swf n n#Browser Info nUseragent：Mozilla/5.0(linux；安卓10；zh-cn；Redmi Note 8 Build/QKQ 1.200114.002)AppleWebKit/537.36(KHTML，类似壁虎)版本/4.0 Chrome/77.0.3865.120 MQQBrowser/11.6 Mobile Safari/537.36 COVC/045635

**Comment by Poopooracoocoo** [comment]
QQ Browser is based on a version of Chromium that is unsupported by Ruffle. View the wiki for further information. If you can repro with a new version open a new issue.
