### ISSUE TITLE
Game runs but missing visual elements

### ISSUE THREAD

**Issue by josephr333** [ruffle-rs/ruffle#4747]
**Describe the bug**
http://www.freewebarcade.com/game/hex-empire/

Game loads and plays correctly. However, the skins for land/sea tiles and for each player's tokens do not display, so the player has no idea of what is going on. It seems to me that some image resources are being lost when the game loads now.
![image](https://user-images.githubusercontent.com/86856417/124330454-4f518880-db42-11eb-9f8f-d8f7c0fe6664.png)

**Expected behavior**
When the map initially loads, some of the tiles should be land and others should be water - rather than them being all light green as currently happens. The movable unit tiles should take the color of the player that controls them rather than all being green.
![image](https://user-images.githubusercontent.com/86856417/124330428-42349980-db42-11eb-99ba-749da5adf9cb.png)

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).
Using Chrome Version 91.0.4472.124 on Windows 10

**Comment by jwblangley** [comment]
+1

**Comment by FallCheetah7373** [comment]
+1

**Comment by Risu** [comment]
In recent version the background map is now rendered. But still territory marker is solid yellow for all nations.

**Comment by Davidmcfaul123** [comment]
Any update on this?

**Comment by selankon** [comment]
How it can be fixed?

**Comment by FallCheetah7373** [comment]
using the last version of flash player from flatpak doesn't has this issue...it is ruffle specific.

**Comment by josephr333** [comment]
indeed. and +1 to the fixes in the recent ruffle version, but without unit and map colors it becomes a pretty serious memory test :)

**Comment by Risu** [comment]
Fixed in nightly 2023-07-18. Game seems fully playable.

**Comment by selankon** [comment]
Is  there any website running this with the fix?

**Comment by selankon** [comment]
I finally downloaded the `swf` from a web site, for example flasharch.com, and then I run it on https://ruffle.rs/demo/ and runs like a charm
