### ISSUE TITLE
Ruffle ignores content inside iframes

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#475]
Ruffle will always ignore any Flash content inside iframe tags. Though this makes sense for the self-hosted (JS) build, this is more unexpected from the extension.

Attached a sample:
- Add a JS build to "ruffle/", then run "web.html", notice Ruffle does not convert the file.
- Run "extension.html" with the extension, notice the same behavior.
- "workaround.html" is an attempt to fix the issue on the JS build (actually it just duplicates the Ruffle configuration on the parent page and appends it to each iframe).

[iframeruffle.zip](https://github.com/ruffle-rs/ruffle/files/4389981/iframeruffle.zip)

Also, I haven't tried, but I would expect the same behavior with the old frameset / frame tags.

**Comment by Justin-CB** [comment]
I could probably add code to apply polyfills using window.frames, unless someone else wants to do this.

**Comment by Justin-CB** [comment]
Also, I found that coolmathgames.com actually does this. Most of the games on that site are HTML5 nowadays, but all the remaining flash games are in an iframe.

**Comment by Justin-CB** [comment]
I will start coding this after my MIME type pull request is accepted unless someone else has an objection/wants to do this themself.

**Comment by Justin-CB** [comment]
I've discovered that adding a key to the extension's manifest("all_frames": true) coupd potentially resolve this issue for the extension. Should I still attempt to code a fix for the web or would it be better to simply note that the ruffle code should be loaded into the (i)frames with the flash content rather than from the top level document?

**Comment by Justin-CB** [comment]
@Toad06 Would you be willing to test the fix I have written? It's available from my fork( https://github.com/Justin-CB/ruffle ).

**Comment by Justin-CB** [comment]
I've got the example working(web.html):
[iframeruffle.tar.gz](https://github.com/ruffle-rs/ruffle/files/4497486/iframeruffle.tar.gz)

**Comment by Justin-CB** [comment]
The fix has been merged now.

**Comment by Herschel** [comment]
Fixed by #483
