### ISSUE TITLE
Onda Educa: Implement "full-screen

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#4785]
**Describe the bug**
As of current Ruffle builds, stage.fullScreenState remains unimplemented Onda, as an example , require this for its fullScreen buttons present in the jumpoff screen in almost all activities.

**Expected behavior**
Clicking on the fullscreen buttons in the activity launches should put them into fullscreen, just as the context menu in the web builds does.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
This would apply to desktop and web as the implementation needs to happen in core.

**What platform are you using?**
Last tested with 7/3 self-host, FF and Chromium extensions, as well as self-host.

Some notes on what is needed for this task:

Mike:
- Add the fullScreenState property to  core::avm1/avm2::globals::Stage; this will forward to the property on the Stage display object:
- core::display_object::Stage::fullScreenState member to the Stage display object. This is the code that actually manages the state. Whenever this is set to fullscreen, call:
- UiBackend::set_fullscreen, which actually tells the desktop/web player to enter fullscreen mode.

Adrian and szooloo:
We've had some games reported as trying to use the fullscreen FS command to also accomplish fullscreen.
This should be done as another ExternalInterfaceProvider implementation, similar to what is already there for JS. it already has a method for handling fs commands.

**Comment by ousia** [comment]
I think this is already mentioned in #4258.

**Comment by ousia** [comment]
@hatal175, I wonder whether you would be interested in implementing the remaining parts of `Stage` (#274), which are mainly related to full screen mode.

Many thanks for your contributions.

**Comment by hatal175** [comment]
Perhaps. Still has to finish a current pull request.

**Comment by ousia** [comment]
@sombraguerrero, could you check whether #5137 fixed this issue?

**Comment by sombraguerrero** [comment]
@ousia Half way. The buttons will enter full screen now, but they will not exit.

**Comment by sombraguerrero** [comment]
@ousia If you saw my previous comment, disregard.
Yes, it does appear that #5137 has resolved this!
