### ISSUE TITLE
Default vertical scrollbar doesn't work if text changes programmatically after creation

### ISSUE THREAD

**Issue by midgleyc** [ruffle-rs/ruffle#4792]
**Describe the bug**
Flash provides a "scrollbar" element `FScrollBarClass`. This is used in the SWF in #4217, and the "Causes and Prevention" error and "Hallmarks of Cancer" errors mentioned in https://github.com/ruffle-rs/ruffle/pull/4698#issuecomment-869195107 (the latter has a different skin for the scrollbar).

[scrollbar.zip](https://github.com/ruffle-rs/ruffle/files/6775337/scrollbar.zip)

If the text changes programmatically after creation, vertical scrolling doesn't work. Confusingly, horizontal scrolling still works. The text is an input box; if you type some characters the scrollbar will work.

**Expected behavior**
Scrollbar should work.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Desktop

**What platform are you using?**
Windows Desktop

**Comment by midgleyc** [comment]
Requires `Object.watch` to work on `TextField.text`.

**Comment by danielhjacobs** [comment]
I may be mistaken, but I believe TextField.text is a virtual property, which is why it was unimplemented: #825.

**Comment by midgleyc** [comment]
Setting `textField.text` calls `call_setter` in `script_object.rs` (because `text` is on the prototype, not the object, so `!self.has_own_property`). This doesn't call watchers.

**Comment by danielhjacobs** [comment]
While it isn't directly related to the issue, I figured I'd note, even though I could swear it didn't work with the scrollbar branch before it was merged, the scroll buttons on "Hallmarks of Cancer" are working with the latest extension (2021-07-11). The "Causes and Prevention" scroll bar still isn't working because of this issue though.
