### ISSUE TITLE
Balls to the Brawl - Doesn't advance when enemy ._x == null

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#4793]
https://www.newgrounds.com/portal/view/734315/format/flash?emulate=flash

Once you defeat your first batch of enemies, the level fails to advance. I talked to FuturecopLGF about it and it appears to be how the game is checking for null values. Here is his description:

"In terms of playing through the game, yes, I'm seeing the same problem you're seeing where the screen doesn't unlock and progress with GO> when killing the first enemy. Not localized to the first level, either, seems to be happening for them all, whether enemies start on the initial screen or spawn within a bit of initial walking.

Let's see, digging through my old files...I'll try to sum it up. Each level is a frame on the timeline that the header goes to and stops on, where something like this is running on that frame:

---------

HandleEnemies = function()
{

  //Monsters in scene holds references to all monsters you're currently fighting against
  for (counter=0;counter<MonstersInScene.length;counter++)
  {
  
    //run the reference AI function that is assigned to them
    MonstersInScene[counter].gotoFunction();
    
    //determine if a monster has been killed but still exists in the array
    if(MonstersInScene[counter]._x == null)
    {
    
      //monster is dead and gone, remove from array
      MonstersInScene.splice(counter,1);
      counter = 0;
      HandleChainKill();
      
      if (MonstersInScene.length == 0)
      {
      
        //last enemy defeated, display GO mark
        _root.attachMovie("GOSIGN", "GOSIGN", 999993, {_x:860, _y:400});
        
        //determine if was a perfect round
        if (perfectHits == 0)
        {
        
          points = points + perfectpoints;
          _root.attachMovie("PARFECT", "PARFECT", 999995, {_x:80, _y:280});
        
        }
        perfectpoints = 0;
        perfectHits = 0;
        HandleVariation();

      }
    }
  }
}

onEnterFrame = function()
{
  //tons of handler functions which handle triggers, handle velocities, handle depth rearrangement, etc, which includes
  HandleEnemies();
}

---------

So basically, every frame the HandleEnemies function is being called, which runs the AI code for every monster (enemy) in the scene and also removes monsters from the scene when they have been beaten. Well, technically the monsters have already removed themselves from the scene by calling removeMovieClip on themselves, this is just the function noticing that they've been removed and doing cleanup by removing their null reference from the array. Once it detects that all monsters in the scene have been removed by seeing the empty array, it should spawn the GO sign and unlock progress. Obviously, something has gone wrong.

My guess as to what is going wrong...maybe the way that I was 'detecting' whether a monster referenced in the array no longer exists was really dumb and is being misinterpreted, being the line if(MonstersInScene[counter]._x == null). Other potential culprits might be the splice function being misinterpreted and not properly adjusting the array, as maybe splice doesn't exist in Ruffle? Also, there's the fact that I'm calling the monster's goToFunction when they might have already been reduced to null and Ruffle might be, instead of ignoring that bad code like Flash did, stopping the code in its tracks there with an error, not running the rest of the function."

**Comment by adrian17** [comment]
```
//determine if a monster has been killed but still exists in the array
if(MonstersInScene[counter]._x == null)
```

At a glance, this sounds similar to:
https://github.com/ruffle-rs/ruffle/issues/3839
https://github.com/ruffle-rs/ruffle/issues/993#issuecomment-675182938
