### ISSUE TITLE
No way to stop currently streaming swf

### ISSUE THREAD

**Issue by thebestnom** [ruffle-rs/ruffle#480]
Im currently trying to do a file list than play by click, and ruffle just don't stop the already playing one... so I'm refreshing page everytime...

**Comment by Herschel** [comment]
#487 will add code to stop the audio once the Ruffle DOM element is removed

**Comment by thebestnom** [comment]
any news on the PR?

**Comment by thebestnom** [comment]
Just tested that this is working, thanks!

**Comment by Herschel** [comment]
Sorry for the delay, thanks for the report!
