### ISSUE TITLE
Error on https://www.play-arcade.de/ibproarcade.php?&act=Arcade&do=play&gameid=283/mahjongg-3d-004-classic-abstract.html

### ISSUE THREAD

**Issue by DERLEU** [ruffle-rs/ruffle#4832]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 20 5f 5f 5f @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 20 5f 5f 5f @+0
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.play-arcade.de/ibproarcade.php?&act=Arcade&do=play&gameid=283/mahjongg-3d-004-classic-abstract.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by danielhjacobs** [comment]
This issue is very old, but in general, this error message usually means a cached version of Ruffle is interfering with a newer version. If encountering this issue, it's best to clear your cache and reload the page.
