### ISSUE TITLE
youkeepdying.spacebar.org doesn't work properly

### ISSUE THREAD

**Issue by agoode** [ruffle-rs/ruffle#4834]
**Describe the bug**
http://youkeepdying.spacebar.org/

When moving between rooms, the player doesn't line up properly and the collision detection seems offset by some amount. This makes it impossible to start the game properly.

ruffle move to 2nd screen (incorrect behavior): 
![Screenshot from 2021-07-11 17-30-06](https://user-images.githubusercontent.com/59842/125210459-f2568080-e26d-11eb-8490-59494ea071c9.png)

flash player move to 2nd screen: 
![Screenshot from 2021-07-11 17-30-09](https://user-images.githubusercontent.com/59842/125210469-ff736f80-e26d-11eb-9e38-eaebc9a1583f.png)

ruffle can't start the game:
![Screenshot from 2021-07-11 17-30-54](https://user-images.githubusercontent.com/59842/125210480-0ef2b880-e26e-11eb-90df-927fbb2f0099.png)

on paper screen (ruffle, character is standing on invisible object):
![Screenshot from 2021-07-11 17-34-42](https://user-images.githubusercontent.com/59842/125210521-54af8100-e26e-11eb-9be9-f021b3197233.png)

on paper screen (flash player, correct behavior):
![Screenshot from 2021-07-11 17-34-44](https://user-images.githubusercontent.com/59842/125210541-609b4300-e26e-11eb-8721-07cbb9a0a58a.png)

Source code is available at https://sourceforge.net/p/tom7misc/svn/HEAD/tree/trunk/youkeepdying/

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

desktop

**What platform are you using?**

Linux, from git

**Comment by Toad06** [comment]
Collisions appear to work as of nightly-2023-03-02, assume fixed by #9447.
