### ISSUE TITLE
Oiligarchy has these annoying black areas all over the game 

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#4955]
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.

there are large annoying black areas on this oil simulation game thus making the game hard to play.
https://www.addictinggames.com/strategy/oiligarchy

If this is a visual issue, please attach a screenshot of the problem.
![oilblack dots](https://user-images.githubusercontent.com/64484245/127728623-02f65cd5-1306-48ef-9305-87b08c4b7c9f.png)
![oil black dots 2](https://user-images.githubusercontent.com/64484245/127728630-d684c1dc-5295-41d8-adf8-9b419fdcb2b3.png)

**Expected behavior**

for the game to function as normal without huge black areas hindering the playablility of the game

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?** ruffle extension  nightly 2021-07-29

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).
 - ChromeOS Google Chrome

**Comment by Lord-McSweeney** [comment]
I cannot reproduce this issue in the latest versions of Ruffle.
