### ISSUE TITLE
Serious error loading Ruffle: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by lordwars** [ruffle-rs/ruffle#497]
When I run the script (web-demo) in my website I got this error:
`Serious error loading Ruffle: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
`
in my Chrome Console, how can I fix it? (I have been tried to change my embed type to wasm, without success)

**Comment by mdonoughe** [comment]
What are you using to host the wasm files? The server needs to send the correct mime type in the Content-Type header: https://rustwasm.github.io/book/reference/deploying-to-production.html

**Comment by mdonoughe** [comment]
See also #400

**Comment by Herschel** [comment]
Closing in favor of #400; you need to configure your web server to serve .wasm files with "application/wasm" MIME type. The issue provides info on how to configure Apache to do this, but the method will be different for other web servers.
