### ISSUE TITLE
Full screen in a mobile device

### ISSUE THREAD

**Issue by DeBosh185** [ruffle-rs/ruffle#4980]
Hi!

Thank you to everyone who participates in the development of the Ruffle plugin.
In earlier versions of Ruffle, it was possible to turn on the game in full screen on a mobile device, now this does not work.
It would be nice to fix this.

Thanks

**Comment by danielhjacobs** [comment]
This was disabled as a result of #1972. I tried designing a middle-ground compromise in #5000, but I'm not sure it's going to be approved as it makes games where right click on mobile messes with controls slightly more annoying to use.
