### ISSUE TITLE
npm run bootstrap did not install extension package requirements

### ISSUE THREAD

**Issue by hatal175** [ruffle-rs/ruffle#5001]
**Describe the bug**
Tried following build instructions by running npm run bootstrap and npm run build but typescript compile failed on missing packages (@tsconfig/recommended and @types/chrome for example).
Build finished successfully after manually running npm install in extension directory.

**Expected behavior**
just run and build magically works.

**What platform are you using?**
Tried compiling on windows.

**Comment by relrelb** [comment]
Strange, this doesn't happen to me even after cleaning `node_modules` etc.
I'm on Windows 10, Node.js 16.7.0 and npm 7.6.3.

**Comment by hatal175** [comment]
Must have done something wrong then.
