### ISSUE TITLE
[Extension] coolmathgames.com flash detection doesn't work with ruffle

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#501]
This is independent from the iframe issue: if flash detection worked properly, the "iframe1" tag would change to an "iframe" & we would see the "Plugin Not Supported" message.

**Comment by Dinnerbone** [comment]
Detection code:
```javascript
function checkIfFlashIsEnabled() {
    var ie_flash;
    try {
        ie_flash = (window.ActiveXObject && (new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) !== false)
    } catch(err) {
        ie_flash = false;
    }
    var _flash_installed = ((typeof navigator.plugins != "undefined" && typeof navigator.plugins["Shockwave Flash"] == "object") || ie_flash);
    if (typeof _flash_installed == "undefined" || !_flash_installed) {
        return false;
    } else {
        return true;
    }
}
```

Looks like the "best" way here would be to pretend to be Shockwave Flash inside of `navigator.plugins`.

**Comment by Justin-CB** [comment]
Do you think that ruffle will ever support polyfilling the ActiveXObject (IE flash)?

**Comment by Herschel** [comment]
We already pretend to be Flash in `navigator.plugins`, the issue is that the extension needs to inject the Ruffle plugin spoof before the detection scripts run on that page. This is difficult with the way the extension works currently (see #448).

**Comment by Justin-CB** [comment]
We could potentially add the plugin polyfill code directly to lv0.js as non-async code.

**Comment by Justin-CB** [comment]
I've written a working fix for this, but I'd like to hold off on it until my frame pull request is resolved.
