### ISSUE TITLE
I only see a grey screen

### ISSUE THREAD

**Issue by siky112** [ruffle-rs/ruffle#5036]
**Describe the bug**
When I use the extension, it only shows a grey screen. Audio works.

**Expected behavior**
The extension shows what's actually happening.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Extension.

**What platform are you using?**
Web version, using Edge.

**Comment by danielhjacobs** [comment]
What page?

**Comment by siky112** [comment]
http://www.neopets.com/games/game.phtml?game_id=1191&size=regular&quality=high&play=true
Also, other pages on Neopets break too.

**Comment by danielhjacobs** [comment]
Ah, it's AS3 and not yet supported: #1368

**Comment by siky112** [comment]
Oh, ok then.
