### ISSUE TITLE
× ｢wdm｣: Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by adsy2010** [ruffle-rs/ruffle#505]
I have attempted to launch demo and selfhosted with the following commands:
```

npm install
npm run build
```
or 
`npm run serve`

The error in the title comes from both routes and although serve runs, it doesnt display anything and I only receive this message:

`i ｢wdm｣: wait until bundle finished: /`

I am running npm version 6.14.4 and node 12.16.2 but have tried with 6.4.1 for npm and 10. something or other on node.

Any suggestions or is there an issue at the moment?

Verbose error

```
> ruffle-demo@0.1.0 serve C:\Users\...\Downloads\ruffle-master\web\demo
> webpack-dev-server

Building production...
�  Checking for wasm-pack...

ℹ️  Installing wasm-pack

× ｢wdm｣: Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\...\Downloads\ruffle-master\web\demo
i ｢wdm｣: wait until bundle finished: /
```

**Comment by Dinnerbone** [comment]
What platform are you trying to build on? Did you install both wasm-pack and rust in addition to node?

**Comment by adsy2010** [comment]
wasm-pack appears to auto install (as you can see from the edit). Rust however is not mentioned in the documentation.

**Comment by Dinnerbone** [comment]
The first line under "Building from source" is "Follow the official guide to install Rust for your platform." - but you're right, perhaps we can make that more clear :)

**Comment by adsy2010** [comment]
I'll give it a go and let you know the result

**Comment by adsy2010** [comment]
I didn't wait long enough. Its compiling properly now.

**Comment by Dinnerbone** [comment]
Great news! Please let us know if you have any more questions or issues. We definitely could stand to improve documentation and feedback from first-time setups is so very useful for that.
