### ISSUE TITLE
Nightly 2021-08-12 xpi does not support Firefox 91

### ISSUE THREAD

**Issue by bowknot** [ruffle-rs/ruffle#5053]
Nightly 2021-08-12 xpi does not support Firefox 91

![剪贴板02](https://user-images.githubusercontent.com/11291839/129352935-3f8e1d1f-66b7-492c-bed9-48677486b86e.png)

**Comment by torokati44** [comment]
That's "only" a warning. I remember getting it on older versions of both Ruffle and Firefox as well. The extension should still work as intended despite this.

**Comment by relrelb** [comment]
Thanks for the report!
This warning should be resolved in the upcoming nightly, so I guess we're all done here and closing.
