### ISSUE TITLE
Serious error loading Ruffle: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by adsy2010** [ruffle-rs/ruffle#506]
After successfully setting up an npm served page, I decided to move on to getting ruffle working on a locally hosted linux virtual machine using apache.

I ran the npm run build command successfully and found the files required to include on a webpage a in the dist directory within the selfhosted directory. 3 files are there:

- a .wasm file
- a core.ruffle.****.js file
- and a ruffle.js file

I copied these to the root/dist directory on the apache server, copied the base .html file from the demo directory (just a basic page to test with) and then added the following from the documentation to the bottom of the html file:

```
  <script>
    window.RufflePlayer = window.RufflePlayer || {};

    window.addEventListener('DOMContentLoaded', (event) => {
      let ruffle = window.RufflePlayer.newest();
      let player = ruffle.create_player();
      let container = document.getElementById('main');
      container.appendChild(player);
      player.stream_swf_url("myfile.swf");
    });
  </script>
  <script src="./dist/ruffle.js"></script>
```

3 Errors are thrown on running the page. The first is in the subject but I will copy it below too:

`Serious error loading Ruffle: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`
`Serious error occured loading SWF file: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`
`Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

So I get the idea its something to do with loading the wasm file but I am at a loss as to what I need to do to make sure this works. If its as simple as installing wasm on the virtual machine, I'll try that first.

I have found the 2 functions within the compiled js throwing the errors and they are below:

```
        async stream_swf_url(e) {
            try {
                if (this.isConnected && !this.is_unused_fallback_object()) {
                    let t = new URL(e, window.location.href).toString();
                    console.log("Loading SWF file " + e);
                    let _ = await fetch(t);
                    if (_.ok) {
                        let t = await _.arrayBuffer();
                        await this.play_swf_data(t), console.log("Playing " + e)
                    } else console.error("SWF load failed: " + _.status + " " + _.statusText + " for " + e)
                } else console.warn("Ignoring attempt to play a disconnected or suspended Ruffle element")
            } catch (e) {
                throw console.error("Serious error occured loading SWF file: " + e), e
            }
        }

        async play_swf_data(e) {
            if (this.isConnected && !this.is_unused_fallback_object()) {
                console.log("Got SWF data"), this.instance && (this.instance.destroy(), this.instance = null, console.log("Ruffle instance destroyed."));
                let t = await this.Ruffle.catch((function(e) {
                    throw console.error("Serious error loading Ruffle: " + e), e
                }));
                this.instance = t.new(this.canvas, new Uint8Array(e)), console.log("New Ruffle instance created.")
            } else console.warn("Ignoring attempt to play a disconnected or suspended Ruffle element")
        }
```

I had a look but suspect theres nothing wrong with the code, more likely my setup. Can someone make a suggestion?

**Comment by Dinnerbone** [comment]
You need to configure your web server to serve WASM files correctly. There's a tracking issue on improving the documentation and possibly detecting this and giving better errors over at #400.

You need to configure any `.wasm` files to be served with the type `application/wasm`

**Comment by Dinnerbone** [comment]
I've updated the docs with a bit more info about this, and since it looks like you're using Apache then it should help.
https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-wasm-mime-type

**Comment by adsy2010** [comment]
Thanks Dinnerbone. I have got it working but it was a little more than suggested. I'm running Ubuntu which required adding the mime type to the mime types file at /etc/mime.types followed by restarting the apache server. Might want to add that to the documentation too!
