### ISSUE TITLE
Full screen for mobile devices

### ISSUE THREAD

**Issue by DeBosh185** [ruffle-rs/ruffle#5092]
Hi!

Please return the full screen for mobile devices.

Thanks

**Comment by torokati44** [comment]
I think https://github.com/ruffle-rs/ruffle/pull/5000 would help with this.

**Comment by relrelb** [comment]
How is this issue different from #4980?

**Comment by DeBosh185** [comment]
> How is this issue different from #4980?

This release says that the problem should be solved and not disable the function, the full screen is necessary on a mobile device.

**Comment by relrelb** [comment]
> > How is this issue different from #4980?
> 
> This release says that the problem should be solved and not disable the function, the full screen is necessary on a mobile device.

I might have been missed something, but it seems to be already said in #4980. I don't see any reason to keep both #4980 and this issue open. Can you please close this issue, or correct me if I'm wrong?

**Comment by relrelb** [comment]
Closing as #4980 is fixed now.
