### ISSUE TITLE
web: Vector Tower Defense - Game bug

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#5095]
One of the more classic Tower Defense Games are not working correctly.

https://www.spiele-umsonst.de/vector-tower-defense-t107.html

You can place the tower but they all just shoot at a certain spot and does not hit or harm the enemies.

**Comment by desertking** [comment]
Damn this bug is still alive...

**Comment by n0samu** [comment]
Also reported in #5711
