### ISSUE TITLE
Bunni: How we first met Flash game from childhood

### ISSUE THREAD

**Issue by 1zz1e** [ruffle-rs/ruffle#5110]
http://replyall-bunni.s3-website.us-east-2.amazonaws.com/

Flash game not loading. Please help, I can't figure out how to get it to properly load (using desktop extension on chrome) 

I have tried to use this, and have spent hours trying to get this game to work

https://archive.org/details/bunni-how-we-first-met-flash-game.
(^attemps to fix it)

**Comment by adrian17** [comment]
I opened it with the extension and immediately got this:
![2021-08-23_17-55-57](https://user-images.githubusercontent.com/4729533/130479395-24a82ac7-edb4-492e-8b9a-826274109650.png)
AVM2 support in Ruffle is currently extremely barebones so this game won't be supported for some time still - sorry.

**Comment by dginovker** [comment]
Ruffle is saying it's AS3 now? :thinking: 
![image](https://user-images.githubusercontent.com/32943174/181490394-12db7c86-f043-4cc7-8e59-07aebe8136cf.png)

**Comment by n0samu** [comment]
Yes, Ruffle's ActionScript 3 message has been changed to be more clear, but that was supposed to be the implication since the beginning. Closing in favor of #1368
