### ISSUE TITLE
Error on https://www.quizland.co.uk/index.php?action=arcade;sa=play;game=535

### ISSUE THREAD

**Issue by Underdog-01** [ruffle-rs/ruffle#5114]
# Error Info
Error name: TypeError
Error message: WebAssembly.instantiate(): Argument 0 must be a buffer source or a WebAssembly.Module object
Error stack:
```
TypeError: WebAssembly.instantiate(): Argument 0 must be a buffer source or a WebAssembly.Module object
    at https://www.quizland.co.uk/Themes/default/arcade_scripts/ruffle/ruffle.js:1:37174
    at n (https://www.quizland.co.uk/Themes/default/arcade_scripts/ruffle/ruffle.js:1:37257)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.quizland.co.uk/Games/angryAS3mrX/angryAS3mrX.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.quizland.co.uk/index.php?action=arcade;sa=play;game=535;reload=8090;#playgame

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-08-14
Channel: nightly
Built: 2021-08-14T00:10:27.353Z
Commit: 5dee7f163c4ba033ba747079533fd4d588e679d9
Is extension: false

**Comment by Poopooracoocoo** [comment]
Note: requires site login. registration is free.

But SWF and URL now 404 so closing.
