### ISSUE TITLE
Ruffle not playing nice with Web Components polyfills for non-WebComponents-capable browsers

### ISSUE THREAD

**Issue by dilworks** [ruffle-rs/ruffle#5118]
As per issues #2568 and #3729, it's clear that Web Components support is required for the self-hosted version of Ruffle (concretely: Custom Elements and Shadow DOM). But there is still a not so insignificant amount of users using browsers that are NOT OLD, OBSOLETE AND OR/OUTDATED, yet that they don't support Web Components just yet, as they're usually projects with little manpower, and Web Components is a rather big, complex, and living (!!!) specification that it's quite hard to implement.

Fortunately, we have [the official polyfills from the Web Components project](https://github.com/webcomponents/polyfills), which are meant for these cases, to fill in the gap while browsers do the heavylifting to bring support for Web Components and keep its users happy. As an user of one of such browsers (SeaMonkey 2.53.9b1, which is the current beta/preview version - the latest stable version is 2.53.8.1, and I'm on Debian 10/11, BTW), while Web Components support is on the roadmap, it's still quite far away for a number of reasons (but they're working on it, slowly but steady... unfortunately the spec seems to be an "all-or-nothing" issue as pointed by Pale Moon's lead developer), so we absolutely need the use of the polyfills.

Having said that, I decided to check how far we could get with Ruffle on our "not cutting edge" browsers, with the use of the respective Web Components polyfills. I suspect this hasn't been a widely tested setup (if at all), but the results are surprising.

Testcase here: https://jsfiddle.net/rjmhcpkq/
Screenshots: https://imgur.com/a/utn5sCv
(The animation in question is IOSYS' "Cirno's Perfect Math Class", which is known to work fine on Ruffle, but then, it's about 15 years old!)

With the use of the WC polyfills, I could get Ruffle to load our test SWF on Seamonkey, but that's as far as I could get. The animation doesn't respond to interactivity: trying to click the (9) to start the movie does nothing, as not even the hover event (which should change the "9" to "Go") works. Even worse, the animation doesn't render inside its container element, instead it defaults to fill the entire window area, obscuring the rest of the elements of the page, as evidenced on the screenshots. For reference, on the same linked album, screenshots from Firefox 78 ESR (the version available on Debian 10) are included - since this one has proper support for Custom Elements and Shadow DOM, the polyfills get out of the way and everything works as intended. So close, yet so far, in other words. UPDATE: Testing it with other .SWFs lacking interactivity of the same vintage (more old Touhou videos) yields good results, aside of the obvious "rendering outside the container element" issue), so I feel this could be worked around, either at the polyfill level, or directly within Ruffle.

Bear in mind that as of SeaMonkey 2.53.7, support for NPAPI plugins was dropped for good, so there is no Flash plugin fallback possible for those users.

I know that WC polyfills may never become an officially supported use case, but many users would be thankful if some Ruffle dev could take a look at it, as it is more likely to find a workaround or solution, rather than wait for our browsers to get native WC support (it WILL happen, just not this year...). I mean, I'm surprised that leaving aside this obvious flaw, everything seems to be on the proper track...

**Comment by adrian17** [comment]
> But there is still a not so insignificant amount of users using browsers that are NOT OLD, OBSOLETE AND OR/OUTDATED, yet that they don't support Web Components just yet

Looking at raw numbers, we're already using some features that require even newer browsers than Web Components. For example, our Rust side uses `Object.fromEntries` API, which AFAIK requires same base FF as Custom Elements.

Further, in general we tend to prefer to stick to newer browser versions, if only for WebAssembly support. Sooner or later, we'll plan to switch on past-1.0 wasm features like bulk-memory, multi-value or SIMD, which would definitely also push the minimum supported version past FF60.

AFAIK, current SeaMonkey is based on FF 60, which we already haven't supported back then. I understand that from seamonkey's POV it's a not-obsolete, regularly updated browser; but from my POV, this is equivalent to supporting FF 60.

**Comment by kmeisthax** [comment]
This personally sounds like the polyfill itself is broken, or we're relying on WebComponents features that can't be polyfilled. If it's something we can easily change to fix, I'm not against it. However, I should warn that we do plan to make more use of WebComponents features over time - maintaining compatibility with just the polyfillable subset of WC might not be tenable long-term.

>Bear in mind that as of SeaMonkey 2.53.7, support for NPAPI plugins was dropped for good, so there is no Flash plugin fallback possible for those users.

This is actually quite unfortunate, as porting Ruffle to NPAPI would have actually been a good long-term option for targeting forks of old browsers that don't track web standards.

**Comment by dilworks** [comment]
> This personally sounds like the polyfill itself is broken, or we're relying on WebComponents features that can't be polyfilled. If it's something we can easily change to fix, I'm not against it. However, I should warn that we do plan to make more use of WebComponents features over time - maintaining compatibility with just the polyfillable subset of WC might not be tenable long-term.

Is there a list somewhere of WebComponets features used currently by Ruffle? This would help narrowing down where is the issue, in the case of the polyfills.

I'm well aware that the polyfills are only a stopgap measure while browsers get their stuff sorted out and come out with their WebComponents implementations (hopefully sooner than later, but this is hard as the specification is a moving target by its very nature), but in the meanwhile, the polyfills are all what we got, and they're actively supported upstream.

**Comment by Herschel** [comment]
Thanks for the report! It's good to know how Ruffle is fairing in these other browsers.

Unfortunately, we are going to be using so many new-ish features that supporting these kind of use cases will be difficult. I don't think we have the bandwidth to support these browsers, as even dealing with the Big Four is a significant effort.

I think the best solution is for someone to maintain a fork that is specifically targeted at these browsers; it could remove the usage of Web Components and other features that might prevent Ruffle from working. I'd be happy to provide info to guide this effort, although I don't have much knowledge of SeaMonkey et al.

**Comment by Herschel** [comment]
Closing since we aren't planning any official support. Feel free to ask questions if info is needed for anyone trying to add support to a fork.
