### ISSUE TITLE
web: Stick War - Cannot click on start at misson - Bug

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#5126]
Hey,

https://www.newgrounds.com/portal/view/509310?emulate=flash another bugged game where the sound is a little buggy also it seems the menus are over-blended. But the main problem is I cannot start the game as the "button" start does not react to start the mission

**Comment by Poopooracoocoo** [comment]
@relrelb Did you wanna close this?

**Comment by relrelb** [comment]
> @relrelb Did you wanna close this?

No, I re-opened this issue intentionally because the fix commit was flawed and was reverted in #5471, so this issue remains.

**Comment by mero09-99** [comment]
oh, my issue was the same as this one
this still occurs on 10/09/2022

**Comment by desertking** [comment]
Error still persists. Maybe it's related to 2-3 other games I found where you can't click the Play-button..

**Comment by MegaTophat** [comment]
Is this planning on being fixed? Maybe someone could inform me on why the button can't be clicked so I could try to submit a commit? It seems the slight flaw in the commit caused the original fix to be reverted so quickly, but then the actual fix has taken so long, despite the difference being an inventory bug which had a workaround, and literally not being able to get past the start of the game, so if there's any way I can help to resolve the bug I would be eager to assist.

**Comment by Jmousy** [comment]
I checked on **2023-07-15 Nightly** and the problem is still there, and unlike before, the Start button has a black square on it:

Ruffle:
![image](https://github.com/ruffle-rs/ruffle/assets/75052171/d0936404-6e13-4d40-bcf8-9935bc36bda1)

Original:
![image](https://github.com/ruffle-rs/ruffle/assets/75052171/d5996179-8047-4713-8379-654dab2b83a4)

**Comment by SpaceWallaby936** [comment]
the error persists

**Comment by Milli189** [comment]
this issue is still happening in the latest nightly build

**Comment by sxqbunachita-dev** [comment]
guys download adobe flash player 32 https://archive.org/details/flashplayer_32_sa then get the swf files from https://github.com/AsePlayer/Stick-War-Classic

**Comment by sxqbunachita-dev** [comment]
also if you want to download games like these, go to internet archive, it has some cool stuff https://archive.org/
