### ISSUE TITLE
Dyamically attached movieclips run their first frame too late

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#513]
When you attach a movie clip in Actionscript, it's supposed to run its frame 1 during the frame it was attached. Currently, it delays until the next frame.

I've amended the `attach_movie` test over here to reproduce the issue: https://github.com/Dinnerbone/ruffle/commit/e2ad433afc166134a09c8cb0e0ab7a64e05245a5

**Comment by Herschel** [comment]
Seems like this might have been fixed by #521 ?

**Comment by Herschel** [comment]
Looks like this is fixed.

**Comment by Dinnerbone** [comment]
We should pull in that test if we haven't already, to keep it fixed
