### ISSUE TITLE
web: Super Adventure Pals - game scene bugged

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#5139]
Hey,

another game which is not running perfectly. Ingame lots of graphics and stuff is missing.

https://www.newgrounds.com/portal/view/600197?emulate=flash

Bests

**Comment by torokati44** [comment]
This game uses `BitmapData.draw()`, which is not yet implemented. This is a reasonable explanation for the missing graphics.
Unfortunately at this time I'm not able to test my in-progress work on it to see if it helps with this.

**Comment by relrelb** [comment]
Related to #290.

**Comment by Sonikkustar** [comment]
Graphics seem to load up on my end. Not sure what the extent to the graphical glitches there are here so more testing might be needed.

![image](https://user-images.githubusercontent.com/22226938/190017785-0c322546-7db0-4a69-9c3b-dc3cc7441574.png)

**Version Used**
ruffle-nightly-2022-09-10-windows-x86-64

It looks like NG is using an outdated version of ruffle? Seems like the graphical glitches only happen on the site.

![image](https://user-images.githubusercontent.com/22226938/190018149-c00065c8-f6a8-40cb-b8b6-df0f13b2d0b3.png)

**Comment by Lord-McSweeney** [comment]
`BitmapData.draw` now works on web with wgpu-webgl, but there are still collision problems and some objects are not drawn. Additionally, entering the main world (view levels) screen presents major lag.

**Comment by Lord-McSweeney** [comment]
The ground for the tutorial still doesn't render.

**Comment by n0samu** [comment]
Closing since the original issue is fixed. The ground rendering issue can be tracked in #13986.
