### ISSUE TITLE
Allow overriding the stage scale mode

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#5186]
Hey,

Ruffle had a better "fit to screen" option in the beginning. Now it's more like the Flash Player and it's worse. It was a good feature because it scaled the games that couldn't before. Like "Arcuz" or "Submachine".

I guess the player zoomed better and used the + - mode like the browsers to scale which works on those games. Now you made it more like the Flashplayer and broke it. 

I would highly suggest to role it back to how it worked before as it was a good feature or make an option to the JavaScript api to use "standard" mode or "fit to screen / div" mode. Especially nowadays with big screens non-saleable games in 400x300 are not playable anymore!

**Comment by Toad06** [comment]
I think the `letterbox` option (set to "on") is what you need? But this is only for the self-hosted version as it's not possible to configure the options in the extension at the moment.

**Comment by desertking** [comment]
Hey, I used "fullscreen" before, tried "on and "off". But nothing changed. But I'm pretty sure it worked before as the Submachine parts scaled. Basically it should "mimic" the browser + and - in that case within the container used. As it would scale in that way. Dunno what you did before but it worked with many games that didn't support other sizes by default as submachine parts.

See those images, there were no  black space before it scaled anyway in the container before some changes were made. Now it acts like flash back then.

![image](https://user-images.githubusercontent.com/23042167/131622492-5d80495c-7a9c-4d56-8e29-94bbe46d3be5.png)

![image](https://user-images.githubusercontent.com/23042167/131622684-2b5ecb22-fae8-4c68-81ca-96883fde0bca.png)

**Comment by Toad06** [comment]
The game uses scaleMode: `Stage.scaleMode = "noScale"` found in `\frame3\DoAction`.
`scaleMode` was implemented as part of #4033 and doesn't seem to look at the `letterbox` option.

This also affects DTunnel 3D (https://www.newgrounds.com/portal/view/174308/): the game looks broken because the display rect is only 200x250 but the canvas size in the DOM is doubled (the canvas size was changed when they realized the game was working in Ruffle - Stage.scaleMode wasn't implemented in Ruffle yet).

**Comment by desertking** [comment]
Yeah. It would be better if we can "override" this setting. As I did the same. I tested games with ruffle, saw they worked and scaled now and used bigger screen res. Especially nowadays with those high res Monitors no one can play those 500x300 games.

**Comment by desertking** [comment]
No update on that case yet?

**Comment by Herschel** [comment]
This is working "as intended", but I definitely want to provide quality-of-life options to fix this.

We should provide a user-facing way to force-override the scale mode on both web and desktop. I believe setting `Stage.scaleMode` via AS overrides any of the JS API or HTML settings.

**Comment by desertking** [comment]
Is there an update yet?

**Comment by Benman2785** [comment]
+1
