### ISSUE TITLE
mh's Visualizer - Screen clipped in awkward way

### ISSUE THREAD

**Issue by firoball** [ruffle-rs/ruffle#5220]
**Describe the bug**
Screen appears to be clipped in an awkward way. 
![grafik](https://user-images.githubusercontent.com/4692010/132085815-50023638-4d4b-48fc-a186-63220f568f2d.png)

**Expected behavior**

Screen fully visible

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
**What platform are you using?**
 - Ruffle Web Demo 2021-09-04 in Firefox 91.0.2

SWF Link: http://visualizer.theopensourcelock.org/
Source Repo: https://github.com/mh-/AxisVisualizer

**Comment by firoball** [comment]
Could this code section possibly be the culprit?
`		// Set the stage
		// Stage.scaleMode = "noscale";
		Stage.scaleMode = "showAll";
		Stage.align = "CC";`

**Comment by Toad06** [comment]
The issue is that Ruffle maintains the aspect ratio of the file (300x400) in the web demo and the extension (when opening an SWF in a tab) because it always sets the `letterbox` option to `on`. We need to provide a way to change this default behavior.

**Comment by firoball** [comment]
This is fixed in latest nightly, probably resolved long before.

**Comment by Toad06** [comment]
Not really - there's a regression that affects the current builds when applying the configuration (it is not applied at all in fact, so the `letterbox` option is not set to `on`). The file will no longer be displayed correctly when #8093 is merged.

**Comment by firoball** [comment]
Reopening due to comment above.
