### ISSUE TITLE
request: add BMP image file format

### ISSUE THREAD

**Issue by toutis** [ruffle-rs/ruffle#5224]
Hey,
The old game I'm playing contains images with .bmp format,
Would it be possible to add it please?

**Comment by relrelb** [comment]
From my understanding, BMP images are represented in an SWF as `DefineBits` tags, which are supported in Ruffle.
Can you please report what exactly is not supported? Referring to an SWF would help a lot too.

**Comment by torokati44** [comment]
Maybe the .bmp images are external files?

**Comment by dginovker** [comment]
Can you link the .swf?

**Comment by n0samu** [comment]
Closing due to lack of response
