### ISSUE TITLE
[Web] Play button is not displayed if height attribute is missing

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#529]
If an object or embed tag lacks the "height" attribute (or if the value is not correct), the play button will be displayed at a height of 100% of 0, so it is not possible to start the file.
I suppose the fix would be just a matter of a CSS change.

[missingheight.zip](https://github.com/ruffle-rs/ruffle/files/4545523/missingheight.zip)

Ruffle could eventually set its own default width and height if these attributes are missing, but values are not consistent across browsers.
Here they are for the record:
- object tag:
Firefox: 0x0
IE: 240x200
Chrome: 300x150

- embed tag:
Firefox: 240x200
IE: 240x200
Chrome: 300x150

**Comment by Herschel** [comment]
Did a quick fix for this (CSS gurus welcome to do this better!). I set the `:host` element to have a default width of 550x400 (old school default Flash dimensions). This should get overwritten by any user set attributes/styles. Also tweaked the play button style to ensure it'd be visible regardless.
