### ISSUE TITLE
game does not work correctly

### ISSUE THREAD

**Issue by glitchtraper** [ruffle-rs/ruffle#5315]
### Describe the bug

it did not allow me any interaction at all

### Expected behavior

i was supposed to use a custom cursor hand but that glitched out

### Affected platform

Desktop app

### Operating system

windows 10

**Comment by relrelb** [comment]
Can you please refer to a specific SWF? Otherwise we have no way to investigate the problem.

**Comment by Herschel** [comment]
No info provided.
