### ISSUE TITLE
Cannot enter fullscreen in the offline build of Ruffle

### ISSUE THREAD

**Issue by GK6475** [ruffle-rs/ruffle#5328]
### Describe the bug

When I open any SWF file, I cannot access any right click menus, and therefore, no fullscreen.

### Expected behavior

I expect to see a menu when I right click so that I can enter fullscreen and so that quality can be adjusted.

### Affected platform

Desktop app

### Operating system

Windows 7 Ultimate x64

**Comment by relrelb** [comment]
Unfortunately, right-click menu is currently not implemented on desktop (see #895). However, there is an <kbd>Alt</kbd>+<kbd>Enter</kbd> shortcut to enter/exit fullscreen.

**Comment by sleepycatcoding** [comment]
Desktop now has <kbd>F11</kbd> shortcut and View menu item from which you can enter fullscreen. Quality options are also available in the context menu.
