### ISSUE TITLE
Frizzle Fraz is still unplayable after i turned on ruffle

### ISSUE THREAD

**Issue by LovelyRamonaKitty** [ruffle-rs/ruffle#5342]
I turned on Ruffle, and try to play Frizzle Fraz.
It won;t let me play. it still says adobe flash is no longer supported.
https://www.frizzle-fraz-games.com/?p=game&id=1
THis game has an issue.

**Comment by danielhjacobs** [comment]
See #1368.

**Comment by Toad06** [comment]
Closing in favor of #1368 as per above comment. Thanks for reporting.
