### ISSUE TITLE
Error on https://kissu.moe/f/thread/105

### ISSUE THREAD

**Issue by ECHibiki** [ruffle-rs/ruffle#5348]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object.rs:1219:34

# Player Info
Allows script access: false

# Page Info
Page URL: https://kissu.moe/f/
SWF URL: https://haiji.kissu.moe/f/src/1598303651730.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-09-14
Channel: nightly
Built: 2021-09-14T00:12:54.264Z
Commit: a882f85d14bd7d3d8e9d372dd3549e6e9fddc598
Is extension: false

**Comment by ECHibiki** [comment]
Proceeds to break the execution of all other Ruffle operations, likely related to the error flood:
Unable to lock Ruffle core ruffle.js:1:26012

**Comment by Toad06** [comment]
Thanks for the report.

This is likely the same issue as #5347.
