### ISSUE TITLE
fonts with accentend

### ISSUE THREAD

**Issue by vgeneau** [ruffle-rs/ruffle#5357]
hello,
I am French and I would like to use animations with accented text. 
Some accented fonts do not work. How can I go about solving this problem?
Thank you

example: http://vincent.geneau.free.fr/NewCligne/06_conversion_unites_compose_exo.html
![Capture](https://user-images.githubusercontent.com/31799332/134652485-44bbb1ff-dd9b-4353-9af1-7d5d3edc5a40.JPG)

**Comment by ousia** [comment]
@vgeneau, if you want to use system fonts, #1862 should be implemented first.

Otherwise, Ruffle with default to a font that lacks most of non-ASCII chars.

A workaround would be to embed all fonts with all required characters.

Just in case it might help.

**Comment by vgeneau** [comment]
Thanks for these informations. Could you tell me how I can integrate all 
the fonts?


Le 2021-09-26 16:59, Pablo Rodríguez a écrit :

**Comment by ousia** [comment]
@vgeneau, I don’t even know how you generate your SWF files...

**Comment by torokati44** [comment]
This should be fixed by #6224 now.
