### ISSUE TITLE
Need help editing a flash game

### ISSUE THREAD

**Issue by DeBosh185** [ruffle-rs/ruffle#5389]
Hi!
Please do not swear that I am addressing here, I do not know where else to ask. If someone understands the ActionScript 2, please help. I've been puzzling over a flash game for five days now, I can't get it to work properly. If someone wants to help, please write to me.
Thanks
DeBosh185@yandex.ru

**Comment by relrelb** [comment]
Closing as this has nothing to do with Ruffle.
