### ISSUE TITLE
https://www.fukgames.com/tags/flash  (every game in the flash section is white-screen)

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#5416]
### Describe the bug

![fukgames pottyracers](https://user-images.githubusercontent.com/64484245/135732881-4958f2b3-9929-4b6c-a305-77aebc27fc47.png)

Every single flash game on this website is behind a white screen and Ruffle does not show up at all. 

Even though i was able to verify that the .swf files on the website were there and the open in new tab that normally shows up on CORS issues type websites did not pop up.

```
using flash downloader for google chrome
https://chrome.google.com/webstore/detail/flash-downloader/eepdaplnjgknikdfmmiihcohocmpmimg

and the FlashPlayer - SWF to HTML extension https://chrome.google.com/webstore/detail/flashplayer-swf-to-html/nodnmpgjlnclahkmgjiinfjklgbbgecg

i was able to use dr link check to verify the existance of the .swf files as well
https://www.drlinkcheck.com/blog/find-flash-files-on-website

the website would presumably work with https://github.com/jamesgrams/pull-up-flash
but i have not tested it yet 


```

### Expected behavior

i expected the games to work on the website but all i get is white screen

i expected the games to work like they normally do on most flash game websites

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 93.0.4577.95 (Official Build) (64-bit)

**Comment by Poopooracoocoo** [comment]
This website actually self-hosts Ruffle but something is wrong on their side. They're running Ruffle 2021-02-1 which is super old. 

@flashliberty5467 Can you find a way to contact the site to let them know and get them to fix it?
