### ISSUE TITLE
Firefox extension signed again?

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#5419]
After nightly from 2021-09-14, Firefox extensions aren’t signed?

Are there any plans to sign Firefox extensions again? This is essential to test new implementations.

Many thanks for your help.

**Comment by torokati44** [comment]
This is not our fault, the system tries to sign every single nightly, just isn't able to.
Many people have this problem recently, see: https://discourse.mozilla.org/t/can-anyone-release-extensions-right-now-to-me-it-looks-like-addons-mozilla-org-is-critically-broken/84830

**Comment by ousia** [comment]
@torokati44, I didn’t know that this was an issue in Mozilla.

So closing the issue myself.
