### ISSUE TITLE
Ruffle doesn't work with file scheme

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#543]
Possible solution:
https://stackoverflow.com/questions/42108782/firefox-webextensions-get-local-files-content-by-path

**Comment by Herschel** [comment]
Unfortunately security restrictions in modern browsers disallow extensions from accessing file: URLs, and the workaround in that StackOverflow post doesn't seem to work in modern Chrome/Firefox.

Possibly we can investigate a workaround using the File System Access API, but this requires showing the user a file picker dialog, so probably not a great solution.
