### ISSUE TITLE
Tab key behavior from Adobe Flash Player not present in Ruffle

### ISSUE THREAD

**Issue by Sunlitspace542** [ruffle-rs/ruffle#5443]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

This was a feature the original Flash Player had, if you press the tab key, it cycles through each clickable item, highlighted with a yellow box around the item. pressing enter "clicks" on the item.
Screenshot attached with example of what I'm talking about using a Flash projector:
![image](https://user-images.githubusercontent.com/35207254/141229727-b9b7bcc5-b0bc-4a70-8a0a-977a76dc185f.png)

**Comment by Erisfiregamer1** [comment]
Would be nice.

**Comment by mero09-99** [comment]
I agree

**Comment by battaglia01** [comment]
Kind of curious how hard this would be to implement. Has anyone looked into this? What does the tab key do now?

**Comment by ActionWavele** [comment]
This is very important for accecibility

**Comment by Atario** [comment]
> What does the tab key do now?

Nothing, looks like

**Comment by VL4DST3R** [comment]
Any updates on this? This and the zoom functionality are some of the most noticeable pain-points with ruffle compared to native flash.

**Comment by rikkoooo** [comment]
This is ultra-very important, and maybe even more important than the mouse support. And, this is a bug report, not an enhancement request.

**Comment by battaglia01** [comment]
Ok. Does anyone have any idea how to implement this? Where would one poke around to do this?

**Comment by kjarosh** [comment]
Implementation status:

- [ ] Tab key support (https://github.com/ruffle-rs/ruffle/pull/15542)
- [ ] AVM1 support for `tabEnabled`, `tabIndex` (https://github.com/ruffle-rs/ruffle/pull/15542)
- [ ] AVM1 support for `tabChildren`
- [ ] AVM2 support
- [ ] Analysis and implementation of a proper automatic order
- [ ] Visual highlight around the tabbed element

**Comment by Croworbit** [comment]
does it work across other OSes?

**Comment by kjarosh** [comment]
> does it work across other OSes?

This feature is platform-independent. Should work on every OS and on web (although I am not able test it on all OSes).

**Comment by RavenAgentDev** [comment]
Note: It works on the browser version (as in the swf file can detect its being pressed)

**Comment by kjarosh** [comment]
I think the tab key support is in a pretty good shape now. Referenced the two remaining TODOs in new issues.

Closing as completed!
