### ISSUE TITLE
Fall back to canvas rendering on webgl error

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#545]
If there's a webgl error, we should still be able to use the canvas backend, rather than failing entireley.

**Comment by Dinnerbone** [comment]
I agree with this (and I think we could even add wgpu into the mix when support lands in any stable browser release) - but we should find a way to tell the user which backend they're using, for when they want to report bugs. And probably a way to force a specific backend, too.

**Comment by Herschel** [comment]
This should already work if the `canvas` feature is enabled (WebGL gets priority), I just hadn't enabled it by default quite yet. I think it's a good idea, too. I have a WIP branch also for options that allows the user to request a specific backend via command line or JS API.

What's an acceptable way to tell the user which backend they are using? Is console log enough?

**Comment by Dinnerbone** [comment]
I've been thinking that we should add some branding to the "click to play" button, something like the ruffle logo in the footer and "Powered by Ruffle, an open source Flash player" with links to github. We could also use that for a warning about canvas renderer, or even a handy diagnostics bug to capture a bunch of info (like swf info, browser info, GL support) for them to copy paste into bug reports.

**Comment by Herschel** [comment]
Enabled canvas feature by default in 2331b49. For reference, it adds ~270k to the binary size.

I think it should be both a site-owner option and an end-user option to override, i.e., the JS API can request a specific backend if it's known that content works better on it, but a user setting can always override it. I think this actually applies to most options, such as letterboxing, bitmap smoothing, etc. NG will probably add setting field to their project page where users/admins can paste in JSON settings blobs for ruffle to enable things as appropriate (for example, disable bitmap smoothing on old pixel animations). Ideally users can enable/disable this somewhere as they please, too.

For the user-facing options, this starts to move into a bigger issue of how we expose UI on desktop and web.

**Comment by Dinnerbone** [comment]
I can agree with all of that 👍

**Comment by Justin-CB** [comment]
It still isn't falling back for me. I built the latest commit.
It's showing this in the console & a black background for the ruffle player.
![Screen Shot 2020-05-04 at 10 34 22 AM](https://user-images.githubusercontent.com/55590227/80984138-77890e80-8dfb-11ea-98c8-f8525ec8cb41.png)

**Comment by Herschel** [comment]
Thanks! It's a little harder because this error occurs after the WebGL context creation. When the canvas tries to create its own context, it blows up (you can't create 2 contexts on a single canvas, we'll have to wipe out the old canvas and recreate it.)

I'm curious why there's a shader linker error (with no linker error message). What graphics card are you using? What happens if you comment out https://github.com/ruffle-rs/ruffle/blob/master/render/webgl/src/lib.rs#L1333-L1344 ?

**Comment by Justin-CB** [comment]
If I comment out the lines you mentioned, it just shows a black box in the place of the ruffle player. The console logs a bunch of "Unhandled morph shape combination" buttons, but it also does that with fingerprint blocking disabled(which makes it work). The only error message that's different(It only appears with fingerprint blocking disabled) is:

![Screen Shot 2020-05-04 at 12 45 59 PM](https://user-images.githubusercontent.com/55590227/80990980-50cfd580-8e05-11ea-8dd9-a330ae904ed8.png)


Note that I'm using <a href="https://www.newgrounds.com/portal/view/87004">Uniwar LC</a> for this test.

The background behind the play button is black, but I'm building from my "playbutton" branch, which puts the play button's svg inline in the playbutton div, rather than as a CSS background. I'm only mentioning this as the background is white when it works.

**Comment by Justin-CB** [comment]
Also, I'm using Brave Browser Nightly on a Mac Mini 2012 with integrated intel graphics. Brave is a chromium-based browser that has various privacy features, some of which can conflict with some websites(it is possible to disable them on a site-by-site basis). The specific feature that is causing this error is Fingerprint Blocking(which has the side effect of disabling WebGL), as turning that off allows ruffle to work.

**Comment by Herschel** [comment]
If I understand correctly, you're saying that WebGL works and the movie plays when you disable the fingerprint blocking in Brave?

Thanks, that's helpful (we'll have to do some more testing with Brave).

The morph shape errors are an unrelated minor issue (we should file an issue on that one too!)

**Comment by Justin-CB** [comment]
Yes, WebGL works & the movie plays with fingerprint blocking disabled.

I was assuming the morph shape errors were unrelated, as they were showing up in the log with fingerprinting blocking both enabled and disabled.
