### ISSUE TITLE
Clicking a button doesn't trigger the correct action in Steppenwolf (regression)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5470]
[Steppenwolf 3-3](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/495/original/steppenwolf_chapter_3_episode_3.swf)

**Steps to reproduce**

- Start a new game (skip intro).
- Press "I" to open the inventory.
- Click on the left part of the "Mail" button. Notice that everything works as expected and the "E-mail account" screen is displayed.
- Now click on the right part of the "Mail" button. Notice that you unexpectedly select an item from the inventory (the magnetic card). This is because the game creates multiple instances of an item behind the PDA for some reason (but they shouldn't be clickable), so if you click between "Items" and "Quit", you would select another item (the communicator), etc.

---

This wasn't an issue in nightly-2021-10-11. I believe that something in 37e3f0903ec45ae2d946b63bcfb0b1c294641cc9 introduced the regression.

Originally reported in #1386.

**Comment by relrelb** [comment]
Good catch! I tossed a revert PR for now as I don't have time to figure out what exactly was broken.
