### ISSUE TITLE
web: iOS 15 displays a magnifying glass when holding down on the screen

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5483]
![image0](https://user-images.githubusercontent.com/14274782/137595872-82ad272f-f5b8-4907-a07d-92e648ffc4a1.jpg)

- Run any file (can be one on the [web demo](https://ruffle.rs/demo/)) on a device using iOS 15 or iPadOS 15.
- Touch the canvas for 1 or 2 seconds without moving.
- Notice a magnifying glass appears on the screen.

Originally reported by linzers on Discord.

**Comment by Herschel** [comment]
I'll take a peek at this later, I expect there is some CSS property we might have to add to the player elements.

**Comment by torokati44** [comment]
I'm not able to test, but just a guess:
In `ruffle-player.ts`, adding this line could help:
```ts
    private pointerDown(event: PointerEvent): void {
        // Give option to disable context menu when touch support is being used
        // to avoid a long press triggering the context menu. (#1972)
        if (event.pointerType === "touch" || event.pointerType === "pen") {
            event.preventDefault();  //  <---- THIS LINE
            this.isTouch = true;
        }
    }
```
Again, maybe not, but I haven't found any relevant CSS property so far...

**Comment by Toad06** [comment]
It seems like Apple has made some changes, as this issue no longer occurs on iPadOS 15.2.

**Comment by Toad06** [comment]
Still good on iPadOS 15.3, I think this bug could be a wontfix.
