### ISSUE TITLE
Don't panic on unimplemented codecs

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#549]
I just came across a game that has audio using the nellymoser codec, which caused ruffle to panic.

**Comment by Herschel** [comment]
Thanks for reporting! Related to #531, but for AudioBackend.

**Comment by ROBERT-MCDOWELL** [comment]
dunno if it cann help
https://docs.rs/flv_codec/0.1.0/flv_codec/enum.SoundFormat.html
https://github.com/rust-av/speexdsp-rs

**Comment by Justin-CB** [comment]
I'm going to post those links in the audio codecs issue.

**Comment by Herschel** [comment]
Could you post a link to the SWF using Nellymoser? Thanks!

**Comment by Justin-CB** [comment]
It was on this page:
https://www.coolmathgames.com/0-abducktion
Thru inspecting element, I found that the URL of the SWF is:
https://www.coolmath-games.com/sites/cmatgame/files/games/abducktion-locked.swf
