### ISSUE TITLE
No sound in online demos in Firefox 75.0

### ISSUE THREAD

**Issue by ebkalderon** [ruffle-rs/ruffle#551]
None of the included SWF files in the Ruffle online demo page in Firefox 75.0 (x86_64 macOS) appear to have any audio. However, when playing the same demos in Google Chrome 81.0.4044.129, the sound seems to work fine.

I tested "Wasted Sky" and "Saturday Morning Watchmen," and neither are able to produce any sound in Firefox 75. Sound seems to be work in other tabs when playing YouTube videos, so I don't think this is a general issue with the browser itself.

**Comment by ebkalderon** [comment]
I restarted my browser and cleared my cache, and everything seems to be working. 🤨 Not sure what the issue was, but audio is now playing as normal. I guess this issue is fine to close as invalid. Thanks anyway!

**Comment by Herschel** [comment]
Thanks for the report! If you ever reproduce it, could you take a peek in the JavaScript console to see if there is any relevant output? This may be an issue with the AudioContext not  starting due to autoplay restrictions or similar.

**Comment by ebkalderon** [comment]
@Herschel Will do! Wish I had done that first before restarting the browser, honestly, haha. I'll re-open the issue and log the console output if I experience it again. ☺️
