### ISSUE TITLE
The Binding of Isaac rocks and background not showing.

### ISSUE THREAD

**Issue by CableTV1123** [ruffle-rs/ruffle#5522]
### Describe the bug

When I try to play TBOI WOTL or the demo using ruffle for some reason the rocks and background don't show
I forgot to add this earlier but the holes also don't show
also also sometimes when entering a room the background will blink on for a second then dissapear

I'm using ruffle nightly 2012-10-19 on a website so I'm not sure what the affected platform should be
![image](https://user-images.githubusercontent.com/80400552/138454881-d89fc068-11fc-4b8e-ae06-562edb814c74.png)
also this is extra info just in case

### Expected behavior

The rocks and background should show

### Affected platform

Self-hosted version

### Operating system

Chrome OS

### Browser

Google Chrome

**Comment by narwalions** [comment]
made an account specificly to ask you for a link to your site or some help with my own. i cant quite figure out how to embed ruffle into my site. it just doesnt want to work.

**Comment by CableTV1123** [comment]
I didn't make the website but here's the link
https://flasharch.com/en/archive/play/055f7891ebd8400448fb410e6285d0a5

**Comment by narwalions** [comment]
thanks. hopefully theyll fix this soon. i need a nolstalgia fix

**Comment by n0samu** [comment]
This is fixed in the Ruffle desktop app since BitmapData.Draw was implemented there. The feature should come to web builds of Ruffle at some point in the future. One implementation is being worked on in #6629.

**Comment by CableTV1123** [comment]
epic
I can wait a bit for the website I'm trying to use to update ruffle

**Comment by CableTV1123** [comment]
> thanks. hopefully theyll fix this soon. i need a nolstalgia fix

You can download the .swf file (if you can find it) and play it on the desktop flash player
or buy it on steam

**Comment by Lord-McSweeney** [comment]
Fixed by #9134, but there are now performance issues when you move between rooms.
