### ISSUE TITLE
Acrivating Ruffle on ComDotGames causing seizure inducing flashing and unplayable games

### ISSUE THREAD

**Issue by Anuyushi** [ruffle-rs/ruffle#5526]
### Describe the bug

As you activate ruffle on ComDotGames, the front of the game shows but it's impossible to click anything. The game begins to flash rapidly with no way to stop it and trying to click the play button is unsuccessful. The only way to stop it is to reload the page. 

### Expected behavior

The game should load up and be playable

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
This needs some XML for Google Analytics.

**Comment by Lord-McSweeney** [comment]
Fixed in latest nightly.
