### ISSUE TITLE
Frame rewind(or skip) occurs whenever the space bar is pressed (in some games)

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#5527]
### Describe the bug

**Reproduced in Nightly builds after 2021-07-01, but not in 2021-06-01 builds.**
(However, I haven't been able to confirm exactly when the problem started.)

'Spam, Spam, Spam, Spam!' In the game, each time you press the space bar, you will be taken to the beginning of the game. at any point in the frame.

The original action is that the game should start when you press the space bar on the main screen, and after the game starts, pressing the space bar should not respond.

[Spam, Spam, Spam, Spam!.zip](https://github.com/ruffle-rs/ruffle/files/7402079/Spam.Spam.Spam.Spam.zip)

https://user-images.githubusercontent.com/75052171/138538492-679abe13-4ce2-4abc-87fd-c3d335946d14.mp4

**I think I've seen a few games that suffer from these symptoms.**

In another example below (Korean game named '미리스토리 도적 떼 잡기!') it seems to be forced to the next frame.
Press the start game(게임 시작) button, and Each time press the spacebar, the frame is forcibly moved to another location.

In the original, the spacebar doesn't do anything.

[미리스토리 - 도적떼 잡기!.zip](https://github.com/ruffle-rs/ruffle/files/7402086/-.zip)

https://user-images.githubusercontent.com/75052171/138538501-41d0b084-5e58-4524-ad6e-8f9d402c269f.mp4

### Expected behavior

The phenomenon that the frame is forcibly moved by input of the space bar should be eliminated.

### Affected platform

Self-hosted version

### Operating system

Windows 10 x64

### Browser

Google Chrome 94

**Comment by Toad06** [comment]
Both of these games seem to work without the mentioned issues in the last nightly builds, I think this was fixed by #6123. @Jmousy, could you please confirm this is also working on your end?

**Comment by Jmousy** [comment]
As of selfhosted 2022-01-31, I confirmed that the issue was resolved for both files in my environment as well.

I will close this issue. Thanks for your help!
