### ISSUE TITLE
Wrong-colored paint in Ninja Painter

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#5538]
### Describe the bug

SWF URL: http://i.notdoppler.com/files/ninjapainter.swf

In Ninja Painter, the paint buckets and paint are always red, even if they are supposed to be a different color. Below is an example of the problem in level 3 of the game: 
![image](https://user-images.githubusercontent.com/71368227/138613321-338b3e70-00e6-4b72-b26f-bc442fedfae2.png)

### Expected behavior

Here is how the same level looks in Adobe Flash Player:
![image](https://user-images.githubusercontent.com/71368227/138613316-7b00c966-51d7-42b9-a376-4ab7976269c0.png) 

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Mozilla Firefox 93

**Comment by Lord-McSweeney** [comment]
Should be fixed by #9243.

**Comment by Lord-McSweeney** [comment]
Fixed by #11702.

**Comment by Lord-McSweeney** [comment]
BTW I believe this uses a DropShadow and/or Bevel for the stars, too.
