### ISSUE TITLE
600kb swf uses 50gb+ of memory

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#554]
I don't know what the cause is, but this swf will just eat all of the memory available to the system and not load (or perhaps will eventually load given enough time and memory): https://www.newgrounds.com/portal/view/1734/format/flash?emulate=flash

This happens in desktop, but it crashes much sooner in web (possibly same issue but the browser isn't letting it get that bad)

**Comment by Herschel** [comment]
This movie has a busted Flash-4 style preloader loop using `isFrameIsLoaded` that causes an infinite loop. It hangs the official Flash Player too. We end up running out of memory because the stack grows without bound -- it'd probably be a good idea to put a sanity cap on this somewhere.

**Comment by Justin-CB** [comment]
This might be something we could detect to make it work in ruffle, as it worked in older versions of flash.

**Comment by Herschel** [comment]
That was my thought, too, and certainly if it's a version difference, it'd be neat to offer compatibility settings.

Not sure how this particular movie ever worked, though. It's at least broken all the way back to Flash Player 6 (which is the earliest I have, maybe I can ping nosamu on Discord if he has FP4). And looking at the bytecode, it's quite clearly a typo'd frame #. I even tried using the "Simulate Download" in the debug player to see if it was something triggered by the file downloading slowly/quickly, but no luck.

**Comment by n0samu** [comment]
Just randomly found this issue. I tested the SWF in Flash Player 4 and it works fine, but it's broken in Flash Player 5. You can get the projectors to test this from here: https://archive.org/details/MacromediaFlashProjectors.7z
