### ISSUE TITLE
Marvin Spectrum runs in turbo speed once tab regains focus

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#5545]
### Describe the bug

Marvin Spectrum fails to jump through many obstacles while the game should be paused when the tab is not visible.

Tested on ruffle.rs/demo using Ruffle nightly 2021-10-26

### Expected behavior

Marvin Spectrum would pause

### Affected platform

Online demo

### Operating system

Windows 10 21H1

### Browser

Chrome 95

**Comment by torokati44** [comment]
I think https://github.com/ruffle-rs/ruffle/pull/2819 may have fixed this.
