### ISSUE TITLE
"Drivers Ed" is an old game I'd like to see working...

### ISSUE THREAD

**Issue by SecularSteve** [ruffle-rs/ruffle#5548]
### Describe the bug

The game either gives a "Blank Screen", or a "Plug-in not supported" Screen, even while running the Ruffle add-on in Edge...

I've been to all of the sites, these three are the primary examples:

https://www.mofunzone.com/games/driversed.html
https://www.kongregate.com/games/lamprider/drivers-ed
https://www.y8.com/games/drivers_ed

### Expected behavior

The game to open and play like this:

https://www.youtube.com/watch?v=LSs1mfvvk6A

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 95

### Additional information

I hope you make good progress in the meantime. It's a damn shame Adobe didn't at least release the Source Code in order to make it easier for any of us.

**Comment by flashliberty5467** [comment]
your best option is bluemaxima flashpoint or download palemoon and the offical adobe shockwave player with the ankon arcade instructions
https://andkon.com/arcade/faq.php#shockwave

https://bluemaxima.org/flashpoint/


i have also in my reasearch came across a .dcr(shockwave decompliler) https://github.com/ProjectorRays/ProjectorRays
