### ISSUE TITLE
Poor collision detection with line objects

### ISSUE THREAD

**Issue by Kwing95** [ruffle-rs/ruffle#5555]
### Describe the bug

My game has randomly generated maps, with the hallways being lines drawn with the lineTo method. The player character is capable of interacting with these lines horizontally but not vertically (they can enter and traverse horizontal but not vertical paths.)

Hungry Joe: https://www.newgrounds.com/projects/games/842945/preview/filetype/0/emulate/flash

### Expected behavior

The player should be able to walk vertically up and down paths.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Version 95.0.4638.54 (Official Build) (64-bit)

**Comment by Toad06** [comment]
Thanks for the report. This was fixed by #5975 earlier this year.
