### ISSUE TITLE
AS2 : HandPointer sustains after a press/release interaction with the stage...

### ISSUE THREAD

**Issue by depPat** [ruffle-rs/ruffle#5561]
### Describe the bug

...and it fails to go back as a normal cursor after press buttons and clips.
But only if there is an interaction script within the main stage frames.

By instance following this button function :

_on(press){
gotoAndStop(2)
}_

So, when mouse moves all over the screen, handPointer sustains everywhere !... untill its rolls over a new button or clip.

demo of bugs here :

http://kniaka.fr/testRuffle/ruffle-bugHandcursor.html

### Expected behavior

Hand pointer has to go back to a normal cursor after a press/release interaction with the main stage

### Affected platform

Self-hosted version

### Operating system

Windows 10 - Android

### Browser

Firefox, Chrome, Edge, Opera...

**Comment by depPat** [comment]
@Herschel 
...and in fact, with that :
on(rollOver/press/release){ gotoAndStop(n)} function,
because we go straight from frame 1 to another frame,
this prevents the Mouse HandPointer to get it's necessary "rollOut" of a button or clip for taking place to a normal Cursor !
Hope it could be helpfull !...

**Comment by Toad06** [comment]
This issue is now fixed in the current build. Thanks for the sample, it was useful. I'm also [attaching it here](https://github.com/ruffle-rs/ruffle/files/8160769/sample.zip) in case we need it again. Thanks again.
