### ISSUE TITLE
`GetProperty` unexpectedly returns undefined in Steppenwolf 6-1

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5565]
[Steppenwolf 6-1 (ZIP)](https://github.com/ruffle-rs/ruffle/files/7442148/steppenwolf_6_1.zip) has a regression that prevents the player from completing the game.

2e3154baa036619968c180da54e94bebcbd44046 is the commit that is causing the issue. That being said, I don't think there's anything wrong with this commit - it's rather a side effect affecting the `action_get_property` function. The following warning is now logged into the console:

> GetProperty: Invalid base clip

---

Here's a video showing the issue. The guard on the right shouldn't shoot in this situation.

https://user-images.githubusercontent.com/14274782/139441688-dfacb0c8-d427-459b-a048-fd5c23e7fe66.mp4

---

The variable that controls the behavior of this guard is `/Variables:Mechant2Tir` (it is set to true when the conditions for him to shoot are fulfilled), in `\frame 704\PlaceObject2 (2608) Depth: 9\onClipEvent(enterFrame)`.

I've added the following traces in this frame (see in the attached zip above):
```
trace("//_target");
trace(_target);
trace("//_root.Mechant2:_X");
trace(_root.Mechant2:_X);
```

When you haven't climbed the pipe yet, the values are consistent across Flash Player and all the versions of Ruffle:
- `_target`: "/"
- `_root.Mechant2:_X`: 404.95

After you have used the pipe, things are different:

Flash Player:
- `_target`: undefined
- `_root.Mechant2:_X`: 404.95

Ruffle - before the mentioned commit:
- `_target`: "/"
- `_root.Mechant2:_X`: 404.95

Ruffle - master:
- `_target`: undefined
- `_root.Mechant2:_X`: undefined

As a domino effect, these wrong/unexpected values affecting `_root.Mechant2` end up triggering the conditions that set `/Variables:Mechant2Tir` to true.

**Comment by Herschel** [comment]
Ok, this one is _actually_ #768. 😄 `_target` and `this` correctly return undefined, but `_root` should remain accessible because it should be accessible as a normal variable in scope, not as a property as `this`/`_target`.

**Comment by Toad06** [comment]
I got back to this issue and found out it is only happening with `GetProperty`: when using `GetVariable` and `GetMember`, `_root.Mechant2._x` (or `Mechant2._x`) returns the expected value and matches Flash.

So I think that `fn action_get_property` should not fail immediately if the call to `target_clip` returns None. I tried different things and getting the display object after calling `get_variable` seems to work: `_root.Mechant2:_X` (or `Mechant2:_X`) returns the expected value, and our tests still pass. Dunno if there could be edge cases though...

This is how the function looks like:

```
    fn action_get_property(&mut self) -> Result<FrameControl<'gc>, Error<'gc>> {
        let prop_value = self.context.avm1.pop();
        let prop_index = prop_value.coerce_to_f64(self)?;
        let path = self.context.avm1.pop();
        let (target_clip, display_object) = if let Some(target) = self.target_clip() {
            (
                Some(target),
                self.resolve_target_display_object(target, path, true)?,
            )
        } else {
            let path = path.coerce_to_string(self)?;
            let path_value: Value<'gc> = self.get_variable(path)?.into();
            if let Value::Object(obj) = path_value {
                let clip = if let Some(clip) = obj.as_display_object() {
                    Some(clip)
                } else {
                    None
                };
                (clip, clip)
            } else {
                (None, None)
            }
        };

        let result = if let Some(_target) = target_clip {
            if let Some(clip) = display_object {
                if prop_index.is_nan() || prop_index <= -1.0 {
                    avm_warn!(self, "GetProperty: Invalid property {:?}", prop_value);
                    Value::Undefined
                } else {
                    let prop_index = prop_index as usize;
                    let display_properties = self.context.avm1.display_properties;
                    let props = display_properties.read();
                    if let Some(property) = props.get_by_index(prop_index) {
                        property.get(self, clip)
                    } else {
                        avm_warn!(self, "GetProperty: Invalid property index {}", prop_index);
                        Value::Undefined
                    }
                }
            } else {
                avm_warn!(self, "GetProperty: Invalid target {:?}", path);
                Value::Undefined
            }
        } else {
            avm_warn!(self, "GetProperty: Invalid base clip");
            Value::Undefined
        };

        self.context.avm1.push(result);
        Ok(FrameControl::Continue)
    }
```

If these changes are correct, `fn action_set_property` will also have to get similar changes.
