### ISSUE TITLE
unreadable text in super mario 63 game seems to work just fine otherwise

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#5567]
### Describe the bug

![unreadable text super mario 63](https://user-images.githubusercontent.com/64484245/139514322-4b053e94-2841-4429-85d3-d6b2e46c66ed.png)

i can not read the text in super mario 63 when using ruffle otherwise the game seems to be working just fine
https://playmariogames.com/super-mario-63

### Expected behavior

to be able to read the tutorials and talk to the toads in the game by pressing Z instead all i get is unreadable text

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 94.0.4606.104 (Official Build) (64-bit)

**Comment by MarioLover63** [comment]
the text is there, it's just that the glow filter used for the outline is missing

**Comment by torokati44** [comment]
In that case: https://github.com/ruffle-rs/ruffle/issues/15

**Comment by Briellenoel123** [comment]
#11878

**Comment by Lord-McSweeney** [comment]
Fixed by #11878.
