### ISSUE TITLE
web: Kitten Cannon has a couple of rendering issues

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5593]
[Kitten Cannon](https://github.com/ruffle-rs/ruffle/files/7462370/kittencannon.zip) has a couple of rendering issues that affect the canvas renderer.

- When the cat is off the screen, an altimeter is displayed with a text to indicate the cat's position. When the cat is visible again, the altimeter shouldn't be displayed anymore, but on the canvas renderer it remains on screen with no text:
![alti](https://user-images.githubusercontent.com/14274782/139904685-7374738c-27cc-4854-8326-9cd8e55d7763.png)
In `\DefineSprite (402)\frame 1\DoAction`, there's a code that controls the alpha value of the altimeter. Adding `trace(_alpha);` shows that the alpha can be outside the range [0-100] (_-3.90625_ and _107.421875_ are the values I've seen). So maybe the canvas renderer does not clamp these values?

- When you lose the game, click the "Continue" button. A transition should be played to restart the level, but for some reason the transition looks completely broken. No idea what happens here.

**Comment by relrelb** [comment]
The second issue has been fixed by #5692.
