### ISSUE TITLE
API drawings add 2 extra unexpected lines

### ISSUE THREAD

**Issue by starblinky** [ruffle-rs/ruffle#5598]
### Describe the bug

When creating an API drawing, there will be a line now going from origin (0,0) to the starting point of the API drawing and the end point of the API drawing. These lines shouldn't exist.

Ruffle on left, Flash on right. This was not an issue in Ruffle as of yesterday (Nov 2nd, 2021). 

![image](https://user-images.githubusercontent.com/51274080/140269608-b46723a5-6515-45e0-bd97-3dcd354869f3.png)

[Archive.zip](https://github.com/ruffle-rs/ruffle/files/7524656/Archive.zip)

### Expected behavior

The extra lines shouldn't exist. 

### Affected platform

Online demo

### Operating system

Mac OS Mojav 10.14.6

### Browser

Safari 14.1.2, Chrome Version 94.0.4606.61

**Comment by relrelb** [comment]
Could you please provide a link to the SWF?

**Comment by starblinky** [comment]
I added a zip folder with FLA and SWF example of what's happening

[Archive.zip](https://github.com/ruffle-rs/ruffle/files/7524663/Archive.zip)

**Comment by kmeisthax** [comment]
#5573 might have triggered this
