### ISSUE TITLE
"Vintage Carbon Auto Theft" has no collision detection

### ISSUE THREAD

**Issue by SecularSteve** [ruffle-rs/ruffle#5600]
### Describe the bug

The car just goes through everything. And I mean everything...

### Expected behavior

For the car to collide with anything solid (the walls, the cars, the tires, the columns). In order to trigger a Game Over screen.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Mozilla Firefox 94

### Additional information

The site:

https://www.gamesflow.com/jeux.php?id=249015

**Comment by Toad06** [comment]
Thanks for the report.

Looks like this is caused by `BitmapData.draw` and `BitmapData.getColorBoundsRect`, which are currently unimplemented (#290).

**Comment by Lord-McSweeney** [comment]
The car collides properly now.
