### ISSUE TITLE
wrong logo display

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#5616]
The following Python [logo](https://github.com/ruffle-rs/ruffle/files/7492970/python.swf.txt) (remove `.txt` extension to get the SWF file is displayed poorly in https://ruffle.rs/demo/:

![pyruffle](https://user-images.githubusercontent.com/203767/140659508-582d12e1-031f-4cf6-8334-953162533c3e.png)

Flash player displays it right:

![pyflash](https://user-images.githubusercontent.com/203767/140659507-de1b4280-20d5-4d59-bf60-ba489a26de72.png)

Just in case it might help, `pdf2swf` (from SWFTools) reported the following during conversion:

```
NOTICE  File contains forms
NOTICE  File contains transparency groups
NOTICE  File contains shaded fills
NOTICE  File contains axial shaded fills
``

**Comment by Toad06** [comment]
Seems like the `clipDepth` property is ignored in the tag info (objects 12 and 14 in JPEXS).

There's also another issue that only affects the canvas renderer:

![canvr](https://user-images.githubusercontent.com/14274782/140661958-f10161b7-97ab-4361-a64f-a02d722ce473.png)

**Comment by ousia** [comment]
The Firefox [logo](https://github.com/ruffle-rs/ruffle/files/7493124/firefox.swf.txt) seems to have similar problems:

```
NOTICE  File contains shaded fills
NOTICE  File contains axial shaded fills
NOTICE  File contains radial shaded fills
NOTICE  File contains soft masks
```

Ruffle is displayed this way:

![ffruffle](https://user-images.githubusercontent.com/203767/140662573-da5857ab-e36c-430a-9cdc-02f7cb5c3492.png)

But Flash displays it correctly:

![ffflash](https://user-images.githubusercontent.com/203767/140662571-63b727d7-3b6c-4f69-a8e4-037e5208dd05.png)
