### ISSUE TITLE
"Marisa and Pocky Game" does not work properly

### ISSUE THREAD

**Issue by gensokyo-kenken** [ruffle-rs/ruffle#5648]
[魔理沙とポッキーゲーム(Marisa and Pocky Game)](http://hkz.kitunebi.com/flash/marisapocky.html)
I don't see the buttons that normally appear.
通常表示されるボタンが表示されません。

Works with Flash(http://flamani.blog.fc2.com/blog-entry-902.html)
![IMG_20211112_174928.jpg](https://user-images.githubusercontent.com/51988985/141438369-901befa3-19f3-4ab1-92c9-2636745650b6.jpg)

Works with Ruffle
![IMG_20211112_175446.jpg](https://user-images.githubusercontent.com/51988985/141439125-441c3968-f108-4473-9f5c-f0fbf1097570.jpg)

**Comment by Toad06** [comment]
Thanks for the report.

Ruffle seems to ignore the `autosize` parameter in `texts/DefineEditText (44)`. As a consequence, Ruffle uses the `xmax` and `ymax` parameters both holding a value of 0, preventing the text/button from being displayed.

**Comment by ousia** [comment]
@Toad, I wonder whether issues #1560 and #2999 might be related to this issue and also whether #6343 might fix them.

**Comment by ousia** [comment]
I apologize to @toad, since I meant @Toad06 in my previous comment.

**Comment by Toad06** [comment]
> @Toad06, I wonder whether issues #1560 and #2999 might be related to this issue and also whether #6343 might fix them.

No sorry, #6343 won't help for the issues you mentioned.

**Comment by Toad06** [comment]
Fixed by #6343.
