### ISSUE TITLE
Text is not correctly displayed in the attached sample

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5658]
[Sample](https://github.com/ruffle-rs/ruffle/files/7532698/sample.zip)

Nightly 2021-11-11:
![11](https://user-images.githubusercontent.com/14274782/141658003-ae8ae548-ad94-44c7-af40-e7a5be3e2560.png)

Nightly 2021-11-12:
![12](https://user-images.githubusercontent.com/14274782/141658005-cea2937c-aa43-4f0e-bb4c-9561c1476c4c.png)

**Comment by relrelb** [comment]
Thanks for the report! Probably caused by #5611. Will look into this later.
