### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

### ISSUE THREAD

**Issue by chxsjakdb** [ruffle-rs/ruffle#5683]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

# Browser Info
Useragent: Mozilla/5.0 (Linux; U; Android 11; zh-cn; M2104K10AC Build/RP1A.200720.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.116 Mobile Safari/537.36 XiaoMi/MiuiBrowser/15.5.16
OS: Linux aarch64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by adrian17** [comment]
They're using a >3 year old version of Ruffle, and looks like there's something badly configured on their page. I don't think we can do anything here.
