### ISSUE TITLE
Problem displaying image at http://buyingtime.webcomic.ws/comics/30/

### ISSUE THREAD

**Issue by jonathancreedon** [ruffle-rs/ruffle#5695]
### Describe the bug

![image](https://user-images.githubusercontent.com/42479937/142744287-7fc211d4-9d87-4a62-9d60-026d28292631.png)

The webpage pictured above is from a webcomic that uses Flash animation.  It seems what was intended to be a filter or background effect is instead covering the entire image.

### Expected behavior

The image should be of a cinema audience as they are reacting to the film showing offscreen but instead a flashing colored square is shown.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome

**Comment by relrelb** [comment]
Requires `BlendMode::Multiply`, which is currently unimplemented (#58).

**Comment by Lord-McSweeney** [comment]
Fixed by #8262 and #9134.
