### ISSUE TITLE
Dragon Ball Devolution no download option in context menu

### ISSUE THREAD

**Issue by MaverickHunter07** [ruffle-rs/ruffle#5696]
### Describe the bug

I manually installed the extension in Microsoft Edge, then opened the game. When I right clicked it, there was no download option in the context menu. I made sure to toggle it on in the settings menu. The game's official website is [https://www.txori.com/index.php?static5/dbdevolution](url).
Context menu:
![screenshot (95)](https://user-images.githubusercontent.com/49660722/142749349-3af9d0a3-67db-490d-818f-b2ff8f12cfaf.PNG)
My settings:
![screenshot (96)](https://user-images.githubusercontent.com/49660722/142749350-306855b2-5ec1-43fd-b3ae-37aa3eaa7538.PNG)
Someone on Ruffle's official discord (nosamu#3385) stated that they "think it must be a conflict between the selfhosted and extension versions of Ruffle, since the website is self-hosting" and that they "think that even though the extension version of Ruffle is loaded, the preferences are loaded from the webpage instead of from the extension".
You can see the full Discord conversation here: [https://discord.com/channels/610531541889581066/722872096002408529/911812753604378634](url).

### Expected behavior

I expected there to be a download option in the context menu.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge Version 96.0.1054.29 (Official build) (64-bit)

**Comment by ousia** [comment]
@MaverickHunter07, sorry but I think I’m not getting your point here.

Preferences such as this one should be read from the selfhosted extension (if the site has any).

There may be legitimate reasons to publish animations and to disallow downloading them.

If that could be bypassed by installing the browser extension, it would make no sense to have the option on the selfhosted extension.

Many thanks for your help.

**Comment by danielhjacobs** [comment]
@ousia This was added to the extension options (the same place as where you choose whether to load Ruffle in the current tab) but the self-hosted configuration takes priority. showSwfDownload defaults to false, so you can't download the game if the site self-hosts, and most site-owners are not going to explicitly allow the swf to be downloaded in the configuration, but may not have a problem with users doing so either.

**Comment by ousia** [comment]
@danielhjacobs, many thanks for your reply.

I have tried it at both https://free-culture.tk/ and https://free-culture.tk/original/.

The first one uses a loader (https://free-culture.tk/lfc-loader.swf) for the actual presentation (https://free-culture.tk/lfc-presentation.swf) with `loadMovie()`.

In such a case, it seems that only the loader can be downloaded (btw, I don’t know whether this is intended).

I think that a good compromise solution would be that if and only if the site owner explicitly sets `showSwfDownload: false`, this configuration should be honored by the browser extension.

Both users and site owners would have options in this way.

**Comment by Txori** [comment]
This isn't a bug. showSwfDownload being set to false works exactly as I intend it to on my website.
Please support my work if you want the game to continue evolving.
