### ISSUE TITLE
Nightly update of 11/21 gave a Firefox incompatability error 

### ISSUE THREAD

**Issue by C-Listensprechen** [ruffle-rs/ruffle#5699]
### Describe the bug

Ruffle Nightly 11/21 generated an incompatability error in Firefox version 89 and so was unable to load.
I don't want to update the browser to 9
![Firefox-Ruffle-error-1](https://user-images.githubusercontent.com/78556139/142773273-59164ed2-b505-467c-9c5d-6d626a6b8db6.jpg)
0.

### Expected behavior

I expect compatability without any errors even on one generation older Firefox versions, let alone other earlier versions

### Affected platform

Browser's extension

### Operating system

Windows 7

### Browser

Mozilla Firefox 89.0

### Additional information

See attached screenshot.

**Comment by midgleyc** [comment]
The current version is 94, and the LTS version is 91. 89 is currently 5 major versions out of date, and also below the current LTS release. We make no guarantees of support for older versions.

We updated the required version to try to fix the inability to sign the extension (which hasn't worked so far). Even so, we don't make any efforts to support versions beyond the last LTS. Why don't you want to upgrade? I don't think there are any major changes between 89 and the current latest: Proton came in in 89, and Fission comes in 96 I think.

**Comment by torokati44** [comment]
That is a fair point @midgleyc ut since there was no other reason for the bump than what you mentioned, and that didn't really work out either, we could just as well revert the version bump, no?

**Comment by midgleyc** [comment]
Yeah. I can put in a PR tonight.

I still would recommend that folk upgrade, though.
