### ISSUE TITLE
Allow calling of flash functions from javascript

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#571]
[free80sarcade.com](http://free80sarcade.com) uses a very old version of [dynamicaudio.js](https://github.com/bfirsh/dynamicaudio.js) for audio in its html5 games, which uses a flash polyfill in all browsers except very old versions of firefox. This does not work in ruffle because it doesn't support calling flash functions from javascript.

**Comment by Dinnerbone** [comment]
#1092 adds ExternalInterface, but the specific movie used in that framework seems to be ActionScript 3 so it'll still be broken for a bit.

**Comment by Justin-CB** [comment]
Alright, this should be closed, too(AVM2 support may be necessary to run the specific example that I gave, but that's a separate issue).
