### ISSUE TITLE
Weird behavior in Vector TD

### ISSUE THREAD

**Issue by Computerdude77** [ruffle-rs/ruffle#5711]
### Describe the bug

In the game [Vector TD](https://www.coolstreaming.us/forum/arcade/game/2455.html), there seems to be an issue where the towers will destroy one enemy and then not stop firing, causing money and points to be racked up quickly in this glitched state. This is on the most recent web extension version of Ruffle, which is 2021-11-23 at the time of writing this.

https://user-images.githubusercontent.com/55714746/143133468-44d41ba6-8d3a-4e5f-9235-626f4f29d648.mp4

### Expected behavior

The tower is supposed to stop firing and target another enemy, awarding the player with a normal amount of points and money.

https://user-images.githubusercontent.com/55714746/143133874-31601950-44a6-4b07-b166-37d6376e97d3.mp4

### Affected platform

Browser's extension

### Operating system

Windows 10 21H1

### Browser

Chrome 96

**Comment by adrian17** [comment]
(At a glance, I'm pretty sure this is the same issue as https://github.com/ruffle-rs/ruffle/issues/3839 , with attempted fix hanging in https://github.com/ruffle-rs/ruffle/pull/5492 .)
