### ISSUE TITLE
AVM2 error: VerifyError: Trait z in class BitmapAsset marked as override, does not override any other trait

### ISSUE THREAD

**Issue by rameshvarun** [ruffle-rs/ruffle#5719]
### Describe the bug

I'm testing out Ruffle's AS3 support, which I know is WIP. I tried with [this SWF](https://github.com/ruffle-rs/ruffle/files/7603966/MrCow.zip) and got the following error.

```
AVM2 error: VerifyError: Trait z in class BitmapAsset marked as override, does not override any other trait
```

I think the offending source is coming from the Flex SDK.

### Expected behavior

I think this error occurs because DisplayObject does not implement the `z` property yet.

~~I would expect this to be allowed since the SWF works in the original Flash Player. If I comment out [this condition in avm2/class.rs](https://github.com/ruffle-rs/ruffle/blob/79deba87f3d8e93cc990f657b14ca3af396afc5a/core/src/avm2/class.rs#L452) the error disappears and the class seems to be initialized.~~

~~Is it possible that Ruffle is being too strict with this check?~~

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by adrian17** [comment]
You're right, we haven't added 3D-related properties yet. I imagine we could add them as no-ops for now; the only remaining consideration is that we didn't implement version-aware lookups (`z` is supposed to be available since SWF10), but that could probably be left for later.

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
