### ISSUE TITLE
"Ed Edd 'n Eddy: The Ed Touchables" won't load properly...

### ISSUE THREAD

**Issue by SecularSteve** [ruffle-rs/ruffle#5760]
### Describe the bug

Every time I try to run the SWF in the Demo mode of Ruffle, it just shows up stuck on 90%:

![Screenshot 2021-11-29 at 20-34-20 Ruffle Web Demo](https://user-images.githubusercontent.com/33793273/143931165-1777d55f-e97f-493e-a45e-16c68f187a0b.png)

And if I "Right Click > Play", it literally bugs out, and throws everything all at once on the screen:

![Screenshot 2021-11-29 at 20-34-43 Ruffle Web Demo](https://user-images.githubusercontent.com/33793273/143931291-0aa80cbc-aee2-40a5-9d67-fd0e96243f59.png)

### Expected behavior

Just for the game to get to the Title Screen so you can play it like this:

https://www.youtube.com/watch?v=SwidESeYug4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Mozilla Firefox 94

### Additional information

You're going to need the raw SWF, because for some reason (or error), the game won't run out of the browser directly:

[EEnE_The_Ed_Touchables.zip](https://github.com/ruffle-rs/ruffle/files/7620694/EEnE_The_Ed_Touchables.zip)

**Comment by GoonyBaloney** [comment]
The attached SWF doesn't even work probably on the actual Flash Player as it's missing other files [config.xml, sounds.swf]

![2024-02-17 03_25_51-Adobe Flash Player 32](https://github.com/ruffle-rs/ruffle/assets/54896404/6ede367f-ce15-4f0c-a695-4d44ad90bdb1)
![2024-02-17 03_26_06-Adobe Flash Player 32](https://github.com/ruffle-rs/ruffle/assets/54896404/92c2de0d-4183-484b-b589-a12909caa535)

I've downloaded one directly from Flashpoint and it loads properly on Ruffle
![2024-02-18 23_30_55-Ruffle - lib_ENG swf](https://github.com/ruffle-rs/ruffle/assets/54896404/afaf5fd7-bf54-4aa8-b9ca-c7df460e1f4c)
