### ISSUE TITLE
Regression on Adrenaline Challenge 

### ISSUE THREAD

**Issue by liberodark** [ruffle-rs/ruffle#5768]
### Describe the bug

At lvl 2 (Hybrid Rainbow) you instant die.
But on old version of ruffle : Nightly 2021-10-19 is work without issue
And on Nightly 2021-11-30 is not work correcly.
Last version have regression.

Nightly 2021-11-30 :
![image](https://user-images.githubusercontent.com/4238928/144030137-d6c6533c-0fce-44fb-aa96-e4b65826e95c.png)

Nightly 2021-10-19 :
![image](https://user-images.githubusercontent.com/4238928/144030347-9afb8257-70de-4bad-ac19-589de3861d07.png)

Game : 
[Adrenaline Challenge.swf.zip](https://github.com/ruffle-rs/ruffle/files/7624537/Adrenaline.Challenge.swf.zip)
### Affected platform

Desktop app

### Operating system

Linux

**Comment by sombraguerrero** [comment]
I confirmed that this broke on the 11/2/21 nightly, and according to the compare, that is exactly what happened.
https://github.com/ruffle-rs/ruffle/compare/nightly-2021-11-01...nightly-2021-11-02

**Comment by Herschel** [comment]
Fixed by #5975.
