### ISSUE TITLE
Ferry Halim's Winterbells doesn't load

### ISSUE THREAD

**Issue by rmst** [ruffle-rs/ruffle#5776]
### Describe the bug

Neither `https://www.ferryhalim.com/orisinal/g3/bells.swf` nor `https://www.ferryhalim.com/orisinal/g3/00bells.swf` load properly. Context: https://en.wikipedia.org/wiki/Orisinal.

### Expected behavior

The game loads properly

### Affected platform

Online demo

### Operating system

MacOS Arm

### Browser

Chrome 96

**Comment by Toad06** [comment]
Thanks for the report.

This game will not work on the online demo as it implements mechanisms that somehow lock the SWF to a specific domain name. For this reason, the file doesn't work on the Flash Player Projector as well.

Instead you can use [the last version of the Ruffle extension](https://github.com/ruffle-rs/ruffle/tags) and play on the Orisinal website directly:
http://www.ferryhalim.com/orisinal/g3/bells.htm

**Comment by rmst** [comment]
Works perfectly! I had tried the Ruffle extension before your comment but it didn't work so I assume you fixed it as a response to this issue, thanks a lot!!
