### ISSUE TITLE
Simplify build process for various web targets

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#578]
Currently, we run `npm run build` in several different directories to build the various web targets. All of these build scripts more or less do the same thing, building the Rust code into `src/pkg`. There are also several `package.json`s and webpack configs that get out of sync and are annoying to maintain. Dependabot is currently only caring about `web/selfhosted`.

It'd be nice to consolidate these into a single `package.json` and `webpack.config.js` in `web/src`. This would build the Rust core a single time, package it for the various subtargets, and copy it around as otherwise necessary (for example, copying into `web/demo` and `web/extension`.) Commands could be added to this single script to allow for building specific targets.

This is also nice because the `web/demo` would act more like a proper example of how a user could use Ruffle using the final packaged bundle, as opposed to webpacking in the demo JS as currently happens.

**Comment by Dinnerbone** [comment]
It may be worth switching to Yarn, they support workspaces and it would work much the same way that our rust source does - we can split it off into components that can depend on one another, reuse the same common library versions, etc

**Comment by Herschel** [comment]
I'm not familiar with yarn, how does it work exactly? Would it replace `npm` in the build process? I'm a little wary of adding "yet another thing to install", but if it simplifies things, I'd be okay with trying.

**Comment by Dinnerbone** [comment]
It's a replacement for npm, often preferred for multiple or "complex" setups (which I'd argue ours is). It could simplify our web build scripts quite a lot.
