### ISSUE TITLE
DisplayObject blend mode tracking issue

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#58]
Desktop:
 - [x] Normal
 - [x] Layer
 - [x] Add
 - [x] Alpha
 - [x] Darken
 - [x] Difference
 - [x] Erase
 - [x] Hardlight
 - [x] Invert
 - [x] Lighten
 - [x] Multiply
 - [x] Overlay
 - [x] Screen
 - [x] Subtract
 - [ ] Shader (Pixel Bender)

Web canvas:
 - [x] Normal
 - [x] Layer
 - [x] Add
 - [x] Alpha
 - [x] Darken
 - [x] Difference
 - [x] Erase
 - [x] Hardlight
 - [x] Invert
 - [x] Lighten
 - [x] Multiply
 - [x] Overlay
 - [x] Screen
 - [x] Subtract
 - [ ] Shader (Pixel Bender)

ActionScript:
 - [x] `DisplayObject.blendMode`
 - [ ] `DisplayObject.blendShader`

**Comment by wizzwizz4** [comment]
Some of those (Screen, I think, and some others) don't have a single definition. It'll take some snooping, and maybe reverse-engineering, to figure out which algorithm they're using.

**Comment by karliss** [comment]
AS3 documentation https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/DisplayObject.html#blendMode has a bit more information than swf format specification.

**Comment by Herschel** [comment]
All of the non-normal blend modes cause the display object to have "cache as bitmap" type behavior, where the display object is rendered into an offscreen render target first, and then rendered with the blend mode onto the stage. In fact, Layer blend mode is just Normal with the offscreen buffer behavior.

So the first step is to implement render target functionality in `RenderBackend`. It's already there for masking on web, but needs to be added to desktop.

**Comment by ThisFlyingPotato** [comment]
Lacks blend effect

<details>
  <summary>Screenshots</summary>
First is how it is with Ruffle, second is how it is supposed to be.


![ruffle2](https://user-images.githubusercontent.com/69724149/116792286-fb81df00-aabf-11eb-9c7c-83fc0468a030.png)
![correct2](https://user-images.githubusercontent.com/69724149/116792310-15bbbd00-aac0-11eb-9d1f-ec5cadffba16.png)
![ruffle](https://user-images.githubusercontent.com/69724149/116792311-1b190780-aac0-11eb-94d5-912898330831.png)
![correct1](https://user-images.githubusercontent.com/69724149/116792303-0c325500-aac0-11eb-9ef1-45b6e9634e57.png)

OS : Win7-64bits
Both on the Chrome Extension and standalone
On ruffle-nightly-2021_05_01
</details>

**Comment by gskt17** [comment]
> All of the non-normal blend modes cause the display object to have "cache as bitmap" behavior, where the display object is rendered into an offscreen render target first, and then this buffer is drawn onto the stage. Same with all the filters. In fact, Layer blend mode is just Normal with the offscreen buffer behavior.
> 
> So the first step is to implement render target functionality in `RenderBackend`. It's already there for masking on web, but needs to be added to desktop.

So...has this functionality been added for desktop yet? What is our plan for implementing this feature?

**Comment by torokati44** [comment]
Well, I wouldn't call it much if a plan, just my ramblings from a while ago:
https://github.com/ruffle-rs/ruffle/discussions/4288

**Comment by Lord-McSweeney** [comment]
Blend modes have been implemented by #8262, and will appear in web after #9134 is merged.

**Comment by Kippykip** [comment]
Looks like there is an improvement!
Although "Clown Killer 2" still seems to have some blending related display issues
![image_2023-01-23_055658283](https://user-images.githubusercontent.com/33023808/213937410-b084bb72-567e-4d36-9239-2ed8b53d4d1b.png)

**Comment by Lord-McSweeney** [comment]
The only one left unimplemented here is `blendShader` (`BlendMode.SHADER`).

**Comment by Kippykip** [comment]
Excellent progress! :D 
There are some minor glitches with the blur but it is looking very close to the original game!
The health bar finally visibly goes down too!

I think Clown Killer 2 is a great testing SWF for special GFX effects, since it uses a lot of blends, uses text outline glow extensively, and has those health shade bar effects (eggy easter also used it)
![image](https://github.com/ruffle-rs/ruffle/assets/33023808/40a29796-6c36-4e44-8417-4bd8b448345c)
![image](https://github.com/ruffle-rs/ruffle/assets/33023808/7a6995b6-f44d-497a-aff2-64787180e4d4)
![image](https://github.com/ruffle-rs/ruffle/assets/33023808/e10aa60e-46a0-423d-9874-0448d7de083e)

**Comment by Lord-McSweeney** [comment]
Finally closed by #12238.

**Comment by Kippykip** [comment]
![image](https://github.com/ruffle-rs/ruffle/assets/33023808/0549658e-a51e-4a5b-aa29-808960a15f58)
Amazing!!! Pretty much perfect now under ruffle.
