### ISSUE TITLE
Error on https://www.miniclip.com/games/free-running-2/en/#t-c-f-C

### ISSUE THREAD

**Issue by kinkomar51** [ruffle-rs/ruffle#5809]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://www.miniclip.com/js/ruffle/ruffle.js:1:68321
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (https://www.miniclip.com/js/ruffle/ruffle.js:1:67974)
    at https://www.miniclip.com/js/ruffle/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at Function.yi.e (https://www.miniclip.com/js/ruffle/ruffle.js:1:35865)
    at o (https://www.miniclip.com/js/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://www.miniclip.com/js/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: //static.miniclipcdn.com/webgl/gameloader.swf
Param base: https://static.miniclipcdn.com/games/free-running-2/en/
Param allowScriptAccess: always
Param flashvars: mc_gamename=Free Running 2&mc_hsname=3798&mc_iconBig=freerunning2christmasmedicon.jpg&mc_icon=freerunning2christmassmallicon.jpg&mc_negativescore=0&mc_players_site=1&mc_scoreistime=0&mc_lowscore=0&mc_width=680&mc_height=510&mc_lang=en&mc_webmaster=0&mc_playerbutton=0&mc_v2=1&loggedin=0&mc_loggedin=0&mc_uid=0&mc_sessid=1403cd9fa0997e9aff2c62e2b5e08faa&mc_shockwave=0&mc_ua=051418e&mc_geo=us-west-2&mc_geoCode=SA&vid=1&vtype=ima&m_vid=0&mc_preroll_check=1&channel=miniclip.preroll&m_channel=miniclip.midroll&s_content=0&mc_plat_id=2&mc_extra=enable_personalized_ads=1&mc_image_cdn_path=https://avatars.miniclip.com/&login_allowed=1&dfp_video_url=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D600x400%26iu%3D%2F116850162%2FMiniclip.com_Preroll%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26cust_params%3D%26npa%3D0%26cust_params%3DgCat%253Dcategory_3%2526gName%253Dgame_3798%2526width%253D680%2526height%253D510%2526page_domain%253Dgames%2526gAATF%253Dgaatf_Y%2526gLanguage%253Dlanguage_en%2526gPageType%253Dpagetype_gamepage%2526gDemo1%253Ddemo1_2%2526gDemo2%253Ddemo2_3%2526gPageUrl%253Dhttps%25253A%25252F%25252Fwww.miniclip.com%25252Fgames%25252Ffree-running-2%25252Fen%25252F%26url%3D&amfhost=amf-us-west-2&fn=JSProxy.swf&adMiniclipVideo=null&quantSegs=null&bin=0
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.miniclip.com/games/free-running-2/en/#t-c-f-C

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by kinkomar51** [comment]
fgjklghljoiuytjkl

**Comment by kinkomar51** [comment]
bcnmhgfdjhfd

**Comment by kinkomar51** [comment]
lkjhddfhgjuytrghjkllkjhgdfghjkliufddfghjk.

**Comment by danielhjacobs** [comment]
This issue was using a version of Microsoft Edge that included Super Duper Secure mode. This issue was most likely a result of enabling that mode, which did not allow the execution of WebAssembly, required by Ruffle. Since then, Super Duper Secure mode was renamed Enhanced Security Mode, and a new WebAssembly interpreter was released for that mode, which means Ruffle should now work even with that enabled. However, it may be slow, as noted in https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-it-runs-extremely-slowly-or-i-get-a-something-went-wrong-error. As such, closing this issue.
