### ISSUE TITLE
Prefer extension options over default configuration for any options defined in both locations

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#5825]
For showSwfDownload, logLevel, and warnOnUnsupportedContent, on any sites which self-host Ruffle already, prefer the extension toggle over the self-hosted configuration (or default values, which are currently preferred if the values are not set in the configuration). Continue to obey configuration for options that are not toggleable with the extension, like base.

Up for debate: Decide whether to only ignore the default self-hosted configuration values that are not explicitly set, or to always ignore self-hosted configuration options in favor of extension toggles.

**Comment by Elementtair** [comment]
From my point of view, I would feel it as disrepectfull to override self-host configuration for a stable release.
