### ISSUE TITLE
SWF file broken

### ISSUE THREAD

**Issue by EnderquakeYT** [ruffle-rs/ruffle#5831]
### Describe the bug

When using the **browser extension** to play http://i.notdoppler.com/files/ragdollachievement2.swf, all it does is display a white screen, play sounds, then shows an incompatibility warning and after continuing, it goes into a loading loop and displays something like this: 
![image](https://user-images.githubusercontent.com/59123442/145457955-4d7ef60d-d843-4b3c-9a88-db9db2d72813.png)
Steps to reproduce: Type http://i.notdoppler.com/files/ragdollachievement2.swf into the url bar with the ruffle extension installed, click run anyways on the compatibility warning and see for yourself.

### Expected behavior

Expected behavior: Preferably runs the game normally, if not then say something along the lines of: **Sorry! This content is not yet supported by the Ruffle emulator and can't be played yet.**

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 96.0.4664.93

### Additional information

Please at least make it muted so it doesn't start playing music while in an errored state

**Comment by danielhjacobs** [comment]
The compatibility warning displayed says basically exactly what you suggested: "Flash player has been removed from browsers in 2021. **This content is not yet supported by the Ruffle emulator and will likely not run as intended.**" This is #1368.

**Comment by Lord-McSweeney** [comment]
This isn't a case of #8309.
There are a number of errors in the console on the latest version:
<code>

ERROR core/src/display_object/movie_clip.rs:2039 Got RustError("Cannot set undefined property ::componentInspectorSetting on Some(TextLocalized::LocalizedText)") when constructing AVM2 side of movie clip of type RA2_fla::langSelect_14

ERROR core/src/display_object/movie_clip.rs:2363 Error occured when running AVM2 frame script: RustError("Attempted to call \\"\\" with 1 arguments (more than 0 is prohibited)")

ERROR core/src/avm2/events.rs:422 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2143278 }) to handler FunctionObject(FunctionObject { ptr: 0x4660c0 }) : RustError("Font.enumerateFonts is a stub")

</code>

**Comment by Lord-McSweeney** [comment]
#9647 progresses this to `Error occured when running AVM2 frame script: RustError("Failed to parse XML: RustError(\"XML declaration BytesDecl { element: BytesStart { buf: \\\"xml version=\\\\\\\"1.0\\\\\\\" encoding=\\\\\\\"UTF-8\\\\\\\"\\\", name_len: 3 } } is not yet implemented\")")`.

**Comment by Lord-McSweeney** [comment]
This can now get to the main menu, but it needs `net.Socket` support, which is unlikely to be implemented anytime soon.

**Comment by Lord-McSweeney** [comment]
This seems to work now, but has issues with the ragdoll performance.
