### ISSUE TITLE
Hebrew characters are not displayed properly.

### ISSUE THREAD

**Issue by dhtdht020** [ruffle-rs/ruffle#5839]
### Describe the bug

Hebrew embedded text, which used to appear correctly (although, with characters in incorrect order: #3921), appear to no longer display properly.

When hebrew text is used, rather than drawing the hebrew letters, a combination of incorrect characters appears.

Here is a screenshot showing [clock.swf](https://github.com/ruffle-rs/ruffle/files/6273851/clock.zip) on Flash Player 29, and the regression between an old version of Nightly 2021-04-07 (which displayed hebrew characters), and current version Nightly 2021-12-10 (which displays incorrect characters):

![image](https://user-images.githubusercontent.com/18469146/145615594-6758a587-5996-4c10-b80b-3471e11d6967.png)

Link to SWF: [clock.zip](https://github.com/ruffle-rs/ruffle/files/6273851/clock.zip)

### Expected behavior

Hebrew characters are displayed when hebrew text is embedded.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by adrian17** [comment]
@moulins it appears to have regressed on the first nightly after UTF16 refactor was merged, do you want to take a look?
