### ISSUE TITLE
if ruffle became flash maker? 

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5845]
i think good idea so we know something that's flash maker this is evolution FutureSplash, 2, 3, MX, 8, CS3, CS4, CS5, CS5.5, CS6 1996-2012 this is flash player (games and movie) i think it's good idea? "RuffleMaker" that's exist? i don't know we want this RuffleMaker

Look this is Help Video (Flash Maker)
https://youtube.com/playlist?list=PL7z8SQeih5AdCX6GRkiUocqUoPj0Zlzj2 Help Animation
https://youtu.be/r_QFlwRsOco Help Games

if ruffle created RuffleMaker?

**Comment by thatsprettygood** [comment]
That is wayyy out of the scope of this project.
You're completely welcome to try yourself though!
