### ISSUE TITLE
[FEATURE REQUEST] Unpackaging Ruffle From An External Source

### ISSUE THREAD

**Issue by 68r** [ruffle-rs/ruffle#5872]
I’m currently building a game site in Google Sites 2016  and they removed the option to directly upload files to your site. Is it possible for ruffle to be installed in html/js code by being unpackaged from an external source along with the iframe of the flash game? I think this feature would be very helpful to people as directly uploading files to a site is not an option in many popular site editors.

**Comment by yakagami** [comment]
Did you try hosting the ruffle.js file in a cdn and then calling that?

**Comment by n0samu** [comment]
Ruffle can be included from unpkg or another CDN, see https://ruffle.rs/#usage
