### ISSUE TITLE
Text with HTML elements is not displayed in the attached sample

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5873]
[Sample](https://github.com/ruffle-rs/ruffle/files/7728370/sample.zip)

`<p align='center'><b>H<font color='#ff0000'>ello</font> W<font color='#ff0000'>orld</font>.<br>Hello <font color='#ff0000'>World</font></b>.<br>H<font color='#ff0000'>ello</font> W<u><font color='#0000ff'><a href='http://www.macromedia.com/' target='_blank'>orld</a></font></u>.</p>`

The above text produces the following rendering:

Flash Player:
![flash](https://user-images.githubusercontent.com/14274782/146396910-c2680cbf-eb85-435d-822d-2764b026213b.png)

Ruffle <= nightly-2021-12-05:
![ruffle0512](https://user-images.githubusercontent.com/14274782/146397040-34b5c734-4461-4873-8416-30dbe6bbc6a1.png)

Ruffle >= nightly-2021-12-06:
_(nothing is displayed at all)_

Any version of Ruffle logs the following warning into the console:
`Error while parsing HTML: Expecting </br> found </b>`

It also appears that replacing `<br>` with `<br/>` in the file prevents the issue from happening.

**Comment by danielhjacobs** [comment]
I suspect https://github.com/ruffle-rs/ruffle/pull/5795/files#diff-0313d265738726ac783fa404fb5ffff0bf42894a2a806e514185620b9a63251fR780 for why nothing displays. A break was changed to a return (inside a loop).
