### ISSUE TITLE
Hello Ruffle so this is not supported flash games Armor Mayhem

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5877]
This is Armor Games Website
Created Game Date 2011

This SWF Games https://armor-mayhem.software.informer.com/download/
This Website Armor Games https://armorgames.com/play/10215/armor-mayhem

Thank You
-Deivid

**Comment by ellieeet123** [comment]
This is to be expected, the game you are trying to load here uses ActionScript 3 which is currently not supported by Ruffle. It will likely be a couple of months or maybe even longer until it is supported.

**Comment by Lord-McSweeney** [comment]
Closing in favor of #8754.
