### ISSUE TITLE
Friv Classic is here

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5880]
not me this is https://github.com/Tsyuay/FrivReborn called ''Friv Classic Reborn''
but it's deleted page help please https://tsyuay.github.io/FrivReborn/classic.html

**Comment by ellieeet123** [comment]
How is this related to ruffle?

**Comment by deividbinev12** [comment]
i used ruffle player

**Comment by Poopooracoocoo** [comment]
This is not Ruffle's fault.
