### ISSUE TITLE
[Phit] All menu names are displayed as 'test'

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#5887]
### Describe the bug

![image](https://user-images.githubusercontent.com/75052171/146628644-769faccd-f1a6-4599-8807-04f861a3d94b.png)

[phit.zip](https://github.com/ruffle-rs/ruffle/files/7738709/phit.zip)

In the main menu of the Phit game, Ruffle displays all the menus under the name 'test'.

Also, unlike the original, it has 4 menus.

### Expected behavior

The original menu should display correctly.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2 x64

### Browser

Google Chrome 96

**Comment by relrelb** [comment]
Fixed by #12541.
