### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Woainimams** [ruffle-rs/ruffle#5919]
# 错误信息
错误名称: TypeError
错误消息: 第一个参数必须是响应或响应的承诺
错误堆栈:
'''
@ [原生代码]
promiseReactionJob @ [本机代码]
'''

# 玩家信息
允许脚本访问: false

# 页面信息
页面URL: https:// uploads。不接地。net/ruffle_wrapper/ruffleembedhtml？v = 1。0。64 & browsermode = 移动和道具 = % 7B % 22皱褶 % 22% 3A % 22% 2 fruffle_wrapper % 2Flib % 2Fruffle。js % 3F1639324228% 22% 2C % 22 public_path % 22% 3A % 22% 2 fruffle_wrapper % 2Flib % 2F % 22% 2C % 22swf % 22% 3A % 22https % 3A % 2F % 2个Fuploads。不接地。净值 % 2f491000%2f491899_mnf_bdsm_club。swf % 3F1239981566% 22% 2C % 22vars % 22% 3A % 7B % 22 newgroundsapi_publisherid % 22% 3A1% 2C % 22 newgroundsapi_sandboxid % 22% 3A % 2261c62e9ccd279% 22% 2C % 22 newgroundsapi_sessionid % 22% 3A % 22% 2C % 22newgroundsapi _ 用户名 % 22% 3A % 22% 26lt % 3b删除 % 26gt % 3B % 22% 2C % 22newgroundsapi _ 用户名 % 22% 3A0% 2C % 22ng _ 用户名 % 22% 3A % 22% 26lt % 3b删除 % 26gt % 3B % 22% 7D % 2C % 22宽度 % 22% 3A640% 2C % 22高度 % 22% 3A480% 2C % 22图标 % 22% 3A % 22https % 3A % 2F % 2Fimg.ngfiles。com % 2默认 % 2图标端口-xl-a。gif % 3Ff1601395813% 22% 7D

# 浏览器信息
用户代理: Mozilla/5。0 (iPhone;苹果操作系统15_1_1，如苹果操作系统X;zh-CN) AppleWebKit/605.1.15 (KHTML，像壁虎) 移动/19B81 UCBrowser/13。7.2.1636移动AliApp(TUnionSDK/0。1.20.4)
操作系统: 苹果手机

# 皱褶信息
版本: 0。1.0
名称: 每晚2021-12
频道: 每晚
建造时间: 2021-12-12t00: 14:30。969Z
提交: 1f5979f1681cd886e0e2b8245ec43190175b58ba
是扩展名: false

**Comment by Poopooracoocoo** [comment]
Duplicate of #5918
