### ISSUE TITLE
Extension: CSP error for unmute overlay dummy sound

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#5927]
### Describe the bug

When playing an SWF in the extension's internal player page (using Firefox), after clicking anywhere within the game, this error appears in the browser console: 
```
Failed to play dummy sound: NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
Content Security Policy: The page’s settings blocked the loading of a resource at data:audio/wav;base64,UklGRisAAABXQVZFZm… (“default-src”).
```
As I understand it, Ruffle tries to play a dummy sound when the invisible unmute overlay is first clicked. But this fails because the extension's CSP settings don't allow loading data: URLs. This doesn't seem to cause any actual problem but I thought it might be worth reporting the bug anyway.

### Expected behavior

This error should not occur.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox 95

**Comment by relrelb** [comment]
Thanks for the report!
Unfortunately, I can't reproduce this on my end. I've played https://www.eyezmaze.com/grow/island/ on Firefox 95, latest nightly (2021-12-22), both in-page and in standalone player, without any errors. Can you please elaborate on some details that lead you to the problem?

**Comment by n0samu** [comment]
The error only occurs on the extension's internal viewer page. I get it for the game you linked: https://www.eyezmaze.com/game/grow_island.swf
I am using the extension version (2021-12-16) from the project's official AMO entry: https://addons.mozilla.org/firefox/addon/ruffle_rs/

Steps to reproduce:
1. Open the direct SWF link (it should automatically open the extension's internal viewer page)
2. Before clicking anywhere within the game screen, open Firefox's Developer Tools (console tab)
3. Click anywhere within the game screen and the error message should show up.

**Comment by Toad06** [comment]
I think this is a similar issue as the one that affected graphics on the canvas renderer (see the last part of https://github.com/ruffle-rs/ruffle/pull/5387#issuecomment-950022088 for details, and commit 71324a4ae842359340041a55b6d1cd270947ca7b for the fix).

**Comment by n0samu** [comment]
For whatever reason, this error seems to have disappeared. Closing this issue.
