### ISSUE TITLE
Blur not working.

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#5941]
### Describe the bug

[Untitled-1.zip](https://github.com/ruffle-rs/ruffle/files/7788924/Untitled-1.zip)

Real Time Blur not working.

### Expected behavior

Real time blurring works in official Flash player, this is AS2 code.

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by torokati44** [comment]
This is a known missing feature, see: https://github.com/ruffle-rs/ruffle/issues/15

**Comment by waspennator** [comment]
Still broken as of the latest nightly, the green rectangle doesn't have any blur when zooming on the screen and doesn't vanish when it reaches the top left of the screen.

**Comment by n0samu** [comment]
Blur effect is working now thanks to #12176

**Comment by n0samu** [comment]
Oh and this was a duplicate of #3717
