### ISSUE TITLE
[Bridge Savior] Ruffle freezes indefinitely when game over occurs.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#5951]
### Describe the bug

![image](https://user-images.githubusercontent.com/75052171/147808997-3c302ddd-1a79-4d76-a091-5e4ec49e7dbe.png)

[BridgeSavior.zip](https://github.com/ruffle-rs/ruffle/files/7795534/BridgeSavior.zip)

After starting the game on 'Bridge Savior', the Ruffle is frozen if it goes into a game over state after doing nothing for a while (about 30 seconds).

Ruffle goes into infinite freezing and the mouse context menu doesn't open either.

Ruffle Nightly 2021-12-31

### Expected behavior

Game over events should work normally.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H1

### Browser

Google Chrome 96

**Comment by relrelb** [comment]
This is probably caused by an infinite recursion in `DefineSprite 444/frame 1/PlaceObject 442`:
```as
onClipEvent(unload) {
    this.unloadMovie();
}
```
`this.unloadMovie()` fires the same clip event again.

**Comment by Jmousy** [comment]
I don't know where or how this was resolved, but I'll close the issue for now as the issue no longer reproduces in recent Nightly builds. Thanks for your help!
