### ISSUE TITLE
Kitten Cannon!: Newgrounds version reset bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#5958]
### Describe the bug

It's impossible to play this version cause every time you fire the cannon, the game immediately fades to black and resets itself. Just load this up and try to fire and it should do it every time.
https://www.newgrounds.com/portal/view/228520

### Expected behavior

You should be able to fire the cannon without the game resetting the exact moment you do.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 96

**Comment by Toad06** [comment]
Thanks for the report.

This is actually the same issue as #5577. When you press the spacebar to fire the cannon, Ruffle also incorrectly triggers the action of the invisible "Continue" button (`DefineButton2 (170)` in JPEXS) which restarts the stage.

The game was working in [nightly-2021-06-11](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-06-11) and the earlier releases, so one of these commits has likely introduced the regression: https://github.com/ruffle-rs/ruffle/compare/nightly-2021-06-11...nightly-2021-06-12

I've found a very simple way to fix this issue in https://github.com/ruffle-rs/ruffle/issues/5577#issuecomment-989669961 but I'm not sure if that's correct (@Herschel, maybe you could take a look at it? 😉).

**Comment by Herschel** [comment]
Fixed by #6123.
