### ISSUE TITLE
Error on https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=9471&mp_game_uid=faith-fighter&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Ffaith-fighter&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZmFpdGhmaWdodGVyLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Asia%2FJakarta&mp_view_type=

### ISSUE THREAD

**Issue by uyytg** [ruffle-rs/ruffle#5977]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: self.mask_state == MaskState::NoMask ||
    self.mask_state == MaskState::DrawMaskedContent', render/webgl/src/lib.rs:1301:9

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/faithfighter.swf
Param quality: high
Param allowscriptaccess: always
Param allowfullscreen: false
Param wmode: direct
Param flashvars: mp_log_level=4&mp_game_id=9471&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Ffaith-fighter&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_api_id=&mp_api_as3_url=&mp_api_as3_url_bck=&mp_api_user_id=&mp_api_user_token=&mp_locale=en_US&mp_timezone=Asia%2FJakarta&mp_embed=false&mp_base_path=https%3A%2F%2Fwww.minijuegosgratis.com%2Fflash1234%2Fno_hotlink%2F
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.miniplay.com/helpers/game/sandbox.php?mp_assets=https%3A%2F%2Fs2.minijuegosgratis.com%2F&mp_embed=0&mp_game_id=9471&mp_game_uid=faith-fighter&mp_game_url=https%3A%2F%2Fwww.miniplay.com%2Fembed%2Ffaith-fighter&mp_int=1&mp_locale=en_US&mp_player_type=FLASH&mp_player_url=aHR0cHM6Ly93d3cubWluaWp1ZWdvc2dyYXRpcy5jb20vZmxhc2gxMjM0L25vX2hvdGxpbmsvZmFpdGhmaWdodGVyLnN3Zg%3D%3D&mp_site_https_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_site_name=miniplay.com&mp_site_url=https%3A%2F%2Fwww.miniplay.com%2F&mp_timezone=Asia%2FJakarta&mp_view_type=
SWF URL: https://www.minijuegosgratis.com/flash1234/no_hotlink/faithfighter.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-13
Channel: nightly
Built: 2021-01-13T01:01:47.998Z
Commit: 63f2b4f02f8fa4fa69ce61a5f6710bb07fcd2f33

**Comment by Poopooracoocoo** [comment]
@uyytg Could you find a way to contact Miniplay? They're using a very outdated version of Ruffle. The error no longer occurs in newer versions of Ruffle. You can play the game without issue on Newgrounds: https://www.newgrounds.com/portal/view/421199?emulate=flash
