### ISSUE TITLE
Linear RGB setting is not implemented for gradients

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#598]
Visual test: https://github.com/ruffle-rs/visual-tests/tree/master/tests/simple_shapes/gradients/focal_radial

Expected:
![image](https://raw.githubusercontent.com/ruffle-rs/visual-tests/b11b1385bda5b1d2194020fb67cb4c637c0a8738/tests/simple_shapes/gradients/focal_radial/expected.png)

Actual:
![image](https://raw.githubusercontent.com/ruffle-rs/visual-tests/b11b1385bda5b1d2194020fb67cb4c637c0a8738/tests/simple_shapes/gradients/focal_radial/actual.png)

Reproduced with wgpu on desktop, and webgl on web.

**Comment by Herschel** [comment]
This is not related to focal gradients, but instead related to the Linear RGB setting. Linear RGB is not implemented yet (will require a new uniform into the shader to trigger converting to/from sRGB while interpolating). All gradient types will currently be incorrect if Linear RGB is set.

**Comment by Dinnerbone** [comment]
Aha! Good to know, thanks. I made this trying to reverse engineer why my drawing api was giving wrong results and thought it was that

**Comment by Dinnerbone** [comment]
Fixed in #619
