### ISSUE TITLE
DE_dust2: Unauthorized Access Error

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#5989]
### Describe the bug

Unsure if it's intentional or not, but when I try to watch this on newgrounds, it refuses to play the animation, saying that it's being hosted without permission.
https://www.newgrounds.com/portal/view/465817/format/flash
![DE Dust bug](https://user-images.githubusercontent.com/78768499/148145266-154cc88b-3c3f-4a1d-9b81-5174934dfcde.png)

### Expected behavior

The movie should be watchable without throwing up an "Unauthorized Access" error.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 96

**Comment by tsunamistate** [comment]
According to browser dev tools, the flash makes 2 requests upon loading, which are blocked by Same-Origin Policy
![image](https://user-images.githubusercontent.com/4958520/148426193-5e219fc1-2eb6-4124-83ad-900356236895.png)

It may be some sort of copy protection built into SFW

**Comment by Toad06** [comment]
Thanks for the report.

The movie performs checks to detect if the URL that hosts the file is allowed. Newgrounds is allowed with the HTTP protocol:
`safe = _url.indexOf("http://uploads.ungrounded.net");`

Unfortunately, this URL is no longer valid as Newgrounds now uses the HTTPS protocol. This is why the file no longer works, even with the official Flash Player.

#1486 could someday implement something to bypass this issue.

**Comment by waspennator** [comment]
Still occuring, but it is possible to get around it on desktop with the new gui by spoofing the base url and selecting the "upgrade HTTP to HTTPS" option

**Comment by stevethepocket** [comment]
Is the HTTP/HTTPS thing also what's tripping this one's copy protection?

https://www.masswerk.at/demospace/3d_testdrive.html

**Comment by tsunamistate** [comment]
This is solved by using spoofing http://uploads.ungrounded.net SFW URL in Desktop player
I believe there's also an option for URL spoofing in web version
