### ISSUE TITLE
Possible memory leaks on mobile browser

### ISSUE THREAD

**Issue by Dungeonation** [ruffle-rs/ruffle#5990]
### Describe the bug

Trying to play my work in progress Newgrounds game on a mobile browser causes the game to either freeze, or the page to reload in error. Playing on a PC doesn’t have this problem. It’s also behaved this way on my phone’s built in Safari.

Most common moments of freezes and crashes seem to be during loading the SWF, during an animation or after tapping around really frequently like during a fight.

The preview password for the game has been DMed to sombraguerrero.
https://www.newgrounds.com/projects/games/1634279/preview/filetype/0

### Expected behavior

Most other SWFs load and respond to tapping normally, though I haven’t tried rapidly tapping around other SWFs yet.

### Affected platform

Self-hosted version

### Operating system

iOS 14.8

### Browser

Opera GX 1.4.0

**Comment by sombraguerrero** [comment]
Tested both on Newgrounds and my test bed with self-host 1/3/2022. I don't appear to have any issues
Used Safari on iPhone 12 Pro, iOS 15.2

**Comment by Dungeonation** [comment]
I'm now on iOS 15, but the issue might be me using an iPhone 8?

**Comment by Dungeonation** [comment]
Appears to be a memory issue for older hardware, thanks :)
