### ISSUE TITLE
lv0 attempts to write Ruffle configuration, fails due to extension sandboxing

### ISSUE THREAD

**Issue by kmeisthax** [ruffle-rs/ruffle#600]
PR #537, an attempt to fool certain SWFObject embeds, appears to have gained code to attempt to set `window.RufflePlayer` with a default configuration in `lv0.js`. This won't work: the new configuration won't reach the website because `lv0.js` runs in the extension world (Chrome)/with Xrays (Firefox). It's also not necessary: we already ship with code that auto-configures and launches all polyfills if the website doesn't provide it's own configuration upon `DOMContentLoaded` (or after, if we're somehow really late).

This is also a slight policy shift that should be documented somewhere: it's no longer possible to opt-out of the `plugin-polyfill` without completely disabling the extension via `data-ruffle-optout`. This is because the extension cannot read `RufflePlayer.config` until after it's way too late to fool some early-loading `SWFObject` users.

**Comment by Justin-CB** [comment]
The reason why I tried to set `RufflePlayer.config` in `lv0.js` was to prevent the plugin polyfill from running twice and prevent trying to run the frame polyfill in the extension if we decide to run it by default. I was thinking that refactoring `plugin-polyfill.js` so it could be built separately and adding a script to inject that code to the `web/extension/build` directory would be a good idea, but I didn't have the skill to carry it out.

**Comment by n0samu** [comment]
Looks like this was fixed a long time ago
