### ISSUE TITLE
audio buffering causing mismatch in Sound.position()?

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#6010]
### Describe the bug

@Herschel,

this is a tricky issue with `Sound.position()", since _Ruffle_ introduces a mismatch when compared to the original _Flash Player_.

This happens in all animations, but I use this sample (<https://free-culture.tk/lfc-presentation.swf>) to display the issue. Its frame 46 (press right arrow 46 times to get to it) shows the issue.

The original scene can be found at <https://yewtu.be/watch?v=BBgghnQF6E4&t=250>.

In [the animation](https://free-culture.tk/lfc-presentation.swf), sound from video is recorded in the main sound file.

_Flash Player_ matches both sound and image (direct link to video <https://user-images.githubusercontent.com/203767/148681922-45a95b4d-cf16-4026-9e83-e2d2dd7003f4.mp4>): 

https://user-images.githubusercontent.com/203767/148681922-45a95b4d-cf16-4026-9e83-e2d2dd7003f4.mp4

But _Ruffle_ (nightly 2022-01-08) plays audio with about 500ms delay (direct link to video <https://user-images.githubusercontent.com/203767/148681925-f5d5c60a-f9ca-4bd0-b1ad-53931ea7540d.mp4>):

https://user-images.githubusercontent.com/203767/148681925-f5d5c60a-f9ca-4bd0-b1ad-53931ea7540d.mp4

It seems that _Flash Player_ introduces a delay in playing audio content of about 500ms. I was told (about a decade ago, so I don’t remember the details), that this comes from audio buffering.

### Expected behavior

There should be no mismatch in `Sound.position()` and audio playing between _Flash Player_ and _Ruffle_.

### Affected platform

Self-hosted version

### Operating system

All

### Browser

All

### Additional information

I don’t know whether the issue may be solved implementing _Frame subdivision for streaming sound_ from the _SWF File Format Specification_ (<https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf#page=186>).

I’m must confess the explanation is all Greek to me.

BTW, it is a real pain to preview content in three different windows for a single issue report.

**Comment by ousia** [comment]
[This (potential, back then) issue was originally reported in #202.]

BTW, I wonder whether other users that requested the implementation of `Sound.position()` experience this issue or similar issues related to this one (@zumbasana, @ChaseWaylon, @txori and @sombraguerrero).

**Comment by sombraguerrero** [comment]
@ousia Eh, possibly, but Onda's problems are more rooted in the frameskip issue, which was one of the items originally called out as part of #4273.

**Comment by ousia** [comment]
It isn’t clear to me that the cause is a different.

I need to investigate the issue further.

Closing the issue by now.
