### ISSUE TITLE
TextField.autoSize cuts the bottom of the last line of text

### ISSUE THREAD

**Issue by Txori** [ruffle-rs/ruffle#6011]
### Describe the bug

TextField.autoSize Property don't act the same on Flash and on Ruffle.
On Flash, the whole text is visible:
![autofill_flash](https://user-images.githubusercontent.com/3765943/148692339-cfb66173-fe3d-4a1b-b23a-532e39166d3c.png)
whereas on Ruffle (web, didn't try desktop version), the last line of text is truncated, cutting out tall letters such as "p".
![autofill_ruffle](https://user-images.githubusercontent.com/3765943/148692371-d3a0be0d-1813-4575-bb9e-6d1454b19eda.png)

I made an example with source downloadable here: https://www.txori.com/stuff/ruffle/debug/

### Expected behavior

TextField.autoSize should give the same size on Flash player and Ruffle.

The problem can be temporary solved in actionscript by adding this after setting the text:
txt._height += 5;

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 97

**Comment by Txori** [comment]
I just verified this morning: https://www.txori.com/stuff/ruffle/debug/text_autosize.php
I don't know since when, but this bug is fixed ;)

**Comment by torokati44** [comment]
Could have been fixed by https://github.com/ruffle-rs/ruffle/pull/6460 perhaps.
