### ISSUE TITLE
I'm trying to use ruffle on Glitch.com, however I keep getting this error

### ISSUE THREAD

**Issue by ericksoncohen** [ruffle-rs/ruffle#6029]
I'm working on a games site on glitch.com and I'm trying to get ruffle to work, I think I have everything configured correctly but I still continue to get this error, you can see the code here: https://glitch.com/edit/#!/ruffle-rs (not the full project but same error). Am I doing something wrong or is this an issue with ruffle/glitch?

# Error Info
Error name: CompileError
Error message: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 4e 6f 74 20 @+0
Error stack:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 4e 6f 74 20 @+0
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle-rs.glitch.me/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-11
Channel: nightly
Built: 2022-01-11T00:13:04.329Z
Commit: b39ab9034c5bff008a6cff32d0890e5d4cc0942b
Is extension: false

**Comment by adrian17** [comment]
If you look into devtools, you'll see that the .wasm file wasn't loaded at all (status 404).

**Comment by torokati44** [comment]
Which is strange, because the URL in the beginning of `ruffle.js` (https://cdn.glitch.global/7b3f6e09-b8ae-47f0-8107-d098780e414d/42ef41f25116839c8e75.wasm) does point to an available and perfectly intact copy of a release `.wasm` file.

**Comment by torokati44** [comment]
Except it is concatenated to a certain `n.p+`, so the actual URL the script tries to fetch from is: https://abalone-bubble-estimate.glitch.me/https://cdn.glitch.global/7b3f6e09-b8ae-47f0-8107-d098780e414d/42ef41f25116839c8e75.wasm
And that returns a 404.

Just removing that `n.p+` from before the URL fixed it for me.

Keeping that there, but replacing the string with just `"/42ef41f25116839c8e75.wasm"` "should" also work, but it doesn't for some reason...

**Comment by ericksoncohen** [comment]
> Except it is concatenated to a certain `n.p+`, so the actual URL the script tries to fetch from is: https://abalone-bubble-estimate.glitch.me/https://cdn.glitch.global/7b3f6e09-b8ae-47f0-8107-d098780e414d/42ef41f25116839c8e75.wasm And that returns a 404.
> 
> Just removing that `n.p+` from before the URL fixed it for me.
> 
> Keeping that there, but replacing the string with just `"/42ef41f25116839c8e75.wasm"` "should" also work, but it doesn't for some reason...

Thank you so much, that worked. That it doesn't work with `"/42ef41f25116839c8e75.wasm"` is because the glitch "asset" cdn is located at a different domain than the glitch.me project. this makes it try to get a file that does not exist in the directory.

**Comment by torokati44** [comment]
Glad to hear that. So can this be closed now, then?
