### ISSUE TITLE
Loading extension on Newgrounds results in missing .wasm file error

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#6042]
### Describe the bug

Run version 2022-01-13 of extension on https://www.newgrounds.com/portal/view/561860?emulate=flash 

### Expected behavior

No error.

### Affected platform

Browser's extension

### Operating system

Windows 10 21H2

### Browser

Google Chrome 97.0.4692.71

### Additional information

![image](https://user-images.githubusercontent.com/51363864/149262517-387afd8a-8f73-4aab-b95f-725e1e8e5583.png)

# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 966 failed.
(error: https://uploads.ungrounded.net/ruffle_wrapper/lib/966.js)
Error stack:
```
ChunkLoadError: Loading chunk 966 failed.
(error: https://uploads.ungrounded.net/ruffle_wrapper/lib/966.js)
    at Object.s.f.j (chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:1695)
    at chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:327
    at Array.reduce (<anonymous>)
    at Function.s.e (chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:305)
    at chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:4700
    at async R.ensureFreshInstance (chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:17486)
    at async R.load (chrome-extension://pfnhhbjpflcfonhglloecpkdlaniiina/dist/ruffle.js?id=74318532280:1:19917)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.64&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1641907039%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F561000%2F561860_sierra7_v102.swf%3F1297479127%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2261dfa0952d73c%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A750%2C%22height%22%3A340%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F561000%2Fflash_561860_card.png%3Ff1623158156%22%7D

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-13
Channel: nightly
Built: 2022-01-13T00:18:17.083Z
Commit: 70bb5fa3f2544882e027fbdf55f455e63f609133
Is extension: false

(is extension reports as false but I'm running version 2022-01-13 of the extension when Newgrounds runs 2022-01-11)

**Comment by Poopooracoocoo** [comment]
Should I close this as there are other issues for negotiation between extension and self-hosted versions of Ruffle?

**Comment by Herschel** [comment]
Is this a regression (does 1/12/2021 work?)

**Comment by Poopooracoocoo** [comment]
> Is this a regression (does 2022-01-12 work?)

No. It's not a regression. I can also reproduce this with 2021-12-18, the version on the CWS.

**Comment by Herschel** [comment]
Let's merge all of the extension+selfhosted conflict issues into one issue then. Thanks!

**Comment by Poopooracoocoo** [comment]
Closing in favour of #5547
