### ISSUE TITLE
Standalone Ruffle starting from nightly build 2022-01-12 doesn't work on Windows 7

### ISSUE THREAD

**Issue by SN902** [ruffle-rs/ruffle#6049]
### Describe the bug

When i try to run ruffle.exe, application asks for "api-ms-win-shcore-scaling-l1-1-1.dll" and can't find required file in system32 folder (because Shcore part of windows 8.1, which used for GetDPIForMonitor in AppCore.dll) 
![unknown](https://user-images.githubusercontent.com/38821724/149445897-e2e47d4e-f3c5-443e-9dc2-595c36970383.png)

### Expected behavior

Now it just doesn't work

### Affected platform

Desktop app

### Operating system

Windows 7 x64

### Additional information

Right now only one way to run Ruffle on windows 7 - copy patched stub: api-ms-win-shcore-scaling-l1-1-1.dll + msvcr120d.dll + mfc120ud.dll and after it will run without issues.

**Comment by SN902** [comment]
[dlls.zip](https://github.com/ruffle-rs/ruffle/files/7867638/dlls.zip)

**Comment by SN902** [comment]
Most likely this PR root of problem https://github.com/ruffle-rs/ruffle/pull/6024

**Comment by Poopooracoocoo** [comment]
https://github.com/jdm/tinyfiledialogs-rs/issues/36

**Comment by CoolDino1** [comment]
Try searching www.dll-files.com and see if you can find the missing dll file.

**Comment by relrelb** [comment]
This should have been fixed by #6265. `tinyfiledialogs` was replaced with `rfd`.
