### ISSUE TITLE
Raze is broken game with ruffle

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#6055]
### Describe the bug

hello ruffle
we have problem i used ruffle player
http://www.andkon.com/arcade/adventureaction/raze/ this is problem
fix please so this is not supported game

this is swf download http://woodstockgames.weebly.com/raze.html

### Expected behavior

http://www.andkon.com/arcade/adventureaction/raze/

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge

### Additional information

thank you

**Comment by danielhjacobs** [comment]
This content uses Actionscript 3 and is not yet supported by Ruffle. Se #1368, as well as the FAQ: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content.

**Comment by deividbinev12** [comment]
i already know

**Comment by theonlypwner** [comment]
I downloaded Raze from https://uploads.ungrounded.net/529000/529542_SideShooterSWF_.swf and tried it in https://ruffle.rs/demo/

The error is

```
ERROR core/src/display_object/movie_clip.rs:2669 Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: http://adobe.com/AS3/2006/builtin::push)
```
