### ISSUE TITLE
Everything loads in the same time + TypeError

### ISSUE THREAD

**Issue by Stefannag** [ruffle-rs/ruffle#606]
Hello,

I tried to install Ruffle to my site, but I've got the following error "TypeError: this.dynamic_styles.sheet is null", and the animations from the flash game will continually play - all the animations and stages will be loaded in the same time, so you can't play anything.

I uploaded the files to my server, and in the game, the page added the script tag.

Any ideas on how to solve it?

![image](https://user-images.githubusercontent.com/44028084/82302862-d5ecea00-99c2-11ea-8634-1c5c875ef379.png)

Thank you! :)

**Comment by Herschel** [comment]
Hi, do you have an example SWF that displays the problem? It sounds like that this is an ActionScript 3 file, which we don't support quite yet.

**Comment by Stefannag** [comment]
Hello,

I've made a test page for you: https://www.gameszap.com/Games/test/ruffle.html.

I hope this will help.

**Comment by Herschel** [comment]
Thank you for the report! I can confirm that these are AS3 files and won't work in Ruffle at present. It is on the roadmap, and we hope to support these in the somewhat-near future. Closing this in favor of #12.

The TypeError is indeed a separate issue and I've opened #607 for it. Thank you!
