### ISSUE TITLE
error report on https://www.guidemagazine.org/onlinegames/730-river-run-game-v20

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#6065]
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 966 failed.
(undefined: undefined)
Error stack:
```
ChunkLoadError: Loading chunk 966 failed.
(undefined: undefined)
    at Object.s.f.j (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:1695)
    at chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:327
    at Array.reduce (<anonymous>)
    at Function.s.e (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:305)
    at chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:4700
    at async N.ensureFreshInstance (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:17486)
    at async N.load (chrome-extension://copkmmjhaeoclglpnighiijjmnmdiaom/dist/ruffle.js?id=21511054341:1:19917)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://www.guidemagazine.org/onlinegames/730-river-run-game-v20

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14324.62.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.77 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-13
Channel: nightly
Built: 2022-01-13T00:18:17.083Z
Commit: 70bb5fa3f2544882e027fbdf55f455e63f609133
Is extension: true

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/149634172-6fe48085-e91e-40b5-b75f-084042b7e2e9.png)
Looks like it isn't Ruffle's fault.

**Comment by Poopooracoocoo** [comment]
My apologies. It works great in Basilisk

**Comment by Toad06** [comment]
Looks like the site is loading a .js file that overwrites a native JavaScript function/method, causing Ruffle to crash.

**Comment by n0samu** [comment]
Same issue as #2567 and #2463

**Comment by danielhjacobs** [comment]
The site owner removed this content from this site. I can't test whether #14215 would have fixed this. It would have if it this was using MooTools version 1.11. Unfortunately, now this can't work because the content was removed.
