### ISSUE TITLE
Text bullets should not appear on blank lines

### ISSUE THREAD

**Issue by midgleyc** [ruffle-rs/ruffle#6072]
### Describe the bug

Ruffle shows bullet points on blank lines.

![image](https://user-images.githubusercontent.com/25565697/149659050-f5900a64-69fa-425d-966c-f95b63c73fda.png)

### Expected behavior

Flash player does not 
![image](https://user-images.githubusercontent.com/25565697/149659078-61cde55f-b82e-42d5-8727-4960a828a789.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF file:
[bullets.zip](https://github.com/ruffle-rs/ruffle/files/7876889/bullets.zip)

**Comment by FernandoKGA** [comment]
This bug seems to have something related with layout rendering from HTML, so I'm checking inside `layout.rs` to functions that add a new bullet to the rendering or related.

**Comment by FernandoKGA** [comment]
With some digging, I've found possible problems that could be making it behave like this:

1. As there are two `TextSpan`, once it iterates to the second one which has the `bullet` property set to `true`, it will never disabled it, so once it hits [this line](https://github.com/ruffle-rs/ruffle/blob/4d8db1e64d36cc59c98c63b6883971cf01c5c9e3/core/src/html/layout.rs#L682), it will append a bullet every time when it checks in this [line](https://github.com/ruffle-rs/ruffle/blob/4d8db1e64d36cc59c98c63b6883971cf01c5c9e3/core/src/html/layout.rs#L282).
2. The [`explict_newline`](https://github.com/ruffle-rs/ruffle/blob/4d8db1e64d36cc59c98c63b6883971cf01c5c9e3/core/src/html/layout.rs#L325) function does not know how to check whether it should append an bullet or not if the text is empty, as it's reference isn't passed along.

Any other suggestions?
