### ISSUE TITLE
Game "Pipol Destinations" doesn't respond to mouse events

### ISSUE THREAD

**Issue by utensil** [ruffle-rs/ruffle#6089]
### Describe the bug

"Pipol Destinations" is a Flash game which is available [here](https://flasharch.com/en/archive/play/d70604574dbd71300b76bb3284419c51).

The game can be opened with ruffle correctly and its main menu can respond to mouse events (clicking), but after clicking "Start Game" and "Level 1" begins, it no longer responds to mouse events (clicking, dragging etc.) thus the game can't be played at all.

I've tried both online demo and the latest desktop app nightly build for Windows.

### Expected behavior

The game can be opened and played with ruffle correctly.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Google Chrome  97.0.4692.71

**Comment by Toad06** [comment]
Thanks for the report.

It looks like the issue is caused by `BitmapData.draw`, which is currently unimplemented (#290).

**Comment by Lord-McSweeney** [comment]
Even though `BitmapData.draw` is implemented, the level background is green and nothing is changed when the mouse is clicked.

**Comment by utensil** [comment]
Many thanks for your work, now I can confirm that the game can be played, at least to level 10.
