### ISSUE TITLE
Interactual Player

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6117]
### Describe the bug

When I start InterActual Player for Candleshoe dvd it says it needs to install Adobe Flash even though I already have the latest version of Ruffle installed. 

### Expected behavior

I expected it to not say it needed adobe flash and run the bonus content for my dvd.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by flashliberty5467** [comment]
your issue is not something ruffle is able to solve unfortunately 
your going to have to follow the instructions on this article from nosamu

https://nosamu.medium.com/how-to-reactivate-flash-based-games-and-screensavers-on-windows-10-or-8-1-f9b0218a332c

**Comment by mero09-99** [comment]
is this still open?

**Comment by CoolDino1** [comment]
Ok thanks. Closing now.
