### ISSUE TITLE
Minor rendering glitch on z0r.de/7751 (flashing eyes)

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#6129]
The eyes of the guy in the middle on https://z0r.de/7751 are flashing in Ruffle, but not in Flash Player.
In all of the desktop, WebGL, and canvas backends (if I did the check correctly...).

Here is just that sprite extracted, as a smaller SWF: [frames.zip](https://github.com/ruffle-rs/ruffle/files/7929455/frames.zip)
And one of the problematic (if I'm not mistaken) frames as SVG: [5](https://user-images.githubusercontent.com/288816/150880169-fcb76c08-f0af-4f1f-81d0-5d19844d0534.svg)

Interestingly, the `wgpu_svg` example in `lyon` renders the eyes in the SVG above correctly.
Maybe the SVG export by JPEXS ffdec altered the path slightly, inadvertently fixing the problem...

This is how the eyes look in Flash Player:
![image](https://user-images.githubusercontent.com/288816/150880393-dd5cc263-ddae-42b8-9eda-e2f21266ce50.png)

And one of the variations in Ruffle:
![image](https://user-images.githubusercontent.com/288816/150880507-3646f4ad-1669-4955-8633-b481c3c0ac7b.png)

**Comment by torokati44** [comment]
Hmm, the teeth of the guy in the right are also doing something funky... (even more so than intended)

**Comment by Herschel** [comment]
The eyes and face are oddly made up of many thick strokes, so I think this is a case of #3186, where we don't render strokes in correct order.
