### ISSUE TITLE
Checkers on itoadu.com

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6130]
### Describe the bug

When playing checkers on itoadu (itoadu.com/games and press checkers, you will have to create a free account) it does not move where clicked.

### Expected behavior

I expected it to move where clicked.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 96.0.2

**Comment by Toad06** [comment]
Thanks for the report.

The game appears to work as expected in the last release, this was likely fixed by #6123. There still remains a little issue where the cursor is displayed as a pointing hand in unexpected places.

**Comment by Toad06** [comment]
Fixed by #6217.
