### ISSUE TITLE
Ping-Pong on itoadu.com

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6131]
### Describe the bug

When playing ping-pong (itoadu.com/games and click ping-pong, you will have to create a free account) it keeps playing the ping pong music even after the game is closed.

### Expected behavior

I expected the same thing except for all sound effects to stop when the game was closed.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 96.0.2

**Comment by Toad06** [comment]
Thanks for the report.

When clicking to close the game, the `<object>` / `<ruffle-object>` tag in the DOM is not destroyed, but instead the parent's div has its `display` CSS property that changes to "none". Flash Player stops running the file when this occurs, but Ruffle keeps playing it.

Here's a sample that reproduces the issue: [sample.zip](https://github.com/ruffle-rs/ruffle/files/7978228/sample.zip)

**Comment by CoolDino1** [comment]
The problem is fixed now. I am now closing this issue.
