### ISSUE TITLE
Level pictures not displayed on New Super Mario Bros website

### ISSUE THREAD

**Issue by XXLuigiMario** [ruffle-rs/ruffle#6142]
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/7153662/151075244-76d09afb-27e3-43ce-bd1a-9923954870fb.png">

Despite being loaded, screenshots of levels in the Worlds section of the site are not displayed. I could not find any error messages in the console regarding this.

**Running on Flash:** https://youtu.be/EgyKDb_ZfeU
**Version tested:** nightly-2022-01-25 (809e91d)
**Game file:** https://nul.sh/misc/nsmb/

**Comment by Toad06** [comment]
Unfortunately support for loading/displaying external images is not implemented yet. #2056 is another related issue.

**Comment by Toad06** [comment]
Fixed by #6547.
