### ISSUE TITLE
Error on https://www.albinoblacksheep.com/games/nanaca

### ISSUE THREAD

**Issue by rholgate-turnto** [ruffle-rs/ruffle#6151]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gc-arena-0.2.0/src/gc_cell.rs:62:29

# Player Info
Allows script access: true
Player type: Object
SWF URL: /swf/games/nanaca(www.albinoblacksheep.com).swf
Param movie: /swf/games/nanaca(www.albinoblacksheep.com).swf
Param quality: high
Param menu: true
Param wmode: window
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: https://www.albinoblacksheep.com/games/nanaca
SWF URL: https://www.albinoblacksheep.com/swf/games/nanaca(www.albinoblacksheep.com).swf

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-26
Channel: nightly
Built: 2021-01-26T00:36:48.131Z
Commit: 7856cdd3d770e406ce546bf1745d8046d7b716f8

**Comment by shinstc** [comment]
Duplicate of #4442, crash fixed by #3322 (a very old version of Ruffle is still being used on this site).
