### ISSUE TITLE
Error on moz-extension://86898582-5d57-4542-8b50-29f81514cd70/player.html

### ISSUE THREAD

**Issue by lennard2021** [ruffle-rs/ruffle#6153]
# Error Info
Error name: Error
Error message: panicked at 'already borrowed: BorrowMutError', core/src/avm2/object/script_object.rs:69:16

# Player Info
Allows script access: false

# Page Info
Page URL: moz-extension://86898582-5d57-4542-8b50-29f81514cd70/player.html?url=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fitchio%2Fupload2%2Fgame%2F4107%2F480116%3FGoogleAccessId%3Duploader%40moonscript2.iam.gserviceaccount.com%26Expires%3D1643234217%26Signature%3DPfaPu%252F3VI05ccv%252Fxlqt6acr3qNb%252FKyoa6ABoJCiFGrqaZufyowr0opu8Mmikwnfljb%252BYfg4lJ%252B6ddUoPGIjlKRYRbbKYzLAJIJtqgYob04vZUg0c5PltFw%252FKhYvJcKTXXiY%252Fs39eJoeFbScQR2RpTksd9kQs%252FsJO431tsITna67M8OJCSi7r57sCdGg2rOZe825kD2hp%252BEZYHCWRFpZXJNBLRpNc%252BU3ee7oEdmd2cnkpcXVT%252Fb7gbYQRshpxw4bTUoEZLB4dNvTdAwc3CmjeSpW9ekXRUmK37YDQXL4ZiyYD30OOw6fLBy8YNzp%252FGMUObeU4asZF5o7T5zH9gMK2ig%3D%3D
SWF URL: https://commondatastorage.googleapis.com/itchio/upload2/game/4107/480116?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1643234217&Signature=PfaPu%2F3VI05ccv%2Fxlqt6acr3qNb%2FKyoa6ABoJCiFGrqaZufyowr0opu8Mmikwnfljb%2BYfg4lJ%2B6ddUoPGIjlKRYRbbKYzLAJIJtqgYob04vZUg0c5PltFw%2FKhYvJcKTXXiY%2Fs39eJoeFbScQR2RpTksd9kQs%2FsJO431tsITna67M8OJCSi7r57sCdGg2rOZe825kD2hp%2BEZYHCWRFpZXJNBLRpNc%2BU3ee7oEdmd2cnkpcXVT%2Fb7gbYQRshpxw4bTUoEZLB4dNvTdAwc3CmjeSpW9ekXRUmK37YDQXL4ZiyYD30OOw6fLBy8YNzp%2FGMUObeU4asZF5o7T5zH9gMK2ig==

# Browser Info
Useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-26
Channel: nightly
Built: 2022-01-26T00:18:09.413Z
Commit: d5986a72947f5552b29805e3971ce58939fdd1a2
Is extension: true

**Comment by Poopooracoocoo** [comment]
@lennard2021 Got another link to the SWF?
