### ISSUE TITLE
Stick Rpg 2 Support

### ISSUE THREAD

**Issue by maxswebservices** [ruffle-rs/ruffle#6160]
**Stick Rpg 2 Support**
Add stick rpg 2 to web-build.
It's quite popular and no one can play it in browser after flash was killed.

**Comment by Toad06** [comment]
http://www.xgenstudios.com/game.php?keyword=stick-rpg-2

Thanks for the report. This game uses ActionScript 3, and AS3 support is still in progress (see https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content). Merging this into #1368.
