### ISSUE TITLE
Circleci failing all builds

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#617]
It looks like circleci is setup to run `npm run bootsrap`(not `bootstrap`), and so fails all commits(technically only the commits the nightly build is run from, I think). This means that some commits will be marked as failing(the ones that are current when the nightly is built), and the build badge always reads "failing" because it's tracking circleci.

**Comment by Dinnerbone** [comment]
Oops!

**Comment by Herschel** [comment]
Broken again because of the web tests looking for Chrome

**Comment by Dinnerbone** [comment]
We should just disable tests on circleci, we have the full suite running everywhere else before they get to master, circleci is just publishing right now

**Comment by Justin-CB** [comment]
Builds are not failing anymore.
