### ISSUE TITLE
About Mutilate A Doll 2

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#6174]
This is not supported games with actionscript 3 under ruffle flash player

SWF downloads
https://archive.org/details/mutilate-a-doll-2_202011

**Comment by Toad06** [comment]
Thanks for the report. This game uses ActionScript 3, and AS3 support is still in progress (see https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content). Merging this into #1368.
