### ISSUE TITLE
Unexpected error upon skipping add

### ISSUE THREAD

**Issue by Github2503** [ruffle-rs/ruffle#6183]
### Describe the bug

# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at n (https://www.gameflare.com/emulators/ruffle/core.ruffle.14afbe2b2ea587f28d56.js:1:37003)
    at https://www.gameflare.com/emulators/ruffle/ruffle.js?release=2022-01-17:1:4900
    at async R.ensureFreshInstance (https://www.gameflare.com/emulators/ruffle/ruffle.js?release=2022-01-17:1:17616)
    at async R.load (https://www.gameflare.com/emulators/ruffle/ruffle.js?release=2022-01-17:1:20047)
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://www.gameflare.com/embed/strike-force-heroes-3/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 14324.72.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.91 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-17
Channel: nightly
Built: 2022-01-17T00:18:08.085Z
Commit: 059c1a34174a546521d1ebc32fd1411a079c2708
Is extension: false

### Expected behavior

The game should load after skipping the ad, however, it does not

### Affected platform

Desktop app

### Operating system

Chrome OS

**Comment by Poopooracoocoo** [comment]
It doesn't look like you were using the desktop app. I found the same error on the same website but that website self-hosts Ruffle. Failing to fetch the wasm file is not an issue with the desktop apps. This doesn't appear to be an issue on Ruffle's side.

I was able to load up Strike Force Heroes on another website that self-hosts Ruffle and saw the AS3 warning. I also loaded up the SWF which is sourced from NotDoppler and saw the the same AS3 warning and continuing just results in being stuck on the preloader.

I'll be closing this issue in favour of #1368. AS3 support is still in progress. View the FAQ in the wiki for more information.
