### ISSUE TITLE
[Bubble Bobble The Revival] Each time press the attack (Space Key), the stage always reset.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6185]
### Describe the bug

In **Bubble Bobble The Revival (By Free Online Games)**, after starting the game, if you press the attack key (space bar), the screen will scroll with the initializing of stage 1 at the same time as the attack.

Therefore, the game does not progress and stage 1 is reset.

[Bubble_Bobble_The_Revival.zip](https://github.com/ruffle-rs/ruffle/files/7978128/Bubble_Bobble_The_Revival.zip)

## ✔ Adobe Flash Player (Working)
https://user-images.githubusercontent.com/75052171/151962633-6bf81bb3-ee71-4a37-aefa-19192cafe626.mp4

## ⚠ Ruffle Nightly 2022-01-31 (Not Working)
https://user-images.githubusercontent.com/75052171/151962644-173da0e8-6090-4034-98f8-e9ade98301d4.mp4

![image](https://user-images.githubusercontent.com/75052171/151963449-0f59aaf6-b367-4d01-bfc6-73ab9b7b91c6.png)

### Expected behavior

The screen should not come out so the character can shoot the bubbles.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 97

**Comment by Toad06** [comment]
Thanks for the report.

Here is the code that is used when clicking "Play" or pressing the spacebar in the menu:
```
      this.start_anim_mc.onEnterFrame = function()
      {
         if(this._currentframe == this._totalframes)
         {
            delete this.onEnterFrame;
            this.start_btn.onRelease = function()
            {
               temp.initGame();
            };
            this.onKeyDown = function()
            {
               if(Key.isDown(32))
               {
                  temp.initGame();
               }
            };
            Key.addListener(this);
         }
      };
```

When the first level starts, `this.start_anim_mc.removeMovieClip();` is called and should remove all the properties from `start_anim_mc` (including the `onKeyDown` event) but because of #3839 this doesn't work. #5492 fixes that issue but we'll have to check again when this pull request is no longer a draft.
