### ISSUE TITLE
Trojan War - Bugged after first hit

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#6203]
### Describe the bug

Seems to be a problem with some Tower defense games as well as this one when hitting the first hit it gets in endless mode and doesn't harm anymore. Thought I've seen this behavior at least in Vector Tower Defense and somehwere else.

https://www.newgrounds.com/portal/view/604949?emulate=flash

### Expected behavior

Should hit and not endless loop stuck

### Affected platform

Self-hosted version

### Operating system

All

**Comment by Toad06** [comment]
Thanks for the report.

#5492 appears to fix this issue but we'll have to check again when the pull request is no longer a draft.
