### ISSUE TITLE
[Absolute Zero] Text and images are displayed without cropping.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6223]
### Describe the bug

There are various issues with 'Absolute Zero' where invisible text is visible in the original or incorrect text is rendered.
Verified in `Ruffle 2022-01-31` build.

I'm not sure if this is a **Bitmap** related issue (especially issue B) that hasn't been implemented yet.

[absolute_zero.zip](https://github.com/ruffle-rs/ruffle/files/8010224/absolute_zero.zip)

## Issue A

![az_1](https://user-images.githubusercontent.com/75052171/152681198-bbf69ff2-685d-4294-a370-4367095da092.png)

1. Hovering your mouse over the `New Mission`, `High Scores`, `Options`, and Ocean Breeze Games links(http://...) on the home screen should turn the mouse cursor into a clickable cursor, but retain the normal cursor shape.

2. A text resource that is not visible in the original is displayed, such as the part shown in the image.

## Issue B
![image](https://user-images.githubusercontent.com/75052171/152681397-02158162-1303-4fce-be74-61f92b7102cd.png)

When i start the game by clicking `New Mission`, all text displays are broken as shown in the image above.

The broken text on the right does not disappear even if you start the game by clicking on the `Training` section here.

The problem seems to be caused by the game clipping and using the same image file resource when displaying different text or images.

![image](https://user-images.githubusercontent.com/75052171/152681619-1203c808-eda9-4d6e-9a7e-121653b7c870.png)

In addition to the text, the same problem can be seen in the effect that occurs when directly hitting a meteorite.

![image](https://user-images.githubusercontent.com/75052171/152681781-0cd9a65f-0da4-4b32-ab59-e4c30086df47.png)

This animation uses the following resource files:

![image](https://user-images.githubusercontent.com/75052171/152681600-52755b7b-400b-41f8-bb29-88ee08a10868.png)

### Expected behavior

Appropriate text and images for the context should be displayed.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 97

**Comment by adrian17** [comment]
Hard to tell, unfortunately. The file was obfuscated to the degree that my JPEXS completely fails to decompile it, so I can't do any analysis on it.
For the record, these are console logs on main menu:
![image](https://user-images.githubusercontent.com/4729533/152683693-9d6b453e-e4b2-415e-b0c3-48b76b525302.png)

**Comment by Jmousy** [comment]
Thanks for the quick response!

It would be nice if a similar problem was found in other flash files in the distant future and this could be resolved as well.

**Comment by adrian17** [comment]
OK, I didn't fully figure it out, but here's what I found:
- there's probably a bug somewhere in register handling?
  - the script does `StoreRegister(StoreRegister { register: 4 })` to store the value to be later used as `BitmapData` size; but at that point, the local activation doesn't have registers, and global avm1 has only 4 (which makes Ruffle do nothing here) - which means that either the activation scope should have had local registers, or... since registers are 1-indexed, maybe global avm1 registers should also support idx==4?

- either way, fixing that most likely won't help much, as later on the script does use `BitmapData.draw` :(

**Comment by Jmousy** [comment]
Another game (Deep Sea Dive) from the same developer (Ocean Breeze Games) has a similar problem. I am attaching it for reference.

[Deep Sea Dive.zip](https://github.com/ruffle-rs/ruffle/files/9078725/Deep.Sea.Dive.zip)

![image](https://user-images.githubusercontent.com/75052171/178137364-83886d66-69fa-44a4-a96f-c54273a5496d.png)

**Comment by n0samu** [comment]
> Hovering your mouse over the New Mission, High Scores, Options, and Ocean Breeze Games links(http://...) on the home screen should turn the mouse cursor into a clickable cursor, but retain the normal cursor shape.
I've moved this to #8200.

The other issues have been fixed by #7770.
