### ISSUE TITLE
Nicholson NY's SnowCraft

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#6227]
### Describe the bug

Startup the swf file.
![image](https://user-images.githubusercontent.com/75534590/152789006-9e6d940a-eccf-4cdb-a0f4-288e501ec923.png)
![image](https://user-images.githubusercontent.com/75534590/152789128-ed8a6e65-0af3-4174-9b96-496b5cf6a4ad.png)
![image](https://user-images.githubusercontent.com/75534590/152789497-83086885-5073-49dc-9c22-ca2c71cd32c3.png)
[snowcraftrewrite10c.zip](https://github.com/ruffle-rs/ruffle/files/8015237/snowcraftrewrite10c.zip)

### Expected behavior

This issue also unable to play on every flash emulator.

### Affected platform

Everything.

### Operating system

Windows 10

### Browser

Google Chrome 98.0.4758.82

**Comment by relrelb** [comment]
This uses `LocalConnection.domain()` for sitelocking, which is currently unimplemented.

**Comment by p0008874** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/75534590/166137108-c0b85881-9272-4280-b9bb-96603bebfcae.png)
