### ISSUE TITLE
Error on https://omega.idv.tw/file/ttt.html

### ISSUE THREAD

**Issue by iamdco** [ruffle-rs/ruffle#6250]
### Describe the bug

i use sugarhosts web hosting
download Website Self Hosted https://github.com/ruffle-rs/ruffle/releases/download/nightly-2022-02-11/ruffle-nightly-2022_02_11-web-selfhosted.zip
SugarHosts cPanel -> ADVANCED -> MIME Types -> add
=MIME Type=
application/wasm
=Extension(s)=
wasm

https://omega.idv.tw/file/ttt.html

https://omega.idv.tw/file/MUZIMAP.swf

container.appendChild(player);

Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at ttt.html:13:19

### Expected behavior

play the swf

### Affected platform

Self-hosted version

### Operating system

Windows 10 ,macOS 10.14

### Browser

Google Chrome 96

### Additional information

container.appendChild(player);

Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at ttt.html:13:19

![image](https://user-images.githubusercontent.com/19567233/153538081-e5369bdb-2779-4f65-bb9c-9ff148cb0d86.png)

**Comment by Toad06** [comment]
This is not a bug with Ruffle, and actually not a bug at all. When using `document.getElementById("container");`, JavaScript tries to find an element with the id "container" in the DOM. As no element has a such id here, `null` is returned and causes an error when calling `appendChild`.

After `<body>` and before `<script>`, add:
`<div id="container"></div>`

This will solve your problem.
