### ISSUE TITLE
Uphill Rush 1 - Missing Tiles after a few seconds of racing

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#6251]
### Describe the bug

Hey, the tiles are missing after you ride a few seconds you drive on unvisible terrain. Only minimap can help.

https://www.newgrounds.com/portal/view/423798?emulate=flash

### Expected behavior

Show the terrain.

### Affected platform

Self-hosted version

### Operating system

All

**Comment by n0samu** [comment]
Fixed by #9447
