### ISSUE TITLE
Electricman 2 HS - used to work, not longer can click into game levels

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#6261]
### Describe the bug

Game starts normally, but when you go to click into any level to play, nothing happens. Used to work ok with previous versions of RUFFLE and could play different levels in the game - not sure exactly when this issue appeared. 

Playing the game on the freeworldgroup.com site

http://www.freeworldgroup.com/games6/gameindex/electricman-2-hs.htm

![Image1](https://user-images.githubusercontent.com/76993246/153732862-eba5dec8-6df1-45e0-a408-51e573b65532.jpg)

### Expected behavior

Clicking into the level icon should start that level normally

### Affected platform

Self hosted version of RUFFLE

### Operating system

WIndows 11

### Browser

Google Chrome current version

**Comment by torokati44** [comment]
Interestingly, the levels can be started by clicking rapidly on the level image several times.
On somewhere between the second and fifth click, the levels usually start.

**Comment by Toad06** [comment]
Yes, this looks similar to #1108 (though in this case this would mean the game has never worked properly).

**Comment by freeworldgroup** [comment]
I was not able to get it to start with rapid clicking...

**Comment by n0samu** [comment]
Fixed by #10862
