### ISSUE TITLE
Ruffle scanner compilation fails

### ISSUE THREAD

**Issue by tsunamistate** [ruffle-rs/ruffle#6266]
### Describe the bug

When you try to compile `ruffle_scanner`, compilation fails with a lot of errors from `scanner\src\cli_options.rs`

It seems that after upgrading `clap` crate, the scanner code wasn't updated for it.

Steps to reproduce:

1. Open Command Prompt or PowerShell window and navigate to ruffle folder
2. Execute the cargo command to compile ruffle scanner:
```bash
cargo run --release --package=ruffle_scanner -- scan {path to folder with SWF} {path to csv file to be generated}
```

Actual result:

Compilation fails with errors like `cannot find derive macro ``Parser`` in this scope`
Logs: [logcompile.txt](https://github.com/ruffle-rs/ruffle/files/8055519/logcompile.txt)

### Expected behavior

Ruffle scanner compilation succeeds. Scanner does a scan of SWF files in folder provided from CLI options, and generates a CSV report in location provided.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by adrian17** [comment]
Yeah, we didn't consider adding scanner to CI pipeline, so we didn't build the scanner in some time. Thanks for noticing.
