### ISSUE TITLE
Simulate user interaction in tests

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#629]
It'd be very useful to test mouse/keyboard interaction in tests. For example, the logic for buttons is quite complicated and changes based on several properties. A simple test could move the mouse over a button, simulate a click, and verify that it switches to the proper state, fires the correct event, and so forth.

Maybe this could start with utility functions in `regression_tests.rs` that take a map of frames to `PlayerEvent`s and tosses those to the test player while running.

**Comment by Lord-McSweeney** [comment]
Ruffle now supports the following automated events in tests:
```
MouseDown
MouseUp
MouseMove
KeyDown
```

**Comment by Lord-McSweeney** [comment]
Ruffle now supports two additional input events:
```
TextInput
TextControl
```

**Comment by Dinnerbone** [comment]
This exists now
