### ISSUE TITLE
Error on http://www.positionchrome.com/flash_index.html

### ISSUE THREAD

**Issue by lempamo** [ruffle-rs/ruffle#6312]
Occurred when navigating to the "links" section.

# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/html/text_format.rs:756:54

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.positionchrome.com/flash_index.html
SWF URL: http://www.positionchrome.com/Position_Chrome.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-01
Channel: nightly
Built: 2022-01-01T00:13:36.533Z
Commit: e477fca9e40295ff550d7709d17afa769d4c461e
Is extension: true

**Comment by relrelb** [comment]
This was fixed by #6084. Please use the latest Ruffle build.
