### ISSUE TITLE
"Extreme Pamplona" doesn't render the background, and crashes after losing.

### ISSUE THREAD

**Issue by florin-cg** [ruffle-rs/ruffle#6336]
### Describe the bug

When you start playing, the background (stadium) is briefly rendered for a couple of seconds and then completely disappears. 
![image](https://user-images.githubusercontent.com/100195672/155100977-d8ea7741-701f-49a2-8dc4-1ed31243452a.png)

When you lose, the game just displays a black screen, and doesn't load anymore.

You can play the game here [https://www.crazygames.com/game/extreme-pamplona](https://www.crazygames.com/game/extreme-pamplona)

Ruffle was build from tag nightly-2022-02-19 and was initialized with "trace" log level, and the self hosted version was built with the debug flag. The log contains the data since the load of the game, until the black screen crash.
[extreme-pamplona-log.log](https://github.com/ruffle-rs/ruffle/files/8115281/extreme-pamplona-log.log)

Here are the game files:
[extreme-pamplona.zip](https://github.com/ruffle-rs/ruffle/files/8115528/extreme-pamplona.zip)

### Expected behavior

- The background should be rendered.
- The game should load again after losing.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome Version 98.0.4758.102 64-bit

**Comment by Toad06** [comment]
Thanks for the report.

The issue with the background is related to `BitmapData.draw` which is currently unimplemented (#290).

I suspect that the issue with the black screen crash (though there is no error in the console) could be related to #3839, but this would need further investigation.
