### ISSUE TITLE
[Ben 10 - Power Splash] The background music is distorted and output at a loud volume.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6403]
### Describe the bug

In **'Ben 10: Power Splash'**, the background music is distorted and loud when the game starts.

Depending on the specific Nightly build of Ruffle, the playback state was different. (Not the exact date.)

Ruffle Nightly 2021-01-01: No sound distortion, but stuttering during playback
Ruffle Nightly 2021-03~: Sound is overly distorted and loud
**(I Checked 2022-02-19 Nightly)**

[Ben10-Power-Splash.zip](https://github.com/ruffle-rs/ruffle/files/8190218/Ben10-Power-Splash.zip)

### 🔊 Adobe Flash Player

https://user-images.githubusercontent.com/75052171/156873060-8189a236-b973-48ec-a449-1bee7b144967.mp4

### 🔊 Ruffle (‼‼Beware of very loud sounds.‼‼)

https://user-images.githubusercontent.com/75052171/156873062-fa588340-9458-4658-a98c-551e493d65d1.mp4

### Expected behavior

Background music should be output normally.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 99

**Comment by relrelb** [comment]
Thanks for the report! This was already fixed by #6352.

**Comment by Jmousy** [comment]
@relrelb Oh, I had to check after upgrading the Nightly build to a bit more up-to-date, but I overlooked that.

Thank you for telling me!
