### ISSUE TITLE
Implement a settings page

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#641]
<a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page">From MDN</a>

<a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages">Settings Widgets</a>

**Comment by kmeisthax** [comment]
I have a branch on my repository called `extension-popup` which provides a popup UI for configuring the plugin on a particular page. It probably needs to be rebased and updated to work with some of the changes we've made to the extension recently but it has a fully styled UI.

**Comment by Justin-CB** [comment]
@kmeisthax Would you mind if I did some continuing work on making an extensions settings page based on your code?

**Comment by Justin-CB** [comment]
The initial work has just been merged.
