### ISSUE TITLE
[AVM2] Error on: https://crazyisland.pl/play/

### ISSUE THREAD

**Issue by Lujek69** [ruffle-rs/ruffle#6414]
### Error info
Error 1: `AVM2 error: Property does not exist: Multiname { ns: [Package("flash.utils")], name: Some("Timer"), params: [] }`
Error 2: `Error occured when running AVM2 frame script: Property does not exist: Multiname { ns: [Package("flash.utils")], name: Some("Timer"), params: [] }`

### Page info
URL: https://crazyisland.pl/play/?dupa
SWF URL: https://crazyisland.pl/play/res/tinyisland321.swf

### Browser info
`Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0`

### Ruffle info
`Version: 0.1.0.402`

**Comment by Lord-McSweeney** [comment]
I could not find an archived copy of the site or SWF. Timer has been implemented and AS3 support is at a reasonable level now, so closing this as "probably fixed".
