### ISSUE TITLE
Regression introduced in nightly-2022-01-08

### ISSUE THREAD

**Issue by northamerican** [ruffle-rs/ruffle#6436]
There is a regression introduced in the nightly-2022-01-08 build that makes this swf with many sounds and fade effects slow to a crawl in Safari. 

To reproduce:
Load the SWF and click "no" here and you will immediately notice the lag. The sound plays repeatedly as well, which is not the intended behavior.
<img width="152" alt="Screen Shot 2022-03-10 at 10 21 46 PM" src="https://user-images.githubusercontent.com/6657634/157795977-d4742faa-6499-4f91-8072-677ca01bc115.png">

SWF file:
[the-wall-radio.swf.zip](https://github.com/ruffle-rs/ruffle/files/8228727/the-wall-radio.swf.zip)

Tested on Safari 15 and on mobile safari. The issue is not reproducible on the previous build (like nightly-2022-01-04) or on any other browser (firefox, chrome).

### Expected behavior

The performance should match that of other browsers and of that in the nightly-2022-01-04 build.

### Affected platform

Self-hosted version

### Operating system

macOS / iOS

### Browser

Safari 15.1

**Comment by n0samu** [comment]
Sounds like the same issue as #6326

**Comment by northamerican** [comment]
@n0samu yup, that's it. closing this issue

**Comment by Toad06** [comment]
FYI, this should be fixed by #6493.
