### ISSUE TITLE
Inverted blending dosent work

### ISSUE THREAD

**Issue by hacker64-pixel** [ruffle-rs/ruffle#6442]
In Flash, you got a blending mode called inverted which inverts colors and in ruffle it doesn't work.
![image](https://user-images.githubusercontent.com/59923822/157888656-a7950859-bb57-42be-93b8-4d4f7ba7ae10.png)

Ruffle just show the normal version of an object like they didn't see that blending mode is changed.

**Comment by Lord-McSweeney** [comment]
Blend modes (including invert) have been implemented by #8262.
