### ISSUE TITLE
Sticksfight.com didn't work as expected

### ISSUE THREAD

**Issue by Silverteal** [ruffle-rs/ruffle#6445]
### Describe the bug

http://sticksfight.com/sticksfight.swf

### Expected behavior

the ads above should be random instead of switching fast

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 98

**Comment by n0samu** [comment]
This game uses ActionScript 3 and is not yet supported by Ruffle.

**Comment by Lord-McSweeney** [comment]
No longer occurring.
