### ISSUE TITLE
Error on https://igrezadecu.com/garfield/igrice/garfield-igrice.html

### ISSUE THREAD

**Issue by kaiklaus87** [ruffle-rs/ruffle#6447]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://igrezadecu.com/ruffle/ruffle.js:1:68311
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (https://igrezadecu.com/ruffle/ruffle.js:1:67964)
    at https://igrezadecu.com/ruffle/ruffle.js:1:35878
    at Array.reduce (<anonymous>)
    at Function.yi.e (https://igrezadecu.com/ruffle/ruffle.js:1:35855)
    at o (https://igrezadecu.com/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://igrezadecu.com/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://igrezadecu.com/garfield/igrice/garfield-igrice.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by danielhjacobs** [comment]
Disable Microsoft Edge's "Enhance your security on the web" setting, or add an exception for any site using Ruffle, such as this site. See https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-i-always-get-a-something-went-wrong-error.
