### ISSUE TITLE
npm run bootstrap no longer installing lerna

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#649]

**Comment by Justin-CB** [comment]
It isn't installing webpack either.

**Comment by Dinnerbone** [comment]
Github actions & circleCI start with a clean slate and appear to get lerna installed when they run `npm run bootstrap`.

Is this happening on your machine? What's the log output from `npm run bootstrap`?

**Comment by Justin-CB** [comment]
Huh. I removed my ruffle directory & re-cloned it & it stopped working, but when I re-cloned it again, it started working again.
