### ISSUE TITLE
Bug in "Intrusion" projectile impact bug

### ISSUE THREAD

**Issue by LoaderY7** [ruffle-rs/ruffle#6495]
### Describe the bug

i've found a minor bug on ruffle, in a game named "Intrusion" the impact that projectiles have (instead of having a impact effect) it shows a black square, i already tested in newgrounds player and it works perfectly, to reply this error, you have to shoot (with space key or right click).

### Expected behavior

The projectile should show an impact effect without a black cube, like the shown in the images
![error image](https://user-images.githubusercontent.com/86942049/159144521-22753401-302b-4164-93fa-df42eef392a7.png)
![newgrounds player image](https://user-images.githubusercontent.com/86942049/159144590-6ce0e200-d7d8-425c-949c-08a87df4fc38.png)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 99.0.1150.46

**Comment by relrelb** [comment]
This is using the `Add` blend mode, which is currently unimplemented (#58).

**Comment by Lord-McSweeney** [comment]
Fixed by #8262.
