### ISSUE TITLE
Text Glow doesn't work

### ISSUE THREAD

**Issue by KabanFriends** [ruffle-rs/ruffle#6507]
### Describe the bug

The text in this screenshot should have a black glow, but it's not displayed, making the text very hard to read:
![issue1](https://cdn.discordapp.com/attachments/917345899389255691/955856435869270077/issue1.png)

SWF used: https://github.com/KabanFriends/mildescape-archive/raw/master/escape62.swf
Make sure to set the language to English if you want to reproduce the issue

### Expected behavior

It should look like this:
![issue1](https://cdn.discordapp.com/attachments/917345899389255691/955856436183855144/issue2.png)

Ignore the font being different, I know it's an unavoidable issue due to ruffle using Noto Sans instead of MS Gothic, and I changed it to the correct font on my personal fork of Ruffle

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Microsoft Edge

**Comment by torokati44** [comment]
This is due to the fact that filter effects are not implemented yet in Ruffle at all.
The main tracking issue: https://github.com/ruffle-rs/ruffle/issues/15

**Comment by KabanFriends** [comment]
Thank you for the information.
I hope they will be implemented ....someday

**Comment by waspennator** [comment]
Should be resolved by #11878

**Comment by Lord-McSweeney** [comment]
Fixed.

**Comment by Lord-McSweeney** [comment]
(Note that you _must_ set the language to English to get the glyphs to display correctly)
