### ISSUE TITLE
Ruffle Error on https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

### ISSUE THREAD

**Issue by 32160924958** [ruffle-rs/ruffle#6515]
# Error Info
Error name: TypeError
Error message: Could not download wasm module
Error stack:
```
TypeError: Could not download wasm module
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentaijoy.com/meet-and-fuck-hentai-games/xxx-teen-action/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-01
Channel: nightly
Built: 2021-01-01T00:47:35.621Z
Commit: 8cdf04384c79c60e066c945566128b7e7ee2620b

**Comment by adrian17** [comment]
They're using a >3 year old version of Ruffle, and looks like there's something badly configured on their page. I don't think we can do anything here.
