### ISSUE TITLE
Anime Fighting Jam Wing 1.2 very buggy 

### ISSUE THREAD

**Issue by ToniSSB** [ruffle-rs/ruffle#6522]
### Describe the bug

Booting the game and its menus all work great but the gameplay is where the issues starts. All of the backgrounds to any given stage don't load correctly and are completely dark, and moves don't work as intended in-game. 

### Expected behavior

I expect the emulated file to have every move work correctly as intended, where it feels some moves are missing hitboxes. It should also render the background images.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I've inspected to the code to this particular game a lot and know the file structure, so if I can help the compatibility in any way please contact me.

**Comment by n0samu** [comment]
Assuming this is the correct file: [](http://media.gamesogood.com/flash/action-games/AnimeFightingJamWing/AnimeFightingJamWing2.swf)http://media.gamesogood.com/flash/action-games/AnimeFightingJamWing/AnimeFightingJamWing2.swf

This game appears to use BitmapData.draw() to display the backgrounds, and this feature is not yet implemented in Ruffle, see #290. That explains why the backgrounds don't show up.
I'm not sure why the move hitboxes are wrong, though.

**Comment by n0samu** [comment]
These problems seem to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
