### ISSUE TITLE
[AVM1] Garfield's Scary Scavenger Hunt: Visual error after loading an swf twice on the same stage

### ISSUE THREAD

**Issue by koonggames** [ruffle-rs/ruffle#6526]
### Describe the bug

After opening the books minigame more than once, all the books appear to be the same "Beefs up" book, which is revealed to be hiding the real configuration of the books after pressing any of them. Additionally, sometimes after pressing one of the books and reopening the minigame, a seemingly random number of the books furthest to the right retain their expected animation frame.
Notes:
- the books minigame is a separate .swf file loaded via loadMovieNum(), it works perfectly fine when opened directly.
- each of the books is a movieclip with 9 animation frames (for all possible book types + 1 blank), their initial positions are always the same but the frames change

![image](https://user-images.githubusercontent.com/70941273/160198805-1abe44cf-aadb-437b-aba8-886723539c5b.png)
1 book with the expected animation frame
![image](https://user-images.githubusercontent.com/70941273/160199383-1df3f0f8-05af-4dbb-bc00-43b0529389f1.png)
2 books with the expected animation frame
![image](https://user-images.githubusercontent.com/70941273/160199535-d6f429f5-0240-4594-b4df-a7c4b7c27657.png)

### Expected behavior

There should only be 1 book of each type (visually) every time the minigame is opened.
![image](https://user-images.githubusercontent.com/70941273/160198749-e1b8bc03-c2c8-45a8-9338-75d45c36411d.png)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Can you provide a link to the game?

**Comment by koonggames** [comment]
Sure: https://www.speedrun.com/gssh1/resources ("GSSH - full" is unmodified)
