### ISSUE TITLE
Error on https://e621.net/posts/348065?q=hatsune_miku+order%3Ascore

### ISSUE THREAD

**Issue by SkittyBitty** [ruffle-rs/ruffle#6543]
# Error Info
Error name: CompileError
Error message: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
Error stack:
```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at <anonymous>:3:32083
    at r (<anonymous>:3:32573)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://e621.net/posts/348065?q=hatsune_miku+order%3Ascore

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-24
Channel: nightly
Built: 2021-01-24T01:05:42.228Z
Commit: 86b4c20809d8778d498474a26601aeda4cec87c4

**Comment by Toad06** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/issues/2201 as this is the same issue. Thanks for reporting.
