### ISSUE TITLE
Error on https://mysexgamer.com/game/peni-parker-tentacled

### ISSUE THREAD

**Issue by tedman135790** [ruffle-rs/ruffle#6550]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/9/8/b98ba49debeebb388c9bb542daf0bcef/b98ba49debeebb388c9bb542daf0bcef.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/b/9/8/b98ba49debeebb388c9bb542daf0bcef/b98ba49debeebb388c9bb542daf0bcef.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://mysexgamer.com/game/peni-parker-tentacled

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by n0samu** [comment]
Looks like a network error unrelated to Ruffle
