### ISSUE TITLE
avm1: `getBytesTotal` and `getBytesLoaded` incorrectly return 0 for images

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#6552]
Some files are using `getBytesTotal` and `getBytesLoaded` to detect if an image is loaded and then continue the execution. As both of these methods return 0 for images, the affected files softlock.

---

[Sample](https://github.com/ruffle-rs/ruffle/files/8362420/sample.zip)

```
// Frame 1:
_root.createEmptyMovieClip("water",2);
_root.water.loadMovie("water.jpg");

// Release button:
trace("getBytesTotal(): " + _root.water.getBytesTotal());
trace("getBytesLoaded(): " + _root.water.getBytesLoaded());
var loaded = _root.water.getBytesLoaded() / _root.water.getBytesTotal();
if(loaded >= 1 && _root.water.getBytesLoaded() > 0) {
   trace("LOADED!");
}
```

Flash Player traces:

> getBytesTotal(): 29665
> getBytesLoaded(): 29665
> LOADED!

Ruffle traces:

> getBytesTotal(): 0
> getBytesLoaded(): 0

**Comment by otherthings** [comment]
Tagging this issue as probably related: https://github.com/ruffle-rs/ruffle/issues/6616
