### ISSUE TITLE
External .PNGs with transparency having artifacting issues

### ISSUE THREAD

**Issue by nullcasting** [ruffle-rs/ruffle#6559]
### Describe the bug

Hello! Firstly, thanks for adding external file loading.🤩!!! Onto the bug:
 
On my site, about 75% of the transparent pngs are loading with intense artifacting. This artifacting is not consistent between image sizes nor transparency values. Image of the artifacting below. On the right is the image with alpha checker to demonstrate its transparency. 
![image](https://user-images.githubusercontent.com/36830453/160514058-4364e1c4-ca37-4485-839b-0777eb66a072.png)
Attempts to re-export the pngs does not change the artifacting. 
These issues do not appear when using the Adobe Flash projector tool. You can test this by locally opening GalleryTest1.swf in the zip file below. 
https://drive.google.com/file/d/1YJ4CbNh_nbulDUlxZVlhjcnt2EMvXhIw/view?usp=sharing

the SWF is hosted on my website @ https://warpzone.site/aboutwarp.htm
### Expected behavior

Character main display images should be transparent with no artifacting. 
![image](https://user-images.githubusercontent.com/36830453/160514533-bea1630e-ae16-493b-9b38-fb5209fcf1e3.png)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox (tested on chrome and edge as well).

**Comment by torokati44** [comment]
This may not be specific to external images, I have seen a similar thing in two places in the past.

There's an outline visible in https://z0r.de/7954 in the bottom right corner with Ruffle, not with Flash Player.

Same thing with the outline of the dad in https://archive.org/details/heyhey16k the first time only the eldest son is visible.

I guess it has something to do with alpha [un]premultiplication not being accurate.

**Comment by Herschel** [comment]
We need to convert the PNG to premultiplied alpha before registering it with the renderer (bitmaps embedded in the SWF are already premultiplied).
