### ISSUE TITLE
Failing polyfill tests: Ruffle isn't loaded after 5 seconds

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#657]
Examples:
https://github.com/ruffle-rs/ruffle/runs/717031241?check_suite_focus=true
https://github.com/ruffle-rs/ruffle/runs/717031739?check_suite_focus=true
https://github.com/ruffle-rs/ruffle/runs/717449637?check_suite_focus=true

Either the tests are bad, or Ruffle isn't loaded (`window.RufflePlayer.invoked === true`) after 5 seconds of being added to the page.

**Comment by Herschel** [comment]
Thanks for the effort in looking into it.
