### ISSUE TITLE
Ruffle won't load any Flash content after moving dates on Wayback Machine

### ISSUE THREAD

**Issue by gradygambrell** [ruffle-rs/ruffle#6574]
### Describe the bug

For example: I go to nick.com that haves a website with flash content (that is an example.) I choose to go to 2005, then later, hope over to 2009. After hoping over to 2009, an error appears on the flash content saying that flash isn't supported (Ruffle ain't working)

### Expected behavior

A grey box saying that flash isn't working.

### Affected platform

Browser's extension

### Operating system

macOS 12.3

### Browser

Brave 1.36.122

### Additional information

I don't know about the ActionScript 1/2/3 on any Wayback machine or nick.com that haves Flash

**Comment by n0samu** [comment]
See https://github.com/ruffle-rs/ruffle/issues/6412#issuecomment-1062275574

**Comment by n0samu** [comment]
Thanks to @p0008874 we finally have a solution for this issue! See the FAQ: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#wayback
