### ISSUE TITLE
npm run build not creating extension/build/dist anymore

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#659]

**Comment by Dinnerbone** [comment]
It doesn't need to. The extension is available in `extension/dist`, like all of the other packages

**Comment by Justin-CB** [comment]
But that's only the firefox extension. I'm using it on Brave, a Chromium/Chrome-based browser.

**Comment by Dinnerbone** [comment]
Does it not make a 'generic' extension there too?

**Comment by Justin-CB** [comment]
No, it doesn't, it only makes the firefox extension, & changing the filename extension to `crx` doesn't work either.

**Comment by Dinnerbone** [comment]
Aha, I see the issue. Will submit a fix asap.

**Comment by Dinnerbone** [comment]
#660 should fix it. As a workaround you can go to `web/packages/extension` and `node run tools/build_generic.js`
