### ISSUE TITLE
The Kitten Game (web ver.) - "light" effect appears as opaque circle.

### ISSUE THREAD

**Issue by gskt17** [ruffle-rs/ruffle#6596]
### Describe the bug

Starting from the fifth level of Matt Roszac's _The Kitten Game_, there is a mechanic where the levels are dark and a large, opaque circle follows the mouse. This circle is supposed to be transparent.

http://kupogames.com/wp-content/uploads/2013/07/KittenGame.swf

### Expected behavior

The circle should be transparent, making the dark graphics behind it lighter.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 98.0.2 (64-bit)

### Additional information

Extension build is Nightly 2022-04-01.

**Comment by torokati44** [comment]
This is due to missing Blend Modes.
See tracking issue: https://github.com/ruffle-rs/ruffle/issues/58

**Comment by gskt17** [comment]
Gotcha.

**Comment by n0samu** [comment]
Works great with #8262 
![image](https://user-images.githubusercontent.com/71368227/209109957-74881ae0-0f18-43c9-9270-a55c3cede6eb.png)

**Comment by Lord-McSweeney** [comment]
#8262 and #9134 have been merged, this issue is fixed
