### ISSUE TITLE
Display object instances should be assigned instance names if none are provided

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#66]
If an instance name is not provided to a MovieClip, Button, or other interactive object, the Flash Player automatically assigns one of the form "`instanceN`", where N is an increasing index starting at 1. The index is global across the entire SWF file. This is done at the runtime level and not stored in the SWF PlaceObject.

**Comment by Dinnerbone** [comment]
I've created a test for this over here: https://github.com/Dinnerbone/ruffle/commit/6582e64331a1b4830591a7f16935588d21746a18

It appears that Flash will increment the "latest ID" for every object made, even if it gets a custom name immediately after. We should probably have a counter of every new display object ever made, and default the names to that counter at time of creation.

**Comment by Herschel** [comment]
Another thing to note is that in AS3, every display object including shapes are proper objects, so shapes cause the instance ID to increment in AS3, but not in AS2.
