### ISSUE TITLE
Flashvortex Wave Text

### ISSUE THREAD

**Issue by blenderbach** [ruffle-rs/ruffle#6610]
### Describe the bug

Ruffle doesn't run this text properly. No waves, nothing. Just a plain flat text. Here's a screenshot as a comparison between Adobe Flashplayer and Ruffle's output. I have also attached the SWF file for testing. Good Luck! 
![image](https://user-images.githubusercontent.com/87039308/161448213-95399076-807b-45a4-a61e-5739ca988b8b.png)
[249_1.zip](https://github.com/ruffle-rs/ruffle/files/8405502/249_1.zip)

### Expected behavior

The output should display the text with a bevel and animated waves. Here's an example with a different font and text.
![ezgif com-gif-maker_39](https://user-images.githubusercontent.com/87039308/161448535-12686e70-2b51-40bf-86b3-5df34d3bc85f.gif)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Additional information

When I use the browser's console, it states that there are no errors...
![image](https://user-images.githubusercontent.com/87039308/161448627-c0f463b9-64b7-4a55-9de4-a45793c8e2d0.png)

**Comment by Herschel** [comment]
Masking is a little broken with textfields currently, because the mask rect used for the textfield bounds interferes.

**Comment by blenderbach** [comment]
An old version of Ruffle ("ruffle_nightly_2020_09_10_windows") does a better job, even though it's still not right.
![image](https://user-images.githubusercontent.com/87039308/161449819-23491dd6-7d13-48a9-8e8a-72b65c4cbb14.png)

**Comment by n0samu** [comment]
This is mostly fixed - now it just needs BevelFilter.

**Comment by waspennator** [comment]
Bevel filter should be implemented by #12018

**Comment by n0samu** [comment]
Seems like even with #12018, the DropShadow and Bevel filters aren't being properly applied:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/a5a44770-bf81-4059-b6c3-5d71e8806fd7)

**Comment by n0samu** [comment]
Seems to be fixed now!
