### ISSUE TITLE
Flashvortex Scrolling LEDs Text

### ISSUE THREAD

**Issue by blenderbach** [ruffle-rs/ruffle#6615]
### Describe the bug

Ruffle doesn't run this text properly. No glow or color. Nothing. Just plain scrolling white text. Here's a screenshot as a comparison between Adobe Flashplayer and Ruffle's output. I have also attached the SWF file for testing. Good Luck!
![image](https://user-images.githubusercontent.com/87039308/161463690-1ba92080-b2fd-4d83-906b-72c092be45e1.png)
[305_1.zip](https://github.com/ruffle-rs/ruffle/files/8406267/305_1.zip)

### Expected behavior

The output should have the text glow with a blue color. Here's an example with different text.
![ezgif com-gif-maker (42)](https://user-images.githubusercontent.com/87039308/161464040-c907de83-9bce-4704-a74b-46628df0c584.gif)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Additional information

When I use the browser's console, it states that there are no errors...

![image](https://user-images.githubusercontent.com/87039308/161464093-941aeb30-644d-4e29-930c-9dc30082cb79.png)

**Comment by n0samu** [comment]
Glow and other filters are not yet implemented, see #15

**Comment by waspennator** [comment]
This issue seems to have regressed as of 2023-07-06.

![Screenshot 2023-07-08 214255](https://github.com/ruffle-rs/ruffle/assets/78768499/b1129bd3-ca6c-4dae-a650-3df7b942de77)

**Comment by n0samu** [comment]
As noted on Discord, the regression is related to bitmap cache invalidation.

**Comment by n0samu** [comment]
Seems like this was fixed a long time ago.
