### ISSUE TITLE
Image loading progress animation fails on Graffiti Archaeology.

### ISSUE THREAD

**Issue by otherthings** [ruffle-rs/ruffle#6616]
### Describe the bug

Hi all!  I'm trying to revive an old Flash project called Graffiti Archaeology (http://grafarc.org/flash/view.htm). We developed this in 2002, so I believe it's ActionScript 1.  The app shows a series of layers of high-res photos, clipped by vector outline shapes, in a time-lapse photomontage, with various UI controls to allow you to move around in space and time.

The bug: In the original Flash, there was animation that would show the progress as each layer was being downloaded, and the image and its corresponding UI elements would appear once loading was complete. In Ruffle, that doesn't happen.

In the ActionScript, we use `img.getBytesLoaded()` and `img.GetBytesTotal()` to calculate how much of each image has been loaded, and the images themselves are only revealed once BytesLoaded == BytesTotal.  I'm told those methods are not yet implemented in Ruffle, so I'm guessing that explains this bug.

### Expected behavior

Here's a video showing how the UI behaved in Flash: https://vimeo.com/695549918/744a0c6baa

Specifically:
(1) The little rhombuses in the timeline at bottom are buttons you can click on. (In Ruffle, they don't show up.) 
(2) The layers of photos all appear with a top-to-bottom grey fill effect, which behaves like a visual progress bar as the data gets downloaded. Once downloaded, the image appears. (In Ruffle, none of that happens.)

### Affected platform

Browser's extension

### Operating system

Mac OS 10.14.6 Mojave 

### Browser

Google Chrome 97

### Additional information

See also this related issue: https://github.com/ruffle-rs/ruffle/issues/6552

**Comment by ROBERT-MCDOWELL** [comment]
I confirm that getBytesTotal and getBytesLoaded are always 0
