### ISSUE TITLE
Error on https://www.koreus.com/jeu/oeufs-paques.html

### ISSUE THREAD

**Issue by melo-i-m** [ruffle-rs/ruffle#6642]
# Error Info
Error name: TypeError
Error message: Load failed

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.koreus.com/jeu/oeufs-paques.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-21
Channel: nightly
Built: 2022-01-21T00:17:44.053Z
Commit: 4d8db1e64d36cc59c98c63b6883971cf01c5c9e3
Is extension: false

**Comment by n0samu** [comment]
This website does not have CORS properly set up for WASM files, which prevents Ruffle from working
