### ISSUE TITLE
Error on https://mysexgamer.com/game/milk-plant-6

### ISSUE THREAD

**Issue by G7g9a** [ruffle-rs/ruffle#6661]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 40 but the index is 40', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/jpeg-decoder-0.1.22/src/upsampler.rs:218:22
Error stack:
```
@https://mysexgamer.com/assets/ruffle/ruffle.js:1:7035
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h6e694fc45f651103]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h99e47643887ee5a5]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hb552ca3003b47989]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h03201bc01a0ed891]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hd44f353696296fec]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::h6f1d19fbb70f7a33]@[wasm code]
<?>.wasm-function[<jpeg_decoder::upsampler::UpsamplerH2V2 as jpeg_decoder::upsampler::Upsample>::upsample_row::h92585c9adef179df]@[wasm code]
<?>.wasm-function[jpeg_decoder::decoder::compute_image::heb7b7611c933e769]@[wasm code]
<?>.wasm-function[jpeg_decoder::decoder::Decoder<R>::decode_internal::h4299ff140ebafdef]@[wasm code]
<?>.wasm-function[ruffle_core::backend::render::decode_define_bits_jpeg::hf25aad6890828b8b]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_bitmap_jpeg_3::h834ce13813bc61ea]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::hc1aa22a23a3780b3]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h5cc1cee597baa183]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h120ccdeae3267ee4]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h72d7af3bf06f1fd6]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4014bfc4ca727422]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h69dd9711782f1b19]@[wasm code]
wasm-stub@[native code]
T@https://mysexgamer.com/assets/ruffle/ruffle.js:1:4274
a@https://mysexgamer.com/assets/ruffle/ruffle.js:1:2799
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/e/2/4/e24a39161b60b2bf73eabfca529c179e/e24a39161b60b2bf73eabfca529c179e.swf
Param movie: https://v8p5i7f9.ssl.hwcdn.net/games/swf/e/2/4/e24a39161b60b2bf73eabfca529c179e/e24a39161b60b2bf73eabfca529c179e.swf
Param quality: high
Param bgcolor: #000000
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: always
Param SCALE: default
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://mysexgamer.com/game/milk-plant-6
SWF URL: https://v8p5i7f9.ssl.hwcdn.net/games/swf/e/2/4/e24a39161b60b2bf73eabfca529c179e/e24a39161b60b2bf73eabfca529c179e.swf

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/100.0.4896.77 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-06-17
Channel: nightly
Built: 2021-06-17T00:11:56.220Z
Commit: 622f35eb713c224a980ab67eb251a4b6880e1834

**Comment by Herschel** [comment]
Closing in favor of #6608.
