### ISSUE TITLE
Ruffle Error on https://www.poopclicker.com/

### ISSUE THREAD

**Issue by qwer444f** [ruffle-rs/ruffle#6669]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://poopclicker.com/ruffle/ruffle.js:1:67052
    at Array.forEach (<anonymous>)
    at Object.vi.f.wasm (https://poopclicker.com/ruffle/ruffle.js:1:66979)
    at https://poopclicker.com/ruffle/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at Function.vi.e (https://poopclicker.com/ruffle/ruffle.js:1:35276)
    at o (https://poopclicker.com/ruffle/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://poopclicker.com/ruffle/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: PoopClicker.swf
Param game: PoopClicker.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.poopclicker.com/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-02
Channel: nightly
Built: 2021-01-02T00:44:12.942Z
Commit: 83c32e8693ec7d585713d457599b87b81e2057c3

**Comment by qwer444f** [comment]
kill

**Comment by Toad06** [comment]
Thanks for the report. It seems like the site is failing to load a required file, so this is not an issue on our end. However you can prevent the issue from happening by navigating to https://poopclicker.com/ (without the www part in the URL).

The file also uses ActionScript 3, which is still a work in progress (cc. #1368).
