### ISSUE TITLE
Don't build in bootstrap

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#667]

**Comment by Dinnerbone** [comment]
I'm not sure what you mean by this, sorry.

**Comment by Justin-CB** [comment]
`npm run bootstrap` builds the entire core package.

**Comment by Dinnerbone** [comment]
Shouldn't it? I think that's just how npm works. I'm not sure there's much we can do here.

`core` is a dependency of `selfhosted`. When you run `npm install` on `selfhosted`, it needs `core` to be build and packaged ready for it.
