### ISSUE TITLE
Dragonzball P: Weird Screen Filter Bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#6702]
### Describe the bug

Other issues aside, the main issue that i've noticed with this animation is that the screen filtering effect it uses looks weird on ruffle, turning it into some kind of old western film, just watch the video version and the flash version together and it should be noticable right away. (You will need to right click and play the flash animation in ruffle to get it working.)

https://www.newgrounds.com/portal/view/586125/format/flash
https://www.newgrounds.com/portal/view/586125

<img width="480" alt="Filter bug 1" src="https://user-images.githubusercontent.com/78768499/163279120-ff136ac3-983b-4d75-97e9-6d1bd141282c.png">

### Expected behavior

The screen filter should look like pic related.
<img width="599" alt="Filter bug 2" src="https://user-images.githubusercontent.com/78768499/163279172-60d74cbf-100f-4c52-8777-edb5edbd063c.png">

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Edge 100

**Comment by torokati44** [comment]
Just by the look of it, this animation uses one of the blend modes other than "normal", none of which are done yet in Ruffle.
See: https://github.com/ruffle-rs/ruffle/issues/58

**Comment by waspennator** [comment]
Gotcha, just wasn't entirely sure if this was relying on an unimplemented feature or not.

**Comment by waspennator** [comment]
![DBZP fixed](https://user-images.githubusercontent.com/78768499/210486057-1d0832a7-e0a0-4ab3-9aaa-b4e9bf6cefcd.png)
Can't test on desktop build of latest nightly cause this SWF requires the right click trick to get working, but on the current web version on NG (Webgl+Wgpu with blend support), the issue seems to be fixed up entirely, so I have a feeling it's probably the same on desktop too.

**Comment by Lord-McSweeney** [comment]
The text doesn't have the black outline around it, although it is present in Flash.

**Comment by waspennator** [comment]
With #8873 merged in, the swf is now capable of starting up on desktop and i'm assuming will no longer need the right click and play trick on web anymore. The only noticable problem that seems to be left at this point is the subtitle text on the bottom not being outlined in black.

**Comment by waspennator** [comment]
![Dragons](https://github.com/ruffle-rs/ruffle/assets/78768499/b3132044-0049-4daa-99df-033a2d1331c1)
Issue should be resolved by #11878
