### ISSUE TITLE
Build Instructions aren't working.

### ISSUE THREAD

**Issue by gitautas** [ruffle-rs/ruffle#6705]
### Describe the bug

Following the contribution guidelines I tried to have a local build of ruffle going as follows:
```sh
git clone https://github.com/ruffle-rs/ruffle.git
cd ruffle/web
npm install
npm run build
```
and the build step errored out with the [following](https://0bin.net/paste/6UgrSobL#IvFA04cvWMXK+lz217rqsV8JMFZK17ZTLTiIsBLqlM6) output.

### Expected behavior

Me cloning and building the repo.

### Affected platform

Online demo

### Operating system

macOS 12.2.1 Monterey

### Browser

N/A

### Additional information

NodeJS v14.19.0
NPM v8.4.1
Cargo/rustc v1.60.0-nightly

**Comment by danielhjacobs** [comment]
I see the output says "consider downloading the target with `rustup target add wasm32-unknown-unknown`"

Have you done so?

**Comment by gitautas** [comment]
> I see the output says "consider downloading the target with `rustup target add wasm32-unknown-unknown`"
> 
> 
> 
> Have you done so?

Sorry to make you read my own logs for me, that did indeed work. I appreciate the help, as sad of a moment as this is for me :D
