### ISSUE TITLE
.dcr files won't play

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6711]
### Describe the bug

This game won't play. Here is the page url: http://www.ancientegypt.co.uk/life/activity/act_main.html Here is the affected file: http://www.ancientegypt.co.uk/life/activity/game.dcr 

### Expected behavior

I expected the game to load and play

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 99.0.1

**Comment by p0008874** [comment]
This will be #6300

**Comment by torokati44** [comment]
Yep, and quoting @n0samu from that issue:
> The ScummVM project is already working on Director emulation: https://wiki.scummvm.org/index.php?title=Director
This is out of the scope of the Ruffle project, at least for the foreseeable future.

**Comment by CoolDino1** [comment]
Will you please reopen this issue, I updated Ruffle and it still did not work

**Comment by torokati44** [comment]
Again: "This is out of the scope of the Ruffle project, at least for the foreseeable future."
The other issue (#6300) is still open nevertheless.

**Comment by CoolDino1** [comment]
If it is not fixed it should be left open

**Comment by torokati44** [comment]
"Out of scope" means that at the moment there is no intention for making this work within this project.

As an analogy, the fact that Photoshop can't do 3D animation is not a bug. It's just not something it even aims to do, so there is nothing to fix.
