### ISSUE TITLE
Text position is wrong

### ISSUE THREAD

**Issue by xvbcfj** [ruffle-rs/ruffle#6713]
### Describe the bug

Text position is wrong in some very very old swf files. [Download sample files here](https://github.com/ruffle-rs/ruffle/files/8496636/swf.zip)
![image](https://user-images.githubusercontent.com/103762739/163587393-6d42aa49-ab9d-4247-b79a-865f51459ce4.png)

### Expected behavior

Text is displayed correctly

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/18361
