### ISSUE TITLE
Some menus in SteppenWolf's website constantly fade in nonstop

### ISSUE THREAD

**Issue by LiquidCat64** [ruffle-rs/ruffle#6720]
### Describe the bug

Title basically says it. On the website for SteppenWolf: The X-Creatures Project, there are three menus that, after loading, will fade in over and over again ad infinitum.

Link to a reconstruction of the website: http://steppenwolf.epizy.com/home.jsp

To reproduce the issue, go to the site linked above, click the Ruffle "play" button, and on the left side bar, click "all chapters", "character dossiers", or "monster manual" to be taken to the buggy areas of the site. In the case of "character dossiers" and "monster manual", hover over one of the character icons to make the buggy part appear; it'll already be there when the "all chapters" menu loads.
![Menu](https://user-images.githubusercontent.com/74896918/163659124-ac61cfd5-a6c3-4d83-bfcc-550c5678f8d3.gif)

### Expected behavior

The Flash behavior is that the menus fade in and constantly remain at 100% opacity so they can be interacted with.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge Version 100.0.1185.39 (Official build) (64-bit)

**Comment by Toad06** [comment]
Thanks for the report.

This site loads multiple inner SWFs and it seems like the issue only occurs once `infotext_gen11.swf` is fully loaded. So if you click quickly enough on "all chapters", "character dossiers" or "monster manual" when the main SWF is displayed, the site will work as expected - if you then click the "Steppenwolf" logo, wait and click one of the links in the menu again, the issue you described will occur.


Maybe related to https://github.com/ruffle-rs/ruffle/issues/5502#issuecomment-947373025?

**Comment by Herschel** [comment]
I think the `infotext_gen11.swf` does not get properly unloaded by Ruffle, and it has some code which says `tellTarget("/") { play(); }` on a timer. Both `infotext_gen11` and `dossiers` get loaded into level 2, so the timer code ends up telling the text to constantly replay itself.

**Comment by Toad06** [comment]
Fixed by #11143.
