### ISSUE TITLE
KingsCall won't open the decoder after it is picked up

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6724]
### Describe the bug

Steps to reproduce
1. go to kingscall.org and click 'start playing king's call'
2. enter your name and play the game
3. make sure to pick up the decoder at the village of soulous
4. once it is picked up try to open it again from the inventory bar
5. it won't work!!!!!!!!!!
6. (it is the same on all the levels i've played)

### Expected behavior

I expected the decoder to open

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 99.0.1

**Comment by n0samu** [comment]
Can you explain where clicking the decoder in the inventory is supposed to do something? I tried clicking the decoder after picking it up in the actual Adobe Flash Player, and nothing happened there either.

**Comment by CoolDino1** [comment]
I don't remember perfectly, as it has been a while since flash was removed, but I think it should open like it did when you picked it up.

**Comment by CoolDino1** [comment]
Sorry my memory is bad. There is no issue. I will close this
