### ISSUE TITLE
AVM1 Layout issue

### ISSUE THREAD

**Issue by Elementtair** [ruffle-rs/ruffle#6784]
### Describe the bug

Here is a flash exemple for the issue: https://www.mercedes-anciennes.fr/forummb/w123.swf

Here is what you can see with ruffle, all versions affected: https://ibb.co/ccxCW9t
Here is what should be seen with flash: https://ibb.co/hcFpsnD

The second picture of the document should stop on the bottom legend, but instead the bottom of the picture is displayed and goes up on the text: https://ibb.co/SJ30xvN

### Expected behavior

Here is what should be seen with flash: https://ibb.co/hcFpsnD

### Affected platform

Online demo

### Operating system

Windows 10 x64

### Browser

Firefox

### Additional information

This document (as other) was bugged until not so long ago by this issue and no text was displayed at all:
https://github.com/ruffle-rs/ruffle/issues/3115

**Comment by relrelb** [comment]
This uses a clipping layer to crop the image using the `clipDepth` property in `PlaceObject2` tags. These are currently ignored.

**Comment by Elementtair** [comment]
Thanks for watching. 
It will then wait until the feature come.

**Comment by n0samu** [comment]
The example provided in https://github.com/ruffle-rs/ruffle/issues/1347#issuecomment-753291983 is a great minimal use of clipping layers, if anyone is interested in working on implementing them.
