### ISSUE TITLE
web:  drag along path not in trail during move

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#681]
In Flash, you can drag an element along a path and it is always bound to the trail.

In ruffle the element can be moved away from the path during the drag, only afterwards it snaps back to the path. 

See http://www.webgeo.de/k_021/#5
(on http://www.webgeo.de you can switch between using ruffle or using flash)

**Comment by KMicha** [comment]
![flash_k_021_5](https://user-images.githubusercontent.com/1667683/83648413-4fd1c580-a5b6-11ea-9b2c-fb11cd67c724.jpg)

![ruffle_k_021_5](https://user-images.githubusercontent.com/1667683/83648436-56603d00-a5b6-11ea-9878-b21162c9b194.jpg)

**Comment by KMicha** [comment]
BTW: The labels are missing completly

**Comment by KMicha** [comment]
[k_021_05.zip](https://github.com/ruffle-rs/ruffle/files/4723982/k_021_05.zip)

**Comment by Herschel** [comment]
Seems to be that `startDrag` drag updates should run before enter frame code (which later clamps it), but needs more investigation.

**Comment by KMicha** [comment]
Looks like it"s working now - thanks for the fix...
