### ISSUE TITLE
matrix pandemonium: Background not link to current location

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#6814]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/165343610-0060f14d-8a80-43e1-a1ed-198ae84df4df.png)
[matrix-pandemonium_Unpacked.zip](https://github.com/ruffle-rs/ruffle/files/8571078/matrix-pandemonium_Unpacked.zip)

### Expected behavior

It supposed be like this.
![image](https://user-images.githubusercontent.com/75534590/165347565-f26c7c52-e7c8-4bcf-ac98-e3626d70af36.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome 100.0.4896.127

### Additional information

none

**Comment by n0samu** [comment]
It looks like your zip file failed to upload, can you try again?

**Comment by p0008874** [comment]
> It looks like your zip file failed to upload, can you try again?

[matrix-pandemonium_Unpacked.zip](https://github.com/ruffle-rs/ruffle/files/8571078/matrix-pandemonium_Unpacked.zip)

**Comment by n0samu** [comment]
I guess a clearer description of this issue is that the level's background image does not scroll with the foreground objects like it should, instead staying fixed in place. As for the cause of this issue, I have no idea honestly :(

**Comment by p0008874** [comment]
It sound's like it Fixed in nightly 2022-08-30.

**Comment by torokati44** [comment]
Sounds like this was fixed by #7739 (and/or perhaps #7806).
