### ISSUE TITLE
Rage 3 attack Issue

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#6879]
### Describe the bug

step to reproduce the issue:
1, load Rage 3 into Ruffle
2, go to 'Adventure' and select the first world (any will do)
3, press the attack button at least once (not the gun) and run near an enemy.

### Expected behavior

When attacking, the player needs to continually press the attack button to defeat an enemy

In Ruffle, pressing the attack button once makes the player recieve a sort of death 'aura', where no more action is needed to kill an enemy, aside from going near them.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by gunsg-92** [comment]
https://user-images.githubusercontent.com/103858019/166474090-709953f7-7920-469d-aab4-b93a95c3f520.mp4

The issue in Ruffle


https://user-images.githubusercontent.com/103858019/166474152-b5db35a6-13e3-4f4f-8309-7694117c7778.mp4

 in FP, no issue.

**Comment by p0008874** [comment]
This has been fixed by #9447
