### ISSUE TITLE
Flash content flashing at http://gameflash.xyz/game00252/

### ISSUE THREAD

**Issue by c933103** [ruffle-rs/ruffle#6887]
### Describe the bug

# Enter the URL http://gameflash.xyz/game00252/ which host a flash game
# Click start running

### Expected behavior

# For it to run stably

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 93

### Additional information

The Flash content keep blinking.

Extension being used is https://addons.mozilla.org/ja/firefox/addon/flash-player-emulator/

**Comment by n0samu** [comment]
This content uses ActionScript 3 which is not yet supported by Ruffle. See the [FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content).

**Comment by Lord-McSweeney** [comment]
Seems to work fine now.
