### ISSUE TITLE
Windows logo rendered without transparency

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#6893]
### Describe the bug

The shapes in [this Windows logo SWF](https://web.archive.org/web/20071222094810id_/http://www.snakzstock.com/famicon/index.swf) are rendered with white backgrounds instead of transparent backgrounds as shown below:
![image](https://user-images.githubusercontent.com/71368227/167070670-77930774-2d5d-4c7e-9f24-c75f0542d944.png)
The backgrounds of the shapes overlap each other, leading to the weird-looking image.

### Expected behavior

This is what it looks like in Flash Player:
![image](https://user-images.githubusercontent.com/71368227/167070839-ffe9c1b9-c67b-46c5-9709-d034c58a4e5a.png)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 99

### Additional information

I took a quick look through the SWF and it doesn't seem to be using unsupported features like clip depths or blend modes, so I'm not sure why it's rendering incorrectly.

**Comment by Herschel** [comment]
Hmm, this is exported as DefineBitsJPEG3 (JPEG + alpha), but the colors don't seem to be correctly premultiplied alpha. Flash will normally premultiply the colors by the alpha when exporting, so I'm not sure what to do here. Maybe `alpha == 0` is special cased to zero out the color?
