### ISSUE TITLE
[Monst] The longer the game is turned on, the lower the performance. (Memory Leak?)

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6896]
### Describe the bug

In **Monst**, if you start the game right away and proceed with the game, there seems to be no problem.
(Actually, compared to Adobe Flash Player, it's a bit slow due to performance issues.)

[monst.zip](https://github.com/ruffle-rs/ruffle/files/8638145/monst.zip)

However, if you **wait for a very long time before clicking the Play button**, you can see that the speed is noticeably slower than when it was not.

The following is a comparison video between when the game started after waiting for about 10 minutes and when it did not.

https://user-images.githubusercontent.com/75052171/167083122-15078fc1-a725-4f2a-942d-f21cae9deab0.mp4

Both environments above were tested in the same environment, in the same way (but with different timing of clicks).

Verified on the Web Hosted version of `Ruffle Nightly 2022-05-04`.

I don't know if this is a memory leak or a programming mistake in the game.

But what is clear is that Adobe Flash Player showed the same performance over the same time period.

### Expected behavior

Performance should be the same when the game is left on for a long time and when not.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 101

**Comment by Jmousy** [comment]
Once again, this time I checked it through the official desktop app.
After 10 minutes, I could see the memory occupancy going up very high.

As time goes on, the memory is getting higher and higher!

**Comment by mero09-99** [comment]
still an issue
