### ISSUE TITLE
Ruffle blocks connections to external sources

### ISSUE THREAD

**Issue by wildmaster84** [ruffle-rs/ruffle#6901]
### Describe the bug

While launching a SWF game, Ruffle blocks connections required for the game to communicate with the server.

### Expected behavior

Connect to external servers

### Affected platform

Self-hosted version

### Operating system

Windows 11, Windows 10

### Browser

Crome, Edge

### Additional information

While testing around i managed to run Adobe Flash which let get the game connect to servers just fine while Ruffle blocked the connection.

The game sends data to the server and the server returns the results, then the game will connect after the results are received.

I also found that emulators also don't work as they block internal and external connections.

Please let me know if there is a quick way to resolve this bug without converting ActionScript2 to HTML5

**Comment by danielhjacobs** [comment]
Is there a particular site you can point to where this issue is occurring? Ruffle does not support Flash Remoting (https://github.com/ruffle-rs/ruffle/issues/3317 / https://github.com/ruffle-rs/ruffle/issues/4482) / NetConnection (https://github.com/ruffle-rs/ruffle/issues/265), but it supports loading external data using common methods. However, Ruffle is reliant on CORS unlike Flash, so the server must respond with the proper CORS headers. Check the console and paste any errors you see here.

**Comment by wildmaster84** [comment]
the console says no errors. atm i am running the game localhost with adobe which works fine. Since it uses NetConnection, i will need to find something else that does

**Comment by danielhjacobs** [comment]
> i will need to find something else that does

I can only wish you luck. I opened https://github.com/ruffle-rs/ruffle/issues/3317 myself, but we now pretty much consider those sites decommissioned. Browsers will never support regular sockets (see https://stackoverflow.com/questions/8051516/how-to-establish-a-tcp-socket-connection-from-a-web-browser-client-side). Adobe Flash player was given a special exception to that by browser vendors. It looks like NetConnection may rely on sockets.  Maybe the core Ruffle devs can make it work one day as long as the server sets proper CORS headers, but it seems unlikely.

**Comment by Herschel** [comment]
Closing this in favor of #3317 -- features such as NetConnection are a TODO.

We do support loading data from external sources (such as XML), but Ruffle is at the mercy of modern browser security, so loading data from different domains is disallowed by the browser by default unless the server is configured for CORS. Thank you!
