### ISSUE TITLE
Super Mario 63: problems when entering the castle

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#6906]
### Describe the bug

To reproduce the bugs:
1. Load the [SWF file](https://www.play-games.com/files/swf/Super-Mario-63_1402146483_1410902473.swf) with Ruffle
2. Play through the tutorial (takes 10-20 minutes or so) and reach the castle. Press the up arrow to enter the castle

You should notice these problems:
* The transition to the next level is extremely slow (takes 1-2 minutes even on high-end hardware)
* During this transition, memory usage climbs significantly (in my testing, up to 4GB)
* Once the level starts, many of the objects in the level are missing and part of the background is black/blank

It's still possible to reach the next door. But if you go through that door, there will be another extremely slow transition, and then Mario will end up floating in the sky and unable to move (see screenshot below)
![image](https://user-images.githubusercontent.com/71368227/167241861-d2cceacb-1ce2-4eaa-b55d-51d82479b274.png)

### Expected behavior

None of these problems should occur.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 100

### Additional information

I've attached the log from my browser console (log level: info) below, but it may not be very helpful
[sm63.log](https://github.com/ruffle-rs/ruffle/files/8644591/sm63.log)

**Comment by Toad06** [comment]
The [Newgrounds version](https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?1353774292) also has this issue. I'm mentioning this because you can skip cutscenes in this version which is nice when testing.

I tried to investigate the issue. When you enter the castle, the following function runs:

```
_root.StartInsideofCastle = function()
{
   _root.RemoveCourse();
   _root.gotoAndStop("Courseframe");
   _root.StartChar("C-1",0,0,0,0,100,_root.CurrentPlayer,_root.Fluddpow,"StarIn",true);
   _root.onEnterFrame = function()
   {
      _root.CharCode();
   };
};
```

Removing the `_root.onEnterFrame` fixes the crash (Mario enters the castle... then keyboard inputs are no longer registered - this is consistent with Flash Player).

However... the same `_root.onEnterFrame` / `_root.CharChode` calls also exist in the tutorial level, with no issue at all.

So I think the issue comes from `_root.RemoveCourse()` which sets `_root.onEnterFrame` to null and also calls `removeMovieClip()` a bunch of times. Because of #3839, I believe that this later causes issues in `_root.CharCode()`.

It will be worth testing the game again when #5492 is no longer a draft (the game doesn't work at all currently).

**Comment by Myzel394** [comment]
Is there a current workaround? @Toad06 how do you remove `_root.onEnterFrame`? When I download the file and try to edit it, it seems like it contains only minified code.

**Comment by n0samu** [comment]
If you just want to play the game, you can download the SWF file and run it using the standalone Flash projector: https://web.archive.org/web/20220331041116/https://www.adobe.com/support/flashplayer/debug_downloads.html
From what Toad stated, it doesn't sound like removing that piece of code would really make the game playable in Ruffle, anyway.

**Comment by Scott-Steinheiser** [comment]
It does not take me 1-2 minutes. It never lets me enter the castle.

**Comment by n0samu** [comment]
> It is still not working even though I already downloaded the Adobe Flash Projector.
You need to download the SWF file and open it with the Flash projector. [You can download the SWF file from Archive.org](https://archive.org/download/flash_supermario63/supermario63.swf).

**Comment by Luigi-Fan** [comment]
HOW DO I EVEN EDIT THE FILE?!?!?!

**Comment by Luigi-Fan** [comment]
Where do I download Adobe Flash Projector?
I play on chromebook by the way, so I use Chrome OS.

**Comment by Luigi-Fan** [comment]
And, of course, I use Google Chrome.

**Comment by Myzel394** [comment]
@Luigi-Fan not sure if that's possible on ChromeOS, but I ended up using a Windows 11 on a virtual machine and downloaded the exe. It ran perfectly that way

**Comment by SamirTheHuman** [comment]
This is what happened in the older versions before Ruffle became a little more advanced. After, it just becomes a big mess. Did not see this post so thanks for showing me this.

**Comment by n0samu** [comment]
As noted by others already, Ruffle now times out the script so it doesn't have a chance to complete at all anymore. So when trying to enter the castle, Ruffle freezes for a bit and then cycles through the graphics without running any more ActionScript.

**Comment by Adamillo** [comment]
So do we extend the time it takes before the script gets timed out or is there a better solution out there?

**Comment by Myzel394** [comment]
@Adamillo if you want to play the game, you could also try setting up a virtual machine with Windows and run the game inside it. This worked for me at least

**Comment by Adamillo** [comment]
Sure, but at that point why bother when I can can just run the standalone Flash version? Not trying to be mean of course but with the amount of hoops you have to jump through just to play this game on Ruffle...

**Comment by Myzel394** [comment]
Does the standalone version work with the castle? I haven't played this game in the last time but afaik it didn't work for me

**Comment by n0samu** [comment]
You don't need Windows to run the standalone Flash Player. It is also available for Linux and MacOS.

> So do we extend the time it takes before the script gets timed out or is there a better solution out there?

Yes, I'm planning to test the game with the script execution limit increased when I get a chance. Right now the limit is only customizable in selfhosted web builds of Ruffle, which makes it a bit difficult. The option is called `maxExecutionDuration`: https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#list-of-options

**Comment by io12** [comment]
I tested disabling the script execution limit (by modifying the Ruffle code) and when entering the castle, the screen stays black, but RAM usage keeps increasing, which seems like a memory leak.

**Comment by io12** [comment]
I could be wrong, but I think this is the infinite loop (in `UnpausedCharEngine()`).
```as
while(_root.Course.Platforms.hitTest(_X * _root.coursescale / 100 + _root.Course._x,(_Y - 3) * _root.coursescale / 100 + _root.Course._y,true) && !(Squish == true && (_yscale < 70 || attack == true && attackFrame == "Squish")) && (!_root.Course.Platforms.invisground.hitTest(_X * _root.coursescale / 100 + _root.Course._x,(_Y - 3) * _root.coursescale / 100 + _root.Course._y,true) || _root.Invisible !== true) || _root.Course.BPlatforms.hitTest(_X * _root.coursescale / 100 + _root.Course._x,(_Y - 3) * _root.coursescale / 100 + _root.Course._y,true) && yspeed >= -3)
{
   _Y--;
   if(!(attack == true && attackFrame == "Dive"))
   {
      xspeed *= 0.98;
   }
   else
   {
      xspeed *= 0.997;
   }
   _root.FallSquish();
   yspeed = Math.min(0,yspeed);
}
```

**Comment by io12** [comment]
This patch allows entering the castle with key input continuing to work. A zero matrix is appearing somewhere and I think that's breaking the collision check between the castle platforms and the player, causing the infinite loop. I'm not making this a PR though because I'm not sure why the matrix is zero. There may be a deeper issue?

```diff
diff --git a/core/src/display_object.rs b/core/src/display_object.rs
index 47d67a3..8a9d618 100644
--- a/core/src/display_object.rs
+++ b/core/src/display_object.rs
@@ -771,7 +771,14 @@ pub trait TDisplayObject<'gc>:
             if let Some(rect) = display_object.scroll_rect() {
                 matrix = Matrix::translate(-rect.x_min, -rect.y_min) * matrix;
             }
-            matrix = *display_object.base().matrix() * matrix;
+            let s = *display_object.base().matrix();
+            let s = if s.a == 0.0 && s.b == 0.0 && s.c == 0.0 && s.d == 0.0 {
+                Matrix::IDENTITY
+            } else {
+                s
+            };
+            matrix = s * matrix;
             node = display_object.parent();
         }
         matrix
```

**Comment by n0samu** [comment]
Thank you for looking into this! I wish I could help - hopefully someone can!

**Comment by Herschel** [comment]
Haven't investigated yet, but it's possible that we simply need to handle a zeroed-matrix (which could otherwise be valid) in `hitTest` and always return false. I'll dig into it a bit!

**Comment by Herschel** [comment]
Yeah, `hitTest` on a zero-scale object returns `false` in FP, but `true` in Ruffle:
[hittest-microscopic.zip](https://github.com/ruffle-rs/ruffle/files/11015041/hittest-microscopic.zip)
Haven't tested to see if this is the issue in Super Mario 63, but I suspect it is.

Is anyone familiar with the game able to hack the FLA so that the game starts at the problematic section? Otherwise I can try some this week.

**Comment by Toad06** [comment]
@Herschel, here's a hacked version.
[mm63.zip](https://github.com/ruffle-rs/ruffle/files/11035076/mm63.zip)

**Comment by szefkaf** [comment]
Hi, I've fixed castle level manually (see attachment) changing C1-Platform' background with new .svg file. In original version background in Castle level is made from few open images, perhaps somewhere path is open and treated as a zero-scale object. So will You fix it in Ruffle or we have to change all backgrounds level causing errors?
[mm63_castle_fixed.zip](https://github.com/ruffle-rs/ruffle/files/11038667/mm63_castle_fixed.zip)

**Comment by Adamillo** [comment]
Of course it'll get fixed eventually. Just have to be patient for now

**Comment by szefkaf** [comment]
Hello,
I've fixed this game under Ruffle, is playable to the end. If someone wants check what was incompatible with Ruffle:
[https://grywacz.pl/game/super-mario-63-emu](https://grywacz.pl/game/super-mario-63-emu)
Most of the errors occurred when Ruffle calling changecourse(); function. So HitTest may be not enough to fix this game without interfering with the source code.
