### ISSUE TITLE
Morion: Missing menu text

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#6920]
### Describe the bug

The text of the menu buttons is missing, as shown below:
![image](https://user-images.githubusercontent.com/71368227/167297832-4dc86fda-da4c-4c96-92db-2ec338a2b3e7.png)
I've attached a ZIP containing the SWF file.
[morion_final.zip](https://github.com/ruffle-rs/ruffle/files/8647018/morion_final.zip)

Switching the language to English does not help. To test this, click the 3rd menu option, then the 2nd, then the 2nd again.

### Expected behavior

Here is what the menu should look like:
![image](https://user-images.githubusercontent.com/71368227/167298000-de47f928-ff35-4014-9506-ec0e91a3168d.png)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Firefox 100

### Additional information

I think this issue may be related to #1574; the embedded fonts seem to be missing layout data.

**Comment by torokati44** [comment]
FWIW I can no longer reproduce this.

**Comment by n0samu** [comment]
You're right! Testing with https://ruffle-regressions.github.io/, I see that this was fixed in build 2022-09-08. I bet it was something in #7853 that fixed it.
