### ISSUE TITLE
Error on http://xxx-game.org/

### ISSUE THREAD

**Issue by kolia106** [ruffle-rs/ruffle#6924]
# Error Info
Error name: TypeError
Error message: Сетевое соединение потеряно.

# Player Info
Allows script access: true

# Page Info
Page URL: http://xxx-game.org/?page_id=528

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_0_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-02-07
Channel: nightly
Built: 2022-02-07T00:21:18.799Z
Commit: 562a205f3d873720ae71989850240e3ae729df64
Is extension: false

**Comment by n0samu** [comment]
This seems to be a problem with your internet connection, not a problem with Ruffle.

**Comment by Herschel** [comment]
Closing as this appears to be a network problem, although perhaps we could show a better error message/hide the report link in this case?
