### ISSUE TITLE
Nick Jr. Games Site Stuck on Loading Screen

### ISSUE THREAD

**Issue by dev-jacobw** [ruffle-rs/ruffle#6947]
### Describe the bug

Hello Ruffle community! I'd like to report an issue with accessing games on the old Nick Jr. website from 2005 (meaning it should be using AVM1). Here's the link: 
https://web.archive.org/web/20050207012801id_/http://www.nickjr.com/playtime/index.jhtml

Upon opening the linked page, there's a loading screen that apparently never finishes (I've allowed it to load for up to 30 minutes with no result). Below is a screenshot of the loading screen.

![Nick Jr. Loading Screen](https://user-images.githubusercontent.com/103968783/167784437-714f7e35-cb05-4a05-badd-a21c811e609c.png)

### Expected behavior

The expected behavior is that the loading screen finishes after a couple of minutes at most, and the list of Nick Jr. TV shows with their games appears. This is according to my memory of how the site worked back in 2005. Thanks so much for building and maintaining such a great project!

### Affected platform

Browser's extension

### Operating system

macOS Big Sur

### Browser

Google Chrome version 101

**Comment by n0samu** [comment]
Sadly this page behaves exactly the same with the real Adobe Flash Player. So I think it's an issue with the archive, not with Ruffle.

**Comment by Herschel** [comment]
Looks like it's trying to load https://web.archive.org/web/20130110000134/http://www.nickjr.com/kids_common/flash_data/piper.jhtml which was unfortunately not archived by the Internet Archive.

**Comment by dev-jacobw** [comment]
Ah, makes sense. Thanks for looking into it!

**Comment by dev-jacobw** [comment]
By the way, for anyone who still wants to play the games on the classic Nick Jr. site, you can find the SWF files directly on Archive.org by searching for [all URLs under the Nick Jr. domain](https://web.archive.org/web/*/nickjr.com*). I've been able to play several games there with Ruffle this way.
