### ISSUE TITLE
Background defaults to white on iPad

### ISSUE THREAD

**Issue by Mark0669** [ruffle-rs/ruffle#6953]
No problems with our swfs, all working well in Safari, Chrome etc across several devices. However, on an iPad the swf background colour defaults to white. Any ideas?

Thanks,
Mark

**Comment by n0samu** [comment]
Are you able to provide an example?

**Comment by Mark0669** [comment]
https://primarygames.co.uk/tasters/taketime1.html


> Are you able to provide an example?

**Comment by n0samu** [comment]
I just tested it on my iPhone and the SWF background appears blue, just like it does on desktop browsers. What iOS version is your iPad running?

**Comment by Mark0669** [comment]
> I just tested it on my iPhone and the SWF background appears blue, just like it does on desktop browsers. What iOS version is your iPad running?

iPadOS 15.4.1 A bit odd! This is what I get:
![ww](https://user-images.githubusercontent.com/80102846/168049834-b02c7785-535f-421e-b089-55cac9775da1.png)

**Comment by n0samu** [comment]
I wonder if this may be related to #6608. I'm on iOS 15.3 and that issue (which normally causes a crash) occurs on iOS 15.4. iOS 15.5 should be out later this month - please let us know if this problem is fixed for you in the update.

**Comment by Mark0669** [comment]
Possibly, get the same issue in Chrome too though. Will see what the iOS update brings. Thanks!

**Comment by torokati44** [comment]
Apple doesn't let anyone run any web engine on iOS other than the one built into it - so any browser on that device will behave exactly the same.

**Comment by Herschel** [comment]
I believe this is fixed in iOS 15.5 released today, could you verify that @n0samu?

**Comment by Mark0669** [comment]
> I believe this is fixed in iOS 15.5 released today, could you update your device and verify that @Mark0669?

Issue fixed with iOS15.5. Appreciated the feedback on this. Thanks!
