### ISSUE TITLE
Add `Twips2d` type

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#6973]
We use `(Twips, Twips)` in quite a few places. Instead, we could add a `Twips2d` type with operator overloads.

**Comment by Mekomancer** [comment]
Is there a file for custom types, and if not where would `Twips2d` be defined.

**Comment by Herschel** [comment]
Currently Twips is defined in `swf/src/types.rs`: https://github.com/ruffle-rs/ruffle/blob/a453aa73afbd8d8ab509bd7cbd2366a024ca8649/swf/src/types.rs#L199

But it's getting chunky enough that it's probably worthwhile to pull these out into their own file(s) `swf/src/types/twips.rs` and `swf/src/types/twips_2d.rs`, similar to `Fixed8` and `Matrix`.

**Comment by kmeisthax** [comment]
As of #6977 being merged in we now have this type ready to replace things.

**Comment by marcograss** [comment]
is this still relevant @kmeisthax or it can be closed?

**Comment by kmeisthax** [comment]
I want to say no, because we still need to replace coordinate pairs with it
