### ISSUE TITLE
Recent update breaks Gridlock - https://www.newgrounds.com/portal/view/840594

### ISSUE THREAD

**Issue by foumart** [ruffle-rs/ruffle#6976]
### Describe the bug

Nightly 2022-05-11 works,
Nightly 2022-05-13 produces the following errors:

```
ERROR: 0:20: 'saturate' : no matching overloaded function found
ERROR: 0:26: 'saturate' : no matching overloaded function found
ERROR: 0:133: 'saturate' : no matching overloaded function found
Error linking shader program: Some("Vertex shader is not compiled.\n\u{0}")
Error creating WebGL renderer: Error linking shader program: Some("Vertex shader is not compiled.\n\u{0}")
```
Most of the graphics (which are all vector) are not shown.

### Expected behavior

Game should be working as on previous builds.

### Affected platform

Self-hosted version

### Operating system

Windows 10, Chrome 101.0.4951.54 (Official Build) (64-bit)

**Comment by torokati44** [comment]
Thanks for the report!
This was a small mistake introduced in #6959, and will be fixed by #6970 in the next nightly release, in just a few hours.

**Comment by torokati44** [comment]
Although similar to #6969, this might also point to shortcomings of the canvas renderer.

**Comment by foumart** [comment]
The game vector animations were actually playing really smooth, so good job on achieving such good performance.
Otherwise the game has another problem - after a few levels it starts to lag, which is very noticeable on phones, but perhaps that's for another report.

**Comment by foumart** [comment]
The issue was resolved with the latest build from today 14th.
