### ISSUE TITLE
[Barbie Makeover Magic] Cursor is not visible, clicking does not proceed

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6984]
### Describe the bug

![image](https://user-images.githubusercontent.com/75052171/168454351-69ba25f6-9d04-4efc-aacb-8d70e3a206b7.png)

[Barbie Makeover Magic.zip](https://github.com/ruffle-rs/ruffle/files/8694188/Barbie.Makeover.Magic.zip)

### Issue 1. 
When starting out, Barbie's default hair color is different from the original (Adobe Flash Player).

### Issue 2.
Clicking 'Play again' (bottom menu) does not work.

### Issue 3.
After randomly selecting a 'skin color', if you move the mouse near Barbie, a cursor appears, but Ruffle does not display the cursor.

### Issue 4.
After selecting a 'skin color' randomly, clicking on Barbie's face should change her skin color, but Ruffle doesn't respond when clicked.
(In the same way, clicking all hair, eyes, lips and accessories does not work)

Tested from Ruffle 2022-05-14 Nightly

### Expected behavior

All of the above issues must be resolved.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 101

**Comment by Toad06** [comment]
It seems like #6945 fixed the issues you described. Could you please try the game with the last release to make sure I'm not missing something? Thank you. 😉

**Comment by Jmousy** [comment]
@Toad06 Wow, that's amazing!!
Checked in the 2022-05-18 Nightly build, all 4 issues have been resolved.
I haven't been able to check on a slightly more recent build.

Thanks for your help! I will close the issue.
