### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by grimmal72** [ruffle-rs/ruffle#6985]
# Error Info
Error name: Error
Error message: panicked at 'Bezier without endpoint', core/src/shape_utils.rs:213:36
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.3dd8f9eb98ec15e203ad.js:1:7496
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hc3464e04dbb9beda]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h07d0245bef259c27]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f701de063d4daa]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h623ac32ff431b114]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h5118e89563022e7e]@[wasm code]
<?>.wasm-function[core::option::expect_failed::h52436cb58dfe4ec3]@[wasm code]
<?>.wasm-function[<core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h170650d65b3abf1f]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ShapeConverter::flush_layer::hd4bafe8b75f480b9]@[wasm code]
<?>.wasm-function[<ruffle_core::shape_utils::DistilledShape as core::convert::From<&swf::types::Shape>>::from::he0fa8e676b06b56c]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::hd5fb2b9669403339]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h5231642a4025596f]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h0b35d1bc8903b38c]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h03255e28a0fa2806]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3f879241dadcf3ba]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hfed87d79c11977c9]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h322eb2dca09ff847]@[wasm code]
wasm-stub@[native code]
O@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.3dd8f9eb98ec15e203ad.js:1:3868
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.3dd8f9eb98ec15e203ad.js:1:2393
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1652537349%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F410000%2F410867_02final.swf%3F1195382031%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226280eef6844b7%22%2C%22NewgroundsAPI_SessionID%22%3A%221rkisOZzAgLFRYyFIVue165f1df8bb8f12454bc95fd562efb3395c3df257YW4i%22%2C%22NewgroundsAPI_UserName%22%3A%22GurenDraws%22%2C%22NewgroundsAPI_UserID%22%3A7931866%2C%22ng_username%22%3A%22GurenDraws%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%7D
SWF URL: https://uploads.ungrounded.net/410000/410867_02final.swf?1195382031

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-14
Channel: nightly
Built: 2022-05-14T00:17:29.589Z
Commit: a453aa73afbd8d8ab509bd7cbd2366a024ca8649
Is extension: false

**Comment by torokati44** [comment]
Closing in favor of #6608.
