### ISSUE TITLE
Error on https://www.topspeed.com/car-games/car-games/rocket-robin-by-topgear-ar91452.html

### ISSUE THREAD

**Issue by Rushia1195** [ruffle-rs/ruffle#6987]
# Error Info
Error name: TypeError
Error message: _.p._dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h49f5afc31c3c306b is not a function. (In '_.p._dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h49f5afc31c3c306b("www.", "pictures.")', '_.p._dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h49f5afc31c3c306b' is undefined)
Error stack:
```
@https://www.topspeed.com/flashgames/ruffle/core.ruffle.38963ecd862bea892b8e.js:1:37907
s@https://www.topspeed.com/flashgames/ruffle/ruffle.js:1:129
@https://www.topspeed.com/flashgames/ruffle/core.ruffle.38963ecd862bea892b8e.js:1:6032
asyncFunctionResume@[native code]
@https://www.topspeed.com/flashgames/ruffle/ruffle.js:1:4901
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://pictures.topspeed.com/IMG/swf/201006/rocket-robin.swf
Param allowScriptAccess: sameDomain
Param movie: https://pictures.topspeed.com/IMG/swf/201006/rocket-robin.swf
Param quality: high
Param bgcolor: #000000
Param scale: exactFit
Param wmode: direct
Param allowFullScreen: true
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.topspeed.com/car-games/car-games/rocket-robin-by-topgear-ar91452.html

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-01-17
Channel: nightly
Built: 2022-01-17T00:18:08.085Z
Commit: 059c1a34174a546521d1ebc32fd1411a079c2708
Is extension: false

**Comment by n0samu** [comment]
The error information seems to be missing. Closing
