### ISSUE TITLE
web: map is distorted, scroll bars enlarged

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#700]
A map with scroll bars is distorted and the scroll bars are enlarged.
Reset of zooming level is not working (but zooming is).

See http://www.webgeo.de/h_506_en/#2
(on http://www.webgeo.de you can switch between using ruffle or using flash)

![ruffle_h_506_en_2](https://user-images.githubusercontent.com/1667683/84249010-80f84b80-ab0a-11ea-9220-4d555e7f70c6.jpg)
![flash_h_506_en_2](https://user-images.githubusercontent.com/1667683/84249022-83f33c00-ab0a-11ea-985d-9bb6c9444e2c.jpg)
[h_506_swf.zip](https://github.com/ruffle-rs/ruffle/files/4757346/h_506_swf.zip)

**Comment by Herschel** [comment]
Thanks for the thorough bug reports!

This does a lot of calculation involving `_width` and `_height` which is possibly incorrect in some places in Ruffle.

**Comment by Herschel** [comment]
Looks like this is better now with Fixed by #1094.
