### ISSUE TITLE
avm1: Ruffle fails to enumerate properties in the attached sample

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#7016]
[Sample (SWF)](https://github.com/ruffle-rs/ruffle/files/8716637/sample.zip)

```
this.obj = {abc:"ABC", def:"DEF"};
for(e in "this.obj")
{
   trace(e);
}
```

Note that this is using `Action::Enumerate`. I don't know if `Action::Enumerate2` could also be affected.

---

Flash Player traces:
> abc
> def

Ruffle traces:
> Cannot enumerate properties of this.obj

---

Replacing `"this.obj"` with `"obj"` (still a string) fixes the issue in Ruffle (also works in Flash Player), so I suppose that `fn action_enumerate` also has to be able to resolve a path.

Found this issue while checking #6984 (this just affects the `trace`s).

**Comment by Herschel** [comment]
Probably the `self.resolve` call in `action_enumerate` needs to be a full `get_variable` instead, to allow it to handle paths.

@Toad06 Any interest in trying to fix this one?
