### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Zillania** [ruffle-rs/ruffle#7030]
# Error Info
Error name: Error
Error message: panicked at 'Bezier without endpoint', core/src/shape_utils.rs:213:36
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e040f6d42b8f321914a0.js:1:7641
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::he80a94c0f5d51ad9]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h07d0245bef259c27]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::hfd41d197921787cc]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h623ac32ff431b114]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h5118e89563022e7e]@[wasm code]
<?>.wasm-function[core::option::expect_failed::h52436cb58dfe4ec3]@[wasm code]
<?>.wasm-function[<core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::ha289bf4d35849f9c]@[wasm code]
<?>.wasm-function[ruffle_core::shape_utils::ShapeConverter::flush_layer::hdadb3f33bd97cc35]@[wasm code]
<?>.wasm-function[<ruffle_core::shape_utils::DistilledShape as core::convert::From<&swf::types::Shape>>::from::h427abdbc77945df7]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h68ee59fb8eeec44e]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h5c7056996572c073]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h36bbf56b4f13db2f]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1e94c8aec4373731]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h702ae63b0e8ff801]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h199c3e91f8398c24]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfc0231fcf2f16fab]@[wasm code]
wasm-stub@[native code]
L@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e040f6d42b8f321914a0.js:1:3966
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.e040f6d42b8f321914a0.js:1:2491
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1652894223%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F638000%2F638811_alien-abduction-x.swf%3F1399414713%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%226286f1a4a214e%22%2C%22NewgroundsAPI_SessionID%22%3A%22S9XGfuVB8NYfndPiNeng290578fa49a2d37a4bd4f540a3640855eb5c5327QMBO%22%2C%22NewgroundsAPI_UserName%22%3A%22Zillania%22%2C%22NewgroundsAPI_UserID%22%3A11057770%2C%22ng_username%22%3A%22Zillania%22%7D%2C%22width%22%3A910%2C%22height%22%3A512%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%7D
SWF URL: https://uploads.ungrounded.net/638000/638811_alien-abduction-x.swf?1399414713

# Browser Info
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
OS: iPhone

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-05-18
Channel: nightly
Built: 2022-05-18T00:14:23.914Z
Commit: 135833e4000168efe291bca926f718eedc0069bb
Is extension: false

**Comment by n0samu** [comment]
This is a bug in iOS 15.4. Updating your phone to the latest iOS version should fix it!

**Comment by Toad06** [comment]
Closing as per above comment. Thanks for reporting.
