### ISSUE TITLE
 Babes and snuggles: Background Heart did not display.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7034]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/169525489-0755b453-29c6-41c7-a565-00c7f5ebba33.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/75534590/169527049-c64ad406-ba2f-47f4-974b-40a851e3c072.png)
SWF: https://www.pouet.net/prod.php?which=66254

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome 101.0.4951.67

**Comment by n0samu** [comment]
I don't have any insight into this bug but I've attached the SWF here to make things easier for the devs!
[babesandsnuggles.zip](https://github.com/ruffle-rs/ruffle/files/8742008/babesandsnuggles.zip)

**Comment by torokati44** [comment]
Just by a quick look at the screenshots, my guess is that this too is due to the missing blend modes, so cc: #58.
