### ISSUE TITLE
Can not use Learn to fly 3 on gameflare

### ISSUE THREAD

**Issue by ImRenty** [ruffle-rs/ruffle#7067]
### Describe the bug

https://www.gameflare.com/online-game/learn-to-fly-3/

### Expected behavior

When i try starting the game it just flashes white and back to the screen and can not do anything not even play the game 

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft edge

**Comment by n0samu** [comment]
This content uses ActionScript 3 which is not yet supported by Ruffle. See the [FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content).

**Comment by n0samu** [comment]
The current error is: 
`Error occured when running AVM2 frame script: RustError("Cannot access property ::NIL of null or undefined")`

**Comment by Lord-McSweeney** [comment]
`Got AVM2 error RustError("Resolved parameter type org.osflash.signals::SlotList is unresolvable, not a class, null, or undefined")` seems to be the main issue; it also blocks Bloons TD 5.

**Comment by MartySVK** [comment]
Current error is:
``
VerifyError: Trait concat in class ColorMatrix has same name as trait concat in class Array, but does not override it
``

**Comment by n0samu** [comment]
The original issue was fixed, although the game still isn't playable. Closing in favor of #10552.
