### ISSUE TITLE
Ninja Painter: Some sound effects don't play in desktop app

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#7070]
### Describe the bug

SWF URL: http://i.notdoppler.com/files/ninjapainter.swf
When I play this game in the Ruffle desktop app, mousing over and clicking menu options doesn't play the associated sound effects. (Tested on Windows.)

### Expected behavior

When mousing over and clicking menu options, sound effects should play. The sound effects play correctly in web builds of Ruffle.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Herschel** [comment]
minimp3 fails to decode this sound for some unknown reason.
