### ISSUE TITLE
Mission in Snowdriftland: Won't Load.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7088]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/170326441-ab9e5443-b913-4f3b-8f2b-f80ed01273ee.png)

### Expected behavior

It should be loaded like this.
![image](https://user-images.githubusercontent.com/75534590/170326678-c901b103-3971-4c23-9d97-954b16b7b45a.png)
(https://archive.org/details/mission-in-snowdriftland_202104)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome 101.0.4951.67

**Comment by gamer191** [comment]
Most likely fixed in https://github.com/ruffle-rs/ruffle/pull/10281
