### ISSUE TITLE
AVM2: Mouse pointer leaving the window/canvas not handled properly

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#7113]
For example with https://z0r.de/L/z0r-de_7223.swf, when moving the mouse out of the window/canvas, the text on the top should always disappear.
However, if I move the mouse quickly, the text stays on. This does not happen with Flash Player.
Both the desktop application (tested on Linux/Wayland) and the web build (tested on the demo page in Firefox) are affected.
Just make sure not to do it on an edge with any black letterboxing, as that makes it work properly.

**Comment by Diatonator** [comment]
https://z0r.de/6109 same problem
