### ISSUE TITLE
stickpage.com

### ISSUE THREAD

**Issue by TheKnarf** [ruffle-rs/ruffle#713]
I just tested out the ruffle chrome plugin and it seems to work for a lot of old flash animations which was fun. I was also pleasantly surprised to learn that [stickpage.com](http://www.stickpage.com/stickfigures.shtml) was still alive.

Testing out some different animations on that site shows that there's both a lot of stuff working but also a lot of stuff not working with ruffle, so I think that could be an interesting test case for ruffle to test these old animations.

**Comment by Herschel** [comment]
If you could post links to specific instances that are not working correctly, it'd be helpful! Thanks!

**Comment by HomestarRunnerBackup** [comment]
The game Super Mario 63 does not work properly. After the opening cutscene, it just goes to black.
[https://sites.google.com/site/faveflashgames/supermario63.swf](url)

**Comment by Herschel** [comment]
Closing; separate issues can be made if there are problems with specific movies.
