### ISSUE TITLE
[Spongebob Squarepants: Patty Panic] Unable to enter Stage 2

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7155]
### Describe the bug

[PattyPanic.zip](https://github.com/ruffle-rs/ruffle/files/8836928/PattyPanic.zip)

In **Spongebob Squarepants: Patty Panic**, After clearing stage 1, stage 2 does not start. It stays still as in the picture below and doesn't go any further.

(Checked from Ruffle 2022-06-01 Nightly)

![image](https://user-images.githubusercontent.com/75052171/171978700-ede711e7-b643-4a53-b718-d70ccd582c7d.png)
![image](https://user-images.githubusercontent.com/75052171/171978986-384a036a-6f34-4eed-be7b-b2b6b5b23c6a.png)

### Expected behavior

Stage 2 should start normally.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 102

**Comment by relrelb** [comment]
This will probably be fixed by #5492.

**Comment by Jmousy** [comment]
Fixed by #9442, so I'm closing the issue. 😆
