### ISSUE TITLE
[Breakdown at Santaland] Pipe puzzle doesn't progress when clicked

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7170]
### Describe the bug

In **Breakdown at Santaland**, the pipe puzzle doesn't work.

[Breakdown at Santaland.zip](https://github.com/ruffle-rs/ruffle/files/8842854/Breakdown.at.Santaland.zip)

Comparing the two videos below, in Ruffle (checked in Nightly 2022-06-05), if you click on any part, the sound effect is output, but the part does not move.

Based on the screen displayed in Adobe Flash Player, even if you progress through the puzzles in the order of 33-11-777-88-55, it seems that you cannot proceed to the next, so this is not likely to be a graphic display problem. (maybe)

### Adobe Flash Player

https://user-images.githubusercontent.com/75052171/172122133-ac1b50aa-17a2-4f2d-8f72-0cd271a33d66.mp4

### Ruffle Nightly 2022-06-05

https://user-images.githubusercontent.com/75052171/172122151-dfcbcd14-b250-441e-96fd-d5340385e868.mp4

### Expected behavior

The puzzle should proceed normally

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 102

**Comment by Toad06** [comment]
Thanks for the report.

I think this is the same issue as #1108: the fact that the mouse cursor changes from the pointer to the default one when the mouse button is down on a pipe is a good indicator (the button is deleted, which shouldn't happen).

It's still possible to interact with the pipes in the current build but you have to be super fast (clicking and releasing immediately)... Well, that's a challenge. 😄

**Comment by michiel2005** [comment]
At the newest built there is a new bug were the pieces of the card in the first puzzle are disappearing when clicked on them.

**Comment by michiel2005** [comment]
The bug I reported two days ago is gone, that is great. But I found that when clicking on the maze pieces the releaseOutside is being called in Ruffle even when the mouse gets up inside the button. I don't know if this is the right behaviour but I found it very strange.

**Comment by n0samu** [comment]
Fixed by #10862
