### ISSUE TITLE
When can actionscript3 be supported???

### ISSUE THREAD

**Issue by wangyang12611** [ruffle-rs/ruffle#7192]
When can actionscript3 be supported??
My program reported an error ：ruffle_web.js:1275 AVM2 error: Property does not exist: Multiname { ns: [Package("mx.core")], name: Some("SpriteAsset"), params: [] }

**Comment by p0008874** [comment]
Is doing now, But very long.
See: https://github.com/ruffle-rs/ruffle/wiki/Roadmap

**Comment by sodscg** [comment]
Ruffle's discord has a handy FAQ for questions like this.

"I get a message saying that "This content is not yet supported by Ruffle".  Currently Ruffle only supports games written in ActionScript 1 and 2. This includes all games before 2006 and only some games released later.  When will Actionscript 3 games work?  There is no single release date. Development is in progress, and as it progresses, simple content will start working first, while more complex content will follow later. However, as of right now (January 2022),  any kind of support will take at least several months to develop."

"If you’re wondering why ActionScript 3 support is taking a long time to develop, see https://github.com/ruffle-rs/ruffle/issues/4537#issuecomment-870982834 for an in-depth explanation."

**Comment by n0samu** [comment]
Closing in favor of #1368
