### ISSUE TITLE
Error on https://collegesexgames.com/play.php?flash=window-girl

### ISSUE THREAD

**Issue by fuyuusagi** [ruffle-rs/ruffle#7213]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://collegesexgames.com/ruffle/ruffle.js:1:68321
    at Array.forEach (<anonymous>)
    at yi.f.wasm (https://collegesexgames.com/ruffle/ruffle.js:1:67974)
    at https://collegesexgames.com/ruffle/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at yi.e (https://collegesexgames.com/ruffle/ruffle.js:1:35865)
    at o (https://collegesexgames.com/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://collegesexgames.com/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://collegesexgames.com/play.php?flash=window-girl

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by n0samu** [comment]
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-i-always-get-a-something-went-wrong-error).
