### ISSUE TITLE
Error on https://xgame.pro/angry_birds/28771-zlaya-kartoshka.html

### ISSUE THREAD

**Issue by TOTORUS887** [ruffle-rs/ruffle#7219]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at <anonymous>:3:31873
    at r (<anonymous>:3:32235)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://xgame.pro/angry_birds/28771-zlaya-kartoshka.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by n0samu** [comment]
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-i-always-get-a-something-went-wrong-error).
