### ISSUE TITLE
Linux Desktop Nightly: Hard dependency on libss1.1 due to build environment

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#7222]
### Describe the bug

Trying to run the 6/14/22 Linux desktop build, failing to load a library file:
ruffle: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

Looking into the directory structure, it appears with the libssl3 installation that ships with Ubuntu 22, these files indeed no longer exist:

```
/usr/lib/i386-linux-gnu/libssl.so.3
/usr/lib/i386-linux-gnu/libcrypto.so.3
/usr/lib/x86_64-linux-gnu/libcrypto.so
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/lib/x86_64-linux-gnu/libcrypto.so.3
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.3
/usr/lib/x86_64-linux-gnu/libssl.a
```

Thanks to @Aaron1011  for checking this:
```
cargo tree -i openssl-sys
openssl-sys v0.9.72
├── curl v0.4.43
│   └── isahc v1.7.2
│       └── ruffle_desktop v0.1.0 (/home/aaron/repos/ruffle/desktop)
└── curl-sys v0.4.55+curl-7.83.1
    ├── curl v0.4.43 (*)
    └── isahc v1.7.2 (*)
```

### Expected behavior

Ruffle desktop should run.

### Affected platform

Desktop app

### Operating system

Ubuntu 22.04 LTS 64-Bit

**Comment by sombraguerrero** [comment]
I've confirmed my suspicion. Reinstalling libssl1.1 from the impish repository gets the desktop application running again. I realize the Linux desktop app is very low priority in the scheme of things, but we'll need to be aware that it will be broken going forward on any distro that ships with libssl3, until such a time, presumably, that whatever crate we're using for CURL updates.

**Comment by sombraguerrero** [comment]
To complicate this mystery further, I did uninstalled libssl1.1, confirmed Ruffle once again errored out.
I then wrote a simple test program for isahc using their boiler plate code, and pulled the latest crate. This worked without any issue, and since my test and Ruffle are both using version 1.7.2 of that crate, perhaps the desktop app's dependency on libssl1.1 is elsewhere.

**Comment by sombraguerrero** [comment]
@n0samu has pointed out that the nightly builds are currently building on Ubuntu 20.04. libssl3 is the new default as of 22.04, and so when I build from source, everything works because everything is linking to current, bleeding edge libraries. I don't know that 22 has enough adopters yet to justify upgrading our build environment, but we should give some thought to whether or not there's anything we can do with dynamic linkage.

**Comment by sombraguerrero** [comment]
In the meantime, to summarize, the workaround for this is either to build the desktop app from source on 22.04+ or, the security repo from impish (or any other previous version of Ubuntu) can be added to reinstall libssl1.1
`deb http://security.ubuntu.com/ubuntu impish-security main `

**Comment by torokati44** [comment]
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

"Otherwise, our recommendation is to use `ubuntu-latest`, which currently utilizes Ubuntu 20.04 but will begin running on Ubuntu 22.04 in the near future. "

Is there any reason not to explicitly use `ubuntu-22.04` for the time being?
