### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Jeepwrangler12** [ruffle-rs/ruffle#7233]
# Error Info
Error name: Error
Error message: panicked at 'index out of bounds: the len is 4 but the index is 6', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.17.10/src/fill.rs:226:25
Error stack:
```
@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.68383aefdedeb84412e8.js:1:7033
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::hf4bd8358d66e2cc8]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::h8a142b2dcc139875]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ffe884207fb3c6a]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::he2a025723e105e28]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::hb02133958c1e7d35]@[wasm code]
<?>.wasm-function[core::panicking::panic_bounds_check::heb9b88ec73713bda]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::process_events::h864bd97e6f2f97bf]@[wasm code]
<?>.wasm-function[lyon_tessellation::fill::FillTessellator::tessellate_impl::h225feadf8e24f602]@[wasm code]
<?>.wasm-function[ruffle_render_webgl::WebGlRenderBackend::register_shape_internal::hda4ccf5cbc3b9011]@[wasm code]
<?>.wasm-function[<ruffle_render_webgl::WebGlRenderBackend as ruffle_core::backend::render::RenderBackend>::register_shape::h7f676faab9748aa6]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClipData::define_shape::h6e2fe51c4a3c402e]@[wasm code]
<?>.wasm-function[ruffle_core::display_object::movie_clip::MovieClip::preload::h6b974869722ac88b]@[wasm code]
<?>.wasm-function[ruffle_core::player::Player::set_root_movie::h6ec3e7d680e43794]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd08c74454eb5adb6]@[wasm code]
<?>.wasm-function[<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h09ea3a130fe9d3c0]@[wasm code]
<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hecbd40711c9dbe6f]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hd96d956c8ead6a7f]@[wasm code]
wasm-stub@[native code]
L@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.68383aefdedeb84412e8.js:1:3966
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.68383aefdedeb84412e8.js:1:2491
promiseReactionJob@[native code]
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.66&useloader=1&browsermode=mobile&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1654782845%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F698000%2F698063_bayonetta-rodin-dirty.swf%3F1503014991%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2262aabe0c18cf3%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A900%2C%22height%22%3A800%2C%22icon%22%3A%22https%3A%2F%2Fimg.ngfiles.com%2Fdefaults%2Ficon-portal-xl-a.gif%3Ff1601395813%22%7D
SWF URL: https://uploads.ungrounded.net/698000/698063_bayonetta-rodin-dirty.swf?1503014991

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-06-09
Channel: nightly
Built: 2022-06-09T00:14:19.246Z
Commit: dde21a2a606c479e96b454e9eba54084ae173b85
Is extension: false

**Comment by torokati44** [comment]
This is a bug in Safari included in iOS 15.4. Please update to iOS 15.5 and it will be fixed. See: #6608
