### ISSUE TITLE
Capoeira Fighter 3 Ultimate World Tournament:  Some character did not display property + Survival Crash

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7238]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/174061971-8af9ff25-a5c8-4dce-8ffa-b8ef8df4814a.png)

Survival Crash
```
[2022-06-16T11:17:47Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    not enough memory left

', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.12.0\src\backend\direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

![image](https://user-images.githubusercontent.com/75534590/174063402-3735037d-08bd-4702-b395-70bdcf39738a.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

swf file: https://files.catbox.moe/pp5a1v.zip

**Comment by n0samu** [comment]
Since I don't trust that link to stay up, I've mirrored the file here: https://drive.google.com/file/d/1bwKhp9iCUY3Fj-lERhwziz8AV5-GPvVJ/view?usp=sharing
Other than that, I have nothing to add
