### ISSUE TITLE
Fatal error while compiling Arm64

### ISSUE THREAD

**Issue by coreybruce** [ruffle-rs/ruffle#7251]
### Describe the bug

Compiling for Arm64 and ran into this fatal error

```
Fatal error:
Input path is not a file and could not be parsed as a URL.
Error: "Input path is not a file and could not be parsed as a URL."
```
Here is the full log: https://gist.github.com/coreybruce/cfc13e9be61e600645650a509dd5a5cb

### Expected behavior

Completes compiling

### Affected platform

Desktop app

### Operating system

Manjaro Arm64

**Comment by Aaron1011** [comment]
Since you're running that command in a fresh clone of Ruffle, there won't be any `test.swf` in the root of the repository. Try an absolute path to the file you're trying to run.

**Comment by coreybruce** [comment]
Oh alright and do I even need to point it to a swf file when compiling and how do I just compile it into a executable?

**Comment by torokati44** [comment]
Use the `build` command instead of `run`.
And AFAIK the `ruffle_desktop` package is the default anyway.
So all you should really need is:
`cargo build`
Or, to avoid the dramatic performance cost of debug build, this should be better:
`cargo build --release`

**Comment by coreybruce** [comment]
ok I have done cargo build release but where is the compiled binary?

**Comment by coreybruce** [comment]
Should add that to the readme for people who wish to just compile it.

Thanks for the help. 👍

**Comment by n0samu** [comment]
Updated build instructions as part of #7264
