### ISSUE TITLE
web: Add configuration option for text field focus callback

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#7277]
**Describe the feature**
Currently, Ruffle's text input support is extremely lacking - the soft keyboard does not pop up on mobile, non-English IMEs are not supported, text selection and copying/pasting does not work, etc. But as Mike explained in #6952, keyboard events can be manually passed to Ruffle using JavaScript. Web developers could use a library like [simple-keyboard](https://github.com/hodgef/simple-keyboard/) to [show/hide a JS soft keyboard](https://hodgef.com/simple-keyboard/questions-answers/implement-show-hide-toggling/). The one thing missing is a callback feature in Ruffle that calls a specified JavaScript function whenever a text field is focused. With this feature, text input on mobile would finally be possible!

**Comment by kmeisthax** [comment]
I don't see why not. It wouldn't fix the IME problem but we'd at least have something for mobile users.

At some point though, if we *did* have a more robust solution somehow, how would we handle compatibility with developers that implemented their own soft-keyboards? Should we treat the focus callback existing as also overriding any other future text field functionality?

**Comment by n0samu** [comment]
Mobile text input was implemented in #9461. Closing this issue since there's not much need for this feature anymore.
