### ISSUE TITLE
Swords and sandals 2 range weapons bug

### ISSUE THREAD

**Issue by adamcakg** [ruffle-rs/ruffle#7316]
### Describe the bug

There is a problem in swords and sandals 2 game when enemy is using range weapons (Bow or something like that).
When the projectile hits the main character, the instant death is comming.

### Expected behavior

Expected behaviour is that the projectile will do only some damage.

### Affected platform

Online demo

### Operating system

mac os Catalina (Macbook pro M1)

### Browser

Google chrome latest, Safari latest, Opera latest

**Comment by dginovker** [comment]
Working link to the game: https://games.crazygames.com/en_US/swords-and-sandals-2/index.html

Bug works with slingshot too (can get the slingshot earlier in the game than the bow)

**Comment by OIBG98** [comment]
It happens to me too did you manage to fix it??

**Comment by dginovker** [comment]
Looks like it's been fixed at some point. Ticket can be closed :tada:
