### ISSUE TITLE
Learn To Fly 2 Missing Outline For Text On Title Screen + Character Doesn't Move During Gameplay

### ISSUE THREAD

**Issue by DemApplez** [ruffle-rs/ruffle#7333]
### Describe the bug

[secure_Learn2Fly.zip](https://github.com/ruffle-rs/ruffle/files/9031961/secure_Learn2Fly.zip)
This specific game has 2 issues that if they were fixed, would have the game 100% working

1: On the title screen, the text that says "New Game", "Load Game", etc, all have missing outlines on them.

2: The first issue isn't really a big deal and honestly if that was the only issue, I wouldn't have made this. But the second issue happens right as soon as you play the game. The character will get stuck and move upwards forever.

### Expected behavior

1: There should be an outline surrounding the text on the main title screen
![image](https://user-images.githubusercontent.com/50384803/176977407-c3194087-b1a5-489c-95ae-02aea748d396.png)
But ends up looking like this
![image](https://user-images.githubusercontent.com/50384803/176977530-0eb7829b-72a2-4710-bb1f-83d781352b0f.png)

2: The character should be able to move like this
![image](https://user-images.githubusercontent.com/50384803/176977442-6b768bf6-b252-44cb-abb4-f82f2bb08f32.png)
But instead does this
![image](https://user-images.githubusercontent.com/50384803/176977578-ae19218d-1a5f-41da-9d33-90b67990e3b5.png)
![image](https://user-images.githubusercontent.com/50384803/176977652-584e0ecf-64f4-437e-9ba4-8a34f2ada16e.png)

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Microsoft Edge Version 103.0.1264.37

**Comment by n0samu** [comment]
The first issue occurs because of missing filter effects, see #15.
The second issue was already reported in #1839.
