### ISSUE TITLE
Ruffle Not Able To Submit Scores for Neopets Games

### ISSUE THREAD

**Issue by johnsone006** [ruffle-rs/ruffle#7337]
### Describe the bug

Steps to reproduce:
1. Enable Ruffle extension
2.  Play any game not on the flash free list on this page: https://www.jellyneo.net/?go=links (suggestion: Word Pyramid, Faerie Quest 2: Fyora's Quest, or Beach Volleyball
3. Click submit score
4. View the screen that shows up and look at the errors in the console.
Some games, such as Word Pyramid, have an extra bug that replaces the score you get with the word Infinity. Also, that game will say that you get 0 Neopoints (in game currency) no matter what score you get. 
Others will not, but still won't send the score. 

### Expected behavior

When you hit submit score, a black box should appear with the score you got, the number of neopoints you received, and below that should be a link that lets you restart the game. 

### Affected platform

Browser's extension

### Operating system

Linux Ubuntu x64 on a virtual machine. Program is Virtualbox

### Browser

Opera

### Additional information

See ruffle development of disord server for screenshots.

**Comment by n0samu** [comment]
A Neopets account is required to test this. I made a burner account for this and can provide the login details if someone needs it.
I tested the issue with [Snowmuncher](http://www.neopets.com/games/game.phtml?game_id=412), which calculates the score correctly, but does not submit the score correctly.
When running the game in Ruffle, it makes repeated requests to www.neopets.com/games/play_flash.phtml, along with a bunch of URL parameters. This does not occur when running the game in Flash Player. 
When a score is submitted, some data is sent to `www.neopets.com/high_scores/process_flash_score.phtml`. The same data is sent by both Ruffle and Flash Player, but the server response to Ruffle is different.

On Discord, @johnsone006 linked me a [https://gist.github.com/juvian/a50bc06aad0f7f5910f950003feee1f8](userscript) that fixes this issue. The userscript only works in Chromium-based browsers with the Tampermonkey extension. For me it shows an error message when installing, but it still works. It blocks fetch/XHR requests to neopets.com/games/play_flash.phtml , thus preventing Ruffle's repeated requests. With the userscript enabled, scores no longer fail to submit, which tells me that those repeated requests are what cause Neopets to reject the score as invalid. 

Here are the traces from Ruffle from immediately before the repeated requests: 
```
NP8 GAMING SYSTEM (_level100.include): Scoring System: Created!
NP8 GAMING SYSTEM (_level100.include): NeoStatus: Created!
Cannot enumerate Undefined (repeated 111 times)
NP8 BIOS: Loading Translation: http://www.neopets.com/transcontent/gettranslationxml.phtml
```
And immediately after:
```
NP8 BIOS: Starting Game...
Unhandled FSCommand: trapallkeys
```

The issue with Word Pyramid showing a score of Infinity is most likely separate from this issue, I suggest creating a new issue for that.
