### ISSUE TITLE
All components became messy with 06-30-22 version

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ruffle-rs/ruffle#7338]
### Describe the bug

since the version of June 30th, all components (Buttons, Tree, Scrollpane etc...) shows messy, upside down, impossible to use.

### Expected behavior

go back to version june 29th and everything shows ok but the Button component icon disappearing on rollout

### Affected platform

Self-hosted version

### Operating system

ALL

### Browser

ALL

**Comment by Jmousy** [comment]
Can you attach the flash file you're having trouble with or leave a link to it? Or a screenshot might be helpful.

**Comment by ROBERT-MCDOWELL** [comment]
I sent all to Aaron on discord... he can share it with you as I don't want to share it publicly

**Comment by ROBERT-MCDOWELL** [comment]
you can also just create an AS2 project with a Button component and see by yourself.

**Comment by Herschel** [comment]
Looks like this regressed in c7bf11ece.

**Comment by n0samu** [comment]
The issue occurs on https://secure.boophone.com/ . This particular content is extremely difficult to test and debug, so if you can create a small SWF demonstrating the issue and attach it here that would be very helpful

**Comment by Herschel** [comment]
[test_button.zip](https://github.com/ruffle-rs/ruffle/files/9033955/test_button.zip)
Here's an SWF with using the Button component.

**Comment by n0samu** [comment]
Sorry Mike, I didn't mean to make you do unnecessary work, I just didn't realize we even had a way to reproduce this issue yet

**Comment by ROBERT-MCDOWELL** [comment]
Thanks Mike! will test it as soon as the version at unpkg will be updated
