### ISSUE TITLE
Enemy stickmen no longer appear in game - Revenge of the Stickmen TD game

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#7343]
### Describe the bug

In each level the stickmen previously jumped out of the computer screen and were shot out by defenders placed by the player. I have not tested the game in a while, but it appears that they have disappeared entirely in a recent update

http://www.freeworldgroup.com/games6/gameindex/revenge-of-the-stick.htm

### Expected behavior

Stickmen are meant to jump out of the computer screen and be shot at but defenders. 

http://www.freeworldgroup.com/games6/gameindex/revenge-of-the-stick.htm

### Affected platform

Self-hosted version

### Operating system

WIndows 11

### Browser

Chrome browser Version 103.0.5060.66 (Official Build) (64-bit)

### Additional information

Hope someone will look at this!

**Comment by n0samu** [comment]
This has been fixed in today's Ruffle update! (Probably by #7339).
