### ISSUE TITLE
Error on https://be.madwin.com/fr-BE/games/free-games/game-launch.asp?jeu_id=174&joy=1&jeu_mode=0

### ISSUE THREAD

**Issue by BRICHAU** [ruffle-rs/ruffle#7372]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:211:298
    at Array.forEach (<anonymous>)
    at Si.f.wasm (https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:210:30315)
    at https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:203:192
    at Array.reduce (<anonymous>)
    at Si.e (https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:203:169)
    at o (https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:12:16)
    at o.next (<anonymous>)
    at https://be.madwin.com/fr-BE/ruffle-test2/ruffle.js?v=16:17:24
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: /games/free-games/sherlockghost/swf/sherlockghost-5-gratuit-c.swf?v=4-1619507
Param wmode: transparent
Param quality: high
Param allowscriptaccess: sameDomain
Param menu: false
Param flashvars: cle=A77169453F8sDmlpu&pub_ok=0
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://be.madwin.com/fr-BE/games/free-games/game-launch.asp?jeu_id=174&joy=1&jeu_mode=0

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36 Edg/104.0.1293.14
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-16
Channel: nightly
Built: 2021-01-16T16:40:10.699Z
Commit: unknown

**Comment by danielhjacobs** [comment]
Ruffle requires WebAssembly, which is disabled by Microsoft Edge's "Enhance your security on the web" feature. Please consider adding this site to your Exception Site List. See [this FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-i-always-get-a-something-went-wrong-error).

**Comment by Toad06** [comment]
Closing as per above comment.
