### ISSUE TITLE
Duck Life 1 - Every Duck is yellow and left thing is orange

### ISSUE THREAD

**Issue by LegacyAladdin** [ruffle-rs/ruffle#7375]
### Describe the bug

The issue is visual.

![image](https://user-images.githubusercontent.com/108961061/178082759-19628710-fe30-41d7-86c6-3b3286fa9e84.png)
![image](https://user-images.githubusercontent.com/108961061/178082737-bbf898ba-fce8-406f-8dce-4b5f0353de19.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/108961061/178082999-4aeb2aa2-3a49-4c4e-a37e-a87bac456aa2.png)
![image](https://user-images.githubusercontent.com/108961061/178083091-51c9f1ce-c8da-4c0c-9b9e-b60eea76bec1.png)

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

No Log is needed since it's obviously easily to see the issue.

**Comment by Aaron1011** [comment]
@TheAmazingAladdin Can you provide a link to the SWF?

**Comment by waspennator** [comment]
Not him, but i found a site hosting the flash version here.
https://flasharch.com/en/archive/play/4390bffe189a3fdac4e62b4b6b414397

Running nightly 2022-07-08 and can confirm all opposing ducks during races show up as yellow and the skill seed is the same color as the regular seed too instead of being blue.

**Comment by Lord-McSweeney** [comment]
Here's the direct SWF link: https://cdn.flasharch.com/uploads/archived/2020/10/17/aeed718237deaab03c3b02253dd5d439_20201017125820.swf

**Comment by Lord-McSweeney** [comment]
Fixed, but also regressed on mobile by #11702 (see #11738).
