### ISSUE TITLE
WTF is taking so long?!

### ISSUE THREAD

**Issue by TurkPasha** [ruffle-rs/ruffle#7385]
It has been weeks and Ruffle progress is still stuck at 85% and 50% for Actionscript 1 and 2.

Come on people, have you are starting to get really slow.

**Comment by EmperorBale** [comment]
That number is not accurate, as explained by Daniel Jacobs on discord:
```
Because the numbers were made up and arbitrary to begin with, 
and no one knows how to accurately represent arbitrary changes to arbitrary numbers. 
Progress is being made and IMO unless we can determine a quantitative measure of progress those bars 
will continue doing more harm than good.

While it's still not 100% accurate since for Ruffle it considers any amount of API support to be full support, 
this unofficial site is an infinitely better measure of progress for AVM2: https://huwdp.github.io/Flash-Matrix/
```

Another way of checking progress is to see all the new commits in [here](https://github.com/ruffle-rs/ruffle/commits/master)

**Comment by TurkPasha** [comment]
Well, then fuck these people for giving false numbers.

**Comment by torokati44** [comment]
Any meaningful contribution to help advance the project is welcome.
Even from you.
