### ISSUE TITLE
[Manic Rider] An unexpected earthquake occurs on the stage.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7388]
### Describe the bug

When i start stage 1 in **'Manic Rider'**, the terrain is unsteady and wobbles up and down.

Sometimes it gets fixed, but then again when I move it to steer the bike the problem arises again.

[Manic Rider.zip](https://github.com/ruffle-rs/ruffle/files/9078551/Manic.Rider.zip)

## ✔ Adobe Flash Player (Original)

https://user-images.githubusercontent.com/75052171/178133680-de3109a0-8ac7-498a-bf2e-bbf6e9dc33af.mp4

## ‼ Ruffle Nightly 2022-07-07

https://user-images.githubusercontent.com/75052171/178133707-11dba6da-19e2-4383-bc67-743075cd9bce.mp4

### Expected behavior

The terrain must be properly anchored.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 103

**Comment by relrelb** [comment]
Fixed by #7934.
