### ISSUE TITLE
[InuYasha Demon Tournament SE] Stuck at 20% loading after card selection and unable to proceed

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7389]
### Describe the bug

![image](https://user-images.githubusercontent.com/75052171/178135150-b487fe90-bbc0-47e7-bf61-e5954e339bec.png)

In **'InuYasha Demon Tournament Special Edition'**, after selecting a character's motion, I get stuck at the loading screen at 20% and can't proceed with the game anymore.

(Checked at Ruffle Nightly 2022-07-07)

The video below shows how to reproduce it:

**Note**: This game does not start immediately upon launch. You must click 'Play' in the Ruffle context menu to start the game.

https://user-images.githubusercontent.com/75052171/178135276-e2cdef25-c968-4a32-9f83-8a9513d6fab2.mp4

The attached file contains all data files. To run the game, just open `main.swf`.

[Inu.zip](https://github.com/ruffle-rs/ruffle/files/9078632/Inu.zip)

### Expected behavior

The loading screen should exit and the game should proceed normally.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 103

**Comment by sombraguerrero** [comment]
JPEXS does note on load that this SWF is trying to import assets from another SWF, so I would bet those assets or perhaps the entire SWF itself no longer exist. If they do, then Ruffle is probably just struggling with it from the multi-SWF standpoint.

**Comment by n0samu** [comment]
All required SWF assets do exist, but Ruffle doesn't support importing assets via the ImportAssets/ImportAssets2 tags - see also #2365. Loading the game with the Ruffle extension, you'll see that it never requests the SWFs that should be loaded via the ImportAssets tags, while Flash Player does.

**Comment by olux997** [comment]
> All required SWF assets do exist, but Ruffle doesn't support importing assets via the ImportAssets/ImportAssets2 tags - see also #2365. Loading the game with the Ruffle extension, you'll see that it never requests the SWFs that should be loaded via the ImportAssets tags, while Flash Player does.

:
Can it be supported later? [ ImportAssets ]
Because This is a SWF flash 6.0 version very old game, and much game use this funtion.

**Comment by Jmousy** [comment]
In a recent build (I don't know exactly when, but I'm guessing May-June), this issue was fixed perfectly!

![image](https://github.com/ruffle-rs/ruffle/assets/75052171/05b1005d-2829-438d-b5f4-805e210c39ff)

So let's close this issue.
