### ISSUE TITLE
[Fish Tycoon] A large amount of 'memory access out of bounds' occurs during certain actions and the game freezes.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7390]
### Describe the bug

In **'Fish Tycoon'**, when I drag and drop food into the tank, the game freezes and the console log shows a memory error as shown below.

![memory](https://user-images.githubusercontent.com/75052171/178135858-571490f8-bc38-4ff2-beb0-b1c6c5f4a526.png)

Verified on Ruffle Nightly 2022-07-07.

[fish.zip](https://github.com/ruffle-rs/ruffle/files/9078670/fish.zip)

## How to reproduce
1. Start a new game.
2. Click and drag the food on the top with the mouse to drop it into the fish tank.

![image](https://user-images.githubusercontent.com/75052171/178135826-941aa58d-2306-4b4f-8e02-39ef28fac8b8.png)

### Expected behavior

The game should proceed normally without errors.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 103

**Comment by Diatonator** [comment]
I found another one with the similar symptoms: https://z0r.de/5566
![image](https://user-images.githubusercontent.com/75184268/188307828-3ed8f2ae-0745-4190-a855-ccb9d5eaf9ed.png)
This happens right at the startup here.
Nightly 2022-09-04, Chrome

**Comment by relrelb** [comment]
This probably caused due to cyclic references during `SharedObject` serialization. Currently `recursive_serialize` in `shared_object.rs` naively enters an infinite recursion loop. We'll need to handle such cases gracefully by using AMF0 Reference Types, which don't seem to be supported by `flash-lso` at the moment.
