### ISSUE TITLE
Drag and drop don't work as expected

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#7393]
### Describe the bug

Drag and drop don't work in the game. Actually drag is working, but you can not drop the item. I don't see any errors in console.

Game - https://www.gameflare.com/online-game/mutant-fighting-cup/
SWF - https://data.gameflare.com/games/3336/o2AessK30KrIss.swf

### Expected behavior

You can drop the item and it will stay in the box.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 103

**Comment by adrian17** [comment]
Hmm... FYI, I just launched the game in real FP and am also unable to drag the items. Are you sure you're supposed to be able to do that at the beginning? Or maybe it's a bug in the game itself?

**Comment by MartySVK** [comment]
> Hmm... FYI, I just launched the game in real FP and am also unable to drag the items. Are you sure you're supposed to be able to do that at the beginning? Or maybe it's a bug in the game itself?

I just tried it in Flash Player 32 and I can drop the item
