### ISSUE TITLE
The character falls down in first mission

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#7417]
### Describe the bug

The main character is falling out of the game screen in first mission. I don't see any errors in console.

Game - https://www.gameflare.com/online-game/commando-2/
SWF - https://data.gameflare.com/games/269/IQV11x6sv7Pp4Y.swf

### Expected behavior

Main character should jump on the ground.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 103

**Comment by mero09-99** [comment]
this is also an issue in shadow of the ninja

**Comment by Lord-McSweeney** [comment]
Fixed (probably by #9134).
