### ISSUE TITLE
Error on https://aola.100bt.com/play/play.html

### ISSUE THREAD

**Issue by Radium-bit** [ruffle-rs/ruffle#7468]
# Error Info
Error name: TypeError
Error message: r.data.payload.url is undefined
Error stack:
```
t.prototype.add@https://pub-static.100bt.com/pre-dem-web-v.js:1:137185
t.prototype.addSource/y<@https://pub-static.100bt.com/pre-dem-web-v.js:1:120195
t.prototype.action/<@https://pub-static.100bt.com/pre-dem-web-v.js:1:21414
t.prototype.action@https://pub-static.100bt.com/pre-dem-web-v.js:1:21387
n.default/</</</<@https://pub-static.100bt.com/pre-dem-web-v.js:1:142795

```

# Player Info
Allows script access: true
Player type: Object
SWF URL: start~2107300001.swf
Param movie: start~2107300001.swf
Param quality: high
Param bgcolor: #ffffff
Param scale: noborder
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://aola.100bt.com/play/play.html?site=www.google.com

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-24
Channel: nightly
Built: 2022-07-24T00:15:02.761Z
Commit: fc87a35572c0744b9cc0b24b005472c1b1aae996
Is extension: true

**Comment by n0samu** [comment]
It looks like a script on the website is interfering with the Ruffle extension. You can try clicking the Reload button while holding down the Shift key - that might allow the Ruffle extension to load early enough to avoid crashing. However, this content uses ActionScript 3 so it won't work properly, anyway.

**Comment by Radium-bit** [comment]
> It looks like a script on the website is interfering with the Ruffle extension. You can try clicking the Reload button while holding down the Shift key - that might allow the Ruffle extension to load early enough to avoid crashing. However, this content uses ActionScript 3 so it won't work properly, anyway.

So when will Ruffle support ActionScript 3?

**Comment by n0samu** [comment]
> So when will Ruffle support ActionScript 3?

[See the FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users).

**Comment by Radium-bit** [comment]
> 

Thankyou. Looking forward to your success.

**Comment by Radium-bit** [comment]
> > So when will Ruffle support ActionScript 3?
> [See the FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users).
Thankyou,looking forward to your success.
