### ISSUE TITLE
Mobile Web Demo Fullscreen issue with Sanguine 2

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#7486]
### Describe the bug

The game seems to load fine in Ruffle, but when going fullscreen, part of the screen is cut off.
![mcur](https://user-images.githubusercontent.com/102984201/180916011-6f23d6fb-2e96-4505-bacc-aeb900c46715.jpg)
the menu, near the bottom
![mcur2](https://user-images.githubusercontent.com/102984201/180916042-720e6595-3fc5-48cc-b0c9-568439cd5fe6.jpg)
gameplay appears to be okay, but has the same issue, you cannot see the health bars.
![mcur3](https://user-images.githubusercontent.com/102984201/180916121-2cf5c0a6-00ce-44ca-b3b3-d270970a7acc.jpg)
different orientation to show what the health bars look like

SWF file:
[sanguine2.zip](https://github.com/ruffle-rs/ruffle/files/9186279/sanguine2.zip)

### Expected behavior

Fullscreen should display the whole window

### Affected platform

Online demo

### Operating system

Android 10

### Browser

Mozilla Firefox

### Additional information

This might also be an issue on Desktop

**Comment by mero09-99** [comment]
This is also an issue with the synapsis puzzle games

**Comment by sodscg** [comment]
this seems fixed - I can't get this to happen anymore
I also tried the synapsis games and besides being unplayably laggy, it had no issues with the screen
