### ISSUE TITLE
Windows XP Tour: Wrong gotoAndPlay.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7488]
### Describe the bug

https://user-images.githubusercontent.com/75534590/181036022-c8cb8347-2513-431c-a367-4044e6d797db.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/181036084-461fec7d-a716-4ecd-98c4-8d73ed3305b2.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF File.
https://archive.org/details/WinXPTour

**Comment by torokati44** [comment]
I wonder if this is the same problem as https://github.com/ruffle-rs/ruffle/issues/6144...

**Comment by p0008874** [comment]
It sound's like it Fixed in nightly 2022-08-30
