### ISSUE TITLE
Wiki update to reflect project layout changes

### ISSUE THREAD

**Issue by WillBrindle** [ruffle-rs/ruffle#75]
https://github.com/ruffle-rs/ruffle/wiki/Project-Layout has not been updated to reflect change of swf-rs now being included as part of this project. Couldn't see a way to propose changes to the github wiki (not really used that feature before so I might just not be seeing it) so opening issue instead. Haven't looked at the crate itself to add more than the high level detail that was already there but just in case it's useful, quick proposed text changes below:

# Project Layout

 * [`core`](https://github.com/ruffle-rs/ruffle/tree/master/core): Core emulator code, shared among all platforms
 * [`swf`](https://github.com/ruffle-rs/ruffle/tree/master/swf): Crate to handle SWF and AS parsing
 * [`desktop`](https://github.com/ruffle-rs/ruffle/tree/master/desktop): Desktop frontend and backend code
 * [`web`](https://github.com/ruffle-rs/ruffle/tree/master/web): Web frontend and backend code
   * [`demo`](https://github.com/ruffle-rs/ruffle/tree/master/web/demo): The web demo page (served at https://ruffle.rs/demo)

## Core

The `core` directory contains the Flash Player emulation code. This is used on all platforms to parse and execute the SWF file. The [`Player`](https://github.com/ruffle-rs/ruffle/blob/master/core/src/player.rs) struct is the main entry point of the core code.

## SWF

The `swf` directory contains a library for handling the reading and writing of SWF files including ActionScript parsing code.

**Comment by Herschel** [comment]
Thanks! I also opened up the wiki to public edits.
