### ISSUE TITLE
Sound cuts off early

### ISSUE THREAD

**Issue by Sgeo** [ruffle-rs/ruffle#752]
On [3BB.bm.swf.zip](https://github.com/ruffle-rs/ruffle/files/4826708/3BB.bm.swf.zip), the buzzer sound for "wrong" when not answering the question cuts out early. It also doesn't play at all if you click the wrong answer (False).

**Comment by Herschel** [comment]
Seems like this only occurs on the web backend.

**Comment by manokara** [comment]
I remember something like that happening on the desktop backend, because of how `sample` dealt with clipping between release and debug targets. It used  `wrapping_add` on release IIRC, while debug had a normal add, making the audio thread panic. Maybe it's a similar problem?
