### ISSUE TITLE
Regression in z0r.de/1988 - sound became choppy 

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7524]
### Describe the bug

In Nightly 2022-07-31 the audio in z0r.de/1988 became choppy.
I believe this is the nightly build where this change came about (at least for the web extension): https://github.com/ruffle-rs/ruffle/pull/4273
And F12 spams with "Bad MP3" stuff:

![image](https://user-images.githubusercontent.com/75184268/182035091-d9cbae34-295b-42e7-8166-2e75d0b63e48.png)

### Expected behavior

A non-choppy audio.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 103.0.5060.134

**Comment by torokati44** [comment]
Most likely the Symphonia decoder now in use is more sensitive to this kind of data corruption.
After some investigation, should perhaps be reported upstream to them.

**Comment by Diatonator** [comment]
I also see a regression here, but more serious as the audio is completely silent:
https://z0r.de/3682
The error is different:
![image](https://user-images.githubusercontent.com/75184268/182037771-2d4cd142-83c1-448c-853b-9417429dc31a.png)

**Comment by Diatonator** [comment]
While traveling through z0r, I noticed a whole bunch of loops having "invalid main_data_begin" errors, but there are mostly few of those errors in the console per loop, and they don't affect the heard audio. z0r.de/1988 seems to be the only loop which gets crusted by those errors, and there is a whole lotta them in the console.

**Comment by torokati44** [comment]
Yes, https://z0r.de/3682 is mute due to a separate issue, I just submitted a fix to that.
Thanks for the testing!

**Comment by Diatonator** [comment]
Another one partly crusted by "invalid main_data_begin":
https://z0r.de/3114

**Comment by torokati44** [comment]
The sound of z0r.de/1988 and https://z0r.de/3114 is now choppy even on desktop, where Symphonia is not used yet.
So this _sounds_ like #3817 all over again... :/

**Comment by torokati44** [comment]
FWIW deleting just this line fixes the stuttering:
https://github.com/ruffle-rs/ruffle/blob/2ba82c92bc2f295d2a0269fa39feb574fc1fb183/core/src/backend/audio/decoders.rs#L329
In the problematic loops, `self.mp3_samples_buffered` is somehow negative from time to time, and it is for some reason not a problem unless we make it one...?

**Comment by Diatonator** [comment]
https://z0r.de/7637 also got crusted, but I see nothing in the console!
So maybe those "invalid main_data_begin" warnings are not that relevant?

**Comment by torokati44** [comment]
I _think_ I have a guess for the reason for the "underflow by ... bytes" errors.
If I understand this correctly, right now, there is some continuous synchronization going on between the frame rate of the animation relative to the wall clock time (to keep the pace), and the actual progress in processing of the audio and visual portions (decoding, rendering, playback, etc.) of the frames.
This _might_ cause the sync code to skip over a few frames, or _at least_ the feeding of `SoundStreamBlock` contents to the MP3 decoder - under the assumption that this is always fine, given how robust and resilient of a format MP3 is.

Except that in this case, the code where the error originates from: https://github.com/pdeljanov/Symphonia/blob/398dab0af6d349849642f40664511c407fa935a0/symphonia-bundle-mp3/src/common.rs#L408
... is part of a "reservoir" mechanism, that makes this work:

``` low-complexity portions of the audio may not need
/// every byte allocated to the frame. The bit resevoir mechanism allows these unused portions of
/// frames to be used by future frames```

Which means that _sometimes_ there actually _are_ dependencies between subsequent frames, and skipping the decoding of a frame (for synch. purposes, if the machine can't keep up the framerate) breaks this - which then breaks the frame which would re-use the bits in the reservoir, and this can then cascade endlessly.

This reservoir feature might, however, be used relatively rarely, which could by why there arent many more problems like this in Ruffle.
