### ISSUE TITLE
[regression] animation wrong displayed in full screen without hardware acceleration

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#7533]
### Describe the bug

In both Linux and Windows, when hardware acceleration isn’t available, the presentation contained in https://www.free-culture.tk/ is displayed in a totally wrong way:

![fes](https://user-images.githubusercontent.com/203767/181075674-c9abaae6-cfdf-4e4d-a971-1b18457217d0.png)

### Expected behavior

Compare it to the real page:

![fase](https://user-images.githubusercontent.com/203767/181077035-b9123dda-1334-4a72-affc-ef1e0c5cea45.png)

I cannot say when the regression was introduced, but this was displayed fine until recently (I think).

### Affected platform

Browser's extension

### Operating system

Linux

### Browser

Firefox 103

**Comment by n0samu** [comment]
Can confirm this issue:
![image](https://user-images.githubusercontent.com/71368227/182469672-d611ecb8-5057-47c2-bc3e-550f56ad18dc.png)

The screen appears blank most of the time because the text is somehow rendering mostly off-screen.

**Comment by n0samu** [comment]
Strangely, the issue does not occur on the Ruffle extension's internal player page. To figure out what the difference was, I tried disabling the CSS on your site, loading the extension copy of Ruffle into the page and removing the explicit width and height from your Flash embed. Yet the issue still occurs.

**Comment by ousia** [comment]
> Strangely, the issue does not occur on the Ruffle extension's internal player page.

Many thanks for your help, @n0samu.

Do you mean https://ruffle.rs/demo/?

If I drag and drop https://www.free-culture.tk/lfc-presentation.swf over https://ruffle.rs/demo/, once I enable fullscreen mode (pressing **f**), fullscreen image is distorted.

This is not as distorted as in https://www.free-culture.tk/, because the original frame in this case is much smaller.

And again, this only happens with hardware acceleration disabled.

Or the distortion may occur when fullscreen is disabled again (if animation in fullscreen was displayed fine).

For some strange reason, image seems not to be recalculated again when changing fullscreen and normal modes.

I would be very surprised if this were the only animation that displays the issue.

Many thanks for your help again.

**Comment by n0samu** [comment]
> Do you mean https://ruffle.rs/demo/?

No, I meant the Ruffle browser extension (I was using the Firefox extension). If you enable the browser extension and open the SWF URL directly, it will open in the extension's internal player page.

**Comment by ousia** [comment]
I think this regression may be a _Firefox_ issue drawing the frames.

I’m not on _Windows_ now, but Chrome seems not to have any issue displaying the presentation.

Thanks to [https://sourceforge.net/projects/portableapps/files/Mozilla Firefox Developer Portable/](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%20Developer%20Portable/), I was able to test https://www.free-culture.tk with _Firefox_ 99 (beta 1) and with _Firefox_ 104 (beta 1).

The issue arises when hardware acceleration is disabled (or not available):

1. Image is displayed perfectly fine with version 99.
2. Version 104 doesn’t seem to display image at all when in full-screen.

All this happened using the browser extension from the nightly build from today (2022-08-10).

So it is highly improbable that the regression was caused by _Ruffle_ itself (I guess _Firefox_ may be messing things here).

@n0samu, I updated the selfhosted build to the nightly from today.

Would you be so kind to check it with Chrome?

Many thanks for your help.

PS: I’m checking now with _Firefox_ for _Linux_ with hardware acceleration disabled (https://www.free-culture.tk/lfc-presentation.swf). I’m afraid that I have just realized get what was working fine for you, @n0samu (😅).

**Comment by ousia** [comment]
@n0samu,

playing directly https://www.free-culture.tk/lfc-presentation.swf, I get a first image such as:

![beforefullscreen](https://user-images.githubusercontent.com/203767/183971308-7c633e61-bf39-494f-97cb-eb8a8b0ac14d.png)

It will be scaled perfectly fine to full screen (to the same image [I already attached](https://user-images.githubusercontent.com/203767/181077035-b9123dda-1334-4a72-affc-ef1e0c5cea45.png)).

But going back to normal size distorts the image:

![backtonormal](https://user-images.githubusercontent.com/203767/183972022-32bee6b7-550a-4475-9198-ed146683254c.png)

Again, I’m on _Linux_ using _Firefox_ with the nightly browser extension from 2022-08-10.

### Clearer sample?

With a very similar presentation, https://www.improve-presentations.tk/Presentacion-presentation.swf:

The first image is fine:

![before](https://user-images.githubusercontent.com/203767/183973673-7fd1f9e7-1a1c-48d4-bdae-3693bc17468e.png)

Full screen is also fine:
![fs-fine](https://user-images.githubusercontent.com/203767/183973672-cdcceeda-5881-4d5e-8475-de6a6222c2ee.png)

But back to normal gets distorsion:

![after-distorted](https://user-images.githubusercontent.com/203767/183973675-2a886766-4a4d-4687-b4e8-975017cd5dc5.png)

Just in case it helps.

**Comment by ousia** [comment]
After checking myself the presentation in _Chrome_ (same computer as the original issue reported here), image is rasterized fine in both full and normal screen.

So the culprit seems to be _Firefox_ rasterizing the images from frames.

BTW, this is what _Firefox_ displays after setting the image to normal after full screen:

![Untistled](https://user-images.githubusercontent.com/203767/184190110-1e04792f-d1df-44bb-81f2-9a564ff12874.png)

The animation is actually played in the bottom left corner, having the main image flickering but not advancing with the slides.

I think this have to be an upstream issue, but I don’t know where to start or how to report this.

**Comment by ousia** [comment]
Just it case it might help, here you have the resource info:

![ffox-img](https://user-images.githubusercontent.com/203767/184191564-429d6323-596c-4b1e-92df-9bc0d9435bf1.png)

1. Top left: _Chrome_ in full screen.
2. Top right: _Chrome_ in normal screen.
3. Bottom left: _Firefox_ in full screen.
4. Bottom right: _Firefox_ in normal screen.

The animation played was https://www.free-culture.tk.

Just in case it might help.

**Comment by ousia** [comment]
This seems to be fixed in latest Firefox (106.0.1).

Closing the issue myself, although it would be great if @n0samu could confirm the fix too.

**Comment by n0samu** [comment]
Can confirm that this is fixed!
