### ISSUE TITLE
https://z0r.de/7203 has some visual issues

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7538]
### Describe the bug

Two issues with the humping man:
1) He is still - he doesn't hump
2) The man isn't evently spread over the screen - in the Adobe playback below you may see an equal spacing between the man(s)

Nightly 2022-07-31

![Ruffle7203](https://user-images.githubusercontent.com/75184268/182231768-fc5e47df-2e4b-4682-b17f-ae29db9d752e.gif)

Nothing interesting in F12 - the only warning concerns audio, and audio seems fine in the loop.

![image](https://user-images.githubusercontent.com/75184268/182228768-56ae1191-4093-42a6-bda6-1e4bf70099fc.png)

### Expected behavior

Adobe playback:
![Adobe7203](https://user-images.githubusercontent.com/75184268/182231877-e8500c5c-b40f-4e30-8ffc-a7a77c1278f8.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 103.0.5060.134

### Additional information

Interesting thing to know - it seems that some not long time ago (i think) this loop was very broken, and these errors were shown:
![image](https://user-images.githubusercontent.com/75184268/182229178-2514d57d-995f-4912-ab46-c8eb0bd849e7.png)
And
1) The loop was silent
2) No humping man at all
3) Only a first image for the background - there should be a slideshow, but the first image stuck
![image](https://user-images.githubusercontent.com/75184268/182229275-c9820ede-8d3a-4877-ae05-b7ef6f08cf2b.png)

This is reproduced using a version of Ruffle currently hosted on z0r - not sure when it was updated last time.

**Comment by torokati44** [comment]
> This is reproduced using a version of Ruffle currently hosted on z0r - not sure when it was updated last time.

Ruffle on z0r was updated just this weekend... :)

**Comment by torokati44** [comment]
> Interesting thing to know - it seems that some not long time ago (i think) this loop was very broken, and these errors were shown:

These were fixed by #7428.

**Comment by torokati44** [comment]
Looks like https://github.com/ruffle-rs/ruffle/pull/7570 fixes this.
