### ISSUE TITLE
https://z0r.de/7556 vusials cycle through a "preloader"

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7563]
### Describe the bug

2 issues:
- The loop is cycling through a screen resembeling a preloader
- No text with the song name appearing when hovering the mouse over the area

Nightly 2022-08-02
Nothing in F12

![Ruffle7556](https://user-images.githubusercontent.com/75184268/182468198-5ddd0555-9afe-4f92-b304-5afbb712a147.gif)

### Expected behavior

Adobe playback
![Adobe7556](https://user-images.githubusercontent.com/75184268/182468768-e2751749-3922-40e9-a59d-115586476f8c.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

103.0.5060.134

### Additional information

When using z0r's version of Ruffle, on F12 there's this:
![image](https://user-images.githubusercontent.com/75184268/182468585-53e3f05d-8fe1-4fd2-9d2e-b185249ec9ee.png)

**Comment by Diatonator** [comment]
I realised that the preview GIF of the Adobe playback not that clear in that the "preloader" screen is shown only once :)

**Comment by firoball** [comment]
This loop appears to run properly with latest z0r release.

**Comment by torokati44** [comment]
Can confirm, it's no longer flashing. I think it hasn't been for a while now, in fact... :sweat_smile:
