### ISSUE TITLE
https://z0r.de/2579 - stuff is missing from the animation

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7580]
### Describe the bug

For https://z0r.de/2579 various things which should be showing on the screen are not showing:
- When the guy should change emotion - he instead disappears
- Eye bullets are almost not shown
- Explosions are absent

F12 has nothing.

Stuff which is shown:
- "Normal" guy
![kadr 000](https://user-images.githubusercontent.com/75184268/182942598-81874bc2-53a9-46d0-b693-ce7237152e93.png)
- Flashing text and still image fire
![kadr 333](https://user-images.githubusercontent.com/75184268/182942641-151b07c4-266c-4dd0-9169-760bc540ab54.png)
 

### Expected behavior

From the Adobe playback:

"Emotion" face:
![kadr face 69](https://user-images.githubusercontent.com/75184268/182943949-40ad8375-5b05-43be-9479-fe26e76d59ba.png)

Eye bullet explosion:
![Adobe2579_BulletExplosion](https://user-images.githubusercontent.com/75184268/182943608-7a6a6780-2ac2-4ddd-8b9d-ccfb479770ec.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

104.0.5112.81

**Comment by Diatonator** [comment]
Could be somehow linked to this? https://github.com/ruffle-rs/ruffle/issues/3828

**Comment by torokati44** [comment]
Definitely looks similar in nature.

**Comment by torokati44** [comment]
Looks like #7570 fixes this.
