### ISSUE TITLE
https://z0r.de/7049 sounds like a nuclear explosion when it shouldn't

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7584]
### Describe the bug

[EARRAPE WARNING]
https://z0r.de/7049

Many things are not up to Adobe in this flash, but for visual stuff it's understandable as some stuff seems to be not implemented.
![image](https://user-images.githubusercontent.com/75184268/183087293-f0a04f53-f593-4cae-91ca-7bf0503aa0ce.png)

As to why this flash want to gouge out my eardrums in Ruffle I'm not sure.

Nightly 2022-08-04

Other stuff not working:
- Drugs coming from the bucket are not moving
- No sound control - there seems to be a fancier one which smoothly appears when mouse enters the screen
- 99% number seems stuck in the center, whatever it be

### Expected behavior

At the very least I want my ears back.

Adobe playback:
![Adobe7049](https://user-images.githubusercontent.com/75184268/183088211-7623f70d-085c-42fd-b621-f220042a73c4.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 104.0.5112.81

**Comment by Diatonator** [comment]
https://z0r.de/7050 has really similar implements and likely was done by the same author as many things like the volume control and "imprinted 99%" are also here. But the sounds instead of huge bug explosion turn into some occasional glitching over the silentness.

**Comment by Diatonator** [comment]
7049 and 7050 are now looking like this:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/75184268/187024515-d4d3bafb-1b51-4a18-abc4-f7d167a34f36.png">

It's stuck on this screen, maybe because of this:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/75184268/187024541-917f2aa5-7a41-4ef8-a747-05da2558d067.png">

**Comment by torokati44** [comment]
> It's stuck on this screen, maybe because of this:

Yeah, that's likely. `Matrix3D` and `PerspectiveProjection` are on my TODO list, I think about 26 z0r loops are stuck because of them.

**Comment by Diatonator** [comment]
https://z0r.de/7049 works on Nightly 2022-09-28! 
Even the volume slider!

https://z0r.de/7050 is not working.

**Comment by Diatonator** [comment]
And, uh, again - https://z0r.de/7050 works if I press "Play" in the context menu.

**Comment by Korne127** [comment]
This can be closed as the original issue got fixed, and even https://z0r.de/7050 works by now :)
