### ISSUE TITLE
https://z0r.de/5047 - strange behavior of a "fake button"

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7585]
### Describe the bug

Area of the flash which shows some info when mouse enters it (and which is also apparently a "button") is glitching in Nightly 2022-08-04
![Ruffle5047](https://user-images.githubusercontent.com/75184268/183107092-1decd3a2-f097-40d0-80b7-f13f6d413d0b.gif)

On the z0r's version of Ruffle it seems to behave "still":
![RuffleOld5047](https://user-images.githubusercontent.com/75184268/183107107-25cf7d19-620f-4ae6-b70d-29eff3f24dd4.gif)

### Expected behavior

Adobe seems to disappear the "button" just for a little bit and not flash it continiously:
![Adobe5047](https://user-images.githubusercontent.com/75184268/183109108-bc7411c2-aa95-459f-a1ec-20ecd2866b7e.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 104.0.5112.81

**Comment by Diatonator** [comment]
https://z0r.de/5121 seems to show the same behavior

**Comment by torokati44** [comment]
I think this is fixed now. Feel free to reopen if you disagree, @Diatonator.

**Comment by Diatonator** [comment]
@torokati44 well it doesn't seem to work like 100% on flash on my end, but at least there no annoying flashing.
You can see on the "Adobe" gif the one single flash of that "button", and there is no flashing at all on the current version of Ruffle (nightly 2023-07-16)
It really seems like a non-issue for this swf, so I think it could be closed.

**Comment by torokati44** [comment]
I see the big red text in both Ruffle and Flash Player for exactly as long as I press the mouse button on the grey bar below.

**Comment by Diatonator** [comment]
@torokati44 the Big Red Text appears to be working the same, By the "button" I meant that black'ish thing below. It appears to flash slightly in Adobe

**Comment by torokati44** [comment]
Ah, I see. I have the loop in question running in Flash Player right in front of me, and can't get it to _flash_ like it does in the Adobe GIF above.
It _might_ be due to some glitch in encoding or optimizing the GIF, as even the red text is brown there (due to the palette choice)...
