### ISSUE TITLE
Pico’s School

### ISSUE THREAD

**Issue by mISTYmEADOWS** [ruffle-rs/ruffle#7599]
### Describe the bug

It isn't loading up properly. I think it said there was a problem with Flash.

### Expected behavior

The game to fully load and run smoothly.

### Affected platform

Browser's extension

### Operating system

IPad Air 3

### Browser

Safari

**Comment by n0samu** [comment]
> I think it said there was a problem with Flash.

Please send a screenshot of the exact error message.

Also, can you please provide the link to the game?

**Comment by n0samu** [comment]
Closing due to no response. Will reopen if you provide the requested information.
