### ISSUE TITLE
Neopets Flash Game Issue - Usuki Frenzy

### ISSUE THREAD

**Issue by crystalglassxxx** [ruffle-rs/ruffle#7661]
### Describe the bug

While playing the game, the score isn't capping at 628. Sometimes the score will randomly go up while playing without even doing anything. In the screenshot provided, you can see that I have a score of over 300 points before I even grabbed an item.
![image](https://user-images.githubusercontent.com/111154236/184446588-e396774f-b3ff-4430-bdba-7c8d059ed5bb.png)

### Expected behavior

Score isn't supposed to go above 628 even with all of the bonus points

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome Version 104.0.5112.81

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
