### ISSUE TITLE
Canyon Defense: Shots not fired

### ISSUE THREAD

**Issue by nachtklavier** [ruffle-rs/ruffle#7667]
On https://www.browsergames.fm/canyondefense/ game starts perfectly, graphics and sounds are fine, but the missiles won't get fired. You hear their sound but that's it.

**Comment by nachtklavier** [comment]
I assume, it's just a small bug.
Tested with latest nightly build.

**Comment by n0samu** [comment]
Interestingly, whenever the missiles are supposed to fire, this error appears in the console:
`MovieClip.localToGlobal: Missing point parameter`
I think this could mean that Ruffle's implementation of this function is incorrect or incomplete.

**Comment by Aaron1011** [comment]
@n0samu That error appears to be another case of Ruffle catching legitimate bugs in an SWF that are ignored by the AVM1 flash player. Here's the relevant code:

```
         var _loc2_ = new Object();
         if(this._boolTargetsEnemy)
         {
            _loc2_.x = this._mcTarget._x;
            _loc2_.y = this._mcTarget._y;
            this._mcTarget._parent.localToGlobal(objTargetGlobal);
         }
         else
         {
            _loc2_.x = this._numTargetX;
            _loc2_.y = this._numTargetY;
         }
         var objTargetGlobal = {x:_loc2_.x,y:_loc2_.y};
```

The `objTargetGlobal` is incorrectly defined *after* it's used. Flash Player will simply ignore the incorrect call to `localToGlobal`, and continue execution.
