### ISSUE TITLE
Infinite loop regression with z0r swf 1703 after text change

### ISSUE THREAD

**Issue by ubitux** [ruffle-rs/ruffle#769]
ef31a6bea4f30228f30aef3b5d6a7870451a7811 seems to cause an infinite loop regression in at least one of the z0r swf (1703).

It can be reproduced with the following:

```sh
curl 'https://z0r.de/L/z0r-de_1703.swf' -o z0r-de_1703.swf
exporter --frames 1 z0r-de_1703.swf z1703.png
```

**Comment by adrian17** [comment]
Looks like it's fixed by https://github.com/ruffle-rs/ruffle/pull/4339 .
