### ISSUE TITLE
some effect in font is missing in mildescape game

### ISSUE THREAD

**Issue by l12436** [ruffle-rs/ruffle#7693]
### Describe the bug

most of the mildescape has a shadow under message, but the game running under ruffle the shadow is missing.
This cause message is very difficult to see

under ruffle
![Screenshot_20220817_222112](https://user-images.githubusercontent.com/2596649/185159425-18385bc4-20cc-4b76-9b20-d03f7a7bc5c6.png)

original windows flash player
![Screenshot_20220817_222137](https://user-images.githubusercontent.com/2596649/185159476-399af9aa-2373-426a-9f43-bdc0b05a935b.png)

mildescape83 from flashpoint.
[escape83.swf.gz](https://github.com/ruffle-rs/ruffle/files/9363492/escape83.swf.gz)

### Expected behavior

It should has show under message.

### Affected platform

Desktop app

### Operating system

linux

**Comment by p0008874** [comment]
#15
#58

**Comment by p0008874** [comment]
Fixed in #11878

**Comment by Lord-McSweeney** [comment]
Fixed.
