### ISSUE TITLE
Desktop: incorrect rendering on fill

### ISSUE THREAD

**Issue by WillBrindle** [ruffle-rs/ruffle#77]
I haven't looked into this too much yet, but the following swf (a single frame taken from a [larger swf](https://www.newgrounds.com/portal/view/1224) renders correctly in the web version:
![image](https://user-images.githubusercontent.com/8310103/66269052-c954c080-e83b-11e9-9d49-f78d82ec457d.png)

However in the desktop version the fill is only partially rendered as if there's a mask or something over the top:
![image](https://user-images.githubusercontent.com/8310103/66269073-19cc1e00-e83c-11e9-94f7-a18fb981f589.png)

I'm yet to do any further investigation in to whats causing it, will update this issue if I get a chance to.

[1224_freeamerica_brokenframe.swf.zip](https://github.com/ruffle-rs/ruffle/files/3694328/1224_freeamerica_brokenframe.swf.zip)

**Comment by Herschel** [comment]
Looks like the grey background isn't getting traced/tessellated correctly, probably the path isn't closed properly somewhere in`shape_utils`. Looks like the bottom of the candle flame comes to a point where the two sides of grey meet each other -- this could be a problematic part.

**Comment by Herschel** [comment]
Here's a minimal example of the above rendering defect. I started with the art in the above SWF and deleted/reduced things around the candle area. You can see the edge of the top triangle hole get drawn over, looks like a triangle get drawn to the upper left corner of the grey rectangle.

[bad-vector.zip](https://github.com/ruffle-rs/ruffle/files/3699316/bad-vector.zip)
(CS6 FLA)

**Comment by Herschel** [comment]
Flash Player (top) vs. Ruffle Desktop (bottom)
![image](https://user-images.githubusercontent.com/36278/66346630-64ff3300-e907-11e9-8784-e32fbe62f87d.png)

**Comment by Herschel** [comment]
Ugggh, the above example bad-vector.swf was *not* working for me, and then suddenly it is without any changes. Scary... Maybe some non-determinism due to `HashMap` vs. `FnvHashMap`, or somewhere inside lyon... The original badframe.swf still has the issue.
