### ISSUE TITLE
https://z0r.de/7799 some logic doesn't work properly

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7701]
### Describe the bug

In https://z0r.de/7799 the SWF tries to write the lyrics of the song, but in Ruffle it writes only one word - LYRICS:
![image](https://user-images.githubusercontent.com/75184268/185585812-4eba4ddb-25bd-4af3-b82e-952ee223d8ff.png)

### Expected behavior

In Adobe each "window" generates a word from the lyrics for **ATC - All Around The World**, and it's scripted to come word by word synchronized with the actual song:
![image](https://user-images.githubusercontent.com/75184268/185586044-27367408-56ad-4a36-a6f3-7f9d8463e757.png)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 104.0.5112.81

**Comment by Diatonator** [comment]
This got fixed in Nightly 2022-08-27

**Comment by torokati44** [comment]
This too, was fixed by #7570. \o/

**Comment by torokati44** [comment]
(Specifically by 963144e59, it seems.)
