### ISSUE TITLE
https://z0r.de/1978 starts completely frozen and silent

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7702]
### Describe the bug

Animation is completely frozen upon loading and no sound in https://z0r.de/1978.
Nightly 2022-08-19

### Expected behavior

Some animation over the music should play

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 104.0.5112.81

**Comment by Diatonator** [comment]
Another one which just "refuses to start" in a similar fashion:
https://z0r.de/3068

**Comment by torokati44** [comment]
I'm not sure z0r 3068 has the same underlying problem, but IIRC z0r 1978 is stuck due to some misunderstanding of the mysterious `DoABC`/`DoABC2`/`DoAbcDefine` opcodes.

**Comment by Diatonator** [comment]
I'm not sure what facilitated that, but both https://z0r.de/1978 and https://z0r.de/3068 are now working on Nightly 2022-08-24!

**Comment by torokati44** [comment]
Oh, that's interesting. It appears that they were both fixed by #7636. Which is strange. But also amazing of course!
