### ISSUE TITLE
Latest Nightly Break Render

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7703]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/185593897-67cd0a6a-abdc-400b-9252-44ec683bf923.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Swf file: https://www.pouet.net/prod.php?which=67334

**Comment by Diatonator** [comment]
If it's the recent "blend" PR, than I do think that some stuff from it better be switched off before it actually works more or less OK.

Like here is another example of SWF which was degraded visually by the recent changes:
https://github.com/ruffle-rs/ruffle/issues/2813#issuecomment-1220512464

**Comment by Dinnerbone** [comment]
A quick way to test the provided swf:
`cargo run --release -p exporter -- HeartCore_noplayer.swf result.png --skipframes 1580`

Using that to run a bisect gives a6b70e60ead4f52762ae123d46160574cbdb1d43  as the bad commit.

**Comment by Diatonator** [comment]
https://z0r.de/6699 also became a mess, and it also contains "darken".
It seems that the current implementation of "darken" is way too ugly.

**Comment by torokati44** [comment]
May I add, that the second screenshot from an earlier Ruffle nightly is not an actual expected output, as some shading is missing from the clothes for example. Here is how it looks like in FP:
![image](https://user-images.githubusercontent.com/288816/185610042-0ab76b56-2fdb-4037-89f3-fd41134519f7.png)

**Comment by torokati44** [comment]
It also looks different on the demo page in Google Chrome depending on whether I pass the `--disable-gpu` command line argument or not. (So, if it is using the WebGPU/WebGL or the canvas backend... - We should really print this, because sometimes I have no idea which one runs... :D)
