### ISSUE TITLE
Problem in Super Mario 63 (castle)

### ISSUE THREAD

**Issue by Scott-Steinheiser** [ruffle-rs/ruffle#7710]
### Describe the bug

I have been playing Super Mario 63 since 2015 and now I cannot enter the castle. The game crashes and the screen goes black. Not the whole screen of my computer, though. It does not load the map of the inside of the castle even if I wait for 30 minutes. I just started playing Super Mario 63 for the first time in one or two years, by the way. I saw that the gradients and textures for the buttons have changed. It was just because support for Adobe Flash ended a few years ago, and the only website I could find that could play Super Mario 63 was evilgames.eu/flashgames/super-mario-63.htm. I use evilgames.eu and newgrounds.com, but I still can't enter the castle. I don't just play Super Mario 63 on Chrome OS Flex, I also do it on my trusty Windows 8.1 laptop, with newer graphic cards and drivers. The "castle bug" still shows up on both laptops and both websites. I just really need help. This has been going on for two weeks and the game still won't go back to normal for me.

### Expected behavior

I was expecting the gradients to be the same. I had no idea about the "castle bug" thing. 

### Affected platform

Online demo

### Operating system

Chrome OS Flex

### Browser

Google Chrome 104

**Comment by n0samu** [comment]
Same issue as #6906, please add your comment to that issue
