### ISSUE TITLE
Canyon Defense: Objects not resetted

### ISSUE THREAD

**Issue by nachtklavier** [ruffle-rs/ruffle#7711]
### Describe the bug

On https://www.browsergames.fm/canyondefense/ game starts perfectly and thanks to the bugfix with regards to #7667 missile shots are fired. However, the missile turret either sticks on its last position and keeps firing on that one or it just sticks there. As a result, the game is not playable.

### Expected behavior

Missile turrets stop firing when an object is destroyed.
Missile turrets target new object when in range.

### Affected platform

Desktop app

### Operating system

macOS latest

### Additional information

Using nightly build from August 20

**Comment by n0samu** [comment]
This seems like yet another case of Ruffle not correctly removing objects, causing a similar issue to the one in the Vector TD games (#5711)

**Comment by nachtklavier** [comment]
@n0samu Does this mean there is no (immediate) chance of getting this fixed?

**Comment by n0samu** [comment]
Wouldn't say *no* chance, but it's a difficult issue, yeah.

**Comment by ousia** [comment]
@nachtklavier,

if the code to solve this issue depends on #5492, #993 is the first reported issue that will be solved by that PR.

I think that there are over other twenty reported issues that depend on #5492. #993 was reported more than two years days ago. 

Just in case it might give you some context of what may be required for the fix.

Cheers.

**Comment by nachtklavier** [comment]
Thanks, @ousia, I haven't even expected that someone is actually working on an open source Flash implementation :-)
So it was my surprise to stumble upon Ruffle and to experience an actually very smooth beginning of that game.
It doesn't work right now? OK. I played it way back (must have been 10+ years now), so it's plenty of time to wait, until these issues are resolved.
Thanks to all the people who are working on Ruffle!

**Comment by liberodark** [comment]
Hi

I confirm Canyon Defense have issue for play is making loop.
