### ISSUE TITLE
Context menu on iOS not working

### ISSUE THREAD

**Issue by MJegorovas** [ruffle-rs/ruffle#7723]
Because of a [bug](https://bugs.webkit.org/show_bug.cgi?id=213953) in WebKit contextmenu event does not fire on iOS (and iPadOS). Need to investigate any possible workarounds.

**Comment by MJegorovas** [comment]
This [thread](https://github.com/Leaflet/Leaflet/issues/6817) might give some interesting info.

**Comment by MJegorovas** [comment]
This thread might give some interesting info:
#https://github.com/Leaflet/Leaflet/issues/6817

**Comment by ActionWavele** [comment]
is the bug still here?
