### ISSUE TITLE
Error on https://hentai-flash.com/ruffle.php?site=sfg&swf=Pee-Divination.swf

### ISSUE THREAD

**Issue by aaaaaaaaaaa0000a** [ruffle-rs/ruffle#7761]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:68321
    at Array.forEach (<anonymous>)
    at yi.f.wasm (https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:67974)
    at https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at yi.e (https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:35865)
    at o (https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://hentai-flash.com/ruffle_nightly_2021_01_12_selfhosted/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://hentai-flash.com/ruffle.php?site=sfg&swf=Pee-Divination.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by n0samu** [comment]
This problem is caused by Microsoft Edge's "Enhance your security on the web" feature. [See the FAQ for a solution to the problem](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#edge-webassembly-error).
