### ISSUE TITLE
AVM2 Simple Animation Tests - Regression

### ISSUE THREAD

**Issue by sombraguerrero** [ruffle-rs/ruffle#7767]
### Describe the bug

After discussing this with @adrian17, decided this was finally worth logging.
I have a series of really simple AVM2 animations in my test bed. Prior to nightly 2021-03-04, they were all working perfectly, then they regressed. The animals' eyes, heads, or something similar just drop midway through the animation. I see there was a plethora of AVM2 commits included in that nightly. Farm animal pack of SWFs attached.
[animals_as3.zip](https://github.com/ruffle-rs/ruffle/files/9434978/animals_as3.zip)

### Expected behavior

Animations should play without animals losing body parts.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Chromium based and Firefox

### Additional information

https://github.com/ruffle-rs/ruffle/commits/nightly-2021-03-04

**Comment by sombraguerrero** [comment]
I've done some additional testing through manual builds of the desktop app on master, and I've discovered that for some reason, this does not appear to be an issue on Linux, only on Windows. Vulkan is the only backend available for my desktop on Linux, but even when I select Vulkan on Windows, the discrepancy still remains. Linux seems to work no matter what, and Windows doesn't work no matter what.

**Comment by sombraguerrero** [comment]
Perhaps I did need the latest desktop app on Windows to see this fixed after all, which is weird because these SWFs don't even have gotos, but I won't argue :)

**Comment by adrian17** [comment]
Oh yeah, it works on web now too. Weird.
