### ISSUE TITLE
[Pestilence Z Episode 1] Regression to the intro screen when waiting on the main screen

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7783]
### Describe the bug

https://user-images.githubusercontent.com/75052171/187061197-bdc84ab2-90af-4de4-bb0f-cbc6d4829108.mp4

In 'Pestilence Z Episode 1', if you wait for a certain amount of time on the main screen, it rewinds to the initial developer logo screen.

This problem repeats indefinitely, and it keeps returning to the initial screen even after clicking the 'New Game' button.

[Pestilence Z Episode 1.zip](https://github.com/ruffle-rs/ruffle/files/9439214/Pestilence.Z.Episode.1.zip)

last check: 2022-08-28 Nightly

### Expected behavior

Frame regression should be resolved.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 104

**Comment by relrelb** [comment]
This is regressed by #4452.

**Comment by Toad06** [comment]
The issue is that `DefineSprite (5712: splash_zombie)` is not stopped/destroyed after being played, so it endlessly runs `_root.gotoAndStop(282);` when its frame 270 is reached. Adding a `stop();` after `_root.gotoAndStop(282);`  prevents the issue from happening.

**Comment by Lord-McSweeney** [comment]
This issue is no longer happening for me.

**Comment by Toad06** [comment]
Audio is still incorrectly looping.
