### ISSUE TITLE
Vex 3's levels aren't loaded properly

### ISSUE THREAD

**Issue by NoobTracker** [ruffle-rs/ruffle#7796]
### Describe the bug

I've created a hacked .swf of Vex 3 using JPEXS ffdec that automatically starts the game. It works when you run it with a standalone version of Flash, but not when you try to run it with the online ruffle demo. The title screen looks normal, mostly, but when it tries to load the first level / the hub stage, it just cycles through the levels. Similar results occur when you use Flash's Control / Step Forward button. The levels are stored as a single sprite with an animation frame for each level. 
[autostart1.zip](https://github.com/ruffle-rs/ruffle/files/9444959/autostart1.zip)

### Expected behavior

I would expect that the level I want to enter loads properly. 

### Affected platform

Online demo

### Operating system

Windows 7

### Browser

Vivaldi 5.4.2753.37 (Stable channel) (64-bit) 

### Additional information

It's an AS3 game.

**Comment by n0samu** [comment]
You're right about it cycling through the levels when it's supposed to be on the hub stage, but it does seem to automatically start level 1 after a while, and work normally from there. Can you confirm?

**Comment by NoobTracker** [comment]
> You're right about it cycling through the levels when it's supposed to be on the hub stage, but it does seem to automatically start level 1 after a while, and work normally from there. Can you confirm?

Not really, aside from being plagued with visual bugs and gameplay inaccuracies, nothing happens when you finish that first level, you get a transition, but you don't get back to the hub.

**Comment by n0samu** [comment]
> nothing happens when you finish that first level, you get a transition, but you don't get back to the hub.

Hmm... this actually seems to be an issue with the Ruffle Web Demo specifically:
`RustError("Cannot access property ::indexOf of null or undefined")`
Most likely there's some ActionScript checking the SWF URL, which fails on the web demo (see #8448).

Anyway, please try it in the Ruffle desktop app. After beating level 1, it returns me to the hub and I'm able to enter level 2.

**Comment by n0samu** [comment]
Vex 3 should be working fine now!
