### ISSUE TITLE
Cyrillic characters don't render at all

### ISSUE THREAD

**Issue by grishka** [ruffle-rs/ruffle#7811]
### Describe the bug

I tried different swfs, the problem seems to be unrelated to any particular one. Here's one that "works" except the text rendering: [злоген.swf.zip](https://github.com/ruffle-rs/ruffle/files/9449499/swf.zip)

This happens both in the online demo and in the native app.
![2022-08-30 07 10 22 ruffle rs Ruffle Web Demo](https://user-images.githubusercontent.com/1478258/187347408-d33fabde-3cbe-43b2-b04d-d306b9fdc66e.png)
![Снимок экрана 2022-08-30 в 07 12 42](https://user-images.githubusercontent.com/1478258/187347639-a5b19a68-507c-4bd8-b301-288055838b44.png)

Here's one more swf (though AS3 one) that also has this problem: [Graffiti.swf.zip](https://github.com/ruffle-rs/ruffle/files/9449539/Graffiti.swf.zip)

### Expected behavior

Adobe Flash Player renders all characters correctly:
![Снимок экрана 2022-08-30 в 07 11 09](https://user-images.githubusercontent.com/1478258/187347460-43abbfd2-f645-4fc1-8098-531d31e4c703.png)

### Affected platform

Online demo

### Operating system

macOS 12.5.1

### Browser

Vivaldi 5.4.2753.40 (Stable channel) (arm64) aka Chrome 104.0.5112.105

**Comment by n0samu** [comment]
The embedded fonts in this SWF do not seem to provide the needed Cyrillic characters. Flash Player would fall back to a device font in this case, but Ruffle's fake device font does not support Cyrillic characters. See #1862.

**Comment by n0samu** [comment]
This is working in the desktop app now thanks to #14535. It can also work on the web if you provide your own SWF containing the required font - [see our FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-do-i-change-the-fonts-used-by-flash-on-my-website).

**Comment by cleverPhilologist** [comment]
Off-topic but where did you find that text? It's okay if you don't want to say it

**Comment by grishka** [comment]
> Off-topic but where did you find that text? It's okay if you don't want to say it

It's a Russian meme and website from the 00s. Some words that originated there became millennial slang. If you **really** want to find out more, here's two articles that are likely hard to make sense of if you don't speak Russian:
https://lurkmore.online/%D0%A3%D0%BF%D1%8F%D1%87%D0%BA%D0%B0
https://lurkmore.online/%D0%A3%D0%BF%D1%8F%D1%87%D0%BA%D0%B0/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C
