### ISSUE TITLE
Error on https://www.comdotgame.com/play/magic-book-2

### ISSUE THREAD

**Issue by chenxiaojinchenxiaojin** [ruffle-rs/ruffle#7812]
# Error Info
Error name: TypeError
Error message: 已取消

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://echo.comdotgame.com/4x90xhl3k0/games/files/504f15c72c70d87c80a56b2a3366444b.swf
Param allowscriptaccess: always
Param bgcolor: ffffff
Param wmode: gpu
Param flashvars: id=2298744
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://www.comdotgame.com/play/magic-book-2

# Browser Info
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1
Platform: iPhone
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-07-06
Channel: nightly
Built: 2022-07-06T00:17:12.303Z
Commit: 265dcd2e8dc424871b034cbceafb1fbadb76714a
Is extension: false

**Comment by n0samu** [comment]
Looks like a problem with your network connection.
