### ISSUE TITLE
Ruffle doesn't work on CoolMathGames flash games

### ISSUE THREAD

**Issue by BlazerB101** [ruffle-rs/ruffle#7840]
There might be a specific reason for this, but ruffle doesn't seem to fix the 'This flash game is not playable in your browser' problem for coolmathgames flash games. I thought this would work from watching this video (https://www.youtube.com/watch?v=-cubW-IMufk) but the video is a year and a half old and it 'unflashes' a game that's not even flash on the site anymore, so I want to know if this still works and what I can do to make it work if it does still work. Thanks!

**Comment by n0samu** [comment]
Unfortunately it seems that CoolMathGames has disabled access to Flash games entirely, which is not something that Ruffle can fix. It is still possible to find the link to the game's SWF file in the page's source code, but this is quite an advanced method. I'd recommend playing Flash games on other websites for now.
