### ISSUE TITLE
Anika's Odyssee - Gets through logos to title screen then resets to logos.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#7845]
### Describe the bug

https://www.newgrounds.com/portal/view/411623/format/flash?emulate=flash

Anika's Odyssee is AS3 and gets as far as showing the title screen before it resets to the intro logos. 

### Expected behavior

Expected to not reset to the intro logos.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome

**Comment by LukeSaward1** [comment]
This happens with Run 2 as well.
You need to wait until AS3 support is improved.

**Comment by Lord-McSweeney** [comment]
`ERROR core\src\display_object\movie_clip.rs:2363 Error occured when running AVM2 frame script: RustError("Non-public property flash.events:IEventDispatcher::addEventListener not found on Object")`

**Comment by Lord-McSweeney** [comment]
The issue appears to be fixed in latest nightly.

**Comment by n0samu** [comment]
That's thanks to #9622!
