### ISSUE TITLE
Tuper Tario Tros: AVM2 Error Report

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#7875]
### Describe the bug

This will cost #7209 appear on desktop version.
But Fortunately, The web version give error log.
[ruffle.rs-1662373240021.log](https://github.com/ruffle-rs/ruffle/files/9488973/ruffle.rs-1662373240021.log)

### Expected behavior

This error should not occur.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Google Chrome 104.0.5112.102

### Additional information

SWF: https://www.newgrounds.com/portal/view/522276/format/flash?emulate=flash

**Comment by n0samu** [comment]
That error has been fixed by #7956. But now this game seems to be exposing a memory leak; it eats up more and more memory until it crashes.
