### ISSUE TITLE
Alpha channel not rendered on images?

### ISSUE THREAD

**Issue by Gargaj** [ruffle-rs/ruffle#7877]
### Describe the bug

Playing http://www.digshot.com/gameinfopage.php?g=2657 causes a few obvious alpha channel issues - unfortunately they're most visible at the last level, but here's a playthrough video to help you get there: https://www.youtube.com/watch?v=YrlqziJOmW0

![image](https://user-images.githubusercontent.com/1702533/188466417-818484e0-750b-43d6-b664-4f940599ab44.png)

### Expected behavior

It looks to me that the alpha channel on some images isn't honored correctly; the hands on the screenshot should not have the white rectangle around them, and the "END" sign shouldn't have the black background.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 104.0.1

**Comment by torokati44** [comment]
lol csá

**Comment by torokati44** [comment]
Looking at the problematic images in `ffdec` I see them the same way: on a solid black background, without any alpha.
Additionally, they are defined using plain `DefineBits (6)` tags, which has no support for any transparency.
When running the SWF in the desktop player with `RUST_LOG=warn` set, I get a couple messages like these:
```
[2022-09-05T15:57:25Z WARN  ruffle_core::display_object] Blend mode 'screen' is unsupported and will not render correctly.
[2022-09-05T15:57:25Z WARN  ruffle_core::display_object] Blend mode 'lighten' is unsupported and will not render correctly.
```

So, this is likely just another case of #58.

**Comment by Lord-McSweeney** [comment]
The blend modes PR fixes this issue.

**Comment by torokati44** [comment]
Cross-referencing: #8262, #9134

**Comment by torokati44** [comment]
This is fixed now, at least on desktop, and on WebGL-capable browsers.
