### ISSUE TITLE
https://z0r.de/1608 stuck on "Loading"

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#7887]
### Describe the bug

https://z0r.de/1608
Nightly 2022-09-05
Stuck on this
![image](https://user-images.githubusercontent.com/75184268/188508251-2d5ed5cc-db25-4b0d-a410-9d4a02a8782b.png)
![image](https://user-images.githubusercontent.com/75184268/188508268-525c5705-f5f4-4dcc-8e56-7199bcfa0778.png)

### Expected behavior

Animation with sound

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 105.0.5195.102

### Additional information

Something unimplemented yet?

**Comment by Diatonator** [comment]
Now it's this:
![image](https://user-images.githubusercontent.com/75184268/192885741-6cc120ef-e27f-4bc1-bde7-87593ed3f199.png)
Doesn't work yet - same symptoms

**Comment by torokati44** [comment]
FWIW simply adding a stub `public var contentType:String;` to `URLRequest` makes it work.

**Comment by Diatonator** [comment]
@torokati44 I think that a good amount of things will just work in some capacity if everything "connection", "request" related stuff gets stubbed. I do think many flashes just do "connections" for some auxiliary things (maybe submitting leaderboard stuff, some backdoor stuff or statistics) which doesn't interrupt the main flow. But maybe not - I'm not an experienced dev in flash.

**Comment by Diatonator** [comment]
Also it seems to play if I press "Play" in the context menu. 
What's interesting that if I press "Play" again, it goes back to "Loading". Press again - back to the loop, and so on. While music plays without interruptions all the way.
If I press "Play" in Adobe Player, it also does not interrupt the music, but its flashes that "Loading" screen for a very little time and plays the loop again. Maybe if that URLRequest thing will be fixed, the behavior here will match the Adobe's.

**Comment by firoball** [comment]
Seems to run fine with latest z0r release.

**Comment by torokati44** [comment]
Indeed.
