### ISSUE TITLE
Madness Retaliation AVM2 Error

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#7898]
remember this is not supported actionsupport 3.0 game it's game AS3 but here 
https://www.y8.com/games/madness_retaliation
video here ''Madness_Retaliation_AVM2'' that's mp4 you see https://www.terabox.com/play/video?path=%2FMadness_Retaliation_AVM2.mp4&t=-1

i have things
there is error TypeError and AVM2

**Comment by n0samu** [comment]
Next time please provide the actual error messages by copying and pasting them into your issue. Here are the errors I got:
```
Blend mode 'multiply' is unsupported and will not render correctly. (repeated 15 times)
AVM2 error: TypeError: undefined is not an Object
AVM2 error: TypeError: undefined is not an Object
AVM2 error: TypeError: undefined is not an Object
AVM2 error: TypeError: undefined is not an Object
Error occured when running AVM2 frame script: TypeError: undefined is not an Object
SharedObject.getLocal not implemented
SAVE MENU updateChars() ERROR: Cannot access properties of null or undefined
playSound()  Cannot access property ::volume of null or undefined 
```

**Comment by Lord-McSweeney** [comment]
Now I get this:
`ERROR core/src/display_object/movie_clip.rs:2363 Error occured when running AVM2 frame script: RustError("Cannot access property ::stop of null or undefined")`

`ERROR core/src/avm2/events.rs:422 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x19c5da8 }) to handler FunctionObject(FunctionObject { ptr: 0x195b220 }) : RustError("Cannot access property ::armor of null or undefined")`

**Comment by n0samu** [comment]
Seems to be working now.
