### ISSUE TITLE
Combat Tournament from frivlegend.com

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#7900]
### Describe the bug

This is error AVM1 unknown

[frivlegend.com-1662479818196.log](https://github.com/ruffle-rs/ruffle/files/9498675/frivlegend.com-1662479818196.log)
here is 

### Expected behavior

there is bug but it's broken vcam look describe the bug
i played what happened this is 357 errors it's hard look image here
![Combat Tournament Game at FrivLegend com and 1 more page - Personal - Microsoft​ Edge 9_6_2022 7_04_07 PM](https://user-images.githubusercontent.com/80902993/188683193-99f092cc-82e0-4780-929d-11b1f1d54689.png)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Edge

### Additional information

nothing but combat tournament with ruffle player is 357 error

**Comment by n0samu** [comment]
Can you provide the link to the game?

**Comment by deividbinev12** [comment]
ok ok alright

**Comment by deividbinev12** [comment]
https://frivlegend.com/2015/x/combattournament/x.html?z=0iv but remember old friv is have flash menu but ruffle is working old friv now

**Comment by relrelb** [comment]
Closing in favor of #5540.
