### ISSUE TITLE
web: text input fields not working

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#793]
In Flash, you can input text (here numbers) to fields (i.e. last row of the table or "dS/dt=   (1)". 

In ruffle the input is not possible.

See http://www.webgeo.de/h_501_en/#3
(on http://www.webgeo.de you can switch between using ruffle or using flash)

Version:  ruffle_web_2020-06-02

[h_501_03_en.zip](https://github.com/ruffle-rs/ruffle/files/4864176/h_501_03_en.zip)
![flash_h_501_3](https://user-images.githubusercontent.com/1667683/86358296-865f3680-bc6f-11ea-9a97-560f2853f3dd.jpg)
![ruffle_h_501_en3](https://user-images.githubusercontent.com/1667683/86358308-8a8b5400-bc6f-11ea-88e2-d417b2e65259.jpg)

**Comment by lionirdeadman** [comment]
This issue is also present in Sonny (https://armorgames.com/play/505/sonny)

![image](https://user-images.githubusercontent.com/39467792/92052353-4691f980-ed5b-11ea-94a8-94ca67cfbc64.png)

**Comment by Herschel** [comment]
First pass at implementation was added in #1447.

**Comment by KMicha** [comment]
Tested and works as expected....  Thank you

**Comment by vstyler96** [comment]
This is present here: https://www.bubblebox.com/play/1561/the-cabin.htm :(
