### ISSUE TITLE
web: selection not working

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#794]
In Flash, you can select some topics (here "City", "Land use" and "Soil type").

In ruffle the selection range is not shown

See http://www.webgeo.de/h_501_en/#7
(on http://www.webgeo.de you can switch between using ruffle or using flash)

![flash_h_501_en7](https://user-images.githubusercontent.com/1667683/86359432-48631200-bc71-11ea-98ac-bd6e6d94d064.jpg)
![ruffle_h_501_en7](https://user-images.githubusercontent.com/1667683/86359442-4b5e0280-bc71-11ea-8e0c-4a60d2db9d28.jpg)
[h_501_07_en.zip](https://github.com/ruffle-rs/ruffle/files/4864232/h_501_07_en.zip)

Version: ruffle_web_2020-06-02

**Comment by Herschel** [comment]
Looks like this is working now (but slow performance due to text rendering).
