### ISSUE TITLE
Ruffle does not have Options bar

### ISSUE THREAD

**Issue by mero09-99** [ruffle-rs/ruffle#7951]
Ruffle really needs the options bar flash player has. 
![file](https://user-images.githubusercontent.com/109428504/189541378-5d7b5449-c4b6-4656-9999-e085f9076947.png)
File,

Open, for when you want to play a swf but don't want the load a file popup to happen immediately,
Close, for when you want to switch swfs without closing the entire player,
Print, it would be nice if this could do this, https://github.com/ruffle-rs/ruffle/pull/1168#issuecomment-694583237 instead of just sending an image to your printer (if you even have one)

![view](https://user-images.githubusercontent.com/109428504/189541669-b90cfda8-3754-4384-af7b-9fd096efe094.png)
View,
100% and Show all,
zooming in and out (does Ruffle emulate this ?)
Fullscreen/quality settings

!['control'](https://user-images.githubusercontent.com/109428504/189541746-060d17b3-9416-4773-8945-1e6e7fb8ea14.png)
'control' 
Play,  Rewind, forward, backward, loop, etc

![''''help''''](https://user-images.githubusercontent.com/109428504/189541816-9a3b4933-2b0e-40a6-8b82-9a01b6483196.png)

and "help" (which was never helpful when clicked)

I think that Ruffle should put the Readme here, or just change it to be called 'information' and put the SWF information there,.

maybe as well as a changelog,or ruffle versioning, etc, etc

![info](https://user-images.githubusercontent.com/109428504/189541898-4a62e05d-59cb-4a45-b64e-bf672f1e1442.png)

**Comment by p0008874** [comment]
#895

**Comment by deividbinev12** [comment]
agreed

**Comment by ActionWavele** [comment]
when is this being added?
