### ISSUE TITLE
Please ask how can I play .flv format video.

### ISSUE THREAD

**Issue by xutian111** [ruffle-rs/ruffle#7966]
**Describe the feature**
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

Error running definition tag: DefineVideoStream, got Invalid data: Invalid video codec.
Tried to instantiate non-registered character ID 4
Unable to instantiate display node id 4, reason being: Character id doesn't exist

**Comment by n0samu** [comment]
This feature is not yet implemented, see #3801
