### ISSUE TITLE
All text show as "test" in Phit and some rendering issues

### ISSUE THREAD

**Issue by Pranav-FP** [ruffle-rs/ruffle#7979]
### Menu
![image](https://user-images.githubusercontent.com/110013681/190086556-d50e3b90-a35a-4ff9-b2c1-9e0ec5797f0f.png)
All the menu text show up as "test" and also rendering is not perfect.

### Level
![image](https://user-images.githubusercontent.com/110013681/190086959-0541bf4f-470a-43c3-b4a1-7842ae26b79e.png)
Only the outlibes are rendered properly

### Menu
![image](https://user-images.githubusercontent.com/110013681/190087115-5cafa729-2404-4da4-9e7f-10e840075e34.png)

#### Level
![image](https://user-images.githubusercontent.com/110013681/190087789-31d1854e-8660-4222-bdb2-0ffd9a68de80.png)

## Affected platform

Desktop app

## Operating system

Windows 11

## Browser

NA

## Additional information

SWF Link - https://www.addictinggames.com/sites/default/files/flash_games/phit_0.swf

Version - ruffle-nightly-2022_09_14 (latest as of writing this)

**Comment by Pranav-FP** [comment]
Related to #5887 I guess

**Comment by hatal175** [comment]
So the issue here is that there's a 'button sprite' -> button -> text heirarchy.
In the button sprite code CPhitButton it assigns a text to this._buttonText which is the variable name for the text. In flash this works fine but ruffle doesn't make that connection, I assume because of scoping issues (assigning to this._button._buttonText fixes this but ruins flash).
I assume #5492 will help? Not sure what is the pull request currently working on this.

**Comment by n0samu** [comment]
Oh interesting, sounds very similar to #2181 then. As far as I understand, this would take quite a big refactor to fix and no one is working on it at the moment.

**Comment by waspennator** [comment]
Blocks are rendering properly now, but the text is still somewhat buggy. I do notice that during gameplay, most of the button text shows up normally save for the quit button, but as soon as the buttons become active as you move pieces around, they start changing text to test.

![Screenshot_20230727_013323_Chrome](https://github.com/ruffle-rs/ruffle/assets/78768499/ab113135-0625-4604-b5a4-8f7f2d47db9d)
![Screenshot_20230727_013400_Chrome](https://github.com/ruffle-rs/ruffle/assets/78768499/e8bc3ddb-0094-49b7-82a4-1170dbb3a7e2)

**Comment by Lord-McSweeney** [comment]
Fixed by #12541.
