### ISSUE TITLE
Regression: Armor Games logo displayed incorrectly in Ruffle Desktop

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#7999]
### Describe the bug

In [Cube Mayhem](http://i.notdoppler.com/files/cubemayhem.swf), the Armor Games logo in the bottom-left corner of the main menu is displayed incorrectly:
![image](https://user-images.githubusercontent.com/71368227/190836764-2cd83f88-5d6f-441c-9f16-cb7a5e97199e.png)

### Expected behavior

The logo is displayed correctly in web builds of Ruffle, and in older desktop builds:
![image](https://user-images.githubusercontent.com/71368227/190836870-da5f0d3b-e032-4909-9677-528f0f7cedde.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Seems like this broke in [build 2022-09-06](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2022-09-06). ~~So I think it was caused by #7888.~~ (See my comment below)

**Comment by torokati44** [comment]
The shield appears correctly for me on current `master` (423d7e4cc) on Linux, both OpenGL and Vulkan, and both X11 and Wayland, and both SW and HW rendering.

**Comment by n0samu** [comment]
Fixed by using the `-g dx12` option. So I guess this is an issue with wgpu's Vulkan backend on my specific hardware/driver: Intel Iris Xe, driver version 30.0.101.1273.

**Comment by n0samu** [comment]
Update: I've bisected the issue with the help of @Dinnerbone, and it seems to have been caused by 5585772d5458fc3f9b66ec353647523c5b5edb20.

**Comment by n0samu** [comment]
Seems like this was fixed sometime in January.
