### ISSUE TITLE
Most WebHosting uses the CPanel, how do configure CPanel so that it will support SWF MIME Type ?

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#801]
https://i.imgur.com/UovYcaH.png

Can this be fixed in the CPanel ?
or you have to setup your own server for ruffles to work ?
Thanks.

PS: If I do manage to get in contact with the hosting company, what do I tell them ?
Configure *.swf as what mime type ?
Thanks.

**Comment by zanzlanz** [comment]
I believe you may be encountering the issue described on the [Using Ruffle](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle) Wiki page, where Apache is not configured to identify .wasm files properly for Ruffle itself to run.

I think in cPanel you can accomplish this on the MIME Types page:
![image](https://user-images.githubusercontent.com/5413502/86409311-a3ebca80-bc86-11ea-8fcc-9d586e82ac52.png)

Simply enter in a new associated format for Web Assembly:
![image](https://user-images.githubusercontent.com/5413502/86409321-a817e800-bc86-11ea-9a3a-1845d9b7ad25.png)

I should disclaim that I have not run through this process myself. Hopefully it is correct and helpful though!

**Comment by BracerJack** [comment]
I have added wasm:
https://i.imgur.com/QKSEzTX.png
Thank you for helping me to get closer to fixing it.
I am still getting:
https://i.imgur.com/wXzDKgB.png

**Comment by Toad06** [comment]
Maybe try cleaning your browser's cache (or open in a private tab if you want to check first).

**Comment by BracerJack** [comment]
Good idea....
Opening private window...
Ok, now a different, I believe more clear report is coming out ?
https://i.imgur.com/X9qjCyC.png

**Comment by BracerJack** [comment]
Ok, to get to the ROOT of the problem I uploaded the swf to: http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/
And I got this:
https://i.imgur.com/B3I8Pnk.png

The similarities are very telling.

**Comment by Herschel** [comment]
Looks like this SWF is compressed with LZMA, which is not enabled on the web target currently. If possible, you can try switching to Deflate compression for now in the Flash IDE Publish settings. Closing in favor of #405.

**Comment by BracerJack** [comment]
THANK YOU !!!
