### ISSUE TITLE
LoaderInfo: Event.COMPLETE is never resolved

### ISSUE THREAD

**Issue by robinheidrich** [ruffle-rs/ruffle#8010]
### Describe the bug

If you register an event listener to `contentLoaderInfo`, it will never be resolved. This is also true for `Event.INIT`, others I have not tested.

```as3
var loader:Loader = new Loader();
loader.contentLoaderInfo.addEventListener(Event.COMPLETE, initHandler);
var request:URLRequest = new URLRequest(url);
loader.load(request);
```

### Expected behavior

The events should be resolved.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 110.0.5481.96

**Comment by adrian17** [comment]
Is this with the most recent Ruffle verison? I just tried compiling it and it worked.
Can you please show which SWF this fails on?

**Comment by EmperorBale** [comment]
This is due to `LoaderInfo` not being fully implemented (it is currently stubbed)

**Comment by robinheidrich** [comment]
Fixed with the latest Ruffle nightly version. Thanks for your hard work!
