### ISSUE TITLE
On The Moon (Episode 21) graphical glitches https://www.newgrounds.com/portal/view/557193

### ISSUE THREAD

**Issue by 40411** [ruffle-rs/ruffle#8019]
### Describe the bug

Several graphical bugs can be observed.
The flying pixel alien does not have a green glow effect;
![image](https://user-images.githubusercontent.com/80294264/190927343-1f9695f8-ed12-471b-87cb-55409b04dc18.png)
The BBQ smoke is not blurred;
![image](https://user-images.githubusercontent.com/80294264/190927282-a7b24643-e9fc-4c0c-9239-721d0500c29a.png)
The lights on the wall, foreground elements, and the shadow of the Tinsel do not have a blur effect, the scanner light is also missing it and apears less bright;
![image](https://user-images.githubusercontent.com/80294264/190927483-d9b8c853-e6a0-4c26-8a4d-a13caae27e51.png)
Man that slips does not have motion blur;
![image](https://user-images.githubusercontent.com/80294264/190927877-12708cf2-ef99-4981-9227-380dcac40f56.png)
After Toast King turns around his shadow disapears;
![image](https://user-images.githubusercontent.com/80294264/190927606-165ce07d-296f-4908-a8fb-a132d451ca5a.png)
Hole Puncher and Toast King do not have motion blur;
![image](https://user-images.githubusercontent.com/80294264/190928029-71a00598-a2eb-4ac1-8394-148fabb0feba.png)
![image](https://user-images.githubusercontent.com/80294264/190928063-8965ba35-8a8d-4680-8fa6-dd73c5f374b2.png)

### Expected behavior

Here are the same scenes on the official Flash Player, the frames aren't all exact but it illustrates well what's different.
Glowing Alien;
![image](https://user-images.githubusercontent.com/80294264/190927403-3b3f299d-3b37-4ee7-a3d6-21895d145a42.png)
BBQ smoke;
![image](https://user-images.githubusercontent.com/80294264/190927456-493ba414-136b-478c-8eac-ccc4780e757d.png)
Shadows, lights and scanner;
![image](https://user-images.githubusercontent.com/80294264/190927534-6b3cd98a-c0a1-417c-adbf-9993460383d1.png)
Motion blur on man;
![image](https://user-images.githubusercontent.com/80294264/190927861-467d363a-993b-438e-8a46-0716e74c2613.png)
Shadow after turning;
![image](https://user-images.githubusercontent.com/80294264/190927723-d9cf9254-daca-4ce6-8589-265a6b6389b5.png)
Motion Blur on hole puncher and Toast King;
![image](https://user-images.githubusercontent.com/80294264/190928010-884ce18e-bc30-4b04-b5f3-8d96cd9bf77b.png)
![image](https://user-images.githubusercontent.com/80294264/190928082-96b933d4-2d60-4f94-a928-f5bfe49ea277.png)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Additional information

Opened swf file on its own (https://uploads.ungrounded.net/557000/557193_moon21a.swf?1293094762) as it did not load in the Newgrowunds page for me, using Nightly Build 2022-09-18.

**Comment by waspennator** [comment]
Should be fixed by #11878
