### ISSUE TITLE
Access to Ruffle version outside Flash file

### ISSUE THREAD

**Issue by 40411** [ruffle-rs/ruffle#8021]
**Describe the feature**
Right now the only way to view which version of Ruffle a user has installed is by right clicking inside of a Flash window;
![image](https://user-images.githubusercontent.com/80294264/190928929-785a41bb-be91-4dd2-a03d-9c7763e72d00.png)
A way to check in the pop up or the settings page could be useful, especially with users that do not use nightly builds;
![image](https://user-images.githubusercontent.com/80294264/190929051-bd7e433b-2f2a-4167-8c25-10ec627c3291.png)

**Comment by mero09-99** [comment]
this is a pretty simple one, could even be added today

**Comment by ActionWavele** [comment]
is this added?
