### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by BurAndBY** [ruffle-rs/ruffle#8024]
### Describe the bug

Transparent stuff breaks. Works good in decompiler, breaks in ruffle
![image](https://user-images.githubusercontent.com/48630651/190969889-a441d4ef-de7e-48a7-b8d2-e1f7376303e6.png)
![image](https://user-images.githubusercontent.com/48630651/190970067-7c489ab5-7262-402a-a167-3393893e835e.png)

### Expected behavior

Transparent fire textures

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Google Chrome Latest

### Additional information

Website - https://burandby.github.io/YouDontKnowJackWeb/ydkj-ep-2007-03-05.html

**Comment by kjarosh** [comment]
Tested it today, it seems to be fixed
