### ISSUE TITLE
Circus Pop - Doesn't continue after the first level (as3)

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#8027]
### Describe the bug

Hello,
this game seems to work kinda fine but the game does not continue after the first level, sadly.

https://www.newgrounds.com/portal/view/616105?emulate=flash

Fix it :)

### Expected behavior

Level continue...

### Affected platform

Self-hosted version

### Operating system

All

**Comment by Lord-McSweeney** [comment]
Looks like this works now.
