### ISSUE TITLE
Error on https://www.min2win.ru/gm.php?id=5091

### ISSUE THREAD

**Issue by kurggmai** [ruffle-rs/ruffle#8028]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm1/globals/bitmap_data.rs:1079:18

# Player Info
Allows script access: false
Player type: Object
SWF URL: https://www.min4win.ru/swfs/5091.swf
Param bgcolor: #e3f1c6
Param allowScriptAccess: sameDomain
Param allowNetworking: https://www.min2win.ru/
Param base: https://www.min4win.ru/swfs/
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined

# Page Info
Page URL: https://www.min2win.ru/gm.php?id=5091
SWF URL: https://www.min4win.ru/swfs/5091.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-22
Channel: nightly
Built: 2021-01-22T01:05:46.108Z
Commit: b05c6540e18bcca93dce9ed6f65fe1f38d65a979

**Comment by n0samu** [comment]
This website is using a very outdated version of Ruffle. This error has already been fixed in the latest version.
