### ISSUE TITLE
Game size

### ISSUE THREAD

**Issue by noisycityfr** [ruffle-rs/ruffle#8029]
### Describe the bug

Hi !

As you can see there, game size became minimal with latest version (09/19/2022) : 

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.jeuxclic.com/jeux.php?id=224652
SWF URL: https://www.jeuxclic.com/jeux/game-1254625819.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 40
numFrames: 28
swfVersion: 9
backgroundColor: #7F7F7F
isActionScript3: false
uncompressedLength: 1552951

Stéphane.

### Expected behavior

Game should be 100% of its size inside the grey background.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Chrome

**Comment by n0samu** [comment]
What Ruffle version were you using previously? The last time anything related to scaling changed in Ruffle was many months ago. And it looks the same with real Flash Player.
![image](https://user-images.githubusercontent.com/71368227/191414010-26e4fa4a-6c87-4a78-9db2-e7c20afefafd.png)

**Comment by noisycityfr** [comment]
You are right. Latest update was 10 days ago for me.
Is there a way to avoid this scaling reduction ?
Some games became just inconfortable or implayable.

**Comment by n0samu** [comment]
I don't think there is any way yet, unfortunately. See #5186

**Comment by n0samu** [comment]
Closing in favor of #5186
