### ISSUE TITLE
[Coop Catch] "SetProperty: Invalid target"

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#805]
Garfield is trolling Ruffle right now, as you always get back to the title screen as soon as the level should start.
https://www.y8.com/games/garfield_coop_catch

This bug looks similar to #792, as it seems to involve issues in with(), and could actually be already fixed by #803.

In frame 96:

```
with(egg)
{
   gotoAndStop(objectnum)
};
with(this["chicken" + (eggnum + 1)])
{
   gotoAndPlay(2)
};
```

**Comment by Herschel** [comment]
This one seems a little bit more annoying. `gotoAndPlay` gets called with an incorrect `this`. `CallFunction` just calls the function with `this` set to the current clip, which is wrong; we need to pass the `this` from the activation/scope that the property was resolved on.
