### ISSUE TITLE
Will ExternalInterface.call("JavaScript Function") be implemented ?

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#806]
The usage is SO SIMPLE, it boggles the mind:
load_data = ExternalInterface.call("HelloFunction",50,50); //load_data will now contain the number 10.

Somewhere inside the HTML file, you have the script:
<script>
		function HelloFunction(arg1, arg2)
		{
			return (arg1+arg2);
		}
</script>

I literally just tested it on the actual Flash player, blank Flash file, contains nothing, just this, and...it simply just works, MAGIC.

If Ruffles have this single feature, it will open up Pandora's box, suddenly all the new JavaScript framework's power (JavaScript Artificial Intelligence Frameworks, QR Code generation, basically all of modern JavaScript power) will be bestowed/gifted back to our love, Flash ! 

What's old will be new again, Flash as an AMAZING GUI framework, will be back in FULL FORCE.

**Comment by Dinnerbone** [comment]
This is implemented in #1092
