### ISSUE TITLE
Escaping the Prison: sound effects play on loop instead of just once

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8067]
### Describe the bug

When choosing Drill and then Crowbar in [Escaping the Prison](https://www.newgrounds.com/portal/view/533001), the sound that plays for the arrows in the run scene won't stop playing and accumulate as you try more and more again. Keeping the browser console open reports no error during this part of the game.
Originally reported by @bottle2 in #2185.

### Expected behavior

Each sound effect should only play once.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 105

**Comment by LukeSaward1** [comment]
Can confirm this also happens on the swf linked in the speedrun.com resources of EtP. Not sure why it happens, could be the game just doesn't stop the music nor SFX when you fail here.

**Comment by mero09-99** [comment]
happened to me too

**Comment by n0samu** [comment]
We have a similar report from @Infinity48Games: 

> Escaping the Prison: Overlapping music when failing on badass route.
In the chase segment after choosing "Drill" at the beginning, after you lose the music continues and starts overlapping with other instances of itself after you retry.

**Comment by n0samu** [comment]
This is a regression - I've bisected it to commit 1f96af6b6408384e21688235d7401491d588a146 from #4452.

**Comment by waspennator** [comment]
Regression still seems to be present as of latest nightly it seems.
