### ISSUE TITLE
ruffle desktop app does not run

### ISSUE THREAD

**Issue by Joao364** [ruffle-rs/ruffle#8073]
### Describe the bug

hey when i tryed to play any swf file games in ruffle it just broke ruffle did not run in the background plz fix this bug i just wanted to use the ruffle desktop app

### Expected behavior

ruffle did not run at all in the desktop app

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Hi, please run the desktop app from the command line and provide the output that it gives you. Without this information, it is impossible to diagnose the problem.
