### ISSUE TITLE
SimGirls - Stretched text and missing line breaks

### ISSUE THREAD

**Issue by TheRightShoulder** [ruffle-rs/ruffle#808]
On Newgrounds #594476 and ingame with #791 but progressing requires text input.

This screenshot of the car minigame (yellow car on overworld map) demonstrates both, but the issues can be easily seen elsewhere. The "Do you want to rent a car?" and rental fee text also appear centered in flash player.

Maybe not text related but the memory usage jumps to around 5GB for the web player and desktop.

Ruffle:
![ruffle](https://user-images.githubusercontent.com/67752749/86497440-b5e57000-bd4f-11ea-96b3-8b032d8cb8e6.png)

Flash Player:
![flashplayer](https://user-images.githubusercontent.com/67752749/86497535-05c43700-bd50-11ea-9924-c5d96aa68e19.png)

**Comment by Herschel** [comment]
The stretched text is because device text can not be transformed, so any scale on the transform should be ignored (compare this to outline text fields which can be transformed as normal).
