### ISSUE TITLE
Error on https://archive.org/details/blaze-the-cat-dress-up

### ISSUE THREAD

**Issue by AuroraCiambrelli** [ruffle-rs/ruffle#8086]
# Error Info
Error name: TypeError
Error message: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
Error stack:
```
TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/blaze-the-cat-dress-up

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-09-19
Channel: nightly
Built: 2022-09-19T00:15:10.357Z
Commit: 9b9c95bfe28cb862d44e9517e94e9de73acd9de3
Is extension: false

# Metadata

**Comment by n0samu** [comment]
Hi, we've found a solution to this issue which you can find here: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#internetarchive
