### ISSUE TITLE
SandCastle Not Supported AS3 with Ruffle

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8129]
### Describe the bug

https://user-images.githubusercontent.com/80902993/193192697-6904a459-ad05-486d-9b7e-da7fa423388d.mp4

More Error
[www.y8.com-1664513514103.log](https://github.com/ruffle-rs/ruffle/files/9680841/www.y8.com-1664513514103.log)
[www.y8.com-1664513026758.log](https://github.com/ruffle-rs/ruffle/files/9680842/www.y8.com-1664513026758.log)
[www.y8.com-1664513011630.log](https://github.com/ruffle-rs/ruffle/files/9680843/www.y8.com-1664513011630.log)
[www.y8.com-1664512988943.log](https://github.com/ruffle-rs/ruffle/files/9680844/www.y8.com-1664512988943.log)

### Expected behavior

Flash Version (From Flash Storage Games)
https://user-images.githubusercontent.com/80902993/193192554-9d4e84cd-dc66-4bb3-8446-10f917bd2232.mp4

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge

### Additional information

https://www.y8.com/games/sandcastle

**Comment by n0samu** [comment]
This is a game that uses MochiCrypt, which needs a stub/implementation of `getBounds` (among other things, most likely)

**Comment by n0samu** [comment]
Now it's stuck on LocalConnection:
`Error dispatching event EventObject(EventObject { type: "init", class: flash.events::Event, ptr: 0x4ffbd0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x4ff20c }))) : RustError("Cannot set undefined property ::client on Some(flash.net::LocalConnection)")`

**Comment by Lord-McSweeney** [comment]
This game can now run, but has performance issues.

**Comment by n0samu** [comment]
@Lord-McSweeney The original issue is solved, so I am closing it. You could make a new issue for this game related to its performance, or maybe we should make one big issue listing all the known physics-based AVM2 games with performance issues?
