### ISSUE TITLE
https://z0r.de/7140 black screen, sound present

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#8163]
### Describe the bug

https://z0r.de/7140
Only sound, black screen

Nightly 2022-10-03

A bunch of errors, those "Event" errors are getting spammed indefinetely
![image](https://user-images.githubusercontent.com/75184268/193633954-760630f6-d4e1-4469-b582-8747533bed9b.png)

### Expected behavior

A fairly complex looking animation.
Reacts on mouse movements.
![Adobe7140](https://user-images.githubusercontent.com/75184268/193635585-bf0b092e-6d1a-45aa-bc7b-e131b668a511.gif)

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 106.0.5249.62

### Additional information

I guess it's a bunch of "unimplemented" but who knows, maybe some bugs exist too

**Comment by Lord-McSweeney** [comment]
`BitmapData.clone` has been implemented, but `BitmapData.draw` and `BitmapData.applyFilter` have not.

**Comment by Lord-McSweeney** [comment]
This now needs `DisplacementMapFilter` to display correctly.

**Comment by Lord-McSweeney** [comment]
Fixed by #12149.
