### ISSUE TITLE
Loading external SWF files as assets

### ISSUE THREAD

**Issue by fp07** [ruffle-rs/ruffle#820]
Hello,

Will there be any support for loading external SWF files as assets in Ruffle in AS3?

https://helpx.adobe.com/flash/kb/load-external-swf-swf.html

**Comment by kmeisthax** [comment]
Eventually, yes. We implemented all methods of loading movies in AVM1; and AVM2 has fewer entrypoints to worry about compared to AVM1. All of the work necessary to have clips and symbols from multiple movies interacting in a single movie network is already done. That being said, there's still a lot of work until exposing this to AVM2 is viable:

- Extremely MVP AVM2 interpreter (implemented, mostly, needs merge, is extremely basic, doesn't even include math or coercion support)
- Native class support (in progress)
- Host objects for the display tree
- MovieClip class impl
- Global-scope isolation (each ABC runs in a separate global scope that inherits from another, but in a weird way)
- VM barriers (Movies cannot be mixed-VM, AVM2 movies can load AVM1 but the two VMs are sandboxed from each other)
- Loader Class & new load actions for AVM2-initiated movie loads

This looks like six PRs worth of work, and we're only at about one and a half done.

**Comment by fp07** [comment]
Any update on this @kmeisthax, there has been a lot done I think from the PRs you mentioned above 💯

**Comment by torokati44** [comment]
I think this is now done.

**Comment by Lord-McSweeney** [comment]
Mixed AVM isn't working yet.

**Comment by Lord-McSweeney** [comment]
With the merge of #11005 all external files should match FP in loading.
