### ISSUE TITLE
Regression: Sound not synced with Ruffle logo animation

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8222]
### Describe the bug

SWF file: [RUFFLED.zip](https://github.com/ruffle-rs/ruffle/files/9730198/RUFFLED.zip)

In this Ruffle logo SWF, the audio is no longer synced with the animation:

https://user-images.githubusercontent.com/71368227/194452649-0395f859-c924-4bb1-ac78-40a300ca3b9f.mp4

### Expected behavior

The audio should be synced with the animation like it was in older Ruffle versions:

https://user-images.githubusercontent.com/71368227/194452916-63429266-2471-4837-aa4f-3d4eeb1f5155.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I've bisected the issue to commit 85cf383c84de574b4517ff250cb9e7904e77f128.

Looking at the SWF in JPEXS, I see that the frames without SoundStreamBlock tags are supposed to be silent, but instead they are continuing to play the audio stream now.

**Comment by kmeisthax** [comment]
This is my bug; I broke `StreamTagReader` when I added the ability for tag callbacks to stop tag reading early. Probably thought the original code was erroneously stopping on `ShowFrame` instead of yielding each `SoundStreamBlock` in sequence.
