### ISSUE TITLE
DropShadowFilter error on tawog game (AVM2)

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#8240]
### Describe the bug

loading up the amazing world of gumball: wheels of rage will fire up this error which keeps the game from loading

### Expected behavior

the game loads and the error does not pop up

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

log: [2022-10-08T10:19:01Z ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x230c96fb440 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x230dfbd1e88 }))) : RustError("Property does not exist: Multiname { ns: Single(Package(\"flash.filters\")), name: Some(\"DropShadowFilter\"), params: [], flags: (empty) }")

**Comment by n0samu** [comment]
This happens because the flash.filters class is not implemented yet. AVM1 has similar filters, which also are not implemented, so it will be a long time before AVM2 filters are implemented. Maybe stubbing them will help in the meantime, though.

**Comment by c4artisan** [comment]
stubbing DropShadowFilter allows the game to get into the title screen however clicking play will (obviously) make the game stop
