### ISSUE TITLE
Textures not displayed correctly on Ultimate Flash Sonic

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#8250]
### Describe the bug

select textures (the checkerboard on the title screen, the floor, and maybe more) are not displayed in ultimate flash sonic. this has gone on for multiple versions/commits and has gone unreported, and the issue is still there.
![Screenshot_758](https://user-images.githubusercontent.com/41709262/194781310-2e5957fa-b64d-4c15-8bc9-ec5c102897ae.png)
![image](https://user-images.githubusercontent.com/41709262/194781321-1b2cc478-75ab-4a0d-b6fb-32ad541e024a.png)

### Expected behavior

the textures are displayed with no problems whatsoever
![image](https://user-images.githubusercontent.com/41709262/194781345-63c38f78-ac6a-4a78-b841-d7f70b5d7b58.png)
![image](https://user-images.githubusercontent.com/41709262/194781361-2d581f2a-2bc1-4c6e-9c3f-ef6cf0cbc8e4.png)
(screenshots are from flash player)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by n0samu** [comment]
I've bisected this to commit 92044c9c0203f86d19bc7190757f90222c002025 from #7904.

**Comment by firoball** [comment]
Fixed by #8282

**Comment by relrelb** [comment]
Unfortunately there are still some more rendering issues on my end (Windows 11, with `AdapterInfo { name: "Intel(R) UHD Graphics 770", vendor: 32902, device: 18048, device_type: IntegratedGpu, backend: Vulkan }`):

![1](https://user-images.githubusercontent.com/17770360/195812743-95f21858-0615-426d-9885-aeeb1175dabd.png)
![2](https://user-images.githubusercontent.com/17770360/195812758-5dccde8f-a8da-4f9e-8c58-8ac691915a3c.png)

Weirdly enough these issues happened to me only 2 out of 3 plays. The other play was completely okay.

**Comment by n0samu** [comment]
Does the problem occur with the DirectX 12 backend? I also have an issue with the Vulkan backend, but DX12 is fine. I reported it in #7999.

**Comment by relrelb** [comment]
> Does the problem occur with the DirectX 12 backend? I also have an issue with the Vulkan backend, but DX12 is fine. I reported it in #7999.

It works fine with DirectX 12, so closing in favor of #7999.
