### ISSUE TITLE
Adblock Plus kills the Emulator

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#826]
Hello,

when activating adblock plus on my website i get the following error:

ruffle.js:formatted:1050 Serious error loading Ruffle: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
ruffle.js:formatted:1035 Serious error occured loading SWF file: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder

If I don't use it, it runs as expected. What can I do about it? Seems activating the extension will block something. This does not happen on newgrounds but on my website.

**Comment by Herschel** [comment]
Just to clarify, you are hosting Ruffle on your own website?

**Comment by desertking** [comment]
That's correct. I use the Polyfill (just one javascript line which detects the .swf). Without adblock plus activated it works fine on my site but when i activate it i get the error above. If I activate the adblock plus on newgrounds this doesn't happen.

**Comment by Dinnerbone** [comment]
Is it possible for us to see the site?

**Comment by desertking** [comment]
Yeah that's fine you can test with Dad'n Me 
https://www.spiele-umsonst.de/dadn-me-t478.html

Run on chrome without Adblock Plus activated and then with

**Comment by Dinnerbone** [comment]
I just tested it on Chrome and Firefox, but it works with Adblock Plus for me. However, with my usual uBlock Origin, it fails there.

It looks like Ruffle is loading a little bit - it seems to get stopped in its tracks at some point.
It may be with how they're blocking your pre-game ad, and that's having an effect on the ruffle element too. Interesting!

**Comment by desertking** [comment]
Hmm interesting. I never got it to work with adblock activated. Any workaround idea :) ?

**Comment by desertking** [comment]
For me it seems it must have some other reason: https://www.spiele-umsonst.de/ruffle/
This is a pretty simple setup and i get the error as well.

**Comment by desertking** [comment]
I think it seems to be related to a manual method how adblock tries to block something on my site:

https://www.spiele-umsonst.de/ruffle/

Blocked 1 Element 

ruffle.js:1 Serious error loading Ruffle: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
(anonymous) @ ruffle.js:1
ruffle.js:1 Serious error occured loading SWF file: CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder

https://www.izzygames.com/ruffle/

Works fine

Same setup

**Comment by desertking** [comment]
It was a rule used by adblock that made this error on chrome. I wrote to them and they removed the rule
