### ISSUE TITLE
Error on http://127.0.0.1:9090/iemain.html

### ISSUE THREAD

**Issue by Deelout** [ruffle-rs/ruffle#8265]
# Error Info
Error name: TypeError
Error message: Cannot read properties of undefined (reading 'get')
Error stack:
```
TypeError: Cannot read properties of undefined (reading 'get')
    at chrome-extension://lcpgmmoikefgnibaacmlaeeponnmdkad/dist/ruffle.js?id=80562221695:1:5424
    at async M.ensureFreshInstance (chrome-extension://lcpgmmoikefgnibaacmlaeeponnmdkad/dist/ruffle.js?id=80562221695:1:23537)
    at async M.load (chrome-extension://lcpgmmoikefgnibaacmlaeeponnmdkad/dist/ruffle.js?id=80562221695:1:26402)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: http://127.0.0.1:9090/plugin/rtmp-streamer/RtmpStreamer.swf
Param allowScriptAccess: always
Param movie: http://127.0.0.1:9090/plugin/rtmp-streamer/RtmpStreamer.swf
Param quality: high
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: http://127.0.0.1:9090/iemain.html#/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-10
Channel: nightly
Built: 2022-10-10T00:16:25.636Z
Commit: 10c19fef5751b3fd648fb997864f953de9ce9a72
Is extension: true

# Metadata

**Comment by n0samu** [comment]
The provided URLs are local URLs that we cannot access. Nevertheless, from only the URL I understand that your app is related to RTMP streaming, which is not supported by Ruffle and likely won't be for the foreseeable future. You will need to look at other options to restore Flash Player or use an alternative app.
