### ISSUE TITLE
MotionBlur is not showing.

### ISSUE THREAD

**Issue by BracerJack** [ruffle-rs/ruffle#827]
Open the file in the official Flash Player, press the button and you will see it move down with amazing motionblur.
To see it again, you have to restart the file, sorry, I made this just to test.

Run this in ruffles, it works, but no motionblur.

https://a.uguu.se/UjYiHEcdJ0wV_Demo.swf
Files available for 24 hours.

**Comment by Herschel** [comment]
This uses a blur filter (cc #15) along with a BitmapData to render the effect.

**Comment by MrCheeze** [comment]
Here's another swf I ran into where the blur filter doesn't have any effect yet. The shadowed man who appears at the start always has a blur filter applied.

https://www.homestuck.com/flash/hs2/00871/00871.swf
