### ISSUE TITLE
Sushi Cat - The all time classic almost works. Just doesn't release the cat (AS3)

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#8272]
### Describe the bug

https://www.newgrounds.com/portal/view/529334?emulate=flash - Sadly the cat is not released when i click the mouse button. Everything else seems to work mostly at first glance. Maybe it's a quick fix here?

0183127e:0x4b0680 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2668f10 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1d89744 }))) : RustError("Cannot access property ::volume of null or undefined")

Maybe it has to do with that?

### Expected behavior

Cat should be released on LMB click.

### Affected platform

Self-hosted version

### Operating system

All

**Comment by Lord-McSweeney** [comment]
This looks like it also needs BevelFilter: `ERROR core/src/avm2/events.rs:422 Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0x40dee00 }) to handler FunctionObject(FunctionObject { ptr: 0x3661788 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(\"flash.filters\")), name: Some(\"BevelFilter\"), params: [], flags: (empty) }")`. This error appears whenever you click (try to release the cat).

**Comment by Lord-McSweeney** [comment]
Since `drawPath` has been stubbed, the cat falls now, but performance is very bad, and the cat is mostly invisible due to the stub.

**Comment by desertking** [comment]
Yeah I saw that already. So sad that the performance on many games when it comes to "collisions" or other physic events, particles whatever is so bad. I guess at this point 10~20% of the games could be playable with better performance. At least from what I tested.

**Comment by waspennator** [comment]
I'm assuming the cats visible now that graphics.drawpath is implemented now?

**Comment by n0samu** [comment]
Yes. Hopefully we can improve the performance eventually 😅
