### ISSUE TITLE
Derpy Cardcaptor: Preloader softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#8273]
### Describe the bug

Animation gets stuck on the preloader and can't do the right click trick to get it to play. I believe it used to work on an older version with slight graphical issues, but the play button is unclickable as of the latest version.

https://www.newgrounds.com/portal/view/584966/format/flash

### Expected behavior

For the play button to start the animation when pressed......... or to show signs of being pressable at all when hovering over it.

### Affected platform

Browser's extension

### Operating system

Android 12

### Browser

Chrome 106

**Comment by n0samu** [comment]
Yes, it works as of build 2022-08-19 but seems to have regressed later in August. Maybe something was changed in the mouse pick logic around then.

**Comment by waspennator** [comment]
Strangely enough, hovering over the letter with subtitles seems to work fine, it's just all the other buttons that don't work.

**Comment by waspennator** [comment]
Retested again just for clarification, still broken, but it seems like it's just the play button that's not working, I can highlight and click the letter with subtitles in the middle and the quality control buttons on the bottom left.

**Comment by n0samu** [comment]
This was broken by #7719 (3629a55c00409b68db37517016bbf37e5b69e2db)

**Comment by waspennator** [comment]
Fixed as of the latest nightly build, tested on an archived NG page with the animation since NG has yet to rebase on version 2/18/23.
