### ISSUE TITLE
DR3i: Clicking "Play next" doesn't proceed to next level

### ISSUE THREAD

**Issue by Kaube** [ruffle-rs/ruffle#8293]
### Describe the bug

1. Open the game ([DR3I.swf.zip](https://github.com/ruffle-rs/ruffle/files/9791260/DR3I.swf.zip))
2. Click Start and clear level.
3. Click "Play next"

Step 3 does not result in proceeding to the next level.

Note: Video has no sound.

https://user-images.githubusercontent.com/23202586/195971394-deff5741-a55a-4189-a955-0bb7847e3c1e.mov

### Expected behavior

Step 3 should result in proceeding to the next level.

### Affected platform

Desktop app

### Operating system

macOS Monterey

**Comment by n0samu** [comment]
@Toad06 pointed out on Discord that this is likely the same issue as #1108. And after testing this with an autoclicker program, I agree. If I set the autoclicker to click fast enough, it successfully clicks the button.

**Comment by n0samu** [comment]
Fixed by #10862
