### ISSUE TITLE
[Crystal Island] The ball will never move

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#832]
https://www.y8.com/games/crystal_island

When you press the left or right key, the ball is supposed to go in the indicated direction, but this never happens in Ruffle. However, the inputs seem to be registered, as the ball plays its animation. Space bar (jumping) works as intended.

I'm not sure at all (as usual lol) but the issue could be somewhere around these lines:

```
on(keyPress "<Right>"){
   if(/rocket:dood eq "uit")
   {
      xspeed = xspeed + /trig:cos;
      call(/trig:cos);
```

**Comment by Herschel** [comment]
Didn't know you could pass a MovieClip path to a `call` action! `call(/trig:cos)` needs to resolve to the `trig` movie clip and search for the `cos` frame label.
