### ISSUE TITLE
when will ActionScript 3 be supported

### ISSUE THREAD

**Issue by MikecraftTheCoder** [ruffle-rs/ruffle#8325]
I would like to know when you are planning to support ActionScript 3?

**Comment by mero09-99** [comment]
Actionscript 3 support has already started, but is on basic support for now.
These is no set date it will be finished. Be sure to update Ruffle daily.

**Comment by n0samu** [comment]
See the FAQ: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users
Closing in favor of #1368.
