### ISSUE TITLE
New Club Penguin not supported ruffle player

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8330]
### Describe the bug

https://user-images.githubusercontent.com/80902993/196750362-eb8831bc-c234-41c8-aa41-40d783b669d0.mp4

it's not working, because this is multi files, this is actionsupport 3.0
i know ruffle player multiplayer is not working

### Expected behavior

![Screenshot 2022-10-19 192944](https://user-images.githubusercontent.com/80902993/196750531-8067cbf3-45b9-403d-88e4-334f636bac67.jpg)
you know ''Download'' and ''Launch NewCP App'' it's can work with flash player, his server it's working

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge

### Additional information

from https://newcp.net/en/

**Comment by Lord-McSweeney** [comment]
Still not working. Direct SWF: https://media1.newcp.net/play/v2/client/club_penguin.swf
Right now, it's erroring with `Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xb78470 }) to handler FunctionObject(FunctionObject { ptr: 0xb77fb0 }) : RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)")`

**Comment by Lord-McSweeney** [comment]
With #9647, this errors on `ERROR ruffle_core::avm2::activation: ReferenceError: Error #1069: Property * not found on XMLList and there is no default value.`.

**Comment by Lord-McSweeney** [comment]
Now errors: `Error: MainContext could not determine the locale for the specified langauge. Make sure that 'null' has been added to the switch.`.

**Comment by AllinolCP** [comment]
> Now errors: `Error: MainContext could not determine the locale for the specified langauge. Make sure that 'null' has been added to the switch.`.

This is related to flashvars not being provided (e.g. lang=en)

**Comment by evilpie** [comment]
I investigated this and made some progress, but got stuck at some point with something related to `contextView`. This game really needs a lot of stuff. What I've found:
- [ ] `-Plang=en` as @AllinolCP said
- [ ] `decodeURI`
- [ ] `ExternalInterface.call("window.location.href.toString")`
- [ ] XML.parent (#10244)
- [ ] `URLRequest.requestHeaders`

**Comment by Lord-McSweeney** [comment]
This URL works for the page: https://play.newcp.net/eng/index.html#/login

**Comment by Lord-McSweeney** [comment]
@AllinolCP pointed out on Discord that this is caused because of undocumented behavior in `flash.utils.describeType`, as `describeType` should also return `<metadata>` tags inside `<variable>` tags (if there is metadata). Example:
```
  ...
  <variable name="mc" type="flash.display::MovieClip">
    <metadata name="tag">
      <arg key="" value="value"/>
    </metadata>
    <metadata name="someOtherTag"/>
    <metadata name="tag">
      <arg key="dat" value="abcd"/>
    </metadata>
  </variable>
  ...
```

Which is returned by the property:
```
      [tag("value")]
      [someOtherTag]
      [tag(dat = "abcd")]
      public var mc:MovieClip;
```

**Comment by Lord-McSweeney** [comment]
After #11275, this needs HTTPStatusEvent to be implemented correctly. I induced a panic after implementing that:
```
thread 'main' panicked at 'No caller domain available - use Activation::from_domain when constructing your domain', core/src/avm2/activation.rs:681:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:135:5
   3: core::panicking::panic_str
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:119:5
   4: core::option::expect_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:1879:5
   5: ruffle_core::avm2::function::Executable::exec
   6: <ruffle_core::avm2::object::class_object::ClassObject as ruffle_core::avm2::object::TObject>::construct
   7: ruffle_core::player::Player::update
   8: ruffle_core::loader::Loader::load_url_loader::{{closure}}
   9: ruffle_desktop::executor::GlutinAsyncExecutor::poll_all
  10: ruffle_desktop::player::PlayerController::poll
  11: ruffle_desktop::app::App::run::{{closure}}
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  13: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  14: winit::platform_impl::platform::x11::EventLoop<T>::run
```

**Comment by elmemeee** [comment]
has this been fixed? i have been waiting a long time but the only thing that is showing is a white screen.

**Comment by DarkReaper231** [comment]
It still has problem with some language related stuff
```
ERROR core/src/avm2/events.rs:424 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x127b638 }) to handler FunctionObject(FunctionObject { ptr: 0x127b130 }) : Error: MainContext could not determine the locale for the specified langauge. Make sure that 'null' has been added to the switch.
```

**Comment by Lord-McSweeney** [comment]
@DarkReaper231 You need to run it directly through the site, it uses flashvars. See https://github.com/ruffle-rs/ruffle/issues/8330#issuecomment-1475094475
@elmemeee If you bump the execution timeout, it gets as far as it would get on Flash. For some reason one of the necessary asset files is missing from the NewCP server.

**Comment by Lord-McSweeney** [comment]
The next issue seems to be that NCP calls External Interface with `(function() { ... })` (or something similar, don't exactly remember what) as the argument. Ruffle doesn't support that yet.

**Comment by DarkReaper231** [comment]
> The next issue seems to be that NCP calls External Interface with `(function() { ... })` (or something similar, don't exactly remember what) as the argument. Ruffle doesn't support that yet.

Is there a PR for implementation of it?

**Comment by SolsticeSpectrum** [comment]
@Lord-McSweeney Okay so visiting through https://play.newcp.net/eng/index.html#/login instead of https://newcp.net/plays?force=true#/login does indeed gets me further but it still complains about missing sfw, Ruffle should just skip this as original Flash does.

**Comment by Dinnerbone** [comment]
With LocalConnection (WIP local branch), this progresses but still doesn't get past a blue screen.

I can see that it's trying to show a login screen, but it just isn't :(

**Comment by ChrisCPI** [comment]
This isn't directly related to NewCP, but just thought it was worth pointing out.
With the recent updates, I figured I'd test another CPPS that uses the AS3 client (https://play.cpimagined.net)

It does, in fact, get all the way to the login screen, but shows an error after a few seconds when trying to login, which I suppose was to be expected.
![image_2024-06-21_143606923](https://github.com/ruffle-rs/ruffle/assets/92183829/ed3e367b-070c-49e8-8eef-23844d8beb44)
![image_2024-06-21_143652026](https://github.com/ruffle-rs/ruffle/assets/92183829/59c1a403-b056-4ad9-aae6-b34343c6ca7e)

**Comment by AllinolCP** [comment]
yes, because CPImagined would have to set up the WS proxy, the error shown  was just shown to macOS users for some reason

**Comment by Dinnerbone** [comment]
With #16834 newcp.net works. Please open individual issues for any further bugs you find (or other sites if they have issues too, ofc)
