### ISSUE TITLE
weird bug on  https://bonuslevel.org/games/game_hog-pop_8.html

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#8348]
### Describe the bug

the game in question does not start and only shows a white scrren but you can right click on the ruffle menu but if functions just fine  in a normal flash browser for reference i am using puffin browser as the flash browser for testing it works just fine

https://bonuslevel.org/games/game_hog-pop_8.html

![hogpop](https://user-images.githubusercontent.com/64484245/197315537-f4f87dd0-b08f-4cf7-a5c7-dc004799adb4.png)

this using puffin browser as the comparision test
![realhogpop](https://user-images.githubusercontent.com/64484245/197315761-b824ec16-df47-4380-b78c-81fe283c6edc.png)

### Expected behavior

for the game to start like most websites

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 106.0.5249.112 (Official Build) (64-bit)

### Additional information

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://bonuslevel.org/games/game_hog-pop_8.html
SWF URL: https://bonuslevel.org/guploads/blapi.swf?gid=8&stw=500&sth=500&hl=42&packid=-1

# Browser Info
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-10-21
Channel: nightly
Built: 2022-10-21T00:19:26.241Z
Commit: 4cb122461ee5c892a2801077d3173b531e79cb83
Is extension: true

# Metadata
width: 500
height: 500
frameRate: 35
numFrames: 3
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 195053

**Comment by n0samu** [comment]
This site is using a script that conflicts with Ruffle, specifically MooTools. Same problem as #6065, #2567 and #2463.

**Comment by danielhjacobs** [comment]
The MooTools issue should be fixed by #14215. I don't think the content is working 100% still, so feel free to test it again tonight. If it's not working, edit and re-open this issue or open a new issue for the remaining problems.
