### ISSUE TITLE
[Mario's Adventure 2] The map will not load

### ISSUE THREAD

**Issue by BubblyPopper** [ruffle-rs/ruffle#835]
Ruffle:
![image](https://user-images.githubusercontent.com/41709262/87114227-eda75880-c224-11ea-801d-338df272c48b.png)
Flash:
![image](https://user-images.githubusercontent.com/41709262/87114296-162f5280-c225-11ea-8882-41eb820c90c1.png)

**Comment by Herschel** [comment]
Looks like this works now.
