### ISSUE TITLE
Hard Hat Hustle - Glitch at start screen

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#836]
Ruffle:
![image](https://user-images.githubusercontent.com/41709262/87126164-97481300-c240-11ea-9e21-02d0d733a575.png)
Flash:
![image](https://user-images.githubusercontent.com/41709262/87126204-aaf37980-c240-11ea-83ce-4deb3c62d04b.png)

**Comment by BubblyPopper** [comment]
NOTE: The start screen in ruffle has a glitch where gumball goes in a falling loop rendering the game unplayable

**Comment by Lord-McSweeney** [comment]
This SWF experiences the line-drawing bug where lines are drawn too thinly.

**Comment by c4artisan** [comment]
the game has been working for a while now
