### ISSUE TITLE
Load fake device font from external SWF file

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8387]
**Describe the feature**
Right now, Ruffle has one hardcoded "fake device font" (Noto Sans) that is embedded in the binary as a raw DefineFont3 tag. As a first step towards making Ruffle more flexible, it would be great if Ruffle could be changed to load the font from an external SWF file instead. The Ruffle repo already has a `noto-sans.swf` file: https://github.com/ruffle-rs/ruffle/tree/master/core/assets
So I think it would be a matter of changing Ruffle to load and parse the SWF file and then load the DefineFont3 tag within it. 
Once that is accomplished, it would be great if Ruffle could load multiple fonts from the SWF file, and support loading fonts from DefineFont/DefineFont2 as well. Then people could use a variety of methods to create font SWF files tailored to the specific content that they're trying to play. For example, people could use Font2SWF from the [SWFTools package](http://www.swftools.org/) to easily create their own device font SWF.

I'd also like to note that AwayFL supports this feature already, as seen here: https://github.com/eXponenta/away-player-embed
AwayFL loads its default fonts from a fonts.swf file at runtime, and users can specify additional font SWF resources as well.

**Comment by ActionWavele** [comment]
Yes please, I would verh much like my language supported

**Comment by MrCheeze** [comment]
Implemented by https://github.com/ruffle-rs/ruffle/pull/13604 !
