### ISSUE TITLE
HitBox: Black screen on level 9

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8393]
### Describe the bug

#8199 has been fixed, but a very similar bug is now occurring on level 9. This error message is displayed in the terminal:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x18c267f8320 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x18c0f7c6a18 }))) : RustError("Cannot access property ::x of null or undefined")`

SWF URL: http://i.notdoppler.com/files/hitbox.swf

### Expected behavior

Level 9 should load and be playable.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by adrian17** [comment]
@n0samu I think this got fixed at some point, can you confirm?

**Comment by n0samu** [comment]
Ah yes you're right, this is fixed now!

**Comment by n0samu** [comment]
I've tested the relevant commits and it looks like this was fixed by #8343.
