### ISSUE TITLE
Mario Combat crashes Windows or crashes Ruffle with an invalid instruction error

### ISSUE THREAD

**Issue by CelestialAmber** [ruffle-rs/ruffle#840]
Description: It seems to sometimes just cause Windows 10 to freeze, but sometimes I get an invalid instruction error back, then Ruffle crashes without completely crashing Windows.

Version: Tested on the latest version. (ruffle_windows_2020-07-09_ecbab53.zip)
Link to SWF: [Mario Combat.zip](https://github.com/ruffle-rs/ruffle/files/4905002/Mario.Combat.zip)

Sorry for initially posting the issue only partially complete, I was trying to press enter while typing the title thinking it wouldn't submit it, and it ended up submitting it early. 😅

**Comment by Dinnerbone** [comment]
Is there a crash log or any error message? Can you please link to the swf? Which version did you test?

Thanks!

**Comment by CelestialAmber** [comment]
I tried it on Mac, and it's able to boot and go in-game.

**Comment by CelestialAmber** [comment]
It also works fine on the web version, so I guess either it's on my end or an issue with Ruffle for Windows. I don't see how it would be the former though, but maybe.

**Comment by CelestialAmber** [comment]
It's fixed now. Sorry for not checking for a while.
