### ISSUE TITLE
Plant Pong: Cannot break glass bricks

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8417]
### Describe the bug

Link to the game: http://www.thepencilfarm.com/games/plant_pong/
On level 6 of Plant Pong, hitting a glass brick 3 times is supposed to destroy it. But that does not happen. 

This error is shown in the terminal:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1640a452c00 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x16448bd0ac8 }))) : RustError("Cannot access property ::pan of null or undefined")`

The relevant AS3 code is under the Brick class:
```
               _loc1_ = new GlassBreakSnd();
               _loc2_ = new SoundChannel();
               _loc3_ = _loc2_.soundTransform;
               _loc3_.pan = this.x / (Settings.SWF_W / 2) - 1;
               _loc2_.soundTransform = _loc3_;
               _loc2_ = _loc1_.play();
               trace("brick broken");
               addEventListener(Event.ENTER_FRAME,playGlassAnimation);
```
`soundTransform` seems to be implemented in Ruffle already, so I don't understand why this problem is occurring.

### Expected behavior

The glass brick should break after being hit 3 times.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Tested with #8397, which fixes the previous issue with this game.

**Comment by Lord-McSweeney** [comment]
Is `pan` used anywhere else?

**Comment by n0samu** [comment]
Fixed
