### ISSUE TITLE
Vox Populi, Vox Dei(a werewolf thriller): No Intro

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8429]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/199228862-be761032-41d1-47e0-b30d-59e308223e59.png)

```
[2022-11-01T12:03:11Z ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "component_api_available", class: com.kongregate.as3.client.events::KongregateEvent, ptr: 0x1f4e641c950 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1f4e6384018 }))) : RustError("VerifyError: Trait _canvas in class Scene has same name as trait _canvas in class WorldObject, but does not override it")
```

### Expected behavior

![image](https://user-images.githubusercontent.com/75534590/199229293-d224afda-4e95-4c4e-bddf-c40b02c27843.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF: https://www.kongregate.com/games/weremsoft/vox-populi-vox-dei-a-werewolf-thriller/

**Comment by n0samu** [comment]
It's not just no intro - the game doesn't work at all.

**Comment by n0samu** [comment]
#9506 progresses this a little, but there's still a blank screen and now there's this error:
`ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "component_api_available", class: com.kongregate.as3.client.events::KongregateEvent, ptr: 0x241ccc9e120 }) to handler FunctionObject(FunctionObject { ptr: 0x241c0fc6680 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"flash.display\"))), name: Some(\"Shader\"), params: [], flags: (empty) }")`

**Comment by adrian17** [comment]
Yeah, Shader will be one of the hardest ones to support :/
