### ISSUE TITLE
Layering issue with Sniper Assassin

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#8450]
### Describe the bug

You're able to see the world around you, but you're unable to see down the scope, when it should be the other way around.
![image](https://user-images.githubusercontent.com/12412764/199383878-cd563bc9-2078-4816-879d-5af1cd2c34db.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/12412764/199384523-6d0ea891-6a6b-4acb-a01c-28370e911a22.png)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Additional information

Vulkan, DX12 and OpenGL all gave out the same issue.

**Comment by n0samu** [comment]
Hi, can you provide a link or attachment for the game?

**Comment by Spikestuff** [comment]
Sure: [sniperassassin.zip](https://github.com/ruffle-rs/ruffle/files/9915592/sniperassassin.zip)
(Doing attachment cause it's easier)

**Comment by p0008874** [comment]
Fixed on latest nightly.

**Comment by Lord-McSweeney** [comment]
Fixed by #10315.
