### ISSUE TITLE
web: Pursuit of Hat: Terrain not shown

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8451]
### Describe the bug

The first few levels of [Pursuit of Hat](http://i.notdoppler.com/files/pursuitofhat.swf) were previously working, but as of version 2022-11-02, the level terrain is not shown at all in web builds of Ruffle. The problem does not affect the desktop app.
![image](https://user-images.githubusercontent.com/71368227/199400454-d3266ecb-532a-4edb-83f3-acb46ecfcf44.png)

### Expected behavior

The level terrain is visible in build 2022-11-01 and earlier.
![image](https://user-images.githubusercontent.com/71368227/199400525-8c30b315-01c6-464e-acc4-b5b533100c90.png)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 106

### Additional information

I bisected the problem to #8397. But I don't understand how that PR could have caused this problem.

**Comment by n0samu** [comment]
Here are Adrian's comments from Discord:
> They have a class that "optimizes" shape drawing by bitmapdata.draw()ing it and replacing the shape with the bitmap.
Previously it was "crashing" on .getRect() so the replacement didn't happen, so Ruffle was drawing the original shape.
But now it doesn't crash, and webgl bitmapdata.draw() silently does nothing, so Ruffle draws an empty bitmap instead.
So, I think it should fix itself with webgl draw()?

So this needs #6629.

**Comment by Lord-McSweeney** [comment]
Will be fixed by #9134.
