### ISSUE TITLE
Sugar, Sugar: Black screen after beating level 1

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8453]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/sugarsugar.swf
The first level of *Sugar, Sugar* is playable in the Ruffle desktop app. But after beating it, the game gets stuck on a black screen. These errors are repeated:
```
[ERROR ruffle_core::avm2::activation] AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x14ae5c18018 }))))
[ERROR ruffle_core::avm2::activation] ReferenceError: Error #1069: Property close not found on flash.net.SharedObject and there is no default value.
```
This looks like a method that could be stubbed to get the game working.

### Expected behavior

The second level should load after beating the first.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by mero09-99** [comment]
this is a great game, would love to see it fixed
