### ISSUE TITLE
Error on https://res-mspt.gamesow.com/bin/WebLaucher.html

### ISSUE THREAD

**Issue by JoaoBoll** [ruffle-rs/ruffle#8456]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:573:14
Error stack:
```
966/W/n.wbg.__wbg_new_f9bb493369a83c12@moz-extension://9541b17f-a2af-46ce-903c-a9d345515030/dist/966.js:1:6803
std::sync::once::Once::call_once::{{closure}}::hbf2034d80a3bea7d@:wasm-function[1221]:0x2ca764
std::sync::once::Once::call_inner::hb30cfbde5209eed0@:wasm-function[1499]:0x31a183
core::ops::function::FnOnce::call_once{{vtable.shim}}::hc013e36522e0a1cf@:wasm-function[4914]:0x48e02b
std::panicking::rust_panic_with_hook::hb09154fa23e06c37@:wasm-function[3609]:0x44b891
core::panicking::panic_fmt::h9e229748e3ae9f9d@:wasm-function[5135]:0x4927c2
core::option::expect_failed::ha758e0d1c5165b94@:wasm-function[5816]:0x4a4d56
ruffle_core::display_object::stage::Stage::root_clip::h7047f37477870836@:wasm-function[3583]:0x449298
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6215d2c89f7a163c@:wasm-function[1106]:0x29eda3
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he8b001728fe53d0d@:wasm-function[1043]:0x28a77f
wasm_bindgen_futures::queue::Queue::new::{{closure}}::ha20cb871d1d19dc5@:wasm-function[2306]:0x3cddb2
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he1030d2cce2f2dd2@:wasm-function[5505]:0x49c53a
closure2937 externref shim@:wasm-function[5633]:0x49f6ff
C@moz-extension://9541b17f-a2af-46ce-903c-a9d345515030/dist/966.js:1:2728
c@moz-extension://9541b17f-a2af-46ce-903c-a9d345515030/dist/966.js:1:2253

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://res-mspt.gamesow.com/bin/WebLaucher.html?userid=1387139&username=1387139&cm=1&server_id=S39&time=1667403440&server_name=S39&flag=7d0345e0bd7490ead0c6f67c69682d16
SWF URL: https://res-mspt.gamesow.com/bin/WebLaucher.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-01
Channel: nightly
Built: 2022-11-01T00:19:43.674Z
Commit: da02dc453d8ef2403dda19b2d48f7f0e7734d6d5
Is extension: true

# Metadata
width: 1000
height: 600
frameRate: 24
numFrames: 1
swfVersion: 9
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 26568

**Comment by Lord-McSweeney** [comment]
Panic fixed by #10026.
