### ISSUE TITLE
Deep Freeze: Button Filter Effects

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8457]
### Describe the bug

https://user-images.githubusercontent.com/75534590/199538442-1dbc0c46-ef38-455c-919c-30aef3381d02.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/199538531-c12590d2-2585-4e54-bd9d-709593294775.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF: http://cache.armorgames.com/files/games/deep-freeze-127.swf

**Comment by LukeSaward1** [comment]
Filters are not implemented yet.

**Comment by p0008874** [comment]
Blur is back but has been cut.
