### ISSUE TITLE
Toxic 2 (Nitrome game)

### ISSUE THREAD

**Issue by YellowTemperance** [ruffle-rs/ruffle#8462]
### Describe the bug

Hello there! Just a couple days ago, I found a swf for one of my most beloved childhood flash games, Toxic 2. Unfortunately, upon booting it up in Ruffle, I found a myriad of different issues that cause the game to be unplayable in its current state.
[Toxic_2.zip](https://github.com/ruffle-rs/ruffle/files/9925682/Toxic_2.zip)

### Expected behavior

I'll provide a list of all of the problems I've found with the game in Ruffle

- Nothing can take damage, at all. Not you the player, or any of the enemies. The only way the player can take damage is by instakilling themselves in (most) pits of acid, usually the ones found at the bottom of a level. 
- The player cannot pick up any other bomb types. 
- Destructible tiles cannot be destroyed. Upon being bombed, it will show the texture of a destroyed tile, except it's filled with a kind of green screen (shown in the enclosed image). This change is purely visual, as the player will not interact any differently with the "destroyed" tile.
- Text boxes will not appear. Normally, I wouldn't find this to be too much of a bad thing, except that this softlocks you in the first section of the entire game. 
These are just all the problems that I've found with it, there may be more.
![Screenshot 2022-11-02 10 59 08 PM](https://user-images.githubusercontent.com/117334141/199650967-cdced0f2-a021-4090-80f1-26955c542ec9.png)

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Google Chrome 103

### Additional information

Best of luck to anyone who wants to attempt to fix this! I will greatly appreciate it.

**Comment by YellowTemperance** [comment]
As far as I am aware, the game does not work in both the browser extension and the online demo. However, I cannot speak for the other versions of Ruffle, though I have a hunch it's the same in those.

**Comment by n0samu** [comment]
How did you get past the first screen to test this stuff? I can't even get to any of the pits of acid because of the problem described in #3086.

**Comment by YellowTemperance** [comment]
> How did you get past the first screen to test this stuff? I can't even get to any of the pits of acid because of the problem described in #3086.

I also found a file that has all of the levels unlocked. Probably should have linked that too from the beginning, sorry about that. '^-^
[toxic2_IGTv2.zip](https://github.com/ruffle-rs/ruffle/files/9934265/toxic2_IGTv2.zip)
Here you are!

**Comment by n0samu** [comment]
Got it, thanks!

**Comment by MinekPo1** [comment]
I can confirm that all but the second issue (now tracked in #3086) no longer occurs
