### ISSUE TITLE
Chronotron: Levels 32 and 33 are broken

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8463]
### Describe the bug

In level 32 of [Chronotron](https://www.kongregate.com/games/scarybug/chronotron), there are some obstacles above the top of the screen that are supposed to periodically move downwards and slam into the floor. But in Ruffle, the obstacles seem to hit the top of the screen and never make it down to the floor. Basically it seems like the collision detection is treating the top of the screen as solid, preventing the obstacles from passing through.

https://user-images.githubusercontent.com/71368227/199654581-07513ca7-b21d-4955-8748-31367f214de6.mp4

Also, level 33 is impossible to complete because the collision between the box and the switch on the left side of the seesaw does not activate the switch. Since the switch does not activate, the platform does not move upwards like it's supposed to.

https://user-images.githubusercontent.com/71368227/199661834-b928f8c0-2ff9-464b-a3ff-c7caee77a606.mp4

Since it would take a lot of time to get all the way to level 33, I've uploaded both the SWF file and a .sol save file that unlocks all the levels up to 33: [chronotron.zip](https://github.com/ruffle-rs/ruffle/files/9925893/chronotron.zip)

### Expected behavior

**Level 32:**

https://user-images.githubusercontent.com/71368227/199655258-11b2070d-a736-40e6-b2da-de54e3eb2e35.mp4

**Level 33:**

https://user-images.githubusercontent.com/71368227/199661977-53f220cf-95c0-4a08-b2ad-57f242b73f8f.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I'm guessing that this is a hitTest issue. But unlike some of the recent hitTest issues, this is not a recent regression; Ruffle builds from early 2022 have the same problem.

**Comment by mero09-99** [comment]
is this a game that has a hacked sitelock?

**Comment by n0samu** [comment]
Yes I hacked the sitelock out but that's not relevant to this issue :)
