### ISSUE TITLE
Trampoline Trickz 2 "Start" button doesn't work

### ISSUE THREAD

**Issue by Nicholas-Steel** [ruffle-rs/ruffle#8472]
### Describe the bug

Load the program and on the main menu click "Start" to begin gameplay, instead of starting gameplay, the game will remain on the main menu. The other buttons on the main menu work as expected.

### Expected behavior

"Start" button on the games main menu should initiate gameplay.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Latest stable Firefox, Windows 10

### Additional information

http://home.exetel.com.au/franpa/Games/trampoline.swf

**Comment by Nicholas-Steel** [comment]
http://home.exetel.com.au/franpa/Games/trampoline.swf

**Comment by n0samu** [comment]
This problem also occurs in the real Flash Player so I don't think this is an issue with Ruffle. The game seems to be missing a required asset: `http://home.exetel.com.au/franpa/Games/_server/tramp_scores_swf.txt`

**Comment by n0samu** [comment]
Hmm... I see now that the game works in Adobe Flash Player version 9 from here: https://archive.org/details/MacromediaFlashProjectors.7z
So I guess something changed later on in Flash Player that broke this game. Maybe Ruffle can get it working after all.

**Comment by CUB3D** [comment]
This game gets the current player version like so:
```
var v = _root.$version;
flashversion = Number(v.substr(v.indexOf(" ") + 1,1));
```
Which for the current player version of 32 results in `flashversion = 3`

In frame1/defineButtton2(71):
```
if(_root.flashversion >= 5)
{
  _root.gotoAndPlay(2);
}
```

Changing the player version to anything where the first digit >= 5 makes the button work again.
