### ISSUE TITLE
Can't initiate main gameplay in Wrath II 

### ISSUE THREAD

**Issue by Nicholas-Steel** [ruffle-rs/ruffle#8473]
### Describe the bug

- Open the program and skip past the "Avoid colliding with the walls" minigame.
- Skip the Intro
- Click "Play Easy"
- Can't progress past the next screen to start gameplay.

### Expected behavior

I should be able to progress to gameplay.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Latest stable Firefox

**Comment by Nicholas-Steel** [comment]
http://home.exetel.com.au/franpa/Games/Wrath_II.swf

**Comment by n0samu** [comment]
This website actually has an incomplete copy of the SWF file: only the first 555KB of what should be a 1.2MB file. You can play the game on a different website instead, such as Y8: https://www.y8.com/games/wrath_ii

**Comment by Nicholas-Steel** [comment]
So it turns out this wasn't the only issue, this game is affected by browser zoom level. Setting it to 100% and reloading the SWF was needed to get the UI to show correctly.

**Comment by n0samu** [comment]
I am unable to reproduce this problem. Can you describe the symptoms and steps to reproduce in more detail?
