### ISSUE TITLE
Wrath II - Various UI buttons require several/random amount of clicks to function

### ISSUE THREAD

**Issue by Nicholas-Steel** [ruffle-rs/ruffle#8482]
### Describe the bug

https://www.youtube.com/watch?v=BkFxhp3gs-8

The Scroll/Parchment UI seen when clicking Easy Game/Hard Game, between levels and when clicking the "i" button, has buttons that require a variable amount of mouse clicks to register that I'm clicking them. You can see & hear this in the video.

### Expected behavior

These UI elements should only need a single mouse click to register.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Latest stable Firefox

### Additional information

Game is loaded directly, not embedded in a website.
http://home.exetel.com.au/franpa/Games/Wrath_II.swf

**Comment by n0samu** [comment]
This might be related to #1108.

**Comment by n0samu** [comment]
Fixed by #10862
