### ISSUE TITLE
BBC Spanish (Old page) has bugs

### ISSUE THREAD

**Issue by chrishancox** [ruffle-rs/ruffle#8490]
### Describe the bug

Audio works on the landing page, but not the window that opens when clicking the link.

To replicate: 
Go to https://www.bbc.co.uk/languages/spanish/mividaloca/

Choose "Episode 1" of "Real Drama"

New window opens, but audio does not work, and you cannot progress

### Expected behavior

Progression through the Spanish course.

### Affected platform

Browser's extension

### Operating system

Ubuntu 22.04 ARM64

### Browser

Firefox Nightly 108.a01

### Additional information

Debug info:

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://www.bbc.co.uk/languages/spanish/mividaloca/ep01.shtml
SWF URL: https://www.bbc.co.uk/staticarchive/c166786f67df0077dd924920171d2374d7a5ee50.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-04
Channel: nightly
Built: 2022-11-04T00:16:33.453Z
Commit: d16e9e15118bba9b01527ac042c3c00bb987a23f
Is extension: true

# Metadata
width: 720
height: 540
frameRate: 30
numFrames: 4
swfVersion: 8
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 1024946

**Comment by n0samu** [comment]
Hi, the same issue has been reported in #2582. But unfortunately, I am unable to make the content work even in the real Adobe Flash Player now - I think something may have broken on the site. You can try your luck restoring Adobe Flash Player using Waterfox Classic and Clean Flash Builds if you want to see for yourself.

**Comment by n0samu** [comment]
Closing in favor of #2582
