### ISSUE TITLE
Mint Linux - Fullscreen input issue

### ISSUE THREAD

**Issue by Zinc-Exclamation** [ruffle-rs/ruffle#8493]
### Describe the bug

Using Mint Linux, and playing Ruffle, fullscreening in the CQC game makes input for the 'r' key not register.
Playing windowed is fine, but full screen is not.

steps to reproduce, 
ensure you have Mint linux 
download nightly  for november 6
play CQC game
fullscreen
shoot some bullets from your gun
press r

I will do more testing later, to see if it happens always, with other games, and to provide the SWF file.

### Expected behavior

You should be able to reload by pressing r in fullscreen.

### Affected platform

Desktop app

### Operating system

Mint Linux

**Comment by n0samu** [comment]
Link to the SWF file: https://cdn.discordapp.com/attachments/722872096002408529/1038965448382890075/412252_cqc1.swf

**Comment by Zinc-Exclamation** [comment]
This is fixed now
