### ISSUE TITLE
Dirk Valentine: Chain and Rocket

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8498]
### Describe the bug

https://user-images.githubusercontent.com/75534590/200346482-4798371b-893e-475e-99bc-aa3630736138.mp4

https://user-images.githubusercontent.com/75534590/200346561-e4daf978-e726-40cd-b731-1dace6de5739.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/200346779-4c5330be-ea7d-4e3d-9fe0-15b368eb929e.mp4

https://user-images.githubusercontent.com/75534590/200346852-9b8219f1-def9-4fa0-a642-bf8ae8456c68.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF: http://www.nitrome.com/games/dirkvalentine/dirkvalentine.swf

**Comment by n0samu** [comment]
Aside from small visual issues I don't see anything in your videos
