### ISSUE TITLE
Super Mario 63's Castle Problem

### ISSUE THREAD

**Issue by SamirTheHuman** [ruffle-rs/ruffle#8514]
### Describe the bug

I'm unsure what's going on for this game, but the Castle has **always** been a big problem to access. Before, it has been able to load, putting Mario in the wrong location mind you. But now, it's kind of just a big buggy mess.
![Screenshot 2022-11-10 13 33 46](https://user-images.githubusercontent.com/117819592/201092857-8c585c21-9ba5-4a43-9d68-d43ff69cc16f.png)

### Expected behavior

I believe what would've happened is that with Ruffle being more advanced now that it'd work somewhat better.

### Affected platform

Self-hosted version

### Operating system

Chromebook

### Browser

Chrome

### Additional information

I don't necessarily think it's the game's fault. I'm sure Ruffle developers will do an amazing job and hopefully, by 2023, we'll get more things done!

**Comment by n0samu** [comment]
Related to #6906. Maybe this should have been a comment on that issue?

**Comment by n0samu** [comment]
Fixed by #10330
