### ISSUE TITLE
http://nostalgiakidssites.com/pbskids2008/arthur/games/moviemaker/moviemaker.html doesn't load 

### ISSUE THREAD

**Issue by Bestboy087** [ruffle-rs/ruffle#8518]
### Describe the bug

The game is just stucked on a loading screen. its just stucked on a loading bar for a while. and i don't think it will load.

### Expected behavior

I expected it to load like its suppose to.

### Affected platform

Browser's extension

### Operating system

windows 10

### Browser

Google chrome

**Comment by n0samu** [comment]
The same problem exists on the original site. It occurs because the site is missing required assets for the game, such as `sfx.swf`.
