### ISSUE TITLE
Unable to display text inside bubble window

### ISSUE THREAD

**Issue by fangq** [ruffle-rs/ruffle#8520]
### Describe the bug

I recently converted a SWF tutorial page to use ruffle. It was amazing to see the SWF file plays again. One issue I observed is about the bubble window shown in the tutorial. The bubble window (yellow rounded rectangles) are displayed correctly, but the text instructions inside it are not displayed.

to test, you can browse this page and click play - on the very first screen, there is a yellow balloon (callout) with text in it, but it shows in solid color instead

http://mcx.space/tutorials/mmc/replay.htm

### Expected behavior

The expected rendering of this screen should look like this (from gnash)

![gnash_balloon](https://user-images.githubusercontent.com/226913/201411512-05021f51-ed1a-48c0-a890-260e41986e87.png)

### Affected platform

Online demo

### Operating system

Ubuntu 18.04

### Browser

Chrome 106

**Comment by Lord-McSweeney** [comment]
There also seems to be a thicker black border around the round yellow box in Ruffle than there is in the original Flash version.

**Comment by kjarosh** [comment]
The original text issue has been fixed. The border thickness issue is well known, see for instance https://github.com/ruffle-rs/ruffle/issues/14268, https://github.com/ruffle-rs/ruffle/issues/751, https://github.com/ruffle-rs/ruffle/issues/13657, https://github.com/ruffle-rs/ruffle/pull/9981.

**Comment by fangq** [comment]
thank you, I confirm that the bubble text box are now displayed correctly.

one follow up question - compare the ruffle rendered animation with the previous flash animation, it appears that the antialiasing is not enabled - is there a flag for ruffle to enable antialiasing? see the below example page

https://mcx.space/tutorials/mcxstudio/6_How_to_copy_and_delete_sessions.htm

**Comment by kjarosh** [comment]
I'm sorry, I don't know what you're referring to. Generally setting a quality higher than low results in antialiasing being enabled. If you're referring to the fact that the bubble is jagged, it's the same reason why the border is too thick.

If you've got an off-topic issue or question, you can always file a new issue on GitHub or reach out to us on Discord!

**Comment by fangq** [comment]
@kjarosh, sorry for not being clear on this question

I was testing this on my Linux (Ubuntu 22.04) laptop, and noticed that the rendering of both the fonts in the bubble box, or the letters in the screencast look jagged. If opened remote desktop to a Windows desktop, it appears the issue is less.

see my below screen capture with the Linux ruffle and Windows ruffle renderings side-by-side


I can see two major differences

1. The Linux ruffle rendering seems to have a scaling factor greater than 1 - which caused the jagged text - I confirm in both windows, I do not set any page scaling
2. the fonts shown in the bubble box appears to have uneven spacing in both windows and Linux - is this due to the lack of handling of font kerning in ruffle?

maybe neither of these issues are related to this particular bug, if this is the case, I am happy to open new tickets.

![Image](https://github.com/user-attachments/assets/09a075db-6091-4e5e-817e-4f7a4cdef93c)

**Comment by fangq** [comment]
I think I solved the scaling issue - if I set customized DPI to 110 in my Linux desktop, I see low-quality jagged rendering above, but if I uncheck custom DPI, the two renderings appear to show similar size, and the jagged fonts disappeared.

I think my only question left is the uneven spacing for the fonts used in the bubble - for example the gap between "yo" in "you" seems to be very narrow, and the spacing between "xi" in "existing" seems to be very wide. Any thoughts that what might have caused this? choices of the default font?

![Image](https://github.com/user-attachments/assets/10789796-83f0-4f14-bbf0-74b1efe46915)

**Comment by kjarosh** [comment]
Yeah, that's a good question. Ruffle generally supports kerning, but it's known that the horizontal placement of letters can be off in Ruffle compared to Flash. This SWF presents probably one of the worst cases of such misalignment, but that's something I've not yet managed to focus on (but I'm planning to!).

Also note that Ruffle will never match 1:1 Flash on Windows in this case, because this SWF uses a device font—Candara, which is proprietary. We can however at least try matching font metrics.

If it happens to be your website, see also https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-do-i-change-the-fonts-used-by-flash-on-my-website

**Comment by fangq** [comment]
thanks a lot for your helpful comments! I am closing this ticket for now as the bubble text can now be displayed.

I will take a look at the font configuration - on my Ubuntu desktop, noto is installed and used by default, but somehow the font metrics seem to be off.

**Comment by kjarosh** [comment]
I'm glad I could help! It would also be great if you created a new issue about that misaligned text, it would be super helpful to keep track of it. Someone may also get interested in it and fix it sooner!
