### ISSUE TITLE
Add a way to print exif info for .swf

### ISSUE THREAD

**Issue by vadosnaprimer** [ruffle-rs/ruffle#8531]
Over at tasvideos, we use libTAS to record [replay files for ruffle](https://tasvideos.org/EmulatorResources/Ruffle). Before starting a recording, one needs to set framerate properly, to match what a given game has. To know this info, users have to install and run a separate program (exiftool). Since the setup for TASing Flash games is already quite complex, users may forget to do the extra step and set the framerate, which will result in mismatch between when a game is expecting new input and when we can send it (libTAS recordings are videoframe based).

It would be extremely useful if ruffle had a way to print exif into to console upon launching a game, or at the very least the game's framerate and resolution. This is only relevant for the desktop version of ruffle, specifically when ran from console.

**Comment by ActionWavele** [comment]
The TAS community expects a lot
I think the TAS community should help develop Ruffle

**Comment by vadosnaprimer** [comment]
I would have sent a PR already if it was a C-like language. Rust I'm seeing for the first time.
