### ISSUE TITLE
web: FlashVars are ignored on most Motion-Twin websites

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#8537]
### Describe the bug

- Browse to https://www.alphabounce.com/.
If you have an account on AlphaBounce, make sure that you are **_not_** logged onto the website.

- Notice that the file displays the "Invalid char at position 0" error, as well as other various debug traces.

### Expected behavior

- The file should run in "Mode Demo".

- The issue is that [this JS file](https://www.alphabounce.com/js/app.js.gz?v=5) overrides the native `Reflect` object, so FlashVars  are just lost when they are parsed: https://github.com/ruffle-rs/ruffle/blob/08270efee72ab8fe31b1448d76bcda09c8af264e/web/src/lib.rs#L1349-L1361

- Most Motion-Twin websites are affected as they use similar JS files that override `Reflect`.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 106

**Comment by n0samu** [comment]
I first pointed this out in https://github.com/ruffle-rs/ruffle/issues/2388#issuecomment-1259398993, but I wasn't able to figure out what specific JavaScript was responsible. Thanks for looking into this!
