### ISSUE TITLE
ennemy counter doesn't work on Harry Potter: Fight the Death Eaters

### ISSUE THREAD

**Issue by ViGadeomes** [ruffle-rs/ruffle#8541]
swf : https://www.dan-dare.org/FreeFun/Games/CMTVMore/HarryPotterFight.htm

Description of the bug :
After killing an ennemy, the counter shows "..." instead of the intended number from 14 to 0.

Flash :
![bugged](https://user-images.githubusercontent.com/56033116/201551008-43fe21b3-d0e5-43e9-9bae-a40615484bc6.PNG)

ruffle : 
![normal](https://user-images.githubusercontent.com/56033116/201551097-ea5807a4-bb8f-412f-9f3e-05733fefa092.PNG)

**Comment by n0samu** [comment]
At a glance, this looks like something wrong with text size/extent calculation in Ruffle, causing the game to think that the text would overflow its box, and cut it off as a result.

**Comment by ViGadeomes** [comment]
fixed in Nightly 2023-11-10. 

Now just font variations/differences.

**Comment by ViGadeomes** [comment]
font has been fixed. Closing.
