### ISSUE TITLE
House of Dead Ninjas: Doesn't Start

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#8543]
### Describe the bug

Game seems to get stuck preloading and never seems to move past it, even though it looks like it finished loading. I'm also seeing this in the console log.
![House of Dead Ninjas console log](https://user-images.githubusercontent.com/78768499/201563049-fd46710c-4f2c-4214-9f4d-c0baa042ffc1.png)

https://www.newgrounds.com/portal/view/566333?emulate=flash

### Expected behavior

It should load and start without locking up.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 107

**Comment by waspennator** [comment]
Starting to wonder if this has something to do with "NetConnection"

**Comment by Lord-McSweeney** [comment]
`flash.net.NetConnection` is not yet implemented.

**Comment by Lord-McSweeney** [comment]
If `NetConnection` is stubbed the error becomes: `RustError("ArgumentError: Cannot remove object from display list it is not a child of.")`

**Comment by waspennator** [comment]
Tested the game out again on the latest nightly and things seem to be a little different, but still not booting to the title screen. Normally there is supposed to be a fancy little retro loading screen with retro boxart of the game in the background and a fancy dragon loading bar, then the game is supposed to flash white and transition to the intro and eventually the title screen.

But on the latest ruffle nightly, it shows a black screen for a little bit, then the white flash happens and then........... nothing.

[ruffle.rs-1678499214948.log](https://github.com/ruffle-rs/ruffle/files/10947307/ruffle.rs-1678499214948.log)

**Comment by waspennator** [comment]
[House of Dead Ninjas.zip](https://github.com/ruffle-rs/ruffle/files/10947626/House.of.Dead.Ninjas.zip)
Providing a version of the game from Flashpoint since it seems to progress further compared to the one currently on NG.

**Comment by Lord-McSweeney** [comment]
Looking into it, it seems that the XML has a UTF-16 BOM, which Ruffle will need to strip out.

**Comment by Lord-McSweeney** [comment]
#10280 progresses this to `RustError("ArgumentError: Cannot remove object from display list it is not a child of.")`.

**Comment by waspennator** [comment]
Actually I retested the NG version of the game again and I realized, I think most of Adult Swims uploaded games on NG including this one just redirect to a random page on Adult Swim now. Tested it on Flash player and it seems to redirect to Adult Swim games now.

The copy of the game used from the zip file I uploaded a week ago seems to get to the title screen now, but it looks way too zoomed in. (I can also hear the menu hovering noises when hovering over where the options should be on the right side of the screen.)

Ruffle:
![HOTD Ruffle](https://user-images.githubusercontent.com/78768499/226775270-81bd845e-a344-4520-8ee8-0f321898fb30.png)

Flash:
![HOTD Flash](https://user-images.githubusercontent.com/78768499/226775282-dc66d22b-b906-4de6-bd58-3cfab77864ae.png)

I also rechecked the NG version on Ruffle and the loading I do see a similar situation going on too.

Ruffle:
![HOTD 2 Ruffle](https://user-images.githubusercontent.com/78768499/226775495-13914e32-3b97-47ac-8eab-a5585f9b4622.png)

Flash:
![HOTD 2 Flash](https://user-images.githubusercontent.com/78768499/226775515-9c475151-ef82-4f6f-ae08-d1d2dd9aa8ac.png)

**Comment by waspennator** [comment]
Can confirm, I retested the version on NG again and while it is still stuck on the preloader, I re-tested it out on flash again and it seems to just transition to a black screen and clicking on the middle of the screen screen pops up a tab for the games section on Adult swim. Testing on Ruffle desktop the preloader doesn't vanish to a black screen but clicking on the center also seems to open a browser tab to the games section, so dunno if it should be closed or not since this version on NG is borked anyways or open until it can transition to the black screen.


The version I nabbed from Flashpoint seems to work just fine though and I was able to complete a run of the game without any issues i've noticed so far, least on my end. Web seems to run in slow motion during gameplay, while desktop seems to run pretty alright for me speed wise with some slowdown here and there.

![HODN Ruffle](https://user-images.githubusercontent.com/78768499/231323837-a082916b-f130-4c9f-ad1c-e3de85ae5203.png)
![HODN Ruffle 2](https://user-images.githubusercontent.com/78768499/231323861-4a6bf651-0f19-49f5-9eee-c84583b28fa9.png)

**Comment by waspennator** [comment]
With latest nightly, the error tossed up by Ruffle when trying the NG version is.

Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0xda18f0 }) to handler FunctionObject(FunctionObject { ptr: 0x3f5c5a8 }) : ArgumentError: The supplied DisplayObject must be a child of the caller.

It seems like the NG version behavior is similar to Flash, the only difference between the two is that the flash player version goes black before getting stuck on the preloader compared to ruffle (Which doesn't go black but exhibits the same behavior when clicking on the middle of the screen) and Flashpoint's version (Actually works in ruffle and flash)

**Comment by waspennator** [comment]
TBH I think the NG version is just broken, i've been trying it on ruffle web, desktop, and flash and it all seems to lead to the same result, but the copy that's on FP i've managed to get working alright, so i'm guessing for now the game works, but only if it's not the NG version.

**Comment by waspennator** [comment]
Actually update, tried out the ng version and it seems like it works now.
