### ISSUE TITLE
web: localStorage entries can be duplicated

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#855]
With the Flash Player, a same swf can be used on different pages and the storage data will be the same across these pages.

With Ruffle, a new entry in the local storage will be created every time. For example, File_AAA.html, File_BBB.html, and even File_BBB.html?param=whatever will create 3 separate entries.

![localstorage](https://user-images.githubusercontent.com/14274782/87411222-b095ea00-c5c7-11ea-966d-a471196f5431.png)

Tested with "This is the Only Level":
https://www.newgrounds.com/portal/view/508676/

(Small) sample:
[testflash.zip](https://github.com/ruffle-rs/ruffle/files/4917926/testflash.zip)

**Comment by relrelb** [comment]
I think this could be resolved by simply choosing a different prefix.
Currently `window.location.href` is used:
https://github.com/ruffle-rs/ruffle/blob/7898776e0c34c7774e1aecf12887caa86b3ff174/web/src/lib.rs#L302

I have some suggestions for possible prefixes:
* URL of the SWF itself (maybe without query parameters) - but it's not available yet in that point in code.
* Some hash on the actual SWF bytes - same issue of first point, but this should handle more complicated cases like redirects etc.
