### ISSUE TITLE
Samsara Room (2013): General Bugs when Playing. (AS3) 

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#8555]
### Describe the bug

I'm going to list every bug that I encountered so far as of the latest build being 11/16 at the time of writing.

There's a transparency issue which still exists, but this is minor to what I'm about to list through.

Immediately after starting the game and not triggering that bug there (#8278), you must move to the adjacent room to the left/right and then return (grandfather clock) in which you'll be able to put the time at 6:20, as well as collecting the candle on the floor. You are unable to interact with the clock immediately from a fresh instance of the game (or collect that candle).

In mentioning the movement of left/right you are unable to select the triangles themselves, instead around it compared to the Flash version which allows the entire side.

_Alternatively moving to the left/right and collecting the visible candle, and using the game's inbuilt reset game will allow you to adjust the clock from a second boot (with still the same instance of ruffle running, if resetting and closing you'll have to do the same move to a different room and back)._

After completing the first area entirely, you move to a segment which is underwater, and you're a fish.
You're able to collect the shell, rip open the carpet, and move rooms...
![image](https://user-images.githubusercontent.com/12412764/202117368-6ad482d4-8fcc-42cb-a3c1-28aa2261e897.png)
_Yes, I'm using a copied version this will be relevant in a bit._

After moving rooms, your input becomes stubborn.
You are unable to do anything except select the cogwheel in the top right, and then you'll be able to continue, but also not. **You have to brute force your way** in and out that menu to do anything. Sometimes you don't have to brute in to the menu, and just spam click and pray, but most of the time to me (unless placebo) I had to menu in and out then I would be able to do something.
Here's me struggling to do this for 2 and a half minutes and then getting out of there:

https://user-images.githubusercontent.com/12412764/202120041-390ef20e-f976-45b3-9782-b027f4427a31.mp4

After getting out of there, collecting the gecko with the cup and moving to the next sequence where you are on the ceiling nothing stands out and all plays out as intended.

~~Grabbing the caterpillar and moving into its world, you are unable to progress into the human corpse that was stuffed in the grandfather clock **don't close ruffle at this point**. If you close Ruffle you will be hardlocked and unable to progress anywhere, and have to make a copy, what you do is either click the cogwheel and reset, or, go back to the normal world where you're a human.~~

**17th Dec '22 Update:**
You are able to finish the game (12/17), issues above are still the same. New issues below are still mouse pick issues.

Entering the human corpse you are able to grab the first two embers, and then you're in clicking hell. Cycling between menu and the center and basically praying is the only way forward. That's the only locked spot there where I brute forced with an auto clicker.

Entering the final area of the game after placing the Egg in the normal area you go to another grandfather clock to put in 8:25 to reveal a key to open a window of 8's. After going through the window you are only able to progress backwards _once_ then once again to save myself time, I brute forced with an auto clicker and cycling between the menu and the center of the room, and eventual it'll go through and **The End**.

### Expected behavior

[You're able to complete the game with all the issues listed above not occurring once in Flash](https://youtu.be/flxafO7wmEA).

### Affected platform

Desktop app

### Operating system

Windows 10 x64

**Comment by n0samu** [comment]
Thank you for the detailed report! This looks like mostly mouse pick issues similar to the one you already reported with this game.

**Comment by Spikestuff** [comment]
Game can now be complete but with all the same known issues (mouse pick) making it more of a hike:
![image](https://user-images.githubusercontent.com/12412764/208247440-1da615e5-e7e2-46f4-9aa5-2f67d8b82222.png)

**Comment by Spikestuff** [comment]
As of #8744 Samsara Room (2013) is playable from start to end without any headaches that I pointed out at the start of this issue.
All that remains are the graphical issues which is the first thing outlined in this issue request.

**Comment by n0samu** [comment]
Awesome! Small graphical issues are expected since blend modes and filter effects aren't implemented yet. Closing this issue.
