### ISSUE TITLE
TextField doesnt re-center when changing width

### ISSUE THREAD

**Issue by LiEnby** [ruffle-rs/ruffle#8569]
### Describe the bug

I have a MovieClip called "LIBUTTON" inside which is a MovieClip called LiButtonBack (as linkage: backPart)
and a text field with as linkage: labelPart, with center-alignment on

it seems if i programmatically change the size of backPart and labelPart, ruffle does not re-center the text to the new size.

this is the code:
```
LIBUTTON.labelPart.text = "TRANS RIGHTS!!!";
backsize = LIBUTTON.labelPart.textWidth;
LIBUTTON.labelPart._width = backsize + 5;
LIBUTTON.backPart._width = backsize + 12;

stop();
```

### Expected behavior

In adobe flash player 11, i get the following result:
![image](https://user-images.githubusercontent.com/39113159/202601349-ed7d30cc-1305-4de6-b600-08c62a1d2bbf.png)

however; in ruffle i get 
![image](https://user-images.githubusercontent.com/39113159/202601439-170ab1f2-d181-49e7-8003-5d968223e27c.png)

i suspect? its using the old size to calculate the center; instead of the new one, because if i edit my code slightly. to set the text again
AFTER resizing the labelPart and backPart;

```
LIBUTTON.labelPart.text = "TRANS RIGHTS!!!";
backsize = LIBUTTON.labelPart.textWidth;
LIBUTTON.labelPart._width = backsize + 5;
LIBUTTON.backPart._width = backsize + 12;
LIBUTTON.labelPart.text = "TRANS RIGHTS!!!";

stop();
```

THEN it works.

![image](https://user-images.githubusercontent.com/39113159/202601700-b2c3ba9e-767f-4771-a48b-bae1231bd224.png)

attached is the original swf; the edited one to have the labelPart set to text again; and my Adobe Flash CS6 Project File

### Affected platform

Online demo

### Operating system

Windows 11

### Browser

Waterfox

### Additional information

[flash.zip](https://github.com/ruffle-rs/ruffle/files/10037116/flash.zip)

**Comment by n0samu** [comment]
Looks related to (but still distinct from) #10660
