### ISSUE TITLE
web: Ruffle does not detect "base" code to load other files from

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#857]
I just tested the base function which is needed for some flashgames to load the game-files in a order to load files which will not pre-load from a certain directory. 

Example would be: https://amanita-design.net/samorost-1/ which loads level for level 

Example code which ruffle ignores:

<embed  src="https://amanita-design.net/samorost-1/samorost.swf" **base="https://amanita-design.net/samorost-1/basefloder/"** />

**Comment by desertking** [comment]
Hey guys any update on this thing? Could really help if this feature is available to link to a specific folder to get those old games running which are loading .swfs from level to level

**Comment by albertstill** [comment]
Any update on this @Herschel? Let me know if I can help at all, I'm a JS developer and looks like it might be a Rust feature but happy to help if I can

**Comment by mstill63** [comment]
great project - would love to get our old flash games running on www.gridclub.com  - Any update please on this @Herschel  - thanks

**Comment by relrelb** [comment]
Is this fixes by #5026?

**Comment by n0samu** [comment]
@desertking I visited the page you referenced as it appeared on Wayback Machine on that day: https://web.archive.org/web/20200715200055/https://amanita-design.net/samorost-1/
Yet the embed has no base parameter and it references `https://amanita-design.net/samorost-1/main.swf`, not `https://amanita-design.net/samorost-1/samorost.swf`. What's going on?

**Comment by n0samu** [comment]
I can confirm that the base parameter is working fine with GridClub and in albertstill's sample https://github.com/albertstill/ruffle-base-issue
