### ISSUE TITLE
Shopping Cart Hero 2 - Error on loading

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#8571]
### Describe the bug

https://www.newgrounds.com/portal/view/521395?emulate=flash

We all loved it, we all played it during the School. Make it run great again 👍 

0184644a:0x4b5d7f Error dispatching event EventObject(EventObject { type: "init", class: flash.events::Event, ptr: 0x4a28c0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x4a20e4 }))) : RustError("Cannot set undefined property ::client on Some(flash.net::LocalConnection)")
$web_sys::features::gen_console::console::error_1::h8c359f25981109c6 @ 0184644a:0x4b5d7f

### Expected behavior

load and run.

### Affected platform

Self-hosted version

### Operating system

All

**Comment by waspennator** [comment]
Trying out Shopping Cart Hero 2 on my end on Newgrounds, game seems to load pretty fine now for me, haven't played too much of it but it seems to actually get in game now, the only issue i've really noticed is that the stickman doesn't angle his head when shifting left or right, resulting in visual oddities like this.

![SCH2](https://user-images.githubusercontent.com/78768499/210693654-dd240692-b168-453b-a490-f4c85bd7b394.png)

**Comment by n0samu** [comment]
Here are the messages:
`[INFO  avm_trace] Error: MochiServices not connected.   Please call MochiServices.connect().  Function: coins_hideLoginWidget`
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x223d0e347f0 }) to handler FunctionObject(FunctionObject { ptr: 0x223c6fe0580 }) : RustError("ArgumentError: Child not a valid display object")`

**Comment by Lord-McSweeney** [comment]
`ERROR core/src/avm2/activation.rs:936 Error: flash.display.Loader.unload - not yet implemented`

**Comment by waspennator** [comment]
Update, game just regressed and now it breaks spamming this in the log.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x185d960 }) to handler FunctionObject(FunctionObject { ptr: 0x1112458 }) : RustError("Attempted to call \"flash::text::TextField::getTextFormat\" with 2 arguments (more than 0 is prohibited)")

**Comment by MartySVK** [comment]
Looks playable after https://github.com/ruffle-rs/ruffle/pull/10246

**Comment by desertking** [comment]
Looks not for me. 
![image](https://user-images.githubusercontent.com/23042167/226345003-4d48170a-45fd-42d9-b382-015856b46e81.png)

**Comment by MartySVK** [comment]
looks like the problem is only on web

**Comment by MartySVK** [comment]
oh, I did not notice that the last web build failed. It will probably work tomorrow
