### ISSUE TITLE
http://nostalgiakidssites.com/pbskids2008/wordgirl/index.html doesn't load, and buttons do not work

### ISSUE THREAD

**Issue by Bestboy087** [ruffle-rs/ruffle#8600]
### Describe the bug

the loading screen is stuck, and the buttons do not work.

### Expected behavior

didn't really expect anything TBH

### Affected platform

Browser's extension

### Operating system

windows 10

### Browser

Google chrome

**Comment by n0samu** [comment]
The website does not have the required files for the Flash content. Ruffle can't do anything about that.
