### ISSUE TITLE
Error on https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by Yeagh** [ruffle-rs/ruffle#8608]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/collections/btree/navigate.rs:522:22

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/107.0.5304.101 Mobile/15E148 Safari/604.1
Platform: iPad
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-11-23
Channel: nightly
Built: 2022-11-23T00:21:07.838Z
Commit: eb2ee06588d948f334ebd5c6984a8b81b995719d
Is extension: false

# Metadata
width: 1280
height: 720
frameRate: 26
numFrames: 93
swfVersion: 31
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 13065806

**Comment by Lord-McSweeney** [comment]
Which example was it?

**Comment by Lord-McSweeney** [comment]
Interesting that this is exactly 2000 issues after that one.
