### ISSUE TITLE
web: remove tap highlight color

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#861]
I often came across games that will flash the tap hightlight in blue when using ruffle and clicking around. So my workaround I finally found was set the canvas to : -webkit-tap-highlight-color: rgba(0,0,0,0); -webkit-tap-highlight-color: transparent;

But basically maybe ruffle can prevent this by default so you don't need a workaround =)

**Comment by Herschel** [comment]
Could you provide info on what device this occurs on, and are you using the polyfill method? Thanks!

We already add `touch-action: none` on the canvas element which fixes this on my Android device, but probably we need to add the attributes you mentioned for other devices.

**Comment by Toad06** [comment]
FWIW, I can also reproduce this on a phone using Android, and an iPad.

Tested here:
https://www.newgrounds.com/portal/view/38598/format/flash?emulate=flash

When I keep the finger on the game for 2 or 3 seconds, the following happens:
- Android: will highlight the word "Author", just below the game.
- iPad: will select the game as if it was text and asks if I want to copy it.

Possibly needs the "user-select" property (and the prefixed ones) set to "none".

**Comment by Herschel** [comment]
Thx! I can repro the text highlighting on my Pixel, and I also occasionally get the entire canvas highlighted, too.

**Comment by desertking** [comment]
> Thx! I can repro the text highlighting on my Pixel, and I also occasionally get the entire canvas highlighted, too.

Yeah the user-select: none still allows to highlight it somehow as it seems. The only thing worked for me to get rid of the blue flashing was to make it transparent : -webkit-tap-highlight-color: transparent;

**Comment by Toad06** [comment]
I've made some new testing, and it seems like the CSS properties have to be on the ruffle-object / ruffle-embed elements too, not only canvas.

Attached a sample, test3.html should be good, I think.

[testSelect.zip](https://github.com/ruffle-rs/ruffle/files/4933922/testSelect.zip)
