### ISSUE TITLE
BLOCnog: Spiked blocks trigger collision when they shouldn't

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8631]
### Describe the bug

Link to the game: https://www.gameshot.org/?id=9121

In BLOCnog, moving a spiked block in the direction of its spike *always* triggers a collision. The collision should only be triggered if the spike hits another block. Also, the collision seems to destroy the spiked block, when a correct collision would instead destroy the block that the spike hits. This bug makes level 11 impossible to complete.

https://user-images.githubusercontent.com/71368227/204184381-b17f58de-2890-41b3-80ae-f28cfccb0615.mp4

(Note: there is also a visual glitch. See #8630 for details on that.)

### Expected behavior

Spiked blocks should destroy other blocks, not themselves.

https://user-images.githubusercontent.com/71368227/204185811-eb842373-b75a-46af-94ec-ca14c1c34ac6.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This error is shown in the terminal after the incorrect collision occurs:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2802d50e440 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x280120c3ab8 }))) : RustError("ArgumentError: Cannot remove object from display list it is not a child of.")`

**Comment by adrian17** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/8667 .
