### ISSUE TITLE
No always start feature

### ISSUE THREAD

**Issue by juanroman74454811** [ruffle-rs/ruffle#8642]
**Describe the feature**
A always start feature, this would go to the Settings because i wanted to make a video about a JS trojan, and i want the extension for Firefox to always start,

**Comment by n0samu** [comment]
Are you asking for a feature in the Ruffle extension to autoplay Flash content? Just want to make sure I'm understanding correctly.

**Comment by Lord-McSweeney** [comment]
Closed by https://github.com/ruffle-rs/ruffle/pull/9040.

**Comment by juanroman74454811** [comment]
> Closed by #9040.

this is old
