### ISSUE TITLE
Governor of poker - Game paused all the time

### ISSUE THREAD

**Issue by MartySVK** [ruffle-rs/ruffle#8688]
### Describe the bug

It keeps showing a box that says "Game Paused". You can close it, but it will show again.

Governor of poker
url - https://www.gameflare.com/online-game/governor-of-poker/

SWF file https://data.gameflare.com/games/223/poI2veSvzZCSzI.swf

### Expected behavior

Detection for paused game is broken somehow

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 108

**Comment by n0samu** [comment]
Duplicate of #2514
