### ISSUE TITLE
Slush Invaders Click Start Forcing

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8704]
### Describe the bug

https://user-images.githubusercontent.com/80902993/205849462-6c7a814e-34af-4f57-bbc2-03f13fc04cd4.mp4
i already clicked but it's not working

### Expected behavior

https://www.youtube.com/watch?v=S7jcVXZNdjk&ab_channel=Backfire301
this is official video
flash player version

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Edge 108

### Additional information

https://www.kongregate.com/games/gildedguy/slush-invaders-game
kongregate website

**Comment by n0samu** [comment]
This is the same issue as #8593, right?

**Comment by deividbinev12** [comment]
yes

**Comment by n0samu** [comment]
Okay, closing as duplicate.
