### ISSUE TITLE
Little Bear Zuma

### ISSUE THREAD

**Issue by Robert9157** [ruffle-rs/ruffle#8717]
### Describe the bug

- The middle marble (the one that the bear holds) is invisible and you can only guess its color/type by switching between the 3 slots using the spacebar. (Very hard to play)
- The game does not end when the marbles reach the game over zone. Rather, the marbles overlap on top of it. Consequently, a power-up marble can be used to successfully complete the level no matter what.
- Some marbles can appear which aren't actually marbles.

SWF: [little_bear_zuma.zip](https://github.com/ruffle-rs/ruffle/files/10170652/little_bear_zuma.zip)

![Screenshot_20221206_225500](https://user-images.githubusercontent.com/69000275/206035200-96548dea-b620-4d01-b4d8-38e0d50c6c8c.png)
![Screenshot_20221206_225621](https://user-images.githubusercontent.com/69000275/206035211-dac213a1-f451-469c-901f-28320f2d4fbe.png)
![Screenshot_20221206_225743](https://user-images.githubusercontent.com/69000275/206035222-7d751a75-8944-4aa0-892b-a4c3262d072b.png)

### Expected behavior

- The middle marble is visible.
- The game ends when the marbles reach the game over zone. 
![Screenshot_20221206_230130](https://user-images.githubusercontent.com/69000275/206035272-80306f68-0796-4c2f-96bd-05138df4f7df.png)

### Affected platform

Online demo

### Operating system

Linux

### Browser

Brave 1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)

**Comment by n0samu** [comment]
Additional observations:
- If you just sit and let yourself lose, you do in fact get a game over screen. I think the marbles that the user shoots onto the playfield somehow aren't checked when deciding whether to trigger the game over screen.
- Marbles sometimes layer over each other instead of interacting with each other properly even before reaching the game over zone.
- After playing for a bit I somehow triggered an infinite loop that caused the game to completely freeze up.

**Comment by n0samu** [comment]
Regarding the text glow effect, these filters are not implemented in Ruffle, see #15.

**Comment by Robert9157** [comment]
I found a different but better version of the game:
[honey-trouble.zip](https://github.com/ruffle-rs/ruffle/files/10944499/honey-trouble.zip)

I tested both today with the latest build on the web demo, and the bugs seem to be gone, which is great. Not sure about whether it keeps freezing though.

**Comment by n0samu** [comment]
Great! I'll close this issue for now then.
