### ISSUE TITLE
2 errors while trying to run swf that need as3

### ISSUE THREAD

**Issue by cmdocmd** [ruffle-rs/ruffle#8720]
### Describe the bug

I'm getting this first error, im using web version
```js
Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x77d330 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x77d07c }))) : RustError("Cannot access property ::selectedLang of null or undefined")
```
and this is the second error
```js
Got RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type com.cocolani::cocolani
```

### Expected behavior

![image](https://user-images.githubusercontent.com/55096480/206218644-0344bd05-d165-4826-b883-7797353144e3.png)

it should load other swf files 

### Affected platform

Browser's extension

### Operating system

Windows 10

**Comment by cmdocmd** [comment]
[swf.zip](https://github.com/ruffle-rs/ruffle/files/10180447/swf.zip)

ok so in the same path of cocolani.swf u have to make a folder called swf and paste the two folders inside the zip file inside the file u just created

**Comment by cmdocmd** [comment]
[swf.zip](https://github.com/ruffle-rs/ruffle/files/10180546/swf.zip)

**Comment by n0samu** [comment]
Here is a zip with the required files to test the issue: [cocolani.zip](https://github.com/ruffle-rs/ruffle/files/10180559/cocolani.zip)

**Comment by n0samu** [comment]
The errors no longer appear, but the game is still stuck on the same black screen as before.

**Comment by rickc-313** [comment]
> The errors no longer appear, but the game is still stuck on the same black screen as before.
Using the Chrome browser extension, I did not encounter any black screen, 
The link I used for the test: [https://safariislandsgame.com/play/?lang=en](https://safariislandsgame.com/play/?lang=en)

**Comment by n0samu** [comment]
Oh wow, it looks like the problem has been fixed in the past day, awesome! Object coercion is a separate issue so I think this one can be closed now.
