### ISSUE TITLE
Panic on https://z0r.de/5360 (BitmapData already mutably borrowed)

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle#8721]
SWF: https://z0r.de/L/z0r-de_5360.swf
This was likely introduced/exposed by #8191.
This weird aliasing avoidance was originally my idea, though it appeared to work in AVM1.

# Error Info
Error name: Error
Error message: panicked at 'already mutably borrowed: BorrowError', core/src/avm2/globals/flash/display/bitmapdata.rs:538:63

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: http://localhost:8080/

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-07
Channel: nightly
Built: 2022-12-07T18:51:13.109Z
Commit: 2bb4e2e549ab39d2f2cb7d8194ac21bb1ca2e682
Is extension: false

# Metadata
width: 709
height: 1000
frameRate: 24
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 2119988

**Comment by adrian17** [comment]
Fixed via https://github.com/ruffle-rs/ruffle/pull/8762 .
