### ISSUE TITLE
AVM2: HitTestPoint fails when child depth = 0

### ISSUE THREAD

**Issue by CUB3D** [ruffle-rs/ruffle#8732]
### Describe the bug

In the attached swf, clicking on the blue shape should trace `HitTest=true` as it does in Flash Player. However in Ruffle it currently prints `HitTest=false`.

The file in question has been modified in jpexs to set the depth of the PlaceObject2 tag in DefineSprite(2) to 0. This clip is then moved from that sprite to the root by a script. 

Changing the comparison [here](https://github.com/ruffle-rs/ruffle/blob/f79208c75fe73acc6253aba1ceacc5a825334a64/core/src/display_object/movie_clip.rs#L2487), from `>` to `>=` fixes the actual hit test when depth = 0 (although I'm not sure if this depth should actually be 0 here).

Incidentally, that change also fixes bullet collision in Upgrade Complete.

[UGCbullet.zip](https://github.com/ruffle-rs/ruffle/files/10199100/UGCbullet.zip)

### Expected behavior

The file behaves the same in Ruffle as it does in Flash Player

### Affected platform

Desktop app

### Operating system

Linux

**Comment by n0samu** [comment]
Fixed by #8744
