### ISSUE TITLE
Morphing: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8741]
### Describe the bug

After the intro, [Morphing](http://www.notdoppler.com/morphing.php) gets stuck on a blank brown screen. First this warning is shown in the terminal:
`[WARN  ruffle_core::avm2::globals::flash::display::graphics] Graphics.beginGradientFill: not yet implemented]`
Then this error is repeated over and over:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1c865d4b850 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1c859451618 }))) : RustError("Cannot access property ::globalPause of null or undefined")`

### Expected behavior

The main menu should be displayed.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
beginGradientFill has been stubbed by #8355. Now the game is stuck on XML, with this error shown in the terminal:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x13139379920 }) to handler FunctionObject(FunctionObject { ptr: 0x1312ede8be0 }) : RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)")`

**Comment by Lord-McSweeney** [comment]
Progressed by #9647, now needs string-to-XML coercion.

**Comment by n0samu** [comment]
The game is fully completable in Ruffle now! 🎉
