### ISSUE TITLE
Grapple Cat: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8742]
### Describe the bug

After the intro, [Grapple Cat](http://www.notdoppler.com/grapplecat.php) gets stuck on a blank screen. A few errors are repeated over and over in the terminal - I've provided them below in the "Additional Information" section.

### Expected behavior

The main menu should be displayed.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

These errors are repeated over and over in the terminal:

`[WARN  ruffle_core::avm2::globals::flash::display::graphics] Graphics.beginBitmapFill: not yet implemented`

`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "timer", class: flash.events::TimerEvent, ptr: 0x18a6671ffc0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x18a4e512ec8 }))) : RustError("Cannot coerce String(\"<level width=\\\"240\\\" height=\\\"144\\\">\\r\\n  <BackgroundTiles tileset=\\\"BackgroundTiles\\\" exportMode=\\\"XML\\\">\\r\\n    <tile x=\\\"1\\\" y=\\\"6\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"1\\\" y=\\\"7\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"1\\\" y=\\\"8\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"4\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"5\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"6\\\" id=\\\"29\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"2\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"3\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"4\\\" id=\\\"29\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"6\\\" id=\\\"57\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"0\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"1\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"2\\\" id=\\\"29\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"0\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"1\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"2\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"4\\\" id=\\\"57\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"0\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"1\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"2\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"0\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"1\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"2\\\" id=\\\"56\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"0\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"1\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"2\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"0\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"1\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"2\\\" id=\\\"28\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"3\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"2\\\" id=\\\"2\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"3\\\" id=\\\"28\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"4\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"5\\\" id=\\\"56\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"3\\\" id=\\\"2\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"4\\\" id=\\\"28\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"5\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"6\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"4\\\" id=\\\"2\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"5\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"6\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"7\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"8\\\" id=\\\"10\\\" />\\r\\n  </BackgroundTiles>\\r\\n  <Floor tileset=\\\"Beach\\\" exportMode=\\\"XML\\\">\\r\\n    <tile x=\\\"0\\\" y=\\\"7\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"0\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"1\\\" y=\\\"7\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"1\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"7\\\" id=\\\"2\\\" />\\r\\n    <tile x=\\\"2\\\" y=\\\"8\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"3\\\" y=\\\"0\\\" id=\\\"16\\\" />\\r\\n    <tile x=\\\"4\\\" y=\\\"0\\\" id=\\\"17\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"0\\\" id=\\\"18\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"7\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"5\\\" y=\\\"8\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"7\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"6\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"7\\\" id=\\\"2\\\" />\\r\\n    <tile x=\\\"7\\\" y=\\\"8\\\" id=\\\"10\\\" />\\r\\n    <tile x=\\\"8\\\" y=\\\"0\\\" id=\\\"16\\\" />\\r\\n    <tile x=\\\"9\\\" y=\\\"0\\\" id=\\\"17\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"0\\\" id=\\\"18\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"7\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"10\\\" y=\\\"8\\\" id=\\\"8\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"7\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"11\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"6\\\" id=\\\"0\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"7\\\" id=\\\"29\\\" />\\r\\n    <tile x=\\\"12\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"13\\\" y=\\\"6\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"13\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"13\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"14\\\" y=\\\"6\\\" id=\\\"1\\\" />\\r\\n    <tile x=\\\"14\\\" y=\\\"7\\\" id=\\\"9\\\" />\\r\\n    <tile x=\\\"14\\\" y=\\\"8\\\" id=\\\"9\\\" />\\r\\n  </Floor>\\r\\n  <Torch tileset=\\\"Beach\\\" exportMode=\\\"XML\\\" />\\r\\n  <Interactions>\\r\\n    <Crab id=\\\"0\\\" x=\\\"208\\\" y=\\\"80\\\" />\\r\\n    <SandCastle id=\\\"1\\\" x=\\\"160\\\" y=\\\"96\\\" />\\r\\n    <Seagull id=\\\"3\\\" x=\\\"192\\\" y=\\\"32\\\" />\\r\\n    <Seagull id=\\\"4\\\" x=\\\"16\\\" y=\\\"48\\\" />\\r\\n    <GrappleCat id=\\\"2\\\" x=\\\"16\\\" y=\\\"96\\\" />\\r\\n  </Interactions>\\r\\n</level>\") to an XML")`

**Comment by CUB3D** [comment]
This is due to missing the top-level [XML](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/package.html#XML()) function, e.g:
```
var l = XML("<root><foo>Hi</foo></root>");
trace(l);
```

**Comment by n0samu** [comment]
Fixed by one of the recent XML PRs
