### ISSUE TITLE
Sweet Drmzzz: Invisible sugar in "Sugar, Sugar" minigame

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8745]
### Describe the bug

Link to SWF: https://web.archive.org/web/20210111155256id_/https://www.bartbonte.com/sweetdrmzzz/sweetdrmzzz.swf

In [Sweet Drmzzz](https://web.archive.org/web/20210127062810/https://bartbonte.com/sweetdrmzzz/), there is a minigame based on the developer's *Sugar, Sugar* game series. But in the levels with this minigame, the sugar is invisible, making the levels much more difficult than intended to complete.

Steps to reproduce:
1. Run the SWF file in the Ruffle desktop app.
2. Play through the first level and start the second level.
3. Draw a line as shown ingame.

### Expected behavior

Sugar is supposed to fall from the spaceship into the hole at the top of the planet, just like it falls into the cups in *Sugar, Sugar*.
![image](https://user-images.githubusercontent.com/71368227/206986275-712f698e-f3a8-45a8-a39d-e25ce48962ee.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

It seems like the cause of the problem is that `BitmapData.threshold` is not implemented:
`ERROR ruffle_core::avm2::activation] ReferenceError: Error #1069: Property threshold not found on flash.display.BitmapData and there is no default value.`
Here is the relevant line of code in the game's `Main` source file (decompiled with FFDEC):
`this.finalBmp.threshold(this.suikerBmp,_loc6_,_loc7_,"==",this.backkleur,_loc4_,_loc5_,true);`

**Comment by n0samu** [comment]
The same problem also affects [Sugar, Sugar 3](http://www.notdoppler.com/sugarsugar3.php).

**Comment by MartySVK** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/10055
