### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by fp07** [ruffle-rs/ruffle#875]
On the demo website it takes a while before the play button is visible. You will then see a black screen for 10 seconds before the button is visible. I think adding an loading splash screen for ruffle is necessary for large files. (maybe optional?)

Console log:

Got SWF data
Creating WebGL renderer...
Creating WebGL2 context.
Minimum audio buffer sample rate: 5512
Loaded SWF version 6, with a resolution of 550x400

-- creating instance takes more than 10 seconds --

New Ruffle instance created.

Example for loading
https://i.imgur.com/XcbOa1D.jpg

**Comment by Herschel** [comment]
This should get better with proper preloading/streaming (cc #18, #656), but even in the meantime we could add some sort of loading indicator.

**Comment by n0samu** [comment]
#7292 added a basic loading screen. The PR outlines some potential improvements for the future, but I think this issue can be closed.
