### ISSUE TITLE
400 years http://adobe.com/AS3/2006/builtin::indexOf

### ISSUE THREAD

**Issue by ActionWavele** [ruffle-rs/ruffle#8752]
### Describe the bug

when playing the Ruffle demo, 400 years (AS3) doesn't load and only says 
`
Got RustError("Cannot access property http://adobe.com/AS3/2006/builtin::indexOf of null or undefined") when constructing AVM2 side of movie clip of type Preloader`

### Expected behavior

the game should load
[610738_400years_v1_1NG.zip](https://github.com/ruffle-rs/ruffle/files/10210248/610738_400years_v1_1NG.zip)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Mozilla Firefox

**Comment by n0samu** [comment]
The current error is:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: ReferenceError: Error #1069: Property unloadAndStop not found on flash.display.Loader and there is no default value.
        at Main/sponsorIntroEF()
```
This will be fixed by my PR #10076.
