### ISSUE TITLE
Armor Mayhem multiple issues

### ISSUE THREAD

**Issue by ActionWavele** [ruffle-rs/ruffle#8754]
### Describe the bug

the game never loads (AS3) and says 
`
Got RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type net.louissi.ConflictGame::EngineStart`

### Expected behavior

it should load
[armor-mayhem-10215.zip](https://github.com/ruffle-rs/ruffle/files/10210470/armor-mayhem-10215.zip)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Mozilla Firefox

**Comment by Lord-McSweeney** [comment]
Will be progressed by #9647; the SWF needs `flash.text.StyleSheet` next.

**Comment by Lord-McSweeney** [comment]
Now stuck on `Modifying an XML object is not yet implemented`.

**Comment by MartySVK** [comment]
The current error is:
``
Property net.louissi.ConflictGame.global::killed_weapon1 not found on XML and there is no default value
``

**Comment by ActionWavele** [comment]
flash
https://github.com/ruffle-rs/ruffle/assets/120395932/0aa18c0c-1899-4baa-b346-080082ec9322

ruffle

https://github.com/ruffle-rs/ruffle/assets/120395932/d3363947-24d1-44b1-ba8b-e2607a8b88d5



The intro cutscene does not render properly, and you can't even play the game

**Comment by Aaron1011** [comment]
This game now works (though with worse performance than in Flash Player)
