### ISSUE TITLE
Refreshing an page twice results in an javascript error

### ISSUE THREAD

**Issue by fp07** [ruffle-rs/ruffle#876]
Refreshing an page twice results in the following error:
Uncaught (in promise) Error creating player
41.index.js:1 Uncaught Error: closure invoked recursively or destroyed already

Error:
https://i.imgur.com/JUpQF74.png

**Comment by Toad06** [comment]
I wasn't able to reproduce this issue by refreshing the page; but if you load the web demo (wait until the file is loaded) and select another sample swf, then the same error message will be logged in the console (clicking anywhere on the page will also trigger this message everytime).

Also happening on Newgrounds, when you click the "Collapse" icon (then click anywhere else on the page to trigger the error).
Eg: https://www.newgrounds.com/portal/view/38598/format/flash?emulate=flash

Sample attached:
[destroytest.zip](https://github.com/ruffle-rs/ruffle/files/4941857/destroytest.zip)

**Comment by Dinnerbone** [comment]
I've not investigated this yet but I saw this error too when investigating #826. Worth checking that issue after this one is resolved.

**Comment by Teascade** [comment]
Is there any known workaround to this problem? Destroying the ruffle player and not throwing errors after?
