### ISSUE TITLE
Bug with swarm towers in Desktop Tower Defence

### ISSUE THREAD

**Issue by tw-hx** [ruffle-rs/ruffle#8765]
### Describe the bug

Thanks for Ruffle, it's enabling a few blasts from the past! Using the SWF from #1807, Desktop Tower Defence is very playable using Ruffle's website demo (2022-12-13), except for one bug.

"Swarm Towers" won't stop firing after they first encounter a flying creep. They are useless after this and don't appear to target further creeps.

Easiest way to replicate this is select "Challenge" at main menu then "4K Set Maze", then place a few towers including swarm towers and click "Send next level" several times; flying creeps appear on the 7th wave.

### Expected behavior

Swarm towers should act like the other towers and only free when a creep is in range, then cease firing once creep is out of range or destroyed. They should then target fresh creeps in subsequent waves.

### Affected platform

Online demo

### Operating system

Linux

### Browser

Chromium 108.0.5359.98

**Comment by n0samu** [comment]
Same problem as many other AVM1 tower defense games: #7711, #6203, #5711, #2575, ...
