### ISSUE TITLE
Volt Connect 2: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8769]
### Describe the bug

After the intro, [Volt Connect 2](http://www.notdoppler.com/voltconnect2.php) gets stuck on a black screen. This error is shown in the terminal:
`[ERROR ruffle_core::display_object::movie_clip] Error occured when running AVM2 frame script: RustError("Cannot call null or undefined function")`

### Expected behavior

The main menu should be displayed.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Now the game is stuck on a white screen with the developer's name in the bottom-right corner, and this error is shown in the terminal:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Got RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type game`

**Comment by Lord-McSweeney** [comment]
With #9647, this needs `flash.ui.MouseCursorData` and some more XML features that Google Analytics uses (similar problems with GA are also present in many other games).
