### ISSUE TITLE
Papa's AS3 Games/Flipline Ads: Cannot coerce String to an XML

### ISSUE THREAD

**Issue by c4artisan** [ruffle-rs/ruffle#8808]
### Describe the bug

since the "stub more parts of localconnection" commit instead of the "unimplemented" logs when running papa's burgeria (and other papa's gamerias in as3) will log this instead of the old errors: [2022-12-16T05:25:04Z ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x238b2176d40 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x238af4a17c8 }))) : RustError("Cannot coerce String(\"<response><pre_image>http://www.fliplineads.com/serve/images/v19_pastariaTG.swf</pre_image><pre_link></pre_link><pre_uselink>false</pre_uselink><pre_dim>640x480</pre_dim><pre_delay>5</pre_delay><int_image>http://www.fliplineads.com/serve/images/v18_sushiriaTG.swf</int_image><int_link></int_link><int_uselink>false</int_uselink><int_dim>640x480</int_dim><int_delay>5</int_delay><alt_image>http://www.fliplineads.com/serve/images/v17_bakeriaTG.swf</alt_image><alt_link></alt_link><alt_uselink>false</alt_uselink><alt_dim>640x480</alt_dim><alt_delay>5</alt_delay><new_image>http://www.fliplineads.com/serve/images/scooperiaTG_badge.png</new_image><new_link>https://itunes.apple.com/app/id1392608717?ls=1&mt=8</new_link><new_uselink>true</new_uselink><new_usecont>true</new_usecont><promo1_image>http://www.fliplineads.com/serve/images/burgeriaTG_badge.png</promo1_image><promo1_link>https://itunes.apple.com/app/id600626116?ls=1&mt=8</promo1_link><promo1_uselink>true</promo1_uselink><promo1_usecont>true</promo1_usecont><promo2_image>http://www.fliplineads.com/serve/images/burgeriaHD_badge.png</promo2_image><promo2_link>http://itunes.apple.com/us/app/papas-burgeria/id514634235?ls=1&mt=8</promo2_link><promo2_uselink>true</promo2_uselink><promo2_usecont>true</promo2_usecont><version>2.0</version><ato>10</ato><bto>5</bto><success>true</success></response>\") to an XML")

### Expected behavior

the game will not log that and will let the ad load, possibly making the game load all the way to the "CONTINUE" button (this is at least behavior i discovered when trying to run the game in lightspark)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by MartySVK** [comment]
it's already fixed

**Comment by c4artisan** [comment]
yeah. papa's taco mia loads with no problems and probably the others will too
