### ISSUE TITLE
Error on moz-extension://8005444d-a448-4897-be6f-369aa6ac5f47/player.html

### ISSUE THREAD

**Issue by ervasti** [ruffle-rs/ruffle#8817]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
966/D/n.wbg.__wbg_new_f9bb493369a83c12@moz-extension://8005444d-a448-4897-be6f-369aa6ac5f47/dist/966.js:1:6972
std::sync::once::Once::call_once::{{closure}}::hcd46b3a2543691b9@:wasm-function[927]:0x26cae0
std::sync::once::Once::call_inner::h34aee843864daceb@:wasm-function[1403]:0x319a4c
core::ops::function::FnOnce::call_once{{vtable.shim}}::hb7a03847d0b7780a@:wasm-function[4992]:0x4bd53a
std::panicking::rust_panic_with_hook::h70a0e195f4db2a29@:wasm-function[3769]:0x47c2fa
core::panicking::panic_fmt::h751be80779d42b53@:wasm-function[5233]:0x4c2397
core::option::expect_failed::h2290d18a0c9a6a24@:wasm-function[5916]:0x4d5aaf
ruffle_core::display_object::stage::Stage::root_clip::he233f8c082471f13@:wasm-function[3705]:0x476499
ruffle_web::Ruffle::tick::ha75571213826a268@:wasm-function[643]:0x1e9e69
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h2f891ef58527c159@:wasm-function[6160]:0x4ddff1
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha5bbdaf30b9327e7@:wasm-function[5598]:0x4cc137
S@moz-extension://8005444d-a448-4897-be6f-369aa6ac5f47/dist/966.js:1:2576
c@moz-extension://8005444d-a448-4897-be6f-369aa6ac5f47/dist/966.js:1:2253

```

# Player Info
Allows script access: false
Renderer: WebGL

# Page Info
Page URL: moz-extension://8005444d-a448-4897-be6f-369aa6ac5f47/player.html?url=https%3A%2F%2Fchat.kongregate.com%2Fgamez%2F0013%2F9620%2Flive%2Fnss102.swf%3Fkongregate_game_version%3D1362096828
SWF URL: https://chat.kongregate.com/gamez/0013/9620/live/nss102.swf?kongregate_game_version=1362096828

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-07
Channel: nightly
Built: 2022-12-07T00:18:07.185Z
Commit: 2bb4e2e549ab39d2f2cb7d8194ac21bb1ca2e682
Is extension: true

# Metadata
width: 320
height: 480
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 10332489

**Comment by danielhjacobs** [comment]
This was probably fixed by #10026
