### ISSUE TITLE
Epic Combo: Incorrect weapon graphics in the shop

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8819]
### Describe the bug

Link to SWF: https://uploads.ungrounded.net/550000/550865_EpicCombo.swf

In the shop screen of [Epic Combo](https://www.newgrounds.com/portal/view/550865), several of the weapons show the same graphic, even though each weapon is supposed to have its own graphic.
![image](https://user-images.githubusercontent.com/71368227/208267691-12e3782b-02ce-4004-ab48-15e47aedeed3.png)

Exactly what graphic is shown for each weapon seems to be somewhat random, and there are sometimes other glitches with the graphics. Here's another example:
![image](https://user-images.githubusercontent.com/71368227/208268207-c82ba992-fdcc-4d5d-b490-439c40cb724b.png)

Steps to reproduce:
1. Load the game.
2. Press S to go to the shop screen.

### Expected behavior

The weapons on the shop screen are supposed to look like this:
![image](https://user-images.githubusercontent.com/71368227/208267744-0eac7655-9d66-43a5-b8dd-651ff37a8fb0.png)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 108

### Additional information

The problem also occurs in the latest Ruffle extension and desktop app.

**Comment by Lord-McSweeney** [comment]
`"Blend mode 'layer' is unsupported and will not render correctly."` while starting the game.

Also, the "Click here (or S) to return to game" button in the shop is only clickable in the top portion (~5px) of the bottom.

**Comment by n0samu** [comment]
The semi-random behavior suggests this is not a simple case of unimplemented blend modes.

**Comment by Lord-McSweeney** [comment]
#8744 seems to have fixed the button issue I mentioned.

**Comment by n0samu** [comment]
I can't reproduce this anymore and can easily reproduce it in old Ruffle builds, but the results are too inconsistent for me to determine what exactly fixed this. If anyone can take a closer look, that would be much appreciated. Nevertheless, I am closing the issue.
