### ISSUE TITLE
Devilish Series Saga

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8825]
### Describe the bug

All game just won't start due to Error

Same error for all Devilish Series
```
[2022-12-18T17:44:11Z ERROR ruffle_core::display_object::movie_clip] Got RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type Document
```

### Expected behavior

Should startup as normal

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

SWF
~~Devilish Hairdresser~~:
http://www8.agame.com/games/flash/d/devilish_hairdresser/devilish_hairdresser.swf
~~Devilish Pet Salon~~:
http://www8.agame.com/games/flash/d/devilish_pet_salon/devilish_pet_salon_awards.swf
~~Devilish Stylist~~:
http://www8.agame.com/games/flash/d/DevilishStylist/devilish_stylist.swf
~~Devilish Trick~~:
http://www8.agame.com/games/flash/d/devilish_trick/devilish_trick.swf
~~Devilish Christmas~~:
http://www8.agame.com/games/flash/d/devilish_christmas/devilish_christmas.sw
~~Devilish Valentine~~:
http://www8.agame.com/games/flash/d/devilish_valentine/devilish_valentine.swf
~~Devilish Dress Up~~:
http://www8.agame.com/games/flash/d/Devilish/devilish_dressup.swf
~~Devilish Cat~~:
http://www8.agame.com/games/flash/d/DevilishCat/devilish_cat.swf
~~Devilish Cooking~~:
http://www8.agame.com/games/flash/d/devilish_cooking/devilish_cooking.swf
~~Devilish Candy House(crossdomain)~~:
http://www8.agame.com/mirror/flash/d/Devilish_candy_house/Devilish_Candy_House_130221_1537.swf

**Comment by Lord-McSweeney** [comment]
With #9647 the error messages are `RustError("Cannot call null or undefined method ::children of class XML")` and `RustError("Cannot call null or undefined method ::child of class XML")`.

**Comment by Lord-McSweeney** [comment]
In the last one gameplay can be entered, but the line which the cookie is hanging by is not responsive to mouse drags, possibly because of this error: `TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: SetType)`.

**Comment by p0008874** [comment]
Devilish Hairdresser:
```
2023-03-26T08:05:56.153142Z ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: gotoAndStop)
        at code.ui::SureMC/initStarFun()
        at code.ui::SureMC/initBtn()
        at flash.display::MovieClip/flash::display::MovieClip::gotoAndStop()
        at code.tool::TranslateTxt/changeLang()
        at code.tool::TranslateTxt/init()
        at code.tool::TranslateTxt()
        at TXT_POP()
```

**Comment by p0008874** [comment]
Half of the game can't access back when save file exist.

**Comment by p0008874** [comment]
Devilish Trick, Christmas and Valentine.
Are playable to finish.

**Comment by p0008874** [comment]
Devilish Hairdresser and Pet Salon Crash on Latest Nightly.
Devilish Cat and Cooking Are Playable, But can't access back when save file exist.

**Comment by p0008874** [comment]
Devilish Hairdresser No longer Crash, But not Pet Salon.

**Comment by p0008874** [comment]
Devilish Candy House had corssdomain.xml
