### ISSUE TITLE
1 day - black screen

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8827]
### Describe the bug

just a black screen

`ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x17392c4a840 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x173929675b8 }))) : RustError("Cannot access property ::Update of null or undefined")`

### Expected behavior

game should work

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[1day.zip](https://github.com/ruffle-rs/ruffle/files/10254707/1day.zip)

**Comment by n0samu** [comment]
Fixed by #8836. And #9007 allows the New Game button code to get farther. But it still hangs - I'm opening a separate issue for that.
