### ISSUE TITLE
Alien  Transporter

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8831]
### Describe the bug

yes, this is not "air transporter"

`ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x18fbf62ad00 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x18fc765b1b8 }))) : RustError("Resolved parameter type ru.antkarlov.anthill.signals::AntSignalBindingList is unresolvable, not a class, null, or undefined")`

### Expected behavior

game should load

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[AlienTransporter.zip](https://github.com/ruffle-rs/ruffle/files/10254734/AlienTransporter.zip)

**Comment by sodscg** [comment]
still an issue on latest

**Comment by Lord-McSweeney** [comment]
Now needs `flash.sampler::getSize`.
