### ISSUE TITLE
Armor Mayhem - Black Screen

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8832]
### Describe the bug

`ERROR ruffle_core::display_object::movie_clip] Got RustError("Attempted to call \"\" with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type net.louissi.ConflictGame::EngineStart`

### Expected behavior

the game should run

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[armor-mayhem-10215.zip](https://github.com/ruffle-rs/ruffle/files/10254746/armor-mayhem-10215.zip)

**Comment by Lord-McSweeney** [comment]
Closing in favor of #8754.
