### ISSUE TITLE
ATV Offroad Thunder - Graphics residue

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8833]
### Describe the bug

Its actually surprsing to see thisgame work, it used to flash between frames, then whhen it did work, you'd fall through the ground

the issue now is that part of the loading screen stays on screen forever, kind of faint though
![atv](https://user-images.githubusercontent.com/102984201/208322550-e1e3877f-5de6-4c13-aba3-ecf3d8c87ae5.jpg)

### Expected behavior

the game should removing no longer used items

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[ATV_Offroad_Thunder_agame.zip](https://github.com/ruffle-rs/ruffle/files/10254766/ATV_Offroad_Thunder_agame.zip)

**Comment by n0samu** [comment]
Hmm, this is actually really strange. The "01" text is added with a PlaceObject tag in frame 12, and removed again with a RemoveObject tag in frame 13. I don't understand why Ruffle doesn't remove it.
![image](https://user-images.githubusercontent.com/71368227/208323792-1a24747b-b9aa-4d93-83c5-3a90c277c306.png)

**Comment by sodscg** [comment]
![nice](https://user-images.githubusercontent.com/102984201/210422830-2c09f253-61aa-4a37-8d72-ec1e2e8f8efc.png)

whatever was done in the newest build has fixed this!

**Comment by sodscg** [comment]
(ruffle-nightly-2023_01_03-windows-x86_64)

**Comment by n0samu** [comment]
Now I'm trying some earlier Ruffle builds and I'm unable to reproduce the problem again. I wonder if this is a timing-related bug of some kind.
