### ISSUE TITLE
Azurefish -  Black Screen

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8834]
### Describe the bug

`ERROR ruffle_core::display_object::bitmap] Got error when creating AVM2 side of bitmap: RustError("Param <Unnamed Parameter> (index 0) was missing when calling ")`

### Expected behavior

the game should play

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[566907_Final_Azurefish.zip](https://github.com/ruffle-rs/ruffle/files/10254777/566907_Final_Azurefish.zip)

**Comment by Kz-92** [comment]
this seems to work on the latest Ruffle!

**Comment by sodscg** [comment]
you're right! 
at last

thx ruffle team
