### ISSUE TITLE
web: "Unable to lock Ruffle core" console spam after panic

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8835]
### Describe the bug

Consider the Electricman panic (#4932, [SWF link](https://uploads.ungrounded.net/363000/363447_electricman2hs_fwg.swf)).
After the panic occurs, the console is spammed with thousands of "Unable to lock Ruffle core" error messages.
In fact, the message appears on every `requestAnimationFrame`. But why is Ruffle still calling requestAnimationFrame after `Ruffle instance destroyed.`?
As part of the panic handler, we can see that [the Ruffle instance gets destroyed](https://github.com/ruffle-rs/ruffle/blob/b323c086a943052e63ec2033f144650989189984/web/packages/core/src/ruffle-player.ts#L1450). And among other things, that code is supposed to [cancel the requestAnimationFrame calls](https://github.com/ruffle-rs/ruffle/blob/b323c086a943052e63ec2033f144650989189984/web/src/lib.rs#L394). So why isn't this working?

### Expected behavior

requestAnimationFrame should no longer be called after the Ruffle instance is destroyed. And the console spam should not happen.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 108

### Additional information

This also occurs in Edge (Chromium) and in Ruffle selfhosted and web demo.

**Comment by Lord-McSweeney** [comment]
This will probably be easier to debug now that the extension code is no longer minified

**Comment by Lord-McSweeney** [comment]
Some basic debugging shows that requestAnimationFrame is repeatedly called by Ruffle.

**Comment by n0samu** [comment]
I tried adding a bunch of trace statements to web/src/lib.rs to diagnose this. I found that the `destroy` function does in fact get called, but nothing inside the `if let` statement runs: https://github.com/ruffle-rs/ruffle/blob/d849e98902a3af64f3e00d4e74a54b2866a25526/web/src/lib.rs#L309

That line calls `remove_instance`, which never seems to return. Within that function, nothing after the `try_borrow_mut` call seems to execute:
https://github.com/ruffle-rs/ruffle/blob/d849e98902a3af64f3e00d4e74a54b2866a25526/web/src/lib.rs#L834

**Comment by n0samu** [comment]
This is still happening for me in Firefox with the cases mentioned in #8427, as well as #11193. Looking for a way to reproduce it in Chromium.

**Comment by n0samu** [comment]
I can't reproduce the issue in Chromium, so I guess I'll close this and further discussion can happen in #8427
