### ISSUE TITLE
Error on https://e621.net/posts/1424089?q=eropharaoh

### ISSUE THREAD

**Issue by CrunchyGears13** [ruffle-rs/ruffle#8838]
I'm unable to play this flash game, because there is a bug. May you fix that issue for me please.
Love: The G-Man

**Comment by n0samu** [comment]
And what exactly is the bug?

**Comment by CrunchyGears13** [comment]
> And what exactly is the bug?

I don't know but it said "This isn't supposed to happen". I downloaded a Flash Player Emulator and here's a screenshot
![Screenshot 2022-12-18 9 38 31 PM](https://user-images.githubusercontent.com/120999842/208342904-6a347d8a-f28d-4b22-80f5-5afaadf1b48c.png)

**Comment by n0samu** [comment]
Okay, that's the same issue as #2201. It's something e621 would have to fix on their end.
But for this game, you can just click the Download button on the page to view the animation directly.

**Comment by n0samu** [comment]
Also, be sure to use the official Ruffle extension from the Chrome Web Store or Firefox Add-Ons site: https://ruffle.rs/#downloads

**Comment by CrunchyGears13** [comment]
Okay so I downloaded Ruffle and tried playing the flash game that I wanted to play, but then I got these messages. Here are two screenshots.
![Screenshot 2022-12-18 10 09 26 PM](https://user-images.githubusercontent.com/120999842/208346291-b55aeeee-e47c-4bb1-9b5e-9c4468422ab1.png)
![Screenshot 2022-12-18 10 09 59 PM](https://user-images.githubusercontent.com/120999842/208346304-c242fdfc-bf85-421b-9954-3e2e2e81f23c.png)

**Comment by n0samu** [comment]
Yes, well I tried "Run anyway" on this game and it seemed to work

**Comment by n0samu** [comment]
Closing in favor of #2201
