### ISSUE TITLE
navigator.plugins is not iterable

### ISSUE THREAD

**Issue by wdcook4** [ruffle-rs/ruffle#8842]
### Describe the bug

When loading certain websites (like Gumroad), the page breaks for no discernable reason. I was able to isolate the issue down to Ruffle and its override of the PluginArray (at least on Chromium).
When loading Gumroad specifically, product page images will not load, and various other critical functions (like checkout and product search infinite scroll) entirely break, due to RufflePluginArray not being iterable and causing issues with other scripts on the page.

### Expected behavior

I expect websites that don't utilize Flash to work properly and not break.

### Affected platform

Browser's extension

### Operating system

Windows 11 21H2 (Build 22000.1219)

### Browser

Vivaldi 5.6.2867.46 (Stable channel) (64-bit), based on Chrome 108

### Additional information

`navigator.plugins` output with Ruffle's `RufflePluginArray` ![vivaldi_4yZ2Q4SJu8](https://user-images.githubusercontent.com/3598140/208376363-8362495f-f43e-438b-be7c-a8fb3ffd8fe9.png)
`navigator.plugins` output with the browser's default `PluginArray` (note the different prototype) ![vivaldi_lcsgvIwfO6](https://user-images.githubusercontent.com/3598140/208376366-ea8f5e64-76b1-4019-a9eb-4665ef272129.png)
The original error (not directly related to Ruffle) ![vivaldi_Ps3wb60q5v](https://user-images.githubusercontent.com/3598140/208376368-8b42d48c-4c6b-440f-9413-63189d1e8303.png)

**Comment by n0samu** [comment]
Thank you for the report. To assist others in looking into this issue, here is an example of a product page that is affected: https://battleaxe.gumroad.com/l/overlord
