### ISSUE TITLE
Castle Crashing the Beard - very minor error

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8848]
### Describe the bug

This error appears at the end of the game after defeating Tom/The Beard
This game works amazingly in Ruffle

`ERROR ruffle_core::library] Tried to instantiate non-registered character kundefined`

### Expected behavior

shouldn't be an error

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[beardoNDk2.zip](https://github.com/ruffle-rs/ruffle/files/10261589/beardoNDk2.zip)

**Comment by n0samu** [comment]
Closing since you said the game works
