### ISSUE TITLE
Cave Explorer - Funky issues

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8853]
### Describe the bug

the game does load now and the buttons do work, but click the options button, and you get strange graphical glitches, press new game and Ruffle stops a script from running while it loads, and then finally gets ingame, but the keys to move work strangely

![cavex4](https://user-images.githubusercontent.com/102984201/208497788-7de9750c-6e0c-4d55-aead-783dc2bcc6ef.jpg)

### Expected behavior

the game should work properly

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[588630_caveEx4.zip](https://github.com/ruffle-rs/ruffle/files/10261902/588630_caveEx4.zip)

**Comment by Lord-McSweeney** [comment]
The game doesn't work for me on the web. I get `Error occured when running AVM2 frame script: RustError("Cannot access property http://adobe.com/AS3/2006/builtin::indexOf of null or undefined")`

**Comment by sodscg** [comment]
yup, I only tested the desktop version, as my comment above displays 👍

**Comment by n0samu** [comment]
> click the options button, and you get strange graphical glitches

Can confirm this.

> press new game and Ruffle stops a script from running while it loads

I am unable to reproduce this problem. Clicking New Game works fine for me.

> the keys to move work strangely

Can you explain what you mean by this? I'm not noticing anything unusual, but I'm not familiar with this game.

**Comment by sodscg** [comment]
clicking new game for me causes ruffle to think for a while, then the log says sonething like
'this script took too long, ruffle has stopped it'
the game then is playable, but moving basically doesn't work

pressing the 'd' key maybe will make the character move one grid tile, but nothing else, even if held down  and sny more presses gives nothing
and the other keys don't work at all, the game is not frozen, though

**Comment by n0samu** [comment]
I'm adding the performance label to this issue because it seems like a script is running much slower on your computer than on mine. I don't know why that would be happening, but that's what it sounds like.

**Comment by sodscg** [comment]
good news and bad news
the latest update 2023-01-15 makes the game playable, ruffle no longer prevents me from playing

the bad news is, the movement is now still not what it should be, but different from before.

now, you move in a stutter step. the game isn't lagging, though, Ruffle just makes you not move smoothly anymore, and this carries over to mining
now, it was sort of like this in the original, but ruffle really exaggerates it.


flash

https://user-images.githubusercontent.com/102984201/212552374-a46e006f-e74d-4fd9-b566-c3f9203e410d.mp4

Ruffle

https://user-images.githubusercontent.com/102984201/212552426-339fec8f-bbfd-432e-b8be-f0358ce30dd1.mp4

**Comment by sodscg** [comment]
additionally, I've found that the save doesn't work.
![savespot](https://user-images.githubusercontent.com/102984201/212552735-5b488d94-86fb-4616-8ee1-fa69aa32a8f7.jpg)
go there to save

when you close the game and click continue, the game will load like this
![save](https://user-images.githubusercontent.com/102984201/212552782-ede8e23e-fb2d-4b9e-a1fe-54a0b8bb787f.jpg)

I had to delete ruffle's save data to get the footage about the exaggerated movement

**Comment by sodscg** [comment]
everything seems to be fixed, including the options menu
