### ISSUE TITLE
Cube Colossus just keeps looping?

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#8857]
### Describe the bug

Here's a weird one
Cube Colossus will just jump back to the loading screen after starting the first mission, weird, right?

Flash Video

https://user-images.githubusercontent.com/103858019/208505982-6b713169-fa80-4962-b9a7-61c640415ee6.mp4

Ruffle Video

https://user-images.githubusercontent.com/103858019/208506031-37290dca-d9e2-4406-ac36-93bac152cfe4.mp4

### Expected behavior

the looping bit should never happen

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Also take a look at the ship trails, not perfectly the same, I guess

**Comment by Kz-92** [comment]
[cube-colossus - Copy.zip](https://github.com/ruffle-rs/ruffle/files/10262259/cube-colossus.-.Copy.zip)
almost didn't upload the swf

**Comment by Lord-McSweeney** [comment]
The movie jumps back, but the mouse cursor doesn't reset.
