### ISSUE TITLE
Destroy The Village - speed related issues 

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8859]
### Describe the bug

```
ERROR wgpu_hal::dx12::descriptor] Unable to allocate descriptors: RangeAllocationError { fragmented_free_length: 0 }
ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    not enough memory left

```

### Expected behavior

shouldn't  crash

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[bridge040_spill03_TEEN_destroyvillage.zip](https://github.com/ruffle-rs/ruffle/files/10262308/bridge040_spill03_TEEN_destroyvillage.zip)

**Comment by n0samu** [comment]
This seems to be the exact same bug as #8844. Can you check whether the game works for you in the old [2022-09-11 build](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2022-09-11) of Ruffle? If so, we can confirm this is the same bug.

**Comment by sodscg** [comment]
It doesn't crash that version of Ruffle, but I wouldn't say it 'works'
![ssa](https://user-images.githubusercontent.com/102984201/208963925-af8dfdc9-80f2-4e42-9548-aa4df33ed580.jpg)

**Comment by n0samu** [comment]
Right. Well, that's an entirely different bug 😉

**Comment by sodscg** [comment]
this is still an issue as of 2023-03-09

**Comment by sodscg** [comment]
the game seems to work now, but not very fast, as level 3 is pretty difficult to beat, as even though the game slows down, the fuel consumption doesn't, causing you to run out of fuel long before you ever should. even on the levels that are not as intensive, Ruffle is noticably slower

**Comment by n0samu** [comment]
Please open a new issue instead of just changing the title of your existing issue. It sounds like the original issue has been fixed so I'm closing this
