### ISSUE TITLE
Problems when playing Frontline Defense: First Assault by Max Games

### ISSUE THREAD

**Issue by brickblock369** [ruffle-rs/ruffle#8872]
### Describe the bug

[This link is one of the sites that hosts the Frontline Defense: First Assault.](https://www.gameflare.com/online-game/frontline-defense/)

The majority of the screen is filled with a yellow-tinted screen, such as the area selection map in this screenshot. That's not supposed to happen, and it makes viewing harder. Those borders on the edge are unaffected, though.
![Screenshot (113)](https://user-images.githubusercontent.com/59150779/208537422-bf342b69-31de-4d37-986c-a63b4d83e1bf.png)

Additionally, when a turret in-game stops detecting an enemy in range, it still continuously does the attacking animation, and when a new enemy is in range, the turret is still stuck like that, making it useless for the rest of the game.

### Expected behavior

The game didn't even have a yellow-tinted screen at the center, it was just clear.

When a turret doesn't detect an enemy anymore, it's supposed to stop and then attack again whenever a new enemy is in range.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome Version 108.0.5359.125

**Comment by Lord-McSweeney** [comment]
The tower issue seems to be the same issue as #993.

**Comment by n0samu** [comment]
The yellow-tinted screen problem has been fixed by #8262 and #9134.

**Comment by brickblock369** [comment]
Thanks!
