### ISSUE TITLE
Train Mania: Wrong objects are loaded into the level

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8874]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/trainmania.swf

In [Train Mania](http://www.notdoppler.com/trainmania.php), there are a few problems:
- The buttons to select a level and a train are extremely difficult to click.
- Level 1 is completely different in Ruffle from how it is in Flash Player. All of the elements/objects are different and so is the track layout. The level is possible to complete, but is much harder than the real level 1.
- After beating level 1, level 2 is not unlocked, and the game loops back to the intro screen and main menu. When this happens, the following error is spammed in the terminal:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2575f6de930 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x2576cef9868 }))) : RustError("ArgumentError: Child is not a child of this object")`

Here is a video demonstrating all of the above issues:

https://user-images.githubusercontent.com/71368227/208618390-71f69614-f32e-4f49-b3f0-2166544e1da2.mp4

### Expected behavior

These problems should not occur.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
This game runs at less than 10 FPS for me on the web. Is there any performance hit on the desktop app?

**Comment by n0samu** [comment]
If you watch my video you can see that it performs well in the desktop app. Web builds of Ruffle can be slower.

**Comment by n0samu** [comment]
Fixed by #9609! 🎉
