### ISSUE TITLE
Age of War - closure invoked recursively or destroyed already

### ISSUE THREAD

**Issue by XXLuigiMario** [ruffle-rs/ruffle#888]
In Age of War, when attempting to spawn units in-game (first option in the menu), nothing appears to occur.
Instead, the following error pops up in the JavaScript console `Uncaught Error: closure invoked recursively or destroyed already`.

Upon closer inspection of the game under FFDec, I determined that Ruffle errors when accessing an array named "tray".
This snippet is from the `DoAction` attached to tag `DefineSprite (212: menu)`.
![tray](https://user-images.githubusercontent.com/7153662/87863030-0f0bf100-c957-11ea-9cd0-22aa1784ec7a.PNG)

If we get rid of the check along with other references to "tray" we can get units to spawn, however we lose queuing functionality.

**Video**: https://streamable.com/h1bfpu
**Video (once "tray" removed)**: https://streamable.com/govqsm
**Game file**: http://farm.maxgames.com/ageofwarupdate1MzYx.swf

**Comment by Herschel** [comment]
Constructing an array in this way does not work currently: `tray = Array(0,0,0,0,0);` 
`avm1::array::constructor` needs to return the array in this case (the difference between [[Construct]] and [[Call]] bites us again!)

**Comment by Herschel** [comment]
This particular issue is fixed (although the buttons still have clicking issues, requires some investigation but probably due to button shape hit testing).
