### ISSUE TITLE
Sometimes it works, sometimes it doesn't (chrome add on)

### ISSUE THREAD

**Issue by BAP00tato** [ruffle-rs/ruffle#8887]
when I open chrome, it works but as soon as I reload or go on another page with flash it stops working and instead display the "adobe flash is not longer supported"

**Comment by n0samu** [comment]
From the [FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#when-browsing-the-wayback-machine-i-see-a-box-saying-adobe-flash-player-is-no-longer-supported):
> In Chrome, Edge and other Chromium-based browsers, the Ruffle extension sometimes cannot load early enough to play Flash content on the page. To fix the issue, simply ["hard refresh" the page](https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/) by holding down the Shift key while clicking the browser's Reload icon.

Let me know if this helps!

**Comment by BAP00tato** [comment]
Yep! a hard refresh work! Thanks!
