### ISSUE TITLE
https://evilgames.eu/flashgames/frog-fable.htm not working

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#8888]
### Describe the bug

On https://evilgames.eu/flashgames/frog-fable.htm, many AVM errors are reported in the console. They're all something like this: `Got AVM2 error AvmError(Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x20178cc }))))) when attempting to assign symbol class [something]`. Based on the quantity of errors, I would guess that this is unintentional. The game is stuck on a black screen. The only other warning shown in the console is `Unknown tag code: 72`

### Expected behavior

The thousands of warnings should not appear.

### Affected platform

Browser's extension

### Operating system

Ubuntu 20.04, Linux 5.13

### Browser

Chrome 108

**Comment by Lord-McSweeney** [comment]
Looks like the next thing this needs is `flash.display.Shader`.

**Comment by Lord-McSweeney** [comment]
The game is playable now, but is slow and has issues with the BigDino intro.

**Comment by n0samu** [comment]
Original issue is fixed. I've opened #13110 to track the BigDino intro problem.
