### ISSUE TITLE
Vex 2: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8889]
### Describe the bug

After clicking the Play button on the main menu, [Vex 2](http://www.notdoppler.com/vex2.php) gets stuck on the screen shown below. This error is shown in the terminal:
`[ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x24a1f848d20 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x24a5b5f8f98 }))) : RustError("Non-public property http://adobe.com/AS3/2006/builtin::hasOwnProperty not found on Object")`

![image](https://user-images.githubusercontent.com/71368227/209119784-ede4be74-116d-4a78-b47e-fca8691d50c2.png)

### Expected behavior

The game should start.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
There's also `ReferenceError: Error #1069: Property perspectiveProjection not found on flash.geom.Transform and there is no default value.` and `Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xaa87e0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0xaa86e4 }))) : AvmError(Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0xaa90dc })))))`, although neither of those actually stop the game from working.

**Comment by n0samu** [comment]
Now the error is:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: ReferenceError: Error #1069: Property http://adobe.com/AS3/2006/builtin::hasOwnProperty not found on Class and there is no default value.
        at fl.motion::AnimatorFactoryBase/addTargetInfo()
        at gameTransitionIn()
        at Main/checkTransitionDone()
        at Main/update()
```

**Comment by n0samu** [comment]
Now the error is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2029d84d888 }) to handler FunctionObject(FunctionObject { ptr: 0x20292d3b518 }) : ReferenceError: Error #1056: Cannot create property matrix3D on flash.geom.Transform.`

**Comment by MartySVK** [comment]
Probably thanks to https://github.com/ruffle-rs/ruffle/pull/11495, the game looks playable now 🥳
