### ISSUE TITLE
not support some cntv videos

### ISSUE THREAD

**Issue by ivysrono** [ruffle-rs/ruffle#8890]
### Describe the bug

Not support:

https://politics.cntv.cn/special/gwyvideo/likeqiang/201907/2019072301/index.shtml

https://politics.cntv.cn/special/gwyvideo/xiaojie/202010/2020101201/

https://politics.cntv.cn/special/gwyvideo/likeqiang/202012/2020122401/

https://politics.cntv.cn/special/gwyvideo/2019/202010/2020101706/

### Expected behavior

Play these videos.

### Affected platform

Browser's extension

### Operating system

Win11

### Browser

Firefox 108

**Comment by n0samu** [comment]
I am unable to access any of the Flash content on those pages. Regardless, the answer is likely the same as for #8891.
