### ISSUE TITLE
not support some sina video

### ISSUE THREAD

**Issue by ivysrono** [ruffle-rs/ruffle#8892]
### Describe the bug

https://open.sina.com.cn/course/id_686/

```
Ruffle wasn't able to run the Flash embedded in this page. 
You can try to open the file in a separate tab, to sidestep this issue.
```

### Expected behavior

Play the video.

### Affected platform

Browser's extension

### Operating system

Win11

### Browser

Firefox 108

**Comment by n0samu** [comment]
> Ruffle wasn't able to run the Flash embedded in this page. 

Clicking "Open in a new tab" bypasses this error.

Otherwise, the answer is exactly the same as for #8891. Closing in favor of that issue.
