### ISSUE TITLE
Dangeresque Roomisode 1: Behind the Dangerdesque: Intro softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#8895]
### Describe the bug

Found this out on Twitter, this game seems to quickly get stuck in a loop as soon as you start with Strong Bad trying to shut a never closing door, talking with Nosamu this game requires stage.invalidate support to work.

https://homestarrunner.com/dangeresque

### Expected behavior

Strong Bad should be able to shut the door without softlocking.

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 108

**Comment by n0samu** [comment]
CC #8561

**Comment by Lord-McSweeney** [comment]
Fixed by #9339.
