### ISSUE TITLE
Super Mario 63 starts glitching out when you enter the castle after the tutorial

### ISSUE THREAD

**Issue by auserishere** [ruffle-rs/ruffle#8897]
### Describe the bug

It glitches out like this:
![2022-12-22 16_18_00-480 swf - Chromium](https://user-images.githubusercontent.com/120981002/209241526-4cc1cb59-3a7b-4967-94a7-9376face9c43.png)

### Expected behavior

Its supposed to run like this:
![2022-12-22 16_24_50-Adobe Flash Player 32](https://user-images.githubusercontent.com/120981002/209241697-cd4a2e98-9a80-434d-a623-f9de015be730.png)

### Affected platform

Desktop app

### Operating system

Windows 8.1 (Build 9600.20721)

### Browser

Chromium 87.0.4272.0 (Developer Build) (64-bit)

### Additional information

The link to the file:
https://github.com/auserishere/Untitled-Game-Site-Resources/blob/main/480.swf

**Comment by n0samu** [comment]
Already reported in #8217
