### ISSUE TITLE
Cannot open the game 'bloons' (bloons.swf)

### ISSUE THREAD

**Issue by anoop-manakkalath** [ruffle-rs/ruffle#8904]
### Describe the bug

I was using bloons game with ruffle. The last version of ruffle that supported this game was released on 20220902. All the releases after this, fails miserably opening up this swf game.
[bloons.zip](https://github.com/ruffle-rs/ruffle/files/10294248/bloons.zip)

### Expected behavior

The game should be playable by ruffle.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
Does this run on the web app for you? For me it runs fine on web.

**Comment by n0samu** [comment]
I'm not having any problems running this game on either desktop or web. Can you tell me exactly what issue you're experiencing with the game? And does it happen with other games, or only this one?

**Comment by anoop-manakkalath** [comment]
After long time, I tried ruffle with the version 20220202. Now I'm able to open my flash games 'bloons.swf' and 'prince.swf'. Thanks for the fix.
