### ISSUE TITLE
Error on https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html

### ISSUE THREAD

**Issue by Uneuclid** [ruffle-rs/ruffle#8905]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
D/n.wbg.__wbg_new_f9bb493369a83c12@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.78d0f623a87a29523676.js:1:6507
std::sync::once::Once::call_once::{{closure}}::h2e61d96ea4417fe9@:wasm-function[1098]:0x2a793e
std::sys_common::once::generic::Once::call::h62f79875d8dd2a00@:wasm-function[1410]:0x3186b8
core::ops::function::FnOnce::call_once{{vtable.shim}}::hc298a7f922019542@:wasm-function[5022]:0x4b3271
std::panicking::rust_panic_with_hook::he04cb00575f2a1e3@:wasm-function[3748]:0x46f19b
core::panicking::panic_fmt::h586d720a90aa8503@:wasm-function[5264]:0x4b80ea
core::option::expect_failed::h1e9a9cbb22bbd6ac@:wasm-function[5940]:0x4cb59c
ruffle_core::display_object::stage::Stage::root_clip::hce7143ccaa376c8d@:wasm-function[3752]:0x46f4da
ruffle_web::Ruffle::tick::hdcb4afd54d8a568d@:wasm-function[648]:0x1f284c
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h5b63cba1bdda8f36@:wasm-function[6184]:0x4d38fe
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h290fb0fdd8b6051e@:wasm-function[5623]:0x4c1e89
S@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.78d0f623a87a29523676.js:1:2578
c@https://uploads.ungrounded.net/ruffle_wrapper/lib/core.ruffle.78d0f623a87a29523676.js:1:2255

```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&useloader=1&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1671755499%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F560000%2F560190_Justin_Bieber.swf%3F1295769007%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2263a5d364560cf%22%2C%22NewgroundsAPI_SessionID%22%3A%22hfj6w3OodOUkNoZgpMXB6daeb490b65ad1c9415c972eba768b94cf716dc9RnUe%22%2C%22NewgroundsAPI_UserName%22%3A%22CC531%22%2C%22NewgroundsAPI_UserID%22%3A7478992%2C%22ng_username%22%3A%22CC531%22%7D%2C%22width%22%3A550%2C%22height%22%3A400%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F560000%2Fflash_560190.jpg%3Ff1363837880%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D
SWF URL: https://uploads.ungrounded.net/560000/560190_Justin_Bieber.swf?1295769007

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.11.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-22
Channel: nightly
Built: 2022-12-22T00:14:42.760Z
Commit: 7a09dd563980b378eb2b6702a227c7b346b5ae3e
Is extension: false

# Metadata
width: 550
height: 400
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 1190248

**Comment by n0samu** [comment]
This animation uses Flex SWZs, specifically `textLayout_1.0.0.595.swz` (see #8006). As of Ruffle build nightly-2022-12-07, it's possible to skip loading the SWZ and play the animation by right-click => Play. But as of the latest Ruffle build, doing that causes the error reported above.
