### ISSUE TITLE
Madness Rising: Visual issues

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#8917]
### Describe the bug
https://www.newgrounds.com/portal/view/512343/format/flash
For some reason this animation seems to have trouble on my S22, without testing the Blend Mode PR fixes, as soon as I start the animation, it immediately starts throwing up multiple times and looks like this.

[.WebGL-0x2035adb00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
![MD2](https://user-images.githubusercontent.com/78768499/209451349-d9fc468d-17b5-440a-aadc-b7b8fb9ffe3b.png)

With the Blend mode PR, I don't see the texture bound errors anymore, but I do get this instead and it looks like this, which is closer to how it should look, but only a partial amount of the ground seems to show up.

"020ea352:0x66f572 Error running definition tag: DefineBitsJpeg3, got Couldn't register bitmap"
![MD4](https://user-images.githubusercontent.com/78768499/209451392-7e19160d-3385-459c-a9c4-2453448690b4.jpg)

### Expected behavior

It should be displaying perfectly without any black screen or invisible ground issues, it works perfectly on my laptop and on my steam deck, whether i'm using the blend mode PR stuff or not.
![MD](https://user-images.githubusercontent.com/78768499/209451414-96239eb5-a2ce-447e-b0f9-8230a9d51378.png)

### Affected platform

Browser's extension

### Operating system

Android 13

### Browser

Chrome 108

**Comment by Lord-McSweeney** [comment]
This seems to be related to #6365. Are there any "width or height out of range" errors on this one?

**Comment by waspennator** [comment]
Tried it out again with NG's version of ruffle and as soon as I get to the preloader, I immediately saw 

"ruffle_web-wasm_extensions.js:1094 WebGL: INVALID_VALUE: texImage2D: width or height out of range"

in the console log. followed by the texture bound errors if I start the animation.

**Comment by waspennator** [comment]
For some reason testing on the latest nightly on ng, the ground renders perfectly fine on Firefox on my s22, so I'm guessing it's a chromium browser based issue

**Comment by waspennator** [comment]
Animation has regressed on chrominium browsers it seems and is now tossing up a "called Option::unwrap() on a None value'," error on my S22 on browsers that aren't firefox, dying when its trying to run the ingame preloader.

**Comment by waspennator** [comment]
Decided to test the copy on the ruffle web demo with the latest nightly, it doesn't seem to be panicking ruffle anymore with the unwrap on none value error and its rendering the ground too now. Outside of some slight hitching which only happens for like a half second or so every so often, this seems to be resolved. Just need to wait for NG to update to the latest nightly.
