### ISSUE TITLE
Ruff Ruffman Germinator: Enemies do not damage the player

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8920]
### Describe the bug

Link to SWF: https://theghostboi64.github.io/germinator/germinator.swf
This game is multi-asset, so you should run the game directly from its URL.

In Ruff Ruffman Germinator, the enemies don't damage or interact with the player character at all. So the levels present no challenge whatsoever.

### Expected behavior

Immune cells should damage the player and mouthwash should push the player back.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This happens because BitmapData.Draw with blend modes is unimplemented:
`[WARN  ruffle_core::avm1::globals::bitmap_data] BitmapData.draw with blend mode - not implemented`
This game should be a good test for anyone working on implementing that.

**Comment by Lord-McSweeney** [comment]
There are also "Invalid BitmapData size" errors with bitmap sizes such as 7x0, 23x0, and 27x0. Does Flash Player allow 0-height bitmaps?

**Comment by n0samu** [comment]
That's strange, I didn't see any such messages when I tested the game. And I am not seeing them now either.

**Comment by TheGhostboi64** [comment]
Here’s some footage if you are still confused 

https://user-images.githubusercontent.com/99986496/209480941-6753586c-9ca5-4808-a918-dd603073a3c8.mp4

I shrunked it to 8mb so that I can share it on discord as well

**Comment by TheGhostboi64** [comment]
Nevermind I’m not gonna send it to discord
