### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Anunnaki26** [ruffle-rs/ruffle#8928]
Hi guys
 
I became aware of Ruffle recently and I like it a lot. Simply awesome.
I bought a Flash Bulletin board system XML many years ago, but unfortunately this does not currently work with Ruffle.
http://nirvana.bplaced.net/Flash-XML-Pinnwand/index.html
http://nirvana.bplaced.net/Flash-XML-Pinnwand/ruffle.html
	
How long will it take approximately until Ruffle also can play flash files with actionscript3?
 
Do you know a way I can play my file on my notebook in the browser?
Thanks already for your tips!

**Comment by Lord-McSweeney** [comment]
Actionscript 3 support is more advanced than Ruffle claims it is, but most games still won't work well. There's no single release date for AS3, but you can use alternative older to run Flash content in-browser.

**Comment by ousia** [comment]
@Wahrheit26, Lightspark might help you.

**Comment by Wahrheit26** [comment]
Thanks for your answers and your tips!

Does the browser play Flash files automatically or do you need an additional plugin or Adobe Flash Player?

**Comment by Benman2785** [comment]
you need to install a specific version of flash-player: Adobe Flash Player 32.0.0.371
while install you need to UNCHECK UPDATE - otherwise it downloads an update that disables flash player...
ps i use an older version of K-Meleon for use with flash-player

**Comment by Wahrheit26** [comment]
where can I get this specific version of flash-player: Adobe Flash Player 32.0.0.371

**Comment by Lord-McSweeney** [comment]
Still doesn't work, though there are no errors.

**Comment by evilpie** [comment]
This works now. We already have #12872 for the slight rendering issue.
