### ISSUE TITLE
Can't delete save file

### ISSUE THREAD

**Issue by User-444** [ruffle-rs/ruffle#8929]
### Describe the bug

On the game Papa's Pizzeria 
![Untitled drawing (8)](https://user-images.githubusercontent.com/102774895/209576730-879fcec2-4e50-4640-b600-84b7b5ad9715.png)
I'm trying to erase the save data but when i click yes it redirect's me to flipline studios

### Expected behavior

For the save file to be deleted and not redirect me to flipline studios

### Affected platform

Browser's extension

### Operating system

MacOS

**Comment by Lord-McSweeney** [comment]
Can you provide a URL to the site?

**Comment by User-444** [comment]
it happens when i do this <img width="644" alt="Screen Shot 2022-12-26 at 1 21 00 PM" src="https://user-images.githubusercontent.com/102774895/209581117-2af66a6d-8536-44df-b54b-8217856a8fbe.png">
so the website is
chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fi.flipline.com%2Fgamefiles%2Fpapaspizzeria%2Fpapaspizzeria_v2.swf

**Comment by n0samu** [comment]
That means the SWF URL is: https://i.flipline.com/gamefiles/papaspizzeria/papaspizzeria_v2.swf

Anyway, this seems to be a hitTest issue. When you click the "Yes" button, Ruffle interprets that as a click on the Flipline logo button underneath the "Yes" button.

**Comment by n0samu** [comment]
So I just checked the game in Flash Player and it actually has the same problem. So it's an issue with the game, not Ruffle.

**Comment by Lord-McSweeney** [comment]
If you manage click in the correct place, you can click the button.
