### ISSUE TITLE
AVM2 - Sprite with a looping animation displays one frame too many

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#8940]
### Describe the bug

In [This AS3 flash](https://mrcheeze.github.io/homestuck-ruffle-tester/#00397), the main character sprite has a script that loops his idle animation at frame 13.
![image](https://user-images.githubusercontent.com/6541413/209710605-f1b5957c-12ca-42f4-9edb-8c70cd0e29bb.png)
![image](https://user-images.githubusercontent.com/6541413/209711169-0064d5b4-967e-4041-b2fa-6a5d53b442c8.png)
![image](https://user-images.githubusercontent.com/6541413/209711285-de754f82-dd79-42b0-8dd8-5a63cbc5be30.png)

In flash player, we never see him rendered in the "frame 13" pose - he is always holding the stick up. In ruffle, we see him in the frame 13 pose for one frame before the loop happens.

I'm not certain that this issue is AVM2-specific, I'm just assuming that it would have already been noticed and fixed otherwise.

### Expected behavior

Load this flash: https://mrcheeze.github.io/homestuck-ruffle-tester/#00397

The character should have an idle animation where he constantly holds the stick up. Instead, ruffle incorrectly includes the below frame in the idle animation where the stick is missing.

![image](https://user-images.githubusercontent.com/6541413/209710057-0648004f-7025-44e2-a0a7-d7aa3dd3e94e.png)

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Mozilla Firefox

**Comment by Lord-McSweeney** [comment]
This appears to be fixed by #8944, but now there is another issue visible: the health bars are not centered correctly.

**Comment by MrCheeze** [comment]
> This appears to be fixed by #8944, but now there is another issue visible: the health bars are not centered correctly.

You're right on both counts. The issue this ticket was opened for is now fixed. And the healthbar looks slightly wrong in Ruffle compared to flash player.

I already know why that second issue happens though - it's because this flash sets itself to Low Quality, and AFAIK quality settings aren't really supported right now.

Pictured below, from left to right: Flash Player, Flash Player with the quality changed from Low to High, and Ruffle.

![image](https://user-images.githubusercontent.com/6541413/209843091-326a61e5-180f-4b40-9ee3-7e2cfaaeeafc.png)

I am fine with closing this ticket as the original issue is fixed and the quality setting issue is very minor.

**Comment by Lord-McSweeney** [comment]
If you attack it more, the problem becomes clearly visible: the entire health bar shuffles over. (at least, on the desktop version):
![Screenshot at 2022-12-28 20-08-46](https://user-images.githubusercontent.com/84632019/209847720-d781d2f2-1c9e-46ee-9dfd-7a79adafe81f.png)

**Comment by MrCheeze** [comment]
Oh, that? It's just how they're coded to work, it's a gag ;)
