### ISSUE TITLE
opening new tab error

### ISSUE THREAD

**Issue by joskini77** [ruffle-rs/ruffle#8943]
### Describe the bug

NoSuchKeyThe specified key does not exist.properties/cn/cn4/legacy_cdn/PUBLIC_WEB/cn30/content/1/game/copa-toon-superestrellas/spanish/Copatoon2013.ES/Main.swfDQRECFAH655F9STGhilBNL7TLcqx4tMFXOqpwmrC5h/zmhZlXCH58ZhFRYTYCmEKc0YV2uYl6Wn3XgiJTPKhjpL19y8=

### Expected behavior

i was trying to play a cartoon network game but ruffle says is not posible to emulate and they recomend me to
 open a new tab but that dosent work too
<img width="571" alt="isue" src="https://user-images.githubusercontent.com/121525739/209738542-4953aee9-c656-4778-86ad-9ce9040cb769.PNG">
<img width="887" alt="error" src="https://user-images.githubusercontent.com/121525739/209738553-aaa1830b-511d-455a-a441-49d16ee3c723.PNG">

### Affected platform

Browser's extension

### Operating system

windows 10

### Browser

google chrome

**Comment by Lord-McSweeney** [comment]
This looks like a problem with the SWF. It was probably removed by Cartoon Network. You can try finding an archived version on https://web.archive.org. Can you send the URL to the page?

**Comment by joskini77** [comment]
the page of the game is 
https://www.cartoonnetwork.com.mx/juego/copa-toon-superestrellas

**Comment by Lord-McSweeney** [comment]
It looks like the swf was being hosted by a third-party, which then removed those files. It doesn't seem to be archived anywhere on the Wayback Machine, but it is on Flashpoint (https://bluemaxima.org/flashpoint/). Other than that, I could not find the original game anywhere else on the web (all the CDNs that previously hosted it have removed it or are down).

**Comment by Lord-McSweeney** [comment]
This issue should be closed, as it is unrelated to Ruffle.
