### ISSUE TITLE
Pursuit of Hat: Player character does not appear in level 6 after beating level 5

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#8947]
### Describe the bug

Link to SWF file: http://i.notdoppler.com/files/pursuitofhat.swf

The previous issue #8003 with [Pursuit of Hat](http://www.notdoppler.com/pursuitofhat.php) is now fixed. But after beating level 5 and clicking "next level", level 6 loads without the player character.
![image](https://user-images.githubusercontent.com/71368227/209775852-c032511f-ee4d-4c57-a2c7-90ff94b9b5fd.png)

The level loads normally if you click the "reset" button or load it from the level select screen instead.

The problem also happens after beating levels 6 and 7, but not after beating level 8 or levels 1-4.

There are some other minor issues with the game (also mentioned in #8003):
- You need to click inside each level to activate the keyboard controls.
- Restarting a level does not play the associated sound effect.
- The BigDino intro animation is skipped, though its audio plays.

### Expected behavior

Level 6 should load with the player character:
![image](https://user-images.githubusercontent.com/71368227/209775901-0e679df8-a075-40aa-8e35-3104f7bc55c7.png)

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
Besides the BigDino intro being skipped, all of these problems are fixed now!

**Comment by MartySVK** [comment]
looks like game is broken, I see spamming error:

``Error #1009: Cannot access a property or method of a null object reference. (accessing field: parent)
``

**Comment by n0samu** [comment]
The BigDino intro skip has been fixed by #13389!
