### ISSUE TITLE
Newgrounds API Preloader gets stuck

### ISSUE THREAD

**Issue by RealLifeChihiro** [ruffle-rs/ruffle#896]
The Newgrounds API, used in games like "Stealing the Diamond", [https://www.spontaneousegg.com/games/henry-stickmin/stealing-the-diamond/](url) does not function properly in Ruffle (outside of Newgrounds.com at least). As seen on my website, the loading freezes at a certain point, due to Ruffle not doing the API things that Flash Player usually does. If anyone needs it, the swf can be located here. [https://www.spontaneousegg.com/games/henry-stickmin/stealing-the-diamond/stealingthediamond.swf](url)

**Comment by Dinnerbone** [comment]
Looks like the specific thing missing here may be [LoadVars.sendAndLoad](https://github.com/ruffle-rs/ruffle/issues/258)

**Comment by Herschel** [comment]
sendAndLoad was implemented, and looks like this is working now:
https://www.newgrounds.com/portal/view/574241/format/flash?emulate=flash
