### ISSUE TITLE
Character falls through ground

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#8973]
### Describe the bug

On https://www.addictinggames.com/sites/default/files/flash_games/blackopskoreanconflict_0.swf, after starting "Training", the character will fall through the ground. This makes the game completely unplayable.

### Expected behavior

The character does not fall through the ground.

### Affected platform

Browser's extension

### Operating system

Linux

### Browser

Chrome 108

**Comment by n0samu** [comment]
This happens because the game uses `BitmapData.draw` to draw and hitTest against the ground, and this is not yet implemented in web builds of Ruffle.

**Comment by Lord-McSweeney** [comment]
I see now. The game runs fine on the desktop version.

**Comment by Lord-McSweeney** [comment]
Fixed by #9134.
