### ISSUE TITLE
spongebob squarepants saves bikini bottom: buttoms

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#8980]
### Describe the bug

https://user-images.githubusercontent.com/75534590/210172887-9d7d4c8e-9a31-42b1-81b2-b9b3b478ab25.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/210172889-6b30fc01-7800-400b-ad29-524029704ab6.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

https://anonfiles.com/S9Od7aPfyc/sb_saves_rar

main.swf is origin, main1.swf modified due to won't bypassed on original flash player.

**Comment by n0samu** [comment]
When possible, can you please upload the files directly to GitHub instead of using an external upload service? The download from this site is extremely slow and there's no guarantee it won't shut down or delete your file at some point in the future.

**Comment by p0008874** [comment]
@n0samu [sb_saves.zip](https://github.com/ruffle-rs/ruffle/files/10330471/sb_saves.zip)

**Comment by Lord-McSweeney** [comment]
Issue on main1.swf no longer occurring.
