### ISSUE TITLE
The screen is foggy:Micwizard

### ISSUE THREAD

**Issue by chuu2-shakaijin** [ruffle-rs/ruffle#8994]
### Describe the bug

I reported this on Discord a few years ago, but I'll also report it on Github just in case.

The screen is foggy and I can't see it well.
The same problem occurs not only in the desktop version of windows 10, but also in the browser extension of firefox.

Page URL:http://stickpage.com/micwizardplay.shtml

![image](https://user-images.githubusercontent.com/77331544/210224050-1ca2a15f-33ec-4af3-8d39-10ba0cdcc5ea.png)

original view (youtube movie)
![image](https://user-images.githubusercontent.com/77331544/210224095-fb4037cf-722b-450e-9b97-d8fbc5e387ca.png)

### Expected behavior

Perhaps there is a problem with the drawing order or composition method.

### Affected platform

Desktop app

### Operating system

windows 10

### Browser

Mozilla Firefox 108.0.1

**Comment by Lord-McSweeney** [comment]
This is a missing blend mode problem (missing add, overlay, and invert). As #8262 has just been merged, this problem should be fixed in the next release.
