### ISSUE TITLE
AS2/AS3 support

### ISSUE THREAD

**Issue by aolko** [ruffle-rs/ruffle#9]
Does is support AS2/AS3 and what features of it (full support/partial support)?

**Comment by Herschel** [comment]
Hi @aolko,

The project is still very early so ActionScript support is still in the infancy. The beginnings of AS1/AS2 support in place, so I am hoping to have 1999-era Flash games running soon. I am starting from the earliest AS bytecodes in the SWF spec and working up from there.

It will be important to have various test cases for the AS interpreter, and compare it against the output from the official Flash player (see #1).

AS3 execution is not in place at all, although I've written the ABC bytecode parser in [swf-rs](https://github.com/Herschel/swf-rs/blob/master/src/avm2/types.rs). 

I typed up a [project roadmap](https://github.com/Herschel/swf-rs/blob/master/src/avm2/types.rs). It would also be useful to put the project status in the README.

Thanks for the interest, sorry for the delay in responding!

**Comment by Herschel** [comment]
Added the project status to the README. Closing in favor of #12
