### ISSUE TITLE
web: Missing texts and textures on certain mobile devices

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#900]
Tested on Newgrounds using an iPad Air 2. I haven't reproduced this issue on Android devices.

Mini-Putt 2: https://www.newgrounds.com/portal/view/38598/format/flash?emulate=flash
Streets Of Fire: https://www.newgrounds.com/portal/view/225944/format/flash?emulate=flash

iPad (missing default and player scores):
![f1](https://user-images.githubusercontent.com/14274782/88048206-34fde500-cb53-11ea-9c3f-3696d1534405.png)

Windows:
![f1-win](https://user-images.githubusercontent.com/14274782/88048460-a9d11f00-cb53-11ea-8d1f-51000be993ac.png)

----

iPad (missing texture of the grass?):
![f2](https://user-images.githubusercontent.com/14274782/88048259-4cd56900-cb53-11ea-879d-fcc4fff0e635.png)

Windows:
![f2-win](https://user-images.githubusercontent.com/14274782/88048272-5232b380-cb53-11ea-8ae7-ee1fce30af22.png)

----

iPad (again, some missing texts, I've seen that happening on many files):
![f3](https://user-images.githubusercontent.com/14274782/88048303-64aced00-cb53-11ea-8db7-9dd86f980c02.png)

Windows:
![f3-win](https://user-images.githubusercontent.com/14274782/88048495-b9e8fe80-cb53-11ea-858f-b4a3cf6bfbda.png)

**Comment by Herschel** [comment]
I'd imagine this is some issue with the canvas backend (possibly #25). Are you able to try this in Chrome on the device?

**Comment by Toad06** [comment]
Same issue with Chrome on iPad, unfortunately.
Note that clicking "Request Desktop Website" or "Request Mobile Website" does not change anything too.

However, I've tried the mini-golf game with an old version of Ruffle and the default scores and texture of the grass are displayed. That's really weird (could this be because of WebGL 2?).

Mini-golf sample with Ruffle version 2020-03-26:
[ztestGolf.zip](https://github.com/ruffle-rs/ruffle/files/4954574/ztestGolf.zip)

**Comment by Toad06** [comment]
Still happening in the new iPadOS 14.

A few observations using the mini-putt game:
- When Ruffle fallbacks to WebGL 1 (which is always the case on iPad / Safari), the texture of the grass is never displayed, even on Windows (tested on Firefox and Chrome). However, the issues with the missing texts remain exclusive to the iPad.
- When Ruffle fallbacks to canvas, none of these issues appear.

**Comment by BestPresident** [comment]
These files have a similar/related problems. Text appears on PC but not on mobile chrome or safari.
[05jobclothes.zip](https://github.com/ruffle-rs/ruffle/files/5506230/05jobclothes.zip)

[9guesswords01.zip](https://github.com/ruffle-rs/ruffle/files/5506231/9guesswords01.zip)

**Comment by neave** [comment]
I'm seeing the same issue with [hexxagon.com](https://hexxagon.com) – an AS1 game. Most text is not displaying on iOS/iPadOS 14, but text displays fine on desktop browsers.

**Comment by TomFulp** [comment]
In case this is useful, using Arial Bold in my example, the text shows up if the font size is 29 or greater but doesn't render in iOS Safari if the font size is below 29.

Example SWF to try on an iPhone, the top two text boxes are size 50 and 29, bottom two are 28 and 16.
https://www.newgrounds.com/projects/games/1561930/preview/filetype/0

CS5.5 FLA file for example:
https://www.newgrounds.com/dump/item/f730be2f85addccb21825b3f4d9cc7f2

**Comment by Poopooracoocoo** [comment]
If you enable WebGL 2 support in the experimental features page of Safari's settings, what happens?

**Comment by Toad06** [comment]
Good idea, thanks for suggesting it. Unfortunately, the missing texts are still not displayed. This however fixes the issue with the missing texture (grass) in the mini-putt game.

**Comment by x3fold** [comment]
This issue is also occurring on Chromebooks running 87.0.4280.88 and later
Same as Toms observation, if the font is greater than 29pt then it does render

**Comment by Herschel** [comment]
Thanks for the report. The fact that it happens with small font sizes is odd. I wonder if the scale values for these fonts are becoming too small for the particular graphics driver and end up getting clamped to 0.

**Comment by x3fold** [comment]
Also as Toad06 noted on iPadOS 14 the same happens but on iOS 14 (on an iPhone) everything works perfectly.
Have tried both Safari and Chrome on both devices and the same occurs (iPhone works, iPad doesn't)

Something to do with resolution/PPI or renders used on the devices?

**Comment by x3fold** [comment]
Not sure if this helps or not. 

Have tested further and if you create a text field with a pt size of 15 and then scale the field 200% the font will show. Conversely, if you create a text field with a pt size of 29 and scale down 50% the font doesn't appear

[test.zip](https://github.com/ruffle-rs/ruffle/files/5848509/test.zip)

**Comment by Herschel** [comment]
Could someone test and verify that this is fixed by #3049? Thank you!

**Comment by Toad06** [comment]
Tested the mini-putt game again, and I confirm all texts are now displayed. 👍

**Comment by JamesAllgood** [comment]
Fixed all of my text issues on computers phones and tablets. 

Still got this text issue though. Not sure if its related. #2186

**Comment by neave** [comment]
Latest nightly seems to fix this issue for me

**Comment by Herschel** [comment]
Thanks all. #2186 is unrelated. Closing this issue.
