### ISSUE TITLE
Cannot type in EditText (focus related?)

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#9006]
### Describe the bug

Load the following flash: [html](https://mrcheeze.github.io/detritus/ruffle/00397_no_ctrlKey.html) / [swf](https://mrcheeze.github.io/detritus/ruffle/00397_no_ctrlKey.swf)

Press T to open a secret window. In flash player, you can type in the textbox that appears (and it also auto-focuses on the textbox). In ruffle you can't type at all.

Note that this is an AVM2 flash. Also, this may be related to a script that runs every frame, which removes focus from the input box and then gives it focus again. Here is the script (simplified):

```actionscript
public function enterFrame(param1:Event) : void
{
  stage.focus = stage;
  // ...
  stage.focus = this.secrets.promp.secretInput;
}
```

### Expected behavior

When you press T, a window opens with a textbox in it. You can type in the textbox. The textbox is auto-focused, so you don't have to click it.

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Mozilla Firefox

**Comment by Lord-McSweeney** [comment]
#8935 might fix this.

**Comment by n0samu** [comment]
> #8935 might fix this.

That's his own PR. Don't you think he would have tested that? 😛

**Comment by MrCheeze** [comment]
> #8935 might fix this.

It doesn't - that was the branch I first encountered this issue on, actually.

The original version of this flash required pressing CTRL+T to open the secret textbox. However the version I linked in this issue is edited so that CTRL is not required (because it's not actually relevant to the issue here).

**Comment by Lord-McSweeney** [comment]
I see. Does Ruffle implement the focus property at all?
