### ISSUE TITLE
AVM2 - unloaded child not removed from parent

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#9010]
### Describe the bug

I created [a test SWF](https://github.com/MrCheeze/ruffle/commit/dfa4f471246e775457b0776f8e2693698eb6ffcd#diff-0c6d4af2c20e12e7a50413c7a6d0e8669c9e2df15de558e50e2b54b806c7bf9e) that demonstrates this issue. In the movie below, "clip" is placed on the timeline on frame 3. In flash player, rewinding from frame 3 to frame 2 sets this.clip to null. In ruffle it does not:

![image](https://user-images.githubusercontent.com/6541413/210394435-59b418df-c558-44d0-ad75-4b1ac84872b9.png)
![image](https://user-images.githubusercontent.com/6541413/210394470-d820ba51-85a7-4768-8047-a065bbdc9239.png)
![image](https://user-images.githubusercontent.com/6541413/210394497-c46f7cee-2ab8-4ab2-8746-88435987c88a.png)
![image](https://user-images.githubusercontent.com/6541413/210394554-53114652-1e0a-4b56-a022-edcaa462c8cd.png)
![image](https://user-images.githubusercontent.com/6541413/210394601-fa11195b-34cb-41d8-b21a-f3b97f83ab23.png)

### Expected behavior

In the above movie, logging `this.clip` after rewinding from Frame 3 to Frame 2 should log `null` instead of `[object Symbol1_1]`.

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

Feel free to keep the regression test I created once this is fixed. I got as far as creating the test, but then couldn't figure out how to actually fix the issue myself.

Note to self: alterniabound

**Comment by MrCheeze** [comment]
Contrary to what I first wrote, this problem is not specific to rewinding, in fact it's not specific to gotoAndX at all.

Even in regular frame advancement of a movie, you still get the same problem where a parent keeps its references to children that don't exist anymore.

**Comment by MrCheeze** [comment]
@kmeisthax mentions [here](https://github.com/ruffle-rs/ruffle/pull/8667) "two ignored tests that won't work until I implement RemoveObject property nulling", so it looks like this is a known not-yet-implemented feature.

**Comment by n0samu** [comment]
Running your test SWF now in Ruffle, the output is correct, so I guess this was fixed? Please leave a comment if anything is still broken and I can reopen the issue.

**Comment by MrCheeze** [comment]
> Running your test SWF now in Ruffle, the output is correct, so I guess this was fixed? Please leave a comment if anything is still broken and I can reopen the issue.

Not sure when this issue was fixed, but you're right. The original movie I pulled this issue out of is working now as well.
