### ISSUE TITLE
Crush the Castle: Black Screen issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9016]
### Describe the bug

https://www.newgrounds.com/portal/view/494237?emulate=flash
SWF fails to start since it goes right to a black screen as soon as ruffle finishes loading up with this error.

"Got RustError("Attempted to call \ "\ " with 1 arguments (more than 0 is prohibited)") when constructing AVM2 side of movie clip of type Preloader"
Issue also seems to effect the Player pack version of the game too.
https://www.newgrounds.com/portal/view/512354?emulate=flash

### Expected behavior

It shouldn't just immediately go straight to a black screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by Lord-McSweeney** [comment]
Still doesn't work, giving a black screen.

**Comment by n0samu** [comment]
Strangely, the game boots on desktop and with the Ruffle extension, but not on the NG webpage. There the game logs this error:
`ERROR core/src/display_object/movie_clip.rs:2132 Got "ReferenceError: Error #1065: Variable decodeURI is not defined." when constructing AVM2 side of movie clip of type Preloader`
Hopefully #10360 will get the game working on NG.

**Comment by waspennator** [comment]
> Strangely, the game boots on desktop and with the Ruffle extension, but not on the NG webpage. There the game logs this error: `ERROR core/src/display_object/movie_clip.rs:2132 Got "ReferenceError: Error #1065: Variable decodeURI is not defined." when constructing AVM2 side of movie clip of type Preloader` Hopefully #10360 will get the game working on NG.

Tested again on my end as of the latest nightly on NG and I do seem capable of getting to the title screen now, however as soon as I start the game, the game starts stuttering super heavily making it unplayable like Crush the Castle 2, however I don't see any of the performance warnings in the log, unsure if it's cause it's running so slowly that ruffle isn't logging em.

**Comment by n0samu** [comment]
I think it's fair to close this issue since the original problem is fully resolved.
