### ISSUE TITLE
Crush the Castle 2: Stuck at preloader error

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9017]
### Describe the bug

https://www.newgrounds.com/portal/view/547233?emulate=flash

Crush the Castle 2 seems to get a little bit farther then the 1st one, but it softlocks on the preloader throwing up this error message in the console.

"Got RustError("Cannot access property http ://adobe.com/AS3/2006/builtin::indexOf of null or undefined") when constructing AVM2 side of movie clip of type Main"

Crush the Castle 2 Player pack also seems to give similar results with a more than 1 call argument error like Crush the Castle 1 has, 2 errors trying to fetch a swf from the armor games site, and this fetch error.

"Error during movie loading: FetchError("Got JS error")"

https://www.newgrounds.com/portal/view/575726?emulate=flash

### Expected behavior

Clicking play on the preloader should start up the game.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by n0samu** [comment]
The FetchError in Crush the Castle 2 Player Pack seems to just be the game attempting to load the Armor Games API SWF and getting a CORS error. I think the XML issue you already reported is the important issue.

**Comment by waspennator** [comment]
Guess that makes sense, still surprised this one makes it to the preloader before breaking, but the first game just goes straight to a black screen.

**Comment by waspennator** [comment]
Crush the Castle 2 now seems to get past the preloader now, but it only works up until I pick a castle to crush, at which point the everything on the screen vanishes except for the color of the sky and this pops up in the logs.

Error dispatching event EventObject(EventObject { type: "ctc2Event_game", class: core::CTC2Event, ptr: 0x108179f8 }) to handler FunctionObject(FunctionObject { ptr: 0x10762038 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"flash.display\"))), name: Some(\"GraphicsBitmapFill\"), params: [], flags: (empty) }")

**Comment by waspennator** [comment]
According to another user on discord, with #10161, the error changes to 

 `Variable flash.display::GraphicsTrianglePath is not defined`

**Comment by waspennator** [comment]
Game is starting to render more and I can actually play the game now, but there's now a performance drop when starting a level and the level itself........ doesn't look right.

![Crush Castle 2 Ruffle](https://user-images.githubusercontent.com/78768499/226148734-fa4da540-ea04-4cb5-90ef-203aa87a3653.png)

**Comment by n0samu** [comment]
Seems to be caused by another unimplemented AVM2 Graphics API:
`WARN ruffle_core::stub: Encountered stub: AVM2 flash.display.Graphics.drawGraphicsData()`

**Comment by SuchAFuriousDeath** [comment]
I managed to progress this issue, PR hopefully coming soon, after I fiddle with it a bit more.
![image](https://github.com/ruffle-rs/ruffle/assets/48620541/b083e447-6c7b-47de-87bf-aae7acbd197e)
