### ISSUE TITLE
Segway of the Dead: Can't get moving

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9018]
### Describe the bug

https://www.newgrounds.com/portal/view/614276?emulate=flash

Game seems to work fine all the way up until you actually get in game, at which point the main character gets stuck in place talking no matter how many times you press right.

Also a minor issue, but for some reason the main characters eyes stay permanently shut and his mouth doesn't open up at all when he talks in the garage.

![Segway](https://user-images.githubusercontent.com/78768499/210490935-43fce074-56bb-400a-b228-9257cc825eae.png)

### Expected behavior

You should be able to move forward when pressing D or right and the main character should be moving his mouth when talking and looking with his eyes in the garage.

### Affected platform

Browser's Extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by MrCheeze** [comment]
This movie was broken by https://github.com/ruffle-rs/ruffle/commit/aa9e24fb9d7a1d0fe64ae7bf0232f1db8278c312 , which causes this movie to seek to a completely wrong frame at one point.

**Comment by waspennator** [comment]
I only just now realized that it's skipping the preloader and intro movies and going straight to the title.
