### ISSUE TITLE
[AS3] Cube Escape series unable to boot past the splash screen.

### ISSUE THREAD

**Issue by Spikestuff** [ruffle-rs/ruffle#9024]
### Describe the bug

![image](https://user-images.githubusercontent.com/12412764/210505172-3658d99d-78d7-45b1-bf89-fbe73987167c.png)

Listing all the titles that have this issue (note there are slight variants, but all result in being stuck at the Splash).
For the sake of convince. These all link to the Newground pages which has the command set and ready for it:
- [Seasons](https://www.newgrounds.com/portal/view/657567?emulate=flash)
- [The Lake](https://www.newgrounds.com/portal/view/657107?emulate=flash)
- [Arles](https://www.newgrounds.com/portal/view/659187?emulate=flash)
- [Harvey's Box](https://www.newgrounds.com/portal/view/660098?emulate=flash)
- [Case 23](https://www.newgrounds.com/portal/view/661829?emulate=flash)
- [The Mill](https://www.newgrounds.com/portal/view/663439?emulate=flash)
- [Birthday](https://www.newgrounds.com/portal/view/671000?emulate=flash)
- [Theatre](https://www.newgrounds.com/portal/view/673777?emulate=flash)
- [The Cave](https://www.newgrounds.com/portal/view/691196?emulate=flash)
- Paradox (this one is a [Steam Release](https://store.steampowered.com/app/909080/Cube_Escape_Paradox/), that results with Flashing Imagery as well)

Links to each title can be found on either their [website](https://www.rustylake.com/tag/rusty-lake-series/) or [Newgrounds](https://rustylake.newgrounds.com/games/)

### Expected behavior

On Flash Player it loads as intended, and you can continue forward.
![image](https://user-images.githubusercontent.com/12412764/210505115-15b7429c-1520-4e53-b1d8-d84f09fc54a0.png)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

**Comment by Lord-McSweeney** [comment]
There's also the error `ERROR core/src/display_object/movie_clip.rs:2076 Got RustError("Cannot coerce Object(ScriptObject(ScriptObject { name: com.google.analytics::GATracker, ptr: 0x10bc740 })) to an flash.events::IEventDispatcher") when constructing AVM2 side of movie clip of type Main` (at least on the first one).

**Comment by Spikestuff** [comment]
An update. All titles **except for Paradox** can now go ingame as of Nightly 2023-03-02 (version verified with).
Just be sure that you are running the Newgrounds version as the website version brings up a message to use the site (to download the assets, I assume).

This "issue" only occurs to Theatre and The Cave in my testing.
![image](https://user-images.githubusercontent.com/12412764/222369063-7460e0f6-12ca-4174-9a4a-e87cba3904ac.png)

**Comment by n0samu** [comment]
Closing as you stated that the games now work. (Not counting paradox since we have no way of accessing it)

**Comment by Spikestuff** [comment]
> Not counting paradox since we have no way of accessing it

I'm confused by this statement as when you download Paradox it's a standard Flash file and the exe that's played alongside is just a Flash Player.

**Comment by Spikestuff** [comment]
> I assumed that it was a paid game since it's on Steam.

Ah I see, that's on my lack of clarification as all I did was point out it was retrievable on Steam but failed to mention it's not a paid title.
And fair assessment to make when all the other titles on Steam can only be purchased excluding Samsara's Room.

And that's fine if it's out of the current scope for things to do.

Thanks.
