### ISSUE TITLE
1000 Years ago: Nightmare Moon AI bugs out

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9036]
### Describe the bug

https://www.deviantart.com/futzi01-reupload/art/1000-Years-Ago-700385586
Game seems to work alright save for one major issue. Nightmare moon will pick from a pool of attacks to use and one of them involves summoning lightning clouds to rain thunder upon you. On ruffle though, as soon as the lightning cloud barrage attack finishes, she'll spawn 2 lightning clouds and then proceed to do nothing, making the game way too easy. From repeated testing sometimes she'll either stop doing anything after the lightning cloud barrage or she'll do 1-3 more attacks and then stop doing anything.

Just set the game to easy and dodge attacks until she does the lightning cloud storm attack, though fair warning, it's entirely random what attack she'll use.

![Celestia](https://user-images.githubusercontent.com/78768499/210717032-294e26a3-ff10-4b09-944e-f2906241f0de.png)

### Expected behavior

https://www.youtube.com/watch?v=Gca7-bnbhFI (0:26)
Nightmare Moon shouldn't summon 2 random thunder clouds and break AI wise after doing a thunder storm wave attack.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by n0samu** [comment]
Can you upload the SWF file?

**Comment by waspennator** [comment]
https://www.deviantart.com/download/700385586/dbkzoz6-395796b3-4297-4822-b725-975a15dab0f5.swf?token=8fcd37856faa8cb9490a402bb48c80b7d64a9d1d&ts=1672902071

Here's a direct link I yanked from the page, luckily the "free download" button still seems to work

**Comment by n0samu** [comment]
I asked you to upload it. The download link contains a unique token that only works for you

**Comment by waspennator** [comment]
[dbkzoz6-395796b3-4297-4822-b725-975a15dab0f5.zip](https://github.com/ruffle-rs/ruffle/files/10350005/dbkzoz6-395796b3-4297-4822-b725-975a15dab0f5.zip)
Hopefully this should work better

**Comment by waspennator** [comment]
AI still seems to bug out performing this move as of the latest nightly.

**Comment by waspennator** [comment]
Retesting it again as of the latest nightly, got her to perform that specific attack and she doesn't seem to just spawn 2 mini clouds and get stuck any more. Dunno if it's RNG or not on whether it'll happen, but I got her to do it 3 times and not once did it happen as of the latest nightly, so I guess this is solved.
