### ISSUE TITLE
Canterlot Defender: Projectiles too accurate and Stuck Changelings bugs

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9037]
### Describe the bug

[db7cwao-b561dfa8-4cb6-48a1-83ca-85e9276ea1c7.zip](https://github.com/ruffle-rs/ruffle/files/10350209/db7cwao-b561dfa8-4cb6-48a1-83ca-85e9276ea1c7.zip)

The Leniency for landing a shot on an enemy is way too generous, you can literally shoot up into the air nowhere near the changeling horde and it'll still somehow hit one. Also when using your friends powers when a large swarm is on screen (Press 1-6), there's a chance that a few changelings will get stuck on the screen, unable to be killed.

An easy way to see the stuck changeling sprites, press up, up, down, down, left, right, left, right, b, a quickly, then press 6, it's consistent enough to happen on my end every time.

![Defender](https://user-images.githubusercontent.com/78768499/210725163-21f22901-e904-4669-b94b-6fbf1f496487.png)

### Expected behavior

Shooting upwards into the air shouldn't magically hit every single changeling coming in from the right, also using friend powers shouldn't cause changeling sprites to get stuck on the screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by waspennator** [comment]
Even with the latest nightly improvements, the accuracy doesn't seem to be any better. Might need more testing but i'm unsure if the changelings don't get stuck on the screen anymore.

**Comment by Computerdude77** [comment]
It seems like as of the 2023-06-16 nightly, the accuracy issue has been fixed. I also am not seeing the stuck changeling bug occur, so assuming this isn't just on my end, I think this issue can be closed now.

**Comment by waspennator** [comment]
Doing a quick test through again, seems like the accuracy is back to normal now. Shooting up into the blank air doesn't seem to count as hitting a changeling now, so I guess this is solved.
