### ISSUE TITLE
Update actionscript tracking issues

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#904]
There are a number of actionscript tracking issues that have very little checked, even though a number of the parts are in fact implemented.

**Comment by Dinnerbone** [comment]
I've just gone through them about 1 minute before this issue opened 😅 well timed!

I may have missed some of the more vague implemented properties, but it should be fairly up to date for implementations - possibly not for test coverage though, as that's tricky to tell at a glance.

**Comment by Justin-CB** [comment]
OK, I'll close this issue then.
