### ISSUE TITLE
Road of the Dead 2: Stuck on preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9051]
### Describe the bug

https://www.newgrounds.com/portal/view/624102?emulate=flash
Game seems to load up to the preloader now, however it looks kinda borked and you get stuck on it unless you use the right click play method to get the loading bar on top to stop endlessly looping.

![ROTD2](https://user-images.githubusercontent.com/78768499/211117194-b60cdbdd-86ee-47bb-a783-ec5526229fca.png)

However if you use the right click play method, you'll get stuck on the title screen afterwards.

![ROTD22](https://user-images.githubusercontent.com/78768499/211117223-7c94acb0-e974-4fb8-ae4b-20541c36c05b.png)

### Expected behavior

The preloading screen and the title screen should look like this.

![ROTD2 Flash](https://user-images.githubusercontent.com/78768499/211117395-9528d491-28f8-4ca6-80f9-f35950548e2c.png)

![ROTD22 Flash](https://user-images.githubusercontent.com/78768499/211117414-3e731295-fd30-4624-9b76-54765b57295e.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by waspennator** [comment]
Tested this out on recent ruffle builds, game actually loads up normally on desktop and on other sites re-hosting it now (https://kbhgames.com/game/road-of-the-dead-2). Game still gets stuck in a loading loop when running on newgrounds and using the ruffle web demo unless you use the right click and play method. I also noticed this in the command prompt testing it on desktop ruffle, though it does not seem to break the preloader.

ERROR ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: RustError("Cannot access property ::addEventListener of null or undefined")

Also, even on desktop or when using the right click and play trick, the game still isn't playable yet. As soon as you pick who you want to drive, the game gets stuck on the upgrade screen, and no matter how much you click, you are stuck on this screen. with these errors spammed in the logs instead.

AVM2 error: Object(ErrorObject(ErrorObject { ptr: 0x240c0ff8 }))

ReferenceError: Error # 1069: Property transformVector not found on flash.geom.Matrix3D and there is no default value.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2424c320 }) to handler FunctionObject(FunctionObject { ptr: 0xef9ba88 }) : AvmError(Object(ErrorObject(ErrorObject { ptr: 0x23c675a8 })))

![ROTD2 Ruffle](https://user-images.githubusercontent.com/78768499/213336681-94f7d428-d308-47ad-bd60-6f128699fc43.png)

**Comment by waspennator** [comment]
Preloader seems to be working now on Newgrounds, though the issue with the game getting stuck at the upgrade screen remains.

**Comment by waspennator** [comment]
[ruffle.rs-1678458158396.log](https://github.com/ruffle-rs/ruffle/files/10942870/ruffle.rs-1678458158396.log)
Situation seems to be the same, barring a black screen that pops up when you click play for a few seconds before the game actually starts, but now if you pick Diane, she doesn't say anything and the game softlocks there, whereas Cochetta still says something before transitioning to the upgrade screen.

**Comment by waspennator** [comment]
Looking at it again, I think it's getting stuck on the upgrade screen because "transformVector" needs to be implemented

**Comment by n0samu** [comment]
This will hopefully be fixed by #10541!

**Comment by waspennator** [comment]
Tested out on latest nightly and I can confirm that selecting Cochetta now allows you to get past the upgrade screen and actually get in game, though trying to select Dianne still softlocks the game.

Also looking at the preloader, it seems like the daily blurbs section on the right side of the screen still has some issues, on Flash it stays on day 1 one and you can click the button to check through the lore, but on ruffle it jumps straight to day 2 and i'm guessing that's why I can't click on it the read more button to progress it unlike Flash.

**Comment by waspennator** [comment]
The daily blurbs seem to be fixed now and you can read through them normally.

The issue where the game softlocks if you pick Dianne still remains though.

**Comment by waspennator** [comment]
Still occurring as of latest nightly.

**Comment by waspennator** [comment]
Closing since issue in initial post was resolved, moving Diane softlock issue to #17017
