### ISSUE TITLE
Regression in Snow Trouble

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9071]
### Describe the bug

In Snow Trouble (see #4122), there are now black lines extending from the enemy sprites. In the issue reported, there's a video. There are no black lines visible on the enemy sprites.

### Expected behavior

There are no black lines.

### Affected platform

Desktop app

### Operating system

Linux

**Comment by n0samu** [comment]
I've bisected this to 80dd295748672e64acd76e91abcdcd8b558d2760. So this is a problem with lyon.

**Comment by c4artisan** [comment]
happens in wonderputt (in the start screen with the damp gnat logo) and pocoyo playground (in the loading screen of the games section)
![image](https://user-images.githubusercontent.com/41709262/214979365-659b6f13-3d41-4b15-8f53-c4256baaff0d.png)
![image](https://user-images.githubusercontent.com/41709262/214979467-4356c368-49bc-41e7-ba33-2ad359586c2a.png)
