### ISSUE TITLE
ActionScript 3.0: Support EventDispatcher

### ISSUE THREAD

**Issue by fp07** [ruffle-rs/ruffle#908]
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/EventDispatcher.html

**Comment by kmeisthax** [comment]
Already on the roadmap, but won't be implemented for a little while. It will get pushed to https://github.com/kmeisthax/ruffle/tree/avm2-events when I start working on it.

**Comment by fp07** [comment]
Any update for the EventDispatcher? @kmeisthax

**Comment by adrian17** [comment]
With https://github.com/ruffle-rs/ruffle/pull/2041 , can this now be closed?
