### ISSUE TITLE
Wee Express: Stuck at Preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9083]
### Describe the bug

https://www.newgrounds.com/portal/view/532057?emulate=flash
When trying to click the play button on the preloader, the game instantly throws this message up in the console log and gets stuck on the preloader.

"Error dispatching event EventObject(EventObject { type: "click", class: flash.events::MouseEvent, ptr: 0xf3a2a8 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1eb3c54 }))) : RustError("Cannot access property ::removeAd of null or undefined")"

### Expected behavior

For the game to start when pressing play on the preloader.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by Lord-McSweeney** [comment]
The offending code seems to be this:
<code>

      private function playbtfun(param1:MouseEvent) : void
      {
         var event:MouseEvent = param1;
         MenuManager.currentMenu.playButton.removeEventListener(MouseEvent.CLICK,this.playbtfun);
         stage.frameRate = 24;
         try
         {
            this.ngad.removeAd(); <-- Here this.ngad is undefined
            MenuManager.currentMenu.ad.removeChild();
         }
         catch(error:Error)
         {
         }
         this.gotoAndStop(10);
      }

</code>

So `this.ngad.removeAd` will throw an error, which _should_ be caught by the `try...catch`, and then the `gotoAndStop` should run. Except in Ruffle, it throws a Rust error, halting the whole script, instead of throwing an AVM error.
