### ISSUE TITLE
Pilgrimage: Blue Screen Softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9087]
### Describe the bug

https://www.newgrounds.com/portal/view/498177?emulate=flash
Game seems to load up to the title screen fine, but as soon as I press play, it gets stuck on a blue screen with no audio and this message pops up in the logs.

"Error occured when running AVM2 frame script: RustError("ArgumentError: -1 is not a valid frame label.")"

### Expected behavior

Game should start when I press play,

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by Lord-McSweeney** [comment]
Additional errors:
`ERROR core/src/display_object/movie_clip.rs:2344 Error occured when running AVM2 frame script: RustError("Property does not exist: Multiname { ns: Multiple([Private(\"\"), Private(\"\"), Namespace(\"\"), Namespace(\"com.adobe.serialization.json\"), PackageInternal(\"com.adobe.serialization.json\"), Namespace(\"http://adobe.com/AS3/2006/builtin\"), Protected(\"com.adobe.serialization.json:JSONEncoder\"), StaticProtected(\"com.adobe.serialization.json:JSONEncoder\"), StaticProtected(\"Object\"), Namespace(\"flash.utils\")]), name: Some(\"describeType\"), params: [], flags: (empty) }")`

 (`flash.utils.describeType` unimplemented)


`ERROR core/src/display_object/movie_clip.rs:2344 Error occured when running AVM2 frame script: RustError("Property does not exist: Multiname { ns: Multiple([Private(\"\"), Private(\"\"), Namespace(\"\"), Namespace(\"game_fla\"), PackageInternal(\"game_fla\"), Namespace(\"http://adobe.com/AS3/2006/builtin\"), Namespace(\"adobe.utils\"), Namespace(\"flash.accessibility\"), Namespace(\"flash.desktop\"), Namespace(\"flash.display\"), Namespace(\"flash.errors\"), Namespace(\"flash.events\"), Namespace(\"flash.external\"), Namespace(\"flash.filters\"), Namespace(\"flash.geom\"), Namespace(\"flash.media\"), Namespace(\"flash.net\"), Namespace(\"flash.printing\"), Namespace(\"flash.profiler\"), Namespace(\"flash.sampler\"), Namespace(\"flash.system\"), Namespace(\"flash.text\"), Namespace(\"flash.text.engine\"), Namespace(\"flash.ui\"), Namespace(\"flash.utils\"), Namespace(\"flash.xml\"), Protected(\"game_fla:MainTimeline\"), StaticProtected(\"game_fla:MainTimeline\"), StaticProtected(\"flash.display:MovieClip\"), StaticProtected(\"flash.display:Sprite\"), StaticProtected(\"flash.display:DisplayObjectContainer\"), StaticProtected(\"flash.display:InteractiveObject\"), StaticProtected(\"flash.display:DisplayObject\"), StaticProtected(\"flash.events:EventDispatcher\"), StaticProtected(\"Object\")]), name: Some(\"Shader\"), params: [], flags: (empty) }")`

Unimplemented `(something).Shader`.

**Comment by Lord-McSweeney** [comment]
The game now runs fine on the desktop version, it just needs `BitmapData.draw`.

**Comment by Lord-McSweeney** [comment]
Closing as there's no problem with the game on Newgrounds.

**Comment by waspennator** [comment]
Tested again on my end and it does seem to boot in game now, though I wouldn't say there's no problems with this game. There doesn't seem to be any sound once you actually start the game and certain animations like the player character's movement and idle pose, coins and stepping on enemies don't seem to play out correctly, resulting in them never leaving the screen. Also the game seems to toss up a buncha read usage buffer performance errors in the logs, but I didn't really notice any major performance drops.

Also the game still is unplayable at a new point now, around here. Once you move past here, the screen gets stuck slowly zooming in and out depending on whether you move right or left. Checking on flash this is supposed to be the point where the game screen slowly degrades into pixel garbage.
