### ISSUE TITLE
ExternalInterface.call cannot call methods of non-object types.

### ISSUE THREAD

**Issue by MrCheeze** [ruffle-rs/ruffle#9105]
### Describe the bug

I have [a movie](https://mrcheeze.github.io/homestuck-ruffle-tester/#captchas,880,400) that contains the code:

```actionscript
pageURL = ExternalInterface.call("window.location.href.toString");
var tempvars:Array = pageURL.split("&");
```` 

In flash player, this finds the method by running the javascript `window.location.href.toString` which works. In Ruffle [this actually runs](https://github.com/ruffle-rs/ruffle/blob/1b71e288fd984ace46f69c1a2e27e2e2ed31333b/web/src/lib.rs#L1137) the javascript `Reflect.get(window.location.href,'toString')` which throws an error.

These are not equivalent, because js Reflect.get will fail if you pass *anything* other than an object as the first argument. In this case it fails because href is a string (even though it's a string that has the property in question).

### Expected behavior

[This flash](https://mrcheeze.github.io/homestuck-ruffle-tester/#captchas,880,400) should not print
`ERROR core/src/display_object/movie_clip.rs:2344 Error occured when running AVM2 frame script: RustError("Cannot access property http://adobe.com/AS3/2006/builtin::split of null or undefined")`
in the logs.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Mozilla Firefox

**Comment by MrCheeze** [comment]
At least via google, not finding any way to actually do something equivalent to JavaScript `foo.bar` in Rust... would it make any sense to delegate finding the method to typescript, maybe?

**Comment by n0samu** [comment]
> Would it make any sense to delegate finding the method to typescript, maybe?

I think that would be fine, though I guess we should make sure it doesn't prevent non-browser uses of ExternalInterface such as [ruffle-game](https://github.com/cyraid/ruffle-game).
