### ISSUE TITLE
Firefox addon page is dead

### ISSUE THREAD

**Issue by steponmepls** [ruffle-rs/ruffle#9115]
https://addons.mozilla.org/en-US/firefox/addon/ruffle_rs/

Trying to manually install nightly builds from this repo will fail on stable versions of Firefox since unsigned loading of addons is only allowed on ESR, Developer and Nightly versions of the browser.

![image](https://user-images.githubusercontent.com/63500907/211816537-1a1b6b45-73e3-4a4a-a3ed-3efe7bdcc397.png)

**Comment by n0samu** [comment]
Duplicate of #9054
