### ISSUE TITLE
Achillia: The Game: Stuck on Preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9124]
### Describe the bug

https://www.newgrounds.com/portal/view/674381?emulate=flash

Game seems to get stuck on the preloader after pressing play and nothing helpful in the console logs seem to show up about any potential issues.

On flash it transitions to the title screen a second or two after you click play on the preloader.

### Expected behavior

To transition to the title screen after clicking play.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by Lord-McSweeney** [comment]
Will be fixed by #8873.
