### ISSUE TITLE
Spud Saver: Stuck at Title Screen

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9129]
### Describe the bug

https://www.numuki.com/game/tda-spud-saver/
Tested a batch of Total Drama flash games and it seems a chunk of em load up to the title screen, but just get stuck there and pop up a singular error with only slight difference on what the type at the end of the error is called. Yanked this error from the log running this swf.

Got RustError("TypeError: undefined is not an Object") when constructing AVM2 side of movie clip of type SuperMattress

### Expected behavior

The title screen buttons should be working, and music should be playing.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by waspennator** [comment]
[www.numuki.com-1678856621293.log](https://github.com/ruffle-rs/ruffle/files/10976184/www.numuki.com-1678856621293.log)
Update on Spud Saver, game is still half broken (No Audio), like I can actually click the play button on the title screen to actually get ingame, however, Pythonicus just slowly glides to the top right of the screen, no animation, then the potato sack he's holding just vanishes.

I also checked the game again on Flash and I do notice a loading screen pops up for a second before transitioning to the game title screen proper, so I dunno if that has anything to do with the game being in a half broken state.

![Spud Saver Flash](https://user-images.githubusercontent.com/78768499/225212028-0585b5ff-1595-48dc-97e7-8a199f61c496.png)

**Comment by Lord-McSweeney** [comment]
This is being caused because `coerce_to_object` was used in handling values that could potentially be null or undefined.

**Comment by Lord-McSweeney** [comment]
No longer stuck at title screen, but there are some errors while trying to remove event handlers.

**Comment by waspennator** [comment]
Can confirm the game works now as of the latest nightly, played through the first level, should I keep this open till the other errors are fixed or is it safe to close

**Comment by waspennator** [comment]
> No longer stuck at title screen, but there are some errors while trying to remove event handlers.

[drop-of-shame.zip](https://github.com/ruffle-rs/ruffle/files/11780635/drop-of-shame.zip)
Found another Total Drama fan game that works, but seems to exhibit the issue when trying to remove event handlers, whenever I move my cursor over one of the buttons, it plays a sound effect, then this pops up in the logs, similar error that pops up in Spud Saver.

Error dispatching event EventObject(EventObject { type: "soundStop", class: com.zincroe.media::SimpleSoundChannelEvent, ptr: 0x2e2de5c }) to handler FunctionObject(FunctionObject { ptr: 0x2d9a054 }) : TypeError: Error # 1009: Cannot access a property or method of a null object reference. (accessing field: removeEventListener)

**Comment by waspennator** [comment]
Error no longer seems to pop up and the game seems to be pretty much playable now outside of this stub warning showing up, but aside from that popping up, the game works fine now, closing.
