### ISSUE TITLE
Pokemon Trainer Creator: Hue, Brightness, Saturation issues

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9131]
### Describe the bug

[game.zip](https://github.com/ruffle-rs/ruffle/files/10398764/game.zip)

When running this on ruffle, the sliders for Hue, brightness, and Saturation when selecting certain customization options doesn't seem to show up correctly, flickering wildly and being unselectable period.

![Poke custo 1](https://user-images.githubusercontent.com/78768499/211992794-ed7ff38b-b89d-4a99-b567-8fc26ca79540.png)

Two notable messages seem to pop up checking the log

AVM2 error: Object(ErrorObject(ErrorObject { ptr: 0x21b3d7c8 }))

ReferenceError: Error # 1069: Property invalidate not found on flash.display.Stage and there is no default value.

[www.numuki.com-1673504236076.log](https://github.com/ruffle-rs/ruffle/files/10398785/www.numuki.com-1673504236076.log)

### Expected behavior

The Hue, Brightness, and Saturation sliders should look normal like this.
![Poke Custo 2](https://user-images.githubusercontent.com/78768499/211992990-fdf515c9-0359-462e-adc7-2508afd937a2.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
This requires `Stage.invalidate`. It will be fixed when #8561 is merged (if it is ever finished).

**Comment by waspennator** [comment]
Situation seems to be better now, but still has some issues. The Sliders are now showing up and I can move them around now, but they still seem to flicker alot while spamming this error in the logs.

Got error when setting AVM2 child named "thumb": AvmError(Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0xbb3beb0 })))

**Comment by waspennator** [comment]
The flickering issue seems to be fixed now, but moving them around doesn't seem to change the appearance of the character at all.

**Comment by waspennator** [comment]
Seems to be working as of latest nightly now.
