### ISSUE TITLE
Pingu Snowball Shootout: snowball sound is repeatly playing and doesnt dissapear

### ISSUE THREAD

**Issue by TheGhostboi64** [ruffle-rs/ruffle#9135]
### Describe the bug

I think this is something wrong with the emulator, but there are no errors for me when I open inspect element.
HTML LINK
https://theghostboi64.github.io/pinguwebarchive/uk/snowball-intro.htm

SWF LINK
https://theghostboi64.github.io/pinguwebarchive/uk/m/snowball.swf

Whenever I try to throw a snowball at something, the snowball hit sprite repeats, along with the sound.

I am using unpkg's latest build of ruffle.

### Expected behavior

The snowball with dissapear and the sound will only play one time when hits a character.

### Affected platform

Self-hosted version

### Operating system

ChromeOS 

### Browser

Version 108.0.5359.111

**Comment by Lord-McSweeney** [comment]
This may be another case of #993.
