### ISSUE TITLE
addedToStage bug

### ISSUE THREAD

**Issue by barisyild** [ruffle-rs/ruffle#9138]
### Describe the bug

```as3
this.addEventListener("addedToStage",onAddedToStage);
```

The code is causing the following error:

Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x231dca8 }) to handler FunctionObject(FunctionObject { ptr: 0x2317a98 }) : AvmError(Object(ErrorObject(ErrorObject { ptr: 0x2329a00 })))

### Expected behavior

swf needs work correctly

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Google Chrome

**Comment by Lord-McSweeney** [comment]
The full error is `Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2e5f400 }) to handler FunctionObject(FunctionObject { ptr: 0x2e591d0 }) : RustError("Cannot access property ::addChild of null or undefined")`. Can you post a link to the SWF file (or zip it and upload it to github)?
