### ISSUE TITLE
Array removeAt unimplemented in AS3

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9139]
### Describe the bug

AS3 has a simple `removeAt` function (see https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Array.html#removeAt()) which is currently unimplemented.

### Expected behavior

`Array.prototype.removeAt` exists.

**Comment by ActionWavele** [comment]
have any example games that would help with implementing and testing of this function?

**Comment by Lord-McSweeney** [comment]
Someone had an issue on Discord, but the function itself is simple- writing tests should be not be complicated. (I barely know both Rust and ActionScript, so I'm not sure how I can help).

**Comment by Lord-McSweeney** [comment]
Fixed by #10087.
