### ISSUE TITLE
Pony Massages: Stuck on first screen (NSFW)

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9140]
### Describe the bug

[Emma Presents Spitfire Massage.zip](https://github.com/ruffle-rs/ruffle/files/10408430/Emma.Presents.Spitfire.Massage.zip)

(Mark as NSFW)
Not really into this kinda stuff, but I remembered it existing, so I figured i'd throw it at ruffle. Tested on desktop and web, the animation seems to start up, but gets stuck on the first screen, the head logo on the top right works fine clicking on it, but when I try and click the play arrow on the top left after starting the animation, it seems to get stuck and tosses up a "Mouseup error", 2 of the errors which seem to be tied to "play/stop of null or undefined", here's the ones I noticed from the log.

Error occured when running AVM2 frame script: RustError("Property does not exist: Multiname { ns: Single(Namespace(\"flash.system\")), name: Some(\"fscommand\"), params: [], flags: (empty) }")

Error occured when running AVM2 frame script: RustError("Cannot access property ::play of null or undefined")

Error dispatching event EventObject(EventObject { type: "mouseUp", class: flash.events::MouseEvent, ptr: 0xbe0e48 }) to handler FunctionObject(FunctionObject { ptr: 0xc52598 }) : RustError("Cannot access property ::stop of null or undefined")

### Expected behavior

The animation should play out as you click the play button on the top left.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
Unimplemented `flash.system.fscommand`?

**Comment by waspennator** [comment]
Combed through a bit of it with a flash decompiler, apparently some of the fscommands it uses checking through the "maintimeline" script are "showmenu" which is marked as false and "trapallkeys" which is marked as true.

I tried manually removing them via the remove trait option and that makes the animation play out, but now it loops through it repeatedly, think cause it deleted more than it should have.
