### ISSUE TITLE
Kamen Rider Wizard v3,1: Can't exit or full screen

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9141]
### Describe the bug

[_flash__kamen_rider_wizard_v3_1_by_crimes0n_d5zcwv3.zip](https://github.com/ruffle-rs/ruffle/files/10409035/_flash__kamen_rider_wizard_v3_1_by_crimes0n_d5zcwv3.zip)
Running this SWF through my flash player projector on desktop, the button on the top left is supposed to full screen the SWF (Infact the SWF starts in full screen when I launch it on the projector.), while the button on the top right exits the flash projector entirely. These 2 buttons on ruffle though seem to do absolutely nothing.

![Kamen](https://user-images.githubusercontent.com/78768499/212258635-c1013726-0c6d-47ff-9f0c-265f7718740f.png)

### Expected behavior

The top left button should enable ruffle full screen when pressed and the button on the right should close ruffle when pressed.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
These are unimplemented `fscommand` functions.

**Comment by waspennator** [comment]
Running it on the web demo site for testing, I can list out the fscommands it's sending out.

When starting up the SWF: Unhandled FSCommand: fullscreen, allowscale, show menu.

When clicking the full screen button on the top left: Unhandled FSCommand: fullscreen, allowscale, show menu.

When clicking the exit button on the top right of the SWF: Unhandled FSCommand: quit
