### ISSUE TITLE
[Megaman Zero Alpha] The flashportal.com logo sound repeats infinitely at regular intervals.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#9157]
### Describe the bug

[megaman-zero-alpha.zip](https://github.com/ruffle-rs/ruffle/files/10417036/megaman-zero-alpha.zip)

After clicking the Play button in Megaman Zero Alpha, the logo sound of Flash Portal that appears at first startup plays infinitely at regular intervals. Even when the title screen appears, the problem persists.

I've seen it reproduce on the latest Ruffle Nightly (2023-01-13). But there was a problem quite a while ago.

### Expected behavior

The logo screen sound effect should only play once.

### Affected platform

Self-hosted version

### Operating system

Windows 10 22H2

### Browser

Google Chrome 108

**Comment by n0samu** [comment]
This movie has an unusual structure that may be causing the problem (though I'm not sure). The Flash Portal animation is on frame 79, but it is not placed there directly. Instead, it is placed within a button, and that button is placed on the frame.

**Comment by Jmousy** [comment]
This issue is no longer reproduced in the latest Nightly (verified on 2024-12-01)!

I don't know at what point exactly it was fixed. Anyway I'm closing the issue. Thanks!
