### ISSUE TITLE
Ruffle Error on https://freeasteroids.org/

### ISSUE THREAD

**Issue by cool8526** [ruffle-rs/ruffle#9163]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:67050
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:66977)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:35276)
    at o (https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://turbo.freevideogamesonline.org/includes/js/flash-emulator/ruffle.js:1:2895
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freeasteroids.org/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-31
Channel: nightly
Built: 2020-12-31T00:48:27.350Z
Commit: ea3b6f59dfd7c528f2ae305c4dba2d351ada9302

**Comment by Lord-McSweeney** [comment]
This issue is invalid. The site uses a version of Ruffle that came out over 2 years ago, and the issue in question is a fetch error.

**Comment by cool8526** [comment]
und wie kann ich das beheben

**Comment by Lord-McSweeney** [comment]
Contact the site owner and ask them to update their Ruffle version. The issue does not occur for me on the latest version of Ruffle.

**Comment by cool8526** [comment]
welcher Browser nutzt du denn?

**Comment by Lord-McSweeney** [comment]
The same as yours, Chrome 108.

**Comment by n0samu** [comment]
I'm not seeing this issue when using the website's version of Ruffle either, though. So I don't see how it can be related to the website's version of Ruffle. Maybe it is caused by interference from another browser extension on the user's computer?
