### ISSUE TITLE
Error on https://www-sites-opensocial.googleusercontent.com/gadgets/ifr

### ISSUE THREAD

**Issue by Max-is-awsome** [ruffle-rs/ruffle#9164]
# Error Info
Error name: Error
Error message: panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9
Error stack:
```
@https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://sites.google.com/site/s019i5h/ruffle.js:1:6949
wasm-stub@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_once::{{closure}}::h098c4530511c1407]@[wasm code]
<?>.wasm-function[std::sync::once::Once::call_inner::hf7fd718057964857]@[wasm code]
<?>.wasm-function[core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c44fc25588b0f32]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h9d91fa0fae16500f]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h91d2023e5afe1929]@[wasm code]
<?>.wasm-function[std::thread::local::LocalKey<T>::with::h6d81463357c6f29a]@[wasm code]
<?>.wasm-function[ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::h188be77e8f9a3e94]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h40423248ac38b7fb]@[wasm code]
wasm-stub@[native code]
I@https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://sites.google.com/site/s019i5h/ruffle.js:1:3599
a@https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://sites.google.com/site/s019i5h/ruffle.js:1:2887
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://groups.google.com/group/alskfhaskfhalskfhasklfjhaklhfwakl--asd-asd-aw-dasdas-dva-45-45d/attach/5048ae9f38ff3/Gravity-Driver-1.swf?part=0.1&view=1
Param movie: https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://groups.google.com/group/alskfhaskfhalskfhasklfjhaklhfwakl--asd-asd-aw-dasdas-dva-45-45d/attach/5048ae9f38ff3/Gravity-Driver-1.swf?part=0.1&view=1
Attribute 0: undefined
Attribute 1: undefined

# Page Info
Page URL: https://www-sites-opensocial.googleusercontent.com/gadgets/ifr?url=https://groups.google.com/group/alskfhaskfhalskfhasklfjhaklhfwakl--asd-asd-aw-dasdas-dva-45-45d/attach/504a2ccc05c42/cser45--googlecom-gravity-google-driver-463xdadwe-googlecom.xml?part=0.1&view=1;%20frameborder=
SWF URL: https://www-sites-opensocial.googleusercontent.com/gadgets/proxy/refresh=3600&container=enterprise/https://groups.google.com/group/alskfhaskfhalskfhasklfjhaklhfwakl--asd-asd-aw-dasdas-dva-45-45d/attach/5048ae9f38ff3/Gravity-Driver-1.swf?part=0.1&view=1

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-04-21
Channel: nightly
Built: 2021-04-21T00:41:42.992Z
Commit: 46ddc31254ae1394b34b4f2e666bd2dc7eecd75b

**Comment by Lord-McSweeney** [comment]
I find that this URL works better: https://02816823445012794464.googlegroups.com/attach/5048ae9f38ff3/Gravity-Driver-1.swf?part=0.1&view=1&vt=ANaJVrFjm4sH3DfDew6TSTcjrHKkgfj5xHHXbvTkknmO8EOi7a5QeSRr62NiI9qZC0umsYNHGVxeG4GBoI8h5Zcs6cltdzljG-2sD6EP7Tf6OwpYtRw4XfA

Also, the Ruffle version is outdated, it should be updated.

**Comment by Max-is-awsome** [comment]
I’m just playing whatever version is on unblocked games premium

**Comment by Lord-McSweeney** [comment]
The site owners need to update their Ruffle version; it's almost two years old.
