### ISSUE TITLE
Bloons Super Monkey: stage 2, wave 3 is impossible

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9169]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/bloonssupermonkey.swf

In [Bloons Super Monkey](http://www.notdoppler.com/bloonssupermonkey.php), there are far fewer bloons in stage 2, wave 3 than there are supposed to be, which makes the wave impossible to beat.

https://user-images.githubusercontent.com/71368227/212535576-87987c9b-6733-43d9-96fa-3aac69735f9a.mp4

### Expected behavior

This video shows how the wave is supposed to play: https://youtu.be/5-nb-AHuLW8?t=522

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

I'm not sure whether this is related, but I'm seeing many instances of this error during the wave:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::globals::flash::display::movieclip: Attempted to add frame scripts to non-MovieClip this!`

**Comment by n0samu** [comment]
This problem has been fixed at some point.

**Comment by Lord-McSweeney** [comment]
Probably #11084.
