### ISSUE TITLE
Segway of the Dead: Wrong Framejump on newgrounds version

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9194]
### Describe the bug

https://www.newgrounds.com/portal/view/614276?emulate=flash
I've confirmed this game works now on the latest desktop ruffle, the ruffle web demo, and even other sites re-hosting this game, but on newgrounds it seems to just jump onto the title screen without any buttons. I can see this message pop up in the console log before it gets spammed with enterframe errors. I also notice if you right click and click rewind, it will take you back to the preloader, which seems to fix itself once you click play and go through the intros again.

Error occured when running AVM2 frame script: RustError("Cannot access property ::addEventListener of null or undefined")

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xd3bf18 }) to handler FunctionObject(FunctionObject { ptr: 0x171b338 }) : RustError("Cannot access property ::Head of null or undefined")

### Expected behavior

Game should be starting on the preloader on Newgrounds like on the desktop build of ruffle and other sites rehosting this game.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by Lord-McSweeney** [comment]
The relevant code for the error "Cannot access property ::Head of null or undefined":
```
public function UpdateGarage(param1:Number) : *
{
   var _loc3_:int = 0;
   this.DudeBro.Head.Blink.visible = this.m_bBlink; <-- Here this.DudeBro is null or undefined; this explains the blinking issue!
   this.m_fBlinkTimer -= param1;
   if(this.m_fBlinkTimer <= 0)
   {
      this.m_fBlinkTimer = this.m_bBlink ? 0.2 + Math.random() * 2 : 0.1;
      this.m_bBlink = !this.m_bBlink;
   }
   ...
```

**Comment by waspennator** [comment]
I think that batch of code is related to the main character's blinking animations in the garage, which I don't think is related to the bad jump, considering I tested it by rewinding and starting it normally and the character was blinking and speaking normally.

**Comment by waspennator** [comment]
Scratch that, re-tested it again on Newgrounds and the game seems to be properly staying at the preloader this time on Newgrounds as of nightly 2023-01-21
