### ISSUE TITLE
Tuper Tario Tros: Mario can't jump over 4 blocks long.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#9203]
### Describe the bug

https://user-images.githubusercontent.com/75534590/213211615-f4a03bbf-acb4-42b8-a501-92177f03fe23.mp4

### Expected behavior

https://user-images.githubusercontent.com/75534590/213211691-8f596981-9a3b-42aa-a7f4-270b86c8798f.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

https://www.newgrounds.com/portal/view/522276

**Comment by n0samu** [comment]
It's actually possible to make the jump, but for some reason it requires much more precise timing than in Flash Player:

https://user-images.githubusercontent.com/71368227/213244041-697090f3-d954-4a6e-97bd-cee944a8ff75.mp4
