### ISSUE TITLE
Johnny Upgrade: Doesn't play intros

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9209]
### Describe the bug

https://www.newgrounds.com/portal/view/594891?emulate=flash
Game seems to work fine when preloading, but as soon as the armor games logo finishes up, the game goes dead silent and nothing else happens except for these 2 messages in the console log popping up talking about how it failed to pull some kind of swf file called "AGI.swf"

[www.newgrounds.com-1674094069174.log](https://github.com/ruffle-rs/ruffle/files/10452822/www.newgrounds.com-1674094069174.log)

Running it on desktop produces the same result, but only dropping this error into the command prompt log.

ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x25f4f22e380 }) to handler FunctionObject(FunctionObject { ptr: 0x25f487c6020 }) : RustError("Cannot set undefined property ::_cpmstar_lastshown on Some(Main)")

### Expected behavior

Game should play the intros and go to the title screen and not get stuck after the armor games logo

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by Lord-McSweeney** [comment]
I think I've seen a similar CPMStar error on a different game. The AGI.swf error might have been temporary (I can't reproduce it anymore, and even in the crash log it says "ERR_FAILED 200"). As a side note, the AGI.swf file requires the `unescape` function to be implemented to work correctly.

**Comment by waspennator** [comment]
Retested again and its still the same result, but the only thing that pops up in the console log now is something about a failed get attempt from cpmstar that gets blocked by client as soon as the preloader part starts preloading, nothing else pops up in the logs past that now, even after the Armor Games logo intro.

**Comment by Lord-McSweeney** [comment]
I think the error might be related to CORS on the AGI.swf file I mentioned.

**Comment by waspennator** [comment]
Game finally seems to be working now, closing.

![Johnny Upgrade Ruffle](https://user-images.githubusercontent.com/78768499/226082170-f60dc12c-3045-435e-a43e-98a320e14ce2.png)
