### ISSUE TITLE
First variable can be undefined using LoadVars

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#921]
Using the following code:

```
var myVar = new LoadVars();
myVar.load("data.txt");
myVar.onLoad = function(success)
{
  if(success)
  {
    _root.off = myVar.var1 + myVar.var2;
  }
};
```

... and data.txt:

`var1=hello&var2= world`

... you get the following results:
- Flash: "hello world"
- Ruffle: "undefined world"

If you add a "&" as a first char in data.txt, then you get consistent and expected results between Flash and Ruffle: "hello world"

Sample:
[zload.zip](https://github.com/ruffle-rs/ruffle/files/4971160/zload.zip)

**Comment by Herschel** [comment]
This has a UTF-8 BOM at the start of the document that we don't handle. I think we'll have to do proper decoding of the text data here; looks like Flash handles UTF-16 (both LE and BE) as well.
