### ISSUE TITLE
Touch the Core 3: Black screen after preloader

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9211]
### Describe the bug

https://www.newgrounds.com/portal/view/625130?emulate=flash
Game seems to spam this in the console log as soon as the swf starts.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2e4af58 }) to handler FunctionObject(FunctionObject { ptr: 0x10d0888 }) : RustError("ArgumentError: Cannot remove object from display list it is not a child of.")

And then as soon as you try clicking play, it goes to a black screen and starts throwing up this error instead.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x344aa50 }) to handler FunctionObject(FunctionObject { ptr: 0x348dc38 }) : RustError("Cannot set undefined property ::fullScreenSourceRect on Some(flash.display::Stage)")

### Expected behavior

Game should load up to the title screen when pressing play.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by waspennator** [comment]
Tested it out on another site that was hosting it when I saw "FullScreenSourceRect" was stubbed, the title screen seems to pop up for a half second, but vanishes to black while spamming this.

https://slopegame.games/touch-the-core-3

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x10dcbd8 }) to handler FunctionObject(FunctionObject { ptr: 0x3a0f240 }) : RustError("Namespace constructor is a stub.")

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3b09c10 }) to handler FunctionObject(FunctionObject { ptr: 0x3b19de8 }) : RustError("ArgumentError: Child is not a child of this display object")

**Comment by waspennator** [comment]
Game now breaks on this now that Namespace Constructors aren't stubbed anymore.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x35a7360 }) to handler FunctionObject(FunctionObject { ptr: 0x358c9c8 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"avmplus\"))), name: Some(\"Domain\"), params: [], flags: MultinameFlags(0x0) }")

**Comment by Lord-McSweeney** [comment]
Spam of the error `RustError("ArgumentError: Child is not a child of this display object")`, and `RustError("Attempted to load a trait name of index zero")` before `Error: End of file was encountered.`.

**Comment by waspennator** [comment]
Have a feeling this is another one of those games made with stencyl cause I've seen those errors alot for those games on ruffle

**Comment by waspennator** [comment]
As of the latest nightly, ruffle no longer spams cannot remove object from display list errors on the preloader, but now dumps these after you press play.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xdf5658 }) to handler FunctionObject(FunctionObject { ptr: 0x809858 }) : Error: Error #2030: End of file was encountered.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3ed3c38 }) to handler FunctionObject(FunctionObject { ptr: 0x809858 }) : RustError("ArgumentError: Child is not a child of this display object")

**Comment by waspennator** [comment]
#12308 seems to cause the swf to crash with memory allocation of 51539607552 bytes failed

**Comment by Dinnerbone** [comment]
This won't crash on memory alloc now, it's disabled by the sparse array check.

We need sparse arrays to make this content work.

**Comment by Lord-McSweeney** [comment]
Fixed by #16051, though it's slow
