### ISSUE TITLE
Adventure Story: Chest Softlock

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9214]
### Describe the bug

https://www.newgrounds.com/portal/view/586861/format/flash?emulate=flash
Game seems to play alright until you get to this specific area with two chests with hp and mp upgrades inside next to each other. Opening either chest seems to freeze you in place and spams this error in the console log. It's very quick to get to the area with these 2 chests, If you rush through it, you'll go through 2 screen transitions before you get to the area with the chests in question.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x88d98c0 }) to handler FunctionObject(FunctionObject { ptr: 0xcd41a8 }) : RustError("Cannot access property ::ID of null or undefined")

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3c3b428 }) to handler FunctionObject(FunctionObject { ptr: 0x129f990 }) : RustError("Cannot access property ::ID of null or undefined")

![Adventure Story Chests](https://user-images.githubusercontent.com/78768499/213354582-4e6f1c61-b679-4ced-9854-e4d860414500.png)

### Expected behavior

These two chests should upgrade your HP and MP totals and not freeze you in place.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by ActionWavele** [comment]
previously reported on discord.

**Comment by waspennator** [comment]
Game seems to have gotten worse now, as not only do both chests still softlock the game, but it seems like opening any of the chests now softlocks it with this error.

Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x56c7924 }) to handler FunctionObject(FunctionObject { ptr: 0x15ddf8c }) : TypeError: Error # 1009: Cannot access a property or method of a null object reference. (accessing field: data)

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x7bcd6fc }) to handler FunctionObject(FunctionObject { ptr: 0x15a066c }) : ReferenceError: Error # 1069: Property ID not found on int and there is no default value.

**Comment by Lord-McSweeney** [comment]
This is the function which has the `int.ID` issue:
```
internal static function checkChests() : *
      {
         if(player.onGround && !player.dead)
         {
            for each(c in level.chestsMC)
            {
               if(c.hitTestPoint(player.x,player.y - player.n,true))
               {
                  ch = level.chests[c.name.slice(5)];
                  if(!c.opened && Keys.keyIsDown[Keys.interactKey] && !player.attacking && !player.magic)
                  {
                     c.gotoAndPlay(2);
                     c.opened = true;
                     ...
                     break;
                  }
                  if(Boolean(c.opened) || LevelState.getChest(c.name.slice(5)) == 3 && (ch[0] == "hp" || ch[0] == "mp"))
                  {
                     hud.bubble2.fadeIn = true;
                     hud.bubble2.gotoAndStop(ch[0]);
                     if(hud.bubble2.e)
                     {
                        hud.bubble2.e.gotoAndStop(ch[1].ID + 1);
                     }
                     ...
                     break;
                  }
               }
            }
         }
      }
```
Ruffle enters the `hud.bubble2.e` branch, which attempts to lookup `ch[1].ID`. However, `ch[1]` is an int. In FP, that `hud.bubble2.e` branch is never entered, which makes me suspect this is a framescript issue concerning the previous `hud.bubble2.gotoAndStop(ch[0]);`.

**Comment by ActionWavele** [comment]
still broken

**Comment by Kz-92** [comment]
https://github.com/ruffle-rs/ruffle/assets/103858019/ea3696db-1f8b-4f34-b551-13b4496b3e7c

this seems to be fixed on latest

**Comment by waspennator** [comment]
Tested on my end, can confirm the chest softlocks seem to be gone now, closing.
