### ISSUE TITLE
web: drag&drop of right wood piece not working

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#922]
In Flash you can drag both (the coal and the wood) to the scale to weigh them as well as to the oven to fire them.
In Ruffle you can drag the coal for both experiments, but the wood can only be dragged to the scale, not to the oven.

See http://www.webgeo.de/ev_004/#3
(on http://www.webgeo.de you can switch between using ruffle or using flash)

Strange: It works fine when using demo at:
 http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html

Version: ruffle_web_2020-07-24

![ruffle_ev_004_3](https://user-images.githubusercontent.com/1667683/88379366-1beb7300-cda3-11ea-927d-d8de13358ee0.png)
![flash_ev_004_3](https://user-images.githubusercontent.com/1667683/88379373-1e4dcd00-cda3-11ea-80dd-b7d47587af01.png)

[ev_004_03.zip](https://github.com/ruffle-rs/ruffle/files/4971258/ev_004_03.zip)

**Comment by Dinnerbone** [comment]
There's a `<div>` hovering over that side of the page, and it's intercepting clicks.

![image](https://user-images.githubusercontent.com/317625/88383854-9cae6d00-cdab-11ea-8b8b-238ca4d1b45e.png)
![image](https://user-images.githubusercontent.com/317625/88383870-a506a800-cdab-11ea-8310-0400eddd501b.png)

**Comment by KMicha** [comment]
Upps - sorry. My fault. 
Now fixed.

**Comment by Poopooracoocoo** [comment]
@KMicha hey that div is still there for me. :)
