### ISSUE TITLE
Thrack it Trixie: Black Screen

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9268]
### Describe the bug

[thrack_it_trixie_by_sparklepeep_d5naas9.zip](https://github.com/ruffle-rs/ruffle/files/10476135/thrack_it_trixie_by_sparklepeep_d5naas9.zip)

Game gets stuck on a black screen as of the latest nightly spamming this message in the logs.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x332e628 }) to handler FunctionObject(FunctionObject { ptr: 0x33740a8 }) : RustError("Namespace constructor is a stub.")

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x3d5dab8 }) to handler FunctionObject(FunctionObject { ptr: 0x33740a8 }) : RustError("ArgumentError: Child is not a child of this display object")

### Expected behavior

Game should boot to the title screen and not get stuck on a black screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by waspennator** [comment]
With #10116, the game now breaks on a new error.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2c74bd0 }) to handler FunctionObject(FunctionObject { ptr: 0x2c55de8 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"avmplus\"))), name: Some(\"Domain\"), params: [], flags: MultinameFlags(0x0) }")

**Comment by waspennator** [comment]
Tested again, posting log with new batch of errors since this one isn't showing up anymore.

**Comment by waspennator** [comment]
Still seems to be borked with these 2 errors.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x236c884 }) to handler FunctionObject(FunctionObject { ptr: 0x248dfd4 }) : Error: Error # 2030: End of file was encountered.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x62e5fc }) to handler FunctionObject(FunctionObject { ptr: 0x248dfd4 }) : RustError("ArgumentError: Child is not a child of this display object")

**Comment by waspennator** [comment]
#12308 seems to make this swf panic on capacity overflow now.

```# Error Info
Error name: Error
Error message: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5

```
AVM2 stack:
```
    at stencyl.api.io::BehaviorReader$/readBehavior()
    at stencyl.api.data::Assets/loadBehaviors()
    at stencyl.api.data::Assets/loadAll()
    at scripts::MyAssets/initAssets()
    at scripts::MyAssets/init()
    at stencyl.api.data::Assets$/get()
    at stencyl.api.engine::GameState/begin()
    at stencyl.api.engine::GameState/create()
    at org.flixel::FlxGame/switchState()
    at org.flixel::FlxGame/create()
```

**Comment by Aaron1011** [comment]
This requires us to implement some form of sparse array support, since this SWF sets a very large index in an array.

**Comment by waspennator** [comment]
Seems to load up past the black screen now that Sparse Array support has been implemented
