### ISSUE TITLE
[Regression] Drag and drop not working

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#9274]
### Describe the bug

Issue with https://dnalc.cshl.edu/view/16999-Genetic-Traits.html

Ruffle behavior:

[Screencast from 01-23-2023 09:44:41 AM.webm](https://user-images.githubusercontent.com/29206584/214069134-0bd983db-83bc-4758-ace0-530460970ed5.webm)

### Expected behavior

Flash behavior:

[Screencast from 01-23-2023 09:44:04 AM.webm](https://user-images.githubusercontent.com/29206584/214069201-7f096ff9-6b2b-4fd3-a2a9-ac5d362711cf.webm)

### Affected platform

Self-hosted version

### Operating system

Linux Fedora 36

### Browser

Mozilla Firefox 107

**Comment by n0samu** [comment]
Code for this is duplicated per drag and drop target, but here is an example of the relevant code, with a trace statement added:
```as
carrier_MC.carrier_bttn.onRelease = function()
{
    stopDrag();
    trace(eval(carrier_MC._droptarget));
    if(eval(carrier_MC._droptarget) == drophere_1)
    {
        drophere_1.gotoAndStop("carrier");
        drop1 = "carrier";
    }
```
In Flash Player, when I drag the carrier icon onto the nearer "Drop here" box, it traces:
`_level0.drophere_1`
But in Ruffle, it traces:
`_level0.drophere_1.instance9`
Considering that Ruffle does not have DisplayObject string paths correctly implemented (see #5492), it's no surprise that this doesn't work.

**Comment by danielhjacobs** [comment]
Wait, no: This is a regression: https://ruffle-regressions.github.io/?version=0.1.0-nightly.2022.12.18 works, https://ruffle-regressions.github.io/?version=0.1.0-nightly.2022.12.19 doesn't, with https://content.dnalc.org/content/c16/16999/genetic_traits.swf.

**Comment by Lord-McSweeney** [comment]
https://github.com/ruffle-rs/ruffle/commits/master?before=f213ec40fc92ddb5e41573594b2737262d17a04c+280&branch=master&qualified_name=refs%2Fheads%2Fmaster
The only commits I see relevant are the `hitTest` fixes.

**Comment by danielhjacobs** [comment]
I thought the same, but in https://github.com/ruffle-rs/ruffle/compare/nightly-2022-12-18...nightly-2022-12-19, the only AVM1 changes are https://github.com/ruffle-rs/ruffle/pull/8613

**Comment by danielhjacobs** [comment]
Actually, you're right, the actual issue is that https://github.com/ruffle-rs/ruffle/pull/8744, which was supposed to just be AVM2 changes, made incorrect AVM1 changes.
