### ISSUE TITLE
Territory War Online (2) explosion and outline issues

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#9296]
### Describe the bug

Yes, this is an online game, but this affects the offline mode as well.
Previously this game was unable to create the ground for the players due to something with bitmap, that is now added, so well done!
however, a new issue has popped up, namely that explosions now leave behind an outline, where they shouldn't.
additionally, when the destructible ground is blown up, it leaves a black area, instead of showing the background layer.
this black area does fix itself on the next turn, though.

![Territory WAR 2](https://user-images.githubusercontent.com/103858019/214408742-ab99be7a-245d-4ff0-ba5e-ae73379cc7af.png)

the explosion outlines are faint, so look toward the right side and the bottom of the screen as well

Also, player outlines are missing (I assume filters are needed)
here is what *both* explosion craters and player outlines should look like
(no explosion outline here)

![Territory WAR 2-2](https://user-images.githubusercontent.com/103858019/214410347-57c3ba27-b0ae-4ccd-8c58-361be4cb5b97.png)

### Expected behavior

It should look like it does in the second image
[two.zip](https://github.com/ruffle-rs/ruffle/files/10493939/two.zip)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

this is what web shows in the LOG
```

WARN core/src/avm1/activation.rs:993 Cannot enumerate Undefined 2 
WARN core/src/avm1/object/stage_object.rs:714 Unimplemented property _focusrect 
WARN core/src/avm1/activation.rs:993 Cannot enumerate Undefined 44 
WARN core/src/avm1/object/stage_object.rs:714 Unimplemented property _focusrect 2 
WARN core/src/avm1/activation.rs:915 Cannot delete property  from Undefined 
WARN core/src/avm1/object/stage_object.rs:714 Unimplemented property _focusrect 
WARN core/src/avm1/activation.rs:993 Cannot enumerate Undefined 
WARN core/src/avm1/globals/bitmap_data.rs:525 BitmapData.draw with clip rect - not implemented 
WARN core/src/avm1/activation.rs:993 Cannot enumerate Undefined
```

**Comment by Lord-McSweeney** [comment]
From a first glance, it looks like the explosion outlines may be caused by `clipRect` on `BitmapData.draw` being unimplemented in avm1, but I might be wrong there, as the message in the logs is only shown once.

**Comment by Kz-92** [comment]
I can't replicate the explosion issue anymore, this can be closed  once the outlines are fixed 👍

**Comment by Kz-92** [comment]
https://github.com/ruffle-rs/ruffle/assets/103858019/6d7a662d-1336-48b4-b745-06d7f498bfb1

thanks to latest, this issue can be closed!
