### ISSUE TITLE
Ruffle does not support multiline text input boxes

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9303]
### Describe the bug

In Ruffle, when typing into a multiline editable text box, pressing Enter does not create a newline. To reproduce this problem, simply create a text field in Flash, set it to "Input Text" and "Multiline", export the SWF, and open the SWF in Ruffle.
Here is an example SWF provided by a user on Discord: [TextFieldTest.zip](https://github.com/ruffle-rs/ruffle/files/10496259/TextFieldTest.zip)

### Expected behavior

Pressing enter should start a new line.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

The problem occurs with the desktop and web versions of Ruffle and across operating systems and browsers.

**Comment by Lord-McSweeney** [comment]
This should have been fixed by #15096
