### ISSUE TITLE
Dinogeddon: Colors are incorrect on last frame 

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9304]
### Describe the bug

Link to SWF: https://www.dolldivine.com/games/dinogeddon-premNoGallery.swf

In [Dinogeddon](https://www.dolldivine.com/dinogeddon-character-maker), Ruffle renders the colors incorrectly on the last frame of the menu. The colors are correct on all of the other frames. 

Steps to reproduce:
1. Run the SWF file in Ruffle
2. Click the right arrow button to start the game. 
3. Click the right arrow button repeatedly until you get to the last frame of the menu.

In Ruffle, it looks like this:
![image](https://user-images.githubusercontent.com/71368227/214485131-fe5f0dc3-9280-4116-a79f-790e7ff4173a.png)

### Expected behavior

The frame is supposed to look like this. The background colors are supposed to be the same as the previous frames. (Ignore the different-looking girl - her appearance is randomized)
![image](https://user-images.githubusercontent.com/71368227/214485290-3840d96c-90e3-4f51-afed-42f7be366df0.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This seems to be a problem with Ruffle's implementation of the Overlay blend mode. The menu sprite is sprite 1908, and its last frame is frame 12. On that frame, there are 3 PlaceObject3 tags with the Overlay blend mode:
![image](https://user-images.githubusercontent.com/71368227/214485875-4bba337e-4fc3-4446-8297-1eb3108c044a.png)
Changing their blend mode to Normal makes the problem go away. I think their blend mode is being applied to the entire screen instead of just the sprite they are placing.

Also, this seems like a similar issue to #4464. That game also uses PlaceObject3 tags with a blend mode (Erase).

**Comment by Lord-McSweeney** [comment]
Seems to be fixed by #10251.

**Comment by n0samu** [comment]
Uh, no it's not

**Comment by n0samu** [comment]
This is a regression; I've bisected it to commit 8db8e4669adb6bc5498b19af66db78a10ce0cc50 of #9096.

**Comment by n0samu** [comment]
Fixed by #11674
