### ISSUE TITLE
Fairly Oddparents: Battle of the Futurebots

### ISSUE THREAD

**Issue by PokemonHacker1337** [ruffle-rs/ruffle#9312]
There aren't really any issues for the most part. Mostly a bit of a graphical bug with one of the robot heads and cutscenes, but it's still certainly possible to get from start to finish.

Also I'm new to this, but I didn't see anyone post about this game. Apologies if I'm doing this wrong, and I hope you all have a nice day :-)

**Comment by Lord-McSweeney** [comment]
Please post a link to the site or upload the SWF file.

**Comment by Lord-McSweeney** [comment]
In addition, the copy I found on https://www.games-kids.com/game/734/battle-of-future-bots.html has a similar bug to #9071 on the title screen.

**Comment by PokemonHacker1337** [comment]
Yeah, you beat me to posting the link, thanks for the catch. I'll keep that in mind for the next time I make a post here.
