### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by WinIsEpic** [ruffle-rs/ruffle#9332]
### Describe the bug

I tried The Worlds Hardest Game 2 and this is what shows up:

![ruffle](https://user-images.githubusercontent.com/118131074/215279031-1abc8098-9a0e-4ebc-aea9-2c05d6287fb6.PNG)

### Expected behavior

This is what is expected to happen (Adobe Flash)

![Flash](https://user-images.githubusercontent.com/118131074/215279081-90b1af30-5cd0-4f74-a0c3-dcd94a8d65ea.PNG)

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Opera GX version 94.0.4606.79

**Comment by torokati44** [comment]
I wonder if this is also because of the recent lyon update...

**Comment by Lord-McSweeney** [comment]
Another lyon bug?
