### ISSUE TITLE
Can Your Pet: Soccer Ball Softlock and Bicycle Bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9396]
### Describe the bug

[canyourpet.zip](https://github.com/ruffle-rs/ruffle/files/10574164/canyourpet.zip)
Game is almost playable from start to finish save for a few issues (The icons on the bottom don't glow, but they aren't game breaking), the soccer ball minigame cannot be initiated, once you get to the part where you have to click on the soccer ball icon, it will appear on your pet, but no ammount of clicking will initiate the minigame and toss this in the console log.

"Unhandled AVM2 error in timer callback: RustError("VerifyError: Trait onRender in class Particle has same name as trait onRender in class DisplayElement, but does not override it")"

I was able to get to the bicycle option by not using the soccer ball method (Easiest way is to click on the first icon and then dismiss the dress up hud that pops up on the side until the bicycle option unlocks), but that causes the game to just cycle through some of the screens in the game, like the title and a pop up advertising the mobile port. Also the game doesn't seem to swap over to the alternate title after you beat the game once.

### Expected behavior

You should be able to click on the soccer ball to play catch with your pet, you should be able to click the bicycle button without it cycling through a bunch of random screens, and it should swap to the alternate title screen once you beat the game at least once.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 109

**Comment by adrian17** [comment]
The soccer ball part and `Trait onRender in class Particle` error should be fixed now.
The screen cycling on clicking the bicycle is not :/

**Comment by waspennator** [comment]
Can confirm the soccer ball no longer softlocks the game and you can now play properly with your pet, the only issue that remains is the screen cycling issue.

Looking at the cycling bug, it seems to go to the title screen, the alternate title screen (When you finish the game once), a pop up advertising the mobile version of the game, then finally lands on the ending scene without skipping through it. Once you get to the end and click on the button to go back to the main menu, it doesn't seem to swap to the alternate title screen though.

Testing out on flash as well, the pop up advertising the mobile version seems to only show up once you finish the game once with the alternate title screen.

**Comment by waspennator** [comment]
Good news and bad news

Good news: The bicycle bug doesn't seem to be happening anymore and the game seems to be working properly now, it transitions to the ending cutscene without issue, see the alternate title screen, and delete my save data to reset to how it should be normally.

Bad news: If I click the first button to open up the menu for customizing my pets appearance, I can't click on the orange arrow on the right to dismiss it unless I click the customize pet appearance button again.

![Can your Pet Ruffle](https://user-images.githubusercontent.com/78768499/224460068-7ce90095-44f2-4f5e-bf46-ce23fe02b5e5.png)

Extra bad news: The credits now seem to absolutely tank the performance of the game on web and desktop, persists even after clicking back to the main menu and I have to reset the SWF to get performance fixed again.

**Comment by waspennator** [comment]
Thanks to Nosamu, I can confirm that all of the issues listed save for the glow filters should be fixed by #9928, however there seems to be one more minor regression left that doesn't seem to have appeared much earlier build wise.

With ruffle build 2023-02-24, the soccer ball is served at a normal speed and I can continually serve it back and forth between my pet, but on build 2023-02-25, the ball not only seems to be faster, but vanishes instantly even if I manage to serve it back.

**Comment by waspennator** [comment]
All of the issues listed aside from the visual glow filters and the soccer ball minigame being iffy are now fixed as of the latest nightly build, closing and pushing future discussion to #10013
