### ISSUE TITLE
Magic Pen: Drawing certain polygons creates incorrect output

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9408]
### Describe the bug

Tested on Ruffle Nightly 2023-02-04
Magic Pen SWF used: [433935_mpnew202c.zip](https://github.com/ruffle-rs/ruffle/files/10608807/433935_mpnew202c.zip)

This is what happens when I try to draw a circle in the first level.

https://user-images.githubusercontent.com/36887711/216772209-fd59ed34-9f80-46a2-b5c8-586876804311.mp4

Note: I was only able to complete this level once without deleting the Ruffle save file since the Level Select doesn't work when the game is launched again.

### Expected behavior

This is what should happen normally. This game was run using Flashpoint.

https://user-images.githubusercontent.com/36887711/216772593-f05c25bc-b465-4816-8af3-e1939c88bb56.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by mero09-99** [comment]
you know, you're meant to click and hold there, not trace
though I'm not saying it isn't bugged

**Comment by n0samu** [comment]
Seems like this was fixed by #12003 🎉
