### ISSUE TITLE
CLOP: Sitelock on main Foddy website.

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#9440]
### Describe the bug

![image](https://user-images.githubusercontent.com/75534590/217011152-b526445d-e519-481b-9dfb-70a33d579f8a.png)
![image](https://user-images.githubusercontent.com/75534590/217011428-549de410-af0d-47ed-89b0-3ec4b57dfb36.png)

### Expected behavior

It will loading fine main foddy website.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 109.0.5414.120

### Additional information

https://www.foddy.net/CLOP.html

**Comment by Lord-McSweeney** [comment]
This SWF expects `root.loaderInfo.url` to be `http://www.foddy.net/CLOP.swf`, but Ruffle reports it as `https://www.foddy.net/CLOP.swf`.

**Comment by Lord-McSweeney** [comment]
This issue is unrelated to Ruffle and cannot be fixed.
