### ISSUE TITLE
web: Ruffle's Play button appears too soon (regression?)

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#946]
Using the nightly build of the day (2020-07-28), if you click the Play button as soon as it appears, you get the following error:

> panicked at 'root level', core/src/player.rs:598:26

... which in turn causes other errors, preventing the game from running.

This can be reproduced with any game (make sure to disable the cache while testing).

This build also adds some black borders around the white background.

https://www.newgrounds.com/portal/view/225944/
https://www.y8.com/games/streets_of_fire

**Comment by Dinnerbone** [comment]
Ran a bisect.

| Status | SHA | Message |
| ------ | ----- | --------- |
| :x: | aed47d458d7b8b9c510b92fd39f9d56e049cb61c | Level loads in GetURL2 should also propagate origin information.|
| :heavy_minus_sign: | a34e81a70415bc8a83bf5dd3081918e0de30a483 | `_url` on desktop should always return a file URL for file-loaded movies.|
| :heavy_minus_sign: | f0e2c77c1f02255d27ea4c1fa7af86ea2aa47875 | URLs from paths is a desktop-only feature.|
| :heavy_minus_sign: | 9b9d4076fe770d58185d2067ce695dc736650f4f | Expose movie URL to ActionScript.|
| :heavy_minus_sign: | a8877ab63c0735f45a44752802a1fc430f047953 | Yield the correct error when the root movie load fails.|
| :heavy_minus_sign: | d1724416635a7cf2a51cb960e0461fca68c420ae | Also make absolute URLs for all movie loads passed through the load manager.|
| :heavy_minus_sign: | 5d15f5bfe3bcc5615ffd062c360f2caf5de10343 | When loading a movie from the filesystem outside of the core, ensure that the URL is properly |
| :heavy_minus_sign: | c926da8888cfbb33fa8ae289a3ff53cd7127677f | Refactor URL relativization into two utility methods that backends can provide base URLs and |
| :heavy_minus_sign: | 7433bfe28f34253ab6802da4ff0ed7ed576a4144 | Add a `NavigatorBackend` method to resolve relative URLs.|
| :heavy_minus_sign: | 4813942fe7ce07037bd6346eacf45ae29ebd41d9 | The player should always change the audio backend's framerate itself.|
| :heavy_minus_sign: | f56d16a68d7518359c896ee59da54a9f6d13b313 | Separate player creation from root movie setup, and allow users of Ruffle to load in movies |
| :heavy_check_mark: | 6998dafdb9c8c443b544f835f101af0c530cecc6 | Store an origin URL on every movie that is loaded.|

The :heavy_minus_sign: do not compile so I can't test it, so it was added after 6998dafdb9c8c443b544f835f101af0c530cecc6  and before or in aed47d458d7b8b9c510b92fd39f9d56e049cb61c.

This is all in PR #912 - @kmeisthax do you have any idea what could be going wrong here?

**Comment by Dinnerbone** [comment]
This should be fixed by https://github.com/ruffle-rs/ruffle/pull/965.

**Comment by Toad06** [comment]
The same issues can still be observed using the build of the day (2020-08-03), though the first message logged into the console is now different:

> panicked at 'called `Option::unwrap()` on a `None` value', core/src/display_object/movie_clip.rs:1507:37

**Comment by Toad06** [comment]
Still happening in nightly 2020-08-14.
