### ISSUE TITLE
Prior: Pressing "Wake Up" will return you to the game intro

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9463]
### Describe the bug

Tested on Ruffle Nightly 2023-02-08
Prior SWF used: [prior.zip](https://github.com/ruffle-rs/ruffle/files/10681419/prior.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/217424438-c36b79f4-a95c-41f4-866a-52025d18205b.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint. Pressing "Wake Up" will just start the game as normal.

https://user-images.githubusercontent.com/36887711/217424822-05cf0b77-ea15-4917-acb1-b0c4d952854b.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 109

**Comment by n0samu** [comment]
Seems like this was fixed by #9609.
