### ISSUE TITLE
All's Well That Ends Well: Incoming projectiles lack collision

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9468]
### Describe the bug

Tested on Ruffle Nightly 2023-02-08
All's Well That Ends Well SWF used: [allswellthatendswell.zip](https://github.com/ruffle-rs/ruffle/files/10684690/allswellthatendswell.zip)

This is what the game looks like in the Ruffle Demo. The floor below has collision detection, while the projectiles do not.

https://user-images.githubusercontent.com/36887711/217511181-6705ae2e-4212-43fa-9ab2-8e54224913fe.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/217511267-5a7bea02-73ff-44c4-a2bd-6fb4445ca42c.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 109

**Comment by n0samu** [comment]
Seems like this was fixed by #9659
