### ISSUE TITLE
cat ninja not launching

### ISSUE THREAD

**Issue by urmotha** [ruffle-rs/ruffle#9474]
i am aware that actionscript 3 content is not currently supported but I would like for it to be fixed. the problem is that it does not get past the loading screen. i am asking for a fix because it is a very simple game. thank you for your time.

**Comment by Lord-McSweeney** [comment]
Can you add a link to the site or upload the SWF file?

**Comment by urmotha** [comment]
@Lord-McSweeney  the system doesn't allow me to drag and drop the file so I just have a link. [https://a1acd659-a-62cb3a1a-s-sites.googlegroups.com/site/projectyeet1/cat-ninja/CatNinja.swf?attachauth=ANoY7crVMVR5r-NPeUX45OHfDLFZtTKjllkA1aoEPPjT2rLiBcG6e8A4IXf_oeitit2ekuyp1PCGmTT5e6asmNdgwAKumyskndtkFGOjUuJ7YxEWqfnw-EqEzVJVOMsvx3MCfRrpdj0x0c-y8hMr14K_BOpzsIQYlg-CG27DJAJGsAj5QtRBhKhpo9aWEatbMXj_Y_qFoE3-1hTvjho57EggOdY-Il2yhXBbZ18BjRW7uvvmSTvQwOo%3D&attredirects=0]

**Comment by urmotha** [comment]
[CatNinja.zip](https://github.com/ruffle-rs/ruffle/files/10690056/CatNinja.zip)
nvm  i compressed it

**Comment by n0samu** [comment]
This game needs `flash.utils.describeType`, which is not implemented yet.

**Comment by urmotha** [comment]
is there any other emulator that i can use to play it?

**Comment by n0samu** [comment]
You can use the Adobe Flash projector: http://web.archive.org/web/20220401020702/https://www.adobe.com/support/flashplayer/debug_downloads.html

**Comment by urmotha** [comment]
ill try it out

**Comment by urmotha** [comment]
thank you so much. i know it sounds stupid but I have played this game since I was a kid and to finally be able to play it again is so nice. thank you

**Comment by n0samu** [comment]
Glad to help! 😃

**Comment by urmotha** [comment]
I appreciate it
