### ISSUE TITLE
Glean doesn't see Kongregate

### ISSUE THREAD

**Issue by AxoCat** [ruffle-rs/ruffle#9479]
### Describe the bug

Glean (https://www.kongregate.com/games/okaybmd/glean) doesn't see that it's being played on Kongregate and refuses to launch.

### Expected behavior

I was playing on kongregate, it should have launched normally.

### Affected platform

Self-hosted version

### Operating system

Linux

### Browser

Mozilla Firefox Version 109.0.1 (64-bit)

**Comment by n0samu** [comment]
This is not a bug. Kongregate changed their site so that it loads SWFs from a randomized domain such as `game149123.konggames.com`. Most Kongregate games check whether they're running via Kongregate's old subdomain, `chat.kongregate.com`. These games no longer work on Kongregate.

**Comment by AxoCat** [comment]
how to fix it?
