### ISSUE TITLE
Unable to render different colours in Frontline Defense

### ISSUE THREAD

**Issue by brickblock369** [ruffle-rs/ruffle#9490]
### Describe the bug
[Link to game](https://www.kongregate.com/games/kazama_bee/frontline-defense-first-assault)
![Screenshot 2023-02-09 145748](https://user-images.githubusercontent.com/59150779/217958059-c9e51e7f-8492-427e-bb42-c714b5b8dcc6.png)
Turrets are supposed to have different colours, but they don't.

### Expected behavior

First column: The second row (Shotgun Turret) needs to be coloured blue, the fourth row (Sniper Tower) needs to be orange.
Second column: The second row (Heat Ray Tower) and fourth row (Power Amplifier) both need to be orange.
Third column: The second row (Ice Tower) needs to be cyan.

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Google Chrome 109.0.5414.121

**Comment by n0samu** [comment]
The tower sprites use ColorMatrixFilter to change the color, which is unimplemented in Ruffle.

**Comment by Lord-McSweeney** [comment]
Fixed by #11702.
