### ISSUE TITLE
Vectorpark Ball width error

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#9492]
### Describe the bug

![image](https://user-images.githubusercontent.com/151014/217969950-cf85e27c-ed0b-4340-b65c-d8512a6105d9.png)

Swf default is one pixel wide, somehow it works fine in abode flash but not in ruffle.

### Expected behavior

See right part of picture

### Affected platform

Desktop app

### Operating system

xfce mint 21.1

### Additional information
(https://github.com/ruffle-rs/ruffle/files/10702672/Ball.swf.zip)

**Comment by n0samu** [comment]
Hi, please provide a link or attachment containing the SWF file

**Comment by rredford** [comment]
> Hi, please provide a link or attachment containing the SWF file

Ya forgot the file lol
[Ball.swf.zip](https://github.com/ruffle-rs/ruffle/files/10702672/Ball.swf.zip)

**Comment by n0samu** [comment]
This happens because the Ruffle desktop app (and Web Demo) letterboxes Flash content by default. This is the right choice for most movies, but this particular SWF relies on Flash Player's default behavior of showing content outside the stage area. To address this, I've added a `--letterbox` option to the Ruffle desktop app in #9497. You'll be able to run `ruffle --letterbox=off` to make this SWF appear correctly.

**Comment by rredford** [comment]
Note in adobe this is initial appearance for ball 
![image](https://user-images.githubusercontent.com/151014/218004358-812cc64b-0161-43fe-a90d-ff5594de1615.png)

So I guess it has minimum window size or something

**Comment by n0samu** [comment]
Here's how it looks with my PR (on Windows 10):
![image](https://user-images.githubusercontent.com/71368227/218004603-e465394d-1a08-4eb0-8064-62872c00ff5e.png)

**Comment by rredford** [comment]
Odd. On xfce mint it shows as literally one pixel wide. I have to move mouse till it changes to resize in order to set width to be wider than that

**Comment by rredford** [comment]
YUP, it is metacity thing. I changed to xfwm4, and border weirdness is gone, but window size still doesnt match adobe flash. Here it is 
![image](https://user-images.githubusercontent.com/151014/218005977-89f6412e-0631-49f6-9fec-1481ed73e232.png)

**Comment by n0samu** [comment]
Setting a minimum window size for Ruffle would be a separate (very easy) task, see #9346
