### ISSUE TITLE
東方言霊祭 display bug

### ISSUE THREAD

**Issue by zjk261** [ruffle-rs/ruffle#9494]
### Describe the bug

https://user-images.githubusercontent.com/98996990/217969597-e6685577-4686-4784-8d4d-e0a44e0958a7.mp4

[東方言霊祭.zip](https://github.com/ruffle-rs/ruffle/files/10702670/default.zip)

lines on title screen and characters' face
kanji doesn't display
letters below moves when inputting

### Expected behavior

https://user-images.githubusercontent.com/98996990/217969606-63943688-1a59-4fd2-a82a-b862bcefcf1c.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

title screen and characters' face were normal before nightly build 2023-01-26
nightly 2023-01-25:

https://user-images.githubusercontent.com/98996990/217969778-db51bab2-10a4-45cb-8bbe-ac1f6fec07b7.mp4

**Comment by zjk261** [comment]
the world's hardest game series have the same error
ruffle
![r2](https://user-images.githubusercontent.com/98996990/217976805-1ac74b15-7ba4-4e96-bc81-775e907d4b93.jpg)
![r3](https://user-images.githubusercontent.com/98996990/217976809-6e2c8422-e4ad-429b-9616-45827afc47f1.jpg)
![r32](https://user-images.githubusercontent.com/98996990/217976813-b10e3f3b-bb48-40de-94d7-c46242ebf9df.jpg)
flashplayer
![f2](https://user-images.githubusercontent.com/98996990/217976862-02f5bb7d-a834-4a9a-be3e-87fd6b1910ac.jpg)
![f3](https://user-images.githubusercontent.com/98996990/217976865-1a12eeea-8b34-4620-a57c-a7e9904b27da.jpg)
![f32](https://user-images.githubusercontent.com/98996990/217976866-bc9bf3c7-e13c-4d0f-a22d-7923a973bee5.jpg)

**Comment by rredford** [comment]
I wonder if its same bug as my reported one on bubble tank 1 or 2. Some graphics not being removed.

**Comment by Lord-McSweeney** [comment]
Yes, the lines flying everywhere are another instance of the lyon bug. lyon already fixed the bug; an update to lyon will fix the bug. The text bug is unrelated.
