### ISSUE TITLE
Neo Circuit is not playable

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9508]
### Describe the bug

[Neo Circuit](http://www.notdoppler.com/neocircuit.php) works fine until you actually get into the gameplay, at which point everything becomes more or less unresponsive.
![image](https://user-images.githubusercontent.com/71368227/218219906-8e52ccea-ed12-490e-b76e-7992ddaa62ae.png)

When the gameplay is supposed to begin, this error is displayed:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x2299d2a2d10 }) to handler FunctionObject(FunctionObject { ptr: 0x2299cfbcb30 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(\"flash.events\")), name: Some(\"TouchEvent\"), params: [], flags: (empty) }")`

And after that, whenever you click the screen this error is repeated many times:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: ::draw)`

### Expected behavior

After the intro text is over (or dismissed), gameplay should begin.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Seems like this game needs TouchEvent. I didn't know Flash games actually used that.

**Comment by adrian17** [comment]
![2023-02-11_13-41-27](https://user-images.githubusercontent.com/4729533/218258530-345aaed8-9578-489d-86db-d8f6e7f46c97.png)

Looks like they only used it if they detect being played on a mobile device, so we don't actually need to dispatch it, just having a class should be enough.
I imagine we'll also need `Capabilities.screenResolutionX` implemented/stubbed for this to fully load.

**Comment by n0samu** [comment]
With #9538, the errors have disappeared and the first level begins normally. But it's still impossible to actually play the level because the game doesn't seem to recognize when you hover over or click the blue CPU node.

**Comment by Lord-McSweeney** [comment]
There is a minor text issue on the scrolling text at the start of the game, and there are also performance issues, but the game is playable (you can drag from node to node).

**Comment by n0samu** [comment]
Fixed by #9695
