### ISSUE TITLE
Nyan Cat Fly: Missing rainbow text on the title screen

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9509]
### Describe the bug

Tested on Ruffle Nightly 2023-02-11
Nyan Cat Fly! SWF used: [569268_nyancatfly.zip](https://github.com/ruffle-rs/ruffle/files/10712540/569268_nyancatfly.zip)

This is what the game looks like in the Ruffle Demo.
![Nyan Cat Fly - Demo 1](https://user-images.githubusercontent.com/36887711/218237219-55b1c555-b1d7-4dcc-b7f8-344b2d9a8200.png)
![Nyan Cat Fly - Demo 2](https://user-images.githubusercontent.com/36887711/218237222-5f14334d-48f2-4baa-902c-efaafe7d802b.png)

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.
![Nyan Cat Fly - Flashpoint 1](https://user-images.githubusercontent.com/36887711/218237245-fbe8b669-f55a-4144-b7b9-018ac6bdb493.png)
![Nyan Cat Fly - Flashpoint 2](https://user-images.githubusercontent.com/36887711/218237246-d79d58f0-7952-4864-b605-0c5a926f33fd.png)

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

### Additional information

Surprisingly, the rainbow text when you get a new top score doesn't disappear. The look of the text is slightly off, but it still shows like normal.

Ruffle Demo:
![Nyan Cat Fly - Demo 3](https://user-images.githubusercontent.com/36887711/218237455-0a267a62-b3a6-473e-a671-acdacd46a2ca.png)

Flashpoint:
![Nyan Cat Fly - Flashpoint 3](https://user-images.githubusercontent.com/36887711/218237469-58740f3a-8085-4056-a159-fd7edfbe54a0.png)

**Comment by n0samu** [comment]
The rainbow text sprite (sprite 428) uses ColorMatrixFilter and clipDepth, both of which are unimplemented in Ruffle. Despite that, it's a bit surprising that nothing at all shows up though.

**Comment by n0samu** [comment]
Fixed by #10514
