### ISSUE TITLE
avm1: Super Chick Sisters no longer works

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#9522]
### Describe the bug

- Run / Open https://uploads.ungrounded.net/396000/396372_superChickSisters.swf.
- Click "Enter code", type "gopam" and click "ok".
- Notice the screen is almost completely gray.

![new](https://user-images.githubusercontent.com/14274782/218279938-f97f364c-35e6-4b54-adbb-449c1e7277d4.png)

The issue was introduced in [nightly-2023-02-07](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-02-07). Bisection says that 755425ebfaa8f9bca381411309a157fe80fbbfd6 (#8873) is the first bad commit.

### Expected behavior

In nightly-2023-02-06 and older releases:
![old](https://user-images.githubusercontent.com/14274782/218279965-7af77559-d8fb-4bb0-bac2-0ae22d492666.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

Web builds are also affected.

**Comment by p0008874** [comment]
That also include new super chick sisters.

**Comment by Toad06** [comment]
The game doesn't seem to use any unload handlers at all, which is not something I expected.

The negative depth check the `pending_removal` function might not be sufficient (changing this function so it always return false prevents the issue from happening).

https://github.com/ruffle-rs/ruffle/blob/be2d5faa6f4798b7169d83e54171e2ac90407e37/core/src/display_object.rs#L1105-L1107

**Comment by waspennator** [comment]
Still an issue as of the latest nightly, also happens whether you start a new game or type in "gopam", only difference is skipping the intro cutscene before the first level.
