### ISSUE TITLE
[N: The Way of the Ninja] Fatal Error: Stage must always have a root movie

### ISSUE THREAD

**Issue by TheGentleChainsaw** [ruffle-rs/ruffle#9523]
SWF file can be obtained by downloading the macOS .zip file from https://www.thewayoftheninja.org/n.html and extracting `Nv2-Mac.app/Contents/Resources/movie.swf`.

# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:610:9
Error stack:
```
966/W/n.wbg.__wbg_new_f9bb493369a83c12@https://ruffle.rs/demo/966.index.js:1:5400
std::sync::once::Once::call_once::{{closure}}::h3a9cf7405ac8602d@:wasm-function[1904]:0x487c5a
std::sys_common::once::generic::Once::call::h6b012ac601cc39bf@:wasm-function[1842]:0x477a40
core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b5f0905e39c576d@:wasm-function[7167]:0x76d87e
std::panicking::rust_panic_with_hook::hbafe3e603d331223@:wasm-function[5085]:0x6c99ed
core::panicking::panic_fmt::h1d17fc068f528130@:wasm-function[7483]:0x77c7aa
core::option::expect_failed::hde6894209e142acf@:wasm-function[8669]:0x7a7252
ruffle_core::display_object::stage::Stage::root_clip::h27ae964ed6512e4b@:wasm-function[5075]:0x6c87b3
ruffle_web::Ruffle::tick::hda6807de9017f322@:wasm-function[661]:0x20bc49
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h926390cba430ed23@:wasm-function[9114]:0x7b85d5
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h67918aaec4766029@:wasm-function[8044]:0x78b0ba
S@https://ruffle.rs/demo/966.index.js:1:2513
f@https://ruffle.rs/demo/966.index.js:1:2243

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://ruffle.rs/demo/

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-11
Channel: nightly
Built: 2023-02-11T00:19:06.082Z
Commit: a2cd3ee06edcb889e8adc70a221eabb80ad342e5
Is extension: false

# Metadata
width: 792
height: 600
frameRate: 60
numFrames: 2
swfVersion: 14
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 1471114

**Comment by n0samu** [comment]
Same issue as #9219

**Comment by Lord-McSweeney** [comment]
SWF flashes some frames before erroring: `TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: flash.events:IEventDispatcher::hasEventListener)`.

**Comment by Kippykip** [comment]
Strange, older versions run fine. I wonder why Nv2.swf has this issue
[n flash games.zip](https://github.com/ruffle-rs/ruffle/files/11858003/n.flash.games.zip)
