### ISSUE TITLE
But RoboPolice are...: Invisible buildings

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9549]
### Describe the bug

https://www.newgrounds.com/portal/view/598843?emulate=flash

The buildings you need to jump around on are entirely invisible on ruffle, making the game impossible to play.

Running this on the ruffle web demo, I see this pop up in the log as soon as I press play, so maybe it uses this to show the buildings?

Encountered stub: AVM2 flash.display.Graphics.beginBitmapFill()

![Robopolice Ruffle](https://user-images.githubusercontent.com/78768499/218359020-1a7987c6-0a8b-4a31-b252-905fba0bf414.png)

### Expected behavior

![Robopolice Flash](https://user-images.githubusercontent.com/78768499/218359031-a30fd4b6-c29c-445a-b731-e1fec3209844.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by n0samu** [comment]
This happens because `beginBitmapFill()` is unimplemented:
`WARN ruffle_core::stub: Encountered stub: AVM2 flash.display.Graphics.beginBitmapFill()`

**Comment by waspennator** [comment]
The buildings seem to show up now making this game actually playable now, but for some reason they don't have glowing windows.

![Run Ruffle](https://user-images.githubusercontent.com/78768499/225782650-16ba5e98-327e-4276-87ba-2e8809e21ee5.png)

**Comment by Lord-McSweeney** [comment]
Fixed by #10630.
