### ISSUE TITLE
Velocity Wings: White Screen bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9550]
### Describe the bug

https://www.newgrounds.com/portal/view/635264?emulate=flash

Game seems to get stuck on a white screen on ruffle. Running it through the web demo I see these errors in the log.

Unknown tag code: 72

Got AVM2 error AvmError(Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0xc5e500 }))) when attempting to assign symbol class boot_45ea

The latter error is repeated for multiple different assets of the SWF.

### Expected behavior

Game should start up and be playable.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Progressed by #9537 and #9536.

**Comment by waspennator** [comment]
Retested again and the game now seems to get to the title screen, however it now seems to freeze when I click play and tosses this up in the log.

Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x128dc50 }) to handler FunctionObject(FunctionObject { ptr: 0xc5ff18 }) : RustError("Cannot call null or undefined method ::child of class XML")

**Comment by evilpie** [comment]
Seems to be playable with #10004 fixed.

**Comment by waspennator** [comment]
Can confirm on my end too, closing since its merged into latest nightly.
