### ISSUE TITLE
Samantha Wins: Broken on Web

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9552]
### Describe the bug

https://www.newgrounds.com/portal/view/648089?emulate=flash

Game works fine on desktop and I remembered this game used to work on web before the NG api stuff started getting supported, but testing it now on NG, the ruffle web demo, and another site rehosting this game (y8), it gets stuck on the preloader never finishing up.

Bisecting back through the builds on web, it seems like the last version this game worked on web wise was ruffle build 2023-02-11, the next 2 builds onwards just get stuck tossing this up in the logs on web.

Error dispatching event EventObject(EventObject { type: "commandComplete", class: com.newgrounds::APIEvent, ptr: 0x75d82c8 }) to handler FunctionObject(FunctionObject { ptr: 0x75ca6c8 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(\"\")), name: Some(\"unescape\"), params: [], flags: (empty) }")

### Expected behavior

The preloader shouldn't be getting stuck trying to load the game and should work, like on desktop or on web builds before 2023-02-12

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by n0samu** [comment]
This happens because `unescape` is unimplemented in Ruffle.

**Comment by waspennator** [comment]
Seems to work as of the latest nightly.
