### ISSUE TITLE
Button Cut: Unable to cut the in-game buttons

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9555]
### Describe the bug

Tested on Ruffle Nightly 2023-02-13
Button Cut SWF used: [button-cut.zip](https://github.com/ruffle-rs/ruffle/files/10722084/button-cut.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/218455698-ec0e27a8-6745-4568-8aa0-621200d57cbc.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/218455895-d7376e4b-a74f-409a-aa73-bfad431b6e9d.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
Seems like this was fixed by #9659
