### ISSUE TITLE
Lettermania: Player stuck on standing animation

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9556]
### Describe the bug

Tested on Ruffle Nightly 2023-02-13
Lettermania SWF used: [ltrman.zip](https://github.com/ruffle-rs/ruffle/files/10722275/ltrman.zip)

This is what the game looks like in the Ruffle Demo. The character can move perfectly fine, but the character does not change its movement animation.

https://user-images.githubusercontent.com/36887711/218460819-137adc45-76d7-41ec-a3c6-8f5008138006.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/218461083-b3bff4df-8930-4f33-bedf-24c130a88643.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
I'm seeing many instances of this warning:
`WARN run_frame: ruffle_core::avm1::globals::movie_clip: MovieClip.swapDepths: Invalid target`

**Comment by n0samu** [comment]
This is fixed by #9447! 🎉
