### ISSUE TITLE
HitBox (Kong version): Freeze after completing level

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9573]
### Describe the bug

In the [Kongregate version of HitBox](https://www.kongregate.com/games/gameshot/hitbox), the game freezes after completing a level. This only happens when the game is run directly from Kongregate. The problem seems to be caused by Kongregate's online API SWF (and not by its local "shadow" API SWF). To reproduce the problem with the Ruffle extension, you can open this URL: `https://chat.kongregate.com/gamez/0026/3025/live/hitBox_kong_730x550.swf?kongregate_api_path=https%3A%2F%2Fchat.kongregate.com%2Fflash%2FAPI_AS3_d43c4b859e74432475c1627346078677.swf`

This error is repeated in the console:
`ERROR core/src/avm2/activation.rs:930 TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: ::submit)`

### Expected behavior

It should be possible to continue the game after beating a level.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 109

### Additional information

It's possible to reproduce the same problem in Flash Player by giving the game an incorrect API URL, for example:
`https://chat.kongregate.com/gamez/0026/3025/live/hitBox_kong_730x550.swf?kongregate_api_path=https%3A%2F%2Fchat.kongregate.com%2Fflash%2Finvalid.swf`

I also noticed that on the Kongregate page, Ruffle is loading the wrong URL for the API SWF:
`https://game263025.konggames.com/games/gameshot/hitbox/frame/7fe8db98-d738-48df-bdc4-f531068023ac/https%3A%2F%2Fchat.kongregate.com%2Fflash%2FAPI_AS3_d43c4b859e74432475c1627346078677.swf`
I have not been able to figure out why the game loads the wrong URL when run from the Kongregate page. But I found that the game loads the correct URL when run directly from the SWF URL provided in the "describe the bug" section above.

Even when the game successfully loads the API SWF, in Ruffle the problem still occurs.

**Comment by n0samu** [comment]
Now the problem only occurs on the Kongregate game page (https://www.kongregate.com/games/gameshot/hitbox), not on the extension page or in the desktop app. That means it only occurs when the Kongregate API SWF fails to load. And it fails to load on the Kongregate game page because Ruffle tries to load it via the wrong URL, for some reason. (See the "Additional Information" section above.)

**Comment by n0samu** [comment]
The problem occurs because Kongregate is passing URL-encoded `swfobject_flash_vars` directly to Ruffle's `parameters` variable, when Ruffle takes non-URL-encoded variables. This is a problem with Kongregate's setup, not with Ruffle.

**Comment by danielhjacobs** [comment]
According to m0rkeulv on Discord:

> i pulled up the game page from  wayback machine 2011
> https://web.archive.org/web/20110329200506/http://www.kongregate.com/games/m0rkeulv/castle-wars-2
> and they still have URL encoded paths, so i guess its how ruffle handles these that is the issue.
> (flash vars from 2011)
> ```js
> var swfobject_flash_vars = {
>     "kongregate": "true",
>     "kongregate_username": encodeURIComponent(active_user.username()),
>     "kongregate_user_id": encodeURIComponent(active_user.id()),
>     "kongregate_game_id": "82970",
>     "kongregate_game_version": "1282328184",
>     "kongregate_host": "http%3A%2F%2Fwww.kongregate.com",
>     "kongregate_game_url": "http%3A%2F%2Fwww.kongregate.com%2Fgames%2Fm0rkeulv%2Fcastle-wars-2",
>     "kongregate_api_host": "http%3A%2F%2Fapi.kongregate.com",
>     "kongregate_game_auth_token": encodeURIComponent(active_user.gameAuthToken()),
>     "kongregate_stamp": encodeURIComponent(active_user.gameAuthToken()),
>     "api_path": "http%3A%2F%2Fchat.kongregate.com%2Fflash%2FAPI_AS3_46ebaf5ef297ce57605ca0a769f70b7d.swf",
>     "game_url": "http%3A%2F%2Fwww.kongregate.com%2Fgames%2Fm0rkeulv%2Fcastle-wars-2",
>     "kongregate_api_path": "http%3A%2F%2Fchat.kongregate.com%2Fflash%2FAPI_AS3_46ebaf5ef297ce57605ca0a769f70b7d.swf",
>     "kongregate_channel_id": encodeURIComponent(channel_id)
>  };
>  ```
>  so to me it looks like Ruffle is processing  these in a different way than how  the flash player  did it
