### ISSUE TITLE
Accurate Slapshot: Unclickable buttons

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9577]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/accurateslapshot.swf

In [Accurate Slapshot](http://www.notdoppler.com/accurateslapshot.php), various buttons are unclickable.
- After completing a level, the Main Menu, Replay, and Next Level buttons are clickable. But if you complete another level after that, the buttons will be unclickable this time.
- If you click the X button in the top-right corner of the gameplay screen, it will take you back to the level select screen, where all of the buttons will be unclickable.
![image](https://user-images.githubusercontent.com/71368227/218918084-32d295ae-f84b-4d99-b087-088e7efeff06.png)

### Expected behavior

The buttons on the level completion and level selection screens should always be clickable.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by rredford** [comment]
It worked for me, then on third level next buttons or really all buttons didn't work
