### ISSUE TITLE
Garfield Comic Creator: Panel bug

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9589]
### Describe the bug

https://archive.org/details/comiccreator_swf
For some reason, when you finish editing a panel, it shows up as a yellow tinted block for some reason. Choose either layout comic you want to make, edit the panel (Add stuff, don't add stuff, whatever), then as soon as you hit done, the bug should be instantly noticable.

![Garfield Ruffle](https://user-images.githubusercontent.com/78768499/219252951-d9c91a8d-cbe2-4e85-9b24-beee357610d1.png)

### Expected behavior

Editing a panel should show a preview of your edited panel and not an yellow square block.

![Garfield Flash](https://user-images.githubusercontent.com/78768499/219253020-6c46e200-5916-41b6-8e91-a72f31a76ace.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by n0samu** [comment]
There is also a freeze after clicking the Print button that we should investigate.

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/9604
