### ISSUE TITLE
Viricide: Pressing "New Game" will not start the opening dialogue

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9593]
### Describe the bug

Tested on Ruffle Nightly 2023-02-15
Viricide SWF used: [breach_rpg.zip](https://github.com/ruffle-rs/ruffle/files/10756023/breach_rpg.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/219362777-aece9c13-a74a-457f-a265-1c955522d5da.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/219368411-efc87dfa-26b1-4dfb-8e93-c19a659c66d3.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
These warnings are shown:
`WARN run_frame: ruffle_core::display_object::movie_clip: Movie clip 0: Duplicated frame label`
`WARN ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys`

Then this error is repeated over and over:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x26997a1cea0 }) to handler FunctionObject(FunctionObject { ptr: 0x26996d21d60 }) : RustError("ArgumentError: Child not a valid display object")`

**Comment by Lord-McSweeney** [comment]
Those errors are no longer shown, but this warning is: `Encountered stub: AVM2 flash.media.Sound.bytesLoaded getter`. The game hangs and does not load after pressing "new game"- the warning might be the reason for that.

**Comment by n0samu** [comment]
I'm still getting the warning about weak keys, so that's another possible reason.
