### ISSUE TITLE
Blur and Bloom effects missing in Portal the Flash Version

### ISSUE THREAD

**Issue by ProfessorFortress** [ruffle-rs/ruffle#9602]
### Describe the bug

Missing Blur and Bloom effects in Portal the Flash Version, see attached image for comparison.

![Screenshot 2023-02-17 103639](https://user-images.githubusercontent.com/125615515/219512149-b251b3e8-745e-465b-9773-296d23e4f4a7.png)

### Expected behavior

I expected the effects to be there.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by waspennator** [comment]
Should be fixed by #11878
