### ISSUE TITLE
Fullscreen related error in web console when exiting fullscreen with Escape

### ISSUE THREAD

**Issue by EmK530** [ruffle-rs/ruffle#9615]
### Describe the bug

Start up any game, right click the window and click "Enter fullscreen"
When in fullscreen, exiting with the escape button throws an error in console although it seems to have no effect at all and you can continue playing completely fine, even enter fullscreen again and cause the error all over again with the escape button.

### Expected behavior

Exiting fullscreen by using the escape button throws an error in the console that seems to have no effect on the behavior of Ruffle.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Brave 1.48.164 (Chromium 110.0.5481.100)

### Additional information

![image](https://user-images.githubusercontent.com/50961259/219761376-ae172659-1f62-4e5f-855a-75af97066a6d.png)

**Comment by danielhjacobs** [comment]
This was actually caused when you other bug (#5698) was fixed, as I mentioned in https://github.com/ruffle-rs/ruffle/pull/5714#issuecomment-978165996

**Comment by Toad06** [comment]
https://github.com/ruffle-rs/ruffle/blob/1065662e845651bba173236b4a76b74d2881ce56/web/packages/core/src/ruffle-player.ts#L841-L867

As a small fix, I suppose we could replace the line 860 with this?
`if (this.fullscreenEnabled && isFull !== this.isFullscreen) {`
