### ISSUE TITLE
Faithfighter not showing the initial menu

### ISSUE THREAD

**Issue by hugmyndakassi** [ruffle-rs/ruffle#9617]
### Describe the bug

https://www.molleindustria.org/en/faith-fighter/ contains the SWF file for the game of the same name. For good measure, here's the zipped up SWF: [faithfighter-swf.zip](https://github.com/ruffle-rs/ruffle/files/10771890/faithfighter-swf.zip)

Now when attempting to play it in Ruffle, the main menu after the selection (normal vs. censored mode) and the splash screen doesn't show up.

This is how it looks in Ruffle when loading it from https://ruffle.rs/demo/ ...

![Faithfighter via Ruffle](https://user-images.githubusercontent.com/79632072/219800525-9e22c7e8-fc7b-4124-9a11-5be20b8ce801.png)

Please note, it's nevertheless playable in principle if you use some of the keys like cursors and the space bar (initially 1 player mode would be selected anyway).

### Expected behavior

This is how it should look without any interaction after the splash screen disappears:

![Faithfighter via Lutris](https://user-images.githubusercontent.com/79632072/219800326-af5246e9-3928-48ec-b74d-e4a3579b8c63.png)

(Except that "1 player" is selected by default. This is from the `.exe` bundled version run using Lutris.)

### Affected platform

Online demo

### Operating system

Ubuntu 20.04.4 

### Browser

109.0.1 (64-bit)

**Comment by Lord-McSweeney** [comment]
In the console: `WARN RemoveSprite: Source is not a display object`

**Comment by relrelb** [comment]
Fixed as of latest nightly (likely thanks to #10514).
