### ISSUE TITLE
Link on the website to addons.mozilla.org is dead

### ISSUE THREAD

**Issue by assarbad** [ruffle-rs/ruffle#9618]
The link https://addons.mozilla.org/firefox/addon/ruffle_rs shown on your website ...

![image](https://user-images.githubusercontent.com/3238620/219802350-a5317eac-5e88-4bc1-aa55-6589f46260d7.png)

... is a dead link.

**Comment by ActionWavele** [comment]
this is a duplicate issue

**Comment by danielhjacobs** [comment]
See #8799

**Comment by n0samu** [comment]
Closing in favor of #9054

**Comment by assarbad** [comment]
Sorry, should have searched first.
