### ISSUE TITLE
BNKR: Pressing "Main Menu" while in-game will prevent you from interacting with anything on the title screen

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9624]
### Describe the bug

Tested on Ruffle Nightly 2023-02-18
BNKR SWF used: [bnkr.zip](https://github.com/ruffle-rs/ruffle/files/10773848/bnkr.zip)

This is what the game looks like in the Ruffle Demo. The game seems to be working fine, although I only played it briefly.

https://user-images.githubusercontent.com/36887711/219854923-e506e657-f88d-48cb-b995-6a1b6b8514ea.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/219854928-f9638d0f-cd4f-4a61-b55b-17ef11be2231.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
This problem seems to be fixed now. Please leave a comment if anything is still broken and I can reopen the issue.
