### ISSUE TITLE
Amuse Park: Unable to interact with almost all of the attractions while in-game

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9635]
### Describe the bug

Tested on Ruffle Nightly 2023-02-19
Amuse Park SWF used: [amusepark.zip](https://github.com/ruffle-rs/ruffle/files/10776309/amusepark.zip)

This is what the game looks like in the Ruffle Demo. The only attraction I can interact with is the clean-up robot. Any button that does not relate to the attractions works perfectly fine.

https://user-images.githubusercontent.com/36887711/219933496-5e37faf0-517e-4426-ab10-b87dcb87e529.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/219933475-f99b93cf-924f-4dfb-9e27-6519c5603c91.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
The error is:
`ERROR ruffle_core::avm2::activation: ReferenceError: Error #1069: Property core.mvc:IModelContainer::0 not found on Array and there is no default value.`
