### ISSUE TITLE
Write in the Death Note: Pressing the Return key will not do the animation that is supposed to happen

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9636]
### Describe the bug

Tested on Ruffle Nightly 2023-02-19
Write in the Death Note SWF used: [Write in the Death Note.zip](https://github.com/ruffle-rs/ruffle/files/10776445/Write.in.the.Death.Note.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/219937762-2b651a51-eaaa-4944-9efe-d5570bf7cb2e.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/219937823-31b7da67-81a6-4e6d-b040-8bada66d4030.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
Strangely, on the Ruffle Web Demo and on NG's selfhosted build, nothing at all his happening for me when I press the Enter key.

Meanwhile it seems to be working fine for me on the Ruffle desktop app:

https://user-images.githubusercontent.com/71368227/220225137-a7102e23-6d68-4a9b-ab82-0893cdc992cb.mp4

**Comment by Dinnerbone** [comment]
The relevant code here is:
```actionscript
onClipEvent(keyDown){
    if (Key.getAscii() == 13) {
        // .....
    }
}
```

May be similar to #13929 and 13849
