### ISSUE TITLE
Epos: Getting to the save menu will cause it to go into an infinite loop

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9649]
### Describe the bug

Tested on Ruffle Nightly 2023-02-20
Epos SWF used: [540610_epos202c.zip](https://github.com/ruffle-rs/ruffle/files/10779866/540610_epos202c.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/220016071-25c8851a-e020-48f3-9151-ac36b438a57a.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/220016172-1cbb9146-ef86-4dc7-ab65-fc35a92b6e7c.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
The error is: 
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::globals::flash::display::movieclip: Attempted to add frame scripts to non-MovieClip this!`

**Comment by n0samu** [comment]
This was fixed in nightly 2023-05-28, probably by #11084.
