### ISSUE TITLE
Error on https://game160170.konggames.com/games/HeroInteractive/bubble-tanks-tower-defense-2/frame/1875f82a-75e4-4a2e-af38-0dbd325e2677/

### ISSUE THREAD

**Issue by Dioman222243** [ruffle-rs/ruffle#9662]
# Error Info
Error name: Error
Error message: panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    copy of Y 649..1199 would end up overrunning the bounds of the Destination texture of Y size 550

', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu/src/backend/direct.rs:2973:5

# Player Info
Allows script access: true

# Page Info
Page URL: https://game160170.konggames.com/games/HeroInteractive/bubble-tanks-tower-defense-2/frame/1875f82a-75e4-4a2e-af38-0dbd325e2677/?kongregate_host=www.kongregate.com
SWF URL: https://game160170.konggames.com/gamez/0016/0170/live/Bubble_Tanks_TD_2.swf?kongregate_game_version=1357860869

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Platform: Win32
Has touch support: true

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-20
Channel: nightly
Built: 2023-02-20T00:19:50.499Z
Commit: f7a12698b9a5dbfc39529ab5e4abd75880579b99
Is extension: false

# Metadata
width: 650
height: 550
frameRate: 50
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 4102995

**Comment by n0samu** [comment]
Fixed by #10373
