### ISSUE TITLE
AVM2: Bytearray behaviour is not the same as Flash

### ISSUE THREAD

**Issue by AllinolCP** [ruffle-rs/ruffle#9668]
### Describe the bug

Bytearray `readUTFBytes` should terminate after a NULL is detected
in ruffle it traces:
2023-02-22T02:55:51.714413Z  INFO run_frame:run_all_phases_avm2: avm_trace: abcdef
2023-02-22T02:55:51.717318Z  
INFO run_frame:run_all_phases_avm2: avm_trace: 8 ( Bytearray position )
[bytearray.zip](https://github.com/ruffle-rs/ruffle/files/10799635/bytearray.zip)

Uses SWF I attached above

### Expected behavior

However in Flash it traces
abc
8 ( Bytearray position )

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by AllinolCP** [comment]
Additional information after I modified the code a bit to show the length of the text read
![image](https://user-images.githubusercontent.com/56921534/220511173-f059d983-c4e1-455a-8d26-d3e5a933e64f.png)

Ruffle:
![image](https://user-images.githubusercontent.com/56921534/220511243-f261de3b-f6cc-41f1-b2a3-cb2fe8c92e0d.png)
Flash
![image](https://user-images.githubusercontent.com/56921534/220511264-f598bedf-ee34-4786-a107-c775bad896d8.png)

**Comment by divinity76** [comment]
funfact, fully valid UTF-8 can contain null bytes (called `U+0000`), perhaps readUTFBytes uses [MUTF-8](https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8) ?
