### ISSUE TITLE
Powerpool: After starting, the game will get stuck loading the first level

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9670]
### Describe the bug

Tested on Ruffle Nightly 2023-02-22
Powerpool SWF used: [powerpool.zip](https://github.com/ruffle-rs/ruffle/files/10800449/powerpool.zip)

This is what the game looks like in the Ruffle Demo. I waited for a few minutes to see if something would happen, but nothing changed.

https://user-images.githubusercontent.com/36887711/220534431-a6fd8b10-6b2f-4a85-8fc5-aeccd94d7053.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/220534481-4917e0e1-f79f-4ca4-a130-d431221dfd8e.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
The error is:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: RustError("Cannot call null or undefined method ::decode of class flash.net::URLVariables")`
