### ISSUE TITLE
Level music fails to play in "Uncle Sam"

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#9676]
Steps to reproduce:
- [Download the game here.](https://github.com/ruffle-rs/ruffle/files/10807774/unclesam.zip)
- Click the green button ("Easy" mode).
- Press the play button to skip the animation.
- When the level starts, notice that no music is being played.

This is a regression that affects both of the web and desktop builds, but seems to imply different commits.

---

_Desktop (Windows 10):_
- Broken since [nightly-2022-09-07](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2022-09-07).
- Related commits: https://github.com/ruffle-rs/ruffle/compare/nightly-2022-09-06...nightly-2022-09-07

_Web (Firefox 110.0):_
- Broken since [nightly-2022-07-31](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2022-07-31).
- Related commits: https://github.com/ruffle-rs/ruffle/compare/nightly-2022-07-29...nightly-2022-07-31
- Releases from 2022-07-31 to 2023-01-06 used to log the following warnings multiple times in the console:
```
invalid mpeg audio header
skipping junk at 357 bytes

**Comment by n0samu** [comment]
The regression occurred on web when #4273 was merged. That PR switched to decoding audio with Symphonia on web. At that point, Ruffle desktop still used minimp3, not Symphonia. #7894 switched from minimp3 to Symphonia on desktop, causing the same regression to occur there.

The error messages you mentioned are coming from Symphonia. I think they disappeared as a result of #9026. Symphonia is still encountering the same errors, they just aren't making it into Ruffle's log anymore.

I've opened https://github.com/pdeljanov/Symphonia/issues/190 - hopefully they can take a look at this.

**Comment by n0samu** [comment]
This issue has been resolved in Symphonia, so it should hopefully be fixed in Ruffle once we upgrade. 👍

**Comment by Toad06** [comment]
Nice! Also, thank you for reporting this bug to Symphonia. 😉

**Comment by Toad06** [comment]
The fix made it to Ruffle in #11376. Thanks again, @n0samu. 👍
