### ISSUE TITLE
Questionaut: Text appears incorrectly

### ISSUE THREAD

**Issue by wojtekpolska** [ruffle-rs/ruffle#9690]
### Describe the bug

![image](https://user-images.githubusercontent.com/58272360/220869603-fa226f03-a4be-4bcc-a3f7-84e7d7ed4969.png)
Text is incorrectly formatted, spills out of the speech bubble, selecting answers is impossible. 

reproduce by simply playing trough the start of the game

game link: https://amanita-design.net/questionaut/ 

### Expected behavior

![image](https://user-images.githubusercontent.com/58272360/220869837-23523567-a1ec-40be-b326-788519f8b8d9.png)
Text appears as in the image above, player can choose answer by clicking 

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Opera 95.0.4635.37 EDIT: error also appears on Google Chrome

**Comment by n0samu** [comment]
Hi, I am unable to access the link provided. Can you double-check it?

**Comment by n0samu** [comment]
I was able to access the URL [via Wayback Machine](https://web.archive.org/web/20221117212946/https://amanita-design.net/questionaut/).

The text is displayed via an HTML text field and the code that displays the text is in the `zobrazOtazku` function of each of the secondary SWFs (numbers.swf, reading_writing.swf, etc). A similar issue with HTML text field sizing occurs with the FAQ question list in #7340.

**Comment by wojtekpolska** [comment]
> Hi, I am unable to access the link provided. Can you double-check it?

weird, im able to access this link normally without wayback machine. 
maybe try from here: https://amanita-design.net/games/questionaut.html ,scroll to the bottom, and click "Online (Flash)" under "Play Full Game" 

tho as you said its also on wayback machine (tho im really dumbfounded, the link seems to be live for me) 

the bug you linked indeed seems similar, im wondering what could cause this tho


Honestly, i think the sizing directions are just reversed? like the text is as long as it should be wide, and as wide as it should be long? maybe thats the issue (it cant rly be seen in the 7340 bug report, as the size of the box the FAQ is set in is smaller, but in Questionaut its more visible)

**Comment by n0samu** [comment]
Actually the sizing problem occurs because the game uses the TextField `textWidth` property, which is unimplemented (see #280). And even if that were implemented, choosing an answer still would not work because `asfunction` links in HTML text are unimplemented (see #4253).

**Comment by wojtekpolska** [comment]
oh, well thanks for explaining. 

this addon is really great, but this kind of stuff is the reason i still keep an old firefox release with original flash plugin on my pc

**Comment by n0samu** [comment]
We generally leave issues open until all mentioned problems are resolved.

**Comment by n0samu** [comment]
With #12812, asfunction links should work properly, so now we just need someone to solve the text width issue.

**Comment by Lord-McSweeney** [comment]
Fixed by #13923. Though there does seem to be another minor issue: pressing the mouse over any option should result in the question-asker replying with a response, explaining why the option is correct or incorrect. In Ruffle, this response disappears right after the mouse is released (so very quickly if you click on the option instead of holding the option down).
