### ISSUE TITLE
Crystal Crunch Story: Black Screen Issue

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9693]
### Describe the bug

[Crystal Crunch Story.zip](https://github.com/ruffle-rs/ruffle/files/10815111/Crystal.Crunch.Story.zip)

Game seems to have started working recently as of now, but as soon as you start the game and get past the first cutscene, you are greeted with a black screen as the music plays.

![Crystal Crunch Ruffle](https://user-images.githubusercontent.com/78768499/220949764-5ab6783a-93b2-4f41-bb44-37a4eb2ffbbe.png)

### Expected behavior

It should display this screen after the first cutscene.

![Crystal Crunch Flash](https://user-images.githubusercontent.com/78768499/220949797-236cf796-c300-4527-891a-9616deb347cc.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by waspennator** [comment]
Still broken as of the latest nightly and nothing helpful is showing up in the logs save for this, unless this is what's breaking it.

Encountered stub: AVM2 flash.media.Sound constructor with arguments

**Comment by waspennator** [comment]
Checking as of the latest nightly, my only guess is that it uses a combination of glow and dropshadow filters to render the playing field, looking at the logs while running the game.

**Comment by waspennator** [comment]
![Crystal](https://github.com/ruffle-rs/ruffle/assets/78768499/609d4b59-0949-4199-8790-51da6561a7cb)

#11878 seems to make this swf almost perfectly playable, the only issue that i'm noticing is that the blocks dropping aren't making noises, though other noises still seem to play properly.

**Comment by n0samu** [comment]
@waspennator can you open a new issue for the sound problem with this game?
