### ISSUE TITLE
Web Archive Math Playground Troy's Toys

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#9696]
### Describe the bug

When I load the flash file it says: "Troy's Toys is not authorized to be on this website. This game has been stolen. For fun and educational math games created by teachers, please visit www.MathPlayground.com" This is on the web archive for MathPlayground.com. This game no longer exists on MathPlayground.com. The url is https://web.archive.org/web/20200818091747im_/https://www.mathplayground.com/mathgames/SL_ToyStore_secure.swf

### Expected behavior

It should begin the game.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Microsoft Edge 110.0.1587.50

### Additional information

# Player Info
Allows script access: false
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 1920, height: 913, depth_or_array_layers: 1 }

# Page Info
Page URL: chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/player.html?url=https%3A%2F%2Fweb.archive.org%2Fweb%2F20200818091747im_%2Fhttps%3A%2F%2Fwww.mathplayground.com%2Fmathgames%2FSL_ToyStore_secure.swf
SWF URL: https://web.archive.org/web/20200818091747im_/https://www.mathplayground.com/mathgames/SL_ToyStore_secure.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-23
Channel: nightly
Built: 2023-02-23T00:19:44.956Z
Commit: e17b154d47e2f20055770292f4c0a12c15e04efd
Is extension: true

# Metadata
width: 730
height: 500
frameRate: 12
numFrames: 4
swfVersion: 8
backgroundColor: #CCCCFF
isActionScript3: false
uncompressedLength: 149959

**Comment by Lord-McSweeney** [comment]
Ruffle cannot fix this issue- the file is sitelocking itself. Running the SWF with `--spoof-url https://www.mathplayground.com/mathgames/SL_ToyStore_secure.swf` from the desktop Ruffle allows it to run normally, without any issues.

**Comment by CoolDino1** [comment]
would it be possible to create a feature on the browser extension to do what you did?

**Comment by Lord-McSweeney** [comment]
There is a feature on the self-hosted version (not the extension, unfortunately), but it is limited to spoofed URLs on different paths (not on different sites) to prevent breaking past sitelocks. For example, if a file is on `https://web.archive.org/hello.swf`, the URL can be spoofed to `https://web.archive.org/hello-files/hello.swf` or `https://web.archive.org/spoof.swf` but NOT `https://gamehost.com/hello-game.swf`, `https://gamehost.com/hello.swf` or `https://web.gamehost.com/hello.swf`.
