### ISSUE TITLE
パラ2: Bright Game Over and missing Kanji

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9698]
### Describe the bug

[Para2.zip](https://github.com/ruffle-rs/ruffle/files/10820434/Para2.zip)

Found this game when I was searching up Ruffle on twitter and it seems to work alright, but it has 2 minor issues. Start the game by pressing the number key 5 and use 4 and 6 to steer left and right.

1: The Symbol beneath your character isn't correct. It ends up using a copyright symbol for some reason.
![Symbol Ruffle](https://user-images.githubusercontent.com/78768499/221085766-e61929be-da5b-4166-8132-ae31422a1bb3.png)

2: When you get a game over (Miss the moving platform on the bottom), the background gets brighter than expected.
![Game Over Ruffle](https://user-images.githubusercontent.com/78768499/221086051-68e10c52-4753-4acb-94ce-75eed7d55d14.png)

### Expected behavior

1: The Symbol beneath your character should look like this.
![Symbol Flash](https://user-images.githubusercontent.com/78768499/221086108-c5c73174-1b40-49fd-8e5c-e8e810bf20f2.png)

2: The background should be this bright when you get a game over.
![Game Over Flash](https://user-images.githubusercontent.com/78768499/221086706-315e13fe-e9a8-485f-b7fc-c70b213051d5.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by n0samu** [comment]
The copyright symbol issue is another instance of #8390. The character is stored in the EditText field as hex `84 A9`, which is supposed to be interpreted as the SHIFT-JIS character `┼` and rendered using a device font. Ruffle interprets these bytes with codepage Windows-1252, so the text comes out as `„©`.

**Comment by n0samu** [comment]
The Game Over screen issue is a regression caused by #6704. Since that PR did not touch the Canvas backend, the game still appears correctly there. It's particularly strange that the problem happens on desktop, considering that wmode is supposed to be a web-only feature.

**Comment by waspennator** [comment]
![Game over Ruffle fixed](https://user-images.githubusercontent.com/78768499/221328096-884029a7-5733-48d5-a997-c34b05c43eca.png)
Game over screen on ruffle is no longer overly bright, but the symbol beneath the character is still wrong.

**Comment by n0samu** [comment]
We're tracking the symbol/text issue in #8390, thanks for reporting!
