### ISSUE TITLE
kuschnick.com: Images are not displayed

### ISSUE THREAD

**Issue by artnFe** [ruffle-rs/ruffle#9702]
### Describe the bug

![hubi](https://user-images.githubusercontent.com/8668100/187341482-8f52d81d-df1c-40a2-ba70-6eee30dee592.jpg)

# Bug Report
Images (marked red in the screenshot) are not displayed.

# Bug Report
Images (marked red in the screenshot) are not displayed.

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: PUSH_CONSTANTS | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
Available features: TEXTURE_COMPRESSION_BC | CLEAR_TEXTURE | MULTIVIEW
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 2560, height: 1297, depth_or_array_layers: 1 }
Player type: Object
SWF URL: gallery.swf
Param movie: gallery.swf
Param bgcolor: #000000
Param wmode: transparent
Param allowscriptaccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://kuschnick.com/
SWF URL: https://kuschnick.com/gallery.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-02-24
Channel: nightly
Built: 2023-02-24T00:23:51.606Z
Commit: 5a7cd92bfed181aecb90f8bb631b8bbf5506d86f
Is extension: true

# Metadata
width: 800
height: 600
frameRate: 40
numFrames: 37
swfVersion: 6
backgroundColor: #000000
isActionScript3: false
uncompressedLength: 150229

### Expected behavior

Images should be displayed

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Chrome

**Comment by n0samu** [comment]
Hello, why did you close your original issue and create a new one?

**Comment by artnFe** [comment]
It was so old and I thought nobody would look at it.

**Comment by n0samu** [comment]
I think the root cause of this issue is #6552.

**Comment by n0samu** [comment]
Also, I did look at your original issue, but back then I did not have the skills to diagnose it 🙂

**Comment by artnFe** [comment]
I suppose this might be the problem, because I also use the method getBytesTotal() several times in the flash movie.
Wonder why this bug still exists, if so many people have a problem with it. Hope someone finds a solution one day ;-)

**Comment by artnFe** [comment]
@Toad06
@Dinnerbone 
Thank you very much. Works perfectly.
