### ISSUE TITLE
Issue on Neopets Typing Terror game (https://www.neopets.com/games/game.phtml?game_id=574&size=regular&quality=high&play=true)

### ISSUE THREAD

**Issue by ostentia** [ruffle-rs/ruffle#9714]
### Describe the bug

During the first round, I randomly lose 3 lives at once and immediately die every time, even when I've been 100% accurate and should have been allowed to continue.

### Expected behavior

I should only lose a life when I miss a word.

### Affected platform

Desktop app

### Operating system

macOS

### Browser

Safari

**Comment by n0samu** [comment]
Fixed by #9447
