### ISSUE TITLE
Fault Line: Visual Issues

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9735]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/faultline.swf

In [Fault Line](http://www.notdoppler.com/faultline.php), after the folding the platforms, parts of them become invisible:
![image](https://user-images.githubusercontent.com/71368227/221389599-403d3b85-600c-4def-87ca-774e2ba991f8.png)

This is due to `beginBitmapFill` being unimplemented:
`WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.display.Graphics.beginBitmapFill()`

Also, as pointed out in https://github.com/ruffle-rs/ruffle/issues/3794#issuecomment-1445229591, text is flickering in some places, for example:
![ruffle_flicker](https://user-images.githubusercontent.com/71368227/221390105-fdd569d2-af4b-4859-a768-f34431a4456c.gif)
(Note: it flickers much faster than it appears in the GIF)

### Expected behavior

Here is what the folded platform is supposed to look like:
![image](https://user-images.githubusercontent.com/71368227/221390154-d1c11d9d-eb6a-465c-b155-2442877f3d02.png)

Also, the text should not flicker.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Lord-McSweeney** [comment]
Currently, it looks like there's been an error with the `beginBitmapFill` implementation:
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=http%3A%2F%2Fi notdoppler com%2Ffiles%2Ffaultline swf](https://user-images.githubusercontent.com/84632019/225806972-74cc2de8-8863-4a31-8568-ca507b9b2909.png)
(too zoomed in)
Also, parts of the level occasionally flicker and disappear before reappearing.

**Comment by Lord-McSweeney** [comment]
Folding was fixed by #10630.

**Comment by n0samu** [comment]
Fixed by #10734
