### ISSUE TITLE
Reimagine :The Game: Cannot restart levels

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9746]
### Describe the bug

https://www.newgrounds.com/portal/view/569281?emulate=flash
Whenever you beat a level, you end up on a screen like this which is normal. The main issue is that if you try and press the "replay level" button on the top right, nothing happens except for the log spitting out this. The replay level button only breaks at the end of a level on Ruffle, not during the pause screen.

![Reimagine](https://user-images.githubusercontent.com/78768499/221415074-902bdadc-0164-42d1-a446-e32c57196922.png)

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x24e9130 }) to handler FunctionObject(FunctionObject { ptr: 0xa8e910 }) : RustError("TypeError: null is not an Object")

Also sometimes whenever I beat the first level quickly I see some other error messages in the logs about cookies or something, usually when I beat the first level with one of those achievement notifications on the bottom left I believe., but these don't seem to be game breaking issues.

[www.newgrounds.com-1677419532104.log](https://github.com/ruffle-rs/ruffle/files/10833844/www.newgrounds.com-1677419532104.log)

### Expected behavior

The replay level button shouldn't be breaking at the end of each level.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
This is being caused by the function `gamesys::GameController/endGame()`: 
```
      public function endGame() : void
      {
         trace("Why No End 2.1");
         this.cutscene.end();
         this.cutPaused = false;
         this.game.visible = this.HUD.visible = true;
         trace("Why No End 2.2");
         this.playSfx.end();
         trace("Why No End 2.3");
         with(MovieClip(root))
         {
            SoundMixer.stopAll();
            sfx.clear();
            loop.clear();
         }
         trace("Why No End 2.4");
      }
```
Specifically, `MovieClip(root)` is null, which throws an error.

**Comment by waspennator** [comment]
Retested on NG and as noted by another user on the Ruffle Discord, issue no longer seems to be occuring as of latest nightly.
