### ISSUE TITLE
Decision: Medieval does not start in Ruffle or any website at all

### ISSUE THREAD

**Issue by crisluce** [ruffle-rs/ruffle#9759]
### Describe the bug

The game Decision: Medieval does not start because it needs actionscript 3
![image](https://user-images.githubusercontent.com/126494055/221603109-b9e3f03d-9692-4107-ab07-b4f7947e2dfd.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/126494055/221603634-fa5b1857-fb6c-4007-b30c-3f04006766f5.png)

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

Any Browser, any website, the game doesn't start

### Additional information

All the Decision games work except for Decision: Medieval

**Comment by Dinnerbone** [comment]
After #9761 it's now blocked on encodeURI (#9730)

**Comment by Lord-McSweeney** [comment]
Error message now: `TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: http://adobe.com/AS3/2006/builtin::split)`.

**Comment by Lord-McSweeney** [comment]
The game is playable now, with performance and minor graphical issues.

**Comment by crisluce** [comment]
> The game is playable now, with performance and minor graphical issues.

May I ask where I can play it? It's either stuck in a 100% loading screen or a black screen and I got to page 3 of google visiting every flash game website and it's always the same result. I visited the kongregate link above but it's also black screen :(

**Comment by n0samu** [comment]
The game should work if accessed via this URL with the Chrome extension or desktop app:
http://chat.kongregate.com/gamez/0020/8372/live/medieval_v1_08_kong.swf

It may also work on the Kongregate website starting today, but I can't test it yet due to Kongregate's ongoing server/DNS issues.

**Comment by crisluce** [comment]
> The game should work if accessed via this URL with the Chrome extension or desktop app: http://chat.kongregate.com/gamez/0020/8372/live/medieval_v1_08_kong.swf
> 
> It may also work on the Kongregate website starting today, but I can't test it yet due to Kongregate's ongoing server/DNS issues.

IT WORKS!! IT *BLEEPING* WORKS!! Thank you so much person on the internet! ^_^

**Comment by n0samu** [comment]
You're welcome 😄
