### ISSUE TITLE
The multi asset version of World 1 Remix does not load properly.

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#9770]
### Describe the bug

While the [single swf version avaliable in speedrun.com](https://github.com/ruffle-rs/ruffle/files/10842845/FPA.1.REMIX.zip) loads, the [multiasset version originally in kongregate](https://cdn.discordapp.com/attachments/1014415019963846666/1079061104069705858/FPA_World_1_Remix_-_Kongregate_Release.7z) does not.

### Expected behavior

The game would load sucessfully.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
I think this has the same cause as #8010.
