### ISSUE TITLE
Troyis Chess: Couldn't parse SWF

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9785]
### Describe the bug

Link to SWF: https://www8.agame.com/mirror/flash/t/troyis_chess.swf

Loading the SWF file for Troyis Chess fails with this error:
`ERROR run_frame: ruffle_core::avm1::runtime: Couldn't parse SWF: Error parsing AVM1 action ConstantPool: Not enough data for string`
`ERROR run_frame: ruffle_core::avm1::runtime: No more actions will be executed in this movie.`

The game displays but is not interactive.

Note that the game also fails to load in the latest Adobe Flash Player. But it works in Flash Player 7, 8 and 9 from here: https://archive.org/details/MacromediaFlashProjectors.7z

### Expected behavior

The game should load as it does in Flash Player 7, 8 and 9.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

JPEXS Flash Decompiler is unable to disassemble the code in this movie.

I found this from the logs in #9047

**Comment by Dinnerbone** [comment]
Even FFDEC can't read the scripts 🤔

**Comment by n0samu** [comment]
The log from #9047 shows a few other instances of this error, but all of those are immediately following an unknown opcode with a huge amount of bogus data, so I'm not sure if those are a different problem. They similarly fail to load in latest Flash Player, though. An example is Tiny Battle: https://www8.agame.com/mirror/flash/t/tiny_battle.swf

**Comment by Lord-McSweeney** [comment]
For future reference, the reason JPEXS cannot read the scripts was because the ConstantPool entries were invalid strings, which we now ignore.
