### ISSUE TITLE
avm1: sound does not stop

### ISSUE THREAD

**Issue by AllinolCP** [ruffle-rs/ruffle#9795]
### Describe the bug

the bug occurs when you start the game (i believe its #[2914](https://github.com/ruffle-rs/ruffle/issues/2914)) and there's another bug when pressing space in game 

[game.zip](https://github.com/ruffle-rs/ruffle/files/10860661/game.zip)

(Video)
https://user-images.githubusercontent.com/56921534/222135251-11cabb66-7650-47c7-a07f-f4cb38536050.mp4

### Expected behavior

audio should stop after the game loads and the sound should also stop after releasing space and the arm retracts

(Video)
https://user-images.githubusercontent.com/56921534/222135351-995a8f74-6616-445e-8aa8-c4000b475ca4.mp4

### Affected platform

Desktop app

### Operating system

Windows 11

### Additional information

to run the game simply run bootstrap.swf

**Comment by Infinity48Games** [comment]
I made a minimal repro case of this.
[ruffle audio bug test.zip](https://github.com/ruffle-rs/ruffle/files/10891730/ruffle.audio.bug.test.zip)
This uses `loadMovieNum` to load in 'other.swf' and `unloadMovieNum` to unload it. In the adobe player, the sound stops when the movie is unloaded but in Ruffle, the sound continues.

**Comment by AllinolCP** [comment]
there is actually two bugs in this issue, one is the `loadMovieNum` and the other is related to coordinates(?)

**Comment by Infinity48Games** [comment]
I decompiled the game and found out how SFX are handled (frame 4 of 'subgame.swf'):
```actionscript
function addSFX(clip, loops, volume, d)
{
   clearInterval(sfxTimer);
   if(d != undefined)
   {
      sfxTimer = setInterval(this,"addSFX",d,clip,loops,volume);
   }
   else
   {
      if(volume == undefined)
      {
         volume = 100;
      }
      this[clip + "Sound"] = new Sound(this.createEmptyMovieClip(clip + "Sfx",getNextHighestDepth()));
      this[clip + "Sound"].setVolume(volume);
      this[clip + "Sound"].attachSound(clip);
      this[clip + "Sound"].start(0,loops);
   }
}
function stopSFX(clip)
{
   this[clip + "Sound"].stop();
}
```
I am not totally sure what the problem is but I'll copy these functions into a repro just to try and test.

**Comment by AllinolCP** [comment]
@Infinity48Games I have managed to make a minimum reproduction of the issue
[sound bug.zip](https://github.com/ruffle-rs/ruffle/files/10941805/sound.bug.zip)
it is related with the coordinates

**Comment by AllinolCP** [comment]
> it never seems to destroy the MovieClips it creates

This is due to the fact that this game is actually a minigame when you finished the minigame the whole game gets unloaded.

**Comment by AllinolCP** [comment]
Issue 1 seems to be fixed now! one more to go
