### ISSUE TITLE
[extension] SWF file isn’t displayed at all 

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#98]
@Herschel,

congratulations for your Ruffle project!

Using Firefox 66.0.4 with `ruffle_extension_2019-09-20_c2eb96e`, I’m afraid I’m not able to play anything at the classic https://randomfoo.net/oscon/2002/lessig/free.html.

Direct link to Flash file reads https://randomfoo.net/oscon/2002/lessig/free_culture.swf.

Am I doing something wrong? Or how am I expected to browse the SWF file?

Many thanks for your help.

**Comment by Herschel** [comment]
Hi @ousia, did you follow the instructions at https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle to enable the extension? It currently has to be enabled as a Temporary Add-On in Firefox. This will change in the near future when it is properly packaged as a full extension.

You can also run the SWF in the web player manually at http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo

**Comment by ousia** [comment]
@Herschel, I followed the instructions.

If that works for you, I’m obviously doing something wrong.

**Comment by ousia** [comment]
Sorry, I didn’t want to close the issue.

**Comment by ousia** [comment]
@Herschel, do you have any estimated date to release the extension as full version for Firefox?

**Comment by Herschel** [comment]
Hi @ousia, Firefox requires that all extensions be signed by Mozilla. I will try to take some time in the coming week or two to set this process up on our CI to get proper automated packages of the extension for Firefox.

**Comment by ousia** [comment]
Hi @Herschel, I’d love to test _Ruffle_ on mobile platforms.

**Comment by ehea617** [comment]
I believe that I'm getting this issue as well. I have 001a931afe49e1c268d26e9c54b8a4c0a699160b installed as a temporary extension and am unable to load swf files in browser that are able to load just fine in the standalone player. When attempting to load the link in the OP, the developer console outputs these errors: https://gist.github.com/ehea617/d0e4d3c1ee2ffde9bd490a03bd653323. If I download the swf file and load it into the standalone player, it loads fine.

**Comment by ousia** [comment]
@ehea617, many thanks for your report.

My error messages are different from yours. But I’m afraid I cannot get the message from 

From https://www.free-culture.tk, I get the following error in the developer debugger:

```
Serious error encountered when polyfilling native Flash elements: TypeError: e.attributes.classid is undefined www.free-culture.tk:3:11923
    j https://www.free-culture.tk/:3
    content https://www.free-culture.tk/:3
    e https://www.free-culture.tk/:3
    polyfill https://www.free-culture.tk/:3
    init https://www.free-culture.tk/:3
```

The file https://www.free-culture.tk/lfc-loader.swf is rendered perfectly fine by the desktop program in _Fedora Linux_.

Just in case it helps.

**Comment by ehea617** [comment]
@ousia Ah I see. I'm talking about the https://randomfoo.net/oscon/2002/lessig/free.html link. Trying to load https://www.free-culture.tk/ I get the same error as you.

**Comment by ousia** [comment]
@ehea617, many thanks for your report.

@Herschel, can you reproduce these errors?

**Comment by ousia** [comment]
@Herschel,

since we have issues with the web demo in Firefox for Android and I use Firefox on my laptop, I cheched the web extension in Chrome. I’m afraid I didn’t get it working.

Browsing https://www.free-culture.tk/, there is no difference if the extension is installed or not (extension works in incognito mode).

![extension-lfc](https://user-images.githubusercontent.com/203767/74591503-ecc51e80-5018-11ea-8045-f01e171f62b6.png)


With https://randomfoo.net/oscon/2002/lessig/free.html, playing gets stuck after clicking on the presentation (very similar to what @Toad06 describes in #385).

@ehea617, did you use Firefox to check both sites?

**Comment by ehea617** [comment]
@ousia Yes I used Firefox on both.

**Comment by ousia** [comment]
Fixed with newer version of the extension.

@ehea617, I hope you are experiencing the same.
