### ISSUE TITLE
Arcuz: Visual regression with skill cooldown timers

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9805]
### Describe the bug

Link to SWF: https://cache.armorgames.com/files/games/arcuz-5003.swf

@Bimbelimbim pointed out a minor visual regression in [Arcuz](https://armorgames.com/play/5003/arcuz) caused by #9447. Here are the steps to reproduce it:
1. Run the game in the Ruffle desktop app: `ruffle https://cache.armorgames.com/files/games/arcuz-5003.swf`
2. After the game has created a save file (Arcuz.sol) somewhere within your user profile, close Ruffle and replace the save file with this one: [Arcuz_save.zip](https://github.com/ruffle-rs/ruffle/files/10867115/Arcuz_save.zip)
3. Go back into the game; you should now be in chapter 5. Run down to the bottom of the village and enter Plain Arcuz.
4. Click the Skill button and equip Holy Light.
5. Use Holy Light by pressing I or L.
6. Equip a different skill with a shorter cooldown on top of the inactive Holy Light skill. For example, equip Hurricane.
7. Notice that it's still showing the cooldown overlay for Holy Light, instead of highlighting the new skill as active/usable.

Here is a video demonstrating this:

https://user-images.githubusercontent.com/71368227/222320324-d7df7a91-08b0-4e40-943e-3168865b3867.mp4

### Expected behavior

Here is how the cooldowns are supposed to appear (shown in an older Ruffle version):

https://user-images.githubusercontent.com/71368227/222320436-183370a7-bfa8-4210-9b7a-d6b3575e8c18.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

The skills also do not snap into place in their slots as expected, see https://github.com/ruffle-rs/ruffle/issues/3295#issuecomment-1451144664

**Comment by Bimbelimbim** [comment]
Needless to say that these glitched out displays are present with all skills. The cooldown display changes to the correct information of the newly equipped skill, after fully cycling through the cooldown of the first equipped skill.

**Comment by n0samu** [comment]
@Bimbelimbim reports on Discord that this is fixed now.
