### ISSUE TITLE
does not load files for the scene

### ISSUE THREAD

**Issue by geometry88** [ruffle-rs/ruffle#9820]
### Describe the bug

https://freestreet.dance/demo/

### Expected behavior

![image](https://user-images.githubusercontent.com/16748478/222587982-226a6e23-cfe5-4e95-909c-d66d44d003c0.png)

WARN core/src/display_object/movie_clip.rs:3809 DoAction tag in AVM2 movie

### Affected platform

Browser's extension

### Operating system

Windows 11

**Comment by Lord-McSweeney** [comment]
Closing in favor of #8310.
