### ISSUE TITLE
Diggy: Softlock after clicking Hall of Fame button

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9831]
### Describe the bug

Link to game: https://www.kongregate.com/games/Vogd/diggy
To reproduce the bug:
1. Play through the first day of the game. (Takes less than a minute)
2. Start a new day.
3. Click the Hall of Fame button at the top of the screen.
4. The game will be softlocked; none of the buttons will respond to clicks.

![image](https://user-images.githubusercontent.com/71368227/222704429-3ee37eba-9473-420a-b28e-c1687b9231bc.png)

### Expected behavior

It should be possible to switch between the tabs of the Hall of Fame screen by clicking them, and to dismiss the screen by clicking the Hall of Fame button again.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 110

**Comment by waspennator** [comment]
Can confirm issue is fixed by latest nightly.
