### ISSUE TITLE
Symphony: Unstable blur effect

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9832]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/symphony.swf

In [Symphony](http://www.notdoppler.com/symphony.php), the entire game screen is represented as a big BitmapData object, with the blur filter applied to particles, the edge of the "battery" objects, etc. In Flash Player, the blur effect is stable; the ring around an uncharged battery stays the same width, and particles fade away at the same rate that they appear. But in Ruffle, the fading happens much more slowly. Particle colors accumulate on the screen and the ring around a battery expands until it fills the whole battery. You can see this pretty easily if you just move the force field up in the first level and wait:
![image](https://user-images.githubusercontent.com/71368227/222747371-97b16406-0195-44a5-b40a-d2c3885302fb.png)

### Expected behavior

Here's what it looks like in Flash Player:
![image](https://user-images.githubusercontent.com/71368227/222747701-c96b21aa-11bf-4f1f-9241-11494cff3d42.png)

The blur effect is stable and the red color is not accumulating over time.

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This is likely the same problem as #9574.

Another thing to note is that the the force field object is not blurred like it's supposed to be. But I'm not sure if that's related.

**Comment by Sdssourcing** [comment]
#

**Comment by n0samu** [comment]
This looks different now, but still not good:
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/a7d56009-2a6f-4056-b0b9-e9f767d1cbb9)

**Comment by torokati44** [comment]
I think the keyword here is not that the blur should be "stable", rather, it should "decay" over time.
Since FP probably computes all of this with 24.8 fixed point numbers, and the result of computations always seems to be rounded down, repeatedly blurring an image slowly leaks its energy away, therefore fading to black here.

**Comment by torokati44** [comment]
Do you agree with the closure, @n0samu?

**Comment by n0samu** [comment]
Yes, thank you! 😀
