### ISSUE TITLE
Madness Accelerant ending scene but error

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#9835]
### Describe the bug

![Уеб заснемане_3-3-2023_195613_www newgrounds com](https://user-images.githubusercontent.com/80902993/222793231-180ab7fe-f234-4c5f-acfe-5ee3099be7d0.jpeg)
look there is problem

### Expected behavior

Nothing but look this Describe the bug

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Microsoft Edge

### Additional information

i beat madness accelerant madness mode because it's fun but
when i clicked return to menu
i clicked it's error

**Comment by waspennator** [comment]
https://www.newgrounds.com/portal/view/512407
Providing game link for testing, but I can also confirm that this happens on my end as well on normal. Didn't see anything of note pop up in the log when clicking on "Return to menu", but it does seem like it's not properly transitioning from the end screen to the main menu. I can also click on it multiple times and it essentially just does the same thing.
[www.newgrounds.com-1677898315217.log](https://github.com/ruffle-rs/ruffle/files/10887327/www.newgrounds.com-1677898315217.log)

**Comment by deividbinev12** [comment]
yeah he is one point

**Comment by Sonikkustar** [comment]
Issue appears to be fixed now:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/189c0227-a597-409d-b3b2-98521bf5049a)

Game now uses **nightly-2023-12-17**.
