### ISSUE TITLE
Bookmarks feature From Linux Flashplayer on Ruffle

### ISSUE THREAD

**Issue by Zinc-Exclamation** [ruffle-rs/ruffle#9839]
Describe the feature
Provide a clear and concise description of your feature request. Why would this feature be useful? Does the feature involve the desktop build, the web build, or both?

The feature this is requesting is for the Ruffle UI on desktop (when it is added) to display the 'Bookmarks' tab similar to how the linux flash player ( and only the linux flash player??)  displays it.

bookmarks info is useful because of the QOL it provides. It would allow the best feature of the linux flash player to actually be utilized on all platforms (desktop).
it would be an improvement over current windows flash player, and mac, and of course, Ruffle.

linux
something like this
![sclb2](https://user-images.githubusercontent.com/109034847/222826869-9826f005-2778-4912-8191-2f939348df96.png)

it works like this: you play a game in flash player, then at any time, click bookmarks, then add.
it then shows up in the bookmarks menu along with the add button.

windows
![svfdbgfds](https://user-images.githubusercontent.com/109034847/222827916-871d290e-0150-4e27-95fd-625b92019b41.png)

this feature was never on windows, or mac, unfortunately
the only related feature is the 'recently opened' list, which is lame in comparison.
and unhelpful if a game you wanted quick access to was no longer recent.

This feature is described for DESKTOP

I hope to see this in the future, thank you for your time.

**Comment by sleepycatcoding** [comment]
This has been implemented in #15755.
