### ISSUE TITLE
Madness Accelerant: Incorrect menu button animations

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9844]
### Describe the bug

[512407_hank2009.zip](https://github.com/ruffle-rs/ruffle/files/10887386/512407_hank2009.zip)

While testing this game out on Ruffle, I noticed the button animations when you hover over some of the buttons on the main menu look kinda....... incorrect compared to how it should look on flash.

When hovering over the new game button:
![MA menu 1](https://user-images.githubusercontent.com/78768499/222873857-a9336d54-72c3-4378-8d53-2f970aff5027.png)

When hovering over one of the bottom buttons like the moar madness button:
![MA menu 2](https://user-images.githubusercontent.com/78768499/222873919-cfd99a69-f6ff-4c87-bd02-c5b7a2ad2d94.png)

### Expected behavior

![MA Menu 3](https://user-images.githubusercontent.com/78768499/222873987-cbd68657-38c6-423b-aaf4-9b8480fbf6a1.png)

The white static surrounding the button buttons when you hover over them shouldn't be brighter on ruffle.
![MA Menu 4](https://user-images.githubusercontent.com/78768499/222873999-057a665c-f1ab-4b8a-b3b8-d2da26b826df.png)

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by Sonikkustar** [comment]
Issue appears to be fixed now.

Hovering over New Game:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/039887df-50b3-4129-b0fe-9a4cd40affa7)

Hovering over Moar Madness:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/4b06ea7e-6f38-4d2b-acf3-0c7ee2f3eb1b)

Tested over at https://www.newgrounds.com/portal/view/512407 which now uses **nightly-2023-12-17**, though I'd assume the desktop version is likely the same way as this.
