### ISSUE TITLE
Planting a Tower in Bloons TD 4 Adds a Cool Green Circle (and no Tower)

### ISSUE THREAD

**Issue by dginovker** [ruffle-rs/ruffle#9851]
### Describe the bug

I planted this monkey and got a cool green circle instead

![image](https://user-images.githubusercontent.com/32943174/222925649-6c1e1534-4f7c-4a76-a0fb-fed8a1413f96.png)

Tested with two versions of BTD4:

* Regular: https://sites.google.com/site/swffiledump2/home/swf-file-dump-2/bloons%20tower%20defense%204%20%281.3%29.swf?attredirects=0&d=1
* Expansion: https://sites.google.com/site/swffiledump2/home/swf-file-dump-2/bloonstd4exp.swf?attredirects=0&d=1

### Expected behavior

Monkey gets planted

### Affected platform

Online demo

### Operating system

Linux

### Browser

Firefox

### Additional information

Ruffle's da best

**Comment by Aaron1011** [comment]
This should be fixed by https://github.com/ruffle-rs/ruffle/pull/9865
