### ISSUE TITLE
Error on https://game103834.konggames.com/games/ExploreWellcome/high-tea/frame/356be31f-2f09-4229-9271-679a2bfb6b3f/

### ISSUE THREAD

**Issue by GloriousT** [ruffle-rs/ruffle#9866]
# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:625:9
Error stack:
```
339/W/n.wbg.__wbg_new_15d3966e9981a196@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4beee3bfef84afa32e56.js:1:46442
std::sync::once::Once::call_once::{{closure}}::h97aad3534cecf95d@:wasm-function[2041]:0x4f0c8d
std::sys_common::once::generic::Once::call::h6b012ac601cc39bf@:wasm-function[1974]:0x4e173f
core::ops::function::FnOnce::call_once{{vtable.shim}}::h58f54bbbf27f6496@:wasm-function[7451]:0x7b2f53
std::panicking::rust_panic_with_hook::hbafe3e603d331223@:wasm-function[5250]:0x70a7f2
core::panicking::panic_fmt::h1d17fc068f528130@:wasm-function[7780]:0x7c21f5
core::option::expect_failed::hde6894209e142acf@:wasm-function[8994]:0x7ed7cc
ruffle_core::display_object::stage::Stage::root_clip::h5e5ab7688201684e@:wasm-function[5244]:0x709930
ruffle_web::Ruffle::tick::hf697cc8ddb70410e@:wasm-function[672]:0x2452cb
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h528aeb6e1d0ee818@:wasm-function[9462]:0x7ff93f
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h3b0444d648f463f1@:wasm-function[8354]:0x7d10ce
A@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4beee3bfef84afa32e56.js:1:2562
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.4beee3bfef84afa32e56.js:1:2240

```

# Player Info
Allows script access: true

# Page Info
Page URL: https://game103834.konggames.com/games/ExploreWellcome/high-tea/frame/356be31f-2f09-4229-9271-679a2bfb6b3f/?kongregate_host=www.kongregate.com
SWF URL: https://game103834.konggames.com/gamez/0010/3834/live/Main.swf?kongregate_game_version=1320245818

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-05
Channel: nightly
Built: 2023-03-05T00:24:08.325Z
Commit: 33064465b3311df870cbc20337d524bad47b5ee1
Is extension: false

# Metadata
width: 700
height: 500
frameRate: 30
numFrames: 2
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 8493160

**Comment by n0samu** [comment]
Seems to be working fine now!
