### ISSUE TITLE
Neopets: Korbats Lab

### ISSUE THREAD

**Issue by melaniejade** [ruffle-rs/ruffle#9869]
### Describe the bug

https://www.neopets.com/games/game.phtml?game_id=801

When you press the space bar to launch the ball it freezes just above the block.

### Expected behavior

It is supposed to go all the way up and start hitting the blocks.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome

### Additional information

I know other people have this issue on other systems and browsers. It is widely discussed and documented, Macs and Windows, Chrome and Opera and Firefox, etc. It is a game that can get players an avatar (big deal to players) so it is definitely missed way more than some of the other games that do not run perfectly.

**Comment by n0samu** [comment]
Thanks for letting us know! This was already reported in #8674 and #7674, so I'll close this issue.
