### ISSUE TITLE
Some areas render incorrectly in Nevermore 3

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9896]
### Describe the bug

In Nevermore 3 (SWF at https://cache.armorgames.com/files/games/nevermore-3-3391.swf), some areas render incorrectly:
![chrome-extension___donbcfbmhbcapadipfkeojnmajbakjdc_player html_url=https%3A%2F%2Fcache armorgames com%2Ffiles%2Fgames%2Fnevermore-3-3391 swf%3Fv%3D1373587521](https://user-images.githubusercontent.com/84632019/223322856-3b054909-b1ec-417f-b30c-977a5a60cfc8.png)

To get to the areas, travel to the right. The only trick in this case is being able to jump on top of rocks and trees.

### Expected behavior

The area renders green instead of transparent.

### Affected platform

Browser's extension

### Operating system

Linux

### Browser

Chrome 110

**Comment by SN902** [comment]
same issue #9892

**Comment by Lord-McSweeney** [comment]
Closing in favor of #9892.
