### ISSUE TITLE
Closure: Broken stage select & unable to start stage when pressing "Begin"

### ISSUE THREAD

**Issue by WyvernB** [ruffle-rs/ruffle#9900]
### Describe the bug

Tested on Ruffle Nightly 2023-03-07
Closure SWF used: [480006_closure202c.zip](https://github.com/ruffle-rs/ruffle/files/10906260/480006_closure202c.zip)

This is what the game looks like in the Ruffle Demo.

https://user-images.githubusercontent.com/36887711/223346081-853cb0b3-ad81-492a-97d6-512440f73030.mp4

### Expected behavior

This is what the game looks like when I launch it using Flashpoint.

https://user-images.githubusercontent.com/36887711/223346272-b308375a-dd52-4d2f-808a-ef02aa319fc8.mp4

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Chrome 110

**Comment by n0samu** [comment]
Here are some errors that may be relevant:
```
WARN run_frame:run_all_phases_avm2: ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"flash.display\"))), name: Some(\"Shader\"), params: [], flags: (empty) }")
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "commandComplete", class: com.newgrounds::APIEvent, ptr: 0x22b3092d240 }) to handler FunctionObject(FunctionObject { ptr: 0x22b25a46100 }) : RustError("Property does not exist: Multiname { ns: Single(Namespace(Namespace(\"\"))), name: Some(\"unescape\"), params: [], flags: (empty) }")
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: RustError("ArgumentError: null is not a valid frame label.")
ERROR ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: data)
ERROR run_frame:run_all_phases_avm2: ruffle_core::display_object::movie_clip: Error occured when running AVM2 frame script: RustError("ArgumentError: NaN is not a valid frame label.")
```

**Comment by n0samu** [comment]
Side note: I just noticed that this game is mentioned on the [project roadmap](https://github.com/ruffle-rs/ruffle/wiki/Roadmap) as a game that uses the Pixel Bender shader language. I guess implementing it will be an interesting task for the future.

**Comment by Aaron1011** [comment]
You can now enter the stage, but it doesn't render properly. This will be fixed by https://github.com/ruffle-rs/ruffle/pull/12238

**Comment by Aaron1011** [comment]
With https://github.com/ruffle-rs/ruffle/pull/12238, this is now playable:

![closure_working](https://github.com/ruffle-rs/ruffle/assets/1408859/ff5037c3-c178-4b11-b12a-03e68681de24)
