### ISSUE TITLE
Wooden Path 2: Hover popups don't disappear

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9948]
### Describe the bug

In [Wooden Path 2](https://www.kongregate.com/games/Remivision/wooden-path-2), the popup that appears when hovering over a level on the map does not disappear when entering the level.
![image](https://user-images.githubusercontent.com/71368227/224190697-fe5cfc5c-0d4f-4374-ad4c-a34e9b3628a9.png)
The popups build up over time and obstruct other buttons on the level map.
![image](https://user-images.githubusercontent.com/71368227/224190968-5136f53b-a718-4847-8aa9-db5305f57035.png)

### Expected behavior

When you click to enter a level, the popup should disappear.

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Firefox 110

**Comment by Robert9157** [comment]
I cannot reproduce with nightly 2023-03-10.

**Comment by n0samu** [comment]
You're right. By the time I finished reporting this issue, nightly 2023-03-10 had already been out for 2 minutes! 😛
