### ISSUE TITLE
web: What I often came across in the console: gotoandstop / play

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#995]
https://www.newgrounds.com/portal/view/467050?emulate=flash - Hobo Brawl

Don't know really what it causes but I got a feeling that when testing many games I came across the GoToAndStop and Play Console "notice". In this game which almost works okayish I can see that the guys I hit will change the clothes and animations mess around :)

Alos it's missing "Object method setVolume is not callable" - The mute-button is not working

**Comment by relrelb** [comment]
This seems to be fixed now.
