### ISSUE TITLE
Grey Matter: Cannot start game

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9950]
### Describe the bug

https://www.newgrounds.com/portal/view/467236?emulate=flash
Game seems to work up to the title screen, as soon as you try to start a new game by selecting normal and pressing start on the bottom right, the game randomly jumps back to the preloader and gets stuck at 45%.

Also the initials chosen during the preloader is set to null by default.

[www.newgrounds.com-1678421600150.log](https://github.com/ruffle-rs/ruffle/files/10938451/www.newgrounds.com-1678421600150.log)

### Expected behavior

The game should start normally and not randomly jump back to the preloader at 45% and the default initials should be "TAR"

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
Requires String-to-XML coercion, as well as `flash.net.sendToURL`.

**Comment by waspennator** [comment]
Grey Matter seems to be capable of getting in game now, should I keep this open for the string-to-XML coercion or close it since it's not jumping back to the preloader anymore?

**Comment by evilpie** [comment]
I think string-to-XML coercion should already work thanks to #10091. I don't see anything related to XML failing anymore.
