### ISSUE TITLE
lazer man - music reversing and looping issue

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#9952]
### Describe the bug

in this game, lazerman, I think all of the music is one big track, and the music is rewinded and fast forwarded depending on what you're doing (being on the menus, normal gameplay, rampage, etc) so when you complete a level, it will jump to the portion of the track that has the menu theme, and so on.
it seems that playing enough levels will make it reverse and fast forward incorrectly, causing the music to loop too early, and eventually making it sound like I've crashed my Wii console again, haha

(headphone warning!)

you can hear how the music tries to jump to the rampage portion  at the middle of the clip or so, but its looping that too early, and then jumps back to the main theme, which that loop had slowly been getting shorter and shorter, until it got stuck on one note, hence the lock-up like sound (at least, thats how I think its all happening)

https://user-images.githubusercontent.com/103858019/224254151-91c9a195-acb2-4f1f-afa2-fb1593a07a00.mp4

### Expected behavior

the music should not fail to work

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[lazermanMTgzNw==.zip](https://github.com/ruffle-rs/ruffle/files/10939734/lazermanMTgzNw.zip)

**Comment by n0samu** [comment]
I found a consistent way to reproduce the bug "from scratch" in about 1 minute and 30 seconds:

https://user-images.githubusercontent.com/71368227/224260771-e73e55f7-d906-4d8a-96ca-ecd4f7b51a34.mp4

It doesn't seem to matter how quickly you enter and leave, either (as long as you do it a fair number of times). I tried much faster menu-clicking and it took right around the same amount of time to get the bug.

**Comment by Kz-92** [comment]
that was fast, nice

**Comment by Herschel** [comment]
This game has some code which tries to restart paused sounds at their previous position, but this is incorrectly affecting the music causing it to start later and later. I believe the issue is `SoundChannel.position` is incorrectly returning the last played position after `SoundChannel.stop`, when it should return 0 because `position` had not been accessed before. `SoundChannel.position` should only update and cache on access in AVM2.
