### ISSUE TITLE
Easy Joe 4: ABC VerifyError

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9953]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/easyjoe4.swf

Running [Easy Joe 4](http://www.notdoppler.com/easyjoe4.php) in Ruffle just cycles rapidly through the frames and sounds without running any code. The first warning is:
`WARN run_frame: ruffle_core::display_object::movie_clip: Error loading ABC file: AvmError(Object(ErrorObject(ErrorObject { class: VerifyError, ptr: 0x20ee8426b00 })))`

After that, there are many warnings like this:
`WARN run_frame: ruffle_core::display_object::movie_clip: Got AVM2 error AvmError(Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0x20ee8426d10 }))) when attempting to assign symbol class easyjoe4_as3_fastgames_fla.Common_Object_09_2`

### Expected behavior

The game's code should run.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by rredford** [comment]
Strange. When I use controls to skip intro then companies, I can enter maps and all frame just keep looping within frame.

**Comment by Lord-McSweeney** [comment]
Fixed by #14908
