### ISSUE TITLE
Neon Rider: Cannot start game

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#9957]
### Describe the bug

Link to SWF: http://i.notdoppler.com/files/neonrider.swf

After clicking the Begin button in [Neon Rider](http://www.notdoppler.com/neonrider.php), the Armor Games intro animation plays. But after that, the game stays on a blue screen and the intro sound repeats over and over.

This error is displayed many times in the terminal:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: name)`

After the intro animation completes, this error appears:
`ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::activation: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: play)`

### Expected behavior

After the Armor Games intro animation plays, the level select screen should display.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by MartySVK** [comment]
Looks like now it is blocked on `Failed to parse XML: RustError(\"XML.toString(): Not yet implemented`

**Comment by evilpie** [comment]
With #10088 and #10091 we seem to get a bit further, but the menu still doesn't load.

**Comment by MartySVK** [comment]
unfortunately without error

**Comment by n0samu** [comment]
This has recently been fixed!
