### ISSUE TITLE
Super Soldier: Play button doesn't start game.

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#9966]
### Describe the bug

https://www.newgrounds.com/portal/view/284305/format/flash?emulate=flash

Clicking the PLAY button at the top of the Super Soldier (AS2) menu doesn't advance to the game, you remain stuck on the menu.

### Expected behavior

Clicking the PLAY button should start the game.

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Chrome version Version 110.0.5481.178

**Comment by adrian17** [comment]
Known as https://github.com/ruffle-rs/ruffle/issues/1108 :/

**Comment by n0samu** [comment]
Fixed by #10862
