### ISSUE TITLE
AS3 game does not load

### ISSUE THREAD

**Issue by jeppe9821** [ruffle-rs/ruffle#9971]
### Describe the bug

I'm trying to run Habbo.swf in Ruffle. But since Habbo.swf is an AS3 game, it's not fully supported yet (as expected). The game does not load and gets stuck at 25% loading

This is the error:
![image](https://user-images.githubusercontent.com/86717334/224390449-de91a3c0-f341-46ec-84bd-728938de80de.png)

Text form:
ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x2ebbb68 }) to handler FunctionObject(FunctionObject { ptr: 0x2eba3d0 }) : RustError("Cannot call null or undefined method child of class XML")
ruffle_web-wasm_extensions.js:673 ERROR core/src/avm2/activation.rs:940 AVM2 error: Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0x933a08 }))
ruffle_web-wasm_extensions.js:673 ERROR core/src/avm2/activation.rs:942 ReferenceError: Error #1069: Property flash.text::TextRenderer not found on global and there is no default value.
ruffle_web-wasm_extensions.js:673 ERROR core/src/display_object/movie_clip.rs:2112 Got AvmError(Object(ErrorObject(ErrorObject { class: ReferenceError, ptr: 0x933a08 }))) when constructing AVM2 side of movie clip of type Volter

### Expected behavior

The game should load

### Affected platform

Self-hosted version

### Operating system

Windows 10

### Browser

Chrome

### Additional information
[habbo.zip](https://github.com/ruffle-rs/ruffle/files/10944848/habbo.zip)

_No response_

**Comment by Lord-McSweeney** [comment]
It needs `XML.child`, `flash.text.TextRenderer`, and `flash.text.CSMSettings`. The latter two can be stubbed.

**Comment by Lord-McSweeney** [comment]
This has been progressed.
```
INFO ruffle_core::player: Loaded SWF version 9, resolution 960x540 @ 24 FPS
WARN ruffle_core::tag_utils: Unknown tag code: 255
WARN ruffle_core::tag_utils: Unknown tag code: 255
WARN ruffle_core::stub: Encountered stub: AVM2 flash.system.Capabilities.os getter
WARN ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys
ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x558921757e80 }) to handler FunctionObject(FunctionObject { ptr: 0x5589217f6ce0 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: children)
	at com.sulake.core.utils::_-0yp$/parseVariableToken()
	at com.sulake.core.utils::_-0yp$/parseVariableList()
	at com.sulake.habbo.notifications::HabboNotifications()
	at com.sulake.core.runtime::_-Zo/_-1f7()
	at HabboMain/_-tx()
	at HabboMain/_-0UU()
	at HabboMain/_-1Ha()
	at HabboMain/_-190()
	at flash.display::DisplayObjectContainer/flash::display::DisplayObjectContainer::addChild()
	at Habbo/_-31()
	at Habbo/_-0Q3()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.net.URLLoader.close()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.text.Font.registerFont()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.text.TextRenderer.setAdvancedAntiAliasingTable()
ERROR ruffle_core::loader: Error during movie loading of "http://localhost/c_images/hotel_view_images_hq/hotelview_default.png": FetchError("failed to connect to the server")
WARN ruffle_core::stub: Encountered stub: AVM2 flash.display.Loader.close()
WARN ruffle_core::stub: Encountered stub: AVM2 flash.display.Loader.unload()
WARN ruffle_core::player: AVM2 Context menu callbacks are not implemented
```

**Comment by Dinnerbone** [comment]
What's the status of this, is it still broken?

It appears to have the same behaviour as regular Flash Player, for me - both finish loading and then end up on a black screen. If there's more files or instructions needed to test this further, please provide them so we can continue looking into it.

**Comment by Dinnerbone** [comment]
Managed to play a bunch in desktop ruffle. Web needs someone to configure a proxy, but it seems playable to me - just visual issues.

Closing this for now - it works! Please open new issues for further things you find <3
