### ISSUE TITLE
BBC Newsround - Sorry you need flash to play this.

### ISSUE THREAD

**Issue by stuaxo** [ruffle-rs/ruffle#998]
In firefox, I tried the latest extension on this page
https://www.bbc.co.uk/newsround/19630083

When you hit the play button the page comes back with "Sorry you need flash to play this", I don't see any info in the console about ruffle or flash, so at a guess it is the flash detection that is breaking here, not ruffle itself.

**Comment by n0samu** [comment]
I don't think this is a problem with Ruffle. In any case, the site doesn't work even in a browser with Flash Player.
