### ISSUE TITLE
Sword and Souls not starting

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#9986]
### Describe the bug

![Уеб заснемане_11-3-2023_134730_www kongregate com](https://user-images.githubusercontent.com/80902993/224482566-8fc44daa-e92d-4347-a11c-10fbe81a5b67.jpeg)
this is not starting because it's multi files
flash player is only working with multi files

### Expected behavior

https://www.youtube.com/watch?v=05XbrcXqocc&ab_channel=GoGyGames
this is official flash player

### Affected platform

Desktop app

### Operating system

Windows 11

### Browser

Edge

### Additional information

https://www.kongregate.com/games/SoulGame/swords-and-souls

**Comment by Lord-McSweeney** [comment]
Needs `flash.globalization.CurrencyFormatter`.

**Comment by Lord-McSweeney** [comment]
Now I get these errors:
```
Got AVM2 error ReferenceError: Error #1065: Variable FontEstrangeloEdessa is not defined. when attempting to assign symbol class FontEstrangeloEdessa
Got AVM2 error ReferenceError: Error #1065: Variable FontFinger is not defined. when attempting to assign symbol class FontFinger
```
as well as a CORS error. The CORS error can be fixed by opening the SWF in a new tab.

**Comment by n0samu** [comment]
Closing this issue since it's fixed as much as it ever can be, really
