### ISSUE TITLE
ATV offroad thunder - regression with intro now looping

### ISSUE THREAD

**Issue by Kz-92** [ruffle-rs/ruffle#9994]
### Describe the bug

before, Ruffle skipped the end of the logo and its sounds, now the logo is played out, but the sounds loop __

https://user-images.githubusercontent.com/103858019/224505070-f8ba570a-c506-46ab-bab4-1098b08fc4de.mp4

### Expected behavior

 the intro should play out, then stop and go to the menu

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[ATV_Offroad_Thunder_agame.zip](https://github.com/ruffle-rs/ruffle/files/10949152/ATV_Offroad_Thunder_agame.zip)

**Comment by Lord-McSweeney** [comment]
Will be fixed by #9928.

**Comment by Toad06** [comment]
I confirm it's fixed. Closing.
