### ISSUE TITLE
Ruffle breaks XML formatting on Chrome

### ISSUE THREAD

**Issue by Lord-McSweeney** [ruffle-rs/ruffle#9997]
### Describe the bug

If you go to https://www.w3schools.com/xml/simple.xml with the extension enabled the text will be bunched up together, without any formatting: 
![www w3schools com_xml_simple xml](https://user-images.githubusercontent.com/84632019/224509609-eee92ac6-eec0-4a8e-972d-5bef2d9c580b.png)

### Expected behavior

![www w3schools com_xml_simple xml (1)](https://user-images.githubusercontent.com/84632019/224509641-3ce2aa73-96f9-4e50-9872-bc31a4103b55.png)

### Affected platform

Browser's extension

### Operating system

(irrelevant)

### Browser

Chrome

### Additional information

I fixed the problem by inserting
```
if (!(document instanceof HTMLDocument)) {
    return;
}
```
at the start of the concatenated module `load-ruffle.js` in both the `ruffle.js` and the `content.js` final builds, but I don't think TypeScript would like this very much.

**Comment by n0samu** [comment]
The strange thing is that the extension indicates that it is not even loading on the page:
![image](https://user-images.githubusercontent.com/71368227/224542151-e1891956-38e4-4c9c-831a-22e00d4dfff2.png)
And the problem occurs regardless of whether "Play Flash content in Ruffle" is enabled.
